### ISSUE TITLE
[Suggestion] Drones and Shipyards

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#1001]
Based on your last devlog, it seems that you want it so we build at shipyards (keep the specifics of that undefined) rather then out in the open. You are working on drones to move to this, but to me it feels like a half-measure. Not that it isn't incomplete as it is a pre-alpha, but that to complete the move to shipyard build mode, there would have to be a large shift which I feel the drones don't fully address. So let me make this suggestion and Ill try to keep it brief.

The issue with the drones is that they are generally unreliable or at the very least slow building compared to what was before. See many of the other reports, one of them being the tendency to bump into ships making them move around. To me, it feels like the drones are the icing on what will be the shipyards. What I propose instead of the drones now is let us build you a space dock which would be spawned in automatically in the world like the ring. A test shipyard. Then inside the build define a build area, like 500x200x100. After that, all you need to do is "interface" to the shipyard and you can start building. Instead of clicking on a drone to open the interface, have a button which will do the same with all the same functions while building.

There is a bit more to this idea, but I will leave it there. This doesn't mean you have to stop working on the drones, but they feel more like poring the syrup before making the pancake. Eventually you will have to add something like the suggestion. Drones can be added in conjuncture to shipyards. Most of what you did already can be easily moved into this idea. Like the interface for example. To finish, there are advantages of this suggested system. One of the big ones is it can create a soft wall to limit the size of the maximum ships just like you wanted in survival. Ill leave it at that for now, but I'd be happy to discuss the idea more fully.

K bye <3

**Comment by gmunga5** [comment]
Seems like a good idea to an extent Zach the only issue I see is the limited size for ships. I have expressed countless times that I don't think setting up anything that limits how big you can build is a good idea.

**Comment by ZachZent** [comment]
> 
> 
> I have expressed countless times that I don't think setting up anything that limits how big you can build is a good idea.

I am on the side of a soft cap on ship size is beneficial, but I can see where you are coming from. Perhaps I should add to that remark.

With the drones now, there is no rational way to make some relation between size and cost of building at that size. With shipyards of whatever size, the cost for building them is scaleable so that a new player who makes their first shipyard block can't just suddenly place down a 1000x1000x1000 grid. It is not the point of the main idea, but being able to have the ability to add some scaleable cost is something the drones can't do.

**Comment by tsunamayo** [comment]
Thanks for the suggestion, this is actually close to what I want to do. Just the shipyard would be found in the galaxy, not spawned by the player.

Shipyard will be needed for several reasons: to respawn somewhere when your ship is destroyed, to not be attacked by pirate when you build, to have access to a store where you can buy blocks (like if it where a codex).

Also sorry gmunga but yes there will be a maximum size for shipyard as the tech cant handle well very big ships (as you know it firsthand) and was more built with micro detailing / interior building in mind... But I would be able to increase it as I optimize / fix the game. Also it is needed for gameplay, as the idea is that large shipyard would be more rare than smaller one, so bigger spaceship means bigger range needed when building it. This is also unfortunately the kind of stuff I need to sort out before I release.

The drone is buggy, lets fix it! If I had to give up each time something was buggy, there would be no skywanderers ;-). If it is too hard to fix, then I will do another way (most likely like you suggested)
Thanks

**Comment by gmunga5** [comment]
I mean the gameplay thing sounds like a great idea but it still remains that we aren’t quite at the stage where that is a major thing. If something like that does happen some sort of way to adjust the shipyard size in creative would be a good idea as to allow players to build what they want without having to find the right shipyard in creative. 

On a side note I think you are underestimating how well the game can handle larger ships especially with the refactoring. My personal experience may portray it wrong with the ISD but that is more of a result of the abuse of child entities than anything. Not to mention that with the new ability to make 17x17x17 blocks you should be able to make a bigger ship in a more acceptable way to the system.

**Comment by tsunamayo** [comment]
Yes for sure the new rescale is gonna drop the vertex count significantly, which is a huge bottleneck in voxel game. Problem is for the light and other stuff I store a lot of data per voxel, and thats a lot of memory on the gpu side. A 512 x 256x256 ship is 33 millions voxels and 8000 chunks! These things add up very quickly in 3D.
Also I need to optimize things further, as it might seems fine and playable atm and a big ship, but I need those precious ms to do gameplay stuff and not just pure rendering.

**Comment by Garrett-C** [comment]
I mean that is fair enough but that assumes that you are building a 255x255x255 ship which not many people do. I understand you are just using that to display the maths and all. It is worth noting that most people tend to build long thin ships which when you mess around with the dimensions you provided can still be achieved. as a 255x255x255 ship is approximately the same as a 1000x100x165 ship. Based on this I would imagine the game currently can at least handle a 1k ship and if you were to impose a temporary limit something around 1.5k might work well. 

One other point is that if shipyards of varying sizes are added it would likely be a good idea for someone in creative to edit a shipyard to change which of the three sizes it is. If say you have s 200m^3 shipyard and a 500m^3 shipyard a creative player should be able to change the 200 one to a 500 one. It seems silly to have to explore to find a shipyard for building in creative mode. That said the idea of having to search for shipyards in survival sounds great, perhaps you could even create one but it is rather expensive.
