### ISSUE TITLE
[Bug] Sequencer Issues

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Starship-EVO#1010]
### Short Description of the issue:
Sequencer does not seem to actually affect the new hinge. Also, the sequencer seems to randomly break the connection with its input, usually after the values are changed.
### Steps to reproduce the issue:
Try to use the sequencer to set the new hinge to a different angle.
Change the values in the sequencer.
### Environment
- Skywanderers version: 18w47a
- Graphics Card: GTX 1060

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2610642/output_log.txt)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Issue was fixed some builds ago. Thanks!
