### ISSUE TITLE
Moving vessel causes massive fram rate drops

### ISSUE THREAD

**Issue by BrickMacklin** [tsunamayo/Starship-EVO#1024]
### Short Description of the issue:
When I go into flight mode and fly my ship the game's fps drops from 144 to 17-24. If I exit flight mode the frames do not go back up. There is also no engine or light glow. Previous game versions were not doing this. Video below demonstrates.
...

### Steps to reproduce the issue:
Pilot a large ship and turn it/move it.
...

### Environment
- Skywanderers version: 18w47a
- Graphics Card: RTX 2080 Ti

### Additional information:
Video: [https://youtu.be/Ruf6jy5iqwk](https://youtu.be/Ruf6jy5iqwk)
[output_log.zip](https://github.com/tsunamayo/Skywanderers/files/2622114/output_log.zip)

**Comment by tsunamayo** [comment]
Hi! log is too big to be open, if you can reproduce and exit straight away that could help. I think it might be related to the engine. In the new build I remove engine grouping, now you have to create group by stretching the engine. 
I will think on something so that player dont stack engine on top of another and force them to use the stretch, otherwise it wont be optimized.

**Comment by BrickMacklin** [comment]
> 
> 
> Hi! log is too big to be open, if you can reproduce and exit straight away that could help. I think it might be related to the engine. In the new build I remove engine grouping, now you have to create group by stretching the engine.
> I will think on something so that player dont stack engine on top of another and force them to use the stretch, otherwise it wont be optimized.

All of the engines on the ship are stretch engines. No stacking.
Here is the log: 
[output_log.zip](https://github.com/tsunamayo/Skywanderers/files/2626038/output_log.zip)

**Comment by tsunamayo** [comment]
Hi @BrickMacklin , is this something you still get in newer version? If yes could you please send me your blueprint so I can have a look. Thanks!

**Comment by tsunamayo** [comment]
This was a sfx issue linked to a high number of engine I think. Fixed in newer versions. Thanks!

**Comment by BrickMacklin** [comment]
@tsunamayo I am still getting this bug

**Comment by tsunamayo** [comment]
But is was large ship near station right? I think in this particular case it was something else.
