### ISSUE TITLE
Framerate drops when building (reproducable and with clear cause)

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#1045]
### Short Description of the issue
normally run the game at 100fps, can travel around ship and other large projects without any drops. however, after placing and breaking a few blocks, framerate will drop to 56 and stay there until i look away for a while. (then repeats).

if not corrected, framerate will dive again into the 30s with no discernable cause.

...

### Steps to reproduce the issue:
just build.
...

### Environment
- Skywanderers version: Experimental
- Graphics Card: Vega 56
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2684496/output_log.txt)

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by gmunga5** [comment]
Yeah I am going to say that’s just performance issues and not a bug really. The game will probably be optimised in the future. Not to mention in your title you say you can reproduce it with a clear cause but building is fine for other players and you didn’t explain the cause.

**Comment by pinesh** [comment]
pretty sure it has to do with the way the game merges blocks, tsuna earlier said that he stopped engines merging that wasn't in the stretch. the more blocks the game tries to texture and retexture, the worse performance gets.

**Comment by tsunamayo** [comment]
Hi, could you please send me your blueprint? There might be performance issues related to engine, as now the sound effect dont merge ect. I will do something so that player are forced to use the drag function for big thruster. Not sure if it is your issue though! Thanks

**Comment by pinesh** [comment]
hello again, since my ship broke after the stencil bug I am going to have to send you my save data where the ship is present. 
i forgot to report the sound thing as well. glad to hear you already know about it. 
[Save_Data.zip](https://github.com/tsunamayo/Skywanderers/files/2688907/Save_Data.zip)

**Comment by ProPeach** [comment]
Regarding changing the way we build engines using the drag function, is this the only solution available? As I understand it if this went ahead, with the player only being able to build cuboid shaped engines up to a 16m^3 size this would ~severely~ limit our options when it comes to engine types.

**Comment by tsunamayo** [comment]
@pinesh nice ships! Is this something you still have in the latest versions of the game while using stretched engine efficiently (not one by one but stretched). 
@ProPeach 16m^3 is a pretty big size, is it a size issue or a shape issue?
Thanks!

**Comment by ProPeach** [comment]
Both shape and size to an extent, the issue with the current stretchy engines is aesthetic as well as functional. With the drag limit being 16m, you can't build a single engine larger than this and gain a larger bonus. You're also limited to only quadrilateral shapes, unlike previously when thruster texture connected, now the thrusters have a hard border in between quadrilaterals. Here is a sample of engine shapes that are effected by this. Note that any shape other than one with 4 sides smaller than 16m^2 is effected
![image](https://user-images.githubusercontent.com/27857711/60719136-a48c3c80-9f1e-11e9-8cac-1407fb070bd5.png)
