### ISSUE TITLE
[IDEA] Weapon: Lazer/beam

### ISSUE THREAD

**Issue by JRL101** [tsunamayo/Starship-EVO#1074]
So i've been playing a lot of classic space games and watching some classic scifi.

I noticed lasers have a charge time of some sort, BUT the one i enjoyed for its balance was the "charge to max damage" design.

Basically the weapon has a short charge before firing, dependant on its max damage.
`Max damage DEVIDE x =Start Charge = time till beam on`
but instead of being at max damage immediately, the beam/laser needs time to increase damage to max damage.
`D=% of Max Damage
T = x of Max damage
D multiplied by T = Current Damage =Damage does not exceed Max Damage`

_Charge beam to fire.
Damage increases to Max damage over Time.
Time to charge/reach max, is decided by how much max damage the weapon has._

Nice and simple.

**Comment by tsunamayo** [comment]
Yes I like that idea, I wanted something like this but as an addon: Like you charge your laser, and it make 4x the damage (for example). I will tackle laser + addons soon. Thanks
