### ISSUE TITLE
[Suggestion] Alien Catgirls as a Secret Playable Race

### ISSUE THREAD

**Issue by Senakysam** [tsunamayo/Starship-EVO#1079]
For reasons purely in my self interest, I'd like to play as a catgirl and/or have catgirls crewing my ships, but not everyone it on board with it. So how about making it so I can put in a cheat code that will let me choose to play as a catgirl or hire them? Pretty please?

**Comment by PopkaAkula** [comment]
this is so sad

**Comment by BlueStriderX** [comment]
this is so epic, I cant wait to have anime catgirls in spaceship desu nyaa~ uwu please end me

**Comment by BlueStriderX** [comment]
id be ok with adding catgirls as long as we can commit war crimes against said catgirls

**Comment by tsunamayo** [comment]
Yes I also want to add a female version of the cat guy... I keep you posted. Cheers
