### ISSUE TITLE
[RotC] Can drag hull into adjacent ships

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#1093]
### Short Description of the issue:
I'm able to clip hull into an adjacent ship
...

### Steps to reproduce the issue:
Make ship
Make another ship
Drag
...

### Environment
- Skywanderers version: RotC
- Graphics Card: GTX 970

### Additional information:
![20190523213946_1](https://user-images.githubusercontent.com/32974671/58299173-e3699700-7da3-11e9-8946-26a3ecbe4f82.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3214858/output_log.txt)

**Comment by tsunamayo** [comment]
Yes the collision check only operate on our ship - I need to change that indeed. Cheers

**Comment by tsunamayo** [comment]
This sould still be happening...  Thanks
