### ISSUE TITLE
[RotC] Controls get reset

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#1113]
### Short Description of the issue:
Controls get reset when exiting to menu. This happens when playing multiplayer, switching to menu then jumping back to singleplayer as well as playing singleplayer, switching to menu then playing multiplayer
...

### Steps to reproduce the issue:
1. Play singleplayer
2. Exit to menu
3. Join multiplayer
---------
1. Join multiplayer
2. Exit to menu
3. Play singleplayer
...

### Environment
- Skywanderers version: RotC
- Graphics Card: GTX 970

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3219472/output_log.txt)

**Comment by khowhl** [comment]
I experienced that bug without switching from singleplayer to multiplayer or vice versa. Simply exiting to menu from singleplayer and loading the save resets the key mapping to default.

**Comment by tsunamayo** [comment]
I think it should be good in recent version. Thanks
