### ISSUE TITLE
[Suggestion]Save and exit

### ISSUE THREAD

**Issue by ultrak2k** [tsunamayo/Starship-EVO#1164]
Ive heard stories of people leaving the game not realising they saved, maybe it would be a good idea for a save and exit on the menu, would help save some productivity too

cheers, ultra (and the guy who told me to suggest this)

**Comment by ultrak2k** [comment]
oh and some people dont know of F1 to save I  assume

**Comment by tsunamayo** [comment]
Yes, but when the game is ready I will just add auto-save. Thanks!

**Comment by tsunamayo** [comment]
We have auto-save since a while now. Thanks
