### ISSUE TITLE
Game Crash during boot-up

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Starship-EVO#118]
Might be related to difference between Windowed and Fullscreen modes, Launcher must be set to the same mode as the in-game option else the graphics driver crashes. At least for me. First time loading game required me to be Window mode, second time after setting fullscreen IG, required me to Fullscreen mode to log in the second time.

NVIDIA GT530 with non-standard monitor resolution 1360 x 768

[error.log](https://github.com/tsunamayo/Skywanderers/files/1407011/error.log)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1407012/output_log.txt)

**Comment by Napther** [comment]
Came out of game from a different crash, and several attempts in with different settings, the game will not boot up beyond "Made with Unity" message.

**Comment by Napther** [comment]
After tinkering, discovered that the program f.lux (the screen dimmer/redshift for sleeping better after using a computer) was interfering with Skywanderer's boot. After exiting, it works and boots 100% of the time.

**Comment by tsunamayo** [comment]
Okay could you send me your new error.log and output_log after the new driver install? It seems you have a very low graphical card, there was issue related to that in the first log.

**Comment by Napther** [comment]
The card is 1024MB so 1 gigabyte oN the VRAM. Unfortunately I will only be able to send those new logs after getting to my computer in 11 hours time.

**Comment by Napther** [comment]
Annoying that only ZIP works and not my usual RAR files. This is the latest crash to occur during boot up. Will now attempt several times to get into game to finish things...

[2017-10-24_204358 - NaptherBootCrash.zip](https://github.com/tsunamayo/Skywanderers/files/1412294/2017-10-24_204358.-.NaptherBootCrash.zip)

**Comment by tsunamayo** [comment]
Hello. Is the crash / not crash pattern completely random - or did you noticed something that impact it?
It is clearly related to your GFX card, your driver is crashing. Could you try a standard resolution (I dont think it is that, but I still want to check), like 1280 x 720.

**Comment by Napther** [comment]
Every crash has occurred at all resolution as well as windowed VS Full screen starts. There might be combinations I haven't tried but I was completely blocked out from booting 9 hours ago. I can attempt to shuffle a few system things and try maybe the resolution on boot up I missed but otherwise I'm completely unbleached to load

**Comment by tsunamayo** [comment]
Okay sorry for being late on that. Could you please do the following test for me? I suspect issue come from Torus, I would like to know if it is because I am asking too much work too fast or if you are really unable to compute Torus data.

Could you please unzip the following file under 
C:\Users\{YOUR USER]\AppData\LocalLow\TsunamayoCorp\Skywanderers\Save_Data\Characters

[Characters.zip](https://github.com/tsunamayo/Skywanderers/files/1417378/Characters.zip)

Could you restore back the the Torus.swbp first.

Could you please do the following:
1) Load Empty_world : is it working? 
2) Load Torus: is it working? Do you see the torus
3) if 2) is yes, could you please hit ] key a few time to move faster (but not too fast), and then try move slowly toward the torus until you reach the ground. Is it working or crashing?
4) could you load Asteroids, then tell me if you see the asteroids.

Thanks

**Comment by Napther** [comment]
Tsuna,
While I havent done that yet, after over-clocking + 10% of my crappy old GPU the game seems to boot every time now (2 successes 2 different days after overclock first time). (699 MHz core clock and 740 MHz Memory clock to 760 and 820 respectively)

I do mention I never get to see the start menu at all to even ENTER a world, unless very lucky. Ive never been lucky on the first try to load the game. If I encounter this issue again I will roll back to the default GPU clock and try these fixes - Since modifying the Software is far more inclusive than asking for people to Modify their Hardware (and potentially break it).

**Comment by tsunamayo** [comment]
Okay sorry I got you confused with other case, in any way the culprit must be the Computer Shader work that I ask on boot up (compute the first zoom level of the galaxy - as it is always needed for the holomap). I will investigate that, but it is complicated as I dont reproduce the crash and GPU are not talkative.
Would you be open to do some test for me if I give you a few custom build to test?
Btw the file send are not fixes, just test case for me to understand what is going wrong.
Of course I will never ask people to overclock their GPU as a fix ;-) (I might up the minimum req though).

**Comment by Napther** [comment]
I can certainly use my Rig for software tests with the Default clock speeds Just so long as I know "what" to reply/respond with for how the system behaves in a way that will help you.
Since overclocking, I've not encountered a single issue yet in booting up the game. The only thing that is left is to re-try that Galaxy Map crash #126 of mine with these new settings to see if if these 2 are linked to low GPU power.

**Comment by tsunamayo** [comment]
Hi, I made some change to make startup easier on the GFX card. Could you please activate the debug version inside steam (right click on the game, then properties, then betas, then choose debug), and tell me if the game boot correctly (on your non-overclocked rig)? 
Thanks!
