### ISSUE TITLE
[Suggestion] Yet another brick suggestion

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#1189]
### _What's the situation captain?_ ###
I really hate to ask for another brick shape, especially right after you added 2 other shapes, but while pulling my hairs out trying to perfect the MTT's awkward angles, I've finally realized I either need to ask for the missing shape or compromise the design to fit with what is available so may as well ask :D I'm totally fine if you'd rather not add another brick shape by the way

-----------------
### _Hello there!_ ###
Here are two examples of the closest replacements I could come up with to replace the needed brick:

![20190601194342_1](https://user-images.githubusercontent.com/32974671/58756642-b95e5600-84c2-11e9-8a78-d787a700c406.jpg)
![20190601225128_1](https://user-images.githubusercontent.com/32974671/58756652-c11dfa80-84c2-11e9-80f1-ceab08ca0f9b.jpg)

-----------------
### _This is where the fun begins_ ###

And here is essentially what shape I need for this problematic angle:

![20190601225930_1](https://user-images.githubusercontent.com/32974671/58756731-00991680-84c4-11e9-838f-9e0bea21b1a5.png)

-----------------
### _You're breaking my heart_ ###

It really is quite an awkward angle because it comes to a point while shifting over a brick. Again it isn't necessary and to be honest it's quite situational but may as well ask and know for sure.

-----------------

**Comment by Starwhip** [comment]
I don't think that is a possible block. It intrudes on the top block's boundaries.

**Comment by Xerma** [comment]
You could say it's a... stretch to ask for

**Comment by tsunamayo** [comment]
+1 for the pun. But if I understand the shape correctly I am not sure I can make them atm, I have to check there is a few shapes like that that would require a bit of work on the tech side, so most likely not on the short term if ever. Thanks!
