### ISSUE TITLE
[19w22i] Cursor visible on loading screen and in-game

### ISSUE THREAD

**Issue by Breezebuilder** [tsunamayo/Starship-EVO#1190]
The blue mouse cursor remains visible but locked to centre, both on loading screens and in-game over the top of the regular white reticle.
The cursor is locked to screen centre immediately after entering loading screen, and remains visible during play.
The cursor can be hidden temporarily by opening the codex, hovering directly over an item (so that cursor becomes grabbing hand icon), then closing the codex with the Tab key only.  Cursor is also hidden after alt-tabbing out of game.
After opening codex or any menu, cursor becomes visible again as it should, but remains after menu is closed.

### Environment
- Skywanderers 19w22i
- GeForce GTX 1050
- NVIDIA Driver 430.39

**Comment by tsunamayo** [comment]
I dont get the same behaviour. Could you please tell me your monitor configuration (several monitor?) and whether you run the game in fullscreen or not? Thanks!

**Comment by Breezebuilder** [comment]
Using a single monitor, 1920x1080, 120Hz.
The issue occurs in both fullscreen and windowed mode, at any resolution.
Also still occurring in 19w23a.

**Comment by tsunamayo** [comment]
Okay @Breezebuilder I know it have been a while, but if you played the game recently could you tell me if you saw that issue again? Thanks!
