### ISSUE TITLE
[Cannot accurately reproduce] Return of the Stutter

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#1194]
### Short Description of the issue: ###

I discovered something very odd about my notorious stutter issue, and it's that I cannot totally reproduce it every time. Only sometimes when I boot up the game I get the stuttering while other times I don't get any stuttering whatsoever. The only thing that I can describe is waiting a little bit after each boot up. However I had a gap of almost an hour and half between starts. So I'm about as confused as you as to what exactly is going on. During the stuttering I didn't even see anything abnormal in Task Manager. No jumps, no dips, nothing.

------

### Steps to reproduce the issue:

Yes

------

### Environment
- Skywanderers version: 19w22i
- Graphics Card: GTX 970

**Comment by tsunamayo** [comment]
Gotcha, this one is gonna be complicated to fix I am afraid, but I know how annoying stuttering can be. 
Few questions:
 - What is your ram usage when loading the game? 
- Can you give me your full config?
 - Do you have a SSD or a HDD
 - can you take a screenshot of your game with FPS stats (F3 -> Show FPS Stats)

I know I have some garbage collection going on, but if it was the culprit then it would happen all the time... 
Thanks

**Comment by Xerma** [comment]
- Ram usage ranges from 1,300MB to 1,700MB while loading up from steam to menu and menu to game. Stays around 1,500MB thereafter
- PC specs: 
Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (Quad core hyper threaded)
32.0 GB RAM
64-bit operating system (Windows 10)
Nvidia GTX 970 GPU
==Game settings:==
Resolution: 2560 x 1440 @ 59Hz
Fullscreen: On
Vsync: On
Ambient Occlusion: On
Anti Aliasing: Off (causes frame drops when enabled)
Vignetting: Off
Bloom and Flares: On
Chromatic Aberration: On
FOV: 60
- I do have both an SSD and an HDD but system and all games are on the SSD
![20190602222939_1](https://user-images.githubusercontent.com/32974671/58774218-f17a9d00-8585-11e9-8658-71c73beeca99.jpg)
