### ISSUE TITLE
[Suggestion] Return to old seat style

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#1201]
Though the new seats look very nice, they have the very annoying flaw where editing them ends up clipping into the cushion, the sides, or other blocks. Even the couch which is designed to be editable has the problem of clipping. It makes it very difficult to make good looking chair and even harder to make one that is seamless with the standard model of the chair itself. Before the graphics update, the chairs were just the frames and it worked very well for customization. You can make it any shape you wanted without fear of clipping into the better textured chair.

The seat could stay as is, but the at least the couch should really go back to the old design type of only a frame and no cushions. Of course keeping the new texture. The cushion should also return to being a seperate item to be added to the chair. More than that, the separate cushion brick can be added in many more areas besides chairs. Thanks

![Seat](https://user-images.githubusercontent.com/36980446/58778161-4a4a3580-8586-11e9-80b6-7ab03ae98066.png)

**Comment by tsunamayo** [comment]
Yes I planned to do a barebone chair for customization. But cushion wont return, it is just too complicated as you need to deal with raycast the seat below for activation, then there is sitting height issue ect... Thanks

**Comment by ExodistSKY1** [comment]
Could we get an item that allows characters to be harnessed in an upright (standing) position?
