### ISSUE TITLE
Character movement Disabled after liberal use of ] key

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Starship-EVO#121]
After pressing "]" to see if I can get to the star int he Tutorial World (MUCH faster than a ship's natural acceleration can get there), I attempted to go back to the planet by spamming the ] key to accelerate. 

Before I knew it the screen jittered a little and was stuck at 2k LY from the star system. Spawning in a ship confirmed that I was completely unable to move after reaching this point. 
After returning to the Torus with the Teleport, the character still did not respond to movement and required a re-log.

**Comment by tsunamayo** [comment]
Okay this mode also need some better HUD info, it is more of a debug tool but this I would like to keep it so I will put an indication on your current speed factor. 

It is not a boost or something that give you acceleration, it just multiply by 3 your moving speed each time you press it.
So if you pressed ] n time you will need to press [ n time in order to get back to normal speed.

Btw for the normal survival game I wanted to add some kind of booster pack to get the same feature in a less cheaty way.

**Comment by Napther** [comment]
Some hud element would be great to give an idea of relative speed with Debug Speed Boost. And aN EVA pack that allows the first and second speed increase would be great since flying a 1 block ship to get around is... interesting... to say the least

**Comment by tsunamayo** [comment]
Yes, I will add mini spaceship/suit core brick to make custom EVA, that could be re purposed for combat, mining, exploration or building with various tools or more inventory space. How do you move faster in Starmade for example?

**Comment by Napther** [comment]
In StarMade, we can either exit gravity and look down and press Forwards and Upwards at the same time. The vectors of forward and upward combine to create a faster vector 45* above your sight.

FOr anything more than 100m, players will tend to press X to spawn a new ship core, R to hop into it, then control it like a much faster astronaut as it has the same controls on a player as a ship, as in Advanced Build Mode. A ship core in Starmade is significantly easier to control than a Ship control block thing as the Core alignment is always constant with your vision (Mouse pointing) whereas the ship control core thing has a tiny box around it where a player is latched to it (the padlock in the bottom left of the HUD), and has to be guided like a ship with pitch yaw roll and thrust rather than acting like a 50+metres/second astronaut as is in Starmade.

**Comment by tsunamayo** [comment]
Okay, the EVA suit will more look like the ship core trick in starmade I guess.
