### ISSUE TITLE
Very strange rail bug.

### ISSUE THREAD

**Issue by Starwhip** [tsunamayo/Starship-EVO#1216]
### Short Description of the issue:
One rail on my ship seems to have bugged out. It has bugged texture marks and refuses to play nice with logic like Query gates. It can be manually toggled and toggled with switches.

### Steps to reproduce the issue:
Unknown. 

### Environment
- Skywanderers version: Latest (19w23a)

- Graphics Card: Radeon RX 580

### Additional information:

[Screenshot album](https://imgur.com/a/IDWSUQb)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3255044/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, could you please send me your blueprint? Thanks.
Spawn a drone with F5, build a block so the drone understand were you are building, then click export. the blueprint will be saved in:
`%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\Save_Data\Blueprints
Thanks!

**Comment by Starwhip** [comment]
Github doesn't like the raw filetype, here's a .zip containing the blueprint.
[Cargo Shuttle - Bugged Rail.zip](https://github.com/tsunamayo/Skywanderers/files/3259827/Cargo.Shuttle.-.Bugged.Rail.zip)

**Comment by Starwhip** [comment]
I've been able to replicate the issue on a brand new world.
![20190615154708_1](https://user-images.githubusercontent.com/36343006/59555758-51f5db00-8f85-11e9-99a6-aa634d6960b5.jpg)
I've discovered that this is not limited to the rail on my ship. On these fresh rails you still cannot build the circuit in question; I believe it has to do with circular logic.

The switch connects to the OR gate. The OR gate connects to the first rail's sequencer to move it. The first rail connects to a query gate to see if it has moved to the end position.
That query gate connects to and AND gate along with the original switch. The AND gate connects to the second rail's sequencer to make it move. The second rail then has a query gate to see if it has moved into position, which I _want_ to attach to the OR gate, but it will not let me complete the circuit.

NOTE: In the screenshot I am dragging to the AND gate but I meant to drag over the OR gate; neither will connect.

My hypothesis is that the code which controls the logic is not allowing the circular loop in this scenario.

**Comment by Starwhip** [comment]
Here is the blueprint file for a test platform. The red painted logic gates will not connect.
[Circular Rail Logic Test.zip](https://github.com/tsunamayo/Skywanderers/files/3293492/Circular.Rail.Logic.Test.zip)

**Comment by tsunamayo** [comment]
Sorry I slept on this, yes circular logic is not allowed. I will see what I could do to solve this, as in case there should be a delay in the execution which should be okay. I keep you posted!

**Comment by talrey** [comment]
The timer / delay brick already lets us build this sort of circular logic / feedback loop, right? That might not be obvious to people at first, though. Maybe some kind of tooltip (or error message when we have a chat box) could help here, so the game could explicitly tell us "instant loop, use a delay to create this link" or something like that.

**Comment by tsunamayo** [comment]
Yes correct, having some kind of error popup is on my to-do list for a while, as there is many more case where it could prove useful.

**Comment by tsunamayo** [comment]
So this popup was actually introduced a while back. Thanks!
