### ISSUE TITLE
Large Grid Render Bug

### ISSUE THREAD

**Issue by AsageSoftworks** [tsunamayo/Starship-EVO#1222]
### Short Description of the issue:
Graphical bug when loading displaying large grids over 1km in length
...

### Steps to reproduce the issue:
Load included blueprint, which will change to white when trying to view the entire grid.
...

### Environment
- Skywanderers version: newest
- Graphics Card: GTX 1070 TI

### Additional information:
Game will take a while to load the grid, several thousand blocks.

_(Screenshots, Videos, Error logs, Related issues)_
![20190604151754_1](https://user-images.githubusercontent.com/43458562/58981153-6ffa5900-8797-11e9-8c64-3f7679909c43.jpg)
[ISD Issue Zip.zip](https://github.com/tsunamayo/Skywanderers/files/3258580/ISD.Issue.Zip.zip)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

[Output Log Zip.zip](https://github.com/tsunamayo/Skywanderers/files/3258585/Output.Log.Zip.zip)

**Comment by tsunamayo** [comment]
My god... You build this by yourself? How long does it take to load? I know the game have excessive loading time issue with large blueprint... 
Is the visual bug only over the part that is over 1km, or does it happens on all the blocks?
Thanks

**Comment by AsageSoftworks** [comment]
Yessir! Last year I spent a little over 250 hours on it. It takes approximately 7 minutes to load on my end, but I have a higher end pc. 16gb ddr4 ram, I7-8770k, GTX 1070TI. When you first load the blueprint it takes about 2 minutes to do the initial load and 5-8 minutes for the graphical render. I will load some images to show what the issue is specifically. When viewing portions of the ship, it is rendered normally, but when viewing large portions of the vessel, the game turns it white.
![20190604151754_1](https://user-images.githubusercontent.com/43458562/59021004-aa540c80-8810-11e9-9486-7bc53e14d7b3.jpg)
![20190604171845_1](https://user-images.githubusercontent.com/43458562/59021020-b0e28400-8810-11e9-8c46-64ce494280b9.jpg)
![20190604172157_1](https://user-images.githubusercontent.com/43458562/59021027-b4760b00-8810-11e9-9a0c-a436bd93740a.jpg)
![20190605133721_1](https://user-images.githubusercontent.com/43458562/59021056-bfc93680-8810-11e9-9ecb-5fb20f646fe9.jpg)
