### ISSUE TITLE
Major FPS loss while up close to larger blocks

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#1248]
### Short Description of the issue:
I've noticed that as I'm up close to some larger blocks my frames take a major hit and drop to 28 at times. Granted this is a larger build but it's well within the limits you spoke of. The blueprint in the pics is the frame to a spherical ship with a diameter of 236m.

- GPU usage ranges from 45% to 75% while in-game. Jumps to around 80% or 90% while tabbed out of the game.
- CPU is stable
- Memory seems stable at about 2,025 MB
...

### Environment
- Skywanderers version: 19w23d
- Graphics Card: GTX 970

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3270515/output_log.txt)
![20190609225315_1](https://user-images.githubusercontent.com/32974671/59171820-8d6a5280-8b0a-11e9-83c9-a6ca24808358.jpg)
![20190609225314_2](https://user-images.githubusercontent.com/32974671/59171823-8fccac80-8b0a-11e9-944a-94bc828c15b5.jpg)
![20190609225314_1](https://user-images.githubusercontent.com/32974671/59171825-91967000-8b0a-11e9-8110-e75b17c0375f.jpg)
![20190609225313_1](https://user-images.githubusercontent.com/32974671/59171827-94916080-8b0a-11e9-96d0-180844b1474a.jpg)
![20190609225311_1](https://user-images.githubusercontent.com/32974671/59171830-99561480-8b0a-11e9-8892-551633fe839f.jpg)

**Comment by Xerma** [comment]
It might also be worth noting that placing these created brief lag/fps drops that went away after placed

**Comment by Xerma** [comment]
Not so sure anymore that it's related to just large blocks. On a smaller ship (103m) I still get massive frame drops. Is it possible it's because of my resolution? My main "monitor" is a 1440p Wacom 27QHD (59Hz) drawing tablet

**Comment by ProPeach** [comment]
I've noticed that the lag spikes produced when you place a large stretched block only occur on large ships when you're "breaking new ground" so to say. If you're on the edge of an already large ship and place a large stretched block, you'll have a lag spike. But then you can delete and replace that large block with no lag spike at all. It's like it only lags when you initially increase the overall boundaries of the grid

**Comment by tsunamayo** [comment]
Okay so it is when the chunk grid is updated. My guess would be it is linked to the 3d texture. Could you give me one of your large blueprint so I can check? Thanks

**Comment by Xerma** [comment]
I'll email it to you after a little while, wanting to keep the build private :-D not a secret, just private

**Comment by ProPeach** [comment]
[Profundity-ProPeach.zip](https://github.com/tsunamayo/Skywanderers/files/3288644/Profundity-ProPeach.zip)
Here you go, this one is a 1.2km experiment. I was experiencing this bug as I built the slopes on the bottom. If you continue building down you should experience it too

**Comment by tsunamayo** [comment]
@xerma is it a fps hit when you place the block or when doing nothing, just staring at it up close? Also what is your base frame rate? Could you please send me the smaller blueprint also? It is normal to have a drop in fps when looking at a lot of geometry, I just want to see how big of drop it is and see if there is a bug or not. Thanks

**Comment by tsunamayo** [comment]
So I tested your build, and I dont really spotted any area with significant FPS drop. Is this something you get only at a specific place? Thanks

**Comment by ProPeach** [comment]
Here's a video of my experience using the Profundity blueprint as well as the log file. It only happens when you extend the boundary of the current build, I'd suggest trying it right at the bottom and attempting to continue the slope. You can see that it lags when placing a new block in new space, but is perfectly fine when you replace it
[Skywanderers large placement on large structures lag.zip](https://github.com/tsunamayo/Skywanderers/files/3362477/Skywanderers.large.placement.on.large.structures.lag.zip)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3362478/output_log.txt)
Let us know if there's anything else we can do!
