### ISSUE TITLE
[Suggestion] Have window tint rotate with the block

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#1258]
### Short Description of the issue:
I think this was discussed some time ago but as you can see in these examples I think it would be nicer if the tint on the outside of the window blocks rotated along with the blocks. Otherwise you get some weird looking windows like this.
...

### Environment
- Skywanderers version: 19w23d
- Graphics Card: GTX 970

### Additional information:
![20190612130719_1](https://user-images.githubusercontent.com/32974671/59375332-88c4ba80-8d13-11e9-87ff-1094b0b3a468.jpg)
![20190612130722_1](https://user-images.githubusercontent.com/32974671/59375338-8a8e7e00-8d13-11e9-88d5-7ee2d0590d89.jpg)

**Comment by tsunamayo** [comment]
Okay sorry mate I am going through my backlog of cases. I am not sure to get what you mean! Thanks
