### ISSUE TITLE
Logic gates consider low/off signal as a high/on signal (any signal is positive)

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#1270]
Buttons, switches, and other logic send a 1 even if 0 state is triggered.
...
Connect 2 switches to an AND gate. Activate one switch. Deactivate the same switch.
...
- Skywanderers version: 19w24a
- Graphics Card: Nvidia GeForce GTX 1060 6gb
...
issue #1263 might be related.
issue #517 might be related.
issue #156 might be related.
...
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3291789/output_log.txt)

**Comment by tsunamayo** [comment]
I am not sure to understand the case, what do you observe and what you would like to observe?
It works fine on my side.
OFF | OFF -> OFF
ON | OFF -> OFF
ON | ON -> ON 
Thanks

**Comment by talrey** [comment]
Can you post a picture of your test circuit, Majik? That would help a lot here. How are you reading the output of the AND?

**Comment by Majikmonster** [comment]
Most working systems at the moment respond to off signals as well as on, so I use the laser as the output. The gates are supposed to respond to specific combinations of signals, but they don't always do what they describe, which could be a switch/button problem or a gate problem.
example with AND gate:
ON+ON=ON for the laser (it fires)
OFF+OFF=nothing for the laser (no effect)
When the output is a button or switch, any state change on any of the inputs sends a signal and changes the state of the output, even though the AND gate says it is supposed to send a signal only when all of it's inputs are ON. It functions no different to OR / NAND gates.
example with OR gate:
ON+ON=ON for laser
ON+OFF=ON for laser (turning one of the outputs OFF results in activation)
The OR gate considers low/OFF signals as ON, making the OFF state of switches and buttons obsolete.
![20190614225036_1](https://user-images.githubusercontent.com/51390907/59546206-af434b00-8ef7-11e9-8992-573e1d873505.jpg)
Circuit left uses AND gate, circuit right uses OR gate (the faulty icons are a different bug). The left one works as expected for laser, the right one shoots every time either of the switches is changed, same goes for if it uses a NAND gate.

I would like the gate descriptions to match the behaviors. That's the premise of the bug.

**Comment by talrey** [comment]
I've done some extensive logic testing and the gates do in fact match their descriptions for me. Image below of my setup. I did notice some strange behavior with lasers instead of lamps - they seemed to fire multiple times at once, though I can't tell how many based only on the audio cue. They still only fired when expected though.

Just to make absolutely sure - nothing else is wired into the gates or the lasers, right? If you click on them with the link tool you can get a visual.

![20190614211750_1](https://user-images.githubusercontent.com/6946291/59546927-ba43ae80-8eea-11e9-9039-d4fdaad59175.jpg)

**Comment by Majikmonster** [comment]
No extra connections. Switches adjacent to the gate input to the gate only, and the gate only inputs to the laser. There is no backwards or cross-linking either.

**Comment by tsunamayo** [comment]
No issue as latest build. thanks!
