### ISSUE TITLE
[19w24a] Rotors getting stuck on nothing

### ISSUE THREAD

**Issue by Creepthefrenchpastery** [tsunamayo/Starship-EVO#1291]
The trials of building a pivoting thruster system are surprisingly extensive as today i am greeted by a wondrous new bug. Something is inhibiting the rotor form turning fully the only problem is that nothing should be causing it.

![20190620160855_1](https://user-images.githubusercontent.com/37814990/59932768-eba20a00-9415-11e9-89fc-c39f77a700de.jpg)
^ this is what the thruster should be in its off state
![20190621110805_1](https://user-images.githubusercontent.com/37814990/59932794-f9578f80-9415-11e9-989f-d1dac052a218.jpg)
^ this is what it gets to in the off state
i do hope this gets fixed

**Comment by tsunamayo** [comment]
Could you please send me you blueprint so I can have a look at it? Thanks!

**Comment by Majikmonster** [comment]
I have a similar issue. A rotating object that sits directly against the parent entity when spinning, or an object built on a rail that glides right up against the parent's blocks/bricks sometimes gets stuck and can't move at all, or just moves a little. Good to see the issue posted here.

**Comment by tsunamayo** [comment]
@Majikmonster @Creepthefrenchpastery guys if you could give me your blueprint so I can investigate the issue! That would be awesome ;) Cheers

**Comment by tsunamayo** [comment]
The collision for children entity has been greatly improved. Thanks!

**Comment by tsunamayo** [comment]
@Creepthefrenchpastery , hi did you tested your ship again? Collisions are much better now! Cheers
