### ISSUE TITLE
[Suggestion] Damage Shaders

### ISSUE THREAD

**Issue by JRL101** [tsunamayo/Starship-EVO#1301]
So i've mentioned this before but im more updating the idea, after playing "Rebel Galaxy" who seem to do it how i imagined, and that system could be utilised for Skywanderers.

First off this is the person i've been watching do "Shader Art" the last year. 
[Minions Art](https://www.patreon.com/minionsart/posts)
I've been watching them create some interesting Math shaders.
and thought these could help you make some for damage and other elements based on gravity or movement.

The advantage of using shaders is you can literally paint where you want them to show up.
### **For example:**
The damage from a laser. the impact explosion from an explosion, the singe marks from flame throwers.
an entire layer of the texture _(like normal/displacement maps)_
[Snow Shader](https://www.patreon.com/posts/interactive-snow-25641162) 
[Unity Polybrush and Shaders](https://www.patreon.com/posts/unity-polybrush-21033280) 
[World Position Shader](https://www.patreon.com/posts/quick-game-art-19355776) 
[Skybox Shader](https://www.patreon.com/posts/making-stylized-27402644)
[Liquid shader](https://www.patreon.com/posts/quick-game-art-18245226)

You can even do things like Parallax within a shader. for example the burnt out husk versions of the blocks and bricks. Im betting you've already looked into this now you're using things like normal maps for stamping down things. You could also replace that with the shader system too. stamping down a coloured shape or object with the shader applied to it.

Hope most of this makes sense. Most parallax shaders require math so you should find it easier than most people. Have fun experimenting!

**Comment by tsunamayo** [comment]
Thanks for the suggestion, I had seen this guy before but never looked too much into detail. The liquid one is very sexy, it gave me some idea for when I add liquid / gas extraction into the game! Yes I will have to do another pass on damage, and as I made the switch to stretched block it will be shader based, I had in mind using paralax to do show some internal damage from inside the block, I think there is room to do something very cool. Also I will leverage on the sticker tech to spawn special effects at precise location.
You have some example of how it look in rebel galaxy? I have never played it. Their new game looks amazing btw. 
Cheers

**Comment by ProPeach** [comment]
So glad that you've chosen to take this path, can't wait to see these effects!
Here are some examples from Elite dangerous of damage decals that appear when you shoot a ship
https://i.redd.it/0jfa2zjn6qn01.png
https://invisioncommunity.co.uk/wp-content/uploads/2014/09/4021.0.original.jpg
Some damage decals in Elite are time dependant - A laser burn will glow hot for a time before cooling down.
I can't find a reference image, but beam lasers also "draw" hot lines across hull

This one is from Everspace and shows a bit more structural damage, perhaps something like the use of parallax you mentioned like the carve tool (I remember your Q&A response!)
https://everspace-game.com/wp-content/uploads/2015/08/img14.gif

Hope you found these useful

**Comment by JRL101** [comment]
Yes the Painting aspect in Rebel Galaxy 2 looks INSANE! Especially the tool to "rub transfer" bits of images onto the ship. 


Heres some examples of RG1's damage, the first image is the ship undamaged.
![image](https://user-images.githubusercontent.com/33255536/60729862-49863400-9f76-11e9-8e64-d55dd53e0ebc.png)

![image](https://user-images.githubusercontent.com/33255536/60729978-9a962800-9f76-11e9-993c-aef516213a08.png)

These are the same damage spot from different angles, showing it cut into the structure.
![image](https://user-images.githubusercontent.com/33255536/60730004-abdf3480-9f76-11e9-9999-b4a6a43cf2b2.png)
![image](https://user-images.githubusercontent.com/33255536/60730027-be596e00-9f76-11e9-97ff-75603433489a.png)
![image](https://user-images.githubusercontent.com/33255536/60730052-d16c3e00-9f76-11e9-88a4-d74b1927c083.png)

So how it works is by using a coloured map for what shader goes where, you can restrict what shows up at what levels of damage, but telling the shader it can only show up when a specific colour appears.

So example from what i understand:
map decal is multicoloured
when damage on a spot is first placed the decal is 10% Opaque and told to be the darkest of each colour.
as more damage is applied to the area the area gets more saturated and more Opaque
-Say anything from transparent 0% opaque to 100% opaque black = burn mark shader
-anything dark green to green 100% opaque = glowing hot metal shader
-anything blue = light damage shader
-anything from red = bad damage hole shader

it can be as simple as a black and white shader map. and a laser just draws a white line through the black on the surface of a block. and unity just recognises the black on that type of map as "transparent" and anything not black is the damage shader. 

More colours on the damage map, just means more complex visuals using multiple shaders.

**Comment by JRL101** [comment]
This is probably more useful than me explaining :D 
https://assetstore.unity.com/packages/vfx/shaders/damage-fx-102179

https://youtu.be/911SH5KfTAQ

**Comment by tsunamayo** [comment]
We have some damage decal now but they need more variety. Thanks
