### ISSUE TITLE
The invisible blocks bug has returned

### ISSUE THREAD

**Issue by Xxxsquidlover101xxX** [tsunamayo/Starship-EVO#1349]
### Short Description of the issue:
So a while ago I reported a bug about how every block i tried to place kept dissapearing, and it was fixed, it has returned and is harder to fix
...

### Steps to reproduce the issue:
Well, place a block and it will appear to be invisble, this time there is no flash at all, I tried using the F3 menu but it doesn't work
...

### Environment
- Skywanderers version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

https://cdn.discordapp.com/attachments/342383722185883648/599203494930677801/unknown.png

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\
C:\Users\Danny\AppData\LocalLow\TsunamayoCorp\Skywanderers\output_log.txt

**Comment by Xxxsquidlover101xxX** [comment]
Also the graphics card is an GTX 660

**Comment by tsunamayo** [comment]
Hi, did you see previous block from existing ships, or does it concerns everything? Also could you please send the log file?
Thanks

**Comment by Xxxsquidlover101xxX** [comment]
I've never used github before but if you take the link i put in the end and paste it in your own browser it should show up

**Comment by tsunamayo** [comment]
@Xxxsquidlover101xxX I am not sure, does it happens on recent build? Thanks

**Comment by Vicomt** [comment]
OK, we've been experiencing this. it feels like the geometry updates and render updates get put in separate queues, and while the geometry update queue is getting serviced and cleared, the render update queue slowly gets bogged down, as if it wasn't clearing. sorry if I'm using incorrect terms, but that's how my programmer brain sees it ;)

**Comment by tsunamayo** [comment]
@Vicomt, do you get massive lag and an unremovable block after?
Yes those are two separate queue. In my planned refactoring it will be instaneous, taking care of that bug naturally.
Is there more people on discord with this, and do you get that often? Also what is your CPU>
Thanks

**Comment by Vicomt** [comment]
Sorry for the late reply.
the timeline we see is:

1. Initially blocks are placed normally, this lasts for approx 20 mins (but can be shorter depending on how fast we're trying to build)
2. Suddenly, (no known trigger) one placement will take a couple of seconds to show visibly, but the collision outline will update and no further block can be placed in the same location
3. Visible display after this point becomes slightly more laggy, then considerably more laggy, until it stops completely.

it is made worse (happens faster) when both the client and server players are actively placing blocks,  or (possibly) rapidly changing multiple chunks.

CPU details for the server:
![image](https://user-images.githubusercontent.com/7197427/81459187-81619780-9196-11ea-929d-d1358b276c3a.png)

Client is similar

GPU is Geforce 1070

**Comment by Garrett-C** [comment]
I too have been seeing this bug a bit, it seems that it gets worse over time. From my experience you tend to be fine for a while, after a short while they become invisible but become visible after a bit and the time between placement and visibility increases over time.

**Comment by Vicomt** [comment]
Please Please Please can we have this bug prioritised? the more detail we use, the faster this breaks us, and doing multi-minute reloads every 15 minutes is killing our drive to build. Multiplayer stability is going to be really important for a good steam release.

**Comment by tsunamayo** [comment]
@Vicomt are you Oojimaflip from youtube? So I fixed on such invisible block issue, but I cant be certain it is the same as yours. It was the symmetry delete one. It will be in patch 20w24b, so if you tell me if that fixes the main one you were experiencing! Thanks a lot!

**Comment by Garrett-C** [comment]
> @Vicomt are you Oojimaflip from youtube? So I fixed on such invisible block issue, but I cant be certain it is the same as yours. It was the symmetry delete one. It will be in patch 20w24b, so if you tell me if that fixes the main one you were experiencing! Thanks a lot!

I think the bug being discussed here is related to placement not deleting. To me it seems to be an issue related to memory as it tends to get worse over time.

**Comment by tsunamayo** [comment]
@Garrett-C yes this is also my fear, although what I just fixed could also explain the bug. If that was something you had all the time then we will see! The build is up. I just showed your obsidian class on the channel btw ;)

**Comment by Garrett-C** [comment]
> @Garrett-C yes this is also my fear, although what I just fixed could also explain the bug. If that was something you had all the time then we will see! The build is up. I just showed your obsidian class on the channel btw ;)

Yeah I will definitely try it out a bit to see if there is any changes. 

I noticed lol. Glad to see it ran ok for you there. Loved the technical explanation for how it all works.
