### ISSUE TITLE
New build bugs 7/17/19

### ISSUE THREAD

**Issue by ADDexia** [tsunamayo/Starship-EVO#1358]
alright I'm not much for bug reports but this is slightly annoying and goes against what tsuna was going for in his new video/ update. 

1)the canopies do not work properly right now, when on a hinge the hinge wont work with an elongated end canopy piece though it will work if the piece is widened. After a long time of finicky placement I did manage to place an elongated end piece on the hinge but when I use the hinge it only moves slightly and then just stops for no reason, there is nothing blocking it from moving but it refuses to work. speaking of finicky placement, 

2)I've also been having trouble elongating the end piece canopy on just regular hull bricks, it doesn't even have a ghost image of me stretching it, it just doesn't do anything though it still widens. 

3)The smaller hinge also cannot use larger bricks. 

4)The newer rails have a strange bug as well, two canopy pieces can't touch each other apparently. For example when putting a single canopy piece, not the end piece the main piece, on the rail it cannot slide flush with an end piece. It has this strange invisible wall like gap though if you put bricks in front of the end piece it will get past the invisible barrier and sit flush against the bricks. 

5)The thin rail also now doesn't work though that may be due to the update trying to change over to the newer pieces but it makes using rails on smaller ships difficult.

**Comment by tsunamayo** [comment]
5) Thin rail will be removed 3) is also normal as I explained in the video
Could you please send me your blueprint so I can investigate for 1, 2, and 4? Or send a screenshot of how you build your canopy as it will be hard to investigate otherwise. Thanks!

**Comment by tsunamayo** [comment]
I might have fix an issue concerning 2), but I am not sure of your test case at first.

**Comment by ADDexia** [comment]
Ok so I just saw your replies and I attempted to recreate all the bugs on a single flat surface but it was finicky to begin with so they as accurate as I can make. how do i send you the BP though? I'm sorry but I'm not super tech savvy.

**Comment by tsunamayo** [comment]
I think I fixed 4) also! Maybe be it is same issue as 2) but I am not sure... 1) seems like a close collision issue. To send me your ship you need to spawn a drone with F5. Then build a brick so the drone understand on which entity you are building, then press F when looking at the drone to activate it, then press export on the top to generate the blueprint. 

It will be under:
`%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\Save_Data\Blueprints`

I think you will have to zip it. Thanks!

**Comment by ADDexia** [comment]
[Bug Examples.zip](https://github.com/tsunamayo/Skywanderers/files/3413005/Bug.Examples.zip)

**Comment by ADDexia** [comment]
Also I found something that may be helpful for issue 2. It seems it can stretch when you first pull it out but it will not stretch when you rotate it.

**Comment by tsunamayo** [comment]
Collisions should have been improved in newest version. Thanks!
