### ISSUE TITLE
Infinite Loading Screen after character creation/selection

### ISSUE THREAD

**Issue by Mantis2k19** [tsunamayo/Starship-EVO#1399]
### Short Description of the issue:
Game lags up computer but never finishes loading after selecting a character or creating a new character.
Have quit and restarted, have deleted all files in "Save data" folder, have verified game files, have uninstalled and reinstalled, issue persists.
-however, when savedata copies were sent to another player, the game opened for them. When the files were sent back to me (after uninstalling/reinstalling and verifying game files), the game still did not finish opening.

It may be a Unity bug. I don't know if this is important, but I noticed that when I opened TaskManager, the Unity Crash Handler was operating
...

### Steps to reproduce the issue:

...

### Environment
- Skywanderers version: current
- Graphics Card: Nvidia GeForce GTX650
[Save_Data.zip](https://github.com/tsunamayo/Skywanderers/files/3454188/Save_Data.zip)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3454189/output_log.txt)

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by Mantis2k19** [comment]
Should have mentioned above but forgot: The issue with the game lagging when starting has only occurred since the game stopped working. Starting a game on SkyWanderers never lagged up my computer before

**Comment by Gambit06** [comment]
the bug can be corrected by suppression of player data. Thx Propeach.
But i don't think is a good way to correct it definitely.

**Comment by tsunamayo** [comment]
Yes I need to fix this bug, I will have a look at it. Thanks for the save data! Cheers
