### ISSUE TITLE
[19w31a] Multiplayer is broken

### ISSUE THREAD

**Issue by Vicomt** [tsunamayo/Starship-EVO#1405]
### Short Description of the issue:
Multiplayer is broken

### Steps to reproduce the issue:
Host creates new empty game
Client joins host
Host spawns a ship - neither host nor client see it
game is saved, client and host exit and restart

game is loaded by host, ship is visible and modifiable
client joins, ship is not visible or modifiable

host creates a new ship, this is visible to both client and host
host modification of ship works
client modification of ship is not visible to host and result in total loss of ability to modify ship by host, however this modification by the host was visible to the client.

### Environment
- Skywanderers version: 19w31a
- Graphics Card: GTX 970
- Windows 7 host and client

### Additional information:
Client Log
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3464054/output_log.txt)

**Comment by oojimaflip** [comment]
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3464066/output_log.txt)
output log from HOST machine

**Comment by tsunamayo** [comment]
Thanks for trying out multi - yes it needs a lot more work from my side, I will keep you posted  when I have made progress. Thanks!
