### ISSUE TITLE
[Suggestion] Block axis rotation

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#1409]
### Short Description of the issue:
It's good to see axis rotation back but personally I'd like to see it return to it's own hotkey as having to press the rotate keys multiple times to get the right rotation is quite bothersome
...

**Comment by tsunamayo** [comment]
You have a rotate backward key (should be at E) - if that make it go faster...

**Comment by Aiwii** [comment]
The rotate backward key is indeed useful but in my opinion, it doesn't help with speed. When I'm rotating blocks I usually spam Q or E until its the way I want it. This worked well when it was only one axis rotation but now that some blocks can rotate in two axis spamming the rotate key can make rotating annoying as the block continues to rotate without reaching the desired position. I guess what I'm trying to say is just having to rotate a block 4 times is better than 8 with the new rotation system. Xerma's suggestion to have a hotkey control axis rotation would be pretty nice.
