### ISSUE TITLE
Canopy block collision issue on rail.

### ISSUE THREAD

**Issue by AsageSoftworks** [tsunamayo/Starship-EVO#1410]
### Short Description of the issue:
Chair block stops the movement of a canopy on rails
...

### Steps to reproduce the issue:
place chair. Place canopy on rails that pass through the chair blocks grid space. click rail.
...

### Environment
- Skywanderers version: Newest
- Graphics Card: GTX 1070 Ti

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![20190806170428_1](https://user-images.githubusercontent.com/43458562/62580903-2993aa00-b86d-11e9-82fd-f0818a5a158e.jpg)
![20190806170432_1](https://user-images.githubusercontent.com/43458562/62580904-2a2c4080-b86d-11e9-9ac8-a9e4e9051ed6.jpg)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by ZachZent** [comment]
Yea, this has been know for quite a bit now. It isn't the rails or anything, it is that the canopy doesn't have the right collisions. Right now, it is more like a block rather then the canopy it should be. Until Tsuna fixes it, there is nothing that can be done.

Actually, there is one thing. If you put the seat on a separate slider, the canopy will close. It is a little cheaty, but at least you can finish your cockpit

**Comment by tsunamayo** [comment]
Yes it is because of the collision algo. Unfortunately it might still be bugged afterwards in the case of 1m wide canopy (large like yours should be okay...) Thanks

**Comment by tsunamayo** [comment]
This is fixed in later builds. Thanks!
