### ISSUE TITLE
[Question] How many stars are there?

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#1412]
I know the galaxy is going to be revamped and it doesn't mean that much right now, but I wonder if I can get a number of stars in the current galaxy. At least a general number. And if this number is going to be greatly changed or the possible future star count. Thanks

**Comment by tsunamayo** [comment]
Hah good question. For now I dont really know the answer as everything is generated on the fly depending on your cluster and cluster density. I would have to code something to know the exact answer.
But in an upcoming refactor I will pregenerate them to have a faster holomap (and simplier / less buggy). And yes I will drastically reduce the number, I want to move away from the 300 billions star a la Elite (dont really make sense for the game), and have something closer to a 100 - 1 million maybe. I will do some testing to see what work best. 
Cheers

**Comment by ZachZent** [comment]
Just a clarification, you said 100 - 1 million. Did you mean a star count between 100,000 and 1 million, 100 and 1 million (basically anything up to 1 million) or the option to chose the number of stars in the galaxy for the server which can be anywhere between 100 and 1 million (which you should defiantly do in time)

**Comment by tsunamayo** [comment]
No I wont do a setting, the goal is to leverage on having a manageable number of stars to cache things. It was 100M - 1M, but honestly  I dont commit on anything, it will be large but not 1-1 scale with the milky way. Why are you interested in that btw? Cheers

**Comment by ZachZent** [comment]
As for the star count, I am interested in part for an idea I am coming up with where the general count of the stars would be helpful. I was also curious since there is no solid answer thus far and the size of the galaxy is a semi-regular question asked by new players. As for the ability to change the galaxy size...

Regardless of 1 million or 100 million (1 million is better), this is quite a lot in the area of "uncountable." Because of this, any sort of multiplayer will be co-op focused and any sort of competitive server would be much more difficult to manage unless artificially enforced. Hear me out.

For a galaxy size that large, there is no way two people would run into each other at random. This means if two people are in the same server and are at a distance away from one another and not in communication, they won’t meet. There is no reason for them to be in the same server and risk the inevitable lag. Think about Minecraft survival servers. Everyone goes in their direction at quite a distance. If you are alone, you will stay alone. Servers become a bubble of humans near the spawn point and a vast nothing past it which is not the best way to play a game.

Now for the competitive part especially concerning any sort of mass pvp or/and empire gameplay. I know isn’t the main goal, but this sort of gameplay is inevitable and a good number people will want to play this way. Not everyone cares that much about exploration. Getting down to basics, two groups controlling several systems. Since the galaxy is so large, any sort of competition between the two wish means they will have to be very close to each other. Get say 100 stars away and there is no real need to the two groups to interact turning it into just larger co-op and have the same issues as before. Again with the Minecraft survival server comparison, competitive base building and defense is just not realistic as everyone is so spread out. Even if these two groups are next to each other, they can just expand into the null rather than fight each other.

The fact is some multiplayer servers will want the option to limit the number of stars down past the uncountable, say to 1,000 stars to allow this sort of competitive game with factions and groups that have a chance on meeting out of the blue. Or at least not having to cross the entire galaxy. Conquest will mean something when you don’t have the entire galaxy at your disposal and will actually need to take others territory.

Talking about it in the Discord, we came up with a solution that allows servers to choose the size of their game without changing the map. Allow server owners to designate a boarder. This boarder can be anywhere in the map by selected a star system and designating a radius. Any system in that radius can be visited, but anything outside it cannot be visited. This gives server owners the advantage to tailor their server to the style of game they prefer without needing to create an entire new galaxy. The starscape stays the same.

**Comment by ZachZent** [comment]
I know it has been about three weeks since I posted, but looking back it may be a bit confusing and I don't want it to be confusing for an issue as important as this. So I made a video explanation with a game called Galimulator. I hope this visual explains the problems that come with "uncountable" stars and its effects on competitive gameplay and how the solution stated in my last post's last paragraph will allow for competitive gameplay without requiring smaller galaxy sizes

https://youtu.be/KnY9lSoMnKg

**Comment by ZachZent** [comment]
Even though the last post the made three weeks ago, I felt that is could be a little confusing especially for a matter as important as this. So I made a video explanation using a game called Galimulator which should visually explain the issues with an "uncountable" star count and competitive gameplay, the solution, and how the solution pans out compared to the large galaxy size

**Comment by tsunamayo** [comment]
@ZachZent Hi! So there is 1.102.245 stars currently. I am browsing through older issues!
