### ISSUE TITLE
[Suggestion] Make the pilot chair's hitbox conform to the shape of the chair.

### ISSUE THREAD

**Issue by Tomatart** [tsunamayo/Starship-EVO#1414]
### Short Description of the issue:
The canopy blocks cannot slide over a chair due to the hitbox of the chair, even though visually there is no collision.
...

### Steps to reproduce the issue:

...

### Environment
- Skywanderers version: 19w31b
- Graphics Card: GTX 1070

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Yes hitbox are problematic, I have started working on a refactoring though, that should be better (not 100% though - as the goal is actually reduce lag...) Cheers

**Comment by tsunamayo** [comment]
This is working in latest builds, cheers
