### ISSUE TITLE
[Sugestion] FTL travel and dangers

### ISSUE THREAD

**Issue by MrSquid1** [tsunamayo/Starship-EVO#1415]
So I got an idea the other day on how FTL interstellar travel could be handled, It's concept is that instead of having a maximun range for a FTL drive, the drive has a safety zone, if you don't exceed it, you're fine, however exceeding that safety zone, will cause enemies to appear behind you, as for the aesthetics or what these are, it doesn't matter, but the game would have a multiplier depending un how much you have exceeded your safety limit to calculate the amount of enemies that would spawn

**Comment by MrSquid1** [comment]
As for what these enemies are, it can be anything, AI traps, pirates, even energy aliens, space whales or cosmic horrors, another aditional idea that could be onto here would be a secret boss you can spawn by attempting to jump through more than 75% of the galaxy's diameter.

**Comment by ultrak2k** [comment]
Hold on if you wanted long distance escape only to warp into more enemies wouldn’t that be against the point, and if someone didn’t want to fight they would just wait it, making it pointless to ever even add enemies?

**Comment by tsunamayo** [comment]
Funny suggestion - not sure if I would implement it like that though, as why a player would then go over range? Cheers
