### ISSUE TITLE
[Suggestion] Further stretch options for "Small Bevel" brick

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#1418]
I find it strange that this brick only stretches in one direction at the moment when it has such great potential.
This is my suggestion
![image](https://user-images.githubusercontent.com/27857711/64793556-25952f00-d573-11e9-809a-3384fc8ec337.png)
You can see the main advantage of these new dimensions in the middle example, it features a very gentle slope even at 0.25m thickness which is something we currently can't achieve any other way.
In each example, the sides remain 0.125m thickness and do not stretch

**Comment by tsunamayo** [comment]
I see - I will check if I can make that. Cheers
