### ISSUE TITLE
[Suggestion] "Damage" tool (distant future)

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#1426]
With the new damage model and more importantly the holes, it is clear of the aesthetic possibilities that can come from it. Damaged parts in ships can look really good. I was thinking what if in creative mode, there would be a tool to intentionally create these holes without any damage to the ship. This can be for RP purposes before ships are transferred into survival mode or in the submitted ships for KS rewards. Pirate ships with “pre-damage” without having the ships be at a disadvantage or corporation stations that are a bit run down. Again, this is for creative mode only. You won’t have to shoot your own ship to get the aesthetic results you want. An issue I had before the old graphics update where blocks “cracked.” Every time I wanted to add a worn look to a block, I had to make a mini-ship to shoot it.

https://cdn.discordapp.com/attachments/241015944665759764/475800535006707713/unknown.png
My old entry for the “new beginnings” contest. You can see on the walls a bit of damage giving it a worn look. There aren’t any new ships with the aesthetic just yet but when I see one, I will post it.

**Comment by tsunamayo** [comment]
I love the vibe and feel of your screenshot! If you had a handheld weapon that would be better for you? Why having to shoot your own ship is a bad thing? (seems to me the most logical things to do if you want a damaged look). I would prefer to avoid making additional tools unless strictly necessary. Cheers

**Comment by ZachZent** [comment]
Granted I was not thinking of a handheld weapon which would defiantly be easier then what I had to do above and what you would have to do now. Build a "ship" and shoot. As for the tool I totally agree to limit them to essentials. I was thinking more the "hidden" toolbar where special items are. Like the command block in MC. For creative mode only that will allow you to make the effect you want, exactly where you want, and to what level of damage you want WITHOUT taking off health from your ships as I would assume a handheld laser would. This is strictly a creative tool, mostly for the KS builders and creative builders in the future looking to add an atmosphere of worn bulkheads and damage. Would be annoying to want to add that extra level of detail and be penalized for it with essentially pre-fight ship hp damage.
