### ISSUE TITLE
Ship isn't fully rendered when the player loads in

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#1438]
### Short Description of the issue:
Just an odd scenario where the player loads in before the ship(s) are done rendering fully
...

### Steps to reproduce the issue:
Load into the game
...

### Environment
- Skywanderers version: 19w38a
- Graphics Card: GTX 970

![20190920224655_1](https://user-images.githubusercontent.com/32974671/65367557-cd0c0480-dbf8-11e9-8a0c-64950a9528cd.jpg)
![20190920224656_1](https://user-images.githubusercontent.com/32974671/65367559-ced5c800-dbf8-11e9-9936-d138af12591c.jpg)
![20190920224657_1](https://user-images.githubusercontent.com/32974671/65367560-d006f500-dbf8-11e9-8583-53a9315a3b11.jpg)
![20190920224658_1](https://user-images.githubusercontent.com/32974671/65367561-d1382200-dbf8-11e9-9ca0-170002b486e1.jpg)

**Comment by tsunamayo** [comment]
Hum, does this build takes a long time to load (I guess so by the size of it)? Could you please send me the blueprint so I can have a look at it? Thanks!

**Comment by Xerma** [comment]
It takes a fair amount of time but not horribly long, 640 KB file size. This is the "Mini Core Ship 6" as packaged in a zip file in #1457

**Comment by tsunamayo** [comment]
I am still getting this bug but in multiplayer.
