### ISSUE TITLE
Placing lights and breaking them leaves odd little "artifacts"

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#1440]
### Short Description of the issue:
After placing lights on blocks and then removing them, it seems to leave some very peculiar artifacts in the blocks that the lights were originally place on. These lights were place along a mirror plane and overlapped.
...

### Environment
- Skywanderers version: 19w38a
- Graphics Card: GTX 970

![20190920230753_1](https://user-images.githubusercontent.com/32974671/65367735-cdf26580-dbfb-11e9-9aea-9b4042ab8c0c.jpg)
![20190920230808_1](https://user-images.githubusercontent.com/32974671/65367736-cfbc2900-dbfb-11e9-8e8b-4b1357cbfa1e.jpg)

**Comment by Xerma** [comment]
Saving and reloading removes these artifacts

**Comment by tsunamayo** [comment]
This should be fixed in current versions. Thanks!
