### ISSUE TITLE
[Suggestion] Player rotation and somehow a better alignment 

### ISSUE THREAD

**Issue by ultrak2k** [tsunamayo/Starship-EVO#1445]
Currently we have the issue of players only being upright making it a pain to deal with building undersides of ships or getting into places to do things, it would be nice if you could rotate your player on Atleast another axis, like the left and right one. Also alligning by going through menus is a pain in the ass, I don’t know about better solutions but there must be a way

**Comment by tsunamayo** [comment]
You mean aligning with the middle mouse button wheel? Yes I want to refactor this, the idea for a lack of a better one is to have a "thruster tool", that you equip, and that will give you roll with q/e key, and will pitch you when you look up/down.
What I dont want to have is a system where you have to constantly re-align yourself like in Space-Engineer - makes me feel nauseous. 99% of the time you want to be locked in. 
Thanks

**Comment by tsunamayo** [comment]
okay we now have 6dof for when you build under the ship. tx
