### ISSUE TITLE
Data Screen won't display data

### ISSUE THREAD

**Issue by GiinTak** [tsunamayo/Starship-EVO#145]
Linking the Data Screen to a rotor won't display anything. Attempting to following tutorial "Logic 3." Only prebuilt data screen works.

SpookySam on discord checked on theirs, doesn't work for them, either. I've not gotten much further to find out anything else it can link to.

-Giin

**Comment by tsunamayo** [comment]
It is working on my side, could you please me give more details on the step you followed?
ie blocks / bricks useds (tried with the rotor and went fine). Cheers
