### ISSUE TITLE
Builds not loading properly

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#1457]
### Short Description of the issue:
After scrolling through my log file I see that the game is saying it loaded some other builds I tried to load in yesterday but they would appear then disappear or wouldn't appear at all. Builds also only sometimes stay spawned in when using the drone.
...

### Environment
- Skywanderers version: 19w38b
- Graphics Card: GTX 970

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3660235/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, could you please send me your blueprint so I can check whats wrong with them? cheers

**Comment by Xerma** [comment]
[Ships.zip](https://github.com/tsunamayo/Skywanderers/files/3683472/Ships.zip)

I tried spawning "Mini Core Ship 6" once, didn't spawn but tried again later and it spawned

**Comment by tsunamayo** [comment]
I spawned with no issue, it is just taking forever to load (long time issue I need to address for large ship)... not sure if it was that or something else...

**Comment by Xerma** [comment]
Well I just tried spawning in another "Curvy Ship" and it seems I've been sent to another dimension comprised solely of those ships I attempted to spawn in other saved sessions

![20191002190655_1](https://user-images.githubusercontent.com/32974671/66090220-12f59080-e548-11e9-8d5a-9766604ecade.jpg)
![20191002190712_1](https://user-images.githubusercontent.com/32974671/66090222-14bf5400-e548-11e9-99e4-dc96a438dc28.jpg)

In the last picture it looks as if it's clumping them together

**Comment by Xerma** [comment]
Looks as if the Curvy Ship has old engines and the AAT has old custom paints, could those be the issues?

**Comment by tsunamayo** [comment]
I dont think it should be the issue.
Not sure to understand your test case though. You spawned a ship and then you were teleported to another place? Thanks
