### ISSUE TITLE
[Suggestion] Add a rectangular guide around each sticker

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#1459]
### The suggestion:
I think it would be more convenient if people could see the drag outline around stickers so they could line sticker designs up easier.

![20190929233758_1](https://user-images.githubusercontent.com/32974671/65850130-2835a980-e313-11e9-8b70-d3afe910947e.png)

...

**Comment by tsunamayo** [comment]
Also for circle i think having them rescaling with a fixed center would be a lot easier to deal with, what do you think? Thanks

**Comment by Xerma** [comment]
That would also be very beneficial and would make them much easier to use

**Comment by tsunamayo** [comment]
We have this since a while! Cheers
