### ISSUE TITLE
[BUG] Markings and Decal error on slopes

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#1469]
### Short Description of the issue:
As you can see in the gifs, decals and markings sometimes "float" about slopes that you place them on. The Vent Holes decal can clearly be seen conforming to a cube rather than the triangular slope brick that it is placed on. I also sometimes find that they are impossible to break without reloading the blueprint, I try to break the vent decal at the end of the gif to no avail.
![Skywanderers Sticker Bug](https://user-images.githubusercontent.com/27857711/66495219-ce6e7580-eab0-11e9-9679-b5787f049c22.gif)
![Skywanderers Decal Bug](https://user-images.githubusercontent.com/27857711/66495220-ce6e7580-eab0-11e9-89f3-6aff90952e18.gif)
I've included the blueprint so you can get hands on quickly
[A-Wing decal-marking bug showcase - ProPeach.zip](https://github.com/tsunamayo/Skywanderers/files/3708145/A-Wing.decal-marking.bug.showcase.-.ProPeach.zip)

PS - Sorry about the canopy clipping! It's only there until the brick glass options are expanded :)

### Steps to reproduce the issue:
Place decals and markings on a slope/tetra, then move around and look at it from the edge. Alternatively, load in the attached blueprint and use that as a reference

### Environment
- Skywanderers version: 19w40b
- Graphics Card: GTX 1050M

**Comment by tsunamayo** [comment]
This should be fixed for 20w29c, but some of your decal will appears cutted, you will need to replace them... Cheers
