### ISSUE TITLE
[BUG] Stickers on child entities also show on nearby parent entity [19w40b]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#1485]
### Short Description of the issue:
If a sticker is placed on a child entity, and that area of the entity then moves next to the parent entity, the sticker is visible moving across the parent entity.

### Steps to reproduce the issue:
Place something like a slider, place stickers on it, then place bricks on the parent entity over the part with stickers. The stickers should now be visible on the parent entity as well.

### Environment
- Skywanderers version: 19w40b
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
The hole stickers are on a sliding child entity here:
![20191013140435_1](https://user-images.githubusercontent.com/33041786/66720443-6ecedd80-edc2-11e9-9a90-8558cd6d8483.jpg)

When the sliding child entity is retracted, the stickers are visible sliding along the floor of the parent entity:
![20191013140441_1](https://user-images.githubusercontent.com/33041786/66720445-71c9ce00-edc2-11e9-9215-53cda10aa4fe.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3722165/output_log.txt)

**Comment by tsunamayo** [comment]
Yes this is a known issue linked to the new tech :( ... Not sure to have a clean way to fix it anytime soon, so unfortunately I put that in low priority... Thanks

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin The new tech is there, issue fixed in 20w29c. Thanks!
