### ISSUE TITLE
[BUG] Ships forgetting which way is "forward" [19w40b]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#1492]
### Short Description of the issue:
Sometimes the ship will "forget" what its forward orientation is and change it. The bug seems to persist on save/reload, but deleting and replacing the control yoke fixes it.

### Steps to reproduce the issue:
Not yet known, will update when I figure that out.

### Environment
- Skywanderers version: 19w40b
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
This is the normal forward direction of this ship:
![20191014225201_1](https://user-images.githubusercontent.com/33041786/66799054-45eb3d00-eed5-11e9-9510-de711bfaab41.jpg)

And this is what it thinks "forward" is after the bug occurs.
![20191014224608_1](https://user-images.githubusercontent.com/33041786/66798779-b6458e80-eed4-11e9-93c6-d00d081538e4.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3727305/output_log.txt)

**Comment by tsunamayo** [comment]
Okay, is this something still happening? Thanks

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin do you still get this? Thanks

**Comment by tsunamayo** [comment]
I guess it is no longer applicable? Thanks
