### ISSUE TITLE
[Bug] Inconsistent Sicker Hierarchy 

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#1496]
### Short Description of the issue:
Stickers do not behave as you'd expect to when it comes to layering. Sometimes stickers placed over others show on top as you'd expect, while sometimes they don't
https://i.imgur.com/mqJW8VH.gif

They also have an odd "painted over" look that I'd recommend removing if possible, I think players will want to have nice crisp colours rather than this faded look
![image](https://user-images.githubusercontent.com/27857711/67110538-e3db5200-f1ca-11e9-89c7-0a0785c88aa0.png)

### Steps to reproduce the issue:
Play around with different coloured stickers, placing one overlapping the other and see the different results

### Environment
- Skywanderers version: 19w40b
- Graphics Card: GTX 1050M

**Comment by Xerma** [comment]
I get this all of the time and it can be pretty frustrating when you have a design in mind but then it just refuses to work because of this. Newly placed stickers should always get placed on top of any and all previous stickers

**Comment by tsunamayo** [comment]
Yes this is a know issue when you are having design that cross chunk. I will keep you posted when I fix this. For the faded look I am not sure to understand, I do see some faded red near the white, is this what you are referring to? If yes what paint did you used, the same red?
Cheers

**Comment by ProPeach** [comment]
Glad to hear it!
Regarding the faded look that is what I mean, it look like the game has blends the two colours rather than rendered one on top of the other. That colour occurs when two stickers, one white one red, are placed on top of eachother and the bug happens.

**Comment by tsunamayo** [comment]
Fixed for 20w29a, the new tech is here. Thanks!

**Comment by ProPeach** [comment]
Thanks so much for this! : )

**Comment by tsunamayo** [comment]
@ProPeach btw do you have any trouble on latest experimental build? Thanks
