### ISSUE TITLE
Small hinge doesn't fully close

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#1497]
### Short Description of the issue:
When using the small hinge to make this curved door, it leaves a small gap instead of closing the full way.
...

### Environment
- Skywanderers version: 19w40b
- Graphics Card: GTX 970

### Additional information:
![20191023020816_1](https://user-images.githubusercontent.com/32974671/67366993-3190eb00-f53a-11e9-8a93-8e6f6b24afcb.jpg)
![20191023021011_1](https://user-images.githubusercontent.com/32974671/67367029-47061500-f53a-11e9-9697-7b77c761b59e.jpg)

**Comment by Lsutehall** [comment]
I've seen this as well, also on small hinges and possibly large rails as well.

When I checked the angle it stopped at (in the hinge's dialogue) it changed with every activation, making me think this is related to the collision model.

**Comment by tsunamayo** [comment]
Yes it seems to be collision related, if you can send me your blueprint. Right now it will stop in the middle of the frame, which might not be at the full closed position. Thanks!

**Comment by Xerma** [comment]
[Scimitar 1.zip](https://github.com/tsunamayo/Skywanderers/files/3775620/Scimitar.1.zip)

**Comment by tsunamayo** [comment]
@Xerma so it was another example of the removed brick lacking collision shape. Thanks
