### ISSUE TITLE
Awkward alignment issue

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#1506]
### Short Description of the issue:
I'm not too sure how to describe this one but sometimes the player just removes itself from alignment from it's current alignment grid. It doesn't move the player all too much but it's most certainly noticeable
...

### Environment
- Skywanderers version: 19w43a
- Graphics Card: GTX 970

**Comment by ExodistSKY1** [comment]
I have been noticing this as well

**Comment by tsunamayo** [comment]
Does this still happens after the locomotion update? Thanks
