### ISSUE TITLE
Timer issues when coupled to guns [19w43a]

### ISSUE THREAD

**Issue by Lsutehall** [tsunamayo/Starship-EVO#1509]
### Short Description of the issue:

Looks like timers aren't always activating when connected to laser units.

### Steps to reproduce the issue:

Link a button or hotkey to a series of timers, and then on to laser units. Press fire repeatedly: sometimes all the lasers fire, but more often only 2 shots fire for one press. 

In the example below i've linked a hotkey to a laser and then 3 times, set to increments of 0.3, 0.6 and 0.9s in order to ripple fire 4 laser units, but when firing often it only produces 2 shots.

### Environment
- Skywanderers version: 19w43a
- Graphics Card: GTX 1060

### Additional information:

![20191028175820_1](https://user-images.githubusercontent.com/40872394/67704587-498ac380-f9ad-11e9-9047-a7a1eeae381e.jpg)

![20191028175830_1](https://user-images.githubusercontent.com/40872394/67704609-58717600-f9ad-11e9-8cfa-6f140bd9c440.jpg)

[multi turret test.zip](https://github.com/tsunamayo/Skywanderers/files/3780027/multi.turret.test.zip)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3780030/output_log.txt)

**Comment by ProPeach** [comment]
I've also noticed that timers sometimes delay a signal for much longer than the value you give them. A given value of 0.1 seconds turns into closer to a 0.5 second delay

**Comment by tsunamayo** [comment]
Should be fixed!
