### ISSUE TITLE
Texture bugs

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Starship-EVO#1510]
### Short Description of the issue:
Just a compilation of some texture bugs I have been finding. These include some bricks plus some that are sticker based. 

### Environment
- Skywanderers version: 19w43a
- Graphics Card: 

Logic gates:
![image](https://user-images.githubusercontent.com/43644633/67815506-03159180-fa9f-11e9-9593-0093b55e6a47.png)

Laser (Soon to be remodelled so not a massive one)
![image](https://user-images.githubusercontent.com/43644633/67815634-630c3800-fa9f-11e9-9e0d-e695715d7351.png)

Stickers on slopes:

(This one changes based on what angle you are at)
![image](https://user-images.githubusercontent.com/43644633/67815669-7cad7f80-fa9f-11e9-9ec1-df092dde545c.png)
![image](https://user-images.githubusercontent.com/43644633/67815687-846d2400-fa9f-11e9-8da7-61076d7b8d63.png)
![image](https://user-images.githubusercontent.com/43644633/67815692-8931d800-fa9f-11e9-9197-213b057dfc87.png)

**Comment by ProPeach** [comment]
That sticker bug looks like the same one as #1469, it's like the sticker is suspended on top of an invisible box

**Comment by Garrett-C** [comment]
You are right it does look to be a similar bug. I hadn’t seen your report and just added it because I was reporting some other texture weirdness at the same time so figured I would get them all in.

**Comment by ProPeach** [comment]
Awesome, just wanted to make sure these were linked for ease of identification

**Comment by tsunamayo** [comment]
Hi! Do you reproduce the first one consistently? Is it appearing on a specific ship? If you if you could send me the blueprint. Thanks a lot!

**Comment by ProPeach** [comment]
The sticker bug shown happens to me on all ships, you can reproduce it by placing a sticker on a hepta or tetra and moving the camera around. I find it's easier to see if you look sideways at the sticker.

There's a blueprint in the #1469 thread with a gif of the issue on that blueprint if you'd like something ready made

**Comment by Garrett-C** [comment]
[VCX 100 For Tsuna.zip](https://github.com/tsunamayo/Skywanderers/files/3894623/VCX.100.For.Tsuna.zip)
Some of them are not 100% consistent. Here is a copy of the blueprint I was using. I noticed that when placing the logic gates on the floor in the middle corridor they sometimes do it. Still not 100% of the time but it does happen frequently enough.

**Comment by tsunamayo** [comment]
@Garrett-C I just cant find the place where you put the stuff like on the first screenshot. I have found some gate but they were fine. Thanks
