### ISSUE TITLE
[Suggestion] Modular Seats

### ISSUE THREAD

**Issue by PopkaAkula** [tsunamayo/Starship-EVO#1514]
### **Short Description of the suggestion:**

With the old rendition of skywanderers we used to have the old seats that could be customized to a certain extent. But now with the new seats, it is virtually impossible to customize them in any way. It would be great if we could get that kind customization, but in the new style.

Attached below is a methodically drawn mspaint diagram of how the seats might look:
![chare](https://user-images.githubusercontent.com/37738021/68118640-c6172800-ff00-11e9-8831-d59f2fd0cfda.png)

Just a blank seat that we can put bricks on would be great.

**Comment by ThatFungiNub** [comment]
I approve, I do miss the old chairs. Having the freedom to make custom chairs has always been one of the most fun features

**Comment by ZachZent** [comment]
It is possible to make good looking chairs, but it is really hard to do so. The best ones end up cover up almost the entire chair. Most of them left untouched just look rather dull and uniform. Keep the ones we have, but a blank frame would be great. Or make the existing chairs a bit easier to build on

**Comment by ExodistSKY1** [comment]
Honestly the little drawing by Popka, I would be 100% okay with that being the basic chair implemented. I also agree with Zach on keeping the fancy/luxury chairs in game, and having these chairs for those who want to take a more customizable approach.

**Comment by Garrett-C** [comment]
I have said it before and I will say it again, buttons on armrests people. That’s what these chairs lack. As much as I love the new chairs and style, I was vocal about the ability to put buttons on the arms. I think some form of frame chair would help with this.

**Comment by ExodistSKY1** [comment]
> 
> 
> I have said it before and I will say it again, buttons on armrests people. That’s what these chairs lack. As much as I love the new chairs and style, I was vocal about the ability to put buttons on the arms. I think some form of frame chair would help with this.

If this is .5m width at the base and .75m to the back of the chair. This would allow for what you would like to have in game "buttons implemented into the armrests. while still allowing for creative liberty to be used when someone does not want their chair to have "armrests"

**Comment by PopkaAkula** [comment]
> _If this is .5m width at the base and .75m to the back of the chair. This would allow for what you would like to have in game "buttons implemented into the armrests. while still allowing for creative liberty to be used when someone does not want their chair to have "armrests"_

That and having the ability to make your own cushions for the seats would really allow people to add a lot more detail to their ships.

**Comment by tsunamayo** [comment]
Yes I want to add a minimalist chair with no arm rest. I dont pla  on puttin back cushion (or maybe just a cushion tile for deco, but not for seating), as it mess up collision and hit detection, seat height if you dont put anything, it is just a pain to make it work. I just need to make a few improvements to the IK system, so the feet can place themselve neatly (I did it for hand already). 
I keep you posted!

**Comment by ExodistSKY1** [comment]
Cushion tile for Decoration would be fantastic and more than enough for my purposes! (Maybe both a military and a luxury style)

**Comment by tsunamayo** [comment]
This was done years ago! thx
