### ISSUE TITLE
[Bug] Ship hologram model cut off

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#1521]
### Short Description of the issue:
Looks like a reappearance of issue #1286, the hologram in the ship core does not show the complete ship on some builds. This tends to be more common on larger ships.
![image](https://user-images.githubusercontent.com/27857711/69883992-5f521800-12ce-11ea-9e8d-af1a4819d970.png)

The holograms also seem to have lost their colours under excessive shadow, but only on larger blueprints too

### Steps to reproduce the issue:
Open the ship core of a large-ish ship and spin the hologram around

### Environment
- Skywanderers version: 19w23a
- Graphics Card: GTX 1050M

**Comment by Garrett-C** [comment]
Yeah, I had this issue on my Venator back when it loaded and wasn't invisible. The obsidian seems to all be visible in the hologram but is very dark, granted it is black so...

**Comment by tsunamayo** [comment]
Okay guy if you could send me one of your big-ass ship it would be easier for me to test and fix that bug! Thanks

**Comment by tsunamayo** [comment]
Issue was fixed sometime ago. Thanks!
