### ISSUE TITLE
[Suggestion] Renaming logic/hinges/sliders/rotators/etc

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#1523]
Similar to how we used to be able to name buttons and whatnot, I'd like to be able to rename items, namely logic, so you can hover over it and see what it's named instead of having to follow 'link wires'. Link wires are still useful don't get me wrong but it would be very handy to simply name a sequencer, or some other logic pieces, Elevator B Door 4 or something like Main Elevator Sequencer. Although the hover > display text isn't as necessary.

**Comment by tsunamayo** [comment]
Hi, yes you are 100% right it was something I wanted to do. I keep you posted when I add this. Thanks!

**Comment by tsunamayo** [comment]
@Xerma Hi, this will be implemented for some bricks. The remaining brick will require a deeper change. Thanks
