### ISSUE TITLE
[BUG]Screen freezing (the entire OS, not just skywanderers)

### ISSUE THREAD

**Issue by ultrak2k** [tsunamayo/Starship-EVO#1531]
### Short Description of the issue:
Alright, sometimes when I play skywanderers, it flat out just freezes. I can save the game even while frozen, but if I alt tab the mouse seems to be moving, but skywanderers is in the background, still frozen. Sometimes it might  unfreeze freeze, sometimes it may not.

This hasn't happened to anyone else, so I assume this is my GPU being wierd - its from 2012, and no one else has it
...

### Steps to reproduce the issue:
1)Load game
2)Play said game, and if youre unlucky, the screen will flat out freeze. Alt tabbing shows that technically things are happening, but my screen is not displaying these. This is why I can save the game and my builds.
...

### Environment
- Skywanderers version: 19w43a (but has been happening since mid 2018)
- Graphics Card: AMD Raedon 7500 HD series

### Additional information:

Here is video evidence:
https://www.youtube.com/watch?v=ZWxBuKF3ULU&feature=youtu.be

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3981566/output_log.txt)

**Comment by tsunamayo** [comment]
hah, thanks for the vid ;) Okay, how long during the play session does it happens? What are you doing, working on some large ship for example?
Thanks a lot

**Comment by ultrak2k** [comment]
> hah, thanks for the vid ;) Okay, how long during the play session does it happens? What are you doing, working on some large ship for example?
> Thanks a lot

Play session time can be random but if I have things like edge open, its more likely to happen
Its also more likely to happen with large ships but can happen with smaller shit
I was working on a 240m long ship, got close and fps dropped and then boom, frozen

**Comment by tsunamayo** [comment]
Sorry I slept on this. Is this you main PC? What is the rest of the config? Especially RAM.
It seems like a memory issue to me (RAM or VRAM). I have made some recent improvements on the memory side, with more to come. Did it is run better in last version? 
Thanks!

**Comment by ultrak2k** [comment]
> Sorry I slept on this. Is this you main PC? What is the rest of the config? Especially RAM.
> It seems like a memory issue to me (RAM or VRAM). I have made some recent improvements on the memory side, with more to come. Did it is run better in last version?
> Thanks!

This is on my main PC, but I haven't tried in the new verison no
I have 16 gigs of ram though, so its probably Vram, since my GPU is fucking ancient
