### ISSUE TITLE
[Suggestion] Stretchy paint tool

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Starship-EVO#1534]
Hi Tsuna,

So while working on my ship I found myself once again trying to paint a large amount of ship. Obviously this gets a bit repetitive after a while, especially on a larger ship. So I began trying to think of ways that you could allow the player to paint faster. To achieve this I considered a few core elements that a solution should cover.

1. The player should still have the ability to paint individual parts of the stretched blocks 
2. The solution needs to fit both with the Sky wanderers building language and the control language. 
3. The solution should provide the player with a usable tool for painting a bit faster.

With these core ideas in mind, I believe there are two main approaches to this. 

a) A toggle between the single block and whole shape. This solution would work well as it would achieve goals one and three. However, if executed poorly it could fail to achieve point two. The way I see this working would be a hotkey to swap modes and perhaps the icon changes or even make the multi-tool has some indication of the mode change,

b) Stretch the paint. This suggestion is one that primarily aims to achieve point 2. If there was some way of using the same stretch a 16x16 area for the paint tool it would allow for faster painting while still feeling like the same building system.

I am aware that you have had this issue brought to you a few times so this was me trying to add my take on it. For reference on why specifically I am asking, I have included some images of the ship in question. A large amount of the blocks have been replaced with the newer stretch technology and those are where the painting needs to be done.

![image](https://user-images.githubusercontent.com/43644633/71947011-530d8480-31c3-11ea-8034-a91a7ea2bc88.png)
![image](https://user-images.githubusercontent.com/43644633/71947023-5ef94680-31c3-11ea-8cf1-68470786d52f.png)
![image](https://user-images.githubusercontent.com/43644633/71947028-6587be00-31c3-11ea-8480-916aa4a5d8f4.png)

And because I know you are always curious about performance and how larger ships affect the game I have included some shots with information on that for you. 

![image](https://user-images.githubusercontent.com/43644633/71947138-c57e6480-31c3-11ea-8697-8a15de91cd79.png)
![image](https://user-images.githubusercontent.com/43644633/71947152-dc24bb80-31c3-11ea-9c62-fbcdc06ef375.png)

**Comment by Xerma** [comment]
#1449 💯 Would still love to see something like this brought into the game

**Comment by tsunamayo** [comment]
My god this is a massive ship! How long does it takes to load? Anyway I need to think more about it, there is UX design issue and also some potential problem when for example you paint a wedge block. It would mean 3d paint, wich would paint some block on this inside or outside you dont wanted, which would be perceived as a bug by the player.

**Comment by Garrett-C** [comment]
> My god this is a massive ship! How long does it takes to load? Anyway I need to think more about it, there is UX design issue and also some potential problem when for example you paint a wedge block. It would mean 3d paint, wich would paint some block on this inside or outside you dont wanted, which would be perceived as a bug by the player.

Hi sorry for the late response. Your reply totally flew past me.

I see what you are saying about the 3d paint yeah, it's certainly a tough one. I don't envy trying to come up with a solution for something like this. I do trust that you will be able to find some happy medium though. With the ability to stretch blocks to 16m painting 1m at a time isn't ideal, however you obviously want to keep the option to do it that way. Not an easy problem.

In regards to the load time, I timed it there and it loaded in 1 minute 38 seconds. Keep in mind this wasn't a clean world and I was over the torus so I would estimate anywhere between a minute and 2 minutes load time. I will attach a blueprint in case you want to test performance etc yourself.

[Obsidian Class refit.zip](https://github.com/tsunamayo/Skywanderers/files/4106834/Obsidian.Class.refit.zip)

**Comment by tsunamayo** [comment]
The dreaded Obsidian Class Refit. That one I used it quite a bit to stress test my tech... Cheers
