### ISSUE TITLE
[Suggestion - Repost] Multi Axis Mirroring

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#1555]
I hate to bring this up again and again but being able to mirror across more than one axis really feels like something we need for building. Having only one mirror plane makes building feel... incomplete. I do understand that bugs will come should you return this feature but I assure you, not having it in the game could be a mistake in the long run. I personally can't think of another space ship voxel building sort of game that doesn't have the ability to mirror across multiple planes. 

I'm certain that a large quantity of people would genuinely love to see it's return. (I may be the most excited honestly - but that's my own fault.)

My example is quite possibly the most extreme example:
![20200111214321_1](https://user-images.githubusercontent.com/32974671/72213911-b138b100-34bc-11ea-9f53-69911cf873ef.jpg)
![20200110184637_1](https://user-images.githubusercontent.com/32974671/72213912-b269de00-34bc-11ea-8b8e-20e4b3c0d02d.jpg)
![20200110104909_1](https://user-images.githubusercontent.com/32974671/72213913-b72e9200-34bc-11ea-9107-ffd872711b72.jpg)

I have been building spheres for a good amount of time now and the last one was just not smooth enough and tbh it was just ugly and didn't fit with anything around it visually. So I felt the need to make a much smoother one but this process is taking hours and hours just to get all of the Hepta Hull in place and I still have to go back afterwards and add tetras. I estimate for just the hepta's, it will take around 8 to 10 hours and maybe an additional 5 hours for adding the tetras. To contrast this, if we had the ability to mirror across the X, Y and Z axes it would take maybe 4 hours for the whole thing instead of 13 to 15 hours.

Like I said, my example is an extreme but that should go to show just how dedicated players will be to overcome limitations but in the end it just adds to player frustration. Not every ship will use all 3 axes and hell some will only use the 1. But there are countless instances where having this feature back would make all the difference.

**Comment by ultrak2k** [comment]
Multi axis mirror gang, Holy shit is it painful to try slowly build anything with one axis lol, even my simpler ships need atleast two

**Comment by Aiwii** [comment]
I would like to see multi axis mirror also, after single axis is perfected tho

**Comment by tsunamayo** [comment]
Yes I get it it is on my to do but I likely wont have the time before early access - symmetry is such a nest for bugs I dont want to shoot myself in the feet. This is a massive station thing, which is not my focus atm. Thanks

**Comment by Aiwii** [comment]
> This is a massive station thing, which is not my focus atm. Thanks

We have stations now...
