### ISSUE TITLE
[BUG] Ship Shakes Violently when Flying

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Starship-EVO#1558]
### Short Description of the issue:
When flying a ship it jitters around and is difficult to fly, This is the same as issue #1549, I've attempted Exodist's workaround (deleting and replacing all the engines) and sadly it didn't work. Another thing to mention is this bug is happening with a resave of the issued craft. 

https://streamable.com/zndnq 

I have found one thing! My impacted ship has an agility rating of 147% and 30 small thrusters I removed some stuff to change the stats to AG rating of 85% and 12 small thrusters and it flies perfectly fine now (other than the decreased agility).
...

### Steps to reproduce the issue:
Unsure... I've built 5 craft which use small thrusters and have varied agility ratings and only one is impacted with the bug. I can upload the craft file again but it is very likely a client-side issue.
...

### Environment
- Skywanderers version: 20w02c
- Graphics Card: AMD Radeon(TM) RX Vega 11 Graphics

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4051429/output_log.txt)
Re-save of craft has AGR of 147% and 30 small thrusters [VOI-AC16 Atlus.zip](https://github.com/tsunamayo/Skywanderers/files/4051432/VOI-AC16.Atlus.zip)

I removed these engines on both sides to resolve the issue
![removetostopshake](https://user-images.githubusercontent.com/53021785/72225697-a5dd9800-3545-11ea-8e6d-565f567d7e7f.png)

**Comment by tsunamayo** [comment]
Unfortunately I cant reproduce that issue. Could you please tell me what are you frame per second? You can press F3 then hit show FPS Info. Then send me a screenshot! Cheers

**Comment by Aiwii** [comment]
@tsunamayo 
![Skywanderers 2020-01-12 5_46_36 PM](https://user-images.githubusercontent.com/53021785/72228414-8fded000-3563-11ea-9ef9-612d914d82ad.png)

**Comment by tsunamayo** [comment]
@Aiwii did you had this issue in recent patches? Thanks

**Comment by Aiwii** [comment]
I have not had the issue in recent patches. I will close this now
