### ISSUE TITLE
[BUG] Translucent blocks render incorrectly underwater

### ISSUE THREAD

**Issue by AfterRebelion** [tsunamayo/Starship-EVO#1560]
### Short Description of the issue:
Things like windows seem to render above the water, as they don't get affected by the waving effect.

### Environment
- Skywanderers version: 20w02c
- Graphics Card: AMD RX 580

### Additional information:
![imagen](https://user-images.githubusercontent.com/559819/72267991-481e7e00-3621-11ea-8f93-486e448cd851.png)

**Comment by tsunamayo** [comment]
Yes this is gonna be really tricky to get it done properly unfortunately... Thanks
