### ISSUE TITLE
[Bug] Gravity does not affect the player if they are outside the ships boundary box

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#1563]
### Short Description of the issue:
Even if the gravity field extends out of the ships boundary box, the player is not affected by that field. Here I am in the "none" locomotion mode and not falling despite being in the grav field
![Skywanderers Gravity Box Bug](https://user-images.githubusercontent.com/27857711/72458496-9a49d580-37c0-11ea-907c-c6f2e8063996.gif)

...

### Steps to reproduce the issue:
Construct a platform and place a gravity generator on it with power, making sure the field extends out past the edge by about 5 blocks
Fly out to the edge of the field boundary and switch to "none" locomotion mode. You can also fly up to the top of the grav field and see the same effect, just make sure you're within the grav field but outside of the ship boundary
...

### Environment
- Skywanderers version: 20w02c
- Graphics Card: GTX 1050M

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4066499/output_log.txt)

**Comment by tsunamayo** [comment]
Yes this is the intended behaviour, what I need to fix though is the preview and grav field calculation. Thanks
