### ISSUE TITLE
[BUG] rails/hinges will go missing sometimes, when replaced leads to ship spawning invisible [20w02c]

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Starship-EVO#1564]
### Short Description of the issue:

Updated my ship with a blast door for its hanger that had vanished in an earlier save. built the same way and very simple. The new save will only spawn in as an invisible ship. The blocks seem to function the same way as visible blocks. Refer to images below

### Steps to reproduce the issue:

-If you experience a rail or a hinge missing, add another rail/hinge in the same location
-Export the ship
-ship will be spawned in invisible, 
        when you place a block on the invisible ship it will reveal some of the ship
        This invisible ship will create the infinite loading screen upon re-entering your game.

...

### Environment
- Skywanderers version: 20w02c
- Graphics Card: 1080ti

### Additional information:

Placement of block reveals some of the ghost spawn
![20200115122429_1](https://user-images.githubusercontent.com/45324484/72461042-b420f380-3793-11ea-94ab-56826b16f610.jpg)

The ship should look like the ones in the background
![20200115122443_1](https://user-images.githubusercontent.com/45324484/72461049-b84d1100-3793-11ea-8c5d-0b96470adb9a.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4066754/output_log.txt)

**Comment by ExodistSKY1** [comment]
I was doing some more testing to figure out what it could be.  The ships will spawn in perfectly if I do not move during the load in process.

**Comment by tsunamayo** [comment]
Amazing ship! how long? It looks massive! Could you give me the bp so I can try to reproduce?Thanks

**Comment by ExodistSKY1** [comment]
[DSF Battle Cruiser WIP VER5.zip](https://github.com/tsunamayo/Skywanderers/files/4106948/DSF.Battle.Cruiser.WIP.VER5.zip)

Please Delete this after downloading the blueprint so that only you have access to it. Thank you!

**Comment by tsunamayo** [comment]
Thanks, post deleted. How long does it takes for you to load? Cheers

**Comment by ExodistSKY1** [comment]
18-19 seconds for it to fully spawn in for me

**Comment by tsunamayo** [comment]
Sorry what was the name of the ship? Thanks
