### ISSUE TITLE
Stretching bricks into destroyed areas causes the bricks to be destroyed

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Starship-EVO#1567]
Stretching bricks into destroyed areas of a build causes those bricks to take on the damage of the area it is stretched into. 

...

-Destroy some blocks on a build (the tetras and corner blocks/ bricks)
-Stretch a brick into that area (the non physical portion of the wedge/corner block)
-the brick should auto adjust and become destroyed in the block areas that are destroyed on the ship

...

### Environment
- Skywanderers version: 20w02c
- Graphics Card: 1080ti

**Comment by tsunamayo** [comment]
Yes it is perfectly normal with the current tech. The HP level works per voxel, I should prevent building on destroyed voxel first instead. Thanks

**Comment by tsunamayo** [comment]
No longer applicable.
