### ISSUE TITLE
[Bug] Weird Deleting Bug [20w04a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#1582]
### Short Description of the issue:
When deleting blocks, sometimes there is a brief glimpse of what looks like another block in a different color after deleting the first block.

### Steps to reproduce the issue:
Place blocks, then delete. Watch closely for the other block, since it's gone really fast.

### Environment
- Skywanderers version: 20w04a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20200125162235_1](https://user-images.githubusercontent.com/33041786/73128156-ac7dfd80-3f90-11ea-90c2-3082de46fc62.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4112982/output_log.txt)

**Comment by tsunamayo** [comment]
Yes, it is because I am cleaning the block paint, and it is done faster than the geometry rebuild... I need to come up with a nice and clean way to fix this, it is a bit tricky. Thanks

**Comment by tsunamayo** [comment]
It was fixed some time ago. Cheers
