### ISSUE TITLE
[Bug] Cannot link screen to Power Reactor [20w06a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#1594]
### Short Description of the issue:
The screens cannot be linked to the Power Reactor block. Possibly the same issue as the problem with linking described in #1479.

### Steps to reproduce the issue:
Place a reactor block and a screen, then try to link the screen to the reactor. The link trail will stay red. Interestingly, the screens can be linked to the shield unit.

### Environment
- Skywanderers version: 20w06a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20200204124731_1](https://user-images.githubusercontent.com/33041786/73776137-d67fae80-474c-11ea-871e-2a8c8b1418a8.jpg)

![20200204124741_1](https://user-images.githubusercontent.com/33041786/73776139-d8497200-474c-11ea-8df6-961144280c7a.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4155295/output_log.txt)

**Comment by Majikmonster** [comment]
I thought the flat screen was a type of control brick for linking to cameras and such. I could be wrong, but it's never been able to link to a non-player-controllable system that I know of.

**Comment by Dwarf-LordPangolin** [comment]
They actually all work for both systems and cameras -- which is fantastique, since it gives us all the options for setting up cool command centers! For some reason though, they don't seem to like the reactors ATM.

![20200205212019_1](https://user-images.githubusercontent.com/33041786/73903089-95c38a80-485d-11ea-880f-7700dd3999e6.jpg)

![20200205212110_1](https://user-images.githubusercontent.com/33041786/73903096-99efa800-485d-11ea-97cd-5e473c57a41c.jpg)
