### ISSUE TITLE
[Suggestion] ship center of mass indicator

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#1598]
I'm proposing a visual indicator on the HUD / ship core GUI / drone menu that shows where the pivot point for a ship is. I think it would be convenient to see where it is so builders can adjust a design for more intuitive maneuvering, or know where they can put cameras/weapons to keep their aim centered while turning and rolling the ship without having to try and track down that point through ship acrobatics.

What do you think of this suggestion?

**Comment by Lsutehall** [comment]
I was going to suggest this for the hovercraft core actually, to give an indication if how to place the repulsers

**Comment by Majikmonster** [comment]
I used "ship" as a general vehicle term. I would love this to be available for all types of craft. It would also be great if it took into account child entity mass and position.

**Comment by tsunamayo** [comment]
I made it for the Hovercraft already, I can add it for the spaceship core also.
