### ISSUE TITLE
[Question] Building on the torus/asteroid

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#1601]
Now that the torus is back and asteroids have been uncubed, I got thinking on how we would build on them. Obviously this is in the (hopefully not so) distant future but now that the classic voxels are removed, I am unclear how we will build on them with our blocks/bricks. The two options I can think of at the top of my head is keeping a normal voxel building system like Minecraft that just displaces some of the land. Another is you have to place a platform and can only build on it. Just curious if there is an idea how building on the ground/asteroid will work.

**Comment by Aiwii** [comment]
I like the platform idea but does that prevent one from building underground or in caves?

**Comment by ZachZent** [comment]
Not really, just dig underground or walk into a cave then place the platform

**Comment by tsunamayo** [comment]
I havent decided yet, it will depend on several factor. Worst case it will be a platform like, best case it will be some smooth terrain editing. It should be at least that for asteroid I think, but we will see. Thanks
