### ISSUE TITLE
Pressing Save gives no indication that the game has actually saved.

### ISSUE THREAD

**Issue by ike709** [tsunamayo/Starship-EVO#162]
It'd be nice if there was a "Saving..."/"Saved" message or something similar whenever I press F1.

**Comment by tsunamayo** [comment]
There is a small Save signal on the top-left, but indeed since I did made save faster recently I guess you dont have the time to see it, so I will make it stay longer. Thanks!

**Comment by ike709** [comment]
I tested it again and you're right an icon does flash in the corner. But it only appears the first time you save. So not only is it too fast, but it only ever displays once.

**Comment by tsunamayo** [comment]
The second time you save I guess it is so fast you just dont see it (as it is also flashing) - as no ship were saved I guess. I think I might also add a debug message for important event on a side of the screen, wdyt?

**Comment by DarianLStephens** [comment]
If you do, it should probably be toggleable or available in an optional console (As a separate window); don't want messages when you're just trying to get immersed in the game, eh?
At the very least, having them fade shortly after the task is finished would be nice.
Heck, maybe it could be implemented in to a chat thing, where the last few messages are temporarily saved and can be called back up at any time by pressing your chat key (Text entry).

**Comment by tsunamayo** [comment]
Yes I agree it would be immersion breaking and not very elegant (but yes it would have been fading after x second). How other game like Minecraft are doing that?
Yes chat and command line will be implemented at one point for sure.

**Comment by DarianLStephens** [comment]
Minecraft has an optional log window, separated from the game's window that can be moved about freely.
It shows all sorts of debug information, and being a separate window, players can do whatever they want with it to make it easier to see, or just hide it altogether.
If that sort of system won't be implemented for a while, then making the notification unobtrusive would be great.
Something small and in the corner, which fades at most seconds after the action finishes.

**Comment by Aiwii** [comment]
Now that the game has an EA release date, I think fixing the Save Icon is a bit important. A lot of people don't see it flash and just spam F1 and hope that the game saved.

**Comment by DarianLStephens** [comment]
Wow, that's still a problem?
Also, holy cow I commented on this ages ago.

**Comment by tsunamayo** [comment]
No thats no longer a problem as there is an autosave, F1 does nothing now. There was an icon but the save process was so fast it didnt showed. Cheers
