### ISSUE TITLE
Brick offset not working properly

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#1623]
### Short Description of the issue:
It may be due to the change in collisions but that's just my assumption but brick offset doesn't seem to work properly when you offset the grid by .5 but yet it works just fine with a .25 offset as seen in the pictures below
...

### Environment
- Skywanderers version:  20w09a
- Graphics Card: GTX 970

### Additional information:
![20200227125757_1](https://user-images.githubusercontent.com/32974671/75477218-95e90e80-5961-11ea-97a7-11567c54b77f.jpg)
![20200227130022_1](https://user-images.githubusercontent.com/32974671/75477222-97b2d200-5961-11ea-8019-d1288c0207fb.jpg)
![20200227130023_1](https://user-images.githubusercontent.com/32974671/75477230-98e3ff00-5961-11ea-8808-ec6636a92ac8.jpg)
![20200227130024_1](https://user-images.githubusercontent.com/32974671/75477235-9bdeef80-5961-11ea-8791-cf3b5b2639ab.jpg)
![20200227130034_1](https://user-images.githubusercontent.com/32974671/75477242-9da8b300-5961-11ea-83c5-51a70126b25d.jpg)
![20200227130156_1](https://user-images.githubusercontent.com/32974671/75477251-a00b0d00-5961-11ea-9eb5-bec38f5eaf06.jpg)
![20200227130152_1](https://user-images.githubusercontent.com/32974671/75477286-b1541980-5961-11ea-9ef3-91f0c6ce58ba.jpg)
![20200227130309_1](https://user-images.githubusercontent.com/32974671/75477296-b5803700-5961-11ea-810b-f9c0b7ffba98.jpg)

**Comment by tsunamayo** [comment]
Hi, are you positive it was working before? These offset things are a nightmare to work with, I should never have gone that route and just put a 1/4 grid and thats it... Cheers

**Comment by ProPeach** [comment]
Before the offset worked for a half brick, but not for anything smaller which I think is a good compromise. You could still offset by a quarter brick, but only in one direction. If you tried to place a brick on the side of a quarter brick offset brick, it wouldn't work. I think that's fine personally, a half brick offset is a nice balance between what I assume is a tough problem and freedom to build.
