### ISSUE TITLE
Some audio loops

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#1627]
### Short Description of the issue:
I've noticed at times when I'm painting that if I drag away from any blocks/bricks and release that it sometimes continues playing the paint sound until I click again to update it.

Just recently had a hinge sound constantly play even when updated via logic to toggle it. And I'm not too sure how to replicate it as it just seems to happen
...

### Environment
- Skywanderers version: 20w09a
- Graphics Card: GTX 970

### Additional Information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4269096/output_log.txt)

**Comment by tsunamayo** [comment]
Yes indeed, I think I had the paint sound bug (but also with VFX playing) issue a bunch of time. I think the hinge sound issue should be something different though.
I keep you posted when I track this.
Thanks!
