### ISSUE TITLE
Brick Systems Feedback -- Promising Start

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#1631]
I wanted to give you a bit of feedback on the brick reactors now that I've had a chance to look at them more closely.

I think your balancing strategy for reactors -- and for brick-vs-block systems in general -- is going to work. Obviously, the specific numbers will need to be balanced eventually, but there's already clear pros and cons to using each on different sized ships. The buff to heat dissipation from surface area gave smaller ships the ability to carry useful amounts of systems, while the much greater heat generation of the brick systems means that you still have to worry about heat on small ships. The greater heat efficiency of block reactors means they're much more useful on larger ships that have tons of volume but which don't benefit as much from surface area.

You did a _fantastic_ job of using the square-cube law to balance larger & small systems. I can't wait to see what you're planning with regard to block vs brick cost & mass. :+1:

**Comment by tsunamayo** [comment]
Thanks mate, we will see how it goes! Hopefully I no major flaw arise and I can simply tweak my way from now...
