### ISSUE TITLE
Center of Mass

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#1632]
### Short Description of the issue:
I built a little hovercraft car, the GTR Nismo, just to test around a bit and we're curious as to how exactly mass is calculated for bricks and blocks and likewise for center of mass. The reason is this build seems to be perfectly mirrored (even though I didn't use the mirror tool once to prevent duplicates/clipping) but yet the center of mass indicator in the hovercraft core is not centered at all. I tried gutting the interior and systems to just the exterior and every brick seems to be perfectly mirrored. ProPeach and I got to speculating a lot of things about it but it would be best just to know firsthand. 

When activated, the hovercraft drags on the driver's side (left).

On the base entity, I didn't build it centered but instead slightly off centered and to go along with this, it seems that entity bounds can grow when blocks are placed but cannot shrink when blocks are broken. So on the actual build itself and the save, those original bounds are much larger than it should be. However, when a new build is spawned those entity bounds are properly updated and appear to be perfect but the center of mass doesn't change.

...

### Environment
- Skywanderers version: 20w09a
- Graphics Card: GTX 970

### Additional information:
Original Build Entity Bounds:
![20200301111249_1](https://user-images.githubusercontent.com/32974671/75630914-228b0b00-5bb4-11ea-83da-46bcf85147a9.jpg)
Newly Spawned Entity Bounds:
![20200301113826_1](https://user-images.githubusercontent.com/32974671/75630834-92e55c80-5bb3-11ea-80ec-bbfb25f7529a.jpg)
Center of Mass / Center of Thrust:
![20200301105807_1](https://user-images.githubusercontent.com/32974671/75630855-b7413900-5bb3-11ea-8880-8108fd41c238.jpg)

The build:
[GTR Build.zip](https://github.com/tsunamayo/Skywanderers/files/4272195/GTR.Build.zip)

**Comment by Aiwii** [comment]
I am also having this issue
![hmmm](https://user-images.githubusercontent.com/53021785/75638792-e921c200-5bea-11ea-9d8b-5a7991bb28d6.gif)
[CARs.zip](https://github.com/tsunamayo/Skywanderers/files/4272969/CARs.zip)

**Comment by tsunamayo** [comment]
That seems more like a bug to me! I keep you posted. 
Thanks!
