### ISSUE TITLE
[Bug] Free-floating building tool [20w09a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#1639]
### Short Description of the issue:
Sometimes the building tool leaves the player and floats off by itself.

### Steps to reproduce the issue:
Not sure what causes this to happen yet, will post when I figure it out.

### Environment
- Skywanderers version: 20w09a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20200302143126_1](https://user-images.githubusercontent.com/33041786/75715182-9dc2ee80-5c92-11ea-9136-506d15d8de05.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4277748/output_log.txt)

**Comment by Aiwii** [comment]
I've also had this issue
![image](https://user-images.githubusercontent.com/53021785/75730772-00c07f80-5cab-11ea-91cc-dbf5bdb027c0.png)
It kinda just got stuck in the build, I think maybe the player was slightly clipped into the build and when I walked out the tool stayed

**Comment by Thasrion** [comment]
I've had a similar issue but not with the tool.

![image](https://user-images.githubusercontent.com/51243995/75732862-4be18f00-5cb9-11ea-9cc6-5d69360fb5b0.png)

**Comment by tsunamayo** [comment]
It seems to be related to 3rd person mode, did you changed from 1st to 3rd? Did you changed your player customization? 
Thanks

**Comment by Dwarf-LordPangolin** [comment]
I can't remember; I'll check those things and see if it's related.

**Comment by Thasrion** [comment]
> It seems to be related to 3rd person mode, did you changed from 1st to 3rd? Did you changed your player customization?
> Thanks

I did change from 1st to 3rd person but it didn't fix it. However, reloading the game fixed the issue.

**Comment by tsunamayo** [comment]
Was it during multiplayer? Mp is bugged, I just did a pass it is going better now. Thanks
