### ISSUE TITLE
[Bug] Stickers are not shown in the ship preview

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#1641]
### Short Description of the issue:
This might not be super important now, but could be a factor in identifying ships based on their faction colours and patterns. As you can see in the image, despite having grey triangle stickers on the build in the background they do not show up in the preview in ship core, drone or target selection while flying
...

### Steps to reproduce the issue:
Build some stickers on your ship and make them easily visible, either large or brightly coloured.
Check the ship preview in the ship core/drone and notice the stickers are not shown
...

### Environment
- Skywanderers version: 20w09a
- Graphics Card: RX 580 8GB
![image](https://user-images.githubusercontent.com/27857711/75898127-8e2ddc00-5e31-11ea-85ec-0f1f580d297a.png)

**Comment by tsunamayo** [comment]
Right, it is the second big issue of this sticker tech, they are deferred decals. Which means they cant work in the preview! ... Likely will be a wont fix... Cheers

**Comment by tsunamayo** [comment]
Finally fixed for 20w29c. Cheers
