### ISSUE TITLE
[BUG] Glichy character creation

### ISSUE THREAD

**Issue by TheCuriousSkeleton** [tsunamayo/Starship-EVO#1650]
### Short Description of the issue:
I created a new character and it "bugged" out. I was able to turn but not able to move. The camera was inside the character (picture below) and I couldn't open any menus.

### Steps to reproduce the issue:
I'm not sure how it happened.

### Environment
- Skywanderers version: 20w10a
- Graphics Card: 1050 ti

### Additional information:
![20200315180650_1](https://user-images.githubusercontent.com/39653820/76707558-02953480-66e8-11ea-9b5a-417bf8b7c38b.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4334746/output_log.txt)

**Comment by tsunamayo** [comment]
Did you faced this after starting out a new game from windows? Or did you exited the game to the main menu and then went back in?
Thanks
