### ISSUE TITLE
[Suggestion] New light

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#1652]
### Short Description of the issue:
The lights that we currently have are nice and all but they can be awkward to build around since they aren't the full 1x2 brick size and are very thin. Not to mention they aren't as 'fast' to use since they require a more precise placement.
...

### The Suggestion: ###
Now I'm not suggesting to remove them or change them as they work just fine in some cases but I feel it would be nice to have a bit more options to choose from. I personally try to keep my hallways and other bits of interior to as few bricks as possible while still aiming for a good amount of detail. 

My actual suggestion is to use the "Vent Base" as a light and it can simply use the same drag settings as the vent base while emitting the same kind of light from the light bricks based on the "Light Panel's" center. Below is a showcase of the example.
...

### Examples:
![ex1](https://user-images.githubusercontent.com/32974671/76711259-64e83800-66dc-11ea-8a21-decc27efac8a.png)
![ex2](https://user-images.githubusercontent.com/32974671/76711260-66b1fb80-66dc-11ea-87d1-254a5dc13207.png)

**Comment by tsunamayo** [comment]
Draggable light are not likely to come, it trigger some complicated issue to solve. I will do a light refactoring at one point, then I will see what I can do for more light variety. I definitely wants to give more flat light options...
I might change current lights a bit, the light area around them will change to be more optimum, as I want to switch to a shadow map system. 
Thanks!

**Comment by BFett2000** [comment]
It might be nice to have draggable lights like we used to, but only have them use the point light tech of the 1x2 lights, so that a 1x6 is the same brightness and area affected as the 1x2 lights.  The only difference being the visual appearance of the light.  Since from an aesthetic point of view the 1x2 lights that are in this build of the game are not as pretty as the ones just a few builds back.
