### ISSUE TITLE
Super Slow Mirror

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#1660]
### Short Description of the issue:
As of this latest build, the mirror seems to be far slower than normal. Fairly often when I place blocks while there is a mirror axis placed, the original block shows for second then goes invisible until it syncs with the mirror. I recently found the same issue when even deleting blocks with the mirror enabled and thanks to this I finally have a good example to show the issue. It even seems to be a random delay.
...

### Environment
- Skywanderers version: 20w12a
- Graphics Card: GTX 970

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4350648/output_log.txt)

The black blocks you see in these pictures are the blocks that have been broken but are waiting to sync and fully disappear.

![20200318131429_1](https://user-images.githubusercontent.com/32974671/76993802-6f444500-691b-11ea-9d50-5f954e758392.jpg)
![20200318131432_1](https://user-images.githubusercontent.com/32974671/76993808-710e0880-691b-11ea-8665-98262e4136fc.jpg)
![20200318131536_1](https://user-images.githubusercontent.com/32974671/76993811-72d7cc00-691b-11ea-8c8c-176214edf8ed.jpg)

**Comment by Xerma** [comment]
Here is my latest example:
![20200318230006_1](https://user-images.githubusercontent.com/32974671/77030373-5fa11c80-696c-11ea-9de3-10a3611e4b75.jpg)
I've been waiting a few minutes now for it to catch up but it doesn't show any signs of doing so

**Comment by tsunamayo** [comment]
Hum not sure I think it is also linked to the fact that your build is very big. Anyway I just fixed an issue with mirror, you will tell me if it is better on the next update! I keep you posted. Thanks!

**Comment by ProPeach** [comment]
I recently experiences this bug for the first time while just starting to build a 100mx40m ship too, so it might not be limited to large numbers of blocks of Xerma's build, I'll report back after the patch if anything's changed.

**Comment by tsunamayo** [comment]
Okay version 20w13a is up if you want to test! Thanks

**Comment by tsunamayo** [comment]
@ProPeach @Xerma Sorry for the ping, I dont know if you had time to test that. I hope you guys are doing good during the confinement (if you are confined!)...
Cheers

**Comment by Xerma** [comment]
It's possible that it's due to the ship being large but I have never experienced this bug until just recently. I did a super quick test on a newly made entity and it seems to keep up with mirroring just fine.

**Comment by Xerma** [comment]
As I build on the larger ship more and more it seems as if the mirror slows as the session time increases

**Comment by Xerma** [comment]
I'm not 100% sure what's causing the mirroring to be slow at times but it does feel as if it's related to how long a session is going on for. On a fresh new 70m build with hardly any blocks placed on it the mirror showed some signs of slowing down.

**Comment by tsunamayo** [comment]
Okay, now I need to know if it is just build related or mirror related. So once you are sure to have lag, then desactivate the symmetry for a bit and check if there is still lag or not.
I suspect it might not be linked to symmetry. If you work on the outside of your large build the light volume will be regenerated each time, it can be huge on memory, leading to GPU memory fragmentation ect...
Thanks!

**Comment by Xerma** [comment]
That would make sense actually. Still odd that it's just now occurring for me in the latest builds though. I have noticed it hasn't been lagging as much while working within the ship. And when I say lag I'm just talking about the mirror taking a while to catch up or it's not catching up at all. Restarting seems to refresh it but no frame drops, everything else still functions normally. 

Here is the area where I've been recently building and getting little to some mirror lag:
![20200404015448_1](https://user-images.githubusercontent.com/32974671/78420717-4dcfa280-7617-11ea-96c1-f37107ac0425.jpg)
![20200404015453_1](https://user-images.githubusercontent.com/32974671/78420718-5031fc80-7617-11ea-9aa1-dad7ac60be2f.jpg)

Seeing how this part is behind a giant wall, that would make sense that it would lag less. I'll try to keep track on the lag

**Comment by Xerma** [comment]
Errr, scratch that. After some time the area that was in the shade did end up slowing down with the mirror just like before.

**Comment by tsunamayo** [comment]
Okay this issue should be fixed in the latest experimental branch, 20w28c. I dont know if this is something you can confirm easily or not? Keep me posted, cheers
