### ISSUE TITLE
Kinetics vs Energy [SUGESTION]

### ISSUE THREAD

**Issue by MrSquid1** [tsunamayo/Starship-EVO#1677]
Hello i'm going to leave this as a discussion on how balancing kinetic weapons and energy weapons would work. For starters let's make kinetics ammo based and energy power based.
Then i'll start the division.

KINETICS

MISSILES-Deal more damage and can be guided

-HE(red)-Deals more damage against hull

-AP(yellow)-Deals more damage against armor

-EMP(blue)-Deals more damage against shields

GUNS-These can be normal guns, railguns, anything. there are 4 types of ammunition

-HE(red)-Deals more damage against hull

-AP(yellow)-Deals more damage against armor

-EMP(blue)-Deals more damage against shields

-ACID-Deals damage over time
*Normal Acid(green)-Eats away hull and armor
*Plasma barrels(purple)-Eats away hull and shields

ENERGY

ENERGY-These are lasers, there are 3 types again, but these don't relly on ammo, but have to be changed at a shipyard.

Ion-Deals damage to shields
Plasma-Jack of all trades
Beam-Deals small amounts of damage but it also adds heat to enemy ships, 4:3 rate, so only use it if they can stand less heat than you

**Comment by tsunamayo** [comment]
Yes this is pretty close to what I had in mind. Thanks
