### ISSUE TITLE
[Bug] Brick Engines

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#1683]
The brick engines now scales on all axis. I'm hoping this is a bug and not a feature as it makes building fighters, smaller ships, and most importantly maneuvering engines especially difficult. Especially since you have to use brick engines to maneuver.

https://cdn.discordapp.com/attachments/406664114249793536/695162260624244766/unknown.png

**Comment by tsunamayo** [comment]
Yes indeed, and no it was on purpose: the model / texture looks too crappy when distorted... I mean it is still better than a game where you only get no scale at all right ? ;)

**Comment by ZachZent** [comment]
Um, I'm confused. We never were able to scale it in non equal dimensions for the X and Y axis. That part is fine, keep it a circle. What we need back is scaling on the Z axis. Being able to make longer/shorter engine "tubes". What exactly was wrong with only being able to scale it on the Z axis from the previous updates and what is stopping it now?

**Comment by ProPeach** [comment]
I strongly disagree, the texture looked absolutely fine.
The larger problem is that if it scales as a cube, the only way to make a ship more powerful is to make the thrusters wider/taller which has a huge impact on the shape of the rear of your ship. The majority of the times I've seen this brick used are as a long, relatively thin thruster to make the most of a ships length while presenting a small thruster profile. This is the same with any thruster, they're usually much deeper than they are wide/high. This change severely impacts the way you build a ship.

**Comment by tsunamayo** [comment]
Okay I will see what I can do. Thanks

**Comment by ProPeach** [comment]
That would be great thank you, this really is an essential mechanic

**Comment by Aiwii** [comment]
Please bring back Z scaling for the small thruster! Really helpful for fighters

**Comment by ultrak2k** [comment]
@tsunamayo sorry for the ping but a few updates have past, and this issue has made it hard to build - you have to stack brick thrusters to make a brick thruster fit in a hole that isn't a perfect square, and makes side thrusters akward

**Comment by tsunamayo** [comment]
Thruster has been updated and will rescale non-linearly on 20w18b like before. Thanks!
