### ISSUE TITLE
Beam convergence

### ISSUE THREAD

**Issue by schlid** [tsunamayo/Starship-EVO#1696]
Hey Tsuna, glad to see we've got beams back in the game. One thing I couldn't help but notice, we can't converge beams at the moment. When do you see this returning? I miss my death star lasers :))

Cheers

**Comment by tsunamayo** [comment]
Yes I know it sucks, one of those buggy unoptimized stupid idea I had from back in the day...
Maybe one day I will bring them back from the dead, but the code was just too nasty to keep, like all I did a few years back...

**Comment by schlid** [comment]
That's a shame. It was definitely an original feature I'd like to see back in the game at some point. Thanks for the quick reply

**Comment by Xerma** [comment]
It's return would without a doubt draw in more attention. I agree that it was pretty iconic and it would offer a nicer variety for combat
