### ISSUE TITLE
[Suggestion] GUI for ship stats while building + Core option

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#1701]
I'd recommend having the option or hotkey to toggle a GUI on the left or right side of the screen that displays the same information that the drone does. This would help players keep track of heat dissipation and whatnot while building and therefore help prevent ships from blowing up while building. It would also just be a handy thing to have.

The second thing goes along with how ships can blow up while placing systems. For this I have a couple things. The first being to have an option within all of the cores (ship/mech/hovercraft) to completely disable the ship, mech, or hovercraft. This would allow players to place systems and experiment without the risk of having to respawn the ship and try again. It also adds an incentive to place the cores in a more secure area to prevent enemies from disabling your ship that way.

The other thing could be to display how much heat the current build can handle and how much heat the current system you are dragging will produce and give a warning message at the top of the screen if it's going to exceed the entities max heat dissipation.

**Comment by tsunamayo** [comment]
Yes I agree I have to come up with something, this is not acceptable.
What do you think of:
- no overheat while building, only when flying the ship.
- if the ship is not heat balanced then you get a warning that you cant fly the ship.

I can show warning messages now, this is the kind of things I need to explain better to the player.

**Comment by Aiwii** [comment]
I like the ideas of preflight warnings, but a stat bar on the side would be really useful also
