### ISSUE TITLE
[Bug] Window Tile Wedge paint

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#1706]
### Short Description of the issue:
The edge of Window Tile Wedges cannot be painted, but the glass can

### Steps to reproduce the issue:
Place a Window Tile Wedge and try to paint the edge

### Environment
- Skywanderers version: 20w15a
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
So yes you need to target the side of the brick, the edge is not enough. I will see what I can do to make it more logical... Cheers

**Comment by ProPeach** [comment]
Great! Yeah that's not immediately obvious, a more logical approach would be ideal
