### ISSUE TITLE
[BUG] Multiplayer build drone issue

### ISSUE THREAD

**Issue by Womble-TC** [tsunamayo/Starship-EVO#1711]
In Multiplayer, only the host can spawn the build drone. No one else connected to the server can spawn their own drone.

**Comment by Battlepixel** [comment]
We also noticed that.

**Comment by tsunamayo** [comment]
The build drone will be removed.

**Comment by tsunamayo** [comment]
Also welcome back! Thanks for pushing on the multi-side ;) Cheers
