### ISSUE TITLE
Stickers on mirror axis graphical bug

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#1718]
### Short Description of the issue:
I forgot I had symmetry on while trying to put a sticker near/on the symmetry plane and so I broke it to redo it without symmetry but there was a graphical artifact left by one of the stickers. I could not break it to get rid of it, breaking the block it was on did not fix it, updating the grid at all did not fix it. However Restarting the game did fix it.
...

### Environment
- Skywanderers version: 20w15b
- Graphics Card: GTX 970

### Additional information:
![20200410183914_1](https://user-images.githubusercontent.com/32974671/79029710-3171bf80-7b5b-11ea-8575-6a76820c5984.jpg)
After Restarting
![20200410184033_1](https://user-images.githubusercontent.com/32974671/79029715-36367380-7b5b-11ea-8571-c491b657dfc8.jpg)

**Comment by tsunamayo** [comment]
Okay I cant reproduce this, it seems to be ok on my side. Could you give me more info?
- are you reproducing this all the time
- what sticker did you used, did you used any scaling? 
Thanks
