### ISSUE TITLE
[Suggestion] Damage add-ons

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#1729]
The damage add-ons are a really cool way of customizing your gun, but at the moment the Hull Damage add-on for example increases DPS against hull with no change to heat damage. This is a direct upgrade in DPS which is different from the other add-ons like Charge, which are more like a side-grade as they don't increase overall DPS they just change the way it is applied.

I suggest that the hull damage add-on keeps the current damage hull buff it gives, but also reduces the damage dealt in heat and vice versa for the heat damage add-on. This way the gun becomes more specialized in dealing one damage type and has a weakness, rather than simply gaining an advantage with no downside.

**Comment by tsunamayo** [comment]
Hum that could also work, the downside is that it also increase the power / heat under regen (no constant cost like the weapon block though, only regen).
Current value are (in ratio):
Base Laser
- Power / heat draw all the time: 1 / 1
- power / heat under charge 4 / 4
- hp/heat damage addon power / heat under charge 2 / 2

I need to give it more though. If I go this way then I would like that ALL side addon does not impact heat / power draw as rule easy for the player to understand, so I would have to find something for the supercharge.
