### ISSUE TITLE
Turret Tracking

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#1734]
### Short Description of the issue:
For one of my ships I decided to have a little camera on a very simple 'turret stand' instead of making a canopy cockpit and the whole point of the camera is to track and move along with the mouse so I can look around as if the player's head is there instead. For this to work I had to link a yoke to a ship core and the camera on the turret, then link the ship core to the 2 rotor axes. This worked out just fine but the cursor does not accurately track where the camera is looking/camera center. I suppose this is due to I think the dead zone. - Picture "A" below -

I then figured I'd test making a turret to track where I look while piloting, like the droid AAT from the clone wars. Turns out if you remove the camera link from the yoke, the turret no longer tracks with the original setup. But if you have any other camera (placed on the turret or not) linked back to the same yoke, the turret will then track but aiming is nearly impossible this way. - Picture "B" below -

And I'm not sure if you purposely designed cameras this way or not but you also can't switch to third person view if you are in a camera. This does make sense but perhaps we should have a second camera that allows for this? Sort of like a next tier camera - although that could make the basic camera obsolete.

### Environment
- Skywanderers version: 20w15d
- Graphics Card: GTX 970

### Additional information:
Picture A - Cursor is on the left side of the screen while the camera aims at the edge of the torus
![20200412021236_1](https://user-images.githubusercontent.com/32974671/79063062-f8257680-7c64-11ea-9524-b8be8e6180f4.jpg)

Picture B
![20200412021856_1](https://user-images.githubusercontent.com/32974671/79063250-06c05d80-7c66-11ea-8036-245fed79e623.jpg)

**Comment by tsunamayo** [comment]
Turret where broken, I am not sure to understand 100% your issue though. So better is to wait for next patch (20w16d) and you will tell me if that fixed your issue!
Cheers

**Comment by tsunamayo** [comment]
@Xerma do still have this issue in recent patch? Thanks
