### ISSUE TITLE
Stickers display on bricks below

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#1735]
### Short Description of the issue:
In the pictures below I have 2 circle stickers on a brick slab and that brick slab is on top of a brick. When the brick slab is broken the stickers then display to the brick below it and the same happens when the brick is then broken but this time it looks funky.

I personally think stickers should just get destroyed when their host block/brick is destroyed, I think it would make more sense for survival anyways.

### Environment
- Skywanderers version: 20w15d
- Graphics Card: GTX 970

### Additional information:
![20200412024923_1](https://user-images.githubusercontent.com/32974671/79063671-9535de80-7c68-11ea-9be1-437ef02e5853.jpg)
![20200412024927_1](https://user-images.githubusercontent.com/32974671/79063674-96ffa200-7c68-11ea-9f30-2ffea28e712b.jpg)
![20200412024930_1](https://user-images.githubusercontent.com/32974671/79063676-9830cf00-7c68-11ea-83fb-4263005f3601.jpg)

**Comment by tsunamayo** [comment]
Yes, pb is there is no such thing as host brick in code. I will try to detect when there is no brick colliding with the sticker though, and remove them. Then for more issue fix it will have to wait for a big refactor / optimization I have in the pipe. Thanks

**Comment by tsunamayo** [comment]
Fixed for 20w29b, the new tech is here. Cheers
