### ISSUE TITLE
[Suggestion] Crosshairs and aiming

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#1749]
Now that flight in general is starting to feel really nice, let's talk about dogfighting!
Firstly a set of crosshairs would be great so that we know where exactly our fixed guns are pointing. The new momentum based camera feels super satisfying, but it can be a bit difficult to keep track of where your shots are going during maneuvers.

Second, are you still thinking about giving non-turreted brick based weapons a small gimbal to help with targeting? I hope so, as it was an awesome idea.

Lastly, I wanted to talk about aiming your ship. Right now there's a very large deadzone when flying, you need to move your mouse a considerable amount to before the ship starts moving. This makes aiming your ship accurately difficult, especially when moving.
https://i.imgur.com/NchUZZB.mp4
Imagine in this clip that you want to target a ship diagonally up and to the right, the ship instead pitches up or yaws to the side, but does not follow the mouse diagonally. Reducing or eliminating the deadzone and enabling the ship to track diagonally would really improve our ability to fly and reduce some of the clumsiness of the current flight model.

**Comment by tsunamayo** [comment]
I see, I will have a look at it. For the small gimbal I wanted to add a gimbal barrel addon, that makes more sense. 
There should be a dead zone setting, I will have a look.

**Comment by ProPeach** [comment]
I went looking for a more visual example of what I mean about the deadzone, so I tried out Elite and it's pretty much a perfect example.
https://i.imgur.com/XT7zyFQ.mp4
Here' the moment you move your mouse away from the center your ship starts moving in that direction, and the speed of that movement increases the further you move your mouse away. The deadzone is either extremely small, or non-existent. This is ideal for flying in all situations.

I don't agree that a gimbal barrel is the best way to go. It's really tough to hit a target with fixed guns, especially in something with fighter-like maneuverability, and even more difficult to hit a moving target as you're dogfighting. A gimbal barrel would be really be the only choice for that situation which makes the rest of the barrels not effective enough to consider, so all brick guns non on a turret should have the gimbal.

**Comment by ExodistSKY1** [comment]
Just a light gimbal to all brick weapons would be nice, i am not sure about the degrees yet. But I was able to test combat with ZachZent and Aiwi last night, the Gimbal would have helped wonders. I feel the gimbal will help with the star wars style dogfights you would like to see. 

That heads up fighter display in a build far back was awesome, possibly allowing us to toggle it on or off in the ship core maybe?  It could bring some added flair to the fighters and double as a crosshair!

Accuracy as well as range in its current state is atrocious and both need a huge buff. 

    My idea for improvement on these would be to allow a huge range to the weapons measured in Kilometers, preferably tens of kilometers, and spread measured in meters. The gatling is not even a gatling anymore (if it even was before) and the beam has replaced it I will go further into detail on this tomorrow in a new Suggestion (sorry for hijacking the thread Peach)

Currently the only weapon I would use would be the beam. I will do some tests of my own tomorrow and post a suggestion on how to make the other barrels more enticing/viable assets.

**Comment by FelixGold** [comment]
I like the idea of a gimbal barrel, that way you can have an array of fixed and gimbaled weapons depending on what you want to go with.

**Comment by ProPeach** [comment]
The idea with the implicit gimbal for brick weapons was that the longer you stretch your brick gun, the less the gun could gimbal so you still have the choice of how much gimbal your guns have even without a gimbal barrel
