### ISSUE TITLE
[Dev Asks] I need your ideas for warning messages

### ISSUE THREAD

**Issue by tsunamayo** [tsunamayo/Starship-EVO#1751]
A few builds back I implemented a new warning message feature.
It will help newcomers to understand the quirk of the game.
For now I have too few!
If you have any idea of things that would require a message that would be great!
For example:
 No Large Thruster => Warning Message on Lightcruise key pressed (as indicated by ProPeach)
 No Side thruster => Need perpendicular thrusters to turn when ship enterered.

There should be a lot more, especially with the logic system. Thanks!

Thanks a lot!

**Comment by talrey** [comment]
No Timer in logic loop => warning message when trying to connect the last link (it already turns red, but a message could help a new player understand why)

**Comment by Drillz007** [comment]
in the case of operating a ship these would be pretty helpful 
- collision (gives you a heads up if your going fast enough towards something to cause collision damage)
- overheat (before over heating)
- running low on energy (before running out)
- shields going down 
- taking damage (under attack) 
- incoming missile warning (in the future when missiles are added)

for building it would be good to know if you are near to exceeding heat or energy limits that your ship would provide before it either explodes or sucks all the power out of it

**Comment by Aiwii** [comment]
Ship Runs out of power while in control => Some warning on how you can't do anything while discharged "Systems are down! Currently Recharging..."

**Comment by tsunamayo** [comment]
> No Timer in logic loop => warning message when trying to connect the last link (it already turns red, but a message could help a new player understand why)

Good one

> in the case of operating a ship these would be pretty helpful
> 
> * collision (gives you a heads up if your going fast enough towards something to cause collision damage)
> * overheat (before over heating)
> * running low on energy (before running out)
> * shields going down
> * taking damage (under attack)
> * incoming missile warning (in the future when missiles are added)
> 
> for building it would be good to know if you are near to exceeding heat or energy limits that your ship would provide before it either explodes or sucks all the power out of it

So for these one definitely, but not with the current message framework, more a set of dedicated HUD warning and sounds. For the overheat yes, and I will prevent overheat while building, only when flying, and you cannot fly the ship if it is not balanced.

> Ship Runs out of power while in control => Some warning on how you can't do anything while discharged "Systems are down! Currently Recharging..."

Yes definitely, and I will desactivate HUD... Like power is really down.

**Comment by Sei-Neko** [comment]
maybe something if the weight of a child entity is close to exceeding what a rotor/hinge/rail can support.

**Comment by PopkaAkula** [comment]
Some ideas for warnings could be
- improperly connected cores
- insufficient power generation
- insufficient heat dispersion

**Comment by Aiwii** [comment]
A warning for when a yoke is placed on a child entity about how it needs to be linked to a yoke on the parent entity

**Comment by tsunamayo** [comment]
Okay I have added all warning message for 20w19c, except for the Spaceship one, that will use dedicated HUD warning. Thanks!
