### ISSUE TITLE
Odd lighting with bricks

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#1752]
### Short Description of the issue:
I have no clue what's going on with this one but the lighting is very rough and jagged from this point of view on bricks - blocks look just fine.
...

### Environment
- Skywanderers version: 20w16a
- Graphics Card: GTX 970

### Additional information:
From a bit further away:
![20200414010959_1](https://user-images.githubusercontent.com/32974671/79191847-233ad200-7ded-11ea-8d31-b4cfab0f32d7.jpg)
A little closer:
![20200414011141_1](https://user-images.githubusercontent.com/32974671/79191870-3188ee00-7ded-11ea-9795-3c1a1a314108.jpg)
Block point of view:
![20200414011237_1](https://user-images.githubusercontent.com/32974671/79191894-3baaec80-7ded-11ea-870f-dd828cd9fa3b.jpg)
And from the other side (normal looking):
![20200414011009_1](https://user-images.githubusercontent.com/32974671/79191908-4796ae80-7ded-11ea-9d77-4ae7577d5f5b.jpg)

**Comment by tsunamayo** [comment]
Pretty sure it is an artifact linked to shadow mapping... I will do a tweaking pass on day but it could only make it a bit better.
