### ISSUE TITLE
[Suggeston] Brick Borders

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#1755]
Brick borders can look nice if you design around them in some circumstances, but most of the time I believe that a build would look much better without them, or at least with a more subtle version of them.

Here I wanted a very specific, Star Wars like aesthetic so the borders look good. This only works on big, flat, square panels though.
![image](https://user-images.githubusercontent.com/27857711/79241432-f3caaa80-7e6a-11ea-9efc-e0b9442ddf05.png)
![image](https://user-images.githubusercontent.com/27857711/79241573-1e1c6800-7e6b-11ea-87b4-9cf1c0d7e7b3.png)

But the majority of the time they get in the way of the shapes that I try to make. The more advanced and complex the shapes you build are, the more the bricks cut them up.
![image](https://user-images.githubusercontent.com/27857711/79242084-c6cac780-7e6b-11ea-8331-c9494d1f5834.png)
![image](https://user-images.githubusercontent.com/27857711/79242419-38a31100-7e6c-11ea-9c44-05524b7557f9.png)
![image](https://user-images.githubusercontent.com/27857711/79242446-435da600-7e6c-11ea-852b-737828a96a91.png)
![image](https://user-images.githubusercontent.com/27857711/79243824-0abecc00-7e6e-11ea-96f0-26c997fa6cd7.png)
![image](https://user-images.githubusercontent.com/27857711/79244366-bc5dfd00-7e6e-11ea-9317-fa1953bbb9e4.png)

I know that it's not viable to remove them completely as they cover up the seam between the different textures of two bricks, but can their effect be reduced? Perhaps make them thinner, less "deep" or colour them more closely to the colour of the parent brick? Any of these options, or ideally a combination of them would help a lot.

**Comment by PopkaAkula** [comment]
![image](https://user-images.githubusercontent.com/37738021/79243664-36de4b00-7e76-11ea-9f95-1a26882f9221.png)
![image](https://user-images.githubusercontent.com/37738021/79243680-3b0a6880-7e76-11ea-8d63-9d5a2b3a71d6.png)

I have two examples of the borders looking bad

**Comment by ExodistSKY1** [comment]
![20200412133743_1](https://user-images.githubusercontent.com/45324484/79264862-db529400-7e5a-11ea-854e-0c7f0de14eb0.jpg)

**Comment by Xerma** [comment]
![20200414031342_1](https://user-images.githubusercontent.com/32974671/79278302-0f38b400-7e71-11ea-9a99-c7e8c922c4c4.jpg)
![20200301113119_1](https://user-images.githubusercontent.com/32974671/79278340-1f509380-7e71-11ea-8b06-9e78a7744dd6.jpg)
![20190601004834_1](https://user-images.githubusercontent.com/32974671/79278415-4313d980-7e71-11ea-9ac3-1757946daba0.jpg)

**Comment by tsunamayo** [comment]
Yes I do agree it is not ideal for replica,  on the other side I am not trying to make the perfect replica builder ;) And honestly your ship looks good!
I will toy with smaller border, but just be aware that I do not plan to remove them completely.
Cheers

**Comment by ProPeach** [comment]
Yes, the borders are actually good for some Star Wars replicas! It's just that for most other builds, especially original builds they don't look good which I why I made this post.
Thanks for looking into it! Any reduction in their impact would be an improvement to be honest.

**Comment by FelixGold** [comment]
Why not include an option with something like paint to remove the borders? Other games have a mechanism like that.

**Comment by tsunamayo** [comment]
@FelixGold what game? tx

**Comment by ExodistSKY1** [comment]
@tsunamayo  I think the Ark survival evolved: S+ mod   has an option for the metal glass border allowing the user once it is placed to adjust where the "metal" border is seen or if they do not want it to be seen. Including a whole host of other options for the glass.

I agree with Peach, there are lots of areas that I want my ships to be smooth... I have only done one replica build, and that was not a true replica. I think the game and creative liberty stated on the steam page would benefit from the ability to decide on which one a player wanted to use as they both have their uses and a lot of times they overlap!   Only good things can come from it!

**Comment by FelixGold** [comment]
IIRC Empyrion has an option where it smooths things out with paint, as does Space Engineers.

**Comment by ProPeach** [comment]
In SE the border only shows when adjacent blocks are a different colour, but you can remove it with mods. It's different for SE though as they can do connected textures with blocks like SEVO does, but bricks don't work that way.

**Comment by FelixGold** [comment]
I can't make videos but I took some pictures @tsunamayo 

Here is a ridge between two blocks
![](https://cdn.discordapp.com/attachments/416013956331601930/702178977829093457/unknown.png)
I pant them rusty
![](https://cdn.discordapp.com/attachments/416013956331601930/702179111396835369/unknown.png)
Same color, different painted texture
![](https://cdn.discordapp.com/attachments/416013956331601930/702179517569171516/unknown.png)
Same color same texture
![](https://cdn.discordapp.com/attachments/416013956331601930/702179589677645854/unknown.png)

**Comment by tsunamayo** [comment]
Thanks for the screenshots! Okay so this is a different thing - Propeach is right, I have a adjacent border aware only for blocks, not for bricks. Bricks are not voxel based, I cant really do adjacent aware border. Also mine wont show a border for different paint.
To me it looks like another case for a mod for the workshop, bricks with a different texture. 
Give me a bit of time, I should be able to get to this.
My map on the workshop:
- blueprint (simple application so I can get the hand out of the workshop)
- custom bricks. This will require quite a few dev, on the virtual mapping of id on one side, to the brick definition by xml / json and also on the collision side.
Cheers

**Comment by ProPeach** [comment]
Yay for the Steam workshop! I'm glad that we'll be able to share our ships there.

Are you still planning on reducing the effect of the border? I don't think this is a case for different brick shapes, the border affects every brick, that's why I made this thread. New brick shapes will be from the workshop will be great, but the brick borders affect the look of every compound shape that we create for our ships with bricks.

**Comment by tsunamayo** [comment]
Yes it is a matter of texture not shape. I was suggesting that people would create a borderless version on the workshop, and you would use that. I mean if I have modding thats the first thing people would do I guess...

**Comment by ProPeach** [comment]
Ah, I see.
To be honest I don't see Workshop alternatives to every shape/texture as a good solution. The Workshop will be useful for all kinds of great things for sure and is awesome for this kind of game, but the vast majority of the community that have talked about brick borders in Discord and this/other threads aren't a fan of the current brick borders. Wouldn't it make more sense to make the borders smaller/less noticeable in the base game rather than make them mod it in? Especially as you say it won't look good without a border, the border itself is actually a very good solution but it's just a little too strong.

I'm just double checking that we're not misunderstanding eachother here, I hope I don't across too strongly

**Comment by Garrett-C** [comment]
Yeah borders can be used to get some cool effects when building but they can be a bit much when you don't want that effect.

**Comment by tsunamayo** [comment]
@ProPeach mate dont hesitate to state opinion strongly, it is valuable to me, even (or especialy!) when it hurts.

**Comment by ProPeach** [comment]
Coming back to this in light of the new backing wave - None of the new players I've talked to like the brick borders in their current implementation, they would all prefer that they either not exist like blocks (which we now know isn't feasible) or they were much smaller and less noticeable. I know you were thinking of leaving it to the missed a, but I really believe that an issue so widely agreed on like this should be part of the base game.
