### ISSUE TITLE
[Suggestion] Docking

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#1757]
With EA fast approaching and multiplayer becoming functional, ship docking is going to have to be added soon. There are three types of docking. This suggestion is for the first.

1.	Airlock docking – two doors connect forming a tunnel
2.	Magnet docking – one ship attaches onto another via a “magnet”
3.	Gravity docking – one ship lands in another such as a fighter in a carrier.

The problem with the old docking block is that even when they were connected, there is no guarantee that each door would match given that there was no universal model. For example one ship may have the docking block above their airlock door and another would have it below. Instead of a separate docking block, at least for this style of docking, why not combine the old block with the current blast doors.

- Sketchup model on connecting doors
![](https://cdn.discordapp.com/attachments/406664114249793536/698746644610416680/unknown.png)

- Skywanderers recreation
![](https://cdn.discordapp.com/attachments/406664114249793536/699775512024973392/unknown.png)

A ship would request docking like the landing pads. Then the designated blast doors on each ship will connect to each other, see the pictures above. Since the doors are prefabs and not custom child entity doors, they would be able to connect. Then you and future NPCs can cross into the other ship without needing to spacewalk.

This model above was made by ProPeach. I would also recommend that the blast door’s model be changed to something like the above picture. Not just because it would work with the docking idea, but that it removes the door part clipping past its frame, see picture below. It also looks really good.
- Picture how current door when opened will clip though blocks.
![](https://cdn.discordapp.com/attachments/406664114249793536/698746661001756733/unknown.png)

**Comment by tsunamayo** [comment]
Thanks a lot for the suggestion, yes I will need a comprensive docking solution, and you are right on the money of what I wanted to do.
 - Airlock that match the old system like you explain, I had in mind something more circular, with a cool door opening mechanism, like the trap door of the Millenium Falcom if you know what I mean. So a 2x2 door but with a smaller door so it dont get into the neighboor block when opened.
 - Magnet lock for ship in ship. Here you park your small ship aproximatively and then activate the lock. Small ship will stay in place. When the lock is on a child entity you can then move it around, which should be cool.
Thanks

**Comment by ExodistSKY1** [comment]
Would it be possible to add more variance and customization (possibly a selection system with pre-made ways of opening/looks) because having only one style in a game that is catering towards creative freedom is limiting. I would love to see the round and a squared stretch version of these get implemented!

Magnet lock for ships are fantastic!!! and having the ability for them to be on child entities brings a few ideas to my mind!   REALLY looking forward to this

**Comment by tsunamayo** [comment]
If it is stretching then it defeat the purpose of a standardized dock ;) !

**Comment by ProPeach** [comment]
That's actually something I wanted to tackle with the design I made that Zach shows. In the middle of the first picture a 2x2 door docks with a 2x1 door by only opening halfway. This way the doors can stretch in one dimension (width) but still dock together. You could even stretch their height axis if the doors had 3 parts with one coming down vertically and two coming in from either side.
![image](https://user-images.githubusercontent.com/27857711/79931627-51e72700-8443-11ea-958f-501ff9e06319.png)

**Comment by Garrett-C** [comment]
Would be nice to have a 3x3 door as well because having odd widths is nice.

**Comment by Spectre25** [comment]
What about just making a standard size circular docking collar that extends out a few meters, like the collar on the Rocinante in the Expanse, and leave the door designs to the players?
Personally I prefer hexagonal shaped doors so being restricted to one type of door that will only work for docking will really break a lot of my design aesthetics.

![airlock](https://user-images.githubusercontent.com/63756032/80025357-bfc03c80-849d-11ea-9401-e9d64df16c95.jpg)

**Comment by Spectre25** [comment]
Realized during the Discord discussion, I may not have described this idea well enough.
What I am referring to is a standardized block that can be placed over user created doors, that will extend out like the collar from the Rocinante or like the bridge from X-Men (linked below) and will act as the universal/standardized Docking block. 
This way people can still build doors that fit the aesthetic of there ship without being forced to used a plain square door...
[https://youtu.be/65tdVpymXtI?t=102](url)
