### ISSUE TITLE
[Dev Asks] Some people available later on today to shoot some trailer?

### ISSUE THREAD

**Issue by tsunamayo** [tsunamayo/Starship-EVO#1759]
Yo guys, I wanted to popup on the discord but as I changed phone I cannot log because of the crappy 2 factor id.
Anyway I just want to shoot a few quick scene with few people, just wanted to see who was up to shoot a trailer, in a few hours...
I will try to solve the discord mess...

**Comment by Xerma** [comment]
Do you know roughly when that might be? I should be available for 4 or 5 more hours

**Comment by Womble-TC** [comment]
I'd be down to help, but timezones are annoying. Do you have a time in mind we can all meet?

**Comment by Womble-TC** [comment]
also, if you want to make a new account for discord, let us know, we can give you the dev role again

**Comment by tsunamayo** [comment]
I want to fix a bunch more things, yes worst case I create a new account. Up to when are you available @Womble-TC ?

**Comment by Womble-TC** [comment]
Well it's 2am for me now and I should probably get some sleep, so I probably won't be free for a few hours sadly. If I'm not around for filming, is there anything you need built for this trailer?

**Comment by tsunamayo** [comment]
yes sure go to sleep ;)

**Comment by Womble-TC** [comment]
Will do, just let us know if there are any specific spaceships you need

**Comment by tsunamayo** [comment]
I dont think there is time for building at this point, if you have anything not sw replica you can send me ;)
No pressure, I shoot with what I have. Not falling in the old steam greenlight mistake where making the whole thing took a week.

**Comment by ProPeach** [comment]
Isn't it a little early to shoot the whole trailer? Getting it prepared and ready soon would be great, but there are many very eye-catching and iconic parts of the game that aren't in the current build. The galaxy holo map or warping for example are both things that looked incredible in last trailers, it would be a shame not to use them in the next one.

We're also very happy to build more specific ships and environments so that you don't have to shoot with what you have, you can think up any trailer you like and we'll supply the builds to shoot it.

**Comment by Aiwii** [comment]
Wait is this actually happening? I'll be up for it!

**Comment by ZachZent** [comment]
AND MY AXE!

I do have a nice looking shuttle that is ready to go

**Comment by Sullos** [comment]
Always available to help. :) I have a few ships available, however, most don't have interiors. Only exteriors that look semi-okay.

**Comment by ExodistSKY1** [comment]
Ill be available whenever 
![20200415122736_1](https://user-images.githubusercontent.com/45324484/79368689-6c864100-7f15-11ea-896e-3c7fa6bc316f.jpg)
![20200412142026_1](https://user-images.githubusercontent.com/45324484/79368694-6e500480-7f15-11ea-8097-c439a3fd6ecd.jpg)

**Comment by Womble-TC** [comment]
Since I probably wont be awake for filming, I made a little fighter if you needed one for the trailer
[pitBull.zip](https://github.com/tsunamayo/Skywanderers/files/4483936/pitBull.zip)

**Comment by tsunamayo** [comment]
Okay thanks you all, I am dropping in the discord in a few, lets see who's there!
