### ISSUE TITLE
[BUG] In MP, players cant see the AI enemy ship

### ISSUE THREAD

**Issue by Womble-TC** [tsunamayo/Starship-EVO#1762]
When In Multiplayer, if the host spawns in an AI ship with F8, only they can see it. For all clients on the server, the ship is invisible, yet they can still lock onto it while using a ship, and get shot by it (no ship that small has a cloaking device!)
  20w16b

**Comment by tsunamayo** [comment]
This should be fixed in recent builds. Thanks
