### ISSUE TITLE
[Bug] Lighting artifacts

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#1763]
### Short Description of the issue:
A couple of points where light seeps though

From inside
![image](https://user-images.githubusercontent.com/27857711/79348335-ca725300-7f2c-11ea-83dc-a42c38460dda.png)

From outside, it looks like the artifacts were created at the thinnest possible point in the hull
![image](https://user-images.githubusercontent.com/27857711/79348432-e83fb800-7f2c-11ea-8bfa-c3fb76faa59b.png)

Another, more prominent example of the light leaking
![image](https://user-images.githubusercontent.com/27857711/79352915-53d85400-7f32-11ea-8951-d77e5da1dd22.png)

### Steps to reproduce the issue:
Build a test piece like this with slopes and tetras, the artifacts will appear at the point where the hull is thinnest
![image](https://user-images.githubusercontent.com/27857711/79349292-f8a46280-7f2d-11ea-9b75-0fa4d9b92897.png)

### Environment
- Skywanderers version: 20w16b
- Graphics Card: RX 580

**Comment by AfterRebelion** [comment]
![imagen](https://user-images.githubusercontent.com/559819/79384265-cebb6200-7f66-11ea-9fe5-38dfc7717d7d.png)
Simple example showcasing lighting errors. All blocks, no block streched.
Composition:
4 hull full blocks in the back as background.
1 hull full block on the low right
1 hull slope block on the top left

**Comment by tsunamayo** [comment]
Yes these are classical shadow mapping artifacts.
