### ISSUE TITLE
[Bug] Keymapping menu blank

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#1764]
### Short Description of the issue:
When you open the keymapping menu from in game, it shows up empty
![image](https://user-images.githubusercontent.com/27857711/79350115-f5f63d00-7f2e-11ea-85d7-ab8d938a0bb7.png)

### Steps to reproduce the issue:
I haven't been able to find an exact and reliable cause, but it's been more likely to occur the longer I have the session open. I'll update the thread if I find anything new

### Environment
- Skywanderers version: 20w16b
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
Was it okay on the previous build? Thanks

**Comment by ProPeach** [comment]
I've heard of it happening to people before, but this is the first time for me

**Comment by tsunamayo** [comment]
Indeed I just saw this the other day... Thanks for reporting this!

**Comment by ProPeach** [comment]
Is this still on your radar? It happened again today

**Comment by tsunamayo** [comment]
@ProPeach did you had this recently?

**Comment by tsunamayo** [comment]
I guess this was the same as #2221... Cheers
