### ISSUE TITLE
[Bug] Unable to place blocks 

### ISSUE THREAD

**Issue by Drillz007** [tsunamayo/Starship-EVO#1766]
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4483787/output_log.txt)

### Short Description of the issue:
Able to place starting ship block but unable to attach any block to it some times i can place a single block. 
Unable to delete blocks even on existing designs 
no white block outline for blocks 
...

### Steps to reproduce the issue:

...

### Environment
- Skywanderers version: 20w16b
- Graphics Card: asus geforce gtx 1050ti

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4483816/output_log.txt)
 
### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Was it okay for you on the patch before (or maybe you resumed playing on 20w16b). Thanks

**Comment by Drillz007** [comment]
in previous patches I did not have this issue it started on 11th which is
the first time I started the game up in a few months the issue was not to
bad then I was barely able to replace some blocks on a ship design but
since then it got worse until the 14 where I could not place anything

**Comment by tsunamayo** [comment]
@Drillz007 okay with the latest build 20w17c, are you able to put block? Sorry I was busy on the trailer / early access thing.

**Comment by Drillz007** [comment]
placing and removing blocks is flawless now however i did find this 
![image](https://user-images.githubusercontent.com/63330810/80141783-bbfcea80-856f-11ea-833f-5ec3e8ed9dce.png) 
not to serious of an issue but should probably be looked at
