### ISSUE TITLE
Medium/Larger Ship Lag (Near Torus)

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#1771]
### Short Description of the issue:
I've noticed some very sharp fps drops when entering the yoke on my "sphere" build recently. It's size is roughly 250m in diameter and has a volume of about 15,000,000m^3. It's well within the rough estimates for survival size limits that you have mentioned plus this issue only started up just recently. I used to be able to fly it with a few frame drops but now it cuts right in half just when entering the yoke and remains there so long as you're still using it but after you exit the yoke the frames return back to normal.

For further context, the build is somewhat close to the torus but well over 500m away.

This issue seemed to appear right around the same time I began experiencing the laggy mirror, issue #1660 

I do also hope that you don't look at this as a reason to greatly reduce the max build limit even further because that would not be good for the game at all. Nobody within the community would like that and I really do think it would bad for the game to go that route. Not saying you will but I just wanted to say it and be sure.

### Big find
This issue seems to be because the build is that distance from the torus. I spawned the same ship much further away and didn't experience any frame drops when entering the yoke or piloting the ship.

This is also safe to say that it's a more recent event because I was building this ship this close to the torus ever since we got the torus back and had no issues up until now.
...

### Environment
- Skywanderers version: 20w16b
- Graphics Card: GTX 970

### Additional information:

Ship stats:
![20200417171923_1](https://user-images.githubusercontent.com/32974671/79619549-d861d880-80d2-11ea-8883-dbcf81fbb84c.jpg)

Near the torus (Not piloting):
![20200417171834_1](https://user-images.githubusercontent.com/32974671/79619495-af414800-80d2-11ea-9fce-fc8354857a2b.jpg)
![20200417171843_1](https://user-images.githubusercontent.com/32974671/79619511-b9fbdd00-80d2-11ea-9095-908f177e0363.jpg)

Near the torus (Piloting):
![20200417171902_1](https://user-images.githubusercontent.com/32974671/79619518-bec09100-80d2-11ea-932c-3d35bdf04ed5.jpg)

Away from the torus (Piloting):
![20200417173800_1](https://user-images.githubusercontent.com/32974671/79619598-fe877880-80d2-11ea-883e-12c20f8959d5.jpg)

**Comment by tsunamayo** [comment]
I think this should be linked to the collision system, but this should have been happening since quite a bit of time (like a couple of month). You can send me your build so I can confirm.
Anyway I plan to add a LOD algo to improve perf on large build, this should make collision with torus a lot faster. 
Thanks

**Comment by Xerma** [comment]
[Cake Bol 3.zip](https://github.com/tsunamayo/Skywanderers/files/4496112/Cake.Bol.3.zip)

**Comment by tsunamayo** [comment]
In latest version the collisions with very large entity have been really improved. It could still lag due to a high number of children entity though. Cheers
