### ISSUE TITLE
[Bug] Sticker visual error

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#1772]
### Short Description of the issue:
![Skywanderers Sticker Artifacts](https://user-images.githubusercontent.com/27857711/79639226-487b6780-8182-11ea-8a7a-6ac3f37cd618.gif)
![image](https://user-images.githubusercontent.com/27857711/79639409-8a58dd80-8183-11ea-9833-4a56468ab274.png)

When you place a sticker up against a brick with a quarter brick offset, the sticker barely overlaps and produces this odd flashing edge. This does not happen when the sticker is up against a full brick, or a half brick offset

### Steps to reproduce the issue:
Place a thin tile, then place a square sticker next to it.

### Environment
- Skywanderers version: 20w16c
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
Issue finally fixed for 20w29d. Thanks!
