### ISSUE TITLE
LSD mode hovercraft crash

### ISSUE THREAD

**Issue by kaasci** [tsunamayo/Starship-EVO#1775]
### Short Description of the issue:
Basically went lsd mode and instantly crashed
...

### Steps to reproduce the issue:
Attempted to activate a very bare bones hovercraft, ended up backwards and in lsd mode before crash.
Hovercraft was two hull blocks with a reactor on the front, alog with a seat on the rear block and a joystick in the middle connexcted to a hovercraft computer ontop of the reactor. Hovercraft engines attacked in the front and backmost bottom side corners, as well as two more on the bottom frontmost corner of the side of the middle (hull) block.
Starter block was removed.
...

### Environment
- Skywanderers version: 
20w16c
- Graphics Card: 
GTX 1060 6GB
### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4498108/output_log.txt)
![lsd-mode](https://user-images.githubusercontent.com/29951625/79674623-c9674d00-81dc-11ea-92d7-86caf6c94b1e.gif)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Hum sounds bad, could you send me your blueprint so I can check if there something wrong with it? Cheers

**Comment by kaasci** [comment]
I tried twice, the first time it crashed and looked like this:
![lsd1](https://user-images.githubusercontent.com/29951625/79677568-c6735900-81ea-11ea-96ab-ffad8df590bd.png)
The second time the hovercrashed just vanished:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4498210/output_log.txt)
Here's an overview of the craft, its very simple and every component is visible:

**Comment by tsunamayo** [comment]
I cant reproduce, I have improved the overcraft, could you check in 20w18f? Thanks

**Comment by tsunamayo** [comment]
I think it was an incorrect link issue. Thanks
