### ISSUE TITLE
[Suggestion] I can write YT captions

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#1779]
Since I have a lot of time on my hands anyways due to the Kung-Flu, I can help you out with writing the captions for the YT videos.
I've seen a lot of people on Skywanderers' Reddit reported (or upvoted the report) that they cannot understand the French accent. Since I've got used to it and understand 99-ish % of the video, I can help out.
**In fact, I already have - the captions for the latest video update are waiting for approval.**
You could be sending me a link to not-listed-yet videos every time you upload and I would produce the captions before the video even airs.
It takes me roughly 1 hour to process every 3 minutes of material.
Let me know, if you're interested.

**Comment by Kaiser-Indrasil** [comment]
I might proof-read the Steam page of the game, too.

**Comment by tsunamayo** [comment]
Ho thanks a lot mate I am checking this. Yes I very much want a proofread of the steam page! I will open a thread for that ;)

**Comment by tsunamayo** [comment]
Okay I made the subtitles. Next time I will try to give you an heads-up, otherwise it is fine if it come a bit after release I guess.
Thanks a lot for doing this!
Cheers
