### ISSUE TITLE
[Dev Needs Help] Steam store page proofreading + improvements

### ISSUE THREAD

**Issue by tsunamayo** [tsunamayo/Starship-EVO#1782]
Hello hello,
So my steam page is live, but my broken engrish is showing.
If you see any crappy text please shoot!
Suggestion are also welcomed. 
What would you write to make it pop more!
Cheers

**Comment by Kaiser-Indrasil** [comment]
> Make use of a comprehensive selection of logic bricks and mechanism like sliders

mechanisms*

> Experiment and design the weapons that fits your style!

weapon* (or, if you wanted it in plural) ~~the~~ weapons that fit*

> Fight NPCs or friends in tense space battle

battles*

> Play as a human male or female, or as one of four Aliens race.

Alien races*

As for suggestions, I would highlight some of the strenghts of the game's building mechanics. Feel free to use them directly on the Steam Page:
- With bricks as small as 25 centimeters, and the ability to offset them, you can easily build that over-greebed starship replica you've always wanted.
- The collision boxes are surgically tight, so all the ramps, hatches, and other child-entities slide in just right into their compartments, looking flush with the rest of the armour plating.

**Comment by ProPeach** [comment]
I agree with Kaiser, the build system is the absolute jewel of this game right now and you need to show it off!

"Build like you never did before!" changed to "Build like you never have before!" 

I know it might be tough to put things down in writing, but some kind of idea about what the game will turn into after EA release would help a lot. Right now it focuses on the current state of the game which is great of course, but potential players would be a lot happier to buy if they knew about all the other awesome stuff you're planning to add too.

**Comment by ExodistSKY1** [comment]
Possibly a GIF showing off each thing (I am sure the community would love to help with this, allowing you to focus on the things you need to get done)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil mate those are some incredible build! Definitely wants to showcase the yamato in the channel, if you are willing to send a blueprint. Bomber is shaping up nicely also!
Yes if you can take some nice gif or video that would be great! I will be asking for a lot of cool contraptions, landing gear, cockpit, anything!
Also I am working on better physics for children entity (ie children will push the master entity - which is not the case atm), so we can make some cool build using that! This will be needed for Mechs or Rovers.
Cheers

**Comment by Kaiser-Indrasil** [comment]
> Also I am working on better physics for children entity (ie children will push the master entity - which is not the case atm), so we can make some cool build using that! This will be needed for Mechs or Rovers.

Colour me excited!

As for the Yamato and the bomber, these are The Domovoi's builds, not mine ;D You'd have to ask them. I've mentioned this topic to them in Discord.
