### ISSUE TITLE
Child entity collision boxes

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Starship-EVO#1783]
### Short Description of the issue:
I was working on a large hangar door and was going to have it meet with 2 slopes however it appears that the collisions on these don't quite work. One weird part is that they don't seem to comply with what would be the square collision but they also don't seem to comply with the triangular one. 
![image](https://user-images.githubusercontent.com/43644633/79925083-5b679380-8431-11ea-9fc7-3846c6df24f3.png)

**Comment by tsunamayo** [comment]
Send me a blueprint! I know I have one "bug" to fix for wedge/tetra ect, it might be related to this - but hard to see on that screenshot. Cheers

**Comment by Garrett-C** [comment]
I replaced it in the build but have replicated it for you on top of the ship. 

![image](https://user-images.githubusercontent.com/43644633/80026443-0d5a9a80-84da-11ea-8869-6ade7ae0e4af.png)

[Cargo Boy with issue.zip](https://github.com/tsunamayo/Skywanderers/files/4518650/Cargo.Boy.with.issue.zip)

**Comment by tsunamayo** [comment]
Woa nice beefee ship mate ;)
Issue fixed for 20w17f. Thanks
