### ISSUE TITLE
Drone displays wrong orientation of ship

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#1785]
### Short Description of the issue:
Not sure how relevant this bug is considering the drone is getting removed but in the drone menu the ship is displayed how it originally was built where the spaceship core displays it correctly. However, the spaceship core is much more zoomed and clips into the display a bit.

I also want to note that trying to spin the display is a bit funky and takes multiple drags to rotate it but sometimes it's extremely difficult to rotate in the first place.
...

### Environment
- Skywanderers version: 20w16c
- Graphics Card: GTX 970

### Additional information:
![20200421220513_1](https://user-images.githubusercontent.com/32974671/79936286-a6c37700-841c-11ea-92a6-31ad356b071b.jpg)
![20200421220605_1](https://user-images.githubusercontent.com/32974671/79936288-a7f4a400-841c-11ea-82a4-86824e8bd871.jpg)

**Comment by tsunamayo** [comment]
Great, all issues are fixed for 20w17e. Cheers
