### ISSUE TITLE
Shield generator doesn’t produce heat

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Starship-EVO#1786]
### Short Description of the issue:
It appears that shield blocks currently don’t produce any heat. I am fairly certain they are supposed to but I haven’t seen them do this, unless they only do it when regenerating or something. 

### Steps to reproduce the issue
Place a shield block.
Look at heat generation.

**Comment by Xerma** [comment]
The shield block also doesn't display any heat information

**Comment by tsunamayo** [comment]
Okay both issue are fixed for 20w17d. Thanks!
