### ISSUE TITLE
Game crash when piloting a hovercraft

### ISSUE THREAD

**Issue by ItsCrusade** [tsunamayo/Starship-EVO#1792]
### Short Description of the issue:
Game crash when piloting a hovercraft
...

### Steps to reproduce the issue:
1. Build a basic hovercraft on the habitation ring (yoke, reactors, repulsors, hover controller)
2. Attempt to pilot the entity
...

### Environment
- Skywanderers version: 
20w17a

- Graphics Card: 
GTX 1070ti

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: 
The latest log is not dated from the crashes - seems to be a CTD without logging.

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4516232/output_log.txt)

`%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Could you please send me your blueprint file? Thanks

**Comment by tsunamayo** [comment]
I cant reproduce, I have improved the overcraft, could you check in 20w18f? Thanks

**Comment by ItsCrusade** [comment]
Hi sorry!
I did further testing - I've been busy with work.

The crash happens if the hovercraft core is linked to the hover modules.
Causes a game crash as soon as you pilot the vehicle.

**Comment by tsunamayo** [comment]
@ItsCrusade okay amazing investigation! I will try to reproduce and prevent that! Thanks

**Comment by tsunamayo** [comment]
I did manage to reproduce some issue, but no crash. In any case this is now prevented as you cannot link them this way, you will get an warning message. Thanks!

**Comment by ItsCrusade** [comment]
I can put together a blueprint that causes it - I never saved/used a
blueprint to make it happen.
