### ISSUE TITLE
Child entities vanish after the 20w17a update

### ISSUE THREAD

**Issue by OldIronsides** [tsunamayo/Starship-EVO#1793]
### Short Description of the issue:
Hello Tsuna, i have been working on a large ship with a probably unhealthy amount of child entities. In this last update i managed to load the blueprint following your instructions, and other smaller ships have their rotors/child entities in place, only this one has not. They don't seem invisible, and i tried different blueprints for the same ship without change, which makes me think its more about the size/number of them.
...

### Steps to reproduce the issue:
Game updated in the 22nd, and upon copy-pasting the blueprint, the game only loads the main hull, rotors, hinges and the attached entities have vanished,
...

### Environment
- Skywanderers version: 20w17a 
- Graphics Card: NVIDIA GeForce GTX 765M

### Additional information:
Before the update: (i know, its too many, but i have been working on reducing them)
![dfghjk](https://user-images.githubusercontent.com/51378714/79999794-bbdaed00-8492-11ea-981f-b91801c948de.png)

After the update:
![missing turrets](https://user-images.githubusercontent.com/51378714/79999216-0b6ce900-8492-11ea-9a60-5410d7f75447.png)

Output Log
https://www.dropbox.com/s/rvhqrlv70h0o11a/output_log.txt?dl=0

Update: It seems the vanishing is indeed related with you moving the character while the ship is loading. I tried not moving at all and the ship eventually spawned with the child entities.

**Comment by ExodistSKY1** [comment]
Did you move your character at any time before it was loaded in?   My larger builds with child entities will not load in the child entities if you speedily move your character before it is fully spawned in.

**Comment by tsunamayo** [comment]
It should not work like that, so still a bug even if it is that. Havent loaded the ship yet @OldIronsides but it looks mesmerizing. I keep you posted.
Cheers

**Comment by ExodistSKY1** [comment]
@tsunamayo  it is reproduced more easily when you are moving faster

**Comment by OldIronsides** [comment]
Update 2: not sure if something changed, but upon logging in, not only the child entities of the big ship disappeared, now all entities are gone. those were ships already spawned in, so not related to the previous issue i think. still a bit troublesome, as now that the game saves upon exit, the ships were saved like that.

**Comment by tsunamayo** [comment]
@OldIronsides could you send me your save file? Send me the full zipped save folder.

**Comment by OldIronsides** [comment]
> 
> 
> @OldIronsides could you send me your save file? Send me the full zipped save folder.

here it is: 
https://www.dropbox.com/s/4of97koi1bet5ot/save_data.zip?dl=0

Also, i wanted to mention another possible bug. If you decide to close the game while its in the loading screen to your world, you might have all spawned ships erased the next time the game is started. I think it might be because the world is loaded first?, and while the game was loading the ships, i closed the program, and the auto save kicked in saving the world before the ships were loaded. 

( i did it because  i though it was frozen, though i have a huge build spawned that probably is causing it)

**Comment by tsunamayo** [comment]
@OldIronsides do you get this children entity bug only while loading? People report the same bug but when loading two of the same blueprint - the second entity having no children entities.
I loaded you (incredible) build, children entity were there. I was moving all the time...
Thanks

**Comment by OldIronsides** [comment]
I have noticed it happening both upon loading the game itself (child entities are gone after i relaunch the game) and upon loading blueprints, seems to still be happening to me, when i load the world, its about 2mins of loading screen. when i load the yamato its also about a minute loading, and its loads by chunks, but the turrets never come in. maybe there is some relation to the time loading?

**Comment by tsunamayo** [comment]
@OldIronsides so you mean that when loading the game there is children entity on your yamato, but when loading manually the blueprint there is no children entity spawn? Thanks

**Comment by tsunamayo** [comment]
Okay @OldIronsides that dreaded issue is fixed for 20w20c. Sorry it took quite a while but I am happy it is finally gone. Thanks!
btw if you have a newer version of the ship I might want to give a sneek peak on the channel... 
I also want to show this to my japanese brother in law lol.
Thanks!
