### ISSUE TITLE
[Bug] Codex sounds and Logic Linker sounds broken.

### ISSUE THREAD

**Issue by SabreMania** [tsunamayo/Starship-EVO#1794]
Title mostly says it all. The sounds that are made by the codex when you open it, when you hover your mouse above blocks, the sounds when you use tools like the linking logic think and the mirror tool do not respond to the game volume being changed. They are always at 100%, regardless of what you do.

### Steps to reproduce the issue:
Change the game volume and then open the codex. Restarting the game does not fix it
...

### Environment
- Skywanderers version: 20w17a
- Graphics Card: NVIDIA GTX 970

**Comment by Cpt-Fortius** [comment]
It's the same for me too.

**Comment by tsunamayo** [comment]
Okay issue is fixed now, for 20w17d. Thanks!

**Comment by Cpt-Fortius** [comment]
Yes, almost all sounds now play at the correct volume.
Except one: Moving the mouse over items in the codex & hotbar still makes 100% volume clicks.
