### ISSUE TITLE
[Bug] Vertical and Horizontal switched

### ISSUE THREAD

**Issue by SabreMania** [tsunamayo/Starship-EVO#1795]
When you make a turret, the vertical and horizontal options on the rotors are inverted. I have a few turrets, and when I set them up to follow my mice like I usually do, they were all moving in a weird way that didn't correspond to the movements I made. When I inverted the vertical rotor with the horizontal rotor, it was fixed, which is why I believe that they are switched up.
...

### Steps to reproduce the issue:

Make a turret and try to make it follow your mouse movements. 
...

### Environment
- Skywanderers version: 20w17a
- Graphics Card: NVIDIA GTX 970

**Comment by tsunamayo** [comment]
Yes sorry there was a bug, axis were not okay I change them. Label is "Axis pointed to" or something like that, so the new way is correct.
But at the end I want an automatic way, so the player would not have to do the assignment...
Thanks
