### ISSUE TITLE
[Bug] Starter Block offset

### ISSUE THREAD

**Issue by SabreMania** [tsunamayo/Starship-EVO#1796]
The starter block has some kind of weird offset to it when it spawns ships. I haven't been able to test it with more than one ship, because I only have one blueprint that still had it, but this is the result.

...

### Steps to reproduce the issue:

Spawn a blueprint from the previous version of the game.

...

### Environment
- Skywanderers version: 20w17a
- Graphics Card: GTX 970

![image](https://user-images.githubusercontent.com/52141971/80000736-841c7700-848b-11ea-9a90-f29fea322484.png)

**Comment by tsunamayo** [comment]
I dont see much...
Also not sure what is the issue, what do you mean by weird offset?
Now the block start at the middle of the first chunck, which means it is at 8x8x8 position.
But I am not sure on how it is impacting the player in your case...
Cheers

**Comment by SabreMania** [comment]
@tsunamayo Okay, my image is perhaps a bit dark indeed, here is a better picture.
![offsetthing](https://user-images.githubusercontent.com/52141971/80044208-ca94c480-84d1-11ea-80f3-0cb9577bb123.png)

As you can see (hopefully), the block is halfway above the normal block grid, which I don't think is supposed to happen. In any case, it doesn't really affect me for now.

**Comment by tsunamayo** [comment]
Ah okay yes indeed you are right, I added an offset, it is a bit tricky to explain but I needed it. It wont impact beside the fact that you will have to destroy it... You can place it again now. 
No biggies ;) Cheers
