### ISSUE TITLE
[Bug] You can enter the barrels

### ISSUE THREAD

**Issue by SabreMania** [tsunamayo/Starship-EVO#1797]
### Short Description of the issue:

I'm not sure if this is an actual bug as much as an accidental feature, but right now you can enter barrels if they face upwards, and they have an internal collision box that prevents you from moving anywhere else than up. 

While I say it's a bug, I think it's more that they were modeled with a hole, rather than just have a texture that gives the illusion of depth. The latter would take less ressources and achieve the same result
...

### Steps to reproduce the issue:
Place down a Laser weapon against a flat surface, and then place any barrel as much as you can, then slide down into it. It cannot be done if the barrel is facing sideways, it must face the sky (or what from one's perspective would be the sky.)
...

### Environment
- Skywanderers version: 20w17a
- Graphics Card: NVDIEA GTX 970

**Comment by ZachZent** [comment]
![](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Stephanie_smith_human_cannonball_-_melbourne_show_2005.jpg/1200px-Stephanie_smith_human_cannonball_-_melbourne_show_2005.jpg)

**Comment by tsunamayo** [comment]
Haha okay indeed I see, it must be problem with the cap in collider check. You always have the right picture for the job ;)
Thanks

**Comment by tsunamayo** [comment]
Okay issue fixed for 20w17d. Thanks!
