### ISSUE TITLE
[Suggestion] Clear Inventory Option

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Starship-EVO#1800]
### Short Description of the Suggestion:
Not an essential feature but it would be nice to have a button in the UI or way to just clear my entire inventory.

**Comment by Xerma** [comment]
To go along with survival, using shift + left click would work perfectly and is widely used by many games

**Comment by tsunamayo** [comment]
Okay this is implemented, available in 20w17d. Thanks
