### ISSUE TITLE
[Suggestion] Title Screen Music

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#1801]
The title screen music is very loud, could you lower it a bit? Thanks

**Comment by tsunamayo** [comment]
There is a slider in the sound option... You think it is too loud compared to other sounds?

**Comment by Garrett-C** [comment]
For me the slider doesn't seem to save the setting but I am not sure why. Also when you launch a save it tends to shoot up in volume for a second.

**Comment by tsunamayo** [comment]
Yes actually I had this issue but was not able to reproduce it... Are you seeing this all the time?

**Comment by Garrett-C** [comment]
I seem to be yeah. I think it is especially bad if I load into another persons server between my own sessions. This also seems to reset the keybinds.

**Comment by ZachZent** [comment]
A volume slider would defiantly be nice, but at the very least the default title screen sound should be a little lower

**Comment by tsunamayo** [comment]
@Garrett-C the config file (SETTINGS.ini) in the save folder is not in read-only?

**Comment by tsunamayo** [comment]
And there is a music slider already, but yes I will make it lower.

**Comment by tsunamayo** [comment]
okay music is lower by default. Also I should have fixed the sound reset issue and the other reset issue. If you still experience that after 20w17e @Garrett-C  please book a case (I was not able to reproduce 100% of the time)! 
Cheers
