### ISSUE TITLE
3rd Person Camera

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#1802]
### Short Description of the issue:
The third person camera is wayyyy off on newly created entities but seems to be fine on entities that were brought over or made before this update.
...

### Environment
- Skywanderers version: 20w17a
- Graphics Card: GTX 970

### Additional information:
3rd person on ships that were built before the update:
![20200422154919_1](https://user-images.githubusercontent.com/32974671/80032836-5cd8a080-84b1-11ea-9b2a-cf1a4ddf90a8.jpg)
![20200422154942_1](https://user-images.githubusercontent.com/32974671/80032843-5e09cd80-84b1-11ea-8c77-1b2e66b33449.jpg)

3rd person on ships built post update:
![20200422155036_1](https://user-images.githubusercontent.com/32974671/80032861-66620880-84b1-11ea-8110-04469e456b62.jpg)
![20200422155125_1](https://user-images.githubusercontent.com/32974671/80032868-67933580-84b1-11ea-8dd9-44789839e554.jpg)

**Comment by tsunamayo** [comment]
Indeed, issue will be fixed for 20w17b that is dropping very soon. Thanks!
