### ISSUE TITLE
[Things?] Some Media from a Multiplayer Session

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Starship-EVO#1803]
https://imgur.com/a/1Arsk4U

https://imgur.com/gallery/GXN77QC

**Comment by tsunamayo** [comment]
Very cool thanks you! I might want to do a better trailer before the release, I will try to "order" a bunch of things, dont hesitate to continue sending stuff my way! Also please keep your HD file, this is what I would need in case I use them.
Thanks ;)

**Comment by Aiwii** [comment]
No problem! I'll upload my unedited files here: https://drive.google.com/drive/folders/1MNbrYppU_eQ8p97E8xO-sOqTuAc-cfyS?usp=sharing
