### ISSUE TITLE
Can't exit/save multiplayer session

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#1804]
### Short Description of the issue:
Neither the host or joined clients can click exit to desktop - we had to Alt + F4.

It also seems that the new auto saving mechanic does not work in multiplayer at all
...

### Environment
- Skywanderers version: 20w17a
- Graphics Card: GTX 970

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by schlid** [comment]
The auto saving mechanic did not work for me as host; nb the issue occurred on a new character that was created for the session where multiplayer was used.

**Comment by Xerma** [comment]
So this is a bit odd and maybe just on schlid's side but I just had a multiplayer session with Gmunga and everything seems to have saved and worked just fine for me

**Comment by tsunamayo** [comment]
Okay I see, I will investigate. @Xerma did you created a new character or was it an existing one?
Thanks

**Comment by Xerma** [comment]
Existing characters didn't work for me at all so I made a new one, same goes for the instance

**Comment by tsunamayo** [comment]
Yes, so you created a new character and then opened to multiplayer? thx

**Comment by Xerma** [comment]
I made a new character earlier today, opened and closed the game a few times, joined schlid's multiplayer with gmunga, schlid hosted, then schlid couldn't save or exit nor could I exit the game. But a little after that I hosted a game for gmunga to join and it worked just fine.

**Comment by tsunamayo** [comment]
Okay when you said existing character didnt work, what didnt work?
Sorry this is getting complicated to understand what the test case is regarding new character.

**Comment by Xerma** [comment]
My bad, I attempted porting over my old character so I didn't have to redo the hotbars but that broke the game so I ended up just making a new character. What broke was the world was black and all I saw was the multi tool

**Comment by tsunamayo** [comment]
Okay so this is completely different issue I guess.
So could you make a check:
Create a new character and host =>Is there an exit/ save bug?
Use an existing working character and host => is there an exit/ save bug?

Thanks!

**Comment by Xerma** [comment]
I'll try to give it a test as soon as I can but I don't think I'll be available until late tomorrow for me (currently 3:30am :D) Unless @schlid wants to give it a run before I can get to it

**Comment by schlid** [comment]
Currently wfh but I could take a look this evening.

**Comment by tsunamayo** [comment]
I tested on my side and auto-save was  working well in mp, on a new character. 
It might be a different issue that prevented you from saving, if you could send me your output.log there might be issue in there. Thanks!
