### ISSUE TITLE
Panel beveled brick placement issue

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Starship-EVO#1806]
When this brick is placed next to another brick of its same type it can not be placed.

...

refer to reference image below: 
![20200422125336_1](https://user-images.githubusercontent.com/45324484/80047490-2f9cea00-84d3-11ea-8d1c-061923082984.jpg)

...
- Skywanderers version: 20w17a
- Graphics Card: 1080ti

**Comment by tsunamayo** [comment]
Hum I will see what I can do, I dont want to make a special shape for this... This will likely be a long term fix. Thanks

**Comment by ExodistSKY1** [comment]
It has worked in all the past builds, I don't see a reason to make a special shape for it as it is just two of the same blocks, could it just be a collision bug?

**Comment by tsunamayo** [comment]
what do you mean it is two of the same block? Yes collision engine has changed.

**Comment by ExodistSKY1** [comment]
It seems to only be with the Panel beveled brick.

Here are some photos to hopefully show what I am trying to explain:
![20200423012305_1](https://user-images.githubusercontent.com/45324484/80066888-77873580-8502-11ea-9802-1fd5aac7cd85.jpg)
![20200423012309_1](https://user-images.githubusercontent.com/45324484/80066900-7bb35300-8502-11ea-9b97-75031678dbe2.jpg)
![20200423012319_1](https://user-images.githubusercontent.com/45324484/80066909-7eae4380-8502-11ea-82a6-d2df11ce5249.jpg)
![20200423012724_1](https://user-images.githubusercontent.com/45324484/80066914-81109d80-8502-11ea-843b-c31fbe0ae050.jpg)
![20200423012734_1](https://user-images.githubusercontent.com/45324484/80066917-8241ca80-8502-11ea-9632-984f7f4bfcc7.jpg)

All other bricks work so far! it is just this particular one

**Comment by tsunamayo** [comment]
Yes I know ;) it is because its collision check is a box... This is why I said it needs a specific collision shape...

**Comment by ExodistSKY1** [comment]
ahh, okay I was under the impression the shape of the block was the shape of the collision it has in the new collision system.
