### ISSUE TITLE
[Bug?] Building Core Inclusion

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Starship-EVO#1808]
### Short Description of the issue:
Now with the new Building Core, it has to be included in a build for it to be saved meaning that all ships need to include it in their design. This may be problematic for small ships.
...

### Steps to reproduce the issue:
Can't save without core.
![image](https://user-images.githubusercontent.com/53021785/80052164-3fb6c880-84d7-11ea-9265-6870f10b6ae7.png)

...

### Environment
- Skywanderers version: 20w17b
- Graphics Card: Integrated Graphics

### Additional information:
On a larger ship: 
![image](https://user-images.githubusercontent.com/53021785/80052185-4cd3b780-84d7-11ea-80e2-34800a322a88.png)

On a smaller ship: 
![image](https://user-images.githubusercontent.com/53021785/80052240-742a8480-84d7-11ea-968b-dc4b169fc44d.png)
Nowhere for me to place the core meaning I can't save it

**Comment by ExodistSKY1** [comment]
making a singular brick block version could work?

**Comment by Aiwii** [comment]
![image](https://user-images.githubusercontent.com/53021785/80052978-1bf48200-84d9-11ea-9e7a-8f841a8bcc9d.png)
I think we already have a solution

**Comment by tsunamayo** [comment]
Yes I can make it a brick for now.

**Comment by tsunamayo** [comment]
Okay this will be a brick for 20w17c. Thanks!
