### ISSUE TITLE
Window side & Hull Slab in hot bar

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Starship-EVO#1809]
window side: 
![20200422202831_1](https://user-images.githubusercontent.com/45324484/80049347-3c700c80-84d8-11ea-9ae1-813efc27e5c1.jpg)
Suggestion-
Are you keeping this thin version in game? If so can you make it brick, and thin the border around the glass for better visibility?

Hull slab:
![20200422202832_1](https://user-images.githubusercontent.com/45324484/80052535-84932d00-84e0-11ea-8d57-5a86754485a6.jpg)

Steps to reproduce the issue:

In hot bar on startup

...

### Environment
- Skywanderers version: 20w17a
- Graphics Card: 1080ti

**Comment by Aiwii** [comment]
The thin non-brick version fits with the other canopy bricks tho, I don't know about converting it to a brick...

**Comment by tsunamayo** [comment]
You mean on a new character start? @ExodistSKY1

**Comment by ExodistSKY1** [comment]
Yes, upon new player start!

 I think it might be what you had in your hot bar upon the release?

**Comment by ExodistSKY1** [comment]
![20200422102432_1](https://user-images.githubusercontent.com/45324484/80053635-0421fb80-84e3-11ea-936c-07796ab81faa.jpg)
as for the windows, the thin version was previously removed, and it is on the block grid as opposed to the brick grid making it irritating to work with unless planned from the start on brick builds.

**Comment by tsunamayo** [comment]
No I am removing that block. Yes I reproduced the issue!

**Comment by tsunamayo** [comment]
Okay will be fixed for 20w17c. Patch should come today! Cheers

**Comment by ExodistSKY1** [comment]
Perfect!
