### ISSUE TITLE
[Suggestion] core/screen displays

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Starship-EVO#1810]
I think the separation in the lines is a little bit too much on the eyes. Possibly using the crispness of the screens on the left for the other?

Do you think the crispness of the left screens are more appealing and easier to read?  
![20200412141620_1](https://user-images.githubusercontent.com/45324484/80055910-82cd6780-84e8-11ea-9722-4f409629bce0.jpg)

Another image showing the blurriness 
![20200412141515_1](https://user-images.githubusercontent.com/45324484/80056071-f3748400-84e8-11ea-9860-32a05baffa7c.jpg)

**Comment by tsunamayo** [comment]
You mean the scanline effect or the rbg layers?

**Comment by ExodistSKY1** [comment]
I think the scan line effect, this could be just me, but I feel it might be better having it less prominent

**Comment by tsunamayo** [comment]
Yes I agree, I want to do another pass... worst case if I dont have time I will remove it before ea. There is  room to make some cool looking VFX!

**Comment by ExodistSKY1** [comment]
That would be awesome and a small detail that is extremely appealing!
