### ISSUE TITLE
[Kickstarter Discussion] What are our limitations

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Starship-EVO#1811]
Hey there Tsuna, I'm opening this thread for your help and also input from others on how the Kickstarter backer ships should work.

Starting at the Explorer Rank:
* Build a 20m civilian shuttle

You mentioned in the building guide that these shuttles can now be 30m
I think most people are accepting of the fact that civilian shuttles don't really need weapons on them.

Entrepreneur Rank:
* Build a 100m civilian ship
* Build a 20m civilian shuttle

Here is where I believe there starts to be a problem. Whilst we don't know what the game will be like once its got survival mechanics, there seems to be questions regarding what sort of things our civilian ships could be, and if we can have weapons on them. As it stands a 100m ship is a big prize if attacked by pirates, or other players, especially if they don't have weapons. The way I picture it is that if I build my 100m ship it will just a ship floating around in the game that's easy to attack, loot, and destroy if it has no weapons.

I propose a general rule could be put in place saying that if you want your ship to have weapons on it, it is limited to 1 small-medium sized weapon per 50m. This means that some civilian ships can have a very basic 'defense' arsenal on board to prevent raiding. 
In terms of progression, a new player with a very minimal ship coming across a big civilian ship, just being able to fly up to it and take it over, seems very far jumping in progression standards.

Next up is what sort of themes we can have about or ships. Are we allowed to create a generalized look and feel to our ships? If I create a 30m shuttle and a 100m ship, can they be similar in their style so that they look like they could be produced by the same manufacturer or possibly be from a corporation? Or should we be making them look more generalized? What sort of stuff are you after? :)

The future ranks don't quite play into account yet, as pirate ships and corporate stations etc need more work. But similar questions will apply to them, like weapon limitations and other such things.

<img width="718" alt="sevo backer rewards" src="https://user-images.githubusercontent.com/33239800/80056158-e9916600-8566-11ea-8db1-084f52ae47d1.PNG">

Also, I think there might be a problem with the 2nd step. Asking for us to put our Steam key here. If I had the ability to create 4 ships for the game and I only post one with my verification key, what stops someone else from taking the key and trying to get a ship added to the game using my key.
I suggest perhaps making the Post include everything else, and then do a confirmation privately either through discord messaging or an email.

Thanks Tsuna, hope I haven't scared you off with this essay.

**Comment by tsunamayo** [comment]
@Sullos thanks for the input, could you please move the discussion to the backers github (copy the post)? No pb I expect to get quite a few question around here.
Cheers

**Comment by Sullos** [comment]
Moved now :)
