### ISSUE TITLE
[Suggestion] Learning the game

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Starship-EVO#1812]
You recently mentioned making the game easy to pick up and I thought I would move this to its own thread.

The game should be easy to pick up and whilst for me it seems that way, it seems some other people really struggle. I don't know why, but the discord can get swamped with people asking for help. 
Having a starting world already in the game with a tutorial room that they can walk through would be very helpful.
Simply have the game preload with a Character/world already there, set to creative mode that people can load up and explore how to play the game with. 
I'm sure the community would be more than willing to help make these tutorial rooms if we have the tools to do so, especially with so many people trying out MP whenever they can, gives a chance to build as a community.

Off the top of my head, we would need the ability to write things as text on signs, like in the old tutorial rooms. But I can't think of much else that would be mandatory, the hovering item holders were handy too come to think of it.

Thanks Tsuna!

**Comment by tsunamayo** [comment]
Yes I want to do that again. I will give a build with torus raycast soon, so we can build on it.
What people are asking? This is very valuable for me? Cheers

**Comment by ZachZent** [comment]
Have a voice tutorial led by FR-3N
https://cdn.discordapp.com/emojis/508855604086046721.png?v=1
Voiced by Morgan Freeman. Ok maybe not that

**Comment by Aiwii** [comment]
Things people have asked on the Discord
- How to spawn and despawn ships [How to use the Building Core]
- Rotor and Mechanism Questions [How to set rotation and stuff]
- Keybind and Control Questions [What are the F1-12 keys for]
- How to set up a ship [How to Build a Working Craft]
- How to set up a turret [How to Build a Functioning Turret]

**Comment by tsunamayo** [comment]
Hopefully with the tutorial and some in-game help is it better now (still could be improved...) Cheers
