### ISSUE TITLE
[Bug] Little Turrets dont shoot any longer

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Starship-EVO#1816]
### Short Description of the issue:
Since the update 20w17a  the small turrets on all my entitys dont shoot any longer.

### Steps to reproduce the issue:
Spawn any ship with turrets and small weapons. 
I don't know if the weapon size makes the difference, but the two big turrets on the capitalship are the only ones that still fire, all the others just aim but no longer fire. I also tried reset etc.
Manual shooting works.

### Environment
- Skywanderers version: 20w17c
- Graphics Card: gtx 1070 mobile

### Additional information:

![Starship EVO_2020_04_23_09_04_08_012](https://user-images.githubusercontent.com/43222403/80069837-50505880-8542-11ea-923b-5702f38c65b3.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4520809/output_log.txt)

[Blueprints.zip](https://github.com/tsunamayo/Starship-EVO/files/4520828/Blueprints.zip)

**Comment by tsunamayo** [comment]
These are auto-turret? Please send the blueprint so I can investigate.
Thanks

**Comment by Battlepixel** [comment]
Yes they are, I ve added the blueprints. But also the little Turret in the fighter which is in Spaceship-targetting-mode dont shoot any longer. All turrets worked before.

**Comment by tsunamayo** [comment]
Okay I havent test the big ship, but it should be fixed now, it was an issue on bricks. Fix on 20w17e. Thanks a lot!
