### ISSUE TITLE
[Bug] Can't use landing pads

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Starship-EVO#1821]
### Short Description of the issue:
When attempting to use a landing pad, the automated sequence doesn't complete itself, leaving the ships on the pad shaking without showing the menu options. The only option left is to cancel the landing and break the pad.
![image](https://user-images.githubusercontent.com/53021785/80145173-fdd86180-856c-11ea-9cd9-4b5f272d4278.png)

...

### Steps to reproduce the issue:
Attempt to land a ship
...

### Environment
- Skywanderers version: 20w17c
- Graphics Card: Integrated Graphics

### Additional information:
![image](https://user-images.githubusercontent.com/53021785/80145595-a8508480-856d-11ea-8b14-3cc58a57f63c.png)
Problem occurs even when ships fit the landing pad
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4525007/output_log.txt)

**Comment by tsunamayo** [comment]
Issue should be fixed in 20w18c, there is now a smarter stop check. Thanks
