### ISSUE TITLE
[Bug] Cancelling Landings Breaks Pads

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Starship-EVO#1822]
### Short Description of the issue:
If you cancel a landing for whatever reason it breaks the pad and prevents one from using it again until the game is reloaded. 
![image](https://user-images.githubusercontent.com/53021785/80145787-f6658800-856d-11ea-9fbb-8fd45dc71b15.png)

...

### Steps to reproduce the issue:
Cancel a landing and attempt to use the pad again.
...

### Environment
- Skywanderers version: 20w17c
- Graphics Card: Integrated Graphics

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4525040/output_log.txt)

**Comment by tsunamayo** [comment]
From 20w18c you can cancel your landing request and it will free this landing pad. Thanks
