### ISSUE TITLE
[Question] Font

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#1823]
What the the font of the text in the logo both top and bottom? Or at least a similar one.

![](https://cdn.discordapp.com/attachments/271723356795961345/701671528596504596/sEVO_Logo_Rip.png)

**Comment by tsunamayo** [comment]
![Starship EVO 1500px](https://user-images.githubusercontent.com/6604318/80167121-89f49280-861a-11ea-81de-1b263043741a.png)
The EVO font is called heatwave, the Starship one is called Osiris. I can give them to you on discord.

**Comment by ZachZent** [comment]
That is great! Thanks
