### ISSUE TITLE
[Bug] Corner UI element Issues

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Starship-EVO#1824]
### Short Description of the issue:
The corner UI is a bit broken.
- When a ship gets destroyed the corner menu shows the destroyed label on every other selected object after the destruction.

**before**
![image](https://user-images.githubusercontent.com/53021785/80147652-0fbc0380-8571-11ea-965b-e98286bf334b.png)

**destroy a ship**
![image](https://user-images.githubusercontent.com/53021785/80147675-19456b80-8571-11ea-8d37-ef005b300e8c.png)

**now landing pad is destroyed**
![image](https://user-images.githubusercontent.com/53021785/80147701-219da680-8571-11ea-9c3d-cf6f7c717c62.png)

- Additionally, the red and green text from the landing pads 'Cat: X' information carries over to ship information and makes the distance red or green

**before**
![image](https://user-images.githubusercontent.com/53021785/80148235-f9627780-8571-11ea-9d1b-cdf797038dfb.png)

**select a pad**
![image](https://user-images.githubusercontent.com/53021785/80148269-054e3980-8572-11ea-9dc0-dd79b6883a84.png)

**now distance is red**
![image](https://user-images.githubusercontent.com/53021785/80148295-1008ce80-8572-11ea-9e5c-8cbb7043125d.png)

...

### Steps to reproduce the issue:
For the 1st Issue:
- Select a landing pad to check that it's not destroyed
- Destroy a ship
- Select pad again
- Issue

For the 2nd Issue:
- Select a ship to check if the distance is red or not
- Select a pad with a ship larger than the max 'Cat; X'
- Select Ship again
- Issue
...

### Environment
- Skywanderers version: 20w17b
- Graphics Card: Integrated Graphics

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4525167/output_log.txt)

**Comment by tsunamayo** [comment]
Great, issue fixed for 20w17d! Cheers
