### ISSUE TITLE
Unable to click on anything.

### ISSUE THREAD

**Issue by Nosda1** [tsunamayo/Starship-EVO#1826]
### Short Description of the issue:
I am unable to click on a ship in my blueprints to spawn it, I can't teleport and I can't resume a world.

### Steps to reproduce the issue:
I don't know how to repreduce this issue, my game started like this. 

### Environment
- Skywanderers version: Pre-Alpha: 20w17c
- Graphics Card: Nvidia GTX 1080

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4525595/output_log.txt)

**Comment by tsunamayo** [comment]
Hi @Nosda1 , what is your screen resolution? Some user reported similar issue with a non standard screen ratio, you can try to switch your resolution and see if it fix the problem.
It wont be a real fix obviously, I am working on it!
Thanks

**Comment by tsunamayo** [comment]
@Nosda1 could you please tell me if you have the issue with the native resolution AND in graphic settings / UI Post effect deactivated? Thanks

**Comment by tsunamayo** [comment]
@Nosda1 a fix should be live in 20w17d, can you tell me if that fixed the issue? Thanks

**Comment by Nosda1** [comment]
Hello, sorry I did not see your message. Changing the resolution did fix my problem and thanks to this update I can now play using my normal resolution.
Thank you for your help !

**Comment by tsunamayo** [comment]
Okay great to hear that! Have fun ;)
