### ISSUE TITLE
[Bug] Turrets destroy children

### ISSUE THREAD

**Issue by SabreMania** [tsunamayo/Starship-EVO#1827]
So, as the title says, Turrets give little considerations to other turrets. While they will not fire if the ship is in the way, they have absolutely no problem sawing other turrets in half if they just so happen to be in the way. 

### Steps to reproduce the issue:

Create two turrets, with firing arcs that go through each other, and have a target fly in such a way that the turrets will have no choice but to fire on each other to try to hit their mark.
...

### Environment
- Skywanderers version: 20w17c
- Graphics Card: GTX 970

**Comment by tsunamayo** [comment]
Now this is a bit tricky, they should be checking if the raycast hit at fire and not fire if something is in range. But if the ship move and then laser then hit the turret or else then it cant predict that.
Where you using Laser or Beam? Can you reproduce with beam?
Also how big is your ship (how far was the turret), and where you moving?
Thanks

**Comment by SabreMania** [comment]
Okay, here's a little update. 

How I wired up my turret seems to be the problem. I wire up all of my turrets up in the same turret core, which seems to have been causing all sorts of problems that didn't exist in previous versions. 

I re-did my tests, though this time with each turret having it's own turret core, and they no longer fired at each other while trying to destroy a target.

On that note, did you plan people to link up multiple turrets to a single turret core?

**Comment by tsunamayo** [comment]
nope, I need to do something to prevent that...

**Comment by tsunamayo** [comment]
I have added a check to make sure that rotator are parented between them. It will give a warning message and prevent the link otherwise. Available in 20w18c.
Thanks!
