### ISSUE TITLE
[BUG] Blast door arrow

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Starship-EVO#1828]
### Short Description of the issue:

The arrow on the blast door seems to be a bit buggy when you make it 2 tall.

![image](https://user-images.githubusercontent.com/43644633/80163128-09f40b80-85cd-11ea-865d-afa143a2d22a.png)

**Comment by tsunamayo** [comment]
Okay issue fixed for 20w17d! Quicky one but that counts ;) Cheers
