### ISSUE TITLE
Unable to paint glass but can paint frame on canopy block

### ISSUE THREAD

**Issue by schlid** [tsunamayo/Starship-EVO#1831]
As described in the title, I can paint the frame around the glass but the window pane will not take paint regardless of the angle I try. (The wedge canopy is painted to the desired effect, I accidentally broke the normal canopy block which is why I was trying to repaint it.) 
![image](https://user-images.githubusercontent.com/31857052/80209673-60436780-862a-11ea-9cc0-7d5200ee9e2b.png)

I have attached the ship file but it doesn't seem the issue is exclusive as others were having problems too

[kingfisher with system7.zip](https://github.com/tsunamayo/Starship-EVO/files/4528674/kingfisher.with.system7.zip)

**Comment by tsunamayo** [comment]
Okay fixed for 20w17d. Btw I want to make the transparent painted stronger, what do you think? now it is too light.
