### ISSUE TITLE
[Bug] Block borders

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#1832]
### Short Description of the issue:
When a wedge and full block meet at an edge, the bevel effect does not disappear like it did in previous builds

Outlined in red you can see the error, while if the wedge does not meet a block at an edge the error does not occur, shown in green

![Untitled](https://user-images.githubusercontent.com/27857711/80213053-81a75200-8630-11ea-8e0e-e5fe8413e14a.png)

### Steps to reproduce the issue:
Place a wedge so that it ends at the edge of a block, as shown in the example

### Environment
- Skywanderers version: 20w17c
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
In which previous build are you referring to? (I havent touched this in a while)
Thanks

**Comment by ProPeach** [comment]
A couple of days ago these were fine and everything blended smoothly, I loaded up today and the borders were changed. I'm wondering if it has to do with migrating over the saves to the new folder and the new save format. There's an issue that cropped up from the same build with child entities that I'm writing up now which makes me think it happened at the same time.

**Comment by tsunamayo** [comment]
no save format is the same, it is weird indeed. Can you send me the build? Thanks

**Comment by ProPeach** [comment]
Here's the build, although it's worth nothing that this happens on all ships, new or old. It just seems to be that the border doesn't update properly when it's in that position.
Here's another ship where you can see it clearly
![image](https://user-images.githubusercontent.com/27857711/80313805-48641300-87e5-11ea-9f63-574637ad13c4.png)
[Block Borders Bug Showoff.zip](https://github.com/tsunamayo/Starship-EVO/files/4535975/Block.Borders.Bug.Showoff.zip)

**Comment by tsunamayo** [comment]
Issue no longer applicable. Thanks
