### ISSUE TITLE
[Bug] Disappearing/changing child entities

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#1835]
### Short Description of the issue:
Since the change to character specific worlds, some blueprints spawn with no child entities. This happens much more often in larger ships, or if a ship is taking a long time to spawn because the game is currently spawning something else in.

I've attached a blueprint that spawns with blueprints if you spawn it by itself, but spawns without if you start spawning it whilst another ship is spawning. Ships larger than this often lose their child entities when spawning, but smaller ships are less likely to, although still can if it takes too long. It definitely seems like the time taken to spawn is the deciding factor here.

This means that if you load into a world with many ships, most of them will lose their child entities as it takes a while to load the world.

Rotors and sliders seem to be most likely to be removed, hinges seem fine.

Hinges also change position when you reload the game. Before -
![image](https://user-images.githubusercontent.com/27857711/80231745-b5dc3c00-864b-11ea-827d-547a63c12acf.png)

After - 
![image](https://user-images.githubusercontent.com/27857711/80245547-d2d03980-8662-11ea-8817-f71cac218fb2.png)

### Steps to reproduce the issue:
Download the attached blueprint
Spawn one using the starter block, then spawn another while the first is spawning
The first ship will spawn with child entities, the second will spawn without them (Look for the radar dish)
Left with child entities, right without.
![image](https://user-images.githubusercontent.com/27857711/80245328-67866780-8662-11ea-8709-68c466571a51.png)

[Tantive IV.zip](https://github.com/tsunamayo/Starship-EVO/files/4530842/Tantive.IV.zip)

### Environment
- Skywanderers version: 17w20c
- Graphics Card: 17w20c

**Comment by tsunamayo** [comment]
Seems bad, there is another thread on that. I am on it!

**Comment by tsunamayo** [comment]
Hum I cant reproduce that issue, do you get that 100% of the time? thanks

**Comment by tsunamayo** [comment]
That dreaded issue is fixed for 20w20c. Sorry it took quite a while but I am happy it is finally gone. Thanks!
