### ISSUE TITLE
[Suggestion] landing pad permissions

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#1836]
After you request docking on a landing pad, I suggest that tip pop up saying something like "Please proceed to the landing pad" so that players know they need to get close for the automatic docking to kick in.

On the flip side, right now there is no way to cancel a dock in progress. Another tip saying "Press L to cancel docking procedure" could help a lot with that, especially if the docking fails for whatever reason, or the player changes their mind.

**Comment by tsunamayo** [comment]
Yes true!

**Comment by tsunamayo** [comment]
I have added various help message, a UI for autopilot and the ability to cancel the current mode. Will be in 20w18c! Thanks
