### ISSUE TITLE
[Bug] Torus targeting indicator

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#1837]
### Short Description of the issue:
The Torus has no targeting indicator (should show up in the bottom right when you target something) in Lightcruise

![image](https://user-images.githubusercontent.com/27857711/80247010-45421900-8665-11ea-9221-6c26dd54cc24.png)

### Steps to reproduce the issue:
Fly a ship in Lightcruise and target the Torus

### Environment
- Skywanderers version: 20w17c
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
Fixed in recent version, but we still havent the 3d view (will be fixed when I migrated to brick entity) Thanks
