### ISSUE TITLE
[Bug] Nested targeting icons

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#1838]
### Short Description of the issue:
If one target icon is nested in another, you cannot target it.

Here I'm trying to target the ship on the Torus, but I can't because the Torus target icon is in the way
![image](https://user-images.githubusercontent.com/27857711/80247172-820e1000-8665-11ea-83f2-55d54167ad52.png)

### Steps to reproduce the issue:
Enter Lightcruise and try to target something behind/smaller than another object that is close to it

### Environment
- Skywanderers version: 20w17c
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
Issue fixed for 20w18b. Thanks!
