### ISSUE TITLE
[Suggestion] Better AI targetting

### ISSUE THREAD

**Issue by SabreMania** [tsunamayo/Starship-EVO#1840]
Alright, so, right now in the game, there is only two ways to have turrets that automatically target something. There is the Starship Target one, that will cause all of your turrets with this option activated to fire at your selected target, and even try to converge on the very point you clicked on. (This system is technically good but unreliable when you have a tiny little thing zooming about, be it you or the target.)

And there is the Automatic target-finder, which just shoots at everything that isn't your ship or it's children entities. This has the inconveniant that it doesn't really allow you to have any other friendly ship around.

What I would suggest is for the game to have some kind of option that you could select in the turret core. A sort of 'Target preferential' kind of thing, which would help the automatic target finder mode to better select what it fires at. Right now in the game, ships are already categorized as "Cat 0-1-2-3-4-5", so why not have an option in the turret core that tells the turret which one it should be prioritizing?

Of course this wouldn't be an end-all-be-all kind of solution, but it would be great to have this as a starter. An even better world would have all of the categories selectable as targets, and you being able to set your automatic turrets to fire only at certain categories while completely ignoring others. For now of course this isn't really needed, but when things like limited ammunition will be introduced, it'll be important to have something like that.

**Comment by tsunamayo** [comment]
For now they fire at friend because I messed up the selection for testing ;)
I will put it back, normally it only fire at hostile target.
And definitely yes your suggestion is making a lot of sense!
Thanks

**Comment by tsunamayo** [comment]
I have just added two options to the turret computer: Auto Fire Min Size and Max size. So you can have you small gun fire only at small gun ect.
I just want to inverse the category, ie higher number => bigger ship. Otherwise that is too confusing for beginners!
will be in 20w17e.
Cheers
