### ISSUE TITLE
[Bug] Turret hinges & rotators setting themselves to 0 degrees [20w17c]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#1844]
### Short Description of the issue:
After configuring them, some turrets are setting their hinges and rotators to 0 degrees. While it is actually nice to have an "at rest" position for the turrets (might be nice to have something like that in the future), they do this even if it gets them stuck.

### Steps to reproduce the issue:
This seems to be happening with all new turrets that I place. The older, pre-existing ones aren't doing it ATM.

### Environment
- Skywanderers version: 20w17c
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20200424211708_1](https://user-images.githubusercontent.com/33041786/80269128-9573a800-8672-11ea-9988-d99cf6c13ede.jpg)

![20200424212511_1](https://user-images.githubusercontent.com/33041786/80269131-999fc580-8672-11ea-82ed-6706d8a605cc.jpg)

![20200424212757_1](https://user-images.githubusercontent.com/33041786/80269136-9d334c80-8672-11ea-8e55-4cddf8536330.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4532212/output_log.txt)

**Comment by Dwarf-LordPangolin** [comment]
Update: it looks like there's a way to prevent this from happening. If the hinge/rotator is given a value by a sequencer first, it will not move itself to 0 degrees later on, even if the sequencer has been deleted. Hopefully that helps figure out what's causing this.

**Comment by tsunamayo** [comment]
I cant reproduce that one, is there anything special I should try? Thanks

**Comment by tsunamayo** [comment]
Okay I tried to reproduce on your ship, it was also fine. Just to confirm: you were not in multi?
Also exactly your test case:
1) you build a turret
2) you set all angle at non zero (how? - I control the turret in manual for a bit)
3) you open the turret screen config
4) close the screen config -> turret resets.
Cheers

**Comment by Dwarf-LordPangolin** [comment]
I was not in multiplayer, no.

So, the test case was that this just happened spontaneously: I built some of the turrets, went to work on something else on the ship, and came back to find it had happened.

Later, when I built some new turrets, I connected a switch to a sequencer, set both its values to 90, and pushed that value to the hinge a couple times by flipping the switch around; that seemed to prevent this from starting with those turrets.

**Comment by tsunamayo** [comment]
So you mean it was not linked to you entering the turret menu and exiting? (I was under this impression). Did you took control of the ship for a bit? I want to find what was the trigger.

**Comment by tsunamayo** [comment]
okay the thing I think I am actually missing is that: 
when you start build a turret, of course all the rotator are going to be at the default state.
So it means that you must force another value in some way (then they reset to 0).
How are you forcing that value? You mention sequence, but I guess that was not the initial way as you mention that as a fix.
Thanks

**Comment by Dwarf-LordPangolin** [comment]
So I think I see what is going on here: it's not turret hinges that are resetting to 0, it's all hinges. Here's how it's being reproduced:

1. Place hinge. Note the angle reads -90, which I'm guessing is [this bug](https://github.com/tsunamayo/Starship-EVO/issues/1876), but the actual moving part of the hinge is in the middle as usual.
![20200429120742_1](https://user-images.githubusercontent.com/33041786/80625539-f99bc080-8a12-11ea-91b9-8e45f4ffaec0.jpg)

2. Save & exit game.
3. Reload the game and load the save. The hinge's moving part will have moved to the 0 position, instead of in the middle.
![20200429120948_1](https://user-images.githubusercontent.com/33041786/80625548-fc96b100-8a12-11ea-8eaa-2949e4f9abe9.jpg)

What was confusing me earlier about this was the fact that I was using the hinges on turrets; it looks like this actually has nothing to do with turrets.

**Comment by tsunamayo** [comment]
Okay amazing that was the piece I was needing. Issue fixed for 20w18d! Cheers
