### ISSUE TITLE
[Bug] buildings slowly sinks into the ground

### ISSUE THREAD

**Issue by David184** [tsunamayo/Starship-EVO#1849]
I found a bug with the new "building on terrain" feature. when you place down starter block and build around it and then remove the Starter block. the building would start to slowly "sink" into the ground. This doesn't happen when the firstly place started block is there.

...

Steps to reproduce the issue: place down starter block, build a platform, remove started block and build.

...

### Environment
- Skywanderers version: 20w17d

![SEVObug](https://user-images.githubusercontent.com/51233566/80273991-7824f500-86d7-11ea-93f2-e99fb6ed50ee.gif)

**Comment by tsunamayo** [comment]
Oh yes I forget to investigate that one... I keep you posted!

**Comment by tsunamayo** [comment]
Okay issue fixed for 20w17e. Thanks for the gif btw! Patch is coming asap as it is a serious issue. Cheers
