### ISSUE TITLE
[Question] Warheads?

### ISSUE THREAD

**Issue by MRonlin** [tsunamayo/Starship-EVO#1851]
Just wondering if warheads are going to be added to the game in the future.

**Comment by tsunamayo** [comment]
Depends on what you call by warhead! Tell me what you have in mind. thanks

**Comment by MRonlin** [comment]
Hey, sorry for the late reply. By warheads I means I mean a block that would explode when it comes in to contact with another block, or is damaged, space engineers has something similar. I think it would be useful if players could create there own, bombs or missiles, or just to blow stuff up. I think it would a good addition to the game, if you could link it up with the logic systems, and set up timers and other conditions of it to explode.

**Comment by tsunamayo** [comment]
Yes I definitely wants to add some explosive block / item at one point, but the plan is to have true missiles also, with some minimal crafting (payload, propulsion, guiding tech). Thanks!
