### ISSUE TITLE
[Bug?] Still no save-without big-buildblock on top solution

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Starship-EVO#1855]
### Short Description of the issue:

In #1808  you wrote, that there will be a small buildblock to save smaller entities in version 20w17c
But there is no small buildblock and saving small ships will make them as ugly as the picture shows?^^

### Steps to reproduce the issue:
Try to save and spawn a small ship.

### Environment
- Skywanderers version: 20w17d
- Graphics Card: gtx1070 mobile

### Additional information:

![Starship EVO_2020_04_25_14_44_12_123](https://user-images.githubusercontent.com/43222403/80280260-4033a700-8703-11ea-9525-83d90f9c97b6.jpg)

**Comment by tsunamayo** [comment]
New entity button available in 20w18e. Thanks!
