### ISSUE TITLE
[Bug] Spawn distance is no longer adjustable

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Starship-EVO#1856]
### Short Description of the issue:
If you set the build block to 20 km spawning distance, the ship will still spawn in front of you.

### Steps to reproduce the issue:
Try to spawn an enemy ship to test combat.

### Environment

- Skywanderers version: 20w17d
- Graphics Card: gtx 1070 mobile

**Comment by tsunamayo** [comment]
Yes correct, I need to remove that feature, at least the way it is currently implemented. Thanks

**Comment by tsunamayo** [comment]
Fixed for 20w19c. Thanks
