### ISSUE TITLE
Unbreakable Block of Darkness

### ISSUE THREAD

**Issue by TripleHelixxx** [tsunamayo/Starship-EVO#1858]
### Short Description of the issue:

...There is a black block on my ship that I can not destroy. It causes FPS drop when getting close.

### Steps to reproduce the issue:

...No idea how to reproduce this issue.

### Environment
- Skywanderers version: Pre-Alpha 20w17e
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![20200425084008_1](https://user-images.githubusercontent.com/64316439/80281760-6d6c5f00-86db-11ea-9abb-25cbcbc73119.jpg)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4533081/output_log.txt)

Here is also the blueprint of the ship with that block.
[Blueprint.zip](https://github.com/tsunamayo/Starship-EVO/files/4533139/Blueprint.zip)

**Comment by tsunamayo** [comment]
@TripleHelixxx do you remember having build anything specific? Did you try any system, logic gate or mechanism (not at this place, could be at any other place). Thanks

**Comment by tsunamayo** [comment]
Also if you did anything specific with symmetry please tell me! When that block did appears? Was it a load or after a while during a playsession? I can fix your blueprint but I would like to know how it happened. There is actually 1946 Hull block at this spot, for some unknown reason...
Cheers

**Comment by TripleHelixxx** [comment]
I know I wasn’t using symmetry, because I was experimenting with the little bricks trying to figure out a good shape. I wasn’t trying to build with any kind of mechanism at the time either. The only specific thing I can think of is that I was using regular blocks as a starting point for the bricks. I place a regular block, use the side of that block as a place to start the brick shape, then remove the regular size block. The one time I tried to remove the block, it turned into that thing. 
Sorry I don’t have more information, but It hasn’t happened again cents. 
Also by the way, this was a fresh build, not an old blueprint. It happened after I was playing for quite some time.

**Comment by tsunamayo** [comment]
@TripleHelixxx no perfect, it seems to be related to that removed block! Once this happened, did you had to quit the game or did you continued building? Thanks!

**Comment by TripleHelixxx** [comment]
I did try restarting the game to see if that would fix it, but it didn’t force me to. I could still build in that world, just not near that block because of the lag.

**Comment by tsunamayo** [comment]
So starting from 20w18d you will be able to reload your ship. Now it is not a proper fix as it will have to wait for a big refactor on the rendering side that should take care of that naturally, it is just a workaround that will allow you not loose your save. If it happens again you will still have to exit to desktop and reload the game...
If you see it happen frequently please tell me, in that case I would have to schedule that change higher on my to-do list.
Thanks!

**Comment by TripleHelixxx** [comment]
Awesome, thanks. I’ll be sure to keep an eye out for this particular issue and  let you know if it persists.
