### ISSUE TITLE
[Bug] New player spawns with mouse sensitivity set to 0

### ISSUE THREAD

**Issue by Lsutehall** [tsunamayo/Starship-EVO#1862]
### Short Description of the issue:

20w17e - I just made my first character after the change from skywanderers, but once I'd spawned in I could only scroll the hotbar, not look around.

Turns out the mouse sensitivity was set to 0, and it worked correctly after being turned up.

### Steps to reproduce the issue:

Not sure - start from fresh install?

### Environment
- Skywanderers version: 20w17e
- Graphics Card: GTX1060

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4533930/output_log.txt)

**Comment by tsunamayo** [comment]
Thanks indeed, issue will be fixed for 20w17f. Cheers
