### ISSUE TITLE
[Bug] Beam weapon not displaying some information when pressing F [20w17e]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#1865]
### Short Description of the issue:
The panel showing weapon info for the beams does not display some information, including weapon range.

### Steps to reproduce the issue:
Place beam, press F.

### Environment
- Skywanderers version: 20w17e
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20200426020117_1](https://user-images.githubusercontent.com/33041786/80300707-9b49b600-8764-11ea-83ef-e881dba0716c.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4534804/output_log.txt)

**Comment by tsunamayo** [comment]
Issue fixed for 20w18a. Thanks!
