### ISSUE TITLE
[Bug] Multitool graphical bug and issue

### ISSUE THREAD

**Issue by PopkaAkula** [tsunamayo/Starship-EVO#1868]
### Short Description of the issue:

![image](https://user-images.githubusercontent.com/37738021/80306086-5ef87300-87c1-11ea-9327-fdac8f27ebfe.png)

Whenever I would right-click, the multitool would look like the image provided above and it wouldn't delete anything, I could only place things down.

### Steps to reproduce the issue:

I don't really know what caused it, but all I know is that restarting the game fixed it

### Environment
- 20w17e

**Comment by tsunamayo** [comment]
Okay for case like that what would be really useful to investigate is the output.log! Hopefully there is something inside I can investigate. Thanks!

**Comment by PopkaAkula** [comment]
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4537865/output_log.txt)

As you have asked, here it is

**Comment by tsunamayo** [comment]
@PopkaAkula what is your CPU and RAM size? There is leak it seams. Not sure if it linked to your issue. What were you doing when this happened? Thanks
