### ISSUE TITLE
[Bug] Rollover sound effect ignores sound settings

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#1870]
### Short Description of the issue:
When your mouse rolls over a block in the codex, the game plays the appropriate sound even if you have the game sound turned down to 0.

### Steps to reproduce the issue:
Set game sounds to 0
Open codex and roll your mouse over a block

### Environment
- Skywanderers version: 20w17e
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
Issue fixed for 20w18a. Thanks a lot!
