### ISSUE TITLE
[Suggestion] Multiple mirror planes

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#1871]
Now that mirroring is working well apart from a few remaining bugs like #1686 , can we have the capability to place more than one mirror plane on one entity? It would be a wonderful quality of life feature, and it's often asked about by new potential new players, especially recently with EA on the horizon

**Comment by tsunamayo** [comment]
I know I know, I think this would have to wait a bit more, tbh I have plenty of things to do including a bunch of urgent quality of life things. Thanks

**Comment by ProPeach** [comment]
That's fair enough, lots if other more important things to do!

**Comment by tsunamayo** [comment]
Closed as we now have the feature.
