### ISSUE TITLE
[Bug] Dropdown menus turn white in certain resolutions

### ISSUE THREAD

**Issue by Tezlz** [tsunamayo/Starship-EVO#1873]
### Short Description of the issue:

The dropdown menus for selecting a resolution in the settings, and the dropdown menus when choosing ai mode and distance when spawning a ship turn white in certain resolutions. I tried all resolutions available in the settings menu and the problematic ones are 1920x1200 and 1600x1200.

### Steps to reproduce the issue:

Start the game, open graphics settings and change the screen resolution to 1920x1200 or 1600x1200.

### Environment
- Skywanderers version: 20w17e
- Graphics Card: GTX 1060 6GB

### Additional information:
![Screenshot_1134](https://user-images.githubusercontent.com/36267770/80317840-b284b400-87f5-11ea-9461-c299da408e25.png)
![Screenshot_1136](https://user-images.githubusercontent.com/36267770/80317842-b44e7780-87f5-11ea-8684-be967b559c32.png)
![Screenshot_1137](https://user-images.githubusercontent.com/36267770/80317847-b6183b00-87f5-11ea-87c6-2bea8892d375.png)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4536322/output_log.txt)

**Comment by tsunamayo** [comment]
Great, thanks for reporting those one as I dont have a monitor like this is hard to spot them! Will be fixed for 20w18a! Cheers
