### ISSUE TITLE
[Bug] Block ghosts or "lag"

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#1874]
### Short Description of the issue:
Sometimes when placing or deleting blocks, you can experience a lag. When breaking blocks the blocks turn dark, lose their collision boxes and disappear after a while, whereas when placing blocks they show up as invisible but solid

Here's the lag when deleting blocks
https://i.imgur.com/Wqlgz9d.mp4
Here's the lag when placing
https://i.imgur.com/0QZpahC.mp4

I noticed that this happens much more often when my CPU (FX-6300 Black Edition) is at close to max load from running other applications at the same time as SEVO, if I'm not running anything else then the bug occurs. This bug happens with mirror on and off, on child entities and the main entity. The only correlation I've found is the CPU load

### Steps to reproduce the issue:
Run a bunch of different apps so that you CPU is at close to 100% load
Place and delete some blocks quickly

### Environment
- Skywanderers version: 20w17e
- Graphics Card: RX 580

[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/4536344/output_log.zip)

**Comment by tsunamayo** [comment]
So it is a different issue compared to #1858 right? It always disappears after a while?
The geo reconstruction is done on a thread. If you go too fast and place another block it will cancel the current rebuild and start a new one. So if your CPU is running at max the geo might take a while to compute triggering this... 
I have some big improvement planed on the geo rebuild. It was already much much faster compared to before, but with the new system it would be instantaneous on the CPU.

**Comment by ProPeach** [comment]
Sounds great! Yes, the blocks do eventually behave as you'd expect them too but it just takes time when the CPU is under heavy load

**Comment by Xerma** [comment]
This sounds similar to my older issue: https://github.com/tsunamayo/Starship-EVO/issues/1660 

At times it can catch up for my larger builds as well but probably 9 times out of 10 it just takes so long that it's more viable to restart my game rather than wait it out. Once you get that tech into the game, if this issue gets fixed it's probably safe to assume my older issue will be fixed as well

**Comment by tsunamayo** [comment]
Okay this issue should be fixed in the latest experimental branch, 20w28c. I dont know if this is something you can confirm easily or not? Keep me posted, cheers
