### ISSUE TITLE
[Bug] Shadow artifacts on block borders

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#1875]
### Short Description of the issue:
When blocks are in shadow, there is a dark border around their edge on all LODs. This is especially noticeable on tetras and heptas
https://i.imgur.com/Rc97pNn.mp4

### Steps to reproduce the issue:
Move a ship into the shadow and move around to easily see the artifacts

### Environment
- Skywanderers version: 20w17e
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
Yes shadow is an artifact fuck fest. In game there is usually no hidden geo beneath, unfortunately it is not the case in this game. I might do huge tech switch at one point, it is just not urgent atm... Cheers
