### ISSUE TITLE
[Bug] Hinge angle & sequencer bug [20w17e]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#1876]
### Short Description of the issue:
Hinges when placed show an angle of -90 degrees, and sequencers connected to them show a range from 0 to -180 degrees.

### Steps to reproduce the issue:
Place hinge, place sequencer, link sequencer to hinge, check info of both.

### Environment
- Skywanderers version: 20w17e
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20200426160015_1](https://user-images.githubusercontent.com/33041786/80319821-42b40080-87d8-11ea-9627-f8692da0bc0d.jpg)

![20200426160033_1](https://user-images.githubusercontent.com/33041786/80319822-43e52d80-87d8-11ea-8014-ae08801a5939.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4536473/output_log.txt)

**Comment by schlid** [comment]
Also experiencing this bug. With the fix would it be possible to update all negative values in sequencers to a positive value so we don't have to edit every single one? If not and it's a time thing don't worry.

**Comment by tsunamayo** [comment]
Yes it will likely break all current sequencer... It is a bit tricky to convert things like that.

**Comment by tsunamayo** [comment]
I fixed the issue, and there will be no impact on your current sequencer settings. Available in 20w18d. Thanks!
