### ISSUE TITLE
[Bug] Pressing 'esc' to close some menus cause the pause menu to appear without a cursor

### ISSUE THREAD

**Issue by Tezlz** [tsunamayo/Starship-EVO#1877]
### Short Description of the issue:

I always close my menus by pressing esc and I noticed that it isn't really working properly, if you press esc to exit the options menu for an example you will go back to the game but still see the pause menu on your screen but you can still move and look around with your character as if the menu wasn't there at all

### Steps to reproduce the issue:
Prese 'esc' to open the pause menu, press 'options', and then press escape again to exit the pause menu

### Environment
- Skywanderers version: 20w17e
- Graphics Card: GTX 1060 6GB

### Additional information:
GIF of me recreating the bug on different menus, such as the options menu, turret core and some logic blocks:
https://gfycat.com/coolbothemeraldtreeskink

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4536507/output_log.txt)

**Comment by tsunamayo** [comment]
Thanks a lot for the case and video! Issue is fixed for 20w18a. Cheers!
