### ISSUE TITLE
[Bug] Ships not exploding [20w17e]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#1878]
### Short Description of the issue:
Some ships are not exploding when their hull integrity is gone.

### Steps to reproduce the issue:
Not sure what circumstances this is occurring under, so just shoot at ships until it happens I guess? :/ I saved the blueprint of the ship in question, hopefully that will show what's happening.

### Environment
- Skywanderers version: 20w17e
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20200426150106_1](https://user-images.githubusercontent.com/33041786/80320913-e56f7d80-87de-11ea-8348-5e98d34edf30.jpg)

[Zombie Manta Blueprint.zip](https://github.com/tsunamayo/Starship-EVO/files/4536540/Zombie.Manta.Blueprint.zip)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4536541/output_log.txt)

**Comment by tsunamayo** [comment]
Was the manta being driven by an NPC? Thanks

**Comment by Dwarf-LordPangolin** [comment]
No, but it was empty; no pilot.

**Comment by tsunamayo** [comment]
Yes okay make sense.

**Comment by tsunamayo** [comment]
Issue fixed for 20w18a. Thanks!
