### ISSUE TITLE
[Suggestion] Hovercraft are too sensitive and bouncy

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Starship-EVO#1879]
### Short Description of the issue:
I have been messing with the hovercraft and noticed that it is still quite sensitive and bouncy. Moving along causes you to bounce a lot making flipping very common and if you turn it is very easy to flip the entire ship. I think it could benefit from a dampening to the system. The bouncy effect looks cool but can be way too strong.

**Comment by ProPeach** [comment]
Definitely agree, the centre of mass/thrust is a nice mechanic too, but it's also a little too sensitive - it'd really benefit from a "deadzone" to where you only need to be ~90% balanced to get your craft stable

**Comment by Garrett-C** [comment]
Yeah I agree peach. I think the issue is that they aren’t currently very forgiving. It feels like the physics for them is too realistic at times. I mean I don’t mind not being able to turn at high speeds with out flipping but if I flip just for a small turn it’s a bit much.

**Comment by tsunamayo** [comment]
Yes it is on my to-do list. I will fix a few bugs, and add some settings at the repulsor and computer level. Yes it is completely realistic... It is very hard to mix realistic and fake physics. I keep you posted.

**Comment by tsunamayo** [comment]
So I fix all the glaring issues, it is so much better now, I almost never flip in the mustang, you have to really want to do it to flip. Still havent added the setting, I want to work on a new worflow for player customizable settings. Will be in 20w18f. Cheers
