### ISSUE TITLE
Only host can place starter blocks in multiplayer

### ISSUE THREAD

**Issue by hl2shadowslayer** [tsunamayo/Starship-EVO#1881]
### Short Description of the issue:
When in a multiplayer game, only the hosting player is able to place a new starter block entity properly. When a non-host attempts to do so, the starter block will appear in the 'void' where destroyed ships are teleported to. Non-hosts are still able to place starter blocks on existing entities though, and do things like saving with it.
...

### Steps to reproduce the issue:
Join a multiplayer game as a non-host
Try to place a new starter block entity anywhere
Try to teleport to the new entity in F7 menu
...

### Environment
- Skywanderers version: 20w17e
- Graphics Card: Geforce 750ti

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4536938/output_log.txt)

**Comment by tsunamayo** [comment]
This bug will be fixed for 20w18a. Thanks!
