### ISSUE TITLE
[Bug] Shield block does not visibly rotate [20w17e]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#1882]
### Short Description of the issue:
Rotating the shield block with Q and E does not visibly rotate the block. The texture orientation remains the same.

### Steps to reproduce the issue:
Select shield block, press Q and E to rotate.

### Environment
- Skywanderers version: 20w17e
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
The texture on the reactor has rotated 90 degrees to match the block's rotation. The same rotation was made for the shield block, but the texture remains unrotated.
![20200427020927_1](https://user-images.githubusercontent.com/33041786/80343789-22ae2c80-882c-11ea-86b7-c3613ca908da.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4538015/output_log.txt)

**Comment by tsunamayo** [comment]
yes, is it a big deal according to you? It is because of how the addon slot texture is working, it is a texture projection. Thanks

**Comment by tsunamayo** [comment]
Okay issue fixed for 20w18a. No issue is too small to not warrant a fix ;)
