### ISSUE TITLE
[Bug] Scrolling toolbar does not update dots 1st time [20w17e]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#1883]
### Short Description of the issue:
When first scrolling through the toolbar after loading into the game, the dots showing which bar is being viewed do not update the first time that respective bar is viewed. After the first view, they update correctly.

### Steps to reproduce the issue:
Load game, scroll through the 3 different toolbars, watch dots carefully. It only happens the first time after loading.

### Environment
- Skywanderers version: 20w17e
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
First time this toolbar is scrolled to:
![20200427021229_1](https://user-images.githubusercontent.com/33041786/80344242-e3cca680-882c-11ea-8bb5-8ce909b9e1ea.jpg)

Second time this toolbar is scrolled to:
![20200427021231_1](https://user-images.githubusercontent.com/33041786/80344257-e6c79700-882c-11ea-9560-14eac9164bce.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4538035/output_log.txt)

**Comment by tsunamayo** [comment]
I dont have that problem... You get this all the time?

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin did you got these in latest updates? was it something you got 100% of the time? Thanks

**Comment by tsunamayo** [comment]
This should be fixed in recent updates. Thanks
