### ISSUE TITLE
[Question] Level of Detail

### ISSUE THREAD

**Issue by MRonlin** [tsunamayo/Starship-EVO#1884]
Will/does the game have LOD, decreasing the level of detail of the voxels the further away the player is from it, games like no man sky and dual universe use this, and I think it would be a good way of improving performance and allowing larger builds.

**Comment by ultrak2k** [comment]
Doesn’t it already do this

**Comment by ProPeach** [comment]
Yeah, the game has had this tech from the start pretty much, it's mandatory for any game

**Comment by MRonlin** [comment]
Thanks, good to know.
