### ISSUE TITLE
[Bug] Reversing sequence circuit causes the circuit to freeze [20w18a]

### ISSUE THREAD

**Issue by captain828** [tsunamayo/Starship-EVO#1888]
### Short Description of the issue:

Attempting to run a reversing sequence circuit can result in a broken circuit that can only be reset by updating the logic gates.

### Steps to reproduce the issue:

1. set up the circuit either as shown in the image below or as explained in [this guide (under Reversing Sequence | ABBA)](https://www.skywanderersgame.com/forum/viewtopic.php?f=3&t=42047)
2. set both timers to 2 seconds
3. flip the switch ON
4. wait for 1 second
5. flip the switch OFF
6. observe as one of the lights stays on as the circuit becomes unresponsive to further switch value changes

### Environment
- Skywanderers version: 20w18a
- Graphics Card: nvidia GTX 980 | driver ver 445.75

### Additional information:

![reverse sequence issue.jpg](https://user-images.githubusercontent.com/17725004/80487634-d2d38080-8965-11ea-8677-7461d031a83d.jpg)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4545701/output_log.txt)

**Comment by talrey** [comment]
It probably has something to do with how Timers have a "cooldown" where they ignore input changes while delaying, so your 1-second input turns OFF halfway through the 2-second delay of the Timer, and the Timer doesn't realize it should turn OFF afterwards.

**Comment by talrey** [comment]
Side note: it's possible to build this kind of sequence with no loops in the logic, I'd recommend avoiding loops wherever possible due to issues like this.

**Comment by captain828** [comment]
Yes, I agree that we should avoid such circuits but I still don't think the game currently handles this as expected.

**Comment by tsunamayo** [comment]
I just tried it and it is now fixed, I did a change in the timer behaviour for #1941 that fixed it. Thanks!
