### ISSUE TITLE
[Bug] Aggressive AI doesn t attack anymore

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Starship-EVO#1890]
### Steps to reproduce the issue:

Spawn an aggressive AI that worked in previous versions. It spawns together with in NPC-Pilot, its turrets are shooting sometimes but it doesnt move anymore. 

I have also experimented with other target categories, but these are not the cause of the bug.

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4546228/output_log.txt)

after some other tests:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4546642/output_log.txt)

**Comment by tsunamayo** [comment]
Issue fixed for 20w18b. Thanks!
