### ISSUE TITLE
[Bug] Recoil barrel shot same as default laser unit [20w18a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#1891]
### Short Description of the issue:
The patch notes say the recoil barrel fires a "bigger" shot, but the damage per shot of the laser unit with a recoil barrel is the same as an unmodified barrel.

### Steps to reproduce the issue:
Place 2 laser units, give one a recoil barrel, compare stats.

### Environment
- Skywanderers version: 
- Graphics Card: 

### Additional information:
![20200428165032_1](https://user-images.githubusercontent.com/33041786/80541235-6ca02b00-8970-11ea-8124-f50bf766f4c5.jpg)

![20200428165027_1](https://user-images.githubusercontent.com/33041786/80541244-6f028500-8970-11ea-808f-93595c939db4.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4548713/output_log.txt)

**Comment by tsunamayo** [comment]
Yes indeed, fixed for 20w18b. Btw @Dwarf-LordPangolin I dont know if you could answer for #1844 ?
Thanks!
