### ISSUE TITLE
["Bug"] Hard to Read Patch Notes

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#1895]
![](https://cdn.discordapp.com/attachments/406664114249793536/704914868733739008/unknown.png)

It is kind of hard seeing the text. The white color on the bloom effect and the blue text on blue

**Comment by tsunamayo** [comment]
true

**Comment by tsunamayo** [comment]
okay fixed for 20w18c. Do you think that the patch note text font is too small / proggy? Thanks

**Comment by Aiwii** [comment]
font is good

**Comment by ZachZent** [comment]
I think the size/font is fine. I would add a link to the github patch notes if possible.

![](https://cdn.discordapp.com/attachments/406664114249793536/704917782831038535/unknown.png)

You can also remove the numbers (#1838) as well. Doesn't really add anything

**Comment by tsunamayo** [comment]
actually if you click on the text it send you the the github. maybe it is not clear enough? I had a "Comment on github" text before.
I prefer to keep the number, after I copy-past the same text over github, and the # give me a link straight away.

**Comment by ZachZent** [comment]
I did not know it linked already. Does need to be a bit more clear

**Comment by ProPeach** [comment]
Subnautica for example has a tip that pops up whenever you load up a game that said "Press F8 to report bugs or submit feedback", I think making it as clear as possible will be a great help to gather up as many bugs as possible

**Comment by tsunamayo** [comment]
> Subnautica for example has a tip that pops up whenever you load up a game that said "Press F8 to report bugs or submit feedback", I think making it as clear as possible will be a great help to gather up as many bugs as possible

great idea!
