### ISSUE TITLE
[Bug] Gate Icons not displayed properly

### ISSUE THREAD

**Issue by Alkaliii** [tsunamayo/Starship-EVO#1899]
### Short Description of the issue:
Icons on the logic bricks (specifically the gates) are not displayed properly when first placed
https://streamable.com/ce0hpj
...

### Steps to reproduce the issue:
- Place a gate down
- Issue
...

### Environment
- Skywanderers version: 20w18b
- Graphics Card: Integrated Graphics

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4550168/output_log.txt)

**Comment by tsunamayo** [comment]
Are you reproducing this all the time? Because I cant reproduce, it works fine on my side.
If you could send me your blueprint so I can check if there is something with it. 
Thanks!

**Comment by Aiwii** [comment]
Hmm I also couldn't reproduce. Here is the blueprint:
[BiggerBoiC.zip](https://github.com/tsunamayo/Starship-EVO/files/4555685/BiggerBoiC.zip)

**Comment by tsunamayo** [comment]
I think it must be linked to you working on the ship in some way, typically removing another gate or system. Do you remember anything particular, like deleting any kind of block?

**Comment by Aiwii** [comment]
Not really sure if I did anything particular, I just noticed it was happening again and started recording. I'll try to be more aware of what I did previously the next time it happens

**Comment by tsunamayo** [comment]
yes it is an old issue, but we never managed to track it down!
