### ISSUE TITLE
[Github Format] Legacy save data path

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#1901]
When you create a new post here, you're presented with the very handy guide on how to lay out a bug report. Since the location of the savedata folder changed, this information is now incorrect.

Below is what the format shows, notice the old savedata location

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Okay indeed, post updated! Thanks
