### ISSUE TITLE
Mislabeled rotor/hinge axis

### ISSUE THREAD

**Issue by hl2shadowslayer** [tsunamayo/Starship-EVO#1908]
### Short Description of the issue:
When you go to set the turret control axis of a rotor or hinge, the axis options are the opposite of what they actually are. Setting it to vertical will make the turret attach it to horizontal movement, and setting it to horizontal will make the turret attach it to vertical movement.
...

### Steps to reproduce the issue:
Create a basic turret with the minimum requirements. One rotor/hinge for each axis, a weapon, a camera, ect. 
Set the base rotor or hinge to horizontal, and the vertical hinge/rotor to vertical.
Try piloting the turret to see if your control axis are the opposite of what they should be.
...

### Environment
- Skywanderers version: 20w18c
- Graphics Card: Geforce 750ti

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4557190/output_log.txt)

**Comment by tsunamayo** [comment]
So yes it might be a bit confusing. It is the _axis_ orientation, not the plane. I might change it indeed. But actually I will try to compute these with code, so no assignment would be necessary...
Thanks

**Comment by tsunamayo** [comment]
You no longer need to assign this in later versions. Thanks
