### ISSUE TITLE
 critical bug

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Starship-EVO#1909]
I understand that you are very busy. This is also nothing more than a request.

The following bug was posted for a while and is really critical because we can't use hinges at the moment.

#1876

**Comment by Dwarf-LordPangolin** [comment]
As a temporary workaround, I've found you can give the hinges negative values instead of positive ones.

**Comment by Battlepixel** [comment]
> As a temporary workaround, I've found you can give the hinges negative values instead of positive ones.

Thanks very much! 
But the realistic fear remains that all mechanisms built in this way will stop working if the bug is fixed one day.^^

**Comment by tsunamayo** [comment]
yes it was next on my list, I keep you posted!

**Comment by tsunamayo** [comment]
I fixed the issue, and there will be no impact on your current sequencer settings. Available in 20w18d. Thanks!
