### ISSUE TITLE
[Bug] Collision varies based on specific logic bricks

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#1910]
### Short Description of the issue:
Mechanisms display different collision and/or timing based on apparently identical logic.

### Steps to reproduce the issue:
I think this bug has been present for a while but this is the first time I've been able to pin down precisely what I think is causing it. A description of exactly what's happening:

I use a landing gear setup on a lot of my ships that fits smoothly into its position as long as all the logic starts at the same time; if the timing is off slightly, it gets hung up. This is relevant because I've noticed that sometimes, the gear work fine when I'm building them and using temporary logic, but then get stuck when triggered with another set of logic. The logic is identical as far as I can tell, so the difference seems to be something I can't see about the logic; either the timing between the sequencer and both hinges isn't synced somehow, or some other problem is happening.

### Environment
- Skywanderers version: 20w18c
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
This is the gear in its extended position when controlled by the working logic:
![20200430031110_1](https://user-images.githubusercontent.com/33041786/80687772-6dc87980-8a90-11ea-878d-389cd9ee10de.jpg)

And this is the same gear in the extended position when controlled by the non-working logic:
![20200430031133_1](https://user-images.githubusercontent.com/33041786/80687781-70c36a00-8a90-11ea-850b-000a1647866c.jpg)

These are the values for the sequencer that controls the working logic:
![20200430033307_1](https://user-images.githubusercontent.com/33041786/80691824-64421000-8a96-11ea-9459-969ded24f4a2.jpg)

And these are the values for the sequencer that controls the non-working logic:
![20200430033257_1](https://user-images.githubusercontent.com/33041786/80691871-72902c00-8a96-11ea-9bf9-a9d85ffb50ef.jpg)

The problem occurs regardless of whether the non-working logic is triggered via the yoke & hotkey, or by its switch; in both cases, it fails to work. So there's something about how the normal landing gear logic works  that is invisibly different from the local logic I set up when making the gear.

I actually wondered if the player's location affected things -- if somehow the physics simulation was changing based on player proximity to what was moving -- so I also put a button connected to the working set of logic, at the same spot in the ship where the non-working logic was. The working logic still worked when triggered from the same location as the non-working logic though, so it looks like that's not the issue here.
Blueprint, working and non-working logic sets: 
[Mistral -- Landing Gear Bug.zip](https://github.com/tsunamayo/Starship-EVO/files/4557231/Mistral.--.Landing.Gear.Bug.zip)

It gets even stranger!

In an attempt to troubleshoot the issue, I tried disconnecting the non-working logic from the hinges and reconnecting it. After doing that, both sets of logic did not work properly, and both caused the gear to get stuck.
Blueprint, both logic sets non-working:
[Mistral -- Landing Gear Bug 2nd BP.zip](https://github.com/tsunamayo/Starship-EVO/files/4557233/Mistral.--.Landing.Gear.Bug.2nd.BP.zip)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4557252/output_log.txt)

On another note, the blueprint is almost finished; this bug with the gear is one of the last things that needs to be taken care of before I can hand it off to you. :)

**Comment by tsunamayo** [comment]
Okay I will have a look at it, btw it is also the one that bug on landing pad? Cheers

**Comment by tsunamayo** [comment]
Okay mate as suspected it was an execution order issue. It was random because your build was highly dependent on which rotator update first. 
If you are curious this is what I do now:
- first all children system update themselves to their wanted state and update their children position and rotation
- then I check for collisions on all systems
- then I restore each system with a collision detected to their previous state and cancel their movement.

=> this is now order independent, so your landing gear works perfectly. Not yet perfect, I have yet to model torque and things like, so you could a system that is blocked at a given time but unstuck itself once its parent moved enough for example.
Will be in 20w18d. Thanks for all the detailed test cases, I feel the children entity is becoming a lot better!

**Comment by Dwarf-LordPangolin** [comment]
That's great! And yes, I agree; child entities are getting better and better. :D
