### ISSUE TITLE
[Bug] Child entities disappear when loading BP from starter block twice [20w18c]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#1911]
### Short Description of the issue:
If a ship is created, and the blueprint is loaded from the starter block a second time, all attached child entities will disappear.

### Steps to reproduce the issue:
Select the starter block, load a BP from it. Load the BP on that ship a second time. The child entities will be gone.

### Environment
- Skywanderers version: 20w18c
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4557306/output_log.txt)

**Comment by ProPeach** [comment]
Linking for convenience - Looks like a similar/the same issues as #1835 and #1793. Hope it's not too hard to fix!

**Comment by tsunamayo** [comment]
Hum I cant reproduce that issue, do you get that 100% of the time? thanks

**Comment by tsunamayo** [comment]
That dreaded issue is fixed for 20w20c. Sorry it took quite a while but I am happy it is finally gone. Thanks!
