### ISSUE TITLE
[BUG] NAND Logic stuck

### ISSUE THREAD

**Issue by YnotnA** [tsunamayo/Starship-EVO#1914]
### Short Description of the issue:

I wanted to make a flashing system but it seems that the logic block NAND can be stuck.

### Steps to reproduce the issue:
https://youtu.be/DMxCS0Q2hTE

### Environment
- Skywanderers version: 20w18c
- Graphics Card: NVIDIA GeForce RTX 2070 SUPER

### Additional information:

BP : [BugNANDLogic.zip](https://github.com/tsunamayo/Starship-EVO/files/4559633/BugNANDLogic.zip)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4559636/output_log.txt)

**Comment by captain828** [comment]
This might be related to #1888 as there is also a timer involved in a loop.

**Comment by tsunamayo** [comment]
This is fixed in latest build! Thanks
