### ISSUE TITLE
[Bug] Unbreakable lag brick

### ISSUE THREAD

**Issue by Tezlz** [tsunamayo/Starship-EVO#1915]
### Short Description of the issue:

When placing down bricks on my ship (No symmetry mode and not on a child entity) my game suddenly froze and when it began working again shortly after there was a brick on my ship that caused incredible lag when looking at it, increasing as you went closer to it. The brick is also unbreakable, this is probably the same issue as #1858 but in this instance it's a brick and not a hull block, and it has a texture now and is not just a black block.

### Steps to reproduce the issue:

I have really no idea, I just placed down some bricks and this happened, I've tried placing more bricks in the same area but was not able to recreate it.

### Environment
- Skywanderers version: 20w18c
- Graphics Card: GTX 1060

### Additional information:
Blueprint for the ship:
[Tezlz LAAT v3.0 Lag Block.zip](https://github.com/tsunamayo/Starship-EVO/files/4561445/Tezlz.LAAT.v3.0.Lag.Block.zip)

GIF of me approaching the brick with FPS counter enabled:
https://gfycat.com/realinconsequentialbordercollie

Output log:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4561441/output_log.txt)

**Comment by tsunamayo** [comment]
okay do you remember what you did just before this brick happened? also this is not the output.log from the session when it happened I guess?
Thanks!

**Comment by Tezlz** [comment]
Oh sorry about the output log, I didn't realise that it was newly made for every session. In that case I'm afraid that I no longer have the output log from when the error occured. As for what I was doing, I was just placing bricks on the inside on the ship, nothing out of the ordinary, the ship was stationary and I can't really think of anything that I did differently when building this

**Comment by Tezlz** [comment]
@tsunamayo I have just accidentally recreated the bug, this time I was using mirror mode and was just as before placing bricks without doing anything special, for a moment the game wouldn't display any of the bricks that I had placed, but their hitbox was still there but I just couldn't see them, after approx 20 seconds the bricks loaded in but my framerate was dropping hard and I noticed that I had created another unbreakable lag brick.
This time I was able to get the output log before starting a new session, I'm sending it and the blueprint for the ship.
**Output log:**
[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/4561939/output_log.zip)

**Blueprint:**
[Tezlz Imperial Shuttle Broken.zip](https://github.com/tsunamayo/Starship-EVO/files/4561951/Tezlz.Imperial.Shuttle.Broken.zip)

**Comment by Tezlz** [comment]
I have accidentally recreated the bug 3 times now, it seems to occure more often the more of the bugged bricks you already have on your ship. the last instance of the bug I was able to record into a GIF so you can see what I did and maybe get some better insight, the gif gets cut off before the lag brick actually appears but you can still see it's creation
https://gfycat.com/barrenactualfreshwatereel

**Comment by tsunamayo** [comment]
okay amazing find! I keep you posted with the fix, good work!

**Comment by tsunamayo** [comment]
@Tezlz , how was the sound when this happened? Was it bugged, like no sfx or else? Thanks

**Comment by tsunamayo** [comment]
okay, starting from 20w18d you will be able to reload your ship. Now it is not a proper fix as it will have to wait for a big refactor on the rendering side that should take care of that naturally, it is just a workaround that will allow you not loose your save. If it happens again you will still have to exit to desktop and reload the game...
If you see it happen frequently please tell me, in that case I would have to schedule that change higher on my to-do list. 
Thanks!
