### ISSUE TITLE
[BUG] Canopy Collisions incorrect

### ISSUE THREAD

**Issue by CMDBob** [tsunamayo/Starship-EVO#1917]
### Short Description of the issue:
The canopy and canopy wedge blocks have incorrect collisions, which means you can't enter them as a player, when it appears that you should be able to.

### Steps to reproduce the issue:
Build canopy, attempt to move into it. You find that you can't move into the block any further, when you clearly should be able to.

### Environment
- Skywanderers version: 20w18d
- Graphics Card: 

### Additional information:
[Image of what I mean](https://i.imgur.com/wMOKJRI.png)

**Comment by tsunamayo** [comment]
Yes it is known limitation, I will work on compound collider for ea, I keep you posted. Thanks

**Comment by tsunamayo** [comment]
Great news, this will be finally fixed for 20w19a Thanks!
