### ISSUE TITLE
[Suggestion] Advanced logic circuits

### ISSUE THREAD

**Issue by captain828** [tsunamayo/Starship-EVO#1922]
Right now, we have a pretty simple logic system, where there are 0 and 1 signals being sent out which trigger things - be it a switch, a door, rotor etc.

Unfortunately, this means that anything more complex, such as changing a specific item attribute as part of a circuit becomes technically impossible.

Here's what I propose:
### Introduce a scalable [Breadboard ](https://en.wikipedia.org/wiki/Breadboard) block
- The larger the Breadboard, the more inputs it will have
- The smallest version could support only 4 inputs, with the same size as a spaceship core
- For easy visual inspection, used inputs could light up red and available ones green
- An input allows a bi-directional data connection to a supported item (ex: a light)
- Daisy-chaining breadboards could be an option as well, in order to support and/or better structure complex logic

### Introduce a Programmable Chip that can be connected to a breadboard
- This allows controlling the various items connected to the breadboard
- Like other supported items, connecting it to a breadboard will use up an input
- It shouldn't support the direct connection of programmable items, only breadboards
- Accessing it would open the programmable chip editor
- Inside the editor we would have something like this:
![image](https://user-images.githubusercontent.com/17725004/80834257-ffeb9180-8bf8-11ea-9ef8-6ebeee26424b.png)

Where:
- **in the left-pane**, we have the items connected to the breadboard the chip is on, such as lights, rotors etc.
- we can also give more meaningful names to the items, such as _external light_, _bridge door_ etc.
- each item can have:
1. events: these are triggered by the game when something happens to the item, such as the state of a switch changing
2. functions: these represent actions that can be taken on the item, like toggling a switch, a door etc.
3. properties: these represent the underlying values that control the behavior of the item, such as the intensity or color of a light 
- **in the right-pane**, we have the _logic flowchart_ which allows setting up the logic we want
- at the top, we could have the ability to allow multiple logic flows per PC, but I actually think we should only allow one per chip for balancing reasons (as well as simplicity)

### The logic flowchart
- All charts start with an Event, something that the game triggers, such as the flip of a switch done by a player
- Placing an event is done via drag-n-drop
- Only a single event can be placed per logic chart
- Once an event is placed, we can drag from the event to create a new, connected, flow block
- Further flow blocks are created by dragging (and creating a connection to) an existing block
- Flow blocks can be:
1. decision blocks: given a value, it allows one or more decisions to be made based on it
2. processing blocks: these can range from changing a property to calling an item function
- Furthermore, when dragging to create a new flow block from a Decision Block, we will be able to specify the condition for the value we are checking, such as "_>= 45_"
- The condition could even be checked against another item value: "_>= Rotor1.Angle_"
- Creating multiple logic flowcharts could help easily set up complex circuits, such as multiple rotating parts that need to be executed in a very specific order to avoid geometry blocking

### Why I think we should have such a logic system
1. it helps enable complex logic such as programmatically changing item properties, something the current system cannot do
2. it can simplify and enable the development of more complex features such as programmable displays and sounds
3. the breadboard approach promotes building in a scalable & cleaner way for power users
4. it could also allow adding other advanced logic features, such as Constants, Memories & Math units as extension modules
5. users that don't build complex logic systems can stick with the current logic system, which is perfectly fine for simple stuff - this doesn't need to be exclusive
6. the logic flowchart can be easily extended to support extra features, such as wait blocks and loop blocks
7. this kind of predominantly-visual logic system makes it more approachable to users compared to a full-blown scripting language
8. most if not all of the technical requirements for this feature already exist - they just need to be exposed and connected via the UI (a refactor will probably still be required in places)

Let me know what you think - I know this is a long read but, hopefully, we can come up with a nice system that can be implemented.

**Comment by schlid** [comment]
I respect how in depth you've gone with the content of this post but I feel this style of programming even block based would be more suitable for a mod than core gameplay

**Comment by captain828** [comment]
Firstly, to clarify, this isn't meant to replace the "blocky" way of doing it as that is perfect for simple logic which most users will stick with anyway.
It is just meant to add more to the table which otherwise would be impossible.

Whether the game goes with something visual or "blocky" I frankly don't mind - my main issue is really with the lack of the current system to do things like programmatically changing item properties, like a rotors min angle etc.

There is just no way to do that right now nor do I see a way to do it with how the current system works as all it sends is a 0 / 1.

In my eyes, a perfect system would be how it works in Stationeers where you have various extra logic modules as well as writers and readers that can access connected item properties.
You can do everything you want this way using a "blocky" approach but it would require a complete rewrite of the current system.
There is even an Integrated Circuit system that can help simplify things for power users while not taking away from the "blockiness".

**Comment by tsunamayo** [comment]
Okay I can see the use for this, but this is a big dev.
My plan was more:
- Hotkey block becomes input block (essentialy merge with query block). You can link a system to it, and choose a list of event and create a condition.
- Add an output block. Link this to a system, and update one of several params linked to that system.
- Regarding your use I was more into having a LUA type language inside the game. It is something made for advanced user, I feel a LUA type coding will be less of a coding mess to implement on my side ;)
In anycase we are talking about post ea dev, I want to make more progress on gameplay at this stage. 
Cheers

**Comment by captain828** [comment]
I see what you're saying.

In that case, you could just add separate I/O blocks. I don't think there is a need to change the hotkey blocks from how they are now.

I'm not sure if a LUA-type scripting would be easy to get into even for a power user. 
To me, that sounds more for modders than users.

And yes, I agree this would be more of a post-EA dev or at least after survival is fleshed out.

**Comment by tsunamayo** [comment]
the new input key would extend the hotkey logic to any system.
You plug a yoke into the the input command, you get the current hotkey functionality.
You plug a system into the input command, instead of picking "Key 1" you get to pick a value from the system. Ie angle or speed for rotator (so it replace the query gate), or for example you plug the spaceship computer and can pick "On Landed" "On Docked" "On Lightcruise" ect ect.
It is a super hotkey if you will ;)

**Comment by captain828** [comment]
Sounds great!

So when do you think this feature will arrive? :)

PS: feel free to close this issue.

**Comment by tsunamayo** [comment]
Not sure when, but not too long...

**Comment by schlid** [comment]
Aware you closed this one so not sure if I'm breaking an unspoken rule of etiquette by replying, but you mentioned  _or for example you plug the spaceship computer and can pick "On Landed" "On Docked" "On Lightcruise" ect ect._  - If a trigger was to active thrust in <axis> then we could build little fins and flaps that wiggle when you roll your ship and so on which could be another layer of intricacy and detail on peoples builds. 

Just a thought
