### ISSUE TITLE
[BUG] Can't change name of ship

### ISSUE THREAD

**Issue by AfterRebelion** [tsunamayo/Starship-EVO#1924]
### Short Description of the issue:
With the new Entity Button in Codex, the rename button doesn't work anymore

### Steps to reproduce the issue:

1. Load a ship
2. Select that ship by adding or removing a block (Painting it doesn't seem to work anymore)
3. Open the codex, select the ship
![imagen](https://user-images.githubusercontent.com/559819/80858897-f3008980-8c5c-11ea-8c9b-28c0b30bf3a9.png)
4. Select the pencil button to change the name

Expected result:
The interface changes to let you rename your ship

Found result:
Nothing happens

### Environment
- Skywanderers version: 20w18e
- Graphics Card: AMD RX 580

**Comment by tsunamayo** [comment]
Issue fixed for 20w18f. Thanks for being the first to report it!
