### ISSUE TITLE
Shields do not enclose childentities

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Starship-EVO#1927]
Maybe its more a Question as a Suggestion, 
The Suggestion arises from the question:

Is it planned one day to integrate a possibility to avoid this?

![Starship EVO_2020_05_02_14_15_56_024](https://user-images.githubusercontent.com/43222403/80863910-a8443900-8c7f-11ea-99e4-612203ff6641.jpg)
![Starship EVO_2020_05_02_14_21_51_812](https://user-images.githubusercontent.com/43222403/80864086-89927200-8c80-11ea-960d-8a38b43dc478.jpg)

**Comment by tsunamayo** [comment]
Yep I still need to work on this. tx

**Comment by tsunamayo** [comment]
Feature added for 20w24d. Thanks!
