### ISSUE TITLE
[BUG] Ship control with "build-selected" ship not possible

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Starship-EVO#1929]
### Description of the issue:

Once you have placed a block, it is no longer possible to grip the joystick when you are sitting on a seat. If you try you will leave the seat. In addition, "Press F" is no longer displayed when you look at controllable blocks of the selected ship. 
### Environment
- Skywanderers version:  20w18e
- Graphics Card: gtx 1070 Mobile

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4567968/output_log.txt)

**Comment by tsunamayo** [comment]
I cant reproduce that one, I have been seating and griping yoke a lot. Isnt it something with your build? Do you get this on all your build? Maybe you will need to send me the bp so I can investigate. Thanks

**Comment by Battlepixel** [comment]
No I have the Bug on all builds and my Friend too. But it was MP. Today in Single player I cant also reproduce but yesterday I am sur it was also SP. I will test MP again and keep you posted.

**Comment by Battlepixel** [comment]
In version 20w18e we didn't find a way around the bug, but yet we can not reproduce so I will close the post for now.

**Comment by tsunamayo** [comment]
okay great! btw you dont need to close the issue, I prefer to do it on my own so I can know whats up! Cheers
