### ISSUE TITLE
[BUG] Different firing directions for client and host

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Starship-EVO#1930]
### Description of the issue:
While I just shot out straight forward, my Friend saw the following
![](https://cdn.discordapp.com/attachments/263800409611698196/706165746920849539/Screenshot_21.png)

This is just a snapshot, for him the weapons periodically move horizontally from left to right as soon as I take control of the ship. If I just shoot out straight forward, he sees me shooting in all directions according to the changing weapon orientation.

### Environment
- Skywanderers version:  20w18e
- Graphics Card: gtx 1070 Mobile

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4568007/output_log.txt)

**Comment by tsunamayo** [comment]
Can you explain me how these turret are setup / controlled? There is many different way for turret control, it is more a turret problem than a firing problem. Thanks

**Comment by Battlepixel** [comment]
"spaceship-targettingmode"

**Comment by tsunamayo** [comment]
Issue fixed for 20w20b. Thanks!
