### ISSUE TITLE
[BUG] Broken Export Blueprint Button

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Starship-EVO#1931]
### Description of the issue:
Its not mentioned in #1924 but the possibility to click the Export-Button is also broken.

### Environment
- Skywanderers version:  20w18e
- Graphics Card: gtx 1070 Mobile

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4568007/output_log.txt)

**Comment by tsunamayo** [comment]
Okay issue fixed for 20w18f. Cheers

**Comment by captain828** [comment]
@tsunamayo still broken for me in 20w18f
All other UI buttons work fine.

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4570493/output_log.txt)
