### ISSUE TITLE
Infinite Loading Screen

### ISSUE THREAD

**Issue by CaptainKyros** [tsunamayo/Starship-EVO#1932]
### Short Description of the issue:
I keep getting stuck on the loading screen
...

### Steps to reproduce the issue:
Create a new save?
...

### Environment
- Skywanderers version: 20w18e
- Graphics Card: Intel HD Graphics 4600

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4568177/output_log.txt)

**Comment by tsunamayo** [comment]
I am sorry to tell you that your GFX card is below minimum config... Are you playing other game too?

**Comment by CaptainKyros** [comment]
While I'm playing Starship EVO, no. Is there a way to refund the game as it used to run fine back when it had the pixel graphics

**Comment by tsunamayo** [comment]
No I mean what kind of game are you playing on this PC? What is the rest of your config?

**Comment by CaptainKyros** [comment]
Minecraft, Terraria, the new halo master chief collection ran well on low settings
my config i think is [this](https://github.com/tsunamayo/Starship-EVO/files/4569409/DxDiag.txt)

**Comment by tsunamayo** [comment]
ok, please ping me on kickstarter!

**Comment by CaptainKyros** [comment]
I didn't pledge to the kickstarter, I was a late backer

**Comment by CaptainKyros** [comment]
> I didn't pledge to the kickstarter, I was a late backer

@tsunamayo ?
