### ISSUE TITLE
[BUG] Cannot rename ship/blueprint

### ISSUE THREAD

**Issue by FlyingDebris** [tsunamayo/Starship-EVO#1933]
### Short Description of the issue:

When using the new codex blueprint screen, clicking the name edit button does nothing.

### Steps to reproduce the issue:

1: Spawn entity

2: Open codex blueprint menu

3: Attempt to rename

### Environment
- Skywanderers version: 20w18e
- Graphics Card: GTX 1050 Ti

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4568576/output_log.txt)

![image](https://user-images.githubusercontent.com/38392651/80873152-8dc08e80-8c84-11ea-8aef-dbf81b270516.png)

**Comment by tsunamayo** [comment]
Bug was fixed, for 20w18f. Patch coming soon ;) Cheers
