### ISSUE TITLE
[Bug] Information window in Entity tab does not scroll down fully [20w18e]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#1934]
### Short Description of the issue:
The information for ships in the Entity tab is cut off because the window cannot scroll down that far.

### Steps to reproduce the issue:
View ship in Entity tab, scroll down; the bottom will be cut off at the level of the little gear icon.

### Environment
- Skywanderers version: 20w18e
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20200502135631_1](https://user-images.githubusercontent.com/33041786/80873245-be9cc580-8c7c-11ea-9e51-a1e56d95d357.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4568577/output_log.txt)

Also: the entity tab is super-cool; great choice! It's much more convenient to have that function handled by an element of the UI, and it also frees up space on ships that would otherwise need to be taken up by a starter block (which can be a real problem for smaller ships where space is at a premium). In addition to the convenience of it, the fact that the icon is a little picture of your ship is a neat little touch. :)

**Comment by tsunamayo** [comment]
yes thanks, I also did a pass on making the ship looks good using the same trick used for the brick icons. I plan to add a button where you can export some snapshot png of your ship in all angles, with transparent background so people can show their ship around. I will try to plug this into steam.

**Comment by tsunamayo** [comment]
Actually the scroll was fine, it was due to the weapon widget not yet implemented. I have removed it, will put it once it is properly done. Cheers
