### ISSUE TITLE
[Bug] Retracting landing gear when docked launches ship into space [20w18e]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#1935]
### Short Description of the issue:
Raising gear when docked to a platform causes something to happen that propels ships away from the platform at high speed; the game still considers the ship to be in a "Docked" state while this occurs.

### Steps to reproduce the issue:
Dock ship, retract gear.

### Environment
- Skywanderers version: 20w18e
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4568630/output_log.txt)

**Comment by tsunamayo** [comment]
Yes I saw this, I need to deal better with children entity collisions.

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin  finally managed to improve my physics to deal with that for 20w23d. Thanks
