### ISSUE TITLE
[BUG] GUI disappears when exiting Add new server on the "Join Server" tab

### ISSUE THREAD

**Issue by FlyingDebris** [tsunamayo/Starship-EVO#1936]
### Short Description of the issue:

Opened the join servers tab in the main menu, then went to add a new server. Closed out without inputting anything, and all GUI disappeared.

### Steps to reproduce the issue:

1.) Open "Join Server" tab

2.) Click "Add New Server"

3.) Exit out of tab. (Works with both X in top right corner, and pressing Esc.)

### Environment
- Skywanderers version: 20w18e
- Graphics Card: GTX 1050 Ti

### Additional information:
![image](https://user-images.githubusercontent.com/38392651/80891141-21e42300-8c90-11ea-8565-0cc2e799272b.png)

![image](https://user-images.githubusercontent.com/38392651/80891167-5a83fc80-8c90-11ea-944d-bd24de0b6504.png)

![image](https://user-images.githubusercontent.com/38392651/80891139-1bee4200-8c90-11ea-8639-b2c37a55f266.png)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4568712/output_log.txt)

**Comment by tsunamayo** [comment]
Nice catch indeed! Thanks for reporting that.

**Comment by tsunamayo** [comment]
Issue fixed for 20w18f. Thanks!
