### ISSUE TITLE
[Bug] Export manu disappears after painting

### ISSUE THREAD

**Issue by Lsutehall** [tsunamayo/Starship-EVO#1937]
### Short Description of the issue:

The export tab doesn't appear in the codex if the last action you took on a ship was to apply paint. Works correctly after placing other types of block though.

Also, it could do with standing ut a bit more, either by adding a border or by moving it into the same stack as the other codex tabs.

### Steps to reproduce the issue:

Place a block/brick/logic element, press tab: export menu appears.
Paint something, press tab: export menu is missing.

### Environment
- Skywanderers version: 20w18e
- Graphics Card: gtx 1060

### Additional information:

Just placed a logic gate:
![20200502213225_1](https://user-images.githubusercontent.com/40872394/80891609-017e8d80-8cbd-11ea-9bce-b1e1e5919b3c.jpg)
Just applied blue paint:
![20200502213236_1](https://user-images.githubusercontent.com/40872394/80891613-093e3200-8cbd-11ea-9da3-31f0cbb4a825.jpg)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4568823/output_log.txt)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
I made a different stack as I plan to add more button ;). They will move again a bit for sure.

**Comment by tsunamayo** [comment]
Issue fixed for 20w18f. Thanks!
