### ISSUE TITLE
[Bug] New Stats UI doesn't show child entities on ship preview

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Starship-EVO#1938]
### Short Description of the issue:
Child entities seem to not show up on the ship preview on the new stats UI. They show up properly in the codex tho.
![image](https://user-images.githubusercontent.com/53021785/80892471-b5652600-8c87-11ea-86a7-c9e3b0a74762.png)
![image](https://user-images.githubusercontent.com/53021785/80892478-c44bd880-8c87-11ea-90bb-526591a728c3.png)

...

### Steps to reproduce the issue:
- Spawn a ship with noticeable child entities
- compare it to the ship preview
- issue
...

### Environment
- Skywanderers version: 20w18e
- Graphics Card: AMD Integrated Graphics

### Additional information:
Placing a sticker updated the preview once
Ok so when I update the parent entity the child entities show up in the preview
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4568955/output_log.txt)

**Comment by tsunamayo** [comment]
Not reproducing but I have a bug were update the children entity dont update the preview. Maybe they are related... Thanks

**Comment by tsunamayo** [comment]
@Aiwii can you send me your blueprint? Thanks

**Comment by Aiwii** [comment]
@tsunamayo [SK38 Aphrysus (2).zip](https://github.com/tsunamayo/Starship-EVO/files/4569470/SK38.Aphrysus.2.zip)

**Comment by tsunamayo** [comment]
Thanks a lot, issue fixed for 20w18f! Cheers
