### ISSUE TITLE
[Suggestion] Change how child yokes work

### ISSUE THREAD

**Issue by captain828** [tsunamayo/Starship-EVO#1939]
Currently, if you want to control your ship from a child yoke (so a yoke on a rotor or rail etc.) you have to place a yoke on the parent and then connect the child yoke to it.

This is not very intuitive as many players will just try to link the child yoke to a ship computer on the parent and see that it doesn't work, prompting them to think it's not possible to do that.

I understand why it's set up this way, as the yoke gives the orientation of the ship and we don't want to allow it to change on a whim with a rotor block.

After a short discord discussion, two options were found:
1. the orientation is captured only on the initial placement of the yoke - further yoke movement doesn't change the orientation
2. when placing a yoke on a child, warn the player with a message that says "A child yoke can only be used by linking it to a parent yoke." - credit goes to @ProPeach for this

The first option is a bit more robust and also similar to how other building games do it, where the direction of travel can't be changed programmatically. A message could also be added to clarify for the player how the ship orientation is selected.

The second option is a lot faster to implement and serves just to clarify to the player that there is a way to use a child yoke.

**Comment by tsunamayo** [comment]
I will go with option two, as the first might not be the wanted behaviour (cockpit built in opened position for example, or never aligned).

**Comment by tsunamayo** [comment]
Will be in 20w18f. Cheers
