### ISSUE TITLE
[Bug?] Can request to land on occupied landing pads

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Starship-EVO#1940]
### Short Description of the issue:
Landing pads can't be occupied anymore.
https://streamable.com/phnx27
...

### Steps to reproduce the issue:
- Land a ship on a pad
- Get another ship
- Request to land on the same pad
- Issue
...

### Environment
- Skywanderers version: 20w18e
- Graphics Card: AMD Integrated Graphics

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4569087/output_log.txt)
![image](https://user-images.githubusercontent.com/53021785/80893170-3377fb80-8c8d-11ea-9a52-2cf8b37bb3e5.png)

**Comment by tsunamayo** [comment]
Issue fixed for 20w18f. Thanks!
