### ISSUE TITLE
[Suggestion] Remove unintuitive logic behavior

### ISSUE THREAD

**Issue by Tezlz** [tsunamayo/Starship-EVO#1941]
When connecting a button to a timer with a 0.5 second delay or lower, the timer outputs a signal as expected. But when the timer delay is 0.6 or higher it doesn't send an output after the first time, better explained in the gif below. 
https://gfycat.com/sickdazzlingboutu

I was originally going to report this as a bug but I was told that this was intentional behavior, so sorry about the vague title as I wasn't really sure on what the actual suggestion is other than to remove this behaviour as it's unintuitive and confused me and will probably confuse a lot of players as well.

**Comment by talrey** [comment]
Possibly the same issue as
https://github.com/tsunamayo/Starship-EVO/issues/1914
https://github.com/tsunamayo/Starship-EVO/issues/1888
https://github.com/tsunamayo/Starship-EVO/issues/1509

I agree that it's a bit unintuitive, and probably unnecessary now - wasn't it added when logic didn't have single-input linking?

**Comment by tsunamayo** [comment]
Let me have a look I am not sure to understand atm.

**Comment by Arschpollo13** [comment]
We took a closer look at it and basically everything is possible with the current system. Toutorials about the switching behavior of the components and how to design pulse generators would certainly also suffice.
Here is a possible exampe to solve your problem, if the timer delay is longer then the input signal.
There are other possible solutions where a quick double click or holding the button, can't breake the system.

![](https://cdn.discordapp.com/attachments/263800409611698196/706286237182328852/Screenshot_25_LI.jpg)

If you have other problems wich logic then ask the community, i think they can help.

**Comment by Tezlz** [comment]
I personally feel like something as simple as having a delayed signal longer than 0.5s like what I tried to do in my original post isn't something that you should have to use an OR-gate, any other workarounds or have to ask the community for help with, it should just work. 
A system like having a button activate one thing first and then after a delay activate some other thing more than 0.5s later is something that a lot of new players probably will try to do for landing gear or similar things, having that not work for seemingly no reason is really unintuitive and will probably turn some players away from logic overall

**Comment by talrey** [comment]
I agree. I think the core issue appears to be timers not updating their output if a state change happens before they finish. Example:

```
Button    : ....''''........ (1s On)
Timer 0.25 : .....''''....... (1s On shifted .25s)
Timer 2.0 : ........'''''''' (stuck On, missed Off signal)
```

**Comment by tsunamayo** [comment]
Okay indeed that was an issue and confusing for the player. Will be fixed for 20w19b. Thanks!
