### ISSUE TITLE
[Bug] Delete doesn't seem to mirror

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Starship-EVO#1944]
I was recently trying to work on one of my older ships and because I figured that a stretched block would be better performance-wise I decided to replace the old single blocks with some stretched replacements. With there being no mass delete I figured the fastest way would be to use the mirror and delete blocks manually. I quickly realised though that the delete did not seem to be mirroring. The screenshot provided shows that one side has been deleted but the other hasn't. You will also notice that several of the blocks have become black ghost blocks. I believe that the issue is linked to that. Given the large ship I am currently working on I suspect that the ghost blocks and the non mirrored deleting may be a result of a memory issue, this is just speculation though. I couldn't see anything in the output log that looked out of place to me but I figured I would include it in case anything stood out to you. I also included a gif, one interesting note is that the delete particle effect still plays in the mirrored location.
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4569418/output_log.txt)

![image](https://user-images.githubusercontent.com/43644633/80895721-d6596580-8cdf-11ea-88b2-e6a999262acc.png)

![delete gif](https://user-images.githubusercontent.com/43644633/80896122-ddce3e00-8ce2-11ea-9945-5a4cc9ea92d4.gif)

**Comment by Garrett-C** [comment]
Just wanted to add an extra note, I have now tested it at other parts of the ship and it only seems to have the issue in that spot.

**Comment by Garrett-C** [comment]
It seems to mainly affect an area that's about 144 blocks long in the middle of the ship. Outside of that it seems to be very inconsistent, sometimes it mirrors sometimes it doesn't.

**Comment by tsunamayo** [comment]
okay interesting, if you could send me the blueprint, I might have a change of observing the ghost block in its natural habitat. What it is your PC config btw? Thanks!

**Comment by Garrett-C** [comment]
[Obsidian Class refit.zip](https://github.com/tsunamayo/Starship-EVO/files/4570216/Obsidian.Class.refit.zip)

There is the blueprint, it is quite intense to load and have in-game, I tend to use the debug settings to turn shadows off, etc. I also really recommend spawning it somewhere in empty space and not near the torus. 

In terms of my current PC config:
CPU - AMD FX-6300
GPU - GTX 1060 
RAM - 16GB

**Comment by Garrett-C** [comment]
In terms of where it can be observed I have found that the area in front of the big door tends to do it. Ghost blocks seem to appear when you delete quite quickly.

**Comment by tsunamayo** [comment]
Okay I can see the issue indeed. I dont really think it is a delete issue, I think it is linked to the upgrade of the old chunk format. These blocks are not in a mirrored position, I think their orientation are differents... Which I know it sucks as these dont have orientation. I will see what I can do in the future but I cant really spend too much time on that atm... I keep you posted, this is really an insane build, great for testing out the limit of the game (yes shadow are an issue!)

**Comment by Garrett-C** [comment]
Ah that would make a fair amount of sense yeah, if it sees blocks in different orientations as different blocks entirely then the deleting function wouldn’t want to mirror. Indeed that is very interesting. I guess one solution would be having the mirrored delete not care what it deletes but I can see a lot of potential issues there. I would have thought that they were mirrored when I built them but the old mirror system may have handled things differently, or I built them in such a way that it did use a different orientation. Didn’t expect this to be such in interesting bug.

100% understand that this bizarre occurrence can’t be looked at now. If you get a chance to solve it in the future at some stage that would be greatly appreciated but no rush, there are more pressing matters. Thanks for looking at it for me.

Yeah the point of this ship is very much to see what the game can handle. It’s kind of a pet project and one I will complete someday.

I mean the shadows can make things look so much better so even if they can’t be optimised it may be worth keeping them but just having them in the graphics settings or something. They only really become an issue when you go to scales that aren’t common for now.

**Comment by tsunamayo** [comment]
I will definitely use this to improve things around, I need to do further optimization on the shadow side.

**Comment by Garrett-C** [comment]
Glad to hear it. If it can help even in its current state then it’s a win. The more tools you have to test on the better.

**Comment by tsunamayo** [comment]
Hi, this should be fixed now!
