### ISSUE TITLE
[Bug] Cant Save Blueprint

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Starship-EVO#1946]
### Short Description of the issue:
The Exportbutton still doesnt work for me. So I cant save.

### Steps to reproduce the issue:

Try to Export a Blueprint. But Renaming is working now.
It doesnt work with all Blueprints so it is build-independent.

### Environment
- Starship EVO version: 20w18f
- Graphics Card:  GTX 1070 Mobile

### Additional information:
![Starship EVO_2020_05_03_10_37_24_689](https://user-images.githubusercontent.com/43222403/80909636-21986600-8d2a-11ea-988a-08c0057b3fcd.jpg)
If I click the Button nothing happend and It doesnt save.

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4569836/output_log.txt)

**Comment by tsunamayo** [comment]
Okay sorry indeed, there was a new collision bug due to the improved ship preview. This will be fixed for 20w19a! It took time but we will get there ;)

**Comment by Battlepixel** [comment]
If you keep your current motivation and your commitment, there is no doubt about it! ;)
