### ISSUE TITLE
[Bug] Disabling certain graphic options causes menu overlay bug

### ISSUE THREAD

**Issue by Tezlz** [tsunamayo/Starship-EVO#1949]
### Short Description of the issue:
If you disable Vignetting, UI Post Effects, Anti Aliasing, Bloom and Chromatic Aberration in the graphic options, when you try to exit the options menu a new options menu will appear over the graphic options, exiting that options menu causes the pause menu to appear above all the other menus, exiting the pause menu again will not hide any menus and will instead return you to the game with all the menus overlaying the game, and the rendering appears to have frozen as the game doesn't show any movement and is just frozen until you press escape again and a new pause menu will overlay all others.

### Steps to reproduce the issue:
Start the game, load into a character, press escape -> options ->graphic, disable Vignetting, UI Post Effects, Anti Aliasing, Bloom and Chromatic Aberration in any order, exit the options menu.

### Environment
- Starship EVO version: 20w18f
- Graphics Card: GTX 1060 6GB

### Additional information:
GIF of the issue (Already had all the options disabled except for Chromatic Aberration so the gif would be shorter):
https://gfycat.com/unsightlyidealisticarachnid

Output Log:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4570585/output_log.txt)

**Comment by tsunamayo** [comment]
It was pretty nasty indeed. Issue fixed for 20w19b. Thanks!
