### ISSUE TITLE
[Bug] Opening graphic options resets resolution option to native resolution of monitor

### ISSUE THREAD

**Issue by Tezlz** [tsunamayo/Starship-EVO#1950]
### Short Description of the issue:

If you change the resolution in the graphic options to anything other than the native resolution, exit the graphic options, open graphic options again it will automatically put the resolution option back to native resolution

### Steps to reproduce the issue:
Start the game, press options -> graphic, change the resolution to anything other than native resolution, exit graphic options, go back into graphic options and it has automatically put the resolution option back to native resolution.

### Environment
- Starship EVO version: 20w18f
- Graphics Card: GTX 1060 6GB

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4570711/output_log.txt)

**Comment by tsunamayo** [comment]
Issue fixed for 20w19b. Thanks for that Graphic Settings issue pass! Cheers
