### ISSUE TITLE
[Bug] Blueprint export button does not work

### ISSUE THREAD

**Issue by FlyingDebris** [tsunamayo/Starship-EVO#1951]
### Short Description of the issue:

Renaming the ship works fine now, but nothing happens when you try to hit the Export button.

### Steps to reproduce the issue:

1: Rename ship

2: Hit export button

### Environment
- Starship EVO version: 20w18f
- Graphics Card: GTX 1050 Ti

### Additional information:

![image](https://user-images.githubusercontent.com/38392651/80925895-8de28c00-8d61-11ea-9a09-4091262648b2.png)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4571708/output_log.txt)

**Comment by tsunamayo** [comment]
Yes indeed, this will be fixed for 20w19a landing today. Thanks
