### ISSUE TITLE
[Bug] Hinges placed & dragged in symmetry mode can overlap [20w18f]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#1952]
### Short Description of the issue:
Hinges can be placed that intersect each other in symmetry mode.

### Steps to reproduce the issue:
Turn on symmetry mode, place and drag a hinge across the plane of symmetry.

### Environment
- Starship EVO version: 20w18f
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20200503170417_1](https://user-images.githubusercontent.com/33041786/80926980-5cb58c00-8d60-11ea-91b4-663249ae021d.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4571960/output_log.txt)

**Comment by tsunamayo** [comment]
Issue fixed for 20w19b. Thanks!
