### ISSUE TITLE
[Bug?] Difficult to highlight hinge base for deletion [20w18f]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#1954]
### Short Description of the issue:
Not sure this is a bug as much as a quality of life issue, but: it's hard to find a good angle to highlight the hinge base for deletion, because the game tends to highlight the moving part of the hinge. The crosshair has to be pointing pretty much at the lowest .25m of the base to highlight it; otherwise it's usually the moving part that's highlighted.

### Steps to reproduce the issue:
Place hinge, try to highlight base.

### Environment
- Starship EVO version: 20w18f
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
Despite looking like it should highlight the base, this is actually highlighting the moving part.
![20200503211351_1](https://user-images.githubusercontent.com/33041786/80932037-19b8e000-8d83-11ea-816a-6de1df0acc5e.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4572537/output_log.txt)

**Comment by tsunamayo** [comment]
True it is finicky...

**Comment by tsunamayo** [comment]
Fixed for 20w20b, hinge now have a much better hitbox (a compound of a cylinder and a box), and the base is also tighter. Cheers
