### ISSUE TITLE
[smallBug] At 2560 x 1080 resolution the patch notes looks a bit weird

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Starship-EVO#1955]
### Short Description of the issue:
![image](https://user-images.githubusercontent.com/53021785/80932314-49b0b500-8d7c-11ea-9ede-cc1b92fa9b0c.png)

...

### Steps to reproduce the issue:
change resolution to 2560x1080
...

### Environment
- Starship EVO version: 20w19a
- Graphics Card: AMD integrated graphics

**Comment by tsunamayo** [comment]
Fixed for 20w19c. That was bugging me, that is the first thing people will see when they launch the game! cheers
