### ISSUE TITLE
[Bug] Breaking Item stands that have items leaves glow effect

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Starship-EVO#1956]
### Short Description of the issue:
![image](https://user-images.githubusercontent.com/53021785/80932848-82ea2480-8d7e-11ea-8a57-fe7079d7ce44.png)
I broke an item stand and this happened
...

### Steps to reproduce the issue:
- Place an item stand and put an object in it
- Break item stand
- Issue
...

### Environment
- Starship EVO version: 20w19a
- Graphics Card: AMD integrated graphics

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4572584/output_log.txt)

Also, the item stands are really nice
![flower](https://user-images.githubusercontent.com/53021785/80932905-b9c03a80-8d7e-11ea-92db-6902ebc49196.gif)
I think I'm going to use them to display flowers :)

**Comment by tsunamayo** [comment]
Issue fixed for 20w19b! omg in this current state this will make the game lag if used a lot...
