### ISSUE TITLE
[Bug] Deleting hinge left orphaned moving part [20w19a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#1957]
### Short Description of the issue:
I deleted a hinge, and the moving bit got left behind somehow.

### Steps to reproduce the issue:
1. Turn on symmetry mode.
2. Click-drag to place a hinge that straddles the symmetry line. Note that when you do this, the game will **not** give you the usual warning that it can't build an overlapping part.
3. Highlight the hinge and delete it. A second hinge will appear to be there; that is because of [this other bug](https://github.com/tsunamayo/Starship-EVO/issues/1958).
4. Place a new block brick somewhere to refresh the ship and get rid of the ghost symmetry block. The moving hinge part will still be hanging there, and you can even place things on it.

I included the blueprint, but I'm not sure it'll do you any good; saving and reloading the game caused the orphaned piece to vanish. I'm still including it in case there's something you can tell about this in it.

### Environment
- Starship EVO version: 20w19a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20200503224045_1](https://user-images.githubusercontent.com/33041786/80934806-7ae6b080-8d8f-11ea-967d-725ac5a9d977.jpg)

![20200503224053_1](https://user-images.githubusercontent.com/33041786/80934809-7cb07400-8d8f-11ea-86c2-3fb9a61856d7.jpg)

[Orphaned Hinge Bug.zip](https://github.com/tsunamayo/Starship-EVO/files/4572680/Orphaned.Hinge.Bug.zip)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4572681/output_log.txt)

**Comment by tsunamayo** [comment]
Even when reactivating the overlap bug I cant seem to reproduce this one... The fact that you were able to put block on the children base bother me, it means it worse than just the geo rebuild bug.

**Comment by captain828** [comment]
@tsunamayo I also encountered this issue but can reproduce it all the time:
1. set symmetry mode on
2. place 2-to-1 Offset block right on the symmetry line
3. place hinge on top of the offset block (note how the overlap warning doesn't happen)
4. delete it and observe:
- the hinge is now ghosted: the geometry is there but not the mesh and object
- placing another block refreshes the geometry but leaves us with this:
![image](https://user-images.githubusercontent.com/17725004/81439670-64699c00-9177-11ea-8c98-6e7e3adeb4eb.png)
- the new geometry has a mesh and you can place things on it but can't delete it
![image](https://user-images.githubusercontent.com/17725004/81439817-a5fa4700-9177-11ea-86d6-282fcc7affa0.png)

**Comment by tsunamayo** [comment]
@captain828 Okay amazing find and test case, I was able to reproduce and finally close that bug, for 20w22b. Thanks!
