### ISSUE TITLE
[Bug] Invisible collision outside of brick's physical size [20w19a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#1960]
### Short Description of the issue:
The brick cube collides with things that are beside it, when it should be passing by them freely.

### Steps to reproduce the issue:
Not sure, because it doesn't happen with that brick every time or in every orientation; however, I'm including the blueprint that it does happen on, so you can see it directly.

### Environment
- Starship EVO version: 20w19a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
[Invisible Clipping Bug.zip](https://github.com/tsunamayo/Starship-EVO/files/4572888/Invisible.Clipping.Bug.zip)

Trigger the door with the red button at the back of the ship:
![20200504003633_1](https://user-images.githubusercontent.com/33041786/80938608-614d6500-8d9f-11ea-8955-54d22f7e22b7.jpg)

This gets blocked:
![20200504002939_1](https://user-images.githubusercontent.com/33041786/80938425-b177f780-8d9e-11ea-89d2-1fb582b7da1e.jpg)

But removing the unpainted brick frees it up:
![20200504002850_1](https://user-images.githubusercontent.com/33041786/80938422-af159d80-8d9e-11ea-8ab0-1271b73f0df6.jpg)

As you can see, it's getting stuck on the door frame, despite the fact that it should fit completely inside the door frame.
![20200504003350_1](https://user-images.githubusercontent.com/33041786/80938515-0582dc00-8d9f-11ea-9628-adb87834ccc9.jpg)

Once the brick is removed, the door can close just fine:
![20200504003425_1](https://user-images.githubusercontent.com/33041786/80938521-0ca9ea00-8d9f-11ea-91ad-85323e475587.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4572881/output_log.txt)

**Comment by Sullos** [comment]
I have noticed this too, most of my ships moving structures which don't have any form of collision (as I am a changed man, I make sure things don't clip anymore) no longer work. Simple sliding doors, landing gear etc. no longer work to their full intended degree.
Thanks

**Comment by rabenherz-games** [comment]
I noticed the same on a ramp, so I built a simple testing rig to showcase it:

![20200504203825_1](https://user-images.githubusercontent.com/63264527/81001126-91504300-8e47-11ea-9bf4-695144003259.jpg)

As you can see, the hinge should be able to move freely to the 0° position but gets stopped by invisible collision roughly around 45°
This definitely still worked before the last update, if that helps.

**Comment by tsunamayo** [comment]
I am not sure to understand, which kind of collision is it? At first I though it was a brick placement one, but looking at the latest it seems a children entity one. Maybe both? Thanks

**Comment by tsunamayo** [comment]
okay it is a children entity one, I must have messep up something while adding compound colliders:
![image](https://user-images.githubusercontent.com/6604318/81020986-1289f300-8ea5-11ea-9aae-379cb0b6edbe.png)

**Comment by tsunamayo** [comment]
Issue fixed for 20w19b. Thanks a lot all!
