### ISSUE TITLE
[Bug] Odd round thruster + brick bounding boxes [20w19a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#1962]
### Short Description of the issue:
When putting some round thrusters on a build, I found that they were doing something weird.
This works:
![20200504031729_1](https://user-images.githubusercontent.com/33041786/80947668-43d7c580-8db6-11ea-92d9-2e18e8fa57de.jpg)

But this doesn't:
![20200504031735_1](https://user-images.githubusercontent.com/33041786/80947682-46d2b600-8db6-11ea-8afc-084333cc655f.jpg)

The only difference is which face the brick is attached to; these should behave the same but they don't.

This may be the same thing that prevents the wedge bricks from being placed next to the thrusters, as the previously placed bricks have been in the pictures above.
![20200504031028_1](https://user-images.githubusercontent.com/33041786/80947775-75509100-8db6-11ea-9e8e-dff6c1ca1460.jpg)

### Steps to reproduce the issue:
Place a round thruster brick, scale it to 1m across, and try to place bricks as shown next to it.

### Environment
- Starship EVO version: 20w19a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4573526/output_log.txt)

**Comment by tsunamayo** [comment]
Bug fixed, same reason as #1962. Will be in 20w19b. Thanks!
