### ISSUE TITLE
[Suggestion] Remove window tile borders

### ISSUE THREAD

**Issue by captain828** [tsunamayo/Starship-EVO#1963]
Right now we can place thin wedge and straight window tiles that come with a pre-determined border.
We can color the window to give it a slight tint and the border individually (although it's finicky).

Unfortunately, it also means that we are very limited when it comes to these borders as they only come in one size. We can't make them thinner, thicker or remove them.

I propose getting rid of the current borders completely, so just keep plain glass, and instead to be given the necessary blocks to make our own borders.
We would probably need 3 thicknesses like with the small blocks, so small, half and quarter, to allow all possibilities.

This would allow:
1. for much greater control when building windows, cockpits and canopies
2. solving the current painting issue where borders can only be painted from the sides
3. for even more build options due to the new border blocks

**Comment by tsunamayo** [comment]
No I wont remove them, but I will add some pure transparent one, so you will be able to do what you are asking for. Cheers
