### ISSUE TITLE
[Bug] Certain buttons don't work on 1920x1200 res [20w19b]

### ISSUE THREAD

**Issue by captain828** [tsunamayo/Starship-EVO#1965]
### Short Description of the issue:

With 1920x1200 resolution selected:
- On the starter block, the Load BP button doesn't work.
- On the F7 Teleport menu, none of the options are clickable.

### Steps to reproduce the issue:

First, ensure you are on 1920x1200 resolution (16:10).

**For the BP menu:**
1. Create a BP or have one already created
2. Place a starter block
3. Open starter block menu
4. Try to load a BP

**For the teleport list:**
1. Hit F7
2. Try to select a station

### Environment
- Starship EVO version: 20w19b
- Graphics Card: nvidia GTX 980

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4574957/output_log.txt)

**Comment by Xerma** [comment]
It's possible that there may be an issue with your blueprint because I'm able to load things in seemingly just fine

**Comment by captain828** [comment]
I've figured out the issue: it's related to the resolution aspect ratio.
If I stay in 1920x1200 (16:10), it can't click on the load BP or the teleport list.
But if I switch to 1920x1080 (16:9) it works fine.

I'll update the description with this new info.

**Comment by Tezlz** [comment]
It's also related to post UI effects, so if you disable that in the graphic settings it should work as normal. Just a temporary fix if you don't want to use 16:9 aspect ratio

**Comment by tsunamayo** [comment]
I tried and was able to load/teleport in 1680x1050 resolution... Could other people help me with this and try this out? Thanks

**Comment by Tezlz** [comment]
When I reported this bug a couple weeks ago in #1777 you managed to fix it when joining a character, but not when attempting to use the blueprint menu/spawn menu/join server menu, it was related to the post ui effects

**Comment by tsunamayo** [comment]
@Tezlz so you confirm #1777 is still broken with UI Post effect in latest build? It was fine in my test, so it means I cant really reproduce that bug... It is gonna be a pain to fix...
Cheers

**Comment by Tezlz** [comment]
@tsunamayo Yes it is still broken for using the blueprint menu/teleport menu/join server menu. If Post UI Effects is disabled in the graphic options then all those menu buttons become clickable, but with it enabled they don't give any response when clicking on them. 
I just tested the bug in 1680x1050 resolution and that resolution doens't have any issues for me, the only problematic resolutions for me is 1920x1200 and 1600x1200

**Comment by captain828** [comment]
**Quick clarification:** when I first had this issue I tried several 16:10 resolutions and had the same issue.
When I checked again now, I am only having issues with 1920x1200 and 1600x1200.

I'll update the issue to clarify.

**Comment by tsunamayo** [comment]
Okay this issue will be finally fixed for 20w25b, I did a workaround but I think it is a Unity bug, so real choice here... 
Thanks
