### ISSUE TITLE
[Question] Hovercraft Height / Hovering in ships

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#1966]
One thing that I've been curious about for awhile, and I may have already asked this, is how hovercraft will work within ships. Such as for transporting them for land battles or for moving cargo in general. Will they hover at the current height or would we be able to adjust how far off the ground they hover?

Currently we could do this, in theory, by controlling how many or how large the repuslors are but being able to directly control it would make the whole situation easier for more players rather than spending some hours playing with how big or how many repulsors their craft needs to hover in "storage mode" at a 1m height vs "standard mode" which would be what we have now.

**Comment by tsunamayo** [comment]
So what I want to do is add a input and output command. I will add some params in the hover computer like the ride height, and with that gate you will be able to change any params (not just the internal state). So with a toggle you could go in parking mode, with reduced speed on your thruster, lower height, and other. Think of it as a sequencer with any value (it would replace the sequencer in a sense, the angle being just a particular parameter of rotators)
Switch -> ouput ->Hover computer.
Needs to decide on ouput vs input for the name lol, it depends on how you look at things...
Cheers
