### ISSUE TITLE
[Bug] Can only paint door, not door frame [20w19a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#1967]
### Short Description of the issue:
The door frame cannot be painted; trying to paint it just paints the door's moving part.

### Steps to reproduce the issue:
Place door, try to paint frame.

### Environment
- Starship EVO version: 20w19a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20200504134621_1](https://user-images.githubusercontent.com/33041786/81001908-0868e580-8e0e-11ea-9f12-02b392d5fdd3.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4576667/output_log.txt)

**Comment by tsunamayo** [comment]
yes primary / secondary are a bit in a limbo atm, since the collisions refactor.

**Comment by tsunamayo** [comment]
This was fixed for 20w20b, so live now. Thanks!
