### ISSUE TITLE
[Suggestion] Cursor in center of screen for aiming

### ISSUE THREAD

**Issue by FlyingDebris** [tsunamayo/Starship-EVO#1968]
From testing, I found that it was somewhat difficult to gauge where my beam shots would land with the center of the screen being empty. As a result, I'd like to propose adding a small cursor or crosshair in the middle of the screen when flying a ship, so players can more accurately aim their weapons, especially when they're turning.

**Comment by tsunamayo** [comment]
Yes this is planned, I want to give you a visual representation of the dead-zone (and reduce it of course) and also give a bit of gimbal, which will help tremendously for aiming. And a lead indicator.

**Comment by tsunamayo** [comment]
This is all added since a while.
