### ISSUE TITLE
[Bug?] Can Only Edit Text Screens when they are linked to something

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Starship-EVO#1970]
### Short Description of the issue:
Not sure if it's intended or not but I've noticed text screens can only be edited when they are linked to something else or linked to from something else.
...

### Steps to reproduce the issue:
- Place a screen and try to edit the text in it
- issue
...

### Environment
- Starship EVO version: 20w19b
- Graphics Card: AMD Integrated Graphics

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4579001/output_log.txt)

**Comment by tsunamayo** [comment]
Fixed for 20w19c. Thanks!
