### ISSUE TITLE
[Bug] Missing hitbox on lower part of simple seat

### ISSUE THREAD

**Issue by Tezlz** [tsunamayo/Starship-EVO#1971]
### Short Description of the issue:

The simple seat appears to be missing it's hitbox on the lower part, and is instead selecting the blocks behind it, making it difficult to destroy/sit in.

### Steps to reproduce the issue:
Place down a seat, attempt to delete it by looking at the lower part of it.

### Environment
- Starship EVO version:  20w19b
- Graphics Card: GTX 1060 6GB

### Additional information:
Video of the problem:
https://streamable.com/w3i6rq

Output log:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4579276/output_log.txt)

**Comment by tsunamayo** [comment]
Fixed for 20w19c. Thanks a lot!
