### ISSUE TITLE
Bug  Build Direction doesn't update with yoke placement?

### ISSUE THREAD

**Issue by EndoSkull** [tsunamayo/Starship-EVO#1974]
### Short Description of the issue:
I was told that placing a yoke in a direction you want to face and hooking it to the ship core would update build direction - this does not appear to work.
...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
@EndoSkull Does the ship fly in the wrong direction when you enter that yoke? Or is it something else?
I think you could send me the blueprint so I can have a look at it.
Thanks!

**Comment by EndoSkull** [comment]
Where/How send it? Thanks

**Comment by tsunamayo** [comment]
When you build on your ship, you press TAB to open the codex.
Then you click on the left button with your ship.
Then give it a name and press export.
It will create a .mps file under
C:\Users\Francois\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints
You can zip it and frag it there!

Now I want to make sure that you are getting a wrong orientation when flying? It was not clear in your case. Thanks

**Comment by EndoSkull** [comment]
I didn't get so far as thrusters i was just building - but noticed it was facing the wrong way
[B-25.zip](https://github.com/tsunamayo/Starship-EVO/files/4585316/B-25.zip)

**Comment by tsunamayo** [comment]
Okay I saw what was wrong: you linked the computer to the yoke. And then also linked the computer to the thruster (which is not useful).
You actually need to link the yoke to the computer.
Yoke => computer.
Now this is 100% my fault: 
1) first I should prevent that in code
2) I should give you nice help message when you do so
3) I should make tutorials on how to build a working ship.
I am working on all 3! Thanks

**Comment by tsunamayo** [comment]
Okay I made the first 2, proper tuto will follow soon. Thanks
