### ISSUE TITLE
[Bug] Hinges do not move on ground structures

### ISSUE THREAD

**Issue by PopkaAkula** [tsunamayo/Starship-EVO#1975]
### Short Description of the issue:

I recently tried to place a hinge on a ground structure and use a sequencer to set it to a certain angle it wouldn't move at all, I then made a separate structure not attached to the ground and set the hinge to the same angle and it worked fine. After doing that I saved my ground structure and spawned it in not attached to the ground and the hinge on it spawned in at the correct angle.

### Environment
- Starship EVO version: 20w19b

**Comment by tsunamayo** [comment]
Indeed that was not working. Fixed for 20w19c. Cheers!
