### ISSUE TITLE
Is This Intended?

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Starship-EVO#1977]
https://streamable.com/ly0mlh
![specialrelativity](https://user-images.githubusercontent.com/53021785/81140770-da77c400-8f27-11ea-8096-abbbc87e7d92.gif)

I have found out recently that I can put gravity in one of my ships and make it influence another ship. Basically Gravity Docking. The only issue is that the ship that acts upon the other ship is slowly pushed downwards with it. Not as bad as the previous gravity bug #1918 but also not favourable. 

### Short Description of the issue:
Is this how you want gravity gens to be used right now?
...

### Steps to reproduce the issue:
- Place gravity on one ship with another ship within its area
- update other ship by sitting down or entering yoke
- Feature 
...

### Environment
- Starship EVO version: 20w19b
- Graphics Card: AMD Integrated Graphics

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4584925/output_log.txt)

**Comment by Aiwii** [comment]
Yea this is really close to being gravity docking to be fair, the only issue is that the docked ship causes the mothership to fall 
![sinkingwhale](https://user-images.githubusercontent.com/53021785/81141841-0ba5c380-8f2b-11ea-9e08-d9d16011e10d.gif)

And also I can't fly the mothership
https://streamable.com/y36j1m

**Comment by tsunamayo** [comment]
Not really but yes having a gravity field could be a non-mandatory step to your particular docking process. Nice ship ;)
I lack the magnet tech so your mother ship can move around with the other ship fixed.
That way it will also stop pushing the other ship downward.
I will book a dev ask for magnet and docking. I am doing some trigger so it could all fit together neatly!
Cheers

**Comment by tsunamayo** [comment]
Hi @Aiwii if you could send me both of your ship, I will use them to code the docking / magnet lock feature. I think with the trigger we are not too far from that now!
And I will likely show the ship on youtube if you are okay with that! Cheers
