### ISSUE TITLE
Menu and Camera bug

### ISSUE THREAD

**Issue by freddyric0** [tsunamayo/Starship-EVO#1979]
### The camera appears stuck in the characters chest, no tooltips appear and no menus including the escape menu can be accessed

...

### Steps to reproduce the issue: Save with F1, exit to menu and reload the save.

...

### Environment
- Starship EVO version: Not sure how to check.. Latest as  of 06/05/20
- Graphics Card: 1080 Ti
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4587190/output_log.txt)

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Okay thanks for booking the case. Do you remember what character race and hair did you used? Thanks
