### ISSUE TITLE
[Bug] Character got renamed to "Create a new character" and is just black when joining

### ISSUE THREAD

**Issue by Tezlz** [tsunamayo/Starship-EVO#1981]
### Short Description of the issue:

The character that I play on randomly decided to change it's name to "Create a new character" and when I try to join it I don't get a loading screen and can only see this:
![bild](https://user-images.githubusercontent.com/36267770/81205607-78b46a00-8fba-11ea-9074-0862358b6adc.png)
I can still open the codex with 'tab' but I can't look around, place anything, see anything or move at all. I wasn't paying much attention when joining the character at first so I don't know if the name got changed before I tried joining it the first time or if it got changed after I'd already restarted the game due to everything being black. I tried creating a new character to see if that still worked and I was able to create and join it without any problems. I also checked the characters folder in the save data and my character is still called "Tezlz" there. 

### Steps to reproduce the issue:
I don't know, it just happened when I tried to join the character

### Environment
- Starship EVO version: 20w19b
- Graphics Card: GTX 1060 6GB

### Additional information:
Screenshot of how my character looks in the menu:
![bild](https://user-images.githubusercontent.com/36267770/81206303-71419080-8fbb-11ea-8161-d0a91829f8d9.png)

The character that got renamed and am unable to join:
[Tezlz.zip](https://github.com/tsunamayo/Starship-EVO/files/4588225/Tezlz.zip)

Output Log: (I think the error is on row 205)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4588234/output_log.txt)

**Comment by tsunamayo** [comment]
Okay so your save was corrupted. I can deal with it by loading you in the same world but at the same position, but obviously it is not perfect. Do you remember something special the last time you played? Was there an issue?

**Comment by tsunamayo** [comment]
Okay for 20w19c you will be able to load your save, except for the character position and inventory.

**Comment by Tezlz** [comment]
I can't remember doing anything special last time I played, it seemed to have just happened randomly
