### ISSUE TITLE
[Bug] Giant Switch [20w19b]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#1982]
### Short Description of the issue:
I was trying to place a switch, and it ended up being enormous. The actual switch can only be deleted on one tiny part of it, so it looks like the switch's appearance and actual dimensions in-game are different.

### Steps to reproduce the issue:
I have absolutely no idea. I'll see if I can get it to happen again, but this came out of nowhere. The switch is still there on save/reload, and appears when I load a ship from the blueprint, so hopefully you can inspect it yourself.

### Environment
- Starship EVO version: 20w19b
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20200506130331_1](https://user-images.githubusercontent.com/33041786/81212227-311de600-8f9a-11ea-968c-92670f555ee9.jpg)

[Giant Switch Bug Blueprint.zip](https://github.com/tsunamayo/Starship-EVO/files/4588625/Giant.Switch.Bug.Blueprint.zip)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4588603/output_log.txt)

**Comment by tsunamayo** [comment]
My god what is this thing... Thanks for the bp

**Comment by FlyingDebris** [comment]
should make a giant switch tbh

**Comment by alxnns1** [comment]
@tsunamayo 

I've figured out how to replicate this.

- Go to place a hull basic block (or another block you can drag)
- Drag the block to make it longer
- Without releasing the mouse button, scroll to another item in your hotbar
- Release the mouse button to place the block

In the example below I managed to place a wide yoke

**Images:**
![20200507164838_1](https://user-images.githubusercontent.com/485571/81316130-183d2f80-9083-11ea-926e-63e68145f38c.jpg)
![20200507164849_1](https://user-images.githubusercontent.com/485571/81316136-1a06f300-9083-11ea-8896-1d93a34b2ef4.jpg)
![20200507164855_1](https://user-images.githubusercontent.com/485571/81316146-1c694d00-9083-11ea-9627-87217c92a3aa.jpg)

**Comment by tsunamayo** [comment]
@alxnns1 okay fantatisque find, I was able to fix the bug thanks to this. Will be fixed for 20w19c. Thanks!
