### ISSUE TITLE
[BUG] Human Female character with Medium hair rendering issue

### ISSUE THREAD

**Issue by alxnns1** [tsunamayo/Starship-EVO#1983]
### Short Description of the issue:

Human Female character with Medium hair has semi-transparent hair

### Steps to reproduce the issue:

Set race to Human Female and set hair to Medium

### Environment
- Starship EVO version: pre-alpha 20w19b
- Graphics Card: GTX 1050Ti

### Additional information:

![20200506220635_1](https://user-images.githubusercontent.com/485571/81228367-e32ecf80-8fe5-11ea-91e2-75fd04abf033.jpg)
![20200506220100_1](https://user-images.githubusercontent.com/485571/81228296-c85c5b00-8fe5-11ea-92a9-83c61f9deab1.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4589465/output_log.txt)

**Comment by tsunamayo** [comment]
Thanks for reporting that one! Issue fixed for 20w19c. Cheers
