### ISSUE TITLE
[Bug] Inconsistent child entity spawning with starter block?

### ISSUE THREAD

**Issue by ultrak2k** [tsunamayo/Starship-EVO#1984]
### Short Description of the issue:
When spawning in my hovertank with starter block, it randomly didn't spawn its turret

### Steps to reproduce the issue:
Spawn in a craft with child entities, specifically turret in this case, not sure if others work

...

### Environment
- Starship EVO version: 20w19b
- Graphics Card: GTX 840M

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![20200507182308_1](https://user-images.githubusercontent.com/43084360/81262507-162e9d00-9092-11ea-90c2-1ce56f9f4dec.jpg)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4591145/output_log.txt)

**Comment by tsunamayo** [comment]
That dreaded issue is finally fixed, patched in 20w20c. Thanks
