### ISSUE TITLE
[Bug] Negative power usage and heat generation?

### ISSUE THREAD

**Issue by ultrak2k** [tsunamayo/Starship-EVO#1985]
### Short Description of the issue:
Honestly, I just was testing my hovertank, and then suddenly... not sure when, everything just went negative after I stopped flying it (and added a starter block)
Another thing I did is link hover bulbs to the actual hover computer
...

### Steps to reproduce the issue:
This didn't consistently happen, but
-Link hover bulbs to hover computer
-Do stuff with hovercraft
-Stop doing stuff
-Add starter block to your craft

...

### Environment
- Starship EVO version: 20w19b
- Graphics Card: nvidia 840M

### Additional information:
![20200507181738_1](https://user-images.githubusercontent.com/43084360/81264291-4166bb80-9095-11ea-88ef-5b6a2c17f044.jpg)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4591243/output_log.txt)

**Comment by tsunamayo** [comment]
In newer build cant connect repulsor to computer so you should be safe. Thanks
