### ISSUE TITLE
[Bug] The hover bulb of the anti grav hover block sometimes dissapears

### ISSUE THREAD

**Issue by ultrak2k** [tsunamayo/Starship-EVO#1986]
### Short Description of the issue:
When using my hovertank, the bulb part of the anti grav hover block would dissapear - but not all of them, just one
...

### Steps to reproduce the issue:
Place hover block
Use hovercraft
...

### Environment
- Starship EVO version: 20w19b
- Graphics Card: nvidia 840M

### Additional information:
![20200507180938_1](https://user-images.githubusercontent.com/43084360/81264445-82f76680-9095-11ea-83b0-3a7b9f714d62.jpg)
![20200507180819_1](https://user-images.githubusercontent.com/43084360/81264452-87238400-9095-11ea-8bf2-3cac66e401f0.jpg)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4591258/output_log.txt)

**Comment by tsunamayo** [comment]
Issue is fixed for 20w20b (so currently live). Thanks!
