### ISSUE TITLE
[Bug]Teleportation doesn't seem to work, and using it traps you in a certain area

### ISSUE THREAD

**Issue by ultrak2k** [tsunamayo/Starship-EVO#1987]
### Short Description of the issue:
I attempted to teleport to a build in space from the torus, but I was teleported to some point nearby
Trying to leave the vicinity around this point will cause you to rubber band back into this strange zone
...

### Steps to reproduce the issue:
Teleport to anything
Notice how you aren't at the thing
Try fly away
...

### Environment
- Starship EVO version: 20w19b
- Graphics Card: nvidia 840M

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4591353/output_log.txt)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by ultrak2k** [comment]
Saving and reloading does not free you

**Comment by ultrak2k** [comment]
Making new worlds doesn't help

**Comment by tsunamayo** [comment]
You mean that if now, you create a new character you are still facing the issue?

**Comment by ultrak2k** [comment]
> You mean that if now, you create a new character you are still facing the issue?

Yes

**Comment by tsunamayo** [comment]
This is very weird, could you please backup the full save folder :
C:\Users\Francois\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data
Send it to me, then delete it, and start a new world?
Thanks

**Comment by ultrak2k** [comment]
> This is very weird, could you please backup the full save folder :
> C:\Users\Francois\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data
> Send it to me, then delete it, and start a new world?
> Thanks

problem is, it has stopped
I believe that maybe exiting and reloading has fixed it
