### ISSUE TITLE
[Bug] Can't delete worlds

### ISSUE THREAD

**Issue by ultrak2k** [tsunamayo/Starship-EVO#1988]
### Short Description of the issue:
You can't delete worlds

### Steps to reproduce the issue:
Try delete a world
Won't work.

### Environment
- Starship EVO version: 20w19b
- Graphics Card: nvidia 840M
Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4591455/output_log.txt)

**Comment by tsunamayo** [comment]
Bug was already fixed, will be in 20w19c. Thanks!
