### ISSUE TITLE
[Suggestion] Expand blueprint system with prefabs

### ISSUE THREAD

**Issue by captain828** [tsunamayo/Starship-EVO#1989]
While saving a ship to a blueprint is a great first step, it would be great if we could also save prefabs.

By prefabs, I mean a collection of blocks.
Example: a generic cockpit or system that you could use across multiple ships.

**What would be required:**
1. a new tool, the Prefab Tool, so we can designate an area to generate a prefab
- probably the best way would be to first click to set the prefab start point, move to define it and then click again to confirm the area
- dragging could also work but I think the above would be better in this case
2. a way to save & load prefabs
- once we are done with defining the prefab and confirm it, we should be asked to give it a name
- for loading, we could have a new sub-menu as part of the codex and use it like all the other stuff
- we would also need a way to remove saved prefabs, maybe an X in the top right of the prefab

An added benefit, if this system were to be implemented, is that copy-paste would be trivial to do.
With the tool in hand and the area selected, hitting Ctrl+C should act as a shortcut to immediately set the copied area to be pasted with the tool - no need to name anything or save it.

**Comment by tsunamayo** [comment]
Yes, only issue is that people would spam a massive number of detail and make the game lag... I want to do further optimization on  several area first: rendering, collision, children entity collisions. Thanks

**Comment by Garrett-C** [comment]
Even the ability to copy a child entity so you can copy your turrets. As long as the old infinite copy buy stays away...

**Comment by tsunamayo** [comment]
yes for turret I need something. But I cant do it, back in the day I saw people basically replicating the prefab functionality just with child entity - which gave me an heart attack (super bad for perf)
I have to be super careful at how a feature will be used beyond its normal use in order to not shoot me in the foot...

**Comment by tsunamayo** [comment]
Also people would spawn a very big amount of turret, which makes for more lag...

**Comment by Garrett-C** [comment]
Yeah. The infinite copy bug was a weird time. Would be really nice to have something though. I mean people will find a way to abuse it but it feels like something that would add a lot to the tools provided.

**Comment by captain828** [comment]
Well even know people can build huge ships with a ton of detail - it just takes a longer time than if we had something like prefabs.

One easy way to handle it would be to just place various limits:
- you can't have more than X engines
- you are limited to X total number of blocks
- you can't have more than X turrets
- you can only have a max of X child entities
- ship size limits
etc.

**Comment by Garrett-C** [comment]
> Well even now people can build huge ships with a ton of detail - it just takes a longer time than if we had something like prefabs.
> 
> One easy way to handle it would be to just place various limits:
> 
> * you can't have more than X engines
> * you are limited to X total number of blocks
> * you can't have more than X turrets
> * you can only have a max of X child entities
> * ship size limits
>   etc.

Not sure I understand your suggestion here but if it is what I think then I couldn’t disagree more. Hard limits like those would be bad. 

The way I see it there is a minority of people who will abuse the mechanic. The majority will use it in the way it’s intended. You will want to minimise the ways it can be abused but the only way to manage that is to give it to people. You can’t stop the abuse if you don’t know how it will happen. 

Not a lot you can do about people putting lots of turrets on ships though. Other than maybe make it so rotars use energy or generate heat or something to sort of make it impractical to use too many. That said people like using rotors for lots of things so it may not be ideal

**Comment by tsunamayo** [comment]
Yes the problem of hard limit is that it depends on so much things. Also it has the perverse way of letting the player think it is okay to get for example X children entity. Problem being that if one ship has a med/large number of children entity it is fine, but if all the ship get to the limit then its not. Also depends a lot on the config ect...

**Comment by Garrett-C** [comment]
That’s also a point, hard limits can very easily become goals. If you can only have x entities then some people will make sure they always have x entities. It’s kind of an opposite effect.

**Comment by captain828** [comment]
Yeah, I don't like hard limits either but I would rather have some sensible limits in place so that tsuna can add copy-paste & prefabs than not to have that.

If he sets the limits using something like a benchmark tool or profiler to get the max then I think a lot of them could be very high (think 1M blocks, 10 turrets, 500 child entities etc.).
As for the complexity, an average based on how many ships can be allowed to spawn/render could work.

He could also increase them as the game becomes better optimized.

Multiplayer is definitely a place where limits should exist.
Last thing I would want is to be on a server and then someone pulls a 1:1 scale Eclipse SSD or EVE Avatar or other huge ship.
Crap like this already happens many times in SE where the sync speed goes to shit because someone imported a Death Star.

**Comment by Garrett-C** [comment]
Honestly, I would love to have some copy and paste/prefab tech however I would rather not have them and not have arbitrary limits. I would rather have the freedom to spend lots of time building an ISD than be able to copy a room 10 times in a ship with no freedom. 

I don’t mind MP having limits, I would like them to be player adjustable in some way but something like a size limit is fine. Limits to entity count of number of x block/system is a no go if you ask me.

**Comment by captain828** [comment]
For singleplayer, yes, I agree, there shouldn't be any limits at all.
If you want to build that Eclipse SSD, go for it... it will prob lag like crazy but hey it's your choice.

Even for MP, like tsuna alluded to, these should be set by the server config.
Defaults should be sensible but if you wanted to make a server with no restrictions then you should be able to.

**Comment by Garrett-C** [comment]
100% agree. Single player should be up to you. Even if it was say limits until a certain point of progression in order to keep the gameplay balanced or something. 

Multiplayer should have size limits but they should be config based. So maybe one server has no limits but another could limit it to smaller ships etc. There are lots of cool ways to customise a server with config based size limits. That said they should be size limits not limits on how many blocks you use.

**Comment by ultrak2k** [comment]
I personally agree with all those hard limits on child entities - so people don't get any funny game breaking ideas. 
Well maybe mostly in survival, and mostly in multiplayer, but yeah.

**Comment by Garrett-C** [comment]
> I personally agree with all those hard limits on child entities - so people don't get any funny game breaking ideas.
> Well maybe mostly in survival, and mostly in multiplayer, but yeah.
> Block totals might not be the best imo, unless its a very high number @tsunamayo

Only issue is if people get the idea that a limit is a goal. If there is no limit then some people will put a lot of turrets on ships, but some will put less. If you have limits you will have people who decide they need the maximum amount. That’s fine on one ship but not on multiple. So the limits would need to be so low that it doesn’t make a difference which would ultimately be quite disappointing for people who want lots of cool gadgets, I mean say goodbye to logic racks and really fancy landing gear. I can see the appeal but there are also a lot of negatives to a limit on child entities.

**Comment by Battlepixel** [comment]
> Not a lot you can do about people putting lots of turrets on ships though. Other than maybe make it so rotars use energy or generate heat or something to sort of make it impractical to use too many. That said people like using rotors for lots of things so it may not be ideal

Great idea! This is a good way to avoid the "limits-become-goals" prob with child entities. A **config-scale-factor** that raises or lowers the heat output or energyuse compared to a normal value could solve the problems with turrets and childentitys mentioned in my opinion. To balance this, the heat output / energy use of each rotator / hinge / rail would have to depend on the mass that it carries, so that a small hatch does not have the same effect as an entire turret.

**Comment by Garrett-C** [comment]
> > Not a lot you can do about people putting lots of turrets on ships though. Other than maybe make it so rotars use energy or generate heat or something to sort of make it impractical to use too many. That said people like using rotors for lots of things so it may not be ideal
> 
> Great idea! This is a good way to avoid the "limits-become-goals" prob with child entities. A **config-scale-factor** that raises or lowers the heat output or energyuse compared to a normal value could solve the problems with turrets and childentitys mentioned in my opinion. To balance this, the heat output / energy use of each rotator / hinge / rail would also have to depend on the mass that it carries, so that a small hatch does not have the same effect as an entire turret.

Good point. Having it mass based would certainly help balance things a bit. It would also add a trade off to adding armour to your turrets. I feel like you would want to make it so that the turret hinge operates at a heat negative. So if say 1 hull proides 5 cooling the effect of 1 hull on the rotor is say 7 heat for example. Basically you want a cost to having a turret. Shouldn't be a crippling cost but one that makes you have to think about how many you use and what size.

**Comment by Battlepixel** [comment]
> One question though is would the heat cost be an all the time cost or only when the system is moving. I feel like only when moving would work well. That way there is also a tactical reason to turn some turets on/off and it would add an extra element to combat.

if it has no negative effect on the performance, it should protect. But Tsuna will know ;). 
For me it is more important that your idea solves the whole problem, everything else is additional (features)^^

**Comment by captain828** [comment]
I think using heat as a way to limit the use of the children entity spam is not a bad idea but, especially for large ships, heat is a non-issue with how it currently works.

**Comment by Battlepixel** [comment]
yes but thats only a question of balancing and the "config-scale-factor" ;)

**Comment by Calvert4096** [comment]
Even if some kind of energy consumption or heat formula dis-incentivizes performance-killing builds, I think it makes sense to give admins for multiplayer the option to put hard limits on entity counts.

**Comment by tsunamayo** [comment]
We now have prefab since a while...
