### ISSUE TITLE
Canopy hitbox issue

### ISSUE THREAD

**Issue by schlid** [tsunamayo/Starship-EVO#1991]
### Short Description of the issue:
The canopy block does not slide through a half brick wide gap anymore (This was previously possible until the most recent update.)
...

### Steps to reproduce the issue:
Put a canopy on a rail
Create a half brick wide gap aligned with the canopy
Activate the rail to attempt to move the canopy through the gap.

...

### Environment
- Starship EVO version: 20w19b
- Graphics Card: RTX 2060

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![image](https://user-images.githubusercontent.com/31857052/81351784-024c6080-90bd-11ea-8d74-aa8f08a6fbe9.png)

**Comment by tsunamayo** [comment]
Not sure to see what you want to do, if you could send me a blueprint! Thanks

**Comment by schlid** [comment]
[kingfisher with system12.zip](https://github.com/tsunamayo/Starship-EVO/files/4596430/kingfisher.with.system12.zip)

**Comment by tsunamayo** [comment]
Issue fixed for 20w19d. Now due to how the collision system work your canopy will actually penetrate too much... It is less of an blocking for the player. 
Amazing build btw!
Cheers
