### ISSUE TITLE
[Bug] Ship gravity is very bouncy & can't jump [20w19c]

### ISSUE THREAD

**Issue by captain828** [tsunamayo/Starship-EVO#1993]
### Short Description of the issue:

With the new build, the ship inside gravity (from grav gen) is very bouncy and when in walk mode I can even walk over thin tiles or jump.
**FYI: Wasn't happening on 20w19b.**

### Steps to reproduce the issue:

Not 100% sure:
1. outside the grav field of the torus, place a ship that has a grav gen  (see attachment below for example)
2. try walking inside the radius of the grav gen 

### Environment
- Starship EVO version: 20w19c
- Graphics Card: nvidia GTX 980

### Additional information:

[Itaki Light Freighter v2.zip](https://github.com/tsunamayo/Starship-EVO/files/4596586/Itaki.Light.Freighter.v2.zip)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4596587/output_log.txt)

**Comment by captain828** [comment]
I also can no longer see the preview of the gravity generator.

Tested it on a flat plane now and the issue is still happening just not as bad,
There could be something to do with the gravity unit positioning as well.

**Comment by tsunamayo** [comment]
Okay let me check, yes I have been making change to gravity.

**Comment by tsunamayo** [comment]
Yes indeed there was an issue, fixed for 20w19d. I am releasing the patch now, as it is a bit blocking.
