### ISSUE TITLE
[Bug]Its hard to comprehend, but it's certainly a hover bug.

### ISSUE THREAD

**Issue by ultrak2k** [tsunamayo/Starship-EVO#1995]
### Short Description of the issue:
Two theories: what I think is wrong here, I can't quite comprehend what is wrong because sometimes even if the door is closed, it does this. Maybe its the fact that there is... "stuff" that is under the hover bulbs? (some sections are lower then them, not that they are covered"
That, or it's the fact that perhaps opening doors causes this - since the opened door clips through the ground, and it was making sparks.

I have a video showing what is happening below, but
Basically, the hovercraft can't move because its banging itself on the ground - but it has 500% thrust to weight ratio, which I assume is 5 thrust force per 1 weight force, so it should be plenty right?

...

### Steps to reproduce the issue:
Either build a hovercraft but the hover bulbs aren't the lowest point of the craft, or build a hovercraft with a door block, and have the opened door clip through the ground
...

### Environment
- Starship EVO version: 20w19c (issue was in last version too)
- Graphics Card: nvidia 840M

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
https://youtu.be/efausxvQZtw
(is the bulbs freaking out related?)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4596866/output_log.txt)

**Comment by ultrak2k** [comment]
actually is this just a really low ride height problem?

**Comment by tsunamayo** [comment]
Could you send me your blueprint so I can investigate? Thanks

**Comment by ultrak2k** [comment]
[Misaka Mikoto HMBT.zip](https://github.com/tsunamayo/Starship-EVO/files/4596933/Misaka.Mikoto.HMBT.zip)

**Comment by ultrak2k** [comment]
> Could you send me your blueprint so I can investigate? Thanks

Something that should be noted is that even if this bug isn't happening the hovercraft can barely move properly anyway
https://youtu.be/EWqkR9qNK_Y

**Comment by Aiwii** [comment]
[CARs (2).zip](https://github.com/tsunamayo/Starship-EVO/files/4600774/CARs.2.zip)
another bp just cause

**Comment by Sullos** [comment]
I too recently experimented with Hover vehicles and noticed the bouncy properties they have. I believe that the collision bounce is the main problem. I wanted to make a small city scene with a hover car or a few going down the streets of the city, but the hover vehicles are just so bouncy, the moment you steer a little bit too far in one direction over a block surface especially, if metal touches metal, all sorts of bounciness happens, and then next thing you know you're flying through space! Well nearly. But the bounce amount seems to be the main problem at the moment.

**Comment by tsunamayo** [comment]
Okay so there is a mix of issues at play here:
1) there was not enough repulsor, you need twice more => my bad, the thrust to power display was right but is not the right thing to show to the player. I will display a rating like for the rest.
2) there were not build in the right direction. They have to be build like wheel. I am not sure is it not logical to new player? Do I need to explain that better? I will add something like build it like a wheel.
3) I updated the math a bit, it is a lot smoother now.
4) You need also a much higher ride height, I will give a ride height setting (among other things)

I keep you posted once all of that is implemented, but I got your baby running smooth!

**Comment by tsunamayo** [comment]
Okay it should be much better in new update.
