### ISSUE TITLE
[Bug] Holding gravity block turns everything purple [20w19d]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#1996]
### Short Description of the issue:
If a gravity generator is placed on a ship, then when the gravity block is also held in the player's hand, everything looks purple.

### Steps to reproduce the issue:
Place gravity block on ship & have gravity block selected in player hand.

### Environment
- Starship EVO version: 20w19d
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
Before:
![20200508012640_1](https://user-images.githubusercontent.com/33041786/81377627-8a396700-90cb-11ea-920c-068891eb61ed.jpg)

After:
![20200508012636_1](https://user-images.githubusercontent.com/33041786/81377647-9291a200-90cb-11ea-8020-2c514fb9a13f.jpg)

Gravity block placed but not selected:
![20200508012936_1](https://user-images.githubusercontent.com/33041786/81377664-9a514680-90cb-11ea-97ac-74cea853c1b5.jpg)

Gravity block placed & selected:
![20200508012934_1](https://user-images.githubusercontent.com/33041786/81377683-a2a98180-90cb-11ea-8487-ba9d0025995d.jpg)

Unselected:
![20200508013325_1](https://user-images.githubusercontent.com/33041786/81377871-f3b97580-90cb-11ea-85ae-232631217195.jpg)

Selected:
![20200508013327_1](https://user-images.githubusercontent.com/33041786/81377878-f61bcf80-90cb-11ea-8c80-95ebbfdefcb9.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4597342/output_log.txt)

**Comment by tsunamayo** [comment]
Thanks, issue fixed for 20w19e. Cheers
