### ISSUE TITLE
Question on calculation method used for logic gates

### ISSUE THREAD

**Issue by jimmybub** [tsunamayo/Starship-EVO#1998]
### Short Description of the issue:

Simply, what type of calculation do you use?  There are implications for performance and accuracy for anything you chose but that isn't really why I'd like you to explain it.  Considering the game shall soon be in my grasp this month, and that I hope to focus mainly on the creation of logic systems, It would save me and hopefully others some time to know more about how it works on the back end.

Those that I am aware of were explained to me years ago for a different game, but was essentially a choice between propagating logic signals traveling from a HIGH output to the next IC in the chain, or one where the whole circuit needs to be calculated first / every time it is changed, which is obviously more accurate but takes far more resources and limits the size and scope of logic systems compared to the less accurate method.

There are plenty of hybrid solutions that I'm not aware of I'm sure, but those are just the ones I know.

### Steps to reproduce the issue:
1: Be me.
2: Have question.

### Additional information:
https://www.sciencedirect.com/topics/computer-science/logic-simulation
For reference.

**Comment by tsunamayo** [comment]
Let me read that paper first, thats interesting.
I only propagate the signal when it changed, except in some case (enter command - but it is not really logic). In theory it should behave same as continuously updating all elements, but in practice it get messy - if you manage to find a case where it is not working this way please ping me.
Cheers
