### ISSUE TITLE
Hovercrafts: Small vehicles end up 'stuck' on ground

### ISSUE THREAD

**Issue by ItsCrusade** [tsunamayo/Starship-EVO#1999]
Smaller-sized hover vehicles tend to get 'stuck' on the ground due to the repulsors pushing them into the floor.

...

1: Spawn attached entity on habitation ring
2: attempt to pilot the entity for an extended period of time, be sure to try and pass over water/uneven terrain.

...

### Environment
- Starship EVO version: 20w19d
- Graphics Card: GTX1070ti

### Additional information:
Blueprint:
[speeder.zip](https://github.com/tsunamayo/Starship-EVO/files/4599801/speeder.zip)

Screenshot:
https://i.imgur.com/Hw3AZIw.png

Log:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4599799/output_log.txt)

**Comment by tsunamayo** [comment]
Issue fixed! Your mini speeder is now a lot of fun. There was two issue to fix actually, other was #2020.
Now it is not very stable, it wants to topple off. I will add a few settings soon, you will be able to try to improve it that way. Issue fix is in 20w20b. Thanks!
