### ISSUE TITLE
[Bug] Can't paint cushion part of Ottoman

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Starship-EVO#2001]
### Short Description of the issue:
Can only pain the edges of the ottoman and not the centre
![image](https://user-images.githubusercontent.com/53021785/81458114-109a8b00-9156-11ea-8eef-28afd4e38e95.png)

...

### Steps to reproduce the issue:
- Paint ottoman
- Issue
...

### Environment
- Starship EVO version: 20w19d
- Graphics Card: IGPU

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4602252/output_log.txt)

**Comment by tsunamayo** [comment]
Issue fixed for 20w20b, it was quite an odyssey ;)
