### ISSUE TITLE
[Suggestion] Paint Tools

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#2002]
Painting especially for larger ships is quite difficult and annoying. Here are two tools that could make this a little easier. Both of these apply to blocks and not bricks

1. Paintbrush sizes: Quite simple, options to use the current 1x1 brush, 3x3, 5x5, etc.

2. Fill bucket: This would change the color of an entire stretched block

After EA of course*

**Comment by alxnns1** [comment]
or maybe even a way to fill an entire ship with a specified colour

**Comment by nokturnihs** [comment]
I too find painting my cruise ship hard - especially the windows which require you to hit the corner to paint the frame... any chance we could get left click (primary paint/fill), right click (alternative paint - frames, etc) or q/e to switch between paint modes, something like that?

**Comment by nokturnihs** [comment]
If you used q/e to shift between modes you could use paint/fill, paint (small area), paint (alternative area), paint (all areas, small) and "paint stripper" modes...

**Comment by ZachZent** [comment]
Paint stripper you say...

**Comment by nokturnihs** [comment]
Eraser? I use paint stripper modes all day. :)

**Comment by zalexville** [comment]
Be able to color the block before you place it, making it easier to build. Also keeping the brush helps with painting afterwards like currently.

**Comment by BrickMacklin** [comment]
I'd take any of these suggestions. Painting is very tedious

**Comment by tsunamayo** [comment]
No longer applicable to Neovox.
