### ISSUE TITLE
[BUG] Non-dismissable "Docked at Station" window

### ISSUE THREAD

**Issue by alxnns1** [tsunamayo/Starship-EVO#2004]
### Short Description of the issue:

Non-dismissable "Docked at Station" window when blueprinting docked ships.

### Steps to reproduce the issue:

- Dock a ship at a landing pad
- Export the blueprint
- Load the blueprint from a starter block
- Enter the ship activate the yoke

The window to undock the ship will appear but pressing the buttons will do nothing and it cannot be dismissed.

### Environment
- Starship EVO version: 20w19d
- Graphics Card: GTX 1050 Ti

### Additional information:

[Blueprint](https://github.com/tsunamayo/Starship-EVO/files/4602406/CRS.Light.Cruiser.zip) (yoke is inside, at the front)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4602412/output_log.txt)

**Comment by tsunamayo** [comment]
Issue fixed for 20w20b. Thanks!
