### ISSUE TITLE
[Bug] Falling through landing pad when game is alt-tabbed [20w19d]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#2007]
### Short Description of the issue:
When standing on the large landing pad while a ship is docked in Walk mode, if the player alt-tabs, their character will fall through the pad.

### Steps to reproduce the issue:
Dock ship on large pad, stand on pad in Walk mode, then alt-tab.

### Environment
- Starship EVO version: 20w19d
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4605243/output_log.txt)

**Comment by tsunamayo** [comment]
Issue fixed for 20w20b. Thanks!
