### ISSUE TITLE
[BUG] Endless falling on new world

### ISSUE THREAD

**Issue by alxnns1** [tsunamayo/Starship-EVO#2012]
### Short Description of the issue:

Endlessly falling through the habitat and space on a new world.
Unable to control the character.
Continue to endlessly fall when I teleport.

### Steps to reproduce the issue:

Create a new world/character

### Environment

- Starship EVO version: 20w20a
- Graphics Card: GTX 1050 Ti

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4608706/output_log.txt)

**Comment by tsunamayo** [comment]
You did not had any issue previously? Thanks

**Comment by alxnns1** [comment]
no, and I just created a new character again and it works fine, seems to have been a one-off

**Comment by tsunamayo** [comment]
okay, did you remember if you alt-tabbed while loading? It might be related to #2007.
Thanks

**Comment by alxnns1** [comment]
Tried creating a new character with alt-tabbing while loading but it still isn't happening again. Still seems to be a on-off
