### ISSUE TITLE
[BUG] Spawned in blueprints don't obey gravity

### ISSUE THREAD

**Issue by alxnns1** [tsunamayo/Starship-EVO#2013]
### Short Description of the issue:

Entities spawned in with the starter block on the habitat seem to not fall in it's gravity

### Steps to reproduce the issue:

- Create a blueprint
- Load in that blueprint on the habitat
- Watch it not fall

### Environment

- Starship EVO version: 20w20a
- Graphics Card: GTX 1050 Ti

### Additional information:

Blueprints used to test this:
[Blueprints.zip](https://github.com/tsunamayo/Starship-EVO/files/4608851/Blueprints.zip)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4608847/output_log.txt)

**Comment by tsunamayo** [comment]
Issue fixed for 20w20b. Thanks!
