### ISSUE TITLE
[BUG] Wrong text displayed

### ISSUE THREAD

**Issue by TheCuriousSkeleton** [tsunamayo/Starship-EVO#2014]
### Description of the issue:
Wrong text displayed

### Environment
- Starship EVO version: 20w20a
- Graphics Card: GTX 2070 Super

### Additional information:
![20200511114736_1](https://user-images.githubusercontent.com/39653820/81553683-70bf4600-937d-11ea-88b0-516ea6ad5667.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4609097/output_log.txt)

**Comment by tsunamayo** [comment]
Okay I fixed this bug, this was the same as the HUD - fix is available now. Thanks!
