### ISSUE TITLE
[Bug] immobile "lightsabers" generated by small laser unit

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#2015]
[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/4609208/output_log.zip)
small laser unit creates "lightsaber blades" when fired via logic (not always)

### Steps to reproduce the issue:

- Load the attached blueprint

- Press the pink button on the pink 8-barrel forward laser array
- Watch as the bright and noisy artifacts appear

### Environment
- Starship EVO version: 20w20a
- Graphics Card: Nvidia GeForce GTX 1060 6GB

[Xeno_Larger Ship Prototype_bugged.zip](https://github.com/tsunamayo/Starship-EVO/files/4609164/Xeno_Larger.Ship.Prototype_bugged.zip)

![20200511064309_1](https://user-images.githubusercontent.com/51390907/81555179-15c62880-9356-11ea-9582-a6d0c0884d47.jpg)
![20200511060557_1](https://user-images.githubusercontent.com/51390907/81555199-28d8f880-9356-11ea-9129-a253493611bb.jpg)
![20200511064120_1](https://user-images.githubusercontent.com/51390907/81555216-2f677000-9356-11ea-841c-36628e2b05d8.jpg)

**Comment by tsunamayo** [comment]
@Majikmonster okay could you please give me a little bit of background on the logic system, ie what it is doing? Thanks

**Comment by tsunamayo** [comment]
Okay issue fixed for 20w20e, but I am still very much curious on what that thing was.
Thanks
