### ISSUE TITLE
[Bug] Query gate dysfunctional and inconsistent

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#2016]
Query gates cannot fire weapons even if the criteria is met, and even if the logic linked to them and the weapon activates.
Query gates do not always send a signal when their criteria is met.
All query gates adopt the Superior/Inferior setting of the last accessed gate (not the value) when accessed after that gate.

### Steps to reproduce the issue:

Link a rail/rotor/hinge to the gate and set the query values
Link the gate to a bare weapon, a button, and another logic gate.
Link the other logic gates to separate weapons
Trigger the rail/rotor/hinge to try and get the weapon to fire (may result in #2015 )

### Environment
- Starship EVO version: 20w20a
- Graphics Card: Nvidia GeForce GTX 1060 6GB

[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/4609202/output_log.zip)

**Comment by tsunamayo** [comment]
Issue fixed for 20w20c. Thanks!
