### ISSUE TITLE
Laser Sensor beam passes through blocks, disappears when sensor body out of view

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#2017]
[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/4609268/output_log.zip)

The laser beam goes through all blocks/bricks.
The beam disappears when the sensor body is not in the view window, or is obstructed by another block/bricks, even though the beam would not be obstructed.

### Steps to reproduce the issue:

Disappearing beam:
-Place laser sensor on block, and cover one side of it with another block, without obstructing the laser path
-Fly to the other side of that block until you can't see the sensor body

Piercing beam:
-Place laser sensor on block, and cover opposite side of it with another block, directly obstructing the laser path
-Look from the side to see beam sticking through

### Environment
- Starship EVO version: 20w20a
- Graphics Card: Nvidia GeForce GTX 1060 6GB

![20200511024003_1](https://user-images.githubusercontent.com/51390907/81557498-152f9100-935a-11ea-8247-0c3af5e66eb9.jpg)

**Comment by tsunamayo** [comment]
Yes both issue are known, the second one will be harder to fix and will have to wait for the big rendering update. It is the same issue with trap / blast door not rendering. Thanks

**Comment by tsunamayo** [comment]
@Majikmonster Hi, issue is fixed for 22w45a. Thanks!
