### ISSUE TITLE
[Bug] [20w19d] can delete blocks/bricks with decal selected on tool

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#2018]
[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/4609311/output_log.zip)

Rapidly pressing right mouse button/remove more times than there are decals to delete allows you to delete the blocks/bricks behind them.

### Environment
- Starship EVO version: 20w19d
- Graphics Card: Nvidia GeForce GTX 1060 6GB

**Comment by tsunamayo** [comment]
I cant reproduce this, what it is your exact test case? Can you reproduce this all the time? Thanks

**Comment by Majikmonster** [comment]
I think all the cases have been in multiplayer, but had occurred regularly enough for me to become cautious when deleting decals. I'd suggest stacking quite a few decals on top of each other and trying from there. That's really the only consistent variable.
