### ISSUE TITLE
[Bug] [20w19d+] Auto-landing impossible, pads bounce ship away

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#2020]
[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/4609386/output_log.zip)

Ships touching the landing pad clip slightly through it, and most times bounce off.
The autopilot that lands the ship on the pad doesn't recognize this and keeps attempting to land, sending the ship into a loud frenzy of crashing, twirling, and bouncing off the pad repeatedly.

### Steps to reproduce the issue:
-Attempt to touch down on a landing pad.
-Request landing on a landing pad, and approach so that autopilot engages and tries to land.

### Environment
- Starship EVO version: 20w19d
- Graphics Card: Nvidia GeForce GTX 1060 6GB 

These screenshots were taken in quick succession, and without a pilot controlling the ship on all but the first image.
![20200511002035_1](https://user-images.githubusercontent.com/51390907/81559360-4067af80-935d-11ea-84b2-0fbef067cb61.jpg)
![20200511002103_1](https://user-images.githubusercontent.com/51390907/81559361-41004600-935d-11ea-90fc-9a0939dd09d5.jpg)
![20200511002106_1](https://user-images.githubusercontent.com/51390907/81559362-41004600-935d-11ea-9aca-835616707888.jpg)
![20200511002110_1](https://user-images.githubusercontent.com/51390907/81559364-41004600-935d-11ea-9cd0-932ff3a06f04.jpg)

**Comment by tsunamayo** [comment]
This is a very tricky subject and very ship dependent. I would need to investigate your ship to see how the lower section looks collision wise. Thanks!

**Comment by tsunamayo** [comment]
Thanks for the gatling like fire volley of case btw ;)

**Comment by Majikmonster** [comment]
[Majikmonster_ship_police_patrol_hot fuzz.zip](https://github.com/tsunamayo/Starship-EVO/files/4610048/Majikmonster_ship_police_patrol_hot.fuzz.zip)

Xenoprophet and I had fun making complex and compound weapons, which is probably why we revealed so many bugs. It won't be the last time I attempt a volley weapon like that 😈

**Comment by tsunamayo** [comment]
@Majikmonster amazing build! Did the canopy opening was fine or was it blocked too early (I did change to the hinge so I am not sure if the opening is "normal").

**Comment by tsunamayo** [comment]
So I did increased the collision grid resolution for smaller build, now your ship can land fine with landing gear deployed. Will be in 20w20b.
Thanks!
