### ISSUE TITLE
Child entities with lights don't impart light on surfaces

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#2021]
[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/4609402/output_log.zip)

A child entity will not emit light onto other entities' surfaces (either other ships/torus/landing pad or their own mothership) or itself.

### Steps to reproduce the issue:

-build platform on shaded side of torus/space
-place hinge/rotor/rail on that platform
-place a light on the child entity

### Environment
- Starship EVO version: 20w19d
- Graphics Card: Nvidia GeForce GTX 1060 6GB 

The yellow crane light does not brighten or tint any surface, even its own.
![20200508083540_1](https://user-images.githubusercontent.com/51390907/81559829-25496f80-935e-11ea-96f6-8913e9a55865.jpg)

**Comment by tsunamayo** [comment]
Issue fixed for 20w20b. Thanks!
