### ISSUE TITLE
collision/selection mesh for some blocks/bricks doesn't conform to visual shape

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#2022]
[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/4609446/output_log.zip)

-Some blocks, like the quarter-sphere, have a full cubic selection shape, blocking what looks like an open gap between it and blocks behind it.
-Some bricks, like the beveled brick, have collision mesh of a full block
### Environment
- Starship EVO version: 20w19c-20a
- Graphics Card: Nvidia GeForce GTX 1060 6GB

**Comment by tsunamayo** [comment]
Yes, is it a big deal in your opinion? I could work on improving the raycast, but they wont have full shape, at least for a while.
Thanks

**Comment by Majikmonster** [comment]
It's been a problem reaching around them to edit things behind without tearing sections away. It also greatly effects how decals are applied to the surface, since the face(s) the decal is applied to is different in shape and distance from the face(s) it appears on.

**Comment by tsunamayo** [comment]
Yeah too bad, now I am considering removing them... =(
