### ISSUE TITLE
Tutorial zone feedback

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#2023]
![image](https://user-images.githubusercontent.com/27857711/81569298-00bdb980-9397-11ea-8bf5-b8551c4dc269.png)
"Congratulations" rather than "Congratulation"

![image](https://user-images.githubusercontent.com/27857711/81572375-0c12e400-939b-11ea-91ea-ca7e3b46d431.png)
Here you can use a button linked to the switch so that you don't have to flip the switch twice to get them to toggle

![image](https://user-images.githubusercontent.com/27857711/81569394-1cc15b00-9397-11ea-82f7-39fdd7481c23.png)
Can't walk up these stairs in "None" mode

![image](https://user-images.githubusercontent.com/27857711/81570121-12539100-9398-11ea-9c86-798a3514de9a.png)

Here, I think the dark blue area should be the first thing that the player interacts with as it tells them how to stretch and rotate bricks, afterwards they can go to the green area and play with the whole codex. They should be directed here first with the laser trigger at the entrance.  I also think that the laser trigger popup should tell the player to stand inside the coloured boundaries for tips on how to proceed, as that might not be obvious. Right now if they follow the arrows on the floor, the blue area is ignored.

![image](https://user-images.githubusercontent.com/27857711/81570588-b4737900-9398-11ea-991d-94480cfa16fa.png)
"Generates" rather than "Generate"
"Consumes" rather than "Consume
Maybe mention that the widget appears on the right of the HUD, rather than just "to the right" as that might make the player think they should look to the right of the sign.

![image](https://user-images.githubusercontent.com/27857711/81570774-f69cba80-9398-11ea-93ac-8183154d4ba0.png)
Here I think it's important to differentiate between heat generated by all the ships systems, as well as heat damage coming from incoming fire. 
At this stage I ran out of slots on my first hotbar. Because I've played before I know that I can scroll them using shift+scroll, but a new player won't know that

![image](https://user-images.githubusercontent.com/27857711/81570897-19c76a00-9399-11ea-995c-04b1b6361f4b.png)
"Produce" rather than "procude"

![image](https://user-images.githubusercontent.com/27857711/81570973-3794cf00-9399-11ea-9e50-d932cc12717b.png)
Might be better to say "place it anywhere on the ship" when talking about the ship core"

![image](https://user-images.githubusercontent.com/27857711/81571470-e76a3c80-9399-11ea-853a-2f65d97889c9.png)
Here, some extra information about how to link a sequencer to a mechanisms would help I think, just mentioning to link Switch -> Sequencer -> Rotor for example

![image](https://user-images.githubusercontent.com/27857711/81571678-2dbf9b80-939a-11ea-9868-28d8fd43ab90.png)
"Orthogonal" isn't a very common word, maybe replace it with "for the horizontal and vertical axis"

![image](https://user-images.githubusercontent.com/27857711/81571931-7c6d3580-939a-11ea-863b-a62643d4081a.png)
Throughout the turret tutorial there is no mention of the Hotkey brick. I think a reminder that you need one to fire a gun would be useful here too.

![image](https://user-images.githubusercontent.com/27857711/81572061-a3c40280-939a-11ea-91da-3ca501d40b49.png)
Very last thing, I think it would be nicer to have Sen's hovercraft on a platform with a ramp down to the ground rather than just having it lying on the ground like this with a drop.

Overall, great tutorial! Just a couple of things to pick up on, but soon it will be fantastique!

**Comment by YnotnA** [comment]
I find that the tutorial area is too "rough". Perhaps there should be a slightly stricter zone. Offer only one path that brings the elements as you go

**Comment by ZachZent** [comment]
There needs to be a 45 degree fence rather than placing down all those fence corners

**Comment by tsunamayo** [comment]
Thanks a lot @ProPeach, I will do all the change!

**Comment by tsunamayo** [comment]
Okay changes done for 20w21c. Thanks!
