### ISSUE TITLE
[Suggestion] Better mouse aim controls

### ISSUE THREAD

**Issue by PopkaAkula** [tsunamayo/Starship-EVO#2024]
### Short Description of the Suggestion:

I find the current way of controlling craft in Starship EVO right now very cumbersome, especially if you have fixed guns on your craft because the current controls make it very difficult to aim.

[Stevo example](https://imgur.com/a/5Vd3Oia)

I think that there should be a choice for people who don't like these controls and that the best option would be the sort of controls that War Thunder has.

[War Thunder example](https://imgur.com/a/op7vQ6e)

This kind of control method is very easy for users and makes it very easy to aim your craft at things.

The main difference is that currently the crafts are controlled via a virtual joystick where the movements of your mouse are like the axes of a joystick. The new method is a completely different way of control. Rather than the cursor being a virtual joystick it exists in a sort of 3D sphere around the craft and when the cursor is moved, the craft tries to align itself with the cursor as well as it can.

Some possible pros i can think of for this method of control is that:

1. There won't have to be any dead-zone for it because fine control and level flight would rely off of the cursor being in place or not.

2. It makes the game a lot more accessible to people because the mouse controls will be very intuitive and easy to use.

3. It would make aiming your craft at anything incredibly easy and precise.

I have spoken to some community members about this and they also feel that this would be a better way to control a craft with a mouse.

**Comment by ProPeach** [comment]
Wathunder is a great example of a flight system. Although it recreates the flight of an aircraft, it is tight, simple and easy to use with a large margin for mastering it. It's a free game on Steam if you'd like to experience it yourself Tsuna.
The improvements that Popka outlines, especially the function of the ship following the mouse rather than the more linear virtual joystick we have now would be excellent. I understand that Tsuna is cooking up something himself already, exciting to see what that turns out to be!

**Comment by Majikmonster** [comment]
The dead zone is definitely an issue. It makes it difficult to tell when your steering will engage, and steering corrections from any fault of the previous maneuver takes flinging the mouse to the other end of the dead zone and risks making the same mistake. A more exact translation like Popka's suggestion is optimal not only for precise flight, but also for pilot comfort and easing the learning curve for each ship.

**Comment by tsunamayo** [comment]
so I wanted to add a bunch of things to improve that. I will do this first, then we will see how it goes.
How does it works for large ship? For small ship that turn really fast in make sense, but maybe not for larger boi...

**Comment by ProPeach** [comment]
To use Warthunder as an example again, it has large, heavy bombers that turn very slowly and those work great using the same system. I think the thing that makes the most difference is that the further you move your cursor from the forward position, the faster your ship tries to follow it (limited by the ships base turn rate of course).

Whether the same aeroplane like flight model we have now works for large space ships with turrets is a different issue though which might require a different flight mode all together.
