### ISSUE TITLE
[BUG] Window Tile stretch range

### ISSUE THREAD

**Issue by alxnns1** [tsunamayo/Starship-EVO#2025]
### Short Description of the issue:

Window Tiles can be stretched up to 4.25m instead of the usual 4m for bricks

### Environment

- Starship EVO version: 20w20a
- Graphics Card: GTX 1050 Ti

### Additional information:

![20200511155301_1](https://user-images.githubusercontent.com/485571/81576158-d02e4d80-939f-11ea-85d0-d594b2e879ee.jpg)

**Comment by tsunamayo** [comment]
Fixed for 20w20b. I also updated the canopy and the barriers. Thanks!
