### ISSUE TITLE
Codex Spelling/Grammar

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#2026]
Since Early Access is just around the corner (wooo!), I thought I'd put together a list of text errors in the codex that I could find to help polish things up for when Early Access goes live.

**Movement Panel**

> Choose a locomotion device.

- This sounds a bit odd; maybe change it to "Choose a mode of locomotion", or "Choose a locomotion mode", or "Choose a locomotion method". "Choose movement" would probably be the simplest way of putting it.

> Anti-gravitation: The suit compensate for the gravitational force, but keep you aligned with the gravity field.

- "compensate" should be changed to "compensates"; "keep" should be changed to "keeps".

> Full 6 dof: Compensate for gravitational force. You can control your alignment manually.

- "Compensate" should be changed to "Compensates". You might want to change this to match the Anti-gravitation tooltip:
"The suit compensates for gravitational force. You can control your alignment manually."
- Also, you might want to clarify what the abbreviation "6 dof" stands for.

**Tools Panel**

> Link Tool: Use the link tool to link systems, button and command between them.

- "button" should be changed to "buttons", and "command" should be changed to "commands".
- Also, as a firm defender of the Oxford comma ( ;) ), this should be "systems, buttons, and commands between them" to indicate that buttons and commands are separate things.

> Symmetry Tool: Use the Symmetry tool to setup symmetry plane on entities.

- I noticed that the names of some of the tools are capitalized in their descriptions, while others aren't; for example, "link tool" is not capitalized, but "Symmetry tool" is. Either is fine, but they should all use the same style. Since the tools themselves have both words capitalized when selected in the codex ("Symmetry Tool") you might want to use that method across the board, with both words capitalized.
- "setup" should be "set up;" it's being used as a verb here, for which the correct form is "set up." When written as a single word, "setup" is a noun, and means the same thing as "configuration."
- "symmetry plane" should be "symmetry planes".

> Anti-Grav Tool: Use this tool to move Entities around.

- "Entities" is capitalized here, but it's not capitalized in the description of the symmetry tool. Again, either way of writing it is fine, but the usage should be the same for all.

**Systems**
- For the large/small systems, you might want the small versions to be either "[System], Small" or "Small [System]".

> Reactor: Generate power.
- "Generate" should be "Generates". This is because it is the block that is performing the action. "Generate" would be used if it was the player performing the action. Both versions.

> Capacitor: Increase the capacity of reactors and shields.
- "Increase" should be "Increases". Same as above. Both versions.

> Shield: Generate a force field shielding the ship.
- "Generate" should be "Generates", same reasons as above.

> Thruster: This thruster provide Lightcruise ability.
- "provide" should be "provides".
- Also, I know that the tooltip (love the stats in the tooltips, BTW!) shows that it also provides thrust, but you might want the description to say something about that too.

> Thruster Small: Placed sideways the small thruster provide angular and lateral thrust.
- "provide" should be "provides". You should probably insert a comma after "sideways".

> Repulsor: Allows hovercrafts to levitate.
- "hovercrafts" should be "hovercraft".

> Gravity Unit: Generate a gravity field over a cubic area.
- "Generate" should be "Generates".

> Jump Pad: Generate a gravity field over a column area. Can be configured as elevator or jump pad.
- "Generate" should be "Generates".
- "Column area" is an unusual phrase, but I'm not entirely sure what to change it to. Might want to make this "Generates a vertical gravity field."
- The second sentence should read "Can be configured as **an** elevator or jump pad."

> Beam Weapon: Fire a beam ray.
- "Fire should be "Fires".
- Also, "beam" and "ray" are basically synonyms with the same meaning; just one of them would be OK.

> Laser Weapon: Fire Laser projectiles.
- "Fire" should be "Fires". Both versions.
- "Laser" does not need to be capitalized here. Both versions.
- Since real-life lasers are beams, players might be confused if the "laser weapon" doesn't fire beams; you might want to change "laser" to "energy," or something else. This is really minor though; since most lasers in sci-fi aren't beams either, most players probably won't have any trouble figuring it out. ;p

> Range Barrel: Increase projectile velocity and lower spread.
- "Increase" should be "Increases". Both versions.
- "lower" should be "lowers". Both versions.

> Cooling Barrel: Decrease the heat generated during the weapon cooling
- Sentence is missing a period at the end. Large version.
- "Decrease" should be "Decreases". Both versions.
- Either "weapon" should be "weapon's", or "the" should be deleted. Both versions.

> Recoil Barrel: Decrease the weapon recoil and spread.
- "Decrease" should be "Decreases". Both versions.
- Either "weapon" should be "weapon's", or "the" should be deleted. Both versions.

> Gatling Barrel: Fire by volley by 4.
- "Fire" should be "Fires". Both versions.
- First "by" should be "a". Both versions.
- Second "by" should be "of". Both versions.

> Charge Addon: Increase the charge capacity to fire longer with the beam, or fire volley with the laser.
- "Increase" should be "Increases". Both versions.
- "volley" should be "volleys". Both versions.

> Overheat Addon: Increase heat damage.
- "Increase" should be "Increases". Both versions.
- Does a weapon's heat damage still also affect how much damage it does to shields? If so, the description should also reflect that.

> Damage Addon: Increase hull damage.
- "Increase" should be "Increases". Both versions.

> Supercharge Addon: Increase hull damage.
- "Increase" should be "Increases". Both versions.

**Hull Blocks**

> Hull Basic: Dissipate heat and provide Hull Points.
- "Dissipate" should be "Dissipates".
- Do you want heat to be capitalized like Hull Points is? Or should Hull Points be lowercase like heat is?

**Mechanisms**

> Sliding Rail: Slide in a direction
- "Slide" should be "Slides". Both versions.

> Sliding Rail Addon: Extend the sliding rail range of motion. Can be connected to another addon.
- "Extend" should be "Extends". Both versions.
- "rail" should be "rail's". Both versions.

> Rotator: Rotate around the block vertical axis.
- "Rotate" should be "Rotates". Both versions.
- "around the block vertical axis" is slightly unclear. Maybe us the same style as you used with the hinge? "Rotates around the vertical axis" would work fine. Both versions.

> Hinge: Rotate around the lateral axis.
- "Rotate" should be "Rotates". Both versions.

**Logic Elements**

> Hovercraft Computer: Link a yoke to the Hovercraft Computer to control an entity like an hovercraft.
- "an" should be "a".

> Logic Gate: Mix several input according to a preset rule.
- "input" should be "inputs"
- "according to a preset rule" is unclear. You should probably ask someone who knows more about logic than I do, but at a guess this sentence should read "Mix several inputs to vary the output" or something like that.

> Sequencer Gate: The sequencer can control a rotator or slider to ping-pong between two values.
- This only mentions rotators and sliders, but not hinges.
- I love the expression "to ping-pong," but maybe this should be "to alternate"

> Query Gate: Link this gate to a mechanism to trigger signal at a specific time.
- "signal" should be "a signal".

> Warning Message Gate: Use this gate to display a message to the player who activate it.
- "activate" should be "activates".

> Button: The button that will send an ON signal value while pressed.
- "that" can be deleted.
- Button Wedged needs the same change.

> Switch: The switch button will alternate between ON and OFF state when pressed.
- "switch button" is confusing; "button" can be deleted.
- "state" should be "states".
- Switch Wedged needs the same changes.

> Slider: Allows to manually control mechanism.
- Should probably be "Allows manual control of mechanisms."
- Slider Wedged needs the same change.

> Speedometer: Display the vehicle speed.
"vehicle" should be "vehicle's".

> Laser Sensor: Trigger action when player or other entity crosses it.
- "Trigger" should be "Triggers".
- "action" should probably be "an action".
- "player" should be "a player".
- Volumetric Sensor needs the same changes

**Interior**

> Cushion Tile: Small sizable brick.
- "sizable" actually means "fairly large." Should be "resizable."

> Trap Door: Blast door.
- "Blast door" should probably be "Trap door", although you might want to change the description of both doors to describe how they move, since one slides and the other swings.

> Ladder: Use the ladder to move upstair.
- "upstair" should probably be "vertically."

> Handle: Decorative element.
- Since this is not merely decorative but functions the same as the ladder, this should probably read:
"Handle: Use the handle to move vertically."

**Construction**

> Armature: Armature block that stretch upward.
- "Armature" might not be the right word; Googling it gives me pictures of electrical motors. After some research, "[Lattice Girder](https://en.wikipedia.org/wiki/Lattice_girder)" looks like the correct term.
- "stretch" should be "stretches".
- "upward" should probably be "lengthwise".

> Rail: Rail.
- This is probably another type of Lattice Girder. 
- Calling it a rail might confuse some players, since they might expect it to do the same thing that rails in games like Minecraft do.

> Rounded Block: Rounded block that stretch laterally.
- "stretch" should be "stretches".

> Rounded Corner: Quarter Sphere.
- "Sphere" should probably be "sphere".

> Cube Small: Small sizable brick.
- As with the Cushion, "sizable" should be "resizable."
- Also applies to: Wedge Small, Tetra Small, Hepta Small, Corner Small, Bevel, Thin Tile, Panel Rounded, Panel Beveled, and Hollow Wedge.

> Tile: Medium stud-based brick.
- Studs aren't mentioned elsewhere, so this should probably be changed.
- Calling the 1/8m brick medium when the 1/4m brick is called small could be confusing. This can probably use the same description as the Thin Tile; the difference in their names and Codex icons should be enough to show players the difference.

> 2-to-1 Offset: Allows to offset the building grid.
- This should probably be "Allows building offset from the grid."
- Also applies to: 1-to-2 Offset, 4-to-1 Offset, and 1-to-4 Offset.

**Windows and Canopies**

> Canopy: Main Canopy brick.
- "Canopy" should be "canopy".
- This is also true for Canopy Wedge.

> Transparent Pipe: Small Transparent pipe.
- "Transparent" should be "transparent".

**Pipes**

> Pipe Creased Small: Small Construction brick.
"Construction" should be "construction".
- Also applies to: Arm, Pipe Small, Pipe Angle Small, Round Tile, Round Tile Thin, Cone, Round Tile Creased.

**Comment by tsunamayo** [comment]
Massive thanks for that sizable and exhaustive list, you must have take a lot of time to do it.
I cant manage to put that damn 's... Also I learned quite a few things!
Thanks a lot that was much needed...
Fixed for 20w20b. Cheers
