### ISSUE TITLE
[Bug] Some graphics options not staying disabled [20w20a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#2027]
### Short Description of the issue:
Ambient Occlusion and Chromatic Aberration do not stay off if turned off in Graphics options.

### Steps to reproduce the issue:
Turn these settings off, quit the game, and start it again. They will have turned themselves back on.

### Environment
- Starship EVO version: 20w20a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4611712/output_log.txt)

**Comment by tsunamayo** [comment]
Fixed for 20w20b. Thanks!
