### ISSUE TITLE
[Bug] Brick collision error on hinges

### ISSUE THREAD

**Issue by Lsutehall** [tsunamayo/Starship-EVO#2029]
### Short Description of the issue:

There is an error with the collision detection on hinges when placing bricks straight onto them; this prevents the hinge from moving to its full extent. 

### Steps to reproduce the issue:

Place a square of bricks onto the flat face of a large hinge, try to move the hinge.

### Environment
- Starship EVO version: 20w20a
- Graphics Card: GTX1060

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![20200511211127_1](https://user-images.githubusercontent.com/40872394/81607415-8d369f00-93cc-11ea-9448-0c5b35e54d3b.jpg)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4611851/output_log.txt)

**Comment by tsunamayo** [comment]
Yes indeed... I keep you posted.

**Comment by tsunamayo** [comment]
Issue fixed for 20w20b. Thanks!
