### ISSUE TITLE
Cannot Load Blueprints Using Starter Block

### ISSUE THREAD

**Issue by BrickMacklin** [tsunamayo/Starship-EVO#2030]
When I place down a Starter Block to load a blueprint I cannot select any of the available blueprints. This goes for backed up blueprints and newly created ones. My cursor hovers over the ships but nothing is clickable. I have tried clicking but nothing happens. I have attempted new saves, verifying file integrity and reinstalling the game. 

...

Place down starter block and try loading a blueprint. 

...

### Environment
- Starship EVO version: 20w20a
- Graphics Card: RTX 2080 Ti

### Additional information:

![image](https://user-images.githubusercontent.com/37836252/81608156-ce668900-93a3-11ea-948e-65c03adbbf9e.png)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4611883/output_log.txt)

**Comment by tsunamayo** [comment]
This is a resolution issue - I am still working on it sorry.
In the meantime to get the game working properly you will have to desactivate UI Post Effect in the Graphics settings. Thanks!

**Comment by tsunamayo** [comment]
So this issue will be fixed by a workaround in 20w25b. Thanks!
