### ISSUE TITLE
[BUG] Landing Pad kicks you out of ship

### ISSUE THREAD

**Issue by alxnns1** [tsunamayo/Starship-EVO#2031]
### Short Description of the issue:

Landing a ship on a landing pad and pressing the `X` will kick the player out of the ship entirely instead of kicking the player out of the yoke or the chair.
This is especially annoying on large ships with interiors you have to navigate to get back to the yoke.

### Steps to reproduce the issue:

- Dock large ship at landing pad
- Press the `X` on the window that comes up

### Environment

- Starship EVO version: 20w20a
- Graphics Card: GTX 1050 Ti

### Additional information:

Large ship I'm using:
[W.D. Destroyer.zip](https://github.com/tsunamayo/Starship-EVO/files/4612285/W.D.Destroyer.zip)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4612283/output_log.txt)

**Comment by tsunamayo** [comment]
I think it was a bug with the chair. I cant really reproduce, but I did a refactoring regarding the chair in 20w20e. I will ask you to test then to see if you reproduce again! I keep you posted when update is live.
Thanks

**Comment by tsunamayo** [comment]
@alxnns1 could you please tell me if you reproduce this in 20w21a? Thanks a lot!

**Comment by alxnns1** [comment]
seems to work fine now, the character steps out of the seat instead of appearing outside the ship

**Comment by tsunamayo** [comment]
Great to hear that!
