### ISSUE TITLE
[Dev Asks] Steam Page question

### ISSUE THREAD

**Issue by tsunamayo** [tsunamayo/Starship-EVO#2033]
Does anyone of you remember if the game WAS or WAS NOT labelled as Early Access or when the page went live (like if you have a clear remember of each one)?
I just noticed it wasnt, option must have been unchecked for some reason at one point. I just dont know if it was from inception or just lately.
Thanks

**Comment by MRonlin** [comment]
![image](https://user-images.githubusercontent.com/64201628/81677196-a0875000-9448-11ea-80b4-b979783dd45f.png)
This was taken on April the 21st. It didn't have the early access label.

**Comment by tsunamayo** [comment]
Okay damn, I think thats pretty clear. 
I missed that, and somehow nobody picked-up on that too. I dont think it should an issue.
Thanks
