### ISSUE TITLE
[Question]A question of release - how ready do you think we are?

### ISSUE THREAD

**Issue by ultrak2k** [tsunamayo/Starship-EVO#2034]
Hey, so recently, as bugs keep being reported and release date gets closer, ever since the actual release date was announced, people were asking if the game is ready for release. A month or two ago, I asked what you wanted the state of the game to be - and although I think that state has been reached, the question now is that if you think it’s close to being ready seeing as there’s still a lot of bugs to grind through (though I don’t think the ability to fix them is doubted). 

People have also raised concerns about “what if it dies on release, since quite a few games have released with little content but cool concept like building”, so I’m wondering what your response is to that

Lastly, but most importantly, why did you choose the state you chose, aka - why now, and not later? Is there a reason to do with financials as some people brought up or do you think it was right time?

Sorry if this sounds too pessimistic, I was just trying to capture some concerns from the discord - Ultra

**Comment by Garrett-C** [comment]
I mean I would say that there will pretty much always be bugs, Tsuna has been keeping on top of them recently and the game is really more stable than it has been for a while. 

Additionally games like scrap mechanic released with just a cool building system and it has survived and is now getting survival several years down the line. I don’t see it as a major issue. Would love to see tsuna’s response to this though.

**Comment by ultrak2k** [comment]
> I mean I would say that there will pretty much always be bugs, Tsuna has been keeping on top of them recently and the game is really more stable than it has been for a while.
> 
> Additionally games like scrap mechanic released with just a cool building system and it has survived and is now getting survival several years down the line. I don’t see it as a major issue. Would love to see tsuna’s response to this though.

I don't personally see it as too big of an issue either, but I'm still curious - and people have been insistent on the discord that we aren't ready

annoyingly so
