### ISSUE TITLE
[Suggestions] Grass and sand blocks

### ISSUE THREAD

**Issue by MRonlin** [tsunamayo/Starship-EVO#2036]
Grass and sand blocks? 

It would be cool if we could have habitats on our ships, like O'Neill cylinders.
![image](https://user-images.githubusercontent.com/64201628/81680523-18567a00-944b-11ea-8d5e-4179b4264e68.png)

**Comment by tsunamayo** [comment]
Yes I am not sure on how I will do that, but once mining is there I will want to add those.
Now you wont be able to do something as big as the o-neil cylinder, but maybe one day I will have the player simply buy one... In the long long term ;)
