### ISSUE TITLE
[Bug] Player holds a yellow box

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#2038]
### Short Description of the issue:
When the player first loads in, they appear to be holding a bright yellow box despite having nothing in their hotbar. The box disappears when you switch hotbar slots

### Steps to reproduce the issue:
Load into the game with nothing in your hotbar, happens to new and old players

### Environment
- Starship EVO version: 20w20b(?) (Game still says 20w20a but shows all the features of 20w20b)
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
I dont reproduce this issue... Does anybody else see this? Thanks

**Comment by tsunamayo** [comment]
@ProPeach is this something you get all the time in latest build? I never had that issue...

**Comment by ProPeach** [comment]
Yes, I've had it happen in multiplayer and single player consistently. Now that it's happened a few times, it seems to occur when you load into a world with an empty toolbar.

Separately, in multiplayer the same yellow cube appears on the multitool of other players when they hold a block or paint. I'm not sure if that's related or not

**Comment by ProPeach** [comment]
I realised I never attached and image, here's what it looks like
![image](https://user-images.githubusercontent.com/27857711/82157898-2443a100-987c-11ea-8a9e-ba780c08cf6e.png)
![image](https://user-images.githubusercontent.com/27857711/82157899-2ad21880-987c-11ea-8390-33a01d73d7ba.png)
Oddly, no one else in the multiplayer game experienced this

**Comment by tsunamayo** [comment]
@ProPeach my best guess it is some artifact on AMD. I made a fix but I cant test it. You will tell me if in 20w20b it is better! Thanks

**Comment by tsunamayo** [comment]
@ProPeach okay tell me if you see this in the latest build 20w20b! Thanks

**Comment by ProPeach** [comment]
This is fixed for single player, I haven't been able to test mp yet but I suspect it's fine too. Nice one!

**Comment by tsunamayo** [comment]
Great!
