### ISSUE TITLE
[Bug] Hover spheres are flat.

### ISSUE THREAD

**Issue by SageThe13th** [tsunamayo/Starship-EVO#2039]
![Flat](https://user-images.githubusercontent.com/58193603/81716853-79785080-943f-11ea-9fc5-d558255c3615.png)

Version: 20w20b

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4616773/output_log.txt)

**Comment by tsunamayo** [comment]
That was a miss from my side, it is fixed now for 20w20b. Thanks
