### ISSUE TITLE
[Bug] Walking and torus gravity

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#2040]
### Short Description of the issue:
When walking on the torus, there seems to be intermittent gravity as the player often resorts back to its default stance. If I stand still in the "None" locomotion mode, the Stranded in Space error message pops up. As an aside, you can't seem to jump very high at all

![image](https://user-images.githubusercontent.com/27857711/81717582-a3973600-9472-11ea-9c7b-a922ab50ce4b.png)

[Starship EVO Walking bug.zip](https://github.com/tsunamayo/Starship-EVO/files/4616813/Starship.EVO.Walking.bug.zip)

### Steps to reproduce the issue:
Walk on the torus in "None" mode

### Environment
- Starship EVO version: 20w20b
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
@ProPeach okay I remember always having trouble to jump also indeed.
I did some tweak to the terrain collision for 20w20c, and now I can jump just fine, all the time.
Could you test in 20w20c and tell me if you still see the issue? 
Thanks

**Comment by tsunamayo** [comment]
@ProPeach I am not sure if you got this issue again or if I can close it. Thanks!

**Comment by ProPeach** [comment]
Looks like this one is fixed, awesome!

**Comment by ProPeach** [comment]
Actually, if you stay still while walking on the torus the warning message pops up still. Walking is smooth now though
![image](https://user-images.githubusercontent.com/27857711/82512818-18b8da00-9b09-11ea-9d66-21069da5d1c4.png)

**Comment by Dwarf-LordPangolin** [comment]
I am actually also getting the walking stance bug, as well as the "Stranded in space" error.

**Comment by tsunamayo** [comment]
This should be fixed in current 20w21c. Thanks!
