### ISSUE TITLE
[Bug] Hovercraft warning message

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#2041]
### Short Description of the issue:
When you try to pilot a hovercraft without an engine, a warning message pops up saying you need to add a small thruster
![image](https://user-images.githubusercontent.com/27857711/81718206-5d8ea200-9473-11ea-8922-1d25d8447d4f.png)
You can actually use a large thruster to, I think the tip should mention this

### Steps to reproduce the issue:
Pilot a hovercraft without a thruster

### Environment
- Starship EVO version: 20w20b
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
Fixed for 20w20c. Thanks!
