### ISSUE TITLE
[Bug] Hovercraft instability

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#2042]
### Short Description of the issue:
Depending on the Thrust to Weight ratio of a hovercraft, it can be very unstable. In the videos attached the same hovercraft has a TtW of 600 vs 2000, the 2000 craft jitters and turns in circles while the 600 craft is more stable (although still turns in circles). Hovercraft in general seem very sensitive to even very small unbalances in their centre of mass, ideally this would be less sensitive.

A while ago you mentioned the ability to change the hovercraft parameters in the Hover core with sliders etc, is this still planned? That might be a quicker and easier method than trying to balance every possible configuration with one set of equations.

### Steps to reproduce the issue:
Spawn in the attached blueprint and control it, then change out the repulsors for 0.5m^3 ones instead of the current 1m^3 ones to see the difference in stability,

### Environment
- Starship EVO version: 20w20b
- Graphics Card: RX 580
[Hovercraft testing.zip](https://github.com/tsunamayo/Starship-EVO/files/4616942/Hovercraft.testing.zip)

**Comment by tsunamayo** [comment]
I have done some more change to the physics and now this seems to be corrected. It is so much better now! Only caveheat is that people will have to be careful on how the repulsor is built, you can no longer build them from the bottom it have to be from the side. I will add a little arrow preview to make that clear.

**Comment by tsunamayo** [comment]
Live in 20w20c. Thanks

**Comment by ProPeach** [comment]
Brilliant! Looking forward to testing them

**Comment by tsunamayo** [comment]
Okay it should now be better by default, and if it is too strong then you can reduce the strength into the computer screen. Thanks!
