### ISSUE TITLE
Weird hovercraft balancing issues.

### ISSUE THREAD

**Issue by ItsCrusade** [tsunamayo/Starship-EVO#2043]
Hovercraft balances on its nose upon spawning

...

1: Spawn attached blueprint on habitation ring
2: Hovercraft will balance on its nose.

Deleting bricks doesn't change this behaviour.
...

### Environment
- Starship EVO version: 20w20a
- Graphics Card: GTX1070ti

![Starship_EVO_2020-05-13_02-32-40](https://user-images.githubusercontent.com/64144395/81721887-ec2b0f80-94c3-11ea-9a6e-8a9bcf7c4c43.png)

[Hovland.zip](https://github.com/tsunamayo/Starship-EVO/files/4617141/Hovland.zip)

**Comment by tsunamayo** [comment]
Issue fixed for 20w20c. Nice idea for the landing gear! Cheers
