### ISSUE TITLE
[Bug] 20w20b shows as version 20w20a [20w20b]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#2044]
### Short Description of the issue:
The version number displayed for 20w20b is "20w20a."

### Environment
- Starship EVO version: 20w20b
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
Note the ottoman paint fix, but the old version number:
![20200512124418_1](https://user-images.githubusercontent.com/33041786/81727545-bef04a00-944e-11ea-88fe-2613ec30a978.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4617520/output_log.txt)

**Comment by tsunamayo** [comment]
That was a miss from my side, it is fixed now for 20w20b. Thanks
