### ISSUE TITLE
[Bug] Fence block resized itself [20w20b]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#2045]
### Short Description of the issue:
The fence block has been resized with the currently released version.

### Steps to reproduce the issue:
Load blueprint from previous version with fence blocks on it, compare current size of block with previous size.

### Environment
- Starship EVO version: [20w20b]
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
The fences here previously stretched across the whole raised area:
![20200512124555_1](https://user-images.githubusercontent.com/33041786/81727801-20181d80-944f-11ea-9437-40e944df50b6.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4617531/output_log.txt)

**Comment by tsunamayo** [comment]
Yes sorry I forgot to mention it, it was since the 20w20a though. I realized that a smaller step was more convenient to build barrier. I hope it wont be too long to adjust!
If you see more block that you think would need a better rescale, please shoot before ea. After it will be more tricky...

**Comment by Dwarf-LordPangolin** [comment]
That's perfect; I was actually just thinking the other day that it would be handy for the fence to scale in smaller increments! And I will pass that on to everyone on the Discord.
