### ISSUE TITLE
[Crash] Game Crash while loading world

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Starship-EVO#2046]
### Short Description of the issue:
Just leaving a crash report, although recently my system has been having issues so it's more likely to do with that than the game
...

### Environment
- Starship EVO version: 20w20a? might be b
- Graphics Card: AMD Radeon(TM) RX Vega 11 Graphics

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4618701/output_log.txt)
[Crash_2020-05-12_220843060.zip](https://github.com/tsunamayo/Starship-EVO/files/4618710/Crash_2020-05-12_220843060.zip)

**Comment by tsunamayo** [comment]
Yes there was something clearly wrong with the GFX card. Is it working fine now? Did you reinstall your GFX drivers? Thanks

**Comment by Aiwii** [comment]
hmm I should do that, Yea after that crash my computer died for a few days so I reset the CMOS updated some drivers (not the GFX one tho) and updated the BIOS

**Comment by tsunamayo** [comment]
I think you managed to play the game after that ;) Cheers
