### ISSUE TITLE
Hovercraft centre of mass/thrust indicator

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#2047]
More of a question than anything, but did you remove the indicator for the centre of mass and thrust in the hovercraft core? They were useful in determining how to correctly balance a hovercraft if it was leaning more to one side, which happens very easily due to how sensitive they are.

If they did come back, a coloured dot with an up arrow for thrust and a differently coloured dot with a down arrow for mass would be a nice icon choice for them to explain to the player what they are.

**Comment by tsunamayo** [comment]
Okay I have added this for 20w20c. Thanks!
