### ISSUE TITLE
[Bug] Strange Happenings

### ISSUE THREAD

**Issue by SageThe13th** [tsunamayo/Starship-EVO#2048]
It's a little hard to even describe what happened. I got in a hovercraft. My screen turned white and I lost control of the character. I exited the world to the title and came back to this.

![What1](https://user-images.githubusercontent.com/58193603/81755133-93d11f00-947d-11ea-9cef-6b8438f42d92.png)

I exited the game via the task manger as I couldn't even bring up the Esc menu. When I came back I was seated in a different vehicle in space. A vehicle was previously on the Torus.

![What2](https://user-images.githubusercontent.com/58193603/81755243-e14d8c00-947d-11ea-96aa-44d04c6bdec7.png)

Also, everything on the Torus was now in space.

![What3](https://user-images.githubusercontent.com/58193603/81755482-836d7400-947e-11ea-8e77-2ea57993327f.png)

![What4](https://user-images.githubusercontent.com/58193603/81755484-85cfce00-947e-11ea-9ab7-be4b5fb56179.png)

Version: 20w20b

I'm including an output log I grabbed after taking the first screenshot:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4618917/output_log.txt)

And one I got after everything was moved to space:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4618948/output_log.txt)

I'll update this if I can get to happen again.

**Comment by tsunamayo** [comment]
This seems bad... I keep you posted...

**Comment by SageThe13th** [comment]
I'm back with the steps to reproduce. I rebuilt the vehicle that caused the problem, but on a on a new character in a new world. As soon as I tried to drive it the something similar happened.

I got these distorted graphics. 
![What5](https://user-images.githubusercontent.com/58193603/81756792-59b64c00-9482-11ea-8cf8-c8283bdac78d.png)

When I left and came back everything was in space again. Below is the vehicle causing this.

![What6](https://user-images.githubusercontent.com/58193603/81756835-7f435580-9482-11ea-81c1-e8778d946b03.png)

Here's the BP:
[Cursed.zip](https://github.com/tsunamayo/Starship-EVO/files/4619032/Cursed.zip)

Here's two more output logs:
[output_log_3.txt](https://github.com/tsunamayo/Starship-EVO/files/4619035/output_log_3.txt)
[output_log_4.txt](https://github.com/tsunamayo/Starship-EVO/files/4619036/output_log_4.txt)

And here's my save files:
[Sage.zip](https://github.com/tsunamayo/Starship-EVO/files/4619041/Sage.zip)
[Neo.zip](https://github.com/tsunamayo/Starship-EVO/files/4619043/Neo.zip)

**Comment by tsunamayo** [comment]
Okay issue fixed for 20w21b. Thanks a lot!
