### ISSUE TITLE
[Bug] Query gates near each other change superior and inferior

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Starship-EVO#2049]
### Short Description of the issue:

Basically when two query gates are near each other, possibly linked in a circuit, if you change one of the query gates to Superior, and then go to the other and change it to inferior, if you go back to the first one, it will now be inferior. If you change that first one back to Superior, the second will change to superior too. 
Externally they will appear as the icon you set them to, as either superior > or inferior <.
This means logic circuits using 2 or more query gates don't actually work.

### Environment
- Starship EVO version: 20w20b
- Graphics Card: 2080 Super OC

**Comment by Majikmonster** [comment]
This is one I've noticed as well. Query gates are really screwy 😞 #2016

**Comment by Sullos** [comment]
That appears to be the same issue yes. One of the only things stopping me from finishing my builds other than being busy :P

**Comment by tsunamayo** [comment]
Issue fixed for 20w20c. Thanks!
