### ISSUE TITLE
[Bug] Hovercraft lose lift at edges of terrain chunks [20w20b]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#2051]
### Short Description of the issue:
Hovercraft lose their lift while over the edges of the chunks on the torus.

### Steps to reproduce the issue:
Take a hovercraft, and switch to 3rd person camera. Fly slowly over the terrain and wait for the hovercraft to lose altitude. Move the camera under the terrain; it will be over the edge between terrain chunks.

### Environment
- Starship EVO version: 20w20b
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
https://gfycat.com/unevenleafycormorant

https://gfycat.com/unimportantbrownacornweevil

![20200512202106_1](https://user-images.githubusercontent.com/33041786/81763150-28467c00-9494-11ea-8364-b5b62a0ab776.jpg)

![20200512205819_1](https://user-images.githubusercontent.com/33041786/81763153-2a103f80-9494-11ea-86d2-17a6663acd8b.jpg)

![20200512205832_1](https://user-images.githubusercontent.com/33041786/81763164-2f6d8a00-9494-11ea-8b0a-361a0805c4d5.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4619423/output_log.txt)

**Comment by SageThe13th** [comment]
I reproduced this myself. I took a slow hovercraft approached on the edges methodically. I could actually watch the hovercraft drift down gradually as I closer. If I pulled back the hovercraft recovered to it normal height. Once I got too close the edge the hovercraft got sucked into the ground and became stuck. Even the anti-grav tool couldn't force it out.

**Comment by tsunamayo** [comment]
Okay great find, issue is fixed for 20w20c. It was gravity that was applied for the neighbor patch also.
As a side trick as you guys are advanced tester you can view the patch when pressing F3 -> Habitat -> View patches.
Thanks!
