### ISSUE TITLE
[Bug] Fullscreen isnt fullscreen with multiple monitors.

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Starship-EVO#2052]
### Short Description of the issue:
I will need people to help me confirm this, but as it stands I run a triple monitor setup, it means I can watch something, play SEVO, and run discord all at once. 
However, it seems somewhat recently the game has had a setting changed which has made it so that even if the game is in fullscreen mode, when I move my mouse to the edge of the game screen, it goes off and on to my other monitors. This in itself actually made a few other bugs, but due to no one else experiencing these other bugs I figure it must be related to the monitor issue.

I have searched far and wide for a few hours today, and all sources seem to point towards it being a development aspect of a game, not having the mouse stay hard locked in a game.

I also decided to look in the settings.ini file and I could not find any actual way to force the game to start in fullscreen. There was no fullscreen option at all. This sort of makes me wonder if there is even any other options other than fullscreen in-game? Typically there are windowed, windowed borderless and fullscreen. With fullscreen locking the mouse into the window.

The other bugs I have seen appear because of this, is when I enter my ship and control it, typically a player just points the mouse to look and aim the ship, then you can press tab and it will let you pan around the ship. Now, due to the mouse not always locking to the game, sometimes I enter the ship and straight away, it goes into a very crazy spin because the mouse is off to the side. And for whatever reason, this carries over to the tab mode too, instead of panning around the ship, the ship itself actually spins. 
To my knowledge, if the problem with the game not being in true fullscreen is fixed, these other bugs will be fixed too.

These bugs appeared I believe about 1-2 weeks ago, I was managing with them being there believing it was a temporary problem, and I already had programs installed that let me manually lock my mouse to a specific monitor (as many other games have this problem too, even my own game I was coding had this and I couldn't fix it easily.). 

### Steps to reproduce the issue:

Open SEVO, move the mouse to the edge of the screen, and keep moving it as it goes onto other monitors as per normal.

### Environment
- Starship EVO version: 20w20b
- Graphics Card: 2080 Super OC

If you need any more information please let me know, this is a killer of a bug for me at least. I don't know if anyone else uses multiple monitors, but I have not heard of anyone else suffering yet.

Thanks Tsuna
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4619642/output_log.txt)

**Comment by Sullos** [comment]
Oh and for further information, I also tried several things on my end including completely uninstalling all display drivers, reinstalling from fresh, rebooting pc countless times, and disabling all programs in the background one at a time manually through task manager. I have steam in game UI disabled too.
Thanks

**Comment by tsunamayo** [comment]
Okay so if I understand the game is in windowed borderless and not true fullscreen? Thanks

**Comment by Sullos** [comment]
Yes, that seems like it. A few weeks ago it was all working fine, perhaps you have changed something to do with how fullscreen is?

**Comment by tsunamayo** [comment]
Okay I have added a dropdown for 20w20c: now you can select Fullscreen / borderless / windowed.
I am also forcing the cursor to be confined to the game windows.
As I have only a single monitor I am not 100% sure it will correct your issue, so tell me if that worked! 
Cheers

**Comment by Sullos** [comment]
Thanks Tsuna, you're the man!

**Comment by tsunamayo** [comment]
Okay build is live, tell me if that fix the issue for you. Thanks

**Comment by Sullos** [comment]
Appears to have worked a charm, thats tsuna!
