### ISSUE TITLE
[Suggestion] Gyroscopes

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Starship-EVO#2053]
### Short Description of the suggestion:
I don't know how well received this will be, as it flies very close to how Space Engineers works.
But it would open up new possibilities.
Currently, as it stands the maneuvering thrusters add the ability to turn a ship. Acting as a gyroscope as it is. I am suggesting that the gyroscope aspect of maneuvering thrusters be separated from the lateral and vertical movement the thrusters allow.

I believe this would both make sense in the aspect of, people don't have to place thrusters to allow for pitch, roll and yaw movement currently, and so me having one big maneuvering thruster at the front of my ship doesn't make sense for why it allows me to move laterally without spinning me around in circles.
So other than the 'logical' aspect of things, I believe having it separated would allow for different sorts of builds too.
Recently I started a project of Lagrangian Point Defence Satellites. Basically, satellites that have the ability to rotate around (point at things) and fire a weapon, but ignore the ability to move really, due to the fact its a satellite. Most satellites (or space stations even) won't need thrusters, but some weapons will still want to be able to point. If I put an AI in my satellite weapon, my only option would be to put a few maneuvering thrusters on it, but not so much that it can move at high speed, only enough to rotate and point its main weapon.

This gyroscope could be handled in several ways if you went ahead with separating that functionality from the maneuvering thrusters. Space Engineers, for example, has a block that you place like thrusters. So long as it's in the ship, and the more you have the better the ability to turn is.
In SEVO, you could either tie the functionality into 1 block (like ship core) with a slider to increase how powerful the turning mechanism is ( this would also allow for the cinematic effect of really big ships turning slowly upon demand) but also taking in to account the size of a ship, and therefore the power requirement.
Otherwise simply having a block, like shields or generators, the more you place, the better the ability to turn is.

I am interested to hear what others think of this, as well as how you feel about this Tsuna. This may not be an Early access level of requirement, but I think it would add to the game greatly.

**Comment by tsunamayo** [comment]
This was suggested and discussed quite a long time ago, as people were afraid of not being able to integrate side thruster to their design neatly. 
Discussion was I made small thruster a bit less in your face than the bigger one, and I think I like how people manage to integrate them. 
I think with the side mechanism you could still make a pivoting station.
Now I might add them later, as an upper technological tier, but it will have to have a meaning and use, to bring something different. But we can brainstorm and see what other think of that.
Thanks

**Comment by captain828** [comment]
A level of extra thinking when you're building could be added with this:
- the large thrusters for a slow curve but with a high top speed, perfect for forward/breaking movement
- the small thrusters for immediate (no curve, just X amount of force) and quick maneuvering (think RCS here)
- gyros for very precise angular maneuvering (pitch and roll) but not a replacement for RCS when a quick roll/pitch is wanted

**For the large thrusters:**
- you could also add different types, like thrusters more gears towards top speed than acceleration
- or thrusters that have a high acceleration but low top speed
- or even much lighter thrusters that don't have FTL capability or have both low top speed and acceleration
- large thrusters would also use significantly more energy compared to the small variants

**For the small thrusters:**
- I would rename these to RCS thrusters to better differentiate them from the large ones or you could see this as a completely new type of block instead
- these would have an immediate and constant impulse force compared to normal thrusters that would have an acceleration curve
- energy-wise, they are far more efficient than the large thrusters

**For the gyros:**
- they would give a variable and linear amount of radial force that would allow a ship to maneuver on its axis very precisely
- would use very little energy when being operated

I don't know how the game currently does the handling of ships but with such a system you could add proper force-based movement around a ship's center of mass, something that would add a further layer of depth.

**Comment by SageThe13th** [comment]
I get you're trying to replicate the feel of certain design Sullos. But, is there any real benefit to a "ship" that can turn, but not accelerate. If you want stationary defenses why is a turret or turrets on an immobile object not enough?

**Comment by Sullos** [comment]
Sorry Sage, I don't quite get what you mean with replicating the feel of a design. If you mean like rebuilding something from other games, that is not the case, as SEVO is all I have played for the last 3 years, and I never much played any other games before that.
The real benefit I am trying to open up here is freedom of design.
Separating the functionality of things into separate components is what allows creativity to thrive.

Think about it from a lego perspective, if the motors from lego Mindstorm also had wheels built into them, as well as the visual light sensors, that would massively limit builds. Every build that you simply wanted a motor with now must have a sensor and wheels.

Of course, if you're not a lego person, then think of it from any other game perspective. Separate components allow for better creativity and possibilities. That's what makes a physics-based sandbox, like Space Engineers, for example, have so many possibilities. Whilst I don't play it anymore, that's what I loved about it.

As to the stationary defense point, if you want an entire structure to turn, tell me how you could achieve that with a turret based design. You don't see space stations in orbit moving the docking port to the spaceship whilst leaving the rest of the station where it was. You use RCS thrusters to rotate things.
This was all just a suggestion that would not only help on a build in terms of logic but to better refine a system that currently does multiple jobs instead of its own logical job.

**Comment by SageThe13th** [comment]
Actually, I'm on board with gyros now. I too want addition control over how a vehicles maneuvers without always increasing it's thrust in the process.
