### ISSUE TITLE
[BUG] Sliding along the floor

### ISSUE THREAD

**Issue by alxnns1** [tsunamayo/Starship-EVO#2055]
### Short Description of the issue:

While standing in a ship without a gravity module landed on the habitat, I am sliding along the floor

### Environment

- Starship EVO version: 20w20b
- Graphics Card: GTX 1050 Ti

### Additional information:

My save where I am currently landed on the habitat sliding on the floor of my ship:
[Alex.zip](https://github.com/tsunamayo/Starship-EVO/files/4621550/Alex.zip)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4621555/output_log.txt)

**Comment by Sullos** [comment]
Is it possible the ship is built at an angle and so due to its lack of gravity the gravity of the torus is just sliding you? Just a suggestion as I've experienced it if I'm not out of range of the torus on a ship

**Comment by alxnns1** [comment]
I've actually landed on the torus, and since there isn't a flat surface on the torus terrain, I slide slowly along the floor

**Comment by alxnns1** [comment]
I should also note that if I step out of my ship and stand on said terrain, I don't slide

**Comment by tsunamayo** [comment]
@alxnns1 okay issue now fixed in 20w23d. Thanks!
