### ISSUE TITLE
[Bug] Canopy Wedge placement hitbox error [20w20b]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#2057]
### Short Description of the issue:
The Canopy Wedge's placement hitbox extends further out from it than its actual dimensions.

### Steps to reproduce the issue:
Place a canopy wedge and view it from the front. Move the crosshair off to the right of the canopy with a block selected. The block's placement ghost will appear floating in midair and can be placed "on" the canopy. The canopy can also be deleted from here. The placement box error also prevents switches/buttons in the affected region from being activated.

### Environment
- Starship EVO version: 20w20b
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20200513140901_1](https://user-images.githubusercontent.com/33041786/81854477-99814000-9523-11ea-9cd5-126357754bc9.jpg)

![20200513140842_1](https://user-images.githubusercontent.com/33041786/81854486-9be39a00-9523-11ea-8eb7-d9fdcf45128c.jpg)

Note that when pointing at the button, the tooltip to press F does not show up, but that the canopy to the left is highlighted:
![20200513140744_1](https://user-images.githubusercontent.com/33041786/81854506-a2721180-9523-11ea-93dc-435f11c527fd.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4624156/output_log.txt)

**Comment by alxnns1** [comment]
the same happens with hinge brick too

**Comment by tsunamayo** [comment]
Yes I had some issue with the raycast I saw that yesterday and fixed it already. Will be in 20w20c, coming soon. Thanks!
