### ISSUE TITLE
[Bug] Hovercraft Warning Message

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Starship-EVO#2064]
### Short Description of the issue:
![image](https://user-images.githubusercontent.com/53021785/81900076-649fd800-9579-11ea-95a2-e340d2609147.png)
wrong symbol?
...

### Steps to reproduce the issue:
flip a hover
...

### Environment
- Starship EVO version: 20w20c
- Graphics Card: integrated graphics

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4626402/output_log.txt)

**Comment by tsunamayo** [comment]
Fixed for 20w20d. Thanks!
