### ISSUE TITLE
[20w20b] Turrets clip selves into ship

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#2065]
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4626501/output_log.txt)

Grandchild entities can and do still clip, most notably with turrets.

### Steps to reproduce the issue:
-Have turret on surface of ship
-Set to aim at ship target or auto
-Enter yoke

### Environment
- Starship EVO version: 20w20b
- Graphics Card: Nvidia GeForce GTX 1060 6GB

![20200514022816_1](https://user-images.githubusercontent.com/51390907/81901621-cfa6da00-958c-11ea-9bb0-c243d4277082.jpg)
![20200514004540_1](https://user-images.githubusercontent.com/51390907/81901622-cfa6da00-958c-11ea-90ba-f0cb51e5cfd6.jpg)
![20200514004607_1](https://user-images.githubusercontent.com/51390907/81901623-cfa6da00-958c-11ea-9820-1dbfba31cb83.jpg)

**Comment by Majikmonster** [comment]
Seems to be fixed in 20w20c.

**Comment by ultrak2k** [comment]
(close the report)

**Comment by tsunamayo** [comment]
@ultrak2k @Majikmonster thanks, good to heat that. Now if you could let me close the report myself ;) so I can track whats fixed, and put it in my fixed patch not, just tell me it is fixed. Thanks guys for being so active!
