### ISSUE TITLE
Continually spinning rotors

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#2069]
Back before the graphics refactor we were able to build rotors that spun continuously at a speed set by logic. Will this feature be making a comeback before EA?

**Comment by tsunamayo** [comment]
Not before EA for sure, as it will have to wait for collision baking. It is resource intensive as collision check is needed, but if I bake (pre-compute and store) the result it is almost free. But there is a lot of side case, when your rotor is built on a moving children entity ect.

**Comment by ProPeach** [comment]
Thanks for replying! This baking tech sounds awesome, we'll be patient and wait them
