### ISSUE TITLE
[Bug] Cameras don't seem to work

### ISSUE THREAD

**Issue by ultrak2k** [tsunamayo/Starship-EVO#2071]
### Short Description of the issue:
I was preparing my hover for submission, when I noticed after the update my tank's cameras were not working :(
I tried this with hover linked and not linked, turret linked, and on a child entity and not on a child entity.

### Steps to reproduce the issue:
Link camera to yoke
Use yoke
Nothing.

### Environment
- Starship EVO version: 20w20c
- Graphics Card: nvidia 840M

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4631723/output_log.txt)

**Comment by tsunamayo** [comment]
> Link camera to yoke
This is the issue, it is
> Link Yoke to camera.
I will make sure to not allow this, and give you a little warning message when you try to do so.
For some reason a lot of tester wants to link the other way around, I had the same issue with thrusters also.
I keep you posted.

**Comment by ultrak2k** [comment]
> > Link camera to yoke
> > This is the issue, it is
> > Link Yoke to camera.
> > I will make sure to not allow this, and give you a little warning message when you try to do so.
> > For some reason a lot of tester wants to link the other way around, I had the same issue with thrusters also.
> > I keep you posted.

That's strange, since doing that worked before.

**Comment by tsunamayo** [comment]
Hum I would be surprised if that ever worked... But in any case I added a warning and prevented that.
This is why I need tester! It is not always bug but improve things that are not logical.
Fixed for 20w20d.
