### ISSUE TITLE
[Bug] Turret stuck in position - worked last update, broken now

### ISSUE THREAD

**Issue by ultrak2k** [tsunamayo/Starship-EVO#2072]
### Short Description of the issue:
Same story as #2071 , but with me testing my tank's turret. I set the rotors to horizontal base vertical gun, and the reverse, but none of them seemed to work.
The gun itself worked fine - the hotkey brick was okay.

Blueprint provided

### Steps to reproduce the issue:
Build turret
Operate turret 
Won't work - cannot turn whatsoever

### Environment
- Starship EVO version: 20w20c
- Graphics Card: nvidia 840m

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
[Misaka Mikoto HMBT.zip](https://github.com/tsunamayo/Starship-EVO/files/4631730/Misaka.Mikoto.HMBT.zip)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4631728/output_log.txt)

**Comment by Majikmonster** [comment]
I'm having this exact issue. I've fixed the turrets on the blueprint submitted in #2066 / #2067 many, many times, only for them to break in some form or another, including movement.
Here's a snippet of my rant on Discord after spending 6 hours working to fix a dozen turrets:
![SEVO_cinematic_pirate ship turret woes](https://user-images.githubusercontent.com/51390907/82000559-bb172000-9626-11ea-8419-6f08b61a39ec.PNG)
It must be a 20w20b/c problem. I hadn't worked on turrets so extensively until this latest release, so I wouldn't know if it was an issue before.

**Comment by tsunamayo** [comment]
Okay guys I am on it. @Majikmonster No need to spend too much time on something if it is broken!
I did a few change to the children entity collision point logic.

**Comment by ultrak2k** [comment]
> Okay guys I am on it. @Majikmonster No need to spend too much time on something if it is broken!
> I did a few change to the children entity collision point logic.

Actually, it turns out that the camera not being linked properly broke the turret, lol

**Comment by tsunamayo** [comment]
@ultrak2k turret work now? I saw you also enter the turret with the yoke, I wonder if thats legit.

**Comment by ultrak2k** [comment]
> @ultrak2k turret work now? I saw you also enter the turret with the yoke, I wonder if thats legit.

yeah, its fine
yeah, multicore turret and hover is functional too, no bugs there

**Comment by tsunamayo** [comment]
@Majikmonster are #2066 and #2067 the only issue you have atm, or is there more? Do you have a turret stuck issue also? Thanks

**Comment by SageThe13th** [comment]
[Omniturret.zip](https://github.com/tsunamayo/Starship-EVO/files/4632212/Omniturret.zip)

Here's a turret. Before I could use this in 3rd person mode just fine. Now it spins around wildly until you enter the camera.

**Comment by tsunamayo** [comment]
@SageThe13th thats seems to be a different issue...

**Comment by tsunamayo** [comment]
yeah okay your design is really audacious, but I like it. I can see why it dont work, the second axis position is moving around the player. I will see if I can fix it.

**Comment by tsunamayo** [comment]
@SageThe13th okay your turret design was not working simply because no weapon link assignment was made. Turret computer needs that to understand what to point. I added a warning message so hopefully it will be easier for newcomer to understand that. I will also add a help message in the turret computer menu as it is tricky.

**Comment by ultrak2k** [comment]
wew
