### ISSUE TITLE
[Bug?] Hovercraft don't hover on water

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Starship-EVO#2073]
### Short Description of the issue:
Hovercraft Have troubles hovering on water sometimes they do sometimes they don't
https://streamable.com/za9sq3
...

### Steps to reproduce the issue:
- try to hover on water
- issue
...

### Environment
- Starship EVO version: 20w20c
- Graphics Card: Integrated Graphics

### Additional information:
[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/4632641/output_log.zip)

**Comment by tsunamayo** [comment]
Thanks for the vid, your truck looks lovely!
Btw I dont see any grass - have you deactivated that?
Also there is a lot of error message in the log, I wonder if you activated anything specific?
Cheers

**Comment by tsunamayo** [comment]
Issue fixed for 20w20e. Thanks!

**Comment by Aiwii** [comment]
Sorry for the late reply, Yes I deactivated grass and foliage and rocks
