### ISSUE TITLE
[Bug(s)][20w20c] Turret movement and fire modes bugged

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#2074]
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4633412/output_log.txt)

Turrets are inconsistent in their performance.
Sometimes I enter the ship yoke and the ship turrets work fine.
Getting in again, they then can't move, fire, or both on either one or both barrels on either axis.
The AI tracking sometimes doesn't work, and the auto-fire sometimes doesn't work.
These individual problems seem to mix-and-match depending on the moment, and revert from resolved to re-broken whenever I try to remedy them.
### Steps to reproduce the issue:
- load blueprint from issue #2066 / #2067 
- pilot ship
- select a target for ship
- deselect ship target
- exit yoke
- repeat from step 2
- watch the turrets decay in performance
### Environment
- Starship EVO version: 20w20c
- Graphics Card: Nvidia GeForce GTX 1060 6GB

**Comment by tsunamayo** [comment]
Hi, could you please send me the smaller blueprint if you also have the issue with this one? this will be easier for me to work with.
Are you seeing this on all turrets? Like the large side turret and the smaller one?
I saw the smaller one had an additional gate pluged into them. 
What is that and what is the purpose? Thanks

**Comment by tsunamayo** [comment]
I not 100% sure to manage to ever reproduce that, but looking at my code I have found something that could have explain some randomness in turret behaviour. 
I fixed it, did quite a few run like you instructed, and the turret were just firing fine.
I will release the next patch soon (20w20d), you will tell me if you manage to reproduce or not.

For the logic I think the purpose was to reset the angle if I am correct - it is a bit weird, not sure what should happen if you activate this when running a turret. I think the best should be to add a rest position parameter in the turret setting, what do you think?

**Comment by Majikmonster** [comment]
All the turrets suffered from the bug.
I can send you the 2 smaller versions of the ship, yes.
A resting position parameter would be fantastique!

**Comment by tsunamayo** [comment]
Okay I noticed that some turret where not pointing at all, but their hinge were not linked from the turret computer... Instead they were linked from the other hinge...
As this is the case for many turret I guess it is intentional.
Now I would like to know why you assigned them this way? 
Maybe you thought that this way the move from the first hinge will propagate to the second one?

It seems that there is an accessibility issue - turret making is tricky - I might prevent that link, or not allow a link when this is turret rotator / hinge.
Definitely interesting to me to see how people are using the system - this is why I am requesting blueprint.
Thanks

**Comment by tsunamayo** [comment]
Okay @Majikmonster new build is live if you could tell me if that fix some of your issue (the one where it seemed random after enter/exit the yoke). Thanks

**Comment by Majikmonster** [comment]
Haven't had the issue so far. I even stress-tested it by repeatedly entering/exiting and selecting/switching targets. Looks like it's been resolved, at least from what I've seen.
I'll try another series of tests before I consider it resolved.

**Comment by tsunamayo** [comment]
@Majikmonster okay great, tell me if you see that again. Cheers
