### ISSUE TITLE
[BUG] Bouncing on Habitat Landing Pad

### ISSUE THREAD

**Issue by alxnns1** [tsunamayo/Starship-EVO#2075]
### Short Description of the issue:

The character seems to bounce on the landing pads on the habitat where the landing pad merges with the terrain.

### Steps to reproduce the issue:

- Slowly walk to where the terrain rises through the lading pad
- Watch as you are bounced into the air
- Try to stay in that spot to watch you bounce higher and higher

### Environment

- Starship EVO version: 20w20c
- Graphics Card: GTX 1050 Ti

### Additional information:

![20200515104902_1](https://user-images.githubusercontent.com/485571/82037581-3fef5180-969a-11ea-802d-e05be303c6a4.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4633630/output_log.txt)

**Comment by tsunamayo** [comment]
Okay as I just removed those pad this wont longer apply. This was more an experiment, building on torus will use something different. Thanks!
