### ISSUE TITLE
[Bug] Query Gates Don't Support Decimal Numbers

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Starship-EVO#2076]
### Short Description of the issue:

Basically, after the query gates were fixed and updates, they now no longer support decimal numbers. So if I have a slider 3.75m, and I want the query gate to activate 3.74m superior, it doesn't work nor allow it.

Also some general instructions regarding how the new query gate interface works would be helpful. I got a bit lost on some parts, sadly I can't remember what at the moment. 
I just saw this bug still hadn't been reported considering it was found about 10 minutes after the update went live.

### Steps to reproduce the issue:

Type a decimal number in the query gate.

### Environment
- Starship EVO version: 20w20c
- Graphics Card: 2080 Super OC

**Comment by tsunamayo** [comment]
Issue fixed for 20w20d. Thanks! Thats a bit scary if people see some issue but dont report it... =(
