### ISSUE TITLE
[Bug][20w20d] Ship heat balance double from previous version (on spawning blueprint)

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#2078]
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4637796/output_log.txt)

I loaded up the package drone I submitted earlier to the hovercraft thread, and the 92% heat rating (says 74% in the screenshot but I doubled the thrusters) of the 20w20c submission has mysteriously become 179% heat in the current version.
**edit: This was corrected by breaking and replacing some hull.**

### Steps to reproduce the issue:
- load this blueprint
[Majikmonster_Amazin_drone_delivery_BEEG.zip](https://github.com/tsunamayo/Starship-EVO/files/4637790/Majikmonster_Amazin_drone_delivery_BEEG.zip)

### Environment
- Starship EVO version: 20w20d
- Graphics Card: Nvidia GeForce GTX 1060 6GB

Before:
![20200515115646_1](https://user-images.githubusercontent.com/51390907/82110018-23d6c900-9709-11ea-8055-e1387db7186f.jpg)
After:
![20200516000003_1](https://user-images.githubusercontent.com/51390907/82110024-29ccaa00-9709-11ea-8492-30aacaef96ff.jpg)

This was in multiplayer. I haven't tested other ships, but as I haven't had any problems with them, I think it may be a ship-specific or hovercraft-related bug.

**Comment by tsunamayo** [comment]
I cant reproduce this, I will try in multiplayer.

**Comment by tsunamayo** [comment]
Also can you try to load in single player? Do you see the same issue? Thanks

**Comment by tsunamayo** [comment]
@Majikmonster Also what bugs me is that you have save issue in your log file.
=> Is the game saving correctly? Was this a new player or an existing one? 
Thanks

**Comment by Majikmonster** [comment]
- I've spawned the same blueprint several times in singleplayer, but haven't had the bug again.
- The game is saving correctly that I know of. Maybe it's all the times I've pressed Alt+F4 to exit multiplayer.
- My character data was reset with one of the previous updates as well as the introduction of the tutorial zone, so I deleted the character and started fresh.
