### ISSUE TITLE
[Bug] Hostile ships spawned missing NPC pilot, not moving/fighting [20w20d]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#2080]
### Short Description of the issue:
Spawning a hostile ship from the starter block does not place an NPC at the controls, and the ship does not move or fight.

### Steps to reproduce the issue:
Spawn ship from starter core with hostile setting.

### Environment
- Starship EVO version: 20w20d
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4637935/output_log.txt)

**Comment by tsunamayo** [comment]
Yes sorry I was in the middle of a dev regarding that aspect. Not sure how I will integrate that in its final form... This should be only for creative, or maybe a sim mode where you can try your design against various enemy?

**Comment by Dwarf-LordPangolin** [comment]
Either would be fine; it's definitely a handy feature to have, and testing balance without it is harder.

**Comment by tsunamayo** [comment]
Fixed for 20w20c. Thanks!
