### ISSUE TITLE
[BUG] Camera launched into space when docked

### ISSUE THREAD

**Issue by alxnns1** [tsunamayo/Starship-EVO#2081]
### Short Description of the issue:

The camera (not the brick, the user's viewport) gets launched into space when the user docks at a landing pad while in third-person view and in free-camera mode

### Steps to reproduce the issue:

- Fly to a landing pad
- Press `F4` to go into third-person view
- Press `TAB` to go into free-camera mode
- Dock at the landing pad
- Watch as the camera/viewport is sent backwards into space, quickly reaching distances of light years until the viewport gets flooded with colours

### Environment

- Starship EVO version: 20w20d
- Graphics Card: GTX 1050 Ti

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4638193/output_log.txt)

The ship used:
[New Entity1.zip](https://github.com/tsunamayo/Starship-EVO/files/4638194/New.Entity1.zip)

Screeshots:
![20200516111238_1](https://user-images.githubusercontent.com/485571/82117538-92973f00-9768-11ea-92d2-3d359c06e39c.jpg)
![20200516111241_1](https://user-images.githubusercontent.com/485571/82117539-932fd580-9768-11ea-94ed-c310d33aed93.jpg)
![20200516111243_1](https://user-images.githubusercontent.com/485571/82117541-932fd580-9768-11ea-989a-89619ddcaaea.jpg)
![20200516111244_1](https://user-images.githubusercontent.com/485571/82117542-932fd580-9768-11ea-9fca-d826b6c5c0df.jpg)
![20200516111249_1](https://user-images.githubusercontent.com/485571/82117543-93c86c00-9768-11ea-8b1a-5a318f7ecb24.jpg)

**Comment by tsunamayo** [comment]
I cant reproduce your test case.
=>Did you activated a mechanism of some sort when docked?
=>Are you able to reproduce this all the time or was just this time? Also if you ever had this with another ship?
Thanks

**Comment by alxnns1** [comment]
I can recreate this with different ships and on different landing pads of different categories, every time, but only in third-person

**Comment by tsunamayo** [comment]
What is your mouse setup (standard mouse and no controller, or something else?)
I dont know if anybody else is reproducing this.
Also I dont know if you can record video easily or not, I think a short video of the bug could help me... This bug is a bit scary, I would like to fix it asap...
Thanks!

**Comment by alxnns1** [comment]
ok, I was able to recreate it up until I tried to record it with Xbox Game Bar (I don't have any proper recording software). I switched to fullscreen (I usually have the game in windowed mode at the smallest resolution) then it stopped happening. When I switched back to windowed I still was not able to recreate it so I'm not entirely sure what caused it and I am now not able to recreate it.

I use a standard mouse, no controller.

**Comment by tsunamayo** [comment]
okay so it seems to be related to windowed mode I guess.

**Comment by tsunamayo** [comment]
And if you start again a new game in windowed, you still reproduce?

**Comment by alxnns1** [comment]
Not anymore, no
