### ISSUE TITLE
[BUG:] Show version CACA ingame

### ISSUE THREAD

**Issue by JRL101** [tsunamayo/Starship-EVO#2082]
### Short Description of the issue:
Being able to see the version of game im playing either in the ESC menu or always in a corner of the game.
Currently only displays "CACA"

### Environment
- Windows 10
- Starship EVO version: **20w20d**
- Graphics Card: **Geforce GTX1080**

![image](https://user-images.githubusercontent.com/33255536/82123299-33b6e180-97cb-11ea-8ba9-4d014c19cb9b.png)

**Comment by JRL101** [comment]
Oh forgot to mention it only shows "CACA" under the current version ingame

**Comment by ProPeach** [comment]
![image](https://user-images.githubusercontent.com/27857711/82121346-2de9dd80-9784-11ea-8f60-a627410f34ad.png)
Not sure what else you're asking for, but it shows the version in the top right already

**Comment by JRL101** [comment]
![image](https://user-images.githubusercontent.com/33255536/82123248-ed618280-97ca-11ea-9d05-19ad5f96103d.png)

**Comment by Garrett-C** [comment]
![image](https://user-images.githubusercontent.com/43644633/82124450-07816d80-9797-11ea-9cf0-eb07ea529dcf.png)

looks fine to me.

**Comment by JRL101** [comment]
Yea not sure why mines showing CaCa

**Comment by Garrett-C** [comment]
Did you perhaps quit to menu and then reopen a save without relaunching the game. I believe that used to cause the caca issue.

**Comment by JRL101** [comment]
**REINSTALLED** seems to have fixed the version ingame

**Comment by tsunamayo** [comment]
Not sure what happened, I guess some conflict in the install folder on steam update...
