### ISSUE TITLE
[Crash] Crashed While Selecting a Character

### ISSUE THREAD

**Issue by SageThe13th** [tsunamayo/Starship-EVO#2084]
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4638444/output_log.txt)

This there somewhere a crash report gets generated?

**Comment by tsunamayo** [comment]
Yes but it wont be useful. 
Was it a new character or an existing one?
Where you able to load your character after that? 
Can you send me your save folder?
Thanks
