### ISSUE TITLE
[bug?] Ship keeps exploding/Black void  [20w20d]

### ISSUE THREAD

**Issue by JRL101** [tsunamayo/Starship-EVO#2086]
[[20w20d] [#2086] output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4638588/20w20d.2086.output_log.txt)
### Short Description of the issue:
Balanced a ship with the info i had,  tried to shoot the guns and the ship instantly self destructed.

None of the stats seem to be outside of the heat threshold im not understanding how the heat works or its being buggy im not sure.

During said destruction, the ship and myself were put into a black void in which i couldnt escape, and everything around me was gone. No ring no landscape nothing. 
I cant even save the world/blueprint because it refuses to let me do that.
...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: **20w20d**
- Graphics Card: **GeforceGTX1080**

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![image](https://user-images.githubusercontent.com/33255536/82122827-72976800-97c8-11ea-9f86-52677e0bcec9.png)

**------LOG:-----**
File is 200+mb
NEW log - old log is renamed and new log was created by game by loading and exiting the save 
[[20w20d] [#2086] output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4638588/20w20d.2086.output_log.txt)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by JRL101** [comment]
Reloading seems to put me into the same place but ESC wont work


![image](https://user-images.githubusercontent.com/33255536/82122938-36b0d280-97c9-11ea-9690-42b9419d508f.png)

**Comment by Majikmonster** [comment]
Heat works in 2 ways: passively and actively.
- Passive heat is the statistic you see in the TAB ship menu, in the bottom right corner when holding your multitool after selecting a ship, or in the bottom left corner when piloting the ship.
- Active heat comes from heat damage inflicted on your ship by weapons, or by heat generated when shields are charging or when guns are cooling. Your ship may have been balanced to dissipate  passive heat, but the additional heat created by your own weapons cooling overwhelmed it.

It is possible that the heat mechanic did not work correctly, as I have experienced some bugginess with it as well in 20w20d.

Unfortunately you can't save the ship in it's current destroyed state.
Fortunately, you are not stuck in a true void. You are inside the sun, which can be exited by opening the TAB menu and using the teleport options to relocate to the space habitat/torus, or by increasing your speed with the square bracket end key **]** and flying out as the player in anti-gravity or 6dof mode.

The world/universe saves on exit to the title or desktop via the Esc key menu. If this wasn't possible, that would be useful information to add in the report.

**Comment by Garrett-C** [comment]
Guns produce heat when they are fired, it's possible that they are the cause for you overheating.

**Comment by JRL101** [comment]
> 
> 
> Heat works in 2 ways: passively and actively.
> 
>     * Passive heat is the statistic you see in the TAB ship menu, in the bottom right corner when holding your multitool after selecting a ship, or in the bottom left corner when piloting the ship.
> 
>     * Active heat comes from heat damage inflicted on your ship by weapons, or by heat generated when shields are charging or when guns are cooling. Your ship may have been balanced to dissipate  passive heat, but the additional heat created by your own weapons cooling overwhelmed it.
> 
> 
> It is possible that the heat mechanic did not work correctly, as I have experienced some bugginess with it as well in 20w20d.
> 
> Unfortunately you can't save the ship in it's current destroyed state.
> Fortunately, you are not stuck in a true void. You are inside the sun, which can be exited by opening the TAB menu and using the teleport options to relocate to the space habitat/torus, or by increasing your speed with the square bracket end key **]** and flying out as the player in anti-gravity or 6dof mode.
> 
> The world/universe saves on exit to the title or desktop via the Esc key menu. If this wasn't possible, that would be useful information to add in the report.

I understand how the heat works. But **RESPAWN** for the ship is not working, and there is no escape from the void created by the explosion.
**It seems any ship i build with a weapon no matter how small compared to the heat dispersion, over heats, with a single shot from a gun. It's odd and im thinking its a bug.** 

> 
> 
> Guns produce heat when they are fired, it's possible that they are the cause for you overheating.

Yes, and no. 
**It seems any ship i build with a weapon no matter how small compared to the heat dispersion, over heats, with a single shot from a gun. It's odd and im thinking its a bug.**

**Comment by Garrett-C** [comment]
Interesting, I made a quick test there and was able to build a block and gun and it doesn't blow up when the gun is fired. Do you have some of these ships for us to look at?

**Comment by Majikmonster** [comment]
The respawn function is unimplemented. No mechanic in the current version is able to bring ships back from total destruction.

Have you tried teleporting out of the void? Are your menus disabled? Are controls seized/unresponsive?

If all else fails, you will have to delete the world save file and start fresh.

**Comment by JRL101** [comment]
> 
> 
> Interesting, I made a quick test there and was able to build a block and gun and it doesn't blow up when the gun is fired. Do you have some of these ships for us to look at?

Thats one of the problems i cant export it to upload the ship. was trying to extract it from the files. 
Doing a quick reinstall to see if i can test the same thing or if it fixes by getting rid of old files.



> 
> 
> The respawn function is unimplemented. No mechanic in the current version is able to bring ships back from total destruction.
> 
> Have you tried teleporting out of the void? Are your menus disabled? Are controls seized/unresponsive?
> 
> If all else fails, you will have to delete the world save file and start fresh.

No teleporting works, no collision from anything that was present before explosion, its like i've been loaded into a complete void. ESC wasnt working, but i got it working, but teleporting still refused to work. was just ignoring me. i didnt even jump to a position, I tested gravity to see if something could attract me to it in the void, but nothing.

**Comment by JRL101** [comment]
**REINSTALL COMPLETE**
No change *(except fixed the version in the corner)*

for some reason the ship has zero thrusters but actually has 8 small thrusters (four front four back)
![image](https://user-images.githubusercontent.com/33255536/82124693-6238ba80-97d3-11ea-9fdf-75ebd80d4617.png)

**Comment by Garrett-C** [comment]
What does the gun look like? 

Also what do you mean about no thrusters? Looks to me like it has them based on the thrust value?

**Comment by JRL101** [comment]
> 
> 
> What does the gun look like?
> 
> Also what do you mean about no thrusters? Looks to me like it has them based on the thrust value?

![image](https://user-images.githubusercontent.com/33255536/82124819-26eabb80-97d4-11ea-89bd-19721a53b8a4.png)

**Comment by Garrett-C** [comment]
Interesting. Did you use the round or square ones, seems that it isn't being included. It could be an issue related to the ship being exploded though.

**Comment by Garrett-C** [comment]
Based on the fact that the laser also isn't being shown it looks like it's a result of the ship being dead.

**Comment by JRL101** [comment]
I would assume so too if this wasnt similar to the example ship in the tutorial area.
Engines mirrored both sides
![image](https://user-images.githubusercontent.com/33255536/82124902-d3c53880-97d4-11ea-9207-264dc7835d85.png)

**Comment by JRL101** [comment]
I would have said the explosion shader consumed my vision, but considering there's nothing around thats likely not right. 

Lets see if i can rip the ship 
![image](https://user-images.githubusercontent.com/33255536/82124951-2e5e9480-97d5-11ea-8d5c-b4e1f885cfd0.png)

**Comment by Garrett-C** [comment]
Just did a test and t seems that the numbers are indeed broken, That's kind of it's own bug though.

**Comment by JRL101** [comment]
mps? are those the new ship file types?

**Comment by Garrett-C** [comment]
Yes

**Comment by JRL101** [comment]
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Characters`
[JRL101.zip](https://github.com/tsunamayo/Starship-EVO/files/4638735/JRL101.zip)

**Comment by tsunamayo** [comment]
Hi @JRL101 ,
so thanks for the save folder, I was able to reproduce.
So what happened:
1) you ship overheat because there is too much weapon when firing
2) your ship exploded
3) then for some reason the ship had an incorrect respawned point that led it to the inside of the star
4) being inside a star/planet means the ship was desintegrated, also the screen/reticle was weird because of the star shader. Each time you put a block it was destroyed again...

So I have done a few change:
1) Now weapon will stop firing if close to overheat. So no possible explosion.
2) I handle incorrect spawn point.

Fixes in 20w20e. Thanks!
