### ISSUE TITLE
[Question/Suggestion] What plans do you have for survival?

### ISSUE THREAD

**Issue by MRonlin** [tsunamayo/Starship-EVO#2087]
**What ideas do you have for survival?(In terms of full release)** 

-The ability to create your own faction.
-Trade? 
-Enemy factions / Allied factions / Neutral factions
-Boarders, and the ability to claim territory (Enemy factions attacking the players territory.)
-Diplomacy? 
-Random encounters (E.g Abandoned stations/Ships, Pirates, "Bosses"(Large ships/fleets), etc..)
-The enemy factions actively search and attack the player.
-Difficulty, having the ability to play in a sort of peaceful mode without any enemies.

**Comment by JRL101** [comment]
> _-Random encounters_ 
I know Tsuna wants that sorta stuff, but considering hes the only one working.

> _-Difficulty_ 
I know Tsuna wants a creative mode, i dont see why peaceful wouldnt also be an option 

everything else im unsure on.
AI will pilot ships to fight with, so weather or not they are in factions is up to the structure Tsuna decides on.

**Comment by ultrak2k** [comment]
There’s an important distinction to make here - on early access alpha or the full picture?

**Comment by MRonlin** [comment]
full picture

**Comment by tsunamayo** [comment]
Hi, so here we go:

-The ability to create your own faction.
=> we will see, this is a performance related issue.
-Trade?
=> yes
-Enemy factions / Allied factions / Neutral factions
=> yes
-Boarders, and the ability to claim territory (Enemy factions attacking the players territory.)
=> we shall see!
-Diplomacy?
=> pve yes, pvp we shall see
-Random encounters (E.g Abandoned stations/Ships, Pirates, "Bosses"(Large ships/fleets), etc..)
=> yes
-The enemy factions actively search and attack the player.
=> yes
-Difficulty, having the ability to play in a sort of peaceful mode without any enemies.
=> yes, creative mode will have a toggle, for when you want to be alone. Also for survival some zone will be under police monitoring - so no fight.

Hope that clear everything!

**Comment by MRonlin** [comment]
Sounds great, thanks for the reply.
