### ISSUE TITLE
Alternative to build mode copy / paste tool

### ISSUE THREAD

**Issue by jimmybub** [tsunamayo/Starship-EVO#2088]
From my reading on Github I've gathered that Tsunamayo has some opinions about copy / paste mechanics.  There are understandable performance concerns, namely that easy copy and paste tools would enable players to make exceedingly large ships quickly.  I'm combining the notes of others on this Github that have talked about things like a docking block, and a post from two weeks ago here by endoskull: https://github.com/tsunamayo/Starship-EVO/issues/1897

My suggestion may be far more difficult to add than a simple copy paste feature, but It may solve the qualm of having large block placements be easily accessible.  Basically my solution is to implement a docking block that can permanently combine two entities similar to the merger block in space engineers.  This isn't to say it's an EASY fix per say, or even a good one, but I figured it couldn't hurt to post it on Github to get some thoughts about it.

**Comment by tsunamayo** [comment]
I am not sure to understand if you could detail more, what is the merger block in SE? (didnt played it)
I am confused as you talk about copy and paste / docking and some stuff I dont know about ;)
Thanks

**Comment by jimmybub** [comment]
This is the first image I could find that seems to illustrate things well.  
![chrome_I606XyZOK8](https://user-images.githubusercontent.com/13528733/82136048-8bf3e080-97d7-11ea-97e8-00948d1a6815.png)
(the merger blocks are the ones with orange lights on each structure)
It's a block from space engineers that when powered, combines two entities in to one entity.  When I made this issue post I was under the impression that it permanently combined them, but I may have been conflating that with a mod of some kind.  But essentially you would fly one ship, dock it to another, and my idea was to then make the merger blocks become inert and convert the two ships in to one.

**Comment by tsunamayo** [comment]
Okay so yes it is a docking block.
Docking block are planed, but not to be used as a copy-paste replacement, performance wise it is 1000% worse than a copy-paste ;)
Are you using that to get a copy-paste function in SE?

**Comment by jimmybub** [comment]
yes, the method is to create a new entity, or spawn it in, then maneuver the two ships together.  it works in SE with ships that don't have any control.  That's why I think it may be in interesting take on how to prevent fast building of ships.  though honestly, this method is far less convenient than a simple copy / paste.  If your intention, though, is to reduce average ship size by making them harder to build, this may be a method that suits you.

**Comment by jimmybub** [comment]
If you don't mind me reiterating and following with a question, when the ships combine, my intention is not to make them appear to be one entity, but to be code wise only one entity.  This may not be possible with the current game engine and that's absolutely fine, just making sure that the point is across.  If you and I have the same understanding of my proposal, what would cause the loss of performance?

**Comment by tsunamayo** [comment]
So weld like tool is possible, it is just trouble some to code. Main issue would be the logical links. I dont want to go into that atm, I can small all the issue and edge case I would have to deal with after...

**Comment by tsunamayo** [comment]
Btw copy-paste seems a lot easier code-wise than entity merging.

**Comment by jimmybub** [comment]
seems that way to me too, lol.  I'll go ahead and close this issue then, and wait patiently for copy/paste functionality at whatever point it's implemented at ;P
