### ISSUE TITLE
[Suggestion] Hold key to free look in cockpit

### ISSUE THREAD

**Issue by Calvert4096** [tsunamayo/Starship-EVO#2090]
Apologies if this has been suggested/planned already but I couldn't find another instance of this.

The ability to hold a key (Alt, for example) to free look in a cockpit and momentarily disable mouse control of the ship would be desirable.  At the moment this can be accomplished by exiting/re-entering the yoke control, but a key hold similar to many flight-sims would be a little less cumbersome I think.

**Comment by Calvert4096** [comment]
Nevermind ... noticed this was already possible by pressing tab.

**Comment by tsunamayo** [comment]
Yes, I was thinking of moving to a scheme were we do right
