### ISSUE TITLE
[Bug] Torus grass rendering is glitchy

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#2091]
[output_log_2020-5-17.zip](https://github.com/tsunamayo/Starship-EVO/files/4639950/output_log_2020-5-17.zip)

### Short Description of the issue:

Grass blades pop in and out of rendering depending on what chunk/section of the torus you are near or looking at.

### Steps to reproduce the issue:

Walk around torus and look at the grass patches/seams

### Environment
- Starship EVO version: 20w20d
- Graphics Card: Nvidia GeForce GTX 1060 6GB

![20200517050542_1](https://user-images.githubusercontent.com/51390907/82140248-91175680-97fc-11ea-8fee-3f4f286beda2.jpg)
![20200517050540_1](https://user-images.githubusercontent.com/51390907/82140249-91afed00-97fc-11ea-81dd-c318667a2008.jpg)

![20200517051056_1](https://user-images.githubusercontent.com/51390907/82140402-e05d8700-97fc-11ea-9be9-3afdda7ac574.jpg)
![20200517051059_1](https://user-images.githubusercontent.com/51390907/82140404-e0f61d80-97fc-11ea-9637-3ab72d34142f.jpg)

**Comment by tsunamayo** [comment]
You have a lot of error in your log, might be unrelated or not.
=> do you get this 100% of the time? 
Obviously I dont see this on my PC...

**Comment by Majikmonster** [comment]
Not all the time, no. It seems to coincide with long sessions or laggy/buggy gameplay, both in singleplayer and in multiplayer.

**Comment by tsunamayo** [comment]
okay long and buggy session - good to know. Do you remember anything particularly buggy, typically a yoke activation or desactivation of some kind? There is some error related to that.

**Comment by Majikmonster** [comment]
A lot of times when It was noticed, myself and few others were testing ships that ended up being subjects of bug reports. My double heat hovercraft, the ships whose turrets wouldn't work, and some multiplayer sessions where the performance was terrible due to one issue or another resulting in ships ghosting through the terrain or becoming immune to gravity.

I'm not sure what any of that has in common other than coincidence, but that's when the grass issue gets noticed most.

**Comment by tsunamayo** [comment]
I see. What kind of issue was there is multiplayer, was it reported? Thanks

**Comment by Majikmonster** [comment]
After some time, I've realized it isn't exclusive to multiplayer or presence of other bugs. It just seems to happen after long times running the game.

I think all of the bugs we've noticed in multiplayer have been reported, but I will make sure (I've been keeping a list).

**Comment by tsunamayo** [comment]
I think this issue should be fixed in 20w23d - if not dont hesitate to ping me! Cheers
