### ISSUE TITLE
[BUG] Able to fly through the sea-bed

### ISSUE THREAD

**Issue by alxnns1** [tsunamayo/Starship-EVO#2098]
### Short Description of the issue:

As a character in anti-gravitation mode you are able to fly through the lowest sea-beds on the habitat as if there was no terrain there

### Steps to reproduce the issue:

- Change locomotion mode to anti-gravitation
- Go to a lake with a flat sea-bed
- Fly though it

### Environment

- Starship EVO version: 20w21a
- Graphics Card: GTX 1050 Ti

### Additional information:

![20200518103136_1](https://user-images.githubusercontent.com/485571/82197740-41678680-98f3-11ea-809e-9ce61c4b109a.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4643247/output_log.txt)

**Comment by tsunamayo** [comment]
Indeed! Issue fixed for 20w21b. Thanks!
