### ISSUE TITLE
[Suggestion] Hovercraft power down

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#2099]
Just a small one to make things feel a bit better - Right now when you exit a yoke after controlling a hovercraft, all power cuts and it drops to the ground. This looks wrong and feels a bit dangerous especially if collision damage is implemented, so I suggest a slower drop of the repulsor strength to zero rather than a straight cut to zero and then the reverse for powering up. This would also give landing gear a change to catch the hovercraft, rather than it just bouncing back up and potentially tipping over.

**Comment by tsunamayo** [comment]
yes indeed, just fyi for powering up it is already a smooth take-off. Thanks

**Comment by tsunamayo** [comment]
Okay implemented for 20w21b. Thanks
