### ISSUE TITLE
[Bug] Torus Targeting

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#2101]
### Short Description of the issue:
When flying inside the torus, the boundary box for targeting it extends inside the middle, so you see the "0m interact" icon all the time. Ideally the targeting box would more tightly conform to the torus so that this doesn't happen

![image](https://user-images.githubusercontent.com/27857711/82224260-8ef7e980-991b-11ea-8a12-54d831387762.png)

### Steps to reproduce the issue:
Fly a ship in/around the torus

### Environment
- Starship EVO version: 20w21a
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
You cant make a tigther bounding box ;) but I know what you mean - actually it is supposed to not be shown at all so it is a bug.

**Comment by ProPeach** [comment]
Gotcha!

**Comment by tsunamayo** [comment]
Okay issue fixed for 20w20b. Thanks!
