### ISSUE TITLE
[Bug] Turret Warning message

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#2102]
### Short Description of the issue:
The warning message "unable to align - need to link to gun" pops up even if you've linked your turret yoke to a camera, which also aligns the turret correctly. This could be frustrating for players building a turret with no weapons, like the movable camera in the old tutorial zone
![image](https://user-images.githubusercontent.com/27857711/82226524-8228c500-991e-11ea-91bd-1dd14401c5ca.png)

### Steps to reproduce the issue:
Build a turret with a camera, but don't link the turret core to a gun

### Environment
- Starship EVO version: 20w21a
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
Fixed for 20w21b. Thanks!
