### ISSUE TITLE
Logic bomb.

### ISSUE THREAD

**Issue by ItsCrusade** [tsunamayo/Starship-EVO#2103]
### Short Description of the issue:
A logic bomb that tanks performance in-game.
Uses 5 logic bricks to achieve this

...

### Steps to reproduce the issue:
1. BACK UP YOUR WORLD FILES.
2. Spawn in the attached blueprint.
3. Flip the switch and watch your performance tank hard.

...

### Environment
- Starship EVO version: 20w21a
- Graphics Card: gtx1070ti

### Additional information:
Suggested fix - limit the amount of logic commands a since circuit can process per second/tick.
[XNOR logic bomb.zip](https://github.com/tsunamayo/Starship-EVO/files/4645901/XNOR.logic.bomb.zip)

**Comment by ItsCrusade** [comment]
Video/GIF of the device. 

https://gfycat.com/boilingelementarycurlew

**Comment by tsunamayo** [comment]
Thanks for this demonstrative test case - I indeed put a limit of one tick per frame, might change that to some more elaborate limit in the future. Will be fixed in 20w21b. Thanks a lot!
