### ISSUE TITLE
stuck in turret

### ISSUE THREAD

**Issue by crazyxangel** [tsunamayo/Starship-EVO#2104]
### Short Description of the issue:

i enter turret nothing works i cant exit turret i restart game and i am stuck as a flying tool that cant do anything

### Steps to reproduce the issue:
none seeing as i am literally just stuck

### Environment
- Starship EVO version: w/e the regular download version is at this very moment
- Graphics Card: irrelevant

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

![image](https://user-images.githubusercontent.com/37293964/82257086-b7053e00-9957-11ea-9872-c84214e0d131.png)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4646537/output_log.txt)

**Comment by tsunamayo** [comment]
@crazyxangel could you send me your blueprint so I can investigate the issue! I should be able to get it sorted out.
Thanks

**Comment by crazyxangel** [comment]
thats actually the biggest problem i cant i didnt blueprint it before entering the turret and i most certainly cant do it now that my character is stuck

**Comment by tsunamayo** [comment]
@crazyxangel, no problem, if you could simply zip me your full Save_Data folder in:
UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\
And tell me the name of your character, I will do the rest!
Thanks

**Comment by crazyxangel** [comment]
theres only one character "crazy"
[Save_Data_crazyxangel.zip](https://github.com/tsunamayo/Starship-EVO/files/4649992/Save_Data_crazyxangel.zip)

**Comment by tsunamayo** [comment]
@crazyxangel okay issue fixed for 20w20b. Thanks a lot!
