### ISSUE TITLE
[Suggestion] Change Corellian Shuttle name?

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#2106]
Because Star Wars is owned by Disney, and because Disney has a reputation for taking legal action against anything remotely related to IPs they own, some of us wanted to suggest that you change the name of the Corellian Shuttle ship.

**Comment by ZachZent** [comment]
Just name it the Skywanderer and call it a day

**Comment by AlienXtream** [comment]
^
