### ISSUE TITLE
[SUGGESTION] angled small block connectors

### ISSUE THREAD

**Issue by nokturnihs** [tsunamayo/Starship-EVO#2108]
### Short Description of the issue:

To reduce child entities so we can acconplish some smaller decorative needs, add a 45° angled connector or "elbow" so we don't need to use hinges when we want to do things like recliners, etc. 

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by Aiwii** [comment]
Yes something like an angled offset that is stationary but offsets the grids angle

**Comment by tsunamayo** [comment]
This was suggested, unfortunately an angled grid is by nature a separate grid, with separate collision data, separate gfx data and pass and all that make children entity bad for performance.
In short angled connector = children entity.
So it is not really possible in a way that would help performance...
Cheers
