### ISSUE TITLE
large laser with range barrel not working

### ISSUE THREAD

**Issue by crazyxangel** [tsunamayo/Starship-EVO#2112]
### Short Description of the issue:

when i fire the weapon it deals no damage and i get no heat buildup

### Steps to reproduce the issue:

place laser weapon block attach range barrel connect to yoke with hotkey brick attempt to fire it

### Environment
- Starship EVO version: latest

**Comment by tsunamayo** [comment]
Okay I cant reproduce this, could you send me your blueprint?
Also make sure that the assignment is as below:
Yoke => hotkey => weapon.

**Comment by crazyxangel** [comment]
i'll toss you my entire save
oh and the weapon fires no problem its just the laser phases trough everything and deals no damage but only with the range barrel
if i install the heath/gattling/the-third-barrel it does work and destroy blocks but when i ductape on the range barrel it does not.
only one character in it
[Save_Data.zip](https://github.com/tsunamayo/Starship-EVO/files/4661394/Save_Data.zip)

**Comment by tsunamayo** [comment]
I think it was just the issue of firing at things that were too close. There was an issue with that, it is fixed for 20w21d. Thanks
