### ISSUE TITLE
Manual Turret Camera Bug

### ISSUE THREAD

**Issue by ADDexia** [tsunamayo/Starship-EVO#2117]
When a camera is placed on a turret or on the ship itself manual turrets break and do not move properly if at all. When I place a camera on a turret it moves left and up at the same time regardless of what i'm doing with my mouse BUT when i remove the camera and just view through F4 they work perfectly. The turret follows your mouse and I think they don't work with a camera because the cameras don't follow your mouse movements, they just freeze them in place. I do not understand how your example turrets camera is working but when I copy the exact same design it still doesn't work.

**Comment by tsunamayo** [comment]
Hi, thanks for booking the case. Did you made the rotator axis assigment?
Do that you need to press F on the rotator and choose between Horizontal / vertical and inverted or not. I will try to remove these assigment in the future.
Thanks

**Comment by ADDexia** [comment]
that fixed it thank you, I didn't realize you had to press F on the rotator to switch it yourself. I assumed it was automatic. thank you though, this was driving me nuts until now!
