### ISSUE TITLE
[Bug?]Do hovercraft not do damage?

### ISSUE THREAD

**Issue by ultrak2k** [tsunamayo/Starship-EVO#2118]
### Short Description of the issue:
So I tried shooting at another unshielded hovercraft and a wall, only to notice that nothing happened to the enemy hull.
...

### Steps to reproduce the issue:
Try shoot something in a hovercraft (in my case with turret)
Doesn't work
...

### Environment
- Starship EVO version: 20w21b?
- Graphics Card: nvidia 840m

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

https://youtu.be/llkNCADQtfs

**Comment by tsunamayo** [comment]
Issue should be fixed on 20w21d, there was an issue for hitting things that are too close. Thanks
