### ISSUE TITLE
Question, what's the refund policy for keys bought over Paypal?

### ISSUE THREAD

**Issue by TurklerRS** [tsunamayo/Starship-EVO#2122]
Just shooting this here, came over from discord. What's the refund policy for keys bought over paypal? Is it the same ''About 2 hours to back out with no questions asked'' as Steam provides, or is it a no-refund policy, or anything inbetween?

**Comment by tsunamayo** [comment]
No its is definitely not like steam, I cant check these things manually. If you are not sure and want a refund policy I would suggest to wait for the official early access, it is soon! Otherwise check first that your hardware can run the game, if you are not sure you can ask me or on the discord.
