### ISSUE TITLE
[Bug] View Collisions Boxes defaults to on [20w21c]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#2123]
### Short Description of the issue:
The setting in the F3 debug menu "View Collisions Boxes" defaults to On. If disabled, it will re-enable itself when the game is restarted.

### Steps to reproduce the issue:
Start game, check setting. 

### Environment
- Starship EVO version: 20w21c
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20200521222814_1](https://user-images.githubusercontent.com/33041786/82628563-c8965200-9bb2-11ea-8b02-04486f56cca0.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4665922/output_log.txt)

**Comment by tsunamayo** [comment]
Fixed for 20w21d. Thanks!
