### ISSUE TITLE
Glass Wedge Does not Widen [Bug]

### ISSUE THREAD

**Issue by EndoSkull** [tsunamayo/Starship-EVO#2124]
### Short Description of the issue:
I've tried various ways to stretch the Glass wedge and it only stretches long ways and does not go wide like other blocks - I've tried using suggest e or q key and does not work. 
Is this a bug or a missing glass wedge feature?
...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Yes it is normal, it is supposed to be a side wedge for windows. I will add a normal wedge block for the use you want, I will do it soon (before EA at least...). Thanks

**Comment by JRL101** [comment]
Ahh okay, i was about to report the weird mixture of glass blocks, maybe an easy fix for this is to turn "glass" into a paint/shader for any block. 

You could change the "window brick" into a brick that masks the block its on to create a window, bit like how the decals work, but looks something like the "vent" for the window boarder. (if that makes any sense without a diagram) 

that would then give us a "bordered window" brick.
and "glass paint"
