### ISSUE TITLE
[BUILDS] NPC ship designs (ideas/designs)

### ISSUE THREAD

**Issue by JRL101** [tsunamayo/Starship-EVO#2125]
Topic is for Uploading images and designs for ships to be NPC's

Must include with post:
Faction name:
Ship Class:
Difficulty:
Built in weakness:

other details are welcome, but backstory is unnecessary right now.

If you post a ship file, please include a screenshot of the ship at least from one angle.
WIP images are also welcome this should be a smelting pot of designs. This includes modifying posted designs and tweaking them to fit design parameters. (if Tsunamayo sets any) Optimised NPC's are best.

Ship restrictions would be welcome, having boundaries like limiting the decals and amount of blocks we use will be vital to making an optimised NPC

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by JRL101** [comment]
![image](https://user-images.githubusercontent.com/33255536/82644759-6ab24a80-9c44-11ea-93e3-7e076023b148.png)
![image](https://user-images.githubusercontent.com/33255536/82644779-7736a300-9c44-11ea-80e0-f0381494d28a.png)
![image](https://user-images.githubusercontent.com/33255536/82644896-a0efca00-9c44-11ea-9628-0639b8af989b.png)
![image](https://user-images.githubusercontent.com/33255536/82644926-ae0cb900-9c44-11ea-923b-65f0e77d2b7d.png)
![image](https://user-images.githubusercontent.com/33255536/82644986-c250b600-9c44-11ea-8276-273441b45d36.png)
![image](https://user-images.githubusercontent.com/33255536/82645020-ced50e80-9c44-11ea-8714-f29d6e707884.png)
![image](https://user-images.githubusercontent.com/33255536/82645064-e01e1b00-9c44-11ea-9bb3-2bf9d1532e11.png)
![image](https://user-images.githubusercontent.com/33255536/82645110-f035fa80-9c44-11ea-9851-33280dbcc3e8.png)


[Pirate Runner 01a_JRL101.zip](https://github.com/tsunamayo/Starship-EVO/files/4666782/Pirate.Runner.01a_JRL101.zip)

**Comment by Majikmonster** [comment]
We already have an official thread for this:
[Dev - Feedback] Any cool blueprint to share? Faction Help #1569 
It includes a link to the Google doc for building guidelines set by Tsuna.

**Comment by JRL101** [comment]
> 
> 
> We already have an official thread for this:
> [Dev - Feedback] Any cool blueprint to share? Faction Help #1569
> It includes a link to the Google doc for building guidelines set by Tsuna.

Oh okay, i was looking for a thread and i didnt see that. Should be pinned. Thanks! Removing Thread.
