### ISSUE TITLE
Walking on air

### ISSUE THREAD

**Issue by Demozo** [tsunamayo/Starship-EVO#2126]
### Short Description of the issue:

Able to walk into the air by looking straight up or down.
In "None" locomotion mode.
Also seems to be a thing Jetpack mode.

### Steps to reproduce the issue:

Select locomotion mode: None or Jetpack.
Look straight up or down, and then press W or S respectively.

### Environment
- Starship EVO version: pre-alpha 20w21c
- Graphics Card: GTX 1080Ti

**Comment by tsunamayo** [comment]
Okay I see. Where are you located? Do you have that all the time? I am not reproducing on my side. Thanks!

**Comment by Demozo** [comment]
I am in the disc. I'm honestly not quite sure what causes it, however I am also slightly sliding over the floor, which seems to suggest that the game doesn't properly register me touching the ground. It persists even when going back to the Title Screen and restarting the game.

Also happens when in outer space in a gravity zone.

**Comment by AlienXtream** [comment]
got a video of this. 
https://youtu.be/_YAnbwNYV90

first 5 sec are me jumping for comparison. glitch starts once i look down

**Comment by tsunamayo** [comment]
Okay I see now! Issue fixed for 20w21d. Thanks!
