### ISSUE TITLE
[Bug] Paint cubes

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#2130]
### Short Description of the issue:
When you hold a paint in your hand, it appears as a cube on top of the multitool. Could be related to #2038 
![image](https://user-images.githubusercontent.com/27857711/82691422-c933f480-9c55-11ea-9cd0-4dfc0d274f83.png)

### Steps to reproduce the issue:
Hold some paint in your hand (maybe using an AMD card?)

### Environment
- Starship EVO version: 20w21c
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
So yes I guess it is another AMD thing. Did you ever saw the paint blob? Thanks

**Comment by ProPeach** [comment]
Yes, it's only since I first saw the yellow cube that this became an issue, before then the paint blob worked great
