### ISSUE TITLE
[Bug] Logic gate stops changing output when has 2 or more query gates as input

### ISSUE THREAD

**Issue by milan-t** [tsunamayo/Starship-EVO#2132]
### Description:
Logic (OR) gate stucks on value 1 when activated from 2 or more query gates reporting state of hinges. Query gates are configured to indicate "on" position of hinges.
When hinge turned on and off, OR gate still has value 1 evan all query gates reports 0.

Problem started to occure since version pre-alpha 20w21b.

Logic gate state can be fixed temporarily by opening and closing logic gate's properties dialog (changing function type is not necessary). When any connected query gate changes from 0 to 1 and back to 0. OR gate stuck on value 1 again.

### Steps to reproduce the issue:
1) place 2 or more hinges
2) place for each hinge query gate and connect hinge to query gate
3) set query gate threshold to value between "on" and "off" positions of hinge to detect active position
4) place logic gate (with OR function) and connect all query gates to logic gate
5) place indicator lights for all gates and connect gates to them
6) place swich that will control hinges
7) turn switch on and off 

Expected: Output from OR gate should change from 0 to 1 then back to 0.
Current: Output from OR gate changes from 0 to 1 and stays 1.

### Environment
- Starship EVO version: pre-alpha 20w21b, pre-alpha 20w21c
- Graphics Card: GeForce GTX 1660 Ti

### Additional information:
I noticed problem when I was finalising a hoover bus. It has 3 pairs of doors. Each door pair have 4 hinges. 4 query gates connected to OR gate serves as "open" position indication. Doors also have some lights above them controlled by their position. First doors have control circuit allowing driver open/close doors from outside.

A hoover bus uses many gates (most of them for doors), so first idea was that observed problem with gates has something to do with the fix for #2103 . Today I was able to reproduce problem using simple mechanism.

If logic gates reads from swithes, they work fine.

Issue probably affects other logic functions.

_output_log.txt:_
[output_log__milan-t__200522-2110.zip](https://github.com/tsunamayo/Starship-EVO/files/4669951/output_log__milan-t__200522-2110.zip)

_Blueprint - simple mechanism:_
[query-to-logic_gate_bug_minimal.zip](https://github.com/tsunamayo/Starship-EVO/files/4669958/query-to-logic_gate_bug_minimal.zip)
_(small mistake - exported with OR gate already in error state)_

_Blueprint - various mechanisms (including pair of doors from a hoover bus) that demostrates problem and other mechanisms that works properly:_
[query-to-logic_gate_bug_demo.zip](https://github.com/tsunamayo/Starship-EVO/files/4669959/query-to-logic_gate_bug_demo.zip)

_Blueprint - combination of sliding rails and hinges:_
[query-to-logic_gate_bug_-_slider_rails_and_hinges.zip](https://github.com/tsunamayo/Starship-EVO/files/4670200/query-to-logic_gate_bug_-_slider_rails_and_hinges.zip)

**Comment by milan-t** [comment]
Mentioned hoover bus, indicator lights on driver's left shows status of retractable platform and doors. Doors are closed but front doors indicator is still green and also warning light above doors blinks.
![hoover_bus_doors_indicator_wrong](https://user-images.githubusercontent.com/65783423/82709504-08c40600-9c81-11ea-8f44-1fd7d66a7465.jpg)

Sliding rails and hinges - different combinations. All indicator lights should be red,
![slide_rails_and_hinges_-_all_indicators_should_be_red](https://user-images.githubusercontent.com/65783423/82709515-0eb9e700-9c81-11ea-9d1f-d6fb74e0b3ed.jpg)

**Comment by tsunamayo** [comment]
Thanks a lot for the detailed case, I keep you posted.

**Comment by tsunamayo** [comment]
Issue fixed for 20w22c. Thanks for the great test case!
