### ISSUE TITLE
[BUILD] Fletcher Micro-Light Fighter 

### ISSUE THREAD

**Issue by nokturnihs** [tsunamayo/Starship-EVO#2134]
### Short Description of the issue:
@tsunamayo - You keep asking for ships so I'll keep submitting them in case you find any of them useful for some reason - this one is a super-small fighter. 1 Shield unit, no full-size reactors and 4 small weapons systems (forward fire only) - Painted it up and hope you like it!

![20200522162728_1](https://user-images.githubusercontent.com/7344403/82713925-eebb0100-9c49-11ea-92a6-46fcd5d6a967.jpg)
![20200522162654_1](https://user-images.githubusercontent.com/7344403/82713930-efec2e00-9c49-11ea-8c24-cf7f3cfcda6f.jpg)
![20200522162633_1](https://user-images.githubusercontent.com/7344403/82713931-f084c480-9c49-11ea-9986-5e9a0b17d536.jpg)
![20200522162623_1](https://user-images.githubusercontent.com/7344403/82713932-f11d5b00-9c49-11ea-8024-3b905ba25b44.jpg)
![20200522162619_1](https://user-images.githubusercontent.com/7344403/82713933-f11d5b00-9c49-11ea-9efd-d13ccda39c1d.jpg)
![20200522162615_1](https://user-images.githubusercontent.com/7344403/82713934-f1b5f180-9c49-11ea-87bc-3acdacc9cb89.jpg)
![20200522162601_1](https://user-images.githubusercontent.com/7344403/82713935-f1b5f180-9c49-11ea-9c9c-8fda34e879aa.jpg)
[Fletcher Micro-Light Fighter.zip](https://github.com/tsunamayo/Starship-EVO/files/4670656/Fletcher.Micro-Light.Fighter.zip)

**Comment by tsunamayo** [comment]
I like it! Thanks ;)

**Comment by nokturnihs** [comment]
Do you want me to repost the hoverbike and the other ship I sent your way here? Put them in the backer github...
