### ISSUE TITLE
[Bug] Loss of quality of black markings/decals on black paint.

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#2135]
![image](https://user-images.githubusercontent.com/63756057/82715887-f5b73300-9c8c-11ea-80f0-82178ef11931.png)
1. Build some bricks and paint them black
2. Cover a part of them in silver markings/decals
3. Apply black decals to cover up some of the silver markings.

The texture looks off compared to un-marked brick texture, very pixelated.

It's possible that this problem applies to any given colour combination.

**Comment by tsunamayo** [comment]
Fixed for 20w29d. Thanks!
