### ISSUE TITLE
[Suggestion] Unspawn button confirmation 

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#2136]
Right now it's possible to instantly delete your ship by hitting Unspawn in the codex menu, which could be very unfortunate if you haven't exported it as a blueprint. Just to save some pain for curious new players, a popup saying something like "Warning! This removes the entity. Make sure to Export the blueprint before proceeding"
and then a "Cancel" and "Unspawn" button.

**Comment by tsunamayo** [comment]
Implemented in 20w40c! Thanks
