### ISSUE TITLE
[Bug] Entering seat/yoke on a building on the ringworld locks character [20w21c]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#2137]
### Short Description of the issue:
One of our new players, GlitchyGirl, found this issue: while building a hovercraft, the starter block ended up accidentally being placed on the surface of the torus, making the hovercraft a building. When the player enters the seat or yoke (not sure which), this causes the character to become completely locked up; the player model is gone, and the player cannot move. Using the F10 camera causes the multitool to float around without any player. This state persists after saving & reloading, requiring a new character to be created.

### Steps to reproduce the issue:
The player that found this gave me permission to include their savegame file, so you can see this for yourself:
[GlitchyGirl_char.zip](https://github.com/tsunamayo/Starship-EVO/files/4671007/GlitchyGirl_char.zip)

### Environment
- Starship EVO version: 20w21c
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
This bug apparently creates a huge output_log file, which I have had to zip to fit here.

[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/4671012/output_log.zip)

**Comment by Dwarf-LordPangolin** [comment]
Update: this can be duplicated easily by placing a starter block on the ringworld's terrain, then adding a ship core, yoke, and reactor to it, then entering the yoke. The character will freeze and be unable to do anything. On saving, quitting, and reloading, the character will still be locked up, and the multitool will be visibly floating.

**Comment by tsunamayo** [comment]
Yes indeed this was easily reproducible. Issue fixed for 20w21d. Thanks!
