### ISSUE TITLE
[Bug] Quit/Reload issue

### ISSUE THREAD

**Issue by AlienXtream** [tsunamayo/Starship-EVO#2139]
### Short Description of the issue:

a lot happened all at once. the major thing is several problems after quitting and reloading the save. i have a video of the event(s). the video also contains several more minor bugs and oddities that need addressing but are not a priority

### Steps to reproduce the issue:

quit save and reload.

### Environment
- Starship EVO version: latest steam build as of posting date. specific version in video
- Graphics Card: not relevant

### Additional information:
https://youtu.be/Muqvg_cZONc?t=929 <- video.
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4671082/output_log.txt)

**Comment by SpuzzBunn** [comment]
I got the same issue.

**Comment by tsunamayo** [comment]
I see, thanks for reporting the bug!

**Comment by tsunamayo** [comment]
It was the same issue as #2139. Issue will be fixed for 20w20d. Thanks!
