### ISSUE TITLE
world disappeared because of a turret glitch

### ISSUE THREAD

**Issue by Xenoprophet-Nail** [tsunamayo/Starship-EVO#2140]
### Short Description of the issue:
I constructed a turret I had on a ship that suffered a lost child entities glitch on a testbed platform I had. Well when I went to test it it's barrel glitched into it's body and caused it to get stuck, I deleted the hinges that were tied to it and the head of one remained, as did the weapon, I deleted the weapon and placed another hinge thinking that the head would disappear when I placed it. It was still there so I removed the rotator, the torus disappeared and all i saw were stars and everything was under the effect of a black light, in this mode I saw no child entities.. it makes me wonder if my ship got saved in that state causing all the stuff to be missing.. 
...

### Steps to reproduce the issue:
make a small turret and without a camera look around, if it gets stuck in the rotator then you have the start of the glitch. I use a thin tile for the base place the turret core on that and I have a 2 to 1 piece behind that I put a hinge on that and a block, at the right angle (hinge still at 90 degrees) I mounted a small beam weapon 1 in length from there I put two hinges on the top of the block and proceeded to make a shroud for the turret, one that would raise and lower
...

### Environment
- Starship EVO version: 20w21c
- Graphics Card: Nvidia GeForce 1060 6gb ram

### Additional information:
![20200522232503_1](https://user-images.githubusercontent.com/51257864/82721416-ef27bc00-9c8a-11ea-9d34-2cee4e96006e.jpg)
![20200522234015_1](https://user-images.githubusercontent.com/51257864/82721420-f4850680-9c8a-11ea-875c-9839296b31ae.jpg)

[Animated test platform 01.zip](https://github.com/tsunamayo/Starship-EVO/files/4671127/Animated.test.platform.01.zip)  be careful I was too scared that the glitch would replicate itself so I may not have set the rotator or the main hinge correctly

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
I had to relog to see if everything was okay considering I was playing with a friend at the time

**Comment by Xenoprophet-Nail** [comment]
this is I guess where I first encountered the but, though without the missing world issue, all my child entities were removed. Spawning this in it'll be invisible until you place blocks all around the exterior, you'll note the rotators are there but missing their head and the turrets attached, perhaps spawning this in will cause the issue to rear it's head faster if it is a hard thing to replicate 
[DSE Craft 01.zip](https://github.com/tsunamayo/Starship-EVO/files/4672360/DSE.Craft.01.zip)

**Comment by tsunamayo** [comment]
@Xenoprophet-Nail thanks a lot for the blueprint. Issue is fixed for 20w21d, you will be able to load you ship in next patch. Thanks!
