### ISSUE TITLE
Question: Query Gate

### ISSUE THREAD

**Issue by JRL101** [tsunamayo/Starship-EVO#2141]
### Short Description of the issue:

Im trying to understand how this works, but its confusing me, how do i check a status of a joint, then choose the reaction for an output signal?

so have a rotor, and i want a piston to extend when the rotors finished and before it starts in reverse

I understand the max min is just telling me what the thing connected is capable of, but is the integer the value its looking for to activate? 
and whats inferiour and superior? 
![image](https://user-images.githubusercontent.com/33255536/82721628-6ee87180-9cf1-11ea-9d06-a25096593715.png)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
So the query will trigger once the condition is realized:
Say your condition is > 70deg.
When the rotator is at 0 deg the query gate is at Off.
Then once the rotator move over 70deg, the query gate toggle its state at On.
Then if goes below 70deg again, query goes back to Off.
That's it!
