### ISSUE TITLE
I can't reach your forum page

### ISSUE THREAD

**Issue by cssi-dev** [tsunamayo/Starship-EVO#2142]
### Short Description of the issue:
when i try to reach your forum page (https://forum.skywanderersgame.com/) i recive a DNS_PROBE_FINISHED_NXDOMAIN error. I am not sure if the Problem is just when you connect from Austria to it or globally.
...

### Steps to reproduce the issue:
Open your Forum page.(or open it from Austria)
...

### Environment
- Webbrowser Version:68.0.3618.125
Update stream:Stable
System:Windows 10 64-bit (WoW64)

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
yes we unplugged it, we were not using it. We are using that github instead. The forum tech was really slow... Thanks
