### ISSUE TITLE
[Suggestion] Indication of orientation for hinges and rotators

### ISSUE THREAD

**Issue by esauftgz** [tsunamayo/Starship-EVO#2143]
When building a craft with many hinges and rotators, it is hard to tell what orientation they are (which is especially annoying when trying to hook up many hinges/rotators to one sequencer).

I would recommend showing the orientation by indicating where 0 degrees and the turning direction is on the preview for hinges and rotators before you put them down, similarly to how hover thrusters indicate the downwards direction.

**Comment by tsunamayo** [comment]
Yes it was on the to-do list. Thanks for the suggestion!

**Comment by tsunamayo** [comment]
It was added a while back. Thanks
