### ISSUE TITLE
[Bug] inconsistent hinge hit detection

### ISSUE THREAD

**Issue by AlienXtream** [tsunamayo/Starship-EVO#2144]
### Short Description of the issue:

inconsistency between stretched small tile and non stretched small tiles of same length
### Steps to reproduce the issue:

hinge folding to 90deg at same length as cutout in a wall. if using single small (cube) tiles, hinge door closes. if using stretched small (cube) tiles, hinge door does not. all other tested stretch types worked as expected.

see video for details

### Environment
- Starship EVO version: 20w21c
- Graphics Card: N/A

### Additional information:
https://youtu.be/cF6GPA0JlUE

**Comment by tsunamayo** [comment]
Okay nice find. Could you send me your blueprint? Thanks

**Comment by AlienXtream** [comment]
[Hinge hit-detection bug.zip](https://github.com/tsunamayo/Starship-EVO/files/4672749/Hinge.hit-detection.bug.zip)

**Comment by tsunamayo** [comment]
Okay I had a look at it, unfortunately it is not really an bug in the sense that the correct behaviour would be to not close. I add a little bit of margin so things dont get stuck too easily, and it happened that the non stretched block falls below that margin wereas the larger one dont. But if it were in real life this mechanism would not close...
Thanks
