### ISSUE TITLE
Spaceship hopping with 3 point landing gear

### ISSUE THREAD

**Issue by Servomotor** [tsunamayo/Starship-EVO#2146]
Made first ship tonight. Put 3 landing gear under it with hinges. 2 in the back, 1 in front. I went to land on the ground and it started hopping on the front landing gear. 

[Servo S-1.zip](https://github.com/tsunamayo/Starship-EVO/files/4672934/Servo.S-1.zip)

EDIT: I wonder if it has to do with the degree of the hinge being different in the front landing gear vs the rear landing gear, or the fact that they are most likely not leveled (to make the ship sit level).
...

Not sure. Land ship on ground. 

...

### Environment
20w21c
RTX-2080

### Additional information:
10 second video
https://www.youtube.com/watch?v=-LqDKy1LcE0

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Okay, amazing music ;) Can you send me your blueprint so I can investigate? Thanks

**Comment by Servomotor** [comment]
I know you work hard and are very busy. I am new so forgive me, but how or where should I send the blueprint.

**Comment by captain828** [comment]
You can find your blueprints under:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints`

You then need to zip it and then drag & drop it here.

**Comment by TripleHelixxx** [comment]
My ship always seems to do this as well. It has 4 landing gear though. Whenever I try to land on anything but an official docking pad, the ship won’t stop bouncing and clanging. Even when it seems to have settled down, whenever you try to walk around in the ship it starts up again.

**Comment by captain828** [comment]
Same here actually with landing gear on rails.

**Comment by Servomotor** [comment]
Thank you all. @tsunamayo Attached is the ship that was bouncing. 

[Servo S-1.zip](https://github.com/tsunamayo/Starship-EVO/files/4672759/Servo.S-1.zip)

**Comment by tsunamayo** [comment]
@Servomotor It seems to be fixed in recent updates. Thanks
