### ISSUE TITLE
Labeling mistake in the tutorial

### ISSUE THREAD

**Issue by i-Likeyogurt** [tsunamayo/Starship-EVO#2150]
### Short Description of the issue: the first section of the tutorial tells the player [R] is used to rotate blocks when [E] and [Q] are the actual keys used
 edit checked earlier issues, youve already seen this
...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 20w21c
- Graphics Card: radeon rx560x

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Fixed for 20w21d. Thanks!
