### ISSUE TITLE
clash between controls for rotating in 6dof locomotion mode

### ISSUE THREAD

**Issue by i-Likeyogurt** [tsunamayo/Starship-EVO#2151]
### Short Description of the issue: When building in 6dof, the keys [Q] and [E] are used to rotate the player, and blocks so when building in it the player rotates, i know this is a simple fix with changing locomotion but its just something id like to make a note of, its not a major issue

...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 20w21c
- Graphics Card: radeon rx560x

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Yes default setting should be rotate with R. Thanks for booking all the cases!

**Comment by tsunamayo** [comment]
Fixed for 20w21d. Thanks!
