### ISSUE TITLE
Suggestion - ignore this one

### ISSUE THREAD

**Issue by i-Likeyogurt** [tsunamayo/Starship-EVO#2152]
### Short Description of the issue: edit no ships are fine, but landings always feel to hard, if there was an option to control ship speed or power output manually that might be good
...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
I add a gate that will make this possible. Thanks
