### ISSUE TITLE
the old cushion tile that you could sit on and use to make custom seats was cool, itd be nice to see it return

### ISSUE THREAD

**Issue by i-Likeyogurt** [tsunamayo/Starship-EVO#2153]
### Short Description of the issue: Like the title says, that flat cushion tile you could sit on was cool because you could make really custom seats, just wondering if it will return
...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by Sullos** [comment]
We actually already have a resizeable version of that in-game already. 
You could never actually sit on the old ones in the game, they were just there as the actual seat cushioning for the blank chair canvas. We have 3 or so different chair options, one of which is customizable. Perhaps you missed these?

**Comment by tsunamayo** [comment]
Maybe it was about the one where we sleep on? There is another suggestion on different stance chair. Thanks
