### ISSUE TITLE
Suggestion - make buttons and switches able to be interacted with while sitting in a chair

### ISSUE THREAD

**Issue by i-Likeyogurt** [tsunamayo/Starship-EVO#2154]
### Short Description of the issue: itd be really cool if you could flip buttons and switches while sitting in a chair, i dont know if that actually is in the game but i couldnt get it to work

...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by Majikmonster** [comment]
You **can** activate buttons/switches while seated, even while piloting. At least, that's how it's supposed to work. (the buttons/switches have to be linked to something to work at all)
