### ISSUE TITLE
nevermind that, i just didnt know what i was doing

### ISSUE THREAD

**Issue by i-Likeyogurt** [tsunamayo/Starship-EVO#2155]
### Short Description of the issue: if we could interact with switches while sitting in a seat it would be cool this might be in the game but i cant do it so that might be a bug too
...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by Majikmonster** [comment]
Go ahead and close the ticket if it is no longer an active issue.

**Comment by i-Likeyogurt** [comment]
will do, sorry dont know how to use the game or github yet thanks
