### ISSUE TITLE
Ship inventory and cargo suggestion

### ISSUE THREAD

**Issue by i-Likeyogurt** [tsunamayo/Starship-EVO#2156]
### Short Description of the issue: A system similar to sea of thieves and star base would be cool, it would add a a reason to build large cargo bays, if you had to physically move large containers around, maybe cargo crates could have items put in them and then you physically move the cargo crates with a forklift or robot arm or a grav gun tool like the one from half life

...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by Majikmonster** [comment]
The official discussion about this is in post #2116 .

**Comment by tsunamayo** [comment]
Yes dwarf had an idea like this, if you could contribute to the original post that would be great!
