### ISSUE TITLE
Turret still controlled after exiting yoke

### ISSUE THREAD

**Issue by orangep9** [tsunamayo/Starship-EVO#2162]
### Short Description of the issue:
Once I exit the yoke connected to my turret it still rotates with my camera.
...

### Steps to reproduce the issue:
Just a basic turret config as far as I can tell. Video included
...

### Environment
- Starship EVO version: 20W21C
- Graphics Card: RTX 2070 Super

### Additional information:

Video in the ZIP file.

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4672699/output_log.txt)
[Starship_Evo_Issue.zip](https://github.com/tsunamayo/Starship-EVO/files/4672704/Starship_Evo_Issue.zip)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by orangep9** [comment]
Update: Only happens if the grid is attached to the ringworld.

**Comment by tsunamayo** [comment]
Thanks a lot for the video! I cant reproduce the issue, so you could send me your world file that would be great. Zip the full:
%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Characters\[YOUR CHARACTER NAME]
Thanks!

**Comment by orangep9** [comment]
I can't reproduce it any more ether it seems like you may have accidentally fix it.

**Comment by tsunamayo** [comment]
Okay it was maybe another issue then. Thanks
