### ISSUE TITLE
Game locks up when entering yoke for big/detailed ships

### ISSUE THREAD

**Issue by i-Likeyogurt** [tsunamayo/Starship-EVO#2163]
### Short Description of the issue: the game completley lock up when i enter the yoke of ships like the ursula class fighter and primaris repluser in the skyware, cant lok around, cant control ship, nothing happens, can enter nocllip f10 and access option menu, but cant do anything else, have to delete the world because still stuck in ship when reloading

...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 20w21c
- Graphics Card: radeon rx560x

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Could you send me the blueprint? Thanks

**Comment by tsunamayo** [comment]
Never mind I found the blueprint. - but I dont have any issue. Could you send me the output.log so I can investigate? Thanks

**Comment by ItsCrusade** [comment]
Additional information;

This may be a CPU issue - I'm running an i7-2600, a fairly old CPU.

When I attempt to pilot large/complicated ships while close to the ring (in gravity), my game will lock up for up to 40 seconds as it 'initializes' the entity I'm taking control of. 

I suspect this might be a physics engine issue.

**Comment by tsunamayo** [comment]
yes collision near the terrain will be laggy - still wip. I just want to know if there is an issue though, as having the engine write down issues in the log also cause lags.

**Comment by i-Likeyogurt** [comment]
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4673352/output_log.txt)

thats it there, if the log doesnt show the event (just done some hard drive cleaning) i can recreate it, i have a ryzen 5 cpu, so it may be a cpu thing, it happens with most large ships from the warehouse and it was on the terrain

**Comment by tsunamayo** [comment]
What I am not sure to understand is the part were the games lock up and you need to delete your save. Bad performance should not do that. If you could take a screenshot with the FPS (press F3, then - Show FPS stats) enabled that would be great.
