### ISSUE TITLE
Vertical Axis Sticker Mirror Incorrect

### ISSUE THREAD

**Issue by ItsCrusade** [tsunamayo/Starship-EVO#2170]
### Short Description of the issue:
When mirroring on a vertical surface, the mirrored sticker   will have incorrect rotation
...

### Steps to reproduce the issue:
Build a vertical wall, enable symmetry, and try to apply a triangle/non-symmetrical sticker onto one side. The other side will have the wrong orientation.
...

### Environment
- Starship EVO version: 20w21c
- Graphics Card: 1070ti
### Additional information:

![Starship_EVO_2020-05-24_16-33-40](https://user-images.githubusercontent.com/64144395/82747500-b566ca80-9ddc-11ea-946f-b061eae89240.jpg)
![Starship_EVO_2020-05-24_16-33-48](https://user-images.githubusercontent.com/64144395/82747501-b861bb00-9ddc-11ea-9143-7cb059650eb7.jpg)

**Comment by tsunamayo** [comment]
@ItsCrusade Hi, it is fixed in recent updates.
