### ISSUE TITLE
mis-spelling

### ISSUE THREAD

**Issue by T00Code34215** [tsunamayo/Starship-EVO#2171]
### Short Description of the issue:
Codex has written flora as flaura
... As far as can tell universal

### Steps to reproduce the issue:
Open codex.
...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by AlienXtream** [comment]
yeh there are a few translation issues as tsuna is a native french speaker afaik. for now it gets the message across well enough that its not a priority. we will collectively work on translations closer to survival mode i would imagine.

**Comment by T00Code34215** [comment]
that is what i had suspected. It is not major anyway - i am pretty sure most people will breeze over it

**Comment by AlienXtream** [comment]
indeed. do make mental note of them anyway. might be worth tsuna adding a separate tag for "spelling" or "translation" errors so that reporting them now they can still be found and crossed off later.

**Comment by tsunamayo** [comment]
No problem guys, book as many mis-spelling as you find! Community already helped fixed a lot of them. This one is fixed. Thanks
