### ISSUE TITLE
[Suggestion] welder/plasma tool

### ISSUE THREAD

**Issue by AlienXtream** [tsunamayo/Starship-EVO#2174]
tool to allow removing or adding bevel seems between stretched small tiles (similar to how large tiles render) as well as editing existing stretch blocks by "cutting" them into smaller parts. not 100% sure on how exactly this would work but its a suggestion and it could be useful in some niech cases

**Comment by i-Likeyogurt** [comment]
yeah i like this, but i think it should be a plasma tool, a welding tool like the one in scrap mechanic could be another thing

**Comment by tsunamayo** [comment]
So not likely unfortunately:
1) this is not possible in the current tech as the voxel grid is 1m. The small bricks dont comply to the voxel grid, so they cant know whats near them.
2) This also I am not sure to understand really there is two case:
 - You want to create a shape only possible by splitting. => not possible engine wise
 - You want to go faster than deleting the brick and placing two bricks => not really useful, I mean a little bit but I dont want to spend time and add complexity for this.
Thanks!

**Comment by AlienXtream** [comment]
fair enough
