### ISSUE TITLE
[suggestion] a small block just like the glass tetra but as a metal brick

### ISSUE THREAD

**Issue by i-Likeyogurt** [tsunamayo/Starship-EVO#2177]
### Short Description of the issue: Trying to build a tie fighter in an octagon shape, and need a block just like the glass tetra but metal, basically imagine the metal block with the triangular slice out of it, but it was a flat panel, like the glass tetra

...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by MRonlin** [comment]
Don't we already have a tetra block
![20200525121802_1](https://user-images.githubusercontent.com/64201628/82808476-f95fdb00-9e81-11ea-83e6-bce182ffcff6.jpg)

**Comment by Servomotor** [comment]
@MRonlin The Glass Tetra is flat on the opposite side. When you scale it, it scales with both sides being flat. The regular block does not. We also need the glass 45 degree angle as a metal brick.

**Comment by tsunamayo** [comment]
Hi, you have now both block in the game. thx
