### ISSUE TITLE
[Bug within a bug?] Invisible ship.

### ISSUE THREAD

**Issue by MRonlin** [tsunamayo/Starship-EVO#2178]
### Short Description of the issue:
Half of ship disappearing. 
...

### Steps to reproduce the issue:
I was experiencing the backwards turret bug and when I deleted the main horizontal rotor all the ships paint and decals disappeared and half of the ship went invisible, I was however still able to interact with the invisible blocks.

However when I reloaded the game it fixed itself.

...

### Environment
- Starship EVO version: 20w21c
- Graphics Card: Gtx 1050

### Additional information:
What the bug looks like:
![20200524133158_1](https://user-images.githubusercontent.com/64201628/82754371-63b24600-9dc4-11ea-8d12-b8d5114fa685.jpg)
What the ship is supposed to look like:
![20200524134440_1](https://user-images.githubusercontent.com/64201628/82754456-e5a26f00-9dc4-11ea-8e3e-d2a7b5de50ab.jpg)

_(Screenshots, Videos, Error logs, Related issues)_
The output file:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4673524/output_log.txt)

**Comment by tsunamayo** [comment]
okay this is weird - could you please send me the blueprint?
I hope you like the game - thanks for backing ;)

**Comment by MRonlin** [comment]
@tsunamayo 
Love the game, I already poured so many hours into it :).
Here is the blueprint: https://www.skywa.re/blueprint/srf-23-fighter
