### ISSUE TITLE
first person camera hight incorrect

### ISSUE THREAD

**Issue by darkvoid305** [tsunamayo/Starship-EVO#2181]
### Short Description of the issue: the camera position in first person mode doesn`t align with the position of the head in third person mode wich will make it confusing how high you ceiling needs to be if your building in first person if your in first peron mode you will built the ceiling to low and if you then go into third person your head will be clipping in the ceiling

...

### Steps to reproduce the issue: standard there

...

### Environment
- Starship EVO version: pre alpha 20w 21c
- Graphics Card: 

### Additional information: 

_(Screenshots, Videos, Error logs, Related issues)_
![problem picture 2](https://user-images.githubusercontent.com/44634108/82758024-51e09b00-9de4-11ea-9fa0-949124099934.png)
![problem](https://user-images.githubusercontent.com/44634108/82758029-5907a900-9de4-11ea-9d01-2a02a5d2f10c.png)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Indeed, I will fix this. Thanks

**Comment by tsunamayo** [comment]
Fixed in recent updates. Cheers
