### ISSUE TITLE
[Bug] Deleting hinge makes ship invisible [20w21c] 

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#2182]
### Short Description of the issue:
I was trying to redo some turrets on my fighter, but deleting the hinge did not delete the stuff attached to it.

### Steps to reproduce the issue:
I don't know what caused this to happen in the first place, but I'm including both the blueprint of the ship this has happened on, and the world too:

[Dwarf-Lord Pangolin.zip](https://github.com/tsunamayo/Starship-EVO/files/4674506/Dwarf-Lord.Pangolin.zip)

[Hammerhead Heavy Fighter.zip](https://github.com/tsunamayo/Starship-EVO/files/4674507/Hammerhead.Heavy.Fighter.zip)

### Environment
- Starship EVO version: 20w21c
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
This is after deleting the hinge; note the floating hinge part and things connected to it:
![20200524170242_1](https://user-images.githubusercontent.com/33041786/82765993-df21f080-9de0-11ea-960e-9b5234a6ce07.jpg)

Save/reloading shows that the ship has gone invisible, but is still there; blocks under the crosshair are outlined:
![20200524170326_1](https://user-images.githubusercontent.com/33041786/82766008-f82aa180-9de0-11ea-9305-31720e075e10.jpg)

Placing a block reveals part of the ship:
![20200524170329_1](https://user-images.githubusercontent.com/33041786/82766018-1f816e80-9de1-11ea-9378-243f9a689a85.jpg)

However, other parts are still invisible, and require placing more blocks to reveal them:
![20200524170339_1](https://user-images.githubusercontent.com/33041786/82766019-21e3c880-9de1-11ea-94ca-ba7a8fb84cdf.jpg)

All of the child entities appear to have disappeared:
![20200524170420_1](https://user-images.githubusercontent.com/33041786/82766100-b64e2b00-9de1-11ea-993c-4cb8b0be5700.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4674510/output_log.txt)

**Comment by Dwarf-LordPangolin** [comment]
Update: I loaded into the world a third time, and it's all back, and the hinges I'd originally deleted are gone; however, deleting more hinges results in the same failure to delete the attached bits:
![20200524171633_1](https://user-images.githubusercontent.com/33041786/82766219-d03c3d80-9de2-11ea-8a92-a603578ba19c.jpg)

Saving and reloading started the whole cycle over again, with the ship once more invisible:
![20200524172131_1](https://user-images.githubusercontent.com/33041786/82766246-1d201400-9de3-11ea-9a6d-72e382a2e2c5.jpg)

Saving and reloading after that, the ship is once more visible:
![20200524172319_1](https://user-images.githubusercontent.com/33041786/82766275-4d67b280-9de3-11ea-8767-4c479a58125e.jpg)

I'm assuming this cycle continues as long as there are hinges or other moving parts to delete.

**Comment by tsunamayo** [comment]
Okay let me check this.

**Comment by tsunamayo** [comment]
Issue fixed for 20w22a. Thanks!
