### ISSUE TITLE
[BUILD] NIE Blackbox MicroLight 

### ISSUE THREAD

**Issue by nokturnihs** [tsunamayo/Starship-EVO#2187]
Welcome to another Fantastic Nox Imperium Enterprises Model Premier!

Cargo and Docking Bay space is always at a premium and we introduced a compact Hoverbike in the NIE GoldBox (https://github.com/tsunamayo/Starship-EVO-Backers-Ships/issues/19) - But that might not meet the needs of the tasteful in the market for small personal craft, thus we introduce:

The NIE BlackBox MicroLight

When in storage configuration this small spacecraft takes a mere 3x3x5 meters of storage space! Don't worry though, it's not nearly so cramped in flight configuration! Featuring twice the shield capacity of it's hoverbike counterpart, full light-cruise capabilities and of course the NIE aesthetic you've come to expect, this craft will serve the needs of short trips across a planet or solar system, and even has a quad-beam array to take care of small barriers or hostile natives! 

Order now wherever Nox Imperium is sold!
[NIE BlackBox Micro-Light.zip](https://github.com/tsunamayo/Starship-EVO/files/4676441/NIE.BlackBox.Micro-Light.zip)
![20200525031918_1](https://user-images.githubusercontent.com/7344403/82800676-4ec3ca00-9e39-11ea-8329-c03464000142.jpg)
![20200525031909_1](https://user-images.githubusercontent.com/7344403/82800678-4ff4f700-9e39-11ea-9169-30882000452e.jpg)
![20200525031827_1](https://user-images.githubusercontent.com/7344403/82800680-4ff4f700-9e39-11ea-9521-c77d08a6812d.jpg)
![20200525031700_1](https://user-images.githubusercontent.com/7344403/82800681-4ff4f700-9e39-11ea-8bab-b11d2a610ba1.jpg)
![20200525031652_1](https://user-images.githubusercontent.com/7344403/82800683-508d8d80-9e39-11ea-9ec3-5f14bda940c4.jpg)
![20200525031628_1](https://user-images.githubusercontent.com/7344403/82800684-508d8d80-9e39-11ea-896f-e8cc017bf15c.jpg)
![20200525031616_1](https://user-images.githubusercontent.com/7344403/82800687-508d8d80-9e39-11ea-8a08-3f6f23c73c43.jpg)
![20200525031611_1](https://user-images.githubusercontent.com/7344403/82800688-51262400-9e39-11ea-9794-007ec1120b3f.jpg)
![20200525031602_1](https://user-images.githubusercontent.com/7344403/82800690-51262400-9e39-11ea-9c88-26b6d9b3f367.jpg)
![20200525031559_1](https://user-images.githubusercontent.com/7344403/82800691-51beba80-9e39-11ea-9c51-00cae604c112.jpg)
![20200525031554_1](https://user-images.githubusercontent.com/7344403/82800693-51beba80-9e39-11ea-919b-5e93e4469103.jpg)
![20200525031545_1](https://user-images.githubusercontent.com/7344403/82800694-52575100-9e39-11ea-93bd-0e5f3c61b4a2.jpg)
![20200525031539_1](https://user-images.githubusercontent.com/7344403/82800695-52575100-9e39-11ea-897f-e01e229febbd.jpg)
![20200525031535_1](https://user-images.githubusercontent.com/7344403/82800698-52575100-9e39-11ea-9927-1d4bd2a788f7.jpg)
![20200525031531_1](https://user-images.githubusercontent.com/7344403/82800699-52575100-9e39-11ea-82dc-f87c8e0d460a.jpg)

About Nox Imperium Enterprises:
After leaving their home planet and disappearing for hundreds of years into the unknown, Nox Imperium Enterprises, a theocratic corporation returned to the known regions of space to provide luxury craft catering to the powerful, wealthy or vain. Their craft are known for their split-hull configurations and their audacious black, gold, silver and royal purple detailing.

**Comment by tsunamayo** [comment]
Thats quite a bold shape, thanks! I dont know if you could move it over to the Backers Ship (even if it is not a backers reward), I need to catch-up over there btw... You are on fire lately, Cheers
