### ISSUE TITLE
[Bug] Laser sensor's range not updating [20w21c]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#2192]
### Short Description of the issue:
The laser sensor does not seem to update its range when a longer range is entered.

### Steps to reproduce the issue:
Place a laser sensor, link it to systems, increase the range, then try to trigger it at the newer, longer range.

### Environment
- Starship EVO version: 20w21c
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4678646/output_log.txt)

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Fixed for 22w45a. Cheers
