### ISSUE TITLE
[Bug] Deleting triggered laser sensor leaves linked logic stuck "on" [20w21c]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#2193]
### Short Description of the issue:
Deleting a laser sensor while it's triggering linked logic leaves those things stuck "on" as if they were still receiving a signal from it.

### Steps to reproduce the issue:
Link a laser sensor to something, then move into the sensor's range. While the linked logic is being triggered, delete the laser sensor; the thing in question will keep acting as if the sensor is still triggering it until new logic is linked to it telling it to stop.

### Environment
- Starship EVO version: 20w21c
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4678680/output_log.txt)

**Comment by tsunamayo** [comment]
Issue fixed for 20w22b. Thanks!
