### ISSUE TITLE
[Bug]Invisible blocks[20w21c]

### ISSUE THREAD

**Issue by MRonlin** [tsunamayo/Starship-EVO#2194]
### Short Description of the issue:
Blocks become invisible when placed.
...

### Steps to reproduce the issue:
This may be system related (performance din't dip during or up to this bug though), however I found that It only happened when building on large ships. There are no child entities on this ship, it is not near the ring or the asteroid belt, there are a few small ships it is near to which do have child entities. 

...

### Environment
- Starship EVO version: 20w21c
- Graphics Card: gtx 1050

### Additional information:
![20200525211442_1](https://user-images.githubusercontent.com/64201628/82841340-96943100-9ecd-11ea-86b4-37b53b6af554.jpg)

_(Screenshots, Videos, Error logs, Related issues)_

You can find the log here: 
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4678730/output_log.txt)

**Comment by tsunamayo** [comment]
It stays always invisible or does it takes time to show up? Thanks

**Comment by MRonlin** [comment]
It stays invisible, however when I reload the game it shows up.

**Comment by Dwarf-LordPangolin** [comment]
I've also encountered this bug or a related one; the blocks eventually appear, but only after a delay. The ship in question is also a large one; it doesn't have a lot of blocks, but it's 200m long.

**Comment by thecosmonaut4** [comment]
I am also getting this bug, seems to start after an extended session of building a large (500m) ship. Newly placed blocks will be invisible (sometimes they turn visible after a bit). Reloading the game makes all blocks visible. I suspect this is a memory or garbage collection issue?
