### ISSUE TITLE
[Visual Bug?] When deleting a brick in symmetry

### ISSUE THREAD

**Issue by MRonlin** [tsunamayo/Starship-EVO#2195]
### Short Description of the issue:
A black brick is left behind for a short period after deleting a brick in symmetry mode. This brick disappears shortly after. Nothing is painted.
...

### Steps to reproduce the issue:
This appears to occur when using symmetry on large builds 250m+. 

...

### Environment
- Starship EVO version: 20w21c
- Graphics Card: gtx 1050

### Additional information:
![20200525221531_1](https://user-images.githubusercontent.com/64201628/82844102-1c68aa00-9ed7-11ea-8632-e72675baac61.jpg)

_(Screenshots, Videos, Error logs, Related issues)_

You can find the log here: 
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4678883/output_log.txt)

**Comment by tsunamayo** [comment]
Yes this is a performance related issue on large build. I will update the technology and this should no longer happens. Thanks!

**Comment by MRonlin** [comment]
Ok :)
