### ISSUE TITLE
[Suggestion] Increase stretch limit

### ISSUE THREAD

**Issue by MRonlin** [tsunamayo/Starship-EVO#2196]
Currently the max you can stretch a block is 16, I think it would make building easier if this was increased, or if It allowed the player to enter a value for the stretch. This would not apply to systems (Thursters, reactors, etc..)

**Comment by tsunamayo** [comment]
Yes I can understand the request, unfortunately it is a hard limit linked to the way the data is stored. It also has impact on performance when building. So I cant change it, sorry! ;)
