### ISSUE TITLE
[Bug] Can't move and hotbars blank

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#2199]
### Short Description of the issue:
Just updated to test out the new handheld weapons, and I can't move in any locomotion mode and my hotbars have been wiped. I've included my savedata if it doesn't happen with your character.

### Steps to reproduce the issue:
Update the game, load an old character

### Environment
- Starship EVO version: 20w22a
- Graphics Card: RX 580

### Additional information:
[Save_Data - ProPeach.zip](https://github.com/tsunamayo/Starship-EVO/files/4679361/Save_Data.-.ProPeach.zip)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4679364/output_log.txt)

**Comment by ProPeach** [comment]
Looks like the same issue happens with a new character. I can move up and down, but not forwards/back/left/right. I checked the keybinds and they're fine too

**Comment by tsunamayo** [comment]
It was linked to having the guy skin - I am pushing a new build now!

**Comment by ProPeach** [comment]
Brilliant!
