### ISSUE TITLE
[Bug] Camera mode resets locomotion mode

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#2200]
### Short Description of the issue:
When you hit F6 to exit camera mode, your locomotion mode is reset to "None"

Side note, the GUI in the camera mode is a great feature. It's easy to think the game is bugged without knowing what you've done by pressing F6

### Steps to reproduce the issue:
Fly into the air with the jetpack mode
Hit F6 
Hit F6 again to exit camera mode

### Environment
- Starship EVO version: 20w22a
- Graphics Card: RX580

**Comment by ProPeach** [comment]
This also resets the player speed

**Comment by tsunamayo** [comment]
Issue was fixed a few update ago! Thanks
