### ISSUE TITLE
[Bug] New characters cannot move [20w22a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#2201]
### Short Description of the issue:
I created a new character for the current patch, and the character cannot move with WASD or up and down in any mode; the only type of movement possible is jumping when standing.

### Steps to reproduce the issue:
Create new character, try to move.

### Environment
- Starship EVO version: 20w22a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4679458/output_log.txt)

**Comment by Dwarf-LordPangolin** [comment]
Update: a workaround for this is to add a block to the hotbar; this will enable movement.

**Comment by tsunamayo** [comment]
Fixed for 20w22b. Thanks!
