### ISSUE TITLE
[Bug] Character bounces when standing on surface [20w22a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#2203]
### Short Description of the issue:
When standing on a surface, the character bounces up and down rapidly.

### Steps to reproduce the issue:
Go to the ringworld, and stand on surface.

### Environment
- Starship EVO version: 20w22a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
Short clip demonstrating the problem:
https://gfycat.com/carelessmemorablekomododragon

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4679510/output_log.txt)

PS: the handheld weapon system is amazing! :grinning:

**Comment by tsunamayo** [comment]
Yes it seems to be linked to being close the the weapon...

**Comment by tsunamayo** [comment]
Issue fixed for 20w22c. Thanks!
