### ISSUE TITLE
Items disappearing in hotbar upon reload

### ISSUE THREAD

**Issue by BrickMacklin** [tsunamayo/Starship-EVO#2205]
Everytime I reload a save after exiting all items disappear from the hotbars.

...

Fill hotbars. Exit game. Reload. Items gone.
...

### Environment
- Starship EVO version: 20w22a
- Graphics Card: 2080 Ti

### Additional information:

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4679720/output_log.txt)

**Comment by tsunamayo** [comment]
I dont have this issue - could you please send me your save folder? You can zip entirely. Thanks

**Comment by BrickMacklin** [comment]
Sometimes it loads but most of the time it does not.
[K.zip](https://github.com/tsunamayo/Starship-EVO/files/4682514/K.zip)

**Comment by BrickMacklin** [comment]
@tsunamayo This issue is no longer happening after the latest update. Thanks!

**Comment by tsunamayo** [comment]
@BrickMacklin glad to hear that!
