### ISSUE TITLE
Unable to move on spawn

### ISSUE THREAD

**Issue by hl2shadowslayer** [tsunamayo/Starship-EVO#2208]
### Short Description of the issue:
When you spawn into a world, singleplayer or multiplayer, you cannot walk. You can jump, and you can roll when in 6DOF, but you can't move in any direction. Teleporting may randomly fix this.

...

### Steps to reproduce the issue:
Create a new world
Try to move.
...

### Environment
- Starship EVO version: 20w22a
- Graphics Card: Geforce 750ti

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4680467/output_log.txt)

**Comment by tsunamayo** [comment]
Yes sorry it was a regression with the build on this morning - issue is already fixed, patched 20w22b is coming soon. Thanks
