### ISSUE TITLE
[Bug] Walking in Ringworld gravity (bug reappearance)

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#2212]
### Short Description of the issue:
Looks like #2040 has come back, I still get the stranded in space error when standing still on the Ringworld. This happens much more often if you're tabbed out of the game.
![image](https://user-images.githubusercontent.com/27857711/82912453-0b667a00-9f65-11ea-8d7c-22ec209e62f1.png)
The walking stance also constantly resets when standing still too as per #2040 

### Steps to reproduce the issue:
In "none" locomotion mode, stand still on the Ringworld
Tab out and wait for the error sound if the error didn't show

### Environment
- Starship EVO version: 20222b
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
Tab issue fixed for 20w22c. I keep you posted on the stance bug.

**Comment by tsunamayo** [comment]
Okay both issue fixed for 20w22c. Thanks ;)
