### ISSUE TITLE
[BUG] Selfexploding barrels

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Starship-EVO#2213]
### Short Description of the issue:
since the last updates my ship's weapons explode every time I want to use them

### Steps to reproduce the issue:

build a moveable mounted small weapon on a fighter connect it and try to fire->no problem
than place a rangebarrel on the laser -> the next time you fire the gun will explode

The blueprint worked before. When I dismantle the rangebarrel the weapons dont exlpode.
I tried reloading, reconnecting and rebuilding but I couldnt fix the issue
### Environment
- Starship EVO version: 20w22b
- Graphics Card: gtx1070 mobile

### Additional information:

![Starship EVO_2020_05_26_16_26_36_758](https://user-images.githubusercontent.com/43222403/82912732-b5e29b00-9f6d-11ea-8025-e5a4bc0771d4.jpg)

![Starship EVO_2020_05_26_16_13_16_880](https://user-images.githubusercontent.com/43222403/82911785-98f99800-9f6c-11ea-9c09-0b5a748b870e.jpg)
even if I dismantle two out of three weapons, the remaining one explodes

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4682857/output_log.txt)

[Hyäne 24.zip](https://github.com/tsunamayo/Starship-EVO/files/4682860/Hyane.24.zip)

I would like to add that for a week there has also been a logic bug that has caused our landing gears to stop working, but I suspect that the cause of this issue is the  Bug: #2132 that has already been posted. So don't be surprised what is going on with the landigng gear.

**Comment by tsunamayo** [comment]
Okay I am having a look at both bugs. Thanks

**Comment by Sullos** [comment]
I also noticed this with the gatling barrel. I built a small gatling gun, If I placed 1 gatling brick extension, it was fine, but extending it to anywhere between 2-4 bricks length, the end would be shot off leaving only the closest brick to the tip of the actual laser brick. 
I believe it has something to do with where the laser projectile is spawning. In the case of the 1st brick extension it is safe as the laser projectile spawns just beyond 1 brick from the tip, but any more extensions get shot off as they're in the path of the spawned projectile.
I believe this is a similar issue, if not, I can make a new post.

**Comment by tsunamayo** [comment]
Yeah @Sullos issue is now fixed for 20w22b. Actually projectile should spawn from the tip of the barrel, it was an issue in my raycast check. Thanks!

**Comment by Totheleftofit** [comment]
I don't mean to resurrect a squashed bug, but it seems I'm having this issue again with one of my builds. Has it somehow crept back in? Is any one else experiencing this? It only happens when I fly at normal speed or anything above a crawl. It's like the lasers are moving slower than the ship and end up impacting the turrets.

![20200605180611_1](https://user-images.githubusercontent.com/46333618/83926227-4e8bce80-a757-11ea-96a9-10eee0bbef69.jpg)

![20200605180601_1](https://user-images.githubusercontent.com/46333618/83926234-52b7ec00-a757-11ea-82a5-d8bc4cdf4971.jpg)

**Comment by tsunamayo** [comment]
yes @on-your-left correct, issue was fixed yesterday for 20w23d. Thanks!

**Comment by on-your-left** [comment]
Excellent! I'll wait for the patch to hit and test again. By the way, great job on this game; I'm really liking the building system and aesthetics so far.
