### ISSUE TITLE
Block rotation and rolling occur simultaneously

### ISSUE THREAD

**Issue by dhelonious** [tsunamayo/Starship-EVO#2218]
### Short Description of the issue:

Rotating blocks is mapped to Q and E by default. However, in full 6DOF mode the character rolls every time the block is rotated. This is somewhat annoying.

Right now, a short key press is sufficient to rotate the block once and simultaneously  leads to a small rotation of the player. Maybe this could be resolved if rolling would only start when Q and E are pressed for a longer amount of time.

### Steps to reproduce the issue:

Start the game with default settings, choose full 6DOF locomotion mode and rotate a block using Q and E.

### Environment
- Starship EVO version: 20w22b

**Comment by tsunamayo** [comment]
Okay actually I changed the default keybind for rotating to R. SHIFT-R to rotate backward.
It was a keybind conflict dating from the time were we didnt had 6-dof mode. Thanks!
