### ISSUE TITLE
[Bug?]Extreme lag near ship

### ISSUE THREAD

**Issue by MRonlin** [tsunamayo/Starship-EVO#2219]
### Short Description of the issue:
When building I have no lag (about 75-74 fps), but went I fly a spaceship near my large ship the fps drops to 1 or 2.
...

### Steps to reproduce the issue:
Fly close to a large ship (450m+)

...

### Environment
- Starship EVO version: 20w22b
- Graphics Card: gtx 1050

### Additional information:
This image doesn't show the fps reading, but at this distance it was 1 fps.
![20200526225707_2](https://user-images.githubusercontent.com/64201628/82958485-5f954c80-9fad-11ea-8a2d-ba23cfd34ca2.jpg)
 

You can find the log here: 
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4685427/output_log.txt)
`

**Comment by tsunamayo** [comment]
My god this things is big... But it should not lag if you are using a small ship. So I guess it is a bug - if you can send me your blueprint! Thanks

**Comment by ProPeach** [comment]
I have a similar issue - If I fly a smaller ship into the boundary box of the attached large ship, my framerate drops heavily. Otherwise performance is fine even with the large ship spawned
[Profundity.zip](https://github.com/tsunamayo/Starship-EVO/files/4689327/Profundity.zip)

**Comment by tsunamayo** [comment]
Should be much better in newer versions. Thanks
