### ISSUE TITLE
[Bug] Keybinds Missing

### ISSUE THREAD

**Issue by DestinySilver** [tsunamayo/Starship-EVO#2221]
![emptykeybinds](https://user-images.githubusercontent.com/65915749/82962816-84be9680-9f7e-11ea-9a6f-1025a744303c.jpg)
I opened up keybinds to check if there was an in-game chat, only to find this - the keybinds are completely blank. There is nothing there. I have no idea how this happened or how one might go about recreating this, but the evidence is there.

**Comment by tsunamayo** [comment]
Could you please send me the output.log so I can investigate the evidence ;)
Thanks!

**Comment by DestinySilver** [comment]
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4685848/output_log.txt)
I don't know where in the log the bug occurred. I can't decipher it. Sorry, but you'll have to look through the whole thing.

**Comment by tsunamayo** [comment]
@DestinySilver thanks, no pb thats my job ;). Did it happens right away, or deep into the session? Also was it the first time you opened to control key screen? You have a lot of other error in the log, it might be related.

**Comment by DestinySilver** [comment]
It was pretty deep into the session, but I think it was the third time I opened that screen, or the fourth. I've been experimenting and searching for a ton of bugs, so I can imagine why I have so much error. Anyways, it was I think the second session and pretty deep in when the bug happened.

**Comment by tsunamayo** [comment]
Issue fixed for 20w22d. Thanks!
