### ISSUE TITLE
[Suggestion] Add multiplayer chat.

### ISSUE THREAD

**Issue by DestinySilver** [tsunamayo/Starship-EVO#2222]
Upon my keybinds returning, I realized that there was, in fact, no multiplayer chat function available in the game. It would be very handy if you added a chat system so that players don't have to shift+tab every time they want to say something in multiplayer - and this is assuming that they're playing with steam friends. On a public server, if you need to communicate with someone, you've got problems.

**Comment by tsunamayo** [comment]
Yes multiplayer is low on feature atm. I will close that as there is already a chat suggestion. Thanks
