### ISSUE TITLE
Some more hand weapon issues

### ISSUE THREAD

**Issue by Xenoprophet-Nail** [tsunamayo/Starship-EVO#2225]
### Short Description of the issue:
1, Can not edit logic on a weapon, I had a laser detector tied to a warning block on a sniper rifle, thinking the laser would function as the scope, after the recent patch I can't replicate the weapon design at all.
2, swapping an item with the weapon does not put the item in the display stand, it instead lets you pick up the gun you built removing that from a display stand you may have placed it on elsewhere
3,attach a hinge to a weapon handle and the hinge's size mismatches, so no animated bits on guns.. little extra oddity I made a weapon that looked like I tore a gun off of my turret and it worked until I tried to place the front flat tile, it didn't translate the scale difference correctly also shoved me around comically but I couldn't complain too much

...

### Steps to reproduce the issue:
1, Make a cool weapon and stick the laser detector and a warning block on the weapon, wire them together, not tied to anything else and attempt to enter a message in the warning block, if you can then pick up the weapon, place it back down and try to edit the message. 
2, after that you can place the gun is a new item display and go to the original one and you'll pick it up.. It'll disappear from the item display it was in and be in your hands, placing it back on the original item display will put it in the other one.. 
3, place a hinge onto a weapon handle
...

### Environment
- Starship EVO version: 20w22b
- Graphics Card: Nvidia GeForce Gtx 1060 6gb

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4686298/output_log.txt)

![20200526231546_1](https://user-images.githubusercontent.com/51257864/82974435-ff4fdc00-9fa7-11ea-8f57-a30c9992a865.jpg)
![20200526231549_1](https://user-images.githubusercontent.com/51257864/82974441-01b23600-9fa8-11ea-81d2-c39ff781cda5.jpg)
![20200526022153_1](https://user-images.githubusercontent.com/51257864/82974691-8ef58a80-9fa8-11ea-8f41-b21569d3da7b.jpg)
![20200526013807_1](https://user-images.githubusercontent.com/51257864/82974807-d0863580-9fa8-11ea-9656-746b460bc37a.jpg)

**Comment by tsunamayo** [comment]
All issues fixed for 20w25a. Thanks a lot!
