### ISSUE TITLE
[Suggestion] Ability to nest a new block matrix into an existing grid

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#2230]
![image](https://user-images.githubusercontent.com/63756057/83011594-08759300-a012-11ea-8fcf-137f7f74dd0b.png)
As you can see here, I could move the Starter Block around the brick matrix in 25 cm increments.
I cannot do the same with other blocks.
Once I place the first Starter Block, the block matrix is set in stone and cannot be changed.

Could you implement a solution where we can either:
1. Move all the blocks around in 25cm increments instead of 100cm increments
OR
2. Set a new block matrix by placing a new Starter Block.

**Comment by tsunamayo** [comment]
Sorry I you might guess, the grid is a hard technological limit, the big block have to comply to it. Several elements are voxel based like the light and damage model. So I cant do that! Cheers
