### ISSUE TITLE
[Bug] Character models chasing player?

### ISSUE THREAD

**Issue by MRonlin** [tsunamayo/Starship-EVO#2233]
### Short Description of the issue:
When I went into picture mode (F6) in third person (F4) and then left picture mode, two character models spawned floating about 5-50m away, as I moved they would "follow" my character staying about the same distance away.
...

### Steps to reproduce the issue:
Enter picture mode in third person, leave picture mode.This may have something to do with the large ship, but I don't know.

### Environment
- Starship EVO version: 20w22c
- Graphics Card: gtx 1050

### Additional information:
![20200527162854_1](https://user-images.githubusercontent.com/64201628/83042791-f60f4f80-a039-11ea-86f0-bcf15d6b836f.jpg)

Here is the output log (a lot bigger than usual🤔 (1.95MB) So many errors😢):
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4689877/output_log.txt)

Here is the blueprint:
[O'Neill Cylinder Ship.zip](https://github.com/tsunamayo/Starship-EVO/files/4689872/O.Neill.Cylinder.Ship.zip)

**Comment by tsunamayo** [comment]
This issue should have been fixed a while ago! thanks
