### ISSUE TITLE
[Bug?] Phasing through blocks, when travelling. 

### ISSUE THREAD

**Issue by MRonlin** [tsunamayo/Starship-EVO#2234]
### Short Description of the issue:
When the players speed is increased enough, on collision with a block they can clip through it.

...

### Steps to reproduce the issue:
Make a wall and increase player speed. And then fly into the wall.

...

### Environment
- Starship EVO version: 20w22c
- Graphics Card: gtx 1050

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

You can find the log here: 
[output_log (1).txt](https://github.com/tsunamayo/Starship-EVO/files/4689949/output_log.1.txt)

**Comment by tsunamayo** [comment]
This will likely never be fixed - because it is actually convenient to get unstuck... And also because increasing player speed is a debugging option that will be hidden from the player for release. Thanks
