### ISSUE TITLE
Multitool still in hand when holding weapons

### ISSUE THREAD

**Issue by i-Likeyogurt** [tsunamayo/Starship-EVO#2237]
### Short Description of the issue: When holding a custom weapon, the multittol and the weapon are both in hand when in first person, like the multitool clips through the weapon

...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Is it only when you do F6 (photo mode), 1st person or 3rd person (or all). Thanks

**Comment by i-Likeyogurt** [comment]
> Is it only when you do F6 (photo mode), 1st person or 3rd person (or all). Thanks

Its only in first person, if you go f4 then f6 from that, its not there, but if you go f6 from first person its there, it is also there in first person too

**Comment by i-Likeyogurt** [comment]
![20200529200117_1](https://user-images.githubusercontent.com/65824432/83295723-5b547380-a1e7-11ea-9b28-24834e7813ea.jpg)

**Comment by tsunamayo** [comment]
Issue fixed in 20w23a. Thanks!
