### ISSUE TITLE
[Bug] Alphanumeric string when mousing over handle on item stand [20w22c]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#2239]
### Short Description of the issue:
When a handle is placed on the item stand, an alphanumeric string appears when mousing over it.

### Steps to reproduce the issue:
Place handle on item stand, mouse over the handle.

### Environment
- Starship EVO version: 20w22c
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20200527135852_1](https://user-images.githubusercontent.com/33041786/83061673-00721f00-a023-11ea-810e-c2ad35de7100.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4691171/output_log.txt)

**Comment by tsunamayo** [comment]
Oh yes thats the SGUID of the weapon entity, I put it for debugging but I will remove it. Thanks

**Comment by tsunamayo** [comment]
Issue fixed for 20w20d, now you see the true weapon name. Thanks
