### ISSUE TITLE
[Bug] Item stand glow resets to defualt

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Starship-EVO#2243]
### Short Description of the issue:
If you paint and item stand it changes it's glow. If you remove the object and put it back in the glow on the item stand resets
![image](https://user-images.githubusercontent.com/53021785/83084474-47bdd700-a046-11ea-9e92-6d548fc194e4.png)

...

### Steps to reproduce the issue:
- Place an item stand
- Place something in it
- Paint the item stand
- remove whats in it
- put it back
- issue
...

### Environment
- Starship EVO version: 20w22c
- Graphics Card: Integrated Graphics Gang

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4692517/output_log.txt)

**Comment by tsunamayo** [comment]
Issue fixed for 20w22d. Thanks!
