### ISSUE TITLE
[Bug] Different handheld weapon animations in normal/F6 camera vs F10 camera [20w22c]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#2244]
### Short Description of the issue:
When holding 2-handed weapons and viewed in the F10 camera, the character is capable of holding them in a typical rifle-pose; however, when viewed in the normal camera and the F6 camera, the animation changes to a different one.

### Steps to reproduce the issue:
We've been experimenting with different grip positions to see how that affects the animations (by the way, the adaptive holding system is really cool!), and I noticed that putting the handle in this position gives this slightly awkward result when viewed in F6:
![20200527223739_1](https://user-images.githubusercontent.com/33041786/83096272-e3f9d500-a06a-11ea-9cbb-b521ee49a453.jpg)

But when viewed in F10, the animation is a much more natural-looking one:
![20200527223756_1](https://user-images.githubusercontent.com/33041786/83096291-ee1bd380-a06a-11ea-8e43-cce2bcfdea55.jpg)

### Environment
- Starship EVO version: 20w22c
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4693093/output_log.txt)

**Comment by tsunamayo** [comment]
Actually I think the correct one is F6 unfortunately. F10 was the old freeze time way, I replaced it with F6. F10 just shows the normal pose without IK which happens to be what works best for your weapon. But thats not how you look during normal gameplay (you could try seing yourself through a camera). The way you positioned the handle wont work well I guess - if you want to send me the blueprint I could have a look at it. Weapon IK is definitely finicky...
