### ISSUE TITLE
[BUG] Inverted mouse does not work with vehicles. 

### ISSUE THREAD

**Issue by Servomotor** [tsunamayo/Starship-EVO#2245]
I play with mouse inverted controls. I have seleted the option in the interface to use inverted mouse. My character moves with inverted mouse, but my vehicles do not. I just started playing with this recent funding and it has been this way since day 1 (meaning the past 3-4 versions of the game). 

...

### Steps to reproduce the issue:
Just play normally and move around
...

### Environment
- Starship EVO version: 20w22c
- Graphics Card: Nvidea RTS 2080

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
@Servomotor there two option, one in the Control Menu for the player. Then there is also an option per axis for ship control in the keybind menu. The reason is that the ship control can be mapped with more freedom, mouse or not.
I will make this clear in the inverted description. Thanks!
