### ISSUE TITLE
[Bug] Something sent ship out of the system [20w22c]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#2248]
### Short Description of the issue:
I had been carrying a gun, then took control of a fighter. Shortly after I took control of it, something flung the fighter way outside the bounds of the system.

### Steps to reproduce the issue:
I'm not sure, and I'm trying to reproduce this, but it was really weird.

### Environment
- Starship EVO version: 20w22c
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
You can see that there is a target box inside the ship itself, and when I targeted it, it turned out to be the gun I was carrying. Not sure if that's related or not.
![20200527234542_1](https://user-images.githubusercontent.com/33041786/83100093-a9953580-a074-11ea-845f-4f53c26bf055.jpg)

The ship went far enough that the graphics went crazy:
![20200527234630_1](https://user-images.githubusercontent.com/33041786/83100177-dba69780-a074-11ea-9694-3b2665d10c77.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4693314/output_log.txt)

**Comment by tsunamayo** [comment]
This issue should have been linked to weapon collision, which has been fixed in recent build. Thanks a lot!
