### ISSUE TITLE
Secondary weapon handle placement has bad issues

### ISSUE THREAD

**Issue by Xenoprophet-Nail** [tsunamayo/Starship-EVO#2249]
### Short Description of the issue:
when I try to place a handle in a certain position, it moves in the opposite direction, I can't get a rifle styled grip because of this. I've seen the pose before and others have managed it on their games, I'm not sure why the rotation is off in that position. If you look at it like a analog clock I can have the handle at 12, 6, and 9 o'clock at 3 o'clock it lays sideways and goes backwards
 ...

### Steps to reproduce the issue:
I have some pictures to explain:
https://media.discordapp.net/attachments/634150325426716702/715391767645651004/guide.jpg?width=1076&height=605
was womble's idea on how to make a rifle that is held correctly, doing that my character's left arm is off, I thought rotating that handle so the trigger faces you in that picture it would be held correctly.
well trying to rotate that handle to the position I need is where the glitch occurs: 
![20200528002905_1](https://user-images.githubusercontent.com/51257864/83103495-cfc2d180-a084-11ea-82cf-874316c3b27a.jpg)

...

### Environment
- Starship EVO version: 20w22c
- Graphics Card: Nvidia Geforce Gtx 1060 6gb

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4693490/output_log.txt)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Issue fixed for 20w23a. Thanks!
