### ISSUE TITLE
[BUG] Animation Bug when in chair with yoke.

### ISSUE THREAD

**Issue by Servomotor** [tsunamayo/Starship-EVO#2250]
### Short Description of the issue:
My character went into a funny animation when I was sitting in a chair. I recall how I got this to happen, I started laughing too hard. But its a thing. Video is self explanatory on what the bug does.

...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 20w22c
- Graphics Card: Invidia RTX 2080

### Additional information:
https://www.youtube.com/watch?v=HGo4ywjQAk0
_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Thanks for the laugh ;), I keep you posted.

**Comment by Servomotor** [comment]
Thank you for all your hard work on this game. It's a dream come true for me :)

**Comment by tsunamayo** [comment]
Glad to hear that! Go tell all your friends ;)

**Comment by Servomotor** [comment]
My wife is playing it. Sadly most of my friends are not into computer games. They are boring. Are we able to still purchase kickstarter packs? I'd like to get the adventure one to support you monetarily and change my discord color LOL.

**Comment by tsunamayo** [comment]
haha thanks, maybe after the ea release I will see I havent made up my mind on that ;)

**Comment by tsunamayo** [comment]
And thanks for wanting to support the game!

**Comment by Servomotor** [comment]
I'll support you whatever your decision, just remember I have money burning a hole in my pocket, LOL :)
I made an exotic hovercraft, the folks in discord told me to make sure I reach out to you so you can see it. Dwarf said it showcases what can be done in the game, I hope. I just like making cool stuff and love to see others cool stuff. I have a lot to learn, but also have a lot of experience (played landmark for years until they cancelled it). 
https://github.com/tsunamayo/Starship-EVO/issues/2070

**Comment by tsunamayo** [comment]
Your ship is amazing mate!
I dont really manage to reproduce your issue though - if you could tell me how you did it?

**Comment by tsunamayo** [comment]
Okay I have fixed a couple of issue regarding this, I think it should have taken care of that one. Thanks!
