### ISSUE TITLE
[Bug] with building ships

### ISSUE THREAD

**Issue by termi17385** [tsunamayo/Starship-EVO#2251]
### Short Description of the issue:
not sure if its entirely caused by building a large ship but sometimes blocks appear invisible or when blocks are removed they leave behind black remanets of themselves with vanish after a few mins 
...

### Steps to reproduce the issue:
![image](https://user-images.githubusercontent.com/66066987/83135450-313c7c00-a129-11ea-84ed-4c3a5e1edb92.png)
build a large ship using symmetry 
...

### Environment
- Starship EVO version: Pre-alpha 20w22c
- Graphics Card: geforce 1060 gtx

### Additional information:

![Bug 2](https://user-images.githubusercontent.com/66066987/83135187-d3a82f80-a128-11ea-8f62-5cc0a6815ea7.png)
![Bug 1](https://user-images.githubusercontent.com/66066987/83135192-d6a32000-a128-11ea-8ad1-92577c98d598.png)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4695187/output_log.txt)

**Comment by zalexville** [comment]
I also get this bug. The blocks reappear under odd conditions but it seems "fixed" for about an hour after reloading the game, but then it comes back.

**Comment by ProPeach** [comment]
I believe this is a similar issue to #1874, it tends to happen more often when your CPU is under load. Tsuna has some optimizations planned that should eradicate the issue though : )

**Comment by tsunamayo** [comment]
Yes this is a know issue with large ship - a dev is planned to address it (post ea though). Thanks
