### ISSUE TITLE
[Bug] F2 disables keybinding

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#2253]
Disabling the HUD with F2 makes it so you can't set new keybinds

https://cdn.discordapp.com/attachments/406664114249793536/715632588781518848/Starship_EVO_2020-05-28_11-24-21.mp4

**Comment by tsunamayo** [comment]
Amazing mate, this was the trigger for the now keybind issue! I should be able to fix that one now. Thanks ;)

**Comment by tsunamayo** [comment]
Fixed for 20w22d. Thanks!
