### ISSUE TITLE
Sequencers and Rails

### ISSUE THREAD

**Issue by chacalik** [tsunamayo/Starship-EVO#2255]
### Short Description of the issue:
It appears that you can't input a correct value to the sequencer block, since it didn't accept comma (,). Also inputing period (.) won't work aswell. Trying to put any value above 1 or any value in dots, cause the value, once the box is closed, to be updated to the maximum lenght of the rail (ie: 125).
...

### Steps to reproduce the issue:
Put a block with at least 1,25m long, put a sequencer and a switch. Connect the logic of the switch to the sequencer, the sequencer to the rail and change the settings on the sequencer. Try any value above 1 and any value between period either, close the settings box and open it again.
...

### Environment
- Starship EVO version: 20w22c
- Graphics Card: AMD Radeon RX 590

### Additional information:
There was no crashing, so output_log.txt is empty.
_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Hi, what is your keyboard locale? Thanks

**Comment by tsunamayo** [comment]
Okay I think it was a locale issue, but it should be fixed for 20w22d. Thanks

**Comment by chacalik** [comment]
> Hi, what is your keyboard locale? Thanks

Sorry for the late... Its PT-BR (Portuguese-Brazil) Thx!
