### ISSUE TITLE
Last backing wave steam-key Issue

### ISSUE THREAD

**Issue by MantidChew** [tsunamayo/Starship-EVO#2256]
### Short Description of the issue:

Hi Tsuna, I was sent here by one of the moderators on discord to contact you about an issue. My key of the game hasn't arrived yet, though I purchased through PayPal the day I got the notification of the backing wave. What information would I need to provide in order to resolve this issue and get my key? My email is samuelparker.au@gmail.com and I am @ Caribbean_Amphibian245 on the Starship Evo discord. 

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Contacted by mail.
