### ISSUE TITLE
[Bug?] [Suggestion] F6 movement

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#2257]
### Short Description of the issue:

Before 20w22c, F6 build mode would control much like the player except more precise.
In 20w22c, it now has a substantial speed reduction and drifting problem.

I see it has been officially named "photo mode". I do not think it is wise to allow building in that mode if it cannot control properly and is not earmarked for building in any way.

Regardless, it is now incredibly difficult to build while in F6 mode due to the movement change, and F10 now seems pointless given it basically achieves the same effect of being a disembodied camera. If F6 is meant to be a photo mode, I suggest giving it the same movement behavior as current F10, and to remove the ability to build. F10 should then have the movement of the previous F6 and gain the ability to build. Either that, or rename F10 to photo mode and restore F6 to its previous movement behavior.

### Environment
- Starship EVO version: 20w22c
- Graphics Card: Nvidia GeForce GTX 1060 6GB

**Comment by tsunamayo** [comment]
Yes sorry it was wip. It is just meant to be a photo mode for taking screenshot, not building - I will prevent that. Thanks

**Comment by Majikmonster** [comment]
Will F10 then become the build mode?

**Comment by tsunamayo** [comment]
There is no build mode. Where you using this as a build mode?

**Comment by tsunamayo** [comment]
Okay issue fixed for 20w22d. I am uploading the build now. Thanks ;)
