### ISSUE TITLE
[Bug] Volumetric Sensor Bug MP

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Starship-EVO#2259]
### Short Description of the issue:

When in Multiplayer, if 1 person is inside a volumetric sensor's area, if a second person walks inside the area, and then walks out, it is no longer triggered by the 1st person that was already in it.

In other words, as soon as a second person activates a volumetric sensor, it is disabled the moment the second person leaves it, regardless of the first person being still in it.

### Steps to reproduce the issue:

For example, hook up a volumetric sensor to an indicator light, have player 1 walk into the volumetric sensors bounds, and activate the indicator light. Have player 2 walk into the volumetric sensor area, the indicator light should stay lit, and then go off once player 2 walks out of the volumetric sensor's area.

### Environment
- Starship EVO version: 20w22d
- Graphics Card: 2080 Super OC

If you need anything else let me know.
Thanks Tsuna

**Comment by tsunamayo** [comment]
Good test case, indeed it is not mp proof, I will fix that!

**Comment by tsunamayo** [comment]
This should be fixed in 22w45a. Thanks
