### ISSUE TITLE
[Bug] Weapon already in hotbar appears in hand on game reload

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Starship-EVO#2260]
### Short Description of the issue:

If you have a handheld weapon on your Hotbar, in any of the slots other than the 1st slot, upon reloading the game, the weapon appears in your hand until you select it and then deselect it (put it away properly).

### Steps to reproduce the issue:

Build a weapon, put it in any Hotbar slot other than the 1st slot (as when the game reloads you're holding the 1st slot by default.) save game and close. Reopen the game, you should find that the gun appears to be held in your hand even though you're not holding it. To make the gun appear to be put away, select the appropriate hotbar slot, and then deselect it.

### Environment
- Starship EVO version: 20w22d
- Graphics Card: 2080 Super OC

Thanks Tsuna

**Comment by tsunamayo** [comment]
Issue fixed for 20w23c. Thanks for the always clean test cases!
