### ISSUE TITLE
[Suggestion] Text Screen Interface

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#2263]
Typing in <sprite=##> is very awkward when trying to space a mix of letters and sprites. It is also next to impossible for a new player to learn unless they are told about it. Instead of typing, we could just click on an icon and it will be added to the text. I'm sure this is planned already, but just in case it is not there is the suggestion.

![](https://cdn.discordapp.com/attachments/406664114249793536/715962736252813322/unknown.png)

Also is there a way to add some basic font colors. Not saying add the entire color pallet in game, just the basic colors. Red, blue, yellow, green, orange, purple, black, and white.

**Comment by tsunamayo** [comment]
Honestly not sure, as I dont want to loose time making a text editor - that would take a huge time to deal with all the feature. I will put an help instead (that was my plan), it uses rich text http://digitalnativestudios.com/textmeshpro/docs/rich-text/
I did the tut myself, honestly once you understood the tag concept it is okay to work with that.
My plan is to add a little Help button near the close button (for all gate!).
Thanks
