### ISSUE TITLE
[Suggestion] 3/4 Point Triangles

### ISSUE THREAD

**Issue by Titaniclover** [tsunamayo/Starship-EVO#2264]
A small suggestion, but an idea to make angle placing much easier is making a version of the slopes that, rather than placing normally, allows you to select 3 to 4 points for the triangle/tetra/etc to form. This way, when creating irregular angles, it will be much easier in general to place.

**Comment by tsunamayo** [comment]
Okay I think I understand your suggestion, unfortunately I dont really plan on doing that. I see how it could make sense but it would be nightmare to code, and to explain to player how it works. Honestly placing tetra is very easy, no rotation needed. Placing hepta and corner also is easy, I think you will get used to it!
Thanks

**Comment by Titaniclover** [comment]
I get that. I was thinking about more irregular shapes and triangles, but now that I think about it more I can see those being done in different positions. Thank you for the response.

**Comment by tsunamayo** [comment]
Actually we had that back in the day, it was called the Freeform tool. But it was a pain code-wise, and not very practical to use. It was replace with the current tech, much easier to use!
