### ISSUE TITLE
[Suggestion]-A hotkey for swapping through locomotion modes

### ISSUE THREAD

**Issue by i-Likeyogurt** [tsunamayo/Starship-EVO#2265]
### Short Description of the issue: if there was a key that would go through different locomotion modes on the fly

...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by Majikmonster** [comment]
Since scroll and Shift+scroll are taken, perhaps Alt+scroll would be a good key combo.

**Comment by tsunamayo** [comment]
I wanted to use the middle mouse action wheel for that - I havent had time to do it yet. Thanks

**Comment by tsunamayo** [comment]
We now have the J-key!
