### ISSUE TITLE
[Question] Is the Stations tab in codex supposed to be there? [20w22d]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#2266]
There is a new tab in the codex with station blocks; are these supposed to be there?

**Comment by Womble-TC** [comment]
Yeah, my tea does seem a little big today... 
![image](https://user-images.githubusercontent.com/29961381/83307895-8a75df80-a1fd-11ea-9e56-245e3753abf0.png)

**Comment by tsunamayo** [comment]
Hehe yes sorry again I forget to hide them, but I am working on station tech.
The tech will consist in station Hull 4m sized block, interior normal size but only loading when you enter the station. They will also be modular, so it is easy to spawn and attach a new modules.
I need big station for gameplay! 

If you are interested in doing that guys (looking at you @Womble-TC  ;)) . Also do you know if OldIronSides is on the discord? I would need his amazing skill for interior.

**Comment by Womble-TC** [comment]
Would love to help out with that, just let me know when! I'll give you those updated tutorial buildings soon too.

**Comment by tsunamayo** [comment]
Thanks! Soon, I am rushing this feature, it will bugged and lacking but I just want you guy start to build asap. To get you up to speed I would need:
1) shiyard of various sizes
2) some connector and corridors
3) a hub, where I could get my gameplay related hotspot
4) some habitable quarter just for immersion (interior less urgent, could do without for now)

**Comment by Womble-TC** [comment]
awesome, cant wait to get started and see the system in action

**Comment by Aiwii** [comment]
mind if I pitch a build???

**Comment by tsunamayo** [comment]
of course it is open to anybody!

**Comment by ProPeach** [comment]
What form will the the shipyards come in? Will they be like the current landing pad style, or more like a space age "drydock" where the ship floats in a cage type structure? I think the second option is much more suited for a true shipyard as it's difficult to build a ship from scratch on a landing pad. Just want to check before starting to build a "shipyard" station!

**Comment by tsunamayo** [comment]
So actually shipyard should be renamed, as it is more a simple landing pad. 
But I would like to do both type ultimately, not sure how to handle the UX for your drydock, maybe a placeholder block that show the preview only when selected.
But they are respawn / servicing point, I dont really want to force the player to go there to build in survival, to build your ship and access the station store you will just need to be close to it.
I will make a super large frame block; 4 voxel wide, a voxel is 4 meter, max scale is the usual 16. So that makes for a 256 meter ship. 
Beyond that size just mean your ship cannot be serviced, they will go in the category "capital ship", "mother ship" ect. with different rules. I think thats fine, 500m ships feels capital ship to me.

**Comment by ProPeach** [comment]
Sounds great! The landing pad/shipyard name change will definitely help clear things up.
I really enjoy the thought of really large ships requiring more effort to service rather than just parking them in a shipyard - could they perhaps use repair drones, or small repair ships instead?

**Comment by tsunamayo** [comment]
Yes exactly, repair should be okay, it is more the respawn I need to give more thinking. Maybe no respawn? Like you have to get the wreck back and repair it, or salvage it and spawn a new one.
I will make the repair a weapon, so you could have repair gun, repair drone and repair ships.

**Comment by ZachZent** [comment]
There is still the idea of ship insurance. You lose the ship, but get a certain amount back. Then you can go salvage the wreck.

**Comment by ExodistSKY1** [comment]
Not respawning ships would be best.  I really like the idea of having to get the wreak back to repair it or just salvage it. 

I do like Zachs idea. 

A thing I feel needs to be a thing is the larger the ship or more mass a ship has the longer it should take to be constructed/spawn in. Instantly spawning in any ship with currency or resources sounds like fun but leaves the a lot to be desired in terms of rewarding gameplay.

Tsuna, 
"not sure how to handle the UX for your drydock, maybe a placeholder block that show the preview only when selected" Possibly a shipyard core you access and can set the center placement for the hologram with an "invisible block" maybe?    a hologram BP version that slowly gets "3D printed" over time maybe?

**Comment by tsunamayo** [comment]
So we have a block just like the gravity block for shipyard. So you can make a drydock or a landing pad, I will add a toggle in the config screen. Right now setting the volume is crappy, but I will do something to improve it, and that will work for all "volume" gate, gravity, sensor, shipyard.
