### ISSUE TITLE
[Suggestion] Return of freecam build mode

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#2267]
It has been suggested before to have a body-less build mode, and in 20w21# versions and up to 20w22b, we had that. Could we see the return of that mode (even though it was technically an oversight before)?

**Comment by tsunamayo** [comment]
Hi, you mean a no clip mode?

**Comment by Majikmonster** [comment]
Yes.

**Comment by tsunamayo** [comment]
So no it is not really planned - I am not a fan of the no-clip mode for normal gameplay, sorry!
