### ISSUE TITLE
[Bug?] and Solution - Can't connect monitor to a turret core and a camera, disconnects all connections

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Starship-EVO#2269]
### Short Description of the issue:

When connecting a monitor as an entry point to a turret core, if you also try to link the monitor to the camera on the same turret, it removes both the links from the monitor.

### Steps to reproduce the issue:

Link a monitor to a turret core. (The turret core has to be set up with a functional turret.) Place a camera on the turret. Link the same monitor to the camera. Both logic links you just made will be removed.

### Environment
- Starship EVO version: 20w22d
- Graphics Card: 2080 Super OC

### Solution:

Instead of just fixing the monitor linking to two things problem, I suggest simply making it possible once again to link a turret core to a camera. So that way we can have security cameras that can move once again. 
Do the same thing as you have with setting up a turret, how the laser bricks determine what is forward on a turret. Except allow a camera to determine what is forward.

This way you have a turret core, link it to the two rotors/axis, link to the laser bricks and if you want a camera on it, link a camera to it too.
I heard this being talked about at some point, but I haven't seen it in-game yet.

It would be very handy to be able to make moveable cameras once again.

Thanks Tsuna

**Comment by tsunamayo** [comment]
Now you can link a turret to the camera, it will act as the pointer. For 20w26a.
You will have to connect the turret to the camera though, not the yoke.
Thanks
