### ISSUE TITLE
[Bug] Can't fly a ship with guns stored away in item stands

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Starship-EVO#2271]
### Short Description of the issue:

It seems quite inconsistent in recreating this bug, so I need others to help me figure out how to recreate all the time, but basically, if you have handheld guns stored in items stands in a ship, sometimes they glitch and stop the ship from flying. Its as if the gun entities on the item stand's clip inside the actual ship hull, and so the ship won't move due to collisions happening within blocks of the ship. Consequently sometimes when just walking around a ship, the ship shakes like an earthquake because of the collision between gun entities bouncing around inside the ship?

### Steps to reproduce the issue:
Get a ship with an interior, place item stands, place some weapons on them. Try flying ship. Sometimes it doesn't happen, but upon saving and relaunching the game, it is almost always glitched out, and I can't fly a ship until I remove all guns from their item stands.

Sometimes I even see sparks of where an invisible entity offset is clipping into the hull in the ship.

### Environment
- Starship EVO version: 20w22d
- Graphics Card: 2080 Super OC

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4705117/output_log.txt)

This has been going on for a few versions, but I was hoping among other bug fixes it would be fixed, as I wasn't sure how to recreate consistently.

Thanks Tsuna

**Comment by tsunamayo** [comment]
So this should be fixed in 20w24b. I am uploading the build now. Thanks!
