### ISSUE TITLE
Invis ship floating freeze multi character

### ISSUE THREAD

**Issue by Vadenn** [tsunamayo/Starship-EVO#2273]
![Annotation 2020-05-30 105846 - Copy](https://user-images.githubusercontent.com/66177563/83334900-d3ae4980-a266-11ea-8e3d-2b9ec99b918e.png)
### Short Description of the issue:
Everything except the player camera and the pause menu is unresponsive including the tab menu, even after key rebinding and changing characters. It also happens on newly created characters entering the game for the first time.
...

### Steps to reproduce the issue:
So I was building, and was setting up logic, when the ship turned invisible, and then I found that I was stuck in the air, floating, so I closed skywanderers, thinking it was another crash, and re-entered the game, only to find that it was still going on, So I quit again and did a full computer restart, didn't change anything. I tried to crate a new character, and was still only able to look around and access the pause menu, and nothing else.

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
![Annotation 2020-05-30 105846 - Copy](https://user-images.githubusercontent.com/66177563/83334905-e032a200-a266-11ea-8ef9-9bc65e61dcc9.png)

[output_log - Copy.txt](https://github.com/tsunamayo/Starship-EVO/files/4706164/output_log.-.Copy.txt)

[Save_Data - Copy_2.zip](https://github.com/tsunamayo/Starship-EVO/files/4706165/Save_Data.-.Copy_2.zip)

**Comment by Vadenn** [comment]
Update, managed to sort it'self out on it's own, although I will keep this here just in case

**Comment by tsunamayo** [comment]
Thanks a lot for the save folder, I am investigating this. What is worrying me is the fact that you said you had this issue on a new character, this I cant reproduce => can you confirm?
Thanks
