### ISSUE TITLE
Visual errors on weapons

### ISSUE THREAD

**Issue by dhelonious** [tsunamayo/Starship-EVO#2274]
### Short Description of the issue:

Decals are shown of weapons from certain angles (see the screenshots below).

There seems to be another issue with my character holding both the multitool and the weapon simultaneously. However, the visual error also occurs on the item stand in the second picture, so this seems not to be related.

### Steps to reproduce the issue:

I have no idea how to reproduce this issue. I accidentally discovered this by building my weapon on top of the tutorial building. However, there the issue can be reproduced consistently.

Since it might be realted to my graphics card I also uploaded my savegame. Maybe you could test it yourself.

### Environment
- Starship EVO version: 20w22d
- Graphics Card: Radeon RX 470

### Additional information:

Screenshots:
![20200530212033_1](https://user-images.githubusercontent.com/6987220/83337596-32061700-a2bd-11ea-8494-89627c04a4d2.jpg)
![20200530212143_1](https://user-images.githubusercontent.com/6987220/83337597-34687100-a2bd-11ea-83b2-47ffd4ebd2df.jpg)

Savegame:
[Savegame.zip](https://github.com/tsunamayo/Starship-EVO/files/4706304/Savegame.zip)

**Comment by tsunamayo** [comment]
Both issues fixed for 20w23a! Thanks a lot, and nice idea ;)
