### ISSUE TITLE
[Bug] Paint changes on blueprints [20w22d]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#2275]
### Short Description of the issue:
Some blueprints' paint is being altered when loaded. This change persists after save/reload.

### Steps to reproduce the issue:
I'm including the blueprint I've found it on so far so you can see it directly.

### Environment
- Starship EVO version: 20w22d
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
Odd changes to paint on loading the blueprint:
![20200530141701_1](https://user-images.githubusercontent.com/33041786/83338082-4aa70a80-a286-11ea-81a6-5cff0d77ca38.jpg)

Changes still around after saving, quitting the game, and reloading:
![20200530145432_1](https://user-images.githubusercontent.com/33041786/83338088-54307280-a286-11ea-9a3d-21c169f865e3.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4706346/output_log.txt)

**Comment by tsunamayo** [comment]
Okay this is bad... Ps you forgot the blueprint, but I will try with my version of the whirlwind.

**Comment by tsunamayo** [comment]
whirlwind is fine over there!

**Comment by Dwarf-LordPangolin** [comment]
What is it with me and forgetting to send blueprints ... so sorry about that!
[Whirlwind Destroyer - v4 Paint Bug.zip](https://github.com/tsunamayo/Starship-EVO/files/4706810/Whirlwind.Destroyer.-.v4.Paint.Bug.zip)

**Comment by Dwarf-LordPangolin** [comment]
This is happening with other ships as well; I think this might actually be the same paint bug as [this one](https://github.com/tsunamayo/Starship-EVO/issues/2277).

![20200531160655_1](https://user-images.githubusercontent.com/33041786/83363466-50245380-a35f-11ea-8adb-ac70bf28f7f1.jpg)

It's harder to see in this picture, but the paint has the same block, unpaintable spots as the one in the station bug.
![20200531165315_1](https://user-images.githubusercontent.com/33041786/83363467-51558080-a35f-11ea-9b0f-bbfcc1a71537.jpg)

I remembered the blueprint this time!
[200m Cruiser Prototype.zip](https://github.com/tsunamayo/Starship-EVO/files/4708554/200m.Cruiser.Prototype.zip)

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin I have loaded both your ship, and they are both fine! Do you confirm you still get the issue in 20w22e? 
If yes could you send me your full character save?
Thanks

**Comment by tsunamayo** [comment]
I was finally able to reproduce and fix the issue for 20w27a. Thanks!
