### ISSUE TITLE
Position Glitching on 1-to-4 Offset

### ISSUE THREAD

**Issue by chacalik** [tsunamayo/Starship-EVO#2276]
### Short Description of the issue:
When building over a 1-to-4 Offset block, the position of a block will constantly glitch between the center and the desired position of the block. 
...

### Steps to reproduce the issue:
Put a 4-to-1 Offset block on the ground, put an Arm block on top of it and then a 1-to-4 Offset block, then try to put another block over that last one.
...

### Environment
- Starship EVO version: 20w22d
- Graphics Card: AMD Radeon RX 590

### Additional information:
The following two screenshots shows two glitching moments with the mouse stopped.
![Screenshot_1](https://user-images.githubusercontent.com/4794243/83338578-0888c380-a29c-11ea-8c69-ff68c761bac4.png)
![Screenshot_2](https://user-images.githubusercontent.com/4794243/83338579-0b83b400-a29c-11ea-847b-8136f281b66a.png)

**Comment by tsunamayo** [comment]
I cant reproduce that, could you please send me your blueprint? Thanks!
