### ISSUE TITLE
[Bug] Station paint issues [20w22d]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#2277]
### Short Description of the issue:
This is probably just due to the tech still being worked on, but there's an issue with the paint where some patches on blocks appear as a different black color when placed and cannot be painted. They also have lines around them as though the game thinks they're not part of the same block.

### Steps to reproduce the issue:
Create a station and start placing blocks. It should show up after a while.

### Environment
- Starship EVO version: 20w22d
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20200530163900_1](https://user-images.githubusercontent.com/33041786/83339675-f60b8b80-a295-11ea-88ca-8addbc7f6aae.jpg)
The block patches ignore what they're painted, and are a different color than the in-game black paint. There's also an outline around them.

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4706624/output_log.txt)

PS: really excited about building station modules!
![20200530164510_1](https://user-images.githubusercontent.com/33041786/83339707-1c312b80-a296-11ea-80d8-ff93c57b6688.jpg)

**Comment by tsunamayo** [comment]
Okay I will look into that, but dont spend time on this, your station might not be functional (the interior wont load), I dont think it was working when I made the patch.

**Comment by tsunamayo** [comment]
No longer applicable.
