### ISSUE TITLE
[Bug] Laser bolts bypass shields

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#2278]
### Short Description of the issue:

Laser bolts of both block and brick weapons go right through shields, while beams still hit the shield.

When testing some turrets, I noticed that I was destroying blocks on ships in a single shot. I knew that was mathematically impossible due to the shields on those ships. Upon checking the shields of a ship and shooting them with both beams and lasers, the beam hit the shield but the lasers still passed through. I tested this with multiple ships both firing and taking shots.
 
### Steps to reproduce the issue:

Fire at a shielded ship with both a beam weapon and laser weapon, brick or block sized.

### Environment
- Starship EVO version: 20w22d
- Graphics Card: Nvidia GeForce GTX 1060 6GB

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4707000/output_log.txt)

**Comment by tsunamayo** [comment]
Issue fixed for 20w23a. A lot of unreliable stuff from unity side... =( Thanks
