### ISSUE TITLE
[Bug] Tools in item stands disappear after game reload.

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Starship-EVO#2281]
### Short Description of the issue:

If you store tools like the Grav tool, link tool, or repair tool, in an item stand. If you close the game and reopen it, the tools don't appear visually in the item stand. If you interact with the item stand and press f on it, you will still get the respective tool you left in the item stand, and you can replace it again to get the visual of it back. 
This would be bad if someone loaded up a new game and had not completed the tutorial building after restarting their game, as things like the grav tool or link tool would be invisible in their item stands for part of the tutorial.

### Steps to reproduce the issue:

Place a tool in an item stand, color it if you want. Save and close the game. Reopen game, the item stand should appear empty but still holds the tool in it if you press F on it.

### Environment
- Starship EVO version: 20w22d
- Graphics Card: 2080 Super OC

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4707184/output_log.txt)

**Comment by tsunamayo** [comment]
Issue fixed for 20w23a. Thanks!
