### ISSUE TITLE
Deleted entity still rendered

### ISSUE THREAD

**Issue by chacalik** [tsunamayo/Starship-EVO#2284]
### Short Description of the issue:
When deleting something in simetry mode, the opposite side entity will still be there until render update (like placing another block or deleting other). 
...

### Steps to reproduce the issue:
Enable simetry mode, delete a block wich has an opposite dual, notice the opposite entity is still there, but is not interactive.
...

### Environment
- Starship EVO version: 20w22d
- Graphics Card: AMD Radeon RX 590

### Additional information:
Following screenshot shows the bug.
![image](https://user-images.githubusercontent.com/4794243/83346712-4d8d1400-a2f5-11ea-95e8-7e710c868c55.png)

**Comment by esauftgz** [comment]
I can confirm that this happens.

**Comment by tsunamayo** [comment]
Thanks for booking the bug, yes it is a known issue that will be addressed with a deep refactoring of the rendering tech. Thanks

**Comment by tsunamayo** [comment]
Should be fixed now! Thanks
