### ISSUE TITLE
[Bug] Bricks placed on the interior of stations are offset

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Starship-EVO#2288]
### Short Description of the issue:
Bricks are offset and cannot be directly placed on the interior parts of the station
![image](https://user-images.githubusercontent.com/53021785/83361169-ea769e00-a343-11ea-89ad-7f0b0fdc1841.png)

...

### Steps to reproduce the issue:
-build station
-go inside
-try to place brick
-issue
...

### Environment
- Starship EVO version: 20w22e
- Graphics Card: Integrated

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4708272/output_log.txt)

**Comment by tsunamayo** [comment]
Okay issue fixed for 20w23a. Thanks!
