### ISSUE TITLE
New station construction mechanics, unable to place a number of items

### ISSUE THREAD

**Issue by enterprise-E** [tsunamayo/Starship-EVO#2290]
### Short Description of the issue:
cannot place buttons, sliders, switches, chairs...
...

### Steps to reproduce the issue:
start with station block
place a couple of hull blocks
try to place blocks listed above
...

### Environment
- Starship EVO version: 20w22e
- Graphics Card: radeon sapphire pulse 8GB, using on dual monitors

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4708841/output_log.txt)

**Comment by tsunamayo** [comment]
Yes of course, you dont want to place a 4m wide chair... But I will come up with something for you to use a small grid also.
