### ISSUE TITLE
[Bug] Stickers barely visible on station, cannot be removed [20w22e]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#2292]
### Short Description of the issue:
Stickers placed on stations are only partially visible from certain angles, and cannot be removed.

### Steps to reproduce the issue:
Place sticker on station block, try to remove.

### Environment
- Starship EVO version: 20w22e
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
You can just barely see the sticker here:
![20200601024324_1](https://user-images.githubusercontent.com/33041786/83387911-2a289e80-a3b3-11ea-8be7-8bbbf98eb49c.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4710064/output_log.txt)

**Comment by tsunamayo** [comment]
Issue fixed for 20w23a. Thanks!
