### ISSUE TITLE
[Bug] Stretching blocks/bricks on stations allows clipping [20w22]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#2293]
### Short Description of the issue:
While dragging blocks or bricks for placement, they can be clipped through other things. Additionally, this can cause them to ignore symmetry limitations on double blocks.

### Steps to reproduce the issue:
Click drag a block or brick through another.

### Environment
- Starship EVO version: 20w22e
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20200601024749_1](https://user-images.githubusercontent.com/33041786/83388016-5512f280-a3b3-11ea-9bba-ce97c2771410.jpg)

![20200601024747_1](https://user-images.githubusercontent.com/33041786/83388022-56441f80-a3b3-11ea-868e-6aecfa70de84.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4710073/output_log.txt)

**Comment by tsunamayo** [comment]
You mean dragging through the other grid right (interior into parent or vice versa?)

**Comment by tsunamayo** [comment]
oh okay actually exterior vs exterior clip.

**Comment by tsunamayo** [comment]
No longer applicable.
