### ISSUE TITLE
[Bug] Light placement error inside stations [20w22e]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#2294]
### Short Description of the issue:
Light bricks placed on the inside-mode of stations are placed inside the full-size station blocks

### Steps to reproduce the issue:
Enter station module, place light on full-size station block.

### Environment
- Starship EVO version: 20w22e
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
Trying to place the light, but the placement outline is barely visible:
![20200601025722_1](https://user-images.githubusercontent.com/33041786/83388300-d4082b00-a3b3-11ea-8b73-ae5708821c05.jpg)

After placing it, there is light but no fixture:
![20200601025724_1](https://user-images.githubusercontent.com/33041786/83388307-d5395800-a3b3-11ea-9d99-e05bb74900c7.jpg)

Ah, there he was.
![20200601025726_1](https://user-images.githubusercontent.com/33041786/83388316-da96a280-a3b3-11ea-9750-5b48ffc65e16.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4710098/output_log.txt)

**Comment by tsunamayo** [comment]
Issue fixed, it was the same as #2288. Thanks
