### ISSUE TITLE
Station Interior Brick Offset Bug

### ISSUE THREAD

**Issue by TripleHelixxx** [tsunamayo/Starship-EVO#2295]
### Short Description of the issue:
When inside a station, using the small/normal grid, bricks placed on any exterior block are offset half way into the block. This doesn't happen for Blocks, only Bricks. In fact, it seems like this happens with any brick sized element, Lights, logic bricks, small windows, etc. It doesn't seem to happen with some larger elements that still use the brick size grid, such as the gravity generator.
...

### Steps to reproduce the issue:
1. Build a station. 
2. Enter the station.
3. Select a brick of choice and place it on any block that is part of the exterior. 
...

### Environment
- Starship EVO version: 20w22e
- Graphics Card: NVIDIA GeeForce GTX 1060 6GB

### Additional information:
The green block in this screenshot is the only interior block, the green brick is attached to that block and is fine, while the red brick to the right of that is attached to the floor of the station which is an exterior block. all other elements seen are also attached to the floor or wall. Note the gravity generator to the left is not effected by this bug, even though it uses the same 0.25 grid as bricks do. 

![20200601035923_1](https://user-images.githubusercontent.com/64316439/83389093-9e683f80-a3bd-11ea-94ce-6b0f0fd9ecfe.jpg)

Output Log:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4710176/output_log.txt)
`

**Comment by Aiwii** [comment]
#2288

**Comment by TripleHelixxx** [comment]
Oh oops. Guess I didn’t see that one

**Comment by tsunamayo** [comment]
Yes that is already fixed ;) build coming soon - I want to fix the sticker bug first.
