### ISSUE TITLE
Broken handle rotation angle

### ISSUE THREAD

**Issue by Xenoprophet-Nail** [tsunamayo/Starship-EVO#2297]
### Short Description of the issue: 
well I want to first thank you for all the bug fixing you've done so far man, but this one seemed to slip through somehow. When rotating a weapon handle on a sideways axis for a rifle position you can't get it with the trigger facing right. If that position existed rifle poses would be easier to achieve
...

### Steps to reproduce the issue:
place handle as I have in the video, rotate it around and watch it lay flat at an angle instead of having the trigger face to the right side of the weapon
...

### Environment
- Starship EVO version:  20w23A
- Graphics Card: Nvidia Geforce GTX 1600 6gb ram

### Additional information:

Enclosed is an eight second video to see what I mean about the placement

[Starship EVO 6_1_2020 9_45_50 AM.zip](https://github.com/tsunamayo/Starship-EVO/files/4711596/Starship.EVO.6_1_2020.9_45_50.AM.zip)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4711602/output_log.txt)

**Comment by tsunamayo** [comment]
Ah okay I think I misunderstood your previous bug. I managed to reproduce and it is fixed for 20w23d. Thanks!
