### ISSUE TITLE
[Bug] Blocks are offset by 0.5m in a station interior

### ISSUE THREAD

**Issue by Womble-TC** [tsunamayo/Starship-EVO#2298]
Blocks are offset by 0.5m when in a station interior: 
![image](https://user-images.githubusercontent.com/29961381/83430820-3bfb5780-a42e-11ea-992d-c6d89b88f1a4.png)

**Comment by Aiwii** [comment]
#2288 #2295

**Comment by Womble-TC** [comment]
Ok so I restarted my game and its seems to be fine now? I definitely had my game up-to-date before hand though .

**Comment by tsunamayo** [comment]
You are totally fine now?

**Comment by Womble-TC** [comment]
Yeah it seems so, sorry for the fake bug!

**Comment by tsunamayo** [comment]
I dont think thats a fake bug, must be something harder to reproduce!
