### ISSUE TITLE
[Bug] Light placement offset after linking modules [20w23a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#2299]
### Short Description of the issue:
Lights placed on the inside of station modules are appearing far outside them after linking station modules.

### Steps to reproduce the issue:
Place two station modules with lights placed inside them, and link them together. The lights of the module that moved will be floating in space away from their module.

### Environment
- Starship EVO version: 20w23a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20200601143051_1](https://user-images.githubusercontent.com/33041786/83448744-0ba8be80-a418-11ea-9fd3-232717fb2750.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4713159/output_log.txt)

**Comment by Dwarf-LordPangolin** [comment]
Update: things can be placed on these lights. However, the Codex cannot be opened when working on their entity.

**Comment by tsunamayo** [comment]
Did you had something more than light on the entity inerior? It is really weird if only the light move. If you can send me the blueprint that would be great!

**Comment by tsunamayo** [comment]
No longer applicable.
