### ISSUE TITLE
[Bug] Unspawning station module leaves lights from interior [20w23a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#2300]
### Short Description of the issue:
Lights on the interior of a station module are left after unspawning the exterior.

### Steps to reproduce the issue:
Spawn station module with lights, then unspawn. Lights from the interior will be floating in space.

### Environment
- Starship EVO version: 20w23a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20200601145721_1](https://user-images.githubusercontent.com/33041786/83448951-604c3980-a418-11ea-809b-a37689a6035c.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4713171/output_log.txt)

**Comment by Dwarf-LordPangolin** [comment]
Update: attempting to place things on these lights causes the entity to disappear.

**Comment by tsunamayo** [comment]
No longer applicable...
