### ISSUE TITLE
Gravity field view inside Yoke

### ISSUE THREAD

**Issue by chacalik** [tsunamayo/Starship-EVO#2301]
### Short Description of the issue:
The gravity bounding box can be seen while controlling a Yoke, if you activate it with the gravity block in hands.
...

### Steps to reproduce the issue:
Activate the Yoke with a gravity block in hands.
...

### Environment
- Starship EVO version: 20w23a
- Graphics Card: AMD Radeon RX590

### Additional information:
![image](https://user-images.githubusercontent.com/4794243/83450928-92679680-a42c-11ea-965e-d558153099e6.png)

**Comment by chacalik** [comment]
Although is good for debugging some projects, I believe it shouldn't happen as the players put anything in hands away to control the Yoke.

**Comment by tsunamayo** [comment]
Yes you are right! Issue fixed for 20w23b. Thanks!
