### ISSUE TITLE
[Bug] Blueprint despawns on save/reload, cannot change interior [20w23a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#2302]
### Short Description of the issue:
Attached blueprint despawns itself whenever the world is saved & reloaded; additionally, interior of blueprint cannot be edited, and hotbar selection cannot be change while inside interior.

### Steps to reproduce the issue:
Load the blueprint, save the world, quit and reload. Blueprint will be missing. Additionally, enter the module while it is loaded and attempt to select items in the hotbar; hotbar will be locked, and things cannot be placed in interior.

### Environment
- Starship EVO version: 20w23a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4713601/output_log.txt)

[Bugged Placement Station Module Blueprint.zip](https://github.com/tsunamayo/Starship-EVO/files/4713598/Bugged.Placement.Station.Module.Blueprint.zip)

**Comment by Dwarf-LordPangolin** [comment]
Update: I just noticed that there's also something very off about the placement of things on the blueprint's exterior now:
![20200601164854_1](https://user-images.githubusercontent.com/33041786/83458275-ddcb7600-a427-11ea-8dcf-22baceda1a60.jpg)


![20200601164900_1](https://user-images.githubusercontent.com/33041786/83458270-db691c00-a427-11ea-9905-c1accc58dc80.jpg)

**Comment by Dwarf-LordPangolin** [comment]
Update: it turns out these modules aren't despawning when save/reloading and their placement isn't weird -- they're just turning invisible. I realized this when I bumped into something invisible, and saw the outline of a block.

![20200601184627_1](https://user-images.githubusercontent.com/33041786/83465098-736f0180-a438-11ea-8266-df1d0ab773e8.jpg)

I tried placing something on it, and this popped up:
![20200601184629_1](https://user-images.githubusercontent.com/33041786/83465115-7bc73c80-a438-11ea-9440-19fd67810845.jpg)

**Comment by Dwarf-LordPangolin** [comment]
Update: I managed to duplicate this, and I think I've figured out what causes this: if, while working on a blueprint, you are working on the exterior, and you close the exterior with the character inside, exiting through the connector causes this bug for that blueprint permanently. Something about exiting through the connector when it wasn't entered through in the first place seems to confuse the system.

**Comment by Dwarf-LordPangolin** [comment]
Another update: I noticed that the blueprints affected by this do not update their interior blueprint when the Export button is pressed; the exterior is saved in BlueprintsStations, but not the interior blueprint. Also, the Export button does not beep when these affected blueprints are exported.

**Comment by Dwarf-LordPangolin** [comment]
One more update: the bug where the interior cannot be edited seems to apply to all blueprints loaded from the station starter, even ones where the interior can be edited on the original module.

**Comment by tsunamayo** [comment]
okay after a few days in this mess I think this approach is gonna be too much pain to get right - I will scrub it.

**Comment by tsunamayo** [comment]
No longer applicable. Your module looks fantastique, I still very much would like them in 1m grid ;) If you need any block brick tell me, I just did a 4m wide Lattice Girder for example. Thanks!
