### ISSUE TITLE
[Bug] Gun destroying itself when moving at speed

### ISSUE THREAD

**Issue by esauftgz** [tsunamayo/Starship-EVO#2304]
### Short Description of the issue:

Above a specific speed (not specific, issues started to happen for me when speed up), guns will destroy themselves when fired. Seems like this was an old fixed bug that appeared again.

### Steps to reproduce the issue:

1. Firing a gun at 0m/s works as intended.
![20200602124922_1](https://user-images.githubusercontent.com/65807125/83481259-d3fd4d80-a4cf-11ea-8fe8-3f42c590da17.jpg)

2. Firing a gun above 100m/s completely destroys it.
![20200602124938_1](https://user-images.githubusercontent.com/65807125/83481286-e5465a00-a4cf-11ea-8773-28c6991f4b61.jpg)

**Comment by Battlepixel** [comment]
I ve also noticed this.

**Comment by tsunamayo** [comment]
Issue is fixed in 20w23d. Thanks!
