### ISSUE TITLE
[Bug] Interior overlapping when pasting from station starter

### ISSUE THREAD

**Issue by itsKeq** [tsunamayo/Starship-EVO#2306]
### Short Description of the issue:
Blocks over lap on interior when pasting from new station starter
...

### Steps to reproduce the issue:
pasted from station starter block
...

### Environment
- Starship EVO version: 20w23a
- Graphics Card:RTX2060  

### Additional information:

![20200602133725_1](https://user-images.githubusercontent.com/65949046/83495576-361f7800-a4fb-11ea-9ce9-14b2397a376e.jpg)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
#2305 Dont spend time on that, I am scrubbing that tech! It is too buggy. But I would bery much like if you could make me some neat corridor and stations module in the same style! This time at 1m scale, no station tech. The docking port is gonna be 2mx2m to work on spaceship also.
Sorry again =(
