### ISSUE TITLE
[Bug] Cant paint door on blast door

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Starship-EVO#2310]
### Short Description of the issue:

When painting a blast door you can paint it, but only the frame gets painted, no matter if you're looking at the center of the closed door or the edge.

### Steps to reproduce the issue:

Paint a closed door. The door itself stays the base texture, but the frame changes color.

### Environment
- Starship EVO version: 20w23a
- Graphics Card: 2080 Super OC

**Comment by tsunamayo** [comment]
Okay with new doors...
