### ISSUE TITLE
Focussing of blocks on weapon is not working reliably

### ISSUE THREAD

**Issue by dhelonious** [tsunamayo/Starship-EVO#2311]
### Short Description of the issue:

Blocks connected to weapons on the item stand are hard to focus:

1. Focussing only works at a very close proximity. Otherwise, adding/removing blocks acts on the structure behind the weapon. The same holds for decals.
2. Some faces are only focussable from certain positions and angles, in particular for blocks placed below the weapon handle. I have to use full 6 DOF mode by trial and error to focus them in the end.

### Steps to reproduce the issue:

Place a weapon handle on an item stand and add some blocks to it. Then move away from the item stand and try to focus the weapon and add/remove blocks.

### Environment
- Starship EVO version: pre-alpha 20w23a
- Graphics Card: Radeon RX 470

**Comment by tsunamayo** [comment]
Actually I also noticed this bug and fixed it a couple days ago, fix will be in 20w23b. Thanks!
