### ISSUE TITLE
No preview for decals on weapon

### ISSUE THREAD

**Issue by dhelonious** [tsunamayo/Starship-EVO#2312]
### Short Description of the issue:

Previews for decals on weapons are not correctly drawn on each surface. On some surfaces the decal is not shown, however, one can place them correctly (though one has to do it blindly).

For me, this seems always to occur on faces on the "left" side of the weapon.

### Steps to reproduce the issue:

Place a block on a weapon handly and try to add decals to each face of the block.

### Environment
- Starship EVO version: pre-alpha 20w23a
- Graphics Card: Radeon RX 470

### Additional information:

Screenshots:
![20200602202642_1](https://user-images.githubusercontent.com/6987220/83555994-738e0080-a50f-11ea-9c6f-3f24dc4e3a24.jpg)
![20200602202649_1](https://user-images.githubusercontent.com/6987220/83556001-7557c400-a50f-11ea-822a-adc6946cdd72.jpg)

**Comment by tsunamayo** [comment]
Issue fixed for 20w23d. Thanks!
