### ISSUE TITLE
[Bug] Shipyard bounds only showing when clicked with Link tool [20w23c]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#2316]
### Short Description of the issue:
The shipyard's bounds only show up when the block is clicked with the Link tool, not when the block is selected in the toolbar.

### Steps to reproduce the issue:
Place shipyard block, configure field, hold shipyard block in hand. Field will be invisible; then select link tool and click shipyard block; field will show up.

### Environment
- Starship EVO version: 20w23c
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20200603104401_1](https://user-images.githubusercontent.com/33041786/83658136-67458a00-a587-11ea-8856-9df33386a7f0.jpg)

![20200603104407_1](https://user-images.githubusercontent.com/33041786/83658142-6a407a80-a587-11ea-8f23-ce8ff3cee68f.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4724477/output_log.txt)

**Comment by Sullos** [comment]
Ah, I mentioned this yesterday, I wasn't sure if I was missing something, as I couldn't see the outline of the shipyard with it in the hotbar. But its good to know there is one in general.

**Comment by tsunamayo** [comment]
Yes it is actually normal, I will add a toggle inside the shipyard UI to show the gizmo - I think that will make more sense.
