### ISSUE TITLE
Logical blocks texture out of aligment

### ISSUE THREAD

**Issue by chacalik** [tsunamayo/Starship-EVO#2317]
### Short Description of the issue:
Some blocks that uses interactive textures like logic gates, timers, queries etc. Are getting their texture out of align depending on where you place them. 
...

### Steps to reproduce the issue:
Put some logic gates or queries in diferent positions, behold their icons out of the center of the 3D model. 
...

### Environment
- Starship EVO version: 20w23c
- Graphics Card: AMD Radeon RX590

### Additional information:

![image](https://user-images.githubusercontent.com/4794243/83676723-83f6b780-a5b1-11ea-8945-023083411f0c.png)

**Comment by Sullos** [comment]
I've noticed this too, sometimes it starts happening with timers as well. I think it starts happening once there is a lot of logic bricks placed in general.

**Comment by tsunamayo** [comment]
That is not the first time it was report, but I never managed to reproduce this bug... 
If you could send me your blueprint, send the log file and also tell me more on what you did before seeing this.

**Comment by Sullos** [comment]
I've just been trying to recreate the bug, but I haven't been able to. I believe it might be a long play session related bug. At least I know I usually see it after many hours of playing. Restarting the game fixes the problem so I can't even show examples of where problems did appear.
I have seen the issue appear on a few occasions when I was working on this ship: https://github.com/tsunamayo/Starship-EVO-Backers-Ships/issues/22
However, even going in-game and placing a few hundred logic bricks, I was not able to get the glitch to occur. 
In the event it appears again, I will post my output log and anything I did leading up to it.

**Comment by tsunamayo** [comment]
@Sullos thanks a lot for checking this! Now my guess is that it happens when removing blocks, question is which one? Thanks

**Comment by tsunamayo** [comment]
and by blocks I mean logical blocks of course, but not only logic, system also. Everything that glows or has a dynamic screen, or something dynamic like door ect.

**Comment by chacalik** [comment]
[Gozanti Class Cruiser.zip](https://github.com/tsunamayo/Starship-EVO/files/4726774/Gozanti.Class.Cruiser.zip)

Thats the Blueprint. Although... removing and placing or in the case of logic gates, changing the gate type fixes it.

**Comment by tsunamayo** [comment]
@chacalik you mean you can reproduce that bug when loading the ship straight away? Thanks

**Comment by chacalik** [comment]
![image](https://user-images.githubusercontent.com/4794243/83701687-e2875a00-a5e0-11ea-87f5-887a34d6c700.png)
I just did it, so it seem so... just go for the nose landing gear and put logics randomly... preferably logic gates like this

**Comment by tsunamayo** [comment]
@chacalik thanks, could you guide me to where are those gate?

**Comment by chacalik** [comment]
The landing gears must be downed, its beneath the bridge... Access the pilot yoke if need to lower the landing gears... Although, I believe that anywhere you try to place those gates, since you differ the positions, you'll mostly see it happening

**Comment by tsunamayo** [comment]
![image](https://user-images.githubusercontent.com/6604318/83985381-009fe200-a974-11ea-8c33-4321c8af8549.png)

Okay I cant reproduce this issue.
Do you confirm you simply load the game, then go to that place, put a few logic command and see the bug? Or are you doing something more?
It might be another blueprint corrupting this one, so could you please send me your full character folder? Thanks
