### ISSUE TITLE
[Bug] Reloading after crash resets player position to tutorial building [20w23c]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#2318]
### Short Description of the issue:
If the computer crashes during gameplay, on reloading the save the player can appear in the tutorial building. All entities still present, it just looks like the game reset player position.

### Steps to reproduce the issue:
Don't know yet, will update if I find out how.

### Environment
- Starship EVO version: 20w23c
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4725996/output_log.txt)

**Comment by tsunamayo** [comment]
Okay there is two things: 
1) fixing the issue that lead to the crash. Do you remember anything particular? It seems there was an issue with a handhelp weapon a bit before, not sure if it is related.
I guess it crashed during a save, hence the save corruption. Do you had any weapon equiped (selected or not, just a weapon in your inventory) at this moment?
2) Save backup <- I will work on that so I can restore a previous save if the current is corrupted.
Thanks

**Comment by Dwarf-LordPangolin** [comment]
I'd gone AFK when it happened; I was using a handheld weapon a short while before (made to look like a fish, of all things, so I could make an [aquarium](https://gfycat.com/vastdeliciouseasternglasslizard-starship-evo)). There might have been one still in my inventory.

Didn't notice any corruption, though the reset to tutorial building thing was a bit unusual.
