### ISSUE TITLE
[Question] Elevators

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#2319]
Heyo tsuna, I just wanted to get something clarified before continuing on a larger build. I know you mentioned adding an elevator block system thing for stations and I was curious if this is something you were planning on bringing to ships as well instead of using rails as elevators. If this is the case and you plan to have this system on the ship or standard 1m grid then how might this work? I'm curious so I can plan ahead to avoid having to rebuild a large section(s).

**Comment by tsunamayo** [comment]
Actually with the current plan I no longer need a dedicated block, if you could do that with a normal rail that would be great!
Thanks
