### ISSUE TITLE
[BUG] Unable to disconnect from control yoke after after connecting to turret controller.

### ISSUE THREAD

**Issue by AsageSoftworks** [tsunamayo/Starship-EVO#2320]
### Short Description of the issue:
Control yoke connected to Turret Computer, cannot disconnect from control yoke but player can still use buttons and sit in seat. 
...

### Steps to reproduce the issue:
Connect turret controller to 4 lasers and 2 axis rotors, connect control yoke to 
...

### Environment
- Starship EVO version: Latest 06/03/2020 1400 CDT
- Graphics Card: GTX 1070TI

### Additional information:
https://streamable.com/vw44f8

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\App
[Starship EVO - Copy.zip](https://github.com/tsunamayo/Starship-EVO/files/4726185/Starship.EVO.-.Copy.zip)
Data\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Okay I am not sure to understand 100% the test case. Could you please send me your blueprint and output.log so I can have a look at it? Thanks a lot!

**Comment by AsageSoftworks** [comment]
> Okay I am not sure to understand 100% the test case. Could you please send me your blueprint and output.log so I can have a look at it? Thanks a lot!

Apologies, I thought I had included it. I also included the full save file for the game at time of the bug.
[Starship EVO - Copy.zip](https://github.com/tsunamayo/Starship-EVO/files/4732860/Starship.EVO.-.Copy.zip)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4732862/output_log.txt)

**Comment by tsunamayo** [comment]
Okay thanks indeed it was possible to enter several time a yoke... Fixed for 20w24a. Thanks!
