### ISSUE TITLE
[Bug][Performance] Game freezes when placing blocks.

### ISSUE THREAD

**Issue by MRonlin** [tsunamayo/Starship-EVO#2321]
### Short Description of the issue:
The ship currently has the dimensions of: 936x455x461m When any of the dimensions are increased the game freezes for a few seconds.

...

### Steps to reproduce the issue:
Add blocks which would extend the length, width or height of a large ship. 

...

### Environment
- Starship EVO version: 20w23c
- Graphics Card: gtx 1050

### Additional information:
      I couldn't get any screenshots.

_(Screenshots, Videos, Error logs, Related issues)_

You can find the log here:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4726210/output_log.txt)
 
Here is the blueprint: 
[O'Neill Cylinder Ship (2).zip](https://github.com/tsunamayo/Starship-EVO/files/4726226/O.Neill.Cylinder.Ship.2.zip)

**Comment by tsunamayo** [comment]
Yes this is because of the light volume recompute. It will do a refactoring that will improve the situation. Your station is absolutely massive, the game cant handle it very well atm! Thanks

**Comment by tsunamayo** [comment]
This should no longer be an issue since neovox.
