### ISSUE TITLE
FPS loss/Entity FPS lag and general FPS skips

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#2322]
### Short Description of the issue:
So on that larger spherical build of mine (roughly 240m in diameter) I was just beginning to make a setup for elevator testing with rails and noticed I get extreme fps drops. When it collides with the player my frames drop to about 16 immediately and stay that low while the entity continues on. If I activate the rail without it touching the player, the frames slowly start to get lower and lower as it continues on but goes back to normal when it stops.

I also noticed that my game performance seems worse than what it was before. Even working on the large spherical build was better before some of the recent updates. I'm unsure if I just need to install a fresh version or not but it still seems odd that my frames take that much of a hit with a simple rail.

I'll edit/close this issue should a fresh install fix anything.

...

### Environment
- Starship EVO version: 20w23c
- Graphics Card: GTX 970

### Additional information:
Frames when colliding with the player model:
![20200603162155_1](https://user-images.githubusercontent.com/32974671/83690982-514fbd80-a5b7-11ea-9035-71dda81a0a25.jpg)
![20200603162203_1](https://user-images.githubusercontent.com/32974671/83690989-544aae00-a5b7-11ea-9f1e-97a2a4b3e340.jpg)

Frames back to normal after it stops:
![20200603162216_1](https://user-images.githubusercontent.com/32974671/83691022-5ca2e900-a5b7-11ea-9df1-9b07a62427cc.jpg)

Rail activated without touching the player model and frames drop as it continues moving:
![20200603162224_1](https://user-images.githubusercontent.com/32974671/83691210-6cbac880-a5b7-11ea-9940-db30b2af51a0.jpg)
![20200603162227_1](https://user-images.githubusercontent.com/32974671/83691219-6fb5b900-a5b7-11ea-9618-284941dd4b13.jpg)
![20200603162233_1](https://user-images.githubusercontent.com/32974671/83691230-73494000-a5b7-11ea-9fb7-05a928bcb952.jpg)
![20200603162241_1](https://user-images.githubusercontent.com/32974671/83691236-76443080-a5b7-11ea-90f7-da0181b7aeda.jpg)

**Comment by tsunamayo** [comment]
Your elevator doesnt have a lot of brick so it should not lag. If you could send me the bp so I can have a look at it. Thanks

**Comment by Xerma** [comment]
[Cake Bol 4.zip](https://github.com/tsunamayo/Starship-EVO/files/4726639/Cake.Bol.4.zip)

**Comment by tsunamayo** [comment]
okay what I think happens is that the children entity moving since a few update wakes up the parent one, as it might be colliding with the ground. Then as your big-ass ship is inside the torus, it lags because I dont have yet collisions LOD...
I will see what I can do and keep you posted.

**Comment by tsunamayo** [comment]
Okay I did a quick workaround as I was not checking any torus hull / entity anyway. Fix for 20w23d. Thanks ;)
