### ISSUE TITLE
[Bug] Trapdoors

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Starship-EVO#2324]
### Short Description of the issue:

A few issues with trapdoors appeared recently. 
1. You can fall through trapdoors when you don't have anti-gravity locomotion. If you are walking in an area with gravity, you can fall through the trap door.
2. Existing trapdoors are glitched out. See below.
![711980_20200604093503_1](https://user-images.githubusercontent.com/33239800/83699303-041b2c80-a647-11ea-829e-73bedeadbe50.png)

3. New trapdoors are even more glitched out. See below...
![711980_20200604093609_1](https://user-images.githubusercontent.com/33239800/83699336-185f2980-a647-11ea-8ad0-3cc1eb9962cd.png)

The small white square in the middle of my placement area represents the trapdoor I just placed. I can also, as you can see, place another trapdoor right on top of it. More little white squares will start to appear.

### Steps to reproduce the issue:

Place a trapdoor or view an existing trapdoor.

### Environment
- Starship EVO version:  20w23c
- Graphics Card: 2080 Super OC

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4726694/output_log.txt)

The blueprint that was perfect before most recent updates:
[SX Salvager.zip](https://github.com/tsunamayo/Starship-EVO/files/4726696/SX.Salvager.zip)
Same as https://github.com/tsunamayo/Starship-EVO-Backers-Ships/issues/22

**Comment by tsunamayo** [comment]
Fixed for 20w23d. Thanks a lot!
