### ISSUE TITLE
Sunglare passing through entities

### ISSUE THREAD

**Issue by chacalik** [tsunamayo/Starship-EVO#2327]
### Short Description of the issue:
When aiming player view to the Sun, the red sunglare image is over any entity. Thats a simple visual glitch.
...

### Steps to reproduce the issue:
Place an entity or a building betwen the player and the sun and aim the view for the sun.
...

### Environment
- Starship EVO version: 22w23c
- Graphics Card: AMD Radeon RX590

### Additional information:
![image](https://user-images.githubusercontent.com/4794243/83703187-27ad8b00-a5e5-11ea-8dbd-ff7b5c02e158.png)

**Comment by tsunamayo** [comment]
Issue fixed for 20w25b. Thanks!
