### ISSUE TITLE
[Bug] Unselectable Ports

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Starship-EVO#2328]
### Short Description of the issue:
Ports become unselectable if they are connected to something and then the entity they were connected to gets despawned.
![image](https://user-images.githubusercontent.com/53021785/83704944-cda2ca80-a5d0-11ea-9b88-f56eba782e85.png)

...

### Steps to reproduce the issue:
- Connect two ports
- Unspawn one of the entities
- Try and select the other port
- Issue
...

### Environment
- Starship EVO version: 20w23c
- Graphics Card: Integrated graphics gang

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4726966/output_log.txt)

**Comment by tsunamayo** [comment]
Fixed for 20w23d. Thanks a lot!
