### ISSUE TITLE
[Bug] Unable to reposition connected entities

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Starship-EVO#2329]
### Short Description of the issue:
If two entities are connected incorrectly. One cannot reselect the ports to reposition the incorrectly connected entity.
...

### Steps to reproduce the issue:
- Connect two ports
- Try to reconnect them so you can change the rotation of one
- Issue
...

### Environment
- Starship EVO version: 20w23c
- Graphics Card: Integrated Graphics Gang

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4726973/output_log.txt)

**Comment by Sullos** [comment]
I noticed this too, the only fix is to break and replace the connector door/ring.

**Comment by tsunamayo** [comment]
Fixed for 20w23d. Thanks!
