### ISSUE TITLE
[BUG] Thin Large Lattice Girder improperly centered to grid

### ISSUE THREAD

**Issue by Kadzar** [tsunamayo/Starship-EVO#2332]
### Short Description of the issue:

The new Large Thin Lattice Girder is slightly off-center to the grid, such that it doesn't properly fit inside a 4-block wide area

### Steps to reproduce the issue:

Try to place a Thin Large Lattice Girder between a 4-block wide area, and you will notice that it can't be placed because there is a slight gap on one side and a slight overlap on the other

### Environment
- Starship EVO version: 20w23c
- Graphics Card: NVIDIA GeForce GTX 1080 

### Additional information:

![20200603204847_1](https://user-images.githubusercontent.com/66035211/83706377-ea44ff80-a5dc-11ea-99d9-3e3f2011516a.jpg)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4727049/output_log.txt)

**Comment by tsunamayo** [comment]
Issue fixed for 20w23d. Thanks!
