### ISSUE TITLE
[Bug] Middle clicking custom landing pads causes turrets set to autofire to attack the landing pads

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Starship-EVO#2337]
### Short Description of the issue:

If a turret is set to autofire, if you middle-click a custom landing pad to request landing, the guns will open fire and attack the pad.

### Steps to reproduce the issue:

Middle-click a custom landing pad with turret cores set to auto-fire: On

### Environment
- Starship EVO version: 20w23c
- Graphics Card: 2080 Super OC

I suggest that the solution to this could be to have a switch linked to a turret core that will set the autofire on or off. Otherwise, this could be potential for the new input or output gates you have planned.
People will still want the ability to attack space stations, so I suggest either allowing control via logic to disable or enable autofire, or perhaps adding a hotkey.

**Comment by tsunamayo** [comment]
Yes it is a whole subject as selecting and targeting are the same atm. I will add a no civilian shoot rules, but players needs to overwrite this in case they want to play the bad guy or just shoot a spawning non-aggressive ship.
I am still debating the best approach...
In any case your switch approach will be for when I have my input / output gate.

**Comment by tsunamayo** [comment]
Okay fixed for 20w23d. Thanks a lot for being so active!
