### ISSUE TITLE
Station Module Uploads

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#2340]
I figured I'd put all these in a single place to make them easier to find, and others can in this thread if they want to. :) I'll update my post as-needed.

Current update: added a hub module; it currently only has a partial interior. The finished version will have things like stores, offices, restaurants, etc. Also added a turret/shield module. Next goal is to make a 100m shipyard.

[AAM Station Modules 04132020.zip](https://github.com/tsunamayo/Starship-EVO/files/4774103/AAM.Station.Modules.04132020.zip)

![20200613003041_1](https://user-images.githubusercontent.com/33041786/84560841-34309280-ad0d-11ea-8af1-ad29bf2171a6.jpg)

Old Versions:
[AAM Station Modules 04062020.zip](https://github.com/tsunamayo/Starship-EVO/files/4733630/AAM.Station.Modules.04062020.zip)

**Comment by tsunamayo** [comment]
Amazing, thanks a lot! I will put that lovely apartment module in the game.

**Comment by tsunamayo** [comment]
I just checked it and it is really lovely, I want to live in one of these! Love the aquarium and the plant, the two floor layout is also a great idea!
I wonder if you wanted to do another one (as this one is called small), but if you do could you try to make a vertical one?
Also I think having a continuously rotating dock could allow a lot of interesting design. If I manage to find a solution for a dock in at a bend angle we could make rotating habitat, like the 2001 station.

**Comment by Aiwii** [comment]
[PartyPack.zip](https://github.com/tsunamayo/Starship-EVO/files/4741174/PartyPack.zip)
Still very much WIP (no interiors still) but good enough to send now I wonder how the pcg will work with these...?

Modules:
![image](https://user-images.githubusercontent.com/53021785/83956654-a4c34500-a81d-11ea-887c-c2072e5a4092.png)
2 Hab modules??
1 Corridor
1 4 way
1 landing pad
1 Ring

A station I built with them:
![image](https://user-images.githubusercontent.com/53021785/83956667-bd335f80-a81d-11ea-903c-55913b0976b8.png)

**Comment by itsKeq** [comment]
basic layout hallways and an empty habitat module
all modules are WIP any suggestions are welcome
[modules.zip](https://github.com/tsunamayo/Starship-EVO/files/4741259/modules.zip)
whats included in the pack
![20200607110300_1](https://user-images.githubusercontent.com/65949046/83957844-a852dc80-a8ae-11ea-8b31-f5e6b9b12411.jpg)

**Comment by Dwarf-LordPangolin** [comment]
> I just checked it and it is really lovely, I want to live in one of these! Love the aquarium and the plant, the two floor layout is also a great idea!
I wonder if you wanted to do another one (as this one is called small), but if you do could you try to make a vertical one?

Thank you! I'm really glad you like them; and yes, I can do a vertical one at some point. :+1:

**Comment by tsunamayo** [comment]
Thanks a lot everybody, unfortunately as I am rushing toward ea I didnt had time to check everything, but will do as soon as things clear up a bit!

**Comment by Dwarf-LordPangolin** [comment]
Just wanted to let you know that I'm (finally) getting the interiors done on these. Copy-paste is going to make this infinitely easier; I'm making the halls in 10m segments, which can be copy-pasted as-needed, which should speed this up a ton.

![20210107031628_1](https://user-images.githubusercontent.com/33041786/103877953-62a3ff80-509b-11eb-9eb5-fa05cc018d44.jpg)

![20210107035100_1](https://user-images.githubusercontent.com/33041786/103878093-93843480-509b-11eb-83fc-7fa266ad6a55.jpg)

**Comment by Dwarf-LordPangolin** [comment]
Hi! A looong time back [you asked for](https://github.com/tsunamayo/Starship-EVO/issues/2351#issuecomment-640211519) drydock-style landing areas. I finally got around to making one if you still need that. This is a rough draft, since it sounds like the removal of the voxel system will require stuff like this to have a little work done on it later; that will be really easy for this though, since a lot of the blocks used for the exterior have measurements that are multiples of 4, so bigger blocks should align with this easily.

![20210322210858_1](https://user-images.githubusercontent.com/33041786/112082665-c0e96600-8b53-11eb-84be-08d6bed8d503.jpg)

![20210322210915_1](https://user-images.githubusercontent.com/33041786/112082673-c2b32980-8b53-11eb-80bc-69c0186b4554.jpg)

![20210322211636_1](https://user-images.githubusercontent.com/33041786/112082774-e8d8c980-8b53-11eb-8ecd-c9f04dc6e94f.jpg)

[AAM Station Module - 100m Shipyard.zip](https://github.com/tsunamayo/Starship-EVO/files/6186436/AAM.Station.Module.-.100m.Shipyard.zip)

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Amazing, let me check this! It look like the old one from the greenlight trailer...
Yep dont spend too much time on stations atm it as I think I will want slightly bigger on, I need to check with you guys if it could be feasible.
The funny think is that if you recall I had a botched attempt at large voxel (4m) last year, I gave up because it was too complex.
With the new tech you would get:
- mix of small and large block, no interior vs exterior bullshit.
- much larger block (I could do 16m or 64m blocks for the space habitat)
- better performance
- muuuch simplier code
Total win!
I am still working on decommissioning voxels at the level of the collisions, it is taking a bit of time but should be completed soon. Thanks

**Comment by tsunamayo** [comment]
As it is a bit old I will close this, but you can re-open if you have anything new!
