### ISSUE TITLE
[Bug] Singularity.

### ISSUE THREAD

**Issue by MRonlin** [tsunamayo/Starship-EVO#2341]
### Description of the issue:

**Sorry for the long description.**

This is quite an interesting bug. When going into the picture mode [F6] on my big ship, I went to go take a screenshot using [F12] I miss clicked and pressed [F8], it spawned a bunch of character models with a **Black Orb** floating above them (I think related to this bug #2233). 

Something like this, but without the ship and with a **Black Orb** instead.
![20200605161048_1](https://user-images.githubusercontent.com/64201628/83894560-5ba1c100-a749-11ea-948e-d1e933ef01a9.jpg)

In my curiosity I pressed [F8] again (I would soon come to regret that choice). It spawned a ship within my ship, When I saw a force field appear, I knew I shouldn't have pressed [F8], 

I didn't get to see what ship it spawned but Im sure it was the default ship. Due to the ship "spawning", this bug occurred #2219. I was experiencing 1 fps now, and then not only did my ship disappear but the sun, the planets and the ring also disappeared.

I was experiencing about 2 fps when I took this picture. I looked around, but saw nothing but empty space. I tried to use teleport but I still saw nothing.
![20200605153459_1](https://user-images.githubusercontent.com/64201628/83894682-8724ab80-a749-11ea-885a-61e536dfc99a.jpg)

After this I left the game, waited, and then reloaded the save. The sun and the planets were back, I was still out in empty space, but teleport worked now, so I teleported to the tutorial area _on_ the ring. However it was not _on_ the ring.

All the ships, hovercraft's and buildings I had on the ring (which were far apart from each other on the ring) were seemingly ripped from the ring (possibly an act of anger by God Chatdethon). (Some of them were even clipping through walls, it looked like they had been pulled into some kind of _**Singularity**_ .

![20200605153535_1](https://user-images.githubusercontent.com/64201628/83895236-52fdba80-a74a-11ea-934b-7c9f2200f65c.jpg)

![20200605153556_1](https://user-images.githubusercontent.com/64201628/83898408-c73a5d00-a74e-11ea-9d77-e5a5f8fa7c73.jpg)
![20200605190257_1](https://user-images.githubusercontent.com/64201628/83913892-16d95280-a768-11ea-9b1d-7cf8f97f2b7d.jpg)
![20200605190235_1](https://user-images.githubusercontent.com/64201628/83913909-1ccf3380-a768-11ea-8f42-707b01245861.jpg)

I went down to ring, but saw nothing out of the ordinary, besides from all the builds being in space.

I then teleported to some of my other blueprints, I saw the same thing. All of the nearby ships had been pulled together. Clipping through each other.
![20200605153722_1](https://user-images.githubusercontent.com/64201628/83895882-344bf380-a74b-11ea-92f2-081857f7df98.jpg)

I finally teleported back to my big ship, it was still their, the ship I spawned which had caused all of this had disappeared, along with the floating character models and it seemed like everything was back to "normal".

Here is were it all began.
![20200605153843_1](https://user-images.githubusercontent.com/64201628/83896398-00250280-a74c-11ea-8298-2c11facf52c2.jpg)

  

...

### Steps to reproduce the issue:
Im not sure if this is fully repeatable.
Large ship, go into picture mode (Im not sure if going into picture mode effects this.), Press F(8) repeatedly.  

...

### Environment
- Starship EVO version: 20w23c
- Graphics Card: gtx 1050

### Additional information:
The log:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4737195/output_log.txt)

Please also include the `output_log.txt` file. You can find your log here: ``

**Comment by tsunamayo** [comment]
Hi, I think this issue should be fixed now. thanks
