### ISSUE TITLE
[Bug] Stretched textures on brick wedge

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#2342]
### Short Description of the issue:
When stretched, the texture on brick wedge also stretches
![image](https://user-images.githubusercontent.com/27857711/83905175-256c3d80-a759-11ea-9d90-4d9d72258bae.png)
Oddly, this only happens when the wedge is only stretched in one orientation
![image](https://user-images.githubusercontent.com/27857711/83905427-91e73c80-a759-11ea-9bad-4bb35bd04f5b.png)

### Steps to reproduce the issue:
Stretch a brick wedge on any ship in two different orientations and note the different textures

### Environment
- Starship EVO version: 20w23c
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
Issue fixed for 20w25d. Thanks!
