### ISSUE TITLE
Girder blocks not correctly orienting when using mirror mode

### ISSUE THREAD

**Issue by Misteropie** [tsunamayo/Starship-EVO#2348]
### Short Description of the issue:

When working on any build and using mirror mode all girders will not use the proper orientation when placed. It is more apparent on the XL girder blocks like the thin one.

### Steps to reproduce the issue:

Use mirror mode on a build, place a girder.

### Environment
- Starship EVO version: 20w23c
- Graphics Card: Nvidia GTX 1080

### Additional information:

![image](https://user-images.githubusercontent.com/66394949/83943805-a821e680-a7b3-11ea-96d0-31aafa5df276.png)
On the image above the two girders on the center were placed with mirror mode on, while the outside girders were placed with mirror mode off. The outside blocks are the desired orientation.

When testing this I thought I'd check the others to be safe and the XL blocks had some interesting interactions with mirror mode. Below is a picture with all girder blocks in the game. The larger ones share the same issue with the smaller ones but they also have the issue of not being placed in the right spot.

![image](https://user-images.githubusercontent.com/66394949/83943915-86752f00-a7b4-11ea-910e-18c95436f950.png)

**Comment by tsunamayo** [comment]
Okay fixed for 20w24a. Thanks!
