### ISSUE TITLE
Ringworld only visible to host on multiplayer

### ISSUE THREAD

**Issue by TwoNiner29** [tsunamayo/Starship-EVO#2349]
### Short Description of the issue:
In multiplayer, the ringworld disappears for everyone except the host.
...

### Steps to reproduce the issue:
connect to a multiplayer server
...

### Environment
- Starship EVO version: 20w23c
- Graphics Card: Nvidia Geforce GTX 1060

### Additional information:

![20200607023623_1](https://user-images.githubusercontent.com/66531332/83952104-fcd36900-a868-11ea-899c-447250ec1b41.jpg)
spawn building and the tutorial platform are still there but the ring itself is missing. players who are not the host can fly through the ring and not be affected by gravity, as if the ring does not exist at all. Only the host can interact with the ring.

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4740811/output_log.txt)

**Comment by TwoNiner29** [comment]
we've tested this with 4 players and all have the same issue

**Comment by tsunamayo** [comment]
Thanks for testing and reporting issues on multiplayer! Issue fixed for 20w23d. Thanks!
