### ISSUE TITLE
[Suggestion] Separate Weapons from Systems in the Codex 

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Starship-EVO#2350]
### Short Description of the Suggestion:
Weapons and their add-ons currently make up 50% ish of the systems group in the blocks tab of the codex. I suggest weapons be moved to their own group with their own header especially if more weapon blocks are to come in the future.
...

### Environment
- Starship EVO version: 20w23c

**Comment by tsunamayo** [comment]
Yes I was thinking of doing that too.

**Comment by tsunamayo** [comment]
Done for 20w24a. Thanks
