### ISSUE TITLE
[BUG] cant land on shipyard (sometimes)

### ISSUE THREAD

**Issue by Womble-TC** [tsunamayo/Starship-EVO#2352]
### Short Description of the issue:
When using a shipyard, I request a landing using any ship. However, once entering the area of the shipyard, my ship stops moving, and I continuously get this pop-up every few seconds: 
![image](https://user-images.githubusercontent.com/29961381/83970019-21602d00-a8cb-11ea-8820-4d275c43c043.png) After this, I can't move the ship unless I cancel the process. The landing gear also do not deploy.

As mentioned in the title, this only happens about 50% of the time, and I'm not 100% sure what causes it (sorry about that). I think it has something to do with the enter direction, but I'm not sure.

### Environment
- Starship EVO version: 20w23d
- Graphics Card: GTX 970

**Comment by ProPeach** [comment]
[Starship EVO Shipyard Docking Bug.zip](https://github.com/tsunamayo/Starship-EVO/files/4742152/Starship.EVO.Shipyard.Docking.Bug.zip)
Here's a video of what's happening, I can't determine a cause either. The ship will rotate into the landing orientation (which is a super cool feature) and land successfully around 1 in 3 times although it is quite bumpy still when the ship is coming down.

**Comment by anunes30-ford** [comment]
Mine does this 100% of the time on landing pads and dry-docks that I create, the ship will also orientate facing 45 degrees between the up direction and the forward direction

**Comment by tsunamayo** [comment]
@anunes30-ford @Womble-TC  send a blueprint so I can investigate, both your landing pad and ship.
Thanks!

**Comment by Aiwii** [comment]
[S5 Small Landing Pad.zip](https://github.com/tsunamayo/Starship-EVO/files/4743181/S5.Small.Landing.Pad.zip)

**Comment by tsunamayo** [comment]
also output.log could help! Thanks

**Comment by tsunamayo** [comment]
I think @Womble-TC issue is different, it seems that there is an issue of some kind.
Then for @Aiwii it is because the pad is also moving when the ship is landing on it, I will work on that anchor block to solve this.

**Comment by anunes30-ford** [comment]
The dry-dock:
[Shipyard.zip](https://github.com/tsunamayo/Starship-EVO/files/4745421/Shipyard.zip)
A ship that the bug happens for (although it happens for every ship that I try):
[Mako Corvette.zip](https://github.com/tsunamayo/Starship-EVO/files/4745422/Mako.Corvette.zip)
Log:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4745423/output_log.txt)

**Comment by tsunamayo** [comment]
Okay I think I already fixed those issue earlier in the week as I dont reproduce them. If not please ping me! Cheers
