### ISSUE TITLE
[Bug] Player is pushed out of the yoke and seat when in a shipyard

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#2354]
### Short Description of the issue:
When a ship lands, control of the ship is taken away from the player and they're ejected from the yoke and seat if they're sitting down. If a player tries to enter the yoke of a ship while a ship is docked and tries to close the undock/repair menu the same thing happens.
This is frustrating if you just want to sit in your ship for a little while on the docking pad, or use the 3rd person view to look around. At the very least it should not eject you from your seat.

### Steps to reproduce the issue:
Dock a ship to a station, notice that you are ejected from the yoke and seat
Try to control a ship that is docked and close the repair/undock menu

### Environment
- Starship EVO version: 20w23d
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
Can you send me your blueprint I dont have that issue. Thanks!

**Comment by ProPeach** [comment]
Sure, here's the blueprint I was using. However, this happened in any ship that I piloted including the Mistral
[Shuttle9.zip](https://github.com/tsunamayo/Starship-EVO/files/4743344/Shuttle9.zip)

**Comment by tsunamayo** [comment]
But you mean you are ejected once you close the windows right?

**Comment by tsunamayo** [comment]
Okay I guess it was the case, issue fixed for 20w24a. Thanks!
