### ISSUE TITLE
[Bug] Manoeuvring thrusters firing and ship wobbling in Lightcruise

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#2355]
### Short Description of the issue:
When in Lightcruise, the manoeuvring thrusters on a ship fire randomly and constantly and the dynamic camera wobbles a little too
https://i.imgur.com/nLlOrPd.gifv

Also, the option to "Engage Supercruise" is still in the menu. Is this still correct, or is "Lightcruise" the new name?

### Steps to reproduce the issue:
Engage lightcruise in any ship

### Environment
- Starship EVO version: 20w23d
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
Both issues fixed for 20w24a, thanks a lot!
