### ISSUE TITLE
Ships Lags When Getting Close To A Station

### ISSUE THREAD

**Issue by BrickMacklin** [tsunamayo/Starship-EVO#2356]
When getting close to a station with my ship the game drops a ton of FPS. It isn't gradual. Once it is within several blocks the FPS goes down. Below is a video showing it.

...

Load in a large ship and go to a station. I will link one of my vessels.

...

### Environment
- Starship EVO version: 20w23d
- Graphics Card: 2080 Ti

### Additional information:

https://youtu.be/_eo7rdQfGu4

[Paris Frigate.zip](https://github.com/tsunamayo/Starship-EVO/files/4742311/Paris.Frigate.zip)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4742308/output_log.txt)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Yes it is because of the collision engine, I havent implemented a LOD yet for larger ship like yours. Amazing ship btw!

**Comment by BrickMacklin** [comment]
@tsunamayo awesome, looking forward to that. Thanks for the feedback!

**Comment by tsunamayo** [comment]
This should be fixed in 20w26a. Thanks!
