### ISSUE TITLE
cant go up with moving platforms connected to a railing (elevators)

### ISSUE THREAD

**Issue by darkvoid305** [tsunamayo/Starship-EVO#2357]
### Short Description of the issue:
when standing on the platform and trying to go up the character will glitch through the platform 
...

### Steps to reproduce the issue:
stand on elevator try to go up
...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
What is your locomotion mode? Thanks

**Comment by darkvoid305** [comment]
walking modus

**Comment by tsunamayo** [comment]
Okay it is a bit of a workaround for now but it is working on elevator. Fix for 20w24a. Thanks!
