### ISSUE TITLE
[Bug] Can't set ship AI to hostile

### ISSUE THREAD

**Issue by Calvert4096** [tsunamayo/Starship-EVO#2359]
### Short Description of the issue:
Unable to set ship or station AI to hostile; pressing F on starter block currently seems to only provide options for "Load Station Module." Spaceship computer menu does not appear to have this option, though I believe it wasn't here previously.

### Steps to reproduce the issue:

Load existing ship or create new ship with starter block; access starter block menu with "F"

### Environment
- Starship EVO version: pre-alpha 20w23d
- Graphics Card: AMD Radeon HD 7800 Series (ID=0x679e)

### Additional information:

![image](https://user-images.githubusercontent.com/65469633/83979186-510a3780-a8c1-11ea-9bb2-023dd6c00988.png)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4742847/output_log.txt)

**Comment by anunes30-ford** [comment]
Also cannot move terrain buildings up/down anymore

**Comment by tsunamayo** [comment]
Fixed for 20w24a. Thanks!
