### ISSUE TITLE
[Suggestion] Procedural ellipses, cylinders, and ellipsoids

### ISSUE THREAD

**Issue by Calvert4096** [tsunamayo/Starship-EVO#2363]
I think it would be a huge time-saver for builders to have a procedural tool for procedural elliptical cylinders and ellipsoids.

Some potential tool options:
-Cylinder vs. ellipsoid (cylinder of length = 1 would be just a flat ellipse or circle)
-Choose X/Y/Z axis direction using Q/E (cylinders only)
-Solid vs. Shell
-"Smooth" surface using triangle blocks (screencap 1) vs. cubic voxel only (screencap 2)

Screencap 1 (courtesy of Aiwi):
![image](https://user-images.githubusercontent.com/65469633/83980984-cb8d8400-a8ce-11ea-8cbd-1ba887e22f04.png)

Screencap 2:
![image](https://user-images.githubusercontent.com/65469633/83981109-db599800-a8cf-11ea-9b6f-54dcc7235f2f.png)

**Comment by ZachZent** [comment]
I'd love to see a web application for circles in SEVO similar to the ones you see for Minecraft

**Comment by Calvert4096** [comment]
For design purposes I've just been using MS paint -- personally I find that adequate for that purpose.  I'm hoping there's a way we can avoid busywork to actually build them in-game, however.
