### ISSUE TITLE
Collision and selection mesh for some bricks/blocks misshapen or too large

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#2364]
### Short Description of the issue:

Some bricks have a full cube mesh when they look to have areas of space (hollow wedge, beveled brick, pipe corner). Others have mesh that only covers the middlemost portion of the brick and makes it impossible to select/build/delete unless you target their center (the round tile bricks).

Some blocks have full cubic mesh where there is ample empty visual space (large pipe corner, curved hull, quarter sphere hull).

I know I've mentioned the curved hull in another post. I've just included them here to be thorough.

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4743182/output_log.txt)

### Environment
- Starship EVO version: 20w23d
- Graphics Card: Nvidia GeForce GTX 1060 6GB

![20200607181700_1](https://user-images.githubusercontent.com/51390907/83981885-fe943f80-a8ef-11ea-88ae-d05df417d99e.jpg)
![20200607181706_1](https://user-images.githubusercontent.com/51390907/83981886-ff2cd600-a8ef-11ea-97e6-3c3239c618b1.jpg)
![20200607181803_1](https://user-images.githubusercontent.com/51390907/83981887-ff2cd600-a8ef-11ea-8c9a-fb0e5f0f2fa9.jpg)
![20200607181813_1](https://user-images.githubusercontent.com/51390907/83981888-ff2cd600-a8ef-11ea-9e82-216739d55e80.jpg)
![20200607181842_1](https://user-images.githubusercontent.com/51390907/83981889-ffc56c80-a8ef-11ea-9c09-d5f7c55076c2.jpg)
![20200607181856_1](https://user-images.githubusercontent.com/51390907/83981890-ffc56c80-a8ef-11ea-9c01-6917a191e7e6.jpg)
![20200607182011_1](https://user-images.githubusercontent.com/51390907/83981891-ffc56c80-a8ef-11ea-83be-4b521666425d.jpg)
![20200607182018_1](https://user-images.githubusercontent.com/51390907/83981892-005e0300-a8f0-11ea-9a68-12804251ad7c.jpg)

**Comment by tsunamayo** [comment]
Okay I will try to fix as many as I can but it will always stay a bit wonky, collisions shape are approximation by nature and I cant make a tight one for each of them.
