### ISSUE TITLE
[BUG][20w23d] hud not highlighting targets correctly when turned away.

### ISSUE THREAD

**Issue by LazyZarra** [tsunamayo/Starship-EVO#2367]
### Short Description of the issue:

fly flying around, if I'm not pointing directly at my target, the hud will miss align the target highlight corners

...

### Steps to reproduce the issue:

... just play the game I guess?

### Environment
- Starship EVO version: 20w23d
- Graphics Card: RTX2080
- Game resolution 3840 x 2160

### Additional information:

in the screenshot below, the center of my aim is just beneath those those small bodies of water in among the hills there. the target I've selected is pad 1, I have my mouse cursor roughly on it. however the actual targeting brackets (is that the correct term for those four corners?) are offset to the left of the actual target. the more right I aim my ship, the more left those brackets go. only if I align my ship directly at the target do the brackets align as well.

![20200608163105_1](https://user-images.githubusercontent.com/39645615/84043197-4bd2e880-a9a6-11ea-8d5a-3a092eeb4a3b.jpg)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4746615/output_log.txt)

**Comment by tsunamayo** [comment]
Hum my guess is that is linked to your screen resolution, it works fine for me. Let me check this.

**Comment by LazyZarra** [comment]
that was my thought as well. I game on a 4k monitor, if you need me to try anything, let me know.

**Comment by LazyZarra** [comment]
it is looking like any resolution above 1920 x 1080 will get the issue. The higher the resolution, the more offset the targeting brackets are from the actual object.
I game on a 4K monitor so I really don't want to drop the resolution below 3840 x 2160 if I can help it.

**Comment by tsunamayo** [comment]
@LazyZarra Issue fixed for 20w25b. Thanks!
