### ISSUE TITLE
[BUG] Wrong speed units

### ISSUE THREAD

**Issue by alxnns1** [tsunamayo/Starship-EVO#2368]
### Short Description of the issue:

The largest unit measuring speed in the game is shown as Mm/h but seems to actually be Mm/s by my measurements which would be consistent with the other units of m/s and km/s.

### Steps to reproduce the issue:

Go fast

### Environment

- Starship EVO version: 20w23d
- Graphics Card: GTX 1050 Ti

**Comment by tsunamayo** [comment]
Fixed for 20w24a. Thanks!
