### ISSUE TITLE
indoor shipyards don't work

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#2370]
### Short Description of the issue:

trying to get a ship to dock in the hanger appears to be impossible, regardless of directions set, it seems to try to spin upside down gets stuck. 

failure to dock and subsequent cancellation causes the shipyard interface to duplicate resulting in multiple shipyard instances.

### Steps to reproduce the issue:
Using the provided blueprints, attempt to dock in the station, configure the shipyard block in the hanger however you wish.  if the issue is that shipyards need significantly more space to maneuver, let me know. as even docking when facing the correct way caused a spin.
...

### Environment
- Starship EVO version: 20w203d
- Graphics Card:  vega 56

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
[blueprints.zip](https://github.com/tsunamayo/Starship-EVO/files/4750121/blueprints.zip)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4750123/output_log.txt)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by pinesh** [comment]
I'd like to add that after some further testing, it looks more like landing pads just require more space to work around, however the duplication of the interaction is a real bug, breaking a shipyard and placing another in the same spot leaves two interactable shipyard fields.

**Comment by tsunamayo** [comment]
Okay fixed for 20w24a. Thanks!
