### ISSUE TITLE
[Suggestion] AI ship/station color variability

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#2372]
Don't worry, this isn't about the color pallet (though the dark green is still way too light)

I been thinking that even if all the KS ships are made, the player will probably come across the same ship a few times or the same type of station. This isn't the end of the world nor can it be avoided. To add some variability, I suggest a type of paint that will pick a random color when an AI ship is spawned. Many players paint their ships in three colors: primary/base color, secondary color, and detail color. By painting the detail color with this tool, NPC ships that spawn in won't be exact copies of each other. This would be a dev tool, not available to every player. Just the ones who are adding a ship to the game.

For example Dwarf's ships/stations color scheme is usually light grey base, blue secondary, and orange detail. The orange would be painted with this tool. That way it will spawn with the orange detailing in one sector and a red detailing in another. This will also work for NPC factions. They can have some dedicated ships, assuming that is part of the plan, but the faction can have additional "faction civilian" ships with their color.

Of course this would be in the future, but something to think about to give AI ships a bit of variability when spawning.

**Comment by tsunamayo** [comment]
Yes I was thinking the same thing, I need to think more about how it could merge or not with the come back of custom colors.

**Comment by ZachZent** [comment]
It would probably use the sameish tech as custom colors, but I don't think it would need to be merged. Players won't be changing their ship's colors when spawned since it is for themselves/factions. It will be painted red and black for the faction or because they want it painted that way in the first place. It's why I suggested it as a hidden dev tool. It would only, or at the least most useful for ships being added as NPC ships.
