### ISSUE TITLE
[Suggestion] Bring Back Middle Click Align to Entity

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Starship-EVO#2373]
### Short Description of the suggestion:
Not urgent or anything. True 6dof Movement mode is great and all but the Align to entity function is quick and easy. I remember you saying you want to revamp the middle-click menu so when you do please bring back the Align to Entity function, it would be great to have alongside true 6dof.
...

### Environment
- Starship EVO version: 20w23d

**Comment by tsunamayo** [comment]
honestly I was not a fan of the middle click to align feature, what do you want to do, align to ship that dont have gravity?

**Comment by Aiwii** [comment]
In my opinion, it helps when working on a bunch of projects in close proximity that don't have gravity and are not aligned with each other. But now that I think about it I should use gravity more

**Comment by ZachZent** [comment]
I agree. Not all ships have gravity, either at all or just hasn't been placed yet. It is quite annoying needing to readjust yourself each time when there was such a convenient feature. And it's survival mode friendly.

**Comment by tsunamayo** [comment]
@ZachZent werent you one of the guy pushing for 6dof? I dont know a lot of people were pushing hard on me for 6dof, for that exact reason. Like being aligned was being the worst thing, when you want to work beneath your ship and so on.

**Comment by orangep9** [comment]
I think the best option would be a key in 6dof that aligns you to the grid your looking at or if your not looking at a grid the last grid you placed an object on. Having a quick menu to change movement types would be great too.

I imagine this feature used for example so I can rotate sideways to place somthing then as Im moving back to work on something else I can quickly rotate back while moving regardless of if im facing the ship.

**Comment by tsunamayo** [comment]
You can now selected any mode you want with the J key (for 21w03b) thanks
