### ISSUE TITLE
Brick offset when built on lattice girder, thin.

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#2375]
### Short Description of the issue:
Placing a brick on a lattice block thin side will be offset slightly compared to the standard brick grid.
...

### Steps to reproduce the issue:
place a brick on the side of a girder and compare it to a brick placed on something else. They'll be off like in the screenshot.
...

### Environment
- Starship EVO version: 20w23d
- Graphics Card: Vega 56

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![image](https://user-images.githubusercontent.com/14081996/84226564-f1658500-aa96-11ea-854c-02a3962f631a.png)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Isse fixed for 20w25a. Thanks!
