### ISSUE TITLE
CRASH - Loss of monitor signal after game freeze. 

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#2378]
### Short Description of the issue:
Crash to no signal monitor, ctrl-alt delete to recover. 

### Steps to reproduce the issue:
unknown, sending report. 
...

### Environment
- Starship EVO version:  20w23d
- Graphics Card:  Vega 56

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4760201/output_log.txt)
 find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
It is really weird, it seems to be related to the saving that fails. Could you send me your Character save folder? Thanks

**Comment by pinesh** [comment]
certainly
[Starship EVO-bugged.zip](https://github.com/tsunamayo/Starship-EVO/files/4766882/Starship.EVO-bugged.zip)
