### ISSUE TITLE
[Bug] Overlapping UI elements

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Starship-EVO#2380]
### Short Description of the issue:
The New item popup that appears when something is selected with the link tool is obstructed by the mechanism stats popup. This occurred at 1280x720
![image](https://user-images.githubusercontent.com/53021785/84320373-caf32880-ab2e-11ea-9e29-24bd10d7fcdb.png)

...

### Steps to reproduce the issue:
- Link something to a mechanism
- Issue
...

### Environment
- Starship EVO version: 20w23d
- Graphics Card: Integrated gang

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4761343/output_log.txt)

**Comment by tsunamayo** [comment]
Yes sorry this is a new workflow that is supposed to replace the older windows. If will remove it and migrate it completely! Thanks

**Comment by tsunamayo** [comment]
I trashed that UI it was bugging big time - I will catch up with the new one.
