### ISSUE TITLE
[Bug] Gravity Affected Station Modules

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Starship-EVO#2381]
### Short Description of the issue:

I connected a new rib yard dry dock module to my station that I had worked on. If no ship is docked in the dry dock, I can place blocks on the rib yard and all is fine. However, if I fly a ship into the rib yard and dock, everything is fine until I place a block on the Station. If I place something then the gravity of the ships, despite not touching the rib yard, affects it.

### Steps to reproduce the issue:

Dock a ship that has gravity in a shipyard / drydock, place a block on drydock, the drydock module/entity should update after the block is placed and experience the gravity of the ship docked in it.

### Environment
- Starship EVO version: 20w23d
- Graphics Card: 2080 Super OC

### Additional information:
Before:
![711980_20200611123054_1](https://user-images.githubusercontent.com/33239800/84338452-70fe6b80-abdf-11ea-95ec-29322d784bd7.png)

After:
As you can see below, my ribyard 'fell' onto my ship and both went drifting off into space.
![711980_20200611122314_1](https://user-images.githubusercontent.com/33239800/84338213-d736be80-abde-11ea-9647-a5ed9607ff5e.png)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4762208/output_log.txt)

**Comment by tsunamayo** [comment]
Yes it is because I need to give you the anchor block, making your station completely stationary. I am working on it!

**Comment by Sullos** [comment]
Sorry about that, wasn't sure if it was a bug or something else. I forgot about the anchor block WIP
