### ISSUE TITLE
Landing pad small ship bug - hover/freeze/loop [Bug]

### ISSUE THREAD

**Issue by Vadenn** [tsunamayo/Starship-EVO#2382]
### Short Description of the issue:
Autopilot freezing up and not descending after being guided to landing pad, as well as some instances of wobbling 
![auto pilot jamm](https://user-images.githubusercontent.com/66177563/84338127-82506500-ab58-11ea-9d2f-a048682ab831.png)

...

### Steps to reproduce the issue:
Try to dock at the 2nd auto-spawn space station landing pads with a small ship, the oculus specifically, it will mostly freeze a few meters from the landing pad with the autopilot continually notifying you to head towards the pad
...

### Environment
- Starship EVO version: 20w23d
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[output_log - Copy.zip](https://github.com/tsunamayo/Starship-EVO/files/4762218/output_log.-.Copy.zip)

**Comment by Sullos** [comment]
I notice this at random too, I haven't been able to recreate it efficiently. However, for me, I was able to fix it on a case by case basis, by simply canceling docking, flying away, and requesting docking once again.

**Comment by tsunamayo** [comment]
@Vadenn could you send me the ship blueprint? thanks

**Comment by Vadenn** [comment]
@tsunamayo 
Here you go, I included two versions, the one I had been testing with more thrusters, as well as the original.
[NEA X-On Oculus 2.0 Test.zip](https://github.com/tsunamayo/Starship-EVO/files/4767297/NEA.X-On.Oculus.2.0.Test.zip)
here you go 
[NEA X-On Oculus 2.0.zip](https://github.com/tsunamayo/Starship-EVO/files/4767298/NEA.X-On.Oculus.2.0.zip)

**Comment by tsunamayo** [comment]
I managed to land successfully in 20w24c. It was a bumby landing but it was fine.
Do you still see this in 20w24c? Thanks

**Comment by tsunamayo** [comment]
@Sullos did you still saw this in 20w24c if you played on that one? Thanks!

**Comment by Sullos** [comment]
So I am still seeing this issue in my test case. My test case is using a dry dock shipyard though not a small landing pad. However, the results are very much the same.

I tried in the exact same manner as I did last time, and it seems as though, sometimes at random, when approaching a shipyard, it locks up and leaves you at a distance. See below..
![711980_20200616094511_1](https://user-images.githubusercontent.com/33239800/84716431-6e708d00-afb6-11ea-8dbe-31eebbd0c4a5.png)

Here is my output log up till the moment just after my attempt, hopefully, it reveals something.
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4783529/output_log.txt)

I simply selected the landing pad, and approaching it, but once I get close enough to be pulled in by the autopilot, it has trouble and freezes up. 
Here is my character folder, I have the ship and the dry dock I've been using all lined up in case you need to try it yourself. It happened twice in a row.
[sullos new character folder.zip](https://github.com/tsunamayo/Starship-EVO/files/4783538/sullos.new.character.folder.zip)

Let me know what else I can do, eager to help! 
Thanks

**Comment by tsunamayo** [comment]
@Sullos I guess it is fixed I was not able to reproduce. If I am wrong tell me! I had an issue though, there was a circular reference in your docking so it was making your station bug. I fixed the bug that allowed you to do that, but you will have to manually unspawn the faulty solar panel to fix it on your side.
Very cool station btw, I had lag issue in the asteroids though... 
Cheers
