### ISSUE TITLE
[Bug] bulid menu and flight controls overlap 

### ISSUE THREAD

**Issue by itsKeq** [tsunamayo/Starship-EVO#2383]
Can not leave yoke have loaded in an other save yet  the player is locked in that save also.

### Environment
- Starship EVO version: 20w23d
- Graphics Card:RTX2060

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![20200611100512_1](https://user-images.githubusercontent.com/65949046/84341130-b9b92300-abe5-11ea-8fb9-cd95336c8a3c.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4762387/output_log.txt)

**Comment by tsunamayo** [comment]
Could you please send me the folder zipped of your character?

**Comment by itsKeq** [comment]
[keqi.zip](https://github.com/tsunamayo/Starship-EVO/files/4762580/keqi.zip)

**Comment by tsunamayo** [comment]
Okay good to know!
