### ISSUE TITLE
[Bug] Invisible starter block

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Starship-EVO#2385]
### Short Description of the issue:

Starter block is invisible.

### Steps to reproduce the issue:

![711980_20200611143707_1](https://user-images.githubusercontent.com/33239800/84345667-49180380-abf1-11ea-950e-95a0850af290.png)

### Environment
- Starship EVO version: 20w24a
- Graphics Card: 2080 Super OC

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Issue fixed for 20w24b. Thanks!
