### ISSUE TITLE
[Bug] Missing tutorial zone

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Starship-EVO#2386]
### Short Description of the issue:

Some of the tutorial buildings are missing

### Steps to reproduce the issue:

![711980_20200611142641_1](https://user-images.githubusercontent.com/33239800/84345723-71076700-abf1-11ea-8c74-025ff1f29a7b.png)

### Environment
- Starship EVO version: 20w24a
- Graphics Card: 2080 Super OC

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Issue fixed for 20w24b. Thanks a lot!
