### ISSUE TITLE
[Bug] Not all things in codex where they should be

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Starship-EVO#2387]
### Short Description of the issue:

A codex item is out of its place. The large overheat addon.

Also, the Stations category is still down the bottom. I wasn't sure if it was staying or not.

### Steps to reproduce the issue:

![711980_20200611144420_1](https://user-images.githubusercontent.com/33239800/84345948-20443e00-abf2-11ea-8324-681a75680cd3.png)

### Environment
- Starship EVO version: 20w24a
- Graphics Card: 2080 Super OC

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Issue fixed for 20w24b. Thanks for being on the ball! Cheers
