### ISSUE TITLE
[Bug] Broken mirroring axis planes

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Starship-EVO#2389]
### Short Description of the issue:
When using the mirror tool, if you try pressing Q and cycling through Blue Green and Yellow planes, the Green and yellow are invisible, I also found that my character could not really move. Like I was stuck.

### Steps to reproduce the issue:

Equip the mirror tool, aim at an entity, cycle through the planes of symmetry with Q! E still works!

### Environment
- Starship EVO version: 20w24a
- Graphics Card: 2080 Super OC

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4762663/output_log.txt)

**Comment by tsunamayo** [comment]
Fixed for 20w24b. I will do a patch soon. Thanks!
