### ISSUE TITLE
[Bug]/[Suggestion] Lots of junk in the world

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Starship-EVO#2390]
### Short Description of the issue:
In-game, there's a lot of entities floating around. There are many Corellian shuttles, some of which if you teleport to are simply just floating through space at high speed with no pilots. Otherwise, there are also just many various things to teleport to. I understand that its also your testing world. Just would recommend cleaning it up every now and then ;D

### Steps to reproduce the issue:

Open the teleport menu and see all the entities to teleport to.

I understand there are NPC's now, but I do not mean these to be junk.

Also would be good to see more variation in the ships flying around :)

### Environment
- Starship EVO version: 20w24a
- Graphics Card: 2080 Super OC

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Yes it was still wip, basically I want you guys come up with any issues. That is why this update was not called NPCs, as I know the feature is not ready...
Btw the bug here is that there is  no pilot, you should see one! I will see if I can reproduce.
I will also hide the spawn points - I used them for debug.

**Comment by Sullos** [comment]
Many ships did have pilots, however, some did not, 1 Corellian shuttle was traveling sideways without a pilot, which is what made me think it was just space junk.

**Comment by tsunamayo** [comment]
Ah okay... I did spot a lot of issues in your log file, so there must be something fishy.

**Comment by tsunamayo** [comment]
Fixed for 20w25d. Thanks!
