### ISSUE TITLE
[Bug] Can't connect new connector that is already 'connected'

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Starship-EVO#2391]
### Short Description of the issue:

If you connect a few station modules together, if you move one module away, then try connecting another module to a connector that originally had something connected to it, it won't let you 'connect' them. I believe we have had this bug before, but it is here again.

### Steps to reproduce the issue:

Connect some modules together
Connect one of the modules off to another separate module.
Try connecting something to the connector port you just moved the module away from.

Replacing the connector port is the only way to fix it.

### Environment
- Starship EVO version: 20w24a
- Graphics Card: 2080 Super OC

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Okay issue is now fixed for 20w24c. Thanks!
