### ISSUE TITLE
[BUG] When interacting with ship while docked to pad, ship ejects from pad

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#2392]
### Short Description of the issue:

...After getting in the seat of a ship I had on a station landing pad and flipping a switch to close the canopy, the ship flew diagonally downward through the pad at hundreds of km/s and proceeded to overheat and explode after a couple seconds.

### Steps to reproduce the issue:

...
- Dock a ship/have a ship already docked to a landing pad on a station
- Enter the seat of the ship
- interact with any logic or system on the ship

### Environment
- Starship EVO version: 20w24a
- Graphics Card: Nvidia GeForce GTX 1060 6GB

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4762730/output_log.txt)

![20200611005959_1](https://user-images.githubusercontent.com/51390907/84347702-349c2280-ab81-11ea-8574-1454c33cd7fd.jpg)
![20200611010001_1](https://user-images.githubusercontent.com/51390907/84347703-3534b900-ab81-11ea-9773-42a4ed22fee7.jpg)
![20200611010025_1](https://user-images.githubusercontent.com/51390907/84347704-3534b900-ab81-11ea-8110-4a93d1f17308.jpg)

**Comment by tsunamayo** [comment]
Seems like a nasty one, if you could send me your character save? or the ship blueprint and I will do the landing.
Thanks

**Comment by Majikmonster** [comment]
I think it exploded because it skimmed the atmosphere of the planet. I went back and checked the ship heat just to be sure it wasn't overheated, and sure enough it was only 63%.

[Majikmonster_Arcadia_Fighter-01_2019-6_2020-6-2.zip](https://github.com/tsunamayo/Starship-EVO/files/4763242/Majikmonster_Arcadia_Fighter-01_2019-6_2020-6-2.zip)

**Comment by tsunamayo** [comment]
Yes if you go inside planet you will be destroyed.

**Comment by tsunamayo** [comment]
@Majikmonster it look like it could be the same bug as #2388 dont you think? Thanks

**Comment by Majikmonster** [comment]
It might be related, although the gravity would have had to effect the ship and not only the player. After game reload and testing again with the same ship, I was not able to reproduce the bug. I will test again and see if it happens. The NPC ships haven't suffered the bug as far as I know.

**Comment by Sullos** [comment]
In all my test cases the gravity does affect the ship as well as the player. I have been able to fly station modules across the solar system just by entering a gravity field. It is possible that the high-speed travel when entering a gravity field is actually a bug separate from the teleporting bug though, as I have experienced both. Teleporting happens somewhat randomly, whereas the high speed is certainly linked to the gravity field and entering it.

**Comment by tsunamayo** [comment]
@Sullos not sure to understand the gravity bug then, do you have a test case I could try to reproduce? Thanks

**Comment by Sullos** [comment]
My current main test case, is to simply walk into a gravity field on a structure. I have a big habitat ring, and only some sections have gravity, by walking from an area with no gravity to an area with it, the entire structure starts warping through space.

**Comment by tsunamayo** [comment]
Okay so we all agree that the issue was fixed I think!
