### ISSUE TITLE
[Bug]? No shield information on entity info screen in codex

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Starship-EVO#2393]
### Short Description of the issue:

If you have an entity selected, you can typically press tab, and then see information about it. You can see most info except shield info.

### Steps to reproduce the issue:
As you can see, I have heat info, HP, power, everything except shield info. The entity does have shields for the record ;D

![711980_20200611151822_1](https://user-images.githubusercontent.com/33239800/84347869-f9d4d180-abf6-11ea-9ef4-8e5782196d00.png)

### Environment
- Starship EVO version: 20w24a
- Graphics Card: 2080 Super OC

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Was it always small like that? I know for the blue UI bug but not that one.

**Comment by Sullos** [comment]
For me, I believe it always has been. I believe it's one of those screen resolution bugs. I just accepted it to be normal.

**Comment by tsunamayo** [comment]
Yes I need to do a pass on those screen resolution issues!

**Comment by tsunamayo** [comment]
Okay fixed for 20w24b. I will have a look at your resolution issue too. Thanks!
