### ISSUE TITLE
[Bug] AI aggresive not very aggresive, and no AI passive option

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Starship-EVO#2394]
### Short Description of the issue:

A while back when we first got AI aggressive spawn in option, the AI were actually aggressive. If you attacked them they would attack back, but now they just fly away.
Also, there is no longer an AI passive mode, to spawn in ships that are meant to just fly around.

### Steps to reproduce the issue:

Try spawning in an AI aggressive ship of any sort, once the pilot gets in, they immediately chicken out and fly away.

### Environment
- Starship EVO version: 20w24a
- Graphics Card: 2080 Super OC

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
We can now spawn civilian ships and have a peaceful option. Thx
