### ISSUE TITLE
[Bug?] AI ships don't interact with stations, crash into things, and fly in loops

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#2395]
### Short Description of the issue:

...The NPC ships don't seem to know what to do with themselves around other objects. A couple Minstrals looked like they tried to dogfight with no weapons, and a Corellian shuttle decided to ram and park its nose on one of the habitat modules of the station it approached. None of the ships tried landing on a pad, and sometimes they would just spin in place or do drift turns with no clear target in mind.

### Environment
- Starship EVO version: 20w24a
- Graphics Card: Nvidia GeForce GTX 1060 6GB

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4762777/output_log.txt)

![20200611005905_1](https://user-images.githubusercontent.com/51390907/84348675-88a80680-ab83-11ea-92c4-650b1435b865.jpg)
![20200611005921_1](https://user-images.githubusercontent.com/51390907/84348676-88a80680-ab83-11ea-9f07-fb319bec8e2f.jpg)

**Comment by enterprise-E** [comment]
I had something similar, when getting a ship top dock at a shipyard, it froze while still trying to dock, right in front of the shipyard, when I changed a setting in the shipyard block, then got back into flying the ship, it completed the dock

**Comment by tsunamayo** [comment]
@enterprise-E this issue is related to NPC, are you talking about NPCs or a ship you flew on your own?

**Comment by enterprise-E** [comment]
one I was flying

**Comment by tsunamayo** [comment]
Fixed for 20w25c. Thanks!
