### ISSUE TITLE
[Bug] All colouring removed from wedge that were covered by other wedges

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Starship-EVO#2396]
### Short Description of the issue:

I will describe this with pictures.

### Steps to reproduce the issue:
Step 1: have something similar to this setup.
![711980_20200611155351_1](https://user-images.githubusercontent.com/33239800/84350066-ff80e600-abfb-11ea-8f03-6907fc39eab3.png)
Step 2: Place an identical opposing wedge block..
![711980_20200611155357_1](https://user-images.githubusercontent.com/33239800/84350090-0f002f00-abfc-11ea-96ef-586fc13ed45d.png)
Step 3: Actually place it..
![711980_20200611155400_1](https://user-images.githubusercontent.com/33239800/84350164-2d662a80-abfc-11ea-912e-6c21c9948ec0.png)
Step 4:  break that newly placed wedge piece
![711980_20200611155403_1](https://user-images.githubusercontent.com/33239800/84350220-44a51800-abfc-11ea-8c5d-7daa512fc7d7.png)
Step 5: Notice that the wedge that was placed first now turned black. If you middle-click and try to select color, it has no color at all. Not even the base metal or even black despite its appearance.

### Environment
- Starship EVO version: 20w24a
- Graphics Card: 2080 Super OC

**Comment by tsunamayo** [comment]
This is not a regression right? Actually you should not be able to place a second wedge in the save space, it will create all sort of issues, so I will try to prevent that instead (it should have been... thats the real bug!)

**Comment by Sullos** [comment]
Oh really, I thought it was awesome that we could. Whilst its very pointless in that example you can make some cool shapes if you don't have the wedges going all the way to completely cover the other wedge.
But regardless I see your point!
I think I've been able to do this for a long time, however, I only just realized how to actually recreate the black block bug.

**Comment by Majikmonster** [comment]
We aren't supposed to be able to put 2 wedges/tetras/corners in the same block space??? How are we supposed to get these angles and shapes? Bricks? Child entities?

![20200611025800_1](https://user-images.githubusercontent.com/51390907/84354792-7af87e00-ab8f-11ea-934e-bf0deab1ca25.jpg)

Please don't remove this. I use these combinations often, especially the corner pairing. They're even on my station modules!

**Comment by MRonlin** [comment]
That kinda looks like those void blocks

**Comment by ProPeach** [comment]
I always thought that placing multiple blocks in a one voxel space was intentional too, it's an awesome feature.

**Comment by Aiwii** [comment]
I also use this feature plz don't remove it

**Comment by tsunamayo** [comment]
No longer applicable since neovox!
