### ISSUE TITLE
[BUG] Unwanted warping

### ISSUE THREAD

**Issue by T00Code34215** [tsunamayo/Starship-EVO#2397]
### Short Description of the issue:
Character warped to a certain recurring location if they pass a certain distance. Prevents progression.
...

### Steps to reproduce the issue:
Built and loaded a large ship (exceeding size of 100*15*20)
sometimes rebuilt/edited/placed  blocks and bricks, othertimes just loaded straight into the game. 
Will not allow any progression beyond around 40 blocks in any direction
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4764182/output_log.txt)

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by T00Code34215** [comment]
Furthermore, getting on any vehicle can warp you into different environments, for instance I mounted the hovercraft originally positioned in the starter zone (Starter zone no longer exists) and I was warped into deep space, and the saturn-like planet was a major distance away (probably over 1000km away)

**Comment by tsunamayo** [comment]
I think it should be the same as bug #2388, which is fixed for 20w24b. I am pushing a build soon. Thanks a lot!
