### ISSUE TITLE
[Bug] Void blocks

### ISSUE THREAD

**Issue by MRonlin** [tsunamayo/Starship-EVO#2399]
### Short Description of the issue:
When starting a new build with the starter block, building blocks in two directions causes these void blocks to appear. They have a spacing of 15 blocks between them. (except the 5 block spacing next to the starter block. You can collide with them.

![711980_20200611135332_1](https://user-images.githubusercontent.com/64201628/84388221-1cadb880-abec-11ea-9b73-29cf3bc4844a.png)

![711980_20200611135320_1](https://user-images.githubusercontent.com/64201628/84388312-46ff7600-abec-11ea-9662-8e30a9480dff.png)

It continues in all directions when you build on top of them:
![711980_20200611135710_1](https://user-images.githubusercontent.com/64201628/84388778-0b18e080-abed-11ea-8b71-62014023a67c.png)

![711980_20200611135519_1](https://user-images.githubusercontent.com/64201628/84388806-14a24880-abed-11ea-8c71-36d19c04fc2f.png)

...

### Steps to reproduce the issue:
Im not sure.

...

### Environment
- Starship EVO version: 20w24a
- Graphics Card: gtx 1050

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4764923/output_log.txt)
`

**Comment by tsunamayo** [comment]
I think Dwarf-Lord had a similar issue, I was not able to reproduce. Could you send me your blueprint? Is it okay when you reload? Thanks

**Comment by MRonlin** [comment]
All the void blocks had disappeared when I reloaded, however I was still able to reproduce the bug. Here is the blueprint 
[Void Blocks.zip](https://github.com/tsunamayo/Starship-EVO/files/4765712/Void.Blocks.zip)

**Comment by ZachZent** [comment]
I get this a lot both in mp and sp. It usually comes when placing/breaking down lots of blocks quickly using mirror or just with a lot of players placing at once.. Invisible blocks coming from placing, ghost (black) blocks coming from breaking.

**Comment by tsunamayo** [comment]
Issue finally fixed for 20w27a. Thanks!
