### ISSUE TITLE
Returning to the title while in photo mode causes problems.

### ISSUE THREAD

**Issue by SageThe13th** [tsunamayo/Starship-EVO#2401]
While in photo mode if I exit to the title screen and then load the world again I become unable to control the character. Additionally things are visually broken.

- Starship EVO version: 20w24b

![What](https://user-images.githubusercontent.com/58193603/84407767-e282ed80-abd0-11ea-8710-11fc2b55f626.png)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4765851/output_log.txt)

**Comment by MRonlin** [comment]
Similar effect to what I was experiencing in #2402

**Comment by tsunamayo** [comment]
I dont think it is related to photo mode, I am reproducing this just by quitting to title.

**Comment by tsunamayo** [comment]
Issue fixed for 20w24c. Thanks!
