### ISSUE TITLE
[Bug] Frozen Character

### ISSUE THREAD

**Issue by MRonlin** [tsunamayo/Starship-EVO#2402]
### Short Description of the issue:
My character froze in one place and I couldn't move my character using wasd. I teleported around but all of the blueprint were invisible I have a video to show you what happened next: 
**(Note: the audio is from a video I was watching at the time.)**
https://www.youtube.com/watch?v=oKcw84Vj0ZI
I could move my character again when I reloaded the game.
...

### Steps to reproduce the issue: 
It happens "randomly" when im building 

...

### Environment
- Starship EVO version: 20w24b (note: I was experiencing a similar effect before the update, where the character would freeze for a few seconds when approaching a newly placed starter block.) 
- Graphics Card: gtx 1050

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

You can find your the log here: 
(had to zip it because of size restrictions)
[Output log.zip](https://github.com/tsunamayo/Starship-EVO/files/4765917/Output.log.zip)

`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\

**Comment by tsunamayo** [comment]
Thanks, it might be linked to an AI...
