### ISSUE TITLE
Suggestion/Question: Fix docked ships to the mother entity

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Starship-EVO#2403]
### Short Description:

I did some tests with the shipyard block. The Ai-docking system implemented with this really works very well with the various hangar designs. For this reason, I would like to propose to rename the shipyard block into a general docking block or Maintenance dock block and to implement that docked ships are fixed to the mother entity, so you can use it also on moving entities.

I know that a simple magnetic docking is also planned, but this way, later (if the time comes)  AI drones or small carriers with a few little NPC fighters can be implemented by using
the existing docking mechanism. In my opinion, that would be incredibly cool! :)
I also wanted to come up with an idea in this regard, the ability to hire NPC pilots or NPC-drone-pilots (if we can have them some day) could be limited through a combat rank or level system (something like Recruit, ... ,Captain Admiral.). 

The NPC-Station update was really a milestone. Stay tunded! 

Version: 20W24b

**Comment by nokturnihs** [comment]
I agree the shipyard dock works really well! Haven't tested what happens to a docked ship when the mother ship moves about
