### ISSUE TITLE
[Bug] Ship randomly teleporting

### ISSUE THREAD

**Issue by OldIronsides** [tsunamayo/Starship-EVO#2404]
### Short Description of the issue:

as of 20w24b i started to see the ship i am working on (or just going through without placing blocks) to randomly teleport to other locations taking me with it. In a hour of game, it happened 4 times.
Most recently, go teleported inside the torus.

### Steps to reproduce the issue:

 i could not find out what exactly makes the bug happen as it occurred both while placing blocks and just walking on the ship (in this case the Yamato).

### Environment
- Starship EVO version: 20w24b
- Graphics Card: NVIDIA GeForce GTX 765M

### Additional information:
![20200611145241_1](https://user-images.githubusercontent.com/51378714/84423070-51be0900-abf4-11ea-87e2-f459074977d2.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4766526/output_log.txt)

Also, wow, focusing so much on the Yamato on the recent video! : ) Thanks for not showing much of the mess the stern is at the moment. Here is the most recent version. it has a lot more interiors, in particular the hangar bay and corresponding control rooms, the corridors around the № 2 and 3 barbettes on deck 1 and the mess hall beneath them, also the entire third main gun has a full spinning structure inside now. (sorry about all the bricks!)

[Grand Yamato.zip](https://github.com/tsunamayo/Starship-EVO/files/4766536/Grand.Yamato.zip)

**Comment by TripleHelixxx** [comment]
I’ve also been experiencing this for the last hour or so.

**Comment by BrickMacklin** [comment]
I have been experiencing this. As soon as I enter a gravity field the ship and myself teleport far away. And then the ship despawns.

**Comment by Majikmonster** [comment]
This looks exactly like issue #2388 
The gravity module is responsible for this, or at least it seems so.

**Comment by tsunamayo** [comment]
So I havent really fixed #2388... It was okay in my test case though...

**Comment by tsunamayo** [comment]
@TripleHelixxx @BrickMacklin Do you have any idea of how it happens? I cant reproduce on my side...
Do you manage to reproduce it often, or even all the time? If you have any blueprint to send so I could have a look at it. 
Thanks

**Comment by BrickMacklin** [comment]
It happens with all my builds since the latest update, big or small. Here's one it was happening with.
[Stalwart Frigate.zip](https://github.com/tsunamayo/Starship-EVO/files/4768259/Stalwart.Frigate.zip)

**Comment by tsunamayo** [comment]
@BrickMacklin okay to confirm you simply enter the gravity field, and it happens?

**Comment by tsunamayo** [comment]
I am stepping inside the gravity field, and nothing happens... I wonder if you could give me more detail about your test case, like what kind of locomotion mode, if it happens 100% of the time, if you were in multiplayer for example.

**Comment by BrickMacklin** [comment]
It is happening for me everytime. I am in anti-gravitational mode. Singleplayer

**Comment by tsunamayo** [comment]
@BrickMacklin could you please send me yoru character save folder?

**Comment by BrickMacklin** [comment]
@tsunamayo Sure thing! I also have the output log and a video of the problem

https://youtu.be/KWY8oFt8jok
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4768518/output_log.txt)
[K.zip](https://github.com/tsunamayo/Starship-EVO/files/4768519/K.zip)

**Comment by tsunamayo** [comment]
I still cant reproduce... You just load your game and you enter the field and then it flies off? 100% of the time?
This is driving me crazy, I really need to fix this bug asap...

**Comment by Sullos** [comment]
Perhaps if you can not reproduce the bug, it means you have fixed it in your client, but we do not have the same version as you? That is all I can think of, as it happens very easily, even by accident some times. Just entering a gravity field is all it takes. I am usually in anti-gravitational locomotion mode too. I'm pretty sure it happens in the event that we touch the hull of an entity. So basically walking on the ship that has gravity. As soon as you enter the gravity field, sometimes there's teleportation, otherwise, it seems to just send the ship flying.

**Comment by tsunamayo** [comment]
yes that is why I am uploading a build at the moment and I will ask you guy to reproduce!

**Comment by tsunamayo** [comment]
@BrickMacklin Okay the new build is up, tell me if you still reproduce! Thanks

**Comment by Majikmonster** [comment]
So I did a little testing in 20w24a some more, starting with the known cause of movement (gravity unit) and then trying to add on things that affected entities had or might have (lots of hull, more than 1 gravity unit, thrusters, connectors, starter blocks, etc.)

Some things I noticed happened consistently:
- The only time it moved was when the player was both in a gravity field and close to the entity itself
- The entity always moved some distance instantly, and always a direction related to the position of both character and gravity unit when they entered the gravity field.
- The entity does not need power, thrusters, or hull. The only thing it needs is a gravity unit.
- There seems to be a distance requirement and time requirement that "resets" the effect. Going up to it after already being close or repeatedly approaching rapidly does not make it move.

Some things I only noticed with some entities or some of the time:
- Entering a gravity field but not near the hull (it must have hull/surface it seems) causes constant momentum in the direction relative to the position of character and gravity unit. The only way to stop the movement is to exit the gravity field. The entity stops fully and immediately (an efficient mode of travel). Updating the entity by building/deleting/painting it stops this effect completely and forever on that entity.

These are tests I did using the player character. I have yet to do extensive testing with ships. I hope this information helps!

**Comment by tsunamayo** [comment]
yes that is what I noticed also, but I cant reproduce that in 20w24c, tell me if you reproduce in that version!

**Comment by Majikmonster** [comment]
I haven't been able to make it happen. It's fixed then (hopefully)!

**Comment by BrickMacklin** [comment]
New update has stopped this from occuring

**Comment by tsunamayo** [comment]
Okat great, it must have been a mismatch in my release... weird...
