### ISSUE TITLE
Turrets don't seem to be targeting, 

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#2406]
### Short Description of the issue:
Turrets don't appear to be able to target, move, and/or fire.

They can be controlled **manually** just fine but they appear inanimate on their own. 
...

### Steps to reproduce the issue:
Try any of the included turrets or even just use the tutorial one, none of them seem to work.
...
[Turrets.zip](https://github.com/tsunamayo/Starship-EVO/files/4767774/Turrets.zip)

### Environment
- Starship EVO version: 20w24b
- Graphics Card: Vega 56

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4767775/output_log.txt)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Just to be sure, what are you targetting with turret? I tweak the algo, they can only target Hostile NPCs so you dont accidently shoot on landing pad or else.

**Comment by BrickMacklin** [comment]
I'm having the issue. Either setting them to auto or target they don't shoot

**Comment by tsunamayo** [comment]
@BrickMacklin are you shooting at an hostile NPC or at something else?

**Comment by BrickMacklin** [comment]
I've tried on a hostile NPC and a random targeted ship

**Comment by nokturnihs** [comment]
Same. The prison Transport ship I just finished had fully functional tracking turrets and the sector patrol ship and one of the last few updates killed the tracking. Even tried fully reprogramming and didn't seem to fix the issue.

**Comment by tsunamayo** [comment]
@nokturnihs on hostile NPC? I will have a look at your transport then!

**Comment by tsunamayo** [comment]
@pinesh your turret is working fine, you have to target hostile NPC otherwise it wont track and shoot.
I will add a way to force fire on neutral target.
@BrickMacklin if you can send me a bp also I can have a look at it.

**Comment by nokturnihs** [comment]
@nokturnihs I should have mentioned I did NOT test it on hostiles - I can't remember the F Key for it and I usually break the shit out of things trying to "guess". It was tracking on neutral targets a few updates ago.

**Comment by nokturnihs** [comment]
I have it set to spaceship target however.

**Comment by BrickMacklin** [comment]
@tsunamayo The same Paris Frigate I sent you has the turrets on it.

**Comment by tsunamayo** [comment]
Okay it was hostile spawned from the starter block that were the issue. Fixed for 20w24d. Thanks!
