### ISSUE TITLE
character locked up after key mapping.

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#2407]
### Short Description of the issue:

attempted to rebind rotation keys after the character wipe. cannot move or change selected items in the hot bar.

holding w and then pressing tab lurches the character forwards and then opens the codex. the same happens when opening the settings.

quitting and rejoining breaks the game outrate so I'm including the app data

...

### Steps to reproduce the issue:
remap the rotate keys to q and e then esc out.
...

[Starship EVO-Frozen Bug.zip](https://github.com/tsunamayo/Starship-EVO/files/4768009/Starship.EVO-Frozen.Bug.zip)

### Environment
- Starship EVO version: 20w24b
- Graphics Card: Vega 56

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Quitting to title is broken, it will be fixed in next patch. Do you still have issues when quitting to desktop?

**Comment by pinesh** [comment]
i had to delete my character data to resolve it. Unsure if quitting to desktop was related to the bug.

**Comment by tsunamayo** [comment]
Okay I dont think it has anything to do with rebind the key.
It works fine over here, and I can load your save file.
I think you faced the teleport bug, then the going back to title bug.
If you try to change your rotate key and face a problem please dont hesite to tell though!
Cheers

**Comment by pinesh** [comment]
Thank you!
