### ISSUE TITLE
[BUG] Sit in any seat and that ship will blast off

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Starship-EVO#2408]
Short Description of the issue:    Sit in a seat and your ship will blast off in a direction

...

Steps to reproduce the issue:   Sit in seat and watch your ship as you launch!

...

### Environment
- Starship EVO version: 20w24b
- Graphics Card: 1080ti

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4768304/output_log.txt)

**Comment by tsunamayo** [comment]
I dont reproduce that issue it works just fine for me. If you could give me more details and the blueprint of your ship. I really need to fix all those bug but I am reproducing none of it...
Are you reproducing 100% of the time?
Could you also send me the full character save folder? 
Where were you located? 
Thanks

**Comment by pinesh** [comment]
I can reproduce it, I have a recording and the save file in which its happening.

**Comment by pinesh** [comment]
[recording.zip](https://github.com/tsunamayo/Starship-EVO/files/4768399/recording.zip)
[Char.zip](https://github.com/tsunamayo/Starship-EVO/files/4768401/Char.zip)

**Comment by ExodistSKY1** [comment]
Okay i just reproduced it, but I am not sure if it was sitting in a seat that caused it, It might be entering a gravity field on a ship.

[Exodist.zip](https://github.com/tsunamayo/Starship-EVO/files/4768449/Exodist.zip)


[DH-H-DS-War Pigeon v1.zip](https://github.com/tsunamayo/Starship-EVO/files/4768450/DH-H-DS-War.Pigeon.v1.zip)

After you download my ship can you delete these please

**Comment by tsunamayo** [comment]
Okay thanks for the save and the video. I still cant reproduce, I will push a build and you will tell me if you still see the issue. Thanks

**Comment by tsunamayo** [comment]
@pinesh  Okay the new build is up, tell me if you still reproduce! Thanks

**Comment by ExodistSKY1** [comment]
Looks good I have tried it on 3 newly spawned ships

**Comment by tsunamayo** [comment]
Okay great!
