### ISSUE TITLE
[Bug] Character movement and controls frozen after reloading world with unloaded NPCs

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#2409]
### Short Description of the issue:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4768533/output_log.txt)

After pressing F8 to spawn multiple Pirates (I replaced the shuttle with a larger ship) and the ships not loading in before exiting the game, restarting the game results in frozen character looking and no ability to move. I can still open GUIs and do things like teleport, but other than that the player character is stuck.

### Steps to reproduce the issue:

- Spawn a large NPC ship and before it can load in, exit to menu.
- Reload world

### Environment
- Starship EVO version: 20w24a
- Graphics Card: Nvidia GeForce GTX 1060 6GB

NPC with no ship.
![20200611223718_1](https://user-images.githubusercontent.com/51390907/84460475-03325e00-ac38-11ea-8361-b1c99e5ffda6.jpg)
Frozen character, even in gravity.
![20200611224313_1](https://user-images.githubusercontent.com/51390907/84460486-0d545c80-ac38-11ea-877e-6cf90d302e0a.jpg)

**Comment by tsunamayo** [comment]
I think it is just the issue of getting back to title - it is fixed in 20w24c if you can confirm that fixed the issue. Thanks
Thanks
