### ISSUE TITLE
[Bug][Multiplayer] Joining host causes client to experience convergence of NPC ships on player charcter

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#2410]
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4768594/output_log.txt)

### Short Description of the issue:

The player joining a host will load into the world with 1 of each ship or loose entity gathered in 1 spot on top of them, causing massive collisions lag (down to 13 or as low as 1 FPS). The entities will follow the client player around via teleportation-like snapping no matter how fast they move away.

The host experiences none of this. The client is the only one affected.

### Steps to reproduce the issue:

- Log into a host server.

### Environment
- Starship EVO version: 20w24a
- Graphics Card: Nvidia GeForce GTX 1060 6GB

First person view:
![20200611231111_1](https://user-images.githubusercontent.com/51390907/84462439-0bd96300-ac3d-11ea-9b19-d47f87736aec.jpg)
From a little distance, not far away enough to force them to teleport.
![20200611232135_1](https://user-images.githubusercontent.com/51390907/84462440-0bd96300-ac3d-11ea-8ce2-419162fa37fd.jpg)

**Comment by Sullos** [comment]
Looks like this issue https://github.com/tsunamayo/Starship-EVO/issues/2400
:)

**Comment by tsunamayo** [comment]
yes issue is fixed, I will push an update soon, I just cant reproduce the teleport bug it is driving me crazy...

**Comment by Majikmonster** [comment]
OOF, didn't see that issue before I posted.
