### ISSUE TITLE
[Bug] Despawning NPC ship freezes character

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#2411]
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4768648/output_log.txt)

### Short Description of the issue:

...Unspawning an NPC ship will make the player stuck in space. You can still look around, but cannot move at all.

### Steps to reproduce the issue:

...Unspawn an NPC ship from the ship TAB menu

### Environment
- Starship EVO version: 20w24a
- Graphics Card: Nvidia GeForce GTX 1060 6GB

**Comment by tsunamayo** [comment]
Thanks for reporting all theses issues, it is fixed for 20w24d! Cheers
