### ISSUE TITLE
[Bug] Small sphere hovering on right side of NPC ships

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#2412]
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4768686/output_log.txt)

### Short Description of the issue:

...A tiny white sphere appears a few meters on the right side of NPC ships most notably when they are landing/landed on a station pad.

### Steps to reproduce the issue:

...Follow an NPC ship as it goes to land on a station

### Environment
- Starship EVO version: 20w24a
- Graphics Card: Nvidia GeForce GTX 1060 6GB

![20200611222120_1](https://user-images.githubusercontent.com/51390907/84463420-bce0fd00-ac3f-11ea-8d2b-704f1ec8cded.jpg)
![20200611222112_1](https://user-images.githubusercontent.com/51390907/84463432-c36f7480-ac3f-11ea-977b-f39b5cad8799.jpg)

**Comment by tsunamayo** [comment]
Issue fixed for 20w25a. Thanks!
