### ISSUE TITLE
[Bug] Exiting to menu while near entity with thrusters plays thruster sound loop while in menu

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#2414]
### Short Description of the issue:

...Exiting to menu when nearby a ship or station with any thrusters will cause the thruster sound to play continuously when in the menu screen.

### Steps to reproduce the issue:

...Exit to menu when near thruster

### Environment
- Starship EVO version: 20w24c
- Graphics Card: Nvidia GeForce GTX 1060 6GB

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4768873/output_log.txt)

**Comment by tsunamayo** [comment]
Issue fixed for 20w24d. Thanks!
