### ISSUE TITLE
[Bug] Exiting to menu and reloading world causes NPC ships docked on pads before exit to vanish

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#2415]
### Short Description of the issue:

...
Reload of world from menu screen results in NPCs disappearing. I saw it specifically with those docked to landing pads. I'm not sure about the others loose in space.

### Steps to reproduce the issue:

...
- Wait for NPC to land on station pad
- Exit to menu
- Load same world from menu

### Environment
- Starship EVO version: 20w24c
- Graphics Card: Nvidia GeForce GTX 1060 6GB

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4768880/output_log.txt)

**Comment by tsunamayo** [comment]
Yes no NPC are saved currently. As it is till wip I want to spawn new one every time you load the game.
NPC stations are also not saved and respawned, because they will evolve quite a lot.

**Comment by Majikmonster** [comment]
Ah, ok. This isn't a bug then. Thanks for explaining how it works.
