### ISSUE TITLE
[Bug] Exiting a single player game to title, then joining a mp game, causes the mp game to overwrite sp world

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Starship-EVO#2416]
### Short Description of the issue:

As the title says, if you play in a singleplayer world, and if you exit to title, as opposed to exiting to desktop, if you then join someone else's mp game, the singleplayer world you were just in gets overwritten with the mp world.
I believe this is due to the game not fully deinitializing a singleplayer world, and so when autosave of the mp world happens, it just overwrites the world file.

### Steps to reproduce the issue:

This is actually a bug I forgot to report, so I don't have a current output log. Sorry.

### Environment
- Starship EVO version: 20w24c
- Graphics Card: 2080 Super OC

**Comment by tsunamayo** [comment]
Okay I keep you posted!

**Comment by tsunamayo** [comment]
Fixed for 20w25a. Thanks a lot!
