### ISSUE TITLE
[Bug] Connectors on blueprints rotated 180* along placement point

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#2418]
### Short Description of the issue:

...
I loaded in several station module parts I was working on, and noticed very quickly that a connector had moved and was clipping into the blocks next to where it was supposed to be located. I noticed this with every connector on each module, and that each was rotated from the corner that they orient to when first building them.

### Steps to reproduce the issue:

...
- Spawn in a blueprint with connectors on it, saved before the last couple of versions.

### Environment
- Starship EVO version: 20w24c
- Graphics Card: Nvidia GeForce GTX 1060 6GB\

![20200612015855_1](https://user-images.githubusercontent.com/51390907/84470388-3f25ed00-ac51-11ea-8b7b-62d11a743a43.jpg)
![20200612003128_1](https://user-images.githubusercontent.com/51390907/84470389-3fbe8380-ac51-11ea-84a1-0c408b10ef06.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4769032/output_log.txt)

**Comment by Sullos** [comment]
This is just one of those 'game breaking bugs' tsuna mentioned with the 2x2 connectors in update 20w24a from memory. you just need to replace them and resave the blueprint. Works fine for me after I did that.

**Comment by tsunamayo** [comment]
Yes correct, sorry for that the docking port was not symmetry compatible. You will have to fix them manually! Maybe I should add a small warning message for build that break something.
