### ISSUE TITLE
[Bug] Players become invisible in MP

### ISSUE THREAD

**Issue by PopkaAkula** [tsunamayo/Starship-EVO#2420]
### Short Description of the issue:

I was playing in multiplayer and noticed that the other player's model goes invisible sometimes.

### Steps to reproduce the issue:

Join a multiplayer game and look at a player

### Environment
- Starship EVO version: 20w24c
- Graphics Card: GTX 1060

### Additional information:

[footage](https://streamable.com/ntj1pq)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4772721/output_log.txt)

**Comment by tsunamayo** [comment]
Fixed for 20w25a. Thanks!
