### ISSUE TITLE
Invisible block bug when mirroring.

### ISSUE THREAD

**Issue by Vicomt** [tsunamayo/Starship-EVO#2421]
### Short Description of the issue:
So, the invisible block bug didn't go away like we hoped
![20200612211552_1](https://user-images.githubusercontent.com/7197427/84543125-a8aa0800-acf2-11ea-828c-66542b421fb3.jpg)

it felt better to start off with, time from insertion to display very low, but quickly moved to a state where every insertion was slow, and eventually didn't display at all.
...

### Steps to reproduce the issue:
build a large ship (world attached)
mirror it along one axis
have a client join
start placing blocks whilst the other client is also placing blocks
watch the lag happen.

### Environment
- Starship EVO version: 20w24c
- Graphics Card: GTX 1070

### Additional information:

world save data including log to last session where issue was apparent:
[Save_Data.zip](https://github.com/tsunamayo/Starship-EVO/files/4773089/Save_Data.zip)

**Comment by tsunamayo** [comment]
So to confirm, is the game freezing or does the building takes time to catch up (fps staying constant). Thanks

**Comment by tsunamayo** [comment]
Also how big is your ship? Do you noticed this is single player also? Thanks

**Comment by Vicomt** [comment]
Oojimaflip tried to break it in singleplayer on the ship that's in the savedata submitted above, and couldn't. once he joined my server in MP things started going wonky.

the game never actually lags, FPS is solid and high, it's just the geometry that doesn't draw. the lag I talk about is the time between clicking to insert/delete, and the insert/delete visibly happening.

The ship we're working on (as I said, it's in the save data) is 512m long and about 256 wide

**Comment by Vicomt** [comment]
The new build (25w25e) still exhibits this issue. attached is a log file
[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/4815358/output_log.zip)
