### ISSUE TITLE
[Bug] NPC is not in pilot seat

### ISSUE THREAD

**Issue by itsKeq** [tsunamayo/Starship-EVO#2422]
NPC doesn't spawn in pilot seat on station causing the landing pad to be locked.

### Environment
- Starship EVO version: 20w24c
- Graphics Card: rtx2060

![20200613114508_1](https://user-images.githubusercontent.com/65949046/84557265-e186c300-ad6c-11ea-85df-3517aecdc2f4.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4773840/output_log.txt)

**Comment by tsunamayo** [comment]
Okay I am not sure to understand the detail of your case:
1) did you spawned your ship manually?
2) do you confirm it is a rotating seat?
3) I am not sure to understand the relation with the shipyard landing. What happens exactly, how are you sure it is related to the seat?
Thanks!

**Comment by tsunamayo** [comment]
For rotating seat I think I am gonna have to apply a rule, where the seat needs to be linked to the yoke, otherwise AI is never gonna work. Maybe I will enforce that rule for all the seat actually.

**Comment by itsKeq** [comment]
yes its a rotating seat i didnt spawn it in, i went to a new NPC station were it was landed

**Comment by tsunamayo** [comment]
@itsKeq it is just for immersion, it should not impact gameplay. 
How long did you waited?
What I am interested is the "Landing pad is locked" part of your issue, that is the real issue.

**Comment by itsKeq** [comment]
ah ok,waited at the station for around 5 minutes went back to the station NPC has moved and pad is now unlocked

**Comment by tsunamayo** [comment]
Okay now for children seat you have to link the seat to the yoke for it to work. Thanks!
