### ISSUE TITLE
[FEATURE REQUEST] grass decal

### ISSUE THREAD

**Issue by nokturnihs** [tsunamayo/Starship-EVO#2423]
Would like a grass decal for making artificial grass blocks. Can maybe submit some images if you'd like... Can tweak some old minecraft custom resource pack textures if you like... Need to know what format and what you need though (need a _n layer, etc)

**Comment by nokturnihs** [comment]
I don't know what format you want but here's a few I messed with for 20min or so and the GIMP project file if you want to mess with it. 
![Smoother-COLOR-transparent](https://user-images.githubusercontent.com/7344403/84559909-1575d000-acfc-11ea-8718-616a0415784d.png)
![smoother-desat-transparent](https://user-images.githubusercontent.com/7344403/84559910-16a6fd00-acfc-11ea-9f87-6d7174487b83.png)
![busy-bump-desat-transparent](https://user-images.githubusercontent.com/7344403/84559896-0c84fe80-acfc-11ea-8511-75017d1953d9.png)
![busy-COLOR-transparent](https://user-images.githubusercontent.com/7344403/84559897-0d1d9500-acfc-11ea-8411-52905223067c.png)
![busy-desat-transparent](https://user-images.githubusercontent.com/7344403/84559899-0e4ec200-acfc-11ea-952c-eb000ecc9e48.png)
[Grass Decal.zip](https://github.com/tsunamayo/Starship-EVO/files/4773994/Grass.Decal.zip)

**Comment by tsunamayo** [comment]
Thanks, I am not sure yet on this I would prefer to wait for deeper interaction with the ground, as to not ship something and break it later on... I need to make up my mind on this.

**Comment by nokturnihs** [comment]
Oh I wouldn't recommend that for the ground of planets - a decal would be a good way to work it on a ship though, at least for decorative items. I'm wondering though, how hard would it be to implement a way for players to use their own decals? Like for example a transparent PNG or dds file in a series of subfolders like decals/skull and read the image file(s) inside that folder. Set established sizes/formats and then allow people to use what they want? Dunno how that'll translate on blueprints but it would be an amazing feature with the additional benefit of saving you some time and/or collecting assets for use later.

**Comment by ExodistSKY1** [comment]
Could we get 3d grass to place like the grass we see on the torus?
