### ISSUE TITLE
[Bug] Connectors moved themselves [20w24c]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#2424]
### Short Description of the issue:
Connectors on station modules moved themselves to new positions; it looks like they moved around the rotation point, by 180 degrees.

### Steps to reproduce the issue:
Happened only once, something seems to have changed on an update; I am sending a blueprint with the bug on it so you can see it. Whatever it was does not seem to be recurring, so it looks like a weird one-time bug. I haven't started a new world yet (busy IRL), so I suspect it was one of the bugs you were expecting with the changes in 20w24a. So, it's probably not going to crop up again, but I wanted to make sure it was known just in case.

### Environment
- Starship EVO version: 20w24c
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
[AAM Station Module - Hall 4 Connector Bug.zip](https://github.com/tsunamayo/Starship-EVO/files/4774036/AAM.Station.Module.-.Hall.4.Connector.Bug.zip)

![20200613001108_1](https://user-images.githubusercontent.com/33041786/84560489-64c2fd00-ad0a-11ea-8f68-7a1814ccf3f2.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4774037/output_log.txt)

**Comment by tsunamayo** [comment]
Yes sorry there was a breaking change in this docking port in #2384, I already updated your blueprints.
It was because the model was not compatible with symmetry.

[Blueprints.zip](https://github.com/tsunamayo/Starship-EVO/files/4774100/Blueprints.zip)

Thanks!
