### ISSUE TITLE
[Suggestion] Turret Default Position

### ISSUE THREAD

**Issue by esauftgz** [tsunamayo/Starship-EVO#2425]
I would like to suggest some sort of functionality to allow turrets to have some kind of default position. This should help with maintaining a certain profile/look for builds with turrets.

My suggestion would be like:
1. Have a button in the turret computer window that sets a turret's current position as "default".
2. When the turret isn't targeting anything, it would return to that set position.

**Comment by tsunamayo** [comment]
Yes it is a valid request, something that was on the roadmap.

**Comment by tsunamayo** [comment]
It was added at one point.
