### ISSUE TITLE
[Bug] Void lines?

### ISSUE THREAD

**Issue by MRonlin** [tsunamayo/Starship-EVO#2426]
### Short Description of the issue:
When spawning in a ship, rows of void lines appear on the ship. Happens on every ship. Reloading fixes the issue.

...

### Steps to reproduce the issue:
It appears to only happen with my primary character 
...

### Environment
- Starship EVO version: 20w24c
- Graphics Card: gtx 1050

### Additional information:

![711980_20200613221231_1](https://user-images.githubusercontent.com/64201628/84579394-4f5ed900-adc5-11ea-8668-7ee9c1349422.png)

You can find the log here:
[ezyzip.zip](https://github.com/tsunamayo/Starship-EVO/files/4775471/ezyzip.zip)

**Comment by tsunamayo** [comment]
Could you send me your character folder? Thanks

**Comment by MRonlin** [comment]
@tsunamayo Sorry for the late response.

[M.R.zip](https://github.com/tsunamayo/Starship-EVO/files/4780256/M.R.zip)

**Comment by BrickMacklin** [comment]
I am also getting this bug.

**Comment by tsunamayo** [comment]
Issue finally fixed for 20w27a. Thanks!
