### ISSUE TITLE
[Bug] (?)  Lack of sunlight specular highlight on water

### ISSUE THREAD

**Issue by Calvert4096** [tsunamayo/Starship-EVO#2428]
### Short Description of the issue:

Specular highlight of water from sunlight seems to be absent (see screenshot).  Note specular highlight on sand adjacent to the water.

### Steps to reproduce the issue:

Look at water and ground with the sun at a low angle

### Environment
- Starship EVO version: 20w24c
- Graphics Card: AMD Radeon HD 7800 Series (ID=0x679e)

### Additional information:
Screenshot:
![image](https://user-images.githubusercontent.com/65469633/84584665-e6bf2e80-adbb-11ea-88f6-20a712b3f25d.png)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4775844/output_log.txt)

**Comment by tsunamayo** [comment]
Yes, sorry it is not really a bug for now, I had trouble to make good looking specular on water and I spent way too much time on water for now, so it will have to wait a bit for more improvements! Cheers
