### ISSUE TITLE
[Bug] Frosted windows are transparent

### ISSUE THREAD

**Issue by milan-t** [tsunamayo/Starship-EVO#2429]
### Short Description of the issue:
Frosted windows look like normal window with thiner frame.
![20200614172330_1](https://user-images.githubusercontent.com/65783423/84597443-5b4da800-ae64-11ea-970f-bc7a111a6d92.jpg)

Note: On debug option window option "Enable Disort & Blur Effect" is checked.

### Steps to reproduce the issue:
Create or use some existing entity and place Frosted Window or Frosted Pattern Window brick on it.

### Environment
- Starship EVO version: 20w24c
- Graphics Card: NVIDIA GeForce GTX 1660 Ti

### Additional information:
Output log:
[output_log__milan-t__200614-1725.zip](https://github.com/tsunamayo/Starship-EVO/files/4776735/output_log__milan-t__200614-1725.zip)

**Comment by ZachZent** [comment]
Well it is glass :D

**Comment by tsunamayo** [comment]
Yes the distort effect was bug (as the UI blur), but I fixed it a couple day ago, fix will be in 20w25a. Thanks!
