### ISSUE TITLE
[Bug] [Multiplayer] Playermodel Invisable

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#2430]
Players are invisible in multiplayer except from certain angles

https://cdn.discordapp.com/attachments/406664114249793536/721848507882930256/2020-06-14_15-06-28.mp4

**Comment by tsunamayo** [comment]
Yes I need to investigate this... 
And howly s**t that is some sexy stuff you have here...
If you are okay give me that! I am shooting some featurette for the steam store, it could be a cool thing to show.

**Comment by ZachZent** [comment]
That is a secret project that is supposed to be done before release, but may not get done time

The station is Nuc1earLemon's

**Comment by tsunamayo** [comment]
okay, and the little builder?

**Comment by ZachZent** [comment]
Ah right. It is DarthPeter0

**Comment by tsunamayo** [comment]
Thanks, I dont know if he is willing to share? Bug is fixed for 20w25a. Thanks!
