### ISSUE TITLE
[BUG] Ai rams into space stations

### ISSUE THREAD

**Issue by StarrKiss** [tsunamayo/Starship-EVO#2431]
### Short Description of the issue:
When there are AI ships are around space stations, rather than land on them, they do one of two things ( in my experience)  try to 'land' and ram into the station, or fly around the station in giant circles for eternity.

### Steps to reproduce the issue:
Step 1- Go to a space station
Step 2- Profit
### Environment
- Starship EVO version: Auto-latest
- Graphics Card: GTX 1070 ti

### Additional information:

![image](https://user-images.githubusercontent.com/13007697/84607022-4119c700-ae70-11ea-8d8a-27c66fc2dace.png)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4777427/output_log.txt)

**Comment by tsunamayo** [comment]
Flying around is normal as it is a coded behaviour (they are a bit simple for now). As for ramming yes I have noticed this, I need to work on collision avoidance as now we have bigger stations. Thanks

**Comment by tsunamayo** [comment]
Fixed for 20w25c. Thanks!
