### ISSUE TITLE
[Question/Suggestion] Music

### ISSUE THREAD

**Issue by MRonlin** [tsunamayo/Starship-EVO#2433]
I really love the title screen music, are we going to be getting In game music?

**Comment by ProPeach** [comment]
Btw did you see Tsuna's response to your other issue #2426? He needs your save data folder to help out

**Comment by MRonlin** [comment]
Oh whoops must have missed that, thx

**Comment by tsunamayo** [comment]
Thanks both, yep I want to add more music for sure, but I am a bit short on time, will see when I could do that! Cheers
