### ISSUE TITLE
[Bug] Decals have broken appearance on sloped surfaces

### ISSUE THREAD

**Issue by Calvert4096** [tsunamayo/Starship-EVO#2435]
### Short Description of the issue:

Decals on sloped surfaces tend to look broken up when viewed at a shallow angle.

Screenshot 1 -- viewed normal to surface:
![image](https://user-images.githubusercontent.com/65469633/84725439-77724780-af3f-11ea-9411-275d9ad3c717.png)

Screenshot 2 -- viewed at angle:
![image](https://user-images.githubusercontent.com/65469633/84725415-688b9500-af3f-11ea-9567-b75ee437bde9.png)
 

### Steps to reproduce the issue:

Place series of decals stripes on a sloped surface (overlapping in the example shown)

### Environment
- Starship EVO version: 20W25a
- Graphics Card: AMD Radeon HD 7800 Series (ID=0x679e)

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4784044/output_log.txt)

**Comment by ExodistSKY1** [comment]
What I have found is when you are placing on a curved surface you have to start from the lowest point and move the sticker uphill in a sense and that should help negate what you are encountering

**Comment by tsunamayo** [comment]
Yes exo is correct I also noticed this, it actually make sense in my code this is something I will need to address. Thanks

**Comment by Calvert4096** [comment]
Thank you both, I will use that workaround.

**Comment by tsunamayo** [comment]
This issue will be fixed for 20w29c. Thanks!
