### ISSUE TITLE
[Bug] yoke locks to chair

### ISSUE THREAD

**Issue by itsKeq** [tsunamayo/Starship-EVO#2436]
once you have connected the chair to the yoke you can not un-link it

### Steps to reproduce the issue:

 link chair to yoke 

### Environment
- Starship EVO version: 20w25a
- Graphics Card: gtx2060
![20200616124617_1](https://user-images.githubusercontent.com/65949046/84726355-09c22c00-afd0-11ea-9c62-7f5efecec2bb.jpg)

**Comment by tsunamayo** [comment]
Fixed for 20w25b. Thanks!
