### ISSUE TITLE
[Bug] Walk animation in mp not working

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#2437]
In multiplayer, you can only see the other players in the floating animation even when they are in walking mode in a gravity field.

https://discordapp.com/channels/406664114245599244/406664114249793536/722302816139477052
Output log

**Comment by tsunamayo** [comment]
Whats that link I cant open it, but I think the description is clear enough...

**Comment by ZachZent** [comment]
Output log. For whatever reason I can never seem to attach documents and such anymore. Very annoying

**Comment by tsunamayo** [comment]
Okay issue fixed for 20w25d. Thanks!
