### ISSUE TITLE
[Bug] Paint blob shows as cube

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#2439]
### Short Description of the issue:
When a player or item stand holds paint, it is displayed as a coloured cube
![image](https://user-images.githubusercontent.com/27857711/84922222-76ffbb00-b0bd-11ea-8ffc-c158fdf40008.png)
![image](https://user-images.githubusercontent.com/27857711/84922245-7ebf5f80-b0bd-11ea-89b1-1936a74362a0.png)

I have a laptop with an Nvidea card so I'll check to see if I get the same issue on that too

### Steps to reproduce the issue:
This might be an AMD GPU related issue, all paint in all play modes appears as a cube

### Environment
- Starship EVO version: 20w25a
- Graphics Card: RX580

**Comment by tsunamayo** [comment]
great... I though this was fixed...

**Comment by ProPeach** [comment]
I tried the same test on a different machine, this one has a GTX 1050M.
![image](https://user-images.githubusercontent.com/27857711/85019174-4de73500-b166-11ea-993c-6c0e21e38414.png)
Sorry to bring this up again : (

**Comment by tsunamayo** [comment]
But it was fixed before? Or was it never fixed on AMD? Thanks

**Comment by tsunamayo** [comment]
I will have to kill those blob, and use a more conventional preview.

**Comment by ProPeach** [comment]
I don't think I've seen it working recently, sorry I haven't been able to play much.
That's a shame, the blob was super cool but if that's what it takes to get it fixed then oh well

**Comment by tsunamayo** [comment]
@ProPeach to confirm it also happens in 1st person view?

**Comment by Daomephsta** [comment]
Works correctly with my RX 570 in StEvo 20w25c
![20200619161252_1](https://user-images.githubusercontent.com/10936237/85098507-08526700-b24f-11ea-971a-d5d90efed286.jpg)
![20200619161819_1](https://user-images.githubusercontent.com/10936237/85098510-09839400-b24f-11ea-9e06-d2dab2578636.jpg)

**Comment by tsunamayo** [comment]
hum, that is interesting... @ProPeach are you GFX driver up to date? 
Maybe those blobs are not dead yet...
Does somebody else have the same issue as ProPeach, and does somebody else with an AMD card sees the blocs correctly?
Thanks

**Comment by ProPeach** [comment]
@tsunamayo looks like you were right and it was a driver issue! I updated to the latest June drivers and it all works flawlessly now
![image](https://user-images.githubusercontent.com/27857711/85202973-48beed00-b302-11ea-9b75-f946ecc99ed2.png)
