### ISSUE TITLE
[Bug] Camera only turrets are no longer possible

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#2440]
### Short Description of the issue:
Previously it was possibly to build a turret that only needed a camera to designate the forward direction of a turret rather than a weapon. Now, the turret will not move unless the turret core is linked to a weapon.
Here is the test case I used, the turret does not move and the gizmos don't turn green with just a camera in the system. You can't link a turret core to a camera either
![image](https://user-images.githubusercontent.com/27857711/84927366-a4039c00-b0c4-11ea-822d-6bc04604f4d3.png)
![image](https://user-images.githubusercontent.com/27857711/84927374-a6fe8c80-b0c4-11ea-8eda-890bae368fa3.png)

### Steps to reproduce the issue:
Build a turret with a camera, but no gun

### Environment
- Starship EVO version: 20w25a
- Graphics Card: RX580

**Comment by chacalik** [comment]
If cameras were threaten like weapons, the turret could automaticaly track targets by it self and it wouldn't need much of a new coding on that part

**Comment by Sullos** [comment]
Indeed, I also mentioned this back in this bug: https://github.com/tsunamayo/Starship-EVO/issues/2269
Would be good to have the cameras work in turrets.

**Comment by Majikmonster** [comment]
I fully support camera-only turrets. It might not be much to attach a single weapon brick to the mount and have it work, but it would be nice if we didn't need the weapon at all.

**Comment by Servomotor** [comment]
I tried to make a camera only turret for my current project. I wanted to make something passengers could interact with while flying. I think having camera only turrets is a good feature.

**Comment by tsunamayo** [comment]
Fixed for 20w26a. Thanks
