### ISSUE TITLE
[Bug] Torus moved on old saves

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#2442]
![](https://cdn.discordapp.com/attachments/271723356795961345/723004050999869440/unknown.png)

As said, on every one of my older saves the torus is gone. The buildings are still there, just no ring

**Comment by ZachZent** [comment]
Sorry, one change. The torus is still there, but not in the position it once was

![](https://cdn.discordapp.com/attachments/271723356795961345/723004687770451999/unknown.png)

**Comment by tsunamayo** [comment]
Yes sorry I forgot to mention it, it is better to start on new player save as the torus position is nuked.

**Comment by ZachZent** [comment]
I sent you a message on Discord considering the video I sent you
