### ISSUE TITLE
[Bug] Ship UI says right shift for everything

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Starship-EVO#2443]
### Short Description of the issue:
![image](https://user-images.githubusercontent.com/53021785/84977053-a1b23980-b0e6-11ea-9526-d38dc4c16807.png)

...

### Steps to reproduce the issue:
Fly a ship
...

### Environment
- Starship EVO version: 20w25b
- Graphics Card: 

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4796468/output_log.txt)

**Comment by tsunamayo** [comment]
I dont get that, could you give me your output.log? Thanks

**Comment by Aiwii** [comment]
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4796469/output_log.txt)

**Comment by tsunamayo** [comment]
Does someone else sees this? Thanks

**Comment by tsunamayo** [comment]
@Aiwii hey mate sorry indeed I was able to reproduce, it is one of those things that works in the editor but is broken in the build. Fixed for 20w25c. Thanks!
