### ISSUE TITLE
[Bug] Index mouse drag offsets block's icon

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#2445]
In the current version (didn't happen in 20w24c) when I'm dragging a block or brick from the Index onto a toolbar, the block's / brick's icon is displayed way off to the upper right, always with the same position to the mouse pointer.

- Starship EVO version: 20w25b
- Graphics Card: 2080Ti
- Resolution: 3440x1440

![image](https://user-images.githubusercontent.com/63756057/85030354-424f3a80-b175-11ea-8e94-a2a71debfedb.png)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4799057/output_log.txt)

**Comment by tsunamayo** [comment]
It does this 100% of the time? Thanks

**Comment by tsunamayo** [comment]
Okay I did a change to the code, you will tell me how it is in early access version. Thanks!

**Comment by tsunamayo** [comment]
Fixed for 20w25d! Thanks
