### ISSUE TITLE
[Bug] Exit to Title and Desktop buttons not working

### ISSUE THREAD

**Issue by Facest4b** [tsunamayo/Starship-EVO#2446]
### Short Description of the issue:

After loading a save and alt tabbing, pressing the 'Exit to Title' button simply closes the escape menu and returns to the game and pressing the 'Exit to Desktop' button does nothing at all, leaving the escape menu open.

This bug occurs in Fullscreen, Borderless and Windowed screen modes

### Steps to reproduce the issue:

Open the game and load any save
Alt-tab to a different window and then alt-tab back to the game
Try to use the 'Exit to Title' button and 'Exit to Desktop' buttons in the escape menu

### Environment
- Starship EVO version: 20w25b
- Graphics Card: 2070 Super

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4799697/output_log.txt)

**Comment by tsunamayo** [comment]
This issue should be fixed now 20w26b, I dont think it was the alt-tabbing, I think it was the quit to title and then going back. Thanks!
