### ISSUE TITLE
[Bug] Item Dragging

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#2450]
https://imgur.com/a/1kUvWFN

When you drag an item from the codex to your hotbar, the item is far away from the mouse

**Comment by tsunamayo** [comment]
okay I dont really get it, what is your monitor resolution? Are you in fullscreen or else?

**Comment by ZachZent** [comment]
1920 x 1080 in fullscreen. Xeno got the same bug

**Comment by tsunamayo** [comment]
main monitor? it works fine on my side.

**Comment by Aiwii** [comment]
I have this issue also

**Comment by tsunamayo** [comment]
you know if everybody has this? It is driving me crazy...

**Comment by tsunamayo** [comment]
ah okay I have it, it is when the UI Post effect are enabled.

**Comment by tsunamayo** [comment]
Okay issue fixed for 20w25d. Thanks you guys for booking  that one fast!
