### ISSUE TITLE
[Bug] MP Player Desync Part 2

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#2451]
Before, only the host could see everyone else driving or flying while everyone else could sometimes see others but not always. Now even the host can't see the other players flying or driving. Videos show each player's perspective, flyer and spectator. This was tested on both my and his server switching places. Same result each time.

https://imgur.com/a/SzavIin - Zach's Perspective
https://imgur.com/a/LZ4pkKh - Xeno's Perspective

Zach's Output Log
[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/4802217/output_log.zip)

Xeno's Output Log
[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/4802225/output_log.zip)

**Comment by tsunamayo** [comment]
Okay issue fixed for 20w25d. It was some NPCs optimization that broke this. Thanks!
