### ISSUE TITLE
Can Not Delete Ship in multiplayer

### ISSUE THREAD

**Issue by Xenoprophet-Nail** [tsunamayo/Starship-EVO#2452]
### Short Description of the issue:
I can't seem to delete my ships on a friend's server the host has to remove the ship.

...

### Steps to reproduce the issue:
Log into a friend's server and spawn a ship, then try to delete the ship.
...

### Environment
- Starship EVO version: 20w25c
- Graphics Card: Nvidia Geforce Gtx 1060 6gb

### Additional information:
https://imgur.com/a/WohEctQ
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4802390/output_log.txt)

**Comment by tsunamayo** [comment]
Issue fixed for 20w26c. Thanks!
