### ISSUE TITLE
[Video] Fan Trailer

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#2454]
Enjoy
https://youtu.be/4g_kvFZbNgs

**Comment by MRonlin** [comment]
:)

**Comment by tsunamayo** [comment]
Thanks a lot, that was great to watch! Sorry to have messed up the torus position =( It must have taken a lot of time to create! There is also a lot of cool builds. 
Cheers!

**Comment by ZachZent** [comment]
Actually it took but an hour and a second one to edit/render. The old one you already saw took much longer. If you want the video file, just ask. I don't plan to use my Youtube channel for actual content
