### ISSUE TITLE
[BUG] Game crashing upon character creation.

### ISSUE THREAD

**Issue by Rhoiss** [tsunamayo/Starship-EVO#2455]
### Short Description of the issue:

   Upon trying to create a new character the game starts to load into the world but every time i hear a sound like stepping on gravel as if the character is loaded and the game crashes. Ater reloading the game there is no character created and the same name can't be used again. There is also a folder, with the name i tried to create, in Save_Data\Characters but it only contains 2 empty folders Instances and PlayerEntities.

   After searching for a bit i found that this problem is almost the same as mine.
https://github.com/tsunamayo/Starship-EVO/issues/1205

### Steps to reproduce the issue:

- Start game
- Click on "Play"
- Click on "Create a new character"
- Write a name and click on "Play with this character"

### Environment

- Starship EVO version: early-access 20w25d
- Graphics Card: MSI GTX 1660

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4805263/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, sorry to hear that!
Is the crash a crash to desktop to confirm? 
As a start can you confirm that your GFX driver are up to date? Thanks

**Comment by Rhoiss** [comment]
All of my drivers are up to date. Every time the game crashes the image that shows when it's loading stays while i have a simple error message in the background that just tells me that the game stopped working.

**Comment by tsunamayo** [comment]
So you reproduce the crash each time?
Are you running other program in the background?
Also could you please send me the crash dump and error.log, they should be in the same folder.

**Comment by Rhoiss** [comment]
Yes, the same thing happens every time.
The only programs running in the background are chrome, discord, and steam, also i can't find those files anywhere. The same folder only contains a SETTINGS file, Save Data and Unity folders. There are also only 2 files in the Unity folder config and values.

**Comment by tsunamayo** [comment]
Okay, could you look into the game installation folder, it depends on your steam settings:
Then look into the root folder Starship EVO and then in Starship EVO\Starship EVO_Data
Could you try to uninstall the game and reinstall it also? 
Thanks

**Comment by Rhoiss** [comment]
Looked everywhere in the root folder and all other folders in it and didn't find any files like that, also uninstalling the game and deleting everything connected to it and installing again didn't change anything.

**Comment by tsunamayo** [comment]
Okay so no crash dump...
It is gonna be hard to investigate...
What are you seing in
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\ \Save_Data\Characters
Are there folder with all your character name attemps or nothing?
Thanks

**Comment by Rhoiss** [comment]
There are folders for the attemps but they only have the empty folders Instances and PlayerEntities. Can i try to copy someone else's character folder, that has all necesary files, and see if i can run with it?

**Comment by Rhoiss** [comment]
Installed the new update that appeared in steam and succeeded in creating a character.
![image](https://user-images.githubusercontent.com/57365578/85196741-ec99a000-b2e4-11ea-9b59-aedca65340a2.png)

**Comment by spasquini** [comment]
Sorry to bother, but I just installed the game and I have the very same problem.

**Comment by tsunamayo** [comment]
@Rhoiss okay glad to hear that, I will continue the investigation and keep you posted! It indeed looks like an issue with your GFX card, I will check with other people with a GTX1660 to see what is up.
Btw were was the crash data, and what is your OS (windows 10 or else?) ?
@spasquini so could you please send me the output.log and the crash folder? Thanks

**Comment by tsunamayo** [comment]
btw @Rhoiss I cant open the crashes.zip... Thanks

**Comment by Rhoiss** [comment]
The folder was in `%UserProfile%\AppData\Local\Temp\Moonfire Entertainment\Starship EVO and it's odd that it didn't open since it worked for me. I'll send it to your discord directly, also i am using windows 10.

**Comment by spasquini** [comment]
This is from my first crash. I have windows 10
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4808137/output_log.txt)
[error.log](https://github.com/tsunamayo/Starship-EVO/files/4808138/error.log)

**Comment by tsunamayo** [comment]
@spasquini you also have a GFX card issue. Your card though seems below the minimum recommended, do you manage to player any other recent 3D game with that card? Thanks a lot

**Comment by spasquini** [comment]
Yes, I play Minecraft, Minecraft Dungeons, and I played some other 3D games in the past, even from Steam. I'll try to update the drivers, even if they should be automatic.

**Comment by spasquini** [comment]
I update the drivers and there is a change! Now the game doesn't crash to desktop, but it stays still on the load screen (wonderful artwork btw) indefinetely. I had to force it closed after 20 minutes.
Can be of help that I have just 2.38 GB free on the main drive?
This is the last output_log
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4809043/output_log.txt)

**Comment by spasquini** [comment]
This time, however, the player has been created because at the second try, I had a player to choose from. Even second time the game freeze at the loading artwork.
May I suggest to add a progress bar? It helps to understand if the game is frozen or simply slow to load.

**Comment by Rhoiss** [comment]
Update on my case:
Sometimes i still get the same crash but most of the time the game works perfectly. The world loads just fine and building is also not an issue. Left the game on for a few hours too and nothing bad happened.

**Comment by spasquini** [comment]
Update on my case:
20w26 and nothing change. Game frozen on loading artwork. It's frustrating.

**Comment by tsunamayo** [comment]
@spasquini hold no I will send you a character save far from the Space Habitat, it might be the culprint we will see.
What is the rest of your configuration? Processor and RAM.
Thanks

**Comment by spasquini** [comment]
I cannot check at the moment (i'm in office now). When I will return home, this evening, I will check and tell.
Actually I have a character created, but I'm not sure if it's corrupted or not.

**Comment by tsunamayo** [comment]
[Asteroids.zip](https://github.com/tsunamayo/Starship-EVO/files/4817514/Asteroids.zip)
Hi, so this is a character file. Please unzip in in the path below.
Then in game try to load character named Asteroids and tell me what happened.
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\\Save_Data\Characters
Thanks!

**Comment by spasquini** [comment]
OK, I downloaded your character file.
First thing I compared my character files with your. I had a lot of subfolders in my Character folder. Only two are visible in the Play list, all the others are missing the diplomacy_map.dat and the .mpc file.
Using Asteroids the game starts (Hooray!) Still going slow, lagging a little. 

My data: Intel Core i7-8700T CPU @ 2.40GHz
RAM 8 GB - 64 bit System, processor based on x64

**Comment by spasquini** [comment]
Just for information, with your Asteorids I found myself in the void of space. No ground, no ships, no asteroids. Beautiful star, planets and so, but nothing else I can do there.
In the beginning I saw some ship parts really near to me, but moving a little they disappeared.

**Comment by spasquini** [comment]
Some investigations I made:

Actually I have two characters to play with: Asteroids (that tsunamayo gave me) and Saurone (created by me).

Saurone freeze the game. No crash, simply stay there indefinitely.

Asteroids let me wait a good 5 minutes than it enter the game. Here I'm stranded in space. Alone. No ships apparently. I can see far away a saturno-like planet, a sun, some planets, many nebulosae, and, I think, a ring-world.
Trying to move around I understood that a spaceship is near me, but its blocks are completely invisibile unless I'm really near to them. The textures appears only if I'm almost touching them or I can see their contour if I select my gun with a block and point at them.
By wandering blindly around the mass of the ship, I succeeded to find a door and to get inside. Same problem also inside. I succeeded to seat in the pilot and to start the engines. Moving a little straightforward. 104 m/s reached.

It doesn't seem to be a problem of a poor graphic card. textures are great (when I see them), lights and shadows works fine (I saw my shadow on one of the ship hulls, when outside), simply a problem of visibility. Maybe something involving the calculation (mistaken) if a surface should be drawn or not.

**Comment by Rhoiss** [comment]
Update:
it seems that overclocking my gpu also makes the game unstable. I noticed that crashes happened mostly when the gpu spiked to 2055MHz so by lowering it to the default 1950MHz i haven't had any crashes so far. It's a bit odd since i haven't noticed any problems like this with other games.

**Comment by Silentistaken** [comment]
Im getting this same issue when creating a character. im new here but noticed this was my issue and wanted to see if i could get help. iuse vsync on and im on windows 10. i dont know how to find my hardware

**Comment by tsunamayo** [comment]
@Silentistaken you can send me the log file as a starter:
Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
Then to view the config:
Right click on the window icon, then select System.
You will see a screen with Device specification. Just tell me your Processor and RAM.
Thanks

**Comment by doubleshadow** [comment]
I have the same problem as the OP, CTD every time I try to start a new game.
I was able get stacktrace for you, although the crash is in UnityPlayer. When you google the offending function (`CullCastersCommon`), there are several devs having their SW crash at that function.

I've tried the save game https://github.com/tsunamayo/Starship-EVO/files/4817514/Asteroids.zip. It crashes as well. I also tried changing graphic settings - doesn't help.

I've tried to locate the `output_log.txt`, but it doesn't exist.

Game version: 21w06a
Intel(R) Core(TM) i9-9900KF CPU 16,0 GB RAM
AMD Radeon RX 5700 XT
Windows 10 Home 19042.804

[starship evo stack.txt](https://github.com/tsunamayo/Starship-EVO/files/5976564/starship.evo.stack.txt)
[error.log](https://github.com/tsunamayo/Starship-EVO/files/5976560/error.log)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/5976561/Player.log)
[crash.dmp.zip](https://github.com/tsunamayo/Starship-EVO/files/5976562/crash.zip)

**Comment by tsunamayo** [comment]
@doubleshadow Thanks a lot for the stacktrace! 
I took a shot at doing a fix that might have explained the issue (as I cant reproduce I cant be sure though).
I will ping you when the patch 21w06b is out
Cheers
