### ISSUE TITLE
[BUG] Able to open ESC menu while loading world

### ISSUE THREAD

**Issue by alxnns1** [tsunamayo/Starship-EVO#2459]
### Short Description of the issue:

While loading the world, pressing ESC will show the mouse and upon finishing loading, the ESC menu will be open

### Environment

- Starship EVO version: 20w25d
- Graphics Card: GTX 1050 Ti

### Additional information:

Couldn't get a screenshot of it as the mouse does not appear in screenshots

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4806373/output_log.txt)

**Comment by tsunamayo** [comment]
Fixed for 20w25d. Thanks!
