### ISSUE TITLE
[Suggestion] New sticker

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#2461]
Just a suggestion for a new sticker. A thin straight line on the scale of the other small stickers. That way you can make some nice thin designs using the thin stickers. The curved sticker (left) can also be changed a bit to be able to connect to the straight line sticker

![](https://cdn.discordapp.com/attachments/406664114249793536/723636675221127168/unknown.png)

**Comment by tsunamayo** [comment]
Sounds reasonable! Thanks for the review btw, and holly cow those playtime stats ;)

**Comment by ZachZent** [comment]
Yea... many nights where I just left it open. I mean enjoyed it for hours and hours!

But a number of these thinner stickers will do well for detailing

**Comment by Xenoprophet-Nail** [comment]
Yeah a square indent may look good too, for when you can't fit a screen or say for a tray. I mean the triangles made it over to indents, why not the quad? I mean then someone could build a giant waffle Iron.. or a keypad.. *shrug*

**Comment by Xerma** [comment]
@tsunamayo #1424 I made a suggestion for many stickers and normals a long while back and in there you asked to be reminded about it :p

**Comment by tsunamayo** [comment]
We can do that in recent update with neovox...
