### ISSUE TITLE
[BUG] Moving Starter Block does not move its build area

### ISSUE THREAD

**Issue by Brushes2** [tsunamayo/Starship-EVO#2463]
### Short Description of the issue:
I started a ship in tutorial, decided i wanted to move the starter block afterwards, but when i placed it back it's build area was skewed and blocks wont attach to it properly unless i put it in its original location.  

**CLARIFICATION** upon further observation, i noted that all large blocks have skewed building areas when trying to fix to small blocks, but only after moving the starter block.

### Steps to reproduce the issue:
Start ship construction, move starter block, try to place something on it again.

### Environment
- Starship EVO version: 20w25d
- Graphics Card: 

### Additional information:
Hard to tell in the screen but i moved starter block back one block, and it's build area did not move so if i try to place a large thruster on it, it's recessed.
![711980_20200619165029_1](https://user-images.githubusercontent.com/67161654/85182193-ec9e8f00-b255-11ea-842f-e10834ec5c78.png)

**Comment by tsunamayo** [comment]
Hi, thanks for booking over here!
So I have to admit it must be a bit confusing, but the large block conform to a 1m grid and cannot be placed in the middle of it - so it is perfectly normal.
I think I should throw a help message to explain that better to the player!
Thanks

**Comment by Brushes2** [comment]
Yes, that's confusing, it seems to let me place it in the middle though until i move the starter block.
![711980_20200619173655_1](https://user-images.githubusercontent.com/67161654/85184046-4904ad00-b25c-11ea-8b83-600779a27f94.png)

**Comment by tsunamayo** [comment]
Yes small block can be placed anywhere, but larger block have to conform the voxel grid.
I think that with a preview of the grid it could make more sense?

**Comment by tsunamayo** [comment]
@Brushes2 I have added a voxel grid preview, so hopefully it will be clear that the larger blocks wants to stick to this large grid. I agree as the identity block is large is is confusing, I will try to address that.
Thanks
