### ISSUE TITLE
[BUG] Teleport & menu broke after exiting seat

### ISSUE THREAD

**Issue by Brushes2** [tsunamayo/Starship-EVO#2464]
### Short Description of the issue:
Exited the seat of the tutorial blue fighter inside planets asteroid belt and was flug far in a random direction. Exit to title and exit to desktop stopped working.

### Environment
- Starship EVO version: 20w25d

### Additional information:
Output log att.
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4806902/output_log.txt)

**Comment by tsunamayo** [comment]
Thanks, I was able to reproduce, it seems to appears after a quit to title and then get back in game, if you can confirm? Cheers

**Comment by tsunamayo** [comment]
Issue fixed for 20w25d. Thanks a lot for booking the case!
