### ISSUE TITLE
Suggestion - GeForce NOW Support?

### ISSUE THREAD

**Issue by Monsieur-Bleu** [tsunamayo/Starship-EVO#2465]
Hey! Love the game, but its a little demanding on some older systems. Would you consider getting GeForce Now Support? They've gone ahead and done it for a lot of other Early Access games, as well as games similar to this one like Empyrion and Space Engineers. Congrats on the Steam release. :)

**Comment by tsunamayo** [comment]
Thanks a lot for your kind words, I dont think I have the bandwitdh for that unfortunately...
What is your PC spec?

**Comment by Monsieur-Bleu** [comment]
16.0 GB RAM
Intel Core i7 1065G7 1.30 GHZ - 1.50 GHz 
Intel Iris Pro Graphics
I'm on a Microsoft Surface rather than an older system haha, it can actually run other games pretty well, but for the tougher stuff like Space Engineers for example I just run it through GeForce Now. 

I guess I'll have to wait until I can get a better computer, or find some kind of cloud gaming alternative.
