### ISSUE TITLE
[Dev Asks] Exiting seat animation

### ISSUE THREAD

**Issue by tsunamayo** [tsunamayo/Starship-EVO#2467]
So looking back at this I am having a lot of trouble with exiting seat, on top of that the animation or the lack thereof is not looking good. Which is okay for now but with crew it would be glaring.
So I was thinking of simply blinking the player in position, I think it could look weird at first but better than the current thing.
Also it could make my life a lot easier to deal with children entity seat! Thanks

**Comment by ZachZent** [comment]
Teleporting out will look really weird, even weirder then the current awkwardness. Just speed up the animation and lock the player in place for a second

**Comment by Battlepixel** [comment]
I agree with Zachzent.

**Comment by Calvert4096** [comment]
I honestly wouldn't mind the "teleport" idea if it frees up your time to do other things.

**Comment by nokturnihs** [comment]
Either way works for me, but I'd put in a teleport for now and circle back later. This is polish stuff after a content freeze in my mind. You got bigger fish to fry at the moment :)

**Comment by Aiwii** [comment]
I think teleporting would be cool although I would have to see it first

**Comment by Servomotor** [comment]
I think other games mostly do teleport into the seat. I mean, even world of Warcraft teleports you on your mount, like any mmo, so its not a new thing for players to deal with. I would guess 99.9999% of people could care less. It's not a complaint I have heard people go on about in other games, so I would not worry.

Do whatever makes your life easier now. As Nokturnihs said you can always circle back to this if its a feature you really want. 

I would rather have teleport into a seat and be able to have my character in a sport bike riding postion, or teleport into a bed and have them lying down (I really like lying down animations for pretend sleep and REALLY like sleep mechanics), or have them teleport into any other animation vs a "getting into the seat" animation with just one pose. 

Teleport & Multi poses > Climbing in with 1 pose.

**Comment by Servomotor** [comment]
Think of it this way. Gazillions of people play Minecraft and you teleport into the bed in that game or on your mount, and no one cares...Gazillions still buy it and play it.

**Comment by Xenoprophet-Nail** [comment]
I'm perfectly ok with teleporting and perhaps replacing later, that way Tsuna can fix it when he has the time to and it lets him focus on more important things now.

**Comment by AlienXtream** [comment]
teleport with a little particle effect is the easiest and probably best option for this game. ideal solution would be dynamic animations that change depending on the structure but thats WAY too complex for something so small to be worth the time and effort.

**Comment by tsunamayo** [comment]
Okay, thanks for the feedback all - I will work on that. Could make my life easier for AI pathfinding also, ie if a crew get stuck in can always blink to position...

**Comment by AlienXtream** [comment]
just be sure to work something into the lore to explain why no one can be bothered standing up :P
