### ISSUE TITLE
[BUG] Decals Layering Improperly

### ISSUE THREAD

**Issue by Kadzar** [tsunamayo/Starship-EVO#2468]
### Short Description of the issue:

While placing decal on a door of my ship, I've found that new ones seem to be placed underneath the old.

### Steps to reproduce the issue:

Originally I thought maybe the problem was with child entities, since earlier I was able to place decals properly on the ship as a whole, but it seems like it might just be a problem with a specific door section.

### Environment
- Starship EVO version: 20w25d
- Graphics Card: NVIDIA GeForce GTX 1080

### Additional information:

This last bit I placed is under the circle decal and can't be colored ![20200619184558_1](https://user-images.githubusercontent.com/66035211/85186556-5c654780-b25f-11ea-8677-9135047133db.jpg)
The ship having troubles: [KSE Saucer Shuttle 0.7.4.1.mps.zip](https://github.com/tsunamayo/Starship-EVO/files/4807049/KSE.Saucer.Shuttle.0.7.4.1.mps.zip)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4807056/output_log.txt)

**Comment by Calvert4096** [comment]
Ditto... I made various attempts at "layering" by drawing decals on different brick layers and then deleting those extra bricks so the decals "collapse" onto the underlying surface... same result.

**Comment by tsunamayo** [comment]
Yes sorry there is an issue when you are near a chunk limit, I will upgrade my sticker tech to deal with that!

**Comment by Kadzar** [comment]
Oh, I forgot to mention that this is working properly now. Thank you so much!

**Comment by tsunamayo** [comment]
Fixed for 20w29b, the new tech is here. Cheers
