### ISSUE TITLE
[Bug] Bricks appear darker than adjacent hull blocks of same color and slope

### ISSUE THREAD

**Issue by Calvert4096** [tsunamayo/Starship-EVO#2469]
### Short Description of the issue:

Bricks appear much darker than adjacent full size hull blocks of the same slope and paint color when in direct sunlight... but only for "single axis" slopes; the "two-axis" slope blocks appear to look fine.

Both look fine when in shadow/ facing away from the sun.

### Steps to reproduce the issue:

Place various sloped bricks of the same slope as adjacent hull blocks, paint white, and orient intro direct sunlight.

### Environment
- Starship EVO version: 20w25d
- Graphics Card: AMD Radeon HD 7800 Series (ID=0x679e)

### Additional information:
Sunlit appearance:

![image](https://user-images.githubusercontent.com/65469633/85187440-9846df80-b254-11ea-8e1e-f8e0de280c7c.png)

Shadowed appearance:

![image](https://user-images.githubusercontent.com/65469633/85187497-e360f280-b254-11ea-895f-ff14ad29451b.png)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4807121/output_log.txt)

**Comment by tsunamayo** [comment]
Issue should be fixed for 20w25d (it was a wrong normal for the wedge). Thanks a lot!
