### ISSUE TITLE
[SUGGESTION] Add even/odd symmetry option to tool

### ISSUE THREAD

**Issue by Brushes2** [tsunamayo/Starship-EVO#2470]
That's it, switching between even and odd dimension symmetry.

**Comment by tsunamayo** [comment]
Hi, you can already place the plane inside a voxel (1m grid), maybe you are referring to placing them inside a 0.25cm space?

**Comment by Brushes2** [comment]
Yes, sorry.... the grid is messing me up.

**Comment by tsunamayo** [comment]
I see, what other game are you coming from so I can understand better what are the expectations of new players?
The problem with a grid in 0.25cm place is that the big voxel block wont be able to be placed inside...
Thanks

**Comment by Servomotor** [comment]
Brushes you can use the offset bricks to offset the symmetry tool. I have an entire build of bricks built on an offset brick.

**Comment by tsunamayo** [comment]
yes there is a trick, I think endoskull uses this also, but it will be very finicky to make it works correctly...

**Comment by Brushes2** [comment]
> 
> 
> I see, what other game are you coming from so I can understand better what are the expectations of new players?
> The problem with a grid in 0.25cm place is that the big voxel block wont be able to be placed inside...
> Thanks

Starmade, though it doesnt have to contend with different block sizes.

**Comment by tsunamayo** [comment]
Okay so I can better understand your expectation:
Say you can place a symmetry where you want: do you expect the big block to be placed with that symmetry axis or are you fine if now block is placed? Thanks

**Comment by tsunamayo** [comment]
We can now have a different grid for the symmetry tool.
