### ISSUE TITLE
[Bug] docking pad on ships stops autopilot early

### ISSUE THREAD

**Issue by nokturnihs** [tsunamayo/Starship-EVO#2471]
### Short Description of the issue:
Using docking pads on ships, setting forced direction causes the autopilot procedure to stop early. 
...

### Steps to reproduce the issue:
Set a ship with a docking pad:
Min: -28,0,0
Max: 0,20,28
Forward: 0,0,1
Up: 0,1,0
Landing pad: yes
Forced direction: yes
Entry direction: 0,0,5

Use the Cerberus ship if you want (what I tested with)
Stops at 5 blocks, or maybe the main ship entity edge(?)

Can attach the entity I was testing with (with the dock) upon request.

Note the landing pad is in a doored hangar inside the ship, but there should be zero collision involved (was working a few builds ago).

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Yes if you could give both blueprint that would help! Thanks

**Comment by nokturnihs** [comment]
[ForTesting.zip](https://github.com/tsunamayo/Starship-EVO/files/4807282/ForTesting.zip)
Here you go! pad is on the left. Like I said I used my Cerberus shuttle to test (was using for the video I just posted) - May want to tweak the settings (I changed it so I could land ship, make video) - the above settings were what it was set to when it worked.

**Comment by tsunamayo** [comment]
@nokturnihs there is only a single blueprint of what look like the spaceship ;) thanks

**Comment by nokturnihs** [comment]
Yeah, the second you should already have, the Cerberus shuttle.... Trying to dock the Cerberus shuttle in the cruise ship shows the failure... Am I missing something?

**Comment by nokturnihs** [comment]
https://github.com/tsunamayo/Starship-EVO-Backers-Ships/files/4806864/NIE.Cerberus.Transport.-.fixed.zip

For easy reference

**Comment by tsunamayo** [comment]
This should be fixed in 20w27a. Thanks
