### ISSUE TITLE
[BUG] Stuck in Place and Entities Invisible after Teleporting

### ISSUE THREAD

**Issue by Kadzar** [tsunamayo/Starship-EVO#2472]
### Short Description of the issue:

I teleported in the terrain under a ship on the ringworld, then teleported elsewhere while underground and all the entities became invisible and I am unable to move

### Steps to reproduce the issue:

Probably doing what I did again will do it. I want to get a log while it's still bugged before trying again.

EDIT: I can't seem to get it to bug out again. Not sure what happened there.

### Environment
- Starship EVO version: 20w25d
- Graphics Card: NVIDIA GeForce 1080 GTX

### Additional information:

This should be a teleport pad I put down in the tutorial base
![20200619221228_1](https://user-images.githubusercontent.com/66035211/85190122-c5a68400-b27a-11ea-8fc1-a95e7505f2f5.jpg)

Need to link output log from my Google Drive since it's apparently too big for Github
[]https://drive.google.com/file/d/1kkq8YaRFTbVUi8Pw10JnFtPbQWMIIgiY/view?usp=sharing

**Comment by tsunamayo** [comment]
@Kadzar Hi, sorry for the lack of update. I think you did nothing wrong, from the look of your "massive" log it was a bug related to AI, I keep you posted!

**Comment by tsunamayo** [comment]
So I fixed what was likely the faulty code. Fix in 20w26c. Thanks!
