### ISSUE TITLE
[Major Bug] Codex Broken

### ISSUE THREAD

**Issue by azaz3025** [tsunamayo/Starship-EVO#2475]
### Short Description of the issue:
Blueprints do not show up in codex. Pressing "Export" on blueprint saves the file, but does not update the list.
...

### Steps to reproduce the issue:
Create a new blueprint using "Export" button. Will not show up in list.
...

### Environment
- Starship EVO version: early access 20w25d
- Graphics Card: RX590

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4807589/output_log.txt)

**Comment by tsunamayo** [comment]
@azaz3025 I cant reproduce the bug, it works fine on my side.
Could you guide me through the exact steps you followed? Also is the output.log the one from the play session you encountered the bug? Thanks

**Comment by azaz3025** [comment]
Are exported blueprints only supposed to show up in starter block menus or are they supposed to also show up in the codex at all times? If they are only intended for starter blocks, the only issue would be that the default spawn-able ships in the codex disappeared. Sorry for the confusion.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tsunamayo** [comment]
In the codex you will only the entity you are currently working on, it has no relation to the blueprint spawning.
Sorry I guess this is a bit confusing! In the survival mode you will have to be at a shipyard to spawn a blueprint. 
Thanks!
