### ISSUE TITLE
[Bug] Not able to delete parts, and character cannot move whilst cross-hair is over one of these parts.

### ISSUE THREAD

**Issue by CapShortstuff** [tsunamayo/Starship-EVO#2476]
### Short Description of the issue:

I was deleting some parts of a ship to do some redesigning and it wouldn't let me delete a reactor. The frame rate dropped dramatically when the cross-hair was centered over this reactor. Additionally the player character would not move in any direction whilst the cross-hair was centered over the reactor.

### Steps to reproduce the issue:

A string of reactors next to each other were deleted leaving one reactor detached from the all other ship blocks. From this point on it could not be deleted.

### Environment
- Starship EVO version: Latest update as of June 20th 12:00 BST (I don't know what the version number is, sorry!)
- Graphics Card: Radeon RX 570

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4807817/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, thanks for booking the bug. Did it had a capacitor connected to it?
If you could send me the blueprint I will investigate.
Thanks a lot!

**Comment by CapShortstuff** [comment]
Hi,

There wasn't a capacitor connected to it. When i restarted the game the bug
went away and i was able to delete it again, so i continued on playing. The
blueprint looks very different now to when i had the issue and i haven't
seen the bug again since. Would you like me to send it to you anyway?

I'm really enjoying the game, congratulations on a successful early access
launch!

**Comment by tsunamayo** [comment]
Okay I did some change in the code, this error should no longer cause any frame-rate drop like you saw. For 20w27a. Thanks!
