### ISSUE TITLE
[Bug] Key mapping screen blank after Exit to Title

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#2477]
### Short Description of the issue:
The key mapping screen is blank if you enter it after Exiting to Title from ingame. It stays blank even if you then load a world and navigate to it from the esc menu.
![image](https://user-images.githubusercontent.com/27857711/85203294-9b99a400-b304-11ea-9590-50731cf287aa.png)

### Steps to reproduce the issue:
Load a player world
Exit to Title
Options -> Keymapping

### Environment
- Starship EVO version: 20w25d
- Graphics Card: RX 580

**Comment by Vasbac** [comment]
Again, I have this bug too, plus "exit to title" and "exit to desktop" buttons that no longer work (seem to be related).
Same conditions. It appears when you exit to title once and go back to a game.
(version 20w25d, Geforce 960M)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4808017/output_log.txt)

**Comment by tsunamayo** [comment]
I swear exit to title is the hardest thing to make work... I keep you guys posted, thanks for booking.

**Comment by tsunamayo** [comment]
Hi, both issues are fixed in 20w26b. Thanks!
