### ISSUE TITLE
World disappeared and friend ctd in multiplayer

### ISSUE THREAD

**Issue by Xenoprophet-Nail** [tsunamayo/Starship-EVO#2478]
### Short Description of the issue:
My friend logged into my world hopped onto my hovercraft and when I went to get in my vehicle the world turned into a void
...

### Steps to reproduce the issue:
pilot a hovercraft while the host looks at a hovercraft
...

### Environment
- Starship EVO version: 20w25d
- Graphics Card: Nvidia Geforce Gtx 1060 6gb

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4808065/output_log.txt)

**Comment by tsunamayo** [comment]
Okay I can indeed see a lot of issues in that log, did you did anything special before that? Like removing an entity or else? Thanks

**Comment by Xenoprophet-Nail** [comment]
I deleted some weapons and had an issue where the weapon showed up on the display instead of my hand

**Comment by tsunamayo** [comment]
Okay sorry to ping you late on this @Xenoprophet-Nail , do you remember if the weapon delete was a few seconds before the void issue or a lot longer than that? Did your friend deleted something also? Thanks

**Comment by Xenoprophet-Nail** [comment]
yeah I Hope I remember this correctly.. I had a glitch with placing weapons back on the item display, as I got that sorted he hopped into a hover vehicle and then it crashed him and my world disappeared. I've encountered that bug before and placing the weapon several times and finally deleting the display seemed to fix it both times, it's odd to go to equip a weapon and you see it on the item display and having it fire from there lol
