### ISSUE TITLE
[SUGGESTION] Add option to skip tutorial

### ISSUE THREAD

**Issue by Brushes2** [tsunamayo/Starship-EVO#2479]
Please.

**Comment by Tezlz** [comment]
Just break the walls or increase your speed until you phase through it and escape the tutorial building. Nothing is forcing you to do the tutorial, it's just the location that all new characters spawn at.

**Comment by ProPeach** [comment]
There's also a hatch in the roof that you can open up, I think it's the middle panel. Hit F on it when you see the blue outline

**Comment by Brushes2** [comment]
oh alright, thanks

**Comment by AlienXtream** [comment]
yeh, tutorial area is not actually a programed thing but a structure using in game elements. nothing stopping you breaking out. you can also use the "[]" keys to decrease and increase your speed. get enough and you can just phase through any collisions if you dont wana break the structure

**Comment by tsunamayo** [comment]
Yes indeed I need a way to teleport out of the tutorial zone...

**Comment by ProPeach** [comment]
Im sure we could build an optional escape door into the tutorial building, I'll talk to Womble if you like. Let us know if there is anything else that could be improved!
