### ISSUE TITLE
[Suggestion] Mechanism collision point debug tool

### ISSUE THREAD

**Issue by Calvert4096** [tsunamayo/Starship-EVO#2480]
It may be useful to those designing mechanisms to have a "collision debug" option or tool that visually highlights the two voxels or bricks which are stopping mechanism motion and the associated collision point.  Indication could have both transient and persistent elements to make the timing of the collision readily apparent.

**Comment by Aiwii** [comment]
Using the F3 menu you can turn on an option that lets you see collision points

**Comment by tsunamayo** [comment]
Yes F3 -> Physics -> View Collision points. Looks for the larger sphere, it will be the point that hit the geometry. I will make it a bit better, for now it was more a debugging tool for me. Thanks!
