### ISSUE TITLE
station assembled, not staying that way

### ISSUE THREAD

**Issue by enterprise-E** [tsunamayo/Starship-EVO#2481]
### Short Description of the issue:
modular station, parts "drifting" AFTER assembly, when a ship impacts a part of the station
...

### Steps to reproduce the issue:
3 or more part station, multiplayer scenario, impact from a larger vessel (100m length)
...

### Environment
- Starship EVO version: 20W25C
- Graphics Card: Radeon Sapphire Pulse 8GB

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4808305/output_log.txt)

**Comment by tsunamayo** [comment]
Thanks, yes this is still wip!

**Comment by tsunamayo** [comment]
This was fixed a couple of build ago. Thanks!
