### ISSUE TITLE
[BUG] Teleportation Not Working, Also Seem to Have Reverted a Version

### ISSUE THREAD

**Issue by Kadzar** [tsunamayo/Starship-EVO#2482]
### Short Description of the issue:

When I click on a teleport target, nothing happens. Also, it seems like my version possibly reverted somehow?

### Steps to reproduce the issue:

Teleportation doesn't seem to work at all for me currently, even after restarting the game. Also, I'm apparently on 20w25d, even though I earlier was on 20w35e, or at least I had the grid and less teleport targets.

### Environment
- Starship EVO version: 20w25d
- Graphics Card: NVIDIA GeForce GTX 1080

### Additional information:

![20200620125251_1](https://user-images.githubusercontent.com/66035211/85208536-f9bf8a80-b2f6-11ea-935d-4a102b03614e.jpg)

My output log got weirdly large again, so I have to link it from my Google Drive again: []https://drive.google.com/file/d/1rVmzJl3gID5GbS4YVZmZUixZwd0KdJdy/view?usp=sharing

**Comment by Calvert4096** [comment]
Experiencing the same problem, version indicates20W25d even though steam downloaded an update (I would have expected E).  Output log below... I'm not having the large file size issue you describe.
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4808431/output_log.txt)

**Comment by Aiwii** [comment]
Also having this issue

**Comment by tsunamayo** [comment]
@Aiwii which one, the teleport or the version?
For the version it is a miss on my side!

**Comment by Aiwii** [comment]
Teleport issue. None of my teleport stations work

**Comment by tsunamayo** [comment]
Fixed for 20w26a. Thanks a lot!

**Comment by Sullos** [comment]
I noticed that teleporting wasn't working due to in F3 menu, the 'allow teleporting to any ship in-game' option wasn't checked. Once I ticked that, it all worked fine.
