### ISSUE TITLE
Loading error

### ISSUE THREAD

**Issue by Aeronaut105** [tsunamayo/Starship-EVO#2485]
### Short Description of the issue:
Bought game but wont start. Getting Steam error.
Application load error 3:0000065432
What is it and how do I fix it
Checked firewall and game is set the same as others I play
...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Hi, sorry to hear that!
So it seams it more an issue on the steam side, could please try to re-install the game?
Check out a guide here:
https://appuals.com/fix-application-load-error-30000065432/

What is your OS?

**Comment by tsunamayo** [comment]
@Aeronaut105 Anything new on that? Thanks
