### ISSUE TITLE
[Bug] Autopilot light cruise offset endpoint; ship freezes

### ISSUE THREAD

**Issue by Calvert4096** [tsunamayo/Starship-EVO#2486]
### Short Description of the issue:

Attempting to autopilot lightcruise to "Space Station 0" near the adjacent planet results in spacecraft navigating to a point offset several km distant from the station.

The ship appears to come to a stop relative to the planet, but the visual effect of debris streaking past persists, and the speedometer still indicates 10 km/s.

After terminating autopilot and light cruise, the ship refuses to maneuver in response to pilot input.

### Steps to reproduce the issue:

Flew some Mm out of solar system before flying back to the station.  Attempt to transition from free-flight while in lightcruise to autopilot to Space Station 0.

### Environment
- Starship EVO version: 20w25d
- Graphics Card: AMD Radeon HD 7800 Series (ID=0x679e)

### Additional information:

Screenshot:  ship is stationary relative to planet, but visual effect of debris streaking past persists.

![image](https://user-images.githubusercontent.com/65469633/85212178-fd5a0e00-b304-11ea-84ed-c52955191508.png)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/4808604/output_log.zip)

output log is over 50 MB, uncompressed; zipped copy is attached.

**Comment by tsunamayo** [comment]
Hi, sorry for sleeping on this. Actually it was an issue related to a NPC behaviour that caused that, it just happened during your lightcruise and it broke the game. Issue was already fixed a couple patch ago. Thanks!
