### ISSUE TITLE
[Bug] Inconsistent Canopy Stretch

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#2487]
### Short Description of the issue:
When stretching the Canopy Wedge, it will not stretch in the expected direction in some orientations as shown in the video.  I'm trying to place it in the same orientation as the canopy on the ship in the background and stretch it. It stretches as you'd expect when it's backwards on the ship, but when I rotate it 180 degrees and try to stretch it in the same axis as before, it doesn't work. Hitting the rotate keys don't help either
https://i.imgur.com/tJwC1xb.mp4
Also, the canopies only stretch in 2 axis currently. I'm not sure if this is intentional or a bug, but can we have the 3 axis stretch back?

### Steps to reproduce the issue:
Place and stretch a canopy wedge
Rotate the wedge 180 degrees and try and stretch it in the same direction

### Environment
- Starship EVO version: 20w25d
- Graphics Card: RX 580

**Comment by Bertimus** [comment]
I thought I had this issue as well, but you just have to continue rotating to get the expected direction. This could be resolved by making it more clear which direction the canopy will extend after rotating.

**Comment by tsunamayo** [comment]
Hi @ProPeach, so this was fixed in a recent update, we have 3 axis now on these. Cheers
