### ISSUE TITLE
Cannot place block where I should be able to.

### ISSUE THREAD

**Issue by wick-3d** [tsunamayo/Starship-EVO#2488]
### Short Description of the issue:
Cant place a Tetra Small alongside the edge of a Corner Small
...

### Steps to reproduce the issue:
Unknown, image attached.
...

### Environment
- Starship EVO version: 20w25d
- Graphics Card: GTX 760 

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4808858/output_log.txt)

_(Screenshots, Videos, Error logs, Related issues)_
[https://cdn.discordapp.com/attachments/342383722185883648/724095436448858143/unknown.png](url)
Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
I am having a hard time understand this screenshot, but by the look of it your brick collide with the other bricks, so you should not be able to place it...
Thanks

**Comment by tsunamayo** [comment]
@wick-3d are you sure it was really an issue? Thanks
