### ISSUE TITLE
Game crashes at large dimensions

### ISSUE THREAD

**Issue by BrickMacklin** [tsunamayo/Starship-EVO#2491]
After expanding out a certain size by stretching blocks the game crashes. Space station is this big:
![image](https://user-images.githubusercontent.com/37836252/85232806-fe0ba680-b3cf-11ea-85a6-86f80d673e28.png)

![image](https://user-images.githubusercontent.com/37836252/85232812-049a1e00-b3d0-11ea-8796-ceab2db2bf87.png)

When stretching the game hangs for a second and then crashes. This might be the size limit of the engine.
...

### Steps to reproduce the issue: Stretch blocks from any extreme point on the station. 

...

### Environment
- Starship EVO version: 20w25e
- Graphics Card: 2080 Ti
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4810097/output_log.txt)

### Additional information:

Provided is the output log, save file and station file.
[117.zip](https://github.com/tsunamayo/Starship-EVO/files/4810102/117.zip)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4810097/output_log.txt)
[ODP Station.zip](https://github.com/tsunamayo/Starship-EVO/files/4810104/ODP.Station.zip)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by anunes30-ford** [comment]
Also crashed on my machine, placing a block to extend the 1079m dimension to 1080m crashed it

Environment:
Starship EVO version: 20w25e
Graphics Card: 1050 Ti

**Comment by anunes30-ford** [comment]
it should also be noted that as the dimensions approached this size, extending the dimensions would cause a few seconds to a minute of freezing

**Comment by BrickMacklin** [comment]
I was only getting at most one second of freezing if we were building in multiplayer

**Comment by tsunamayo** [comment]
So it might be due to the light 3d texture. I will remove that texture to move to per-light texture, which will ease the memory impact and remove the freeze. It is a planned dev!

**Comment by BrickMacklin** [comment]
@tsunamayo This is really good to hear, hopefully this will allow us to keep building. To clarify this was not included in the latest patch correct?

**Comment by tsunamayo** [comment]
nope, latest patch is just the collisions. thx

**Comment by tsunamayo** [comment]
@BrickMacklin So now with Neovox you can make 10km wide ship if you want...
