### ISSUE TITLE
[Performance] Multiple rails sliding at the same time lower FPS

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#2495]
I've been told on Discord that I should upload the blueprint I'm currently working on for you to test performance levels with, and hopefully, to improve them.

The mechanism in question is the cargo hatch at the (current) front of the ship, at the bottom. Just flip the middle switch once you're inside to trigger the open and close sequences (**wait for them to finish before flipping the switch again**). In my test case, the mechanism lowers the FPS from 100 to 60. Here's my specs:

CPU: 3900X
graphics card: 2080Ti
resolution: 3440x1440
RAM: 24 gb
[Eve Online - SoE Astero frigate.zip](https://github.com/tsunamayo/Starship-EVO/files/4810892/Eve.Online.-.SoE.Astero.frigate.zip)

**Comment by tsunamayo** [comment]
Hi, how big your children entity is, and is there a lot of them?

**Comment by Kaiser-Indrasil** [comment]
I've done some testing (I should've done before booking an issue...) and it turns out that with simple logic the rails and even grand-grand-child entities are fine. It's the logic what tanks the FPS. I believe the blueprint I've sent you uses a stacked ABBA approach which first triggers the main ABBA, where A is an ABCCBA sequence for the central door, flanked by B doors on either side of the ship, opened and closed by an ABBA sequence.

Using separate ABBA sequences or one for the side gates doesn't seem to make a difference.
However, once I removed the main ABBA sequence which controlled all 3 sub-sequences and opened and closed the gates separately, all was fine.

In case that turns out to not be a logic-related problem:
The side gates each comprise of 2 child entities, moving the grand-child entities for 0.4 seconds, and then these grand-children move their grids for around 3 seconds.
The central gate moves 3 child entities for 0.4 seconds. Then, 3 grand-child entities move their grids for 3 seconds - one of them featuring the biggest object in question, a 2x5m brick plate. One of these grand-children has 2 child entities on its own placed on hinges instead of rails.

**Comment by tsunamayo** [comment]
So CE moving should impact much less if at all FPS now...
