### ISSUE TITLE
[Suggestion] Add Browns To The Color Palette

### ISSUE THREAD

**Issue by BrickMacklin** [tsunamayo/Starship-EVO#2499]
While we wait for an expanded color palette and the return of custom colors a number of us on the Discord have been in need of the color brown for our builds. We are generally content with the current color palette for now (olive green when?) but the lack of brown has been a major hold back for many of us. It is the one basic color missing from our choices and nothing else comes close to it. We would like to have something like this:
![image](https://user-images.githubusercontent.com/37836252/85287972-06f98800-b463-11ea-914d-13164e6c8ff5.png)
Maybe a little darker toward the greyscale side.

Selfishly, here is why brown is a major point for me. Below I have a picture of a ship I was working on before you first implemented custom colors that utilized a variation of brown. next to that is a picture of it in the background after the custom colors and the final picture is of it now after it was carried over to the current build.
![](https://user-images.githubusercontent.com/37836252/84573718-54de0400-ad70-11ea-85b4-f088381703fb.png)

![](https://user-images.githubusercontent.com/37836252/84573749-8656cf80-ad70-11ea-9995-16b207721bdd.jpg)

![](https://user-images.githubusercontent.com/37836252/84573758-953d8200-ad70-11ea-9782-2e3c0c35631d.jpg)

This is my favorite build I've had in the game but currently I won't work on it since I do not have a brown of any kind to use on the hull. So it is at present staying dormant. This is what I am trying to emulate and highlights why I only need that color. 

![image](https://user-images.githubusercontent.com/37836252/85288553-ebdb4800-b463-11ea-96ea-fce16a039b3b.png)

I concur with above posters asking for some browns until we have a more expanded color palette. I think some lack of colors are holding us back.

**Comment by SovietSponge** [comment]
I require brown desperately, I need my fake wood man ;-;

**Comment by MRonlin** [comment]
Browns

**Comment by Kaiser-Indrasil** [comment]
Browns can bring all kinds of cozy and homey interiors, on spaceships and structures both, to life. It would also let me build my ship line which features brown as one of 2 main colours.

**Comment by tsunamayo** [comment]
Gotcha, I will try to get this up for next update. Thanks

**Comment by tsunamayo** [comment]
Okay, I added some brown like your suggestion for 20w26c. Thanks, sorry for doing it so late!
