### ISSUE TITLE
Invisible blocks when building

### ISSUE THREAD

**Issue by zorozeenee** [tsunamayo/Starship-EVO#2501]
### Short Description of the issue:

Whenever you build large blocks a few times they will occasionally turn invisible after place

### Steps to reproduce the issue:

build large blocks over and over again

### Environment
- Starship EVO version: 
- Graphics Card: nvidia gtx geforce 965m

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

Also i tried uploading the txt file and it says "We don't support that file type"
Lmao i tried this several times with the output_log.txt, wtf

**Comment by omrwcs** [comment]
i think any ai ship shooting and damage you blocks, use tool repair and confirme

**Comment by chacalik** [comment]
That's not the case @omrwcs ... My build is now over 900m long and I did had to exit game and load the save again to continue with the build. After some time building with blocks, they become invisible, they are physicaly there, but not rendered. The effect also happens as void colored blocks sometimes.

**Comment by ZachZent** [comment]
This is a common bug I believe is linked to rendering which is being fixed. Blocks are invisible for a second after placing and are blacked out when breaking.

**Comment by MRonlin** [comment]
#2421
#2251
#2194
#1349

**Comment by tsunamayo** [comment]
Yes sorry guys, it is quite high on my list, but thats a big dev. @zorozeenee  how big is your build? Thanks

**Comment by Vicomt** [comment]
The bigger you go, the faster it happens

**Comment by tsunamayo** [comment]
@chacalik are you building in single player or multiplayer? @Vicomt I know you build in mp, but does it happens in single player too? Thanks

**Comment by Vicomt** [comment]
It *can* happen in SP, but you have to try *really* hard.

**Comment by tsunamayo** [comment]
yeah that is my worry, I will do the big rendering update and the bug will still be there because thats a mp bug, not a rendering one...
Although if it is a GC / mem fragmentation issue steaming from long mp building session the rendering refactor should still makes things better.

**Comment by Vicomt** [comment]
I don't have logs to hand, but my bro has found that (at least on our ships) the invisible block bug is still happening, in SP AND MP.

if you need any further information on this, please don't hesitate to ask, we'll give you anything you need (and we can probably show you it happening in MP if you'd care to join my server) - it really is a big important issue for us.

**Comment by chacalik** [comment]
@tsunamayo sorry for the late reply again...
I am building in single player and it seems that the occurency of that bug has raised. Not sure if that was consequency of of the latest updates or the amount of blocks that my build has.

It is over 900m long (real size victory star destroyer) so I was expecting somes issues like that anyway
