### ISSUE TITLE
Recomended and issue with ai ships

### ISSUE THREAD

**Issue by omrwcs** [tsunamayo/Starship-EVO#2502]
### Short Description of the issue:
with fullscreen the tool out size display
ai ship stuck near my
Please give radar and comunication
Is one idea, give, when you buid one radar the radar on, when build comunication, comunication on line
Give dedicated server :) to many players join
...

### Steps to reproduce the issue:
The problem the ships ai fly and stop near my and dont move, in minuts the ship continue flying

...

### Environment
- Starship EVO version: 20w23d
- Graphics Card: geforce gtx750

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
with fullscreen the tool out size display
The tool out the screen
![Starship_EVO_f](https://user-images.githubusercontent.com/67280789/85312120-c3b40f00-b48c-11ea-910f-be72bdf2c8b6.jpg)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Hi, thanks for booking the bug.
The AI ship was stuck near what? Your position? Or something else? Thanks

**Comment by omrwcs** [comment]
The ai ship stuck near my position
