### ISSUE TITLE
[Suggestions] Minor gameplay improvements

### ISSUE THREAD

**Issue by Vasbac** [tsunamayo/Starship-EVO#2503]
Hi there.

After few hours playing on my not so old computer (but still low FPS :D), I just have thinked about some very minor gameplay improvements that could make my life easier. So here are my suggestions, good or not…

-	When building, a hotkey to free your hands would be much appreciated, instead of having to switch to a free slot on the toolbar (especially usefull when your three toolbars are full)

-	Adding more than three toolbars. 

-	About ship controls : I like that pressing tab free the camera. And I really enjoy that turrets can follow the camera at the same time. But what I suggest is that pressing tab again give you back command of the ship without setting the camera back at the center. Thus, you can control the ship and turn around while looking and firering on your side. Then, a hotkey would center back the camera instead when needed.

-	Minor minor point: instead of pressing tab to free the camera, holding tab would be much intuitive in my sense. 

I don’t know if you will figure what I mean. I still can explain in French if needed :D
Best regards! 
G.

Additionnal point:  Because of my computer, i have to lower the resolution to have decent FPS. But the game doesn't remember it between two game sessions.

**Comment by Aiwii** [comment]
You can Shift-Click on blocks to remove them.

**Comment by Vasbac** [comment]
@Aiwii  Right! I have removed this point! Thanks

**Comment by tsunamayo** [comment]
Thanks for suggestions, what is your PC config and what is your FPS? Cheers

**Comment by tsunamayo** [comment]
For the free camera, I am still not sure on the best control scheme, it might indeed change a bit.

**Comment by Vasbac** [comment]
Hi Tsuna,
I run on Nvidia Geforce 960M. In deep space i have around 20-30 when buidling ships which is more than enough. But it drops around 10 on the ring. So i have to desactivate plenty of things and lower the resolution to avoid weird bugs (falling through objects, allerady discussed in #2456).
I'm planning to change my computer anyway
Cheers!

**Comment by tsunamayo** [comment]
okay good to know, I will have to improve my character collision algorithm, it seems that a lot of low spec are getting this bug. Thanks
