### ISSUE TITLE
Start Caracter creation

### ISSUE THREAD

**Issue by XenoShreek** [tsunamayo/Starship-EVO#2504]
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4815185/output_log.txt)
### Short Description of the issue:
Hello, i just bought the game .. i create a caracter .. Xeno ... a nice backscreen come but no more loading and after 5 min i log out, i create a new caracter ... XenoShreek because i dont see the first one in the list and name already taken ... but happend same, i try again but this time looks like i can't create anymore new caracters
...
Other thing is i not see any server .. i create one but nothing change

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 20w26a
- Graphics Card: laptop asus GeForce GT740M

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Hi, sorry to hear that! 
Could you please make sure that your GFX driver are up to date?
Also to confirm now you cant create a new character with a different name?
I would very much like to help you, obviously as I dont reproduce the issue unfortunately it will take a bit of time to figure it out. Thanks!

**Comment by XenoShreek** [comment]
Hello
Yes all my drivers was up to date .. i just check it to be sure and yes it is
I just try to create a character .. i am waiting on the nice backround screen

I know already, badly it will take time to clear this ... i try some years ago to create a game on unity too that why i know its not easy to clear some problems sometime ^^

hum time to finish to write here and looks like i am logged in ^^

**Comment by XenoShreek** [comment]
ok its work i was log in ... and now log off i see my character in the list
I think you know it but have many colision bugs ... at starting place i pass many walls and not easy to come back to follow clearly the tutorial, but no prb for me
last question, discord is good to report some bugs or you prefer i continue to do it on github ?

i think we can close this issue

**Comment by tsunamayo** [comment]
@XenoShreek github is better for real bug, if you need help on how to do stuff discord is your friend!
Now I think you might have low FPS...
Could you try the following:
For the time being could try to deactivate a few options and see if your FPS are better?
Press F3 then go to: Space Habitat, then toggle disable grass, rock and Fog.

**Comment by XenoShreek** [comment]
i desactivate them but for now i can't really see if it's better or not
i use the jump jetpack for finally be too far from "earth" then i am finally in space but i can't move .. i try 6 degrees jetpack but looks like i still can't move ... i try teleport but looks like i can't use it too because no destination

**Comment by tsunamayo** [comment]
I see, I think you got lost in space! I will make sure you can go back to your starting position. Thanks

**Comment by XenoShreek** [comment]
Thx i create already a other character to test from start .. sadly looks like my i5-4200U CPU 1.60GHz 2.30GHz is very limited to play correctly with this game, but its ok for some test i will buy a new computer later ^^
I speak this because i get again a colision bug with the new character in the tutorial ... just at a other place, first time it was in the bathroom at starting place .. second time it was near the magnet 
i will be a little busy irl for the next couple days but i will continue testing and report you all what i can to help your game developpement ... its a very nice project you made

**Comment by tsunamayo** [comment]
Thanks a lot, yes there is some issue with lower end config and collisions.
