### ISSUE TITLE
[Misc] Subreddit link

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#2505]
The Reddit link in the game menu links to the old Skywanderers Subreddit - https://www.reddit.com/r/skywanderers/

We've created a new sub with the new game name here - https://www.reddit.com/r/StarshipEVO/

I believe the old one will be archived soon as it's no longer relevant. We'll put a link to the new sub in the old one and pin it to redirect any old wanderers

**Comment by tsunamayo** [comment]
Okay updated for 20w26b. Thanks
