### ISSUE TITLE
[Bug] Weird shading on the Small Corner brick

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#2506]
There seem to be a problem with how the Corner Small brick is lit, compared to the adjacent Wedge brick. As you can see, depending on the angle of the light being cast upon these bricks, they are lit differently despite their surfaces being co-planar. All of the bricks are of the same colour.
![Starship_EVO_0JfTohQFdX](https://user-images.githubusercontent.com/63756057/85349048-4c669580-b4f5-11ea-8f3a-9e49b7380227.png)
![Starship_EVO_AmLv9MYTen](https://user-images.githubusercontent.com/63756057/85349049-4cff2c00-b4f5-11ea-9cde-373a3692bf42.png)

**Comment by tsunamayo** [comment]
Issue fixed for 20w26c. Thanks for booking these one ;)
