### ISSUE TITLE
Ship appears to be drifting in opposite directions, isn't actually moving.

### ISSUE THREAD

**Issue by JLAMontoya** [tsunamayo/Starship-EVO#251]
I'm working on a ship that is sometimes moving very slowly to the left, or not moving at all. Saving the game seemed to stop moving the ship, but shortly thereafter after I moved around the ship started drifting again. Only when I get very close can I see the ship moving- the lighting changes and I can see it pass in front of stars or terrain in the background. When I back away about 10-20 meters, it's still, not doesn't cover and stars or terrain no matter how long I wait.

The pre-made ships do not seem to be doing the same thing, only the one I'm working on is moving. It has a ship core, an identity block, a connected stick, power, engines.

Edit: The ship does not appear to be _actually_ moving. When I go to the far right side, it looks to be moving to the left. When I go to the left, it looks like it's drifting right. When I go to the middle, it's perfectly still.

**Comment by tsunamayo** [comment]
Okay very interesting bug, I can indeed reproduce also! I keep you posted! Thanks.

**Comment by tsunamayo** [comment]
No longer applicable. Thanks
