### ISSUE TITLE
[Bug] Possible brick normal incorrect

### ISSUE THREAD

**Issue by Calvert4096** [tsunamayo/Starship-EVO#2510]
### Short Description of the issue:

Similar to this: https://github.com/tsunamayo/Starship-EVO/issues/2469
The bricks are painted white in the image shown (ignore copper).

The bottom two (0.25x0.25x0.25 "pyramid" and slope") seem to match well.  But the top two (same bricks but elongated to 4 m) show a noticeably different shade though the upper surfaces should be parallel.

![image](https://user-images.githubusercontent.com/65469633/85370785-1967d600-b4e4-11ea-98b9-9b39470d76dc.png)

### Steps to reproduce the issue:

Place slope & pyramid bricks with low surface angle to sun; paint white.

### Environment
- Starship EVO version: 20w26a
- Graphics Card: AMD Radeon HD 7800 Series (ID=0x679e)

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4817622/output_log.txt)

**Comment by tsunamayo** [comment]
Not sure to understand what is wrong on the picture.
I just fixed an issue for the corner block, maybe it was that? The wedge should be good in curret build, right? Thanks

**Comment by demonfiren** [comment]
I think the problem is shadows not making much sense.

**Comment by Calvert4096** [comment]
It's not the shadows so much as I think a goofy surface normal.  The problem goes away if they're both in shadow (i.e only ambient lighting, as in the case of the previous bug) -- the difference in brightness of the surfaces becomes apparent in direct sunlight.

**Comment by tsunamayo** [comment]
Between the stretched wedge and the stretched corner right?

**Comment by Calvert4096** [comment]
Correct

**Comment by tsunamayo** [comment]
Yes this is fixed for next update 20w26c.
