### ISSUE TITLE
[BUG] Connected vessel teleporting on block placement

### ISSUE THREAD

**Issue by demonfiren** [tsunamayo/Starship-EVO#2511]
### Short Description of the issue:
I am currently building a craft, and in order to prevent it flying away every time the game's physics engine CLANGs (eg when I drop a custom weapon) I've docked it to a large, static structure on the ring. As of this update, loading the relevant save spawns the craft undocked from the ring and placing any block on it teleports it back to its original position.
Less importantly for the purpose of building, reconnecting it shows absurd speed readouts ranging from several hundred m/s to several thousand km/s.

### Steps to reproduce the issue:
Place connection port on any land-based structure.
Place core into empty space.
Place connection port on core.
Connect floating port to structure-based port.
Place any block on the now-docked floating construct.

### Environment
- Starship EVO version: 20w26b
- Graphics Card: 2xGeForce GTX 1070

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4817762/output_log.txt)

**Comment by tsunamayo** [comment]
Thanks for booking the bug, issue should be fixed for 20w26c. Cheers
