### ISSUE TITLE
[BUG] Faulty decal mirroring 

### ISSUE THREAD

**Issue by Tocks13** [tsunamayo/Starship-EVO#2514]
### Short Description of the issue:

Some (not all) of the decals are flipped 180° while using mirror planes and painting decals parallel to the mirror plane

### Steps to reproduce the issue:

1. Build a Block/Brick
2. Make Mirror plane through its middle. (works with all three planes)
3. Paint the decal on a side of the Block/Brick parallel to the mirror plane
4. look at the otherside of the Block/Brick

Additional Infos:
It doesn't matter whether or not the Blocks/Bricks the decals are on are the same or different ones.

Decals observed to have this Issue:
-Cirle Lines (Probably a typo and is supposed to mean Circle Lines)
-Triangle
-Creased Vert Triangle
-Ventholes

### Environment
- Starship EVO version: 20w26b
- Graphics Card: Nvidia GTX 1080

### Additional information:

![20200623105702_1](https://user-images.githubusercontent.com/67311622/85385457-a04b9b80-b542-11ea-8c26-30f58cd5955a.jpg)
![20200623105654_1](https://user-images.githubusercontent.com/67311622/85385479-a5104f80-b542-11ea-8e40-1c115a9e4d68.jpg)

**Comment by tsunamayo** [comment]
Hi, this is fixed in recent update. Thanks
