### ISSUE TITLE
[Bug] Invisible Asteroids

### ISSUE THREAD

**Issue by Tezlz** [tsunamayo/Starship-EVO#2515]
### Short Description of the issue:
Some of the asteroids in the planetary rings are not visible but with collision boxes and can still be crashed into. They are invisible unless you enable collision boxes in the debug options.

### Steps to reproduce the issue:
Enable collision boxes in the debug options, fly around in the asteroid field until you bump into something invisible.

### Environment
- Starship EVO version: 20w26b
- Graphics Card: GTX 1060 6 GB

### Additional information:
Screenshot of the collision boxes of the invisible asteroids:
![Screenshot_1164](https://user-images.githubusercontent.com/36267770/85419253-5f16b400-b561-11ea-88e2-e57610d7792a.png)

Output log:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4820176/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, although I didnt saw the exact same bug I did some fixes to the engine that should have fixed this issue. Fix for 20w26c. Thanks!
