### ISSUE TITLE
Controller Support

### ISSUE THREAD

**Issue by Lucifer-Baphomet** [tsunamayo/Starship-EVO#2516]
Steam page says the game has partial controller support, but there is no option I can see to enable or configure this.

**Comment by tsunamayo** [comment]
If you plug your controller you should be able to map it in the control key right?

**Comment by Lucifer-Baphomet** [comment]
Thanks, BTW bought this today, and love it already. Found your dev vidoe on joystick control.

**Comment by tsunamayo** [comment]
Thanks a lot! Some functionality needs to be rethinked for the controller though. Cheers
