### ISSUE TITLE
[BUG] Rotor Movement Options Broke

### ISSUE THREAD

**Issue by Brushes2** [tsunamayo/Starship-EVO#2517]
### Short Description of the issue:
Placing a small rotor and changing its movement options from 'horizontal/vertical' to 'horizontal/vertical inversed' has no effect. Only way to change rotation direction is to move the block.

### Environment
- Starship EVO version: 20w26b
- Graphics Card:

**Comment by ProPeach** [comment]
Those options are actually for turrets and their axis, you can get a finer degree of control using the Sequencer brick
Link a Switch -> Sequencer -> Rotor
You can then hit F on the Sequencer to change the angles that it travels between when you toggle the switch
To reverse the rotation you need to switch around the numbers in the Sequencer. Going from 0 - 20 degrees vs 360 - 340 degrees will both travel 20 degrees, but in opposite directions for example

**Comment by Brushes2** [comment]
oh dang! ok, thanks
