### ISSUE TITLE
[BUG] Station I had spawned in teleporting to my position every time I load the world.

### ISSUE THREAD

**Issue by orangep9** [tsunamayo/Starship-EVO#2518]
### Short Description of the issue:
Every time I load the world the station I had placed awhile ago is now moving to my position repeatedly.
this only started after the most recent update.
...

### Steps to reproduce the issue:
I'm not sure, I have a few different things pasted in but only this one is doing it.
video, save and log included.
...

### Environment
- Starship EVO version: 20W26b
- Graphics Card: RTX 2070 SUPER

### Additional information:

[SEVOTPBug.zip Video](https://github.com/tsunamayo/Starship-EVO/files/4821104/SEVOTPBug.zip)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4821074/output_log.txt)
[CharacterSave.zip](https://github.com/tsunamayo/Starship-EVO/files/4821080/CharacterSave.zip)

**Comment by tsunamayo** [comment]
Hi, was this station docked to another one? Thanks

**Comment by tsunamayo** [comment]
Okay I was able to reproduce, issue is fixed for 20w26c. Thanks!
