### ISSUE TITLE
[Bug] Multiplayer host cannot interact

### ISSUE THREAD

**Issue by Tomatart** [tsunamayo/Starship-EVO#2519]
### Short Description of the issue:
After another player joins a multiplayer game, the host can no longer interact after the other person interacts in the world (spawning an entity or placing blocks)
...

### Steps to reproduce the issue:
Host a multiplayer session, have another person join and begin placing blocks, the host will no longer be able to interact.
...

### Environment
- Starship EVO version: 20w26b
- Graphics Card: RTX 2070 
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4822536/output_log.txt)
super

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Thanks Tom, it was a pretty big issue... Fixed for 20w26c. Cheers!
