### ISSUE TITLE
[BUG] Lag Spikes occuring with Windows photo viewer open

### ISSUE THREAD

**Issue by Brushes2** [tsunamayo/Starship-EVO#2520]
### Short Description of the issue:
Experiencing lag spikes every ~20-25 seconds regardless of location or task. Takes me from ~78fps to 2-4fps. I know it's photo viewer and not Starship EVO but i haven't experienced this issue in other games, or in Starship EVO until recently.

If i have a picture open with photo viewer, and start running the game, after a few minutes memory usage for photo viewer begins to jump way up.

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 20w26b
- Graphics Card: MSI GTX 980

### Additional information:
I've attached the photo in case that matters, it isnt a big one.
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4823489/output_log.txt)
![midhat-kapetanovic-alphabet-wings-01](https://user-images.githubusercontent.com/67161654/85507306-2f4ac900-b5c0-11ea-91a2-0eb0fff7f3d0.jpg)

**Comment by tsunamayo** [comment]
whoa thats a pretty weird one, you reproduce that several time? Thanks

**Comment by Brushes2** [comment]
Yes, every time i open that image with photo viewer and leave it in the background while playing. It takes a few minutes but memory usage begins to get high.

**Comment by Brushes2** [comment]
It just took 5min to duplicate. It may be necessary to zoom in on the image after opening, than minimize and play game.
