### ISSUE TITLE
[BUG]  broken docking process

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Starship-EVO#2525]
In the past, I could use the shipyard block to dock small space fighters in larger ships, unfortunately the entities were never connected. The last update should fix that. When I tried to test this, I noticed that it only positions the fighter but no longer lowers it into the dock.

### Environment
- Starship EVO version: 20w 26c
- Graphics Card: gtx 1070 mobile

### Additional information:

![Starship EVO_2020_06_24_14_27_09_645](https://user-images.githubusercontent.com/43222403/85556846-88017c80-b627-11ea-96cb-28cd9e739591.jpg)

Docking in this configuration has always worked

![Starship EVO_2020_06_24_14_27_34_281](https://user-images.githubusercontent.com/43222403/85556869-8c2d9a00-b627-11ea-9881-0a203b6684e3.jpg)
![Starship EVO_2020_06_24_14_28_17_912](https://user-images.githubusercontent.com/43222403/85556886-9059b780-b627-11ea-9e0f-14f9c1e71801.jpg)
the last picture shows how the fighter was automatically aligned over the dock but the docking process does not continue. 
In the past, the spacecraft slowly lowered itself into the dock until the landing gear touched down.

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4825360/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, please send me both your ship I will investigate! Thanks

**Comment by Battlepixel** [comment]
[ships.zip](https://github.com/tsunamayo/Starship-EVO/files/4828409/ships.zip)


I also tried to change the boundaries of the shipyard block and the distance of the entrypoint, but to no avail.

**Comment by tsunamayo** [comment]
Issue fixed for 20w27a. I will also make sure your ship stick inside the bigger one. Thanks
