### ISSUE TITLE
[Suggestion] Thruster switch on/off function

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#2528]
I'll be the first to admit to have used round thrusters for detailing since they are the only brick you can stretch in parallel to the mounting surface. Since the exhaust flames look out of place because of that, it would be very handy to be able to just turn them off with a switch.

![image](https://user-images.githubusercontent.com/63756057/85588155-56de7780-b63a-11ea-9858-dfb02def237f.png)

**Comment by tsunamayo** [comment]
haha, sorry mate I think I will have to shot down this one ;) I better give you some more detailing bricks, as what you are doing will have all kind of other impacts down the road (I will actually find a way to prevent it). Thanks
