### ISSUE TITLE
[BUG] Teleportation broke

### ISSUE THREAD

**Issue by Brushes2** [tsunamayo/Starship-EVO#2532]
### Short Description of the issue:
I got stuck in a ship so tried teleporting away and every place i went to the character was unable to move from the teleporter pad... and some locations would not load.

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 20w26c
- Graphics Card: 

### Additional information:
some pics showing oddities... hovering, things not loading, random plums, etc
![711980_20200624140251_1](https://user-images.githubusercontent.com/67161654/85616792-39a2ac80-b62c-11ea-9552-1b34c68e3ad6.png)
![711980_20200624140715_1](https://user-images.githubusercontent.com/67161654/85616978-7a9ac100-b62c-11ea-9a88-91e72a75027d.png)
![711980_20200624140820_1](https://user-images.githubusercontent.com/67161654/85617025-8f775480-b62c-11ea-987c-5a6307ce967a.png)

**Comment by Brushes2** [comment]
world save
[hijack big ship test.zip](https://github.com/tsunamayo/Starship-EVO/files/4827438/hijack.big.ship.test.zip)

**Comment by tsunamayo** [comment]
Thanks, for issue like this the output.log is also very much welcome as I guess there would be a lot of error spitting inside...

**Comment by Brushes2** [comment]
Right, sorry! I loaded the world again and got the same issues but not as bad. Maybe the beginning and end of the log has something? That's when I was teleporting inside terrain and ships.
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4828310/output_log.txt)

**Comment by tsunamayo** [comment]
@Brushes2 So I have used that save, nothing wrong except for the weird place...
As I dont have the correct log I dont think we will be able to investigate that one...
But if you see that happening again please book an issue with the log! When you see some weird thing happening and the game not responding, the only thing to do is to exit the game and send me the log ;)
Cheers, thanks for being so active over here!
