### ISSUE TITLE
[BUG] Cannot build or interact in Multiplayer after a bit

### ISSUE THREAD

**Issue by David184** [tsunamayo/Starship-EVO#2534]
### Short Description of the issue:

Tried playing in MP with friend but once he started to build, i couldn't build or interact with things. Friend was also frozen in place.

### Environment
- Starship EVO version: 20w26c

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4828041/output_log.txt)

**Comment by tsunamayo** [comment]
Issue fixed for 20w26d. Sorry for all this mp instability! Cheers
