### ISSUE TITLE
[BUG] Symmetry does not remove weapon addons

### ISSUE THREAD

**Issue by Brushes2** [tsunamayo/Starship-EVO#2537]
### Short Description of the issue:
As title says.

### Steps to reproduce the issue:
Place a large/small weapon base in symmetry mode, place an addon, now try to remove. Symmetry only places addons, not remove.

### Environment
- Starship EVO version: 20w26c

### Additional information:

**Comment by tsunamayo** [comment]
Hi, is is fixed in recent builds. Thanks
