### ISSUE TITLE
block request

### ISSUE THREAD

**Issue by darkvoid305** [tsunamayo/Starship-EVO#2539]
### Short Description of the issue:
we don't have this block and it would be realy nice if we did
...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

https://cdn.discordapp.com/attachments/725704872288059392/725705152639795320/unknown.png

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by darkvoid305** [comment]
I meant as a hull block sorry for not specifying that only saw it just now

**Comment by tsunamayo** [comment]
As a hull transparent? Because we already have the hull wedge. Thanks

**Comment by darkvoid305** [comment]
Yea but i cant find a small hull wedge with the width of a slab

**Comment by darkvoid305** [comment]
the one on the left is the window block wich this post is talking about the one on the right is the small wedge block wich we already have 

https://cdn.discordapp.com/attachments/726407219456901171/726407296288030801/unknown.png

**Comment by tsunamayo** [comment]
Ah okay, yeah I am not sure I want to go into that direction, after people would request all sort of half-width shape to go with the rest of their half-width build... The transparent one is there to make side canopy... Thanks
