### ISSUE TITLE
[Bug] Rail stops responding to sequencers permanently after reaching full extension via sequencer

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#2540]
### Short Description of the issue:

...After using a sequencer gate to set a block rail at maximum extension, the rail no longer moves when any sequencer gate tries to set another position. This includes the gate that set it to its position in the first place.

### Steps to reproduce the issue:

...- Place stretched block rail
- link 2 or more sequencers to the rail
- set one sequencer with the rail's maximum extension value
- activate the sequencer with the maximum value
- activate the other sequencer
- toggle rail manually with F (to show it isn't just stuck on something)

### Environment
- Starship EVO version: 20w26c
- Graphics Card: Nvidia GeForce GTX 1060 6GB

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4833878/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, I think the issue is that you should not be able to link two sequence to a rail, it would cause all sort of issue it was not intended to work that way.
So instead I will prevent you doing that...
Cheers

**Comment by tsunamayo** [comment]
Okay fixed for 20w27c. Cheers

**Comment by ProPeach** [comment]
Is there another way you could prevent this? If you can only link one sequencer to a rail/rotor etc, then we'll only be able to toggle it between two positions which is very limiting.

This also breaks an extremely simple elevator circuit that players have been using.

It consists of a Button -> Sequencer -> Rail link for each floor  then you set the Off value in the sequencer to the right position on the rail for the desired floor.
I think the problem arises only when you send multiple *On* signals to a rail, but isn't that a logic error rather than an error with the game?

**Comment by Majikmonster** [comment]
Wait a minute! We weren't supposed to be able to do that all along? I'm confused as to why you think that's a bug and not a feature.

I agree with ProPeach that it's a problem that this use case can't be handled by logic rather than a problem the use case was possible in the first place, and that's exactly how I thought of it when I submitted the issue. If reporting bugs like this results in removed features, I'll be more selective in what I submit tickets for in the future.

**Comment by ProPeach** [comment]
@tsunamayo I think there's been a bit of a misunderstanding here ^

**Comment by Aiwii** [comment]
How exactly can one define multiple states for a mechanism if we cannot link multiple sequencers to them? If we can get an option for that I'm fine with this _feature_ being removed.

**Comment by Xenoprophet-Nail** [comment]
Yeah, this is going to break a lot of elevators people have made using this.

**Comment by SovietSponge** [comment]
Rn elevators can be made really simple which is awesome since it actually makes them accessible to most people, if this gets removed then it'll really be a gut punch to us that aren't that skilled with logic.
