### ISSUE TITLE
Game Running, But Can't See Anything

### ISSUE THREAD

**Issue by ZedMercury** [tsunamayo/Starship-EVO#2541]
### Short Description of the issue:

I start the game up and while its definitely running, the game cursor shows up, the music plays, ect. nothing shows up on screen, all I can see is my desktop. This issue shows up every time I boot up the .exe, preventing me from playing the game.

### Steps to reproduce the issue

1. literally just start up the .exe in any way shape or form

### Environment
- Starship EVO version:  20w26c I believe, its the most recent version at this time in 6/25/2020
- Graphics Card:  Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz 2.80 Ghz

### Additional information:
playing on an Acer Laptop, laptop model: Acer Aspire VX5-591G
![image](https://user-images.githubusercontent.com/67449056/85815429-39360e80-b71d-11ea-87fb-ce9c49e26056.png)

I know it just looks like I tabbed out of the game, but believe me no matter how many times I click on it, the cursor will change, but I can still only see my desktop.

**Comment by tsunamayo** [comment]
Hi, sorry to hear that.
Do you have a multi monitor setup?

It seems there is other ACER owner with the same issue as you, it is related to some Intel drivers:
https://forum.unity.com/threads/games-not-showing-invisible-in-full-screen.538738/
If you can make sure that all your driver (GFX card and other) are up to date!
Thanks

**Comment by ZedMercury** [comment]
I do not have a multi-monitor setup (not even sure you can do that with a laptop) 
I looked onto the threads and their solutions were related to windows 7, I use windows 10 so that doesn't apply to me.
My drivers are all up to date.
The only solution I found that could've helped said to download a certain VGA driver or something, but because he shared no link and he was very vague it wasn't much help.
I do think its intel related, I just don't know where to go from there.

**Comment by tsunamayo** [comment]
Have you tried alt-tab - Could you send me a screenshot of alt-tab? Thanks

**Comment by ZedMercury** [comment]
![image](https://user-images.githubusercontent.com/67449056/85927672-8240ac80-b85c-11ea-84a2-19234301fcce.png)

This is what I get when I press Alt+Tab

**Comment by ZedMercury** [comment]
oh nevermind, I was able to fix the issue by downloading and older driver believe it or not. thank you for your help regardless.

**Comment by tsunamayo** [comment]
@ZedMercury a new user has the same issue on an ACER laptop... Did you download an older GFX driver or another driver? Thanks
