### ISSUE TITLE
Creation Fell through ground

### ISSUE THREAD

**Issue by Caesura17** [tsunamayo/Starship-EVO#2542]
### Short Description of the issue: A ship which I had been building for the past few hours fell through the ground of the Habitat Upon removing the starter block and allowing it to fall. All creations that weren't attached to the ground fell through as well, along with anything I tried to spawn. I had not saved the ship, as I was trying to move it before doing so, and Have now lost the past few hours of progress, which is more than a bit disappointing. I mean... It's "early access" for a reason, and I knew the risk was there but... well, you know. I'm sure you've gone through a lot more frustration with the game than I have.

...

### Steps to reproduce the issue: I don't know what I did exactly. Before it happened, I had left the world with a large "ship" (it was really only a shell at that point, with no computer identifying it as a ship) in it and decided to rejoin in order to save the blueprint. I had left with a starter block attached to the ship, and when I pressed Tab to try and get to the ship screen it (The tab on the left of the inventory) wouldn't show up so I deleted the Starter block and planned to replace it and try again. When the ship's starter was removed, it began succumbing to gravity, and I suspected that it would stop once it hit the ground, like would make sense. Unfortunately, I was wrong. When I tried to spawn another ship in thinking that I may be able to go out to the other side (The outside) of the habitat and see if it had continued all the way through the ground, the ship I spawned also fell through the ground. See Attached Video

...

### Environment
- Starship EVO version: 20w26c
- Graphics Card: nvidia geforce gtx 1060 6GB

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4835110/output_log.txt)   //   I dragged the file straight onto the page. This isn't what I expected it to make, but hopefully that's right.

[Video.zip](https://github.com/tsunamayo/Starship-EVO/files/4835120/Video.zip)   //   The website doesn't like video files, so I put it in a Zip Folder and attached that.

Thank you for attention.

**Comment by Caesura17** [comment]
PS, I have no idea what happened to the crop of that video, but you can still see all of the important things.

**Comment by Caesura17** [comment]
PPS, The player is able to interact with/ walk on the ground. It's only freefloating Creations that don't. (The Tutorial buildings were also collisionless, and the default hovercrafts as well as the default ships had fallen through the building and ground respectively)

**Comment by Aiwii** [comment]
@Caesura17 If you didn't despawn the craft you can teleport to its position within the ground by pressing F3 and scrolling to the bottom and enabling the ability to teleport to any ship. Then open the teleport menu and teleport to it so you can save it.

**Comment by tsunamayo** [comment]
Hi, sorry for hearing this and thanks for booking the ship. Aiwii is correct, if you cant manage to do it can you zip your character folder here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\
 I will send you back your ships - no problem we will get them back!
It seems it must have been an issue relative to AI causing this - I will get back to you.
Cheers

**Comment by Caesura17** [comment]
I was able to get to it by using the teleportation, and managed to get a
good laugh out of seeing the piles of ships that were sitting down there at
the same time. Thanks for the help and the timely response. I'm enjoying
the game so far other than the occasional ship sinking through the ground
and then being jettisoned into the cosmos, but now that I can solve the
issue myself it's no more than the occasional annoyance. Keep up the good
work, and thanks for the entertainment.

**Comment by tsunamayo** [comment]
Thanks mate, issue should be fixed for 20w26d. Not sure 100% as it is not something  I could reproduce, tell me if you ever see this again! Cheers
