### ISSUE TITLE
[Bug] "Host cannot interact" still persists

### ISSUE THREAD

**Issue by Tomatart** [tsunamayo/Starship-EVO#2546]
### Short Description of the issue:
After a player joins a multiplayer session the host can no longer interact.
...

### Steps to reproduce the issue:
Host a multiplayer and have someone join and build/spawn something.
...

### Environment
- Starship EVO version: 20w26c
- Graphics Card: RTX 2070 Super

### Additional information:
This is the same bug submitted for the previous build
_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Okay this time it should be good. For 20w26d. Thanks
