### ISSUE TITLE
[Crash] Spawning Blueprint crashes game soft locks game

### ISSUE THREAD

**Issue by MRonlin** [tsunamayo/Starship-EVO#2547]
### Short Description of the issue:
When spawning in this specific blueprint, it crashes the game, when reloading the character it crashes every time (I was not able to get back into this character again). Using it on a fresh character it will do the same thing.

### Steps to reproduce the issue:
Spawn in the blueprint. (It will crash the character)

### Environment
- Starship EVO version: 20w26c
- Graphics Card: gtx 1050

### Additional information:

Log: [output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4838996/output_log.txt)

The infamous blueprint: [The Reverence 3.zip](https://github.com/tsunamayo/Starship-EVO/files/4839005/The.Reverence.3.zip)

**Comment by tsunamayo** [comment]
Okay there is cleary a corruption in the save. I would like to know what did you do regarding children entity (rotator I guess), there was a  manipulation you did that trigger the issue (and this is the real fix I need to do!). I will also try to deal with such corruption in a smooth way. Thanks!

**Comment by tsunamayo** [comment]
Okay I have fixed the freeze for 20w26d. Still want some detail on how that happened if you remember something! Thanks

**Comment by MRonlin** [comment]
I was trying to get around the turret clipping bug #2543, trying out different things to see what worked, for some reason the vertical rotor wasn't working, I was going to rebuild the entire turret, but thought that it would be best to save the vehicle before continuing, when I went to spawn in the vehicle again, my game froze and crashed.
