### ISSUE TITLE
Hoverbike clips through platform attached to rail on powering down

### ISSUE THREAD

**Issue by CurioInventorium** [tsunamayo/Starship-EVO#2550]
### Short Description of the issue:
A sideways moving platform was created for moving vehicles up to a mountain top base. Moving the vehicle onto the platform works fine, but when powering down the vehicle clips through the platform onto the ground.

...

### Steps to reproduce the issue:
I'm guessing by building a platform attached to a rail that moves horizontally. In the one tested on, there's a rotate block first with a rail attached, so that the rail is at a 55 degree angle. Essentially a sloping rail system for connecting a mountain top to ground level.
The platform is then built by having another rotate block to counter the angle of the initial one, so that the blocks for the platform are level.
Driving a hoverbike style vehicle on it and then powering it down should replicate the problem.
**An important note** is that the ground-level platform is a separate base from the mountain-top and they are clipping into each other at the end of the rail system. This seemed to be the only way to get everything to work in terms of alignment.
But may (most likely) the source of the problem. Too many objects clipping?
...

### Environment
- Starship EVO version: 20w26c
- Graphics Card: NVIDIA GeForce RTX 2060

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

YouTube link: https://youtu.be/WsLMT2JJ13E?t=284
Note: This is a few versions back, but the bug was replicated in 20w26c as well.

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4840295/output_log.txt)
Screenshots show the hoverbike vehicle still powered up.
![20200627111033_1](https://user-images.githubusercontent.com/51359034/85919965-b5d50400-b867-11ea-9434-29f50a8f8760.jpg)
![20200627111046_1](https://user-images.githubusercontent.com/51359034/85919966-b8cff480-b867-11ea-8f27-8e7f4e9618fa.jpg)

**Comment by tsunamayo** [comment]
Hi, so I had a look at it, and it should be fixed for 20w27a. Thanks!
