### ISSUE TITLE
[BUG] Blueprints from before 20w26d have black lines

### ISSUE THREAD

**Issue by alxnns1** [tsunamayo/Starship-EVO#2552]
### Short Description of the issue:

Blueprints from before 20w26d that I spawn in have black lines. Ships that were already in the world do not.

### Steps to reproduce the issue:

Spawn in the provided ship blueprint

### Environment
- Starship EVO version: 20w26d
- Graphics Card: GTX 1050 Ti

### Additional information:

![20200627124346_1](https://user-images.githubusercontent.com/485571/85921465-6d701300-b874-11ea-810d-6b0dcec00166.jpg)

[Charon.zip](https://github.com/tsunamayo/Starship-EVO/files/4840437/Charon.zip)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4840439/output_log.txt)

**Comment by MRonlin** [comment]
I Don't think its because of the update, I was having the same issue a while ago #2426 Usually happened on the character worlds with lost of ships spawned.

**Comment by tsunamayo** [comment]
I never manage to reproduce the issue, could you please send me your full character folder, I might reproduce this way. Thanks

**Comment by alxnns1** [comment]
I just did some more testing and have some more info; the void lines are on any entity that I spawn in or build, reloading clears up the void lines, and on a new world they don't appear. I think it's to do with the fact that I have multiple large structures on and around the habitat.

Here's my world:
[Alex.zip](https://github.com/tsunamayo/Starship-EVO/files/4841434/Alex.zip)

**Comment by tsunamayo** [comment]
@alxnns1 did you did one or several quit to title to see the problem pop?
Also do you see that often?
Can you interact with the block row? Can you paint them for example?
Thanks

**Comment by alxnns1** [comment]
The problem started after the update but that also coincided with when I spawned multiple space elevators on the habitat, each about 1km long.
On that save it happens 100% of the time.
As for painting, the whole entity reacts weirdly to paint as shown here:
https://imgur.com/LVJ9EzU

**Comment by tsunamayo** [comment]
hey mate I just managed to reproduce! I had to spawn a yamato and a obsidian class to reproduce, but I got the bug. I have black and orange paint on my side, but I see the same weird behaviour when painting.
I will start the investigation, cheers

**Comment by tsunamayo** [comment]
Okay issue fixed for 20w27a! Thanks I am glad we finally got that one ;)
