### ISSUE TITLE
[Suggestion] New Laser barrel, possible rename to Plasma?

### ISSUE THREAD

**Issue by Adtrl** [tsunamayo/Starship-EVO#2554]
Wondering one day why don't we have a laser barrel that redirects it in multiple ways like a shotgun. I'm thinking it could look like a Disco ball, or so while the barrel itself could influence the shots spread. Say the shorter the barrel makes the shots spread out more while the longer one compacts the shots.
P.S. Now I'm thinking of a rotating shotgun barrel for Autofire spreading shots, and a shotgun like effect for shots on the other barrels. Maybe it could be a module at that point, maybe.
---------------------------------------------------------------------------------------------------------------------------------------
Secondly, I found the names of the two barrels ,Laser and Beam, to be confusing as to me they seem the same in name. (IE Laser Beam) So I'm thinking would it to much to, maybe, rename Laser to Plasma? Merely to differentiate the two barrels Laser-Projectile and Beam-laser beam.
No problem if it's a no.

**Comment by MRonlin** [comment]
The "laser" does already have the Gatling barrel addon

**Comment by Adtrl** [comment]
> The "laser" does already have the Gatling barrel addon

I'm aware of this, I mean like a new barrel that when you press the fire button, it fires multiple shots instead of one really really fast.

**Comment by tsunamayo** [comment]
Yes I guess you are right for the name, but for the shotgun I will have to shoot down that one ;) as it would create a bit too much performance and network load gratuitously! But I dig that idea - it just I have to keep in mind performance.
Cheers
