### ISSUE TITLE
[Bug] Export UI doesn't fit on screen when resolution is set to 1280x720

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Starship-EVO#2556]
### Short Description of the issue:
![image](https://user-images.githubusercontent.com/53021785/85934278-30207b00-b89e-11ea-9e93-d80027109351.png)

...

### Steps to reproduce the issue:
- set resolution
- open export menu
- issue
...

### Environment
- Starship EVO version: 20w26d
- Graphics Card: Integrated Graphics Gang

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4841444/output_log.txt)

**Comment by tsunamayo** [comment]
yes I have a lot of issue with the 720p resolution, I think I am gonna give up on that and scale it down on 720p...

**Comment by tsunamayo** [comment]
Fixed for 20w27b, UI will scale down like in 1080p. Thanks
