### ISSUE TITLE
[GRAPHICS] Big space particles

### ISSUE THREAD

**Issue by Brushes2** [tsunamayo/Starship-EVO#2557]
I thought something was flying at me but it was just one of the space particles that fade in and out. Haven't noticed it before but they're pretty big and solid causing them to appear as glowing orbs.

### Environment
- Starship EVO version: 20w26d
- Graphics Card: MSI GTX 980

### Additional information:
![blobs](https://user-images.githubusercontent.com/67161654/85934966-80a4d200-b8b8-11ea-9381-4a6da225abca.jpg)

![711980_20200627194726_1](https://user-images.githubusercontent.com/67161654/85934924-fe1c1280-b8b7-11ea-9005-f7414eecf73d.png)

**Comment by ZachZent** [comment]
Space ghosts probably

**Comment by tsunamayo** [comment]
Finally fixed for 20w46a. thanks
