### ISSUE TITLE
[BUG] landing on a station and repairing doesn't seem to repair your ship

### ISSUE THREAD

**Issue by Womble-TC** [tsunamayo/Starship-EVO#2558]
### Short Description of the issue:
My ship was damaged, so I landed on a landing pad to repair it by pressing "repair". Visually, this repaired my ship but I still couldn't interact with the broken component since it said it needed to be repaired first. I tried to use the repair tool, but this didn't help.

### Steps to reproduce the issue:
-Damage your ship
-Land on a station and repair your ship by pressing "repair"
-Try and Interact with the block
...

### Environment
- Starship EVO version: 20w26d
- Graphics Card: GTX 970

### Additional information:

![image](https://user-images.githubusercontent.com/29961381/85934946-389aa500-b8e2-11ea-959a-a37b9195e75d.png)
![image](https://user-images.githubusercontent.com/29961381/85934951-40f2e000-b8e2-11ea-9f02-41a8cbcc7ca4.png)

Here is the Blueprint if that helps: 
[X-wing 4.zip](https://github.com/tsunamayo/Starship-EVO/files/4841503/X-wing.4.zip)

**Comment by tsunamayo** [comment]
Okay great test case indeed, issue fixed for 20w27c. Thanks!
