### ISSUE TITLE
[BUG] Build orientation indicators gone

### ISSUE THREAD

**Issue by Brushes2** [tsunamayo/Starship-EVO#2559]
### Short Description of the issue:
Not sure if it's a bug but i didnt see it mentioned in update notes. It seems the orientation arrows are gone when building things. All sides of the build cube have red/green/blue so i'm confused.

### Environment
- Starship EVO version: 20w26d
- Graphics Card: MSI GTX 980

### Additional information:
![711980_20200627194339_1](https://user-images.githubusercontent.com/67161654/85934983-dc6f5b00-b8b8-11ea-8f5f-1b77d366918e.png)

**Comment by tsunamayo** [comment]
Fixed for 20w27a. Thanks!
