### ISSUE TITLE
[SUGGESTION] Heat Dissipation

### ISSUE THREAD

**Issue by Brushes2** [tsunamayo/Starship-EVO#2561]
To make ship heat dissipation based on blocks with faces exposed to space so that interiors dont add to dissipation rate.

**Comment by tsunamayo** [comment]
So this is the case for the surface heat, but not the case for hull block heat. It might change, we shall see. Thanks

**Comment by Brushes2** [comment]
What's the difference between hull block heat and surface heat? I put small and large blocks into an enclosed area and both added to the ships heat dissipation. It doesn't distinguish between different types.
