### ISSUE TITLE
ship display in the buildingdrone menu overlaps some of the UI boxes

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Starship-EVO#2562]
ship presentation overlaps the top UI boxes in the Building drone menu:

![20200627152651_1](https://user-images.githubusercontent.com/45324484/85939443-4698f780-b8db-11ea-8bc7-ca07aa129bf5.jpg)

Image below shows the two UI text boxes and how they differ
![20200627152743_1](https://user-images.githubusercontent.com/45324484/85939451-5284b980-b8db-11ea-8bcd-9704eaee87c6.jpg)

...

### Environment
- Starship EVO version: 20w26d
- Graphics Card: 1080ti

**Comment by tsunamayo** [comment]
Fixed for 20w27a. Thanks!
