### ISSUE TITLE
Disappearing ships and ring when scrollwheel clicking on a ship

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Starship-EVO#2563]
Anything built will disappear when using the scroll wheel click to lock onto a ship... the ring will also disappear 

![20200627232019_1](https://user-images.githubusercontent.com/45324484/85939528-ebb3d000-b8db-11ea-9a7e-17cb8f1ba0fe.jpg)
![20200627232029_1](https://user-images.githubusercontent.com/45324484/85939530-eeaec080-b8db-11ea-876f-115ddecab95b.jpg)
![20200627232034_1](https://user-images.githubusercontent.com/45324484/85939531-f0788400-b8db-11ea-847d-28703477d2aa.jpg)

### Environment
- Starship EVO version: 20w26d
- Graphics Card: 1080ti

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4841755/output_log.txt)

**Comment by tsunamayo** [comment]
It is weird you shouldnt see all the module boxes... Was this station spawned by the game or by you? Thanks

**Comment by ExodistSKY1** [comment]
It was not spawned in it was natural

**Comment by tsunamayo** [comment]
Do you get that on any world or just this one? Could you send it to me if yes?
Thanks

**Comment by ExodistSKY1** [comment]
It seems to just be that one world during the open port Multiplayer session

**Comment by tsunamayo** [comment]
Ho so this is a multiplayer session? This kind of detail is important ;)
Were you the host or the client? Other was fine?
What entity did you selected, was it NPC or something spawned by you? Thanks

**Comment by tsunamayo** [comment]
Okay I manage to reproduce, issue fixed for 20w27b. Thanks!
