### ISSUE TITLE
Handheld weapons will just float in gravity when thrown out of inventory 

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Starship-EVO#2564]
Handheld weapons will just float in gravity when thrown out of inventory 

![20200628001056_1](https://user-images.githubusercontent.com/45324484/85939597-7eed0580-b8dc-11ea-967f-3adf3200801f.jpg)

### Environment
- Starship EVO version: 20w26d
- Graphics Card: 1080ti

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4841755/output_log.txt)

**Comment by Aiwii** [comment]
you have to despawn them like ships, I think the idea is so you can drop them and pass them to others

**Comment by tsunamayo** [comment]
This should be fixed in recent update 20w27a. Thanks
