### ISSUE TITLE
Linking tool sound hurts in headphones

### ISSUE THREAD

**Issue by gertvdwalt** [tsunamayo/Starship-EVO#2565]
### Short Description of the issue:
Linking tool very loud with high base.
...

### Steps to reproduce the issue:
Use linking tool to connect logic etc.
...

### Environment
- Starship EVO version:  20w26d
- Graphics Card: n/a

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Tweaked for 20w27a. Dont hesitate to report any more weird stuff sound wise! Thanks

**Comment by gertvdwalt** [comment]
Thanks. it was the first thing I checked when I saw there was an update
