### ISSUE TITLE
Codex Item description is missing

### ISSUE THREAD

**Issue by gonzo6969** [tsunamayo/Starship-EVO#2566]
### Short Description of the issue:

The item descriprition disappears. I could not find a key to reactivate ...

### Steps to reproduce the issue:

No idea

### Environment
- Starship EVO version: 20W26D, steam-edition
- Graphics Card: GEFORCE GTX970
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4842127/output_log.txt)
![codex-screen](https://user-images.githubusercontent.com/58293977/85945941-4a5f6500-b941-11ea-9914-2285d84650ff.jpg)

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Issue fixed for 20w27a. Thanks!
