### ISSUE TITLE
[BUG]Blueprints from files saved in game or downloaded from Skywa.re not spawning in game.

### ISSUE THREAD

**Issue by Servomotor** [tsunamayo/Starship-EVO#2568]
### Short Description of the issue:
I had 30ish blueprints in my blueprint folder and was only able to get about 5 of them to spawn.
I started a new game. Updated drivers. Downloaded blueprints from Skywa.re and tried to spawn them and they will still not spawn.

Aiwi tested one of my blueprints and it would not spawn for them either.
DarthPeters Interceptor will not spawn either. 
...

### Steps to reproduce the issue:
Try to spawn ship with starter block
...

### Environment
- Starship EVO version: 20w26d
- Graphics Card: RTX 2080 current drivers

### Additional information:
[Blueprints that will not spawn.zip](https://github.com/tsunamayo/Starship-EVO/files/4842770/Blueprints.that.will.not.spawn.zip)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4842779/output_log.txt)

**Comment by alxnns1** [comment]
[Blueprints.zip](https://github.com/tsunamayo/Starship-EVO/files/4842783/Blueprints.zip)
Here are mine that won't spawn

**Comment by tsunamayo** [comment]
Issue fixed for 20w27a. Thanks!
