### ISSUE TITLE
[bug] Modules Spawning with Black Lines

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Starship-EVO#2571]
### Short Description of the issue:
So I'm working on a large terrain structure and I reloaded the game after some physics issues. I spawned and placed a few modules and now they spawn with black lines. https://streamable.com/o0wer9
...

### Steps to reproduce the issue:
- no clue
...

### Environment
- Starship EVO version: 20w26d
- Graphics Card: Integrated Graphics Gang

### Additional information:

Character Data: [Modular City Map V.2.zip](https://github.com/tsunamayo/Starship-EVO/files/4843152/Modular.City.Map.V.2.zip)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4843162/output_log.txt)

**Comment by tsunamayo** [comment]
Yes it is a known bug, but I never manage to reproduce the issue, I will try with your character save. Amazing idea btw!

**Comment by tsunamayo** [comment]
Of course I cant reproduce the bug...
Does it happen straight away after loading or after a long session?
Does it happens 100% of the time?
When you say reloaded the game you mean quit to title or back to windows?
Thanks

**Comment by Aiwii** [comment]
It seems to happen immediately after I load in. And it happens every time. I reload by quitting to desktop

**Comment by tsunamayo** [comment]
Issue finally fixed! Glad we got that one, thanks a lot! For 20w27a. Cheers
