### ISSUE TITLE
[Suggestion] Brick weapons scaled down to the datail level seen on the multi-tool

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Starship-EVO#2572]
After playing with the personal weapons builder for a little over a week or two I have a suggestion 

My suggestion:

     Scale the bricks to allow for multi-tool level detailing on small arms 

Seen in this image, the detailing makes sense and flows with the graphics revamp
![20200628223743_1](https://user-images.githubusercontent.com/45324484/85971952-31cc6a80-b994-11ea-98fc-acbd0fad3b16.jpg)

Seen in this images below, The detailing is there kind of but this is the smallest you can go without it looking dumb and blocky... if we had the old art style this would be the perfect size and the right approach. But in order to stay true to the newer graphics I feel a more detailed approach is necessary. With this smaller scale detailing comes far more creativity and variance with the weapons than we as a community have already produced, and that is never a bad thing!

![20200628231144_1](https://user-images.githubusercontent.com/45324484/85972555-ee72fb80-b995-11ea-8de8-098639dfe9ee.jpg)
![20200628231152_1](https://user-images.githubusercontent.com/45324484/85972558-f03cbf00-b995-11ea-8170-4b14d6a42c18.jpg)
![20200628231231_1](https://user-images.githubusercontent.com/45324484/85972562-f16dec00-b995-11ea-8507-d3a8cca246f9.jpg)
![20200628231248_1](https://user-images.githubusercontent.com/45324484/85972565-f29f1900-b995-11ea-9f31-46d28eb0a7f4.jpg)
![20200628230234_1](https://user-images.githubusercontent.com/45324484/85972571-f5017300-b995-11ea-84c5-3a794a244102.jpg)

There are a few other things I would love to see added:

- a pistol grip similar to the Multi-tools
-a flat or angled fore-grip for the off hand on two handed weapons 
-Possibly simple optics???  (Such as futuristic red dots/ scopes)
-The weapons on small arms need to have their damage nerved hard and fire rates possibly increased

I really enjoy having the ability to create my own small arms and thank you for implementing this into the game!

**Comment by Kaiser-Indrasil** [comment]
I agree, having a much smaller brick scale for guns than we have now would enable a much higher design diversity, both in terms of looks and function. I also agree that they should have their DPS lowered and maximum fire rate massively increased to enable weapons like assault rifles.

All these changes sound like reasonably easy to pull off and would make an already awesome and unique feature even better!

**Comment by Tomatart** [comment]
I am in complete agreement with the above statements.

**Comment by Tommyg930** [comment]
I agree with this suggestion. correctly the way things are, bricks are already quite big. and none of them really provide any useful starts like cooling which you kind of need to even remotely need to make any kind of solid assault or squad support weapon. you can only really do that with normal hull blocks. and if the bricks are already a bit too large, normal blocks are 4 times too large.

**Comment by tsunamayo** [comment]
@ExodistSKY1 first let me tell you I really love your weapon design, can I get the blueprint? I think people manage to create amazing stuff with it.
I can see why you guy would want that, and indeed you could make crazy design with it, but on the flip side:
- I dont have time to work on the many issues this would cause, I already spent way too much time on that
- Weapon will also be a mech thing
- I like the current block style and they look in place with the rest of the ship
- they propose a quick and fast build opportunity when you are tired of your massive ship...

@Kaiser-Indrasil they are not easy, nothing is easy. For example how you build on the mini scale? How you deal with mini weapon, how you deal with balancing ect ect, plus all the things I even think about yet.

We already had that debate when weapon were released.

Cheers and sorry guys ;)

**Comment by ExodistSKY1** [comment]
[Exodists Player & mini Mech weapons.zip](https://github.com/tsunamayo/Starship-EVO/files/4862224/Exodists.Player.mini.Mech.weapons.zip)
@tsunamayo 

Here you go, I hope you like them!!  (can you delete this post, I am weird with my builds)

Just a shameless request: could you shrink the personal weapons down just a tiny bit more??? not asking for extreme detail! and I understand if no!  ;)  Also they will look fantastic with mini-mechs I am eagerly awaiting to get my designs built!!!
