### ISSUE TITLE
The turret dont move

### ISSUE THREAD

**Issue by omrwcs** [tsunamayo/Starship-EVO#2574]
### Short Description of the issue:
The turret dont move
...

### Steps to reproduce the issue:
finished the turret and dont move
...

### Environment
- Starship EVO version: 20w26d
- Graphics Card: gtx750

### Additional information:
i make tree turret and dont moved, dont follow the mouse
_(Screenshots, Videos, Error logs, Related issues)_
the ship is there (need login steam)
https://steamcommunity.com/sharedfiles/filedetails/?id=2147044681
Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4846127/output_log.txt)

**Comment by Adtrl** [comment]
To make a turret that fully works you'll need a Yoke, Turret controller, hotkey gate, and Camera.
2. Place them down and leave them easy to access for linking later and make sure you set the Hotkey gate to Fire Primary. (Or another other one you'd like to shoot with.)
3. Place your Rotor down so the turret can move left to right followed by another rotor or hinge for the up and down.
4. Set the left and right rotor to Vertical followed by the other rotor(s)/Hinge(s) to Horizontal Inverted.
5. Place your weapon of choice, if Laser a barrel of your choice.
6. Now link the yoke to the Turret controller than to the hotkey gate and lastly the Camera.
7. Now link your TC(Turret controller) to the rotor(s)/Hinges and barrels.
Finally 8. Now link your Hotkey gate to the barrel(s).
Boom, there you go. A fully working turret.

**Comment by omrwcs** [comment]
I did like this in the example of the tutorial and it did not work

**Comment by ProPeach** [comment]
Does your ship have power? Turrets need power

**Comment by omrwcs** [comment]
have power :) the turret dont follow the mouse, is confuse control

**Comment by tsunamayo** [comment]
@omrwcs do you use them in manual mode or in auto-tracking mode? Thanks

**Comment by omrwcs** [comment]
i think is manual mode. thanks you :)

**Comment by omrwcs** [comment]
i make one turret laser and have problem: no possible control turret is confuse control

**Comment by tsunamayo** [comment]
@omrwcs could you send a screenshot of your turret build? While selecting the turret core with the link tool. Thanks

**Comment by omrwcs** [comment]
Yes sure :) my friend, here the turret
https://youtu.be/PHWmwbizi6g
![turret](https://user-images.githubusercontent.com/67280789/86357427-328b2800-bc44-11ea-9963-a00904a2ca4d.jpg)

**Comment by tsunamayo** [comment]
Your turret is good from an auto standpoint. If you want to use it manually you will need to set your axis settings in each rotator. It sucks a bit, I will try to do it automatically in an upcoming update. Thanks

**Comment by tsunamayo** [comment]
So now you no longer needs to specify the axis manually. Thanks
