### ISSUE TITLE
[Bug] Massive lag when spawning into world, long load time, no entities load in

### ISSUE THREAD

**Issue by AsageSoftworks** [tsunamayo/Starship-EVO#2575]
[Starship EVO Asage 06-29-2020.zip](https://github.com/tsunamayo/Starship-EVO/files/4847105/Starship.EVO.Asage.06-29-2020.zip)

### Short Description of the issue:

...Loading into Starship Evo today took around 10 minutes. When I finally spawned in the game dropped to well below 20 frames/second. No entities were loading, the torus had a checker pattern grid on it. 

### Steps to reproduce the issue:

...I honestly do not know if it is possible to reproduce it. 

### Environment
- Starship EVO version: Latest 06/29/2020 1100 cst
- Graphics Card: GTX 1070ti

### Additional information: My computers RAM usage for SEVO was at 7.5gb consistently during loading and after spawning.

_(Screenshots, Videos, Error logs, Related issues)_
https://streamable.com/c9f28e
![Annotation 2020-06-29 114633](https://user-images.githubusercontent.com/43458562/86034057-8e18a400-b9ff-11ea-86bf-6a98c2aa9e11.png)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4846933/output_log.txt)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by AsageSoftworks** [comment]
Bug continues after a fresh install for me. Will do a full Steam uninstall to check if that fixes it.

**Comment by AsageSoftworks** [comment]
Full steam install did not fix it.

**Comment by AsageSoftworks** [comment]
File integrity validation came back with no issues

**Comment by tsunamayo** [comment]
@AsageSoftworks I guess you have a GFX card issue.
You say 1070ti but in the log file it says Intel(R) HD Graphics 530, so maybe your gfx card is not correctly setup of something.
Also there is some Sound problem of some sort, do you have sound in the game? Thanks

**Comment by AsageSoftworks** [comment]
I did not notice any sound at all.

**Comment by tsunamayo** [comment]
Did you looked into your GFX setting, it seems you were running it on the motherboard card not the nvidia one.

**Comment by tsunamayo** [comment]
@AsageSoftworks any news? Did you fixed it? Cheers

**Comment by AsageSoftworks** [comment]
Yessir, my apologies I guess my previous reply didn't send. The fix was to go into windows apps manager, force SEVO to run on dedicated graphics.

**Comment by AsageSoftworks** [comment]
I still have no idea why the game decided to run on my motherboard though. That was a random occurrence.
. .

**Comment by tsunamayo** [comment]
Okay great to hear! Yeah the wonderful magic of windows ;) Cheers
