### ISSUE TITLE
[BUG] Tooltips Missing for Codex

### ISSUE THREAD

**Issue by Kadzar** [tsunamayo/Starship-EVO#2576]
### Short Description of the issue:

All the tooltip info is currently missing for the codex, as only the currently selected block is shown.

### Steps to reproduce the issue:

Open codex, mouse over blocks, see that the tooltip info isn't shown.

### Environment
- Starship EVO version: 20w26d
- Graphics Card: NVIDIA GeForce GTX 1080

### Additional information:

![20200629160502_1](https://user-images.githubusercontent.com/66035211/86056291-db5a3d00-ba22-11ea-9427-feabb548fb29.jpg)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4848055/output_log.txt)

**Comment by tsunamayo** [comment]
Yes this is fixed for 20w27a. Thanks!
