### ISSUE TITLE
The blocks seem to be semi-invisible, hard to tell where I'm placing them.

### ISSUE THREAD

**Issue by L3GAC7** [tsunamayo/Starship-EVO#2578]
### Environment
- Starship EVO version: Early-access 20w27a
- Graphics Card: Intel(R) Iris(R) Plus Graphics

### Additional information: The blocks appear as if they are see-through, in this image,  https://i.imgur.com/lI3TEsp.png

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4850180/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, do you get this for all your starter block? Thanks

**Comment by L3GAC7** [comment]
> Hi, do you get this for all your starter block? Thanks

Yes, that seems to be the case.

**Comment by tsunamayo** [comment]
Can you give me more info on your GFX card? It seems to be quite low, what other 3d game are you running on? Thanks

**Comment by L3GAC7** [comment]
> Can you give me more info on your GFX card? It seems to be quite low, what other 3d game are you running on? Thanks

I'm not exactly sure how to do that, but I am running Windows 10, and my Microsoft Surface Pro 7 can run Hitman 2 at max settings.
Maybe the display? Desktop resolution: 1368 x 912, active signal resolution: 2736 x 1824, refresh rate: h9 Hz, bit depth: 8-bit, color format: RGB, color space: Standard dynamic range.
