### ISSUE TITLE
[Bug] Items dragged from codex hidden under codex until over hotbar

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Starship-EVO#2579]
### Short Description of the issue:

Sorry if this has been reported already, I had a quick look and didn't see it.

Dragging an item from the codex on to your Hotbar, whilst the item is being dragged, it is 'under' the codex panel, and only visible to see what you are dragging once you drag it over the Hotbar.
Here is a screenshot, you can see the item I am dragging, underneath the codex, and above the hotbar gui.

![711980_20200630183455_1](https://user-images.githubusercontent.com/33239800/86104163-04e99600-bb01-11ea-9dad-11b76f07aaa5.png)

### Steps to reproduce the issue:

Drag item from codex, it will be invisible until it reaches the hotbar.

### Environment
- Starship EVO version: 20w27a
- Graphics Card: 2080 Super OC

**Comment by Sullos** [comment]
Sorry, I just saw that this also affects the text of spawning a blueprint in. See below. This makes it near impossible to see what is being spawned in with the newer image based interface, if the blueprints have no image at the time.
![711980_20200630184346_1](https://user-images.githubusercontent.com/33239800/86104680-b5579a00-bb01-11ea-8b94-d7658dff4e44.png)

**Comment by Sullos** [comment]
Alrighty I figured it out!
Simply, if I disable UI post effects, the main issues are fixed, with only a new minor bug appearing.
![711980_20200630195107_1](https://user-images.githubusercontent.com/33239800/86112307-2485bc00-bb0b-11ea-98b7-b2979f51c0ca.png)
As you can see, depending on the length of the name of the blueprint, the grey background box for the text doesn't expand to meet the length of the text. It might be that you just haven't added this feature yet, but it would be a nice little 'clean' feature.

Both bugs, the one dragging an item over the codex, and the bug with the text which I found also mentioned here: https://github.com/tsunamayo/Starship-EVO/issues/2553
Servomotor mentions: "the mouseover tooltip is behind the grid/icon interface." 
this is fixed too, by disabling the UI post effects.

Hope this helps! 
Thanks

**Comment by tsunamayo** [comment]
Yes the combo large screen + UI post effect proved impossible to work with, I will have to remove it entirely, again some work thrown out of the window for nothing...
Thanks

**Comment by tsunamayo** [comment]
okay I will do one last try, you will tell me how it is on upcoming build!

**Comment by tsunamayo** [comment]
@Sullos okay tell me how it is, for the character save selection, the tooltip and the workshop interface. Thanks!

**Comment by Sullos** [comment]
It all appears to work fine! Nice work, looks like it is fixed!
Last thing to fix/change would be to have the grey text box extend to encompass the text of the name of a blueprint. Currently, the text will extend out of the grey background, and it looks a bit silly, and in some cases can be harder to read.
![711980_20200701182836_1](https://user-images.githubusercontent.com/33239800/86221821-bd2e4180-bbc8-11ea-89bc-3893f4d19839.png)
As you can see, the "Hall T" part of the blueprint name goes out of the grey background box. I recommend either doing some text wrapping, so the text goes to a new line if it reaches the edge of grey box, or to have the grey box extend.

Thanks!

**Comment by tsunamayo** [comment]
Yes this is till wip... Thanks!
