### ISSUE TITLE
[BUG] Ship to ship Landing Pad needs (too much?) Resistance/Weight

### ISSUE THREAD

**Issue by Tocks13** [tsunamayo/Starship-EVO#2580]
### Short Description of the issue:

If a ship tries to dock at a Landing Pad of another ship, which is too light, it won't register the landing and keeps pushing the Landing Pad downwards. 

### Steps to reproduce the issue:

1. Build two ships, which are very light, one with a landing Pad. 
   Test Example:
![20200630174317_1](https://user-images.githubusercontent.com/67311622/86147087-3f4f3500-baf9-11ea-8f39-29a5d19f4bfa.jpg)

![20200630174429_1](https://user-images.githubusercontent.com/67311622/86147225-6c9be300-baf9-11ea-95b1-61cbc856ca29.jpg)

2. Setting the Shipyard to landingpad
3. Try to Dock

The docking ship will correctly try to dock, but when it reaches the Landing Platform, it will not register and instead keeps pushing the landingplatform downwards.

### Environment
- Starship EVO version: 20w27a

### Additional information:
If the landingplatform offers enough resistance, for example it is heavy enough or lies on the ground, the ship will dock correctly.

My tests so far:
The ships from above can't dock, but putting 16x16x16 Blocks underneath the landingpad, gives it enough resistance/weight, to allow Docking.
A ship consisting of only 16x16x1 blocks and minimum required System for flight and Shipyard, is also too light to allow docking.
The bricks on the bottom of the docking ship are not the reason, as it shows the same behaviour with a block on the bottom.

**Comment by tsunamayo** [comment]
Thanks for the detailed test case, issue fixed for for 20w27c.  Cheers
