### ISSUE TITLE
[BUG] Player freezes when accessing ship

### ISSUE THREAD

**Issue by FlyingDebris** [tsunamayo/Starship-EVO#2585]
### Short Description of the issue:
While attempting to use the yoke on one of the starter ships, I lost any ability to control my character or the ship.. Reloading does not fix the problem. The only thing I am able to do is toggle the landing gear with G, and to press ESC to open the menu.

### Steps to reproduce the issue:

Unsure of the exact method, but I believe I may have let go of pressing F a bit too early. Along with this, I was holding the link tool, and I believe I may have been looking at a logic component involving the landing gear instead of the yoke by mistake.

### Environment
- Starship EVO version: 20w27a
- Graphics Card:  GTX 1050

### Additional information:

![image](https://user-images.githubusercontent.com/38392651/86193521-18edc180-bb1a-11ea-92bc-3e2590485a75.png)
Screenshot of my view after freezing

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4855153/output_log.txt)

**Comment by tsunamayo** [comment]
Thanks for the detailed test case! It was in single player? Thanks

**Comment by FlyingDebris** [comment]
It was, yes,

**Comment by tsunamayo** [comment]
I cant really reproduce this, was it the base ship unmodified? Thanks

**Comment by FlyingDebris** [comment]
It was unmodified, the only other thing I can think of is that I may have tried to use the yoke as my player's view was still moving to the chair?

**Comment by tsunamayo** [comment]
@FlyingDebris was it docked or something? Did you played with docking or shipyard a bit before that? Sorry I sound like a police officer or something lol

**Comment by tsunamayo** [comment]
Okay I think the issue should be fixed - there was a similar issue with the same log posted. Fix for 20w27c. Thanks!
