### ISSUE TITLE
[SUGGESTION] Ship Build Orientation

### ISSUE THREAD

**Issue by Brushes2** [tsunamayo/Starship-EVO#2586]
It seems the ship yoke doesn't actually change the build orientation of the ship, but rather linking it to a ship computer does. Not sure if intended but consider updating the last part of tutorial to reflect that?

- Starship EVO version: 20w27a

**Comment by tsunamayo** [comment]
Hum it says you have to link it to yoke, so I think we are good!
It make sense you can build many yoke, so the computer have to pick one...
