### ISSUE TITLE
[SUGGESTION] GPU usage in SLI

### ISSUE THREAD

**Issue by Brushes2** [tsunamayo/Starship-EVO#2587]
I've noticed that second GPU inst utilized much in SLI. Not sure if that's a game issue or Nvidia issue as SLI seems fussy as to what it does and when. Memory usage is even but that's it. 

### Environment
- Starship EVO version: 20w27a
- Graphics Card: MSI GTX 980 2xSLI

### Additional information:
![Capture](https://user-images.githubusercontent.com/67161654/86197709-f6f93c80-bb23-11ea-984d-3966b1aaadf4.JPG)

**Comment by tsunamayo** [comment]
Hum sorry I dont think I cant do anything about it, I guess it is up to unity / nvidia, plus I cant reproduce that as I dont have the hardware, plus as a very tiny % of people uses SLI it would be a time not well spent... Sorry mate!
