### ISSUE TITLE
My thoughts on the whole Copy/Paste Lag thing

### ISSUE THREAD

**Issue by ultrak2k** [tsunamayo/Starship-EVO#2589]
I've seen many people be in favour of copy paste, and only a few argue against it in temporary - and honestly, I'd love it to be in the game not because I'd use it (besides turret paste), but because there can be one less complaint vector on the discord

So here are my thoughts on the idea that copy paste will cause lag

- If they’re the type of person to go super detail they’re probably the type of person who has the patience to make loads of super detailed hallways anyway - just because they'd be more frustrated, doesn't mean that they will stop doing what they do. And not everyone would go big complexity - if lag was an issue, copy paste or not, competitive ro mindful players for example would want to minimize lag - they wouldn't be the type to make super complex lag hallways or whatever

- If your the type of person to make lag bombs, you can spawn one in, you don’t need to make a a lag bomb every single time, meaning they can spend any amount of time on one anyway, and I mean they’d probably find more efficient ways to lag things then copy paste anyway

- For single player players, I don’t think lag constructs matter - It’s their problem, and single player players wouldn't be building super complex constructs for themselves - people who do like to display them, so its mainly creative builders who build them in single player for the sake of building.

Many in the community consider it a major oversight in an otherwise great builder, and much more believe the benefits far outweigh the downsides - other games do copypaste too, and its not a major cause of lag more then lag machines, or people building unique and complex - mind you, not every complicated superdetailed object can be copypasted.

I do understand, however, that if there's more important things to focus on, like gameplay, sure. But many believe QOL and fixes to the flight system should come before gameplay - otherwise, getting to the gameplay might be frustrating

**Comment by tsunamayo** [comment]
Other game have a very different building system. The amount of detail you can but in the game is really massive, people already complain that large build lag... I wont shoot myself a bullet in the foot doing that.
I hear your request but sorry it is not reasonable for now, but maybe after my planned set of optimization it would be more realistical.
Thanks
