### ISSUE TITLE
[Bug] Graphical issue with new piston mechanism and large piston not extending

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Starship-EVO#2592]
### Short Description of the issue:

As you can see in the picture below, there is a missing piece of the piston brick.
![711980_20200701183207_1](https://user-images.githubusercontent.com/33239800/86222288-607f5680-bbc9-11ea-9010-7390f1175218.png)
![711980_20200701183231_1](https://user-images.githubusercontent.com/33239800/86222302-637a4700-bbc9-11ea-9381-eaffac6afb33.png)

Extending the small piston, it will only extend/stretch on one axis for some reason, even after pressing Q to rotate the axis. When you place it, there is another graphical glitch.
![711980_20200701183729_1](https://user-images.githubusercontent.com/33239800/86222849-21053a00-bbca-11ea-904f-78717b7e8c5a.png)

Furthermore, the large piston block doesn't seem to extend at all. I tried various lengths, but nothing happened. 
![711980_20200701183456_1](https://user-images.githubusercontent.com/33239800/86222995-5447c900-bbca-11ea-8d16-d713bd214535.png)

### Steps to reproduce the issue:

Use switch on large piston, it doesnt extend.
Observe graphical problems on small piston brick, and inability to stretch it on more than one axis.

### Environment
- Starship EVO version: 20w27b
- Graphics Card: 2080 Super OC

If you need more help with these issues, let me know!

**Comment by AfterRebelion** [comment]
I don't have this issue with an AMD RX 580:
![imagen](https://user-images.githubusercontent.com/559819/86236166-e97e9980-bb99-11ea-8b07-20a6d1911e08.png)

Might be related to nVidia RTX

On the extending side, it seems like the wrong axis was configured:

![imagen](https://user-images.githubusercontent.com/559819/86236463-66aa0e80-bb9a-11ea-92f2-7a447d8350ac.png)
![imagen](https://user-images.githubusercontent.com/559819/86236523-85a8a080-bb9a-11ea-9083-dae481f857c8.png)

**Comment by ProPeach** [comment]
![image](https://user-images.githubusercontent.com/27857711/86262768-36716880-bbb8-11ea-9276-45e99fc46bd0.png)
It seems like the piston head spawns inside the piston base on the large variant, which prevents it from extending. The small piston seems fine, apart from the missing part of the shaft. Glad to see these introduced!
I'm also running with an RX 580, but experience the same issue as Sullos with 1m wide large piston

**Comment by tsunamayo** [comment]
All issues fixed for 20w27c. Thanks!
