### ISSUE TITLE
[SUGGESTION] Steam in-home streaming is not enabled on Starship Evo.

### ISSUE THREAD

**Issue by StarrKiss** [tsunamayo/Starship-EVO#2598]
### Short Description of the issue:
Recently, I have re-painted my room, and so I cannot access my PC. To play my games, I use a feature called 'Steam in-home streaming' which allows you to run a game on a desktop PC and play it on a laptop through streaming. However, this feature must be enabled in Steam by the developer (Based on what I have read). Starship Evo lacks this feature.
### Steps to reproduce the issue:

1. Have SEVO installed on a Desktop
2. Go on to a laptop or phone or steam link and view Starship Evo.

### Environment
- Starship EVO version: Auto-Latest
- Graphics Card: GTX 1070 TI

### Additional information:
https://i.imgur.com/cay5dHY.jpg
This is what Space Engineers, a supported game, looks like in library.
https://i.imgur.com/tcxjwjN.jpg
This is what SEVO, a game with Steam in-Home streaming disabled, looks like in library,

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Is it is the same as Steam Remote Play? Is Steam in-home streaming the exact name of the feature? I cant find it anywhere... Thanks

**Comment by StarrKiss** [comment]
> Is it is the same as Steam Remote Play? Is Steam in-home streaming the exact name of the feature? I cant find it anywhere... Thanks

Yes, it is the same as remote play! Thanks!

**Comment by tsunamayo** [comment]
Okay it is not clear how to implement this, I will do further research but it seems oriented toward mobile devices. If thats the case I wont be able to implement it as I dont have the bandwith to work on this... Thanks

**Comment by StarrKiss** [comment]
> Okay it is not clear how to implement this, I will do further research but it seems oriented toward mobile devices. If thats the case I wont be able to implement it as I dont have the bandwith to work on this... Thanks

It is not meant for mobile devices, at least I don't think so- It's for playing using your desktop on another device like Steam Link or game console, though it can be used for mobile streaming if wanted.

**Comment by tsunamayo** [comment]
From the steam dev portal all I see is mobile / controllers options, not sure if I can activate it only for streaming on a PC...

**Comment by StarrKiss** [comment]
> From the steam dev portal all I see is mobile / controllers options, not sure if I can activate it only for streaming on a PC...

Hello, I was able to determine it was a problem with my network, not the game- sorry for wasting your time lol
