### ISSUE TITLE
[Crash] Crash to desktop when loading world

### ISSUE THREAD

**Issue by Lsutehall** [tsunamayo/Starship-EVO#2600]
### Short Description of the issue:

I tried to load in a world last save a week ago (a 20w26 build, not sure which), and got a crash to desktop. It seems to have crashed the steam client as well!

### Steps to reproduce the issue:

Don't know - load a save from a previous version?

### Environment
- Starship EVO version: 20w27b
- Graphics Card: GTX1060

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4860397/output_log.txt)

**Comment by Lsutehall** [comment]
Reproduced straight away.

Character folder attached.
[Lester 3.zip](https://github.com/tsunamayo/Starship-EVO/files/4860415/Lester.3.zip)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4860417/output_log.txt)

**Comment by tsunamayo** [comment]
@Lsutehall I can load your save just fine. You got an out of memory issues, what is your system memory? Do you have other program running at the same time, like chrome? If you could send me a screenshot of the task manager so we can have a look at the memory usage.
Could you try rebooting your computer and launching the game?
Thanks

**Comment by Lsutehall** [comment]
System memory is 8GB and I've been running the game successfully for over a year.

There wasn't anything running at the same time that hasn't been running in the background before, certainly not anything taking up loads of RAM.

I'm happy to report that a reboot fixed it - not sure what was different though. 

Sorry if this has been a waste of time - I saw it CTD and wanted to report right away!

Ok to close?

**Comment by tsunamayo** [comment]
Yes I think that was a memory issue, not sure if it was related to the game or anything else with windows... Cheers
