### ISSUE TITLE
[Suggestion] Preview for Shipyard

### ISSUE THREAD

**Issue by RedVanGhoul** [tsunamayo/Starship-EVO#2603]
This may be in the works already, in which case just disregard. 
Is it possible to get a preview of affected area for shipyards in much the same way gravity generators do?  I've been getting around it by simply layering a gravity generator on top temporarily and then removing it when I'm done, but having a preview native to the shipyard would be much better, especially since gravity generators only extend out 16 blocks.

**Comment by tsunamayo** [comment]
just use the link tool to select the shipyard block. I will add an option inside the UI to show the bound. Thanks

**Comment by RedVanGhoul** [comment]
Thank you kindly
