### ISSUE TITLE
[Bug] FPS info doesn't work

### ISSUE THREAD

**Issue by Womble-TC** [tsunamayo/Starship-EVO#2604]
### Short Description of the issue:

The FPS info option doesn't work

### Steps to reproduce the issue:
- Press F3 to show fps info
- Observe how the fps info doesn't appear 

### Environment
- Starship EVO version:  20w27b
- Graphics Card: gtx 970

### Additional information:
![image](https://user-images.githubusercontent.com/29961381/86303110-b7555200-bc02-11ea-838e-6c64fb4c2d3a.png)

**Comment by Tezlz** [comment]
You can see it if you disable Post UI Effects

**Comment by tsunamayo** [comment]
@Womble-TC what is your screen resolution? Thanks

**Comment by Womble-TC** [comment]
1920x1080 @tsunamayo

**Comment by Kaiser-Indrasil** [comment]
Confirmed, it happens to me, too.
My resolution: 3440x1440
UI Post Processing: ON
I think it happened after resolving #2555

**Comment by tsunamayo** [comment]
Issue fixed for 20w27c. Thanks!
