### ISSUE TITLE
[BUG] Ships Freeze When Trying to Undock From Landing Pad

### ISSUE THREAD

**Issue by Kadzar** [tsunamayo/Starship-EVO#2606]
### Short Description of the issue:

Every time I try to fly a docked ship, the ship won't move and I can't exit it, and I have to restart to undock.

### Steps to reproduce the issue:

Dock a ship, exit ship controls, reenter ship controls, ship freezes up.

### Environment
- Starship EVO version: 20w27b
- Graphics Card: NVIDIA GeForce GTX 1080

### Additional information:

![20200701235502_1](https://user-images.githubusercontent.com/66035211/86318788-8b34d380-bbf8-11ea-9536-e98dfec08ffa.jpg)

Output log (got a big one again) []https://drive.google.com/file/d/1stC12Ov2kSjxGPv0mWQgrlOrWqKWXLyR/view?usp=sharing

**Comment by tsunamayo** [comment]
Works fine for me, can you send me your character save? Thanks

**Comment by tsunamayo** [comment]
Okay I was able to reproduce, issue fixed for 20w27c. Thanks
