### ISSUE TITLE
Player controls and mouse view freeze up after entering ship controls

### ISSUE THREAD

**Issue by CurioInventorium** [tsunamayo/Starship-EVO#2608]
### Short Description of the issue:
After sitting in a chair on a spaceship and then accessing the control yoke, the movement controls freeze up and view in no longer controlled by mouse movement.
Some keyboard controls work, like F2 and Esc to bring up the menu.
Quitting out and reentering the world doesn't fix the issue.
...

### Steps to reproduce the issue:
I've been hesitant to raise an issue at first as I wasn't sure how to explain what happened. But after starting a new character/world I've realised what steps may recreate the issue.
I spawned in two AI Aggressive ships, one after the other. They both had time to fly away before spawning the next.
I then spawned the same ship, but with AI set to none. I got into it a flew it to a shipyard zone and auto-docked.
After exiting the ship and messing around for a bit building things, I sat back in and tried to access the control yoke.
At this point the issue occured.

This series of events happened in both worlds I've created so far and I'll try it all again in a third one after I've had some dinner.

Looking in the output.txt there's a load of NullReferenceException's in there.
...

### Environment
- Starship EVO version:
20w27b
- Graphics Card: 
NVIDIA Geforce RTX 2060

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4865650/output_log.txt)

**Comment by Tezlz** [comment]
Seems to be the same problem as #2585 which should be fixed for 20w27c

**Comment by CurioInventorium** [comment]
Ah, I thought I might have seen it somewhere. Guess I should have read past page 1 of raised issues :/
Not sure whether to leave this open or not, as it is at least another output.txt file to help diagnose with.

**Comment by Tezlz** [comment]
You should keep it open, doesn't really hurt to have another report of it. It might even not get fixed at all and then he'll already have a report ready for it with another output log. And if not he can just close this himself if he feels it is unnecessary.

**Comment by FlyingDebris** [comment]
This is exactly what happened to me, yeah. I didn't have any of the AI ships, however. Good catch! I wasn't sure what caused it.

**Comment by tsunamayo** [comment]
Issue should be fixed soon in 20w27c. No problem if there is a double bug, I like to see what kind of bug players gets a lot, help with setting the right urgency. Cheers
