### ISSUE TITLE
[Bug] Pistons Ignore Set Length on start of gaming session

### ISSUE THREAD

**Issue by Xenoprophet-Nail** [tsunamayo/Starship-EVO#2611]
### Short Description of the issue:
Pistons ignore length settings on start of game
...

### Steps to reproduce the issue:
set a piston at 0.1 exit to desktop and reload
...

### Environment
- Starship EVO version: 2w27b
- Graphics Card: Nvidia GeForce GTX 1060 6gb ram

### Additional information:
this is how far the pistons should extend: https://imgur.com/a/6g0rtUV

This is what I see at the start of a play session: 
![20200702221901_1](https://user-images.githubusercontent.com/51257864/86427659-c0085f80-bcb8-11ea-8dde-2d4a4142d769.jpg)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Ho whoa that's so _sexy_ 
I keep you posted.

**Comment by tsunamayo** [comment]
Okay issues fixed for 20w27c. I am uploading the build soon, cheers
