### ISSUE TITLE
You cannot build Pistons Upside Down

### ISSUE THREAD

**Issue by gonzo6969** [tsunamayo/Starship-EVO#2613]
### Short Description of the issue:
You cannot build pistons Upside Down or another direction. It works only if you place the piston on top.  
### Steps to reproduce the issue

...

### Environment
- Starship EVO version: 20W27B
- Graphics Card: GEFORCE GTX 970
![piston-bug](https://user-images.githubusercontent.com/58293977/86440447-c0c9e180-bd0a-11ea-8ca5-162bcb7175a9.jpg)

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Hi, fixed for 20w27c. Thanks!
