### ISSUE TITLE
[BUG] Crashes when attempting to re-enter ship after docking

### ISSUE THREAD

**Issue by T00Code34215** [tsunamayo/Starship-EVO#2615]
### Short Description of the issue:
Created a simple landing pad, which worked successfully for landing. After leaving ship briefly, i returned inside, and grabbed yoke. At this point the game froze, and all you could do was open exit menu. After returning to homescreen, game became very laggy. Upon entering world again, your character was uncontrollable.
...

### Steps to reproduce the issue:
Create/use landing pad
Land there and leave ship
Return after a few minutes
Enter seat and yoke.
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4869088/output_log.txt)

...

### Environment
- Starship EVO version: 20W27B
- Graphics Card: Geforce GTX 1070

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Fixed for 20w27c. Thanks!
