### ISSUE TITLE
[Bug] Hover pod heat and power consumption don't scale with strength

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#2618]
### Short Description of the issue:
When you reduce the Hover pod strength through either the Hover core on an individual pod, the power requirement and heat production of that pod does not reduce

### Steps to reproduce the issue:
Adjust the strength of a Hover Pod and watch the heat percentage on the GUI

### Environment
- Starship EVO version: 20w27c
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
Good catch! Fixed for 20w28a. Thanks
