### ISSUE TITLE
[BUG] Box around cursor obscures UI elements in background when flying ship

### ISSUE THREAD

**Issue by StarrKiss** [tsunamayo/Starship-EVO#2623]
### Short Description of the issue:
When in 3rd person, flying a ship, the ship has a black box around it that obscures UI elements, but NOT scenery/environments.
EDIT- this also occurs in first person, but in either case, not in TAB/free-look mode
EDIT2- After testing, it happened in the two stock ships, and after looking more closely, it is less of a bounding box and more of a square around the cursor
...

### Steps to reproduce the issue:
Fly around in a ship, the one I am using is- https://steamcommunity.com/sharedfiles/filedetails/?id=2152764891  
Look at a UI element
...

### Environment
- Starship EVO version: 20w27d
- Graphics Card: Nvidia GeForce GTX 1070 ti

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

![issue](https://user-images.githubusercontent.com/13007697/86514107-25666880-bdff-11ea-854f-92b3129d53b2.png)

![image](https://user-images.githubusercontent.com/13007697/86514250-a83bf300-be00-11ea-92e1-6af09180136a.png)

**Comment by StarrKiss** [comment]
THIS ALSO OCCURS IN FIRST-PERSON
![image](https://user-images.githubusercontent.com/13007697/86514156-a58cce00-bdff-11ea-94aa-7eb11b7a2fd5.png)

**Comment by Kadzar** [comment]
I've found the same thing ![20200704105650_1](https://user-images.githubusercontent.com/66035211/86516494-a36a4580-bde6-11ea-9491-acb979cee3dc.jpg)
I assume it's some sort of transparency issue or something around the new deadzone reticule, since it's actually that that cuts off the ui, not the cursor itself.

**Comment by TIKIRobo** [comment]
I have the same bug on my ships aswell 
![image](https://user-images.githubusercontent.com/56371294/86522437-7af84080-be12-11ea-9a23-17fd764e878b.png)

**Comment by tsunamayo** [comment]
Thanks all, fixed for 20w28a. Cheers
