### ISSUE TITLE
[Bug] Putting away link tool while highlighting a block does not un-highlight the block

### ISSUE THREAD

**Issue by FlyingDebris** [tsunamayo/Starship-EVO#2624]
### Short Description of the issue:

When using a link tool and swapping to some other hotbar slot, the block currently highlighted will remain highlighted until the link tool is brought back out.

### Steps to reproduce the issue:

Place linkable block
Point link tool at it
Change hotbar slot, not looking away

### Environment
- Starship EVO version: 20w27d
- Graphics Card: GTX 1050

### Additional information:

![image](https://user-images.githubusercontent.com/38392651/86517477-34491d00-bdf7-11ea-87c0-2cb9ae478110.png)

**Comment by tsunamayo** [comment]
Fixed for 20w28a. Thanks!
