### ISSUE TITLE
Crash at Main Menu

### ISSUE THREAD

**Issue by Hurriccoo** [tsunamayo/Starship-EVO#2627]
### Short Description of the issue:

I am unable to start the game. The entire computer crashes (powers off and reboots with no blue screen) when selecting any option from the main menu. I just bought the game on Steam, so I don't know if this issue existed in previous versions or not.
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4873898/output_log.txt)

### Steps to reproduce the issue:

Start the game with my configuration and click Options.

### Environment:
- Starship EVO version: 20w27d
- Graphics Card: GTX 1080
- Windows 10 Home 64-bit (10.0, Build 18362) 
- 24576 MB RAM
- Intel Core i7-3770 processor 3.40 GHz

### Additional information:

See attached: [output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4873898/output_log.txt)

**Comment by tsunamayo** [comment]
Your computer is good enhough, could you make sure your driver are up to date? Thanks

**Comment by Hurriccoo** [comment]
I just updated my drivers (including the GTX 1080) and the crash still persists. I have hundreds of games in my steam library and this is the only game I've ever experienced a crash like this with. I have attached more output_logs in case these help. The crash usually occurs within a second after clicking Play, Join Server, or Options. Clicking Exit or any of the buttons on the bottom right does not cause a crash.

[output_log_Crash_1.txt](https://github.com/tsunamayo/Starship-EVO/files/4876224/output_log_Crash_1.txt)
[output_log_Crash_2.txt](https://github.com/tsunamayo/Starship-EVO/files/4876221/output_log_Crash_2.txt)
[output_log_Crash_3.txt](https://github.com/tsunamayo/Starship-EVO/files/4876222/output_log_Crash_3.txt)
[output_log_No_Crash.txt](https://github.com/tsunamayo/Starship-EVO/files/4876223/output_log_No_Crash.txt)

**Comment by tsunamayo** [comment]
What is your monitor resolution and setup? Thanks

**Comment by Hurriccoo** [comment]
I tried running 3 different configurations and the crash occurred in all cases:

1. 1680x1050 @ 60 Hz LG DVI monitor 
2. Same monitor forced to 1920x1080 with Nvidia Control Panel
3. Fueran 4K HDMI Display Emulator 4096x2160 @60Hz

**Comment by tsunamayo** [comment]
Okay I guess I am gonna have to kill that UI Post effect.

**Comment by tsunamayo** [comment]
@Hurriccoo could you confirm that the game works fine once you load it with UI Post Effect OFF? With all the other effects at ON.
Thanks

**Comment by Hurriccoo** [comment]
Yes, I just tried with all other effects ON (True). The game works fine now. I was able to play through the tutorial, drive the hovercraft, shoot the laser, and fly to a space station without any problems. I only needed UI Post Effects=False

**Comment by tsunamayo** [comment]
Okay good, I will be unplugging this option from 20w28a so this issue will no happens. Cheers
