### ISSUE TITLE
[Bug] When placing small piston, half of vehicle loses physics

### ISSUE THREAD

**Issue by FlyingDebris** [tsunamayo/Starship-EVO#2630]
### Short Description of the issue:

I went to place a piston on a vehicle, and the front half sank into the ground.

### Steps to reproduce the issue:

Build hovercraft, place a small piston anywhere on it. This seems to work with all hovercraft.

### Environment
- Starship EVO version: 20w27d
- Graphics Card: GTX 1050

### Additional information:

![image](https://user-images.githubusercontent.com/38392651/86525004-52426c00-be4f-11ea-9a2a-01ee0043f07e.png)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4874383/output_log.txt)

**Comment by tsunamayo** [comment]
@FlyingDebris Issue fixed on recent update. Thanks a lot!
