### ISSUE TITLE
[Bug] Some lights are on on the world's load

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#2631]
![Starship_EVO_Io6wbbC5W8](https://user-images.githubusercontent.com/63756057/86527444-a9b7fa80-be96-11ea-8153-4aa2f9182f4c.jpg)

Everytime I load up the world, the same lights are turned on despite that I always have all of them turned off before I quit the game - they just load up turned on anyway. I was looking for some consistency in their behaviour but I can't find one - some of them are even dimmed down, others are at full brightness, and all can be affected - the ones on the main grid or any child entity. Very peculiar.

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil send me some bp to investigate! Thanks

**Comment by Kaiser-Indrasil** [comment]
Sure, here you go:
[Blueprint.zip](https://github.com/tsunamayo/Starship-EVO/files/4875912/Blueprint.zip)

**Comment by tsunamayo** [comment]
Issue fixed for 20w28a. Very nice ship! Cheers
