### ISSUE TITLE
Strange square on HUD

### ISSUE THREAD

**Issue by AlienXtream** [tsunamayo/Starship-EVO#2634]
### Short Description of the issue:

there appears to be a weird transparent square stuck to my cursor/hud

### Steps to reproduce the issue:

(courtesy of user "ultra[******* weeb]")
pilot ship then enter "build mode"
### Environment
- Starship EVO version: 20w27d
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![image](https://user-images.githubusercontent.com/12606809/86544316-42b74600-bf69-11ea-8042-efb8b0dcc3f8.png)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
This should be fixed for 20w28a. Thanks

**Comment by AlienXtream** [comment]
that was fast... seriously, are you like an android or something tsuna?! XD
