### ISSUE TITLE
[Bug] Rendering / Shader - Dark paints appear pitch black when underlit

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#2636]
Pretty much self-explanatory. Affects multiple dark colours, even including Steel. They look as before when lit properly but when in shade, they appear way darker than they should.
![image](https://user-images.githubusercontent.com/63756057/86560377-0b8b6980-bf56-11ea-92d1-260877bbc7d9.png)

**Comment by tsunamayo** [comment]
Okay it seems that the environment map doesnt apply anymore, I keep you posted.

**Comment by tsunamayo** [comment]
Fixed for 20w28e. Thanks!
