### ISSUE TITLE
Laser sensor only triggers at 2 meters when mounted on a weapon

### ISSUE THREAD

**Issue by CurioInventorium** [tsunamayo/Starship-EVO#2638]
### Short Description of the issue:
Minor issue: I built a weapon with a Laser sensor to allow Item-stand traps and the sensor only seems to trigger at 2 meters.
When this same combination is fitted to a building the laser sensor works as intended (Tested with a value of 50) 
...

### Steps to reproduce the issue:
Create a weapon with a laser sensor that is linked to a laser module. The sensor only seems to trigger when the player is at 2 meters in range.
...

### Environment
- Starship EVO version: 20w28a
- Graphics Card: NVidia Geforce RTX 2060

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
YouTube video where I'm showing off weapons at the correct timestamp:
https://youtu.be/cBB1gtsNXX4?t=919

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
@CurioInventorium Hi, this should be fixed in 22w45a. Thanks
