### ISSUE TITLE
[Bug] Light's glow but don't produce light

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Starship-EVO#2639]
### Short Description of the issue:
Just started a new world and noticed that the lights don't seem to work.
![image](https://user-images.githubusercontent.com/43644633/86605490-af006c80-bf9e-11ea-93bc-a57cc2d10938.png)

Interestingly when you place a new light it seems to trigger an update which turns them all back on.

### Steps to reproduce the issue:
create a new world and look at the tutorial area.

Then place a new light.

### Environment
- Starship EVO version: 20W28a
- Graphics Card: Gtx 1060

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by zorozeenee** [comment]
Yep having this too, terrible bug

**Comment by tsunamayo** [comment]
Okay thats a pretty big bug, for newcomer that is terrible...

**Comment by tsunamayo** [comment]
Fixed for 20w28b, I am upping the build now. Cheers
