### ISSUE TITLE
Chunks derender at distance including flying the ship

### ISSUE THREAD

**Issue by BrickMacklin** [tsunamayo/Starship-EVO#2640]
Move far enough a way and chunks derender until they disappear entirely. Even in third person ship flying you cannot see the full vessel. Used to be able to see a ship from far away. Now all details are missing. Lights don't appear until you get close and they are very dim. Below is a video of the issue.
...

### Environment
- Starship EVO version: 20w28a
- Graphics Card: 2080 Ti

### Additional information:

https://youtu.be/P-jjhfzFqQQ

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by Kaiser-Indrasil** [comment]
Yeah, happens to me, too. Seems like the issue's with the new culling features.

**Comment by BrickMacklin** [comment]
Turning off culling mostly fixes it

**Comment by tsunamayo** [comment]
What is you guys resolution? Thanks

**Comment by ExodistSKY1** [comment]
my resolution is:  1920x1080 @144htz

![20200706175740_1](https://user-images.githubusercontent.com/45324484/86662619-7f5b5f80-bfb2-11ea-8cf0-bf87187d5f41.jpg)
![20200706175742_1](https://user-images.githubusercontent.com/45324484/86662630-81252300-bfb2-11ea-96c9-476ffeb4b61c.jpg)
![20200706175744_1](https://user-images.githubusercontent.com/45324484/86662640-82eee680-bfb2-11ea-9fb5-f2ad2add754d.jpg)
![20200706175749_1](https://user-images.githubusercontent.com/45324484/86662647-84201380-bfb2-11ea-850b-f3fb26795603.jpg)



There is also something similar with in some instances some chunks become invisible when close to the ship.

![20200706163608_1](https://user-images.githubusercontent.com/45324484/86662749-a154e200-bfb2-11ea-9974-d0cdce8a9772.jpg)
![20200706163610_1](https://user-images.githubusercontent.com/45324484/86662757-a31ea580-bfb2-11ea-950b-d8d2a79a90e6.jpg)
![20200706163611_1](https://user-images.githubusercontent.com/45324484/86662764-a44fd280-bfb2-11ea-8c2b-b436f5e20a8c.jpg)
![20200706163613_1](https://user-images.githubusercontent.com/45324484/86662768-a580ff80-bfb2-11ea-92c3-7ce156460b94.jpg)

**Comment by BrickMacklin** [comment]
My resolution is 2560x1440p @144hz.

**Comment by tsunamayo** [comment]
The one close to the ship is more serious, do you get that often? Thanks

**Comment by ExodistSKY1** [comment]
Ship completely disappears at about 6290m away... in the old system it would disappear at around 50k

I would really like for us to continue to see ships at that distance.

The up close one happens more so near angled blocks, but i am still trying to figure out a cause. 

Here are the distances and visibility:


![20200706195654_1](https://user-images.githubusercontent.com/45324484/86679296-1203fa80-bfc3-11ea-93a2-b7d32eea305e.jpg)

![20200706195346_1](https://user-images.githubusercontent.com/45324484/86679323-17f9db80-bfc3-11ea-90cd-b961ff715673.jpg)

![20200706195401_1](https://user-images.githubusercontent.com/45324484/86679336-19c39f00-bfc3-11ea-9534-425b738ac313.jpg)

![20200706195418_1](https://user-images.githubusercontent.com/45324484/86679349-1af4cc00-bfc3-11ea-9ed9-baa504226422.jpg)

![20200706195429_1](https://user-images.githubusercontent.com/45324484/86679357-1c25f900-bfc3-11ea-9c74-1febe9a70eb3.jpg)

**Comment by StarrKiss** [comment]
I am getting this too at 1920x1080 60hz

**Comment by ExodistSKY1** [comment]
I went through some of my ships and tested: 

I took 3 screenshots per: Close, right before the bug and after the bug
Close is to show the blocks/bricks 

on some instances just moving left or right at the same distance from the ship makes this bug appear 

Close:
![20200707162027_1](https://user-images.githubusercontent.com/45324484/86850258-a1b6b100-c076-11ea-92f6-db10256835ea.jpg)
Distance:
![20200707162005_1](https://user-images.githubusercontent.com/45324484/86850221-91063b00-c076-11ea-9735-b83aa66bb418.jpg)
![20200707162009_1](https://user-images.githubusercontent.com/45324484/86850224-92376800-c076-11ea-9255-aa50e3362774.jpg)
![20200707162013_1](https://user-images.githubusercontent.com/45324484/86850238-995e7600-c076-11ea-9406-f317dec38c89.jpg)

Close: 23m ship
![20200707162857_1](https://user-images.githubusercontent.com/45324484/86850337-beeb7f80-c076-11ea-8260-6c2da00602c4.jpg)

![20200707162852_1](https://user-images.githubusercontent.com/45324484/86850365-c90d7e00-c076-11ea-83e7-b43c4d6478cb.jpg)
Bug
![20200707162901_1](https://user-images.githubusercontent.com/45324484/86850399-d591d680-c076-11ea-8680-666fec278355.jpg)

Close: 162m ship
![20200707162247_1](https://user-images.githubusercontent.com/45324484/86850459-eb070080-c076-11ea-9918-bd523246196f.jpg)

![20200707162244_1](https://user-images.githubusercontent.com/45324484/86850471-f2c6a500-c076-11ea-8104-0c26ba1d97e6.jpg)
Bug
![20200707162242_1](https://user-images.githubusercontent.com/45324484/86850489-fa864980-c076-11ea-9fa3-b87ba40c77e6.jpg)

**Comment by tsunamayo** [comment]
Fixed for 20w28e. Thanks!
