### ISSUE TITLE
[Question] How to change steam preview

### ISSUE THREAD

**Issue by MRonlin** [tsunamayo/Starship-EVO#2641]
On the steam workshop I've been seeing some blueprints which have custom preview images, Im not sure if this was an added feature or not?, I've tried to add a custom preview image to my own blueprints through the workshop folder but It doesn't seem to be working.

**Comment by tsunamayo** [comment]
So you have to go to the folder indicated before uploading, and change manually the preview png image.

**Comment by MRonlin** [comment]
Many thanks, I've got it working now.

**Comment by tsunamayo** [comment]
Great!
