### ISSUE TITLE
[Bug] Glass tetra/seat funky collisions

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Starship-EVO#2646]
### Short Description of the issue:
The collision box for the glass tetra or the chairs seems to be a bit buggy. 

![image](https://user-images.githubusercontent.com/43644633/86830280-6a073380-c08d-11ea-951c-afa78ed652d0.png)
Here you can see that in the symmetrical room I was able to place the small chair but not the larger one, the tetra's making up the canopy are far enough away that the chairs should be fine.

![image](https://user-images.githubusercontent.com/43644633/86830421-9622b480-c08d-11ea-986c-559dde11f1e0.png)
Here you can see that raising the small chair by a half brick makes it unplaceable so it is safe to assume that the hitbox of the chair is only fitting by 1/2 a brick.

![image](https://user-images.githubusercontent.com/43644633/86830554-be121800-c08d-11ea-9b5b-d6b82973c9be.png)
Here I have removed the upside-down tetra being used as a hepta on this window and the seat is now placeable. That suggests that the issue is with the top face of the tetra. 

Interesting to note though is that if the seat is placed first then the tetra can be placed fine. This seems like an issue to me because something like this should be possible in either build order. Plus it could be very confusing to someone who is new to the game that the seat won't place.

### Environment
- Starship EVO version: 20w28b
- Graphics Card: GTX 1060

### Additional information:
Here is the blueprint of the ship I was using when I experienced these issues. 
[Blueprints.zip](https://github.com/tsunamayo/Starship-EVO/files/4886726/Blueprints.zip)

**Comment by tsunamayo** [comment]
I think I might just have fixed that bug for 22w04a...
