### ISSUE TITLE
Game freeze while entering lightcruise

### ISSUE THREAD

**Issue by hl2shadowslayer** [tsunamayo/Starship-EVO#2648]
### Short Description of the issue:

When I attempted to enter lightcruise manually, my ship and character froze. The ship was stuck in place, its speedometer always reading at 14km/s, and when I tried to leave my seat my character wouldn't be able to move, even though I was able to interact with objects and even get back into the seat again.

### Steps to reproduce the issue:

Fly around and try manually entering lightcruise a few times.

### Environment
- Starship EVO version: 20w28b
- Graphics Card: Geforce GTX 750ti

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4887717/output_log.txt)

**Comment by tsunamayo** [comment]
From what I can see from your log it was not your fault, but more an issue with AI behaviour. It will be fixed for 20w28d. Thanks!
