### ISSUE TITLE
[BUG] Little Blue Orbs (balls) in Planets Rings are seen through blocks.

### ISSUE THREAD

**Issue by Servomotor** [tsunamayo/Starship-EVO#2649]
### Short Description of the issue:
As title states. The blue floating orbs in the ice ring of the planet can be seen through blocks.
...

### Steps to reproduce the issue:
Fly construct to rings, turn off lights and notice you can see blue balls/orbs through blocks.
...

### Environment
- Starship EVO version: 20w28b
- Graphics Card: RTX 980

### Additional information:
https://www.youtube.com/watch?v=GRR4ABShEmk
_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by Brushes2** [comment]
Fix these space ghosts! [2557](https://github.com/tsunamayo/Starship-EVO/issues/2557)

**Comment by Servomotor** [comment]
Thanks for the link to your post Brushes. I read through some of the issues to see if this had been brought up, but I must have missed yours. 
I like your name for them, space ghosts, lol :)

**Comment by Brushes2** [comment]
It was [ZachZent](https://github.com/ZachZent) who named them. Yeah, it's fitting.

**Comment by tsunamayo** [comment]
Finally fixed for 20w46a. thanks
