### ISSUE TITLE
Can leave ship during warp

### ISSUE THREAD

**Issue by Talvieno** [tsunamayo/Starship-EVO#265]
In short, it shouldn't be possible to leave your ship during warp. Your ship disappears and the skybox "breaks" when this happens. After a time, it drops you out of warp into the next star system, but your ship is still nowhere to be seen. This essentially ends the game.

My suggestion would be: instead of permitting the player to get far enough away from the ship to "leave", simply not permit them to do so in the first place, likely by use of invisible barriers using the convex hull algorithm that seems to already be in place - the same one that seems to define artificial gravity and momentum. Simply turn that into a solid wall during warp. It's not like the player will need to be outside their ship during that time anyway.

**Comment by Hanfree85** [comment]
Maybe in the future in "survival mode" when you leave your ship you die

**Comment by Talvieno** [comment]
That could work, yes, but in creative mode, turning the "am I in the ship" bounding box into a collidable mesh seems to make the most sense.

**Comment by tsunamayo** [comment]
Your are all right: for creative I will put a box around the player, then for survival I will kill him ;-).

**Comment by tsunamayo** [comment]
No longer applicable. Thanks
