### ISSUE TITLE
[PETITION] Name the big blue gas giant "Bloopitur"

### ISSUE THREAD

**Issue by Weskerdoo** [tsunamayo/Starship-EVO#2658]
As adventurers in a far-flung section of the galaxy, are we not given the ability, by right of discovery, to name things as we see fit? 

I move that the planet be named "Bloopitur".

Thank you.

**Comment by Rexxios** [comment]
I Second this!

**Comment by Kaiser-Indrasil** [comment]
As the rule of dibs says, whoever should proclaim "dibs" first, to them the right of dibs belongs.
Hence, DIBS!

**Comment by MRonlin** [comment]
Not bloopitur

**Comment by tsunamayo** [comment]
lol I will think about it ;)

**Comment by Jorpis-Jorah** [comment]
Why Bloopitur? It's been changed to purple now, so it should be...Purplilture
