### ISSUE TITLE
[Bug] XL lattice girder has collision issues

### ISSUE THREAD

**Issue by InCrIpTiOn** [tsunamayo/Starship-EVO#2660]
The XL lattice girder does not have any collision when it's size is over 32 blocks in size.
It has collision up to 33 blocks at sizes greater than 32:
![image](https://user-images.githubusercontent.com/23437039/87189004-c1a0db80-c2e7-11ea-9245-bd29136b9e18.png)

**Comment by InCrIpTiOn** [comment]
Same problem with the thin lattice girders (large)

**Comment by tsunamayo** [comment]
Fixed for 20w41a. Thanks!
