### ISSUE TITLE
[SUGGESTION] Need to brainstorm to make it easire to see larger builds on the shadow side 

### ISSUE THREAD

**Issue by Servomotor** [tsunamayo/Starship-EVO#2661]
### Short Description of the issue:
I love the new shadows and how dark ships are when not being lit up but it seems that some folks are having issues being able to see their builds and build effectively, especially on large builds. 

Perhaps we need some kind of debug light mode that allows for the ship to be lit up on all sides (how the game used to look) that is disabled when piloting a craft (to help ensure the greater light does not affect survival). 

I don't really know what to recommend because I am not sure what the game engine will allow, but there has to be a way of maintaining the current look of the game, but also allow for greater light for easier building on the shadow side of a build. 

...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by InCrIpTiOn** [comment]
I suggest a natural "fix" to this would be by giving the planet ambient light so that it illuminates your ship. This way you can build in  front of the planet and have your entire ship illuminated. However I am not sure how bright it would be, but I assume it's enough to see relatively well.

**Comment by tsunamayo** [comment]
It was an issue with reflections map, this is fixed for 20w28e. Thanks!
