### ISSUE TITLE
[Suggestion] Prefabs!

### ISSUE THREAD

**Issue by CaptainKronos** [tsunamayo/Starship-EVO#2663]
Something that would make any ship with turrets (or any weapon) much easier to build would be the addition of a new kind of local/workshop blueprint: a prefabricated object.
This would be used to make copies of objects (which could be done in a similar fashion to the stretch building system) so you could then paste them in their entirety on an entity such as a ship or station.
An alternative to this would be allowing separate entities to be merged together, IE you build a ship, build a turret for that ship, take the turret as a BP, spawn it in, and use a tool of some kind to connect it from a certain block to another certain block on the ship. Kind of like merge blocks in SE.

**Comment by Rexxios** [comment]
Indeed, and space engineers-style landing gear would be implemented much easier as well

**Comment by tsunamayo** [comment]
Okay I am gonna close this one, yes this is a valid suggestion but it has been posted countless time ;) cheers
