### ISSUE TITLE
Invisible blocks in MP

### ISSUE THREAD

**Issue by Vicomt** [tsunamayo/Starship-EVO#2664]
### Short Description of the issue:
This is a repeat of the older problem - after a while, blocks placed become invisible. block placed by either a client or host exhibit this behaviour.

### Steps to reproduce the issue:
open a large build
start placing blocks, deleting blocks until placed blocks do no render.

### Environment
- Starship EVO version: 20w28b
- Graphics Card: GTX 1070

### Additional information:
![20200711193730_1](https://user-images.githubusercontent.com/7197427/87231400-df854380-c3ae-11ea-8a6f-d03b4f2b7ca9.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4907462/output_log.txt)

**Comment by Vicomt** [comment]
20w28c super-cedes this. and appears to fix it.

**Comment by Vicomt** [comment]
Further to the original issue and how 20w28c performs - It's freakin excellent. we had a two player 4 hour+ session today with zero block lag, zero invisible blocks, zero reloads and 99% buttery smooth 50fps.

**Comment by tsunamayo** [comment]
great to hear that, I think it was issue closed 2000 on top of that lol.
Next update will see a bigger FPS improvement if you are using a lot of children entity. 
Cheers
