### ISSUE TITLE
Connectors cannot attach to rails

### ISSUE THREAD

**Issue by TheShadowSage** [tsunamayo/Starship-EVO#2669]
### Short Description of the issue:
So I've tried experimenting with connecting ships together via railways and connectors. Unfortunately they cannot, and I was wondering if it may be possible to change that? You can use the connectors with other blocks, but even when I have them connected onto a railway the connector refuses to link together. Thanks! 

### Environment
- Starship EVO version: 20w28b

**Comment by alxnns1** [comment]
https://github.com/tsunamayo/Starship-EVO/issues/2602

**Comment by tsunamayo** [comment]
Yes it is a valid suggestion, unfortunately it is a bit complex to make it work. I will close this as there is already an suggestion booked by @alxnns1 ! Cheers
