### ISSUE TITLE
[Bug] rolling while using spectator camera spins character 

### ISSUE THREAD

**Issue by itsKeq** [tsunamayo/Starship-EVO#2671]
### Short Description of the issue:
If using spectator camera and you roll (Q or E) while using camera and switch back to character the character model will spin with no way of stopping unless you reload
...

### Steps to reproduce the issue:
use spectator camera (F6) then use q or e to roll switch back to character camera (F4)
...

### Environment
- Starship EVO version: 20w28b
- Graphics Card: RTX2060

**Comment by 5URG3** [comment]
Can confirm, I also have this issue.

**Comment by CaptainKronos** [comment]
I have also had this issue. 

Also hello Keq and 5URG3

**Comment by tsunamayo** [comment]
Issue seems to be fixed in recent update. Thanks
