### ISSUE TITLE
[Bug] Sticker Bugs

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#2679]
1. Stickers will layer on top of most bricks that are one brick above the sticker. Stickers will not show up two bricks above the sticker.

![](https://cdn.discordapp.com/attachments/406664114249793536/733569346458353754/unknown.png)

2. I'm not sure how to describe this bug. The sticker color shows up in the boarders of bricks next to the sticker

https://cdn.discordapp.com/attachments/406664114249793536/733569490889080842/Starship_EVO_2020-07-16_23-22-45.mp4

**Comment by tsunamayo** [comment]
Fixed for 20w29c, thanks for trying out EXP! Cheers
