### ISSUE TITLE
Lag spikes when moving towards or away from large clustered ships near torus

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Starship-EVO#2684]
-Single player

The game will start lagging when i get a certain distance towards or away from the ships near the torus. there seems to be a specific range area distance from the ships this happens. 

...

Move closer to the ships in my world save with the "]" pressed twice

...

### Environment
- Starship EVO version: 20w29d
- Graphics Card: 1080ti

### Additional information:

I do not have gifs but you can see the lag spikes on the FPS tracker

Far (no problems about a 40fps drop in the most recent update but still at 140ish)
![20200718224136_1](https://user-images.githubusercontent.com/45324484/87866574-25ab4b80-c949-11ea-82bd-e3543b7ec502.jpg)

Medium/close after the lag spike as seen in the FPS tracker
![20200718224147_1](https://user-images.githubusercontent.com/45324484/87866583-38be1b80-c949-11ea-97f9-1dc523b2e5d9.jpg)

about the middle of the affected lag spike distance area 
![20200718224207_1](https://user-images.githubusercontent.com/45324484/87866594-57241700-c949-11ea-93ab-d76e721d82d5.jpg)

[Characters.zip](https://github.com/tsunamayo/Starship-EVO/files/4943201/Characters.zip)
If you spawn in you should be right next to the area where this was happening.

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4943199/output_log.txt)

**Comment by InCrIpTiOn** [comment]
Also having the same issue with 1050ti, perhaps it's an issue with loading lods with such large ships

**Comment by tsunamayo** [comment]
@what lods? maybe there is a feature I am not aware of ;) . So it is due to the decal sorting algorithm, I increased the max number of decals to solve another bug and it kill perf due to that, I will sort this out. Amazingly I it is coming from the smaller ship, not the bigger one.

**Comment by tsunamayo** [comment]
Okay I fixed the issue, the decals now render a bit less tidy though because of this but I think it is acceptable. Btw @ExodistSKY1 amazing fleet, and you are gonna love the next update as I have just added a mag-lock for carrier ships (if you dont want to use shipyard).
Also I would not spend too much time doing the camo pattern (it was the fps killer btw), now fps are fine but I plan to add a camo pattern paint at one point ;)
Cheers
