### ISSUE TITLE
[BUG] Ship Surface Area Seems Wrong and Won't Update

### ISSUE THREAD

**Issue by Kadzar** [tsunamayo/Starship-EVO#2686]
### Short Description of the issue:

I have a ship that was fine for heat the previous night, but today it overheats, and the surface area won't change no matter how many bricks or blocks I add.

### Steps to reproduce the issue:

Not sure what caused it. Checking my blueprints, it seems the bug showed up somewhere between version 0.4 and 0.4.1 (I probably need a better numbering system).

### Environment
- Starship EVO version: 20w29d
- Graphics Card: NVIDIA GTX 1080

### Additional information:

![20200719163214_1](https://user-images.githubusercontent.com/66035211/87885883-5b4e4400-c9de-11ea-8048-bbd5ad0fec8d.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4944715/output_log.txt)
Latest version[Small Saucer Fighter 0.5.1.zip](https://github.com/tsunamayo/Starship-EVO/files/4944717/Small.Saucer.Fighter.0.5.1.zip)
Last unbugged version[Small Saucer Fighter 0.4.zip](https://github.com/tsunamayo/Starship-EVO/files/4944719/Small.Saucer.Fighter.0.4.zip)
First bugged version[Small Saucer Fighter 0.4.1.zip](https://github.com/tsunamayo/Starship-EVO/files/4944723/Small.Saucer.Fighter.0.4.1.zip)

**Comment by tsunamayo** [comment]
Great test case, thanks for sending the ships. Issue fixed for 20w30a. Cheers

**Comment by Kadzar** [comment]
Awesome! Thanks!
