### ISSUE TITLE
[Bug] Stuck after maglock is destroyed

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Starship-EVO#2688]
### Short Description of the issue:
Deleting an active maglock block does not delete the effect leaving a ship stuck
...

### Steps to reproduce the issue:
- place block
- lock a ship
- delete block
- try to fly ship
- issue
...

### Environment
- Starship EVO version: 20w30a
- Graphics Card: integrated graphics

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4945259/output_log.txt)

**Comment by tsunamayo** [comment]
Good point indeed, issue fixed for 20w30b. Thanks!
