### ISSUE TITLE
Odd Mass Calculations

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#2689]
I found an odd thing while testing out the new Maglocks.

It seems this cube with a dimension of 16x16x16m has a mass of 410 t
![20200719215516_1](https://user-images.githubusercontent.com/32974671/87895691-afbbe880-ca0b-11ea-95db-80f82e10d62d.jpg)

While this ship, the sphere has a diameter of 72m, has a mass of 1456.7 t
![20200719215456_1](https://user-images.githubusercontent.com/32974671/87895731-cc582080-ca0b-11ea-98fc-40e3d757e5a3.jpg)

I'm not sure if this is how you intended it to work but to me this doesn't make a lot of sense. Either the cube should have much less mass or the spherical ship should have way more. Granted maybe it's due to the cube having more concentrated mass into one block? But even then the sphere ship has wayyyy more blocks to overcome the total that the cube would have.

**Comment by tsunamayo** [comment]
I dont know, your cube / sphere are empty I guess? Tetra and hepta mass are smaller than the main one. It doesnt sounds too shocking to me.

**Comment by InCrIpTiOn** [comment]
For the sphere:
![image](https://user-images.githubusercontent.com/23437039/87978444-4f3eb100-cac8-11ea-8afe-65d99894197b.png)
= 1204t
For the cube:
![image](https://user-images.githubusercontent.com/23437039/87978558-801ee600-cac8-11ea-881e-0408a55ae22d.png)
= 610t
Even know the masses aren't accurate you can see that when the radius of the blocks in the sphere are 0.5 the mass is still much greater than the cube, so there is nothing out of the ordinary here

**Comment by tsunamayo** [comment]
wait @Xerma your cube is full but your sphere is empty? in that case I would have even expected the opposite.

**Comment by InCrIpTiOn** [comment]
Well you can see by the math that the hollow sphere has more mass even though it is mostly empty
