### ISSUE TITLE
Maglock doesn't lock - Entity too heavy

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#2690]
### Short Description of the issue:
The cube in this example has a mass of 410t while the maglock says it supports up to 1000T but yet it refuses to lock to the entity
...

### Environment
- Starship EVO version: 20w30a
- Graphics Card: GTX 970

### Additional information:
![20200719220822_1](https://user-images.githubusercontent.com/32974671/87896195-22799380-ca0d-11ea-82ae-b0a19ead86a1.jpg)

**Comment by BrickMacklin** [comment]
I am having the same issue. entity is 3.1 tons but the maglock refuses to latch.

**Comment by tsunamayo** [comment]
Issue fixed for 20w30c. I was using the weight and not the mass... Cheers
