### ISSUE TITLE
[Bug] Unspawning maglocked ships strip host ship of parent entity

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#2694]
### Short Description of the issue:
While testing the new maglock blocks, I locked onto another ship with this A-Wing (The A-Wing had the maglock on it). I then despawned the other ship, and the A-Wing ~~stripped naked~~ parent entity turns invisible, and a ghost of the parent entity follows the ship by teleporting around.
In the forground are all the child entities left on the ship, and in the background you can see the ghost of the parent entity.
![image](https://user-images.githubusercontent.com/27857711/88083380-df3d3300-cb7a-11ea-996f-e8d2dd33f9f9.png)

### Steps to reproduce the issue:
Lock onto a ship with using the maglock
Unspawn the ship that you locked onto

### Environment
- Starship EVO version: 20w30b
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
Fixed for 20w30c. Cheers!
