### ISSUE TITLE
BUG ship corrupted? from rendering?

### ISSUE THREAD

**Issue by TripleHelixxx** [tsunamayo/Starship-EVO#2698]
### Short Description of the issue:
was working on a ship when thing would vanish after placing other thing. pipes, bricks, blocks, etc. Reloaded to try and fix, then ship was half missing and half invisible. 
...

### Steps to reproduce the issue:
not sure how to reproduce this. 
...

### Environment
- Starship EVO version: EA20w30b
- Graphics Card: GTX 1060 6GB

### Additional information:
As shown in the image below, a large portion of the ship is missing. Some of the ship is just invisible. 
additional note, I tried spawning a copy of the ship, but the issue persisted, so It seams the blueprint itself may be corrupted or something.

![20200721183711_1](https://user-images.githubusercontent.com/64316439/88115666-b0c45580-cb84-11ea-89f3-6ddf445959b6.jpg)
![20200721183655_1](https://user-images.githubusercontent.com/64316439/88115667-b15cec00-cb84-11ea-8c98-32dd622519ba.jpg)

Blueprint:
[Jupiter (corrupted).zip](https://github.com/tsunamayo/Starship-EVO/files/4956934/Jupiter.corrupted.zip)

Output Log:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4956907/output_log.txt)

**Comment by tsunamayo** [comment]
Thanks for the blueprint, issue is now fixed for 20w30d, you will be able to see your ship fully. Cheers
