### ISSUE TITLE
Visual bug - Blocks become see through

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#2700]
### Short Description of the issue:
I have no idea what's causing this but it seems when you're up close to some certain part of a an entity, well these door panels are on pistons, at some specific level the block(s) below you become completely see through.
...

### Environment
- Starship EVO version: 20w30b
- Graphics Card: GTX 970

### Additional information:
![20200722102146_1](https://user-images.githubusercontent.com/32974671/88196004-4eac3480-cc06-11ea-9457-c56d161bf0aa.jpg)
![20200722102156_1](https://user-images.githubusercontent.com/32974671/88196009-51a72500-cc06-11ea-9ae3-edb7a7eba0e6.jpg)
![20200722102157_1](https://user-images.githubusercontent.com/32974671/88196017-5370e880-cc06-11ea-8826-2911e7fcf8a7.jpg)
![20200722102159_1](https://user-images.githubusercontent.com/32974671/88196022-54a21580-cc06-11ea-9117-acdc5b51e960.jpg)
![20200722102209_1](https://user-images.githubusercontent.com/32974671/88196026-566bd900-cc06-11ea-8b5e-14ae965fc117.jpg)

And the blueprint to see if you can reproduce:

[72m Sphere Shell 3.zip](https://github.com/tsunamayo/Starship-EVO/files/4960893/72m.Sphere.Shell.3.zip)

**Comment by AlienXtream** [comment]
its called frustum culling and its technically intentional.... except its only supposed to happen to thing OFF screen... seems the new rendering tech still has some hiccups

**Comment by tsunamayo** [comment]
Okay to confirm it is a hull block that disappears? Not a piston or a blast door?
Yes there is still a few glitches to fix with the new tech. Thanks

**Comment by Xerma** [comment]
Yep it's a block

**Comment by tsunamayo** [comment]
Okay thanks for the test case, I managed to reproduce, actually it was not the frustrum cull but the occlusion cull for some reason. I keep you posted once it is fixed.

**Comment by tsunamayo** [comment]
Okay issue fixed for 20w30c! Cheers
