### ISSUE TITLE
[Bug] Window tile wedge is opaque in Ship preview

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#2701]
### Short Description of the issue:
Just a quick one, as the title says the brick wedge canopy appears as a solid part in the ship preview. It looks like it could be a really cool shape to have though ;)
![image](https://user-images.githubusercontent.com/27857711/88226765-7cc06180-cc64-11ea-9cce-bb72fa548756.png)
Also, the view in the preview is not centred
![image](https://user-images.githubusercontent.com/27857711/88226889-b002f080-cc64-11ea-9c8d-64d893815fd4.png)

### Steps to reproduce the issue:
Place a window tile wedge
Look at the ship preview

### Environment
- Starship EVO version: 20w30b
- Graphics Card: RX 580

**Comment by ProPeach** [comment]
Looks like Window Tile Tetras and Window Tile Triangles are completely invisible on the preview too. The regular Window Tile is also opaque

**Comment by tsunamayo** [comment]
Fixed for 20w30e. Thanks!
