### ISSUE TITLE
[Bug] vehicle 3rd person view broken and engine sound glitching

### ISSUE THREAD

**Issue by OverSavior** [tsunamayo/Starship-EVO#2706]
When in a vehicle and piloting, the camera is still attached to the character, not the ship. Consequently it won't zoom out very far, just as far as seen in the video. As for the sound, when flying fast enough it begins to glitch. I'm not sure how to describe it better.
https://youtu.be/ymUM3daOnXk

**Comment by tsunamayo** [comment]
It is a pretty serious one, 3rd person is not usable. Fixed for 20w30d, I upload the patch soon. Thanks!
