### ISSUE TITLE
[Bug] "It seems you're stuck!" Tip pops up even when already in UnStuck Mode

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#2707]
### Short Description of the issue:
Just a quick one, even if you've already enabled UnStuck Mode you sometimes get the help tip for it.
Also, this mode is commonly called "No-Clip Mode" in other games, I think that might be a better name for it.

### Steps to reproduce the issue:
Enter Un-Stuck Mode
Get yourself "stuck". It doesn't come up very often, but I've seen it happen twice in about 5 minutes

### Environment
- Starship EVO version: 30w20c
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
So I am not sure how you manage to get the message (I was not able to reproduce), but in any case it wont popup when the mode is ON! From 20w30e. Thanks!

**Comment by tsunamayo** [comment]
Ho I also renamed it to no clip like suggested ;)
