### ISSUE TITLE
[Bug] Dropped Weapons spawn next to the player on reload

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#2708]
### Short Description of the issue:
This one took some testing to figure out. If you create a handheld weapon, then drop it (drag it off of your hotbar onto the codex), it will spawn floating next to the player a few meters away every time you load into the world.

As an aside, is there any way to actually remove a weapon from the world? I expected dragging it from your hotbar to the codex to delete it like what happens when you drag a building block onto it. Perhaps it should be deleted if you drag it on to the Trash icon

### Steps to reproduce the issue:
Load the attached character
A test weapon looking like this will close to you
![image](https://user-images.githubusercontent.com/27857711/88289221-d1a7ba80-ccec-11ea-88eb-e9bbaed91739.png)
Fly away from the test weapon
Quit to desktop and reload the character
You will find that the weapon has moved and is now floating close to you again

### Environment
- Starship EVO version: 30w20c
- Graphics Card: RX 580

###Additional Files
[Handle Bug.zip](https://github.com/tsunamayo/Starship-EVO/files/4965993/Handle.Bug.zip)

**Comment by tsunamayo** [comment]
Issue fixed for 20w31a. Thanks!
