### ISSUE TITLE
[Bug] The Command List menu can't be closed with 'esc'

### ISSUE THREAD

**Issue by Tezlz** [tsunamayo/Starship-EVO#2711]
### Short Description of the issue:
The Command List menu can't be closed with 'esc'. 

### Steps to reproduce the issue:

Try to close it with 'esc'.

### Environment
- Starship EVO version: 20w30d
- Graphics Card: GTX 1060 6 GB

**Comment by tsunamayo** [comment]
Issue fixed for 20w30d. Thanks!
