### ISSUE TITLE
[Bug] Command List Menu doesn't show changed keybinds.

### ISSUE THREAD

**Issue by Tezlz** [tsunamayo/Starship-EVO#2712]
### Short Description of the issue:

If you rebind the MoveFaster and MoveSlower keys in keybinds they still show up as '[' and ']' in the command list menu.

### Steps to reproduce the issue:

Change the keybinds of the MoveFaster and MoveSlower keys to anything other than their default. Open the command list menu and see that it still says '[' and ']' as the keybinds for moving faster and slower.

### Environment
- Starship EVO version: 20w30d
- Graphics Card: GTX 1060 6 GB

**Comment by tsunamayo** [comment]
Okay so starting from 20w30e they are no longer bindable (these are debug keys...)

**Comment by Tezlz** [comment]
@tsunamayo In that case I would recommend choosing different keys for it as not all keyboards have '[' and ']' keys (mine included)

**Comment by tsunamayo** [comment]
Good point I didnt knew that, I guess I will have to make them bindable, and simply remove them from that screen! It is the screen for non-bindable hotkeys... Cheers
