### ISSUE TITLE
[Bug] Destroyed voxels do not turn invisible unless the world is reloaded

### ISSUE THREAD

**Issue by ted234521** [tsunamayo/Starship-EVO#2713]
When targeting a ship or structure with weapons, destroyed sections of the construct do not turn invisible and instead display the damaged texture (holes/grate). They are not physically simulated, ie can be shot/walked through, but are not turning invisible as intended.

Reloading the world from the main menu fixes this.

**Comment by Kaiser-Indrasil** [comment]
Indeed, I'm getting the exact same bug myself.

**Comment by BrickMacklin** [comment]
I get this bug as well

**Comment by tsunamayo** [comment]
So I also saw this issue a couple days ago and fixed it, it will be in patch 20w30e, thanks!
