### ISSUE TITLE
[Bug] High GPU usage with only a few objects ingame

### ISSUE THREAD

**Issue by Rexxios** [tsunamayo/Starship-EVO#2714]
### Short Description of the issue:

Just by playing the game, the GPU usage percentage is in the high 90s.

### Steps to reproduce the issue:
Open the game, then load a save.

### Environment
- Starship EVO version: 20w30d
- Graphics Card: Nividia 1060 6G Vram

### Additional information:
Comparison to other games:
-Space Engineers: ~40%
-Arma 3: ~36%
-Skyrim Special Edition: ~53%

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4976235/output_log.txt)

**Comment by BrickMacklin** [comment]
I've always had high GPU usage with this game. Runs the fans high. Both with a 1080 and not a 2080 Ti.

**Comment by tsunamayo** [comment]
What is your vsync setting? if you do not set it ON, then the game will try to render as many FPS as possible, and being GPU bounds it will max out the GPU.

**Comment by ProPeach** [comment]
My GPU also works hard, often at 90-100% with or without V-Sync on with my RX 580
With V-sync off I get around 80-150 frames, so in theory there should be quite a difference when it's sitting at a steady 60 with V-sync on

**Comment by Misteropie** [comment]
I still have the same problem. Seems like it is identical to my old issue #2326

**Comment by SovietSponge** [comment]
The only way I can describe what this game in general does to my poor laptop is a jet engine, very few games will do this even with max settings so it's kind of concerning and I have v-sync on and everything.

**Comment by tsunamayo** [comment]
I just dont reproduce this issue, on my side with v-sync ON I switch from 100% to 70%. 
What I did (could you do the same ?)
- I had to first make sure I am GPU bound by going to the torus surface.
- Then as I was naturally too close to the v-sync target I deactivated all GFX options, bloom and other filters
- Press F2 to not render UI

Then do the comparison: if you could take a screenshot of your GPU usage graph and in-game FPS with v-sync ON/OFF. Same location, same camera angle!

If your fps with ON and OFF are close, then I guess it is normal, otherwise there is something wrong.
Also could you make sure your GFX driver are up to date as usual?

Thanks!

**Comment by StarrKiss** [comment]
I have this issue too on a friends pc, it doesn't occur on mine. His has a GTX 1060 and Ryzen 5 2600, mine a Ryzen 7 3700x and a GTX 1070 ti. It doesn't seem that there should be that drastic difference, but his runs at v low FPS unless he sets the resolution super low, in which case it's smooth. For him there is constant high CPU +GPU usage. We both use the same operating system and Nvidia drivers.

**Comment by tsunamayo** [comment]
@StarrKiss what is a very low FPS? Could you give a number, what was on screen at that time, and the resolution used? I am running the game on a GTX960, and I am mostly at 60fps, except on torus or during fights.

**Comment by StarrKiss** [comment]
@tsunamayo  Around 5 FPS. it was just on the torus with the starter base + ships, in 1920 x1080. When in space its more like 10 -15 fps. When he sets the res of the game down to the lowest available (or one or two tiers above) it runs smoothly at around 60, but still drops to 30-40 at some parts of the world.

**Comment by tsunamayo** [comment]
@StarrKiss this is definitely not normal! Could I have your friend go over here, I would to investigate that issue, maybe some other people had the same. I would like a log for starter, and do a try with some graphics options off. Could you convince him to come over here? Thanks!

**Comment by Misteropie** [comment]
I've tried doing what you said above Tsuna. The lowest usage I could get it down to was 70% while on the Torus. But this was with all graphical options disabled and v-sync on and not looking at any of the builds. FPS was at ~120 the whole time except when I turned off V-sync then it would go to 140-155. Could we have more control on how hard V-sync limits fps? 

I would still like to play the game with those options on though. What you've made is very pretty, it just hurts to see it run so high on stronger GPU's.

As for low FPS issues like Star's friend I've only ever experienced it when flying larger ships in gravity and tanking to 0 when touching water.

**Comment by tsunamayo** [comment]
@Misteropie Does your monitor support 120 Hz? That is quite a high refresh rate! From what you just said there seems to be no bug, I just need to give you an option to run the game at lower fps than 120hz. But again what is the point of having a high refresh rate monitor, a high-end GPU but wanting to throttle back everything? Cheers
