### ISSUE TITLE
Grey paints have no effect on lights

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#2717]
### Short Description of the issue:
Pretty simple, the grey paints don't change the lights at all. I do believe they used to dim the lights to a degree but black paint on lights just makes the light(s) purple - which may be intended but is kind of ironic: blacklight. Could we get the grey paints to dim the lights? I'm trying to get a less saturated blue in one of my ships but the only way to get the effect is by manually connecting a slider to each light. Whereas being able to paint the lights would be much easier for the player in terms of dimming white lights.
...

### Environment
- Starship EVO version: 20w30d
- Graphics Card: GTX 970

### Additional information:
Just blue:
![20200726153218_1](https://user-images.githubusercontent.com/32974671/88489335-5434b200-cf59-11ea-87a5-126c625f9c45.jpg)

With dimmed white lights + blue:
![20200726160346_1](https://user-images.githubusercontent.com/32974671/88489399-99f17a80-cf59-11ea-87ab-4e00c58721a5.jpg)

**Comment by tsunamayo** [comment]
Yes indeed, it is fixed for 20w32a! Cheers
