### ISSUE TITLE
Magnetic lock messes with both ships

### ISSUE THREAD

**Issue by TheFifthWarrior** [tsunamayo/Starship-EVO#2718]
### Short Description of the issue: 
Using magnetic locks at two ships at a time disabled both of them / made them unavailable
... 

### Steps to reproduce the issue:
I built a ship and wanted to test the new magnetic lock. After discovering that it doesn't couple with a random block i placed another ship start block and another magnetic lock underneath it and activated the lock on the parent ship. I got a message along the lines of: "Sucessfully locked New Entity to Old Entity". After that i was wondering what would happen if i activated the lock i had on the new ship. After i clicked the switch, i couldn't interact with any of the ships anymore and there seemed to be some sort of wall around them, which i could actually deconstruct. When i pressed tab and brought up the entity menu, it only showed a ship of 1x1 dimension, which certainly wasn't what i had build. After exiting and restarting the game and the character, the ships got stuck in the ground without any possibility to interact with them, i good bit of them buried in the ground.
Also i was wondering if there is some way to access an earlier save or earlier version of a ship i built?
...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:
[output_log - Kopie.txt](https://github.com/tsunamayo/Starship-EVO/files/4979003/output_log.-.Kopie.txt)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by Kadzar** [comment]
> Also i was wondering if there is some way to access an earlier save or earlier version of a ship i built?
If you saved an earlier version of ship under a different name, you should be able to respawn that earlier version. Otherwise, I believe the game saves over blueprints with the same name.

**Comment by tsunamayo** [comment]
Hi, this will be fixed for 20w32a. Thanks!
