### ISSUE TITLE
[BUG] Cockpit Canopy Randomly Becoming Opaque While Flying

### ISSUE THREAD

**Issue by Kadzar** [tsunamayo/Starship-EVO#2720]
### Short Description of the issue:

After the latest update came out, I've noticed my ship's cockpit occasionally becoming opaque at random, in a sort of stuttering interval.

### Steps to reproduce the issue:

No idea what causes it, but I think I also noticed a brick near the side of the cockpit flash white when the cockpit wasn't opaque, and also in 3rd person free-look mode It looked like there was a selection outline on bricks that my cursor was over.

This video is what I mean by the brick near the cockpit flashing white[Starship EVO 2020-07-26 22-07-41.zip](https://github.com/tsunamayo/Starship-EVO/files/4979748/Starship.EVO.2020-07-26.22-07-41.zip)

If you see that blue line there on the hull, that's what I mean by the selection outline. Not sure if that's even connected to what's going on, but thought I should bring it up. ![20200726215715_1](https://user-images.githubusercontent.com/66035211/88499451-7b0bdc00-cf8b-11ea-9535-6a1064f390c2.jpg)

### Environment
- Starship EVO version: 20w31a
- Graphics Card: NVIDIA GeForce GTX 1080

### Additional information:

One second, it would look fine ![20200726213828_1](https://user-images.githubusercontent.com/66035211/88499087-84e10f80-cf8a-11ea-9306-5d9448d7634a.jpg)
And then the next, I couldn't see anything ![20200726213829_1](https://user-images.githubusercontent.com/66035211/88499096-89a5c380-cf8a-11ea-9892-86fb8ec17480.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4979707/output_log.txt)

**Comment by tsunamayo** [comment]
Okay I am not reproducing this, could you send me your blueprint @Kadzar ? Is this something you get 100% of the time? Thanks

**Comment by Kadzar** [comment]
I don't think I've really encountered this bug since I first posted it, but I can share the blueprint regardless.
[KSE Sunfish Starfighter.zip](https://github.com/tsunamayo/Starship-EVO/files/5014227/KSE.Sunfish.Starfighter.zip)

**Comment by Kadzar** [comment]
Okay, so I've encountered this a bit more, and it seems to happen when I look at ships I've shot at or am shooting at while flying in a ship with a canopy. I'm attaching a video that shows that the problem occurs when looking at a ship I've shot at, and stops when I look away.
[Starship EVO 2020-08-13 13-13-58.zip](https://github.com/tsunamayo/Starship-EVO/files/5070740/Starship.EVO.2020-08-13.13-13-58.zip)

**Comment by tsunamayo** [comment]
So I also managed to reproduce and fix the issue, for 20w34a. Neat fighter!
