### ISSUE TITLE
Texturing bug

### ISSUE THREAD

**Issue by T00Code34215** [tsunamayo/Starship-EVO#2721]
### Short Description of the issue:
Ships spawning with weird texturing
...

### Steps to reproduce the issue:
1. Spawn any ship (I used https://steamcommunity.com/sharedfiles/filedetails/?id=2159819541)
2. Ship should appear like picture included
3. Spawn the same ship again. Problem solved on first ship but carried to second ship.
...

### Environment
- Starship EVO version: 20W31A
- Graphics Card: Geforce GTX 1070
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4982583/output_log.txt)
![20200727152814_1](https://user-images.githubusercontent.com/36076197/88554958-0d10f480-d01f-11ea-8cb9-82dfa85b3cd8.jpg)

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by Rhedd-V** [comment]
I’ve had the same thing happen consistently, but only after the last update. For me, spawning a different blueprint then going back to the one I wanted fixes it every time.

**Comment by Rhedd-V** [comment]
Update: This happens almost every time I first load a blueprint. Also, often (but oddly not always,) placing a light on the bugged ship will fix it. Placing any block other than a light does not work.

**Comment by tsunamayo** [comment]
Issue fixed for 20w32a. Thanks a lot!
