### ISSUE TITLE
[Suggestion] Have the blueprint files placed in folders (in the Blueprints folder)

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#2726]
In short, I'd suggest making blueprints save to folders in the blueprints folder and in those folders are the mps, png, xml, bloom, and preview files. At the moment, if you have many blueprints it gets chaotic very fast and is a bit tricky to find the file you're looking for. I personally feel like this would help things be more organized and easier to navigate.

I suggest taking this:
![nopacking](https://user-images.githubusercontent.com/32974671/88819190-4794a180-d185-11ea-9101-c8d86574d445.png)

And making it like this:
![packing](https://user-images.githubusercontent.com/32974671/88819222-52e7cd00-d185-11ea-9db8-358892d36514.png)

**Comment by tsunamayo** [comment]
Yes it was on my to-do list ;) Cheers

**Comment by tsunamayo** [comment]
Finally done for 20w40c mate ;) Cheers
