### ISSUE TITLE
[BUG] absent shadows and grating textures

### ISSUE THREAD

**Issue by OldIronsides** [tsunamayo/Starship-EVO#2727]
### Short Description of the issue:
 i have been seeing a graphic bug that has the shadow effects disabled despite toggling them on/off on the F3 tab. Also blocks like grating are missing the grate texture (it shows up as an empty frame).  I have tried completely uninstalling the game and removing the world files from the computer, but the issue persists.
it has been happening since a few updates ago (the last screenshots i have taken without the problem are tagged with 20w28b, the next one was in 20w30d and had the bug).

### Steps to reproduce the issue:
none, from startup the shadows and some textures are absent

### Environment
    Starship EVO version: 20w31a
    Graphics Card: NVIDIA GeForce GTX 765M

### Additional information:
![20200729142810_1](https://user-images.githubusercontent.com/51378714/88833513-bd5e3480-d1a8-11ea-9c7a-e2f2f50c5e40.jpg)

output_log.txt file:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4996525/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, sorry for being late - I wanted to check the yamato myself to check if I reproduced and I dont... 
A few questions:
1) are your driver up to date?
2) do you get this on all world, all ships?
3) in the Codex preview, do you see the grating texture?

Thanks!

btw do you have my mail address? I would like to ping you to get one or two of your marvelous build for stations modules, if you are interested... Cheers

**Comment by tsunamayo** [comment]
Hi, so it seems that your drivers are a bit old, could you please update your OS and GFX drivers? I think I know exactly what is not working, it seems that the atomic operation in compute shader is not working which points to a driver issue. Cheers

**Comment by OldIronsides** [comment]
I updated them both (wow, its been a while), but the same problem persists, this computer has windows 8.1, if it changes anything.
i will keep on trying 

As for the stations, i have not worked much in the past few weeks, so while i have some sketches of what i want to do, i have not even started on my own station. maybe soon!

**Comment by tsunamayo** [comment]
@OldIronsides what is the OS in that other laptop? Thanks

**Comment by OldIronsides** [comment]
Its Windows 10 Home.

**Comment by tsunamayo** [comment]
@OldIronsides so I have made a workaround tentative fix for 20w24a. I am uploading the build soon in Experimental, I keep you posted, hopefully it will fix it but I cant guarantee it. Cheers

**Comment by tsunamayo** [comment]
@OldIronsides  so could you please tell me how it goes in the new Experimental beta 20w34a - build is live? Thanks

**Comment by tsunamayo** [comment]
@OldIronsides sorry it took so long, it should finally be fixed in next update 20w36a. Thanks!
