### ISSUE TITLE
[BUG] Logic Elements not detecting correctly

### ISSUE THREAD

**Issue by SimonLain** [tsunamayo/Starship-EVO#2728]
### Short Description of the issue:
In the game Logic elements such as the "Laser Sensor" and the "Volumetric Sensor" describe being able to detect Players **or an entity** crossing it. During my testing things like other ships/child entities (on the same ship and a separate one)/blocks and basically anything that isn't a "Player entity" does not trigger the Sensor blocks whilst I believe it should.
...

### Steps to reproduce the issue:
Get out the Sensor block and put any type of other "entity" that isn't a player in front of it.
...

### Environment
- Starship EVO version: (experimental) 20w31a
- Graphics Card: RTX 2080

### Additional information:
I confirmed with other users on the same version that this issue persists in their clients as well.

**Comment by tsunamayo** [comment]
Yes sorry it is still wip, the problem is making something that wont lag when player will inevitably uses 100s of them...

**Comment by tsunamayo** [comment]
@SimonLain Hi, so this will be finally working for 22w45a. Thanks
