### ISSUE TITLE
[Suggestion] Connector GUI / Connection Options

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#2729]
It would be super sweet if we could open up a screen and label what type of connector can connect to another connector (a GUI where you can choose from a list of preset labels or make your own) - This would probably be made simpler if we also get the option to toggle between whitelisting or blacklisting connections with certain labels. This would enable some very unique station spawning and allow for more control and I think it would make it all feel more controlled.

For example in the screen lets say some default labels are: "hallway-straight", "hallway-corner", "6-way-connector", "living-quarters-1", "living-quarters-2", "landing-pad", "shipyard" but then you want to add a label for "cargo" then you could set a connector to only connect to "cargo" or turn on the blacklist and say that it can connect to anything but "cargo"

**Comment by ZachZent** [comment]
I like the idea, though I would keep the options simple and generally few as to promote organized by random generation. Hallway is for all types, straight, corner, etc. Habitat for all living quarters. Hub. Really basic labels as too many will result in the virtually same station being generated all the time.

**Comment by Garrett-C** [comment]
I mean is it needed though? I don't see players needing to procedurally generate stations. Maybe if there is a way to subscribe to a station set on the workshop in the future sure. As it is though everything is pretty manual.

**Comment by tsunamayo** [comment]
Yes player wont procedurally generate them except from modding, and if you do all info will be to ouput over at 
\Starship EVO_Data\StreamingAssets\Factions\AAM\AAM.xml (replace AAM by your faction name)
still wip I will make something a bit easier to edit (for example the type is an enum).Thanks

**Comment by BrickMacklin** [comment]
While at it could we name buttons?
