### ISSUE TITLE
[Suggestion/Bug] Chair output issue

### ISSUE THREAD

**Issue by AlienXtream** [tsunamayo/Starship-EVO#2731]
### Short Description of the issue:

Seat gives continuous pulsed output (like a timer gate or button). should give constant signal like switches

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
What do you mean exactly, did you plug your seat into something? Thanks

**Comment by AlienXtream** [comment]
https://youtu.be/DyHGkAFzwJ4

**Comment by tsunamayo** [comment]
Okay I see, it was not made for this indeed, so from 20w32a you wont be able to do the link.
But I will add soon a "event gate" to do just that, event you will be able to choose will be "pulse: On Seat" "pulse: On Exit", "Signal:Is Seated"
Cheers
