### ISSUE TITLE
[Bug] paint colors changing when re-spawning a ship

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#2738]
### Short Description of the issue:
My ship was dark blue but when I spawned it in the blue paint turned black and it wont let me paint the parts
...

### Steps to reproduce the issue:
I went from the asteroid belt then flew to the habitat and spawned in a painted ship and it turned black.
...

### Environment
- Starship EVO version: 20w31a
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
![Starship EVO 7_31_2020 4_11_30 PM](https://user-images.githubusercontent.com/56371294/89087708-026d9c80-d34a-11ea-8106-f17d317f7db9.png)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5009361/output_log.txt)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Could you send me the blueprint? Thanks

**Comment by TIKIRobo** [comment]
[TIPS-102-01.zip](https://github.com/tsunamayo/Starship-EVO/files/5012304/TIPS-102-01.zip)
this should be the closest version of the blueprint unfortunately when I re-spawned the ship it's colors went back to normal.

**Comment by tsunamayo** [comment]
Hi, I think it was the same issue as #2721, which is now fixed. Your bp loads fine over here! Fix for 20w32a. Thanks!
