### ISSUE TITLE
[Question] Can i change my creation from Structure to Ship?

### ISSUE THREAD

**Issue by Sev87** [tsunamayo/Starship-EVO#2739]
Out of old habit (Space Engineers) i constructed a huge ship by tether the starter block to the Torus surface and now, on the planned maiden flight, the game tells me that it is a structure, not a ship. No permission to fly.
Are there any parameters in the ships save file i can change to make it a ship or is there already an option implemented? I don't wanna wasted a week of work for looking at a 50m long hangar queen. Thanks in advance and have a nice weekend.

**Comment by tsunamayo** [comment]
Hi, have you tried exporting your ship as a blueprint, then re importing it from a starter block (not build as a terrain structure this time of course)? Thanks

**Comment by Sev87** [comment]
> 
> 
> Hi, have you tried exporting your ship as a blueprint, then re importing it from a starter block (not build as a terrain structure this time of course)? Thanks

Good morning, mon Capitaine. Negative. I tried it both within the Torus "atmosphere" and in space. When trying to activate the Controls, the game still says, "You cannot control a terrain structure".

**Comment by tsunamayo** [comment]
Okay I made a few change to the way entity loads, so in 20w32a you will be able to load the blueprint as a spaceship. I am fixing a few more bugs and pushing the build. Thanks!

**Comment by tsunamayo** [comment]
Okay so this actually wrecks havoc in other part of the game, so I will have to revert it. If you still want to do the change be quick to use the Experimental beta branch as I will have to overwrite that build very soon! Cheers

**Comment by Sev87** [comment]
Got it. Now that i had the chance to test and streamline my ship design (it was massively under-powered and flew like a brick), i can wait for a solution that not fuck up other parts of the game. You doing great man, so far i have lot of fun with the game. Have a nice and productive week, mon Capitaine.
