### ISSUE TITLE
[Bug] Teleporting ship

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#2740]
### Short Description of the issue:
I destroyed a ship then when I flew to it I flew right threw it and later when I went back to my ship the destroyed ship followed me
...

### Steps to reproduce the issue:
destroy a ship then see if you can fly through it if not try again
...

### Environment
- Starship EVO version: 20w31a
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
It wont let me upload the video so if you want to see it dm me at TIKI2000#7759

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5010932/output_log.txt)

**Comment by tsunamayo** [comment]
Okay so what do you mean by destroying a ship? Do you mean hitting it with weapons until it is destroyed or do you mean unspawning? Thanks

**Comment by tsunamayo** [comment]
Nevermind, actually the issue was to build on an entity that is selected by the tracking cam. It breaks the game, but is is fixed for 20w32a. Thanks!
