### ISSUE TITLE
Ship missing multiple parts (doors, landing gear, rotors, foils, wings) after spawning in, Blueprint shows all those parts still exist

### ISSUE THREAD

**Issue by dpaynex** [tsunamayo/Starship-EVO#2741]
[Blueprints.zip](https://github.com/tsunamayo/Starship-EVO/files/5011412/Blueprints.zip)
### Short Description of the issue:
Issues with spawning in a ship from a blueprint.  My ship looks perfect and intact on the blueprint window.  But when you spawn the ship in, only 60% of the ship spawns in.  The other parts are missing and not just invisible.  You cant interact with any of the missing parts, if you try to add a cube to where this missing part is nothing happens, you cant paint the missing parts either.  however some of the missing parts were rotors with wings on them, when i press the button to activate it, you can hear the invisible rotors moving.

Upon further inspection, it appears that whats missing, is Any part of the ship that was attached via a mechanism (rotor/rail/hinge/etc).  Those parts show up in the blueprint image, but when spawned in, all the parts attached to a mechanism do not load in.
...

### Steps to reproduce the issue:
Select ship starter cube, use it, spawn in blueprint of ship
...

### Environment
- Starship EVO version: Early Access 20w31a
- Graphics Card: 2080 super

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Blueprint https://imgur.com/3eSrISJ
Spawned Ship (missing wings, doors, foils, hatches, landing gear, all of which the blueprint shows) 
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5011396/output_log.txt)
 https://imgur.com/46n0uTP

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by dpaynex** [comment]
Update:  Last night I tried multiple restarts, a full reboot, even a new saved game and no matter what when respawning thr ship, it was still broken and all parts attatched to mechanisms were still missing.

This morning I load up the previous saved game, and the ship is completely fixed all on it's own.  All the parts are back, all the mechanisms are back, and all the logic is working.

I didnt make any changes to my install or computer and didnt do anything this morning that I didnt try last night

**Comment by tsunamayo** [comment]
Okay I was able to reproduce, issue is fixed for 20w32a. Thanks a lot for sending the detailed test case and the blueprint! Cheers
