### ISSUE TITLE
[Bug] ships glitching around 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#2744]
### Short Description of the issue:
After getting out of my lovely hovercraft as i flew away from it, it and other ships began to move a few meters to the side and then teleport back to where they were.
...

### Steps to reproduce the issue:
Drive the hovercraft a few meters then get out and fly a bit back from hovercraft at 3x or 9x speed 
...

### Environment
- Starship EVO version: 20w31a
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:

![ezgif com-optimize](https://user-images.githubusercontent.com/56371294/89137420-e5250380-d4ec-11ea-9ed2-7758f55679ef.gif)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5013384/output_log.txt)

**Comment by TIKIRobo** [comment]
sorry if the GIF is a bit laggy, if you want the video dm at TIKI2000#7759

**Comment by tsunamayo** [comment]
I dont think it is related to the hovercraft but it is coming from another issue. There is plenty of issues in your log file, I have a few aldready, but there is one that I dont understand related to the symmetry. Could you please tell me what you did with the symmetry tool, where did you used it (on a children entity or main entity), did you unspawn the entity on which you had the symmetry or anything else you can remember? Thanks

**Comment by TIKIRobo** [comment]
If I remember correctly I had symmetry on the hovercraft as well as a crane child entity and I didn't despawn it but maybe the fact that I rotated the crane would have made something break.
