### ISSUE TITLE
Beam weapon firing off angle and delayed

### ISSUE THREAD

**Issue by BrickMacklin** [tsunamayo/Starship-EVO#2747]
The new experimental build has introduced this.When firing the beam it fires anywhere but straight. It is also only firing some beams delayed unlike prior. Please see gif below.
https://imgur.com/a/stqzdIq
...
 Fire a beam weapon from a ship

...

### Environment
- Starship EVO version: 20w32a
- Graphics Card: 2080 Ti

**Comment by tsunamayo** [comment]
I see it is because you are firing in 3rd person view and the gimbal try to match. I dont know what to do for that, I guess you expect the beam to fire straight?

**Comment by BrickMacklin** [comment]
@tsunamayo Yes my mistake I did not know about the gimbal before. I am trying to fire forward and that is not a possibility in this view. Also in third person fixed view I cannot fire forward at all. Please see here:
https://imgur.com/a/G9EeZQE

Can we have an option to lock the beam forward? I was hoping to not have to fire this on a gimbal at all.

**Comment by tsunamayo** [comment]
So in third person it will now lock on to forward in 20w32b. I will add a no gimbal setting later on. Thanks!

**Comment by BrickMacklin** [comment]
Thank you Tsuna. Looking forward to the toggle
