### ISSUE TITLE
[BUG-EXPERIMENTAL] Buildings on ring fly into the air

### ISSUE THREAD

**Issue by Rhedd-V** [tsunamayo/Starship-EVO#2750]
### Short Description of the issue:

Buildings on ringworld fly into space on game start. This only happens in the experimental branch. It happens at new game creation, and also upon loading a game where the player is saved near the buildings.

If a pre-experimental game that was saved far from the buildings is loaded in the experimental build, and the player flies to the buildings, they do NOT fly into the air. It only happens when first loading a game.

### Steps to reproduce the issue:

Start a new game in the experimental release, or load an existing game that was saved near the buildings.

### Environment
- Starship EVO version: 20w32a

**Comment by tsunamayo** [comment]
Yes, it is fixed for 20w32b, I am fixing a few more bug and upping the build. Thanks!
