### ISSUE TITLE
[Bug] Piston Sprite

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#2751]
### Short Description of the issue:
When you select a piston (small or large) with the link tool, it displays the sprite code rather than the actual sprite
![image](https://user-images.githubusercontent.com/27857711/89320838-f2232d80-d679-11ea-9cac-b194acf1e922.png)

### Steps to reproduce the issue:
Click on a piston with the link tool in your hand

### Environment
- Starship EVO version: 20w32a
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
Fixed for 20w32b. Thanks!
