### ISSUE TITLE
[Bug] Codex preview bloom

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#2752]
### Short Description of the issue:
The preview in the codex is extremely bright, washing out the colours and making details hard to make out. This also affects thumbnails in the Spawn menu and Workshop uploads

![image](https://user-images.githubusercontent.com/27857711/89330290-f0f8fd00-d687-11ea-8de6-e5e9514ff244.png)

### Steps to reproduce the issue:
Select a ship
Open the codex

### Environment
- Starship EVO version: 20w32a
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
Yes I also noticed this, I keep you posted!

**Comment by tsunamayo** [comment]
Issue fixed for 20w32b. Thanks!
