### ISSUE TITLE
[Bug] Hovercraft Preview does not appear in the Hover Core

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#2753]
### Short Description of the issue:
Previously a diagram of your hovercraft would appear in the Hover Core with arrows showing the centre of mass and thrust as well as hover pod vectors, that preview can no longer be reached by clicking on the eye symbol as it's not in the GUI. I was going to use it here to work out the best place for landing gear.
![image](https://user-images.githubusercontent.com/27857711/89337238-8d280180-d692-11ea-8b2c-5d806dd286e1.png)

While we're here, I suggest enabling the preview by default so it shows up immediately when you open the Hover Core so you don't need to learn to click the eye symbol to show it.

### Steps to reproduce the issue:
Open the Hover Core
...

### Environment
- Starship EVO version: 20w32a
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
Fixed for 20w32b. Thanks!
