### ISSUE TITLE
[Bug (?)] Markings have Mass

### ISSUE THREAD

**Issue by PFSCommissar** [tsunamayo/Starship-EVO#2763]
### Short Description of the issue:
Adding markings adds mass to ships. Not sure if that's intentional or not, but it seems to me that they should be massless, since painting a block without a pattern has no effect on mass. 
...

### Steps to reproduce the issue:
add markings and check ship mass

...

### Environment
- Starship EVO version: 20w32b
- Graphics Card: Geforce GTX 1650

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5048547/output_log.txt)

**Comment by tsunamayo** [comment]
true

**Comment by tsunamayo** [comment]
Issue fixed for 20w34a. Thanks!
