### ISSUE TITLE
[Bug] Unable to delete marking

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#2764]
### Short Description of the issue:
I places down a small rectangle of markings but when I tried to delete them it wouldnt let me
...

### Steps to reproduce the issue:
no idea 
...

### Environment
- Starship EVO version: 20w31a
- Graphics Card: AMD Radeon 5600 XT
![### Additional information:
ezgif com-optimize (1)](https://user-images.githubusercontent.com/56371294/89842564-d8c32b00-db2a-11ea-81a6-a18e68e0c1be.gif)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5054024/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, thanks for booking the issue and the gif. If I want to reproduce I need you blueprint, can you send me the file and an indication of were is the offending decal? Thanks
