### ISSUE TITLE
Suggestion: Reset Turret Position

### ISSUE THREAD

**Issue by 5URG3** [tsunamayo/Starship-EVO#2765]
Currently Turrets remain in the last position they were in when firing. This is annoying if you wish to take screenshots or upload your ship to the WS as it makes things look messy.

I propose either of the following:
A. Turrets return to their original position after combat.
B. A button is added to the ship info screen that resets the turret positions.

**Comment by Rhedd-V** [comment]
I agree with this suggestion 500%!

**Comment by Calvert4096** [comment]
Fixing this would also really help those trying to make retractable turrets.

A possible option "C" would be to allow switching rotor inputs between a turret controller and sequencer so the player can choose and edit the "off" position of each joint.  But I think this would require a change to both how turret controllers and sequencers currently work.

**Comment by tsunamayo** [comment]
Yes this is planned. Thanks

**Comment by tsunamayo** [comment]
Feature was added a while back but lacks polish. Thx
