### ISSUE TITLE
[BUG] Stuck in Ship Controls

### ISSUE THREAD

**Issue by Kadzar** [tsunamayo/Starship-EVO#2768]
### Short Description of the issue:

I entered my ship's yoke to try to stop it moving, and now I can't exit or look around or anything.

### Steps to reproduce the issue:

I entered my ship yoke while it was moving without getting into the seat first. Otherwise I don't know.

### Environment
- Starship EVO version: 20w33a
- Graphics Card: NVIDIA GeForce GTX 1080

### Additional information:

![20200813232546_1](https://user-images.githubusercontent.com/66035211/90214019-edb6ed00-ddbc-11ea-8f2c-6d0bd7960d34.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5072635/output_log.txt)

**Comment by PFSCommissar** [comment]
I have also experienced this same issue today in 20w33a

GeForce GTX 1650
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5079401/output_log.txt)

**Comment by Kadzar** [comment]
> I have also experienced this same issue today in 20w33a
> reverting to non-experimental build fixes the issue
> 
> GeForce GTX 1650
> [output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5079401/output_log.txt)

Yep, that worked. Thanks!

**Comment by tsunamayo** [comment]
What I really need to investigate these kind of issue is your blueprint! If you can send me the faulty ship that would be great. Thanks!

**Comment by tsunamayo** [comment]
@Kadzar also of course reverting to a previous build will work but wont fix the issue, so I still need your blueprint mate ;)

**Comment by Kadzar** [comment]
> @Kadzar also of course reverting to a previous build will work but wont fix the issue, so I still need your blueprint mate ;)

Here you go:
[KSE Harlequin Fighter 1.1.zip](https://github.com/tsunamayo/Starship-EVO/files/5081739/KSE.Harlequin.Fighter.1.1.zip)

**Comment by tsunamayo** [comment]
@Kadzar thats quite a nice opening mechanism... I was able to reproduce and fix the issue. Fix in 20w34a. Thanks!

**Comment by tsunamayo** [comment]
@Kadzar also I love that little guy, can I use it as Pirate? Was is supposed to be part of a faction? It remind me so much of Homeworld and some 80s scifi (Chriss Foss) Cheers

**Comment by Kadzar** [comment]
> @Kadzar also I love that little guy, can I use it as Pirate? Was is supposed to be part of a faction? It remind me so much of Homeworld and some 80s scifi (Chriss Foss) Cheers

I would be honored if you used my ship! And, yeah, it's meant to be part of my personal ship-building corporation whose designs often end up in the hands of pirates (though they deny any responsibility). And Chriss Foss was definitely a big inspiration for this one.
