### ISSUE TITLE
[Bug] Text Modifier Not Working

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Starship-EVO#2772]
### Short Description of the issue:
Modifying the text of a screen doesn't work.
![image](https://user-images.githubusercontent.com/53021785/90303973-409dac80-de70-11ea-9a00-df7901b25e52.png)

![image](https://user-images.githubusercontent.com/53021785/90303979-472c2400-de70-11ea-97fa-bb25768e598b.png)

...

### Steps to reproduce the issue:
- Modify the text size on a screen
- Issue
...

### Environment
- Starship EVO version: 20w33a
- Graphics Card: Integrated Graphics

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5078034/output_log.txt)

**Comment by tsunamayo** [comment]
Indeed, it was linked to the <size=15> you used. Fixed for 20w34a! Cheers mate
