### ISSUE TITLE
[BUG] Improperly Spawned Ship Becomes Infinite Loot Piñata

### ISSUE THREAD

**Issue by Kadzar** [tsunamayo/Starship-EVO#2774]
### Short Description of the issue:

I shot at a ship didn't spawn completely, and it exploded in a sea of Upgrade Chips

### Steps to reproduce the issue:

I spawned in a ship that only had a portion of its blocks showing up, then shot at it, there was some collision sparks, then lag, and I found myself surrounded in a sea of Upgrade Chips, which caused a great deal of lag.

EDIT: I relogged and the lag improved, and it turned out it was more a large trail of Upgrade Chips.

### Environment
- Starship EVO version: 20w33a
- Graphics Card: NVIDIA GeForce GTX 1080

### Additional information:

![20200815215024_1](https://user-images.githubusercontent.com/66035211/90325576-fdf8d480-df42-11ea-85d2-152ac16bb159.jpg)
![20200815215125_1](https://user-images.githubusercontent.com/66035211/90325577-03561f00-df43-11ea-8898-d32e85fe64ef.jpg)

[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/5079903/output_log.zip)

**Comment by tsunamayo** [comment]
@Kadzar nice view ;) Do oyu have to faulty ship blueprint so I can try to reproduce the issue? Thanks

**Comment by Kadzar** [comment]
I believe it was this one from the workshop.
https://steamcommunity.com/sharedfiles/filedetails/?id=2144972582

**Comment by tsunamayo** [comment]
Okay the ship is loading fine on my side, so I cant reproduce your issue. Looking at your log there is really tons of issues out there. Do you recall anything particular before loading that ship?
Once the game start to act erratically it is best to exit to desktop straight away and book a bug, as all that happens after the first issue is not really relevant. Cheers

**Comment by Kadzar** [comment]
> Once the game start to act erratically it is best to exit to desktop straight away and book a bug, as all that happens after the first issue is not really relevant. Cheers

Okay, that's good to know. I'll keep that in mind for the future.
