### ISSUE TITLE
SEVO turrets dissapearing

### ISSUE THREAD

**Issue by matejkar** [tsunamayo/Starship-EVO#2777]
### Short Description of the issue:
Same story as my previous post about a glitch where i cannot place a block, now that issue i have not seen again and i accidently started a new character therefore removing that output log.
Now i come with another issue, regarding the same 300m long ship i talked about before, and all of its turrets dissapeared, those who were set up to work with a turret computer and those who did not (yet), but now i load into the game and the turrets were gone, only thing left were the rotors which had different textures. After checking on the turrets i set up to work, i found out that the links to them were completely out of place, but when i checked out the ends where the link leads, nothing there.
This time, i got the output log, and some screenshots.
In case tsunamayo sees this, i will say that i cannot send the ship file, as for some reason it doesnt support .mps files.
However, i will be finishing the ship soon, and posting it on the workshop so its free for everyone to download

...

### Steps to reproduce the issue:
In my case, i had built a turret and set it up, added the computer and linked all the stuff. Then i piloted the ship, and the turret fired. After leaving the ship the working turrets and the not yet working were in place like they should be. I saved my blueprint a few times (now its possible that saving multiple times frequently has an issue, but i dont know about it), and left the world. Later i reenter hoping to work on the ship, and i find out the turrets are missing, all but the base rotor (even the hinge is missing).
Its possible the people dont get the issue, but here are some screenshots:

...

### Environment
- Starship EVO version: 20w33a
- Graphics Card: Nvidia Geforce GTX 1060Ti
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5081338/output_log.txt)
![20200816222551_1](https://user-images.githubusercontent.com/69653738/90343472-e2f49600-e010-11ea-9f49-774b4ee3cd15.jpg)
![20200816222610_1](https://user-images.githubusercontent.com/69653738/90343476-eab43a80-e010-11ea-937b-f43acb7fa4b5.jpg)

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by matejkar** [comment]
[hive class carrier.zip](https://github.com/tsunamayo/Starship-EVO/files/5081347/hive.class.carrier.zip)
never mind, got the blueprint zipped

**Comment by matejkar** [comment]
![20200816224604_1](https://user-images.githubusercontent.com/69653738/90343586-4a5f1580-e012-11ea-89c8-3711b3ad47f6.jpg)
started a new world again, still happens

**Comment by matejkar** [comment]
another weird thing, as i pilot the ship now, i noticed some of the missing turrets that were set up actually still fire. I cannot really screenshot it as it is like a couple of frames the time the laser leaves the screen

**Comment by matejkar** [comment]
![20200816225617_1](https://user-images.githubusercontent.com/69653738/90343749-b5f5b280-e013-11ea-9b1b-339af853f91a.jpg)
kinda did it, there is the turret base, no turret, and above is the dual laser it fired

**Comment by matejkar** [comment]
![image](https://user-images.githubusercontent.com/69653738/90344016-21408400-e016-11ea-99c3-a8da6b4de8bc.png)
interestingly enough, upon looking at the ship preview, the turrets are there. That means there is a problem ingame and not a blueprint issue (i've circled where the turrets are)

**Comment by tsunamayo** [comment]
Thanks for the blueprint and the log, I keep you posted ;)

**Comment by tsunamayo** [comment]
Issue fixed for 20w34a. Thanks for that strong test case. Cheers
