### ISSUE TITLE
[BUG] Can No Longer Paint Certain Area of Ship

### ISSUE THREAD

**Issue by Kadzar** [tsunamayo/Starship-EVO#2787]
### Short Description of the issue:

I have a ship that has a certain area that I can no longer paint, even though I painted it before, and even after removing and replacing the bricks.

### Steps to reproduce the issue:

I'll attach the blueprint. It's the underside portside area that's unpainted.

EDIT: Checking, it seems that the opposite side is also affected.

### Environment
- Starship EVO version: 20w34a
- Graphics Card: NVIDIA GeForce GTX 1080

### Additional information:

![20200819212626_1](https://user-images.githubusercontent.com/66035211/90710464-15e29800-e264-11ea-8496-3daaa7319a6e.jpg)

[Prong Fighter mk2 v 0.8.1.zip](https://github.com/tsunamayo/Starship-EVO/files/5100356/Prong.Fighter.mk2.v.0.8.1.zip)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5100358/output_log.txt)

**Comment by Ezarhon** [comment]
You may have a stencil there, try equiping a stencil pattern, right-click and see if the bare patch goes away.

**Comment by Kadzar** [comment]
> You may have a stencil there, try equiping a stencil pattern, right-click and see if the bare patch goes away.

That actually seems to have worked, which is weird, because I don't really recall putting a stencil there.

**Comment by tsunamayo** [comment]
I think that what is confusing regarding the stencil is that for stencil with a non square shape you will always paint them even if you are not targeting then (only their bounding box). This still needs a fix.

**Comment by Kadzar** [comment]
Okay, looking at the previous version from before I removed the stencil, it seems the stencil is actually part of the interior cockpit, attached to a brick that isn't one of the bricks affected.
![20200820180522_1](https://user-images.githubusercontent.com/66035211/90834776-9f4fa400-e310-11ea-980b-5d1cf6acf837.jpg)The bricks affected
![20200820180530_1](https://user-images.githubusercontent.com/66035211/90834794-aaa2cf80-e310-11ea-970a-e946f317f38e.jpg)
The interior cockpit with stencil on a different brick.

**Comment by Rhedd-V** [comment]
This happens to me a LOT. Decals (stencils) often seem to have very large bounding boxes, and sometimes an interior decal will color instead of the ship exterior, etc. Place a large diagonal decal and huge areas of the ship will become unpaintable. 

Glad to hear this will be fixed at some point.
