### ISSUE TITLE
[SUGGESTION] Choosing a blueprint for workshop upload

### ISSUE THREAD

**Issue by OverSavior** [tsunamayo/Starship-EVO#2788]
I think it would be great if we could choose a specific blueprint in our library to update our own uploads. I still have this fighter build of mine that I uploaded some time ago into WS, then the sticker fix happened and its screenshot on WS page doesn't correspond to the actual look anymore. Although, I can't seem to update it, becuase the original entity was deleted and if I just spawn it as the blueprint I saved there's no option to update the WS file.

I suggest the following: when the player spawns a ship that is a WS blueprint which they uploaded (meaning they subscribed to it), there can be something like a separate "update upload" button which, when pressed, lets the player choose a certain blueprint from their entire library to replace the current WS blueprint with.

**Comment by tsunamayo** [comment]
Yes this was suggested and is planned. Thanks!

**Comment by tsunamayo** [comment]
Implemented for 20w40c. Thanks!
