### ISSUE TITLE
[BUG] Game freezes whenever I'm in first person mode

### ISSUE THREAD

**Issue by ItsDimple** [tsunamayo/Starship-EVO#2791]
### Short Description of the issue:

Everything works fine unless I'm in first person, all I can do is access the inventory/toolbar, I can't move or build or look around, the game is practically frozen except for the menus. Sometimes it even crashes upon entering first person.

### Steps to reproduce the issue:

1. Load in with any character at any location in the game
2. The game is initially frozen because first person is the default setting
3. Press F4 to unfreeze/freeze

### Environment
- Starship EVO version: 20w32b
- Graphics Card: NVIDIA GeForce GTX 1050ti

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5103222/output_log.txt)

![Screenshot (165)](https://user-images.githubusercontent.com/69971510/90774043-242dc400-e2f7-11ea-9963-41d9ed5a93fd.png)
![Screenshot (166)](https://user-images.githubusercontent.com/69971510/90773872-dca73800-e2f6-11ea-9ef9-c263837f68fc.png)
![Screenshot (167)](https://user-images.githubusercontent.com/69971510/90773875-ddd86500-e2f6-11ea-92b3-55d86293cf91.png)

**Comment by tsunamayo** [comment]
@ItsDimple Thanks for booking this issue. I see some error related to the head bobbing setting in graphics options. Is this something you updated during your play session or not at all? Thanks

**Comment by ItsDimple** [comment]
@tsunamayo Hi, thanks, I set my head bobbing to 100%, it didn't display anything before I changed it... But that seems to have fixed the issue!

**Comment by tsunamayo** [comment]
Okay I made some fixed to the head booking UI script, it should have taken care of this. For 20w25b. Thanks!
