### ISSUE TITLE
Steam forums need some attention

### ISSUE THREAD

**Issue by AlienXtream** [tsunamayo/Starship-EVO#2792]
the game has started to gain some attention from new people and many of them are either unaware of or dont want to use github. i know you tend to be most active here but now that the audience is growing a more reliable presence on the steam forums is a must. whether that means you do it yourself or promote some of the discord moderators. at the bare minimum a pinned post regarding the state of the game and where to go to post bug reports and find the discord channel. i know they are in the bottom right of the main menu of the game but a lot of people dont seem to know that. 
feel free to close this "issue" when you've seen it, i just wanted to make you aware of the situation :)

**Comment by AlienXtream** [comment]
ok. the player numbers are ramping up and its getting tiresome answering the same things (generally "plz post bugs on github" and such). if you, myself or someone else makes a FAQ and bug report guide would you pin it for users to see?

also, here is some info i found relating to setting up steam forums. it supports french language too if you are more comfortable reading that : https://partner.steamgames.com/doc/features/community#discussions

**Comment by tsunamayo** [comment]
@AlienXtream sorry mate yes I will do this asap, I was off a few days and rushing on 10 things before leaving.

**Comment by AlienXtream** [comment]
hey, no worries. you are just one person working on a very ambitious project and to top things off life itself is kinda important from what ive heard :P 

dont stress about it too much. we know you are working hard (and as ive mentioned a few times before a little TOO hard imo. dont burn yourself out man!), thats why i shared those links. it wasnt to say "hurry up" it was to say "i know you're busy so heres something that might help a bit" :)

**Comment by tsunamayo** [comment]
@AlienXtream okay mate you are now a mod ;) You are doing an amazing job, discussion can get quite heated but you are always lowering the heat.
I made a few sticky thread also. I will do a post to watch for other mods.
Cheers
