### ISSUE TITLE
[Test] Brick benchmark on low end PC

### ISSUE THREAD

**Issue by ultrak2k** [tsunamayo/Starship-EVO#2796]
### Environment
- Starship EVO version: 20w34a (EXP)
- Graphics Card:  Nvidia 840m
(Other specs include 16gb of ram, and an i7 5600 2.59ghz)

So, I have a 31.5 thousand brick build, all bricks contained in a volume of 50x50x50 (approx).
![20200824120633_1](https://user-images.githubusercontent.com/43084360/90992285-c1903d00-e602-11ea-89c0-a5c3a73b5266.jpg)
![20200819181339_1](https://user-images.githubusercontent.com/43084360/90992330-18961200-e603-11ea-8f48-8dd7ce3c183e.jpg)

I have a low end computer, which I use for school, with a very outdated graphics card, however, normally I get 20fps playing the game and staring at empty space. My FPS drops to 10-12 when looking at my mansion bridge build head on, which IMO isn't bad for 31k bricks .Just wanted to post this, as it seems that bricks aren't too heavy on performance relatively speaking

Blueprint:
[Scarlet Devil Mansion.zip](https://github.com/tsunamayo/Starship-EVO/files/5115218/Scarlet.Devil.Mansion.zip)

**Comment by Aiwii** [comment]
#2793

**Comment by ultrak2k** [comment]
whoop, didnt mean to post this seperately, but, oh well

**Comment by Whackjob** [comment]
Now, that's pretty.

**Comment by tsunamayo** [comment]
Thanks a lot for this, very useful!
