### ISSUE TITLE
[BUG]Medbay sprite on item display name is sprite-1

### ISSUE THREAD

**Issue by ultrak2k** [tsunamayo/Starship-EVO#2799]
### Short Description of the issue:
Get out a medbay, the name is wrong - sprite is wrong

### Steps to reproduce the issue:
Open codex
Get medbay
Observe item name on left

![20200824194540_2](https://user-images.githubusercontent.com/43084360/91017470-667e3a80-e642-11ea-82a8-e8c0a2dda60c.jpg)

**Comment by tsunamayo** [comment]
Indeed, issue fixed for 20w35b. Thanks!
