### ISSUE TITLE
[Bug] Repeatedly Clicking 'Scan' in a medbay stacks the SFX

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Starship-EVO#2802]
### Short Description of the issue:
When scan is repeatedly clicked the sfx stacks
...

### Steps to reproduce the issue:
- Spam Click scan in a medbay
- Issue
...

### Environment
- Starship EVO version: 20w35a
- Graphics Card: Integrated Graphics

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5120479/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, issue fixed for 20w35b. Thanks as always!
