### ISSUE TITLE
[UNPLAYABLE BUG] Blocks and other graphical assets Invisible/flickering 

### ISSUE THREAD

**Issue by UnicornGit** [tsunamayo/Starship-EVO#2806]
### Short Description of the issue:

.In borderless and windowed mode certain graphical assets all blocks and grass are invisible, in fullscreen same graphical assets flicker rapidly

### Steps to reproduce the issue:

Start Game and load any world in borderless windowed or fullscreen 

### Environment
- Starship EVO version: 20w32b
- Graphics Card: AMD R9 295X2 

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5126048/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, sorry to hear that. Could you make sure your GFX drivers are up to date? Thanks

**Comment by UnicornGit** [comment]
It was a driver issue I updated my graphics and it works now

**Comment by tsunamayo** [comment]
@UnicornGit Great to hear that! Cheers
