### ISSUE TITLE
Broken hinge

### ISSUE THREAD

**Issue by Leha44581** [tsunamayo/Starship-EVO#2809]
### Short Description of the issue:

Texture bug 

### Steps to reproduce the issue:

Place a hinge
Observe

### Environment
- Starship EVO version: 20w32b
- Graphics Card: gtx1070

### Additional information:

[output_log — копия.zip](https://github.com/tsunamayo/Starship-EVO/files/5131344/output_log.zip)
![86deafb5ca](https://user-images.githubusercontent.com/70238465/91335638-58165700-e7d9-11ea-8bfd-b9bc216e35b7.jpg)
![2919fc0c0c](https://user-images.githubusercontent.com/70238465/91335640-59478400-e7d9-11ea-8da5-c0e6f1c2137d.jpg)
![1736b9478a](https://user-images.githubusercontent.com/70238465/91335642-59478400-e7d9-11ea-9882-b99000b3529b.jpg)

**Comment by Leha44581** [comment]
The ship is destroyed, but i still can build on it, also hinges rotators and pistons still work but no texture changes
[starship-evo-20200826-20255505_VM5zkGst_eHIe.zip](https://github.com/tsunamayo/Starship-EVO/files/5131375/starship-evo-20200826-20255505_VM5zkGst_eHIe.zip)

**Comment by Leha44581** [comment]
For some reason im able to save destroyed ship as a blueprint and i still can pilot it and enter lightcruise but it don't moves at all

**Comment by tsunamayo** [comment]
@Leha44581 hi, thanks for being active over here but for some reason I cant open any of your zip file... What are you using to zip them? Thanks

**Comment by Leha44581** [comment]
I use winrar and then just convert it into .zip and for me it works fine
