### ISSUE TITLE
[BUG] round stickers become square at distance 

### ISSUE THREAD

**Issue by Womble-TC** [tsunamayo/Starship-EVO#2813]
### Short Description of the issue:
Round stickers appear square at a distance, a swell as some other weird visual effects on other stickers.

Close: 
![image](https://user-images.githubusercontent.com/29961381/91356067-f6f58000-e7e6-11ea-95bf-1afe99cfc1b3.png)

Far away:
![image](https://user-images.githubusercontent.com/29961381/91356097-0379d880-e7e7-11ea-8dd5-31b053502c30.png)
(mostly on the eyes)

### Environment
- Starship EVO version: 20w32b
- Graphics Card: GTX 970

Here is the blueprint if you want to look at it
[hombre.zip](https://github.com/tsunamayo/Starship-EVO/files/5132751/hombre.zip)
![image](https://user-images.githubusercontent.com/29961381/91356360-72efc800-e7e7-11ea-87e4-b53001db2d75.png)

**Comment by glorbo703** [comment]
hummus

**Comment by ZachZent** [comment]
Was this just an excuse to show off your sticker work? Because if so, damn those are nice

**Comment by Womble-TC** [comment]
This was about 50% of the reason yes

**Comment by tsunamayo** [comment]
omg I need a donut now

**Comment by tsunamayo** [comment]
btw I check for the issue, my guess it is a mip map issue. Amazing work, I have no idea how you made those curvy lines.
right now there is some issue with painting the right sticker as it wont check if the texture is actually hit, it must have been so painful... Cheers

**Comment by tsunamayo** [comment]
Fixed in recent updates.
