### ISSUE TITLE
Hull blocks on hinges don't count towards heat reduction.

### ISSUE THREAD

**Issue by gdumler** [tsunamayo/Starship-EVO#2816]
### Short Description of the issue:
All blocks on hinges don't count towards heat reduction. This is a problem when your ship is consisted of movable parts on hinges. 
...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Yes thats a bug!

**Comment by tsunamayo** [comment]
Okay I have checked, are you talking about surface heat? Hull heat dissipation was fine. Thanks
