### ISSUE TITLE
Ship Shields and overlapping [Suggestion]

### ISSUE THREAD

**Issue by Drillz007** [tsunamayo/Starship-EVO#2818]
Currently shield cover the entire main entity of a ship but if a child entity where to extend passed this it would exit the shield and not be covered
Previously we had the issue of shield stacking or shields being used within one another abusing the coverage and recharge rates but would allow us to cover smaller things like turrets with there own shields

my suggestion is to return to the previous style of multiple shields but have all shields on one entity work off the same refresh time this would allow things like turrets to have there own separate little shields and protection without breaking combat engagements due to refresh rates the time this would be based on the slowest shield that the ship has and would have to count down in order to begin recharging all the shields if any of the shields took damage it would reset the counter 
setting the shields up like this would allow for different shapes and designs to be fully shielded this would not give any kind of advantage
(in an ideal situation the shield would also not have an inner layer and would just bulge out from the main without having any bubble inside)

another option would be to have the shield grow and stretch about to just cover over the other entities on the ship i feel like this would be very complicated to do though 

here is ms paint illustration cause why not
![Untitled11111111111111111111111111111111111111](https://user-images.githubusercontent.com/63330810/91377065-2951ae00-e7e4-11ea-83e5-d92ce51c6d50.png)

**Comment by tsunamayo** [comment]
Hi, no actually what we have currently is your Possible graph. On what version are you? Thanks

**Comment by Drillz007** [comment]
Well let me just take a second to thank you for the amazing work you have been doing i have been back and forth with playing the game and it has been a real pleasure seeing your work take shape so quickly and cleanly...

that being said i did find a "bug" where the shield does not return to size when blocks are removed the shield coverage just keep growing to accommodate for the new shapes (is this intentional)
![image](https://user-images.githubusercontent.com/63330810/91663005-b0847780-eaab-11ea-8272-1484aed15a1e.png)
the image on the left is the ships center before i added some random bricks the image on the right side is after i added and removed the bricks it has been pushed off to the bottom left permanently and now the shield is offset

**Comment by tsunamayo** [comment]
@Drillz007 it is not sensitive to damage, but I guess yes it is a bug! Let me check that!

**Comment by tsunamayo** [comment]
Issue fixed for 20w37a. Thanks!
