### ISSUE TITLE
[BUG] Ships Rubberbanding Away

### ISSUE THREAD

**Issue by Kadzar** [tsunamayo/Starship-EVO#2819]
### Short Description of the issue:

An aggressive shuttle hit my lineup of ships in space and knocked them away, and, after quitting to title to try to make the shuttle despawn and returning, all the ships rubberbanded away from me.

### Steps to reproduce the issue:

Line up some ships and hit them with a shuttle?

### Environment
- Starship EVO version: 20w35a
- Graphics Card: NVIDIA GeForce GTX 1080

### Additional information:

[Starship EVO 2020-08-27 00-46-05.zip](https://github.com/tsunamayo/Starship-EVO/files/5134400/Starship.EVO.2020-08-27.00-46-05.zip)
Video of the rubberbanding in effect

[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/5134403/output_log.zip)

**Comment by tsunamayo** [comment]
@Kadzar that is a weird bug. Is the log file from that session? Are you still reproducing that? Thanks

**Comment by Kadzar** [comment]
Yeah, the log file should be from that session. And it stopped after a restart.
