### ISSUE TITLE
Visual Issue Bug (2 bugs with similar issue)

### ISSUE THREAD

**Issue by logan15105** [tsunamayo/Starship-EVO#2822]
### Short Description of the issue:
Bug 1: Blocks will visually disappear but still be selectable with only the outline of where the texture used to be. Example: https://prnt.sc/u7485a

Bug 2: https://prnt.sc/u74gvc
The block after being deleted left behind an entity (the top of the rotator block where you would place things on) And is unable to be deleted.
...

### Steps to reproduce the issue:

When I was placing same blocks within close proximity of one another, some times this bug occurs. Notably with small thrusters and small rotators. 
...

### Environment
- Starship EVO version:  Current stable non experimental version of the game on 8/27/2020 at 5:45pm EST
- Graphics Card: Nvidia 1050 on Acer Nitro 5 laptop purchased from bestbuy (IIrc some manuf. have slightly diff. cards or setups on their systems.

### Additional information:

The bugs occur within a few hours of playing the game. I don't believe it to be a memory leak issue but rather something of a code hiccup or rendering problem. Though i'm pretty ignorant of these things

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

-----------------------------------------------------------------------------------------------------------------------------------

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5138973/output_log.txt)

**Comment by tsunamayo** [comment]
Hi thanks for booking the bug. There is quite a few issues in this log. Did you used symmetry? Thanks

**Comment by tsunamayo** [comment]
@logan15105 Hi, could you please send me the Capital Ship you were working on I want to check if there is anything wrong with it. Did you manually despawned entity? Thanks

**Comment by li3** [comment]
I've seen this one repeatedly today. I normally see it after removing a block. Exiting to the title screen then reloading fixes the problem. I tried turning off occlusion culling in the debug menu (since it felt like the entity just wasn't being rendered) but that had no effect (on frequency of occurrence or already missing blocks). I'll see if I can come up with a way to reproduce.
