### ISSUE TITLE
ship graphical glitching

### ISSUE THREAD

**Issue by nukeguard** [tsunamayo/Starship-EVO#2826]
### Short Description of the issue:

Graphical jitter while flying, normal flight, boost, and lightcruise
In lightspeed thrust effects are noticeably attached to camera movement and move around separately from the ship while in lightcruise

### Steps to reproduce the issue:

not really sure how to repro this issue as it still happens in this save even after restarting game

after a few reloads now I can't get the glitch to happen again

### Environment
- Starship EVO version: 20w32b
- Graphics Card: gtx1080

### Additional information:

https://streamable.com/zse6gk

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5139870/output_log.txt)

**Comment by tsunamayo** [comment]
Big thanks for the video it is really nice to see what was happening. Is this the log from the session where you had issues? Thanks

**Comment by nukeguard** [comment]
sorry, long reply, yes that should have been log from when was happening, i didn't start game again so log did not get overwritten
