### ISSUE TITLE
Issues to launch game

### ISSUE THREAD

**Issue by IymriI** [tsunamayo/Starship-EVO#2829]
### Short Description of the issue:
Greetings , ive stumble across an problem after i bought the game on steam , once i try launch the game it seams to be out of "frame". i cant really explain it better then having sound seeing the curser turn into the game curser but having nothing els then sound , its like the game itself and its window is invisible i can hear sound when i move the curser so i think the game start normal just with the issue of not beeing able to see anything but the background of my home screen.
Also when i deactivate my Geforce card over the hardware manager the game just run.

### Environment
- Starship EVO version: recent
- Graphics Card: Nvidia gtx 970m

### Additional information:

Iam running this game onna Laptop brand Acer Predator G9 791

Specs.
Win 10 64bit

CPU:
Intel i7 6700HQ

GPU:
Intel HD 530 onboard
Nvidia geforce GTX 970m

**Comment by tsunamayo** [comment]
Hi, do you confirm you only have a single screen? 
Also could you make sure your drivers are up to date? Thanks

**Comment by tsunamayo** [comment]
@IymriI so it seems to be a problem with ACER laptop:
https://github.com/tsunamayo/Starship-EVO/issues/2541
The way this user fixed the issue was to download an older ACER driver...
Thanks
