### ISSUE TITLE
Logic Gate: AND not respecting Timer input in latest Experimental Update

### ISSUE THREAD

**Issue by SangurianSoul** [tsunamayo/Starship-EVO#2830]
### Short Description of the issue:
Building a "Reversing Sequence" Logic setup. Outputs go in a certain order, then will turn them off in the reverse order. Im sending attached picture to better visualize.

Outputs happen simultaneously, even though one of the signals the AND Logic Gate is receiving is on a 10 second timer. The reverse order happens in the correct sequence just fine. So the problem is in the AND Gate.

Everything works just fine in the 'stable' branch

### Steps to reproduce the issue:
Will attach picture to show.

### Environment
- Starship EVO version: 20w34a (experimental)
- Graphics Card: GeForce GTX 1060

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5142526/output_log.txt)
![hbs3I33](https://user-images.githubusercontent.com/6137742/91577729-23a8b500-e917-11ea-833f-96c84d5528f7.png)

**Comment by tsunamayo** [comment]
Okay, not sure what is happening. Btw from what I can recall you can do a flip flop with just a single timer... I guess this is that feedback loop that is causing the issue. I have made some change so you cant make the logic system crash. Cheers

**Comment by tsunamayo** [comment]
@SangurianSoul Hi could you please send me a blueprint? I am not sure of your timings. thanks!

**Comment by tsunamayo** [comment]
I think it will be fixed in 20w41a. Thanks
