### ISSUE TITLE
Seamless Small Block

### ISSUE THREAD

**Issue by MrNobodyX3** [tsunamayo/Starship-EVO#2831]
Small blocks should appear seamless next others just like the large blocks appear next to other large blocks. We have the decals if we want the detail there.

**Comment by ZachZent** [comment]
The problem with that is the small blocks/bricks don't work like the large blocks. Because of offsetting a few other things, the brick boarders can not connect like the blocks

**Comment by tsunamayo** [comment]
So yes it is a old complain. It remind me I still need to make smaller border. As ZachZent said these are a completely different tech. Also I need the border for various reasons, so you understand what to delete and how the thing is built, and also to force player to use stretch as much as they can. Cheers!

**Comment by ProPeach** [comment]
Looking forward to a smaller border! :)
