### ISSUE TITLE
[BUG] Unable to see window textures, screens, grate textures, etc.

### ISSUE THREAD

**Issue by wick-3d** [tsunamayo/Starship-EVO#2832]
### Short Description of the issue:
I cant see the glass parts of windows, i cant see screens, but i can see the text ON the screens, I cant see the grate part of grates, and I cant see a lot of glass blocks at all. This issue didn't happen until a recent update - I've been on hiatus for a few updates.
I've tried verifying game files, reinstalling, and even switching to experimental. Nothing worked.

Edit: I can also not see the green ghost blocks when the repair tool is equipped.
...

### Steps to reproduce the issue:
Unknown
...

### Environment
- Starship EVO version: early-access 20w35a / vanilla current
- Graphics Card: GTX 760

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
https://cdn.discordapp.com/attachments/342383722185883648/749001764765827087/unknown.png
https://cdn.discordapp.com/attachments/342383722185883648/749003549463281835/unknown.png
https://media.discordapp.net/attachments/342383722185883648/749003935414485002/unknown.png?width=1202&height=676

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\` 
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5144073/output_log.txt)

**Comment by tsunamayo** [comment]
Yes sorry it is an issue with the new rendering tech on old GFX card. I will fix it very soon, I keep you posted! Thanks

**Comment by wick-3d** [comment]
I figured it would be that... Thanks for the quick reply.

**Comment by tsunamayo** [comment]
So this will be fixed for 20w36a. The fix will be up soon! Thanks
