### ISSUE TITLE
Unable to join a multiplayer server

### ISSUE THREAD

**Issue by Rocinantus** [tsunamayo/Starship-EVO#2835]
### Short Description of the issue:
Trying to click join on a multiplayer game will not work, pressing the button makes nothing happen
...

### Steps to reproduce the issue:
1:have a friend set up a server 2:try joining shortly after server is opened to multiplayer
...

### Environment
- Starship EVO version: 20w35a
- Graphics Card: radeon rx580

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Hi, okay lets fix this!
Did you opened and forwarded port TPC and UDP 7777? Thanks

**Comment by Rocinantus** [comment]
> Hi, okay lets fix this!
> Did you opened and forwarded port TPC and UDP 7777? Thanks

Thanks for the info, that really helped, thank you.

**Comment by tsunamayo** [comment]
Ok great, thanks!
