### ISSUE TITLE
[Suggestion] Hotkey Gate lightcruise option

### ISSUE THREAD

**Issue by Monstertruck-swe** [tsunamayo/Starship-EVO#2839]
### Short Description of the suggestion:

Add the "lightcruise" option to the Hotkey Gate block to trigger logic when lightcruise successfully actives/deactivates.
For player and AI ships to use if wanted.

![feedback01](https://user-images.githubusercontent.com/70446055/91642729-f4389c00-ea2d-11ea-9c32-a706682131c2.png)

### Additional information:

Working the same way as logic for landing gears, except its for going into lightcruise. Think EVE Online and the ships sometimes having moving parts that is triggered by the ship going into warp. It could be used for anything during lightcruise activation.

Antennas folding, weapon hardpoint hiding, doors locking, changing interior lights etc.
And when ships exit lightcruise, they all revert to normal again. It could add a nice touch to the atmosphere of lightcruise, yet be very simple to set up for users.

**Comment by tsunamayo** [comment]
Yes this was on the to-do list, it will a much bigger refactor where you will have to link the new hotkey to another system or command/yoke, then pick up an event linked to that system. Cheers

**Comment by TheShadowSage** [comment]
I don't suppose it would be possible to assign multiple hotkeys would there? I've got over 12 buttons on my mouse I wanna try out with >:D

**Comment by tsunamayo** [comment]
@Monstertruck-swe Actually we have this since a long time now! Cheers
