### ISSUE TITLE
[BUG] improper laser colo(u)r 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#2840]
### Short Description of the issue:
When I painted a laser white it shot red lasers 
...

### Steps to reproduce the issue:
Paint a laser white 
fire 
observe 

...

### Environment
- Starship EVO version: 20w35a
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
I was in the 

experimental branch 
![ezgif com-optimize (2)](https://user-images.githubusercontent.com/56371294/91642988-62f10780-e9e4-11ea-91fd-d634e62cc5c3.gif)

My output log is siting at 57 MB so I cant upload it sorry

**Comment by tsunamayo** [comment]
Okay, I am still interested in that log file, not for the color issue but to fix anything that might be bugged in it! If you zip it how large it is? Thanks

**Comment by TIKIRobo** [comment]
@tsunamayo  ok there we go github was not liking what I was doing but here it is


[output_log (2).zip](https://github.com/tsunamayo/Starship-EVO/files/5146958/output_log.2.zip)

**Comment by tsunamayo** [comment]
Issue fixed for 20w36c. Thanks!
