### ISSUE TITLE
[SUGGESTION] Primer "Paint" for block protection and added effects.

### ISSUE THREAD

**Issue by Hecateus** [tsunamayo/Starship-EVO#2846]
been trying this game and listening to the dev logs.  my key immediate frustration was with the accidental removal of blocks, esp. tutorial room floors.  I have also been thinking about features which so far don't appear to be a current part of the game, and I think I have a 'relatively' simple solution to suggest which won't add to the challenge of minimizing blocks and bricks.

A Primer Paint; it doesn't have to be primer white btw, though some outward color would be contextually appropriate.  Whose key feature is to Block the ability to remove a brick/block via the right mouse button.  This would help lock in features and reduce the stress of maybe ruining a build by accident.  The block can still be freely damaged from weapons fire and other things.  The primary paint can still readily removed with the Paint selection tool.

Other secondary effects is where the Primary Paints/Textures/decals can get interesting.  What I imagine so far:
1.  Radiator Black.  Improved Heat dissipation at the cost reduced armor effect.
2.  Angled Gravity.  when present in or near enough to an active gravity field, the field changes direction to be at-the-normal to the plane of the painted block/brick face.  Making for some interesting zones.
3.  Armor.  Improved defense at the expense of mass; different types of armor have different bonuses and penalties.
4.  Stealth Black.  Absorbs energies, appearing black...if proper stealth is ever implemented, this might be a good basis.  Drawback is it hurts Hull Heat Dissipation.
5.  Active Camouflage.  An advanced late game option, needs massive computing power, and higher attention to heat dissipation/absorption.
6.  Sealant.  Seals a room from atmosphere leaks.
7.  Nanite Self repair.  For those hard to reach ares which cannot be allowed to fail in combat.
8.  Static electrical.  Can shock unwary boarders.

I will probably think of more later.

**Comment by tsunamayo** [comment]
Hi, okay that is an interesting suggestion that goes some place:
I do agree 100% it is a problem, but I think it needs a different solution.
1) Faction / player build lock. That way the player wont be able to destroy the starting building, or other player your ship in multiplayer (weapon damage is excluded like you pointed out)
2) Some local override block. Like you can still build in a given zone.
3) Some confirmation for large block / children entity mechanism.

Then regarding your other suggestion that also interesting but having them linked to paint would prove complicated.
We have gravity modifier block already. Armor tier / heat tier will come from different hull. If stealth come one day it will also be either a specific hull block or system. Same for self repair. Sealant will be different mechanic, but all hull block will be sealed (but not smaller brick!).
Cheers

**Comment by Hecateus** [comment]
Sounds good, though I should clarify the gravity paint notion.  The idea is not to replace the Gravity field, but to allow it to not be tied solely to the x y z axis directions.  Perhaps a different Hull in the future then.

**Comment by Hecateus** [comment]
Much simpler suggestion: put a timer wheel on right-click, much like the timer wheel on the [F] keyboard command

**Comment by tsunamayo** [comment]
@Hecateus yes it might be a possibility for countering accidental delete, at least for large / logic gate.
