### ISSUE TITLE
[BUG] Cannot use, move, or view new chips.

### ISSUE THREAD

**Issue by wick-3d** [tsunamayo/Starship-EVO#2847]
### Short Description of the issue:
I am unable to hover over, move, click on, or see newly acquired chips. I have tried restarting twice, verifying files, and re-spawning the ship.
...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: early-access 20w35a
- Graphics Card: GTX 760

### Additional information:
What I see: https://media.discordapp.net/attachments/271723356795961345/749533452210012191/unknown.png?width=1204&height=677
_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5146469/output_log.txt)

**Comment by tsunamayo** [comment]
@wick-3d Hi, could you please send me your blueprint? Is it happening with all your blueprint? Thanks

**Comment by wick-3d** [comment]
I will check if it is happening with other blueprints. 
In the meantime, here is a zipped folder containing the blueprint for the current ship in question.
[Chip Error Ship.zip](https://github.com/tsunamayo/Starship-EVO/files/5146509/Chip.Error.Ship.zip)

**Comment by tsunamayo** [comment]
Hi, issue is fixed for 20w36b. Thanks!
