### ISSUE TITLE
[Bug] Invisable codex icons

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#2855]
![](https://cdn.discordapp.com/attachments/406664114249793536/749859732537475173/unknown.png)

Only on the sticker page, doesn't seem to be a problem on any other page

**Comment by ZachZent** [comment]
Same issue in the hotbar

**Comment by ultrak2k** [comment]
I have this issue too, however I also crash in the process

**Comment by tsunamayo** [comment]
Okay I just repushed the build as it was a regression. It is all good now! Thanks
