### ISSUE TITLE
[Bug] Gravity Tool Causes Game to Freeze

### ISSUE THREAD

**Issue by Xenoprophet-Nail** [tsunamayo/Starship-EVO#2857]
### Short Description of the issue:
Using gravity tool causes game to freeze

...

### Steps to reproduce the issue:
Load the save add then cycle to the gravity tool

...

### Environment
- Starship EVO version:  Early-Access 20w36a
- Graphics Card: Nvidia Geforce Gtx 1060 6gb

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5152115/output_log.txt)
[Beta Experimental.zip](https://github.com/tsunamayo/Starship-EVO/files/5152121/Beta.Experimental.zip)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Indeed! Fixed for 20w36b.
Cheers
