### ISSUE TITLE
Compressed Ship Stats

### ISSUE THREAD

**Issue by BenjSeaman** [tsunamayo/Starship-EVO#2870]
### Short Description of the issue:
On 1280 720 P 59Hz Resolution Ships Stats Compressed cant Read Them
...

### Steps to reproduce the issue:
Have the same resoultion 
...

### Environment
- Starship EVO version: 20w35a
- Graphics Card: Palit RTX2070 Dual 

### Additional information:
![20200902155614_1](https://user-images.githubusercontent.com/70651056/92001365-82669800-ed36-11ea-9bbd-daaaaaf2b416.jpg)

_(Screenshots, Videos, Error logs, Related issues)_

Cant Read Hull And Shields
Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Issue fixed for 20w37a. Thanks!
