### ISSUE TITLE
Could I get a list of some planned features or answer yes or no to my list?

### ISSUE THREAD

**Issue by jupitervesselcorp** [tsunamayo/Starship-EVO#2878]
#question 
weights,mass, volume
orbit mechanics
warping inside of current play field to another location in playfield
any can of hard artificial limits for balancing thus taking away freedom
motion dectectors
modding
npc ships that are under your control so you can forum a fleet
economy 
advance crafting system or simple one

what planned features will make this game better then empyrion both survial and building type play?

**Comment by tsunamayo** [comment]
So I will do my best ;)

weights,mass, volume -> humm yes?
orbit mechanics -> nope, it is not fun - this game is not KSP.
warping inside of current play field to another location in playfield -> not sure to understand, but we have lightcruise and interstellar travel will be back.
any can of hard artificial limits for balancing thus taking away freedom -> hum yes there are some limits like in any game, but the freedom of build is above average I would say 
motion dectectors -> yes (player only atm, but I will add entity detection)
modding -> we shall see, it is a long term goal. I need a solid game and player base first!
npc ships that are under your control so you can forum a fleet -> we shall see. 
economy -> some trading is planned.
advance crafting system or simple one -> not sure how you would define those. It will be a multistage crafting so you have to setup factory to be efficient.

Thanks

**Comment by jupitervesselcorp** [comment]
Thank you thatc

**Comment by jupitervesselcorp** [comment]
Thank you. Man you replied fast.  By factory you mean you won't just have one magical device that can build any parts no matter how exotic.  This game you are working so great.  You going make me leave empryrion for this gem you are building.

**Comment by tsunamayo** [comment]
yeah it mean a few crafting machine, then a few intermediate build items for crafting (plate, mesh ect).
