### ISSUE TITLE
Cannot use triangle half blocks as landing gear.

### ISSUE THREAD

**Issue by ArinCollie** [tsunamayo/Starship-EVO#2882]
### Short Description of the issue: I had triangle half blocks on the end of my landing gear, but they're still treated as full blocks when touching terrain or other blocks, making my ship float in the air and throw sparks around.

...

### Steps to reproduce the issue: Make the large flat end of the block touch parallel to a surface and it won't visually touch.

...

### Environment
- Starship EVO version: 20w35a
- Graphics Card: AMD Radeon RX 5700 XT

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5172308/output_log.txt)

![floatgrass](https://user-images.githubusercontent.com/70682651/92192399-73c2d280-ee55-11ea-89cc-a0e1438aefe8.png)
![floatmetal](https://user-images.githubusercontent.com/70682651/92192404-76252c80-ee55-11ea-9069-7c5f0b72a55e.png)

**Comment by Servomotor** [comment]
@tsunamayo I wonder if this has to do with issue #2146
I have noticed that my ships with flat landing gear behave more favorably than the ships with the 45 degree slopped block (stretched) being used as landing gear. 

This ship https://steamcommunity.com/sharedfiles/filedetails/?id=2147555466 uses the sloped 45 degree block for landing gear and when I use a ship yard it does not touch down completely. I am working on a ship ATM that uses flat landing gear, and its perfect. 

There seems to be an inherent issue using sloped blocks for landing gear. 
![20200903213236_1](https://user-images.githubusercontent.com/65745916/92193286-89240680-ee2d-11ea-9ade-f012957a5d4a.jpg)
![20200903213536_1](https://user-images.githubusercontent.com/65745916/92193289-89bc9d00-ee2d-11ea-93e0-c4648ac8ba16.jpg)

**Comment by Rizzo911** [comment]
Any thoughts on when the hitboxes will be fixed on angle blocks? They are used quite extensively on ramps and landing gear.

**Comment by tsunamayo** [comment]
This is now fixed. thx
