### ISSUE TITLE
[BUG] lightcruised into a planet died and became stuck noclip doesn't help

### ISSUE THREAD

**Issue by UnicornGit** [tsunamayo/Starship-EVO#2885]
### Short Description of the issue:

I lightcruised into a planet and died but I didn't respawn and I'm now stuck unable to move noclip isn't working

### Steps to reproduce the issue:

lightcruise into small planet I think I had no medbay selected or deleted it

### Environment
- Starship EVO version: 20w35a
- Graphics Card: AMD R9 295X2

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5172705/output_log.txt)

**Comment by tsunamayo** [comment]
@UnicornGit Ah indeed, for newer player they will always be a medbay but for older save I wont work.
I will fix it asap, I keep you posted! Thanks

**Comment by tsunamayo** [comment]
Issue fixed for 20w27a. Thanks!
