### ISSUE TITLE
[BUG] Camera freaking out when piloting the ship from a linked yoke

### ISSUE THREAD

**Issue by OverSavior** [tsunamayo/Starship-EVO#2888]
Here's what happens when I try to pilot my ship with a yoke that is not linked to the computer, but to another yoke
https://youtu.be/d1fDRQrTNYQ

**Comment by tsunamayo** [comment]
Hi, I see, could you please send me the blueprint? Thanks

**Comment by OverSavior** [comment]
@tsunamayo Yes, you can find it here https://steamcommunity.com/sharedfiles/filedetails/?id=2167238236

**Comment by tsunamayo** [comment]
@OverSavior Issue fixed for 20w37a. Thanks a lot!
