### ISSUE TITLE
Game crash & crashing in main menu/character select afterward

### ISSUE THREAD

**Issue by Foxthedark** [tsunamayo/Starship-EVO#2890]
### Short Description of the issue:
Game crashed while opening the inventory. Crashes on the main menu/while loading a character after restarting both steam and the whole desktop. 
...

### Steps to reproduce the issue:
unsure
...

### Environment
- Starship EVO version: 20w35a (latest on steam main)
- Graphics Card: Radeon RX 550 (Sappire pulse)

### Additional information:
Game went black for one or two frames every few minutes before the crash. As it crashed for the first time both steam and discord (wich were running in the background) crashed with it. When attempting to re-launch steam after it crashed received the "steam requires 250 mb to update" message (ssd still has 3gb free). 
_(Screenshots, Videos, Error logs, Related issues)_

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5174968/output_log.txt)

**Comment by tsunamayo** [comment]
@Foxthedark Hi, sorry to hear that.
So it seems you have some GFX issues. Could you make sure your GFX drivers are up to date? Thanks

**Comment by Foxthedark** [comment]
@tsunamayo 

shall check. one thing to note that happened so far is that i uninstalled something about 30 gb big and now it works again. Wich i find quite weird.

**Comment by tsunamayo** [comment]
Okay not sure what it was exactly, but it seems related to low disk space! Thanks
