### ISSUE TITLE
[BUG] With latest updates, new ships spawned in have constant z-fighting on painted areas and more than half of the blocks are transparent.

### ISSUE THREAD

**Issue by StarrKiss** [tsunamayo/Starship-EVO#2891]
### Short Description of the issue:
I have never used copy +paste on these ships, but yet, the ships I newly spawn in have constant z-fighting and more than half of the blocks are transparent. 

### Steps to reproduce the issue:
Spawn in a ship
### Environment
- Starship EVO version:  20w36c
- Graphics Card:  NVidia GTX 1070 ti

### Additional information:
Image of newly spawned in fighter. The hull should be opaque as there is one:
![image](https://user-images.githubusercontent.com/13007697/92251434-798ad900-ee92-11ea-9233-2389102c01e8.png)
This is what it looked like after spawning it in after multiple tries / preupdate.
![image](https://user-images.githubusercontent.com/13007697/92251491-8d363f80-ee92-11ea-813c-4c80da72f625.png)

_(Screenshots, Videos, Error logs, Related issues)_

**Comment by StarrKiss** [comment]
Here is the output.log:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5175607/output_log.txt)

**Comment by tsunamayo** [comment]
@StarrKiss do you get this on all ships? Also was it a multi session? Thanks

**Comment by tsunamayo** [comment]
I cant reproduce, that ship loads just fine...

**Comment by StarrKiss** [comment]
@tsunamayo  On all ships, it was a multiplayer game, But it seems to randomly occur on a per-launch basis- after a relaunch it was fine.

**Comment by tsunamayo** [comment]
@StarrKiss including single player game? Also you are sure that the log file was from a session where the bug happened? Thanks!

**Comment by StarrKiss** [comment]
It didn't occur in a single player game, and I am not sure as to logs- It might just be a one/two time thing after I started the game, it seems pretty infrequent.

**Comment by StarrKiss** [comment]
@tsunamayo  Another user is having this issue:  #2897 It might be worth it to take a look at THEIR output log

**Comment by tsunamayo** [comment]
Fixed for 20w36d. Thanks!
