### ISSUE TITLE
Query Logic Gate doesn't seem to work properly with Pistons

### ISSUE THREAD

**Issue by MatCat** [tsunamayo/Starship-EVO#2892]
### Short Description of the issue:
When using a query logic gate to check for greater or less then of a value on a piston it does not seem to work properly, it seems to only recognize greater then 0 as a condition.
...

### Steps to reproduce the issue:

Link a piston to a query logic gate and check for superior to 1 and extend to 2 meters, will not trigger.

...

### Environment
- Starship EVO version: Latest steam experimental (I think 20w36c)
- Graphics Card: 660 TI

**Comment by MatCat** [comment]
edited to properly reflect I was on 36c

**Comment by tsunamayo** [comment]
Gotcha. Btw how does the game run on a 660TI ? Thanks

**Comment by MatCat** [comment]
> Gotcha. Btw how does the game run on a 660TI ? Thanks

Ha, well funny you ask, I was thinking it was pretty good but I turned on FPS counter to actually see, getting about 16 FPS in an area with a bunch of stuff going on, 30 FPS floating around out in space near a fairly good sized ship, it doesn't feel that bad though very smooth even with low FPS.  I am on a 21:9 ultrawide as well so it is a pretty big resolution.

**Comment by tsunamayo** [comment]
@MatCat So I cant reproduce this issue, it works fine on my side. Are you still having some issue also? Thanks

**Comment by MatCat** [comment]
I will check and see if I can reproduce it later tonight when I get off work.

**Comment by MatCat** [comment]
I tried to recreate this issue and was not able to, seems it got fixed :).

**Comment by tsunamayo** [comment]
Okay good to hear ;)
