### ISSUE TITLE
[Issue] 1st person camera near plane clipping + 1st person camera height

### ISSUE THREAD

**Issue by Monstertruck-swe** [tsunamayo/Starship-EVO#2895]
### Short Description of the issue:
Camera height in first person is too high compared to third person models. About 1 head length or 0.25m in game.
Near clipping plane is set wrong.

### 3rd person: (can't see over the orange block)
![feedback03a](https://user-images.githubusercontent.com/70446055/92294183-e1d8c980-ef29-11ea-9def-40efc321ca75.png)
![feedback03b](https://user-images.githubusercontent.com/70446055/92294184-e43b2380-ef29-11ea-9df3-b11875da6d4c.png)

### 1st person: (easily sees over the orange block, and clips really badly with blocks above.
![feedback03c](https://user-images.githubusercontent.com/70446055/92294186-ebfac800-ef29-11ea-9b75-a5c03de46ec7.png)
![feedback03d](https://user-images.githubusercontent.com/70446055/92294187-ed2bf500-ef29-11ea-9ace-e93d162179a4.png)

### Additional information:
The earlier this can get some attention, the less creations affected negatively by it. Ships are purposely built around these issues as of now. I am playing at 80 FOV, but any FOV will cause the near plane clipping when it shouldn't. Even if the character animations are going to be different so it matches up with the camera height, the 1st person camera height might still be a little too high and the near clipping plane is still not satisfactory.

When looking at a ship from the front in 3rd person, the character is piloting ships as if it's an old person, not able to see over the steering wheel. Meanwhile the 1st person camera clips in the ceiling.

**Comment by tsunamayo** [comment]
Yes I only recently changed the character height, so cam needs a bit tweaking. The camera near plane is much much tricky than you expect, you can loose a lot of precision on the g-buffer because of this, so I will have to do some test and it might not be possible. 
Thanks

**Comment by Monstertruck-swe** [comment]
I see. Well, the camera height is the most important of the two. If the 1st person camera height corresponds slightly better to the actual character height, less players will build something directly over the characters head and see clipping. Thanks for clarifying!

**Comment by tsunamayo** [comment]
I fixed the height for 20w36d. I didnt touch the near plane though. Thanks!
