### ISSUE TITLE
[BUG] Ship Spawned in Incomplete

### ISSUE THREAD

**Issue by Kadzar** [tsunamayo/Starship-EVO#2897]
### Short Description of the issue:

I spawned in a ship and it spawned in incomplete

### Steps to reproduce the issue:

I don't know what happened, but I'll include the blueprint

### Environment
- Starship EVO version: 20w36c
- Graphics Card: NVIDIA GeForce GTX 1080

### Additional information:

![20200904231032_1](https://user-images.githubusercontent.com/66035211/92297464-1c7c3b00-ef05-11ea-9131-f2f452ecac55.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5177523/output_log.txt)

Blueprint: https://steamcommunity.com/sharedfiles/filedetails/?id=2205290268

**Comment by StarrKiss** [comment]
This is #2891

**Comment by tsunamayo** [comment]
Okay, it seems there is something bad with the ship preview, I keep you posted. Thanks

**Comment by tsunamayo** [comment]
Okay fixed for 20w36d. Thanks!
