### ISSUE TITLE
[BUG] Piston Shaft Seems to Extend Really Long on Its Own

### ISSUE THREAD

**Issue by Kadzar** [tsunamayo/Starship-EVO#2898]
### Short Description of the issue:

I spawned in a ship that has a piston shaft extending unnaturally long on its own

### Steps to reproduce the issue:

I don't know what happened, but I'll include the blueprint

### Environment
- Starship EVO version: 20w36c
- Graphics Card: NVIDIA GeForce GTX 1080

### Additional information:

![20200904234909_1](https://user-images.githubusercontent.com/66035211/92298002-556ade80-ef0a-11ea-9126-f737f956d797.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5177547/output_log.txt)

Blueprint: https://steamcommunity.com/sharedfiles/filedetails/?id=2218037277

**Comment by tsunamayo** [comment]
@Kadzar I think it must have been linked to the issue you had in log, which is fixed. It works fine over here! Cheers
