### ISSUE TITLE
Game doesn't open on steam

### ISSUE THREAD

**Issue by ob567** [tsunamayo/Starship-EVO#2899]
### Short Description of the issue:
when I want to start the game a window pops up that says "Application load error 3:0000065432"
...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 2018.3.14.59889
- Graphics Card: rtx 2080 super

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by ProPeach** [comment]
Check out issue #2485, it's a Steam related issue

**Comment by tsunamayo** [comment]
@ob567 Hi, sorry to hear that!
Propeach is right:

So it seams it more an issue on the steam side, could please try to re-install the game?
Check out a guide here:
https://appuals.com/fix-application-load-error-30000065432/

What is your OS?

Cheers

**Comment by ob567** [comment]
I tried a couple of things but it turned out to be a problem with my antivirus software. Thanks for the help
