### ISSUE TITLE
Logic brick output limitation

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#2902]
NAND logic gate does not provide a high output by default. It must be given at least one high input and then that input taken low before the default high output is made. I think for more complex logic arrays, such dependent behaviour could be difficult to flush through for all the state permutations. I suggest this (and all logic gates similarly affected) should provide their default output from the moment they are placed.

A similar specific problem occurs with the sequencer gate when connected to a mechanism brick. The input must be cycled before the output will change. Also when the position fields within the sequencer gate are changed, the input must be cycled again to update the effect on the mechanism brick.

A further difficulty with the sequencer gate is that if the mechanism brick is deleted and replaced, then re-linked to the original sequencer gate, it becomes necessary to change the values AND cycle the input in order to force the mechanism brick to react.

In all cases, it would make design and debug activities much more predictable (rewarding / sane/ etc.) if the output could always reflected the relevant logical interpretation of the present inputs.

- Starship EVO version: 20w35a
- Graphics Card: GTX 1070

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5178622/output_log.txt)

**Comment by tsunamayo** [comment]
Yes you are right, I think this can be considered a bug. Thanks

**Comment by tsunamayo** [comment]
Issue with the AND gate is fixed, also now new link will propagate their value. I will look at the sequencer issue and keep you posted. thx

**Comment by tsunamayo** [comment]
All fixed for 20w41a. Thanks!
