### ISSUE TITLE
Turret manual tracking seems wrong

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#2909]
Turrets controlled with a yoke move in fixed diagonal path. At first I thought it was the complexity of the turret, but I tried a simple one too and that also has the same problem.

- Starship EVO version: 20w35a
- Graphics Card: GTX1070

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5178968/output_log.txt)

[Retractable Turret_preview.zip](https://github.com/tsunamayo/Starship-EVO/files/5178967/Retractable.Turret_preview.zip)

**Comment by ProPeach** [comment]
If it's moving in a diagonal path, it sounds like you have the rotor axis configured to the same type. Press F on your turret rotors and set the base one to Vertical, and the second one to horizontal

**Comment by cloudrambler** [comment]
@ProPeach  You are a scholar. Thank you.

My favourite kind of bug; the "read the manual" kind.

Will close as the problem is not software related.
