### ISSUE TITLE
[Suggestion] Turret position reset

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#2910]
For retractable turrets, it would be useful to have the turret in a known position. Would it be possible for turrets to return to a default position when inactive. This could be after 30 seconds from when it was last fired / aimed. Thanks.

**Comment by GorettiEruadan** [comment]
Alternatively, if there was a way to bring back the feature where you could connect multiple logic gates to the same mechanism, you could just have the turret reset to a default position with the press of a button

**Comment by cloudrambler** [comment]
Could we have a control switch logic gate? It would have a digital input and an analogue input. With the digital input high the analogue input would be passed on to the output link. With the digital input low, the output could be null.

This way multiple analogue links could be connected to a mechanism, with external control over which one is active.

**Comment by WILDCATreactor** [comment]
Just being able to loop a "return to zero" sequencer to a switch and have it connect to a turret or turrets also controlled by a yoke would be nice.  Similarly, having the ability to assign multiple yokes to a single turret core, and maybe assign "control primacy" to one yoke in particular would be cool.  I can see ways of using a "primary controller" on yokes and turret/ship cores to create gun batteries that can be split into firegroups if a secondary yoke is manned (i.e. each yoke has primary control over a turret core, each turret core has primary control over some turrets but not all, all turrets are wired to all the turret cores).  Return-to-zero controls and similar would always be considered "secondary" to occupied control yokes.  But that's probably a ton of coding work... so maybe just having a "Primary Controller" or "Exclusion" gate where one control yoke or switch can be set as the 'master input'?

**Comment by cloudrambler** [comment]
Issue #2765 is near identical request with an affirmative from Tsuna, so I will close this one for clarity.
