### ISSUE TITLE
[Question] When will clipping be removed?

### ISSUE THREAD

**Issue by ultrak2k** [tsunamayo/Starship-EVO#2911]
Clipping has been around for a while, though not in the full form as it was before ( I believe blocks can't clip but bricks can right now, yes?)
Simple question, but since clipping has presumably been known to exist for months now but has stayed around, when will clipping be removed?
While I don't personally mind people using it, in other ways it can also be annoying as barrels clip into your hovercraft tank, or your wings or doors clip into your ship when you don't want them to (needing to check and constantly adjust a sequencer)

**Comment by tsunamayo** [comment]
Hi, you mean clipping on children entity? Thanks

**Comment by ultrak2k** [comment]
> Hi, you mean clipping on children entity? Thanks

Yes

**Comment by tsunamayo** [comment]
Yes it is on the to-do like 100s of other stuff...

**Comment by ultrak2k** [comment]
oh ok

**Comment by tsunamayo** [comment]
Yeah it is a good point I will put it on the top of my list, now that there is more people playing I guess it is more important.

**Comment by Womble-TC** [comment]
Can you give us some warning for when you are going to remove it? I have a ship(s) I need to finish that sort of use child entity clipping quite a bit.
