### ISSUE TITLE
[Suggestion] Border + Borderless versions of all glass panes

### ISSUE THREAD

**Issue by StarrKiss** [tsunamayo/Starship-EVO#2914]
### Short Description of the issue:
As of now, there are three glass blocks, the tetra, the pane, and the slope. Depending on the build, it bothers me greatly that either:

- The tetra doesn't have borders
- The pane  + slope do.

For instance, on a recent ship designed to look industrial, it was very annoying the tetras had no borders, and on a recent fighter, it was very annoying that the slopes DID.

**Comment by tsunamayo** [comment]
I can make no border version of the flat and slope, but I cant make border version of the tetra. Thanks

**Comment by tsunamayo** [comment]
So we now have borderless version. But still not border version of the tetra as it is not possible... Thanks
