### ISSUE TITLE
[Question] Lights

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#2917]
Short and simple, I just want to know how intense the number of lights used in a ship would be on performance - I don't want to build sections of interior for copy and pasting to realize in the end it's too much. As it stands a 12 meter hallway section has 16 lights and this is for that large spherical ship which is about 250m in diameter. I won't be having interior in every section possible but there will be a good amount of interior. Thanks!

**Comment by tsunamayo** [comment]
Good question!
Okay for now it has no impact. But with an upcoming refactor it would... I need that refactor for several reasons:
- Per light control: to make blinking light, color change ect
- To greatly reduce the memory usage, and fix the nasty large bug when you make your grid larger on larger ship
- To stream light computations
- To put a better lighting model with specular
- To maybe put some shadow!

Now it would have a negative impact the more you put. So yes beware of that. It would not be the worst things as the pipeline would be optimized like in AAA game (same tech as the decals) though.
 On the plus side cramming a lot of light wont look good as light would add up, so you would have overly bright corridor.
I might give you some small "neon" tube to decorate if you are after the look.

Cheers

**Comment by Xerma** [comment]
Very nice. The only reason it's using 16 lights is to achieve this dull-looking blue light as you see here:

1 light is a dark grey with another being blue, in each ridge you see in the hallway
![20200906182409_1](https://user-images.githubusercontent.com/32974671/92338133-e4473a80-f073-11ea-9dc8-95ead2785574.jpg)

**Comment by Servomotor** [comment]
I had 72 lights in my 6 way module for the space station contest. All of them attached to a volumetric sensor. When I triggered the sensor, I would get a 1 second pause/FPS drop and then I would go back to 60 FPS (I max the game at 60 intentionally). So, there was some kind of performance hit, not sure if it was lights or logic but I did get a 1 second stutter. 

I scaled the lights down to I think 12 or 16 and that solved the issue. 

I am not sure about SEVO, but when I played Landmark if you stacked lights on top of each other, they could lag you out fast. They key was to place them in such a way that that did not really overlap. Think about the engine having to calculate rendering for light, but then introducing another light source, the engine was now calculating for the additional light, now add another and repeat. 

I am not sure how this game works, but just giving you my experiences with lighting in building games.

**Comment by tsunamayo** [comment]
I will use Tiled Rendering like decals so we should be fine I guess shader wise, as soon as you dont put like dozens that light same area.
Your issue on perf is because of light recomputing. With the new tech they would be virtually not impact, it would have to do no additional computation. 
Cheers

**Comment by Xerma** [comment]
That sounds like a welcome change 👍

**Comment by tsunamayo** [comment]
We have the tiled rendering since a long long time! Cheers
