### ISSUE TITLE
[Commendation] I don't think you guys realize what an achievement this iteration of copy and paste actually is

### ISSUE THREAD

**Issue by Whackjob** [tsunamayo/Starship-EVO#2918]
Not a complaint, not a bug report, but I wanna give the dev an over-the-top commendation on what he's done here.  Specifically, his engine isn't dying on me, despite the ABSURD LEVELS OF STRESS I am putting on it.  So, just so everyone understands how freaking hard I'm trying, is a screenshot.   In this, I am pasting, *successfully*, a chunk over a kilometer tall.  A kilometer.  *Over and over again because I can.*

HOW?

https://i.imgur.com/UYiWiy2.png

**Comment by tsunamayo** [comment]
Okay that one is scary, as the culling cant do a lot of stuff - so a lot of stuff is gonna be drawn. Could you send me the blueprint so I can check the perf? Thanks

**Comment by Whackjob** [comment]
Of course.  Here you go.   Here's how it looks to me.  Quick clip:  https://imgur.com/sCgAHUb.png

**Comment by StarrKiss** [comment]
Lol @Whackjob  hows your megaship going btw?

**Comment by tsunamayo** [comment]
There is some bug with despawn, it is fixed for next update. Let me check the build out

**Comment by Whackjob** [comment]
@StarrKiss Honestly, now that I've figured out how to properly orient cut and paste and set things up for that transfer, I'm gonna start tonight.
Tsunamayo, just a heads' up, I'm going for 5km.

**Comment by tsunamayo** [comment]
@Whackjob could you make me a smaller version of that tesseract? Like 10x smaller. It make my PC lag af. Thanks

**Comment by Kaiser-Indrasil** [comment]
Yeah, this one is a fringe case. Most people's builds are more reasonable ;)

**Comment by StarrKiss** [comment]
Yeah I just used copy+ paste to move a turret because I placed the rotator in the wrong spot, and to replicate some patterns for a hallway.

**Comment by Whackjob** [comment]
@tsunamayo In progress now.  ETA 5 minutes or so.  Watch this space.

**Comment by tsunamayo** [comment]
@StarrKiss children entity copy dont work for now...

**Comment by StarrKiss** [comment]
> @StarrKiss children entity copy dont work for now...

Yes, I copied the bricks on the turret and replaced the guns on the hinges

**Comment by Whackjob** [comment]
Ok, here's a Tesseract 307 cubic meters in size.  

[TesseractLite.zip](https://github.com/tsunamayo/Starship-EVO/files/5180916/TesseractLite.zip)

**Comment by tsunamayo** [comment]
@Whackjob amazing! Thanks

**Comment by Whackjob** [comment]
If you need something different, let me know.  I have time now and then to whip up a whatever.

**Comment by tsunamayo** [comment]
@thanks ;) Still lagging a lot, but if I want to optimize shader pressure I can use it.
So yeah maybe a big ass cube of death with a different twist:
Enclosed Room with a lot of bricks inside them. No need to make door, just 16x16x16m room with stuff inside ;)
So I can see if it is a vertex or pixel bottleneck.

**Comment by Whackjob** [comment]
Ok, so 16x16x16m rooms, enclosed, bricks, how big overall you want that cube of death?  ~300m again?

**Comment by Whackjob** [comment]
Also, I did it, @tsunamayo.  I killed your engine, at long last.  I built a beast of a frame to hang off parts on, armor plating, shields, reactors, guns, et cetera.  I went for the 5k goal.  Well, the engine dies not long after two kilometers.  You probably already know.  But copying just one "frame" and extending the length causes a hard crash to desktop.  Here is the file.

[Arkingthaad II.zip](https://github.com/tsunamayo/Starship-EVO/files/5182015/Arkingthaad.II.zip)

She was amazing.

https://imgur.com/phKhi0E.png

**Comment by AlienXtream** [comment]
ok so just over 2km is the current upper size limit of ships. not quite death star scale like i had theorized but thats hefty. i mean, a 2km scaled version of the death star is still quite an accomplishment. tsuna, i think your concerns about the engine not being able to handle it are all but gone for anything less than 1.5km. stick a hud warning after going past that to advise thinking about stopping and i would call that good

**Comment by Whackjob** [comment]
See, there's nothing really stopping me at 2km aside from things crashing when I paste.  So maybe if I built manually, I could go past?  But that's just a matter of how long it would take without cut and paste.  What I did here in a few hours took me over 125 hours with the previous vessel.   So there's just something with cut and paste that crashes out when building that far from the origin.  It could potentially be fixed.  Flying a 2km ship, no problem.  Flying around it, no problem.

**Comment by BrickMacklin** [comment]
@Whackjob I told you on Discord this would happen. It is not a copy and paste issue. We have a post on here already about it. Above 2km but below 3km you will encounter a crash. The engine currently cannot handle it. You would have run into this building manually. We had this happen months ago.

**Comment by AlienXtream** [comment]
well, infinite building size (or at least big enough no one can reasonably reach the limit) is not really possible. still, a 2-3km dynamic 3D voxel based movable entity is no small feat for a game engine to achieve, even at cripplingly low framerates. i keep holding hope we will one day be able to make death star scale structures but for that either the game would need another refactor and a supercomputer or some independant build system for "super structures" (basically a "framework" that the game would treat similar to how the ring world is handled which the player builds "ground" structures on)

**Comment by MatCat** [comment]
I know this isn't the best place to ask, but, HOW do you copy and paste?

**Comment by Whackjob** [comment]
@MadCat There's a tool for it now.  Drag a marquee to select what to copy, hit R for depth, let go of button to copy, and then right click to paste.   Paste carefully.  There is no undo at this time.

**Comment by tsunamayo** [comment]
Yeah it is not about the length (again you think like if it was another game, that is why I was concerned at the first place) as you can put unlimited details in small spaces. So you could make a 100m ship that lag 100x more than a 1km one.
The issue with size you get I would say are memory issue, right now the light volume will kill your v-memory I guess, or you might run into a DX11 texture hard limit.
I dont have any fear with memory and copy-paste, the memory impact of geometry is really tiny and super optimized.
I have some concerns about shader pressure because of having to draw all that geometry though, this is what I want to check.
So it is not about the size of things (this is a different problem, memory will be taken care with the light refactor), but their brick density!
Cheers

**Comment by Whackjob** [comment]
Interesting!  So the dump-to-desktop I'm seeing might be alleviated significantly if I just get some more ram in my system.  Well, the one I'm using now is getting an upgrade in the first quarter of the next year... so I just have to be a little patient, then.

**Comment by tsunamayo** [comment]
nope I am talking about v-ram, and I have to do the computation but you might hit DX11 max texture size before your gfx card max v-ram if you have a big card. So nothing you can do...

**Comment by tsunamayo** [comment]
There you go
https://docs.microsoft.com/en-us/windows/win32/direct3d11/overviews-direct3d-11-resources-limits
So we are limited to 2048 meter because of the light volume I guess.
Then you cant have a texture bigger than 2048MB or 25% of your VRAM on top of that.

**Comment by Whackjob** [comment]
Hrm.  I'd say it's lowest possible priority right now, but think there's a way around that?

**Comment by MatCat** [comment]
I just tried copy and paste in 37a, I noticed it doesn't copy screen text and links between logic, but it did seem to copy all the bricks and blocks just fine.
