### ISSUE TITLE
Starting building won't render. 

### ISSUE THREAD

**Issue by Som3guy802** [tsunamayo/Starship-EVO#2919]
### Short Description of the issue:
It seems that the starting building and ship textures wont load. Every new character starts in a floating invisible cage i have to no-clip through. Floating icons in other rooms can be seen and can be interacted with but the building around them is tangible, but non-visible. 

...

### Steps to reproduce the issue:
I've messed with a few settings and debug tools, but with no change.
...

### Environment
- Starship EVO version: 20w35a
- Graphics Card:  AMD FX-8800P Radeon R7

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by tsunamayo** [comment]
Hi, could you please send me the log file as explained here?
Please also include the output_log.txt file. You can find your log here: %UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\
Thanks
