### ISSUE TITLE
[BUG] Camera goes haywire when accessing yoke on subgrid linked to yoke on maingrid

### ISSUE THREAD

**Issue by XNargaHuntress** [tsunamayo/Starship-EVO#2921]
### Description:
Building a ship with a yoke on a subgrid that attaches to a yoke on a main grid causes the camera to go haywire when sitting in a seat and accessing the yoke on the subgrid. Switching to third person camera fixes the issue until you exit the yoke or switch to first person view.

### Steps to reproduce:
1. Build a ship with a yoke on the main grid
2. Build a canopy subgrid with yoke attached
3. Link 2nd yoke to main yoke
4. Add chair to main grid (in reach of 2nd yoke)
4. Sit in chair, close canopy and access 2nd yoke

(Alternately, use ship in attached blueprint. Switch on left side of seat closes canopy.)

### Environment:
- Starship EVO version: 20w34a Experimental
- Graphics Card: nVidia RTX 2060
  - Driver Version: 451.67
- CPU: Intel i7-9750H

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5183933/output_log.txt)
[Chonkrat Shuttle.zip](https://github.com/tsunamayo/Starship-EVO/files/5183934/Chonkrat.Shuttle.zip)
![Screenshot (192)](https://user-images.githubusercontent.com/39832634/92405060-d7255c80-f102-11ea-849b-a98b44aae4c6.png)
![Screenshot (191)](https://user-images.githubusercontent.com/39832634/92404736-39319200-f102-11ea-9bc8-aa9b78e3807a.png)

**Comment by tsunamayo** [comment]
Hi, thanks for booking this. Actually this bug was already fixed, it will be in next update 20w37a. Thanks!
