### ISSUE TITLE
[BUG] lag spike every four to six seconds

### ISSUE THREAD

**Issue by UnicornGit** [tsunamayo/Starship-EVO#2926]
### Short Description of the issue:

every four to six seconds there's a lag spike no matter what I'm doing in the game even just standing still.   

### Steps to reproduce the issue:

I don't know how to reproduce it because it's constant and I don't know what's causing it

### Environment
- Starship EVO version: 20w36b
- Graphics Card: AMD R9 295x2

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5190370/output_log.txt)
[SETTINGS_ini.txt](https://github.com/tsunamayo/Starship-EVO/files/5190384/SETTINGS.txt)

**Comment by Brushes2** [comment]
I know it's not _quite_ the same but could [this be related?](https://github.com/tsunamayo/Starship-EVO/issues/2520)

**Comment by UnicornGit** [comment]
I still get lag spikes even without photo viewer open.

**Comment by tsunamayo** [comment]
@UnicornGit Hi, how big are the spike? Does it completely ruin the experience or is it a bit irritating?
Could you open the FPS counter in the F3 menu, let it run a bit and take a screenshot so I can see how big they are? 
Thanks
