### ISSUE TITLE
Save corruption when saving in  a system with a Purple star?

### ISSUE THREAD

**Issue by NekNekx** [tsunamayo/Starship-EVO#293]
I tried to save the game twice now inside a purple star system everytime i try to load the game it loads to infinity. Sadly i removed the save and refreshed the game currently trying to find another purple system (will update when i find one)

**Comment by tsunamayo** [comment]
I dont think that purple star have anything specific, are you able to load everytime with a normal different star? Cheers

**Comment by NekNekx** [comment]
Yep its all fine in other Systems so far i only had this Problem at the
edge of the galaxy with a purple Star

Am 30.10.2017 09:52 schrieb "Francois Duret" <notifications@github.com>:

**Comment by tsunamayo** [comment]
No longer applicable. Thanks
