### ISSUE TITLE
[Suggestion] Select entity to copy when multiple entities are within the Copy-Paste field

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#2930]
I'm trying to copy a large chunk of a turret which features multiple child entities. I drew a field that would cover top-most parent entity and it copied one of the child entities instead. I want to bring up an issue that there's no control we have right now over what entity will be copied. An ideal solution would be to have the copy-paste tool to copy all the entities within the field but I imagine it would take some time and testing to develop.

Here's the link to the video picturing the above mentioned scenario:
https://1drv.ms/v/s!AmcHNSRjXywp6UsSvoO6Ltg7QOxC?e=eeKo5D

**Comment by tsunamayo** [comment]
Yeah for now you cant copy children entity. This is gonna be tricky to make, stay tuned... Cheers
