### ISSUE TITLE
[QUESTION] Building well detailed turrets

### ISSUE THREAD

**Issue by matejkar** [tsunamayo/Starship-EVO#2934]
Hello there, 
since i started working on turrets i was doing turrets in a way that the entire turret body was moving vertically and horizontally, and i've seen people doing turrets with complete bases, and looking like proper turrets, compareble to star wars turbolasers or real life battleship main battery guns.
So i tried doing stuff like placing a rotor, putting blocks for the turret base on it (as if building a cube on the rotor) and placing a vertical rotor inside the turret that matches the number of barrels in the turret. I thought that would have worked but upon asking well experienced people how does it work, they said it does not.
![20200525105205_1](https://user-images.githubusercontent.com/69653738/92641717-6edfa200-f2df-11ea-9258-19fdb81dfba7.jpg)
this is how i build turrets, also maybe i should mention that the turrets work, rotate and fire, but i don't like the look on them and want to build proper turrets.
![20200530125730_1](https://user-images.githubusercontent.com/69653738/92641916-bd8d3c00-f2df-11ea-847a-b2199cd64fa7.jpg)

![20200530125726_1](https://user-images.githubusercontent.com/69653738/92641963-ce3db200-f2df-11ea-81b4-efaecb32cece.jpg)
![20200530125730_1](https://user-images.githubusercontent.com/69653738/92641966-d0a00c00-f2df-11ea-94cd-a3d0ac4a0786.jpg)
![20200530125720_1](https://user-images.githubusercontent.com/69653738/92641968-d1d13900-f2df-11ea-892f-4679d271bcc4.jpg)
and this is a prototype turret i was talking about, turns out i placed a larger block on the vertical rotor to support the barrels.
Also i should mention i have not actually tried that design on a ship, i just asked people, and didnt try anything else.
![image](https://user-images.githubusercontent.com/69653738/92643655-6a68b880-f2e2-11ea-9b4e-0383fa373ec5.png)
and these are the types of turrets i wanna build (last pic - https://steamcommunity.com/sharedfiles/filedetails/?id=2206000343)

So if anyone has knowledge or ideas on how those turrets are build and is willing to share it, i would be very thankfull.

**Comment by TIKIRobo** [comment]
my suggestion to make turrets look good is to use bricks and blocks (bricks being the small ones blocks are the big ones) to form a "mold" around the gun then make it look nice by adding bits of greeble on the turret ect just work with it until it looks nice (if you dont know what greeble is look it up)

**Comment by TIKIRobo** [comment]
also a better place to ask this would on the discord https://discord.gg/starshipevo

**Comment by CurioInventorium** [comment]
There's also been a few YouTube videos made on making turrets too

**Comment by WILDCATreactor** [comment]
also keep in mind that the hit boxes are not always in line with the shape of the block and invisible hitbox clipping can cause issues on a build that otherwise looks like it should work, other than that I'm not sure if you can have multiple rotors/hinges operating on the same axis control, but you can build "floating" structures for more complex turret designs by creating a bridge-like structure to anchor the blocks you want and then deleting the bridge after you have everything placed the way you want it
