### ISSUE TITLE
[SUGGESTION] turret blueprints

### ISSUE THREAD

**Issue by matejkar** [tsunamayo/Starship-EVO#2935]
I love the building of turrets in SEVO, but there are a lot of turret designs i cannot really build, so i would like the possibility to implement turret blueprints.
Not sure yet how this would work out, probably saving the turret computer, and upon going to place it holding down RMB and the turret is shown, then the player can rotate it as they wish.
Or make the turret simply like another block, but then make the turret computer a part of the turret.

**Comment by tsunamayo** [comment]
Yes this is planned, it was in the discussion on copy-paste/prefab. Thanks
