### ISSUE TITLE
[Bug] Copy/Paste issue with rotate

### ISSUE THREAD

**Issue by Cheackraze** [tsunamayo/Starship-EVO#2936]
### Short Description of the issue:
  I was trying to copy and paste my apartment from one template and rotate it, mirror it to fill the hallway.  When placing, it soft locks and slows to a crawl of less than 1 fps.  I thought the complexity of some of the tiles was the issue, even though its relatively small, and no matter how I trimmed the bathroom it caused the same issue.  Even recreating the base blueprint, with a new entity and plain frame, caused the same issue.

However, if I copied the template, pasted onto the frame with mirror on X axis, it worked fine.  So copied that template, without rotating, placed onto a new frame with mirror on Y axis, worked fine just fine.
![20200909185215_1](https://user-images.githubusercontent.com/71046427/92664893-36d26200-f2d3-11ea-8d2e-c4b9e374cf2c.jpg)
[Blueprints.zip](https://github.com/tsunamayo/Starship-EVO/files/5198371/Blueprints.zip)

...

### Steps to reproduce the issue: 
 Start a new game, spawn both Apartments and Apartments Template Slim2, copy the template, rotate it twice to place inside the frame and then place.
[Blueprints.zip](https://github.com/tsunamayo/Starship-EVO/files/5198371/Blueprints.zip)
...

### Environment
- Starship EVO version: 20w37a

- Graphics Card: nvidia gtx 970

### Additional information:

Blueprints file attached with original, plus the split templates to recreate the issue.

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5198380/output_log.txt)

**Comment by Cheackraze** [comment]
I encountered the bug again, this time when trying to paste a turret.  It was rotated several times, and it looks like it keeps placing infinite blocks down, as the child entity weight warning popped up fast and climbed very high before I exited the game:

![20200912033218_1](https://user-images.githubusercontent.com/71046427/92990281-11974c80-f4a9-11ea-8f86-0d5728d21518.jpg)

**Comment by tsunamayo** [comment]
Issue should be fixed for 20w40c. Thanks!
