### ISSUE TITLE
[BUG] Phantom query gate signal

### ISSUE THREAD

**Issue by UnicornGit** [tsunamayo/Starship-EVO#2940]
### Short Description of the issue:

I found out if you remove a query gate with something linked to it still sends an output

### Steps to reproduce the issue:

setup a query gate with an input and an output then delete the query gate

### Environment
- Starship EVO version: 20w36b
- Graphics Card: AMD R9 295X2

### Additional information:

![711980_20200910203807_1](https://user-images.githubusercontent.com/70233827/92794898-e11bb980-f3a7-11ea-98a2-46a36460f4e0.png)
![711980_20200910203815_1](https://user-images.githubusercontent.com/70233827/92794924-e5e06d80-f3a7-11ea-9eeb-0a95e1040cd5.png)
![711980_20200910203843_1](https://user-images.githubusercontent.com/70233827/92794966-ef69d580-f3a7-11ea-92ac-eae38dfdb46c.png)
![711980_20200910203927_1](https://user-images.githubusercontent.com/70233827/92794991-f395f300-f3a7-11ea-8097-bb185845fda5.png)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5204356/output_log.txt)

**Comment by tsunamayo** [comment]
Issue fixed for 20w43b. Thanks!
