### ISSUE TITLE
[Suggestion] Light gate (logic)

### ISSUE THREAD

**Issue by JessaTehCrow** [tsunamayo/Starship-EVO#2942]
# Description
A new gate that you can hook up to any block that glows (Lasers, Medbay, Connectors, Thrusters, etc.)

It works like the sequencer, it has a off and on value.

When turned on it'll set the glow factor of the block to the `on` value of the light gate, and same for off.

### Extras
Maybe an additional option for transition time

**Comment by tsunamayo** [comment]
Okay I understand the request. But that is confusing game-mechanic wise. Having the main block glow turning off means that this blocks is turned off, period. If you link a switch to the block (except the laser), you will get the same result visually, but of course the block is inactive.
Cheers!

**Comment by Gliese-832-c** [comment]
To be honest, turning off the RGB lights inside my PC doesn't turn the PC itself off.
