### ISSUE TITLE
[Bug] blueprints not fully loading in.

### ISSUE THREAD

**Issue by MRonlin** [tsunamayo/Starship-EVO#2944]
### Short Description of the issue:
When loading in a blueprint some of the ship appears invisible, this happens with all blueprints and fixes itself apon restart. 

### Steps to reproduce the issue: Not sure.

...

### Environment
- Starship EVO version: 20w 36b
- Graphics Card: gtx 1050

### Additional information:
![711980_20200911104011_1](https://user-images.githubusercontent.com/64201628/92905742-d69b0780-f41b-11ea-9f3c-dfc4f739ba5e.png)
![711980_20200911104221_1](https://user-images.githubusercontent.com/64201628/92905774-db5fbb80-f41b-11ea-8ae2-12398b0392f9.png)

Please also include the `output_log.txt` file. You can find your log here: 
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5208100/output_log.txt)

**Comment by tsunamayo** [comment]
Okay not sure to understand the test case:
It is an issue when you spawn a blueprint after the initial game load?
And it seems to happens with any blueprint?
Am I correct?

Nice ship btw
Thanks

**Comment by MRonlin** [comment]
Yes, however oddly it seems to have fixed itself as I no longer have this problem anymore.
