### ISSUE TITLE
[Suggestion] Larger paint brushes

### ISSUE THREAD

**Issue by MadTheDog** [tsunamayo/Starship-EVO#2946]
Suggestion to be able to paint larger areas using the paint tool.
Could be like Space Engineers system where if you paint while holding in ctrl it paints a 3x3 area around your cursor, and if you shift click it paints a 5x5 area around your cursor.

**Comment by ZachZent** [comment]
Agreed and shamelessly linking my previous post on the issue
https://github.com/tsunamayo/Starship-EVO/issues/2494

**Comment by MadTheDog** [comment]
Oh I didn't realize someone had suggested it before! But I do hope it will be added in the near future

**Comment by tsunamayo** [comment]
Yep we have a suggestion for this already. Thanks
