### ISSUE TITLE
Blast door not truly mirrored

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#2947]
Placing a blast door with the symmetry mode active creates a paired door of the correct proportions but incorrect orientation. The sliding door itself always moves in the opposite direction to that which would be correct as a full mirror of the original.

Also if you then replace the mirrored door to the intended orientation, but leave mirror mode active, the original door would be updated to the inverted orientation. So it seems impossible to place fully mirrored doors with the symmetry mode active.

Turning off the symmetry mode and placing all doors individually seems to yield a stable method without constraint.

The above effect is consistent with all three symmetry plane orientations.

...

### Steps to reproduce the issue: Build a blast door in symmetry mode, observe the opening direction of it and it's mirror. 

...

### Environment
- Starship EVO version: 20w36b
- Graphics Card: GTX1070

**Comment by tsunamayo** [comment]
@cloudrambler Hi, so that one will be finally fixed for 21w51b. Thanks
