### ISSUE TITLE
Cannot create new character.

### ISSUE THREAD

**Issue by Aurimukstis1** [tsunamayo/Starship-EVO#2948]
### Short Description of the issue:

So, I go to create a new character for a new world. 
I press "play with this character", but absolutely nothing happens.

### Steps to reproduce the issue:

I don't know... It happened out of nowhere.

### Environment
- Starship EVO version: 20w36b
- Graphics Card: GTX 1060

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by tsunamayo** [comment]
Hi, this is weird!
You dont get the loading screen?
Could you give me the output.log?
Was it your first try or did you played the game before?
Thanks

**Comment by obsoletenerd** [comment]
I get this bug too. I can play the game fine on my gaming PC but on my laptop I can't get past the character creation screen.

I can enter my name + seed, then when I click Play I just see the big splash screen graphic and it never goes past that. Music fades out and game locks up until I kill the application.

When I launch the game again, there's no characters in the character list but if I try use the same name as last time it says it's taken. If I put a new (different) name in and press Play, it crashes again like the first time.

Output_log.txt:

---

Initialize engine version: 2018.3.14f1 (d0e9f15437b1)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: Intel(R) UHD Graphics 620 (ID=0x5917)
    Vendor:   
    VRAM:     4187 MB
    Driver:   26.20.100.7810
Begin MonoManager ReloadAssembly
- Completed reload, in  0.129 seconds
<RI> Initializing input.

XInput1_3.dll not found. Trying XInput9_1_0.dll instead...
<RI> Input initialized.

<RI> Initialized touch support.

The referenced script (GrabbableBox) on this Behaviour is missing!
 
(Filename:  Line: 195)

The referenced script on this Behaviour (Game Object 'Box') is missing!
 
(Filename:  Line: 294)

UnloadTime: 0.740200 ms
 -- LOADING RESOURCES -- 
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Functional Blocks
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Weapons
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Moving Bricks
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Logic Items
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Hull Blocks
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Block for interior building.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Construction Blocks
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Construction Bricks
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Pipes
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Windows and Cockpits
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Paints
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Decals
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Loading all textures
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Shape Mesh Data Buffer Count: 75063
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Allocating Voxel Resources
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Allocating Chunk Resources: 51110
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Allocating Brick Data Resources: 5815278
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Unloading 5 Unused Serialized files (Serialized files now loaded: 0)

Unloading 1928 unused Assets to reduce memory usage. Loaded Objects now: 12266.
Total: 19.149400 ms (FindLiveObjects: 1.287700 ms CreateObjectMapping: 1.168100 ms MarkObjects: 15.679900 ms  DeleteObjects: 1.012800 ms)

Unloading 1 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 12266.
Total: 16.439900 ms (FindLiveObjects: 1.039800 ms CreateObjectMapping: 0.898500 ms MarkObjects: 14.471900 ms  DeleteObjects: 0.028800 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)
TOTAL MESH DATA 34440
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

RESTARTING THE GAME
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Starship EVO Version: early-access 20w36b
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

System GFX memory 4187 mb
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

System memory 16238 mb
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Steam Log Success
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

SETTINGS Loaded
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)


Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 26259.
Total: 32.378600 ms (FindLiveObjects: 4.179100 ms CreateObjectMapping: 0.743200 ms MarkObjects: 27.405000 ms  DeleteObjects: 0.050000 ms)

Unloading 1 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 26259.
Total: 37.172100 ms (FindLiveObjects: 2.918600 ms CreateObjectMapping: 1.883900 ms MarkObjects: 32.323000 ms  DeleteObjects: 0.045800 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 26259.
Total: 44.652100 ms (FindLiveObjects: 2.719400 ms CreateObjectMapping: 2.511500 ms MarkObjects: 39.345200 ms  DeleteObjects: 0.075500 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 27003.
Total: 55.499400 ms (FindLiveObjects: 3.395600 ms CreateObjectMapping: 2.105100 ms MarkObjects: 49.896400 ms  DeleteObjects: 0.101600 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 27003.
Total: 61.805500 ms (FindLiveObjects: 5.066000 ms CreateObjectMapping: 1.100300 ms MarkObjects: 55.559800 ms  DeleteObjects: 0.078900 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 27003.
Total: 49.798400 ms (FindLiveObjects: 3.998000 ms CreateObjectMapping: 2.398200 ms MarkObjects: 43.305600 ms  DeleteObjects: 0.095800 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 27003.
Total: 50.448300 ms (FindLiveObjects: 6.853900 ms CreateObjectMapping: 1.081800 ms MarkObjects: 42.461800 ms  DeleteObjects: 0.049700 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 27003.
Total: 41.275500 ms (FindLiveObjects: 3.147200 ms CreateObjectMapping: 1.713500 ms MarkObjects: 36.324300 ms  DeleteObjects: 0.089700 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 27003.
Total: 37.517700 ms (FindLiveObjects: 2.835700 ms CreateObjectMapping: 1.028700 ms MarkObjects: 33.605000 ms  DeleteObjects: 0.047700 ms)

Level 0 computation finished 105772
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Level 0 computation finished 106127
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

SETTINGS.ini Saved
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Loading player PlayerOne
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

SETTINGS.ini Saved
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

SETTINGS.ini Saved
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

SETTINGS.ini Saved
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

New Character: Sen2
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

network adress 0
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

OnPlayerConnected
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Unloading 5 Unused Serialized files (Serialized files now loaded: 0)
SETTINGS.ini Saved
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

UnloadTime: 88.426300 ms
Creating slots for CHIPS
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Warning: no canvas scaler on Canvas_StatsMonitor(Clone)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

PLAYER WEAPON WAKEUP
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

PLAYER HEALTH WAKEUP
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Culling Manager Online
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Uploading Crash Report
NullReferenceException: Object reference not set to an instance of an object
  at Manager.PhysicsManager.Update () [0x00018] in <f2c1c3721dbb436689021945c3bcd9bf>:0 
 
(Filename: <f2c1c3721dbb436689021945c3bcd9bf> Line: 0)

Block Entity Manager Start.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Local player Start sequence: 
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Material doesn't have a texture property '_MainTex'
 
(Filename:  Line: 1261)


Unloading 193 unused Assets to reduce memory usage. Loaded Objects now: 95220.
Total: 128.974600 ms (FindLiveObjects: 9.183800 ms CreateObjectMapping: 2.864200 ms MarkObjects: 116.658300 ms  DeleteObjects: 0.267500 ms)

NEW SYSTEM
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Loading Entity Instances on System: c[64 0 30]l0n0
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

total stars 2176
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Kuroshio : Command already existing 1589768
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Kuroshio : Command already existing 1589768
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Kuroshio : Command already existing 1589768
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Kuroshio : Command already existing 1589768
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Kuroshio : Command already existing 1589768
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Kuroshio : Command already existing 1589768
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Kuroshio : Command already existing 1589768
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Kuroshio : Command already existing 1589768
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Kuroshio : Command already existing 1589768
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

De-allocating Voxel Resources
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Asset Repo: On Application Quit
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

UNLOADING ASTEROIDS RESOURCES
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Application Quit: Cleaning Render Texture for Habitat Nodes
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Setting up 2 worker threads for Enlighten.
  Thread -> id: 40f4 -> priority: 1 
  Thread -> id: 300c -> priority: 1 
SETTINGS.ini Saved
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

18849 LOADING SEQUENCE FINISHED
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Uploading Crash Report
NullReferenceException: Object reference not set to an instance of an object
  at Manager.LoadManager.OnDisable () [0x00019] in <f2c1c3721dbb436689021945c3bcd9bf>:0 
 
(Filename: <f2c1c3721dbb436689021945c3bcd9bf> Line: 0)

Destroying Starfield Particles
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Uploading Crash Report
NullReferenceException
  at (wrapper managed-to-native) UnityEngine.Light.AddCommandBuffer(UnityEngine.Light,UnityEngine.Rendering.LightEvent,UnityEngine.Rendering.CommandBuffer,UnityEngine.Rendering.ShadowMapPass)
  at UnityEngine.Light.AddCommandBuffer (UnityEngine.Rendering.LightEvent evt, UnityEngine.Rendering.CommandBuffer buffer) [0x00001] in <f2abf40b37c34cf19b7fd98865114d88>:0 
  at Common.RenderPipelineBuffers.RemoveFromCamera (UnityEngine.Camera camera, UnityEngine.Camera farCamera, UnityEngine.Light light) [0x00083] in <f2c1c3721dbb436689021945c3bcd9bf>:0 
  at VoxelEngine.VoxelRenderingManager.OnDestroy () [0x0006b] in <f2c1c3721dbb436689021945c3bcd9bf>:0 
 
(Filename: <f2abf40b37c34cf19b7fd98865114d88> Line: 0)

GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

**Comment by tsunamayo** [comment]
@Aurimukstis1 Hi, do you still experience the issue? I would  like to fix this as other player might have faced the same issue. If you have a log file that could help.
@obsoletenerd Hi, do you confirm your laptop only have a Intel UHD 620 GFX card or does in also have a dedicated card? Thanks

**Comment by obsoletenerd** [comment]
Sorry for the slow reply, yes I only have the Intel UHD 620, I'm on a Lenovo Thinkpad X1 Carbon.
