### ISSUE TITLE
[BUG] Copied gating blocks do not copy over original color 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#2952]
### Short Description of the issue:
When copying grating blocks (grating B to be specific) the original color is not retained  
...

### Steps to reproduce the issue
paint a grating block then copy and paste it
...

### Environment
- Starship EVO version: 20w37a
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![image](https://user-images.githubusercontent.com/56371294/93005773-14298e80-f509-11ea-808a-d682f1401afb.png)
the one painted orange is the original 

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5213315/output_log.txt)

**Comment by tsunamayo** [comment]
So to fix this bug I have to move this brick to a brick paint, not a voxel paint like the hull. I think it is okay, but it will clear all the paint on your grating unfortunately...
"Fixed" for 20w41a.
Thanks!
