### ISSUE TITLE
FPS Issues with screen size change

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#2958]
### Short Description of the issue:
I used to play this game, and everything, on my drawing tablet which used to be my main monitor until I switched up my setup some long time ago. I had small fps drops on a regular 1600 x 900p monitor and if I remember correctly my GPU usage was 40 - 50%. I chose to switch my drawing tablet back to my main display just today and I get constant frame drops in-game to around 46fps with very obvious stuttering. My drawing tablet display size is 2560 x 1440p (Wacom Cintiq 27QHD). GPU usage while using my tablet as my display is 99 - 100%
...

### Environment
- Starship EVO version: 20w37a (experimental)
- Graphics Card: GTX 970

### Additional information:
![20200913155412_1](https://user-images.githubusercontent.com/32974671/93028411-7782f180-f5d9-11ea-8c07-c527311b4110.jpg)

**Comment by Xerma** [comment]
Frames drop when looking at/being in larger entities

**Comment by tsunamayo** [comment]
Hi, what are the old config and the new config (GPU - CPU - RAM)?
Thanks

**Comment by tsunamayo** [comment]
Ah sorry it is just a monitor change! Yeah you cant expect to draw 2.6x time more pixels and not have any impact...
For the stuttering it is different, you did not had any with the old monitor?
Thanks

**Comment by Xerma** [comment]
It only happened every once and a while and was maybe a drop of 2 or 3fps. It does make sense that it would have an impact but I wasn't expecting it to be such a big difference with 43fps on average. The strangest part is that it didn't happen way back when I used this same tablet as a monitor. The monitor I was using and my drawing tablet both have a refresh rate of 60hz if that's of any use to you

**Comment by tsunamayo** [comment]
That is not a big impact fps wise, I wonder if there is something else... Is it really disturbing? Thanks

**Comment by Xerma** [comment]
It's still playable but it is visually disturbing seeing the stuttering. I just quickly opened up Starmade to test the frames there but it's not exactly on the same level as Starship EVO in terms of graphics. When I'm in the spherical ship I get an average of 42 fps. When away from that ship and looking at the ground of the torus from space I get an average of 55 fps. When looking at nothing I get a solid 60 fps. When away from the ship but looking at it I get 60 fps. Disabling all graphic options does nothing for frames. Setting my resolution on my tablet to 1600 x 900 brings back the smooth frames but I lose the nice coloring my tablet brings. One fix for me would be to move my tablet to my right hand display I suppose but it would definitely be nice to run the game on my tablet plus other people may have the same problems with bigger screen resolutions

**Comment by Xerma** [comment]
1920 x 1080 is pretty smooth as well

**Comment by tsunamayo** [comment]
@Xerma Hey mate, do you still get this in latest version (as things should run better?) Thanks
