### ISSUE TITLE
ESC key and GUI functionalities

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#2960]
Not sure whether this is a bug or suggestion as most games have this functionality and maybe you meant to have it this way, I don't know.

Basically, whenever another GUI screen is open you should be able to press ESC to close that screen and only when no other screens are open should ESC bring up the main menu GUI. Currently if you press ESC to get out of any screen then it brings up the main menu screen instead of closing that screen.

**Comment by tsunamayo** [comment]
Yep thats a bug I guess... Thanks

**Comment by MatCat** [comment]
Would love to see this one fixed, I used ESC to get out of logic gate UI and such and always get annoying at the menu popping up :).

**Comment by tsunamayo** [comment]
Issue finally fixed for 20w41a. Thanks!
