### ISSUE TITLE
First person camera on chair clips through window tile wedges when it should't

### ISSUE THREAD

**Issue by IkLam14** [tsunamayo/Starship-EVO#2962]
### Short Description of the issue: When sitting on a chair under window tile wedges head clips through them when 3rd person camera shows it should't
...

### Steps to reproduce the issue: Build a chair under a 1x2 of window tiled wedges and look up in first person then switch to third person 

...

### Environment
- Starship EVO version: ea 20w36b
- Graphics Card: Amd RX 570

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_  
![image](https://user-images.githubusercontent.com/71272652/93098807-f185aa00-f6af-11ea-8341-c49f37aae1cb.png)
![image](https://user-images.githubusercontent.com/71272652/93098840-f9dde500-f6af-11ea-9911-151f259d469c.png)

Please also include the `output_log.txt` file. 
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5219135/output_log.txt)

**Comment by Monstertruck-swe** [comment]
https://github.com/tsunamayo/Starship-EVO/issues/2929
It's been adressed in the upcoming version. If you enable experimental build you'll get the fix now.

**Comment by IkLam14** [comment]
thanks
