### ISSUE TITLE
[Commendation]: I just made the first flight of a starship five kilometers long.  She flew great.  This engine is incredible.

### ISSUE THREAD

**Issue by Whackjob** [tsunamayo/Starship-EVO#2965]
### Short Description of the issue:

https://imgur.com/Uqtnf2W.png
https://www.youtube.com/watch?v=e2QmZJC-EYg

The building part was rough with many weird issues, pasting going inverted into the wall, memory running out, crashes dumping me out into the desktop... but I persevered.  5,043 meters long.

Screenshot of stats: https://imgur.com/pHIp72c.png

### Steps to reproduce the issue:

Build!

### Environment
- Starship EVO version: latest experimental
- Graphics Card: Quadro P5000

### Additional information:

Videos and screenshots already included.  But what the hell, here's the latest save of the ship if anyone wants to try to load it.

[Arkingthaad2Build6.zip](https://github.com/tsunamayo/Starship-EVO/files/5221659/Arkingthaad2Build6.zip)

Tsunomayo, this is also an open truss currently.  I couldn't say why, but I'm getting *better* results than if she'd been enclosed.  So far anyway.

**Comment by StarrKiss** [comment]
This is honestly amazing- Space Engineers crashes at just over 1km.

**Comment by Whackjob** [comment]
What's incredible is the only bottleneck I'm seeing is just things acting up during construction.  If I'm just flying about or messing with a turret or whatever, it's still butter smooth.  Tsuno, I'm still getting like 70~110 fps zipping around that thing.

**Comment by tsunamayo** [comment]
@Whackjob amazing! Good job!
Let me test that.
Pro-tip, if you close the frame you will get better performance ;)
Cheers

**Comment by Whackjob** [comment]
@tsunamayo Please test! I'm interested to hear about your findings.  Speaking from my own experiences, I seem to have better performance with an open frame.  I cannot explain it.  Currently, I am slowly adding armor and internal systems and turrets.

I hope an upgrade to cut-and-paste comes soon, where we can copy and paste child entities, that also carry the settings over as well.  I've got a lot of turrets to make, and only so many decades left of my life to work with.
