### ISSUE TITLE
Out of ship experience

### ISSUE THREAD

**Issue by level70elite** [tsunamayo/Starship-EVO#2968]
### Short Description of the issue:

...Ship freezes in place, player character continues as if still controlling the ship. Leaving the ship results in the player being teleported back to where the ship desynced and the ship is teleported to where to player exited.

### Steps to reproduce the issue:

...Unsure. Possibly having 63 blueprints saved and having many of them spawned all at once.
blueprints were from the steam workshop...

### Environment
- Starship EVO version: 20w36b
- Graphics Card: GTX970

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5223872/output_log.txt)
video of the issue: https://www.youtube.com/watch?v=I05ewmBEFUw

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by tsunamayo** [comment]
Thanks a lot for the video, there is indeed a lot of issues in the log file, I keep you posted. Cheers

**Comment by tsunamayo** [comment]
@level70elite This issue should be fixed in recent update - please ping if it is not the case! Thanks
