### ISSUE TITLE
[Bug] Broken Turrets

### ISSUE THREAD

**Issue by Cheackraze** [tsunamayo/Starship-EVO#2977]
### Short Description of the issue:

Only the forward most turrets work, even though they are connected properly and are identical using the copy and paste tool... even if rebuilt using hinges and giving large amount of clearance space, only the forward turret works

### Steps to reproduce the issue:

only the right side turrets are hooked up in this blueprint I was testing and found that the turrets are broken, the forward turrets on the left and right side work but the others do not and I can't figure out why

### Environment

Starship EVO version: 20w37a
Graphics Card: nvidia gtx 970

### Additional information:

[brokenturrets.zip](https://github.com/tsunamayo/Starship-EVO/files/5239240/brokenturrets.zip)

**Comment by matejkar** [comment]
I had a lot of turret issues but didnt use copy paste so i cant say.
if u dont copy paste and if u did all the connecting well u should have no problems.

**Comment by Cheackraze** [comment]
it is strange because on this blueprint they are all copy and pasted, and the front set appeared to work fine so I continued to  paste the turret and then later learned that the rear 4 are broken and I dont understand why 2 work and 4 dont

**Comment by Cheackraze** [comment]
Ok, even making brand new turrets, by hand, not copy pasted, they are still broken, majorly.  Even on a new save, a new entity, a new turret, its borked.  Im about to give up on the game till the bugs are fixed

**Comment by tsunamayo** [comment]
@Cheackraze Hi, thanks for booking the case. I dont really understand though, copy/paste does not copy command logic and children entity, how are you building those turrets? Thanks

**Comment by tsunamayo** [comment]
@Cheackraze so you are trying to use several turret at once in manual am I correct?
If yes then it is not supported and likely wont work, the manual input means that your mouse movements are mapped to the turret itself. Which means that all the turret will point in various directions, it is wont make a lot of sense. I will prevent the player from linking several turret computer to their yoke so that it is more clear.
Cheers!

**Comment by Cheackraze** [comment]
They are being built one step at a time, only the dozen or so decorative blocks are being copied onto the final entity.  And although the original plan was to have the 3 turrets on each side connected to 1 yoke, it wont work even when only connecting 1 turret.

**Comment by Cheackraze** [comment]
Even when each turret has 1 yoke, they do not work

**Comment by tsunamayo** [comment]
Hi, cool ship btw.
Okay I see for the copy/paste. Your turrets looked fine to me!

So right now what wont work well is one yoke plugged into several turrets. 
I think you should be able to plug several yoke into a single turret though.

I think for your use case you might want to try instead:
 - dont use the camera on the turret. This is what is forcing the raw input mode that is not working well. If you simpy use it without a camera each turret will do their best to look at what you are currently looking (when the camera is mounted into the turret they are essentially locked so thats why it is have to be a different logic)
 - turret in auto-mode. Thats obviously different but that would work.

Cheers

**Comment by tsunamayo** [comment]
Okay as a quick explanation on the three mode:
1) auto tracking. the turret tracks a given target
2) look at: aim at what the player is looking. When activating the turret via a yoke, without a camera (or body locked)
3) raw input: when using a camera or when the player body is locked to a turret axis.

Then you can have a mixed situation: the player body is on the first axis only (horizontal for example). The horizontal axis will be raw input, then the vertical will be look at. That way a turret like the falcon is possible.
https://www.youtube.com/watch?v=fBagc1Ww0_Y&ab_channel=TheStarWarsSaga.com
Here the player seat is on the horizontal axis.
It is all quite complex I admit but it is necessary to deal with all the design possibility, I need to give a better player feedback on how the turret is working.

Thanks

**Comment by Cheackraze** [comment]
From more testing, it seems that the second rotater is not being allowed to move, and is causing the whole turret to be locked in the rear.  The square on the rotator is 'black' where the other ones are mostly red, it seems like it thinks the turret is colliding with something when it really isnt

**Comment by tsunamayo** [comment]
I see - it indeed means that there is something fishy with collisions. I will have a look at it tomorrow.
Do you know since when people saw issues with their turrets?
Pro-tip you can debug Collision Points (and collisions) by pressing F3 / Physics / View Collisions Points. 
Cheers

**Comment by Cheackraze** [comment]
yea ive got it on and I see arrows all up the wazoo on it.  It seems just with the last update or so, just heard from some people that their turrets are getting 'stuck' and that old turrets work but new ones made are buggy, so I dont know when

**Comment by Cheackraze** [comment]
here is the 2nd rotor on front turret that is working:
![20200919084357_1](https://user-images.githubusercontent.com/71046427/93667481-4b8dc300-fa54-11ea-9afd-5850707fd30a.jpg)

and they are identical turrets, it should look more like that but something funny is going on with collision

**Comment by Cheackraze** [comment]
in that blueprint, it is unfinished ship and i had been messing around with the yokes/blueprints/turret settings so I understand where you are coming from, thanks for the explainations though!

**Comment by tsunamayo** [comment]
Okay I have checked this in more detail, there is indeed something fishy - I have yet to figure what it will take more time. I would say the difference between your turrets must be the orientation of the rotator.
I have fixed a couple of issue but it didnt impact your turret, so there is still something to find.
In the rear turret you have to have 0 bricks to get some red. Even a tiny brick will give a full black so there something wrong...
I keep you posted!
Cheers

**Comment by Xenoprophet-Nail** [comment]
I only have an issue with the turret's barrel aligning to the player's eye level when he grabs the yoke, that causes some of my turrets to get locked in place because there's no account for parallax and the barrel aims down into my ship/hovercraft ect. other than that turrets have worked okay for me.

**Comment by Cheackraze** [comment]
@tsunamayo yes I knew that it would not have 100% range as there is a little blockage, but it should have at least some movement.  Thank you for looking at this issue.  My build process is usually 1 step at a time so I place all base rotors first making sure they are same orientation, then move to second rotor on all to make sure they are the same as well.  I have tried to create new turrets from scratch with 0 bricks blocking movement and it still shows black square no movement.  I worked on the ship and got the wing logic down this is what the plan is for the articulated armor plates:

![wing giphy](https://user-images.githubusercontent.com/71046427/93719312-9fc99d80-fb4f-11ea-97ee-9683af89e113.gif)

I'm curious if the game is incorrectly calculating the positions of other child entities and thinking that turret hing is being blocked even though it isn't

**Comment by tsunamayo** [comment]
@Cheackraze hooo I see I should have check that first, they are on a moving children entity... 
This is not really supported for now - I still have the code it.
The problem is that the collisions are baked in a 2D map so we dont do real time collision check, otherwise that would kill performance. 
It is on my to-do list for turrets for a while now (with the rest position), I will try to add it on the short term (my galaxy / holomap update is almost there) as it is something quite a few people want.
The only issue is that every time you will move the children entity the turret will be unavailable for a bit as the collision map is being recomputed.
Cheers

**Comment by Cheackraze** [comment]
That explains a lot of the strange turret behavior I have seen on my builds and others.  I hope this functionality is addressed soon, as I know many designs will have turrets that 'retract' or move in some way.  I believe I will still finish the ship but alter turret design to fixed hardpoints on direct control rotors until this issue gets addressed.

**Comment by tsunamayo** [comment]
@Cheackraze okay I finally had time to do another pass at this after the holomap update.
So the initial issue with children entity is fixed, for 20w40b.
Also I added the recompute on parent move, so retractable turret will also work. 
Will work on the rest position now, and turret will be much better in next update!
Thanks for your help all!
Cheers
