### ISSUE TITLE
Landing position modifier

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#2978]
It would be useful to adjust how an individual ship is positioned within a landing zone. Presently, matching the centre of volume is easy enough when building a dedicated landing pad. But for generic / public landing pads, it could be limiting, as many ships have a centre of volume that is quite different to their centre of mass. Landing gear are normally placed around the centre of mass, and such ships could safely land on pads that are smaller than the ship and/or with significant offset.

It would allow larger ships more choice of landing pads and could (in some cases) improve landing aesthetics. This then allows more design freedom while reducing the burden for every station to have massive pads. Ship level adjustment does not remove the overall problem, but it would soften it and add some finesse.

My suggested implementation is to add a toggle button within the ship computer that selects between "volume centre" and "computer centre". With the computer centre option then using the computer position as the nominal ship centre for landing approach and final landing position. 

Clearly poor/extreme placement of the computer would make the ships effective turning volume larger, so it would have to be used carefully to avoid increasing the collision rate. Conversely by placing the computer low within a ship, its landing approach would be higher than standard, allowing more space for the AI to pick a clean landing path.

An alternative method would be to use a "mass centre" option. But that could be unpredictable once cargo and transferable mass is involved. I think a fixed nominated landing centre is a simple and stable solution.

**Comment by tsunamayo** [comment]
Okay so if I understand your idea correctly it is not really doable: I want to enforce that the size of landing pad is a limit for the size of the ship. There are several reason for this: to make them compatible with AI, and for gameplay.
Ie I do not want a 100m ship to land on a 50m pad...
Cheers

**Comment by cloudrambler** [comment]
@tsunamayo So if ship size is to be constrained by landing pad size, and those are going to be embodied as public locations, then we should have some rationale for defining the size of each, so that a reasonable range of options is made available to ship captains.

For example I would not want to be the guy with a 150m ship if few of the stations have pads bigger that 100m. Likewise it would be frustrating to have a 101m ship and have to wait for the availability of an "oversized" landing pad, if the guys in the 100m ships had more options.

My point is that if we have 50m, 100m, 150m etc. pad sizes, then all the ships will tend to those exact same proportions for efficiency. That would be boring for the game and would introduce a conflict between creativity and convenience.

For me, as someone who wants to invest a lot of time to design a really nice ship, it would be helpful to know what the logical restrictions and sensible opportunities will be. Should I stick to 100m, or will there be fair opportunities for all ships regardless of specific or relative size?

**Comment by cloudrambler** [comment]
An alternative (and perhaps more realistic and fun) approach would be to limit landing pads to a maximum size. Thus any ships larger than this would have to use smaller tenders or shuttles to access stations. Such a hard limit could then be universal and would prevent players from finding unexpected variations from one region to another.

It would simplify station design as the question of how big to build the pads, or what range of sizes to offer, would be nullified. The choice then simply becomes how many pads, or maybe how many large and small pads to offer.

The game already provides a technical means of housing a tender within larger ships. I must say that when correctly set-up the docking mechanic works really well. But it raises the question of security. If you leave your main ship unattended and floating in space while visiting a station, then it would be easy for others to capture it. 

A further suggestion is that for larger ships, we have a remote shipyard. A point in space that a larger ship can fly to and stop. Where it would go offline and be provided with some degree of security by implication of having "docked" to the station. These points could be widely separated, for example on a 1km grid and would have the shipyard style beacon but no bounding box.

So for example the provision could be 50m pads, 100m pads, remote beacon points for anything larger than 100m, with dedicated small pads (maybe 25m) for the tenders. This would then work similarly to a commercial marina.

**Comment by Gliese-832-c** [comment]
Maybe add a dedicated docking connector, similar to the station connector?

**Comment by cloudrambler** [comment]
@Gliese-832-c I think this has been suggested before several times and I agree it would be a very welcome addition to the game.

However using a docking collar does not solve the size definition problem, in fact it could make it worse when you factor in the rules that Tsuna needs to maintain for AI compatibility. You would still need to designate a region externally adjacent to the docking collar, but in that instance the minimum distance would have to be in all directions from that point. So the clear space for docking would be twice that required for an equivalent pad.

This does not necessarily limit designs, but it does mean that we would still have to designate large and specific clearance areas for such docking to be universally suitable (PC & NPC).

It has also been suggested to provide ships with a telescopic docking collar, though this only simplifies the geometry problem and not the size and clearance problem.
