### ISSUE TITLE
Logic gates don't work as intended!

### ISSUE THREAD

**Issue by Gliese-832-c** [tsunamayo/Starship-EVO#2983]
### Short Description of the issue:
Logic gates don't work as intended.

As you can see in the picture, I tried building a 4-bit computer consisting out of 4 full adders using the logic gate system provided with the game.
![grafik](https://user-images.githubusercontent.com/55159077/93720403-06b77880-fb89-11ea-92b5-e6deef7cc19e.png)
(The grayed out areas are irrelevant stuff that I built, please ignore them.)
I quadruple-checked, and it is not an issue with my design, but the game.
Being a new player, I asked the more experienced people on the Discord server for more information, and it looks like I came to a conclusion. Apparently, it was decided, that the logic gates shouldn't be able to process more than one signal per frame/game tick. After more investigation, it was revealed, that that was done, to prevent logic bombs. Now here's the question: Why only a single signal? That limits circuits so much! I understand, that lag needs to be prevented, but why a single signal? Why not ten, or even just five? I'm all for accesibility, but there should be a very high ceiling for those who are willing to go that far. The current system makes anything more complex than an OR-gate, door, and a few buttons impossible. If performance really is that much of a concern, make it an option, or even a hidden option in the debug menu, and slap a fat red warning on it.

### Environment
- Starship EVO version: 20w36b
- Graphics Card: MSI RX 570 8GB Armor OC

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5252463/output_log.txt)

**Comment by MatCat** [comment]
There are a lot of bugs and wierdnesses with logic, complex stuff can be done but you have to inject timers in at some points to get around it, its very annoying as I have been working with some very complex logic stuff and also have hit many walls.

**Comment by Gliese-832-c** [comment]
Yeah, that could easily be circumvented by replacing the one signal limit with 5 or 10 signals. Or make it be a configurable number, so people with better PCs/servers can configure it to their liking. I'm ok with setting defaults for a good player experience for new players, but there should be options to remove those defaults for more advanced players.

**Comment by Doperwt** [comment]
What i have found is that if you(for example) have 3 switches connected to an AND gate and you turn them all on at exactly the same time the AND gate won't update correctly. This extends to other logic gates, i resolved this by injecting timers like MatCat said

**Comment by tsunamayo** [comment]
Seems the same issue as #2980 

@Gliese-832-c I see, I will increase the limit, but the problem is that people will always run into the limit...
What about having a frame delay, how this would impact your logic contraption?
Ie once an input is different the logic gate set itself "dirty" and update itself next frame, but with the input for the previous frame only. So all input are taken into account at the same time.
You seems more proficient at logic that I am, so I am not sure if there would be some negative impact. 

Cheers

**Comment by Gliese-832-c** [comment]
> You seems more proficient at logic that I am, so I am not sure if there would be some negative impact.
Oh, wow, thanks for your compliment. I myself would say that I'm only mediocre...
Your solution with giving gates a "dirty" flag would only impact very very big contraptions, that only a handful of players will ever build. (By making them slower, since if I understood correctly, it takes one frame to send and receive some signals, which means, that if you have hundreds of logic gates, it might take a few seconds.) However, 99.999% of the contraptions out there will work just fine, though.

What could also be done is a hybrid solution. Increasing the limit, and using the "dirty" flag solution past that limit, but I would be happy with just the dirty flag solution, as it would make every contraption that is affected by the problem work (even if, again, very large contraptions, would get slowed down a bit).



Oh, and sorry for going offtopic, but I'm going to have to thank you for replying to issues very quickly and caring about what the community wants. You are a great game developer, and more people should be like you! <3

**Comment by tsunamayo** [comment]
Issue fixed for 20w41a. Little by little the logic system is getting better! Thanks!
