### ISSUE TITLE
A possible chance to further optimize Copy and Paste

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#2988]
So I've noticed when copying and pasting that it makes the placing particles for every single 1m section within the copy. You could have a 16x16 panel and it would show/render the particles for each 1m block within that so 256 times. I haven't tested this with paint or anything else but I'd recommend getting rid of displaying the particles when pasting because I feel that would help the tool out immensely. It can already handle pasting very large sections but this could make it even faster

**Comment by tsunamayo** [comment]
Yes for sure I need to fix this... And a bunch of other stuff. Still a lot to do on the copy/paste side... Cheers
