### ISSUE TITLE
[Question] Youtube Devlogs 

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#2990]
I noticed that it's been quite a while since anything has been uploaded to the YouTube channel, despite all the brilliant updates that the game has a really received on Steam. I think the YouTube channel and the Steam page are both very important in displaying how active and fast paced are development of SEVO is, it would be easy for someone unfamiliar with the game to think that it was not receiving constant updates.

The new galaxy tech would make a beautiful video ; )

**Comment by CaptainKronos** [comment]
I concur. Devlogs and steam page posts would be nice.

**Comment by AlienXtream** [comment]
indeed. something as big as the whole F-ing galaxy deserves to be covered in a video. i understand the slower pace of video updates post release but if anything should be the thing to break the YT silence it should be that :D 

also, a question on the galaxy update. will actual planets be included in that update or will they be added later?

**Comment by StarrKiss** [comment]
Def. later, the planets will be a MAJOR update- he needs to basically create a new marching cubes terrain system (I've done that for a project in Unity- it's very hard), adapt gravity to a spherical planet (which should, fingers crossed, be pretty simple judging by how he's done it so far), write terrain seeding +coloration code, and optimize all the previous to work on a large scale. Marching cubes are very difficult to code with good optimization. @AlienXtream

**Comment by StarrKiss** [comment]
Personally I already think he's a code genius judging by the voxel system, which even Keen Software couldn't make work right and they had FAR more money and a larger team.

**Comment by AlienXtream** [comment]
@StarrKiss i would assume the same but with Tsuna we never know. he has dropped rather big features on us out of the blue so it wouldn't be out of character if he did

**Comment by tsunamayo** [comment]
yeah no still a long way before planets. I will do a steam page post soon on the holomap / galaxy.
Youtube, I still would like to resume it but it takes a crazy amount of time (and energy), and I have a crazy amount of bugs and stuff to tackle... Will see when I can catch up!
