### ISSUE TITLE
[Question] Development organization

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#2992]
This is more of a personal curiosity, but how do you organize the development of SEVO? What is your process for storing good ideas from the community versus ideas you always wanted to add? Is there a priority scale, simple like a number scale or something more complex with time trackers and whatnot? Is this on a word document or do you use a more professional tracker like Trello or Jira?

Or does your cat whisper in your ear telling you what to do. If yes blink twice

**Comment by tsunamayo** [comment]
Yes my cat is doing this, this is cat-driven development process...
I have so much stuff to do regarding the gameplay loop (and thats really the most important thing), and the idea from the community being almost all regarding the building aspect (cant blame you guys, thats a game about this for now), that all these are just less high on the priority list. But I am gonna make a thread to see what is your priority, as I need to catch up on a lot of feature that seems to be much needed (rotator speed, turrets, glass bricks ect).
Cheers

**Comment by ZachZent** [comment]
This was not a question about current development, just how you organize it. Like if I posted an idea about a soft drink role play item and you liked it, how would you record and/or organize it. Many people from solo devs to big companies use organizational systems. For example Jira was one I have used in the past.
![](https://cdn.discordapp.com/attachments/406664114249793536/760061389343031326/Group205.png)
Maybe not the best real life example but I thought it was funny.

Systems like these help organize what needs to be done, their priority, deadlines, etc. I was wondering if you use such a system to organize your thoughts and plans. Or do you just write them on a word document. Or is it just in your head?

Nothing to do with a possible feature, just curious

**Comment by tsunamayo** [comment]
Nope I am not using this. I gave shot at using trello, that was just a huge pain and waste of time  as you need to maintain it. Of course for teamwork you need those, but that a big overhead like meeting and such. This is why as a single man I can get a higher productivity, I can spend more of my time just coding compared to working in team where overhead is much higher.
That being said if a kind soul wants to do something like that for the community suggestion, so you guy can vote for the most requested that could be cool. I dont know if there is a vote feature in trello, jira or else.
Cheers

**Comment by ZachZent** [comment]
Very interesting. Part of what I do (or will be doing) is running different groups, previously using both Jira and Trello and I was curious what your organizational system was.

As for the voting thing, I think it is a good idea-ish. The current system of posting suggestions and bugs to github is great as everything is in one place. Generally suggestions (at least the well thought out ones) are discussed in the Discord first, but any comments of support or opposition would come after which gives a good enough idea on how it is supported. Unless a time comes where there are too many suggestion posts covering up the bugs, I don't think anything needs to be changed. However if you have something you would want a community opinion, I'd just use a google form. Easy to set up, easy to link both here and Discord.

**Comment by tsunamayo** [comment]
@ZachZent Okay I will think about it. thx
