### ISSUE TITLE
[BUG] Ship does not recognize shipyard's child entities

### ISSUE THREAD

**Issue by MadTheDog** [tsunamayo/Starship-EVO#2998]
### Short Description of the issue:
My large Carrier tries to land on the shipyard's struts, (see gif). The struts are the lattice girder large put on hinges, with 3 layers of blocks on top. The ship clips through the child entities until it hits the floor of the shipyard. The struts work if they are connected directly to the shipyard floors, so this seems to be an issue with the child entities.

 
...

### Steps to reproduce the issue:
Have a ship, make it land on shipyard where it touches a child entity connected to the shipyard
...

### Environment
- Starship EVO version: 20w37a
- Graphics Card: GTX 1060

### Additional information:

![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/16719231/94346199-508ddc00-002b-11eb-8ca2-7890345bc0f2.gif)

Outputlog:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5287059/output_log.txt)

**Comment by MadTheDog** [comment]
If you need the blueprints I can send them, it just seemed like github did not accept .mps files

**Comment by CurioInventorium** [comment]
I think if you zip the blueprint files github will allow them to be uploaded here

**Comment by tsunamayo** [comment]
Yes thanks for booking the issue, if you could make a zip that would be great! Cheers

**Comment by MadTheDog** [comment]
Will do, but I don't have access to my computer at the moment, so I'll
probably post it on Thursday or Friday.

man. 28. sep. 2020, 09:41 skrev Francois Duret <notifications@github.com>:

**Comment by MadTheDog** [comment]
@tsunamayo 
Here is the blueprints:
[Blueprints.zip](https://github.com/tsunamayo/Starship-EVO/files/5305941/Blueprints.zip)

**Comment by tsunamayo** [comment]
@MadTheDog Issue fixed for 20w41a. Tell me if it was not fixed (just in case)! Cheers
