### ISSUE TITLE
[BUG] Game Froze After Loading World

### ISSUE THREAD

**Issue by Kadzar** [tsunamayo/Starship-EVO#3006]
### Short Description of the issue:

I had spawned an entity that didn't show up, so when I went to title screen to restart the world it took a while to load, and once it did the game froze

### Steps to reproduce the issue:

I don't know, but I'll include all possibly relevant info I can

### Environment
- Starship EVO version: 20w40a
- Graphics Card: NVIDIA GeForce GTX 1080

### Additional information:
Here's the output log [output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/5306795/output_log.zip)
Here's the world folder [Kadzar.zip](https://github.com/tsunamayo/Starship-EVO/files/5306803/Kadzar.zip)
And this is the ship I was trying to spawn in https://steamcommunity.com/sharedfiles/filedetails/?id=2228635175

**Comment by tsunamayo** [comment]
I dont think it was related to the ship spawn but instead to a drop made.
Fixed for 20w41c! Cheers
Thanks
