### ISSUE TITLE
[Bug] Galaxy map still visible without the holoprojector

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3007]
### Short Description of the issue:
If a holoprojector is deleted when the gorgeous galaxy map is still activated, the map will remain visible with no way to remove it 

![image](https://user-images.githubusercontent.com/27857711/94711846-935bf680-0340-11eb-8c7d-f65bc95befcc.png)

### Steps to reproduce the issue:
Show a galaxy map with the holoprojector 
Delete the holoprojector 

### Environment
- Starship EVO version: 20w40a
- Graphics Card: RX580

**Comment by Gliese-832-c** [comment]
I encountered that issue too.

**Comment by greyseer** [comment]
I can confirm. However, this phantom holo-galaxy does vanish when you exit and re-enter the game. It just seems to persist in that space for the length of your play session (have not tested the full extent of this, yet, however).

**Comment by tsunamayo** [comment]
Issue fixed for 20w40b. Thanks!
