### ISSUE TITLE
[Bug] Mouse position does not reset when the galaxy map is closed

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3008]
### Short Description of the issue:
When closing the galaxy map while piloting a ship, the mouse retains its position so if it was in the corner of the map your ship will suddenly veer off to the side when you close the map. Ideally the mouse should reset to the centre of the screen when you close the map to prevent this

### Steps to reproduce the issue:
Pilot a ship
Press H to open the map and move your mouse to a corner of it
Close the map

### Environment
- Starship EVO version: 20w40a
- Graphics Card: RX 580

**Comment by Gliese-832-c** [comment]
I agree 100% with you that it should be reset, it's very inconvenient.

**Comment by tsunamayo** [comment]
Fixed for 20w40b. Thanks
