### ISSUE TITLE
[Bug] Stickers turning invisible

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3009]
### Short Description of the issue:
Sometimes (seemingly randomly), stickers will turn invisible when other stickers are placed next to them. No matter what, both stickers can't exist as they should at the same time.
I've attached a video of the issue and the blueprint, I hope that it persists between clients

### Steps to reproduce the issue:
Load the blueprint
Hold a sticker in your hand and look at the top wing. Multiple stickers are invisible but still show their boundary box. Replacing and painting them will result in the effect you see in the video

### Environment
- Starship EVO version: 20w40a
- Graphics Card: RX580

### Additional information:
[Invisible Sticker Bug - Stinger Mantis.zip](https://github.com/tsunamayo/Starship-EVO/files/5306987/Invisible.Sticker.Bug.-.Stinger.Mantis.zip)
[Starship EVO Invisible Stickers bug.zip](https://github.com/tsunamayo/Starship-EVO/files/5306988/Starship.EVO.Invisible.Stickers.bug.zip)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5306989/output_log.txt)

**Comment by ProPeach** [comment]
After reloading the blueprint, some bricks are invisible now too
![image](https://user-images.githubusercontent.com/27857711/94714494-1cc0f800-0344-11eb-94d9-b17390c977e0.png)
![image](https://user-images.githubusercontent.com/27857711/94714501-20ed1580-0344-11eb-849e-215d605e41ff.png)
![image](https://user-images.githubusercontent.com/27857711/94714510-24809c80-0344-11eb-9ae7-a512a3b70456.png)

**Comment by tsunamayo** [comment]
@ProPeach Hi, sorry for the necro, do you still get this? Thanks

**Comment by ProPeach** [comment]
@tsunamayo no, I haven't experienced this since the neovox update. I think it's safe to say it's no longer an issue!

**Comment by tsunamayo** [comment]
Thanks!
