### ISSUE TITLE
[Bug] Canopy Placement Widget persists 

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3010]
### Short Description of the issue:
When switching from a canopy tile piece to an empty slot on your hotbar, the placement widget remains on your screen
https://i.imgur.com/tjrPrXE.mp4

### Steps to reproduce the issue:
Hold a Canopy Tile piece
Swap to an empty toolbar slot

### Environment
- Starship EVO version: 20w40a
- Graphics Card: RX580

**Comment by tsunamayo** [comment]
Fixed for 20w40b. Thanks!
