### ISSUE TITLE
Improvements to Workshop Upload/Update system required

### ISSUE THREAD

**Issue by 5URG3** [tsunamayo/Starship-EVO#3014]
### Short Description of the issue:
It is currently extremely difficult to update existing workshop uploads, if not impossible. Even if a player keeps the exact original build in their world, they can not update.

This is extremely irritating for workshop uploaders and has greatly diminished my interest in building as I will likely be unable to update things as more game systems are implemented, nor can I fix problems as they are found.

Please make the updating system simpler. Perhaps a hard link to a local blueprint or something similar.

EDIT:

Further Info

This is where I leave the exact builds I upload

![20201001183820_1](https://user-images.githubusercontent.com/67547581/94845187-3f701100-0417-11eb-9b21-c281ab8c7332.jpg)

![20201001185119_1](https://user-images.githubusercontent.com/67547581/94845235-50b91d80-0417-11eb-9710-4423e5f6add2.jpg)

None of them can be updated now.

![20201001183836_1](https://user-images.githubusercontent.com/67547581/94845296-66c6de00-0417-11eb-9693-c0f16f344409.jpg)

![20201001183852_1](https://user-images.githubusercontent.com/67547581/94845304-6a5a6500-0417-11eb-8512-66b96b2d551e.jpg)

Except the one I uploaded at about 1pm GMT as a replacement for the one i uploaded about 12:30 am GMT

![20201001183908_1](https://user-images.githubusercontent.com/67547581/94845483-a4c40200-0417-11eb-97a9-e68507c444ca.jpg)

...

### Steps to reproduce the issue:
Upload a build to the workshop. Close game. Reopen game about a week later. Update no longer possible despite using the exact same build.
...

### Environment
- Starship EVO version: 20w36b
- Graphics Card: EVGA GTX1060 SC

### Additional information:
This one can still be updated
https://steamcommunity.com/sharedfiles/filedetails/?id=2244708985

But most of these can not be updated:
https://steamcommunity.com/profiles/76561198006667695/myworkshopfiles/?section=items&appid=711980

**Comment by tsunamayo** [comment]
Hi, yes I agree it was on my short term to do list following the holomap, I will tackle that asap.
Btw amazing build, I havent saw you uploaded quite a few more I will check this out!
How about selecting an existing upload to replace? How does this works in SE?
I keep you posted. Cheers

**Comment by daOyster** [comment]
In Space Engineers you have a list of blueprints that you manage inside it's own menu. When you select the blueprint from the list in Space Engineers, it shows a few options for the blueprint including one to replace it with whatever you currently have copied. In Starship Evo I suppose you could make it work instead by replacing the blueprint with whatever the current active ship shown in the codex is. A confirmation when the replace option is selected would also be nice to keep people from accidentally overwriting their blueprints with the wrong ship.

**Comment by 5URG3** [comment]
Thanks for responding so quickly tsunamayo, I appreciate it.

> Hi, yes I agree it was on my short term to do list following the holomap, I will tackle that asap.

This is good to hear. Thank you. 

> Btw amazing build, I havent saw you uploaded quite a few more I will check this out!

Thanks again! I'll update my post over in the Pathfinder-group-build so you can easily view them. I didn't want to bug you with them.

> How about selecting an existing upload to replace? 

Yes, this would be great. If we could view the blueprints located in "Moonfire Entertainment\Starship EVO\Save_Data\Workshop" in-game and replace them with the currently selected creation that would be very useful.

> How does this works in SE?

daOyster has explained this pretty well. If you would like further information I could take some descriptive screenshots in SE. Let me know.

**Comment by WILDCATreactor** [comment]
Uploading a new copy of the BP to steam and deleting the old one is an easy workaround ftm, but you'd be removing any comments and subscribers, so upload it as a Mk2 I guess?

Related question, how do we create variants? do we use a shipyard to place a copy of a BPO and modify that? or would it still modify the original file?

**Comment by tsunamayo** [comment]
@WILDCATreactor Not sure to understand your question on variant? What are variant? You can spawn your blueprint and make a new workshop upload, would that be enough? Thanks

**Comment by tsunamayo** [comment]
@5URG3 feature added for 20w40c. I also added blueprint visibility. Thanks! I will be checking your build soon ;)
