### ISSUE TITLE
[Suggestion] Option to hide rotors and hinges

### ISSUE THREAD

**Issue by francklaballe** [tsunamayo/Starship-EVO#3015]
It appears that the rotors, hinges, rails etc ... are very useful for making complex and elegant shapes to the fuselage of ships.

But sometimes it happens that these "tools" must be hidden or made transparent and with the collision disabled so that they do not spoil the rendering of the design.

I am for example on this type of vessel, I finished the complex shape that I wanted to achieve but the rotors and hinges interfere with the rendering. If I suppress them, the whole structure disappears ...
![CACHER ROTORS](https://user-images.githubusercontent.com/72207932/94816023-83edb380-03fb-11eb-849a-57698ab648de.jpg)

my suggestion is to add an option to the rotors and hinges which allow them to be made transparent and with the collisions disabled. And any time to make them reappear at will by a touch whatever.

I also imagine that this proposal can cause problems of which I am not aware

Merci François de nous faire rever :)

**Comment by TIKIRobo** [comment]
you can also place those rotators inside of your ship as they don't need to even touch the part that you are building. also that ship is looking a bit familiar.....

**Comment by francklaballe** [comment]
If i place them on other position i cant place my shappe on exactly the same position of the image.
a bit familiar ship ??? nooooo   ;)

**Comment by TIKIRobo** [comment]
you should be able too you just might need to use a few more hinges/rotators

**Comment by CurioInventorium** [comment]
You can start a block on the rotator (hinge, whatever...) that acts as an offset to your design. You then build the design on that "starter" block. Once completed you remove that initial block. The rest of the design will just hover in place.
Overall this allows you to position the rotator inside of a structure out of sight.
Although this design method can be considered a bit cursed as it's similar to the clipping method of building.
But, if it looks cool it should be okay.
I guess if there's any build competitions, rules can be put in place as to what methods are allowed :)

**Comment by TIKIRobo** [comment]
no if you delete a child entity creating block it will delete it's child entity

**Comment by CurioInventorium** [comment]
Hopefully this will explain what I mean
![20201001185923_1](https://user-images.githubusercontent.com/51359034/94846431-0afd5480-0419-11eb-8644-e2d039f6238c.jpg)
![20201001185929_1](https://user-images.githubusercontent.com/51359034/94846442-0cc71800-0419-11eb-9e8d-56e4653d96b7.jpg)

**Comment by TIKIRobo** [comment]
yea i do that all the time i though you were saying "delete the rotator"

**Comment by tsunamayo** [comment]
Hi, merci pour l encouragement ;)
So sorry to disapoint you, but for various reason I want to discourage the use of children entity for decorative reason. Plus having transparent block just dont make a lot of sense, so I wont be doing that sorry mate =(
But I am sure you can find a way to hide them (for that design it is too late though...). Also there is a nice selection of various shape that can all be stretched, so I am sure you should be able to do something close enough without children entity at all!
Cheers
