### ISSUE TITLE
Question / suggestion - removing mirror planes

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#3018]
Is there a way to remove a mirror plane from a finished build? They don't show when the mirror mode is off, but it would be better to remove them from the build so they are not always apparent when working on other builds using mirror mode.

**Comment by Aiwii** [comment]
right click on a mirror plane with the mirror tool selected

**Comment by cloudrambler** [comment]
Thank you. I did try that. However I have re-bound the delete function to prevent accidentally vandalising my ships. So I presume the remove mirror plane is actually "delete" mirror plane. I will try again with the re-bound key.

**Comment by tsunamayo** [comment]
Thanks @Aiwii for answering! I hope it is working all good on your side @cloudrambler. Cheers
