### ISSUE TITLE
block grid placement issue

### ISSUE THREAD

**Issue by lordofswarm** [tsunamayo/Starship-EVO#3020]
Description: Unknown effects with other block, using girders in this case. Placing the largest girders to increase length(sum of distance from block start points to new block start point) will eventually result to girders being placed but no further placement grid being generating

Step 1: Create a ship
Step 2: Place large girders(in this case, again unknown if bug effects other blocks) to increase length(sum of distance from block start points to new block start point)
Result: block placement grid will disappear, even though block texture is generated.(there is at least one exception, see screenshots)

Environment:
- Starship EVO version: 20w23b
- Graphics Card: Geforce 2016

Screenshots:
![Screenshot (1)](https://user-images.githubusercontent.com/65051945/94957456-6419c680-04b3-11eb-8d9d-a15c7ed6919b.png)
girder structure(starter ship in background, ship start block placed on that end of structure)
![Screenshot (2)](https://user-images.githubusercontent.com/65051945/94957476-6da32e80-04b3-11eb-820d-c2d852bb8208.png)
normal placement
![Screenshot (4)](https://user-images.githubusercontent.com/65051945/94957493-75fb6980-04b3-11eb-93d0-a0a212c517c5.png)
placement beyond certain point on final girder
![Screenshot (5)](https://user-images.githubusercontent.com/65051945/94957554-8b709380-04b3-11eb-9c5d-79c5e7b25558.png)
abnormal block placement grid
![Screenshot (6)](https://user-images.githubusercontent.com/65051945/94957595-9cb9a000-04b3-11eb-9369-94ee405dd246.png)
placement exception on girder within girder with abnormal placement field

Log:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5319675/output_log.txt)

**Comment by tsunamayo** [comment]
fixed for 20w41a. Thanks for the screenshots! cheers
