### ISSUE TITLE
Galaxy projection remains after removing holoprojector block

### ISSUE THREAD

**Issue by CurioInventorium** [tsunamayo/Starship-EVO#3022]
### Short Description of the issue:
While testing out the holo-projecter block, I decided to remove it only to find that the image of the galaxy remained in place afterwards.
Placing down another holoprojecter and linking it, only created a second overlayed galaxy.
I can't remember, but I think if I unlinked the holoprojector before deleting it, it removed the overlay (with the first one still there)
...

### Steps to reproduce the issue:
Place down a holoprojector, link to it the spaceship block and then delete the holoprojector without unlinking it first.

...

### Environment
- Starship EVO version: 20w40a
- Graphics Card: Nvidia Geforce RTX2060

### Additional information:
The only way I could get the galaxy overlay to disappear was by unspawning the ship.

_(Screenshots, Videos, Error logs, Related issues)_
![Holoproject bug](https://user-images.githubusercontent.com/51359034/94989861-a6a0d900-056f-11eb-9533-e35b7fb650c4.jpg)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by ZachZent** [comment]
Make a good wall decoration

**Comment by Gliese-832-c** [comment]
https://github.com/tsunamayo/Starship-EVO/issues/3007

Already known and fixed.

**Comment by CurioInventorium** [comment]
Ah okay, cool. The issue got closed that fast I didn't spot it. :)

**Comment by tsunamayo** [comment]
Yes it is now fixed in the just released 20w40b. Cheers
