### ISSUE TITLE
[Bug] Half rounded brick can't be placed

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3023]
### Short Description of the issue:
Quick little one, this brick cannot be placed on any surface, regardless of offset or grid orientation
![image](https://user-images.githubusercontent.com/27857711/94997475-4b88d980-05a3-11eb-80ee-375a15bb0c25.png)
(Please don't get rid of it! ;) )

### Steps to reproduce the issue:
Try to place the Half Rounded Brick

### Environment
- Starship EVO version: 20w40a
- Graphics Card: RX580

**Comment by tsunamayo** [comment]
Fixed for 20w41a. Actually it was placed but it had a size 100x too small ;) Ceers
