### ISSUE TITLE
[SUGGESTION] Deletion of single blocks from a panel/stretched block.

### ISSUE THREAD

**Issue by N3XTGEN82** [tsunamayo/Starship-EVO#3025]
If possible it would be really helpful to add a build mode that allows the deletion of one block out of a build instead of the whole stretched panel. And a small version of transparent blocks/glass would be nice.

**Comment by tsunamayo** [comment]
Hi, I can understand why that would be useful, unfortunately it is not possible: it is not several blocks but a single one. Cheers
