### ISSUE TITLE
[BUG] turret targeting messed up after the update

### ISSUE THREAD

**Issue by matejkar** [tsunamayo/Starship-EVO#3028]
### Short Description of the issue:
so i have not tested turrets after the latest turret update until now, and the turrets on all my ship seem to be fixated on one spot, and they ignore ship i targeted, even if they are right in front of the turret. I tried playing around with the resting position setting, but it changes nothing
...

### Steps to reproduce the issue:
for me, it was to take a ship with working turrets, spawn some target ships, target them and watch the turrets have a breakdown
...

### Environment
- Starship EVO version: 20w40c
- Graphics Card: Nvidia Geforce GTX 1060ti 6gb

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5323022/output_log.txt)

**Comment by Asnro** [comment]
Have you tried Auto targeting mode? Turrets on my ship aim and shoot just fine, but every time i re-enter ship control each turret spins to last aim position. The first time this happened each turret spun into completely different directions, I guess because they had no "last aim position".

**Comment by matejkar** [comment]
"freely clipping into ship hull but unable to move further (new target or position reset)" thats what happened to me, and yes i have auto fire on, target settings to spaceship targer, and use resting position off (i dont think set current position as resting position matter is use resting position is off)

**Comment by matejkar** [comment]
that means that every time we enter a ship there is a chance turrets noclip trough the ship and are un-usable... great

**Comment by matejkar** [comment]
yea put everything on auto fire (targeting mode setting), still nothing, although i see your ship works well
i will look into your turret settings but idk why do my ships have problems

**Comment by matejkar** [comment]
now i enabled use turret resting position like u have, now my settings are same as yours, my turret design is way less complicated than yours and they are still stuck and dont shoot

**Comment by matejkar** [comment]
@tsunamayo this issue here is huge, as turrets are mostly completely un-usable now, there are some situations where a turret manages to un-noclip and start targeting normally but its completely random and not frequent at all, now all turrets just noclip into the ship and cannot be used.

**Comment by Asnro** [comment]
could you post your ship's blueprint?

**Comment by matejkar** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2156590615
all of these ships which have turrets dont work

**Comment by matejkar** [comment]
the turrets dont work i mean

**Comment by matejkar** [comment]
@Asnro if u manage to get them working tell me what you did please

**Comment by Asnro** [comment]
Your turrets aren't working because they use hinges - when a hinge is stuck in extreme position it for some reason clips, jamming the entire turret. I tested with a turret built only from rotors and too small to clip through anything and it worked perfectly, including after restart.

![kuva](https://user-images.githubusercontent.com/14952174/95017043-8a7c6500-065f-11eb-8efa-dba88eb8da5d.png)

Something related to the turret resting position mechanic causes turret mechanisms to spawn stuck in maximum angles - hinges at 90, rotors at 360 - and that causes them to clip or jam.

**Comment by matejkar** [comment]
well interesting thing is that on one of my turrets i built very well with no hinges they look normal, but still dont fire.
But before the update my standard turrets with hinges mostly worked normally

**Comment by matejkar** [comment]
"look normal, but still dont fire." i mean the turret doesnt rotate at all

**Comment by tsunamayo** [comment]
@matejkar could you send me a single ship .mps where turret dont works? Both rotator and hinge based turret works for me... Dont send me a collection of 10 ships, all I need is a simple and minimal test case. Cheers

**Comment by matejkar** [comment]
@tsunamayo hi unfortunately i couldn't have sent this earlier as i had school so im gonna send it now

**Comment by matejkar** [comment]
[equalizer class heavy cruiser.zip](https://github.com/tsunamayo/Starship-EVO/files/5327427/equalizer.class.heavy.cruiser.zip)
this ship is probably the best example of the glitch, as it has 16 turrets with a rotor and a hinge and they are easily seen noclipping, but also 26 single turrets with a rotor and a hinge but build like star wars ball mounted weapon systems if you know what i mean, and i personally have no issues with those as they are not long enough to noclip trough the ship.

**Comment by matejkar** [comment]
@tsunamayo if you don't find the bug i will screenshot it, it happens every time i pilot a ship with hinge turrets, also the other hinges on like ramps and stuff seem to work normally

**Comment by matejkar** [comment]
just in case im gonna provide some screenshots
![20201005181300_1](https://user-images.githubusercontent.com/69653738/95105035-dfd77580-0736-11eb-888a-57920dd2a648.jpg)
this is what happens the moment i go pilot a ship
![20201005181321_1](https://user-images.githubusercontent.com/69653738/95105056-ea920a80-0736-11eb-93c5-a8742c515c57.jpg)
the turrets with no rotors are fine.. for now
![20201005181328_1](https://user-images.githubusercontent.com/69653738/95105102-f67dcc80-0736-11eb-98f7-e6297313d573.jpg)
and sometimes turrets noclip directly above or directly below like here
![20201005181510_1](https://user-images.githubusercontent.com/69653738/95105161-08f80600-0737-11eb-815d-f4dfeb66a341.jpg)
however they sometimes do un-noclip themselfes like here
![20201005181516_1](https://user-images.githubusercontent.com/69653738/95105199-17deb880-0737-11eb-9ce5-3fba9285fe11.jpg)
but rotor turrets also get glitched quite easily, although this could be in my turret design
![20201005181521_1](https://user-images.githubusercontent.com/69653738/95105249-2c22b580-0737-11eb-8a8e-d066f79b8a48.jpg)
and here
![20201005181547_1](https://user-images.githubusercontent.com/69653738/95105264-31800000-0737-11eb-820b-86791470f546.jpg)
and the rear large turret can definetly hit the ship i targeted as you can see it extremely elevated in the background

**Comment by matejkar** [comment]
"the turrets with no rotors" i meant with only rotors

**Comment by matejkar** [comment]
![20201005182216_1](https://user-images.githubusercontent.com/69653738/95106087-588b0180-0738-11eb-8453-542109667e90.jpg)

![20201005182509_1](https://user-images.githubusercontent.com/69653738/95106096-5aed5b80-0738-11eb-9ba8-f18f4256e2dd.jpg)
now more guns went online

**Comment by tsunamayo** [comment]
Hi @matejkar , your test case is a bit messy, I am not sure on what is going on.
Does the turret do not work at all? Or they work some of the time?
I tried your ship and it seemed fine on my side.
Thanks

**Comment by tsunamayo** [comment]
@matejkar could you tell me if it works in 20w41a? Thanks

**Comment by tsunamayo** [comment]
@matejkar so you confirm it is fixed for you? Thanks

**Comment by matejkar** [comment]
@tsunamayo yes in 41c turrets work better then ever, great work.  Tho not all turrets return to their resting position after leaving the yoke, and the rotor turrers are still a bit inconsistent in tracking. i will send the blueprint i showed screenshots of later cuz i have school soon.
