### ISSUE TITLE
[BUG] Can't upload to workshop

### ISSUE THREAD

**Issue by matejkar** [tsunamayo/Starship-EVO#3029]
### Short Description of the issue:
It is what it says, i now wanted to post a new build to workshop, i click upload to workshop, the settings were public visibility, and new workshop upload, which was right since i was posting a new ship and not updating. Now the item technically appears on the workshop but no name, no photo or option for photos and i get messages as if its a private post. However interestingly enough it is shown in the workshop folder.
...

### Steps to reproduce the issue:
Try to post something to steam workshop.
...

### Environment
- Starship EVO version: 20w40c
- Graphics Card: Nvidia Geforce GTX 1060ti 6gb

### Additional information:
![image](https://user-images.githubusercontent.com/69653738/95019555-535d8200-0666-11eb-9ad1-1aa55db729b2.png)
![image](https://user-images.githubusercontent.com/69653738/95019602-8b64c500-0666-11eb-8ca0-249ad4a72933.png)
![image](https://user-images.githubusercontent.com/69653738/95019643-ce269d00-0666-11eb-98f3-74c2891fdb29.png)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5323483/output_log.txt)

**Comment by matejkar** [comment]
![Uploading image.png…]()
also it says file not found instead of change visibility setting as wanted

**Comment by matejkar** [comment]
![image](https://user-images.githubusercontent.com/69653738/95020469-a71e9a00-066b-11eb-9c02-280c8a068d8e.png)
also this

**Comment by matejkar** [comment]
update, turns out the reason it didnt work was because there was a space after the name, which apperently bugged out the workshop system

**Comment by tsunamayo** [comment]
Okay good to know, not sure if it is a steam bug or a game bug...

**Comment by tsunamayo** [comment]
Okay fixed for for 20w41a! cheers
