### ISSUE TITLE
[Issue] Problem with large pistons

### ISSUE THREAD

**Issue by SnowyBirdot** [tsunamayo/Starship-EVO#3030]
### Short Description of the issue:
Inability to place hull blocks on pistons of the same scale.

...

### Steps to reproduce the issue:
Place a 1x1 meter piston, and attempt to place a hull block on its end.
This is also replicable by attempting to place a hull block on the rear left piston of the ship included.
[New folder.zip](https://github.com/tsunamayo/Starship-EVO/files/5324262/New.folder.zip)

...

### Environment
- Starship EVO version: 20w40b/c
- Graphics Card: GTX 1050 TI

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5324266/output_log.txt)

If any further information is needed I am happy to help, Xerma a moderator on the discord has also experienced the same issue.

**Comment by tsunamayo** [comment]
Issue fixed for 20w41a. thanks
