### ISSUE TITLE
[Bug] Starter block not seeing blueprints of ships in individual folders [20w40c]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#3036]
### Short Description of the issue:
Blueprints that have been exported using the new individual folder system are not showing up in the list of ships when loading them from the starter block. The .mps file must be manually moved to the Blueprints directory to be loaded.

### Steps to reproduce the issue:
Create a new blueprint and export it. Then place a starter block and attempt to locate the new blueprint in the list.

### Environment
- Starship EVO version: 20w40c
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5329816/output_log.txt)

BTW, sorry for the long absence! My wife works in healthcare and this summer was utterly bonkers. Things are closer to normal now. I'm having a blast checking out all the great new features; copy-paste in particular is going to speed up the process of making ships so much, since we don't have to remake things every time we need them! Thank you! :grinning:

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin hey glad to see you over here! Damn yes I can understand that, I hope it smoother now but by the look of it the second wave will hit...
Copy-paste is still a long way off, I need to work on performance and make it work with commands... It is gonna be essential for turrets and such.
So for this issue what happens is that they are visible relegated to the end after the file in no folders... I will see what I can do.
Ideally I would like a true file management system, so you can organize your own folder as you want for local, and use Steam Category for workshop items.
Thanks

**Comment by tsunamayo** [comment]
So the game will now move all your blueprint from the root to their own folder. In 20w41a. Thanks!

**Comment by Dwarf-LordPangolin** [comment]
Ah, I see! My mistake.

I agree that copy-paste still needs work, but even its current form it speeds things up; turrets can be pasted in two steps instead of built from scratch. I'm redoing the Whirlwind's turrets, and work that used to take me several hours is going to be done in one or less. :tada: 

I'm pasting the housing first, then the barrels. Then just need to wire the logic and add some stickers -- much better than before. If I place all the rotators first, it's even faster. So, thank you!
![20201005212206_1](https://user-images.githubusercontent.com/33041786/95152724-5aae8980-0753-11eb-8287-eba42f0126ca.jpg)

![20201005212221_1](https://user-images.githubusercontent.com/33041786/95153015-06f07000-0754-11eb-841a-e99df4f3acbe.jpg)
