### ISSUE TITLE
[BUG] Further issues with child-entities.

### ISSUE THREAD

**Issue by SnowyBirdot** [tsunamayo/Starship-EVO#3037]
### Short Description of the issue:
Unable to place hull on pistons of any size, or small hinges. No issue with large hinges, or any rotors.

### Steps to reproduce the issue:
Attempt to place a 1x1 cubic meter hull block on any piston, or a small hinge.

### Environment
- Starship EVO version: 20w40c
- Graphics Card: GTX 1050

### Output log:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5330637/output_log.txt)

### Blueprints:

[Small spike.zip](https://github.com/tsunamayo/Starship-EVO/files/5330646/Small.spike.zip)
[Big spike (base hull test).zip](https://github.com/tsunamayo/Starship-EVO/files/5330647/Big.spike.base.hull.test.zip)

### Note:
Sorry for coming with functionally the same issue, I just noticed that there were further issues along the same vein, and found it very prudent to mention them to you. Even if it partly covers something previously mentioned.

**Comment by tsunamayo** [comment]
Hi, issue was already fixed for 20w41a. FYI The smaller sized mechanism cannot work with block though. Thanks!
