### ISSUE TITLE
Unable to see or access far right stars in star map. 

### ISSUE THREAD

**Issue by Cateye13** [tsunamayo/Starship-EVO#3041]
### Short Description of the issue:

Not able to access or see the stars on the far right edge of the galaxy map while accessing through ship.

### Steps to reproduce the issue:
Look at galaxy map on ship.

### Environment
- Starship EVO version: 20w41a
- Graphics Card: AMD Ryzen 5 1600 Six-Core Processor 

### Additional information:

![image](https://user-images.githubusercontent.com/71489947/95185774-010f8480-077e-11eb-96bd-63234aa44b05.png)
Output log:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5332820/output_log.txt)
It was 3am help.

**Comment by tsunamayo** [comment]
Hi, issue is fixed in recent updates. Thanks
