### ISSUE TITLE
[BUG] Exported ships not seen in the starter block

### ISSUE THREAD

**Issue by matejkar** [tsunamayo/Starship-EVO#3042]
### Short Description of the issue:
Im aware that the dev got tons of reports already, but we cannot see out own exported ships in the starter block, only workshop ones. Also i have seen the folders for those ships can be copy-pasted into the workshop folder which should make them spawnable.
...

### Steps to reproduce the issue:
export a ship which is not from the workshop and try to spawn it using starter block
...

### Environment
- Starship EVO version: 20w41a
- Graphics Card: GTX 1060ti 6gb

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5334346/output_log.txt)

**Comment by matejkar** [comment]
@tsunamayo i saw u ask in a previous post, yes everone has this issue

**Comment by matejkar** [comment]
and while not exactly game breaking, its a very big issue for shipbuilders and such

**Comment by MadTheDog** [comment]
A work-around is to upload the blueprint to the workshop as private and then paste them from there.

**Comment by matejkar** [comment]
@MadTheDog yes that's what im doing, but we cannot access non workshop ships, like ones we didnt upload before the update

**Comment by tsunamayo** [comment]
Issue fixed in 20w41b. thanks all!
