### ISSUE TITLE
[Bug] FPS loss when moving pieces in motion [20w41c]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#3046]
### Short Description of the issue:
There is a loss of ~20 fps when pistons or other moving parts are used, even when the attached mass is small. Was not noticeable in 20w41a, think it was introduced in 20w41b.

### Steps to reproduce the issue:
Link piston or other moving part to switch & toggle.

### Environment
- Starship EVO version: 20w41c
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
Smooth 60 fps before flipping switch:
![20201007013053_1](https://user-images.githubusercontent.com/33041786/95295811-5c547c00-083d-11eb-8356-a96c22cdaeca.jpg)

Loss of FPS while the piston is pushing the rack out:
![20201007013055_1](https://user-images.githubusercontent.com/33041786/95295870-71310f80-083d-11eb-8dd1-cc02afaa0ac7.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5338641/output_log.txt)

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin could you send me the blueprint? It is weird! What is your CPU btw? Thanks

**Comment by Dwarf-LordPangolin** [comment]
Here you go! It's the Whirlwind; I'm updating it with the new blocks & giving it another coat of polish. CPU is an Intel Core i5-3570K.

[Whirlwind Destroyer - v5.zip](https://github.com/tsunamayo/Starship-EVO/files/5345489/Whirlwind.Destroyer.-.v5.zip)

(I actually remembered to attach the blueprint this time!)

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Sorry for the lack of update, this issue should have been taken care of with the all the recent physics improvements. Thanks
