### ISSUE TITLE
[BUG] Planets and local Star is gone

### ISSUE THREAD

**Issue by MadTheDog** [tsunamayo/Starship-EVO#3047]
### Short Description of the issue:
The planets and local star has dissapeared in the newest patch. New worlds/characters and reseting does not fix this. I have not tried to re-install the game however, that might fix it.
...

### Steps to reproduce the issue:
Open up a new world and try to find the planets
...

### Environment
- Starship EVO version: 20w41c
- Graphics Card: GTX 1060

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5338985/output_log.txt)
Example of missing planet:
![Gone](https://user-images.githubusercontent.com/16719231/95302488-4fa64700-0882-11eb-86bb-509af8c92e5a.jpg)

**Comment by tsunamayo** [comment]
Okay indeed, I just repushed a build for 20w41c with the fix. Thanks
