### ISSUE TITLE
[Bug] Broken axis on canopy

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#3058]
![](https://cdn.discordapp.com/attachments/406664114249793536/764615440436822016/unknown.png)

For the straight canopy, it seems that it can't be stretched verticaly. Just stretched on the X and Y axis

**Comment by ZachZent** [comment]
Same with the curved canopy

**Comment by tsunamayo** [comment]
Yes it was designed that way, because I didnt imagined that people would do stuff like you did. But I will add the feature! thanks

**Comment by AlienXtream** [comment]
i should like to point out that the technical minecraft community literally use cakes and sea pickles as redstone components. never underestimate the players ability to use things in unintended and novel ways ;)

**Comment by tsunamayo** [comment]
Okay implemented for 20w42a. @AlienXtream yeah I know, this is why I love so much working on this! Cheers
