### ISSUE TITLE
[Suggestion] Range of vision while in seat

### ISSUE THREAD

**Issue by Calvert4096** [tsunamayo/Starship-EVO#3065]
Super minor suggestion, but I couldn't find this mentioned elsewhere: Could the range of vision while seated be expanded a bit?  As it is, I can't look over my shoulder past 90 degrees right or left.  This is somewhat restrictive of the amount of usable space for cockpit switches and buttons.

### Environment
- Starship EVO version: 20w41c

![image](https://user-images.githubusercontent.com/65469633/95793147-d2bc0880-0c99-11eb-91c7-cb75cdbd6c45.png)

**Comment by SnowyBirdot** [comment]
I agree, it'd be very helpful, as the inability to look over our own shoulders can be very hindering.

**Comment by tsunamayo** [comment]
Yeah I could do that ;) Thanks

**Comment by tsunamayo** [comment]
Okay this is implemented for 20w42a. Cheers
