### ISSUE TITLE
[Bug] Unable to click/interact shortly after loading game

### ISSUE THREAD

**Issue by Calvert4096** [tsunamayo/Starship-EVO#3066]
### Short Description of the issue:

Within a few minutes of loading a game, I'm unable to place objects, delete objects, interact with blocks, enter a seat, load blueprints, etc.  Initially seen on an existing save, but I loaded up a new game and the same behavior re-occured within a minute or two (see log).

### Steps to reproduce the issue:

1) Loaded new game
2) Placed starter block onto terrain, added mag-lock and switch
3) Spawned Mistral ship, added mag-lock and switch to its underside
4) Suddenly unable to add new parts or interact.  Movement and build menus appear as normal.
5) Re-loading save seems to sometimes resolve the problem

### Environment
- Starship EVO version: 20w41c
- Graphics Card: AMD Radeon HD 7800

### Additional information:

[output_log - Copy.txt](https://github.com/tsunamayo/Starship-EVO/files/5368113/output_log.-.Copy.txt)

**Comment by tsunamayo** [comment]
Okay that seems like a good mag-log bug, I will try to reproduce and keep you posted! Thanks

**Comment by tsunamayo** [comment]
Hi, issue fixed for 20w43a. Thanks!
