### ISSUE TITLE
[Suggestion] Scripting

### ISSUE THREAD

**Issue by Deeplerg** [tsunamayo/Starship-EVO#3069]
Hi! Are there any plans on introducing scripting to the game? 
It could allow different ships or stations to communicate with each other, leading in much more possibilities on creating more complex and diverse systems. It also could reduce the clutter of having lots of blocks for each plain action. And after all, it's just cool!

**Comment by Aiwii** [comment]
#759

**Comment by tsunamayo** [comment]
Hi, as noted Aiwii it was already suggested so I will close that one! Cheers
