### ISSUE TITLE
[SUGGESTION] QoL Improvement - Hotkey to toggle movement modes

### ISSUE THREAD

**Issue by 5URG3** [tsunamayo/Starship-EVO#3072]
I think movement modes should be cycled via a hotkey rather than the codex menu. Changing via menu is clunky and distracting.

I also think that Jetpack mode is unnecessary.

Pressing hotkey should cycle modes like this:
Walking > Anti-Grav > 6DOF > Walking etc

As a workaround, I am currently selecting Walking mode and using Unstuck Mode to fly, so it's not an urgent issue.

**Comment by TIKIRobo** [comment]
We also already have a radial menu so we could just use that, so hold down MMB then select whatever movement mode you need instead of having to cycle through stuff

**Comment by CaptainKronos** [comment]
I completely agree. Similar to how turning on one's jetpack in SE is done by pressing X, or double tapping spacebar to fly in minecraft creative mode, it should be on a hotkey system. Maybe not a cycle, or if on a cycle then have a second key that allows it to cycle backwards a la grenade swapping in Halo 3 and Halo 3 ODST. Or a radial menu, that works too.

**Comment by tsunamayo** [comment]
Yes I wanted to do just that. Get rid of the menu, get rid of jetpack, then use a key or a radial menu.
Also to auto-activate 6dof when in deep space with no gravity.
Will do it soon actually, it seems it is really confusing for beginner and people are dropping out of the first tuto zone... Thanks

**Comment by 5URG3** [comment]
Good to hear you agree! I still favour a button personally, but the radial menu could work too. I don't know what else is planned for that, but I wouldn't want it to get too cluttered.

Auto-activating 6DOF in space seems like a good idea, but please add the option to override gravity alignment with 6DOF while in gravity too.

**Comment by tsunamayo** [comment]
Now everything is implemented for 21w03b. Thanks ;)
