### ISSUE TITLE
[SUGGESTION] Minor Change - Lower minimum FOV

### ISSUE THREAD

**Issue by 5URG3** [tsunamayo/Starship-EVO#3073]
Can we get a lower minimum FOV in the graphics menu please? 

30-40 degrees is nicer than 50 for screenshots. Gives it more of a cinematic feel.

**Comment by tsunamayo** [comment]
Yes I can do this ;) Cheers

**Comment by tsunamayo** [comment]
Okay implemented for 20w42a. Thanks

**Comment by 5URG3** [comment]
Brilliant! Thank you for such a fast response!
