### ISSUE TITLE
[BUG] Blueprints in "Starship EVO\Save_Data\Blueprints\" are no longer saved in seperate folders, older blueprints are not visible in game

### ISSUE THREAD

**Issue by 5URG3** [tsunamayo/Starship-EVO#3077]
### Short Description of the issue:

Blueprints are no longer being saved in separate folders when exported. Instead the MPS, XML and three PNG files are being saved directly to "Starship EVO\Save_Data\Blueprints\"

Older blueprints saved in separate folders are no longer visible when using a Starter Block to spawn.

### Steps to reproduce the issue:

Save blueprint, view "Starship EVO\Save_Data\Blueprints\"

Use Starter block in-game, load blueprint menu. Blueprints in separate folders are no longer visible.

UPDATE: I briefly played Experimental last night, could this be related? I am currently using stable branch.

UPDATE: Tried switching back to Experimental. Blueprints are visible again. The other test BPs I made in Stable had their file system updated and are in separate folders. Switched back to Stable and all the BPs in folders are no longer on the blueprint screen.

Others don't seem to have this issue, so I think it is related to switching between Stable and Experimental. Hopefully it will be resolved when the Experimental updates are merged in to Stable.

### Environment
- Starship EVO version: 20w36b
- Graphics Card: EVGA GTX1060 SC

### Additional information:
![bpbug](https://user-images.githubusercontent.com/67547581/96113816-9fb58700-0edc-11eb-8ca0-d2f36fa23e00.png)

This is all I can see in game:
![20201015121209_1](https://user-images.githubusercontent.com/67547581/96116135-e658b080-0edf-11eb-8baf-9249edd5f080.jpg)

Output Log
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5384244/output_log.txt)

**Comment by tsunamayo** [comment]
@5URG3 Hi, I dont think the blueprint update is in Default, if you launched Experimental, then stable again then yes you will have issues and wont be able to load your blueprint again...
What kind of blocking issue did you got on Experimental that make you want to go back to Default? Thanks

**Comment by 5URG3** [comment]
@tsunamayo Sorry, I missed this message. 

I uderstand there has been a change to the filing system in Experimental. No problem.

I play mostly on Default so that when I upload my builds they are compatible with the most common branch.

**Comment by tsunamayo** [comment]
@5URG3 yeah make sense as you are a very popular builder, so your ships are compatible with most people version. I will add a build id tag so that people can now if they can load a blueprint or not! Cheers
