### ISSUE TITLE
[BUG] Link tool usage randomly causes game mechanics to freeze

### ISSUE THREAD

**Issue by Facest4b** [tsunamayo/Starship-EVO#3078]
### Short Description of the issue:

I don't know the exact trigger, but randomly when using the link tool, suddenly I can no longer alter blocks or decals, or move ships. I can move my player, enter yokes (but nothing happens), and I can hold F on seats but my character does not get into them. 

The game remains broken until you reload the save. The glitch can happen again on the same save.

I have had this happen three times now. The first was when altering logic links, the second was linking a switch to a maglock and the third (seen in the video) was when linking up turret rotors. Every time it happened directly after using the link tool, but it doesn't happen on the first use of the tool. It happens randomly after a few minutes of use.

### Steps to reproduce the issue:

Start a save and mess around with the link tool until the save breaks.

### Environment
- Starship EVO version: 20w41c
- Graphics Card: RTX 2070 Super

### Additional information:

https://www.youtube.com/watch?v=GftnVnsD224&feature=youtu.be
[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/5384471/output_log.zip)

**Comment by Doperwt** [comment]
I feel like im encountering the same issue. Also can't place or interact with  button/switches after linking something. i added my output log
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5386592/output_log.txt)

**Comment by Calvert4096** [comment]
I'm now wondering if this is the same problem:
https://github.com/tsunamayo/Starship-EVO/issues/3066

**Comment by tsunamayo** [comment]
Hi, indeed it seems to be mag-lock related, I keep you guys posted. Thanks

**Comment by Doperwt** [comment]
I can confirm that i was also working on mag-locks

**Comment by tsunamayo** [comment]
Hi all, issue fixed for 20w43a. Thanks!
