### ISSUE TITLE
[Question/Suggestion] Graphics Optimisation, GPU Overheating

### ISSUE THREAD

**Issue by WILDCATreactor** [tsunamayo/Starship-EVO#3083]
I finally figured out that playing ST:EVO for long durations, especially leaving it idle for 10-20min seems to be strongly correlated with my tower crashing, as far as I can tell, because my GPU [AMD 900 series?] is overheating, shutting down, and remains too hot to reboot for some time.  I leave the system down for several hours to a day out of precaution and don't want to delve too deeply into how far I can push things before I need to drop dosh for another card and a bigger tower.

The question is: how much has the game been optimised and should I expect graphical improvements down the line, or at least a deeper graphics setting option in the menu, or should I be investing in cooling equipment?

**Comment by tsunamayo** [comment]
Hi, are you using v-sync in the graphic settings? If you are not then the game will try to run at max fps, which will means your GPU (most likely) will heat a lot. Thanks

**Comment by WILDCATreactor** [comment]
Ah, okay, I'm used to using an FPS limiter setting, I'll check the v-sync and report if issues continue. Thank you.

**Comment by tsunamayo** [comment]
If you are CPU bound and cannot get to the FPS target of your monitor then the CPU will run at 100%... But if your system crash when running at full load you might have a cooling issue nevertheless...

**Comment by WILDCATreactor** [comment]
Plausible, going from 62c idle to 90c when running evo, other games are only clocking 75-80c, gonna replace the thermal paste and start saving up for a new tower and motherboard, might have to open the current case and apply a box fan until a big move can be effected. Might just put together a new tower entirely, since the GPU is starting to show its age anyways and all the hardware has become outdated.

**Comment by tsunamayo** [comment]
Okay gotcha. Thx
