### ISSUE TITLE
Lattice Girder Large collision not working correct

### ISSUE THREAD

**Issue by Foib** [tsunamayo/Starship-EVO#3084]
### Short Description of the issue:
When placing a "Lattice Girder, Large" block with a length of over 32 the collision only goes up to a length of 32.

### Steps to reproduce the issue:
Build a Lattice Girder Large block with a length of over 32 and test the collision.

### Environment
- Starship EVO version: 20w36b
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![collision](https://user-images.githubusercontent.com/39885511/96312220-721b2b80-100b-11eb-82e8-b0e23b9f2a92.PNG)

**Comment by TIKIRobo** [comment]
i too have seen this bug it also can cause some Z-fighting for me

**Comment by tsunamayo** [comment]
This issue was reported and fixed in 20w41a, in experimental. Thanks!
