### ISSUE TITLE
vehicle won't load but the gravity cube show up anyway

### ISSUE THREAD

**Issue by Yaute74000** [tsunamayo/Starship-EVO#3086]
### Short Description of the issue:
I load the cs beluga from the workshop but nothing happened and I tried to load it up many times but nothing, it's when I used the gravity thing that it showed many cubes in the sky but still no vehicule. I try to reload the game but it doesn't change anything. I could load another ship from the workshop.
...

### Steps to reproduce the issue:
load the cs beluga and use the gravity field generator to see the cube.
[Nouveau document texte.txt](https://github.com/tsunamayo/Starship-EVO/files/5397654/Nouveau.document.texte.txt)

...

### Environment
- Starship EVO version: 20w36b
- Graphics Card: Nvidia GeForce GTX 1660 Ti

### Additional information:
https://cdn.discordapp.com/attachments/271723356795961345/767389888583827486/unknown.png

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\
[Nouveau document texte.txt](https://github.com/tsunamayo/Starship-EVO/files/5397651/Nouveau.document.texte.txt)
`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by TIKIRobo** [comment]
Are you in the experimental branch of the game? if the ship was made in exp and you are not it wont spawn in properly

**Comment by tsunamayo** [comment]
Could you send me your log file and the blueprint, or the workshop list if it is a workship item? Thanks

**Comment by tsunamayo** [comment]
@Yaute74000 the ship can load fine in recent version, so it must be because it was made in experimental and you are using default. I will do something to prevent you from importing a build made with a recent version. Thanks

**Comment by Yaute74000** [comment]
Désolé de ne pas t'avoir répondu, du coup oui c'était bien un problème de
version et j'ai bien pu charger le vaisseau en question !

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le jeu. 29 oct. 2020 à 04:05, Francois Duret <notifications@github.com> a
écrit :
