### ISSUE TITLE
[Suggestion] Heavy Naval Guns - Scalable Width/Height Large Weapon Base

### ISSUE THREAD

**Issue by WILDCATreactor** [tsunamayo/Starship-EVO#3091]
Related to #3087 
Assuming we get a large and small 'Gattling Laser Base', would it not make sense to give the Large Weapon Base the ability to scale on all three axes like a round thruster?  Further, would it be possible to limit that scaling to a 2wx2h limit giving us a third size class of weapon bases?  Then you would have Large, Medium and Small lasers/beams and Medium and Small gattling lasers.  Even Further, once missile-type weapons are added back in you would have a similar spread of options giving us three sizes for Rockets (S - brick), Missiles (M - 1x1xX block), and torpedoes (L 2x2xX block).  At this point, I'd retract my previous submission to add a micro-rocket/missile addon to the system so that gattling lasers remain their own special category and missiles can be differentiated by some other mechanic (likely some sort of missile loadout option and tracking/lock-on tech).

**Comment by tsunamayo** [comment]
Hum I am not sure I want to go down this rabbit hole just yet, after that people would want 3 size for every system block in the game, why not hull too? Leading to gigantism, leading to more lag.
Also rescaling weapon would be a nightmare for addon reason... so it is not on the to-do for now...
Cheers
