### ISSUE TITLE
Experimental FPS drop

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#3093]
### Short Description of the issue:
FPS drop in experimental mode
...

### Steps to reproduce the issue:
Any game running in experimental mode runs with low fps (5~20)
...

### Environment
- Starship EVO version: 20w41C
- Graphics Card: GTX 1660 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

![fps drop](https://user-images.githubusercontent.com/73253472/96771660-58d20080-13b8-11eb-96cf-0d4723526587.png)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5418252/output_log.txt)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by tsunamayo** [comment]
Hi,
So you mean when running in Experimental you get this low FPS, but when you open the same character in default you get much higher FPS?
1) how much do you get in default?
2) What is your CPU?
Could you send me your character folder? I had no fps drop on my side.
Thanks

**Comment by Uncle-Ulty** [comment]
Hi,

An update. I changed to normal game, and made de update. Then I changed to experimental again. When I changed to experimental, there was an avaiable update(???). I started a new game, and the problem disapeared.

Gonna send you the character folder which the problem started.

GPU: GeForce GTX 1660
CPU: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
Memory: 16 GB RAM

[Uncle Ulty 3.zip](https://github.com/tsunamayo/Starship-EVO/files/5419965/Uncle.Ulty.3.zip)

**Comment by tsunamayo** [comment]
@Uncle-Ulty It seems to be related to the drop manager. Did you had a region where you have many many drops (upgrade chips for now)? Thanks

**Comment by Uncle-Ulty** [comment]
My game has been ok since that. But every time I start to get any fps drop, I start a new game, and the problem disappears. The fps drop problem seems to connect to the save game somehow. I just keep creating new save game for each new project I start to build, to avoid further problems.

**Comment by Uncle-Ulty** [comment]
well, I'm having more trouble, again.

I removed the Nvidia configuration for fps cap, and let the v-sync manage my fps...

I get fps drop every time I activate a mechanism, idk why...

and sometimes, I get fps drop on idle.

gonna send you the files
[New Project 3.zip](https://github.com/tsunamayo/Starship-EVO/files/5569137/New.Project.3.zip)
[[ULTY] Minas Gerais v0.0.350.zip](https://github.com/tsunamayo/Starship-EVO/files/5569140/ULTY.Minas.Gerais.v0.0.350.zip)

**Comment by tsunamayo** [comment]
@Uncle-Ulty Issue finally fixed for 20w50a. Thanks
