### ISSUE TITLE
[SUGGESTION] ability to import ships from the spawn menu into the world as random bots

### ISSUE THREAD

**Issue by matejkar** [tsunamayo/Starship-EVO#3095]
I feel like in the world (or should i say universe) there should be more variety of ships, from what i've seen its now only mistral, correlian freighter (the one that is spawned with f8), the blue interceptor thingy and one larger ship (about 60m) if im not mistaken.
I think it would be cool to add the ability to place a starter block, enter it with F key, and have the ability to right click on a ship and select "import as AI" or something along those lines, importing the ship as both civilian and pirate (or having an option to choose that as well.

**Comment by AlienXtream** [comment]
there is the option to spawn a ship blueprint as a hostile AI. its in the ship import menu. as for ship variety its likely we will see some sort of automatic workshop integration for random ships later down the line.

**Comment by tsunamayo** [comment]
@matejkar actually as alien said this option already exists. And yes of course more variety is in the works. Cheers
