### ISSUE TITLE
Ship disappears some when flying

### ISSUE THREAD

**Issue by The64bitdude** [tsunamayo/Starship-EVO#3096]
### Short Description of the issue:
the ship disappears some when you get in it because its made of small blocks
...

### Steps to reproduce the issue:
build `something` really big with small blocks
...

### Environment
- Starship EVO version: newest 21w41c
- Graphics Card: evga geforce gtx 1060 6bg

### Additional information:
![image](https://user-images.githubusercontent.com/71862745/96892333-2a533480-144f-11eb-88bb-029c8e3b4d71.png)
[video]https://streamable.com/ux68au

_(Screenshots, Videos, Error logs, Related `issues)_`

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5423772/output_log.txt)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:

`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by tsunamayo** [comment]
Hi, could you please send me your blueprint? Thanks

**Comment by tsunamayo** [comment]
Hi, I dont think there is any issue, it is simply how the engine works unfortunately. Small bricks are not being drawn at a distance. one must use stretched blocks to alleviate this issue. thanks
