### ISSUE TITLE
the pipe thin block has a bad hitbox

### ISSUE THREAD

**Issue by Doperwt** [tsunamayo/Starship-EVO#3097]
### Short Description of the issue:

If you stretch it out in  a certain direction it bugs out. Namely only the center 1x1 meter has a proper hitbox/attachment, the rest of the blocks placement appears to put the attachment grid on the surface underneath while blocking you from placing there

### Steps to reproduce the issue:

Stretch Thin tile up=== bad hitbox
Stretch Thin tile left === good hitbox

### Environment
- Starship EVO version: 20w41c
- Graphics Card: GTX1070

### Additional information:
build bug was last encountered on:
[Station Landing pad 96x64.zip](https://github.com/tsunamayo/Starship-EVO/files/5426490/Station.Landing.pad.96x64.zip)
Screenshots of bug:
https://imgur.com/a/43bGDuQ

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5426483/output_log.txt)
If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by tsunamayo** [comment]
Fixed for 20w43b. Thanks!
