### ISSUE TITLE
Blast Door bug

### ISSUE THREAD

**Issue by Dzombie96** [tsunamayo/Starship-EVO#3099]
My Blast Doors open and closes if i start my sliding rail, but the Blast Doors arent linked to anything

### Steps to reproduce the issue:
I Linked my Blastdoors with an Query Gate to my rail and deleted the Query Gate after a test.
My Blast Doors arent linked anymore to anything and i build new Blast Doors but if i activate my Sliding Rail the Doors open and close by itself, for no reason
...

### Environment
- Starship EVO version: 20w
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5429671/output_log.txt)
36b
- Graphics Card: 

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5429681/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, do you get this on restart? If you could you send me the blueprint? Thanks

**Comment by tsunamayo** [comment]
Issue fixed for 20w43b. Thanks!
