### ISSUE TITLE
[Bug] New Warp Core Block has overlapping textures when stretched

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3102]
![image](https://user-images.githubusercontent.com/63756057/97067486-8e900880-15b5-11eb-8b1c-2a7abd866c59.png)
I'm pretty sure it's not supposed to look that way.

**Comment by tsunamayo** [comment]
Yep indeed ;)

**Comment by tsunamayo** [comment]
Fixed for 20w43b. Thanks!
