### ISSUE TITLE
[Bug] Home System Pin does not track correctly on the Holomap

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3103]
Version: 43A
It happens both in ultrawide 3440x1440p and regular 16:9 2560x1440p, but looks fine in FullHD.
I assume the home system pin display correctly only in FullHD.
![HK1UCAMxHK](https://user-images.githubusercontent.com/63756057/97067647-60abc380-15b7-11eb-9053-8e57b7fbb223.gif)

**Comment by tsunamayo** [comment]
Fixed for 20w43b. Thanks for being on the ball on this updated ;) Btw you will be massively impacted by the children collision fix =(

**Comment by Kaiser-Indrasil** [comment]
> Fixed for 20w43b. Thanks for being on the ball on this updated ;) Btw you will be massively impacted by the children collision fix =(

For the greater good, sacrifices are necessary. Besides, only my turrets will be affected - the rest of my spaceship still holds, as it uses static entities.
