### ISSUE TITLE
[Bug] The Warp path does not switch to 2D view of the Holomap

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3105]
Version: 43A
More of a suggestion, really - I think it should be hard-anchored to selected stars and stay anchored during the 2D-3D switch animation.
![Bj09DMf8lR](https://user-images.githubusercontent.com/63756057/97067738-68b83300-15b8-11eb-91b8-b0455904f6d9.gif)

**Comment by tsunamayo** [comment]
Issue fixed for 20w43b. Thanks
