### ISSUE TITLE
[Suggestion] Warp destination brackets need to be more visible

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3107]
Version: 43A
First time I wanted to warp I spent like 10 seconds searching for the destination point star. Maybe an indicator arrow at the edge of the screen would be helpful.
![image](https://user-images.githubusercontent.com/63756057/97067833-b97c5b80-15b9-11eb-95db-a54f0a3e1535.png)

**Comment by tsunamayo** [comment]
Yeah I noticed that too. Thanks

**Comment by tsunamayo** [comment]
Implemented for 20w44b. Thanks!
