### ISSUE TITLE
[Bug] Less than 30 FPS in and around the galaxy centre

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3108]
Version 43A sees some pretty substantial FPS drops, sometimes very much increasing the timeframe. I've noticed it when warping to the galaxy core and then warping away from it. At the pinnacle it dropped down to as low as 0.5 FPS.

**Comment by tsunamayo** [comment]
You mean once you are there is has 0.5 fps? Or during warp or something else?

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Hi, do you have a log file for this (I cant reproduce...). Was it in multi? Thanks

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Okay I think I was able to reproduce that one, fixed for 20w43a. Thanks
