### ISSUE TITLE
Starting star system not on galaxy map and unable to find way back

### ISSUE THREAD

**Issue by CurioInventorium** [tsunamayo/Starship-EVO#3110]
### Short Description of the issue:
I forgot to get a screenshot, but the star for the starting area isn't shown on the galaxy map and when I used the debug mode to teleport to any ship and selected a building back on the starter ring, I ended up in an area of space where everything I had been working was there, but no ring and all the planets and start where in a different location.
...

### Steps to reproduce the issue:
Warp to different star, warp back to what looks like the original location and then use the teleport to any ship debug option to teleport to a building.
...

### Environment
- Starship EVO version: 20w43a
- Graphics Card: NVidia Geforce RTX2060

### Additional information:
I've managed to find another ring world to begin building on again and I'll test if things move about returning to the star system I'm going to settle in now.

_(Screenshots, Videos, Error logs, Related issues)_
![20201024115244_1](https://user-images.githubusercontent.com/51359034/97080055-86a18a00-15f0-11eb-9d4b-e28bbc9518b6.jpg)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5432764/output_log.txt)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by AlienXtream** [comment]
hey, at least you HAVE stars on your map :P #3111

**Comment by CurioInventorium** [comment]
lol, I just reloaded my save and I'm floating in deep space with none of the buildings or ships that where in my initial screenshot present.
Guess I'll have to spawn in a ride and find out where things have gone. Unless space pirates had gotten there first :D

**Comment by AlienXtream** [comment]
so... predictably, this also happens when you die... i love bugs XD

**Comment by CurioInventorium** [comment]
Started a fresh game and spawned in a ship with warp capability. Upon controlling the yoke I find that a star system is already selected.
When I go to the galaxy map the star I'm current at is not shown.
![20201024130236_1](https://user-images.githubusercontent.com/51359034/97081311-7fcb4500-15f9-11eb-9d41-11b3f6f36722.jpg)


Here's the map in 2D version
![20201024130306_1](https://user-images.githubusercontent.com/51359034/97081320-9376ab80-15f9-11eb-9f7f-6184ddcff957.jpg)

Here's a fresh output log from the newly started game
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5432850/output_log.txt)

**Comment by CurioInventorium** [comment]
I've had to abandon my previous save as I can no longer teleport to any of the buildings or ships I had before. It's like the game has deleted them.

**Comment by tsunamayo** [comment]
@CurioInventorium you cant go back to the original system - I should make that clear as stars are stored differently.
Also if you are on a new system, then the normal behavior is to not see any of the previous system ships... The bug is that you were able to see them after the warp. The behavior after game reload is correct.

I keep you posted.

**Comment by CurioInventorium** [comment]
Referring to my original post, I'd used the F3 debug option of "teleport to any ship" and chose one of my buildings to teleport to. That's when I saw all of my ships and buildings from the starting system, but no ring.

**Comment by tsunamayo** [comment]
So starting from 20w46a it is recommended to move to another system as the older starting system wont work properly.
Tell me if you have issue getting back to your ship, there is a trick to load ship that were not exported as blueprints. Thanks
