### ISSUE TITLE
[Bug] stars gone from map

### ISSUE THREAD

**Issue by AlienXtream** [tsunamayo/Starship-EVO#3111]
### Short Description of the issue:
i appear to have accelerated the heat death of your universe Tsuna :/
![image](https://user-images.githubusercontent.com/12606809/97080035-36ecae00-1644-11eb-99b2-53062261800f.png)

### Steps to reproduce the issue:

idk. i just booted up the game, started a new save (i do that, just in case), added the bits to one of the starter ships and after some faffing about figuring out how to control the map made a jump. next time i opened the map *poof*. no stars for me 😔

need to find a more sustainable method of interstellar FTL that DOESN'T drain all the entropy from the universe 😋
### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5432767/output_log.txt)

Edit: yes... i forgot the damn title >.<

**Comment by AlienXtream** [comment]
oh, i also cant zoom out anymore

**Comment by CurioInventorium** [comment]
I did get that briefly when I zoomed right in, so that it allowed me to switch to 3D rotation of the map. It seemed to fix itself after exiting the map and then going back in. Does clicking on the 3D->2D button work?

**Comment by AlienXtream** [comment]
no, its persistent. i was also able to reproduce it after a reload. im not 100% sure what i did cos i was kinda still fumbling the controls but i THINK i left clicked off a star after calculating a route

**Comment by AlienXtream** [comment]
aaand... now im adrift in space with no way to stop and no way to target anything. it was like i overshot my destination O.o
![Uploading image.png…]()

**Comment by AlienXtream** [comment]
and yes, i had control of my ship's orientation. and yes, it was SUPER laggy cos of the huge numbers it was calculating

**Comment by CurioInventorium** [comment]
I spawned a ship to try and fly to a star and the autopilot glitched out, allowing me to control the ship again. But then it just stayed at warp (without the warp effect) and if I get out of my chair the ship flies off without me at warp.

**Comment by AlienXtream** [comment]
i could get out. this is actually one of the few glitches that actually legit scares me when i think about it. not from a technical standpoint but from the "if this were real" standpoint. the idea of being nowhere. trapped in the infinite void, so near to everything and yet so far out of reach. i coined it "vacuophobia", literally "vacuum fear". actual meaning being "the fear of nothingness"

**Comment by tsunamayo** [comment]
Hi, yes there is some error in the log, I will keep you posted. Thanks

**Comment by tsunamayo** [comment]
@CurioInventorium I would like to know what happened. Do you have the log file?

**Comment by tsunamayo** [comment]
Fixed for 20w43b. Thanks guys!

**Comment by CurioInventorium** [comment]
> @CurioInventorium I would like to know what happened. Do you have the log file?

I think the log for that session is attached at the start of #3110
