### ISSUE TITLE
[BUG] all ships disappeared from world 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3114]
### Short Description of the issue:
all ships in my world have just disappeared 
also the ships i have made now are under the ships from the workshop making it harder to find them 

### Steps to reproduce the issue:
I have no idea
...

### Environment
- Starship EVO version: 20w43a
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5433055/output_log.txt)

**Comment by tsunamayo** [comment]
It seems that you like to put space at the end of your blueprint name, and windows dont like it. I will see what I can do. Thanks

**Comment by TIKIRobo** [comment]
ahh ok i'll try to stop doing that then

**Comment by tsunamayo** [comment]
@TIKIRoboTo confirm, there is two separated issues:
1) blueprint that do not appear => this will be fixed for next update 20w43b.
2) ship in the world not there.
 => Did you warped to a new location?

That your blueprint appears after the one from the workshop is normal though and unrelated.
Cheers

**Comment by tsunamayo** [comment]
Actually I managed to reproduce, it was on a new character creation, on the first save and quit / reload. Fixed for 20w43b! Cheers
