### ISSUE TITLE
[BUG] all star disappear from starmap 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3115]
### Short Description of the issue:
all stars disappear from the map needing a restart 
...

### Steps to reproduce the issue:
double click on a star 
...

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5433083/output_log.txt)

**Comment by AlienXtream** [comment]
#3111

**Comment by tsunamayo** [comment]
Did you made something special? Was it after a quit to title and back in game? Thanks

**Comment by TIKIRobo** [comment]
nope i just double clicked on a star shortly after rebooting the game

**Comment by tsunamayo** [comment]
Okay issues fixed for 20w43b. Cheers
