### ISSUE TITLE
[Bug] Game soft-freezes when attempting to enter warp

### ISSUE THREAD

**Issue by StarrKiss** [tsunamayo/Starship-EVO#3116]
### Short Description of the issue:

When I select a star after computing travel path and click "engage warp jump" the game freezes, but OTHER ships move- mostly its user input thats locked out. However, there is NO warp effect, it is a frozen view of whatever the player was doing right before clicking:
![image](https://user-images.githubusercontent.com/13007697/97086950-1d1f7c80-15ec-11eb-9be3-50386ba66cea.png)
Pressing X cancels this succesfully and you can continue playing. EDIT- this only happens if you MIDDLE CLICK on the option, if you click on it NORMALLY, it works as intended. EDIT 2- It sometimes happens with normal click, sometimes with middle click, just SOMETIMES.
### Steps to reproduce the issue:

1. Press H and select a star + compute warp
2. Engage autopiliot with/middle click

### Environment
- Starship EVO version: 20w43a
- Graphics Card: GTX 1070 ti

**Comment by tsunamayo** [comment]
Hi, could you send me the log file? Cheers

**Comment by tsunamayo** [comment]
Also I am not sure to understand, to select something you have to Hold Middle Click, and release on the option of your choice. So I am a bit confused... thx

**Comment by StarrKiss** [comment]
@tsunamayo  The menu gets stuck open sometimes letting go of middle-click and then I can click on things- also the output log is also linked in  #3117

**Comment by tsunamayo** [comment]
I think it was because of auto-pilot planet avoidance. Issue should be fixed for 20w44a. Thanks!
