### ISSUE TITLE
Cancelling a warp jump in progress (pressing 'x') breaks further warp jumps

### ISSUE THREAD

**Issue by CurioInventorium** [tsunamayo/Starship-EVO#3120]
### Short Description of the issue:
As part of testing I decided to warp to another star system. Everything initiated okay, including the warp effect.
I then noticed the autopilot message on the side saying that I could press 'x' to cancel. So I pressed it.
The ship fell out of warp and I was able to fly the ship normally.
A quick check of the galaxy map seemed to show that I hadn't moved, but there was no nearby star.
I decided to resume the warp jump to my selected star. The progress bar appeared and did its thing, then no warp effect happened. Only the speed went to Mm/s and I could still move the ship about, with what appeared to be no progress to the selected star.
...

### Steps to reproduce the issue:
- Control ship via yoke
- Select star in galaxy map
- Interact with star and choose initiate warp
- During warp press 'x' to cancel autopilot
- Reinitiate the warp jump by interacting with the star

...

### Environment
- Starship EVO version: 20w43a
- Graphics Card: NVidia Geforce RTX2060

### Additional information:
I'll start up the game again and see if warp will work.

_(Screenshots, Videos, Error logs, Related issues)_
![20201025095008_1](https://user-images.githubusercontent.com/51359034/97104073-c330bc80-16a8-11eb-8714-f2cd56139c0b.jpg)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[02 cancelled warpjump output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5434436/02.cancelled.warpjump.output_log.txt)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by CurioInventorium** [comment]
I just noticed in the screenshot that even though I'm supposed to be in warp, the autopilot message hasn't appeared on the right as it normally does.

**Comment by CurioInventorium** [comment]
Went back into the game and using the same ship tried to warp to a different star.
The progress bar and autopilot messages appear, but then there a bit of a jerk to the ship and the HUD circles move all round the bottom of the screen.
The ship speed is in the Mm/s.
When I cancel autopilot the speed stays in Mm/s.

I went to the galaxy map to select another star only to find that my location was showing that I had arrived at the initial star I selected.
Selecting a new star and initiating a warp jump results in the same situation as above.

I then got up from the yoke and tried to move about the ship. As soon as I crossed a boundary point between two gravity blocks the ship clipped away from me moving at Mm/s speed.

Spawning in a new ship results in the same situation occuring again.

I'm going to start a fresh game and see what happens when I don't interrupt the autopilot (at all!)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5434471/output_log.txt)

**Comment by tsunamayo** [comment]
@CurioInventorium Yep the autopilot cancel is broken for the warp, I will disallow that during the warp in next patch. Thanks

**Comment by CurioInventorium** [comment]
Cool okay. I'll be careful with the cancelling further autopilots and test other aspects of the game instead.
I need to set up a new base of operations if the starter area get wiped when leaving it.

I guess the player character can be considered lost to the warp :)

**Comment by matejkar** [comment]
https://github.com/tsunamayo/Starship-EVO/issues/3112 same

**Comment by CurioInventorium** [comment]
I have found that when the warp jump bugs out, if you wait a while you do arrive at the system.

**Comment by tsunamayo** [comment]
So in 20w44a you wont be able to cancel warp. Thanks!
