### ISSUE TITLE
[BUG] Dying in another system doesn't respawn you correctly

### ISSUE THREAD

**Issue by David184** [tsunamayo/Starship-EVO#3121]
If you die in a system and your medbay is in another system. Entities would load but things like planets, ringworld, star and that system's skybox wouldn't load and would use the skybox from the system you died in. also when respawning in another system the game's framerate gets really low for a short period of time.

Version: early-access 20w43a
Graphics card: NVIDIA GeForce GTX 1660 Ti

![20201025124202_1](https://user-images.githubusercontent.com/51233566/97106196-6e993b80-16c0-11eb-9be4-505370f6f76e.jpg)

**Comment by tsunamayo** [comment]
This is now correctly supported in 20w45a. Thanks!
