### ISSUE TITLE
[BUG] Pistons sticking

### ISSUE THREAD

**Issue by SnowyBirdot** [tsunamayo/Starship-EVO#3127]
### Short Description of the issue:
Large pistons are getting stuck on a ship of mine, that to my knowledge should not have any collisions.
...

### Steps to reproduce the issue:
Actuate the pistons via the lower switch, on the left, or just, use pistons separately.
...

### Environment
- Starship EVO version: 20w44a
- Graphics Card: Nvidia GTX 1050 TI

### Additional notes:
I am using the weight workaround, though I don't think it is the cause, given how often I use it, and the fact that this has never happened before.

Output log:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5440156/output_log.txt)

Blueprint:
[Vertical proto 2.zip](https://github.com/tsunamayo/Starship-EVO/files/5440171/Vertical.proto.2.zip)

**Comment by SnowyBirdot** [comment]
So, I've been fiddling around, and it only appears to be while it's vertical. I think the engines might be colliding with the main cockpit because when It's rotated differently it seems to work fine.

**Comment by SnowyBirdot** [comment]
I found it! I misjudged my engine locations! My apologies, it was just clipping.

**Comment by tsunamayo** [comment]
@SnowyBirdot glad you figured it out! cheers
