### ISSUE TITLE
 [Suggestion] A glass decal that could make blocks transparent

### ISSUE THREAD

**Issue by arbiter3904** [tsunamayo/Starship-EVO#3128]
- What if Tsuna were able to make a glass decal that could make blocks transparent (with maybe a glass texture) on the area of a face covered by said decal?

- Essentially making glass 'paintable', This would in theory open up a world of opportunities for make cockpits without clipping

**Comment by tsunamayo** [comment]
Hi, thats a fun suggestion but unfortunately not possible with the rendering tech (and with any rendering tech to be honest). Cheers
