### ISSUE TITLE
[Bug] Ghost blocks on child entities  

### ISSUE THREAD

**Issue by arbiter3904** [tsunamayo/Starship-EVO#3130]
- The anti-clipping causing issues by make "**Ghost Blocks**"

______________________________________________________
Steps to reproduce the issue:

1. Place a Rotor, Hinge, Rail.

2. Then try to place a block onto [**said block above**] as a child entity, while it is next to a parent block.

3. Once you try to build anything, lets say a cockpit as a child entity while next to the parent block it will just show up as red and you will not be able to place.

...

______________________________________________________
- Starship EVO version: 20w43b
- Graphics Card: NVIDIA GeForce GTX 1070

______________________________________________________
Screenshots:
![Evidence 1](https://user-images.githubusercontent.com/73545229/97371245-b11d6c80-18a8-11eb-92b2-3dd0a9eddc5e.PNG)
![Evidence 2](https://user-images.githubusercontent.com/73545229/97371251-b2e73000-18a8-11eb-8b42-b8ff1adf0f7d.PNG)

______________________________________________________
The `output_log.txt` 👍:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5448579/output_log.txt)

______________________________________________________
Blueprint to reproduce Bug:
[111.zip](https://github.com/tsunamayo/Starship-EVO/files/5448595/111.zip)

**Comment by tsunamayo** [comment]
Thanks for the case, it is fixed for 20w44b. Cheers
