### ISSUE TITLE
Entities built in experimental branch don't spawn into stable branch.

### ISSUE THREAD

**Issue by Sebateses** [tsunamayo/Starship-EVO#3131]
Before I start i am mainly wondering if this will even be an issue once next major update to the stable branch comes through as it only happens in 20w36b. Main reason I ask is I have spent a lot of time on some builds in 20w44a and it would be a shame if they aren't compatible with the next stable branch update and cannot be spawned in. So I guess this may be more of a question than a bug report but i'm not sure.

### Short Description of the issue:

Anything i build in experimental mode will not spawn into stable branch.

All that spawns in is the text on the speedometer. No blocks at all. This is separate to the blueprint folder changes issue, as I did  unpack the folder to get it to appear in the starter block menu.

![SevoSpawnIn](https://user-images.githubusercontent.com/72846347/97399148-98f92c00-1940-11eb-88cd-c1d857f26ed2.jpg)
...

### Steps to reproduce the issue:

I have attached the blueprint I tried to spawn into stable branch as well as output log file if needed.  Just see if you can spawn it into 20w36b.

to be clear 

Only Stable builds spawn into 20w36b Experimental branch builds do not.
Stable builds and experimental builds spawn into 20w44a without any problems. 
...

### Environment
- Starship EVO version: 20w36b
- Graphics Card: NVIDIA GeForce GTX 1060

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5449976/output_log.txt)
[Hierax.zip](https://github.com/tsunamayo/Starship-EVO/files/5449982/Hierax.zip)

Loving the game so far great job!

**Comment by AlienXtream** [comment]
interesting. i mean, its better than what i expected. i just assumed it would crash due to missing blocks (unless tsuna added a failsafe for that sort of thing). ofc im only ASSUMING that would happen and even so that works off the assumption you had new blocks on the ship. either way, while forward compatibility is more important some level of backward compatibility especially in the cases of missing blocks is a good idea so that not only can stable branch users spawn experimental branch builds but (and arguably more importantly) when modding eventually happens having the game not crash when loading something with invalid or missing blocks would be preferable :P

**Comment by mxdanger** [comment]
Quick question: does the ship appear after you go to menu and start up the world again? I'd had problems on stable where a ship would only spawn halfway or not at all and you need to basically rejoin for it to load in.

**Comment by Sebateses** [comment]
@AlienXtream yeah its probably just a failsafe thing, it does have a turret on a child entity which I could be wrong but i dont think its supported in the stable build. Apart from that it has none of the new blocks like the holomap or warpdrive.
I thought it could be the hinges since i messed around the speeds of them and I know that the speed feature is not in the stable build either. I also tried removing every moving part so it was just a hull and that didnt work either.
Like you said forward compatibility is important so i'm hoping this wont even matter on the next major update.

@mxdanger nah its not ghost block issue i've had that and resolved it before. nothing is there upon reloading.

**Comment by tsunamayo** [comment]
Actually I dont have two branch code wise, it is just the default that is lagging behind experimental.
So if you build in experimental at one point it will import correctly in default (when the default catch up basically)
Cheers

**Comment by Sebateses** [comment]
Thanks Tsuna, I think i get what you mean. Once default is up to date it should be fine.
