### ISSUE TITLE
World and progress was wiped

### ISSUE THREAD

**Issue by Sekiberius** [tsunamayo/Starship-EVO#3134]
### Short Description of the issue:
I was tinkering with logic loops and what not and suddenly couldn't build or do anything, so I shut it down and restarted it, then when I loaded back in I noticed everything was gone, tens of hours of work gone.
...

### Steps to reproduce the issue:
use logic gates till you can't do anything then restart the game
...

### Environment
- Starship EVO version: 20w43b
- Graphics Card: RTX 3080

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5451490/output_log.txt)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by Sekiberius** [comment]
Update: so i checked the save file, the entities are still present within the world but when i spawn them as blueprints they are all bugged out, however I created a new world and the spawned just fine in the new world, so I stand to believe the save file of that world is bugged.

**Comment by tsunamayo** [comment]
So, sorry to hear that, could you please zip me your character folder and upload it here, I will have a look at it!
Cheers

**Comment by Sekiberius** [comment]
[JYSK.zip](https://github.com/tsunamayo/Starship-EVO/files/5451840/JYSK.zip)

**Comment by Sekiberius** [comment]
and i think this entity was the one i was working on when the issue arose as it's one of the only 2 entities that don't load when I spawn them as blueprints 
[6785B7C-62B3A.zip](https://github.com/tsunamayo/Starship-EVO/files/5451874/6785B7C-62B3A.zip)

**Comment by tsunamayo** [comment]
Sorry I had to fix some serious issues regarding the warp and multiplayer, I keep you posted! Cheers

**Comment by tsunamayo** [comment]
Hi, sorry it is strange indeed there is only a single destroyed entity in that world.
For the last blueprint, I can load it just fine. I fixed a save corruption issue with query gate in the upcoming patch, so I guess that in 20w46a you will be able to import that blueprint fine.
I hope you were able to load the other blueprints just fine!
Thanks
