### ISSUE TITLE
[Bug] Warp Core is a Shield

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#3135]
![](https://cdn.discordapp.com/attachments/406664114249793536/771183969117929512/unknown.png)

Also whatever words are on the bottom overlaps with the text

**Comment by AlienXtream** [comment]
ah. reusing objects to create new blocks. always interesting. :P
also, same is true of the C&P tool. its _apparently_ a connector tool XD
fairly sure this technically comes under "localisation" though as it has no effect on functionality. the text overlapping is however a problem

**Comment by tsunamayo** [comment]
Indeed! Fixed for 20w44b. Cheers
