### ISSUE TITLE
[BUG] Motion sickness, input lag, and full screen bug

### ISSUE THREAD

**Issue by falco708** [tsunamayo/Starship-EVO#3136]
### Short Description of the issue:
ship rotate by it's own and we can't press a magic key to align it so when you get out from your seat it keep moving and you are never align with your ship perfectly, the ground on Ring also do not feel aligned but I guess it's because it's never flat

when you look around with your mouse there is a "smooth" effect and input lag (I feel like it may be unity related for some part)

those two cause motion sickness

also there is the mouse cursor that I can't hide it always appear in the middle of my screen I need to turn up steam overlay and hide it to remove finally the mouse cursor, but it come back everytime I open TAB

lastly this is the less important issue I have but still painful if I need to change my settings: it's painful to set up screen rez + refresh rate + V sync, everytime I try the game (or Unity) just goes like "oh you want v sync ? it's only avilable in 1160x720p" or "oh you want 2k rez ? ok but let me turn off full screen and then turn it on and while  you can't see anything because your screen is black because windows suck, I'll turn off Vsync and also change the rez back to a little square" 
...

### Steps to reproduce the issue:
use my computer: 3440x1440 100hz monitor + windows (8.1)
...

### Environment
- Starship EVO version: 20w36b
- Graphics Card: 1080Ti 

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5456095/output_log.txt)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by tsunamayo** [comment]
Hi, sorry let me get back to you on that one!
