### ISSUE TITLE
Bug: Turrets stuck after 1 sec moving, blocks cant be placed at random places

### ISSUE THREAD

**Issue by Zenti98** [tsunamayo/Starship-EVO#3140]
### Short Description of the issue:

Hi there! first of all sorry for my bad english,

using experimental version but the issue is new since the last update I think:
All turrets in game are stucking, they move without any prob for 1-2 secounds until they stuck. If you enter the yoke a second time, they move again for 1 sec and stuck. Another turret with same structure turns without problems but doesnt move up and down....
Theres any working turret since the update. The issue varries, e.g. sometimesthe turrets stuck after 5 sec

Furthermore since yesterday for the first time (playing nearly every day), I can't place blocks at some places but its so random. in this case the preview of the block I want to place is red without reason, it doesnt depend on the type of the block.
It's mostly next to engines, hinges, rails or pistons but it doesnt have to be connected with it!

There are several minor too bugs but I forgot that I am using the experimental version and it's the first alpha I am playing, so thats fine!
And thats maybe because of the size of the project I am working on

You asked me on steam, wether I used children entity clipping - don't know wthat children entity exactly means, could you explain this for me?
Thank you very much for support!
...

### Steps to reproduce the issue:

Build a turret with 1 Engine at the bottom and e.g. 2 hinges and 4 gun barrels, connect everytrhing - it won't work fine.
Block problem is very random....

### Environment
- Starship EVO version: 20w43b Experimental
- Graphics Card: GEFORCE RTX 2060

### Additional information:

Can't show you the blueprint, github says to me it doesnt support the file?...

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5464568/output_log.txt)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints

**Comment by Battlepixel** [comment]
> using experimental version but the issue is new since the last update I think:
> All turrets in game are stucking, they move without any prob for 1-2 secounds until they stuck. If you enter the yoke a second time, they move again for 1 sec and stuck. Another turret with same structure turns without problems but doesnt move up and down....
> Theres any working turret since the update. The issue varries, e.g. sometimesthe turrets stuck after 5 sec

I have the same Problem with the Experimental for weeks. 
I have this problem with all turrets, regardless of whether they worked before or whether they came from the workshop.

This is related to the Bug thats mentioned in the comments of #3051

**Comment by tsunamayo** [comment]
@Zenti98 Hi thanks for booking the bug! I would need your blueprint to investigate any turret related issues! 
The placing bug is fixed in 20w25a. Patch is landing soon!

Children Entity =>When you build a rail, rotator or hinge, a new secondary entity is built and attached to the main parent entity. We call these children entity!
You can check some debug info in the F3 menu: In Physics there is "View Entity Bounds" and in 20w45a "View Entity Colors", it can help you to debug some situations.

@Battlepixel Is it the one from the comment? Thanks

**Comment by Battlepixel** [comment]
> @Battlepixel Is it the one from the comment?

Yes and its not blueprint-related.

The bug occurs as soon as one of the turret axles is not the full angle of the hinges or rotators free. No turret works that has a stop/contact-point on some axis.

**Comment by Zenti98** [comment]
@tsunamayo Ahh thank you very much for your help! I think you need a zip right, hope this works:?
The project is really big, might take 1-2 min spawn time^^

[Alpha0.1.zip](https://github.com/tsunamayo/Starship-EVO/files/5479935/Alpha0.1.zip)


One question; why does the symmetry and copy paste tool not copy children entities? For example - I want to put many details on my turrets and I have to do this more than 48x Its work for couple of days - if I could use the symmetry tool for this, it would be so nice - alsoin my hangars I use hinges for slants and on each hinge I have to put the further details, is that by design?

**Comment by Zenti98** [comment]
> > @Battlepixel Is it the one from the comment?
> 
> Yes and its not blueprint-related.
> 
> The bug occurs as soon as one of the turret axles is not the full angle of the hinges or rotators free. No turret works that has a stop/contact-point on some axis.

Ahhh yeah this makes sence because two of the hinges of my turrets rest in 0° positon!

**Comment by tsunamayo** [comment]
@Battlepixel so it seems to be related to the use of dual secondary axis turrets. I keep you posted once it is fixed.

**Comment by tsunamayo** [comment]
@Battlepixel Hi, so I fixed the issue for 20w45b. I will see if that fixes @Zenti98 issue.

**Comment by tsunamayo** [comment]
@Zenti98 Massive massive ship, it is hard to test. Anyway the turret looked like dual secondary axis turrets, which are fixed in 20w45b. Please re-open or reply if it is not the case! Thanks
