### ISSUE TITLE
[Experimental] FPS problems

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#3141]
### Short Description of the issue:
So for awhile now I have been experiencing skips in frames that happens occasionally but pretty frequently and I'm pretty sure that was already reported some time ago. But this is related to hovering around a certain area on a ship.

I also want to note that the ladder blocks seem to affect FPS dramatically. This older elevator shaft design had frequent frame drops:
![20201025224021_1](https://user-images.githubusercontent.com/32974671/97770294-f5ef1080-1aff-11eb-8367-bb91586f7ae1.jpg)
But this new one has less, although still has FPS issues for some reason:
![20201030221859_1](https://user-images.githubusercontent.com/32974671/97770302-07381d00-1b00-11eb-8f40-8bea5b64b25b.jpg)

Here's a little more insight for why I'm pretty confused in this situation. Before I optimized the elevator shaft my task manager was showing 22.8% CPU usage, 3000 MB RAM, and 99% GPU usage (GTX 970). I then proceeded to break the lights and ladder blocks and then gpu usage dropped by 30% for a bit then I replaced some other things and gpu usage increased back to 99% but the fps was better. 

More confusion:

These higher detailed areas don't really affect my frames at all:
![20201030221633_1](https://user-images.githubusercontent.com/32974671/97770362-8cbbcd00-1b00-11eb-8690-b51c8398ae81.jpg)
![20201030221641_1](https://user-images.githubusercontent.com/32974671/97770363-8e859080-1b00-11eb-9d06-68d3c0b2685c.jpg)

But hovering around at the elevator shaft, even after optimizing it, drops my frames frequently to 48-57
![20201030221705_1](https://user-images.githubusercontent.com/32974671/97770383-c391e300-1b00-11eb-96c1-b6285b4ffa33.jpg)

### Environment
- Starship EVO version: 20w43b
- Graphics Card: GTX 970

### Additional information:
I can confirm that occlusion culling is not the culprit here:
![20201030222111_1](https://user-images.githubusercontent.com/32974671/97770397-e15f4800-1b00-11eb-9ec9-921f5799762b.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5468472/output_log.txt)

**Comment by tsunamayo** [comment]
The elevator shaft of the death... Send the bp my way I will have a look at it! Build looks amazing (and big) btw, cheers

**Comment by Xerma** [comment]
[Cake Bol Revised 3.zip](https://github.com/tsunamayo/Starship-EVO/files/5470016/Cake.Bol.Revised.3.zip)

**Comment by Xerma** [comment]
I actually think it's my interior palette that's causing my frame drops. I unspawned it and hovered around the same area and didn't notice any significant drops.


[New Interior Set.zip](https://github.com/tsunamayo/Starship-EVO/files/5470721/New.Interior.Set.zip)
