### ISSUE TITLE
Asteroid belt particle z buffer

### ISSUE THREAD

**Issue by berrigo2** [tsunamayo/Starship-EVO#3144]
### Short Description of the issue:

When in the ice ring around the gas planet, the game plays a particle system of little dots floating around to feel like "dust". this dust appears to be in 3d space but when you move past a wall you can see the particle render above the wall and is still visible

### Steps to reproduce the issue:
go to belt
place a block
move around

### Environment
- Starship EVO version: steam latest, non-beta
- Graphics Card: gtx 1050

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by tsunamayo** [comment]
Hi, fixed for 20w46a. Thanks!
