### ISSUE TITLE
Lost in space

### ISSUE THREAD

**Issue by 24poundsplinter** [tsunamayo/Starship-EVO#3145]
### Short Description of the issue:
Was testing the warp drive.  Got killed by auto pilot after reaching another system  and flying to a station there. The regenerator at my base  worked, but it brought the base and everything  on the ring world with it to the middle of nowhere.  Lost my ship and the ones available could not reach nearest star.  Thought about just  building from there, but everything started getting glitchy.
...

### Steps to reproduce the issue:
Build a building on ring world . Put regenerator there . Got ot another system.  Fly into a planet. 
...

### Environment
- Starship EVO version: Beta
- Graphics Card:  not sure but everything  I play  with it works. 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by CurioInventorium** [comment]
This is similar/same to #3110

**Comment by tsunamayo** [comment]
Yes sorry I am currently working on it. The star system format changed, and the legacy starting point is a bit of a hack and is causing issues. Thanks

**Comment by 24poundsplinter** [comment]
Thanks. The game is still more than worth the money I paid.  Every day  extra is a bonus.   
Do you have a way to send more money to invest in this project ? I expected bugs in a Beta.
