### ISSUE TITLE
[BUG] Structures, and ships flickering

### ISSUE THREAD

**Issue by SnowyBirdot** [tsunamayo/Starship-EVO#3147]
### Short Description of the issue:
A sort of image of the ship I've noticed tends to flicker in front of it in the direction of travel. As stated this also applies to buildings.

### Steps to reproduce the issue:
Go somewhat fast, like 9x speed. Doesn't happen in light cruise.

### Environment:
- Starship EVO version: 20w44a/43b, and several past versions
- Graphics Card: GTX 1050 TI

### Output:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5472257/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, thanks for booking the issue, I dont really understand it thought. Do you have a picture or video to show? Not sure what is happening or how to reproduce it.
Thanks

**Comment by SnowyBirdot** [comment]
I don't think I have any videos taken that could show it. I just tend to notice it after I've been on for a while, and am going particularly fast, if I get a video I'll send it.

**Comment by SnowyBirdot** [comment]
https://imgur.com/a/XU1gbVO

I noticed this occur when I started to stream Starship Evo to a friend of mine over Discord. I have absolutely no clue what causes the orange square to appear whenever I record, but I can confirm they are different bugs.

**Comment by tsunamayo** [comment]
@SnowyBirdot so you seems to have encountered an issue with symmetry that in turned caused this issue.
Do you recall doing anything particular with symmetry? Thanks

**Comment by SnowyBirdot** [comment]
I do recall that at the time I was expanding a ship of mine into a dreadnought, so I was using symmetry to get work done faster.

**Comment by tsunamayo** [comment]
@SnowyBirdot thanks for the quick answer ;) Did you deleted the ship in question (or one children entity), or did you warped somewhere?

**Comment by SnowyBirdot** [comment]
No, I flew around a bit as is apparent, and had started a Discord stream, but neither of those.

And no problem, I just noticed the email notification I got.

**Comment by tsunamayo** [comment]
Hum, did you quit to title and loaded back? Sorry I am trying the see what that could have been while it is fresh. I already saw that issue but had no lead on the true cause (apart that it is related to symmetry). Thanks

**Comment by tsunamayo** [comment]
@SnowyBirdot haha I managed to reproduce, this was because of the quit to title and load back sequence. I will fix it now!

**Comment by SnowyBirdot** [comment]
Wohoo!

**Comment by tsunamayo** [comment]
@SnowyBirdot okay issue fixed for 20w45b. Thanks, I am glad to have fixed that one! Cheers

**Comment by SnowyBirdot** [comment]
Happy that I was able to help!
