### ISSUE TITLE
[Bug] Flickering light in first person

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3151]
### Short Description of the issue:
There's a flickering light visible in first person only when I pilot ships, you can see it in the video here - https://i.imgur.com/DPRckh4.mp4
This happens in all ships that I've tried so I haven't included a blueprint
### Steps to reproduce the issue:
Fly a ship in first person, I'll update this post if I find anything more specific

### Environment
- Starship EVO version: 20w43b
- Graphics Card: RX 580

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5477976/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, indeed I can reproduce. It is related to shadow, I keep you posted. thx

**Comment by tsunamayo** [comment]
btw @ProPeach, do you think it is a recent bug or it might be there for some time? Thanks

**Comment by ProPeach** [comment]
I think it's actually been here for a while, I don't fly ships too often these days but I do remember meaning to report this kind of thing in the past

**Comment by tsunamayo** [comment]
@ProPeach Fixed for 20w45c. It is was actually really tricky, I hope I dont have to undo the fix at one point (a lot of impacts).
 Thanks
