### ISSUE TITLE
I want to help with Turkish localization

### ISSUE THREAD

**Issue by DonitaStark** [tsunamayo/Starship-EVO#3156]
if there's a future plan for more language options i would like to participate in it by translating game's texts to Turkish. 

thanks.

**Comment by tsunamayo** [comment]
@DonitaStark Thanks a lot for the offering! I will work on localization very soon, so I will keep you posted! Cheers

**Comment by DonitaStark** [comment]
thank you, at least i can participate in that. please keep in contact. people love building games here a lot; they adore games like SE so  we might get attention from more people in my country.
