### ISSUE TITLE
[BUG] Ships moving strangely, in MP

### ISSUE THREAD

**Issue by SnowyBirdot** [tsunamayo/Starship-EVO#3158]
### Short Description of the issue:
I find this very hard to describe textually however I do have video. This seems to happen with anything we place. and does not affect the host.
...

### Steps to reproduce the issue:
Join a multiplayer session as a client, place a starter block.
...

### Environment
- Starship EVO version: 20w45a
- Graphics Card: GTX 1050 TI (Host running GTX 1060)

### Additional information:
https://imgur.com/a/Gm71jSz
https://imgur.com/a/hl9R5wo

### Output log:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5484061/output_log.txt)

Xenoprophet, the host, will include his output log below.

**Comment by Xenoprophet-Nail** [comment]
Yup here's my output log: 


... odd it won't let me paste it

**Comment by SnowyBirdot** [comment]
Xeno couldn't put it down so here it is from me, 
[output_log (Xeno).txt](https://github.com/tsunamayo/Starship-EVO/files/5484106/output_log.Xeno.txt)

**Comment by Vicomt** [comment]
can confirm. anything spawned by the client does this. I didn't see it personally as I was the host, but Oojimaflip (the client) did.

**Comment by tsunamayo** [comment]
Hi guys, so it is a position recenter issue. It seems related to something else though, I will investigate and keep you posted. Thanks for testing mp!

**Comment by SnowyBirdot** [comment]
No problem Tsuna, just appreciate how attentive you are to bugs!

**Comment by matejkar** [comment]
same here, seems its for everyone, however for me it happened even in singleplayer, and it seems like the starter block we placed to spawn the ship is still visible, but not interactable, always outside the ship, and it moves as a part of the ship

**Comment by tsunamayo** [comment]
Hi guys, so there is a new build 20w45b. I did a few fixes regarding the issues in your log, I am not sure if it fixes this issue though, if you can tell how it went. Thanks
