### ISSUE TITLE
[BUG] Travelling to space stations PART I (experimental)

### ISSUE THREAD

**Issue by Womble-TC** [tsunamayo/Starship-EVO#3159]
### Short Description of the issue:
Right now, in any star system, it is impossible to travel to a space station. There are two stations on the HUD that appear at 944433.1m and 482448.5m away, however, when you try and travel to them, they don't get any closer. 

### Steps to reproduce the issue:
- Create a new world
- Locate station
- Try and travel to it 
- Can't

### Environment
- Starship EVO version: 20w 45a
- Graphics Card: GTX 970

### Additional information:

There is a secondary bug I found relating to this bug, I will put this in "Travelling to space stations PART II" (in theatres 1989)

**Comment by tsunamayo** [comment]
@Womble-TC Hi mate, so you have a log file to show? I will see if I can reproduce. Cheers

**Comment by Womble-TC** [comment]
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5484934/output_log.txt)
here you go

**Comment by tsunamayo** [comment]
@Womble-TC gotcha, it seems that there is some trouble to load a ship, could you send me your character save? Mail is fine if you dont want to drop it here ;) Thanks

**Comment by Womble-TC** [comment]
[Test 3.zip](https://github.com/tsunamayo/Starship-EVO/files/5486322/Test.3.zip)

**Comment by tsunamayo** [comment]
Okay so I was able to reproduce, issue fixed for 20w46a. Thanks!
