### ISSUE TITLE
ghost versions of ships remain after unpsawning

### ISSUE THREAD

**Issue by amplified1** [tsunamayo/Starship-EVO#3161]
### Short Description of the issue:
A not functional "ghost" version of any ship on any save I try to unspawn remains until I relog
### Steps to reproduce the issue:
select ship for unspawning, unspawn it. this works even in a clean slate world

### Environment
- Starship EVO version: 20w45a experimental
- Graphics Card: nvidea 1080 TI

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5484901/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, thanks for booking the issue. Fixed for 20w45b. Thanks!
