### ISSUE TITLE
[Bug] Builds don't despawn until after the world's been re-entered

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3162]
Version: 45A
 It's pretty basic, just:

1. Spawn a blueprint
2. Despawn it
3. Notice its "ghost" is still there
4. Re-enter the world

![image](https://user-images.githubusercontent.com/63756057/98155880-dde80a00-1ece-11eb-9a71-1a10bf433383.png)

**Comment by tsunamayo** [comment]
So this was fixed already for 20w45b. Thanks mate ;)
