### ISSUE TITLE
[Bug] Child entities don't disappear on parent entity's deletion

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3163]
Version: 45A
Works every time, just:

1. Place down any mechanism
2. Delete it
3. The whole child entity remains as a ghost

Also if you repeat the procedure over a few times, the ghostly child entities randomly change places:
![image](https://user-images.githubusercontent.com/63756057/98157194-e3465400-1ed0-11eb-96de-21aeda4c3510.png)

**Comment by tsunamayo** [comment]
So this one was related to the unspawn bug that was fixed already. Fix in 20w45b. Thanks!
