### ISSUE TITLE
[BUG] Clientside teleporty business

### ISSUE THREAD

**Issue by SnowyBirdot** [tsunamayo/Starship-EVO#3167]
### Short Description of the issue:
The issue with objects placed by the client moving is still not resolved.
...

### Steps to reproduce the issue:
Join a multiplayer game as a client, and place a starter block.
...

### Environment
- Starship EVO version: 20w45b
- Graphics Card: GTX 1050 TI

### Additional information:
https://imgur.com/a/JL0kDG2

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5493070/output_log.txt)
[output_log (Xeno).txt](https://github.com/tsunamayo/Starship-EVO/files/5493071/output_log.Xeno.txt)

### End Note:
Terribly sorry for discounting what you've done, but immediately upon my placing of a block, the issue was still present, We both closed the game immediately after encountering the issue, so there shouldn't be much else gunking up the logs. Once more, apologies Tsuna.

You do good work!

**Comment by tsunamayo** [comment]
Oh okay so the test case is client create a new ship? I will try to reproduce then. Thx

**Comment by Vicomt** [comment]
the test case is broader than that. any ship spawned (even by the host) follows the client.

**Comment by tsunamayo** [comment]
Okay so I have just fixed that issue, I will repush 20w46a with this fix. Thanks
