### ISSUE TITLE
[Bug] Large blocks cannot be placed on a small mechanism's child entities

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3168]
Version: 45B

A few versions ago it was possible to place down large blocks like warp engines and shield generators on child entities produced by small mechanisms if they adhered to the large block grid. Here you can see the grid of the bricks should allow the shield generator to be placed down, and yet it doesn't.

Possibly related to #3030 

![image](https://user-images.githubusercontent.com/63756057/98305168-4a3f3800-1fb9-11eb-943e-3f5abb78925b.png)

**Comment by tsunamayo** [comment]
Actually it is by design. It is highly confusing on how the larger grid is supposed to spawn, there is not good answer for that.
Btw did you still get #3164? Thanks

**Comment by Kaiser-Indrasil** [comment]
Nope, the #3164 is gone, thanks!
As for the topic at hand, I'm not sure if this is a good decision to have it this way. After all, small mechanisms are strong enough to easily move around a mass of a large block, even a few dozen of them, so why not just let them? I feel like it's a bit restrictive on space, especially on small builds that could use the space occupied by the large mechanisms for more reactors or thrusters instead. It limits the design choices as well.

**Comment by Kaiser-Indrasil** [comment]
For example, I used to be able to squeeze the warp engines in very thin compartments like that and also pose shield capacitors at an angle for improved looks.
![image](https://user-images.githubusercontent.com/63756057/98309490-83c87100-1fc2-11eb-896e-3fc31c5ed6e6.png)

**Comment by tsunamayo** [comment]
Yeah I know it sucks, but otherwise people would ask for different grid placement and such.

**Comment by Kaiser-Indrasil** [comment]
Aww, I see. Well, it's not that big of a deal though.

Also, I see you managed to practically get rid of clipping. Congrats!

**Comment by AlienXtream** [comment]
been a bit since i tried but i reckon i could make things clip if i wanted to :P

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil haha, so what are the remaining case to hunt down? ;)

**Comment by Kaiser-Indrasil** [comment]
Right now for me it's #3165 . It happens rarely but I'm always forgetting to upload a log ;P

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil yes that one I need to investigate, but I was talking about the clipping! As you said "pratically" ;)

**Comment by Kaiser-Indrasil** [comment]
Oh! Well, there is only a tiny bit of clipping left like you can see here but this is as far as I can possibly push it:
![Starship_EVO_MKNR1lDXch](https://user-images.githubusercontent.com/63756057/98426408-9ad59480-2090-11eb-913e-05b4d83278a0.png)
