### ISSUE TITLE
[Bug] Game Config window opens everytime I launch the game

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3169]
Version: 45B

![image](https://user-images.githubusercontent.com/63756057/98306118-1107c780-1fbb-11eb-8094-8435ddaeaeb8.png)

**Comment by tsunamayo** [comment]
Okay thats weird I did a test indeed but I revert it back... Will be fixed in 20w45c. Thanks!
