### ISSUE TITLE
[BUG] Leaving Photo Mode from inside a turret

### ISSUE THREAD

**Issue by chacalik** [tsunamayo/Starship-EVO#3170]
### Short Description of the issue:
Leaving Photo Mode from inside a turret (either with two rotors or hinges) makes the character begins to roll without stopping. Pressing the key to roll counterwise, make it stop but releasing the key makes roll again. The only way to stop it from happening is load the savegame again.
...

### Steps to reproduce the issue:
Enter a active turret and while controlling it, press F6 (Photo Mode), move around then press again F6 to leave the Photo Mode. Done, it should be rolling already.
...

### Environment
- Starship EVO version: 20w45b
- Graphics Card: RX 590

### Additional information:
Its a very generic bug, so it won't need any specific blueprint.

**Comment by MadTheDog** [comment]
In my experience with this bug, if you go in and out of a seat it fixes it

**Comment by chacalik** [comment]
@MadTheDog the problem is, when you're building something big, getting to a cockpit may be a lot difficult if you're rolling... its like watching "Gravity" movie

**Comment by tsunamayo** [comment]
So issue is fixed for 20w48d. Thanks!
