### ISSUE TITLE
Buildings not loading properly on fresh Game start

### ISSUE THREAD

**Issue by TheRealXaamo** [tsunamayo/Starship-EVO#3172]
### Short Description of the issue:
After loading into a new Game none of the vanilla structures where visibly. Some random strangly warped blocks are flying around in circles. Hitboxes for all buildings still exist.
...

### Steps to reproduce the issue:
Take a Ship, fly it into the Sun. until it explodes. Cannot respawn because of no active medbays. Be dead for ever. Try to start a new Game.
...

### Environment
- Starship EVO version: actual version, not experimental
- Graphics Card: 1060 [6gb]

### Additional information:
https://www.youtube.com/watch?v=FsbO8z3Ogc8&feature=youtu.be
_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by tsunamayo** [comment]
Whoa that was trippy indeed. I am pretty sure this is fixed in recent experimental version (now you simply respawn if there is no medbay active)
To investigate further I will need your character save and the output.log.
Thanks

**Comment by TheRealXaamo** [comment]
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5504734/output_log.txt)

Theres the Log File, but how do i upload my character save?

**Comment by TheRealXaamo** [comment]
[Xaamo 3 Save File.zip](https://github.com/tsunamayo/Starship-EVO/files/5504751/Xaamo.3.Save.File.zip)
well i hope this works

**Comment by tsunamayo** [comment]
Okay I have no problem with this save in current version. You can try to update to experimental by using the BETA branch in Steam! thanks
