### ISSUE TITLE
Revamp player movement [suggestion]

### ISSUE THREAD

**Issue by SoopaPoopa** [tsunamayo/Starship-EVO#3174]
I've had Starship Evo for around 11 hours and I love the building and logic within, however, I have one major gripe, the player movement. I feel as if every action I make is delayed and whenever I want to change locomotion modes I find it a pain to navigate through the menu every time. These are not the only 2 problems I have so I'll list the issues I have down below. Ways to improve movement in my opinion include:

-fixing the movement code to allow inputs for movement to be received and processed faster.

-Make some movement variables available in the debug menu, such as jump force and countermovement.

-In the zero-g locomotion mode, instead of making the character float downwards and upwards in their relative rotation, make them float upwards and downwards in their global rotation (similar to Minecraft's creative mode flight), maybe make this an option in the debug-menu so you can choose whatever you prefer. However, I think people would enjoy Minecraft's method more.

-Add hotkeys to change between the locomotion options quickly and efficiently (if this is already a feature please tell me.)

-When in ships or any structure for that matter, the gravity of any outside force causes the character to slide. I'd recommend giving the player a lot more friction so it doesn't feel like your walking on ice.

-I've noticed that your game is using the unity engine and I think that some of the reasons I listed above arise from you possibly using the default character controller. In order to fix all the issues, I'd recommend writing your own rigid body movement script. Using the rigid body component as a basis for a movement system can allow for much more flexibility and responsiveness regarding movement. (If you already are using this method forget what I just said, but keep in mind that if you ARE using the rigidbody method, there is still a lot of delay when inputting movement actions.)

**Comment by tsunamayo** [comment]
@SoopaPoopa thanks,  I had a few review talking about this recently I am sure what is wrong if you could give more info:
 - what is your config?
 - How many FPS are you having (you can press F3 and then Show FPS stats)
 - Did you use v-sync?
 - Does the input lag concerns player look and / or movement?

Regarding the locomotion yes I will simplify things, get rid of the screen, add a keybind, and do some auto-switch when you exit a gravity zone for example.
For the 6dof zero-g I cant do like minecraft as there is no up and down. The minecraft like mode (which I also prefer) is call Anti-grav, and it force the player to align to the gravity field, so up / down is also relative to the gravity field. You might want to use that mode (I always use that one). 6dof is really to be used when you are in deep space with no gravity field.
Also I am not using Unity rigidbody nor do I use the default character controller, I have my own code doing physics and collision detection. Things are way to complex and specific in order for me to use unity native stuff.
Thanks

**Comment by tsunamayo** [comment]
@SoopaPoopa By the way, could you try the following:
Turn "head bobbing" at 0% in Graphical Options
Also I am supposing you are seing this near the starting zone.
Could you turn some rendering off: In F3 / Habitat, deactivate Fog / Water / Grass / Rock / Hull Rendering. It will improve the FPS.
Tell me if it feels better after that or not.
Thanks

**Comment by tsunamayo** [comment]
Now implemented in 21w03b. Thanks
