### ISSUE TITLE
[Bug] Character getting constantly caught on the ground

### ISSUE THREAD

**Issue by NetGlitched** [tsunamayo/Starship-EVO#3177]
### Short Description of the issue:

After starting a game and going outside, when running around on the ground the character constantly just gets caught on the ground, causing them to slow down for a second constantly when this shouldn't be happening.

Edit: Jumping sometimes behaves similarly when landing.

### Steps to reproduce the issue:

Just run around outside.

### Environment
- Starship EVO version: 20w45a
- Graphics Card: GTX 1080

### Additional information:

No additional information should be necessary. I am in singleplayer if that matters, but I don't see why it would.

**Comment by tsunamayo** [comment]
Issue fixed for 20w48a. Thanks!
