### ISSUE TITLE
[BUG] Stuck in Chair in Build Mode

### ISSUE THREAD

**Issue by Kadzar** [tsunamayo/Starship-EVO#3179]
### Short Description of the issue:
I somehow ended up in Build Mode while in a ship and can't get out.

### Steps to reproduce the issue:
Not sure what happened, though a bit before this happened I had gotten out of the chair while in warp and did some building, then re-entered since the ship didn't seem to want to break out of warp otherwise, and I hadn't gotten out of the chair after that.

### Environment
- Starship EVO version: 20w45b
- Graphics Card: NVidia GeForce GTX 1080

### Additional information:

![20201106201243_1](https://user-images.githubusercontent.com/66035211/98429689-d448d880-206d-11eb-82c6-3933747a2e82.jpg)

[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/5504179/output_log.zip)

**Comment by tsunamayo** [comment]
I get the bug is getting out of your chair while in warp...

**Comment by tsunamayo** [comment]
Hi @Kadzar, could you send me: KSE Coleoptera-Class Shuttle Warp Retrofit?
It might be linked to this particular blueprint.
Thanks

**Comment by tsunamayo** [comment]
Okay actually I think I understood where the issue was, it should be fixed for 20w46a. Thanks!

**Comment by tsunamayo** [comment]
@Kadzar actually could you send me your full character save? it seems there is something fishy inside. thanks!

**Comment by Kadzar** [comment]
Didn't know if you still needed the blueprint also, but I included it just in case.
[KSE Coleoptera-Class Shuttle Warp Retrofit.zip](https://github.com/tsunamayo/Starship-EVO/files/5513134/KSE.Coleoptera-Class.Shuttle.Warp.Retrofit.zip)
[Kadzar 4.zip](https://github.com/tsunamayo/Starship-EVO/files/5513138/Kadzar.4.zip)

**Comment by tsunamayo** [comment]
It can load just fine on my side. Did you recall what did you build exactly when in warp? Thanks

**Comment by Kadzar** [comment]
I don't recall exactly what I built at that time. I think it may have either been the control console next to the warp drive or maybe the logic that connects the yoke controls to the warp drive control console.

**Comment by tsunamayo** [comment]
Ok yes I am gonna try that. It might cause issue as you were flying.
