### ISSUE TITLE
[Bug] Inexplicably low FPS / harmonic stuttering that happens randomly

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3180]
Version 45B

So, this is a tricky one.

![image](https://user-images.githubusercontent.com/63756057/98430575-50f7a900-20a6-11eb-9a3f-a18687ac078d.png)

I noticed no excessive GPU or CPU use and no memory leaks either in the Task Manager.
It says "78 FPS" but it really feels like 10.
The first section of the graph represents the fluid, stutterless 100 FPS.
Second and third ones are where this weird stuttering happens.
There are no changes to the scene, no logic updates, no nothing - it seemingly happens randomly.
The scene's also very simple - just a few small static entities.

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5504228/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, you did nothing special? No looking at something or else?
After the lag did it came back better or did it stayed like that?
Also was it a one off or do you see that often?
Thanks

**Comment by Kaiser-Indrasil** [comment]
Last time it happend, I just left the game in the background to do some stuff in the kitchen, and when I came back, it was already stuttering, without any input and scene change.

**Comment by tsunamayo** [comment]
I dont know, maybe it is related to NPC doing weird stuff in the background? Where you close to a station?

**Comment by Kaiser-Indrasil** [comment]
Nope, just hanging around the torus.

**Comment by Kaiser-Indrasil** [comment]
It might have something to do with the Borderless windowed mode. I noticed there was no problem in Fullscreen.

**Comment by tsunamayo** [comment]
Hum I see, indeed in Fullscreen I think windows give the app a higher priority. So it might be some other process that where trigger behind in borderless. It does happens to me on my laptop, each time I dont touch it there is some windows check starting making my fan louder.

**Comment by tsunamayo** [comment]
Okay so I guess we will say mystery solved ;)!
