### ISSUE TITLE
[BUG] FPS Drop and Freeze in Warp

### ISSUE THREAD

**Issue by Kadzar** [tsunamayo/Starship-EVO#3181]
### Short Description of the issue:
I went into warp and the FPS dropped, then the game froze

### Steps to reproduce the issue:
Don't know, I'll let you know if I get it to happen again.

### Environment
- Starship EVO version: 20w45b
- Graphics Card: NVIDIA GeForce GTX 1080

### Additional information:

Couldn't get Steam to screenshot while it was happening

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5504250/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, so you where playing in multiplayer right?

**Comment by Kadzar** [comment]
> Hi, so you where playing in multiplayer right?

No, singleplayer

**Comment by tsunamayo** [comment]
Okay actually I think I understood where the issue was, it should be fixed for 20w46a. Thanks!
