### ISSUE TITLE
[Bug] Ship size in Codex doesn't account for child entities

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3182]
Version: 45B

I noticed that shield, on the other hand, does account for child entities.
The ship codex summary, however, does not.
I circled the shield generators on the ship preview to show how big it is, compared to the size value displayed by the summary.

![image](https://user-images.githubusercontent.com/63756057/98432500-c8353900-20b6-11eb-9672-249e19cff02f.png)

**Comment by tsunamayo** [comment]
Fixed for 20w45c! Thanks
