### ISSUE TITLE
[BUG] [SUGGESTION] no consistent seamless cube model transition

### ISSUE THREAD

**Issue by Lord-Mortangol** [tsunamayo/Starship-EVO#3184]
### Short Description:

At the moment there is a bug on tetra and hepta cubes causing the edges to look different dependent on the angle you build the structure.
Some edges are seamless and some are visible. There is no consistency.

### Steps to reproduce the issue:

build mirrored tetra and hepta cubes
(appears anyways, on manually building mirrored shapes, as well as shapes build with symmetry)

### Environment
- Starship EVO version: current (nott experimental)
- Graphics Card: ASUS ROG Strix Radeon RX 570 8GB OC Edition

### Additional information:

Sreenshot

![20201107130417_1](https://user-images.githubusercontent.com/66745463/98440941-1d476e00-20fc-11eb-871f-5f6d4746251f.jpg)

As you see, dependent on the angle, there are different edges visible.

output.log

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5504720/output_log.txt)

### Suggestion

Beside solving the bug I suggest:
1. switching to seamless cube transition, like the hulls look like, so you can't see the edges between cubes
2. or giving the player the option to switch between seamless transition and transition with visible edges.

**Comment by tsunamayo** [comment]
Hi, issue fixed for 20w45c. Thanks!
