### ISSUE TITLE
The invisible block bug is back.

### ISSUE THREAD

**Issue by Vicomt** [tsunamayo/Starship-EVO#3185]
### Short Description of the issue:
Blocks get placed invisibly again after a certain point. (seen on client side), not known what the trigger is, although the host used copy/paste

this was slightly different to the previous issues, where the client could see the physics geometry selection, but not see the textures, now, the block is COMPLETELY invisible to the client, no hitbox, no geometry, no textures, yet it is perfectly visible and interactable to the host.

### Steps to reproduce the issue:

we're not sure. as host I opened the world attached, the client joined, I then copy/pasted an engine subassembly from Leviathan to our working platform. blocks placed after this were then invisible to the client, when placed by both the client and the host.
I can't say for definite that the copy/paste triggered it.

the client is also seeing a weird 10% chunks loaded during world open, it feels like there's an upper memory limit that is stopping the chunk load - the client also see less total chunks loaded than the host (again roughly 10%, but not checked or calculated)

### Environment
- Starship EVO version: 20w45b
- Graphics Card:  GTX1070 (host) GTX980 (client)
- RAM: 32GB (host) 16GB (client)

### Additional information:

[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/5504804/output_log.zip) (host)
[vic mp test 2.zip](https://github.com/tsunamayo/Starship-EVO/files/5504806/vic.mp.test.2.zip)

apologies, we didn't get the output log for the client on this run. next time it happens, we'll attach both host and client logs.
btw, please implement log file naming by date/time, that would allow us to go back and fetch any log we wanted ;)

**Comment by Kaiser-Indrasil** [comment]
Can confirm, it happened to me yesterday when I was playing single-player.

**Comment by tsunamayo** [comment]
@Vicomt I will need to client log to investigate. @Kaiser-Indrasil Same thing! 
Also regarding the chunk limit, it might be that or something else in your save. Could you send me the host character save so I can check? Thanks
Cheers

**Comment by Kaiser-Indrasil** [comment]
It was a long overdue but it finally happened! Here you go:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5505798/output_log.txt)

**Comment by Vicomt** [comment]
yeah, we had a major session last night, many hours of building, not a single peep out of this. still can't find a trigger.

is the chunk limit based on a percentage of memory? if so, then could it be that the host (who has double the RAM of the client) determines it's limit, loads chunks based on that, then replicates those chunks to the client, but as the host can load many more chunks than the client, the client drops them after surpassing it's own (lower) chunk limit?

**Comment by tsunamayo** [comment]
@Vicomt yes that could be. What are your guys respective RAM? Is there a lot of stuff in that world?

**Comment by Vicomt** [comment]
in our case, the host has 32GB, the client has 16GB. Our worlds usually don't have a lot in them apart from the ships we're working on. setting up the fleet in positions to take screenshots would be where we have the most stuff loaded, and as soon as we start bringing in the large ships, chunks just stop. they stop being loaded on the client, and even if they are loaded, they don't replicate changes to the client when updates are made by the host.

**Comment by Kaiser-Indrasil** [comment]
I have 32 gigs and in my case there were just a few small fighters in the world.

**Comment by tsunamayo** [comment]
Okay I just pushed 20w46a. There is a mp fix that could have explained some issue, if you can tell me how it went. Thanks!

**Comment by Kaiser-Indrasil** [comment]
I would send a logfile, but apparently it's 180MB-big...

So instead, I will just post a [log but shorter.txt](https://github.com/tsunamayo/Starship-EVO/files/5518904/log.but.shorter.txt).

**Comment by tsunamayo** [comment]
We should be all good in recent updates... thx
