### ISSUE TITLE
The particles in asteroid belts render through blocks

### ISSUE THREAD

**Issue by amplified1** [tsunamayo/Starship-EVO#3187]
I assume that this is just an issue with how they were made but if you go in an asteroid field you can still see the particles when you are in a ship and it is mildly annoying.

**Comment by ZachZent** [comment]
It's the protomolcule
![image](https://user-images.githubusercontent.com/36980446/98452372-1d4f6a00-210c-11eb-879e-6c0e35784eae.png)

**Comment by tsunamayo** [comment]
Protomolecule fixed for 20w46a. Thanks!
