### ISSUE TITLE
[Bug] 3rd person camera doesn't account for the ship's child entities.

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3189]
Version: 45B

It's probably connected to #3182.
Below you can see that in the 3rd person camera the wingtips are clipped outside of the camera's vision and that it's zoomed in way too closely:

![image](https://user-images.githubusercontent.com/63756057/98459689-030d9e80-2195-11eb-93a8-a877731644ac.png)

**Comment by tsunamayo** [comment]
Issue fixed for 20w46a. Thanks a lot mate ;)
