### ISSUE TITLE
[Bug] Blueprint broken after a logic bug

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3190]
Version: 45B

I think this one is the most severe I've encountered yet.
It practically rendered my blueprint unspawnable.
Here's what happened:

I was building away a logic circuit and clicked a query gate.
It didn't display any window. I tried to click another logic gate, same result.
I went to restart the game but before that I saved my blueprint and I think that might've doomed it.
I tried to re-enter the world, only to be greeted my the infinite loading screen.
I made a new world and tried to spawn my ship - nothing happened.

Here's the blueprint: 
[Agni - 45B.zip](https://github.com/tsunamayo/Starship-EVO/files/5506838/Agni.-.45B.zip)
Help me, Obi Wan Kenobi...

**Comment by Kaiser-Indrasil** [comment]
Also here's the broken world file:
[Exp 45B.zip](https://github.com/tsunamayo/Starship-EVO/files/5506845/Exp.45B.zip)

**Comment by Kaiser-Indrasil** [comment]
If you could even either spawn the blueprint or get into the world I've uploaded and send me the blueprint, that would be a huge help. I've literally spend days working on it...

**Comment by tsunamayo** [comment]
Sure let me keep you posted. thx

**Comment by tsunamayo** [comment]
Okay issue fixed for 20w46a! I will push the build tonight. Cheers
