### ISSUE TITLE
[Bug] NPC Stations and Interstellar Travel

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3191]
### Short Description of the issue:
NPC stations will get pulled with the player to new star systems, but will remain permanently off "in the distance" when you arrive at the new system

### Steps to reproduce the issue:
Warp to a new system with a station in view
You can see the station throughout the whole warp sequence
Select the station once warp has completed and try to fly to it

You can still see the station during warp
![20201108185024_1](https://user-images.githubusercontent.com/27857711/98481709-02f0bb80-21f4-11eb-88d0-8b99a9415594.jpg)

Despite travelling at 100km/s, the station always appears at 10km away once you arrive in the new system
![image](https://user-images.githubusercontent.com/27857711/98481679-d177f000-21f3-11eb-9ff0-e6d501b59354.png)

### Environment
- Starship EVO version: 20w45b
- Graphics Card: RX580

**Comment by tsunamayo** [comment]
Hi, how did you manage to see the station first?
Also cool ship, is it yours? Thats a starwars ship right?
Cheers

**Comment by ProPeach** [comment]
I could see it totally fine in the starter system, it acted as normal until I warped and then it just seemed to stay in exactly the same place relative to the ship, no matter how the ship moved in the new system. I could still select it and activate autopilot, but it would never get any closer or move at all.

And thank you! Yes it's one of my builds, the Stinger Mantis from the Jedi: Fallen Order game

**Comment by tsunamayo** [comment]
Is it on the workshop? What I dont understand is when you should start to warp the station should be gone out of sight right? so then it reappears in sight at one point?

**Comment by ProPeach** [comment]
Not yet, I still need to finish the interior

No, the station remains visible even during warp. In the first image I posted, you can see the station selection box just above the nose of the ship. It doesn't dissappear at any point during or after warp. 
Once I arrived at the new system, I could still select it and the second NPC station as if I were still in the first system.

**Comment by tsunamayo** [comment]
Okay so it was actually broken even with no warp. Fixed for 20w46a. thanks!
