### ISSUE TITLE
[SUGGESTION] Add a feature that lets you weld the seams between bricks.

### ISSUE THREAD

**Issue by amplified1** [tsunamayo/Starship-EVO#3192]
![image](https://user-images.githubusercontent.com/40322931/98484151-b04ed980-21ca-11eb-9efb-2778091d96b9.png)
It would be helpful for the looks of a ship if you could avoid things that look like this, so I was wondering if you could make a tool that caused them to merge, like what happens with hull blocks

**Comment by tsunamayo** [comment]
Hi, yes I understand why you would want that, but that is not possible with the current tech unfortunately.  But I will make the seam smaller for what is worth. Thanks

**Comment by amplified1** [comment]
making the seam smaller would be very nice thank you
