### ISSUE TITLE
[Question] How will items and fuel be transported on ships?

### ISSUE THREAD

**Issue by MadTheDog** [tsunamayo/Starship-EVO#3194]
How will it work?
There are many sandbox-games that have item and fuel transportation, the question is how is Starship Evo going to do it?
Will it be like the minecraft mod buildcraft, where each item is in a tube and you can see it moving around, and breaking the tube would spill out items?
Or more like the space engineers aproach where you have to pipe up the different systems needing the items, but they just get transferred "magically" through the tubes, and as long as there is a connection, item retrieval would be instant?
Or more like Dual Universe, where items are transferred "wirelessly" and connected with a link-tool similar to how logic is currently done in STEVO?

All have advantages and disadvantages, it is probably the last one which is going to cause the fewest builds to break, especially if fuel and items are going to be transported in the same way.

**Comment by tsunamayo** [comment]
For now the plan is something closer to space-engineers. But I allow tubing inside hull so it is not too disruptive.
For fuel it will be a matter of having enough flow, so you might need several pipes.
I would like to have real conveyor belt for crafting tough.
Thanks

**Comment by MadTheDog** [comment]
Will mechanisms be able to transfer fuel?

**Comment by MadTheDog** [comment]
@tsunamayo will mechanisms, like rotors be able to transfer items/fuel through them?

**Comment by tsunamayo** [comment]
I think it is a must have yes, but I can foresee some flow limit issue in some case, like if you want to add tons of large thruster onto your build. Not too blocking as you could always put your tank on the same entity. Ideally I will have a shot at having flexy tube ;)

**Comment by JimStarluck** [comment]
Something I've been wondering about: will Fuel be the only thing that needs moving around via pipes? Or will there be other things that need moving in similar fashion?

Power from reactors to systems that consume it?
Oxygen or Water for life support?
Coolant from heat-generating systems to specialized radiators or heat sinks?
Ammo from magazines to projectile weapons?

I could imagine just changing what type of thing a pipe carries or a tank holds by slapping a specific decal on them.

**Comment by tsunamayo** [comment]
Fuel and item transport is now implemented. Thanks
