### ISSUE TITLE
Framrate dropped to 9 fps, blueprints are "DESTROYED" upon fresh spawn

### ISSUE THREAD

**Issue by EmceeAlpin** [tsunamayo/Starship-EVO#3199]
### Short Description of the issue:

After the latest Hotfix Patch to the Experimental branch, I noticed that my frames dropped significantly. I was running at 9 fps, where before I was running around 50 - 70 fps. After creating a new world, the framerate issue was resolved, however now every blueprint that I import is "DESTROYED", as if it had been attacked and destroyed by an enemy. The builds spawned in without any visible damage. It didn't matter what I spawned, they were all destroyed.

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 20w46a
- Graphics Card: Nvidia Geforce GTX1080

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5515599/output_log.txt)

**Comment by tsunamayo** [comment]
Indeed, the destroyed issue is a big one, I will push a patch asap. Thanks

**Comment by tsunamayo** [comment]
Hi, so I just fixed the destroyed issue. I am overwriting 20w46a as it is a serious regression - the build is already live.
Regarding the framerate issue could you send me your world / character save zipped, I will have a look at it.
Thanks
