### ISSUE TITLE
[Discussion] Brick Borders

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3204]
With the removal of brick borders from brick tetras/heptas in 46a, it brings up an interesting discussion. A lot of players in the past have had strong opinions on brick borders so I thought I'd make this thread.

This recent change in some ways is fantastique- brick based curves are now super smooth, with brick tetras/heptas indistinguishable from their block based counterparts.
In other ways though, the weird disparity between the borderless angled bricks and the bordered cubes and wedges is just a little too odd.
Here are a few examples of what different shapes look like in the new build
![image](https://user-images.githubusercontent.com/27857711/98675050-a1defa00-2351-11eb-861c-3d7c07efad9a.png)
![image](https://user-images.githubusercontent.com/27857711/98675063-a6a3ae00-2351-11eb-87fe-0d3fbb1ae289.png)
This thin plate in particular looks *much* better than it used to - https://i.imgur.com/GC89bwG.png
![image](https://user-images.githubusercontent.com/27857711/98675109-b7ecba80-2351-11eb-955d-3fc073f0cbba.png)
![image](https://user-images.githubusercontent.com/27857711/98675171-cb982100-2351-11eb-9e78-d58c69bdd90f.png)

In the past you mentioned that you were considering reducing the effect of the brick border to make them smaller and less "deep", are you still considering this change? Personally, I'd prefer all bricks had a smaller border *or* they were all borderless, the mix of both doesn't mesh well in my opinion.

I'll leave this up so everyone can drop their own thoughts o/

**Comment by PopkaAkula** [comment]
I'm a little conflicted with brick borders personally, on one hand it makes curved surfaces look bad, but on the other hand the borders can be used to add more detail. I think that the best solution would be to get rid of brick borders entirely and have them just be a sticker in the game. That way you can have the best of both worlds and everything would mesh together properly.

**Comment by Kaiser-Indrasil** [comment]
I get the argument of the seams being there because the brick textures often don't match up with each other.
That said, maybe there is a way for seams to be present only where the textures don't match up?

If that's not feasible, then I guess the next best thing would be to get rid of the seams at all.
The textures are very uniform and neutral, so the mismatch would be barely visible, as seen here:

![image](https://user-images.githubusercontent.com/63756057/98687665-e6729180-2361-11eb-9bf0-d0c64bd893e8.png)

If that's not really what you want the game to look like, then I guess the third best thing would be, just like Peach suggested, to make the seams uniform and narrower.

**Comment by CaptainKronos** [comment]
Personally, I'm not the biggest fan of seams between bricks and such. SE does this well, where blocks placed down connect seamlessly with other blocks placed down afterwards.
I think that seams should just be done away with, sure it offers more detail at times (and I have kind of used that to my advantage) but in most circumstances I've encountered... they just make a build look worse.

**Comment by MRonlin** [comment]
I do have a love hate relationship with brick boarders. While they can be used to add details to a build, it can be quite unsightly when you want a smooth effect.

**Comment by tsunamayo** [comment]
Wait there is no border on the wedge? Must be mistake on my side. For several reasons I prefer to keep border on the bricks, but I will reduce them a bit. 
Main reason is to push players to use the stretch tech.
I cant do a smart tech on bricks, they are not voxel aware like the blocks.

**Comment by Garrett-C** [comment]
It would be much nicer if there was a way to choose between a border look and a non bordered look. Bricks do give you the option to get some really nice shapes for say a sleek ship but the borders then ruin the sleek look. 

That said they can also be used to add some extra detail so ideally you want a bit of both.

**Comment by ProPeach** [comment]
Ah, I thought this was your fix for #3184, but maybe it was just a bug introduced by it. Looking forward to seeing the thinner borders!

**Comment by tsunamayo** [comment]
No wedge are fine. Yes this fix removed the border for hepta, tetra and corner non-axis aligned side as I cant get a scaling border on all edges of the triangle.

**Comment by tsunamayo** [comment]
Okay I just made the border twice smaller, you will tell me how it look in next update. Thanks

**Comment by tsunamayo** [comment]
@ProPeach YOU GUYS WON - Rip borders 2021.
