### ISSUE TITLE
[BUG] warp doesn't include parked ships or weapons in item stands 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3205]
### Short Description of the issue:
After jumping twice I realized that all of the ships in my hanger were gone and the items in item stands were also gone
...

### Steps to reproduce the issue:
have a ship with other ships docked in it and item stands with items in them and then jump
...

### Environment
- Starship EVO version: 20w46a

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5518059/output_log.txt)

**Comment by tsunamayo** [comment]
Issue fixed for 20w46b. Thanks!
