### ISSUE TITLE
[Bug] Incorrect collision box on the corner brick

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3206]
Version 46A

Now that you fixed clipping, the collision bugs start to become apparent.
One I've encountered seems to be linked to the corner brick.
Here you can see it should fit just fine, yet it does not.
Still, it somehow can fit on the other side of the symmetry plane.

![image](https://user-images.githubusercontent.com/63756057/98739543-7257de00-23a1-11eb-8daa-84d82da10b0e.png)

**Comment by Kaiser-Indrasil** [comment]
Another one, this time with the tetra brick:

![image](https://user-images.githubusercontent.com/63756057/98739787-e8f4db80-23a1-11eb-8e08-1bec9a641be4.png)

**Comment by tsunamayo** [comment]
Hi, okay it seems related to children entity I guess? If you could send me the bp and paint the faulty area so I can find it! Cheers

**Comment by Kaiser-Indrasil** [comment]
Sure thing! Here you go:
[Agni - 46A.zip](https://github.com/tsunamayo/Starship-EVO/files/5520967/Agni.-.46A.zip)

Try to apply a tetra like this:

![image](https://user-images.githubusercontent.com/63756057/98750894-f1a3dc80-23b6-11eb-9abd-1572e3ccb671.png)

...and the corner like this:

![image](https://user-images.githubusercontent.com/63756057/98751076-47788480-23b7-11eb-9730-f141f0d86050.png)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Sorry to necro this, do you had still this issue recently? Thanks

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo I'm happy to report that I haven't for a very long while! Looks like you fixed the issue with Neovox :)
