### ISSUE TITLE
The jetpack is way too weak to be usable in many environments.

### ISSUE THREAD

**Issue by amplified1** [tsunamayo/Starship-EVO#3207]
depending on the gravity level sometimes using jetpack mode gives you less jump height than just normal walk mode jumping, I think it would make sense for the jetpack to scale to the gravity level so that it isn't too powerful to be usable in normal or lower gravity as well

**Comment by tsunamayo** [comment]
The jetpack is about to be removed for the locomotion refactor. Thanks
