### ISSUE TITLE
[SUGGESTION] Docking ports 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3210]
With the soon addition of fuel it would be nice to have a way to transfer fuel (and perhaps cargo and crew) from ship to ship. 

For this I suggest docking port, more specifically (maybe idk) 3 types of docking ports. Type one would be larger and possibly stretchable to connect large ships and transfer crew from a station to ship or from ship to ship instead of crew just magically teleporting to your ship (yes I know we have teleporters but eventually some is gonna say something along the lines of "why can't we just teleport fuel into our engines?"). 

The other connectors could come in different sizes, that being a 1x1x1 connector for cargo but maybe a .25x.25x.25 one for smaller cargo like ores. then for a fuel connectors there could be that .25x.25x.25 one but it would have a slower transfer rate (and maybe for smaller connectors they aren't two way like the larger ones so the small male can only output items while the small female can only accept items) and then large connector would be better as they would be faster and they can input and output items but small ships don't need to transfer 100s of items a second so its ok if their transfer speed is slower and if they need two connectors as having two blocks would be more symmetrical when placed on the top or bottom of a ship.

I don't know if any of that made sense its pretty early over here so if something doesn't make sense just ask for clarification!

**Comment by tsunamayo** [comment]
Hi, yeah make sense, but I dont want male / female I want something universal for simplicity. Thx

**Comment by AlienXtream** [comment]
you have a couple options. you could go for a merge block type thing like what SE does (but far more optimised naturally). for docking clamps the base should be universal but it should also be versatile enough for players to make their own. perhaps a slim part 2x2x0.25 that has a set orientation. when docking the player must pilot their ship close, match the orientation of their ship to the port and then activate the mag. this will pull the docking ship (lowest mass. if exact same mass first ship to initiate docking) closer until they are close enough and straight enough to each other that snapping into place would both be unproblematic and unnoticable. you should also consider some sort of "welding" mechanic using the same principle as the docking rules but that allows the 2 ships to permanently attach. not 100% sure how this would be done but its a must for survival as there will be cases where you need to get and attach things (or combine ships).
