### ISSUE TITLE
[Suggestion] Legacy Build

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Starship-EVO#3211]
Hi Tsuna,

So I saw [this ](https://youtu.be/r4S5Q-z8jMQ)video the other day and it got me thinking I know the clipping stuff from before can't exist in the game going forward for very good reasons but I thought it could be nice to have a legacy build around this point so people like kings cubed here can finish their build. Sure they won't have access to the new stuff going forward but it gives people a chance to finish stuff they have been working on. And having it as a legacy build means you can say "There will be bugs but that build won't change going forward"

I imagine it's not as easy as setting entity clipping to true or anything but if it was possible to have a build say around 20w41c saved as a legacy build it would give people a chance to finish their builds at least. It would be interesting to hear your thoughts on something like this at least. 

Thanks.

**Comment by tsunamayo** [comment]
Yep that sucks... I say it many time it was a bug but only here, so if people dont go the github then maybe they didnt knew...
Anyway yes I will create a clip legacy build, good idea. So at least people can finish their ship in there! Cheers

**Comment by Garrett-C** [comment]
Thanks for your response Tsuna. Glad to hear you are willing to add a legacy build with clipping. Hopefully it will allow people to finish what they are working on. Thank you.

**Comment by tsunamayo** [comment]
Okay the new legacy_clip branch is pushed with 20w41c. 
But this is temporary so you guy can finish your project, I would not like to see people starting working on new ship moving forward as it is just delaying  the problem, as I will have to remove the build at one point.
Save compatibility it is really hard, so at one point it will no longer be possible to guarantee it. (ie your old ship will be forever trapped to that version, that will be gone...)
Btw the character wont be compatible, so you will have to create a new one. 
Thanks

**Comment by Garrett-C** [comment]
Thanks, yeah that’s all totally reasonable and agreeable. That was the beauty of having be a legacy build. You can say that it won’t be supported forever, there may be comparability issues and then some time in the future you can remove it. But in a couple of months time a legacy build would likely be so old that nobody is really using it anymore so removing it hurts nobody. It’s more a measure to ease the transition.

**Comment by tsunamayo** [comment]
By the way I am not sure it will work actually, if you have your old blueprint from the previous default it will, but if you overwritten it with the new version it might not.

**Comment by Garrett-C** [comment]
Good to know. I will test it when I see the build go live. I have been sort of playing on a cheesed legacy build myself so it would probably be good to see someone who had a ship in a newer build load it in legacy, obviously newer features won't be there so we will have to see.

**Comment by Garrett-C** [comment]
Ok I can report that ships from the older builds are compatible but those saved in the new default build do not seem to be compatable. I tested with ships from the work shop and generally anything uploaded from the 11th of November onwards does not load. So I believe it is safe to say if you saved a blueprint after the update yesterday it isn't compatable. I guess testing the other way round is in order which I will do now.

**Comment by Garrett-C** [comment]
Ok the reverse is possible.

So in summary legacy to stable works.
Anything saved before yesterday can be backdated to legacy I believe.

Also as a small request, when you decide to discontinue legacy in a few months time might it be possible to recieve a warning like in one of the normal update posts have a line "Legacy build will be discontinued in 1 month" for example.
