### ISSUE TITLE
[Suggestion/Question] Will there be possibility/game performance/stability in the future, to create really big projects (3-5km)?

### ISSUE THREAD

**Issue by Zenti98** [tsunamayo/Starship-EVO#3214]
Would love to start a long time projects which grows and evolves with the game, just wanna know if there are planned improvements in the next months-years, which allow to spawn and work on oversized projects :-) surely just with afast GPU, thats okay

**Comment by matejkar** [comment]
sure, i definetly agree with this, however it also needs new blocks for building such massive ships, im talking 10x10m armor blocks, weapons that have 4m diameter, and other new blocks. With that being said, also the building limits should be increased from like 16x16x16 to about 32 or 36m3. 
First its better to add stuff like that, and then thing about their uses.

**Comment by tsunamayo** [comment]
I will do a improvement on the lighting system that will reduce the memory usage for large ship and fix some lag issue when building. Apart from that nope, it will always be  limited by  the fact that voxel are 1m (I give a fair shot at a smarter solution, it was way too complex). So you will have to stick with that tech.
Honestly you cant handle a 5km ship anyway ;)

**Comment by Zenti98** [comment]
> I will do a improvement on the lighting system that will reduce the memory usage for large ship and fix some lag issue when building. Apart from that nope, it will always be limited by the fact that voxel are 1m (I give a fair shot at a smarter solution, it was way too complex). So you will have to stick with that tech.
> Honestly you cant handle a 5km ship anyway ;)

Thank you! I just would like to know whether  there will be compatibility with later game versions so the work isn‘t for nothing - I am sure, there are many people who love to build massive projects, 5km is exzessive sure but maybe build a stardestroyer in original size and I would love to see that the game gives to possibility for that!

**Comment by matejkar** [comment]
@tsunamayo i wanna ask real quick, is there a possibility to add more powerful weapons, since the max length lasers and beams are simply too weak if we are talking capital ship combat (like 200m+ ships) and takes up to dozens of minutes for 2 ships to kill each other.

**Comment by tsunamayo** [comment]
I will first do a big pass on combat, and see if this is something we need to address this way. Honestly for gameplay npc ship I dont think I can go over 200m anyway for performance reason, so this is also something I will test. Thanks

**Comment by Uncle-Ulty** [comment]
thanks, @ProPeach. My suggestion is to implement large blocks to allow bigger structures with fewer blocks. I made this suggestion on #3247

**Comment by tsunamayo** [comment]
It would @Uncle-Ulty  alleviate some aspect (rendering) while making some other more stressed (memory, collision) because well people would build 10km ship instead of 1km. So not a solution. Also again I admire your commitment to make massive ship it is not the end goal of this game. I spend of a lot of time making sure you can make tiny details and stuff that works with the player. Had I wanted to make a gigantic oriented game I would have made very very different technological choice. Thanks all
