### ISSUE TITLE
Brick border incorrect

### ISSUE THREAD

**Issue by Vicomt** [tsunamayo/Starship-EVO#3216]
### Short Description of the issue:
brick borders appear to be too large on the chamfered brick

### Steps to reproduce the issue:
insert a chamfered brick next to a normal brick, so that you can see the borders.

### Environment
- Starship EVO version: 20w46b
- Graphics Card: GTX1070

### Additional information:
![bad border](https://user-images.githubusercontent.com/7197427/99000676-90ecdf00-2531-11eb-9beb-53128cfdfcd2.PNG)

**Comment by tsunamayo** [comment]
Issue fixed for 20w48a. Thanks @Vicomt !
