### ISSUE TITLE
6dof mode pivots by the feet instead of the head and it feels really unnatural to control

### ISSUE THREAD

**Issue by amplified1** [tsunamayo/Starship-EVO#3219]
it is completely inconsistent from the other locomotion modes, is this planned to be fixed when locomotion is redone?

**Comment by Kaiser-Indrasil** [comment]
It's been already gotten rid of, according to the latest devlog video.

**Comment by tsunamayo** [comment]
Yes indeed it feels weird, I will fix it. It is not inconsistent with other mode though as they do not tilt so it is something specific to 6dof. 6dof is not removed, only the jetpack mode is removed! Cheers

**Comment by Kaiser-Indrasil** [comment]
Speaking of the jetpack removal, I can see it's still there.
Is it planned for the next update?

**Comment by tsunamayo** [comment]
yes! thx

**Comment by tsunamayo** [comment]
Implemented for 20w46c. Thanks
