### ISSUE TITLE
[Suggestion] Bring back gimbal for guns linked from the Timer

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3221]
Version: 46B

So it used to be the case when we could arrange our guns in a firing sequence and still be able to use the gimbal assist, and it proved very convenient and intuitive.

Now it's only possible if guns are directly linked from the yoke, so if you want a gimbal assist, you must make them fire all in a salvo, rather than rapid-fire.

Could you make the timer blocks carry the gimbal signal as well, so we can have our gimballed rapid-fire gun arrays back?

**Comment by tsunamayo** [comment]
The problem is that you dont want a gimbal when you fire a weapon from a button for example. So it is actually a bit more complex, but yes I have to fix it. Thanks
