### ISSUE TITLE
[Question] Formula for Heat Dissipation

### ISSUE THREAD

**Issue by Lord-Mortangol** [tsunamayo/Starship-EVO#3222]
### Short Description of the question:

Can you pubish the formula for the heat dissipation calculation?

Thanks in advance!

**Comment by tsunamayo** [comment]
So each Hull block dissipates 5.
Each m2 of surface (any voxel with something in it) dissipates 7.5.
Thats it! Of course this likely will be rebalanced at one point.
Thanks
