### ISSUE TITLE
[Question] About monitors

### ISSUE THREAD

**Issue by Yzdren** [tsunamayo/Starship-EVO#3230]
Is it possible to design a screen box connected to the monitors so that the external situation can be seen from the inside.

It is similar to the cockpit of Star Citizen's Esperia.

There is a similar function in "Stormworks: Build and Rescue".

https://www.youtube.com/watch?v=clxSCVxscko&t=143s  

Can it be done?

**Comment by tsunamayo** [comment]
Hi, yes I can see the use but it would be too challenging rendering and performance wise. It would make the game lag too much unfortunately... Cheers
