### ISSUE TITLE
Target selection idea

### ISSUE THREAD

**Issue by Sidmoka7** [tsunamayo/Starship-EVO#3231]
### Short Description of the issue: I'm aware of that currently the dev, I forget your name sorry, is aware that some people have requested a rework of the targeting system and is going to work on that at some point, for which I had some ideas. I think that turret computers should have an option tab that would identify the gun as a primary, axillary, and point defense. Then, when in control of the ship, you can assign certain types of guns to fire at certain targets. This is the basics of my idea, but I also think it would be interesting if you could assign certain target ship categories to certain gun categories, for example you could set primary gun to only fire on categories Five, and set point blank weapons to only fire at category 1 through 3. But let's say you want your Point Blank turrets to fire at a category 5 then you can switch them to that while still in control of the ship, instead of having it to do it to every single turret individually.
...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: future
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by matejkar** [comment]
we can set them up to fire at different categories, idk if its still a thing tho

**Comment by chacalik** [comment]
It is a thing already. Just check yout Turret Core for more info.

**Comment by tsunamayo** [comment]
So you can already choose some ship size for the turret in auto-fire. I also plan to get a more evolving targeting system at one point, but as an advanced option (it is important to have something easy to learn as the default one). It was on my roadmap so I will close this for now. Thanks
