### ISSUE TITLE
[Suggestion] Save Debug Options, Anticlip Mode and Symmetry

### ISSUE THREAD

**Issue by chacalik** [tsunamayo/Starship-EVO#3232]
Just a very simple suggestion that could spare some time when opening a creative savegame where you are building something. Everytime I load the game, I have to hit F3, activate Allow Fast Movement, hit F5 for anticlip mode and then get the symmetry tool so I won't forget a make a whole side of the ship, remembering myself that I'll have to do exactly the same thing the other side.

Just a suggestion though.

### Environment
- Starship EVO version: 20w46b
- Graphics Card: RX590

**Comment by Kaiser-Indrasil** [comment]
I'd enable the option to "teleport to every entity" by default as well.

**Comment by ZachZent** [comment]
I'd keep the player clip mode off by default because it is turned on and off regularly when playing where the other modes stay on by default and how easy it is to turn it on and off. The rest however last default settings would be great

**Comment by tsunamayo** [comment]
So for the symmetry it is legitimate, could be considered as a bug. For the other I wont, you have to think about new players launching the game for the first time...
Thats one more key to explain, one more thing to screw up (it did happened back then..., player getting locked or zapping super fast)
Thanks
