### ISSUE TITLE
First person camera not working with ship yoke when sat in a rotating chair. 

### ISSUE THREAD

**Issue by vegax778** [tsunamayo/Starship-EVO#3235]
Short Description of the issue:

When entering my ship from the main yoke in first person the camera will not remain in the cockpit at the head of my character but will instead show me a perspective from outside the ship off centre. Seems to only occurs when using chairs placed on rotator blocks

Steps to reproduce the issue:

Use the main ship yoke in first person mode while sat in a chair on a rotator block

Environment
- Starship EVO version: 20W47A

Additional information:

![image](https://user-images.githubusercontent.com/74650052/99509283-7a091b00-297d-11eb-8327-4439a4b31db5.png)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5558990/output_log.txt)

**Comment by superfenrif** [comment]
I just posted a similar issue. Does yours just move the viewpoint or does it teleport your actual character model to that point outside the ship also?

**Comment by vegax778** [comment]
Yes it does. Didn't realise at first. Mine only happens when using a chair on a mechanism. My seat was on a rotator but when deleted it and placed the chair strait on the block it worked fine. However it has happened with chairs in rails and hinges aswell.

**Comment by tsunamayo** [comment]
Issue fixed for 20w47b. Thanks
