### ISSUE TITLE
[Bug] Cannot remap the keybinds

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3237]
Ver. 47A

No special steps are required - just go to the pause menu -> keybind section and try to rebind anything.
Works (or should I say, doesn't) every time.

**Comment by tsunamayo** [comment]
Hi, works for me. What is the exact test case? What is the first keybind you try, with which key (and also your log). It might be a special key that made your game bug. Thanks

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil hey mate I dont know if you have any more info on this ;) Cheers

**Comment by Kaiser-Indrasil** [comment]
The first keybind I tried is jetpack, but it doesn't work for any given keybind.
It just shows the "> <" symbol, waiting for entry, which I cannot provide, so I just cancel with the Escape button.
It instead assigns the one of the Joystick inputs for some reason.

I noticed I can manually change the keybinds within the Settings.ini file, once the game is closed.
It then correctly recognizes these keybinds, so I imagine the bug has something to do with how the game handles the input within the Keybinds menu itself, rather than just rejecting any and all attempts at changing the keybinds.

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Do you have a joystick plugged in? could you try to unplug it? What is the make of this joystick? Does it have a throttle knob (something that might be constantly set as a value non neutral) thx

**Comment by Kaiser-Indrasil** [comment]
I do have a gamepad...
And looks like it was the culprit ;)
Even when I had it unpowered, seems like the wireless adapter was enough to interrupt the input to the keybind menu.
The make is Nacon Revolution Unlimited Pro.

**Comment by tsunamayo** [comment]
Could it be the tactile zone? I dont know if this is something you can map. What was the button/axis mapped?

**Comment by Kaiser-Indrasil** [comment]
I believe it was one of the axes?

**Comment by tsunamayo** [comment]
Okay I guess it was a glitch with that controller... thx
