### ISSUE TITLE
[Bug] Endless loop of painting prohibits any block interaction

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3239]
Ver. 47A

Sometimes when I paint stuff, this happens.
It looks like painting is stuck in this endless loop, barring me from placing down and removing any blocks.
Just when I'm building and occasionally painting, there's no clear trigger.
Hopefully [output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5562857/output_log.txt) helps.

![Starship_EVO_M1ip666L7U](https://user-images.githubusercontent.com/63756057/99590595-71e4c600-29e5-11eb-8a0c-02a1839b4817.png)

**Comment by Kaiser-Indrasil** [comment]
Opening Codex seems to be the current workaround.

**Comment by tsunamayo** [comment]
Indeed there is some error in the log, I keep you posted! Thanks

**Comment by tsunamayo** [comment]
I cant manage to reproduce this, do you have an idea on how it happens? It happens often / quick? Thanks

**Comment by tsunamayo** [comment]
Fixed for 20w47b. Thanks!
