### ISSUE TITLE
[bug] Taking control of a yoke while sitting in a chair teleports the player character

### ISSUE THREAD

**Issue by superfenrif** [tsunamayo/Starship-EVO#3240]
I've noticed this on a few ships, including one I will link below from the workshop. If I sit in the pilots seat and take control of the yoke it teleports my player character to just outside the ship. This also shifts the point of view in first person mode. Doesn't seem to happen if you are not sitting in the chair.

https://steamcommunity.com/sharedfiles/filedetails/?id=2198932313&searchtext=

![teleportitis](https://user-images.githubusercontent.com/74686405/99596076-98a6fa80-29ed-11eb-9c3a-083d6155744b.gif)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5563107/output_log.txt)

**Comment by amplified1** [comment]
I have had this exact same issue, but it always returns me to my original position once I leave the yoke

**Comment by tsunamayo** [comment]
Hi, is it a chair on a children entity? Thanks

**Comment by superfenrif** [comment]
Yes, on the ship in the gifs the chair is mounted on a rail system.

**Comment by tsunamayo** [comment]
Issue fixed for 20w47b. Thanks
