### ISSUE TITLE
After the update walking movement is wierd and inconsistent for me

### ISSUE THREAD

**Issue by amplified1** [tsunamayo/Starship-EVO#3241]
### Short Description of the issue:

Whenever I look up or down while in walking mode my movement becomes slidy and doesn't respond to input very well, sometimes when I look up and move forward or down and move backwards my character seems to float up for a bit, This issue feels like for some reason despite being in walking mode it is taking some of the controls/physics from antigrav mode

### Environment
- Starship EVO version: 20w47a
- Graphics Card: 1080 ti

### Additional information:

https://imgur.com/a/ZL4ZHwA

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5563191/output_log.txt)

**Comment by tsunamayo** [comment]
Issue is fixed in 20w48a. Thanks for being active lately! Cheers
