### ISSUE TITLE
[bug] Controlling yoke seems to delete all constructed entities

### ISSUE THREAD

**Issue by superfenrif** [tsunamayo/Starship-EVO#3242]
I have a drone which I built yesterday. Worked fine with no issues untill this morning when it's started exhibiting this bug. After taking control of the yoke the player character disapears completely. In third person only the vehicle is visible. In first person no vehicles nor ring-habitats are visible. After releasing control of the yoke the I will then be stranded in the middle of empty space. Attempting to teleport to any ship on the list will teleport to the a different piece of empty space (Same for every ship attempted).

Below is the ships workshop entry:
https://steamcommunity.com/sharedfiles/filedetails/?source=Facepunch.Steamworks&id=2291460706

This is what happens when taking control of the yoke. The only input the game is getting from me is some slight mouse movements:
![cursed drone](https://user-images.githubusercontent.com/74686405/99597884-97c39800-29f0-11eb-904d-8c7724b7ed93.gif)

Changing from 1st person to 3rd person perspective. 1st person doesn't show any vehicles, nor the ring in the background.
![cursed drone 2](https://user-images.githubusercontent.com/74686405/99598092-ebce7c80-29f0-11eb-9d75-e8a9a1c41016.gif)

Releasing control of the yoke. All ships and the nearby ring no longer exist in the game
![cursed drone 3](https://user-images.githubusercontent.com/74686405/99598208-191b2a80-29f1-11eb-802d-4698183308d7.gif)

Attempting to teleport to ship (any ship on the list) teleports to this yellow nebula.
![cursed drone 4](https://user-images.githubusercontent.com/74686405/99598480-7f07b200-29f1-11eb-830c-d30f9e00889a.gif)

Just noticed that if I try and create another one of these drones they spawn in saying they are "destroyed" and do not move. 
![cursed drone 5](https://user-images.githubusercontent.com/74686405/99598870-284ea800-29f2-11eb-8014-34806693d3ec.gif)

**Comment by amplified1** [comment]
I have noticed a lot of glitches like this, sometimes the ship stops rendering when you control it, sometimes it destroys it, sometimes your view is teleported around 10 blocks away from where it should, it is very glitchy rn

**Comment by tsunamayo** [comment]
Issue fixed for 20w48a. It was with Yoke on children entity without being seated. Thanks!
