### ISSUE TITLE
[Crash] Crash generated a 52mb Output log

### ISSUE THREAD

**Issue by chacalik** [tsunamayo/Starship-EVO#3243]
### Short Description of the issue:
Game crashed while I was looking around my ship and pressed TAB to see its stats. Then I went to check the output log for a detailed info on the report, then realized that the output log txt was 52mb big.
...

### Steps to reproduce the issue:
Unknown.
...

### Environment
- Starship EVO version: 20w47a
- Graphics Card: Radeon RX590

### Additional information:
// Its compressed. When uncompressed, you'll se the size of that TXT.
[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/5563846/output_log.zip)

**Comment by tsunamayo** [comment]
Thanks, it seems to be mainly issues related to paint. I keep you posted.

**Comment by tsunamayo** [comment]
Paint issue fixed for 20w47b. Thanks
