### ISSUE TITLE
[suggestion] Large blocks for large build

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#3247]
For bigger projects (over 1km length), It would be easier if we had bigger blocks (e.g. 4x4x4, or 16x16x16, maintaining the same grid) to use, stretching it over large lengths and volumes. 
It'd mean fewer objects, but larger. Placing fewer objects, it'd be faster to build. And, maybe, consume less performance due to fewer objects and surfaces?

The same could be made for larger reactors, engines, hinges, and cores.

**Comment by ProPeach** [comment]
You might be interested in #3214 where a similar question was asked

**Comment by chacalik** [comment]
Ain't it possible already?!

**Comment by tsunamayo** [comment]
So I dont want to go down this rabbits hole! It would put a enormous stress on other aspect of the game. As explained in the other issue Starship EVO was not build with gigantism in mind, I get it as we dont have survival for now this is what a lot of people wants to do but the engine was not build around that. Thanks

**Comment by Uncle-Ulty** [comment]
I understand. The only reason I didn't make large ships is specifically this: with the current tools, a gigantic spaceship would require a lot of time and work.

My biggest object till now is a 8700 tons spaceship...
