### ISSUE TITLE
[Bug] Two of the default ships never spawn

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3250]
Version: 47A

When I was casually browsing the game files, I stumbled upon two I've never-ever heard about:
- The pirate ship Hammerhead Heavy Fighter Gimbal
- The civilian ship Nox Imperium Enterprises Cerberus Transport

They never spawn in the game and I can't help but wonder if that's a bug in their spawn behaviour or are they just waiting for their turn further down in the game development?

![image](https://user-images.githubusercontent.com/63756057/99665812-0987fa00-2a62-11eb-9a92-629fb4271390.png)

![image](https://user-images.githubusercontent.com/63756057/99665849-14db2580-2a62-11eb-903f-226357de6643.png)

![image](https://user-images.githubusercontent.com/63756057/99665882-21f81480-2a62-11eb-954c-6457bf87e0c4.png)

**Comment by matejkar** [comment]
I assume the civillian ship in the photo is the one in the background? if not can we get a pic of it

**Comment by Kaiser-Indrasil** [comment]
Yeah, it's the very one

**Comment by tsunamayo** [comment]
Yeah I need to redo a pass on that, I think they had some issue with the landing at the time this is why they were unplugged. Not a real bug ;)
