### ISSUE TITLE
[suggestion] save the text inputted on a sign even when you don't click off of the text input field

### ISSUE THREAD

**Issue by amplified1** [tsunamayo/Starship-EVO#3254]
I constantly lose a lot of inputted text because I forgot to click off of the text input on a sign before Xing out of it

**Comment by tsunamayo** [comment]
I see, it make sense to address this. I will put it as a bug.

**Comment by tsunamayo** [comment]
Okay I cant reproduce this bug. Does it happens on the text input screen or something else? What is the exact test case? Thanks

**Comment by tsunamayo** [comment]
@amplified1 any news on how to reproduce this issue? Thx
