### ISSUE TITLE
Paint Clouds of Doom!

### ISSUE THREAD

**Issue by NEURALDELVERM** [tsunamayo/Starship-EVO#3256]
### Short Description of the issue:
While painting a ship with symmetry on, I encountered the well-known bug of the paint particle effect continuing to duplicate. It then got worse and when I spawned the ship, it disappeared and became 2 globs of paint. I unloaded it again, and then tried to place a starter block, and then the bug happened again.
...

### Steps to reproduce the issue:
Load ship, symmetry mode, paint (maybe hold click instead of tap), save ship while encountering bug, then reload ship.
...

### Environment
- Starship EVO version: experimental - 20w47a
- Graphics Card: NVIDIA GeForce GTX 1050 Ti

### Additional information:
![20201120003016_1](https://user-images.githubusercontent.com/23009112/99778448-8d74cd00-2ac8-11eb-9891-8a2ccbd88ef5.jpg)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5572262/output_log.txt)
[DxDiag.txt](https://github.com/tsunamayo/Starship-EVO/files/5572297/DxDiag.txt)
[[NDM] KITE RACER.zip](https://github.com/tsunamayo/Starship-EVO/files/5572326/NDM.KITE.RACER.zip)

**Comment by tsunamayo** [comment]
Thanks for the solid test case, I keep you posted.

**Comment by tsunamayo** [comment]
Fixed for 20w47b. Thanks!
