### ISSUE TITLE
Player teleports outside of ship when entering yoke

### ISSUE THREAD

**Issue by SovietSponge** [tsunamayo/Starship-EVO#3257]
### Short Description of the issue:
When sitting in a chair and entering the yoke the player gets teleported outside but otherwise pilots the ship with no issue
It doesn't seem to happen when entering the yoke without sitting in a chair 

### Steps to reproduce the issue:
Sit in chair
Enter yoke connected to ship core

### Environment
- Starship EVO version: early access 20w47a
- Graphics Card: gtx 1050 ti

### Additional information:
![16058625870161996822530879793593](https://user-images.githubusercontent.com/66131361/99780357-ae640f00-2b16-11eb-98fe-0a85b48e5b5d.jpg)

**Comment by tsunamayo** [comment]
Is the chair on a children entity? Thanks

**Comment by tsunamayo** [comment]
Issue fixed for 20w47b. Thanks
