### ISSUE TITLE
Seats on sliders are now broken.

### ISSUE THREAD

**Issue by Ninerex** [tsunamayo/Starship-EVO#3258]
### Short Description of the issue:
Seats attached to sliders give incorrect camera view when connecting to a yoke.
...

### Steps to reproduce the issue:
Attach a seat to a slider. Set up a yoke and ship controller. Sit in the seat and connect to the control yoke. Observe bad camera position. 
...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by tsunamayo** [comment]
The issue was already fixed for 20w47b. Patch live soon. Thanks
