### ISSUE TITLE
[bug] Painting sometime breaks

### ISSUE THREAD

**Issue by Citronix** [tsunamayo/Starship-EVO#3260]
I was painting my ship, bricks if that matter, and the paint gun just stop working, i couldn't paint anymore and the paint particules where still generating where i was originaly painting. A restart fix it. I encounterd this bug twice will building my ship for the competition 2.

Environment
- Starship EVO version: Experimental 20w47a
- Graphics Card: Nvidia geforce 1660ti

Additional information:
[Spoiler]

![711980_20201121155511_1](https://user-images.githubusercontent.com/33103748/99880251-a2f60e00-2c12-11eb-95ac-693914ed6f52.png)
![711980_20201120214723_1](https://user-images.githubusercontent.com/33103748/99880260-b86b3800-2c12-11eb-9e26-f22907d03bfb.png)

**Comment by tsunamayo** [comment]
Fixed for 20w47b. Thanks
