### ISSUE TITLE
Deleting issues

### ISSUE THREAD

**Issue by SidTaylor** [tsunamayo/Starship-EVO#3261]
### Short Description of the issue:

...When deleting the large hinge it only deletes half of the hinge. The other half will not delete.

### Steps to reproduce the issue:

...spawn a hinge and try to delete it

### Environment
- Starship EVO version: 20w47a experimental
- Graphics Card: gtx2060

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5577850/output_log.txt)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by Ninerex** [comment]
I have the same issue. I also cannot delete blocks some blocks attached to large hinges.

**Comment by tsunamayo** [comment]
@SidTaylor @Ninerex  I cant reproduce, the hinge deletion works fine on my side. Could you send me your blueprint in which you have some issues?
Thanks

**Comment by Ninerex** [comment]
This was resolved for me in the second 47b update. Thanks

**Comment by tsunamayo** [comment]
@Ninerex good to hear. Thanks
