### ISSUE TITLE
[suggestion] Timer logic blocks should have a setting that lets them release instantly instead of on a delay one way

### ISSUE THREAD

**Issue by amplified1** [tsunamayo/Starship-EVO#3264]
I have been trying to create a vault door where it becomes flush with the wall when closed but when opened it pulls out of the wall and moves to the side, I can get it to work closing but I can't figure out what logic combo is needed to have the piston that pulls the door inwards pull in before the piston that moves the door away moves. So I was thinking that it would be cool if timers had a setting that lets them ignore the delay on either starting or stopping a pulse. so you can have a timer that takes 2 seconds to let the signal through, but stops the signal instantly, or something like that

**Comment by amplified1** [comment]
if someone knows how this could be done with the current logic that would be nice too

**Comment by ProPeach** [comment]
If I've understood you correctly, an ABBA circuit could help a lot here - 
https://cdn.discordapp.com/attachments/342383722185883648/713423735687872546/Starship_EVO_GXf2uDkHGR.png


Blue activates first, then green on the first button press. On the second, green activates first then blue. Link the gates to the sequencers that controll your door

So this can be used for the door to pop out and slide, then slide and pop back in with just a button

**Comment by amplified1** [comment]
hey thanks

**Comment by amplified1** [comment]
Worked perfectly, can't believe I didn't figure it out considering how simple it is

**Comment by ProPeach** [comment]
Glad to hear it!

**Comment by tsunamayo** [comment]
Thanks @ProPeach! Yes ABBA is super elegant once you understand it! Cheers
