### ISSUE TITLE
Piston Ghost is following me...

### ISSUE THREAD

**Issue by EmceeAlpin** [tsunamayo/Starship-EVO#3266]
### Short Description of the issue:

After attempting to place a piston in several places on my build, I noticed an issue. The piston doesn't fully place, only half of the piston. Then when trying to remove the piston, it won't delete. In fact, it seems no other block or bricks will delete. Additionally, there was a severe frame rate drop. Upon reloading the world, the frame rate was normal, however a ghost brick of the piston follows me around the world wherever I go, in the same orientation that it was place previously.

### Steps to reproduce the issue:

Place piston on build, try to delete the piston, check frame rate. Log out of world, Log back into world and check for floating piston piece.

### Environment
- Starship EVO version: 20w47b
- Graphics Card: Nvidia GTX 1080

### Additional information:

An example of a half piston (Note the frame rate):

![20201121200707_1](https://user-images.githubusercontent.com/51394074/99892288-127ef400-2c39-11eb-8bd7-d0adb79c1c0f.jpg)

Several examples of the ghost piston following me:

![20201121200657_1](https://user-images.githubusercontent.com/51394074/99892307-44905600-2c39-11eb-8626-3602585ba71a.jpg)
![20201121200643_1](https://user-images.githubusercontent.com/51394074/99892309-4d812780-2c39-11eb-9b0b-4e0354005ef5.jpg)
![20201121200630_1](https://user-images.githubusercontent.com/51394074/99892311-53770880-2c39-11eb-89fc-0f43046450d3.jpg)

Here's the Output log:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5578825/output_log.txt)

Here's the Build I was working on:

[Class C Shuttle WIP04.zip](https://github.com/tsunamayo/Starship-EVO/files/5578826/Class.C.Shuttle.WIP04.zip)

Here's the World I was building in:

[Utopia Planitia.zip](https://github.com/tsunamayo/Starship-EVO/files/5578827/Utopia.Planitia.zip)

**Comment by tsunamayo** [comment]
Okay it was a pretty serious one, so I repushed the build 20w47b with this fix. It live now. Thanks!

**Comment by EmceeAlpin** [comment]
Thank you!
