### ISSUE TITLE
[Bug] Small Slider Won't Place/Glitches [+ extreme fps loss]

### ISSUE THREAD

**Issue by Daoja1** [tsunamayo/Starship-EVO#3267]
[EDIT] Correction:  Sliders not hinges.

### Short Description of the issue:
When trying to place small slider on any ships (last tried on ships in tutorial area), only the base (I'm assuming it's the 'base') places and can't be deleted.  Sometimes it spawns a bit later, followed by extreme fps dip (see screenshot).

### Steps to reproduce the issue:

- Attempt to place small slider on any ship.
- Try to delete.

### Environment
- Starship EVO version: 20w47b [Experimental]
- Graphics Card: AMD RX 480

### Additional information:
Attempt made with tutorial area ships
![20201121230659_1](https://user-images.githubusercontent.com/74845793/99893627-9ba12580-2c4f-11eb-8005-975e50fd03dd.jpg)

Note the overlapping after they glitch spawn in
![20201121230740_1](https://user-images.githubusercontent.com/74845793/99893672-b378a980-2c4f-11eb-805f-6102c6bfb87a.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5578891/output_log.txt)

**Comment by tsunamayo** [comment]
Okay it was a pretty serious one, so I repushed the build 20w47b with this fix. It live now. Thanks!
