### ISSUE TITLE
[Bug] Unable to interact with the blueprint after drawing a few logic links

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3268]
Version: 47B but also present in the stable branch.

I've been making links between a landing gear hotkey switch and various mechanisms, and suddenly, I couldn't draw a link.
I couldn't build any block, either on that grid.
I suspect it's somehow connected to #3190 because once it produced the black skybox bug upon the world restart.

Here's the output log:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5580732/output_log.txt)

And here's the affected blueprint:
[Agni - asdasdasdasd.zip](https://github.com/tsunamayo/Starship-EVO/files/5580734/Agni.-.asdasdasdasd.zip)

**Comment by Kaiser-Indrasil** [comment]
Reproducing steps:

1. Place down a hotkey gate
2. Set it to switch and landing gear
3. Draw a 2, maybe 3 links from it
4. You shouldn't be able to placy any more and interact with any grid in any way.

**Comment by tsunamayo** [comment]
So it was because of the Hoverpod. Fixed for 20w48a. thanks!

**Comment by Kaiser-Indrasil** [comment]
Oh, right, I have one of these on my build for greebling! Nice catch!
