### ISSUE TITLE
[Bug] reloading made my game made every ships disapear

### ISSUE THREAD

**Issue by Citronix** [tsunamayo/Starship-EVO#3271]
After leaving the game (just after the issue #3270 ) all of my ships and starting ships/building disapeared.
...

→Steps to reproduce the issue:
I don't know if it's reproducable
...

→Environment
- Starship EVO version: 20w47b experimentale
- Graphics Card: Nvidia Geforce 1660 ti

![711980_20201123173723_1](https://user-images.githubusercontent.com/33103748/99992729-05880f00-2db7-11eb-8ac7-ca300d357953.png)

**Comment by tsunamayo** [comment]
I need something to investigate to help you... Could you please send me the log and your character save zipped? thanks

**Comment by domesz09** [comment]
This also Happened to me I was connecting a yoke to a ship computer and then everything (movement and looking around) froze, so i quit to main and while that happened i saw my build dissaper, when i got back everything dissapered.
No build was lost cuz i just saved before that.
(Edited the id number becouse idk if thats important for my security, this being public and all)
> _Initialize engine version: 2018.3.14f1 (d0e9f15437b1)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1660 Ti (ID=*****)
    Vendor:   
    VRAM:     5991 MB
    Driver:   27.21.14.5730_

**Comment by tsunamayo** [comment]
@domesz09 Thanks for reporting that, but I need the full log file to investigate anything...
Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by domesz09** [comment]
It says its too large so thats why i didint attach it for the first time, but here you go.
https://drive.google.com/file/d/1lxNY7i1ApB3Z-5SZP1X_FzPFlK0eulqk/view?usp=sharing

**Comment by tsunamayo** [comment]
@Citronix Issue should be fixed in 20w49a, it was the quit to title that was broken. Thanks
