### ISSUE TITLE
[SUGGESTION] Double or Triple placement range for copy/paste tool

### ISSUE THREAD

**Issue by nokturnihs** [tsunamayo/Starship-EVO#3274]
Double or triple the placement range for copy/paste because pasting larger (8x8+) becomes difficult to place with any precision. This can lead to a LOT of spamming the delete button to remove a badly placed paste (like deleting a fully decorated crew cabin and living areas for example)

**Comment by ProPeach** [comment]
A longer reach for the paste tool would be fantastic. For now I'm using Dwarf Lord Pangolin's trick of checking out the paste ghost in the F6 camera mode before pasting to make sure it's lined up correctly, you might find that a little more reliable (if time consuming)

**Comment by tsunamayo** [comment]
Ho I see, it make sense to have something that scale with the size of what you are building then. I keep you posted.

**Comment by tsunamayo** [comment]
Done for 20w48a. Thanks
