### ISSUE TITLE
 All vehicles/structures gone after crash

### ISSUE THREAD

**Issue by LucasStraub** [tsunamayo/Starship-EVO#3275]
### Short Description of the issue:

After several times going out menu screen to game all vehicles/structures were unspawned after crash. Even tutorial areas and starter vehicles are gone.

### Long Description of the issue:

I was trying to make a vehicle that could alter between spaceship and hovercraft with one button. Game stoped me from edit and interact with the ship after linkin components. Going back to the menu screen and then back to the game fixed the missbehaviour for me, but a doing it feel times later my game crashed and when I booted back, all ships and structures were gone.

### Steps to reproduce the issue:

1. Build a platform with a Starter Block.
2. Add an Simple Seat, two Yokes, a Hovercraft Computer and a Spaceship Computer.
3. Link Simple Seat with both Yokes, one Yoke with the Hovercraft Computer and the other with the Spaceship Computer. _(This will make the player to pop to the seat - maybe another bug)_
3. Add Small Reactor, Hover Pods and Small Thurster (As the minimum for a hovercraft and a spaceship to work).
4. Add a Hotkey Gate (setted to Hotkey 1 and Switch mode) and an Logic Gate (setted as NAND).
5. Link Hotkey Gate to the Logic Gate, and spaceship components (thursters); and Logic Gate to hovercraft components (hover pods and thursters). _(This should make you unable to edit the ship forcing you to reboot)_
6. If unable to edit the ship go back to the main menu and then back to the game scene.
7. Repeat steps 5 and 6 as needed. _(This should make the game crash)_

### Environment

- Starship EVO version: 20w46b
- Graphics Card: NVIDIA GeForce GTX 1050

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5586679/output_log.txt) (First time)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5586751/output_log.txt) (Tried to reproduce without sucess, but game crashed like the first time)

**Comment by LucasStraub** [comment]
Sorry, I forgot to add the tag "[Bug]" in the tittle and I can't edit it

**Comment by tsunamayo** [comment]
@LucasStraub thanks for booking this, no pb for the title. Could you send me the blueprint? I have just fixed the problem for 6.
I think I will prevent you from doing 3, Player should enter only a single yoke otherwise I think could cause all sort of issues.
Thanks

**Comment by LucasStraub** [comment]
@tsunamayo, I didn't have the blueprint from when I got the bug, so I tried to reproduce and got a new blueprint of it: [Spaceship-Hovercraft.zip](https://github.com/tsunamayo/Starship-EVO/files/5587062/Spaceship-Hovercraft.zip)

> Player should enter only a single yoke otherwise I think could cause all sort of issues.
Thanks

I think being able to switch modes (spaceship to hovercraft now) it's a really nice feature to have. Like, Hovercraft + Turret or Spaceship + Turret works pretty well (if you not connect a camera with the turret), you can press tab to make aim without moving your ship. But sure, sadly it might bring issues with it :/

Btw, after I reported the issue here I was able to make the hibrid ship ([Working-Hibrid.zip](https://github.com/tsunamayo/Starship-EVO/files/5587127/Working-Hibrid.zip)). 
I worked around by linking two hotkey switches, one for each yoke, setted as Hotkey 1. Then I first likend spaceship components to switch 1 and hovercraft to switch 2, and just by the end linking the yokes to the seat.
But... It didn't work as I was expecting. Since both hovercraft and spaceship uses left, right and forward thursters, I was unable to turnoff the spaceship pitch, making it hover too much if I bump into something. It basically became a spaceship with an "anti-ground-hit".

**Comment by tsunamayo** [comment]
Okay I can confirm that the this is no longer making the game bug in 20w48a. Yes I can see why it would make sense, I think I need a more builtin way for allowing an hybrid. So for now I will prevent it will thinking on the best way to do this! Cheers
