### ISSUE TITLE
low fps after warp

### ISSUE THREAD

**Issue by KittyCat-glitch** [tsunamayo/Starship-EVO#3278]
### Short Description of the issue:

Got 4-5 fps and 100% CPU load instant after jump to "virsus" system.

### Steps to reproduce the issue:

All i did was a jump to the "virsus" system to test new warp mechanics.

### Environment
- Starship EVO version: 20w46b
- Graphics Card: Nvidia RTX 2060
- Central Processing Unit: Intel(R) Core(TM) i7-8750H CPU @2.20Ghz 2.21Ghz (3.7Ghz max)

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5589851/output_log.txt)

**Comment by tsunamayo** [comment]
@KittyCat-glitch Hi, thanks for booking the case. I dont think this log file correspond to the session. Could you try to reproduce and send me the right log file? Thanks

**Comment by KittyCat-glitch** [comment]
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5593468/output_log.txt)
Managed to do it on another save , was just jumping around. Saw few interesting things: Fps was dropping lower and lower as i was adding new warp cores , removing existing warp cores didn't help return fps back to normal , also 
![Starship_EVO_Ccyxz7Ovz7](https://user-images.githubusercontent.com/74967741/100165243-7405c380-2ec2-11eb-90b3-f5857514633f.png) 
heat and energy displayed as NaN ( Not a Number ) , and  to top it off - this time game ate not only CPU , but RAM as well 
![Taskmgr_6MgkoWgqsW](https://user-images.githubusercontent.com/74967741/100165291-93045580-2ec2-11eb-9082-50099996d7cc.png)
I think those fps drops with adding warp cores and heat + energy displayed as NaN somehow connected.Sorry i wasn't able to record a video , my system was struggling enough to keep the game running at least at 2 fps 0_0

**Comment by tsunamayo** [comment]
Hi, thanks for the extra info. Did you added those core after the initial warp and FPS drop?

**Comment by tsunamayo** [comment]
Ah sorry it is indeed an issue already fixed but not the default branch, it will be fixed when default catches up to experimental. Thanks!

**Comment by tsunamayo** [comment]
@KittyCat-glitch I will push the build with the fix very soon (today)

**Comment by KittyCat-glitch** [comment]
Sorry i didn't answer you , it was 3 am for me and i fell asleep  :D Glad it's already fixed.
