### ISSUE TITLE
You still slide on the ground when looking up or down and also when you jump you always jump above your head and not up

### ISSUE THREAD

**Issue by amplified1** [tsunamayo/Starship-EVO#3279]
The floatiness is fixed but some of the glitch still remains

**Comment by amplified1** [comment]
Oh yeah and also it is still really easy to clip through blocks if you have basically any speed, falling ~6 blocks at 1x gravity is enough 
velocity to clip through exactly one block

**Comment by ProPeach** [comment]
I noticed this too, if you aim down at your feet and jump, the character jumps forward

**Comment by tsunamayo** [comment]
Not sure to understand... There is three issue right?
 - collision stuck on fall
 - some wrong jump logic
 - some slide behaviour
I dont get much the last two. Thanks

**Comment by ProPeach** [comment]
Here's a video of the jump logic one - https://i.imgur.com/mRjw4R1.mp4
Expected behaviour when you look down and jump is that you jump straight up in relation to the gravity. What actually happens is you jump forward, so "up" in relation to the players view

**Comment by ProPeach** [comment]
Looks like you can reproduce the sliding behaviour by looking directly up or down while standing still in walk mode. It's more noticeable if you stand on some flat hull blocks on the torus with a point of reference visible

**Comment by amplified1** [comment]
basically if you are looking up or down your feet lose all friction

**Comment by tsunamayo** [comment]
Okay issues fixed for 20w48b. Feels much better now! I cant reproduce the stuck issue though, is this something you also get @ProPeach ? cheers

**Comment by ProPeach** [comment]
I can't reproduce the collision issue, even falling from 100 m or so. I have heard that one the game is lagging from other issues collision can get unreliable, so perhaps that's it @tsunamayo
