### ISSUE TITLE
[Bug] Rotate arrow persist when swapping from copy/paste tool

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3280]
### Short Description of the issue:
When you swap from the c/p tool to another tool or empty slot, the rotation arrow from the c/p tool persists
![image](https://user-images.githubusercontent.com/27857711/100129886-fc13ab00-2e79-11eb-9083-da07fd4747e2.png)

### Steps to reproduce the issue:
Copy something using the c/p tool
Aim at a ship as if you were going to paste
Swap to another tool (it must be next to the c/p tool on your hotbar), or swap to an empty slot

### Environment
- Starship EVO version: 20w48a
- Graphics Card:RX 580

**Comment by tsunamayo** [comment]
Fixed for 20w48b. Thanks ;)
