### ISSUE TITLE
[BUG] Deleting a Hinge, Rotor, Slider, Piston While In Motion Causes an Infinite Audio Loop

### ISSUE THREAD

**Issue by Rizzo911** [tsunamayo/Starship-EVO#3282]
### Short Description of the issue:
If you delete an engineering block/brick while it is moving and its sliding/moving sound is playing, the sliding sound continues to loop indefinitely. You have to restart the game session to clear the sound.

### Steps to reproduce the issue:
Create a hinge | rotor | slider | piston
Create a switch and link to the item created above
Start the transition (extend, retract, rotate, etc)
As soon as audio starts to play, delete the engineering brick/block (i.e. hinge)
Sound of movement loops indefinitely

Expected behavior: deleting a brick/block should also delete any fx sounds associated with it from the audio manager

...

### Environment
- Starship EVO version: 20W48A (also is in current stable version)
- Graphics Card: GeForce GTX 960

**Comment by tsunamayo** [comment]
Fixed for 20w48b. Thanks!
