### ISSUE TITLE
[Bug] Player rolls a little bit when you transition gravity fields

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3283]
### Short Description of the issue:
When you fly up out of the torus gravity field, the player can tilt to one side if they are flying diagonally up/sideways or up/backwards. You can see the screen tilt in the clip below a little bit, but sometimes I've been tilted up to 20 degrees. Not sure what causes the larger tilts yet

https://i.imgur.com/So4eBbq.mp4

### Steps to reproduce the issue:
Fly up/sideways by holding space and A or D at the same time

### Environment
- Starship EVO version: 20w48a
- Graphics Card:RX 580 

###Additional Information

[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/5591682/output_log.zip)

**Comment by tsunamayo** [comment]
Issue fixed for 20w48b. Thanks!
