### ISSUE TITLE
[Bug] Player drifts when walking

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3284]
### Short Description of the issue:
Similar to the sloppy rolling we were talking about in 6dof, the player also drifts when you use WASD which causes the controls to feel unresponsive and makes small movements hard. This is maybe understandable with a jetpack or in 6dof as "in universe" the suit needs a second to slow you down, but it should not be a factor when walking

### Steps to reproduce the issue:
Hold any of the WASD keys for half a second, then release them. You can see that the character keeps moving for a fraction on a second

### Environment
- Starship EVO version: 20w48a
- Graphics Card:RX 580

**Comment by tsunamayo** [comment]
I already reduced that and it felt pretty fast to me... 
A couple question: what are you FPS? Do you use head bobbing?
Thanks

**Comment by ProPeach** [comment]
I have 60FPS with Vsync on, and headbobbing off.
In other games, you stop almost immediately when you take your fingers off the keys. In SEVO you slide about 25cm even at normal walking speed

**Comment by tsunamayo** [comment]
So it was linked to the other locomotion issue. Basically if you looked forward it was okay, but the more down you looked the longer it took. Now fixed, but I still reduced the response time. You will tell me how it is in next update.
