### ISSUE TITLE
[Bug] Camera mode interferes with gravity alignment

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3285]
### Short Description of the issue:
After rolling in camera mode. the player becomes unable to align to a gravity field after exiting camera mode
https://i.imgur.com/zaLtY6i.mp4

### Steps to reproduce the issue:
Enter camera mode
Roll
Exit camera mode and fly into a gravity well

### Environment
- Starship EVO version: 20w48a
- Graphics Card: RX 580

**Comment by ProPeach** [comment]
Looks like if you fly out of a gravity well, the character starts spinning uncontrollably

**Comment by tsunamayo** [comment]
Thanks for being on the ball mate, I keep you posted ;)

**Comment by tsunamayo** [comment]
Issue fixed for 20w48b. Cheers
