### ISSUE TITLE
[Bug] Canopy tile brick border thickness

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3287]
### Short Description of the issue:
Pretty small one, but the edge of canopy bricks have the old double thickness brick border still

![image](https://user-images.githubusercontent.com/27857711/100153859-a3a1d500-2e9c-11eb-89e0-736c3d14c2f1.png)

### Steps to reproduce the issue:
Place down a canopy tile piece and a brick cube to compare

### Environment
- Starship EVO version: 20w48a
- Graphics Card: rx580

**Comment by tsunamayo** [comment]
Fixed for 20w48b. Cheers
