### ISSUE TITLE
[Bug] Paint splash regression

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3289]
### Short Description of the issue:
Looks like a resurgence of #3239 and similar, an infinite paint splotch appears when painting with the mirror tool on.
It happens pretty consistently with this build (although it's still not every time) - 
[Starship MK1.zip](https://github.com/tsunamayo/Starship-EVO/files/5593057/Starship.MK1.zip)
![image](https://user-images.githubusercontent.com/27857711/100157624-bddeb180-2ea2-11eb-839a-0c207f493196.png)

### Steps to reproduce the issue:
Enable mirror down one of the axis of symmetry of the ship
Paint an unpainted brick (I was using silver)

### Environment
- Starship EVO version: 20w48a
- Graphics Card: rx 580

### Additional information:

[output_log (2).zip](https://github.com/tsunamayo/Starship-EVO/files/5593062/output_log.2.zip)

**Comment by tsunamayo** [comment]
So it seems to happen only if you spawn the blueprint in the session, not after reload. I keep you posted.

**Comment by tsunamayo** [comment]
Okay fixed for 20w48b. I will fix a bunch more bug and push a new build. Thanks!
