### ISSUE TITLE
[Bug] FPS loss through switching movement mode

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3290]
### Short Description of the issue:
Sorry to spam you so early in the morning with all these, but they just keep popping up...
Sometimes, I experience FPS loss from changing movement mode. You can see in the video I load a new world from a fresh game start, switch movement mode to hop up a ledge and then switch back. Throughout the process I go from a stable 60fps with Vsync on to 30, then back up to 60
I've zipped up the video so you can see the FPS counter graph
[Starship EVO Locomotion Mode FPS Loss.zip](https://github.com/tsunamayo/Starship-EVO/files/5593486/Starship.EVO.Locomotion.Mode.FPS.Loss.zip)

### Steps to reproduce the issue:
Enable jetpack mode
Fly a little
Disable jetpack mode

I know this is super vague for now, I'll update the post if I find something more concrete

### Environment
- Starship EVO version: 20w48a
- Graphics Card: rx 580

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5593483/output_log.txt)

**Comment by tsunamayo** [comment]
Are you positive it happened several time when doing the switch? It is weird indeed I will see if I can reproduce.

**Comment by ProPeach** [comment]
Positive, here's a clip of me changing mode a few times with a drop every time I hit J. The FPS does rise back up to 60 after about 7 seconds each time, but the drop is consistent. (It's a minute so Github won't take it)
https://drive.google.com/file/d/1zO7jXDw8i61ucrMpOWlnaWEOhQ0oxQzS/view?usp=sharing
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5599092/output_log.txt)

**Comment by ProPeach** [comment]
@tsunamayo this is still happening every time I change movement mode, even in a new world in the latest experimental patch 
[Starship EVO FPS Loss on Movement Toggle.zip](https://github.com/tsunamayo/Starship-EVO/files/5898339/Starship.EVO.FPS.Loss.on.Movement.Toggle.zip)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/5898336/Player.log)
However, this change only occurs when in the ringworld, I don't get the performance drop out in space.

The grass rendering seems to have the highest impact on this drop, if I disable that then the drops are smaller, but still very noticeable

**Comment by tsunamayo** [comment]
@ProPeach Fixed for 21w51a, easily my most shameful issue...
