### ISSUE TITLE
[BUG] game not saving when exiting to desktop 

### ISSUE THREAD

**Issue by KINGrimson** [tsunamayo/Starship-EVO#3293]
### Short Description of the issue:
game not saving when exiting to desktop. i was building and when i wanted to quite i pressed exit to desktop. when i later got back on the world i found parts of my build missing and sometimes even being in a different spot. had it happen a few times already. so far hasn't been anything big missing but can foresee it causing bigger problems

### Steps to reproduce the issue:
go into a world. build something. exit to desktop, then go back in to the world to see missing parts

### Environment
- Starship EVO version: 20w48b
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5596711/output_log.txt)
`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by tsunamayo** [comment]
Indeed. Issue fixed for 20w48c. This is a pretty serious one so I will push a patch very soon. Thanks!

**Comment by KINGrimson** [comment]
no problem happy to help any way I can
