### ISSUE TITLE
Frosted Window Shader Priorities

### ISSUE THREAD

**Issue by Gliese-832-c** [tsunamayo/Starship-EVO#3297]
### Short Description of the issue:
It looks like some of the rendering priorities of the frosted window shader are messed up. It should probably be rendered before the ghost block (the white hologram looking thing that represents the block you are about to place) and the dot and cross grid.

### Steps to reproduce the issue:
Place down a frosted or frosted pattern window.

### Environment
- Starship EVO version: 20w48b
- Graphics Card: MSI RX 570 8G Armor OC

### Additional information:
![grafik](https://user-images.githubusercontent.com/55159077/100268830-e7a4e080-2f55-11eb-915d-62f08ca20060.png)

**Comment by CurioInventorium** [comment]
This is most likely the same issue as #2961

**Comment by tsunamayo** [comment]
Thanks indeed you are right!

**Comment by tsunamayo** [comment]
Fixed for 20w48d. Thanks!
