### ISSUE TITLE
[BUG] Multiplayer is incredibly borked- a whole medly of issues

### ISSUE THREAD

**Issue by StarrKiss** [tsunamayo/Starship-EVO#3298]
### Short Description of the issue:

To start with, the abomination of characters as seen before is present whenever a client logs on- they spawn in a nightmarish mess of warped character models. 
![proogas](https://user-images.githubusercontent.com/13007697/100268882-5284f600-2f1b-11eb-9e42-144763b46753.png)

Luckily, unlike last time we had this issue, the client CAN MOVE AROUND +SPAWN SHIPS and the host doesn't experience unusual behavior. Unfortunately, this is where the issues started. Firstly, whenever the client teleports to a ship, they do not teleport to the ship, but to a seemingly unrelated location. For instance, when I had my friend teleport to my dual-seat fighter landed on ring world, the friend spawned in the middle of space about 100 km away from ringworld, then when my friend tried to teleport to my flagship in empty space, they spawned under the ground ringworld. Later, when my friend tried to teleport to a station, they teleported to the center of the sun. Eventually, they spawned in around 120km away from a station I was at, was able to spawn in a ship, and we were able to meet up, at which point things went somewhat ok for a little bit- gunfire and combat worked. But, when I asked my friend to sit down in a ship with me, we realized that we didn't see the other in their seat- At my seat on the helm, I saw myself sitting down, but not my friend in the gunners seat, and vice versa. Then, we tried to warp to another star system. While I saw the warp trails, my friend DID NOT, but did see the ship moving- what we thought was a postiive sign. But then, the ship vanished for the client (my friend) and they were stuck in some odd space while I successfully moved over to another star-system. From that point on, whenever my friend tried to build a starter block (to warp to where I was) it looked like this: (his screenshot)
![image](https://user-images.githubusercontent.com/13007697/100269377-0be3cb80-2f1c-11eb-97b0-6a4652650a4a.png)
and nothing spawned. So I decided to warp back to the starter system to see if that fixed things. However, as soon as I arrived back at the starter system, my FPS plummeted from ~130 to 15, sometimes dropping into the single digits, and my friends issue was not fixed. To conclude- Multiplayer is truly and utterly borked. It's just  broken at this point in time. 

Here is the output log: 

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5598696/output_log.txt)

### Steps to reproduce the issue:
Host a server and have literally anyone join.

### Environment
- Starship EVO version: Latest experimental
- Graphics Card:  GTX 1070 ti on host, GTX 1070 non-ti on Client

**Comment by matejkar** [comment]
multi has always been quite broken, but this seems like worse versions of bugs i've already experienced with my friends in mp

**Comment by tsunamayo** [comment]
Thanks for the report, there seems to be several issues, not necessarily all related to mp by the way.
The teleport and the FPS drop on warp could be single players issues too. I keep you posted in any case.
Thanks

**Comment by StarrKiss** [comment]
@tsunamayo  I tested immediately after- teleport issues did NOT occur on single player, and FPS drop only occurs in MP sessions (not in single-player)

**Comment by tsunamayo** [comment]
FPS drop issue is a bit random, I saw the exact same issue back then but it is hard to reproduce all the time. Basically you have to warp again while the game is still spawning NPC ship and stations.
For teleport did you tried long range teleport? Thanks

**Comment by tsunamayo** [comment]
btw the warp issue should have been fixed... but I guess not 100%... =(

**Comment by tsunamayo** [comment]
@StarrKiss also I was thinking on adding a Teleport on Player feature...

**Comment by tsunamayo** [comment]
The warp FPS drop issue is fixed for 20w48c.

**Comment by tsunamayo** [comment]
@StarrKiss I just tried, teleport seems broken for me in Single player, at best I was 500 m close to the building, at worst in the middle of nowhere...

**Comment by StarrKiss** [comment]
> @StarrKiss I just tried, teleport seems broken for me in Single player, at best I was 500 m close to the building, at worst in the middle of nowhere...

Hmm, mightve been chance for me

**Comment by tsunamayo** [comment]
@StarrKiss Teleport issue fixed for 20w48c. Still quite a few to go, now on to the multiplayers bugs...
