### ISSUE TITLE
[BUG] Copied & Pasted Hinge or Rotor's Child Block Are Not Removeable

### ISSUE THREAD

**Issue by MagicalAbyss** [tsunamayo/Starship-EVO#3299]
### Short Description of the issue:

When using Copy-paste Tool on hinges or rotors, it can copy the child block that it came with them, which are not removeable after it is placed down, nor restarting the game or respawning blueprint, but you can remove any blocks you placed down on that child block.

### Steps to reproduce the issue:

Copy & Paste any: 
- Hinge's rotating plate.
- Rotor's rotating round tile.

### Environment
- Starship EVO version: Stable 20w48b
- Graphics Card: GeForce GTX 1080

### Additional information:

![bug](https://user-images.githubusercontent.com/74992463/100279544-c2ec4100-2f34-11eb-9359-6c2ae5cb4a09.PNG)
![bug1](https://user-images.githubusercontent.com/74992463/100281592-35125500-2f38-11eb-905d-836092731dbf.PNG)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5599199/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, thanks for booking the issue. I can reproduce that issue, are you able to reproduce 100% of the time? Thanks

**Comment by MagicalAbyss** [comment]
> Hi, thanks for booking the issue. I can reproduce that issue, are you able to reproduce 100% of the time? Thanks

Yes, is very easy and 100% guarantee to reproduce. 
![bug](https://user-images.githubusercontent.com/74992463/100304419-b4ba1700-2f6c-11eb-9521-71d2e4bab6c9.gif)

**Comment by tsunamayo** [comment]
Ah sorry I misunderstood the issue, thanks a lot for the gif it is very clear now! I keep you posted.

**Comment by tsunamayo** [comment]
Issue fixed for 20w48c. Thanks a lot!
