### ISSUE TITLE
[BUG] FPS halved when firing beams 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3301]
### Short Description of the issue:
when firing beam weapons my fps drops down to 30-37 
...

### Steps to reproduce the issue:
fire a beam weapon (i used the blue starter ship's secondary) 
...

### Environment
- Starship EVO version: 20w48b
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5599509/output_log.txt)
![ezgif com-gif-maker](https://user-images.githubusercontent.com/56371294/100287836-af3fdb00-2f32-11eb-9ced-6764806b09f7.gif)

**Comment by tsunamayo** [comment]
Indeed I can reproduce, I keep you posted.

**Comment by TIKIRobo** [comment]
all right, thank you!

**Comment by tsunamayo** [comment]
I actually fixed an issue where it was detecting a hit with water, but that made the performance hit even worse... So it will need some serious optimization to fix, it will take more time. Thanks

**Comment by tsunamayo** [comment]
Long raycast are just very costly...

**Comment by tsunamayo** [comment]
@TIKIRobo alright I did the optimizations as it was impacting normal flight in some way. It is much better now (FPS when not firing is also higher!) Thanks
