### ISSUE TITLE
[FEEDBACK/BUG] New Player Locomotion causing motion sickness

### ISSUE THREAD

**Issue by nokturnihs** [tsunamayo/Starship-EVO#3303]
Hey @tsunamayo I  know you've been working hard the new player locomotion so I'm really sorry to say that because the keybinds for rotate blocks and rotate player are the same, if you're trying to build out of gravity because we can't manually align anymore it spins us while we're trying to rotate blocks. This leads (at least to me) in motion sickness in under 15minutes of play time. I'm not sure if the keybinds need resetting or whatnot but man, it's pretty hard to build without getting super disoriented. Can we either get a way to manually align to an entity and disable autodetection (that's a little finicky sometimes when switching between multiple grav-gen areas next to each other) or maybe change up the keybinds a little? I will try resetting keybinds and see if that helps....

**Comment by tsunamayo** [comment]
@nokturnihs So by default they should be different, Q/E to roll in 6dof and R to rotate blocks.
Other than that I see a lot of people dont like 6dof for the same reason than me, I wonder how so many people are playing Space Engineer then! I think I will add a simple toggle between anti-g and 6dof then. Thanks

**Comment by nokturnihs** [comment]
Sorry - it's the sudden transition that's causing the sickness. The 6dof isn't it, just can't ever get my bearings because it keeps popping on and off in transitions. I changed my rotate right/left for EVA to Z and C and it's better. at least I'm not spinning when I'm trying to rotate wedges now....

**Comment by tsunamayo** [comment]
So there was a transition bug fixed in 20w48b, it is should be smoother now (not visible basically)

**Comment by nokturnihs** [comment]
OK that's good! Yeah that was the build I'm on. I do like the option for anti-g /6dof toggle options.

Unrelated but Starship EVO is already FAR SUPERIOR to space engineers imo! Thanks for being so awesome!

**Comment by tsunamayo** [comment]
@nokturnihs Thanks mate :)
