### ISSUE TITLE
[BUG] textures not loading

### ISSUE THREAD

**Issue by KINGrimson** [tsunamayo/Starship-EVO#3305]
### Short Description of the issue:
i spawned a ship and part of it the textures weren't loaded and where just black hexagonal's. reloading the world fixed the texture issue 
...

### Steps to reproduce the issue:
load ship into world and see texures missing with black heagonal's
...

### Environment
- Starship EVO version: 20w48c
- Graphics Card: RTX 2060

### Additional information:
![image](https://user-images.githubusercontent.com/74992043/100331897-00061100-2fd1-11eb-8bef-7b48dcf532e2.png)

ship i used
https://steamcommunity.com/sharedfiles/filedetails/?id=2297275555 

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5601770/output_log.txt)
`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by Gliese-832-c** [comment]
Honestly this looks really cool, it should be a type of skin that you can apply to blocks or bricks if you want to.

**Comment by KINGrimson** [comment]
> Honestly this looks really cool, it should be a type of skin that you can apply to blocks or bricks if you want to.

like a carbon paint thing?

**Comment by tsunamayo** [comment]
Fixed for 20w49a. Thanks
