### ISSUE TITLE
[BUG] paint not mirroring 

### ISSUE THREAD

**Issue by KINGrimson** [tsunamayo/Starship-EVO#3306]
### Short Description of the issue:
when using mirror mode paint sometimes does not copy when painting, i had it happen most on tubes
...

### Steps to reproduce the issue:
make a grid set it to mirror. place some tubes and paint to see it not mirroring 
...

### Environment
- Starship EVO version: 20w48c
- Graphics Card: RTX2060

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5602213/output_log.txt)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by tsunamayo** [comment]
If you could send me a blueprint or a screenshot of the configuration that would be great! Thanks

**Comment by KINGrimson** [comment]
i made a gif showing it, was easier to show that way as it was hard to recreate for a screenshot
![ezgif com-gif-maker (7)](https://user-images.githubusercontent.com/74992043/100396745-8dd01380-3046-11eb-86a5-d12196de6aa1.gif)

**Comment by tsunamayo** [comment]
@KINGrimson could you send me the blueprint so I can investigate? Btw the ship look fantastique, is it yours? Cheers

**Comment by KINGrimson** [comment]
@tsunamayo 

> @KINGrimson could you send me the blueprint so I can investigate? Btw the ship look fantastique, is it yours? Cheers

yes its my ship one week of work so far and aint done yet, also blue print is a bit outdated but should still show it, my internet craps out so cant upload the latest version, if i can get it to upload tonight ill send the newer version
https://steamcommunity.com/sharedfiles/filedetails/?id=2297480708

**Comment by tsunamayo** [comment]
@KINGrimson Amazing ship! 
So those brick where not built using symmetry, they were built with non-matching orientation. For symmetry paint / delete to work, brick orientation needs to be symmetrical too (which will be the case if you built them using symmetry).
Thanks
