### ISSUE TITLE
Deleting the "Undeletable"

### ISSUE THREAD

**Issue by MagicalAbyss** [tsunamayo/Starship-EVO#3307]
### Short Description of the issue:

You can delete the "undeletable" brick on mechanisms, though not sure how this bug affects gameplay or game environments, but something to keep in mind and the solution to solve existing undeletable blocks [#3499](https://github.com/tsunamayo/Starship-EVO/issues/3299).

### Steps to reproduce the issue:

- Hold down delete key on a normal block, release right when you reach the undeletable block and press delete as fast as possible. 

Or

- Spam delete key while point and switch between both undeletable block and normal block as fast as possible.

### Environment
- Starship EVO version: Stable 20w48c
- Graphics Card: GeForce GTX 1080

### Additional information:
![bug](https://user-images.githubusercontent.com/74992463/100361437-296e6f00-2fc8-11eb-868e-f0c3ee5dc94e.gif)
![bug1](https://user-images.githubusercontent.com/74992463/100361440-2a070580-2fc8-11eb-9abc-405f2b132885.gif)
![bug2](https://user-images.githubusercontent.com/74992463/100363620-fbd6f500-2fca-11eb-8f69-121cc9ed98e0.gif)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5603582/output_log.txt)

**Comment by tsunamayo** [comment]
Hoho thanks for the trick ;) I will fix this though.

**Comment by tsunamayo** [comment]
I cant make it work...

**Comment by tsunamayo** [comment]
Fixed for 20w48d. Thanks!
