### ISSUE TITLE
Heavy shaking before put any block (20w48c)

### ISSUE THREAD

**Issue by Aristey** [tsunamayo/Starship-EVO#3308]
### Short Description of the issue:
Heavy shaking before putting any block on current update.(20w48c) Didn't had this problem before.
...

### Steps to reproduce the issue:
Need to stay a little far from building surface. Select any block and go closer to building area. 
Select paints/instruments(except copy-paste and mirroring)/empty cell to stop shaking.
If you selected paints/instruments(except copy-paste and mirroring)/empty cell first and go closer you can prevent shaking, but not to everytime
...

### Environment
- Starship EVO version: 20w48c
- Graphics Card: Nvidia geforce 1060 max-q (notebook)

### Additional information:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/75085232/100371931-952cf800-3019-11eb-8f98-d099254fab64.gif)

Blueprint [Tempest.zip](https://github.com/tsunamayo/Starship-EVO/files/5603956/Tempest.zip)
[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/5604050/output_log.zip)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by tsunamayo** [comment]
@Aristey That is terrible, does it happens all the time or over this particular area only? And on every ship? Thanks

**Comment by tsunamayo** [comment]
@Aristey Okay it seems there is some weird stuff with your world, could you please zip me your world folder at 

%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Character

Thanks

**Comment by Aristey** [comment]
> @Aristey That is terrible, does it happens all the time or over this particular area only? And on every ship? Thanks

This happening only with my ship. No any problems with downloaded blueprints. 

I created a New character after last update was released(usually do it after every update), but i have same problem with shaking on both characters 
[Characters.zip](https://github.com/tsunamayo/Starship-EVO/files/5605330/Characters.zip)

**Comment by tsunamayo** [comment]
@Aristey Issue fixed for 20w49a. Thanks!
