### ISSUE TITLE
[Suggestion] Disable popups in Debug Menu

### ISSUE THREAD

**Issue by Titaniclover** [tsunamayo/Starship-EVO#3311]
### Short Description of the issue:
Exactly as it sounds. It would be nice to disable "you are stuck" popups or "activated no clip mode" for both streaming and QoL. We already have a remove HUD option but having the HUD on and not having popups would be neat.

- Starship EVO version: 20w48c

**Comment by tsunamayo** [comment]
The popup message could be important, I will add more in the future, also gameplay will likely use this... So I am not sure it is a great thing long term. Is it that annoying? does they popup too often? Thanks

**Comment by Titaniclover** [comment]
It is a bit annoying, especially when working with gravity generators. They popups are important but it'd be nice to have an option to disable them.

**Comment by tsunamayo** [comment]
@Titaniclover I see - but the gravity (please switch to 6dof of something like that), should be gone right? With the new player locomotion update.

**Comment by Titaniclover** [comment]
The gravity issues are gone, just the popups are still there
