### ISSUE TITLE
[Bug] Stickers Turning Invisible

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3312]
### Short Description of the issue:
Sorry this one is a little messy as it's hard to spot
When building with mirror, sometimes stickers become invisible. Here's a clip of me getting confused when my stickers are disappearing
https://i.imgur.com/i4AuWy3.mp4

Start of the video - theses large orange stickers are visible
![image](https://user-images.githubusercontent.com/27857711/100492312-bdece480-3122-11eb-9314-5dd1508fa95c.png)

00:11-00:30  - I find the first few invisible stickers, you can see their outline but not their colour. I delete some and replace them

00:28 - Orange sticker in the bottom left corner turns invisible when I delete a different invisible sticker. This one -
![image](https://user-images.githubusercontent.com/27857711/100492374-47041b80-3123-11eb-9d3b-15d55b2eb890.png)

At the end of the video, these large orange stickers have turned invisible on both sides of  the ship
![image](https://user-images.githubusercontent.com/27857711/100492304-a281d980-3122-11eb-8184-a5af247e8c2a.png)

### Steps to reproduce the issue:
Download Blueprint
Enable mirroring
Play with stickers on the wings. Stickers start to turn invisible mostly when they are offset and layered
When you first spawn it every sticker will display fine, but they will start disappearing once you start placing/removing stickers

### Environment
- Starship EVO version: 20w48c
- Graphics Card: RX 580

### Additional information:
[TIE-LN Fighter (Sabine).zip](https://github.com/tsunamayo/Starship-EVO/files/5609964/TIE-LN.Fighter.Sabine.zip)
I've experienced it on other ships too, but it mostly occurs on this blueprint

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5609962/output_log.txt)

**Comment by ProPeach** [comment]
After continuing to paint and spawning a new ship to see if the stickers would fix themselves with a fresh spawn, bricks started turning invisible as well as the stickers turning the wrong colour
![image](https://user-images.githubusercontent.com/27857711/100492582-7ddb3100-3125-11eb-89ea-2834c0565f34.png)

[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/5609983/output_log.zip)

[TIE-LN Fighter (Sabine) 2.zip](https://github.com/tsunamayo/Starship-EVO/files/5609981/TIE-LN.Fighter.Sabine.2.zip)

**Comment by ProPeach** [comment]
Here it is "live"
https://i.imgur.com/NaHGSEZ.mp4
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5611074/output_log.txt)

**Comment by tsunamayo** [comment]
@ProPeach is it similar to #3009 ? Thanks

**Comment by tsunamayo** [comment]
@ProPeach I tried to reproduce very hard but I cant make it happens. Do you manage to get a reproductible case? Thanks

**Comment by TIKIRobo** [comment]
#2981 and #2900 might be related as IIRC it sometimes happened on not child entities as well

**Comment by ProPeach** [comment]
@tsunamayo yes it looks like the same issue as #3009 as well as the ones TIKI mention, apologies I didn't realise I had reported it so recently before.

I've talked to a few other players on Discord who've also experienced it, it seems to happen on both parent entities and child entities, with mirror on/off as well as in a new/old world. Both players with Nvidea and AMD cards experience it.

I can reproduce it pretty quickly with the blueprint I've sent you, so I'm going to email you my whole savedata folder in the hope that my world will show it. I've zipped it up and sent it to your address we've used in the past just for privacy sake as there are a lot of WIP blueprints in there.
Load the ProPeach character and the TIE covered in stickers should be right next to you.

**Comment by tsunamayo** [comment]
@ProPeach okay thanks mate I will have a look at it.

**Comment by MagicalAbyss** [comment]
@tsunamayo Got the issues with guarantee results.

**Steps to reproduce the issue:**
1. Load up the blueprint that I provided (fresh load should be in perfect condition).
2. Reload the blueprint with the starter block on the ship.
3. Some blocks and decals will turn invisible.
4. If you unable to find any, repeat step 2.
![Capture](https://user-images.githubusercontent.com/74992463/101542922-7dd30080-3971-11eb-9219-e59dc1ba6bba.PNG)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5662004/output_log.txt)
[Sanguinary - Destroyer.zip](https://github.com/tsunamayo/Starship-EVO/files/5662006/Sanguinary.-.Destroyer.zip)

**Comment by tsunamayo** [comment]
@ProPeach Hi, sorry to necro this, did you saw that again recently? Thanks

**Comment by ProPeach** [comment]
@tsunamayo I haven't, looks like it could well be fixed!

**Comment by tsunamayo** [comment]
Okay glad to hear this!
