### ISSUE TITLE
Character jitters back and forwards when standing still, even in noclip.

### ISSUE THREAD

**Issue by JeffEDDD** [tsunamayo/Starship-EVO#3313]
### Short Description of the issue:

My character model moves side to side rapidly when I am standing still, even in noclip mode.

### Steps to reproduce the issue:

Start tutorial, stand on the spot. It also may be the starting vehicle clipping through the ground, which happens each time I create a new world.

### Environment
- Starship EVO version: 20w48c
- Graphics Card: Intel HD Graphics 620, 12gb RAM system

### Additional information:

https://imgur.com/a/F150YSN 

https://github.com/JeffEDDD/output_log.txt.git

**Comment by tsunamayo** [comment]
Hi, lets fix this issue. A few questions:
This is quite awful, do you get this all the time? Even when you are not pressing any keys?
Could you press the F5 key to check if it stops?
What are your FPS? (you can hit F3 / then Show FPS counter)
Thanks

**Comment by JeffEDDD** [comment]
I found that this issue affects my player model whenever I am on the planet and, when I have been shot into space due to the jittering, whenever I am around a spaceship (any)
I have found that pressing F5 does nothing and most of the time it clips me through the ground and shoots me out into space.
On the planet, I get around 8 FPS (due to the starter ship jumping around) and when I am off of the planet, around 15 FPS.
Thank you!

**Comment by JeffEDDD** [comment]
After testing further, I have some notes on the issue:
- The movement the character model moves around in is usually in the direction last moved (along the X axis if going left or right, along the Y axis if moving up, etc.)
- Moving in the direction that the character model is jittering in seems to reduce the effect and sometimes stops it, but sometimes makes it worse
- Ingame hints state that I am stuck (use noclip mode) after the effect ends even if I am able to move around.
- The effect seems to be worse around larger entities (i.e. big ships, the ring, etc.)
On another note, would it be possible to download an older release and see if the issue persists?

**Comment by tsunamayo** [comment]
You have a very low FPS, I wonder if it could be related. What is the rest of your config (CPU + RAM).
You can try the beta called legacy_clip, it is an older build. You will need to create a new character - tell me if it is better. Thanks

**Comment by JeffEDDD** [comment]
https://github.com/JeffEDDD/System-Specs

After testing an earlier version, 20w41c, I have found that the effect is not there... It may be due to the movement update but I'm not sure...

**Comment by tsunamayo** [comment]
@JeffEDDD Issue fixed for 20w49a. Thanks!
