### ISSUE TITLE
[BUG] In Multiplayer other players turn invisible when inside some ships 

### ISSUE THREAD

**Issue by daOyster** [tsunamayo/Starship-EVO#3314]
### Short Description of the issue:
When inside or even near larger ships, other players turn invisible to each other in multiplayer.

### Steps to reproduce the issue:
In multiplayer, spawn a ship larger than say 30m long, and inside or even near some areas on the ship other players in multiplayer will become invisible to each other.

### Environment
- Starship EVO version: Early-access 20w48c
- Graphics Card: Nvidia RTX 2080 Super

### Additional information:
Output Log: (https://github.com/tsunamayo/Starship-EVO/files/5610048/output_log.txt)

One of a few blueprints it happens in: [OET - Shallow Thorn.zip](https://github.com/tsunamayo/Starship-EVO/files/5610051/OET.-.Shallow.Thorn.zip)

**Comment by Arutus** [comment]
Yeah ive experienced the same issue within my battleship which is around 330m long. It seems to occur all over the ship and doesn't resolve until we leave it.

**Comment by Garrett-C** [comment]
To provide an update on this we discovered that the same thing occurs when you are in an artificial gravity thing.

**Comment by tsunamayo** [comment]
Fixed for 21w02a. Thanks
