### ISSUE TITLE
[Suggestion] Make a "glass" paint

### ISSUE THREAD

**Issue by DamianDrazhar** [tsunamayo/Starship-EVO#3317]
Instead of making a ton of glass and window bricks, we could have a paint that turns bricks and blocks into glass.

**Comment by matejkar** [comment]
if u mean a block that looks like a normal hull block but transparent that exists, in the windows and canopies category

**Comment by tsunamayo** [comment]
Hi, unfortunately it is not possible from a tech standpoint. Thanks
