### ISSUE TITLE
[Bug] Destroyed texture on blueprint spawn

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3318]
### Short Description of the issue:
![image](https://user-images.githubusercontent.com/27857711/100523344-c5a29c80-31a7-11eb-88f1-1380b20e6a24.png)
The first blueprint I spawn usually shows the destroyed texture on at least some of the voxels. Spawning the blueprint again removes the texture on the first spawned blueprint

### Steps to reproduce the issue:
Spawn a blueprint after starting a fresh game
I used the blueprint from
#3312 
### Environment
- Starship EVO version: 20w48c
- Graphics Card: rx580

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5611051/output_log.txt)

**Comment by tsunamayo** [comment]
@ProPeach Okay I finally was able to track it down and fix it for 20w49a. Thanks!

**Comment by ProPeach** [comment]
Fantastic! :)
