### ISSUE TITLE
[BUG] world empty on reloading

### ISSUE THREAD

**Issue by KINGrimson** [tsunamayo/Starship-EVO#3321]
### Short Description of the issue:
when loading a game is sometimes get greeted with a empty world although their should be ships in their. it happend a few times already, on restarting the game everything in that world is back
...

### Steps to reproduce the issue:
make a world, place some ships, exit the world, reloaded, see all missing, try untill get result 
...

### Environment
- Starship EVO version: 20w48d
- Graphics Card: RTX2060

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5612020/output_log.txt)
`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by tsunamayo** [comment]
@KINGrimson Hi, if it happens again I would like to investigate the output.log. Thanks!

**Comment by KINGrimson** [comment]
> @KINGrimson Hi, if it happens again I would like to investigate the output.log. Thanks!

I shall get you the output log as soon as I can, had it happen 5 times today, exit a world to fix a bug get back in to see everything gone, forcefully close the game cause wouldn't want to close and restart and reloaded to get everything back

**Comment by tsunamayo** [comment]
@KINGrimson Hi, if doesnt want to close could you send me the log for that too?
 - take log after your forcefull exit
 - if issue on restart take log 
Thanks a lot! ;)

**Comment by KINGrimson** [comment]
> @KINGrimson Hi, if doesnt want to close could you send me the log for that too?
> 
> * take log after your forcefull exit
> * if issue on restart take log
>   Thanks a lot! ;)

just had it happen again took the log after i closed the game

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5614618/output_log.txt)

**Comment by KINGrimson** [comment]
had it happen again since the last update i have it happen atleast 5 times a day

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5614801/output_log.txt)

**Comment by KINGrimson** [comment]
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5616260/output_log.txt)

**Comment by tsunamayo** [comment]
Thanks, there is indeed tons of errors in the log.
Could you send me your character save also? Do you remember exactly what you did? ie did you quit to the title and then reload the game or something? Thanks

**Comment by tsunamayo** [comment]
@KINGrimson I think the case was simply the quit to title is broken. I just fixed it, you will tell me if you reproduce in next update 20w49a. Thanks!

**Comment by KINGrimson** [comment]
> @KINGrimson I think the case was simply the quit to title is broken. I just fixed it, you will tell me if you reproduce in next update 20w49a. Thanks!

so far it hasn't happened again
