### ISSUE TITLE
[BUG] Gravity doesn't work anymore :(

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3322]
### Short Description of the issue:
ships are no longer affected by gravity 
...

### Steps to reproduce the issue:
spawn in a ship in the gravity field of the habitat and watch it hover 
...

### Environment
- Starship EVO version: 20w48d
- Graphics Card: 

### Additional information:

![image](https://user-images.githubusercontent.com/56371294/100547175-806f8080-3222-11eb-9fd7-2c3f44d7b6fc.png)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5612441/output_log.txt)

(also after relogging I realized that the gravity field is now just very small for ships, about 5-10 meters from "sea level")

**Comment by tsunamayo** [comment]
Yes I got tricked in my test, gravity was there but very low depending on the patch topology. Fixed for 20w49a. Thanks!
