### ISSUE TITLE
[BUG] unable to paste normally 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3324]
### Short Description of the issue:
I am only able to paste something I have copied on child entities 
...

### Steps to reproduce the issue:
try to copy and paste something 
...

### Environment
- Starship EVO version: 20w48d

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5612896/output_log.txt)

**Comment by tsunamayo** [comment]
@TIKIRobo hi, copy and paste works fine for me, or I dont get your test case? What is the relation to children entity? Thanks

**Comment by TIKIRobo** [comment]
the thing that im copying is on the main entity but for whatever reason the hologram/outliner of what i want to past only appears on child entities (specifically the big main doors on the ship im working on) and also doesn't do any thing when i click

**Comment by TIKIRobo** [comment]
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/56371294/100561371-023cc980-3276-11eb-8425-1552822d2ff6.gif)
a gif of it in action, and another buggy thing 

[MRM-224-01.zip](https://github.com/tsunamayo/Starship-EVO/files/5613434/MRM-224-01.zip)
the ship

**Comment by TIKIRobo** [comment]
for whatever reason copy and paste works on other parts of my ship but not the hanger bay

**Comment by TIKIRobo** [comment]
@tsunamayo i figured it out! if your character is within the bounding box of whatever you are copying the thing you are copying will not appear or be paste-able. So just when copying something draw a really big box around it, then when pasting it move back until the holo appears and you are able to paste

**Comment by tsunamayo** [comment]
@TIKIRobo Okay that one is finally fixed for 21w02c! Thanks
