### ISSUE TITLE
issue with movement

### ISSUE THREAD

**Issue by Vengefuldragon98** [tsunamayo/Starship-EVO#3325]
### Short Description of the issue:
Just loaded into the game and while trying to move around my character will start to almost vibrate and move around like crazy.
...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by tsunamayo** [comment]
@Vengefuldragon98 Hi, thanks for booking the issue. What is your config (CPU + GPU + RAM) and what kind of FPS are you doing? Thanks

**Comment by tsunamayo** [comment]
@Vengefuldragon98 okay I managed to reproduce on my Intel 630. It seems somehow linked to very low FPS.
Do you confirm you have an Integrated card and low FPS? Thanks

**Comment by Vengefuldragon98** [comment]
I'm pretty sure I have a quad core CPU, not sure of the graphics card, I
know it's old but I am running 16gb of ram, the game was running around
10-15 fps, guess it's time to upgrade my graphics card lol.

**Comment by tsunamayo** [comment]
@Vengefuldragon98 Do you run it on a laptop (if yes what model)? I want to make sure that you dont have an integrated card and a dedicated one, and for some reason the game runs on the wrong one (the integrated). Thanks

**Comment by Vengefuldragon98** [comment]
It's a desktop, I'm not at my computer right now,  but I think the graphics
card is a nvidia gt 650 which is a 2gb graphics card, currently the weakest
link on my computer.

**Comment by tsunamayo** [comment]
@Vengefuldragon98 Issue fixed for 20w49a. Thanks
