### ISSUE TITLE
[Question] Copy and Paste Tool limitations

### ISSUE THREAD

**Issue by chacalik** [tsunamayo/Starship-EVO#3326]
### Short Description of the issue:

Is there a way to better deal the Copy and Paste tool area limitation? As it seems unlimited, when copying large areas (1600mX200mX900m, for instance), once the left mouse button is released, the game freezes, as the amount of blocks being copied its too much for the system to handle. Though, the use of RAM never went over 4GB. I did try to wait for it to return, but after several minutes, the game kept frozen.

My PC Specs:
![image](https://user-images.githubusercontent.com/4794243/100650471-bbf17400-3322-11eb-9cae-4e06532f75c6.png)

**Comment by tsunamayo** [comment]
Yeah so of course I am gonna have to limit the area size for copy. As you might imagine the area you copied is simply 1000x too big... Thanks
