### ISSUE TITLE
[BUG] Building Up High Crashes to Desktop

### ISSUE THREAD

**Issue by chacalik** [tsunamayo/Starship-EVO#3329]
### Short Description of the issue:
I have a build that has 1622m long, 898m wide and 210m tall, trying to increase its height up to 396m, but even building with the 1m block, it crashes to desktop after 306m, as seen on the gif below.

### Steps to reproduce the issue:
Have a big build, try to expand it in one vector only.

### Environment
- Starship EVO version: 20w48d
- Graphics Card: Radeon RX 590

### Additional information:
![ezgif-4-daf715dc935b](https://user-images.githubusercontent.com/4794243/100688509-4c4ea980-3361-11eb-9b55-32ce25650500.gif)

**Comment by tsunamayo** [comment]
Hi, I need a log to investigate further. The game was never made to be working with build that big... thx

**Comment by chacalik** [comment]
Hey there Tsuna. It doesn't output nothing on the log... It simply quit to desktop. I wonder if there's a limit on volume, as for vectorial limits I have discarded, after building a 160.000m up high and in another build, 16.000 X 16.000 ... Though, building any higher on Z, for instance, it would cause that crash.

If thats a size limitation, I would like to suggest a 2.000 x 2.000 x 2.000 limit, as I've never seen any build higher than that.

**Comment by chacalik** [comment]
Important edit:
I found the log... it seems I was on my older profile app folder... sorry...
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5626050/output_log.txt)

**Comment by tsunamayo** [comment]
So I did some safe guard already on the light texture size, but it seems to be running out of memory in another place.
I will add more debug info to see from where it is coming from. I cant just put a limit as it depends on your computer.
and 2km x 2km x 2km is way too big sorry =(. thx

**Comment by chacalik** [comment]
Oh don't mind, that was just a suggestion of size based on real big ships... everything else is working fine with that blueprint I have... if it does help to investigate, there it goes the blueprint

[Imperial I-Class Star Destroyer (Rebels) WIP 2.zip](https://github.com/tsunamayo/Starship-EVO/files/5626264/Imperial.I-Class.Star.Destroyer.Rebels.WIP.2.zip)

**Comment by tsunamayo** [comment]
With neovox you can now build crazy big!
