### ISSUE TITLE
[Suggestion] Text on buttons and logic

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#3330]
A long time ago we used to be able to put text on buttons and logic. Would it be possible to get it back? Was very nice to be able to label buttons and logic
![image](https://user-images.githubusercontent.com/36980446/100692731-af801200-3348-11eb-82c3-a5788ad7c547.png)

**Comment by tsunamayo** [comment]
Text like that or a simple HUD message is enough? Thanks

**Comment by tsunamayo** [comment]
If I recall the issue (beside optimization stuff) is that you could place button from any orientation, the player could be oriented in any direction too. You could place it on children entity and so on. And I dont have a screen to configure those button, as F activate the button... So I dont know maybe a mini holo text block?

**Comment by ZachZent** [comment]
I say text. HUD message popping up every time you look at a button or logic would get annoying extremely fast. Especially if you have a lot of labeled buttons near each other. Imagine moving your mouse and like 20 messages pop up.

**Comment by ZachZent** [comment]
A mini holo text block would be awesome, but the button text is more of an informational thing. For example if a player downloads a ship, they will know the big red button is for. Or logic tutorials stating what each logic block does in the system. A holo text would not really solve this very minor issue although that would be something I'd love to see.

**Comment by tsunamayo** [comment]
No I didnt meant a  warning like popup, just something like "Press [F] to activate", except it would be "Press [F] to activate Landing Gear" or "Press [F] to activate Death Star Planet Killer Beam"

**Comment by ZachZent** [comment]
Yea that can work

**Comment by BrickMacklin** [comment]
To save space you could probably cut out the "Press [F] to" part

**Comment by tsunamayo** [comment]
@BrickMacklin that is for noob...

**Comment by Kaiser-Indrasil** [comment]
I think the "Press [F] to interact with stuff" has already been a part of the tutorial, which the noobs are probably gonna get their hands on.

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil I dont think there is a place in the tutorial that teach that...

**Comment by Garrett-C** [comment]
Plus it's best to assume that the player hasn't ever played a game before.

**Comment by nokturnihs** [comment]
@tsunamayo - Just make a label tool.... KISS
Add "holo labels/stencils" to an area - paint like a decal, then on mouse-button release you are presented with an edit screen. Inside the screen have options like Angle/text size/color/visibility time/range/etc.

Maybe something like:

Visibility: Always/Within X meters/When off/on (if applicable)
Visibility timer: Always/3s/6s/etc.
Projection: Yes/No
(Projection set to NO would just be flat text like a display screen)
Projected angle: 0-180 (when Projection set to yes)
Text color: (Color picker or RGB entry)
Enter text: [BLAH]
ADD/EDIT REMOVE CANCEL

The settings can only be accessed via label maker tool and to remove simply shoot whatever block you "painted" with the label maker and you can edit, remove or whatever....

Also makes label decals easy and (given either ANSI, emoji, etc support) custom displays and other detail stuff easier as well. Dunno how you'd handle storing the meta data or whatever, maybe as a non-colliding block attached to wherever you blasted or whatever? Failing that you could also do the same thing with decals as-is and the label tool could be used to add more data to the decal shapes you already have... 

just a suggestion but either way - I'd love labels and more text-presenting objects/devices...

**Comment by tsunamayo** [comment]
We now have the Tag tool. thx
