### ISSUE TITLE
[BUG?] messed up game files and disk write error

### ISSUE THREAD

**Issue by matejkar** [tsunamayo/Starship-EVO#3332]
### Short Description of the issue:
This also happened to my friend some time ago, and he just got it working out of nowhere, like steam fixed itself.
But the case here is when steams goes to update starship evo (im on experimental version) it updates normally, but when i went and launched the game, the game crashed and i got an error saying "disk write error". And states that the .exe file of the game cannot be found. I check the steam game folder where SEVO files are found, and the .exe file is not there as was said. But the .exe file is not in the trash bin, and cannot be found anywhere. I tried verifying integrity of game files, and that shows that 1 file failed to verify and will be redownloaded (of course, thats the .exe), but when i let it download once again disk write error. I also tried restarting steam, but that does not fix it. I also cleared download cache, but that as well does not fix it. I will try a reinstallation of the game, and i will update after that.
...

### Steps to reproduce the issue:
After an update of the game, try and run the game, the game crashes and in steam downloads it says disk write error.
Keep in mind this happened to me only now, and i had no issues updating and playing the game before.
So it might be inconsistent, but the issue is there, and my friend who got the game after i reccomended the game to him got the error way earlier then me, some 2 months ago (so not even a month after getting the game). For him, the game was fixed out of nowhere, he tried all the things i mentioned above and more but it didnt work, and after some time the error was just gone, he updated the game and could play it again.

...

### Environment
- Starship EVO version: error occured on updating and launching 20w49a
- Graphics Card: Nvidia Geforce GTX 1060ti 6gb

### Additional information:
When launching the game, the main menu doesn't even appear, the game crashes at the grey screen
_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
there is no output log

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by matejkar** [comment]
Update:  a person in the SEVO official discord stated that the same happened to them, and a reinstall fixed it

**Comment by matejkar** [comment]
Update: a reinstall did fix the disk write error, but after redownloading the game again, in version 20w49a, the game's menu once again did not open, the game crashed and again, disk write error

**Comment by matejkar** [comment]
so for me 20w49a is broken, the game won't start. I will try few more times

**Comment by matejkar** [comment]
now i cannot even redownload the game again

**Comment by matejkar** [comment]
Update: restarting the pc doesn't fix it, so far it was fixed once in a reinstall, but after that reinstallations were not an option anymore, the game would reach its download limit and just stop downloading saying the .exe cannot be found

**Comment by matejkar** [comment]
and since this happened to me, my friend and another person in the discord server i really think this is an issue that could happen to people eventually.

**Comment by tsunamayo** [comment]
@matejkar It seems to be an issue with Steam, not really on my side... If there is a corruption with the steam installer there is simply nothing I can do, it is all on the steam side. In that way the only thing to do a uninstall and re-install.
Thanks for letting me know though!
