### ISSUE TITLE
Character Movement Issues

### ISSUE THREAD

**Issue by Stoneddinosaur9** [tsunamayo/Starship-EVO#3334]
### Short Description of the issue:
Whenever I load into the game my character starts shaking and eventually gets flung out into space, I also seem to be able to go through walls/floors while this is happening even when out of no-clip mode.

I've tried starting new saves and the same bug keeps happening.
...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 20w48c
- Graphics Card: Intel(R) HD Graphics 4600

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by tsunamayo** [comment]
@Stoneddinosaur9 Hi, so this issue is fixed in 20w49a in the experimental beta branch. If you want to play right now you can select on steam, otherwise I a day or two this build will be available in the default branch. Thanks!
