### ISSUE TITLE
Can you add a search feature to the ship blueprint browser

### ISSUE THREAD

**Issue by amplified1** [tsunamayo/Starship-EVO#3336]
don't really get why this isn't already in the game. having to manually scroll through your entire ship library will only become worse and worse as there are more workshop ships so it would be great to have as a feature even in a very basic form ASAP.

**Comment by ZachZent** [comment]
Some other QOL features would be nice too. Maybe different sorting options like alphabetical, most recently edited, etc. And of course a search bar

**Comment by tsunamayo** [comment]
> don't really get why this isn't already in the game. @amplified1 cause I have plenty of things to dooo but yeah this with folder is gonna be great.
