### ISSUE TITLE
[bug] saving to local turned ship invisible 

### ISSUE THREAD

**Issue by KINGrimson** [tsunamayo/Starship-EVO#3337]
### Short Description of the issue:
went to save a ship, pressed on export to local and it saved and turned my ship invisible 
...

### Steps to reproduce the issue:
make a ship, save it buy exporting to local and see it turn invisible 
...

### Environment
- Starship EVO version: 20w49a
- Graphics Card: RTX2060

### Additional information:
picture taken right after saveing
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5638784/output_log.txt)

![image](https://user-images.githubusercontent.com/74992043/101085009-1dc60e00-35af-11eb-8bce-a91935fec631.png)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by tsunamayo** [comment]
@KINGrimson Could you send me the ship? thanks

**Comment by KINGrimson** [comment]
[Kessel BH-50.zip](https://github.com/tsunamayo/Starship-EVO/files/5639582/Kessel.BH-50.zip)
here is the ship,

**Comment by tsunamayo** [comment]
@KINGrimson I cant reproduce this. Do you reproduce this all the time? 
Also it seems you have some ship inside the sun. Could you start a new game and migrate your ships over there? Thanks

**Comment by KINGrimson** [comment]
> @KINGrimson I cant reproduce this. Do you reproduce this all the time?
> Also it seems you have some ship inside the sun. Could you start a new game and migrate your ships over there? Thanks

sadly i have been unable to reproduce this issue, seemed like a one time thing, a reload of the game fixed it, but if it ever happens again and i figure out how to do it reliably ill let you know

**Comment by KINGrimson** [comment]
![image](https://user-images.githubusercontent.com/74992043/101980107-5dea5800-3c63-11eb-957b-0eb3e331a42a.png)
had it happen again but on a smaller scale now, 
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5682790/output_log.txt)

**Comment by tsunamayo** [comment]
@KINGrimson I think it was another issue. Did you reproduce that one again? How did it happened? Thanks

**Comment by KINGrimson** [comment]
> @KINGrimson I think it was another issue. Did you reproduce that one again? How did it happened? Thanks

i dont know how it happend, it happens on random on any ship, all i did was save the ship i was currently working on and boom half the ships in their turn partly invisible
