### ISSUE TITLE
I cant load my world

### ISSUE THREAD

**Issue by quelonio** [tsunamayo/Starship-EVO#3343]
### Short Description of the issue:

...i cant load my world

### Steps to reproduce the issue:

...there aren't any i know of, but i've noticed that the file has 2 instances for god nows why

### Environment
- Starship EVO version: 
- Graphics Card: 
idk
### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: C:\Users\sheit\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Characters\wawa

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
C:\Users\sheit\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Characters\wawa
[wawa.zip](https://github.com/tsunamayo/Starship-EVO/files/5647793/wawa.zip)

**Comment by quelonio** [comment]
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5647796/output_log.txt)

**Comment by matejkar** [comment]
its very useful if u say the game version.

**Comment by tsunamayo** [comment]
@quelonio Hi, thanks for booking the issue - I keep you posted. Your gfx cars is a 1050 with 4gb or VRAM.
@matejkar yes it is better but it is writter in the log, so if there is a log then it is okay.

**Comment by tsunamayo** [comment]
@quelonio So I forgot to update you - but I was able to load the game with no issue. Is this something you get all the time? If you quit to windows, does it still not work? Thanks

**Comment by quelonio** [comment]
@tsunamayo yes, i can't load the character no matter what, i've tried reseting my pc and unisntalling and re-installing the game multiple times and it still dosen't work.

**Comment by quelonio** [comment]
I think i found out something, the bug only happens after warping to a system thats very far away from the starting system, so it might have something to do with that
