### ISSUE TITLE
unfixable lag 

### ISSUE THREAD

**Issue by KINGrimson** [tsunamayo/Starship-EVO#3345]
### Short Description of the issue:
i was playing normally when out of nowhere a hugh lag spike came dropping me to 2 FPS and it didnt go away, i tried reinstalling the game, restarting my pc, reloading the world, verifying integrity, tried 3 different world 1 was even empty, even switched to stable branche still the lag wouldn't go away keeping my fps at 2 

### Steps to reproduce the issue:
their is no information on how to reproduce it 
...

### Environment
- Starship EVO version: 20w49a
- Graphics Card: RTX2060

### Additional information:

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5649508/output_log.txt)

here are also the worlds i used to test for lag
[data runner.zip](https://github.com/tsunamayo/Starship-EVO/files/5649511/data.runner.zip)
[kessel BH-50.zip](https://github.com/tsunamayo/Starship-EVO/files/5649513/kessel.BH-50.zip)
[otchian 3.zip](https://github.com/tsunamayo/Starship-EVO/files/5649517/otchian.3.zip)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by KINGrimson** [comment]
i forgot to mention this, but when the lag hit i was linking logic for a airlock, i then reloaded the world in  a attempted to fix it and the lag got worse,

**Comment by tsunamayo** [comment]
@KINGrimson What is your CPU - RAM? I have had this reported a few time, I really would like to fix this. Thanks

**Comment by tsunamayo** [comment]
@KINGrimson nevermind I was just able to reproduce, will fix asap ;). Cheers

**Comment by KINGrimson** [comment]
> @KINGrimson nevermind I was just able to reproduce, will fix asap ;). Cheers

i had just found it, and thanks i took me a while to fix i had to delte the entire game and the moonfire entertainment folder of my computer and reinstal it before it got fixed

**Comment by tsunamayo** [comment]
@KINGrimson you should not have to do that. When you tried with the other save, did you quit to title or quit to desktop before the reload?

**Comment by tsunamayo** [comment]
@KINGrimson so it happens you have 500 000 drops in this world. Do you remember what happened when you had the airlock issue? Could you tell me what link I should do to reproduce? Thanks

**Comment by KINGrimson** [comment]
ill give a picture of the logic set up to each and gate you need a switch and the and gate goes to the out put can be a hing , piston or rotor, what this logic does i switch the airlock state but allows for the doors to be opend and closed depending on the state, after the reinstal i i tried it again and it worked fine

![unknown-24](https://user-images.githubusercontent.com/74992043/101299229-bbc90b00-3831-11eb-8776-d8c070952344.png)

**Comment by KINGrimson** [comment]
> @KINGrimson you should not have to do that. When you tried with the other save, did you quit to title or quit to desktop before the reload?

I did both, to desktop and tital

**Comment by tsunamayo** [comment]
@KINGrimson thanks, to confirm you retry to do the link or to use the logic system? What I am after is to understand what link assignment with the tool produce the issue so I can fix it.

**Comment by KINGrimson** [comment]
> @KINGrimson thanks, to confirm you retry to do the link or to use the logic system? What I am after is to understand what link assignment with the tool produce the issue so I can fix it.

i did first the system, worked fine then took of all switches to the and gates reattached them and it worked fine, the first time after i added the switches to the and gates it caused the bug

**Comment by tsunamayo** [comment]
@KINGrimson okay fixed for 20w50a. Thanks!
