### ISSUE TITLE
[BUG] turret shoots its own ship

### ISSUE THREAD

**Issue by matejkar** [tsunamayo/Starship-EVO#3346]
### Short Description of the issue:
I know turrets are supposed to not shoot if the ship they are on is in the way, but that keeps happening troughout 20w49a.
Im now building a new ship and its very well seen how 2 or my turrets shoot directly at the ship.
...

### Steps to reproduce the issue:
Have a turret on a ship which has the targeted ship in the line of fire, but not line of sight, it should shoot the player's own ship
...

### Environment
- Starship EVO version: 20w49a
- Graphics Card: 1060ti

### Additional information:
![20201207001940_1](https://user-images.githubusercontent.com/69653738/101296222-80731000-3822-11eb-9d09-94308507cffd.jpg)
![20201207001943_1](https://user-images.githubusercontent.com/69653738/101296230-9aacee00-3822-11eb-9075-0467470117e6.jpg)
![Resolution - class frigate (wip)](https://user-images.githubusercontent.com/69653738/101296276-c6c86f00-3822-11eb-8e7f-a9a89cfc063f.png)
![Resolution - class frigate (wip)_bloom](https://user-images.githubusercontent.com/69653738/101296277-c7610580-3822-11eb-8108-b43e2e76d349.png)
![Resolution - class frigate (wip)_preview](https://user-images.githubusercontent.com/69653738/101296278-c7f99c00-3822-11eb-8dfd-1e2fd4da9b4d.png)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`     i cannot send the output log, the compressed files are still too big (25k kb) and the main output log 380k kb.

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by matejkar** [comment]
[Resolution - class frigate (wip).zip](https://github.com/tsunamayo/Starship-EVO/files/5649769/Resolution.-.class.frigate.wip.zip)
here's the blueprint

**Comment by tsunamayo** [comment]
Issue fixed for 21w04b. Thanks
