### ISSUE TITLE
[Bug] Inconsistency and Miss Labeling of Query Gate

### ISSUE THREAD

**Issue by MagicalAbyss** [tsunamayo/Starship-EVO#3350]
### Short Description of the issue:
The labels from query gate are different than the sequence gate on large or small hinges and small sliders, and it is very inconsistent or confusing.

The prime example for miss labeling of the query gate is when connecting from a hinge, 
![image](https://user-images.githubusercontent.com/74992463/101545182-df489e80-3974-11eb-9ac1-00b20bdc6524.png)
It clearly labelled as [-90,90] range. 

However, as you see from the image I set the query gate as superior (179.9), that mean I have the rotator set as 90 degree angle as it's current angle (OFF with switch), and I want the query gate activate when rotator reach - 90 (ON with switch), but if I set the query gate with inferior (-89.9), the query gate will not activate, instead it activate if I set it as superior (179.9), If you set query gate as superior (-89.9), it will stays ON forever.

Another example for this problem is when you connect a 0.75 m small slider, 
![image](https://user-images.githubusercontent.com/74992463/101545871-e6bc7780-3975-11eb-89bc-08d7f11235ec.png)
It labelled as 0 to 1 m limit, same case if I were connect it from a 1.25m slider.

Not only does it not show as a float number, it get even more confusing if player does not know how slider trigger works when a query gate set as superior (0.5), it does not activate when the slider reached the end, if query gate set at superior (0.499), it activates, and this is a 0.75m small slider, and the activate range is [0, 0.75 - 0.25 = 0.5] because it is brick size of 0.25 differences. Though it gets more clearly with large slider as it is integer number.

### Steps to reproduce the issue:

Large or Small Hinge
- Place down a hinge connect a switch to it.
- Connect the hinge to 2 query gates, set one of them as superior (179.9), another one as inferior (-89.9)
- Connect each query gate to any logic signal indication.

Small Slider
- Place down a 0.75 m small slider.
- Connect the slider to 2 query gates, one set as superior (0.5), another one set as superior (0.499).
- Connect each query gate to any logic signal indication.

### Environment

- Starship EVO version: Stable 20w49a

**Comment by tsunamayo** [comment]
@MagicalAbyss Hi, this issue is fixed with the new query gate.
