### ISSUE TITLE
[Bug] Persistent Logic Signals

### ISSUE THREAD

**Issue by MagicalAbyss** [tsunamayo/Starship-EVO#3352]
### Short Description of the issue:

When working on closed loop logic, sometime when I remove a logic from the loop to open the loop, for unknown reasons, the signal pulses from the loop still manage to send signals to other logic components when connections are removed. The issue can be solve by respawning the blueprint, but it will confuse many players who don't have a good understanding of the logics.

### Steps to reproduce the issue:

Here is a simple example of a "controlled" 0.1 sec loop logic, this issue can be reproduce from any circuits that are in a closed loop.
![image](https://user-images.githubusercontent.com/74992463/101551631-4f5c2200-397f-11eb-804e-cf3dbe8d213a.png)

- Build the circuit from above, leave timer to 0.1 sec.
- Turn the switch on, and remove the AND gate afterward.
- Connect the switch to something else and switch it off. (The piston will stop).
- Turn on the switch again, the piston will be activate again (signal still receive from the loop), and any other logic components that are currently connected with the switch will be turn ON.

### Environment
- Starship EVO version: Stable 20w49a

### Additional information:

![logic](https://user-images.githubusercontent.com/74992463/101552171-5e8f9f80-3980-11eb-9358-a135dc05d335.gif)

[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/5662487/output_log.zip)

**Comment by tsunamayo** [comment]
@MagicalAbyss Hi, this issue should be fixed in recent updates.
