### ISSUE TITLE
[Bug] Player gets teleported into abyss upon every Warp Jump

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3355]
Version: 20w50a

This one's easy to replicate.
Just warp to any system, and get away of the yoke.
You will be greeted by an abyss with no star, planets, and especially your ship.
Teleporting back to the ship bypasses the issue.

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Hi, I cant replicate ;). What are you doing exactly?
I warp to another star. Then when the ship just arrived and is static I exit the yoke. Everything seems normal. Thanks

**Comment by Kaiser-Indrasil** [comment]
Well, I do just that, nothing more. It happens everytime.
Maybe I will just hand over the logs ;)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5669784/output_log.txt)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Okay indeed I cant spot something in the log. Could you give me your character save before the warp, with the warp assigned? It seems it could be dependent on the rng. Thanks

**Comment by Kaiser-Indrasil** [comment]
Sure, here it is: 
[Exp 50A.zip](https://github.com/tsunamayo/Starship-EVO/files/5684643/Exp.50A.zip)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil So I loaded your save, it seems you are very far away from the center. I was seeing stars, but not the main star, is this what you were referring to? Also when you exited the yoke, did you jumped out of the ship? 
I had some massive lag due the to collision system, it seems to not like when being super far away, I will investigate this.
Thanks

**Comment by Kaiser-Indrasil** [comment]
Yeah, this is exactly what happens, apart from the lag spike.

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Sorry I am super slow on that issue. So you exited the yoke, but not the ship, correct? So the real issue is more the fact that you found yourself unliked to the entity while it was still moving very fast. In fact I can reproduce when I spawn to an NPC ship, I will be dropped pretty quickly. I keep you posted.

**Comment by Kaiser-Indrasil** [comment]
No no, this is not what is happening at all. First, I wait for the ship to stop completely. Then, I simply exit the yoke. That alone suffices to teleport me away, way outside the solar system to the point where the star is barely visible.

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil urgh, okay I see. Do you still get this in latest version? There was a serious issue with walking inside ship with the lock not working on grav volume transition, but that one is fixed.

**Comment by Kaiser-Indrasil** [comment]
Yup. Sadly, it prevails.

**Comment by Kaiser-Indrasil** [comment]
Seems like #3367 might hint at the culprit.
The trigger seems to be the lack of seat during the warp.
If the pilot is seated, everything is in order.
But, if we warp without being seated, then after the warp was completed and the ship completely stopped, once we exit the yoke, we get teleported away.
Looks like it happens when the game swaps the star systems, mid-warp.

**Comment by tsunamayo** [comment]
Okay mate you got me increased confused ;)
What do you mean you get teleported earlier, mid warp?
You told me you were waiting for the ship to stop to exit the control.
Mid warp the ship is still moving very fast !

**Comment by Kaiser-Indrasil** [comment]
See, this time I decided to not switch to 3rd person camera and actually keep looking from the character's perspective.

Up until this point I'd thought that the player gets teleported away, but I think, it may just remain at the system's border, while the ship keeps closing in on the star.

You can see the exact moment of the bug occuring in the 1st person, whereas in 3rd person everything seems fine until you exit the yoke after the ship's stopped.

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil I dont know if you can record something, I think at this point that would help to understand the test case... Cheers

**Comment by Kaiser-Indrasil** [comment]
Sure, absolutely, just, I'll get around to it tomorrow, as I'm about to hit the sheets ;)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil sure have a good night ;)

**Comment by Kaiser-Indrasil** [comment]
Right, I hope this video explains the issue than words did

https://youtu.be/oaMR-r_mrY4

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Okay thanks indeed that is quite a complex thing happening. I will try to reproduce again...  When the screen turn black, you did nothing input wise, it was during the system switch I guess?

**Comment by Kaiser-Indrasil** [comment]
Yeah, just sat and watched.
Only switched to a third person camera a few seconds after the system switch.

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Okay mate I was finally able to reproduce ;) I keep you posted, thanks for the vid!

**Comment by Kaiser-Indrasil** [comment]
I should probably include videos more often then. Cuts down the work for both of us ;)

**Comment by tsunamayo** [comment]
Okay the issue is finally fixed  for 21w03a! Thanks ;)
