### ISSUE TITLE
[Bug] Pink patch covering the Gas Giant

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3356]
Version: 20w50a

Some of the gas giants are now part of the Breast Cancer Awareness Campaign

![Starship_EVO_uVgryr0B06](https://user-images.githubusercontent.com/63756057/101562707-cd401d80-39bf-11eb-8473-3a449a294d1a.png)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil I think that is just the normal look ;)
