### ISSUE TITLE
game freezing when connecting yoke to ship computer

### ISSUE THREAD

**Issue by KINGrimson** [tsunamayo/Starship-EVO#3358]
### Short Description of the issue:
title says it all, when you connect a yoke to a ship computer it freezes the game
...

### Steps to reproduce the issue:
connect yoke to a ship computer
...

### Environment
- Starship EVO version: 20w50a
- Graphics Card: rtx2060

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/5668113/output_log.zip)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by tsunamayo** [comment]
@KINGrimson Hi, thanks for being so active lately. I cant reproduce this unfortunately, can you do it all the time on all blueprint? Could you send me your blueprint? Thanks

**Comment by KINGrimson** [comment]
> @KINGrimson Hi, thanks for being so active lately. I cant reproduce this unfortunately, can you do it all the time on all blueprint? Could you send me your blueprint? Thanks

thanks i find this game really fun and has Hugh potential, so i like to see bug small or big fixed, really good job all around, also on the bug i sadly havent been able to reproduce it my self, but ill send over the blueprint i had it happen on 
[Terabyte.zip](https://github.com/tsunamayo/Starship-EVO/files/5671231/Terabyte.zip)
