### ISSUE TITLE
[Bug] Copy paste placement guide disappears

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3359]
### Short Description of the issue:
When pasting large parts, the placement guide disappears when you get close. Could have been introduced with the recent changes to the c/p tools reach.
https://i.imgur.com/4m00yIb.mp4

### Steps to reproduce the issue:
Copy a large part
Try and paste it

### Environment
- Starship EVO version: 20w50a
- Graphics Card: RX580

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5668115/output_log.txt)

**Comment by ProPeach** [comment]
It seems like the distance that the placement guide disappears is not actually dependant on the size of the selected component, I've had it disappear with small and large selections

**Comment by tsunamayo** [comment]
Okay that one is finally fixed for 21w02c! Thanks
