### ISSUE TITLE
[BUG] Brick overlap on copy-paste + symmetry

### ISSUE THREAD

**Issue by YellowMiner** [tsunamayo/Starship-EVO#3361]
### Short Description of the issue:

Using combined copy-paste and mirror, it is possible to place bricks overlapping in unnatural ways. Identical bricks may overlap in the same position preventing detection without witnessing z-fighting when painting one of them.

### Steps to reproduce the issue:

1 - Use copy paste to make a selection of bricks/blocks. Larger selections made of more parts & smaller bricks seem to trigger the bug much more easily

2 - Place near symmetry plane so it overlaps with it's mirrored self.

3 - Check for overlap

Exact set of bricks of the mirrored set that do and don't place vary depending on copied object and overlap, and there is no guaranteed presence of an overlap. What do not place does properly display the cannot place message.

Observation has shown :
- Overlap occurs usually but not always only on one side of mirror, opposite to the side the prefab was pasted on.
- Bricks half on the mirror are usually fine, they seem to check against themselves.
- One of overlapping large hull blocks go untextured.
Both above save in blueprint & game saves
- Rare occurrence of when removing one of 2 perfectly overlapping blocks (small round thrusters in all observed cases), the other becomes unremovable (and loses lightsources) until exiting to menu > return to game.

### Environment
- Starship EVO version: 20w50a
- Graphics Card: NVIDIA RTX 2060

### Additional information:

Providing test blueprint with a bunch of examples and info.

**Comment by YellowMiner** [comment]
Files seem to not have integrated

**Comment by YellowMiner** [comment]
Can't seem to put files on github somehow, hosting to cloud

Log : https://1drv.ms/u/s!AsEjkpnnsE9zlKYs_k4U7LaZ-d28ug?e=YVc9ww
Blueprint : https://1drv.ms/u/s!AsEjkpnnsE9zlKYtqY56S4KOER3t8w?e=xcMepa

**Comment by YellowMiner** [comment]
Can't edit comments either so for clarity :

"Both above save in blueprint & game saves" means overlaping bricks and untextured large blocks

**Comment by tsunamayo** [comment]
@YellowMiner Hi, thanks for booking all these. Can you zip file and drop them here (this should work)? cheers

**Comment by YellowMiner** [comment]
[Overlap test.zip](https://github.com/tsunamayo/Starship-EVO/files/5682708/Overlap.test.zip)
[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/5682710/output_log.zip)

seems i can bypass the problem using another navigator. i'll reupload all the logs too.

**Comment by tsunamayo** [comment]
Should be good now.
