### ISSUE TITLE
[Bug] Title menu slow when quitting to title

### ISSUE THREAD

**Issue by YellowMiner** [tsunamayo/Starship-EVO#3362]
### Short Description of the issue:

When returning to title menu from a save, it is increasingly slower to respond to mouse movement & clicks the more "load save > exit to title" happens in this session. Actual ingame (not title menu) works fine in all cycles. Restarting the game fully resets it to full responsiveness.

Upon alt-tabbing (from title screen) & returning it returns to full responsiveness. From there loading a save may crash the game. if not crashing here, it may upon returning to title menu, possibly multiple cycles later.

### Steps to reproduce the issue:

load save > exit to title
May need more than 1 cycle to become noticeable.

Alt-tab away when menu unresponsive and click back in, then load save > return to menu until it crashes.

### Environment
- Starship EVO version: 20w50a
- Graphics Card: NVIDIA RTX 2060
- Intel i7-10750H 2.6GHz
- 16G RAM

Log : https://1drv.ms/u/s!AsEjkpnnsE9zlKYu1n8Aa9XPpmMNqQ?e=DJ6NdD

**Comment by YellowMiner** [comment]
[output_log2.zip](https://github.com/tsunamayo/Starship-EVO/files/5682711/output_log2.zip)

**Comment by tsunamayo** [comment]
Should be good now! thanks
