### ISSUE TITLE
[Bug] Galaxy map fails to display stars

### ISSUE THREAD

**Issue by YellowMiner** [tsunamayo/Starship-EVO#3364]
### Short Description of the issue:

When in the holomap and in closeup view (the one that lets you rotate with right mouse click), upon clicking in the holomap but between stars (not on any star), map shows grid, gas, position marker & calculated warp route only. Using the focus on ship or focus on warp target buttons, or unzooming to top down view fixes it.

Also when a star is selected and a warp route is set, the cancel it button in the star's panel still says "compute travel route"

Note that it would be nice to have info somewhere in the holomap panel on how to zoom, pan and rotate it ; it took me a while to figure out i could. The zoom in to closeup view with mousewheel is especially low sensitivity and as such it is easy to miss that it is possible to focus any star instead of just local position and warp target.

### Environment
- Starship EVO version: 20w50a
- Graphics Card: NVIDIA RTX 2060

**Comment by YellowMiner** [comment]
I also managed to make only the star i am currently at dissapear somewhow but failed to reproduce.

**Comment by YellowMiner** [comment]
Bug (no stars) also happens when opening holomap in zoomed in state.

**Comment by tsunamayo** [comment]
Yes I noticed that too, it is already fixed for 20w51a. Thanks
