### ISSUE TITLE
[Bug] Warp fails and sends player to abyss

### ISSUE THREAD

**Issue by YellowMiner** [tsunamayo/Starship-EVO#3367]
### Short Description of the issue:

Upon warp to another system, if the player is not seated when piloting the ship (at least that seems to be the trigger), he is sent to deep space when the environement swap between both systems happen. Upon exiting the game, save cannot be loaded anymore.

On occasions while reproducing this bug the autopilot has engaged lightcruise but failed to engage warp. Cancelling it and reengaging warp may work. Could be or not be related.

### Steps to reproduce the issue:

Add warp drive in mistral cargobay, pilot from standing behind seat, plot course, warp.

### Environment
- Starship EVO version: 20w50a
- Graphics Card: NVIDIA RTX 2060

### Additional information:

Log : https://1drv.ms/u/s!AsEjkpnnsE9zlKYxwbFaWXq_5qCNcA?e=b2gCtV

**Comment by YellowMiner** [comment]
May be related to or the same as #3355

**Comment by YellowMiner** [comment]
If they are the same, i explicitely said that you must not be seated when the environement swap happens, which may explain why 3355 failed to reproduce upon exiting the yoke post warp when it must be done during. May be the author not wording what he did properly.

**Comment by YellowMiner** [comment]
[output_log3.zip](https://github.com/tsunamayo/Starship-EVO/files/5682712/output_log3.zip)

**Comment by tsunamayo** [comment]
Okay I will try to reproduce, I keep you posted! Thanks

**Comment by tsunamayo** [comment]
@YellowMiner Hi, could you send me your blueprint? Does the blueprint have gravity unit? If not, and you exit your ship while it is moving then you will be left stranded in space, it is normal. thx

**Comment by tsunamayo** [comment]
Issue fixed for 21w03a. Thanks
