### ISSUE TITLE
Stutter

### ISSUE THREAD

**Issue by thalber** [tsunamayo/Starship-EVO#3369]
### Short Description of the issue:
Significant performance drop on several savefiles. No correlation to the amount / size / complexity of entities spawned.

### Steps to reproduce the issue:

1) Load the savefile
2) 30fps experience

### Environment
- Starship EVO version: 20w49a
- Graphics Card: nvidia 1050ti

### Additional information:

Symptoms:

Performance stably low, sub 20 fps regardless of circumstances, eventual drops to sub-10.

For some reason the game does not take more than 25-30% of GPU power (before this issue appeared it used to chew on 90-100% all the time and run at 45-60  fps); CPU or RAM usage is not increased.
Creating new savefiles while those two savefiles are inside SaveData\Characters causes the newly created save to lag in a similar way; erasing characters directory fixed the issue. Particular blueprints do not seem to be involved; fresh save created from a fresh character folder allowed the game to run at 50-60 fps again.

Savefiles in question:
[Characters.zip](https://github.com/tsunamayo/Starship-EVO/files/5680442/Characters.zip)
Log:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5680431/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, what are your CPU / RAM spec? Also what are your CPU and RAM usage, and did you use vsync? What is the refresh rate of your monitor? Thanks

**Comment by thalber** [comment]
> Hi, what are your CPU / RAM spec? Also what are your CPU and RAM usage, and did you use vsync? What is the refresh rate of your monitor? Thanks

CPU: i5 7500
RAM: 2x 4GB
Display refresh rate: 60Hz

CPU usage always sits around 40%, RAM usage varies but never goes higher than 4.5gb. Neither CPU nor RAM usage go up when the bug is present; the only thing that changes is GPU stress (as I said, the bug *reduces* it from 100% to 25-30%).

Toggling vsync or any other graphics settings did not affect the issue.

**Comment by tsunamayo** [comment]
Perfs are now much better after Neovox.
