### ISSUE TITLE
black boxes

### ISSUE THREAD

**Issue by KINGrimson** [tsunamayo/Starship-EVO#3370]
### Short Description of the issue:
when building a ship made out of bricks you get black boxes
...

### Steps to reproduce the issue:
spawn in a ship made of brick and fly around it until black box is seen
...

### Environment
- Starship EVO version: 20w50a
- Graphics Card: rtc2060
### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![image](https://user-images.githubusercontent.com/74992043/101959222-32d11b80-3c05-11eb-8d0c-712fa494c5ad.png)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[output_log (2).zip](https://github.com/tsunamayo/Starship-EVO/files/5681800/output_log.2.zip)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by quinchinno** [comment]
I've had these black boxes too as well as random artifacts when building.  Wonder what causes it.

**Comment by tsunamayo** [comment]
@KINGrimson Hi, could you please send me the blueprint? Is it on the ship only? Cheers
