### ISSUE TITLE
[Question] thruster damage

### ISSUE THREAD

**Issue by KINGrimson** [tsunamayo/Starship-EVO#3372]
### Short Description of the issue:

simple thing, will their be thruster damage

**Comment by tsunamayo** [comment]
@KINGrimson There is already thruster damage! Thx

**Comment by KINGrimson** [comment]
okey its kinda my fault but i actually ment thruster flame damage

**Comment by BrickMacklin** [comment]
@tsunamayo I think this user means a thruster destroying a block that is near it. Currently that is not happening (and I would love if it stays that way.)
