### ISSUE TITLE
[bug] decal overlap not rendering correctly 

### ISSUE THREAD

**Issue by KINGrimson** [tsunamayo/Starship-EVO#3375]
### Short Description of the issue:
when away from a decal with in 1 meter of the decals if you have multiple it doesnt render the overlap right
...

### Steps to reproduce the issue:
have multiple decals overlap and stand back to see it not overlaping correctly 
...

### Environment
- Starship EVO version: 20w50a
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![image](https://user-images.githubusercontent.com/74992043/101991853-a6c7fe00-3caf-11eb-9e9c-8917e0571394.png)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by tsunamayo** [comment]
@KINGrimson Can you send me your blueprint? Thanks!

**Comment by KINGrimson** [comment]
[LSF-3400 Wombat (2).zip](https://github.com/tsunamayo/Starship-EVO/files/5694177/LSF-3400.Wombat.2.zip)

**Comment by tsunamayo** [comment]
Fixed in recent builds.
