### ISSUE TITLE
Ship has wrong power level upon game loading

### ISSUE THREAD

**Issue by BrickMacklin** [tsunamayo/Starship-EVO#3376]
When I load in the game the ship I am building has the wrong power level. However if I wait a minute it eventually goes back to normal. Please see the screenshots below:
![image](https://user-images.githubusercontent.com/37836252/102021385-6919b280-3d4d-11eb-985d-b5d49625a74a.png)
![image](https://user-images.githubusercontent.com/37836252/102021386-6ae37600-3d4d-11eb-9114-eb781ec717b4.png)

The reactor modules did not change between these two photos.

![image](https://user-images.githubusercontent.com/37836252/102021390-7171ed80-3d4d-11eb-99b4-4e0a35522545.png)

...

Load game and immediately try to fly ship. Then wait a minute or two and check the power levels.

...

### Environment
- Starship EVO version: 20w50a
- Graphics Card: RTX 3080

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5685247/output_log.txt)

**Comment by TIKIRobo** [comment]
this may be because your shields (if you have any if not idk) are recharging and so drawing extra power but im probably wrong

**Comment by tsunamayo** [comment]
@TIKIRobo I guess you are right... thx
