### ISSUE TITLE
Save File bricks after galaxy travel.

### ISSUE THREAD

**Issue by BrickMacklin** [tsunamayo/Starship-EVO#3380]
On two of my saves, after making substantial galactic travel, I can longer load into the world. I have exited the saves. Tried to load them after starting the game and I get a never-ending loading screen. Two of these saves are now unusable.

...

### Environment
- Starship EVO version: 20w50a
- Graphics Card: RTX 3080

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5693354/output_log.txt)

[117.zip](https://github.com/tsunamayo/Starship-EVO/files/5693355/117.zip)
[Sovereign.zip](https://github.com/tsunamayo/Starship-EVO/files/5693357/Sovereign.zip)

**Comment by tsunamayo** [comment]
@BrickMacklin Okay I keep you posted. Thanks  for the save file. Cheers

**Comment by tsunamayo** [comment]
@BrickMacklin Okay so in the new version 21w01a I can load both save. Tell me if you still have issues loading the two worlds! Cheers
