### ISSUE TITLE
[Bug] orange engines glow red

### ISSUE THREAD

**Issue by YellowMiner** [tsunamayo/Starship-EVO#3383]
### Short Description of the issue:

The glow (the light effect, not the texture) colour of large engine blocks painted orange is (or at least seems to be) the same as red. All other colours seem to have it of the right unique colour (may need double check). Seeems fine on smaller engines but it may be because the glow is too small to be noticeable.

### Steps to reproduce the issue:

build large engine. Add blocks on the side to better see the glow, i'd recommend painted black to see better. Paint away.

### Environment
- Starship EVO version: 20w50a
- Graphics Card: Nvidia RTX 2060

**Comment by KINGrimson** [comment]
a picture would help to see the issue

**Comment by zorozeenee** [comment]
it is not quite red but a more blood orange, i personally like the look of it, i use it on all my ships

**Comment by tsunamayo** [comment]
@YellowMiner yeah I see, it is not really a bug this is how colors works. A orange closer to yellow would look less red in glow, so if you really need that that would have to wait for the custom color update. Thanks
