### ISSUE TITLE
[Bug] Crash when blocks were placed on a rail that was on a piston

### ISSUE THREAD

**Issue by FunkyStuff99** [tsunamayo/Starship-EVO#3385]
### Short Description of the issue:
I tried to build a door for my ship, and when I stretch-placed some blocks on a rail that was on a piston, the screen went black.
Game crashed and closed.

...

### Steps to reproduce the issue:
Im not really sure, but just place down a small piston. On it, stretch a small piston with 3.00, 0.25, 0.25. Then, place a small normal block on it and stretch it,
...

### Environment
- Starship EVO version: 20w50a
- Graphics Card: NVIDIA GeForce GTX 1660 Ti
[Crashed_Ship.zip](https://github.com/tsunamayo/Starship-EVO/files/5716198/Crashed_Ship.zip)

### Additional information:

I also opened OBS to record something in the background, dunno if it has something to do with it.

output_log.txt : 
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5719557/output_log.txt)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by AlienXtream** [comment]
hey. could you please drag and drop the actual log file, not copy and paste the contents. it makes it easier to read and manage.

**Comment by tsunamayo** [comment]
Issue should be fixed in recent updates. Thanks
