### ISSUE TITLE
Game don't create character, and doesn't load

### ISSUE THREAD

**Issue by Paul-van-Hummel** [tsunamayo/Starship-EVO#3386]
### Short Description of the issue:

...Hi there, I've bought today the game Starship-EVO,
However I already have problems with the game.

I can't get bejond the creating character setup, where it's only allowed to choose a name, in single modus.
Than I get the loading picture (As I already found out via you-tube) but instead of loading the game,
it shut's down without any error message pop up and Im back on my desktop computer...

I don't know what to do, can you please help me out?

(Sorry for any wrong writing because I'm native Dutch)

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5717751/output_log.txt)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.

Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by tsunamayo** [comment]
Hi, unfortunately your GFX card is below min requirements and is causing some trouble. Try to upgrade your drivers to see if it fixes the issue, (I managed to run the game on a Intel 630), or get a refund.
Thanks

**Comment by Paul-van-Hummel** [comment]
Thanks for the quick reply, I will upgrade my hardware, I have an onboard graphic card, and have slots available to add a good 4K graphic card, I will do this next week if the store is open or apply service by phone (lockdown in my country due to the virus)
I don't gonna get a refund, I already was spoiling myself with you tube, and the game goes alot further than Starmade that I play, and I'm guessing I've gonna love Starship EVO... So for me it means to be a little bit more patient... 

Thanks for your help, and reply... I know now what to do...
