### ISSUE TITLE
[Suggestion] [QOL] adjust light brightness according to color gradient

### ISSUE THREAD

**Issue by CptCamembert** [tsunamayo/Starship-EVO#3387]
Currently, if you color a light red, it will glow red. This is fine of course, but the brightness of the light is not influenced by the hue of red you choose. (bright red results in the same glow as dark red)

Contrarily, lights that are colored grey will actually have their brightness adjusted (light grey glows stronger than dark grey) This is awesome, because the default brightness is quite high and adjusting the brightness using sliders or sequencers is pretty tedious.

The suggestion is to implement the lights in a way that the brightness of the color chosen also changes the brightness of the light on non-grey lights as well, such that you can create three differently bright red lights only using the three different red hues.

**Comment by tsunamayo** [comment]
Yes it makes sense, but that would nuke all current blueprint light... Thanks

**Comment by CptCamembert** [comment]
So, no? Also, why does it nuke all blueprint lights? Do you have to reintroduce the blocks such that old blueprints won't recognize them?

**Comment by tsunamayo** [comment]
It is working this way now. Thanks
