### ISSUE TITLE
[Bug] Gravity unit & jump pad power draws

### ISSUE THREAD

**Issue by YellowMiner** [tsunamayo/Starship-EVO#3395]
### Short Description of the issue:

Gravity unit & jump pad have -40e/s power draws displayed. Placing either down shows no effects on power in either direction.

### Environment
- Starship EVO version: 20w50a

**Comment by YellowMiner** [comment]
No heat effects were observed either despite displayed stats.

**Comment by tsunamayo** [comment]
Fixed for 20w51a. Thanks!
