### ISSUE TITLE
[Not really a bug] Large thrusters placed sideways provide no maneuvering thrust

### ISSUE THREAD

**Issue by YellowMiner** [tsunamayo/Starship-EVO#3396]
### Short Description of the issue:

Large thrusters have no effect beside generating waste heat when placed in any orientation beside back facing. This is most likely intended but counter intuitive given how small thrusters operate.

Given they are useful as decoration if only as fake maneuvering thrusters (the canis interceptor has a set of them in the front) or light sources, especially on larger ships, it would be probably best for them to either not generate any heat when in an invalid orientation or work as maneuvering thrusters like smaller ones (no lightcruise provided).

### Environment
- Starship EVO version: 20w50a

**Comment by KINGrimson** [comment]
large block thrusters are ment for only forward thrust and the brick ones for maneuvering thrust and he cant really make it so that if it isnt facing for forward thrust that it cant generate hear, and i doupbt he will make them work as maneuvering thrusters either as thats not their purpose

**Comment by zorozeenee** [comment]
yea you are supposed to use small thrusters homie

**Comment by tsunamayo** [comment]
@YellowMiner yes you are 100% right, I havent decided on what to do with this... I am waiting for fuel. The large thruster will require some fuel...
