### ISSUE TITLE
[BUG] Turrets damaging my own ship

### ISSUE THREAD

**Issue by zorozeenee** [tsunamayo/Starship-EVO#3399]
### Short Description of the issue:

My turrets are damaging my own ship. They aim at a target on the opposite side of the ship fire and damage my main ship.

### Steps to reproduce the issue:

Make a ship, set a turret up, then when piloting select an enemy target on the opposite side of your ship or have your turret in auto fire mode. The turret will then fire into your ship damaging it.

My ship is rather large (218 x 243 x 560 - 149619 tons)

### Environment
- Starship EVO version: experimental build
- Graphics Card: nvidia gtx 1060 super
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5731417/output_log.txt)

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by zorozeenee** [comment]
In addition I am using range barrels and gatling barrels on the turrets

**Comment by KINGrimson** [comment]
> In addition I am using range barrels and gatling barrels on the turrets

here is a hint if you can place  ablock underneat the barrel of the laser then it stops going further down, will work for the moment

**Comment by tsunamayo** [comment]
@zorozeenee Could you send the blueprint so I can investigate? Thanks

**Comment by tsunamayo** [comment]
Issue fixed for 21w04b. Thanks
