### ISSUE TITLE
Suggestion/Concern

### ISSUE THREAD

**Issue by Halefyre** [tsunamayo/Starship-EVO#3400]
### Short Description of the issue:

Hello! I was directed here to make a suggestion in regards to a concern. I just purchased the game today, and over the course of a few hours figured out the controls and build the layout of a very simple ship. However, after blocking off floors and walls, I found I didn't have any way to carve specific blocks out of stretched blocks. I asked on the Discord server, and was told that you are unable to do so. I was honestly surprised to hear that was the case, and even more surprised that, apparently, no one else has had this concern, as the feature wasn't being considered. Personally, I don't know how people are able to map out their entire design in their head beforehand, as I'm sure they don't place blocks one-by-one, and I can't imagine they delete large swaths of their design to add a door. I realize that might sound like whining, but I am really just not sure how to go about that. At any rate, the blocks are individually marked out and paintable, even if stretched, and it would make designing as you go infinitely easier if you could, say, hold shift while using the placement tool to right-click and delete only the smallest targeted entity. Apologies if this was a little long-winded. The game is really interesting to me, and it's the first time a ship-building toolset has actually convinced me to buy a game. Just hoping to make it more approachable for anyone like me who isn't particularly architecturally-minded. Thanks.

**Comment by tsunamayo** [comment]
Hi, of course it has been suggested / talked over a long time ago ;). Unfortunately it is not possible with the current stretch technology.
This is the main drawback of the stretch tech, it is definitely a bit painful for making windows / door.
It was well though out when we did the switch to the stretch tech, I figured out it would bring so much freedom that it was worth it. No perfect building system exists...
Theoretically it could be possible with full hull block only, but that would be added complexity in many aspect, and would still be frustrating and illogical player wise (why it is okay with full hull and not with the rest?). It seems that the existing player base bite the bullet and embraced the stretched, I hope you get used to that...
Cheers

**Comment by Halefyre** [comment]
I appreciate the speedy response. I guess I'll have to get used to thinking ahead about things. Not the end of the world, I suppose. Thanks for your hard work, and I look forward to seeing where things go!

**Comment by cloudrambler** [comment]
@Halefyre The nice thing about how STEVO works with ship builds is that it does not worry about whether blocks are physically connected. So there is no risk to delete large parts of your ship and then fill in the gaps with smaller parts. It won't fall apart like it would in some other ship building games, as it does not sub-divide the grid.

Also, a neat trick you can use to rough out your ideas is to build a scale model with the bricks first. They have exactly the same proportions as the full size blocks, but at 1/4 scale. That can be easier to work on and visualise than a full size ship. Then once you have the basic form and layout how you want it, start on the full size ship and work on the bits you can fully visualise first, as the rest will make sense once you have some context.

**Comment by tsunamayo** [comment]
@cloudrambler good advice! Cheers
