### ISSUE TITLE
Is light bleed going to be addressed?

### ISSUE THREAD

**Issue by BrickMacklin** [tsunamayo/Starship-EVO#3401]
I am working on a brick built ship and all of my interior lights are showing through my ship's exterior even though they are set to low power setting. The lights can be seen with the sun shining on them or not. In some cases the lights are more visible outside than it is inside. The screenshots below show the lightbleed on the vessel.

![20201223103957_1](https://user-images.githubusercontent.com/37836252/103013936-f8705400-450b-11eb-845b-110cb53f2c5e.jpg)
![20201223104042_1](https://user-images.githubusercontent.com/37836252/103013959-02925280-450c-11eb-8c66-9c7b990e5c02.jpg)
![20201223104047_1](https://user-images.githubusercontent.com/37836252/103013965-04f4ac80-450c-11eb-80fb-f4a18fed4cf1.jpg)
![20201223104057_1](https://user-images.githubusercontent.com/37836252/103013983-0d4ce780-450c-11eb-8da5-80968997212b.jpg)
![20201223104058_1](https://user-images.githubusercontent.com/37836252/103013990-0faf4180-450c-11eb-859a-ccd375b9f11b.jpg)
![20201223104102_1](https://user-images.githubusercontent.com/37836252/103013993-12119b80-450c-11eb-8740-dbc0d4e2e890.jpg)
![20201223103930_1](https://user-images.githubusercontent.com/37836252/103014003-15a52280-450c-11eb-9c50-537bdc4658a3.jpg)
![20201223104108_1](https://user-images.githubusercontent.com/37836252/103014009-18077c80-450c-11eb-8457-dd97dd6faeef.jpg)
![20201223104119_1](https://user-images.githubusercontent.com/37836252/103014013-19d14000-450c-11eb-83d7-b306d0b1d2f5.jpg)

...

### Environment
- Starship EVO version: 20w50a
- Graphics Card: RTX 3080

**Comment by tsunamayo** [comment]
@BrickMacklin Amazing normandy! So it seems you are using blocks, so it should not happens. If you can send me the blueprint so I can investigate! Cheers

**Comment by BrickMacklin** [comment]
Thanks! It's a full brick build interestingly. I could not make the shape work with blocks.
[Normandy SR1.zip](https://github.com/tsunamayo/Starship-EVO/files/5752833/Normandy.SR1.zip)

**Comment by tsunamayo** [comment]
@BrickMacklin there you go, no voxel light computation possible with bricks unfortunately. It has to be voxel (ie hull blocks). I dont think I will have to bandwidth to try other methods... Cheers
