### ISSUE TITLE
[bug] random lagspikes

### ISSUE THREAD

**Issue by KINGrimson** [tsunamayo/Starship-EVO#3403]
### Short Description of the issue:
i keep having random lag spikes in all my world, usealy with  a FPS drop to 10 fps its just for a moment. its anyoing but not game breaking
...

### Steps to reproduce the issue:
load world i provided
...

### Environment
- Starship EVO version: 20w50a
- Graphics Card: rtx2060

### Additional information:

[destoryer.zip](https://github.com/tsunamayo/Starship-EVO/files/5736907/destoryer.zip)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5736945/output_log.txt)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by KINGrimson** [comment]
output file may not be od any use cause i had to reinstal the game to get the output file to work as the one before reinstal was 800MB

**Comment by KINGrimson** [comment]
[output_log (2).zip](https://github.com/tsunamayo/Starship-EVO/files/5737337/output_log.2.zip)
this was a output log of 128MB i was able to zip here you will find some problems i think

**Comment by Kaiser-Indrasil** [comment]
From my experience it tends to happen over a couple of hours of gameplay.
Alt-Tabbing might be one of the culprits, too.
The usual logic-related frame drop does happen but the FPS return back to the baseline once logic operations are finished.
Besides that, there's no big scene modification on my end. No moving ships. Only building by hand.
May be occlusion-culling related? I noticed that my FPS drop considerably when I'm clipping through geometry and revert back to normal when I'm back out of it.

Changing the screen display method from fullscreen to borderless and back does not fix the issue.
However, restarting the world does.

**Comment by tsunamayo** [comment]
@KINGrimson Hi, you have a lot of ship inside the sun for some reason. I would suggest create a new character and see if it is improves it (it might be something else). Thanks

**Comment by KINGrimson** [comment]
> @KINGrimson Hi, you have a lot of ship inside the sun for some reason. I would suggest create a new character and see if it is improves it (it might be something else). Thanks

i have that problem in every world i make so i dont think thats the problem i do findi t weird of the sun as i never get close to it

**Comment by Kaiser-Indrasil** [comment]
I found out that NPCs like to travel into the planets after a few trips, generating graveyards over time, so that might be connected.

**Comment by tsunamayo** [comment]
@KINGrimson Do you still get this in recent experimental? Thx
