### ISSUE TITLE
[Question] Ring environements

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#3404]
This has been something that has been assumed for a long time now, but since planet tech and generation is in the works now, is the plan for the ring environments to eventually "mirror" the various planetary environments? Like a desert ring or a lava ring.

**Comment by tsunamayo** [comment]
Yes I want to start by this. It is not really yet in the work et to be honest though. I am looking at the 3d terrain tech atm first. I need several things like lod, cheap collision and raycast, and be able to generate the voxel data fast, it is a bit tricky. Thanks

**Comment by AlienXtream** [comment]
suspected you would prefer voxel terrain
