### ISSUE TITLE
[Suggestion] Spherical wormholes

### ISSUE THREAD

**Issue by Calvert4096** [tsunamayo/Starship-EVO#3405]
I think there were one or two suggestion posts where wormholes are mentioned already.  Assuming there will be some implementation in the future, it would be neat if they are spherical, as in the movie "Interstellar."  I think it would make attacking or defending them as strategic choke-points more interesting.  Stationary defenses in particular would require a closed volume to provide complete coverage on one side of the wormhole.

In-browser wormhole simulator:  https://sirxemic.github.io/Interstellar/

This simulator is pretty resource intensive, but I'd be curious if there are less resource-intensive approximations of non-euclidean space that could be viable in the SEVO engine.

**Comment by tsunamayo** [comment]
Ho, yeah for sure I could spend a month on that, but for now I think it would be smarter to work on the gameplay loop. Thanks
