### ISSUE TITLE
[BUG] black boxes

### ISSUE THREAD

**Issue by KINGrimson** [tsunamayo/Starship-EVO#3409]
### Short Description of the issue:
a graphical bug that shows black boxes
...

### Steps to reproduce the issue:
no idea how happens on random
...

### Environment
- Starship EVO version: 20w50a
- Graphics Card: RTX2060

### Additional information:
![image](https://user-images.githubusercontent.com/74992043/103160426-318f1980-47d5-11eb-8553-4d7ea8b5e4ae.png)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

https://drive.google.com/file/d/1kSQ47OrE4ytqeY_wJ40VDZClDGIGwtyy/view?usp=sharing
file was to big to upload

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by tsunamayo** [comment]
@KINGrimson Hi, I cant reproduce this issue so I am not sure what happens. Do you get this often? How long into the session? Thanks
