### ISSUE TITLE
[bug] copy paste and large pipes

### ISSUE THREAD

**Issue by KINGrimson** [tsunamayo/Starship-EVO#3410]
### Short Description of the issue:
using copy paste you are abel to ofset large tubes using the brick grid, which shouldn't be possible. altho its nice you can as it allows new design options
...

### Steps to reproduce the issue:
place large pipe, copy it then paste it and see you can use the brick grid
...

### Environment
- Starship EVO version: 20w50a
- Graphics Card: RTX2060

### Additional information:
![image](https://user-images.githubusercontent.com/74992043/103161339-9e5be100-47e0-11eb-8f2e-392e2b63269a.png)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by ProPeach** [comment]
I believe this is a side effect to the ability to offer the pipe vertically. If you place some bricks on a block floor, you can still put a block sized pipe on top of them. I think you'll see the same behaviour with the round grill panel too, it would be a real shame to lose that functionality
