### ISSUE TITLE
[Question] Overload children entity on a hinge?

### ISSUE THREAD

**Issue by Zenti98** [tsunamayo/Starship-EVO#3411]
Hi, just a short question; Will there be any losses in game performance or problems with the project, if I load too much mass on a hinge, e.g. 10.000%,? I don't wanna move it, I know that this becomes impossible with >100%. Its just for a hull construction, most of it will be connected with that hinge. Thank you very much!

**Comment by ProPeach** [comment]
Nothing bad will happen after the 100% mark other than it becoming static, you're good!

**Comment by Zenti98** [comment]
> 
> 
> Nothing bad will happen after the 100% mark other than it becoming static, you're good!

Ah thank you!!

**Comment by tsunamayo** [comment]
Yep, thanks +100pt for the correct answer ;)
