### ISSUE TITLE
[Bug] Invisible blocks and game crashes

### ISSUE THREAD

**Issue by Zenti98** [tsunamayo/Starship-EVO#3413]
Ah I also would like to report two issues...
The invisible blocks are back again. Always after 20-40 min in game, the first one appaers while building, sometime more of them, other times only one. It's fully random...

After the last update there are game crashes, too. Also random, in every project, sometimes after 20 or 60 minutes. Game freezes for a few secs and then it crashes. Always in the moment, I want to place something.

Thank you!

### Environment
- Starship EVO version: Experimental Version 20w50a
- Graphics Card: Geforce RTX2060

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5744685/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, does it happen on the very large ship you must be building according to the logs? There is an issue related to light that I just fixed. Thanks

**Comment by Zenti98** [comment]
> 
> 
> Hi, does it happen on the very large ship you must be building according to the logs? There is an issue related to light that I just fixed. Thanks

@tsunamayo Yes, thats the case ;-) Thank you for your help! One more question to you, do you think there might be an update in future, which will change some fundamental game mechanics, so that current projects won't be able to run anymore? I just talk about the standart blocks and hinges, no detail stuff - thank you very much!

**Comment by tsunamayo** [comment]
@Zenti98 You will be able to load your ship. Just be sure to load them and save them regularly. You might need to do some tweak like when fuel is added for example though. Cheers

**Comment by tsunamayo** [comment]
So the crash issue is fixed for 21w01a. For the other there are a few case opened so I will close this! Thanks
