### ISSUE TITLE
[BUG] Can't upload ships to the workshop

### ISSUE THREAD

**Issue by FunkyStuff99** [tsunamayo/Starship-EVO#3414]
### Short Description of the issue:

When I try to upload my ship onto the workshop, the upload fails with the message: LimitExceeded.
When I look into my uploads, thee's a new blank upload with no picture.

### Steps to reproduce the issue:

Im not sure, I just tried to upload my ship.

### Environment
- Starship EVO version: 
- Graphics Card: Nvidia GTX 1660 Ti

### Additional information:

![bug](https://user-images.githubusercontent.com/69148659/103178714-9dc95600-4885-11eb-9110-a3e0afc50891.JPG)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5745093/output_log.txt)

[Lazarus Hovercarrier - Kopie.zip](https://github.com/tsunamayo/Starship-EVO/files/5745097/Lazarus.Hovercarrier.-.Kopie.zip)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by tsunamayo** [comment]
Hi, does it happens with this ship only, or with any ship? Thanks

**Comment by FunkyStuff99** [comment]
Only this one fails, uploading other ships works.

**Comment by FunkyStuff99** [comment]
Scratch that, looks like I can't upload anything now.

**Comment by FunkyStuff99** [comment]
Seems like I found the error, the preview image was too big :)

**Comment by tsunamayo** [comment]
Okay thanks for the update!
