### ISSUE TITLE
[BUG] Movement speed not resetting when game loaded

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#3415]
Normally, when I load the game and fast movement is deselected by default, the HUD speed mode indicator shows x1. Today I loaded a game and the HUD speed indicator was showing x27, but I was limited to x1 movement. The speed change buttons would not respond until I turned on the fast movement option. So really the only bug was that the HUD did not reset to x1 by default to match the fast movement mode default.

### Steps to reproduce the issue:

Load game, enable fast movement, set speed to x27, exit game.
Reload game; speed mode indicator still shows x27 (fast movement is off by default).
Enable fast movement, adjust speed; all works as expected until next load.

### Environment

- Starship EVO version: 20w50a
- Graphics Card: GTX1070

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5745119/output_log.txt)

**Comment by cloudrambler** [comment]
I would also like to suggest that a sensible cap be placed on the movement speed. I tried moving at "ludicrous speed" and effectively crashed the game. It jumped to the middle of nowhere, becoming unresponsive and slow (1FPS maybe).

My guess is that x729 is the highest useful speed within the ring habitat. Not tried it on / between the new planets.

**Comment by tsunamayo** [comment]
@cloudrambler So I made the fix and suggestion. Limit is at 1000000x though, this is what I need to travel between planet (I do that a lot). Cheers

**Comment by Kaiser-Indrasil** [comment]
The x27 speed at reset exists only as text on the UI.
In practice, the player's speed is reset to x1, so it's more of a problem with the UI.
