### ISSUE TITLE
[BUG] "Cirle" Line, Triangle, Vent Holes and Creased Vert Triangle Decals improperly mirror

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3416]
### Short Description of the issue:
the above mentioned decals do not mirror properly 
...
(also maybe im dumb but i think the cirle decal should be circle unless cirle means something)
### Steps to reproduce the issue:
place decals on ship and see them on the other side of the mirror plane

https://user-images.githubusercontent.com/56371294/103180223-1366ff00-4851-11eb-888b-da9bcbaf3dad.mp4

**Comment by tsunamayo** [comment]
@TIKIRobo Issue fixed for 22w03c. Thanks
