### ISSUE TITLE
[Suggestion] Brick to Pipe Adaptor

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#3418]
Something I've noticed is that when placing pipes and other round objects on top of bricks, it can looks a little out of place or "plonked." It would be nice to have a square to round adapter brick

![image](https://user-images.githubusercontent.com/36980446/103183644-fb06dc80-4870-11eb-9b79-a7861465e1e8.png)
Build by Junosato

![image](https://user-images.githubusercontent.com/36980446/103183670-238ed680-4871-11eb-8d8b-31abc6225025.png)
Model by Peach

**Comment by tsunamayo** [comment]
Hi, hum my brain cant comprehend that 3d shape ;) To be fair I dont event think it make sense, in real life (or scifi for that matter), you always get straight pipe into the wall and thats it, I cant recall seeing that shape anywhere. But some kind of thicker base could make sense and break the monotony I agree, there is just not room for it...
Cheers
