### ISSUE TITLE
Ship disappears on block placement.

### ISSUE THREAD

**Issue by Azathoh-the-blind-idiot-god** [tsunamayo/Starship-EVO#3419]
### Short Description of the issue:

ship partly dissapeared and when I placed a block on it to save it it completely went invisible`.

### Steps to reproduce the issue:

don't know, should appear and reappear randomly

### Environment
- Starship EVO version: 20w50a
- Graphics Card: rx 5700 

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5748334/output_log.txt)

**Comment by tsunamayo** [comment]
@Azathoh-the-blind-idiot-god Hi, could you please upload the blueprint so I can investigate? Thanks
