### ISSUE TITLE
[Suggestion] Seeded Planets.

### ISSUE THREAD

**Issue by Titaniclover** [tsunamayo/Starship-EVO#3422]
I know the generation of planets is slow and you only have a few types, but here's an idea:
Instead of making every planet by hand, make multiple layers of planets and give them seeds.
Example: let's say you have a 3 digit seed, one layer for ground, one layer for clouds, and one layer for the atmosphere. If you use a 0-9 system you can make up to 1000 different planet combinations! And you would only need 30 planet layers total (10 for land, 10 for clouds, 10 for atmosphere).
Just an idea, and you could add more digits to make planets even more varied.

**Comment by KINGrimson** [comment]
planets will be procedural generated
