### ISSUE TITLE
[bug] auto-turrets shots from inside the ship

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#3425]
### Short Description of the issue:
In this particular ship, all the weapons are concealed and need to be deployed. So, if they are concealed, and an enemy appears, it automatically shoots, even from inside.

### Environment
- Starship EVO version: normal version
- Graphics Card: gtx 1660
- cpu i7 3770
- 16gb ram
- 

### Additional information:

video
https://youtu.be/dN0VCp4Cx0c

output log
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5755572/output_log.txt)

blueprint
[[ULTY] Minas Gerais.zip](https://github.com/tsunamayo/Starship-EVO/files/5755571/ULTY.Minas.Gerais.zip)

`

**Comment by tsunamayo** [comment]
Okay I need to have a look at this, it should not fire on itself. Thanks

**Comment by tsunamayo** [comment]
Issue fixed for 21w04b. Thanks
