### ISSUE TITLE
Everything disappear and the ship get weird

### ISSUE THREAD

**Issue by Lecucube** [tsunamayo/Starship-EVO#3426]
### Short Description of the issue:
i launched the game and loaded my world and the the ship was like corrupted, i restarted the game and then there was nothing exept star and ship that was spining with particle
### Steps to reproduce the issue:

i dont really know i closed the game and reopened it and thats it 

### Environment
- Starship EVO version: 20w49
- Graphics Card: GTX 1050 3g
### Additional information:

![Capture d’écran (175)](https://user-images.githubusercontent.com/76791897/103378574-0f521000-4ae3-11eb-9aeb-d4ca75aca47b.png)
*restarted the game*
![Capture d’écran (176)](https://user-images.githubusercontent.com/76791897/103378581-12e59700-4ae3-11eb-908e-101c3aaa00c4.png)

Output_log:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5755565/output_log.txt)

Initialize engine version: 2018.3.14f1 (d0e9f15437b1)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1050 (ID=0x1c91)
    Vendor:   
    VRAM:     2996 MB
    Driver:   27.21.14.5241
Begin MonoManager ReloadAssembly
- Completed reload, in  0.252 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

The referenced script (GrabbableBox) on this Behaviour is missing!
 
(Filename:  Line: 195)

The referenced script on this Behaviour (Game Object 'Box') is missing!
 
(Filename:  Line: 294)

UnloadTime: 0.901600 ms
 -- LOADING RESOURCES -- 
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Shape Mesh Data Buffer Count: 74883
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Allocating Voxel Resources
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Allocating Chunk Resources: 36572
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Allocating Entity Instance Resources
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Allocating Brick Data Resources: 4161111
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Unloading 5 Unused Serialized files (Serialized files now loaded: 0)
Max Queued Frames: 2
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Unloading 1741 unused Assets to reduce memory usage. Loaded Objects now: 13071.
Total: 16.171400 ms (FindLiveObjects: 0.852100 ms CreateObjectMapping: 0.578500 ms MarkObjects: 13.720700 ms  DeleteObjects: 1.019500 ms)

Unloading 1 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 13071.
Total: 15.135100 ms (FindLiveObjects: 1.043300 ms CreateObjectMapping: 0.374200 ms MarkObjects: 13.695000 ms  DeleteObjects: 0.021800 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)
Allocating Mesh Data Resources, total: 34440
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Starship EVO Version: early-access 20w49a
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

System GFX memory 2996 mb
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

System memory 6021 mb
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Steam Log Success
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

SETTINGS Loaded
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 28507.
Total: 39.794900 ms (FindLiveObjects: 2.362900 ms CreateObjectMapping: 1.226500 ms MarkObjects: 36.132700 ms  DeleteObjects: 0.072000 ms)

Unloading 1 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 28507.
Total: 32.492200 ms (FindLiveObjects: 2.343100 ms CreateObjectMapping: 0.960000 ms MarkObjects: 29.133600 ms  DeleteObjects: 0.055100 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 28507.
Total: 32.497000 ms (FindLiveObjects: 1.734900 ms CreateObjectMapping: 0.755100 ms MarkObjects: 29.951300 ms  DeleteObjects: 0.055100 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 29259.
Total: 40.025900 ms (FindLiveObjects: 1.927200 ms CreateObjectMapping: 1.136400 ms MarkObjects: 36.874400 ms  DeleteObjects: 0.087200 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 29259.
Total: 43.861200 ms (FindLiveObjects: 2.269300 ms CreateObjectMapping: 0.967500 ms MarkObjects: 40.558600 ms  DeleteObjects: 0.065400 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 29259.
Total: 42.266600 ms (FindLiveObjects: 3.343900 ms CreateObjectMapping: 1.345200 ms MarkObjects: 37.485500 ms  DeleteObjects: 0.091300 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 29259.
Total: 41.508300 ms (FindLiveObjects: 2.928500 ms CreateObjectMapping: 1.280200 ms MarkObjects: 37.234900 ms  DeleteObjects: 0.064200 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 29259.
Total: 40.099100 ms (FindLiveObjects: 2.698800 ms CreateObjectMapping: 0.928400 ms MarkObjects: 36.408500 ms  DeleteObjects: 0.063000 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 29259.
Total: 41.724700 ms (FindLiveObjects: 2.628800 ms CreateObjectMapping: 1.126300 ms MarkObjects: 37.889100 ms  DeleteObjects: 0.079800 ms)

EXITING GAME
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

De-allocating Voxel Resources
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Uploading Crash Report
NullReferenceException: Object reference not set to an instance of an object
  at VoxelEngine.EntityInstanceResources.UnloadEntityBuffers () [0x00000] in <4d2c3e333a6a43d49b9abe8a0e39cd76>:0 
  at VoxelEngine.EntityInstanceResources.UnloadResources () [0x00000] in <4d2c3e333a6a43d49b9abe8a0e39cd76>:0 
  at VoxelEngine.VoxelMaterialResources.UnloadResources () [0x0000f] in <4d2c3e333a6a43d49b9abe8a0e39cd76>:0 
  at ResourcesLoader.UnloadResources () [0x00000] in <4d2c3e333a6a43d49b9abe8a0e39cd76>:0 
  at ResourcesLoader.OnApplicationQuit () [0x00000] in <4d2c3e333a6a43d49b9abe8a0e39cd76>:0 
 
(Filename: <4d2c3e333a6a43d49b9abe8a0e39cd76> Line: 0)

Asset Repo: On Application Quit
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

UNLOADING ASTEROIDS RESOURCES
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Application Quit: Cleaning Render Texture for Habitat Nodes
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Setting up 2 worker threads for Enlighten.
  Thread -> id: 51b0 -> priority: 1 
  Thread -> id: 2574 -> priority: 1 
SETTINGS.ini Saved
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

This is a bit rude because i was building a ship and idk if there anyway to extract a in-building structure in the files

Goodluck,
Lecucube

**Comment by tsunamayo** [comment]
@Lecucube Hi, so by restarting the game do you mean quit to desktop and restarted the game? Also I dont think this is the right log. Can you reproduce this issue all the time? Thanks
