### ISSUE TITLE
[ TAKE A TOUR TSUNA ] The Talos Explorer 300A

### ISSUE THREAD

**Issue by nokturnihs** [tsunamayo/Starship-EVO#3431]
Hey @tsunamayo - Take a tour and let me know what you think! :) Also has lots of turrets and child entities, multi-crew support - basically a lot to test stuff with!
![20201231173533_1](https://user-images.githubusercontent.com/7344403/103435201-b066c680-4bc8-11eb-9057-7ad8152b3265.jpg)
![20201231180331_1](https://user-images.githubusercontent.com/7344403/103435203-b6f53e00-4bc8-11eb-96e5-1297da08cb56.jpg)
![20201231174753_1](https://user-images.githubusercontent.com/7344403/103435206-c1173c80-4bc8-11eb-98bb-81f21e2410db.jpg)

[https://youtu.be/ayRBkxTaMAk](url)

The Ship you've always dreamed of...

Class: Medium
Size: 62m x 27m x 73m
Tonnage: 2,296

Forward Thrust: 46,240 kN
Warp Range: 14.46 LY

Hull Points: 2,317,282
Shield Capacity: 2,516,000
Shield Recharge: 127,705 pts/sec

Weapon Mount Points: -LOTS-

Video Shot by: a Drunken Idiot (We Fired Him)
Edited by: Same Idiot. He was dumped out an airlock in the neighborhood of a blackhole.

Enjoy!

PS: There's a couple secrets in the cargo hold... Look for the super-secret black button. There's also a "Jeffrey tube" accessible via switch (near the elevator landing on the main deck).

[https://steamcommunity.com/sharedfiles/filedetails/?id=2344575068](url)

[NIE Talos Explorer 300A.zip](https://github.com/tsunamayo/Starship-EVO/files/5758717/NIE.Talos.Explorer.300A.zip)

**Comment by nokturnihs** [comment]
Youtube did some weird shit with the video so had to re-upload.... here's the new link:
[https://youtu.be/1bsDKJwQMUg](url)

**Comment by tsunamayo** [comment]
@nokturnihs whooa massive massive ship! So many little mechanism (+1 for the bed that popup), interior is huge and spacious. So many room and stuff! Indeed a good ship to test crew when I come to this, except for the elevator where I will need to find something for crew.
Good job!
