### ISSUE TITLE
[Bug] Thin tile mirror collision check with self is unreliable.

### ISSUE THREAD

**Issue by YellowMiner** [tsunamayo/Starship-EVO#3432]
### Short Description of the issue:

When placing a stretched thin tile brick on the mirror axis so it overlaps with it's mirrored self it often fails to detect it obstructing the mirrored one, so both get placed. Seems most common when the thin tile is placed on the axis so the mirrored is in the exact same position; but also happens in other cases. When it is offset from the brick main grid, it checks for collision more reliably.

### Environment
- Starship EVO version: 20w50a
- Graphics Card: Nvidia RTX 2060

**Comment by cloudrambler** [comment]
I have found the half and quarter tiles will allow clipping with other bricks on the same grid when stretched to overlap them. Same thin with the bevelled and rounded tiles. I'm not sure if it is intended or a problem for the game, but it is really useful. It allows some tidy asymmetric arrangements to be developed.

![20210101174602_1](https://user-images.githubusercontent.com/70821082/103443711-d0929600-4c59-11eb-829d-cd0d0a1fc231.jpg)

**Comment by Dwarf-LordPangolin** [comment]
Not quite sure if this is part of the same issue, but the half tile also has collision issues with the player character as well; it's possible to walk through them.

https://gfycat.com/leafypolishedhackee

**Comment by tsunamayo** [comment]
Fixed for 21w03a. @Dwarf-LordPangolin unfortunately that is a different one, it is a long time issue because I am not doing a true capsule check but simply two sphere check. I still need to do further progress on the collision side to get there. Cheers all
