### ISSUE TITLE
[Bug] Hinges are labelled as Rotators in their menu

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3433]
### Short Description of the issue:
Just a small one, the Hinge menu (both block and brick) have "Rotator" as their title and not "Hinge"
![image](https://user-images.githubusercontent.com/27857711/103465992-a8c62f80-4d38-11eb-82c7-7ad5778de33c.png)

### Steps to reproduce the issue:
Hit F any Hinge

### Environment
- Starship EVO version: 20w50a
- Graphics Card: RX580

**Comment by tsunamayo** [comment]
Indeed. Fixed for 21w01a! Cheers
