### ISSUE TITLE
[Bug] Copy paste can paste over existing blocks

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3434]
### Short Description of the issue:
When pasting, the copy paste tool only checks one side of the mirror plane for collisions which can result in blocks and bricks superimposed on each other.

https://i.imgur.com/BZ3RCv1.mp4

### Steps to reproduce the issue:
Follow the steps in the video -
Create a symmetrical component to copy
Place down a mirror plane
Paste the symmetrical component over the mirror plane
Turn off the mirror plane
Delete a brick/block of the component, and see that the pasted selection was pasted twice on one side

### Environment
- Starship EVO version: 20w50a
- Graphics Card: RX 580 8GB

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5760918/output_log.txt)

**Comment by tsunamayo** [comment]
It should be good now!
