### ISSUE TITLE
[BUG] Query gates do not show proper piston max distance

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3435]
### Short Description of the issue:
query gates show a max length of 1m when the piston's max length is set to .5
...

### Steps to reproduce the issue:
hook a piston to a query gate
set max piston length to .5
check query gate
...

### Environment
- Starship EVO version: 20w50a

### Additional information:

https://user-images.githubusercontent.com/56371294/103467408-0728e900-4d0c-11eb-9fea-d9a4d0825bf2.mp4

**Comment by tsunamayo** [comment]
Fixed for 21w03a. Thanks!
