### ISSUE TITLE
[Bug] Very low gravity field on the ringworld

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3436]
### Short Description of the issue:
The gravity field of the ringworld only reaches halfway or roughly ~100m up the wall, when in the past (I'm pretty sure) it reached all the way to the top of the side wall

![image](https://user-images.githubusercontent.com/27857711/103484016-5a219f80-4de3-11eb-9151-2ec0e7e66949.png)
The gravity field only reaches this high up

### Steps to reproduce the issue:
Fly from ground level on the ringworld straight up and check the locomotion mode indicator for when the gravity field changes

### Environment
- Starship EVO version: 20w50a
- Graphics Card: RX580

**Comment by tsunamayo** [comment]
Hi, yes I changed it, does it seems to low as it is? Thats a simple tweak on my side. Thanks

**Comment by ExodistSKY1** [comment]
I think having the gravity height as tall as the walls with the lights would make decent sense, or... possibly as tall as the translucent wall seen in Peach's screenshot

**Comment by tsunamayo** [comment]
Okay fixed for 21w01a. Thanks
