### ISSUE TITLE
[BUG] Invisible blocks, with reliable method to create them

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3438]
### Short Description of the issue:
When placing blocks they will sometimes turn invisible, I have found a way to create them reliably 
...

### Steps to reproduce the issue:
as shown in the video you must take a large ship (i used one of mine but it should work on other ships as long as they are large enough) land the ship on a large platform, dont use a shipyard just drop it onto the platform, you want to make as much lag as possible as it seems to happen more often the lower your frame rate is, then start placing blocks on the platform and on the ship until they turn invisible 
...

### Environment
- Starship EVO version: 20w50a
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:

https://user-images.githubusercontent.com/56371294/103489229-1a9d8800-4dd0-11eb-857e-58d61942eb1e.mp4

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5762315/output_log.txt)
[LCH-32-6153-02.zip](https://github.com/tsunamayo/Starship-EVO/files/5762318/LCH-32-6153-02.zip)

**Comment by tsunamayo** [comment]
Thanks for the test case, the weird thing is you seem to still be at 60fps...

**Comment by tsunamayo** [comment]
@TIKIRobo okay thanks I managed to reproduce a couple of time, I keep you posted. Thanks

**Comment by TIKIRobo** [comment]
Great!

**Comment by tsunamayo** [comment]
@TIKIRobo I dont quite think it is related to collisions. Do you reproduce even when no collision is involved? I managed to reproduce, it seems linked to delete and maybe building on two separated entity successively.

**Comment by TIKIRobo** [comment]
@tsunamayo  I've only had invisible blocks pop up randomly so when they were appearing consistently when two things were touching that made me think collisions were related, I will test when two things are not touching though
