### ISSUE TITLE
[Bug] Blast door/trap door collision issues [20w49a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#3439]
### Short Description of the issue:
Moving parts cannot pass through open doors, and can sometimes pass through closed doors.

### Steps to reproduce the issue:
I think [this bug](https://github.com/tsunamayo/Starship-EVO/issues/2417) might have returned at some point; I've been updating the Kuroshio, and the sliding ramp can no longer pass through the blast door at the bottom even when it's open. It keeps stopping where the door would be when closed, even when it's open.

Even stranger, when I tried replacing the blast door with a trap door, it also acts as if the trap door is always closed, but has no collision on the edge opposite the hinge even when the door is actually closed.

### Environment
- Starship EVO version: 20w49a
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5768900/output_log.txt)

The blueprint [here](https://github.com/tsunamayo/Starship-EVO-Backers-Ships/files/4639545/Kuroshio.-.WIP.zip) should still be the current one, and should have the bug.

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Hi, gotcha let me check this.

**Comment by tsunamayo** [comment]
It should be all good now. thx
