### ISSUE TITLE
[BUG] Copy past anti clipping detection ABSURDELY over zealous

### ISSUE THREAD

**Issue by zorozeenee** [tsunamayo/Starship-EVO#3440]
### Short Description of the issue:

I am attempting to literally copy and paste a single block and cannot do it unless it is on the exterior of the ship or literally nothing is remotely close to it or its on a child entity

What is the point of this absurd anti clipping measure anyways? Weight is still calculated so even if someone can make a super tiny ship with high power or whatever it still will be just as heavy and require just as much power to move, not to mention its weapons will destroy itself if those are clipped as well, as well as being extremely vulnerable to simply being hit once and completely disabled. This anti clipping measure has tons of negative side affects and is trying to solve a problem that is already solved simply by calculating the mass. Please remove it and come up with a better solution much later, it would save everyone a ton of sweat.

### Steps to reproduce the issue:

1. Build a large hollow ship
2. Copy a single hull block
3. attempt to paste the single block on the inside of your ship
4. die of frustration

### Environment
- Starship EVO version: 20w50a
- Graphics Card: Nvidia GTX 1060 SUPER

### Additional information:

Cant upload my output.txt because txt files are not allowed to be uploaded

**Comment by KINGrimson** [comment]
> ### Short Description of the issue:
> I am attempting to literally copy and paste a single block and cannot do it unless it is on the exterior of the ship or literally nothing is remotely close to it or its on a child entity
> 
> What is the point of this absurd anti clipping measure anyways? Weight is still calculated so even if someone can make a super tiny ship with high power or whatever it still will be just as heavy and require just as much power to move, not to mention its weapons will destroy itself if those are clipped as well, as well as being extremely vulnerable to simply being hit once and completely disabled. This anti clipping measure has tons of negative side affects and is trying to solve a problem that is already solved simply by calculating the mass. Please remove it and come up with a better solution much later, it would save everyone a ton of sweat.
> 
> ### Steps to reproduce the issue:
> 1. Build a large hollow ship
> 2. Copy a single hull block
> 3. attempt to paste the single block on the inside of your ship
> 4. die of frustration
> 
> ### Environment
> * Starship EVO version: 20w50a
> * Graphics Card: Nvidia GTX 1060 SUPER
> 
> ### Additional information:
> Cant upload my output.txt because txt files are not allowed to be uploaded

for the output log zip the file then send it

**Comment by tsunamayo** [comment]
@zorozeenee I dont think the output.log is needed, but yes the usual way is to zip it.
Now I didnt had any issue, so the best would be to send me screenshot or a video, and the blueprint so I can try to reproduce.
So I can understand: the copied bricks are not clipping but you cant place them? Or they do clip and you still would like to place them?
I wont restart the debate on clipping. Allowing it now to disable it later on is a really bad idea, as it would trigger much frustrations.
Thanks

**Comment by zorozeenee** [comment]
@tsunamayo Ok here is the video

https://www.youtube.com/watch?v=2D_oVo5_anE&feature=youtu.be&ab_channel=SWINE

**Comment by TIKIRobo** [comment]
This seems to be related to #3324 as in that one I was also unable to paste things inside of my ship and yet I could when I was on the outside of my ship, possibly related to the longer raycast but I don't think this is anti clip as if something is clipping and you try to paste it the parts that are clipping just wont be placed

**Comment by ProPeach** [comment]
This might actually be the same issue as #3359, where seems to be a minimum distance that the player needs to be away from their ship for the placement ghost to appear. I think this was introduced after Tsuna implemented a suggestion for increasing the reach of the player when they copy larger components to make it easier (Which is a great change), but it might have introduced this bug along with it

**Comment by tsunamayo** [comment]
yes I think it might be on of those two (which might be the same too actually). I keep you guys posted.

**Comment by zorozeenee** [comment]
thanks

**Comment by tsunamayo** [comment]
@zorozeenee Okay that one is finally fixed for 21w02c! Thanks
