### ISSUE TITLE
[Bug/Issue] Gatling Turret Safe Firing Detection

### ISSUE THREAD

**Issue by Midge57** [tsunamayo/Starship-EVO#3443]
### Short Description of the issue:

Laser turrets with the Gatling attachment seem to have the same 'line' of detection as normal lasers, despite their significantly higher bullet spread. This means that they will shoot straight through friendly hull and other turrets despite technically being blocked by them.

### Steps to reproduce the issue:

Place a Gatling turret somewhere rear of a ship, have it fire at a target forward of the ship. Gatling will likely shoot the hull of the friendly ship trying to shoot your target.

This might be solved by using a cone of detection equal to the bullet spread

### Environment
- Starship EVO version: 20w50a
- Graphics Card: RTX 3070

### Additional information:

![unknown](https://user-images.githubusercontent.com/33131882/103822147-733a8280-5067-11eb-9345-dbb36209c388.png)
![unknown png(2)](https://user-images.githubusercontent.com/33131882/103822151-76357300-5067-11eb-818d-e90c98b92b98.png)
![unknown png(3)](https://user-images.githubusercontent.com/33131882/103822156-77ff3680-5067-11eb-998c-fc1b0ddb065f.png)
![unknown png(4)](https://user-images.githubusercontent.com/33131882/103822162-79c8fa00-5067-11eb-9d43-6dd1b76b19fa.png)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5778298/output_log.txt)

If you want to test it with my ship, which I've noticed my most extreme case of this issue with:
[Corvette WIP.zip](https://github.com/tsunamayo/Starship-EVO/files/5778301/Corvette.WIP.zip)

**Comment by TIKIRobo** [comment]
Yea I've had this happen a few times to some of my ships, making the "line" of detection into a cone would help a lot

**Comment by 5URG3** [comment]
This is definitely an issue with gatling turrets. Both of these ships suffer from it.

https://steamcommunity.com/sharedfiles/filedetails/?id=2321178619
https://steamcommunity.com/sharedfiles/filedetails/?id=2341224957

Point either ship straight at a target and the ship will probably damage itself with it's gatling turrets.

Regarding gatling barrels, I would personally prefer a significant reduction in damage in return for improved accuracy.

**Comment by tsunamayo** [comment]
Indeed, I only raycast in line for the check. I will fix this and keep you posted.

**Comment by tsunamayo** [comment]
Issue fixed for 21w04b. Thanks
