### ISSUE TITLE
Teleportation Teleports a bit too much?

### ISSUE THREAD

**Issue by NoxyNixie** [tsunamayo/Starship-EVO#345]
I am somewhat confused as to what happened here but I managed to teleport all entities to a single location with the exception of one.

I was flying around visiting other stars with my little craft "How Fast Can I Go" when I decided I wanted to do something else so wanted to go back to the Torus we are all so familiar with.

Even Though this video isn't how it happened the first time it clearly shows what happened:
https://youtu.be/uVk0L373ZaQ

I did have various crashes related to the holomap while out exploring but I don't think they would have caused this to happen. If they did, I already reported my particular holomap crash here: #318 .

Here is a save file in which this error already occurred but I'm not certain this will help at all in finding the culprit.

[Save_Data.zip](https://github.com/tsunamayo/Skywanderers/files/1437745/Save_Data.zip)

Because Skywanderers overwrites its output_log.txt I don't have the output_log.txt of the first occurrence of this bug in this world however I do have a later one where I managed reproduce it: 
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1437772/output_log.txt)

**Comment by tsunamayo** [comment]
Thanks, very interesting test case I will fix it!

**Comment by EthanNar** [comment]
still having the same issue with most recent Experimental build.
