### ISSUE TITLE
Turret Linking 'locks' Game

### ISSUE THREAD

**Issue by AnubisEvo** [tsunamayo/Starship-EVO#3450]
### Short Description of the issue:

When linking a turret up to a computer, using a Rotator (brick) and a Hinge (brick) all interaction with the entity (both parent and child) are lost until client is closed and opened again. 

### Steps to reproduce the issue:

In the attached Blueprint, using the linking tool:

1. connect the red turret computer to the rotator painted red 
2. link the computer to the hinge painted red on the outside of the hull

The ability to use the "F" key on any of the blocks is lost and none are able to be deleted. Nothing can be added after this is done either until the client is completely reset.

### Environment
- Starship EVO version: early-access 20w49a
- Graphics Card: GeForce GTX 1070

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5781051/output_log.txt)

[Type-26 Wraith.zip](https://github.com/tsunamayo/Starship-EVO/files/5781070/Type-26.Wraith.zip)

**Comment by tsunamayo** [comment]
@AnubisEvo Hi, this turret is working fine on my side. You also have to link a weapon so the turret understand how to point. Do you get this issue all the time? Could you try in the latest experimental build?
Thanks

**Comment by AnubisEvo** [comment]
Yeah, The issue was that if I connected it up before a weapon or camera was attached to that setup exactly, then it wouldn't allow me to put a weapon on or camera on it until I relaunched the game. I found the simple solution for me was to do so before linking them up but wanted to post this here in case you were able to see the same thing. 

I'll give it a shot in the experimental build tomorrow and then post my results here once I can say if it happens again or not.

**Comment by tsunamayo** [comment]
@AnubisEvo yes, I was not able to reproduce that issue.

**Comment by tsunamayo** [comment]
@AnubisEvo I cant reproduce in 20w49a too...

**Comment by AnubisEvo** [comment]
I tried it in the experimental version and it worked as intended and now it works as intended as well in the stable version. I really am not sure what was happening since I changed nothing. If I'm able to get it again at some point then I'll open up a new one and hopefully get some video of it for you.

**Comment by tsunamayo** [comment]
@AnubisEvo gotcha, thanks for the update.
