### ISSUE TITLE
[Bug] turrets don't move

### ISSUE THREAD

**Issue by quelonio** [tsunamayo/Starship-EVO#3451]
whenever i make a turret it refuses to move, no matter the way i make it, i don't know what causes this to happen nor how to replicate it.
[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/5783717/output_log.zip)

**Comment by cloudrambler** [comment]
@quelonio Hi, I just made a test turret and it would not do anything. I tried adding a power block and now the turret works fine. I don't think power used to be a requirement for turrets, but it now seems to be the case.

**Comment by tsunamayo** [comment]
@quelonio Hi, could you send me your blueprint so I can investigate? @cloudrambler might be right on your issue. Thanks
