### ISSUE TITLE
[Bug?] No menu for planets/moons in system map [21w01a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#3454]
### Short Description of the issue:
Bookmark/plot course menu not appearing for planets/moons in the system map view.

### Steps to reproduce the issue:
Open the **awesome** new in-system map, mouse over a planet, left-click. Compare with doing the same for a station.

I'm not actually sure if this is a bug, or just how it's supposed to be since planets are currently placeholders.

### Environment
- Starship EVO version: 21w01a
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
Left-clicking p1s2 does not move the menu to it; it stays at the last selected station.
![20210108013429_1](https://user-images.githubusercontent.com/33041786/103987562-4ca54600-5152-11eb-80f4-d5681976a9cb.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5785801/output_log.txt)

The map is really cool. 😃

**Comment by tsunamayo** [comment]
Yep I still need to add waypoint for planet. I will close this as it is still wip, but will do it soon... Cheers
