### ISSUE TITLE
Glitchy Loading After Update [21w01a]

### ISSUE THREAD

**Issue by PFSCommissar** [tsunamayo/Starship-EVO#3457]
### Short Description of the issue:

After downloading the update, I loaded in a previously saved world, only to find that my character and all the ships around him had been moved very far away from their original location. I tried reloading the world only to load into blackness and have an empty inventory. I tried restarting the game and loaded in, but this time I was without any ships and far farther from the planet. 

I tried creating a new world to see if that was the issue. Reloaded that world to blackness again. Then restarted the game only to find myself incredibly far out with an empty inventory. 

![image](https://user-images.githubusercontent.com/67161181/104052881-58c3ee80-51b8-11eb-99a8-93d74f7588e0.png)

...

### Steps to reproduce the issue:

Create World, exit and reload, or restart game and reload.
...

### Environment
- Starship EVO version: 21w01a
- Graphics Card: Geforce GTX

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5788899/output_log.txt)

**Comment by cloudrambler** [comment]
I just had a similar experience.

1st load I was in the last position but the ringworld was gone, leaving the starting building and ships behind.
2nd load (from title into a different world) left me with zero background or foreground, just menu.
3rd load (from desktop) put me inside the star, again with the ringworld not where it was.

**Comment by ArnoldHudson** [comment]
I have experienced the same issue as well.

**Comment by tsunamayo** [comment]
I think there might be couple issue at play. 
1) As a starter, like explained in the patch note this update refactored the way planet are generated, so you will need to create a new world and move your build over there. <-- Not an issue
2) Can I confirm that you have issue when creating a new character? Just launch the game, create a new character. (no quit to title) <-- Issue nb1, but I cant reproduce
3) Quit to title is indeed broken. <-- Issue nb2.
Thanks

**Comment by PFSCommissar** [comment]
The issue is the same regardless of if i load an old world or create a new character.
If quit to title is broken, that may be the issue. I created a new character and quit to title and it was black upon return. However, If I quit to desktop and then reload the same world, there's still a problem as I am put out extremely far from the planet.

**Comment by tsunamayo** [comment]
@PFSCommissar maybe it was the quit to title bug that corrupted your save!

**Comment by PFSCommissar** [comment]
I think that may be the case. I just tried a new character, quit to desktop, and reloaded and it works.
