### ISSUE TITLE
[BUG] System map problems

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#3458]
The new system map seems to load correctly the first time, then subsequently loads incorrectly. See screenshot.

Also the star images in the system map are sometimes a different colour to the game world.

### Environment
- Starship EVO version: 21w01a
- Graphics Card: GTX1070

### Additional information:

![20210108193519_1](https://user-images.githubusercontent.com/70821082/104056851-0a7b1380-51e9-11eb-9267-8cfab3fea112.jpg)

**Comment by ArnoldHudson** [comment]
I have experienced a similar issue in which the incorrect load occurs to the background of the System Map (in the image, all the visible stars are blank )

**Comment by tsunamayo** [comment]
Fixed for 21w02b. Thanks!
