### ISSUE TITLE
Problem with fps

### ISSUE THREAD

**Issue by Caribou07** [tsunamayo/Starship-EVO#3460]
### Short Description of the issue:
When I play the game is at 3 fps and I pass through the ground.
In the menu the game work normally.
### Steps to reproduce the issue:
start a world
...

### Environment
- Starship EVO version:20w49a 
- Graphics Card: GTX 1050

### Additional information:
Yesterday it's work great.
_(Screenshots, Videos, Error logs, Related issues)_
![capture](https://user-images.githubusercontent.com/77211431/104108528-a9753d80-52c5-11eb-8bdb-37578212d6cb.png)
Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by matejkar** [comment]
now i have a bit better gpu then u, and i gotta say i also get fps drops, but for a reason, since im building a 800m long ship

**Comment by tsunamayo** [comment]
@Caribou07 Your GFX should be good enough. Could you join the output.log file so I can investigate? What is your CPU and memory? Thanks

**Comment by Caribou07** [comment]
My CPU is an intel core i3 8th Gen and i have 8Go Ram.
the output.log :
[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/5792443/output_log.zip)

**Comment by tsunamayo** [comment]
@Caribou07 Hi, thanks for sending the info. Did you had this from the start or is happening only recently? Thanks

**Comment by Sebateses** [comment]
This may or may not help but I get the same issue sometimes.
I backed up all my blueprints and save files from the appdata folder then deleted them and started a fresh character. Just make sure you back up your files dont wanna lose any work you've done.
After that it went back to running smooth.

**Comment by Caribou07** [comment]
@tsunamayo the game do that recently.

**Comment by Caribou07** [comment]
Now i download the beta version and the game work's normally

**Comment by tsunamayo** [comment]
@Caribou07 okay good to now.
