### ISSUE TITLE
[BUG] turrets still shooting own ship

### ISSUE THREAD

**Issue by matejkar** [tsunamayo/Starship-EVO#3461]
### Short Description of the issue:
As i described in one of my previous issues, the turrets on ships will shoot at the enemy ship even if they dont have line of fire. This doesn't happen always for turrets on the complete opposite side of the ship, but only for turrets that are close to having line of fire to the target. Target mode was spaceship target.
...

### Steps to reproduce the issue:
Get a ship with turrets, spawn a hostile, target it and watch the turrets damage your own ship
...

### Environment
- Starship EVO version: 21w01a
- Graphics Card: GTX 1060ti 6GB

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5791963/output_log.txt)
![20210110000705_1](https://user-images.githubusercontent.com/69653738/104110531-e3037400-52d8-11eb-929c-3bf63e98c2fd.jpg)
![20210110000711_1](https://user-images.githubusercontent.com/69653738/104110532-e4cd3780-52d8-11eb-8bcc-71df21fd64de.jpg)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by matejkar** [comment]
[Kraftwerk - class super dreadnought.zip](https://github.com/tsunamayo/Starship-EVO/files/5791968/Kraftwerk.-.class.super.dreadnought.zip) this is the blueprint, now the ship is massive, being over 800m long, but its the best ship to see dozens and dozens of turrets shoot at it

**Comment by tsunamayo** [comment]
@matejkar hi, do you get the same issue with a smaller ship? Thanks

**Comment by matejkar** [comment]
@tsunamayo yes i was getting that issue on all my ships i released in the last few months, those being 
[Resolution - class frigate.zip](https://github.com/tsunamayo/Starship-EVO/files/5792416/Resolution.-.class.frigate.zip)
[Supernova - class command cruiser.zip](https://github.com/tsunamayo/Starship-EVO/files/5792417/Supernova.-.class.command.cruiser.zip)
[Broadsword - class patrol frigate.zip](https://github.com/tsunamayo/Starship-EVO/files/5792418/Broadsword.-.class.patrol.frigate.zip)
[Equalizer - class heavy cruiser mk.2.zip](https://github.com/tsunamayo/Starship-EVO/files/5792420/Equalizer.-.class.heavy.cruiser.mk.2.zip)
here's a few or my recent ones, now i didn't really see that happen on the broadsword class cuz i think there are no large angled surfaces turrets could mistake for just space and ignore it.

**Comment by matejkar** [comment]
@tsunamayo now i know you don't like ships too large, so my best option would be you test it out on the resolution class, as its built similarly to a star trek federation ship, and you can see the rear 2 gatling guns shoot at its engine array in front

**Comment by matejkar** [comment]
![20210110111412_1](https://user-images.githubusercontent.com/69653738/104120356-7fa82f00-5336-11eb-9189-c90b1cf771e7.jpg)here's and example of my ship shooting a target, and the guns shooting now or auto turret mode
![20210110111417_1](https://user-images.githubusercontent.com/69653738/104120369-8fc00e80-5336-11eb-85bc-82bcbe988589.jpg)
and here you can see the bottom guns not shooting, so the guns don't shoot straight trough the ship

**Comment by 5URG3** [comment]
This seems to be a common issue with gatling turrets. Both of these ships suffer from it.

https://steamcommunity.com/sharedfiles/filedetails/?id=2321178619
https://steamcommunity.com/sharedfiles/filedetails/?id=2341224957

Point either ship straight at a target and the ship will probably damage itself with it's gatling turrets.

**Comment by tsunamayo** [comment]
@5URG3 @matejkar okay I keep you posted guy. Amazing ships as always @5URG3!

**Comment by matejkar** [comment]
@5URG3 but my ships had that issue with recoil barrels on turrets, so i don't think its limited to a barrel type

**Comment by tsunamayo** [comment]
There is dispersion on every laser, just on gatling it is much larger, so the effect will be more visible.

**Comment by tsunamayo** [comment]
@5URG3 @matejkar Issue fixed for 21w04b. I will push the patch asap. Thanks for your patience!
