### ISSUE TITLE
[Bug] Objects floating in water "pushed" to shore [21w01a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#3463]
### Short Description of the issue:
Objects left in the water are pushed out of it.

### Steps to reproduce the issue:
Land a ship in the water, then exit it. Even if it starts out perfectly still, it will be propelled out of the water.

### Environment
- Starship EVO version: 21w01a
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
https://gfycat.com/piercingamusedharborporpoise

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5793402/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, indeed I fixed an issue on the way the force was applied, it will now also impact torque. So we still get some wonky behaviour for flat objects, they will move quite fast underwater seemingly randomly. I dont think it is unrealistic as I see that a lot playing with the kid in the bath ;). I think it is way too strong though, as I still need to implement some drag which is huge underwater.
For 21w02b. Thanks!
