### ISSUE TITLE
[BUG] quit to tile does weird things

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3465]
### Short Description of the issue:
If you quit to title and then reopen the world you were just in it will be completely black and all ships will be deleted, the only things you will be able to see are your hotbar and the outlines of any blocks you place, if you quit the game and then rejoin the world it will be completely empty except for the skybox
...

### Steps to reproduce the issue:
hit quit to title then rejoin world 
then quit game and then rejoin the world
...

### Environment
- Starship EVO version: 21w02a
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5793764/output_log.txt)

**Comment by tsunamayo** [comment]
Yes it is fixed for 21w02b.Thanks!
