### ISSUE TITLE
[Bug] NPC-Ship bugged into my ship and broke my camera

### ISSUE THREAD

**Issue by FunkyStuff99** [tsunamayo/Starship-EVO#3467]
### Short Description of the issue:

I auto-piloted my ship to a landing spot on a space station, and when I logged in again, a npc ship tried to park on the same spot, bugging into my ship and locking my camera.

### Steps to reproduce the issue:

One could try to let the auto-pilot park on a landing pad on the Space-Station 1. Then just wait and see if a NPC ship tries to land there. When it happens, look at the pilot (that locked my camera).

### Environment
- Starship EVO version: 20w49a
- Graphics Card: GTX 1660 Ti

### Additional information:

![20210111114547_1](https://user-images.githubusercontent.com/69148659/104172181-1e4e9180-5404-11eb-8ca8-bf0490c8d47e.jpg)
![20210111114557_1](https://user-images.githubusercontent.com/69148659/104172196-23abdc00-5404-11eb-88b8-f7ceefe1b1eb.jpg)

The last image is what I meant regarding the "camera lock". My view was locked, but I could move my mouse, which seems to move the npc and the wireframe of the cockpit.

[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/5795311/output_log.zip)

**Comment by tsunamayo** [comment]
@FunkyStuff99 Hi, actually this issues was already fixed, but the fix is still in experimental. Thanks for reporting it! Cheers
