### ISSUE TITLE
After most recent update game crashes 100% of time on load 

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#3468]
### Short Description of the issue:
Game crashes in the loading screen 
...

### Steps to reproduce the issue:
>Attempt to load an existing character save
>experience crash
...

### Environment
- Starship EVO version:  21w02b
- Graphics Card:  RTX 3080 FE

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5799628/output_log.txt)

[Player.zip](https://github.com/tsunamayo/Starship-EVO/files/5799629/Player.zip)

![image](https://user-images.githubusercontent.com/14081996/104265665-f2063580-5442-11eb-9cde-7f21bfb23e81.png)

Please also include the `output_log.txt` or `Player.log` file starting from 21w02a. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by Tomatart** [comment]
I can confirm the game crashes everytime since update.
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5799634/output_log.txt)

**Comment by pinesh** [comment]
This seems to only be affecting existing characters, new chars seem to load

**Comment by Dwarf-LordPangolin** [comment]
Same result. Interestingly, the most recent time I tried to load a pre-existing character, it didn't CTD, but instead got stuck loading infinitely.

Log from infinite load with an old character:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/5799687/Player.log)

Log from successfully creating a new character:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/5799667/Player.log)

**Comment by tsunamayo** [comment]
Okay weird, let me check!

**Comment by tsunamayo** [comment]
by the look of it seems to be linked to player made shipyard. I will fix this and repush asap!

**Comment by tsunamayo** [comment]
The new build is up with the fix. Sorry for the miss, I didnt had any shipyard in my save... Cheers

**Comment by Dwarf-LordPangolin** [comment]
Awesome! That was fast.
