### ISSUE TITLE
[BUG] Delete reactor/warp drive

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#3469]
### Short Description of the issue:
I can't delete blocks such as reactor, warp drive, shield. But the screen changes to delete mode, with red cross and red glow. When I try to delete another object, it returns to normal again.
...

### Steps to reproduce the issue:
Press de right mouse buttom on reactor or warpdrive.
...

### Environment
- Starship EVO version: normal version
- Graphics Card: gtx 1660
- cpu i7-3770
- ram: 16Gb (ddr3)

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![image](https://user-images.githubusercontent.com/73253472/104362545-b165f500-54f2-11eb-8e6e-ebbdd81e34f7.png)

video showing what happens when I try do delete reactor*
https://youtu.be/yNZpdYe-LKY

Please also include the `output_log.txt` or `Player.log` file starting from 21w02a. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5804348/output_log.txt)
[[ULTY] Gávea Dropship 03.zip](https://github.com/tsunamayo/Starship-EVO/files/5804350/ULTY.Gavea.Dropship.03.zip)

`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hi, I cant reproduce that bug with your blueprint... In any case I added a fail safe so it wont trigger any issue (for 21w02c). Cheers
