### ISSUE TITLE
[SUGGESTION] Change brick stretch-tech to base 24

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#3472]
There are many instances where the desired construction form is impossible to build because no permutation of proportions will allow certain edges to align neatly. I believe that the base 16 is not ideal because it does not divide well into the common geometric factors (1, 2, 3, 4) which are the basis of setting out controlled forms.

Expanding the base length to 24 would allow far more subdivision types, allowing the bricks to align in more ways to close off surface intersections.

This is only required for bricks and does not need to be done for blocks.

I know this is a long shot request, but it would add a lot of value (IMO), especially for generating pseudo smooth surfaces.

**Comment by tsunamayo** [comment]
@cloudrambler Hi, unfortunately it is not possible as it is a hard limit on the way block are packed in memory... Cheers
