### ISSUE TITLE
[Bug] Huge block artefacts appearing randomly

### ISSUE THREAD

**Issue by Facest4b** [tsunamayo/Starship-EVO#3473]
### Short Description of the issue:

Randomly, placed blocks will have other blocks appear on top of them when viewed at certain angles. The phantom blocks will be extremely distorted. After this happens for the first time, huge clusters of distorted blocks appear very far away, close to the walls of the ring. The clusters disappear at most viewing angles and can't be inspected close up as they disappear, even in camera mode.

I loaded in a community made ship and it was completely absorbed in these phantom block clusters. I tried unspawning the ship, but the clusters latched onto my character and moved with me. Reloading the save removed the artefacts, but they came back after following the same steps.

### Environment
- Starship EVO version: 20w49a
- Graphics Card: RTX 2070 Super

### Additional information:

https://www.youtube.com/watch?v=EigYQQnm5Uk

[output_log - Copy.zip](https://github.com/tsunamayo/Starship-EVO/files/5805346/output_log.-.Copy.zip)

**Comment by tsunamayo** [comment]
Hi, woa it look nasty... What ship was it?
I keep you posted.

**Comment by Facest4b** [comment]
> Hi, woa it look nasty... What ship was it?
> I keep you posted.

It was this ship:
https://steamcommunity.com/sharedfiles/filedetails/?id=2208617390&searchtext=yt-2400

Thanks

**Comment by cloudrambler** [comment]
I hade a similar thing after blasting up the starting zone building 2. That was a few weeks ago and probably a new world. Cannot be certain. But the large black blocks grew as I dished out more damage to the structure, and also changes as I moved relative to them.

**Comment by tsunamayo** [comment]
@Facest4b did you hit another ship with weapon like @cloudrambler ? Thanks

**Comment by Facest4b** [comment]
> @Facest4b did you hit another ship with weapon like @cloudrambler ? Thanks

No, the effect occured immediately after spawning the ship.

**Comment by tsunamayo** [comment]
@Facest4b I cant reproduce. Do you get this often? Thanks
