### ISSUE TITLE
Sub entities causing frame drop

### ISSUE THREAD

**Issue by Kranyolsu** [tsunamayo/Starship-EVO#3477]
### Short Description of the issue:
Moving sub entities seems to be causing fairly significant framerate drops. Spawning an entity with a large number of sub entities seems to cause a similar problem.

### Steps to reproduce the issue:
Move a sub entity (rail, hinge, etc.)

### Environment
- Starship EVO version: 21w02c
- Graphics Card: GeForce GTX 1060 6GB

### Additional information:
GPU, CPU, and Memory where running stable at around 50%
_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` or `Player.log` file starting from 21w02a. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/5823979/Player.log)
Output log was too big even when compressed (33269KB).  I can provide a truncated version but would need to know what is important.

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
I do not own the designs but tested on these from the workshop:
https://steamcommunity.com/sharedfiles/filedetails/?id=2357502383
https://steamcommunity.com/sharedfiles/filedetails/?id=2299474053
https://steamcommunity.com/sharedfiles/filedetails/?id=2360141377
This last one did NOT seem to trigger any issues:
https://steamcommunity.com/sharedfiles/filedetails/?id=2360141377

**Comment by tsunamayo** [comment]
Hi, thanks for booking the issue. Do you think it is a regression from last update - or something you noticed since a bit of time?
Thanks

**Comment by tsunamayo** [comment]
@Kranyolsu I tried a few ship and didnt had any issue. Could you send me your character folder (zip it before)? It seems you have issues related to rendering. Did you unspawned ship too?

**Comment by Kranyolsu** [comment]
It did happen in 21w02b but it seems more frequent in this update.  As far as severity, the drop in framerate is worse than what I would get on creations 5 times the size in 20w50a.  Just spawning the first workshop item I sent you dropped me to 2 fps.

**Comment by Kranyolsu** [comment]
[Kran.zip](https://github.com/tsunamayo/Starship-EVO/files/5824025/Kran.zip)
I did try unspawning the ships but the frame drop only mildly improved.  The strangest part is loading back into the world after clears the problem until I move a rail again.

**Comment by tsunamayo** [comment]
@Kranyolsu thanks, could you tell me what you are moving? The frame rate drop because there is tons of error being written to the log file.

**Comment by Kranyolsu** [comment]
Sorry about the response time. It was 3am here when I wrote my last post. The most consistent trigger I could find was from the second workshop item I sent.  While flying the ship, any time I press [1] or [2] to open/close the window shutters I would get the frame drop.

**Comment by tsunamayo** [comment]
@Kranyolsu I cant reproduce any of this. I really would like to know how that issue happened. Could you:
1) load the game
2) Do a copy of the player.log!
3) move the rail
4) Send me the player.log and the copy (the one before you touched anything!)

Thanks!

**Comment by Kranyolsu** [comment]
I no longer can reproduce the error either.  Only change since yesterday is an update to my graphics driver.  I'll do a bit more stress testing and see if I can reproduce it, if not, then I will close this thread before I go to bed tonight.  Sorry to have bothered you with this.

**Comment by Kranyolsu** [comment]
Ok, so I recreated it by setting a lightcruse target through the new system map, pointing at it, then starting the autopilot.  During the trip I moved a hinge while looking at the ship in third person which instantly dropped me from 50 fps to 15.  I then canceled lightcruse and despawned the ship which brought me back to 50 fps.  I then spawned the same design (first one I sent you) and it dropped my framerate to 2.  I don't know what to make of that but here is the pre-glitch log: 
[PlayerLogPre.zip](https://github.com/tsunamayo/Starship-EVO/files/5825493/PlayerLogPre.zip)
and here is the post 2 fps log:
[PlayerLogPost.zip](https://github.com/tsunamayo/Starship-EVO/files/5825494/PlayerLogPost.zip)

**Comment by Kranyolsu** [comment]
Oh and here is the log after quitting the game:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/5825501/Player.log)

**Comment by Kranyolsu** [comment]
A bit more testing seems to tie it to any use of the autopilot.

**Comment by tsunamayo** [comment]
@Kranyolsu Okay I will try to reproduce. Do you have issues with any ship and autopilot? Which ship did you used? Weirdly it seems that you have the graphic issue even before the drop.

**Comment by tsunamayo** [comment]
I think I was able to somehow reproduce, when selecting another target when the autopilot is active. I keep you posted, not 100% sure it is the reason of your framerate drop yet...

**Comment by Kranyolsu** [comment]
The main ships I used for testing are the ones I sent before but it does seem to apply to any ship with a moving part.  As far as having a graphical issue before the frame drop, I don't know what could be causing it.  I may have to do a clean install if you can't reproduce it.

**Comment by tsunamayo** [comment]
@Kranyolsu I have the issue for 21w03a. The issue was selecting a station and linked to the tracking cam. Now I cant be sure 100% it was your issue as I had no problem with children entity lag, but if this persist when the release is out please ping me! Cheers
