### ISSUE TITLE
[Suggestion] 2x2 version of the holomap

### ISSUE THREAD

**Issue by StarrKiss** [tsunamayo/Starship-EVO#3479]
As it is, the 1x1 holomap cannot be placed with symmetry on a ship- e.g, as the centerpiece of a meeting table or some other prominent position. it would be very cool to add a 2x2 version so that it can be placed with symmetry.

**Comment by Kaiser-Indrasil** [comment]
You don't need that.
Instead, you can offset bricks with tiles.
Holoprojector will have adjustable projection size in the future, but the base will remain the same for the sake of simplicity, I suppose.

**Comment by tsunamayo** [comment]
Yes I would prefer you guy use offset. I will also add the size setting! Cheers
