### ISSUE TITLE
[Bug] Game suddenly runs capped at 60fps

### ISSUE THREAD

**Issue by Facest4b** [tsunamayo/Starship-EVO#3480]
### Short Description of the issue:

So randomly, my game started running capped at 60fps. Earlier today it was running fine at 144fps with vsync, but upon reopening later on, it would only run at 60fps. I haven't changed any settings or updated my graphics drivers, so I really don't know the cause of this. I get this on existing saved as well as new saves. Reloading and restarting doesn't fix it, neither does switching to different resolutions and then back to mine.

### Environment
- Starship EVO version: 20w49a
- Graphics Card: RTX 2070 Super

### Additional information:

[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/5824735/output_log.zip)

**Comment by Facest4b** [comment]
Ok so I tried messing about with the graphics settings more and reinstalling the game but nothing worked.

I switched to the experimental build and this seems to have fixed the issue.

**Comment by tsunamayo** [comment]
@Facest4b I see. I will add a better setting at one point, so you can run at full speed or half speed. Thanks
