### ISSUE TITLE
FPS Drop when toggling flight mode

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#3481]
### Short Description of the issue:
Was testing the new walking sounds as well as just getting a POV on some parts of a larger ship - immediately after pressing [J] to toggle between walking and anti-grav, I notice my FPS dropped by about 5 for maybe 5 to 10 seconds but then go back to 60 and stay that way until I press [J] again. The larger ship itself doesn't cause any FPS issues whatsoever unless I press [J]

{This is taking place within the Torus' gravity field)
...

### Environment
- Starship EVO version: 21w02c
- Graphics Card: GTX 970

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5825612/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, I think ProPeach reported that one, I didnt had time to investigate  yet... I keep you posted.

**Comment by tsunamayo** [comment]
It was fixed!
