### ISSUE TITLE
Sudden and remaining Lag issue

### ISSUE THREAD

**Issue by Junosato** [tsunamayo/Starship-EVO#3482]
### Short Description of the issue:

Game started lagging alot yesterday while I was building solid hull mockups to seek for new designs to use, no Child entitys were produced. Deleted alot of things, issue remained.

Made a new world, game still lagging.
GPU seems unphazed however.

### Steps to reproduce the issue:

Unknown.

### Environment
- Starship EVO version: 20w49a
- Graphics Card: NVIDIA GeForce RTX 2060

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/5826343/output_log.zip)

**Comment by tsunamayo** [comment]
@Junosato Not sure, you are playing on the old version. You can try to use the Experimental branch to see if the issue remains (and keep me posted!) Thanks

**Comment by Swiggzon** [comment]
hey, i just started having this problem with 20W49a, tried experimental branch and it runs smoothly. i also had severe lag even on new worlds with nothing built in. not sure if there was any small patches released last night as my issue started today, but experimental seems to work fine
