### ISSUE TITLE
BUG(s) Multiplayer unplayable

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Starship-EVO#3484]
### Short Description of the issue:

Multiplayer is not playable atm.

### Steps to reproduce the issue:

We wanted to play MP but in 80%, we got an infinite loadingscreen. 
The two times that the server join worked, we each had severe bugs and had to quit the game.

The first time I was able to join after numerous unsuccessful attempts, I was unable to place a build block, (only on the Torus terrain)
The second time he was able to join me after numerous attempts, he had the same problem and when I spawned a small ship it was invisible to the client and the server crashed a short moment later.

We used the Hamachi client as always, but so far the bugs have never been so bad that the game becomes unplayable if you accept regular reboots. Usually we could always join the other without any problems.

The last time we tested the multiplayer, it was several months ago.

### Environment
- Starship EVO version: 21w02c
- Graphics Card: gtx1070 mobile

### Additional information:

Some of my logs were lost during the new installations. However, there should be the information about the last attempst, including the second one when the server crashed.

**My Logs**
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/5832579/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/5832580/Player-prev.log)

**Logs of my Friend:**
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5832640/output_log.txt)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/5832641/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/5832642/Player-prev.log)

**Comment by tsunamayo** [comment]
@Battlepixel Thanks for the report. How big where your world? Could you send me your world then could you try it with a blank world? I did a netcode switch so I could upgrade Unity. It was fine for my test, and I fixed an issue with player disappearing inside ships. I never used Hamachi, I dont know if it could produce some issues. 
If you are willing to help me I am willing to do a specific build using Steam network, to see if that improve the connectivity. Thanks

**Comment by Kaiser-Indrasil** [comment]
I can help you with the multiplayer, Tsuna. Got a port forwarded, so no Hamachi is needed but since it's Steam, I think it won't be needed this time.

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil yeah why not thanks a lot for offering your help, but before spending time on that I want to be sure I am reproducing the same issues, there is quite a few issues in the log I didnt had during my test, so I need to understand what they did and I didnt during my test!
@Battlepixel When the client was still loading did you touch something or fly something?

**Comment by Battlepixel** [comment]
After the first attempst were not succesfull, we tried it with empty new worlds.
And no, to avoid errors, we diddnt move around much or do anything, while the other tried to join.

**Comment by tsunamayo** [comment]
@Battlepixel Hi, so I have finally made some fixes for 22w04a. I think we will still find a lot of issues but I was able to connect, build, see npcs ship moving, fly and spawn ships. Please book any issue you might find!
Thanks
