### ISSUE TITLE
Feature request: Multiple active symmetry planes

### ISSUE THREAD

**Issue by ItsCrusade** [tsunamayo/Starship-EVO#3485]
Hello, I'd like to request an update to the symmetry feature - having multiple active planes

Large projects that are able to take advantage of multiple mirror planes will be able to be created at a faster rate - with more accuracy.

See below for my current source of pain.
![Starship_EVO_9RjVxUIRYe](https://user-images.githubusercontent.com/64144395/104975037-a7da1100-5a4d-11eb-8fab-ff67fedf3fa0.jpg)

732x732 circle for the saucer section of a ship.

Thank you for your consideration! :)

**Comment by tsunamayo** [comment]
Hi, thanks I will close that one as it is a much requested feature and on the to-do list (not short term though). Thanks

**Comment by ItsCrusade** [comment]
Hey!

Awesome, thank you! :)
