### ISSUE TITLE
Enable faster use of Copy/Paste

### ISSUE THREAD

**Issue by sugardose** [tsunamayo/Starship-EVO#3487]
### Short Description of the issue:
Copy paste can be a bit cumbersome. If I am building a ship with lots of repeated groups of blocks, it is hard to iterate between all the different ones.

### Suggestion:
Allow making a copy and saving the copy as a block that can be added in the toolbelt or somewhere else?

**Comment by tsunamayo** [comment]
Hi, yes it is a valid request, on my copy/paste to do list I want to add clipboard instance as item (ie you drag several copy/paste tool in your item bar, each of them will have their own clipboard, just like the paint tool), and an export as prefab. Cheers

**Comment by tsunamayo** [comment]
We now have prefabs. Thanks
