### ISSUE TITLE
Allow precise UP/DOWN alignment when pasting

### ISSUE THREAD

**Issue by sugardose** [tsunamayo/Starship-EVO#3488]
### Short Description of the issue:
When pasting one can use W,S,A,D for sides precise alignment. But one cannot use UP/DOWN.

### Suggestion:
Allow using UP/DOWN (Q/E ?) for precise alignment.

**Comment by tsunamayo** [comment]
Okay could you please show me how you are using the copy/paste tool, with a screenshot of what your are copying? In my mind you are supposed to build stuff that connect to the floor to not that float in the air. Thanks!
