### ISSUE TITLE
Allow exporting/importing ship blueprints to a known format

### ISSUE THREAD

**Issue by sugardose** [tsunamayo/Starship-EVO#3489]
### Short Description of the issue:
I am unable to automate my ship creation. Sometimes I rather automate creating ships by writing code to do it. There is no import/export methods to known file formats that allow doing this.

### Suggestion:
Allow exporting/importing a ship blueprint to a known file format. PROTO, JSON, XML, other?

**Comment by tsunamayo** [comment]
Hi, I understand the request but the problem is the save format is constantly evolving, that would be too much dev time to maintain at this stage for such a small niche use. I guess you want to create perfect shape of massive size? Anyway maybe long term. Thanks!

**Comment by sugardose** [comment]
Perhaps only allow import/export for hull blocks.  This would keep complexity for maintenance small. The aim was not so much for massive ship, but for complex/repetitive shapes.

**Comment by tsunamayo** [comment]
I think a better way to do this would be with copy/paste being saved as prefab, and being shareable with Steam Workshop. What you do think?

**Comment by Kaiser-Indrasil** [comment]
I've always wanted to just save the copy-pasted prefab as a separate entity and upload it to Workshop. It would streamline many workflows, like installing 3rd party turrets for example.

**Comment by sugardose** [comment]
oh btw, not at all wanting to be pushy =) I think this game is great and is heading places. Just adding food for though. Using an existing serialization process to export prefabs is a good way of avoiding complex maintenance for the evolving development. And it should be the way you are heading anyway. Proto3 for instance offers good support for this, and is already used by some games.
That being said, I am happy to prototype this for you as an experiment for this game. I don't need to be payed cause I have a good day job, I do it for fun.
