### ISSUE TITLE
[SUGGESTION] Copy/Paste Toolbox UI

### ISSUE THREAD

**Issue by nokturnihs** [tsunamayo/Starship-EVO#3490]
So @tsunamayo I know that this is probably down in your list but had some ideas related to copy/paste that might be cool for you to consider as you build out the clipboard tool in the future.

So the idea is this, when you have the clipboard in hand but not holding down left or right mouse buttons, a small UI element shows up in a corner of your screen which you can navigate using the rotate buttons and "check/unchecked" using left mouse or middle mouse(?)

A couple thoughts I had for it could be (not sure if all of this is even possible but... )

Modes:
Clipping tool: (when this is the highlighted ui element the left mouse button clips, right mouse hold to clear - current native functions)
eraser tool: (when this is the highlighted ui element use the left mouse to highlight an area to "erase" - last saved erased area is saved to the clipboard and if they right click and hold it will undo as long as they can re-align it - that's on them)
Paint stripper: (left click to highlight an area and reset all paint values to their default on release)

Clipping options: these are checked unchecked toggle options
Store to library: when this is checked and something is captured in the clipboard a ui dialog will appear to finalize the capture to give it a name (and maybe category or label for organization later on)
load from library: left click to open up the library UI and select the saved clipping to your clip - right click to clear selection
paint stripping: if checked any clipped areas won't be saved with their colors
Clip decals: copy any decals into the clipboard in the highlighted area
Clip child entities: if checked copies child entities
Clip logic: if checked copies logic connections
Mirror mode: if checked will override the mirror mode tool to provide an accurate mirror of the clipped area when pasting from the clipboard

After reading some other suggestions and things I know you have plans for some of these - this is just a suggestion for making a user-friendly UI and keeping multiple useful functions all under one toolbox. Eventually it might be nice to consolidate all your meta tools (link, station link, mirror, clipper) into a single "builder's toolbox" and have the mirror/link/clipboard all in a single item that occupies a single slot. Could then also make it a craftable hand-item when you get survival more fleshed out.

Anyway, hope these help give you some ideas to bounce around in that brilliant head of yours! You rock bud! Keep up the good work!

**Comment by nokturnihs** [comment]
Oh I guess paint gun would also work well in the list too...

**Comment by tsunamayo** [comment]
@nokturnihs Yes this could be useful, but I quite dont see it practical to navigate... I mean it is a game not a 3d editor... I need more thinking on how to access that option menu, as there is a few feature I will need like export to prefab... Thanks

**Comment by nokturnihs** [comment]
I might make a demo using autohotkey or something... I may not be explaining it well... But yeah, all good.

**Comment by tsunamayo** [comment]
@nokturnihs So most of these have been implemented recently. Thanks
