### ISSUE TITLE
BUG: Can’t start a Singleplayer Game without getting kicked off.

### ISSUE THREAD

**Issue by ConeOfAWidow** [tsunamayo/Starship-EVO#3491]
### Short Description of the issue:
After Selecting Play with this Character the loading screen starts, audio bleeps out 3 times and I’m back outside the game.
I’ve already tried uninstalling and Installing a few times and tried tampering with the saves because I happened to find the save_data in another section of my OS (C:).
...

### Steps to reproduce the issue:
Open the game
Select Play
Select Play with this Character
...

### Environment
- Starship EVO version: 20w49a
- Graphics Card: 1050 Ti GPU, which has 4GB of VRAM

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` or `Player.log` file starting from 21w02a. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by Kaiser-Indrasil** [comment]
A world file would be helpful. First, you have to find it in the Save_Data\Characters directory, then, just do this thing I linked below and upload the file here.

![image](https://user-images.githubusercontent.com/63756057/105112526-24ef9f80-5abb-11eb-9026-425146511ef9.png)

**Comment by tsunamayo** [comment]
@ConeOfAWidow Thanks for reporting the bug. As Kaiser said I would need something to investigate so I can help you further. Could you send me the output.log and the character save?
Also does it work with a new character?
And does it worked before or are you a new player?
Thanks!
