### ISSUE TITLE
[Bug] A handful of bricks are very picky about their placement

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3493]
Version: 21w03a

I've made a fresh world in this patch and pasted a few medium- and small-sized BPs.
Next thing I noticed, couldn't place a switch nearly anywhere despite there being lots of space around.
Seems like other people are not getting this bug, so I took a liberty to provide the world file: [Experimental Ongoing.zip](https://github.com/tsunamayo/Starship-EVO/files/5839731/Experimental.Ongoing.zip)

I think it pertains to bricks alone. Blocks are safe from it.
I've tested every brick out there and it seems like these are affected:

- Switch (flat)
- Starter Block

It doesn't have to do with proximity to other blocks, since it can even happen in complete isolation on a long rod, way outside the ship.

![Starship_EVO_5l0W8DnHR0](https://user-images.githubusercontent.com/63756057/105117628-b7487100-5ac4-11eb-9629-d5d0cf54bfd8.png)

Also doesn't have anything to do with brick grid offsetting with tiles and thin tiles.

![image](https://user-images.githubusercontent.com/63756057/105117459-6df82180-5ac4-11eb-87fb-cde06bb47386.png)

**Comment by tsunamayo** [comment]
Okay let me check, indeed I reduced the check threshold.

**Comment by Dwarf-LordPangolin** [comment]
I think I see part of why it's doing this, for the switch at least. It seems to only be placeable at the edge of the 1m voxel grid; it can be placed on the side of a 1m block, but doesn't want to be placed "inside" a 1m space. If you look at Kaiser-Indrasil's 2nd picture, the switch lets itself be placed at the edge of a 1m grid space, but not offset from those edges.


To illustrate further, it can be placed on the side of a 1m block:
![20210123162019_1](https://user-images.githubusercontent.com/33041786/105660922-bf702a00-5e91-11eb-978c-17f0db42ea4c.jpg)


... but will not let itself be placed on increments of less than 1m:
![20210123162022_1](https://user-images.githubusercontent.com/33041786/105660927-c139ed80-5e91-11eb-804f-ad99b17cd058.jpg)
![20210123162025_1](https://user-images.githubusercontent.com/33041786/105660929-c39c4780-5e91-11eb-9206-b419645838dc.jpg)
![20210123162029_1](https://user-images.githubusercontent.com/33041786/105660939-c8f99200-5e91-11eb-9c54-47f72805b1a5.jpg)

**Comment by tsunamayo** [comment]
Issue fixed for 21w03b. Thank all!

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo Not so fast ;)
The Starter Block is still borked.

![image](https://user-images.githubusercontent.com/63756057/105864296-b09c8b00-5fe9-11eb-8f40-8913e66d9c79.png)
