### ISSUE TITLE
[Bug] Impostor bricks

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3494]
Version: 21w03a

I'm... not sure what's going on here.
I've noticed it's happening regardless of what brick I'm using.
And it's all over the ship.

It disappears after the game restart.

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5844014/output_log.txt)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/5844015/Player.log)
[Character file.zip](https://github.com/tsunamayo/Starship-EVO/files/5844018/Experimental.Ongoing.zip)

https://user-images.githubusercontent.com/63756057/105209484-cd484700-5b41-11eb-9e4d-478231840dd3.mp4

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Yes I have some trouble with the rendering engine, I have yet to get a clear way to reproduce this. Do you remember what you did during your session? Unspawn ship? Was it after a quit to title / reload? Thanks

**Comment by Kaiser-Indrasil** [comment]
Nope, it was during building session, quite fairly in actually. I didn't do much outside just building bricks. No restarting, unspawning, spawning, anything.

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Did you get that recently? Thanks

**Comment by Kaiser-Indrasil** [comment]
Not anymore, luckily. Thanks for fixing it!
