### ISSUE TITLE
[Performance][Bug] Fps drop

### ISSUE THREAD

**Issue by MRonlin** [tsunamayo/Starship-EVO#3495]
### Short Description of the issue:
I started the game up one day and my fps dropped from 120 to 35-40 in space and 50 to 26 on the ring. It has stayed at that level ever since. 

This is on a empty world.

### Steps to reproduce the issue:
This issue occurred roughly when the patch happened.

### Environment
- Starship EVO version: 21w03a
- Graphics Card: gtx 1050

### Additional information:
V-sync - Disabled
Vignetting - Disabled
Chromatic Aberration - Disabled
Anti Aliasing - Disabled
Bloom - Disabled

Screen resolution 1920 x 1080 75Hz

Player log:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/5844408/Player.log)

**Comment by tsunamayo** [comment]
Hi, it has happened since the latest patch 21w03a? Thanks

**Comment by MRonlin** [comment]
Yeah since the patch.

**Comment by tsunamayo** [comment]
@MRonlin A few people reported this and the fix was to re-install the game apparently. If you could try this and tell me how it went. Thanks

**Comment by MRonlin** [comment]
Ok.

**Comment by Xerma** [comment]
I've been experiencing this lately as well since the patch. I tried reinstalling and even starting a fresh world and my frames still stay around 40-45 on/near the torus and around 53 in empty space

**Comment by Xerma** [comment]
If it helps I'm seeing a lot of this in my log file:

Graphics.CopyTexture called with invalid destination element index (got 37, have 32 elements/layers)
 
(Filename:  Line: 93)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5850661/output_log.txt)

**Comment by Battlepixel** [comment]
I can confirm, reinstallation did not fix the problem.

**Comment by tsunamayo** [comment]
Hi, all, could you give me your PC specs (GFX + CPU + RAM). Also do you tell me your CPU and GPU usage when running the game? Thanks

**Comment by Battlepixel** [comment]
gtx 1070 mobile, i7 8750H, 16GB Ram


Before the patch everything was ok, even with large objects / builds. Now when looking at the background, far away from the torus, in an empty world, I have over 70% GPU utilization. On the torus 100% at <60fps before the patch it was 50% at stable 60fps.

**Comment by Xerma** [comment]
i7 7700k
32GB RAM
GTX 970

CPU @ 8-10%
GPU @ 94-96%

I'm practically in the same position as Battlepixel in terms of large builds had very little to no impact at all on my game before the recent patch

**Comment by tsunamayo** [comment]
So it seems to be GPU related... Could you also give me your GRAM utilization level? Thanks

**Comment by Xerma** [comment]
Not quite sure I'm totally understanding what you mean, do you mean VRAM? and I honestly have no idea how to check that lol. I figured it would just be the amount of VRAM my card has * percentage on task manager

**Comment by Battlepixel** [comment]
VRAM utilization; is 3800MB/8192MB<50%
with >90% GPU utilization

**Comment by Battlepixel** [comment]
@Xerma you can use freeware: "MSI Afterburner" to read data and "Rivatuner"(included) to show it OSD but you need youtube-manual and some time to set everything right

**Comment by tsunamayo** [comment]
@Xerma No worry, it seems it is not an issue of VRAM usage either. There is a new build, if you can tell me if you still have the issue. Thanks

**Comment by Xerma** [comment]
In the new build it seems the issue is gone \o/

**Comment by Battlepixel** [comment]
I can confirm

**Comment by tsunamayo** [comment]
@Xerma ah okay sorry nevermind. Problem is I dont really know what it was, I guess some shenanigan linked to the new Unity version... Thx
