### ISSUE TITLE
[Bug] Problems with shaders in big rooms

### ISSUE THREAD

**Issue by Zenti98** [tsunamayo/Starship-EVO#3497]
### Short Description of the issue:

Hi again.

I would like to report a second one too. In big rooms, the game doesn't render all the shadows of the walls, that means that you can see sunlight in the far end of the room even if it's completely closed, so this isn't possible. Maybe you can help with this, thank you very much and thanks for this great game! :-)

![Evo Test](https://user-images.githubusercontent.com/73694475/105234486-9a1aad80-5b6b-11eb-816d-d5972aca7885.png)

### Environment
- Starship EVO version: Experimental 21w03a
- Graphics Card: Geforce RTX 2060

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5845236/output_log.txt)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/5845237/Player.log)

**Comment by tsunamayo** [comment]
Hi, yes it is not really a bug, unfortunately I cant compute shadow too far away from the camera, it takes too much resources. I will add a setting to increase the distance but it is quite a resource intensive feature (but you have a great GFX card). Thanks
