### ISSUE TITLE
AND Gates Preserving 0-Value Packets

### ISSUE THREAD

**Issue by talrey** [tsunamayo/Starship-EVO#350]
If someone wants to set up a system to alternate between 1 and 0 endlessly - a clock - the most common way to do so is with a NOT, a Delay, and a Dual Output gate. If they want to control when it runs, whether to stop the underlying packets being sent or just to disable whatever logic the clock is toggling, an AND gate is the obvious choice - A compact example build of this is attached.

Now, on to the actual (maybe) bug - this build works as expected exactly once, when the switch is first turned on. Turning it off works, but every activation after the first will increase the number of pulses sent to the Laser Unit by a factor of 2.

What's happening is that the usual pattern of 1 and 0 being sent out from the running AND gate is interrupted by the switch, causing a sudden 0 to appear on the line. This propagates through the Delay and into the NOT, where it arrives back at the AND gate. Instead of simply dying off here, the signals are preserved by the AND gate. Testing this same circuit, but with a NOT gate right before the Laser Unit, reveals that there's an endless loop of 0-value packets passing around the clock, despite the AND gate being off.

I suspect that what's happening is that rather than responding only to valid state changes, the AND gate will send a new packet affirming the existing state when either input detects a new packet. While I'm not sure if this should be classified as a "bug", it's definitely unexpected behavior from the player's perspective.

![clock](https://user-images.githubusercontent.com/6946291/32357985-ec4ada46-bffe-11e7-9ce7-c0ea48c996fd.png)

**Comment by tsunamayo** [comment]
Hello, I am not sure understand completely, but I made a change to the delay gate recently (not yet live), now there can only be a single pulse in the signal. Every input received during the "cooldown" period will be discarded. Also AND will never kill a signal, 0 or 1 are treated the same in a logical circuit. Maybe you want to use the router gate, as it will select only a single output. I could add a filter gate also, I am open to any suggestion. Thanks

**Comment by talrey** [comment]
That sounds useful as a workaround, how long is the cooldown?

A router gate would not help in this situation, as the point here is to send a signal that transitions between 0 and 1 back and forth at a constant rate.

I have a tendency to write too much, haha. The issue here in one sentence is that the AND gate sends a pulse on the output even if the state didn't change: (0 && 1) == (0 && 0), but the AND sends out a second 0 packet anyway, which can cause issues for systems that rely on state transitions.

**Comment by tsunamayo** [comment]
Yes all gate will send an ouput when they receive an input, even if it doesnt change (it seems more logic to me that way).
The cooldown is just the timer value you can specify, minimum being 0.1

For the reverse 0-1 you can very simply put:
dual command into
 => a) your system that will receive the regular pulse
 => b) into not gate => into delay gate => into input of your dual command.

Just tested it worked
Cheers

**Comment by talrey** [comment]
That's true, a simple loop works, but what if people are concerned about being unable to stop the packets? a Delay -> Not -> Dual Link loop will run forever - is that a potential problem if I build 100 of them?

I think that the cooldown may actually solve this issue, I'll have to test that when it goes live. Thanks!

**Comment by tsunamayo** [comment]
If you want to kill the signal you will then have to use a router brick. If it too complicated I could create a filter / switch gate of some kind.

**Comment by tsunamayo** [comment]
This issue is no longer valid in recent build. Thx
