### ISSUE TITLE
[Bug] deleting objects from a section of my ship crashes my game

### ISSUE THREAD

**Issue by quelonio** [tsunamayo/Starship-EVO#3500]
So i started to build a ship that's around 642x572x758m big and found a bug in which, for some reason, if i try to delete objects that are placed in a pretty small section of the ship the game crashes.

Here's an image of the buged section:
![bugged old lady section](https://user-images.githubusercontent.com/75544498/105268209-62a20600-5b57-11eb-919f-5b1517f18e1a.png)
Blueprint:
[Old lady.zip](https://github.com/tsunamayo/Starship-EVO/files/5846276/Old.lady.zip)
Output log:
[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/5846268/output_log.zip)

**Comment by tsunamayo** [comment]
@quelonio Hi, sorry to hear this. It doesnt look like the log is from a session where the crash happened. Also you are building way too big so it is safer for me to tell you that the game is not really made to support such a massive scale. Thanks

**Comment by quelonio** [comment]
@tsunamayo  hi, sorry for the output thing, here is output
[output_log (2).zip](https://github.com/tsunamayo/Starship-EVO/files/5890807/output_log.2.zip)

**Comment by tsunamayo** [comment]
@quelonio Hi, could you confirm me which version you are using? It seems it is not the right log. I need you to reproduce the crash, then send me the log from that very session. The log is overridden each time you restart the game. Thanks!
