### ISSUE TITLE
[Bug] Overlaping triangle decals cause flashing.

### ISSUE THREAD

**Issue by Sebateses** [tsunamayo/Starship-EVO#3505]
### Short Description of the issue:

Overlapped decals start to flash the further you move away from them.
Pretty sure I've narrowed down the main problem is the triangle decal.

I'm not entirely sure this happens for everyone if it is graphics settings related.

![20210122072936_1](https://user-images.githubusercontent.com/72846347/105411268-4ac99f80-5c87-11eb-93f8-ad66467ed1c6.jpg)

### Steps to reproduce the issue:

1. Place one large square decal on surface and paint it a dark colour.
2. Place a  large triangular decal on top of the square decal, leave it white do not paint.
3. Place another triangular decal on top of the 2nd one but reflected so it only semi overlaps/intersects the 2nd one.

I attached a short video to hopefully help recreate. You should be able to see the flickering in the center of the screen.

Video was also taken in a brand new game.

...

### Environment
- Starship EVO version: Default and Experimental
- Graphics Card: RTX 2070

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5851997/output_log.txt)

https://user-images.githubusercontent.com/72846347/105411706-d4796d00-5c87-11eb-8625-b239d1d19db0.mp4

**Comment by Sebateses** [comment]
The first one is a smaller example of this issue. I have a larger one with heavier use of decals.

https://user-images.githubusercontent.com/72846347/105474687-a3825200-5cf2-11eb-8d4b-343913a2b7d2.mp4

**Comment by tsunamayo** [comment]
@Sebateses It should be much better in upcoming 21w38a. Thanks
