### ISSUE TITLE
Clipping problems with turrets

### ISSUE THREAD

**Issue by Lonzo13** [tsunamayo/Starship-EVO#3507]
### Short Description of the issue:
Big ship, lots of clipping errors with turrets and their barrels. Seems to be no great difference, if the barrels are connected via rotators or via hinges. 
Often the barrels of a turret are turned inside the ships hull.  They fire right through the ship too. If i take manual control of a small front-turret, i can not turn it into the ship itself, but i can fire right through it with no problems. At least, luckily there seems to be no damage. 

By the way: This is a great game, i love it. Respect for your fantastic work!  

...

### Steps to reproduce the issue:
All Turrets are set to autofire. So just start the ship and spawn aggressive AI ships per F8 and the firework starts... 
...

### Environment
- Starship EVO version: 
21w03a

- Graphics Card: 
NVIDIA GeForce GTX 1060 6GB

Processor:
Intel i5-3570K  3.40 GHz

### Additional information:
i tried to add the mps-file frpm the blueprint folder, but "we don't support that file type...

_(Screenshots, Videos, Error logs, Related issues)_
![Barrels down](https://user-images.githubusercontent.com/66515119/105495845-f5a88080-5cbc-11eb-89cd-6303b1e8de15.JPG)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5856070/output_log.txt)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/5856074/Player.log)

Please also include the `output_log.txt` or `Player.log` file starting from 21w02a. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by ProPeach** [comment]
Just FYI you can right click on the folder that the blueprint is in (should be named after the blueprint) and click Send to -> compressed zip file then drag in onto your report to upload it here
Great report!

Tsuna, it might be useful to add this to the default report guide to help out in the future

**Comment by tsunamayo** [comment]
@Lonzo13 yes could you zip the file? @ProPeach you are right, I have just edited the report! Thanks all

**Comment by Lonzo13** [comment]
[Linse_Glatt_Warp3.zip](https://github.com/tsunamayo/Starship-EVO/files/5859997/Linse_Glatt_Warp3.zip)

Thanks for your quick answer and thanks for that zip-tip. Why did i not come to this solution...? sorry for that. 
I hope the blueprint helps. The ship is far from beeing complete, more of an ongoing Prototype.
One additional thing to the clipping problem:   If i control a turret manually and the logic considers a collision, i normally cannot move the turret furter in this direction. But now i often cannot move the turret at all. even in the other direction. it seems to be stuck in the moment of collision. 
And sorry for my english, it is not my motherlanguage...  :-)

Greetings 
Andreas

**Comment by tsunamayo** [comment]
@Lonzo13 Issue fixed for 21w04b. Tell me if you still have issues. You can now debug the turret collision map by selecting the second rotator with a link tool. Cheers
