### ISSUE TITLE
[Cat] I built Austin

### ISSUE THREAD

**Issue by Aiwii** [tsunamayo/Starship-EVO#3508]
https://gfycat.com/eachwellinformedaurochs
![image](https://user-images.githubusercontent.com/53021785/105564234-817ed480-5cde-11eb-9684-f69a18f846b7.png)

not bug report, just cat

**Comment by tsunamayo** [comment]
@Aiwii haha nice one mate, may he rest in peace that good old cat. Could you send me the bp? I think it could be cool to put somewhere as an easter egg, like a shrine or inside a station hub. Cheers

**Comment by ProPeach** [comment]
I'm sorry to hear about Austen, such a lovely boy! ❤

A shrine or Easter egg for him would be very touching

**Comment by Aiwii** [comment]
I'm also sorry to hear about Austin, A few of us in the server were actually hoping to get more pictures of him someday. It would be no problem to share the bp with you. @tsunamayo 
> I'm sorry to hear about Austin, such a lovely boy! ❤
> 
> A shrine or Easter egg for him would be very touching

[Austin Statue.zip](https://github.com/tsunamayo/Starship-EVO/files/5859984/Austin.Statue.zip)

**Comment by Weskerdoo** [comment]
Thanks for this. Would you mind if I also use this? The cat in my profile pic was my baby girl and we lost her last March.

**Comment by tsunamayo** [comment]
Thanks to all for the kind words! It was sad but he had a long and happy life! Sorry for your cat too @Weskerdoo! She looked a lot like one of my older cat! Cheers
