### ISSUE TITLE
[suggestion] make paste gravity blocks keep the parameters of the original copied gravity block

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#3510]
One of the hard parts of building race tracks is the default configurations when you paste a gravity block. I need to copy and paste the track floor with the gravity block on it, and if I set it up any of its dimensions outside the -8 ~8 range, the copied version won't keep the modified parameters. The idea is: make the paste version retain all the original configuration.

**Comment by tsunamayo** [comment]
Yes it has planned, for now gate dont copy their state... thx

**Comment by tsunamayo** [comment]
It is okay now!
