### ISSUE TITLE
[Suggestion] Character List

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#3511]
Currently the list of characters is alphabetical. Would it be possible to have the list in order of date last accessed? A little QOL for singleplayer, but will be much more useful when multiplayer comes alone, unless you want servers to be named like insurance companies so they can be at the top of the list (Many are/were named "A whatever insurance company" so they can be at the top of the phone book)
![image](https://user-images.githubusercontent.com/36980446/105613773-f9520b00-5d81-11eb-9c35-d8574d527dd1.png)

**Comment by tsunamayo** [comment]
Yes it makes sense. thx

**Comment by tsunamayo** [comment]
@ZachZent done for 21w05c, LINQ is my friend. Cheers
