### ISSUE TITLE
audio lags when I turn on Recording screen software when I jump onto a Yoke In game.

### ISSUE THREAD

**Issue by Jackbeflippen** [tsunamayo/Starship-EVO#3513]
### Short Description of the issue:
When I turn on my recording software,  Open Broadcast Software (OBS),  and then jump into a yoke of a ship it desyncs my sound from matching the video by a few seconds. It also messes up if I am watching youtube on the side it desyncs my sound from the video. 
...

### Steps to reproduce the issue:

At this point my settings in OBS do it every time and I can record it.
...

### Environment
- Starship EVO version:   20W 49A
- Graphics Card:   GeForce GTX 1060 6GB

### Additional information:
The game when jumping into a ship yoke knocks my audio back 2 to 3 steps before I hear anything coming out of my speakers. I can tell I am seeing this lag due to Discord and people have the green light around their name firing off then seconds later I hear them. It resets when stopping the recoding and re-open my OBS.  This also transfers over into the videos. I know it has something to do with jumping onto a yoke of a ship. it can be a small ship or big one, it still messes up all the timing of the audio. 

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` or `Player.log` file starting from 21w02a. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

cannot find 21w 02a in the file. 

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
Hum I dont know if there is anything I can do for you. OBS works fine on my side. It seems to be a windows shenanigan I have little control over (I use Unity, my code has nothing special in it...) Cheers
