### ISSUE TITLE
[SUGGESTION] Universal Resource Format

### ISSUE THREAD

**Issue by JimStarluck** [tsunamayo/Starship-EVO#3515]
Hey, new guy here! Just picked up the game recently and had an idea that might make fleshing out the depth of ship-building easier and more streamlined. Basically, establish a universal format that can be used for various resources a ship has to utilize & manage which lets you apply the same set of mechanics across the board.

You'd have a standard set of blocks with the same functions:
- Sources: blocks that provide more of a resource
- Storage: blocks that act to hold a resource
- Sink: blocks that consume a resource
- Converters: blocks that act as a combination sink for one resource and a source for another
- Lines: blocks that connect all of the above, allowing you to move resources around the ship

Side note: for lines in particular: I'm thinking a method to have them go "through" other blocks, in one side and out the other, would ease in routing.

This could be utilized for all kinds of resources, potentially simplifying coding and making gameplay consistent and easy to learn across the board.

Thoughts for types of resources this could be employed with:
- Fuel
- Energy
- Coolant
- Oxygen
- Water
- Tribbles

Hope it's helpful!

**Comment by tsunamayo** [comment]
Thanks, indeed it will be a system like that. No worry for the code side, thats my job ;) Cheers
