### ISSUE TITLE
how to reinstall the game after removed files

### ISSUE THREAD

**Issue by Paul-van-Hummel** [tsunamayo/Starship-EVO#3516]
Hi there,

After my last ticket and great feadback, I've bought a graphic card, and have already alot of fun with the game, however I have several usernames that I tried before that, and they don't appear in my screen, only got the message, that the username is already existing, (from the time before I've bought the grapic card and tried to play the game. They aren't accesable or vissable.

I've tried to fix it myself, and made a big mistake with removing the files (I was convinced I found the right map) and when I tried to start the game I still was not able and got the message that username already exist, but I created a new problem as well, Now the start point with all the game tutorials are missing 

the folder I've emtied is: 
C://acer/program filesx86/steam/steamapps/common/starship EVO/Starship EVO_Data/steamingAssets/playerEntities

I was so sure I had the right files that I emtied the bin as well, before testing out.
My mistake to make, and I have tried to find any information how to reinstall the game what hopefully fix the problema with the turorial base and the already existing but not playable usernames.

Can you please help me out?

Thanks in advance,
Regards, Paul van Hummel (The Netherlands)
### Short Description of the issue:

...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` or `Player.log` file starting from 21w02a. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by TIKIRobo** [comment]
C:\Users\(username)\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Characters

Try deleting the character files here, that might hopefully fix it (then verify file integrity through steam)

**Comment by Paul-van-Hummel** [comment]
Many thanks for the quick reply and given steps to follow, I have recovered (downloaded again) the missing files, and found the map with all the characters who could be deleted, and my problem is solved...

Again many thanks.

Paul van Hummel
