### ISSUE TITLE
allow hotkey gates to use any key

### ISSUE THREAD

**Issue by luckyrada** [tsunamayo/Starship-EVO#3519]
### Short Description

would be great if the hotkey gates could be used for any key like "W" "L" "N" ect.

im trying to make a ship (razorback from the expanse) and i would like to be able to make it so wehn the ship turns it can rotate a bearing. could also be useful for lots of other things as well

**Comment by tsunamayo** [comment]
Hi, this is not the right way to do this. What if the player remapped its control? But I will give a way to do something similar. (But that wont be a continuous link, more something like the query) Thanks
