### ISSUE TITLE
bug doesn't let me delete or place anything after interacting with hover core

### ISSUE THREAD

**Issue by SovietSponge** [tsunamayo/Starship-EVO#3522]
### Short Description of the issue:
entered hover core to check balance and speed, found i couldn't delete or place anything after entering the core, trying to reload the world crashed the game
...

### Steps to reproduce the issue:
enter hover core, try building
...

### Environment
- Starship EVO version: 21w03a
- Graphics Card: GTX 1050Ti

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5872332/output_log.txt)

**Comment by Kaiser-Indrasil** [comment]
Yup, it's consistent with my findings, repeatable every time.
I've attached the logs below.

https://user-images.githubusercontent.com/63756057/105858762-96f84500-5fe3-11eb-82e3-97d6ded6a0e9.mp4

Also causes the "black galaxy" bug on the world reload.
It gets fixed upon the game restart though.

![image](https://user-images.githubusercontent.com/63756057/105858021-c9ee0900-5fe2-11eb-8442-03f7640ae4bd.png)

Here are the [pre-world reload logs](https://github.com/tsunamayo/Starship-EVO/files/5873928/Player.log).
And here's the [post-world reload logs](https://github.com/tsunamayo/Starship-EVO/files/5873945/Player.log), this time ending with a crash.
Another one, [this time, with the "empty galaxy and grids removed bug"](https://github.com/tsunamayo/Starship-EVO/files/5873958/Player.log) (what a name, I know).

**Comment by TIKIRobo** [comment]
this also happens when interacting with hover pods

**Comment by tsunamayo** [comment]
Issue fixed for 21w04a. Thanks
