### ISSUE TITLE
[Bug/Crash] building on a grandchild entity causes crash on joining world

### ISSUE THREAD

**Issue by Xenoprophet-Nail** [tsunamayo/Starship-EVO#3523]
### Short Description of the issue:
I was building a round-ish engine frame to test a propulsion idea for a ship/hovercraft and first I saw the rotators go invisible. I know that that happens sometimes so I built onto the invisible bits, when I moved back from my work and I saw the blocks rendered a distance away. so I exited to title so I could reload. It then proceeded to crash hard which is a first for me.
...

### Steps to reproduce the issue: 
Stack four small rotators upon an offset and a tile, the first time the starter block should move oddly, then make a second setup just the same way on a new starter block. then build onto the sides of the second invisible rotator

...

### Environment
- Starship EVO version:  20W3b
- Graphics Card: Nvidia Geforce GTX 1060 6gb

### Additional information:

https://www.dropbox.com/s/b9ctwt74xywf1xo/20210126035134.jpg?dl=0

https://www.dropbox.com/s/aajylnt3ipbsh08/output_log.txt?dl=0

https://www.dropbox.com/s/akybbzjyylqtckw/20210121024654_1.jpg?dl=0

For some reason github won't let me post pics or zip files anymore, please have a look at the links on my dropbox. The first is a screenshot of the issue, the second is my output.txt, the third is the design working in a previous version... Yeah it's a lot of entities but it just looks so good on a ship lol, also I want to tell you I am not clipping there, the gaps prove it and I can send a bp of the engines by themselves if you need to look at it. Plus the edges glow which looks really cool.

**Comment by tsunamayo** [comment]
@Xenoprophet-Nail Hi, gotcha it seems the latest build is buggy as expected. The log file changed, it is now called player.log. Thanks

**Comment by tsunamayo** [comment]
Fixed for 21w04a. I am pushing the build today as it is pretty game breaking. Thanks!

**Comment by Xenoprophet-Nail** [comment]
Thanks  bunch for your quick reply Tsuna! Glad to see things got sorted as I was gonna do some experiments with a hovercraft... Now I can!
