### ISSUE TITLE
[BUG] invisible grandchild entities  

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3524]
### Short Description of the issue:
when placing a hinge on a hinge the 2nd hinges head turns invisible, when i place a hinge on the invisible hinge head that too turns invisible  
...

### Steps to reproduce the issue:
place a hinge on a hinge on a hinge 
...

### Environment
- Starship EVO version: 21w03b
- Graphics Card: Radeon RX 5600 XT

### Additional information:

https://user-images.githubusercontent.com/56371294/105864464-30f1ca80-5faf-11eb-97f6-45fea2186a75.mp4

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5874201/output_log.txt)

**Comment by tsunamayo** [comment]
Fixed for 21w04a. Thanks!
