### ISSUE TITLE
Lights don't work on spawned entities

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#3525]
### Short Description of the issue:
In the newest update lights just don't work on entities that get spawned in, even if you place new ones on that entity. But if you place a light on an entity that already exists in the world I guess it updates the lighting engine and then the lights work on the spawned entity
...

### Environment
- Starship EVO version: 20w03b
- Graphics Card: GTX 970

### Additional information:
![20210126101224_1](https://user-images.githubusercontent.com/32974671/105872380-f7758b00-5fbf-11eb-8f75-c492cd2d73b0.jpg)

Output log is 40mb and is filled with lots of this:

Kuroshio|p2|(-12558856134414 13256010585 5744770507936)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Mistral|p2|(-12522881031938 -38210506890 5713688217006)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Corellian Shuttle|p1|(540965156958 42417069895 -135068681989)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Mistral|p1|(492179432781 35017456930 -108285935181)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Corellian Shuttle|p2|(-12561484298981 38070112984 5751692029619)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Kuroshio|p2|(-12558856134414 13256010585 5744770507936)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Mistral|p2|(-12522881031938 -38210506890 5713688217006)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

**Comment by tsunamayo** [comment]
@Xerma So in latest update the output.log is renamed and called player.log... (Because of Unity upgrade). But I dont really need it for that issue... Thanks

**Comment by tsunamayo** [comment]
Fixed for 21w04a. Thanks!
