### ISSUE TITLE
Copy/Paste ghost not showing

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#3526]
### Short Description of the issue:
It appears we can now use copy/paste within an entities bounds again but now we can't see the ghost preview of what's being pasted.
...

### Environment
- Starship EVO version: 20w03b
- Graphics Card: GTX 970

### Additional information:
![20210126101547_1](https://user-images.githubusercontent.com/32974671/105872580-31df2800-5fc0-11eb-869c-f686246defbd.jpg)

Output log is 40mb and is filled with lots of this:
Kuroshio|p2|(-12558856134414 13256010585 5744770507936)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Mistral|p2|(-12522881031938 -38210506890 5713688217006)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Corellian Shuttle|p1|(540965156958 42417069895 -135068681989)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Mistral|p1|(492179432781 35017456930 -108285935181)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Corellian Shuttle|p2|(-12561484298981 38070112984 5751692029619)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Kuroshio|p2|(-12558856134414 13256010585 5744770507936)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Mistral|p2|(-12522881031938 -38210506890 5713688217006)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

**Comment by tsunamayo** [comment]
Hi. indeed, it is fixed for 21w04a. Thanks for being on the ball ;)
