### ISSUE TITLE
[BUG] Autoturrets dont turn any longer 

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Starship-EVO#3528]
### Short Description of the issue:
-2) Autoturrets dont turn any longer (not blueprint related)(not Character-/world- related)
-3) Autoturrets damage own ships (not blueprint related)(not Character-/world- related)**(very old bug)(is related to #3461 and maybe related to #3052 )**
### Steps to reproduce the issue:
sit in your ship and spawn an enemy. The turrets shoot in all directions but they dont move since last update
### Environment
- Starship EVO version: 20w03b(newest)
![Starship EVO_2021_01_26_20_50_00_466](https://user-images.githubusercontent.com/43222403/105897509-8ca46e00-6018-11eb-9825-ad639d86dfc8.jpg)
2) example

![Starship EVO_2021_01_26_20_44_44_897](https://user-images.githubusercontent.com/43222403/105897537-962dd600-6018-11eb-80e6-9a9793dd440a.jpg)
3)  example
outputlog:
[Player.zip](https://github.com/tsunamayo/Starship-EVO/files/5875772/Player.zip)

**Comment by ProPeach** [comment]
This issue is also present in manual turrets - firing them will produce a laser bolt in the right direction as if they were moving fine, but the turrets themselves stay still

**Comment by tsunamayo** [comment]
Turret not turning issue fixed for 21w04a. Patch incoming! The other bug (self hit) has been reported already.
