### ISSUE TITLE
[BUG] Movement speed less than one

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#3529]
### Short Description of the issue:

Since the latest version (21w03b) attempting to set a movement speed less than 1 no longer takes us to zero. It now takes us to a strange world of rational fractions, culminating at 0.1x. After which, while it is still possible to change the speed between 0.1x and 1000000x, it is not possible to get back to 1x.

### Steps to reproduce the issue:

Enable fast movement keys.
Venture below 1.
Be forever lost inside fractional space-time.

### Environment
- Starship EVO version: 21w03b
- Graphics Card: GTX1070

**Comment by tsunamayo** [comment]
Fixed for 21w04a. No more  fractional space-time =( (that sounded cool)
