### ISSUE TITLE
[Bug] 3D preview missing in Tab menu [21w03b]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#3531]
### Short Description of the issue:
The 3D preview of the ship being worked on no longer shows in the building menu.

### Steps to reproduce the issue:
Start working on a ship, then press Tab. The 3D preview will be blank.

### Environment
- Starship EVO version: 21w03b
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
![20210126165745_1](https://user-images.githubusercontent.com/33041786/105917197-a5e8f280-5ff7-11eb-9c10-bc258f6f6389.jpg)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/5876632/Player.log)

As noted [here](https://github.com/tsunamayo/Starship-EVO/issues/3521#issuecomment-767418248), this is indeed for version 21w03b, despite the version number visible in the screenshot.

**Comment by tsunamayo** [comment]
Fixed for 21w04a. Thanks!
