### ISSUE TITLE
[Bug] Beam and Laser Stats are Identical

### ISSUE THREAD

**Issue by MagicalAbyss** [tsunamayo/Starship-EVO#3532]
### Short Description of the issue:

From the following images, laser and beam have the same hull damage, heat and power, is this intended or a bug?

![unknown (1)](https://user-images.githubusercontent.com/74992463/105934975-240cbf80-601f-11eb-959a-075e7842ddb3.png)
![unknown](https://user-images.githubusercontent.com/74992463/105934976-240cbf80-601f-11eb-86fb-bae5347280eb.png)

### Environment
- Starship EVO version: 20W49a

**Comment by tsunamayo** [comment]
@MagicalAbyss Hi, I guess that is a bug, beam is supposed to be weaker! I will see if it is just UI thing or they are really too strong in game.

**Comment by tsunamayo** [comment]
@MagicalAbyss Sorry no I havent looked too much at your screen, but in fact what matter is the DPS. The beam fire only 1/3 of the time, so it even out. For power it is normal. Thanks
