### ISSUE TITLE
[bugx2] Exiting hovercraft causes it to move upwards on it's own and the hovercraft stats menu isn't showing

### ISSUE THREAD

**Issue by Xenoprophet-Nail** [tsunamayo/Starship-EVO#3535]
### Short Description of the issue:
when I release the yoke on a hovercraft it moves upwards

...

### Steps to reproduce the issue:
load my race sedan (which I will include) and hop in, then release the yoke it should move upwards. 
...

### Environment
- Starship EVO version: 20w04a
- Graphics Card: Nvidia Geforce GTX 6gb

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

https://www.dropbox.com/s/1nnh95ibai2moj6/Player.log?dl=0
https://www.dropbox.com/s/l5ksdogq6w03u8o/Starship%20EVO%202021-01-27%2004-37-17.mp4?dl=0
https://www.dropbox.com/s/a26levul8i5end0/Starship%20EVO%202021-01-27%2004-37-47.mp4?dl=0
https://www.dropbox.com/s/531zwtgtjbh36wz/Racer%20Ltd%20LX%20Prime%20b.zip?dl=0

You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by Xenoprophet-Nail** [comment]
there may be a third bug there when you access the hover core as well but it's in the video

**Comment by tsunamayo** [comment]
@Xenoprophet-Nail Hi, could you send me the second one too? That bug looked funny. Cheers

**Comment by tsunamayo** [comment]
@Xenoprophet-Nail All tree issues fixed for 21w04b. Thanks!
