### ISSUE TITLE
[Bug] Movement becomes locked with entities, which then follow the character

### ISSUE THREAD

**Issue by Midge57** [tsunamayo/Starship-EVO#3536]
### Short Description of the issue:

All entities in the world become connected to the character and move laterally (not rotational)

### Steps to reproduce the issue:

Access hover?
Delete hover?
Move towards another entity, when you get close it may lock to you.

### Environment
- Starship EVO version: 21w04a
- Graphics Card: NVIDIA RTX 3070

### Additional information:

https://gfycat.com/embarrassedcircularcoelacanth

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5880714/output_log.txt)

**Comment by TIKIRobo** [comment]
i think i know what causes it, when i flew a ship around a bit then dispawned it everything latched on to me like you are saying

**Comment by Battlepixel** [comment]
same here

**Comment by tsunamayo** [comment]
@Midge57 Could you send the player.log instead? This  is the log of the new version. I unspawned many ship and had no issues, could you also send the blueprint?
Thanks!

**Comment by Dwarf-LordPangolin** [comment]
Same: this started when I unspawned something. Here's the log:

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/5883805/Player.log)

**Comment by Midge57** [comment]
Thanks Tsuna, here's my player log:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/5883997/Player.log)

And here's the racer I despawned and the large loop that you can see in the gif:
[Hover Racer + Large Loop.zip](https://github.com/tsunamayo/Starship-EVO/files/5884002/Hover.Racer.%2B.Large.Loop.zip)

**Comment by tsunamayo** [comment]
Fixed for 21w04b. These are turbulent times, I will upload the build soon.
