### ISSUE TITLE
Download problem

### ISSUE THREAD

**Issue by LaBarbe1995** [tsunamayo/Starship-EVO#3537]
### Short Description of the issue:
Problem whit the last update, making problem during installation phase: _error writing to disk_
I did everything that is advisable to do in this case (delete the steam download cache, reinstall the game, move its installation location, add an exception to the anti-virus / firewall, ect ...) Nothing works. 
If you want more informations you can contact me on discord LaBarbe#6682. I'm on the official SSE discord.
_I use google translate_

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

![problème EVO](https://user-images.githubusercontent.com/78099701/106027198-f4b38c80-60ca-11eb-971f-bb16e0ce3dcb.PNG)
**note**: it is written on the screenshot "_error writing to disk_"

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` or `Player.log` file starting from 21w02a. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by LaBarbe1995** [comment]
Here the output log
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5882455/output_log.txt)

**Comment by tsunamayo** [comment]
@LaBarbe1995 Sorry to hear this, I cant help you because it is a Steam error, not a game error. How much space left is on your disk? Thanks

**Comment by matejkar** [comment]
@LaBarbe1995 happened to me and my friend as well, now for me this worked:
go to your settings
search up security
click on windows security
then virus and threat protection
go to manage settings under virus and threat protection settings
and disable real time protection

**Comment by LaBarbe1995** [comment]
So.... Today disable real time protection is working....
Problem resolve. Thanks you both for your time.
