### ISSUE TITLE
[SUGGESTION] Selection tool

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3539]
This would be a new tool that could use a system similar to how the C&P tool works to highlight a large volume.

**What could it be used for?**
as seen in #3407 this could be used to set up o2 fields or set up gravity fields, shipyards and volumetric sensors.

It could also have many other uses such as: mass deletion and mass painting.  

**How would it work?**
My though process would be that it would use the radial menu (the menu that pops up when you click middle mouse) and when holding the new tool if you opened the radial menu you would see at the bottom two buttons one red, one blue to swap modes and then the button at the top would show the current mode and have a short description when clicked on.  
![image](https://user-images.githubusercontent.com/56371294/106037929-89e75e80-6094-11eb-86c5-5560ffb20958.png)
a little like this

**Comment by jealousdequan** [comment]
Also another idea: add the ability to hold down the click button while painting, to allow the entire ship to slowly be coated in that one colour. Just so it's easier to get our base colour down.

**Comment by tsunamayo** [comment]
Hi, so I want to solve the volume definition differently, with a hold handle system while looking at the preview. Also for the color I think that would confuse players more than anything...

**Comment by TIKIRobo** [comment]
I'm not too sure I understand what a "hold handle system" is do you think you could explain it differently?

**Comment by tsunamayo** [comment]
So at the end of the 3d bounds preview there will be a little sphere. You will be able to drag the sphere to adjust the size. No need to input the size manually.
