### ISSUE TITLE
[Bug] Docked ship on other ship disappears, pad still Taken on save/reload [21w04a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#3540]
### Short Description of the issue:
I left a ship docked on another ship, and after saving and reloading it had disappeared. However, the landing pad still says "Taken," meaning the pad cannot be used again.

### Steps to reproduce the issue:
Take a ship with a landing pad, dock another ship to it, save and quit, then reload. The docked ship will have disappeared, but the pad will stay say Taken when selected.

### Environment
- Starship EVO version: 21w04a
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
![20210127182436_1](https://user-images.githubusercontent.com/33041786/106072681-34c83e80-60ce-11eb-9c32-f3aa4ebf59b5.jpg)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/5883976/Player.log)

**Comment by Dwarf-LordPangolin** [comment]
As an update, the Taken status of the pad persists even after exporting the ship's blueprint, then unspawning and respawning it.

**Comment by tsunamayo** [comment]
Hi, issue is fixed for 21w05b. Thanks!
