### ISSUE TITLE
When getting out of seat teleported out of ship

### ISSUE THREAD

**Issue by luckyrada** [tsunamayo/Starship-EVO#3541]
### Short Description of the issue:
So I'm playing the game in latest expiremental, flying my ship around, and I get out of the chair and I fly out of the ship. I can go back to it tho it's not far away

### Steps to reproduce the issue:
Get in chair and get out

### Environment
- Starship EVO version: latest expiremental

**Comment by tsunamayo** [comment]
@luckyrada I cant reproduce this bug. Could you join the player.log like requested? Thanks

**Comment by luckyrada** [comment]
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/5891365/Player.log)
should be it. although it seems to only happen with my spaceship... weird. i cant send the blueprint because it says file not suported...?

**Comment by tsunamayo** [comment]
Thanks, issue fixed for 21w04c.

**Comment by luckyrada** [comment]
thank you
