### ISSUE TITLE
[Bug] Game crashes on various occasions

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3542]
Version: 21w04a

I've had a few of these already after the Unity CPU update but only this time did it happen when I was just literally creating a new world.
I've got a Ryzen 3900X, underclocked for maximum stability - it's a damn bronze sample...

Anyway, here's some [player logs](https://github.com/tsunamayo/Starship-EVO/files/5888985/Player.log) and [output logs](https://github.com/tsunamayo/Starship-EVO/files/5888986/output_log.txt)

I will keep you posted if it happens in any other scenario, so we can narrow down the search.

**Comment by tsunamayo** [comment]
Hi, it seems it happened when you quit the game, right? or wrong log... There is now a file called player-prev.log with the log from the session previous, you can give that one (output.log is the one before the version switch, not updated anymore). Thanks

**Comment by Kaiser-Indrasil** [comment]
Ah, I see. Will hand them over at the nearest convenience.

**Comment by tsunamayo** [comment]
And by crash you mean crash to desktop right?

**Comment by Kaiser-Indrasil** [comment]
Yes, CTD.
Surprisingly, this is no longer the case in the current experimental branch, so I'm happy to close the report.
