### ISSUE TITLE
[Bug] Workshop description on the main page cropped too much

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3543]
![image](https://user-images.githubusercontent.com/63756057/106178099-40306e00-6191-11eb-93d5-b43f71acfb35.png)

The single line of the description on the Workshop's main page is cropped a bit too much.
It's somewhat legible, but doesn't look good at all.
Is that something you can address on your end or is it just Workshop's fault?

**Comment by tsunamayo** [comment]
Nope I cant control Steam web formatting for sure ;) Cheers
