### ISSUE TITLE
[Bug] No input after linking to or from a hover yoke

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3544]
Version: 21w04a

What's happening is, sometimes when I link a yoke to the Hover Core, the game ceases to read any and all input, be it mouse, keyboard - anything.
Recently, I've noticed it's happening when I link a seat to the yoke, on one of the default vanilla hoverbikes, of all things.
So it's quite possibly has something to do with the yoke.

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5889205/output_log.txt)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/5889206/Player.log)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Hi, I have seen that error before but was never able to reproduce. What did you do exactly, just link the seat to the yoke? Nothing more? Can you reproduce 100% or is it random? Thanks

**Comment by Kaiser-Indrasil** [comment]
It's pretty consistent. Just linking the yoke to the hover core or seat to the yoke connected to a hover core will do the trick.

I've noticed it happens over at the stable branch as well.

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil even after a fresh reload from windows? I tried it many time and I have no issues...

**Comment by Kaiser-Indrasil** [comment]
Well, looks like whatever you did in 21w04b, it fixed the issue. Case closed I guess ;)
