### ISSUE TITLE
[Bug] Ghost follower grids bug is back + invisible blocks bug

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3546]
Version: 21w04a

It just happened randomly without any clear trigger. So elusive...

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5889401/output_log.txt)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/5889402/Player.log)

https://user-images.githubusercontent.com/63756057/106183587-49710900-6198-11eb-8752-62f7d2ebb432.mp4

**Comment by Kaiser-Indrasil** [comment]
Looks like the trigger is spawning a blueprint, probably a hovercraft.
Doesn't happen every time, but it does, eventually.

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil It seems to be related to unspawning and the preview. I will give a shot and see if I can reproduce - I keep you posted.

**Comment by tsunamayo** [comment]
Issue fixed for 21w04b. Thanks!
