### ISSUE TITLE
[Bug] Negative power balance after respawning craft

### ISSUE THREAD

**Issue by TheWanderer05** [tsunamayo/Starship-EVO#3549]
### Short Description of the issue:
Upon spawning in a saved vessel, the power balance is negative, even if it was positive when it was saved.
...

### Steps to reproduce the issue:
Save a recently created vessel, respawn it, turn the reactors on if they aren't already, and the power balance is negative. If a reactor is added to even out the power deficit and the ship is flown by the player, and the reactor is removed afterwards, it will have the same power balance it had when it was created and saved until the reactors are turned off or the craft or save is loaded again.
...

### Environment
- Starship EVO version: 21w04b
- Graphics Card: GTX 1070

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Bug after loading the craft:
![image](https://user-images.githubusercontent.com/37814712/106226262-cca05800-61b4-11eb-859c-fcb97deb9124.png)

Added reactor to overcome the deficit:
![image](https://user-images.githubusercontent.com/37814712/106226372-02ddd780-61b5-11eb-9be8-5a6fbb1a59e8.png)

Removed reactor after flying the ship (standard power balance):
![image](https://user-images.githubusercontent.com/37814712/106226407-1e48e280-61b5-11eb-8a66-f4662916fc84.png)

Output and Player logs:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5891359/output_log.txt)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/5891360/Player.log)

I have noticed this on at least 2 ships so far:
[Warp Testbed mk1.zip](https://github.com/tsunamayo/Starship-EVO/files/5891363/Warp.Testbed.mk1.zip)
[Warp Testbed Mk2.zip](https://github.com/tsunamayo/Starship-EVO/files/5891364/Warp.Testbed.Mk2.zip)

**Comment by tsunamayo** [comment]
It should be fixed in recent updates. thx
