### ISSUE TITLE
Targeting any entity causes some models to stop rendering

### ISSUE THREAD

**Issue by Kranyolsu** [tsunamayo/Starship-EVO#3550]
### Short Description of the issue:
Targeting any entity causes some models to stop rendering
...

### Steps to reproduce the issue:
target any entity
...

### Environment
- Starship EVO version: 21w04b
- Graphics Card: GeForce GTX 1060 6GB

### Additional information:
Hello again!  This may be a continuation of the graphical issues that you identified before but I have done a fresh install since then so I'm at a loss for what could be causing this, though it may be related to the preview in the lower right corner as that model renders properly.  This started happening after the multithreading update.
_(Screenshots, Videos, Error logs, Related issues)_
![20210129004913_1](https://user-images.githubusercontent.com/77525295/106237705-53f9c580-61cd-11eb-8c40-b9ae074e2493.jpg)
![20210129004917_1](https://user-images.githubusercontent.com/77525295/106237706-54925c00-61cd-11eb-978c-38cb051e7b2a.jpg)

Please also include the `output_log.txt` or `Player.log` file starting from 21w02a. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/5891870/Player.log)
If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
Fixed for 21w04c. Thanks!
