### ISSUE TITLE
[performance] Insanely high RAM consumption

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#3551]
### Short Description of the issue:
I'm building a racing track very big, and it's consuming too much RAM.

Ive been reaching very high RAM consumption on this track, 14 Gb to 15Gb ram consumption (figure). It's a building blueprint, anchored in the ring, without child entities.

A lot of gravity field to make it work.

There are some building errors that I need to fix to make it 100% functional.
...

### Steps to reproduce the issue:
Load the track
...

### Environment
- Starship EVO version: experimental and normal
- Graphics Card: gtx 1660
- cpu i7-3770

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

![20210129050328_1](https://user-images.githubusercontent.com/73253472/106296514-8ab4f780-6230-11eb-83a5-2a7c18a9a5a0.jpg)

Please also include the `output_log.txt` or `Player.log` file starting from 21w02a. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

player:

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/5895438/Player.log)

output log:
[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/5894775/output_log.zip)

character:
[experimental track.zip](https://github.com/tsunamayo/Starship-EVO/files/5894778/experimental.track.zip)

blueprint:
[[ULTY] FINAL RACE.zip](https://github.com/tsunamayo/Starship-EVO/files/5894782/ULTY.FINAL.RACE.zip)

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hi, do you get this on load or it gradually increase over time? Also is it since the latest patch or something that was going on for a while (or you didnt checked until lately?) Thanks

**Comment by Uncle-Ulty** [comment]
I'm not sure, because I was not monitoring the hardware before the patch. But I started the build before the latest patch and continued after the patch. So, as the track started to get bigger, the copy-paste tool began to freeze a lot, so started to monitor the game and noticed the ram consumption.

I abandoned the original track and tried to make it shorter. The short version is on 11Gb on ram already, but I think I can complete it without reaching  16Gb.

**Comment by Uncle-Ulty** [comment]
I looked for a recorded video I made on 24 January, before the patch, and outside experimental mode. On this day, I was consuming 9Gb ram, but the track was smaller with less blocks and gravity blocks.

**Comment by tsunamayo** [comment]
@Uncle-Ulty how big is it in size? Better put a big warning if you share it on the  workshop, if you are gonna make people game crash...

**Comment by tsunamayo** [comment]
Also I would have made something modular, and use the docking tool to build the final circuit... Cheers

**Comment by Uncle-Ulty** [comment]
Wait, for instance, a 1km long track, which consumes less, one 1km entity or several 10m modular entities?

**Comment by Uncle-Ulty** [comment]
I was going to test module performance, so I disconnected from the big track save game, created a new game and loaded, and the high RAM consumption continues, even with default objects. So I suppose I need to close the game and open again...

![image](https://user-images.githubusercontent.com/73253472/106361582-7ee33700-62fd-11eb-8984-f4540d49f8da.png)

**Comment by Uncle-Ulty** [comment]
The entire track (the small one) has these characteristics. Well, dividing it into smaller pieces, would consume less RAM? it's important to know, cuz this serves as a test for future cities and bases inside the ring. If a building of this size can't run properly, it means the ring cities must be very small, a kind of village, in order to work.

![image](https://user-images.githubusercontent.com/73253472/106362839-c967b200-6303-11eb-95ea-a07ecbda946b.png)

**Comment by Uncle-Ulty** [comment]
I'm working on the same track, but I got away from the computer and let the game open. When I came back, the ram consumption dropped... idk why.

![image](https://user-images.githubusercontent.com/73253472/106365227-e2c42a80-6312-11eb-94ae-b44585754fe9.png)

**Comment by tsunamayo** [comment]
Yeah not sure, for sure having a very large entity with some big hole inside is very inefficient because of the large light 3d texture. Basically it will max out at 2gb. With several smaller entity it would be more efficient (or not, it depends you might end up with more ram usage), at least until the light refactor. Did you put light on your build?

**Comment by Uncle-Ulty** [comment]
No, I didn't, because they don't work. Actually, the track is very minimalist, because I know every aesthetic improvement I make will make it heavier for the computer to process...

I'm gonna run some tests... Gonna make a huge hollow cube ( 4 x 4 x 4 km) with 1 entity, and a second one with connected modules working as the edges, and I'm gonna compare the two results...

**Comment by tsunamayo** [comment]
Ffor sure if you make crazy big build the RAM requirement are gonna be through the roof. I might check just to make sure there is no leak or issue but at the end it is a voxel game, dont forget that data grows with the _**cube**_ of length:
a 4x4x4 km is gonna be 8 time bigger than a 2x2x2 km.
So essentially your 4x4x4km is 64000x bigger (40 x 40 x 40) in memory usage than a 100x100x100m ship. Let that sink for a moment... A 100m cubic ship is already a big ship... In your case as it is hollow it wont be that bad (except for the light texture that will give up at 2gb).

**Comment by Uncle-Ulty** [comment]
I ran a test with a 2km x 2km x 2km structure, one with one entity only, and another with 13 modules, and the third test with clear world, without any custom object.

13 modules structure
![image](https://user-images.githubusercontent.com/73253472/107086904-68dfe580-67d9-11eb-8586-bdda5b05dc44.png)

one body structure
![image](https://user-images.githubusercontent.com/73253472/107086988-89a83b00-67d9-11eb-9fe8-dd5261249dfe.png)


now the task manager for each case

![image](https://user-images.githubusercontent.com/73253472/107087040-9dec3800-67d9-11eb-9fc8-01c53a4adb25.png)


![image](https://user-images.githubusercontent.com/73253472/107087071-aa709080-67d9-11eb-9310-3602a583f3f4.png)


![image](https://user-images.githubusercontent.com/73253472/107087100-b65c5280-67d9-11eb-9156-d3a485fdfe0e.png)

I don't see any difference between the two structures (13 small voxels and one big voxel).

Also, when you are building, the RAM consumption is always higher than when you load the structure, examples bellow.

just built, before restart
![image](https://user-images.githubusercontent.com/73253472/107087313-0affcd80-67da-11eb-9a58-fd444c5b9738.png)

load buid, after restart

![Uploading image.png…]()


idk if this helped.

cya!

**Comment by Uncle-Ulty** [comment]
so, based on these results, my guess is: the racing track will consume the same amount of RAM, independently of voxel volume and module quantity.

**Comment by tsunamayo** [comment]
Well I guess now you should be good with neovox!
