### ISSUE TITLE
Ship geometry bugs out rather oddly

### ISSUE THREAD

**Issue by Foxthedark** [tsunamayo/Starship-EVO#3554]
### Short Description of the issue:
I havent played in a while. and decided to play again today. I loaded in one of the ships i built last time i played. And from some angles it weirdly bugs out. almost as if some blocks arent scaled right.

### Steps to reproduce the issue:

Unsure. I included the blueprint
[Scarab.zip](https://github.com/tsunamayo/Starship-EVO/files/5895475/Scarab.zip)

### Environment
- Starship EVO version: 20w49a
- Graphics Card: Radeon Sapphire pulse 550

### Additional information:
![20210129185451_1](https://user-images.githubusercontent.com/39803278/106311187-0761c900-6265-11eb-8874-884f442c4e2f.jpg)
![20210129185443_1](https://user-images.githubusercontent.com/39803278/106311197-0b8de680-6265-11eb-91c2-bdb1df66e2fc.jpg)
![20210129185238_1](https://user-images.githubusercontent.com/39803278/106311209-0f216d80-6265-11eb-9943-fa8d835b320a.jpg)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5895488/output_log.txt)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` or `Player.log` file starting from 21w02a. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Foxthedark Hi, how old was the blueprint? thx

**Comment by cloudrambler** [comment]
This looks similar to #3473.

**Comment by Foxthedark** [comment]
@tsunamayo apologies for the late reply. It was made on the 22nd september of 2020

**Comment by tsunamayo** [comment]
@Foxthedark Could you tell me if you reproduce this issue in the latest experimental? The ship just load fine on my side. Thanks
