### ISSUE TITLE
[Bug] Artefacts in terrain 

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3557]
### Short Description of the issue:
When moving around the ringworld, you can see chunks of the ringworld terrain flashing 
https://i.imgur.com/UyHo4gs.mp4

### Steps to reproduce the issue:
This happened immediately after loading, I enabled no clip mode, fast movement and teleport to all entities then moved around and saw this

### Environment
- Starship EVO version: 21w04b
- Graphics Card: RX 580

### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/5897175/Player.log)

**Comment by tsunamayo** [comment]
Fixed for 21w05a. Thanks!
