### ISSUE TITLE
[Bug] Armour brick collision boxes are incorrect

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3559]
Version: 21w04b

I've noticed that I cannot place down the armour bricks where they technically should fit.
The pieces in question are:
- wedge
- tetra
- hepta
- corner

I'm not using clipping anymore but it sure makes me want to go down that path again.

Here's the world file for you to check it yourself:
[Exp.zip](https://github.com/tsunamayo/Starship-EVO/files/5898641/Exp.zip)

![Starship_EVO_E6GbB3gC7f](https://user-images.githubusercontent.com/63756057/106366929-ec5f8980-6336-11eb-9413-8bea41f49f2a.png)

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo My life is suffering... I literally can't continue working on my projects because of the borked collision boxes.

I would just move the project from the Experimental Branch onto the Legacy Clipping Branch but I just can't spawn it there.

![Starship_EVO_YjGmZpD8W7](https://user-images.githubusercontent.com/63756057/107832045-56d8e680-6d87-11eb-848d-1477075233c2.png)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Hi, I think I have done a fix at one point - tell me if it is not the case!
