### ISSUE TITLE
[BUG] after pasting capacitors game locks up

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3562]
### Short Description of the issue:
after i copy paste capacitors onto a shield block i am unable to delete or place blocks  
...

### Steps to reproduce the issue:
paste a capacitor onto a shield block and attempt to build 
...

### Environment
- Starship EVO version: 21w04b

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5899076/output_log.txt)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/5899077/Player.log)

**Comment by tsunamayo** [comment]
Issue fixed for 21w05c. Thanks!
