### ISSUE TITLE
still teleporting out of ship when exiting chair

### ISSUE THREAD

**Issue by luckyrada** [tsunamayo/Starship-EVO#3563]
### Short Description of the issue:
sry tsunamayo but it seems you didnt quite squash the bug sry

### Steps to reproduce the issue:

get in and out of seat

### Environment
- Starship EVO version: 21w04b
- Graphics Card: intel(r) iris(r) plus graphics 655

### Additional information:

[Player.zip](https://github.com/tsunamayo/Starship-EVO/files/5899078/Player.zip)

**Comment by tsunamayo** [comment]
@luckyrada It is fixed for 21w04c like I said in the comment. You have to wait for the patch release! Cheers

**Comment by luckyrada** [comment]
oh its not released yet? oh im sorry lol i thought it was

**Comment by Kaiser-Indrasil** [comment]
@luckyrada Every patch note will have a yellow "Build Release Note" tag to it.
