### ISSUE TITLE
[Bug] Activating landing gear in light cruise causes blocks to become invisible upon reloading

### ISSUE THREAD

**Issue by TheWanderer05** [tsunamayo/Starship-EVO#3564]
### Short Description of the issue:
Blocks become invisible after reloading a save where a ship's landing gear were activated in lightcruise.
...

### Steps to reproduce the issue:
Fly a ship into lightcruise, then activate the landing gear. The third-person camera will become bugged and pivot around a seemingly arbitrary point near the ship. If the player tries to fix this by reloading the save, many of the ship's blocks will become invisible, but still functional.
...

### Environment
- Starship EVO version: 21w04b
- Graphics Card: GTX 1070

### Additional information:
If the player tries to reproduce this bug without closing the game first, more blocks seem to become invisible, even after respawning the ship. Respawning a ship may also cause some blocks to appear detached from the ship.

_(Screenshots, Videos, Error logs, Related issues)_

Bugged ship below:
![image](https://user-images.githubusercontent.com/37814712/106400934-63f0ef80-63ef-11eb-820e-0cd431ee11ad.png)

Blocks that appear detached from the ship:
![image](https://user-images.githubusercontent.com/37814712/106401027-d792fc80-63ef-11eb-872a-89cac09a8a47.png)

Output logs:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5901014/output_log.txt)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/5901015/Player.log)

Ship file, if needed:
[Warp Testbed Mk2.zip](https://github.com/tsunamayo/Starship-EVO/files/5901021/Warp.Testbed.Mk2.zip)

**Comment by tsunamayo** [comment]
Hi, so I noticed the bug of the 3rd person view and fixed it already. By reloading the save you mean Quit To Title and reload, or loading a blueprint?

**Comment by TheWanderer05** [comment]
> Hi, so I noticed the bug of the 3rd person view and fixed it already. By reloading the save you mean Quit To Title and reload, or loading a blueprint?

By reloading, I meant Quit To Title and reload. Sorry, I should have specified that.

**Comment by tsunamayo** [comment]
@TheWanderer05 This should be fixed in 21w05a. Cheers!
