### ISSUE TITLE
[SUGGESTION] Copy/Paste Functionality Improvements

### ISSUE THREAD

**Issue by tristenbarrett** [tsunamayo/Starship-EVO#3567]
I understand you already have plans to allow for multiple copy-paste tools to be on the bar so I have the following further suggestions:

1)  I think with potential the complexity of reusable parts on this grid scale (think doors, turrets, etc), being able to save a library of parts for use is vital.  If you've ever seen Factorio's take on a blueprint system there's a lot of good ideas there.  An early implementation could simply be a basic save to library, but in the long run a full set of management tools for the library would be great (organisation tools, sharing/publishing, revisioning etc).

2)  It would also be brilliant to have deeper control over the root mounting point.  Perhaps after selecting the volume to be copied, a further click on any individual cube would then set the root? 

3)  While I suspect it's likely a big project or you'd have done it already, I think it the longer term the ability to copy child entities and wiring along with the root will also be very important.

**Comment by tsunamayo** [comment]
@tristenbarrett It has all been added recently. Cheers
