### ISSUE TITLE
Falling through ground [bug] 

### ISSUE THREAD

**Issue by SovietSponge** [tsunamayo/Starship-EVO#3571]
### Short Description of the issue:
Fell through the ground, ground worked properly when I flew back up (love the improved performance BTW, literally doubled my FPS :)) 
...

### Steps to reproduce the issue:
No idea, just happened randomly 
...

### Environment
- Starship EVO version: 21w05a
- Graphics Card: gtx 1050ti

### Additional information:
Will upload output log soon, am unable to access computer at this time

**Comment by Garrett-C** [comment]
Just an added detail the ground in this case is the terrain on the ring.

**Comment by tsunamayo** [comment]
Okay sorry for that one, it was a last minute bugfix that introduced a regression. Fixed for 21w05b. thx
