### ISSUE TITLE
[BUG] Editing a grid affected by a maglock now has limitations.

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#3574]
### Short Description of the issue:

I am building a ship model and in order to orient it to natural light, I have it held by the maglock of another ship. It's been like that for a few days while I made a lot of changes. Then today I found that I could only make one change to that grid per session. After the first change (add or delete brick), it is not possible to make any other changes. Also the highlight (white outline) disappears.

This is a new limitation, so something seems to have been affected by the latest update.

Restarting the game (via desktop) allows a further single change to be made. Alternatively, disconnecting the maglock appears to revert full permissions to change the grid.

### Steps to reproduce the issue:

Make a change to an existing grid that is held by a maglock.
Attempt to make a second change to that grid.

### Environment
- Starship EVO version: 21w05a
- Graphics Card: GTX1070

### Additional information:

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/5927706/Player.log)

**Comment by tsunamayo** [comment]
Indeed I was able to reproduce. I keep you posted!

**Comment by tsunamayo** [comment]
Fixed for 21w05b. Thanks!
