### ISSUE TITLE
[Bug] Targeting AI drunk again

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3575]
Version: 21w05a

Apparently even the NPC turret operators are drunk.
Only my beam boys are somewhat sober.

https://user-images.githubusercontent.com/63756057/106942646-5653a680-671c-11eb-8e8e-e9ea11adf506.mp4

**Comment by tsunamayo** [comment]
Hi, send me your ship ;) Had no issue with mine.

**Comment by Kaiser-Indrasil** [comment]
[Here you go.](https://github.com/tsunamayo/Starship-EVO/files/5929069/SoE.Astero.-.clipping.smooth.exp.zip)
I wonder if the AI's targeting system drunk only in the game, and not in Unity...

**Comment by tsunamayo** [comment]
I dont know, your turret are quite special to be honest ;) but the game should be able to deal with them.

**Comment by Kaiser-Indrasil** [comment]
Admittedly, yeah ;)
But the remaining question is, why would an NPC pirate have their turrets borked, too?

**Comment by tsunamayo** [comment]
Ho sorry indeed the NPC is not shooting at you. Let me check!

**Comment by tsunamayo** [comment]
Okay the issue should be fixed for 21w05b. Thanks!
