### ISSUE TITLE
[BUG] Landing is broken

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Starship-EVO#3577]
### Short Description of the issue:
Landing in shipyard mode means that you can no longer interact with buttons or seats after getting out.
Landing on Landingpad simply doesnt work it touches the ground but never finish the process
### Steps to reproduce the issue:
try to use the shipyardblock on any blueprint to land. 
(2-4 versions previously it worked great)

is not world or blueprint related
### Environment
- Starship EVO version: 21w05a

### Additional information:
[Player.zip](https://github.com/tsunamayo/Starship-EVO/files/5928697/Player.zip)

**Comment by tsunamayo** [comment]
Hi, thanks I will check it out. Did you used your own shipyard or one from a station? Thanks

**Comment by Battlepixel** [comment]
I used the hangar of my own ship. This worked before without errors.

**Comment by tsunamayo** [comment]
@Battlepixel okay, I was able to land / dock without issue. Are you sure the log is the right (it seems from a session with no gameplay). 
Could you send me your blueprints (landing pad and ship), it might be a collision issue that depend on your ship.
Thanks

**Comment by Battlepixel** [comment]
I noticed the bug a week ago. I have reset the world to rule out that it is saverelated.
Today after the new patch I did the test again and the landingpad in the hangar worded fine. The Bug was persistent before. I had tested in different saves with different Blueprints. If you didnt change anything in this direction(in the last patch), 
I can t imagine what caused it.

But okey its working^^
