### ISSUE TITLE
[REQUEST] Centre Of Mass Indicator

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#3578]
Please could we have a simple indicator for the current centre of mass for primary grids. Ideally this would be identical to the point used by the physics engine to determine if something will fall over.

This would be really useful for placing landing gear, when they need to be closer to the centre of the ship for styling reasons.

Personally I would be happy for it to be a debug feature to toggle.

**Comment by tsunamayo** [comment]
I think I already one in debug feature, let me check this.

**Comment by cloudrambler** [comment]
@tsunamayo Turning on entity bounds also shows a small round spot. The spot is not fixed at the bounding box centroid, rather it appears to show the centre of mass. Is that a correct interpretation?

**Comment by cloudrambler** [comment]
If the bounding box spot is the centre of mass, please could you mention it within the Debug Option Text. Something like: "View Entity Bounds & Entity Mass Centre Point". That would help others find it in the future.

**Comment by tsunamayo** [comment]
@cloudrambler I will make it separate.

**Comment by tsunamayo** [comment]
Ok done for 21w05c. Cheers
