### ISSUE TITLE
Incorrect key in tutorial text

### ISSUE THREAD

**Issue by halldorr** [tsunamayo/Starship-EVO#3579]
### Short Description of the issue:

Started a new game and there is the signs in the starting area. One sign says to press F to use the jetpack but it appears that the key is J for jetpack.

### Steps to reproduce the issue:

- Start new game
- Go inside building
- Read second sign

### Environment
- Starship EVO version: 20w49a
- Graphics Card: GeForec GTX 970

### Additional information:

![jetpack](https://user-images.githubusercontent.com/474547/106970059-1db2cd80-671a-11eb-82b9-aae042877dc4.png)

**Comment by tsunamayo** [comment]
@halldorr Thanks a lot for noting that one!

**Comment by tsunamayo** [comment]
Fix for 21w05c. Thanks!
