### ISSUE TITLE
main menu doesn't work

### ISSUE THREAD

**Issue by SovietSponge** [tsunamayo/Starship-EVO#3581]
### Short Description of the issue:
The main menu doesn't do anything no matter what button i press, have to alf+f4 to get out of the game

### Steps to reproduce the issue:
no idea

### Environment
- Starship EVO version: 21w05b
- Graphics Card: gtx 1050Ti

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5931114/output_log.txt)

**Comment by tsunamayo** [comment]
Okay let me check that asap.

**Comment by tsunamayo** [comment]
@SovietSponge Could you try now? Thanks

**Comment by SovietSponge** [comment]
Yep, works now!
