### ISSUE TITLE
Weird piloting bug with held items seen

### ISSUE THREAD

**Issue by matejkar** [tsunamayo/Starship-EVO#3582]
### Short Description of the issue:
After update 21w05a, i cannot enter the main menu, its does not react to any inputs at the screen where it says press any key.

...

### Steps to reproduce the issue:
Launch game in version 21w05a (experimental), and watch the main menu not working
...

### Environment
- Starship EVO version: 21w05a
- Graphics Card: GTX 1060ti 6GB

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` or `Player.log` file starting from 21w02a. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5931339/output_log.txt)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@matejkar okay could you try now? Thanks

**Comment by matejkar** [comment]
@tsunamayo can't atm, but il'l let you know as soon as i do

**Comment by matejkar** [comment]
@tsunamayo yea, thats fixed now, however i now see that unless the character is holding nothing in their hand, the thing they are holding is gonna react to surroundings  when entering pilot seat. For example, the symmetry tool will show the blue symmetry line while piloting the ship, and normal blocks will show the grid they can be placed at. Its seen only in first person tho.
I could do this as a new issue, but im just gonna rename this one.

version: 21w05a
reproduction: in version 21w05a spawn a ship of any size, pick a random block or tool from the inventory, and try to enter the pilot seat of the ship, it will enter but should still show the held item with its reactions to the surroundings. Best examples should be the symmetry tool and small blocks
here are the screenshots and the output log:
![20210205134206_1](https://user-images.githubusercontent.com/69653738/107035288-438eaf80-67b8-11eb-92f9-24d69553625e.jpg)
![20210205134225_1](https://user-images.githubusercontent.com/69653738/107035297-4689a000-67b8-11eb-810a-f522d439dc0e.jpg)
both of those screenshots were taken while piloting the ship, so the "gun" which is used for building is also shown
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5932450/output_log.txt) - this output log seems identical to the first one i sent in this issue to me, but you know better.

**Comment by matejkar** [comment]
here is the blueprint used for the screenshots

[Conqueror - class heavy cruiser.zip](https://github.com/tsunamayo/Starship-EVO/files/5932499/Conqueror.-.class.heavy.cruiser.zip)

**Comment by ProPeach** [comment]
I'm also reproducing the bug when piloting a ship - Here I was holding a block cube before entering the yoke, and it'd still visible afterwards
![image](https://user-images.githubusercontent.com/27857711/107041793-d4fe2180-67b8-11eb-8fc9-24747cdba263.png)

Btw @matejkar the output.log file is no longer used which is probably why it's the same, information is stored in the Player file now, this one
![image](https://user-images.githubusercontent.com/27857711/107041999-1db5da80-67b9-11eb-8457-7567ff980df5.png)

**Comment by matejkar** [comment]
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/5933158/Player.log)
here

**Comment by tsunamayo** [comment]
Yep thats seems to be a regression...

**Comment by tsunamayo** [comment]
Issue fixed for 21w05c. Thanks all!
