### ISSUE TITLE
[Problem] New hovercraft control system is incorrectly set up

### ISSUE THREAD

**Issue by zorozeenee** [tsunamayo/Starship-EVO#3584]
### Short Description of the issue:
New hovercraft control system is really annoying to deal with and here is why

Previously a hovercraft could turn without having to thrust in the opposite direction to slow down. You could go forward turn and stop at the same time. This was convenient and offered an easily controllable hovercraft that operated much like vehicles in many other games.

With the new system you no longer can turn while stopping, instead you have to come to complete stop before you can turn because the system doesnt have sideways thrust, only forward or back. Pressing A or D simply turns your vehicle. The effect of this is that your vehicle if you attempt to turn your ship will continue its momentum until you can align with the direction of the momentum and either reverse or go forward to come to a complete stop.

To fix this you simply revert it to the old system which was fine and preferable.

or

Allow sideways thrust to counteract the new problem, meaning when you press A or D your hovercraft would STRAFE left or right. A new key would then have to be assigned to TURN your vehicle from left to right or vice versa.

**Comment by TIKIRobo** [comment]
It seems that this is just a problem with the new physics, they move as if they were driving on ice

**Comment by zorozeenee** [comment]
yea if you could thrust sideways it would be fixed tho, but honestly i prefer the old system
time to switch off experimental mode

**Comment by Kaiser-Indrasil** [comment]
> Allow sideways thrust to counteract the new problem, meaning when you press A or D your hovercraft would STRAFE left or right. A new key would then have to be assigned to TURN your vehicle from left to right or vice versa.

Imho, it would be best if we could strafe with A and D, and yaw using the mouse instead, bringing the control scheme much closer to that of spaceships.

Pitching would be great too, especially since we don't have gimbal on the fixed guns mounted on hovercraft.

**Comment by zorozeenee** [comment]
> > Allow sideways thrust to counteract the new problem, meaning when you press A or D your hovercraft would STRAFE left or right. A new key would then have to be assigned to TURN your vehicle from left to right or vice versa.
> 
> Imho, it would be best if we could strafe with A and D, and yaw using the mouse instead, bringing the control scheme much closer to that of spaceships.
> 
> Pitching would be great too, especially since we don't have gimbal on the fixed guns mounted on hovercraft.

No that would be a terrible idea, because then you couldnt rotate your turret and still be driving in a different direction similar to how tanks drive.

**Comment by tsunamayo** [comment]
Actually I had many bad review of the old system saying it didnt feel like a hovercraft. New one is physics based (and works like real world hovercraft btw).
If you want less lateral drift you will need to increase the agility rating of your hovercraft by adding some side thrusters.
For the strafing I will think about it. Cheers

**Comment by tsunamayo** [comment]
@zorozeenee Okay sorry I had a look but it actually a regression (I guess since the rigidbody patch). It is undrivable atm, I will fix this.

**Comment by tsunamayo** [comment]
@zorozeenee Issue fixed for 21w05c. Thanks
