### ISSUE TITLE
Audio pisses off

### ISSUE THREAD

**Issue by TurklerRS** [tsunamayo/Starship-EVO#3585]
### Short Description of the issue:
Audio goes away for some reason
...

### Steps to reproduce the issue:
Just fly then land.
...

### Environment
- Starship EVO version:  Experimental
- Graphics Card: 1050Ti 5 gig

No audio, no blueprints. just flew around a tad bit and aduio was gone when I landed back. menu sounds also don't work, though the music still played.

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/5937037/Player.log)

**Comment by TurklerRS** [comment]
also note that no amount of reloading the game fixes it. I'm sure the game isn't muted because music still plays. the game literally has no sound now

**Comment by ProPeach** [comment]
To follow up on this, we talked it over on Discord and found that the game volume slider had been reset to 0%, seemingly by itself

**Comment by tsunamayo** [comment]
@TurklerRS I see... You are 100% you didnt put the volume at 0? Did you touch other settings? When this happened you where simply flying? Thanks
