### ISSUE TITLE
[BUG] Switch hitbox too large

### ISSUE THREAD

**Issue by Facest4b** [tsunamayo/Starship-EVO#3588]
### Short Description of the issue:

Recently I have been unable to open my logic racks, they get stuck open by a small amount. I think this is because of the size of the switch hitbox being changed to be too large, as removing the switches allows them to open fully.

There is visually more than enough clearance between the switches and the wall, so logically it should open.

### Environment
- Starship EVO version: 21w05b
- Graphics Card: RTX 2070 Super

### Additional information:

https://imgur.com/a/mwLrglh
[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/5937754/output_log.zip)

**Comment by tsunamayo** [comment]
ohh yes the logic box. This one is gonna be one of the most popular prefab on the workshop when I add that feature. I indeed had to tweak the switch hitbox recently. Could you send me your ship so I can use it to make it work? Thanks

**Comment by ProPeach** [comment]
Would it be possible to slim down the regular logic brick too? They're just *slightly* too tall for a half brick, same as the switch

![image](https://user-images.githubusercontent.com/27857711/107133264-513e5500-68de-11eb-8968-124be9d13dde.png)

**Comment by Facest4b** [comment]
> ohh yes the logic box. This one is gonna be one of the most popular prefab on the workshop when I add that feature. I indeed had to tweak the switch hitbox recently. Could you send me your ship so I can use it to make it work? Thanks

Here you go! Thanks for quick response.

https://www.dropbox.com/s/f5egtfkniox1ek3/Y2K%20Class%20Freighter%20Rounded%20v2.zip?dl=0

**Comment by tsunamayo** [comment]
@Facest4b Okay issue fixed for 21w05c. I also reduced the bounding box of all the logic command @ProPeach, but I didnt updated the model yet.
Thanks
