### ISSUE TITLE
Overload at load

### ISSUE THREAD

**Issue by Gadgetroch** [tsunamayo/Starship-EVO#3589]
### Short Description of the issue:

Program needed to close when load first game

### Steps to reproduce the issue:

Create a game and launch it

### Environment
Last
Nvidia GTX 1050 TI
Proton - Debian 10

**Comment by Gadgetroch** [comment]
Hi
If you can't help me, i will ask for refund... :(

**Comment by tsunamayo** [comment]
@Gadgetroch Hello, sorry yes Linus is not supported... I know for a fact that some people are playing the game on Linux but I cant support it. Thanks
