### ISSUE TITLE
[BUG] Multiplayer doesn't work 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3591]
### Short Description of the issue:
When joining my friend it just reverts to the main menu, if I join one of my own worlds and then quit to title and then join my friend I just get put into my world instead of my friends 
...

### Steps to reproduce the issue:
Join a friend (i used ZeroTier so that might have effected it) 
Or
Start a new world then quit to tile then  join your friend 
...

### Environment
- Starship EVO version: 21w05b

### Additional information:

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/5940504/Player.log)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5940505/output_log.txt)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/5940506/Player-prev.log)

**Comment by COMICLER** [comment]
_ was the host, we were using zerotier _

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5940527/output_log.txt)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/5940528/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/5940529/Player-prev.log)

**Comment by Garrett-C** [comment]
Odd I hosted a game the other day and while we did see a variety of issues mostly related to syncing we were certainly in mp together on the same world etc.

Also worth noting is you should always quit to desktop before joining a mp game.

**Comment by ProPeach** [comment]
Although @Garrett-C when I was trying to join you with Womble already in the world, I was getting the same issue as TIKI where joining a multiplayer game would drop me back into the main menu a few seconds after joining

**Comment by tsunamayo** [comment]
I think the Join your Own world is a different one, related to the quit to title (most likely a stupid bug). There is quite a few issues in your log, I will investigate and keep you posted. Was the host doing something in the world when the client joined?
Also do you confirm it is doing this all the time?
 Thanks

**Comment by Vicomt** [comment]
can confirm multiple issues in MP. client connected to my host was invisible, also host was invisible to client, when client and host both sat in a ship and the ship was moved, only the host perceived any change in location.

**Comment by TIKIRobo** [comment]
@tsunamayo if I remember correctly he had just restarted, i will try to confirm that it happens often later

**Comment by Garrett-C** [comment]
> Although @Garrett-C when I was trying to join you with Womble already in the world, I was getting the same issue as TIKI where joining a multiplayer game would drop me back into the main menu a few seconds after joining

Very true yeah. 



> can confirm multiple issues in MP. client connected to my host was invisible, also host was invisible to client, when client and host both sat in a ship and the ship was moved, only the host perceived any change in location.

Interesting. When we tried it recently with 3 players we had an interesting varietry.

1. Host could see the shadow of the first player to connect. (The multi tool was also visible when the client held a link tool)
2. Host could see the second person
3. Second person could see host but no ships were visible, despite them definitely existing as confirmed by the selection boxes when piloting a ship.
4. Neither client or host could see any movement from ships. Child entity movement was visible though.

**Comment by tsunamayo** [comment]
@Garrett-C @TIKIRobo Hi, so I have finally made some fixes for 22w04a. I think we will still find a lot of issues but I was able to connect, build, see npcs ship moving, fly and spawn ships. Please book any issue you might find!
Thanks
