### ISSUE TITLE
[QUESTION] Docking ports

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3592]
I know that docking ports are planned but:

1 will docked thing be saved?
Basically if i dock an escape pod to a ship will it get saved if i save the main ships BP?
2 Will ships be mergeable with docking ports?
I actually have i suggestion for this, small docking port should not allow merging because then the different entity's grids would be unaligned, but because large docking ports have to be on the block grid they would remain aligned.
3 will docking ports emit a signal when something is docked to them?

**Comment by tsunamayo** [comment]
Hi @TIKIRobo 
1) I will work on that yep.
2) not sure to understand, merge is they become the same entity? If that is that then no.
3)Yes! Through the yet to be added signal / event / output gate (I need to find the right name)
Cheers

**Comment by TIKIRobo** [comment]
@tsunamayo  yea merging would become one entity, although if docking ports can transfer energy and other things it wouldn't need to become one entity

**Comment by zalexville** [comment]
Basically if we can dock escape pods/other ships it would be neat to be able to take a blueprint of the main ship and it also remember the child ships that are docked to a port. This would make it easier for us to use escape pods and such as we would not need to redock them all everytime we spawn the main ship.
