### ISSUE TITLE
[BUG] OR gates somehow break logic circuits 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3595]
### Short Description of the issue:
when activating a ABBA circuit with an OR gate the ABBA works improperly 
...

### Steps to reproduce the issue:
Make an ABBA gate, then link an OR gate to the switch then a button to the OR
...

### Environment
- Starship EVO version: 21w05c

### Additional information:

Video of it in action 
https://user-images.githubusercontent.com/56371294/107242172-efb6dd00-69e8-11eb-8d96-b5f7edc0b8c1.mp4

test ship:
[Test Area #2.zip](https://github.com/tsunamayo/Starship-EVO/files/5944713/Test.Area.2.zip)

**Comment by ProPeach** [comment]
I can also reproduce this as we were working through trying to isolate this bug, the OR gate is what causes the issue. The signal travels through the circuit fine until after the switch - the switch behaves as it should when toggled by the button through the OR gate, but something goes wrong after that which causes the circuit to not work as it does when you just toggle the switch manually, ignoring the OR gate. A real strange one!

**Comment by tsunamayo** [comment]
Hi all, this is fixed for 21w06a. It was a regression because I actually fixed a performance bug regarding logic gate (that could have explained lag after many use). Cheers!
