### ISSUE TITLE
[Suggestion] Workshop Posts Fix

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#3599]
In the workshop, there are lots of posted builds with the basic New Entity name. Seems to be a mix of random creations, half finished builds, finished builds that the builder forgot to rename, etc. Would it be possible to require a renaming from new-entity before posting?

![image](https://user-images.githubusercontent.com/36980446/107302254-52849480-6a3a-11eb-849f-26045feaff4c.png)

Also this problem has not come up just yet, but are there any safe guards in place to prevent a player from spamming random crap maliciously to the workshop?

**Comment by tsunamayo** [comment]
Well I guess random crap is very suggestive, so I dont think there is quite a way. Player can upvote submission, so thats the best filter you can ever create. Cheers
