### ISSUE TITLE
Voxel Problems

### ISSUE THREAD

**Issue by Cyclicwheel780** [tsunamayo/Starship-EVO#3600]
I am currently working on my gimbal weapons but I can’t get the large weapons to be place on the turret I made for them. Original I thought the surface of the turrets weapon attachment area was too small so I worked on testing different sizes of attachment areas but no dice. Additionally, I know there is a way to connect the voxels to the brick grid but I can’t figure out how.

**Comment by ProPeach** [comment]
Can you show a picture of your setup?
A couple of things that might be causing issues -
-Large weapons cannot be placed on small scale mechansisms
-Large weapons only comply to the large (1m) grid, so if you've built a platform out of small bricks (25cm) the surface you try to place the large weapon on might be offset

**Comment by tsunamayo** [comment]
@Cyclicwheel780 Hi, ProPeach is right, could you please send a screen of your setup? Thanks
