### ISSUE TITLE
[BUG] All editable objects disapear, randomly. 

### ISSUE THREAD

**Issue by DutchWorkingMan** [tsunamayo/Starship-EVO#3601]
### Short Description of the issue: 

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5959186/output_log.txt)
[ORION 21 b12.zip](https://github.com/tsunamayo/Starship-EVO/files/5959208/ORION.21.b12.zip)

All editable objects disapear, only ringworld exist. 

A strange thing happened after the last disapearing bug. Normally I have a framerate of 67. Now the highest is only 24, mostly 17. I tried a new game, and even reinstalled it, but the problem doesn't solve. It's stuck with a low framerate and makes it a terrible gameplay, often falling through the floor now. 

This is only with EVO, the other games works normally. 
...

### Steps to reproduce the issue:

This happens randomly. 

- Working on complex ship, with a lot removing, and replacing objects. Last time I was working with logic. 
- I saved the ship first and 
- went back to windows via the menu.
- When I start the game again, everything was gone. 
 

### Environment
- Starship EVO version: 20w49a
- Graphics Card: GTX 1080

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` or `Player.log` file starting from 21w02a. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by DutchWorkingMan** [comment]
I found out that I could get the last version of EVO. I play now version 21w05c.  FPS is normal now,  around 70. I don't know if this issue is already solved with this version. If this happens again, I let you know.

**Comment by tsunamayo** [comment]
@DutchWorkingMan Hi, thanks I was going to suggest this too. I will push that patch to the DEFAULT branch as it is seems to be more stable now. 
Thanks!
