### ISSUE TITLE
Copy/paste for stickers

### ISSUE THREAD

**Issue by schlid** [tsunamayo/Starship-EVO#3602]
Unsure how difficult this would be to include, but making copy/paste include stickers in the clipboard would be very helpful, especially to save time repeating layered designs.

**Comment by tsunamayo** [comment]
Yep, the only thing to think about is how to select which mode. Maybe a dedicated tool for stickers only? Cheers

**Comment by schlid** [comment]
Yeah either integrating it so you can copy stickered surfaces as a whole, or a way to just copy them individually. Either would work really.

**Comment by TIKIRobo** [comment]
I feel like both would work best so that if you want to copy just a logo you could or if you want to copy a whole room with all decals at once you could do that too

**Comment by ZachZent** [comment]
If the sticker tool are more functionality beyond just a copy paste tool for stickers, I wouldn't mind both. Like a future way to add custom stickers, save existing ones, etc. Sort of like a prefab tool

**Comment by tsunamayo** [comment]
Should be possible now. Thanks
