### ISSUE TITLE
Moon inside the Gas Giant Ring - Build 21w06a

### ISSUE THREAD

**Issue by zalexville** [tsunamayo/Starship-EVO#3605]
### Short Description of the issue:

Planets (specifically Moons) spawn a bit close to each other. 

### Steps to reproduce the issue:

Found in the Virminus Star System. Unknown other parameters causing such a generated position.

### Environment
- Starship EVO version: Build 21w06a
- Graphics Card: GTX 1050ti

### Additional information:

![20210212121432_1](https://user-images.githubusercontent.com/65626266/107800731-26fcf500-6d2d-11eb-9fd0-9458e56a8352.jpg)
![20210212121618_1](https://user-images.githubusercontent.com/65626266/107800732-27958b80-6d2d-11eb-99a3-80358535199b.jpg)
![20210212121828_1](https://user-images.githubusercontent.com/65626266/107800734-27958b80-6d2d-11eb-872e-8aaaaf08831b.jpg)

In my opinion, I like that this can occur. I suggest maybe giving the ring a min/max distance for moon spawns for it but I do like the idea that moons can spawn quite close to other things.

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5973393/output_log.txt)

**Comment by zalexville** [comment]
FYI: I am on the normal branch, not experimental

**Comment by ZachZent** [comment]
Just to add a thought, maybe have planets and especially moons not be 100% on the same plane as planets, some of them up and others down. Adds a bit of verticality.

**Comment by tsunamayo** [comment]
@ZachZent there is orbital inclination, but it is more rare. I get back to you on the bug. thx

**Comment by tsunamayo** [comment]
Fixed for 21w06b. Thanks!
