### ISSUE TITLE
[SUGGESTION] Visibility groups or styles

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#3607]
STEVO allows us to make great ships that are detailed on the outside and inside. We can see each of those aspects separately, but we cannot directly visualise the internal arrangement within the context of the outer form.

My request is to have a method to visualise the whole ship as a three dimensional solid and not just the apparent surface items. The method could be a highlighted transparency like the damage overlay, or it could be a section plane that is moved about, or it could be done by putting blocks & bricks into groups with visibility control.

- This would be very useful for ship design and building as we could see how the internal structures fit within the outer form, allowing better and more consistent use of space. It would also solve the problem of having choose between building from the inside out or outside in, as both methods could be iterated as required.
- It would be a useful format to view the activities of NPC crew within the ship, as you could see where they all are within the ship without having to search for them on foot. Perhaps this would be available through a monitor.
- A transparent or sectional view would also be useful for workshop ships, as it allows others to understand the layout.

**Comment by tsunamayo** [comment]
@cloudrambler Hi, you can already check the F3/Culling/View overdraw option. In 21w06b I have added a new View overdraw overlay which might be closer that what you want. But you will be disappointed it is not really looking that readable.

**Comment by cloudrambler** [comment]
@tsunamayo The new style overdraw is pretty good and I think it will be a useful tool.

It could have more clarity; perhaps if you are interested to take it on a stage, then adding a few extra colours would be great. My suggestion would be to keep the light orange for primary bricks and hull blocks, use blue for system components, and then green for all the decorative stuff. That would be enough classification to see where major elements are within the whole.

Also as feedback to the latest change, the options for "View Overdraw" and "View Overdraw as Overlay" look identical, and are noticeably different from the old style "View Overdraw". My guess is the old style should not have changed.
