### ISSUE TITLE
World loading issue

### ISSUE THREAD

**Issue by KodaiRyu** [tsunamayo/Starship-EVO#3608]
### Short Description of the issue:

When i create game i enter to world with invisible objects and when i load old game i enter to world without "halo planet"

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 21w06a
- Graphics Card: MSI Radeon RX 5700 XT Gaming X

### Additional information:
new world: https://i.imgur.com/KPYdmkr.jpg
old world: https://i.imgur.com/FxQhwpB.jpeg
[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/5975611/output_log.zip)
Haven't made blueprints or use one

**Comment by tsunamayo** [comment]
@KodaiRyu Hi, could you send the player.log file instead? Thanks

**Comment by RockefellerDoctor** [comment]
Part of this is due to the new update to the Default build, changes how the world generation seed builds your world. My preexisting world before the update was now floating in empty space. Starting a new world fixed it.

**Comment by tsunamayo** [comment]
@RockefellerDoctor yes that explains for the old world, but I still need to fix the issue with the first world. Thanks

**Comment by KodaiRyu** [comment]
Here :)
[Player.zip](https://github.com/tsunamayo/Starship-EVO/files/5976941/Player.zip)
