### ISSUE TITLE
Suggestion: Relative Sequencer values

### ISSUE THREAD

**Issue by Cpt-Fortius** [tsunamayo/Starship-EVO#3610]
It'd be useful for building fancy moving parts, to have the ability for sequencers to issue relative commands;

A selector box in the sequencer pop-up menu could be added, where the player sets if the sequencer's output is "absolute" or "relative";

Set to "absolute" on= 10, it still makes the attached rotor turn to it's 10 degree pose, just like it does now.

Set to "relative" 10, it turns the attached rotor 10 degrees in the positive direction from wherever it is pointing now.

Set to "relative" -10, it turns the attached rotor 10 degrees in the negative direction from wherever it is pointing now.

Potential uses:

-Infinite spin (radar dishes, custom rotary weapons, etc)

-Sensor guided self-adjusting landing gear: Makes piston / rotor / hinge move +/- X amount if sensor is active (touching ground)

-Not having to re-build a rotor mounted moving part because I want it to turn in the negative direction, but it can only go in the positive.

-Making a logic system for sending more or less power to ship components based on various conditions.

**Comment by tsunamayo** [comment]
Okay I dont quite think I could allow the infinite spin just yet (collisions check are expensive).
I will add a way to tweak the origin of the motion though.
Cheers
