### ISSUE TITLE
[Bug] Bad collision boxes on bricks

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3611]
Version: 21w06a

My life is suffering... I literally can't continue working on my projects because of the borked collision boxes.

I would just move the project from the Experimental Branch onto the Legacy Clipping Branch but it just refuses to spawn there.

Looks like every armour brick aside from the cube has been affected ever since the Big Clipping Update.

I've had many cases where I couldn't place down bricks next to other bricks located on child entities slanted at an angle.

Here's the world for you to try it out yourself: [Exp.zip](https://github.com/tsunamayo/Starship-EVO/files/5976837/Exp.zip)

![Starship_EVO_YjGmZpD8W7](https://user-images.githubusercontent.com/63756057/107865760-01bdd300-6e62-11eb-9381-863d964ca137.png)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Okay got it, I am looking at this now.

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Could you send me a save at the position of your screenshot? or send me a larger screenshot of where to find the faulty position? I cant find a bugged out placement.

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo Sure - the save I sent you has the character facing this exact spot below. Try to place down the armour bricks in different positions on this exact face:

![Starship_EVO_wPjlI0dzmz](https://user-images.githubusercontent.com/63756057/107880342-03c17980-6ed6-11eb-855f-4795cdc264f6.jpg)

![Starship_EVO_fXn6rDRTt5](https://user-images.githubusercontent.com/63756057/107880347-06bc6a00-6ed6-11eb-9db6-2c292e801717.jpg)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Okay sorry for the screen below, this one is not supported, I would need a full SAT on the wedge shape. I will put that on my to-do list it should not be too hard but it will take a bit of time to get there, that is quite a niche case.
I think the first one should be good now though, I spotted a bug and fixed it. 
What will work now: 
 - bouding box do not overlap
 - for non-box shapes: all points of the other shape are outside an inside face (ie the wedge face for example, or the bezel face in the hepta). This check was not working for different entity, it is fixed now (first screenshot)
Unfortunately your second screenshot case is even more tricky, I need to test additional axes.
Cheers

**Comment by Kaiser-Indrasil** [comment]
Thanks very much for looking into it, looking forward for the SAT pass!

**Comment by ProPeach** [comment]
Bit of a long shot, but would those collision improvements help out with the old left/right corner bricks from #1135? They were really fantastic shapes

**Comment by tsunamayo** [comment]
@ProPeach Yep indeed ;) depending on how I implement it this would mean this shape could be supported but only for the bricks - bricks collisions. Still need raycast and closest point, but I guess a simple check per triangles could be enough. It would still require a bit of time to get there though.

**Comment by ProPeach** [comment]
That's brilliant! Thank you for keeping it in mind 😄

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo 6th form would be amazing for my applications, especially in the brick form!

Meanwhile, I've discovered that the currect collision check doesn't notice no-clip in some cases. 👀 

![image](https://user-images.githubusercontent.com/63756057/107946678-47c18680-6f89-11eb-87f6-bed93dbfdd6f.png)
