### ISSUE TITLE
Bricks not placed at cursor when building handheld weapons

### ISSUE THREAD

**Issue by Cpt-Fortius** [tsunamayo/Starship-EVO#3613]
### Short Description of the issue:

When building handheld weapons floating on an item stand, new bricks appear offset from cursor's location. Weapon dropped on the ground doesn't show same problem.

### Steps to reproduce the issue:

Place bricks on a handheld weapon on an item stand

### Environment
- Starship EVO version: 
- Graphics Card: r9 
![20210214031816_1](https://user-images.githubusercontent.com/38191224/107866766-4a7e8780-6e74-11eb-9a94-94068e18dd81.jpg)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/5976895/Player.log)

290

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Cpt-Fortius Thanks, issue fixed for 21w06a. Cheers
