### ISSUE TITLE
[BUG] Request Landing button misalignment

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#3614]
The "Request Landing" function is very unreliable. I can select the landing pad target, which is shown as free. I can move the cursor over the Request Landing button. But the button acknowledges this action <5% of the attempts; it just does not highlight when the cursor moves over it and so cannot complete the action. This has occurred for every ship and every world I have used the function with since starting with the game back in August. Maybe this works for everyone else, but for me it is really frustrating to work with.

I have actually (just) noticed a specific aspect of the problem. The screen location which corresponds to the button selection area does not always line up with the visible button. If I scan the screen for the selection area (which is in a different place each time), then the function progresses. The same problem occurs with the cancel button.

The problem seems to occur whether the pilot is seated or not.

### Environment
- Starship EVO version: 21w06a
- Graphics Card: GTX1070

### Additional information:

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/5978340/Player.log)

**Comment by tsunamayo** [comment]
@cloudrambler Hi what is your screen resolution? Thanks

**Comment by cloudrambler** [comment]
@tsunamayo I always play at 3840x2160.

**Comment by tsunamayo** [comment]
@cloudrambler okay I guess it is a UI scaling issue. Let me check.

**Comment by tsunamayo** [comment]
Deprecated. Thanks
