### ISSUE TITLE
[BUG] Performance Early-access build

### ISSUE THREAD

**Issue by MRonlin** [tsunamayo/Starship-EVO#3615]
### Short Description of the issue:
When opening the codex building drone on large ships the Fps permanently drops by 50% even when not in the codex. reloading the world fixes the issue.

### Steps to reproduce the issue:
Early-access 21w06a open codex building drone

### Environment
- Starship EVO version: Early-access 21w06a
- Graphics Card: gtx 1050

You can find the log file here: 
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/5978704/Player.log)

**Comment by Kaiser-Indrasil** [comment]
Could you include the ship that drops the most FPS like that?

**Comment by tsunamayo** [comment]
@MRonlin Hi, yep if you could send the blueprint. Thanks!

**Comment by MRonlin** [comment]
@tsunamayo 
[Astrodight.zip](https://github.com/tsunamayo/Starship-EVO/files/5978788/Astrodight.zip)

**Comment by tsunamayo** [comment]
@MRonlin Okay thanks for booking that one, I can reproduce big time, that must be something very wrong. I keep you posted.

**Comment by MRonlin** [comment]
Thanks very much.

**Comment by tsunamayo** [comment]
@MRonlin Issue fixed for 21w06a. Not 100% sure though, as it was linked to SSAO which I have been tweaking for this very update. Please ping me if it is not the case. Thanks!
