### ISSUE TITLE
[SUGGESTION] Remote Input Device 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3620]
The remote input device (which I'm just going to call RID) could send logic from ship to ship. 
It would work by linking a button or switch or what ever into the RID which would then send the signal to any other RIDs that match the first RID's settings.
You could change the RID's frequency (a number from 0-999)  and you could set the RID's range (in meters) form 1m to 1km, any other RID in range and with the same frequency would then be triggered, this way if you have an escape pod system that you want to have trigger a timer on the main craft by hitting a button in the scape pod your could and by changing the range all escape pods and escape pod tubes could have the same frequency but they escape pod in tube 1 would only activate tube 1's RID.

I don't know if I explained this very well so just let me know if you have questions 
Also any other way to do inter-ship logic could also work

**Comment by Briaireous** [comment]
this some good shit, if that becomes a thing, then the trailers for my truck can be a separate entity and I would still be able to hook up the turn signals to it

**Comment by tsunamayo** [comment]
Hi, we have several suggestion about this so I will close this one. thx
