### ISSUE TITLE
hovercars won't stay on their parkingspot after landing

### ISSUE THREAD

**Issue by Paul-van-Hummel** [tsunamayo/Starship-EVO#3622]
### Short Description of the issue:
Hi dear developers,

I've have a problem regarding landing a hovercraft on a platform or anywhere in the planetring sadly, and this problem started with the last update to 21w06a. The crafts don't stay where it is landed, and start jumping out of it's own. 

Also had a minor problem, that with my play file I've have, After the update the whole planetring was missing and all my builds were floating in space (solved that by saving my builds and started a new file to build on the planetring for it's gravity.
Hoping that you already are aware of this problem 

I wanna adress one personal problem I have, I've been building Voyager with the rotating necelles, However, the necelles are so big (true to scale 64m in length) that they can't rotate because the childerenentity is to heavy (over 1000x) and this is while they are still hollow... Maybe there can be added a mass enthanser to the rotators (Idea?)
 And another thing that would make my build stand more out if it would be possible is to make logic connect to the warp core (Than I can make the rotation full automatic on Voyager when going to warp) :) (idea nr2)

Thanks in advance for reading.

Paul (The Netherlands)

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by Briaireous** [comment]
Indeed, I was just talking with some ppl on the discord yesterday about how the hovers would dance alittle when parked
