### ISSUE TITLE
Vehicles launched from the ground

### ISSUE THREAD

**Issue by Cpt-Fortius** [tsunamayo/Starship-EVO#3624]
### Short Description of the issue:

When parked on the ringworld:

-Starships and hovercraft the player interacted with previously will get lauched to space with great force after entering and exiting Photo Mode.

-Hovercraft will get launched into the air with less force, if the player opens the hovercraft core's menu.

### Steps to reproduce the issue:

Be on the ringworld.

A: Pilot any ship or hovercraft, exit yoke to land on the ground. Enter and exit photo mode.

B: Open hovercraft core menu on any hovercraft.

### Environment
- Starship EVO version: 21w06a , hovercraft jumping existed in previous release as well.

**Comment by Cpt-Fortius** [comment]
Update: Present in 21w07a

**Comment by tsunamayo** [comment]
@Cpt-Fortius Hi, this should be finally fixed in 22w04a. Thanks
