### ISSUE TITLE
[BUG] after deleting invisible block game crashed 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3626]
### Short Description of the issue:
after i deleted an invisible laser block my game crashed 
...

### Steps to reproduce the issue:
get invisible laser block, i find that playing around will a lot of decals will make invisible blocks appear faster
...

### Environment
- Starship EVO version: 21w06b
- Graphics Card: Radeon RX 5600 XT

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/6005336/output_log.txt)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6005337/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/6005338/Player-prev.log)
world:
[TIKI_002.zip](https://github.com/tsunamayo/Starship-EVO/files/6005341/TIKI_002.zip)

**Comment by tsunamayo** [comment]
Should be f
