### ISSUE TITLE
[BUG] when landing ships on other ships then tend to "bounce" around a lot

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3627]
### Short Description of the issue:
when landing my micro fighters they like to bounce up and down a bit before fully docking 
...

### Steps to reproduce the issue:
land the included small ship onto the larger one a few times
...

### Environment
- Starship EVO version: 21w06b

### Additional information:

https://user-images.githubusercontent.com/56371294/108417450-38427780-71ed-11eb-93f8-72be975900b1.mp4

[AF-USB-2342-01.zip](https://github.com/tsunamayo/Starship-EVO/files/6005702/AF-USB-2342-01.zip)
[SRD-1731-03.zip](https://github.com/tsunamayo/Starship-EVO/files/6005703/SRD-1731-03.zip)

**Comment by TIKIRobo** [comment]
it would also be nice if ships tried to land a bit more "centered" on the landing pads so that they might line up better for any future refueling systems or docking systems

**Comment by tsunamayo** [comment]
I think it has been improved in recent version. Thanks
