### ISSUE TITLE
[BUG] new ships save improperly 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3629]
### Short Description of the issue:
new ships will save without a "good" preview image 
...

### Steps to reproduce the issue:
place down a starter block build something save it then check in starter block 
...

### Environment
- Starship EVO version: 21w06b

### Additional information:

![image](https://user-images.githubusercontent.com/56371294/108516940-09c3ab80-7284-11eb-84fe-8d5ced7b49e8.png)

![image](https://user-images.githubusercontent.com/56371294/108517073-2e1f8800-7284-11eb-9377-947d80ebc3ff.png)

**Comment by tsunamayo** [comment]
Hi, issue fixed for 21w07a.  Thanks!
