### ISSUE TITLE
[Bug] Large FPS drop after opening ship computer

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Starship-EVO#3630]
### Short Description of the issue:

Game runs fine at a stable FPS but once you open and close the ship computer it becomes a slide show.

### Steps to reproduce the issue:

Open a ship computer on a ship.

### Environment
- Starship EVO version: 21w06b
- Graphics Card: RTX 3070

### Additional information:

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6013514/Player.log)

**Comment by tsunamayo** [comment]
Yep sorry this bug is fixed in next update, I am trapped into something but will do the build soon. Thanks

**Comment by tsunamayo** [comment]
@Garrett-C sorry actually the fix is already there is 21w06b (experimental). Thanks!

**Comment by Garrett-C** [comment]
> @Garrett-C sorry actually the fix is already there is 21w06b (experimental). Thanks!

Odd I was using 21w06b when I noticed the issue.

**Comment by tsunamayo** [comment]
okay sounds bad, could you send me your ship?

**Comment by tsunamayo** [comment]
So the previous issue I fixed was with the codex. I just fixed it with the spaceship computer. Thanks for pointing that one. I am pushing 21w07a now.

**Comment by Garrett-C** [comment]
[Venator for t dawg save.zip](https://github.com/tsunamayo/Starship-EVO/files/6013752/Venator.for.t.dawg.save.zip)

Np here you go. I noticed it on this ship, I also noticed it on a couple from the work shop and peach also noticed it on his ships.

**Comment by Garrett-C** [comment]
> So the previous issue I fixed was with the codex. I just fixed it with the spaceship computer. Thanks for pointing that one. I am pushing 21w07a now.

Oh missed this lo. nice ty.
