### ISSUE TITLE
[Bug]  Game crashes after travelling to different star and spawning new ship

### ISSUE THREAD

**Issue by Calvert4096** [tsunamayo/Starship-EVO#3632]
### Short Description of the issue:

Game crashes after traveling to different star and spawning new ship (ProPeach's A-wing)

### Steps to reproduce the issue:

0) Started fresh save
1) Spawned Danube-class runabout from workshop, added additional warp engines
2) Travelled to nearest star system
3) Flew in the vicinity of gas giant
4) De-spawned runabout
5) Spawned A-wing

The game stuttered for a few frames, showing the ship, the crashed during the shield animation.

### Environment

    Starship EVO version: 21w07a
    Graphics Card: AMD Radeon HD 7800 Series (ID=0x679e)

### Additional information:
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/6014009/Player-prev.log)

A-wing used as-is: https://steamcommunity.com/sharedfiles/filedetails/?id=2186636546

**Comment by tsunamayo** [comment]
Okay I keep you posted.

**Comment by tsunamayo** [comment]
So I pushed a new build where I unplug the new BVH data, (it was not really used anyway yet) until I fixed the issue. Thanks
