### ISSUE TITLE
Failure to run using Steam Play

### ISSUE THREAD

**Issue by douglas-moyes** [tsunamayo/Starship-EVO#3633]
### Short Description of the issue:
Game menu loads, but the game crashes when trying to start a game. 
...

### Steps to reproduce the issue:
Run game, create new character, attempt to start game, see the splash screen, listen to some music, then nothing happens.
...

### Environment
- Starship EVO version: Latest
- Graphics Card: nVidia GTX 1660 Ti
- Ubuntu 20.04 using Steam Play
-  
### Additional information:

Failure for a game to run using Steam Play is a strong indication that there are underlying bugs in the game that will show themselves in future OS and video driver releases. Steam Play uses Proton (based on Wine) which uses the published and researched Windows API calls to create a API translation layer.

The fact the menu loads is a good sign that the game can be patched to work correctly using Steam Play.

**Comment by StarrKiss** [comment]
@douglas-moyes  it works perfectly for me on Manjaro and Fedora and has since day 1. I think the issues are on your side, not on Steam Play or this game.

**Comment by douglas-moyes** [comment]
Manjaro and Fedora **are not** approved distributions  to run Steam under, Ubuntu is. Tests should be made using Ubuntu if this is to be sold on the steam platform. 

Most games work fine with Steam Play, i can even run No Mans Sky without any issues at all. Some other games work fairly well like the Elder Scrolls games and Fallout. So your assertion there is an issue with steam play on my system is a bit suspect. Maybe this game just doesn't like AMD hardware? 

You also completely ignored my statement that Windows players reported a similar crash at the same point in the loading process. This is not a Steam Play issue, it just happens to be more visible when using Steam Play.

It is possible this game just takes forever to load, there is no screen showing that the game is loading assets, nor was there any visible drive activity. About when the music stopped I figured there was an issue. 

In any case, there were enough issues when playing in Windows that I put in for a refund today. I'm not going to be running anymore tests.

**Comment by StarrKiss** [comment]
Alright, then make the issue about AMD hardware or loading crashes, not about using a Not Emulator to run a dev's game.

**Comment by tsunamayo** [comment]
@douglas-moyes Sorry I dont have the bandwidth to support Linux. By the looks of it I also dont have control over Steam Play (it seems that Steam decides which game to whitelist). Thanks for your understanding.

**Comment by tsunamayo** [comment]
@douglas-moyes Hi, to give you more details on the other points:
 - the other windows bugs is on integrated GFX cards (intel UHD) that are well below min spec and that would be able to run the game correctly anyway. Your GTX1660Ti is fine (I coded the game for the most part on a GTX960)
 - I code this on an AMD processor.

I am disappointed by your negative review on Steam for something I have no control over (I dont get to pick if I want to add the game to Steam play, steam is doing all the work here). Also the issue on windows like I said is well known but is on old lower end integrated card well below min specs.
Have a good day.
