### ISSUE TITLE
Invalid brick placement on handheld weapons' sub-grids

### ISSUE THREAD

**Issue by Cpt-Fortius** [tsunamayo/Starship-EVO#3634]
### Short Description of the issue:

Construction not possible on rotators, sliding rails, pistons, or hinges placed on a handheld weapon: A few bricks can be placed, then the area appears blocked, preventing further building.
Hinges appear able to be built upon in two axis.

### Steps to reproduce the issue:

-Place rotator, or hinge, sliding rail, piston on a handheld weapon.

-Attempt placing bricks on the new grids.

### Environment
- Starship EVO version: 21w07a

### Additional information:

![20210220114525_1](https://user-images.githubusercontent.com/38191224/108593378-96996280-7373-11eb-9b29-e241e213fa21.jpg)
![20210220114831_1](https://user-images.githubusercontent.com/38191224/108593379-9bf6ad00-7373-11eb-8333-ebd6e8474ac6.jpg)
![20210220115226_1](https://user-images.githubusercontent.com/38191224/108593383-a31dbb00-7373-11eb-9766-a68f07a49086.jpg)
![20210220115232_1](https://user-images.githubusercontent.com/38191224/108593386-a749d880-7373-11eb-8636-26449718c75c.jpg)
![20210220115316_1](https://user-images.githubusercontent.com/38191224/108593388-a9139c00-7373-11eb-8b2c-758f9326f0ea.jpg)

**Comment by tsunamayo** [comment]
@Cpt-Fortius Hi, issue is fixed for 21w49a. Thanks
