### ISSUE TITLE
Blueprint and Copy Distorted and Ghost Blocks Glitch

### ISSUE THREAD

**Issue by VentgirlJoanne** [tsunamayo/Starship-EVO#3638]
**Short Description of the issue:**
I was working on building my ship and went to overwrite my blueprint to save, but found that large areas of the preview were obscured by random black shapes that appear and disappear.

Although the original copy didn't display any distortions, when I copied the ship from the newly saved blueprint, large sections of the ship become invisible and flashing dark cubes appeared in random places.

**Steps to reproduce the issue:**
Unsure how to reproduce the issue, but I had been working on a number of small hinged cabinets. I thought maybe I just had too many child entities but even once removing the doors the problem persisted. It should also be noted I was hosting multiplayer with one other player at the time.

**Environment**
- Starship EVO version: 21w07a
- Graphics Card: GeForce GTX 1060

**Additional information:**
Blueprint:
[Arrowhead WIP [BUGGED].zip](https://github.com/tsunamayo/Starship-EVO/files/6025505/Arrowhead.WIP.BUGGED.zip)
Video:
https://streamable.com/9j89z3

**Player.log:**
`Mono path[0] = 'C:/Program Files (x86)/Steam/steamapps/common/Starship EVO/Starship EVO_Data/Managed'
Mono config path = 'C:/Program Files (x86)/Steam/steamapps/common/Starship EVO/MonoBleedingEdge/etc'
Initialize engine version: 2019.4.17f1 (667c8606c536)
[Subsystems] Discovering subsystems at path C:/Program Files (x86)/Steam/steamapps/common/Starship EVO/Starship EVO_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1060 6GB (ID=0x1b83)
    Vendor:   
    VRAM:     6052 MB
    Driver:   27.21.14.5671
Begin MonoManager ReloadAssembly
- Completed reload, in  3.728 seconds
D3D11 device created for Microsoft Media Foundation video decoding.
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 1.083700 ms
 -- LOADING RESOURCES --  
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Shape Mesh Data Buffer Count: 74883 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Allocating Voxel Resources 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Allocating Chunk Resources: 73876 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Allocating Entity Instance Resources 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Allocating Brick Data Resources: 8405556 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Unloading 5 Unused Serialized files (Serialized files now loaded: 0)
FMOD: Cleaning up duplicate platform: ID  = c88d16e5272a4e241b0ef0ac2e53b73d, name = 'Low-End Mobile', type = PlatformMobileLow 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

FMOD: Cleaning up duplicate platform: ID  = default, name = 'Default Settings', type = PlatformDefault 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

FMOD: Cleaning up duplicate platform: ID  = 46fbfdf3fc43db0458918377fd40293e, name = 'WebGL', type = PlatformWebGL 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

FMOD: Cleaning up duplicate platform: ID  = e7a046c753c3c3d4aacc91f6597f310d, name = 'Apple TV', type = PlatformAppleTV 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

FMOD: Cleaning up duplicate platform: ID  = 52eb9df5db46521439908db3a29a1bbb, name = 'macOS', type = PlatformMac 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

FMOD: Cleaning up duplicate platform: ID  = 0f8eb3f400726694eb47beb1a9f94ce8, name = 'iOS', type = PlatformIOS 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

FMOD: Cleaning up duplicate platform: ID  = 2c5177b11d81d824dbb064f9ac8527da, name = 'Windows', type = PlatformWindows 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

FMOD: Cleaning up duplicate platform: ID  = b7716510a1f36934c87976f3a81dbf3d, name = 'Linux', type = PlatformLinux 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

FMOD: Cleaning up duplicate platform: ID  = 2fea114e74ecf3c4f920e1d5cc1c4c40, name = 'Android', type = PlatformAndroid 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

FMOD: Cleaning up duplicate platform: ID  = fd7c55dab0fce234b8c25f6ffca523c1, name = 'High-End Mobile', type = PlatformMobileHigh 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

FMOD: Cleaning up duplicate platform: ID  = playInEditor, name = 'Play In Editor Settings', type = PlatformPlayInEditor 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Setting up Debug options 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Max Queued Frames: 2 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

KcpTransport initialized! 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Unloading 1742 unused Assets to reduce memory usage. Loaded Objects now: 14384.
Total: 16.022600 ms (FindLiveObjects: 1.628000 ms CreateObjectMapping: 0.813700 ms MarkObjects: 12.112500 ms  DeleteObjects: 1.467800 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 1)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 14384.
Total: 17.381000 ms (FindLiveObjects: 0.873000 ms CreateObjectMapping: 0.603500 ms MarkObjects: 15.878700 ms  DeleteObjects: 0.025200 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 1)
Allocating Mesh Data Resources, total: 34440 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Starship EVO Version: early-access 21w07a 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

System GFX memory 6052 mb 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

System memory 16348 mb 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Steam Log Success 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

SETTINGS Loaded 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

1 POWER CURVE 4 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[FMOD] Please add an 'FMOD Studio Listener' component to your a camera in the scene for correct 3D positioning of sounds. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 30301.
Total: 30.067900 ms (FindLiveObjects: 1.710700 ms CreateObjectMapping: 0.912500 ms MarkObjects: 27.355800 ms  DeleteObjects: 0.088400 ms)

Unloading 2 Unused Serialized files (Serialized files now loaded: 1)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 30301.
Total: 29.378300 ms (FindLiveObjects: 1.860900 ms CreateObjectMapping: 0.912700 ms MarkObjects: 26.497200 ms  DeleteObjects: 0.106700 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 1)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 30301.
Total: 30.465400 ms (FindLiveObjects: 1.863700 ms CreateObjectMapping: 0.932600 ms MarkObjects: 27.560400 ms  DeleteObjects: 0.108100 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 1)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 31040.
Total: 38.777200 ms (FindLiveObjects: 3.328500 ms CreateObjectMapping: 1.563600 ms MarkObjects: 33.805100 ms  DeleteObjects: 0.079500 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 1)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 31040.
Total: 27.502100 ms (FindLiveObjects: 1.878300 ms CreateObjectMapping: 1.052500 ms MarkObjects: 24.509400 ms  DeleteObjects: 0.061000 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 1)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 31040.
Total: 28.683900 ms (FindLiveObjects: 1.685800 ms CreateObjectMapping: 0.829700 ms MarkObjects: 26.106500 ms  DeleteObjects: 0.061500 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 1)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 31040.
Total: 28.983200 ms (FindLiveObjects: 2.233500 ms CreateObjectMapping: 0.848500 ms MarkObjects: 25.835500 ms  DeleteObjects: 0.065100 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 1)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 31040.
Total: 30.240400 ms (FindLiveObjects: 1.695200 ms CreateObjectMapping: 0.892100 ms MarkObjects: 27.580100 ms  DeleteObjects: 0.072300 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 1)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 31040.
Total: 30.915200 ms (FindLiveObjects: 1.735000 ms CreateObjectMapping: 1.284000 ms MarkObjects: 27.822000 ms  DeleteObjects: 0.073700 ms)

EXITING GAME 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

De-allocating Voxel Resources 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Uploading Crash Report
NullReferenceException: Object reference not set to an instance of an object
  at VoxelEngine.EntityInstanceResources.UnloadEntityBuffers () [0x00000] in <7320ccb63cf145eb8d8ec5a2d703a1c3>:0 
  at VoxelEngine.EntityInstanceResources.UnloadResources () [0x00000] in <7320ccb63cf145eb8d8ec5a2d703a1c3>:0 
  at VoxelEngine.VoxelMaterialResources.UnloadResources () [0x0002d] in <7320ccb63cf145eb8d8ec5a2d703a1c3>:0 
  at ResourcesLoader.UnloadResources () [0x00000] in <7320ccb63cf145eb8d8ec5a2d703a1c3>:0 
  at ResourcesLoader.OnApplicationQuit () [0x00000] in <7320ccb63cf145eb8d8ec5a2d703a1c3>:0 
 
(Filename: <7320ccb63cf145eb8d8ec5a2d703a1c3> Line: 0)

Asset Repo: On Application Quit 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

UNLOADING ASTEROIDS RESOURCES 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Application Quit: Cleaning Render Texture for Habitat Nodes 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Setting up 1 worker threads for Enlighten.
  Thread -> id: 5fe8 -> priority: 1 
SETTINGS.ini Saved 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

`

**Comment by tsunamayo** [comment]
Fixed in recent version. thx
