### ISSUE TITLE
[Bug] spike in GPU usage/fps drops when opening ship computer and then ship blueprint preview in codex

### ISSUE THREAD

**Issue by RockefellerDoctor** [tsunamayo/Starship-EVO#3641]
While working on ship blueprint, if you open the ship computer (which shows all ship stats as well as a 3D preview of the ship), fps will drop (or GPU usage will increase if you are using a 60fps cap like me) and not recover. If you then view the blueprint/builder drone preview in the codex, fps will drop even more/GPU usage will increase more and also not recover.

For me, GPU usage was at 65% standing in front of ship computer; usage then went to 78 after viewing ship computer stats, and then to 99-100% after viewing the codex ship preview, resulting in fps dropping to 52 and staying there (will drop to 35-40 if you view either preview again, and go back to mid-50's once closed).

My layman's guess would be that the game is continuing to render fully detailed preview versions of the ship even after closing the preview windows.

EDIT: further testing with other blueprints that are not mine also exhibit this same behaviour.

...

Step 1: spawn in the aforementioned ship blueprint

Step 2: go to the front bridge and open the ship computer screen.

Step 3: then view the builder drone blueprint preview in the codex (may require placing a block on the build to make it appear in codex)

Step 4: monitor change in fps/GPU usage.

...

- Starship EVO version: current DEFAULT build (21w07a)
- Windows 10 v1809
- Graphics Card: GTX 1070 Ti
- CPU: Intel i5 8600K
- 16GB RAM
- installed on SATA SSD

Additional Info: recently discovered that half the ship blocks will become invisible upon exporting the build to local blueprint file. 

[Issue Report.zip](https://github.com/tsunamayo/Starship-EVO/files/6039254/Issue.Report.zip)

**Comment by Garrett-C** [comment]
I believe this is an issue that has been resolved for experimental. If you want to wait for the next default merge feel free but if you want to play with this bug fixed asap it may be worth swapping to experimental for a bit.
