### ISSUE TITLE
(suggestion) Continuous rotation device applied to a propeller

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#3642]
I know a lot of people already asked for a continuous rotator, and all the problems involved. Meanwhile, I built this ship, using 4x devices for constant rotation, 6 rotators for propellers, 24 rotators in total.

So, it would be easier with a proper constant rotator! The continuous rotation effect we already have, the collision check issue we already have, and it works! Even with 24 rotators working continuously, it works!

![helice continua 02](https://user-images.githubusercontent.com/73253472/109107493-9355fc00-7710-11eb-9ce3-ec8d47a85c66.gif)

steam workshop link:

https://steamcommunity.com/sharedfiles/filedetails/?id=2406891182

![ULTY  Minas Gerais - support airship_preview](https://user-images.githubusercontent.com/73253472/109107681-ef208500-7710-11eb-9775-325aaf8bce3f.png)

**Comment by Garrett-C** [comment]
Maybe it could be a setting on the current rotor. Like a tick box for continuous rotation or something like that. 

It's something that could be useful for things like propellers as shown here but could also probably be used for some reactor rooms or something as well.

**Comment by Uncle-Ulty** [comment]
Yes, there are a lot of applications. I just wanted to show it working, and how cool it is!

**Comment by tsunamayo** [comment]
Cool ship! Yes I know it is possible but it is complicated, so few people are doing it (I am fine with that). It is a question of performance, it might be fine on your design and computer, but definitely would not in other game. I do not wish to shoot myself in the foot by giving something that would make the game lag like crazy. That being said I am refactoring the physics engine, so I will do some test to see if that could be feasible. Cheers
