### ISSUE TITLE
(Suggestion) System blocks being airtight in the future?

### ISSUE THREAD

**Issue by MysticAvian** [tsunamayo/Starship-EVO#3643]
I was thinking how only blast doors and hull would be airtight (and I'm guessing windows) but what about system blocks? Because I was thinking about if you had big stacks of system blocks against a wall/ceiling/floor, and a hull got breached behind it you couldn't reach or see it. Maybe until a hole is shot all the way through a system block into the interior, it stays airtight?

**Comment by tsunamayo** [comment]
Hi, if / when airtightness is implemented, large voxel size system would definitely seal a room. Thanks
