### ISSUE TITLE
[BUG] bad anti clip checks on child entities 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3645]
### Short Description of the issue:
some bits on child entites do not properly check collisions 
...

### Steps to reproduce the issue:
load up blueprint and attempt to place blocks in the area the video shows 
...

### Environment
- Starship EVO version: 21w07a
- Graphics Card: radeon rx 5600 XT

### Additional information:

https://user-images.githubusercontent.com/56371294/109886291-10b3cc00-7c3d-11eb-8a00-1c51ec01ab9f.mp4

[Thingy for city.zip](https://github.com/tsunamayo/Starship-EVO/files/6079797/Thingy.for.city.zip)

**Comment by tsunamayo** [comment]
I think this should be fixed in recent version!
