### ISSUE TITLE
[BUG] Cannot copy and paste capacitors & weapon addons

### ISSUE THREAD

**Issue by zorozeenee** [tsunamayo/Starship-EVO#3648]
### Short Description of the issue:

Cannot copy and past addons to blocks, such as capacitors, weapon addons etc even though it appears on paste preview

### Steps to reproduce the issue:

copy a weapon with addons present or shields with capacitors and attempt to paste
it says X amount of bricks were not built

### Environment
N/A

### Additional information:

N/A Issue is simply a game issue

**Comment by tsunamayo** [comment]
@zorozeenee It is working in recent experimental versions. Thanks
