### ISSUE TITLE
[Bug] Switch hitbox smaller than model [21w09a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#3650]
### Short Description of the issue:
I keep accidentally deleting things behind switches because the hitbox for the switch is now smaller than the actual switch itself.

### Steps to reproduce the issue:
Place switch on surface. Move crosshair over the colored rail on the switch; you will see that the highlighted object changes from the switch to whatever it's placed on.

### Environment
- Starship EVO version: 21w09a
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
![20210306221322_1](https://user-images.githubusercontent.com/33041786/110228785-6ef4df00-7ec9-11eb-9f48-3932bb3be218.jpg)

![20210306221319_1](https://user-images.githubusercontent.com/33041786/110228781-6a302b00-7ec9-11eb-83f0-698e44893633.jpg)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6096531/Player.log)

**Comment by Dwarf-LordPangolin** [comment]
Update: this seems to apply to the logic brick as well.

![20210306224238_1](https://user-images.githubusercontent.com/33041786/110229209-4e2e8880-7ecd-11eb-95eb-0e2f543efe67.jpg)

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Yes bounds box where wrong. Fixed for 21w09b. Thanks!
