### ISSUE TITLE
[Bug] Doors bobbing up and down [21w09a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#3652]
### Short Description of the issue:
Some doors have started bobbing up and down in place (like items on the item stand) inside their frames, and are unable to be used while this is happening.

### Steps to reproduce the issue:
Not sure why or how this happened, so I've attached the blueprint.

### Environment
- Starship EVO version: 21w09a
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
https://gfycat.com/classictenseblacknorwegianelkhound

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6104097/Player.log)

[Apollyon (Bobbing Door Bug).zip](https://github.com/tsunamayo/Starship-EVO/files/6104096/Apollyon.Bobbing.Door.Bug.zip)

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Well sorry I slept on that, but that should be fixed in recent update. Cheers!
