### ISSUE TITLE
[Bug] Codex/map sounds much louder [21w10a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#3655]
### Short Description of the issue:
The most recent update seems to have introduced a bug where the sounds made when using the codex and map menu are much louder than they used to be.

### Steps to reproduce the issue:
No special steps seem to be needed to cause the effect; the sounds are just louder now. I wear headphones, so it may not be as noticeable if using speakers.

### Environment
- Starship EVO version: 21w10a
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6105943/Player.log)

Note: I haven't mentioned this yet, but the sounds you added a while back are really good. 👍

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Hi, I think it has been fixed in recent version, it was because those were not scaling with the setting. Thanks
