### ISSUE TITLE
Disappering surface when painting on or decaling

### ISSUE THREAD

**Issue by Ender1618** [tsunamayo/Starship-EVO#3662]
### Short Description of the issue:

Just got game, when painting or placing a decal on a surface, surface disappears.

### Steps to reproduce the issue:

Fresh download, start game, go thru tutorial...

### Environment
- Starship EVO version: 21w07a
- Graphics Card: RTX 2080 Super

Alienware M17 R3 Laptop

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: 
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6135648/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
Hi, could you please send a screenshot or a blueprint? Do you reproduce every time? Thanks
