### ISSUE TITLE
[Bug] weapons no longer fire when attached to specific blueprint.

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#3663]
### Short Description of the issue:
Hotkeyed weapons won't fire at all when built off the blueprint.  new ships don't have this issue. Neither lasers nor beams will fire when triggered by a hotkey, and if they do, they won't fire all of them.  If connected by a switch, they fire sporadically and not according to their stats. 

I've tried reinstalls, character wipes, breaking every laser or beam on the ship and both standard and experimental versions.
...

### Steps to reproduce the issue:
Spawn In the ship, attempt to build and then trigger either the full-size beam or laser.
...

### Environment
- Starship EVO version: 21w10b
- Graphics Card: rtx 3080

### Additional information:
[nogun.zip](https://github.com/tsunamayo/Starship-EVO/files/6136011/nogun.zip)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6136012/Player.log)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/6136013/output_log.txt)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/6136014/Player-prev.log)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by Kaiser-Indrasil** [comment]
I'm also having this problem as shown in #3640

**Comment by Kaiser-Indrasil** [comment]
@pinesh You should check the new update on the Experimental. It fixed the issue for me.

**Comment by pinesh** [comment]
the update appears to have fixed this issue
