### ISSUE TITLE
Ship explodes when moving

### ISSUE THREAD

**Issue by Swiggzon** [tsunamayo/Starship-EVO#3667]
### Short Description of the issue: no matter if the power or heat is in order or not, the ship will just explode upon moving, i can still shoot guns, but it exlpods as soon as i start moving the ship

...

### Steps to reproduce the issue: simply take control over any ship (build or spawned in. 

...

### Environment
- Starship EVO version: 21w07a
- Graphics Card: GTX 1060

https://user-images.githubusercontent.com/77833869/111077293-5fd8e700-84f0-11eb-87f8-eeb52a712cb0.mp4

### Additional information: as seen in the video provided, i spawn in two ships  that i have downloaded from the workshop, they have always worked just fine. but as soon as i start moving they just die. lastly i build a simple "ship" to show that it is not relative to spawning in ships, it just happens whenever i try to move them around.

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by Cpt-Fortius** [comment]
Have you checked your map?

This happens when you're inside the sun or a planet.
A few days ago I got teleported into the sun after quitting to the main menu and going back to the game world. Took a few tries to realize what's going on. You don't see the sun or the planet from the inside.

**Comment by Swiggzon** [comment]
> Have you checked your map?
> 
> This happens when you're inside the sun or a planet.
> A few days ago I got teleported into the sun after quitting to the main menu and going back to the game world. Took a few tries to realize what's going on. You don't see the sun or the planet from the inside.

ok just checked the map and seems you were right, i was inside the sun. ploblem solved lmao
