### ISSUE TITLE
[Bug] Fuel tank mass scales incorrectly

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3669]
### Short Description of the issue:
A 0.75m^3 brick tank has a mass of 400kg, as labelled on the codex. If you scale that to 1mx0.75x0.75, it has a mass of 800kg, double the mass for only an extra third capacity. This means that a 1x1x1m brick tank weighs 3200kg! :D
Seems like it's adding an extra full mass for every step stretched in a direction, using mass logic for regular blocks rather than something that starts out as 0.75m to a side.

This is also an issue with the block sized fuel tank

### Steps to reproduce the issue:
Place a fuel tank and measure the mass, then measure the mass of a stretched tank

### Environment
- Starship EVO version: 21w10b
- Graphics Card: RX 580

Although the codex says this is 2m to a side, it's actually 1m. Note the 3.2T mass
![image](https://user-images.githubusercontent.com/27857711/111180042-8e17fe80-85a4-11eb-972e-87d33fad9ff2.png)

**Comment by Doperwt** [comment]
to add to this, it seems the small fuel tank(brick sized) and the large fuel tank(block sized) have the same mass per unit of size, this means the brick one is massively overweight

**Comment by tsunamayo** [comment]
@ProPeach Fixed for 21w28c. Thanks
