### ISSUE TITLE
Sloping coloring... 

### ISSUE THREAD

**Issue by bombel28** [tsunamayo/Starship-EVO#3670]
Ouch! Is this already known?

![20210315181914_1](https://user-images.githubusercontent.com/80328658/111194219-40f35700-85bb-11eb-946f-97ddf5326347.jpg)

**Comment by Kaiser-Indrasil** [comment]
This needs context. What exactly are you reporting?

**Comment by bombel28** [comment]
I wanted to colour those inner slopes. Everything was fine. Then I build that outer slopes above and below.
With every block some of the middle slopes turned colour back to grey, and above pic is summary of recolouring.
I can't do this design like on the left or the right.

**Comment by bombel28** [comment]
![20210310211902_1](https://user-images.githubusercontent.com/80328658/111197197-7b122800-85be-11eb-8d01-37d284406e9c.jpg)

In other cases, "between" colouring isn't a problem.

**Comment by tsunamayo** [comment]
Hi, by the look of it you just discovered that voxel paint was a thing. It will be "fixed" very soon...

**Comment by tsunamayo** [comment]
Voxel paint are now long gone in experimental. Thanks
