### ISSUE TITLE
[Bug] Pasting regions made of bricks results in pastes being offset into the block

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Starship-EVO#3671]
### Short Description of the issue:
When trying to copy and paste a brick-built structure the paste region attempts to paste the bricks inside the selected block. It almost appears that the paste is selecting the inside of the face rather than the outside.

![image](https://user-images.githubusercontent.com/43644633/111343640-85dac480-8673-11eb-8068-00119d634a1c.png)

### Steps to reproduce the issue:

Copy and paste a brick build.

### Environment
- Starship EVO version: 21w10b
- Graphics Card: RTX 3070

**Comment by tsunamayo** [comment]
Hi, I am not sure to understand that one... cheers

**Comment by Garrett-C** [comment]
Sorry it is an odd one to try and explain. 

So when you copy something made of blocks or with blocks when you go to paste it applies the paste to the block grid and bases the paste location on the face of the block as a reference for where the paste should go. 

When trying to paste regions made of bricks the game will often try and paste the bricks inside the block you are looking at instead of on top of the selected face. 

So in the image I used on the initial post you can see the brick-based region I have copied. You can also see that where I am trying to paste it the paste is trying to apply inside the block I am looking at. You can see this as the paste indicator is flat and doesn't show the depth. 

Does that help?

**Comment by tsunamayo** [comment]
@Garrett-C Hi, does it still apply with all the latest copy/paste/prefab tech? Thanks

**Comment by Garrett-C** [comment]
> @Garrett-C Hi, does it still apply with all the latest copy/paste/prefab tech? Thanks

No mostly it seems to work much better now and obviously you can adjust the grid used by making it a prefab.

That said I think placing perhaps on 2x2 rotors does have some alignment issues now.
