### ISSUE TITLE
[Suggestion] Let pipes pass through lattice girders

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#3672]
Hi! I was working on some fuel related stuff, and realized that the pipes can't go through the girders. I thought it might look really cool and industrial if they could.

![20210316180020_1](https://user-images.githubusercontent.com/33041786/111390962-a14ccc00-8681-11eb-85f3-296e76eb7426.jpg)

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Somehow I slept on this, it will be available in 21w28c. Thanks
