### ISSUE TITLE
High GPU - FPS deterioration

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#3673]
### Short Description of the issue:

For some time now I've been trying to build as I have been previously but I find myself having to restart my game very frequently just to keep a smooth 60 fps. Everything seems to run smoothly but once I place a block on my 300m ship the game freezes for a second or two then it goes back to normal for a while. Pasting sections that contain lights take longer than average and placing blocks in areas with lights also freezes the game for 1 - 2 seconds. After a bit of time my frames drop to ~44 fps and don't go back to 60 unless I restart my game.

- During the normal period with 60 fps my GPU usage is at roughly 75%
- Once my frames drop my GPU usage is right around 99%
- There are only 3 or 4 spawned entities in my world right now
- Each spawned entity has 0 child entities

Is this related to what you mentioned about how we'll probably notice some performance loss while some transitions are being made on the backend? Everything was normal before all this so I can only assume

...

### Environment
- Starship EVO version: 21w10b
- Graphics Card: GTX 970

**Comment by Regnion** [comment]
I had a 970. It could be you're overheating. If you use Task Manager, go to the next tab over, Performance, and you can monitor your GPU temperature. Just play the game windowed so you can see it at the same time, assuming you have 1 monitor.

300m is demanding on the game. I have a 3080GPU after my 970 died a couple weeks ago. I have a large station probably worth two or three of your ships, and my FPS tanks to 35. The game can only handle so much weight.

**Comment by RockefellerDoctor** [comment]
> 
> 
> I had a 970. It could be you're overheating. If you use Task Manager, go to the next tab over, Performance, and you can monitor your GPU temperature. Just play the game windowed so you can see it at the same time, assuming you have 1 monitor.
> 
> 300m is demanding on the game. I have a 3080 GPU after my 970 died a couple weeks ago. I have a large station probably worth two or three of your ships, and my FPS tanks to 35. The game can only handle so much weight.

GPU temperature would not affect GPU usage to this degree though. Thermal throttling would reduce clock speeds to maintain safe temperatures, but not to the point that you would go from 70% usage to basically 100% usage.

This may be a symptom of the codex builder drone bug where opening the builder drone screen in the codex to view your spaceship mini 3D preview causes fps to basically halve itself.

**Comment by tsunamayo** [comment]
I have spotted the issue where you open the spaceship computer and it will kill your FPS. Will work on it for the next update.

**Comment by tsunamayo** [comment]
Fixed for 21w11a. Thanks!
