### ISSUE TITLE
[Suggestion] Emissive Blocks and spotlights, again.

### ISSUE THREAD

**Issue by Regnion** [tsunamayo/Starship-EVO#3675]
### Short Description: Previously, members of the community have requested some form of emmissive block or sticker, and the idea was declined. I am presenting it to you again.

Emmissive surfaces, glittering lights, these are staples of sci-fi. Currently, our lights are limited. Their glows are small, and spread over a small distance. From far away, they make little diamonds on the surface. They do not cast out a circular field of light. As well, they cannot be seen from a distance unless they are coating a surface in light- if you put lights on an antenna, you won't see them. Radio towers are visible for miles and miles, and their lights do not coat the entire tower in light. Same for aircraft navigation lights.

Previously, you mentioned you did not want surfaces to be emmissive unless they were a critical component, so players know what to shoot- I will tell you right now, virtually everyone does their best to tuck their components into their hulls for protection, and we try very hard to hide the glowing weapons inside barrels of turrets. You can't even _see_ the emmissive glow of components during combat. People are using small reactors and thrusters for decoration, not for actual utility, because we want glowing lights. Some of us are using buttons, permanently activated by a switch, to get a small but strong glowing light. 

Please consider giving us a stretchable glowing brick, as well as a stretchable 45 degree angle emmissive brick, and perhaps even one that has glowing lines like the small thrusters (perfect for stair cases, hallways, etc). These would work perfectly for illuminating antenna, defining a landing pad area, navigation lights, emergency exit lights, and for making our builds look more "sci fi." We, the Players, want emmissive lights that don't cast light like the actual lights. We had them in Skywanderers- please give them back.

Additionally, spotlights that project light onto or across a surface would be great, especially if they cast a soft glowing beam in the direction they face. Consider runway lights, or illuminating a tower with spotlights from below- pretty epic stuff.

Attached are some pictures that will hopefully inspire you to give us suitable lighting methods that don't require logic to get working, which can get taxing on the game.

![20210112213301_1](https://user-images.githubusercontent.com/13087952/111527142-35bc3a80-8725-11eb-8a04-fcdb10ea1b5e.jpg)
![20210121125803_1](https://user-images.githubusercontent.com/13087952/111527146-3785fe00-8725-11eb-898e-8e97ec47c24e.jpg)
![20210313204534_1](https://user-images.githubusercontent.com/13087952/111527150-3785fe00-8725-11eb-85a4-55ce792c96f8.jpg)
![20210316130438_1](https://user-images.githubusercontent.com/13087952/111527151-381e9480-8725-11eb-9b56-4a1db0fc6de2.jpg)

Oh yeah, and please give us new glass bricks/blocks.

With love,

Regnion and other agreeable persons of good taste

**Comment by LtDingus** [comment]
I agree with Regnion 100% on this one. I would absolutely love to see like a beacon light block or something that we can use as navigation lights.

**Comment by Dwarf-LordPangolin** [comment]
100% agreement with Regnion on this. The glowing lights on the system blocks definitely make them look really cool, but they're never going to serve the function of telling the players "aim here;" that makes sense in games where the opponents are all premade NPCs (sort of tells the player "aim here for massive damage" 😉 ), but 99.9% of the time everyone playing this game covers them in at least one layer of armor, or at least bricks. Nobody that's building with combat in mind leaves their system blocks exposed, unless those blocks are a decoy, or purely redundant and being used for cosmetic effect.

Speaking of which: we're currently using the blocks that *do* have an emissive effect largely for cosmetic reasons, which is probably not the intention; I'm using engine blocks for glowy bits on the shipyard I'm making, and I use brick-size reactors in the reactor room I've built for my cruiser (because it looks cool).
![20210317150727_1](https://user-images.githubusercontent.com/33041786/111531782-fc8ac700-8732-11eb-8fa4-67d92539f679.jpg)

![20210317151409_1](https://user-images.githubusercontent.com/33041786/111532197-6e631080-8733-11eb-8100-51c1b36fe354.jpg)

So yeah, giving us something that glows would honestly probably _improve_ performance, because I doubt what we're doing now is good for it! 🤣

**Comment by Uncle-Ulty** [comment]
Why not emissive decals?

**Comment by Regnion** [comment]
> 
> 
> Why not emissive decals?

![3cdfe657c0c0253cfb2fa0ec80df238c](https://user-images.githubusercontent.com/13087952/111545018-00bae280-873b-11eb-8027-589926d296e3.png)
![7957fe3f041cab8386440fb112f15c5e](https://user-images.githubusercontent.com/13087952/111545022-01537900-873b-11eb-8755-ebe79819bdd3.png)
![ef3244de94b5ad36f2a9aeed25232edd](https://user-images.githubusercontent.com/13087952/111545024-01537900-873b-11eb-9a1a-8ddd6d658b58.png)

We have emmissive engines and thrusters, scalable in size. So decals are not really plausible, but a draggable brick that is emmissive, but not an illuminating light, should be possible, and has already been done.

**Comment by Kaiser-Indrasil** [comment]
The glowing brick (or ideally, a glowing decal) would not cast light onto neighbouring blocks. We don't want that. We only want it to glow like the Lightcruise Engines do.

People have been using them, and other glowing bricks, buttons in particular, for that exact purpose, and will continue to use them, pupulating their builds with hundreds or thousands of performance-hoarding bricks, unless you introduce a purpose-built equivalent.

**Comment by Briaireous** [comment]
Would love to use spotlights for mining

**Comment by Xerma** [comment]
This is something many of us have wanted back since the graphical update where we lost many things. I too am guilty of using parts that aren't intended for glowing purposes, IE thrusters

**Comment by Cpt-Fortius** [comment]
Yes please.

Both to spotlights and emissive bricks.

**Comment by jupitervesselcorp** [comment]
Spotlight, lights, glowing lights, and blinking lights are all very important part of making a nice looking space ship.  They are need. The light distance and brightness should be adjustable.

**Comment by tsunamayo** [comment]
@Regnion Hi, sorry for the late reply but as you know glowing block where added a bit after this post (which was instrumental to get me started). Then you now have RGB control. To really get sexy navigation lights I still need to add a sprite overlay like for the torus, and then my life will be complete. Thanks
