### ISSUE TITLE
MULTIPLAYER BUG

### ISSUE THREAD

**Issue by KEVSTRONAUT** [tsunamayo/Starship-EVO#3677]
### Short Description of the issue:

When me and my friend tries to play multiplayer we get on the same server. But when we start to fly, it wont load for the other player. The ship stays in the same place for one person while the other person flyes away. Can this be fixed?

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by Vicomt** [comment]
can confirm this. bloody annoying, but not fatal for builders like us ;)

**Comment by tsunamayo** [comment]
@KEVSTRONAUT Hi, this issue will be fixed for 22w04a. Sorry for the long wait... Thanks
