### ISSUE TITLE
Measurements showing incorrectly

### ISSUE THREAD

**Issue by TheVikingWalrus** [tsunamayo/Starship-EVO#3680]
### Short Description of the issue:
The measurements on the UI showing drone mass etc shows the incorrect size when there is only one block present, for example, one large block shows up as a 2x2x2 meter size, when it is meant to show a 1x1x1 meter size.
...

### Steps to reproduce the issue:
Place a single block and check the UI to see the drone [size.](url
![Screenshot 2021-03-25 190143](https://user-images.githubusercontent.com/81385319/112528883-950cf100-8d9c-11eb-8a05-115f8882449e.png)
)
...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@TheVikingWalrus Fixed in recent versions. Thanks
