### ISSUE TITLE
[BUG] Movement inconsistencies

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#3682]
Character movement in the vertical directions is slow and jittery, compared to smooth movement in the horizontal directions. The problem is not noticeable when movement speed is set to 1x and is most pronounced at 9x. This occurs for both the gravity aligned movement mode and the 6-DOF movement mode.

Seems to be a new issue for 21w12a.

**Comment by Regnion** [comment]
I am also having this issue. Jumpy and stuttery movement vertically, but strafing and forward/backward are fine. It's notable at any high speed, but if you pay attention you'll notice it at 3x as well.

**Comment by tsunamayo** [comment]
Yes correct, let me check this.

**Comment by tsunamayo** [comment]
@cloudrambler @Regnion Issue fixed for 21w12b. Thanks, the build will be up soon.
