### ISSUE TITLE
[Suggestion] Level Of Detail adjustment

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#3684]
The recent visual reconstruction feels like a step forward. Up close, the softer borders, applied universally, look more natural and provide subtle background details without overtly breaking up larger forms. At distance (no shadow), the low-level divisions disappear, leaving just the geometric design, which looks clean and enhances the retro-style silhouette impact.

However there is an intermediate level of detail which can appear much less attractive! This middle LOD always looked bad from some angles, but now it looks worse than before, because the dark shadow lines are more numerous and are more contrasted against the otherwise smooth surfaces. This is particularly bad on partially lit surfaces.

As this middle distance is typically where most ships will be aesthetically viewed from, it makes sense for it to look good.

It would be great if the high detail range could be increased so that it continues up to where the shadows turn off. This would mean only one visual transition point and would be far enough away to be less intrusive.

I was going to suggest moving both distances to a mean point, but I know some people already want the shadow distance to be larger, for big room lighting reasons, so that would not be popular.

If this is mainly a graphics performance issue, would it be possible to provide user settings for these distances. I suspect most gaming computers could handle the high detail mode up to the shadow threshold. The only downside would be that for low end computers, it may have to look like it does now, or drop some FPS (which is pretty high and getting better).

**Comment by tsunamayo** [comment]
Hi, I am not sure of what you are talking of, if you could send some screenshot. Is the the shadow resolution switch? There is no LOD in code whatsoever, just a shadow cascade. I plan to increase the shadow distance at one point. The big drawback of the free stretch tech is that faces not visible as still drawn, and they will do some weird artifact with shadow at some angles.

**Comment by cloudrambler** [comment]
There are two visual transitions that I can see when moving from close proximity to infinite distance; the first transition seems to make the shadows more coarse and the second transition seems to switch the shadows off.

On well lit surfaces, the first transition is almost undetectable. On poorly lit surfaces a series of heavy dark lines appear at regular intervals. These lines look like shadows, but they should not be there as the surfaces are smooth. Also the lines do not correspond to the block edges, but are offset.

![20210328131628_1](https://user-images.githubusercontent.com/70821082/112752025-cbc74f00-8fc8-11eb-9f65-c3fb05ae8c00.jpg)

The lines on the unlit side of the ship are feint when close and dark when at the intermediate distance. The lines look pretty bad and they are visible on dark surfaces also. The worst part is the sudden change at the edge of the sphere.

**Comment by tsunamayo** [comment]
@cloudrambler so yes it is because of shadow, unfortunately I dont really plan on changing that. Shadow in other games are not perfect too, here it is magnified because of the imperfect geometry (hidden faces) due to the nature of the game. Thanks
