### ISSUE TITLE
Consider opening up the Discussions section of the repo

### ISSUE THREAD

**Issue by Pharap** [tsunamayo/Starship-EVO#3685]
I apologise for using an issue to bring up something that isn't directly related to the game, but I believe this suggestion may be of use.

I've been flicking through some of the issues here and it seems to me that some people are treating the issues section a bit like a forum (e.g. they just want to chat and socialise, or they're asking questions that other players could answer), so it got me wondering if perhaps opening up the "[Discussions](https://docs.github.com/en/discussions/collaborating-with-your-community-using-discussions/about-discussions)" section of the GitHub repo might be useful for separating out discussions from actual bug reports. It would probably also be a good place for doing announcements, Q&A and other less formal things.

Naturally, I understand if you think there isn't a problem or that this wouldn't be beneficial, you are certainly better positioned to understand your own issues section than I am, but I thought I'd suggest it just in case you aren't aware of the feature since GitHub introduced it fairly recently. (It's still in beta even.)

Merci pour votre temps, et bon chance avec le jeu.

**Comment by tsunamayo** [comment]
Nope that is a valid point I will have a look into that I was not aware of this. Cheers

**Comment by tsunamayo** [comment]
@Pharap Les discussions sont ouvertes depuis quelque temps! Merci
