### ISSUE TITLE
Copy & Paste issues

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#3687]
### Short Description of the issue:

1.When you copy something that has colors to it, the colors don't paste in the way that they were copied.
2.The larger the copied object is, the stranger the color difference gets
3.Copy & Paste can create invisible blocks - after relogging into the game they are back and not invisible anymore. 
(still not the correct color though!) 

### Environment
- Starship EVO version: 21w12b

### Additional information:

1.Left is the original, middle is the copied version of it
![20210328132353_1](https://user-images.githubusercontent.com/81495956/112750549-88211500-8fc9-11eb-9ece-c11246a953cc.jpg)

2. + 3.
![20210328133206_1](https://user-images.githubusercontent.com/81495956/112750669-37f68280-8fca-11eb-9be5-c3559760d02a.jpg)

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, so I wont bother with this bug as I will remove voxel paint soon, that will makes my life easier. It will be fixed when the voxel kill update is out. Thanks
