### ISSUE TITLE
[BUG] Symmetry: Hull blocks have no collision with same entity hull blocks 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3689]
### Environment
- Starship EVO version: 21w12b
### Additional information:

https://user-images.githubusercontent.com/56371294/112767863-e7812400-8fcd-11eb-94f4-73a1e4aac07e.mp4

**Comment by TIKIRobo** [comment]
This also happens with a wide range of other blocks such as; small & large reactors, small bull blocks, shields, warp cores, small and large thrusters, small and large capacitors, and probably more.

**Comment by tsunamayo** [comment]
Fixed for 21w13a. Thanks
