### ISSUE TITLE
decals are copy paste-able... somehow...

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3691]
https://user-images.githubusercontent.com/56371294/112777199-6f7b2400-8ff6-11eb-9ae6-1b2c7e1dddbf.mp4

**Comment by TIKIRobo** [comment]
Overlapping decals seem to have trouble pasting properly but it could have also been a bad copy
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6218733/Player.log)
also player log incase this is a "bug"

**Comment by Regnion** [comment]
https://www.youtube.com/watch?v=KkF8-vhVM_0

**Comment by Regnion** [comment]
https://user-images.githubusercontent.com/13087952/112790143-ea0a6a80-901b-11eb-9017-dc60e49d1e71.mp4

**Comment by tsunamayo** [comment]
@Regnion ;). I havent worked on that much, but what was the bug? The upcoming "great simplification" will make my life a lot easier regarding copy-pasting.

**Comment by tsunamayo** [comment]
Okay, yeah things have changed, I think there will be some overlap issue though.
