### ISSUE TITLE
Lights are super weird Right now.

### ISSUE THREAD

**Issue by jealousdequan** [tsunamayo/Starship-EVO#3692]
### Short Description of the issue:
Instead of a short description, I have included a short video of this strange light issue, as I feel it perfectly showcases the bug.
...

### Steps to reproduce the issue:
Place light, then delete it.
...

### Environment
- Starship EVO version: 21w12b
- Graphics Card: GeForce GTX 1070

### Additional information:

https://user-images.githubusercontent.com/72936878/112868629-46a46e80-908a-11eb-8193-e29475112794.mp4

**Comment by tsunamayo** [comment]
@jealousdequan It is fixed in recent version. Thanks
