### ISSUE TITLE
[Bug] Placing block causes object to fly away [21w12b]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#3693]
### Short Description of the issue:
Placing a block can now cause the object in question to move away from the player.

### Steps to reproduce the issue:
I suspect this is the same issue with the physics of large builds that Kaiser-Indrasil mentioned [here](https://github.com/tsunamayo/Starship-EVO/issues/3681#issuecomment-808725690):
> When testing collision check optimisation, I noticed that it works very janky for very big builds like the Venator. When I tried to ram it in a Kodashi, it started glueing towards me, promptly accelerating itself towards me to a ridiculous speeds of 2-3 km/s.

### Environment
- Starship EVO version: 21w12b
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
https://gfycat.com/ultimatepolishedachillestang

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6224731/Player.log)

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin I wonder if it could not be because of the docked entity instead...

**Comment by tsunamayo** [comment]
I think it should be good in recent versions... Thanks
