### ISSUE TITLE
cant turn off jetpack completly

### ISSUE THREAD

**Issue by luckyrada** [tsunamayo/Starship-EVO#3694]
### Short Description of the issue:
i am in gravity, i continously press J but it only switches between 6 degree and anti-gravity

### Steps to reproduce the issue:

be in gravity, press J

### Environment
- Starship EVO version: latest experimental
- Graphics Card: intel(r) iris(r) plus grapchics 655

**Comment by tsunamayo** [comment]
Hi, I will need a blueprint to reproduce the issue. Thanks

**Comment by Rhedd-V** [comment]
I have the same problem, and it's a bug with ALL blueprints in my game. including the default space stations and NPC ships in a fresh game. It's like none of the gravity generators are actually working. Gravity works fine when I play the release branch, so it must be something that's changed in experimental.

**Comment by luckyrada** [comment]
yes, its not a bug with a blueprint. it dosnt even work in a halo ring.

**Comment by jealousdequan** [comment]
Yes I get the same bug with all of my blueprints as well. Only gravity I can get is on the ring.

**Comment by tsunamayo** [comment]
@luckyrada @Rhedd-V @jealousdequan again I need a blueprint to reproduce that issue, it is all fine on my side. Are you still reproducing the bug?
