### ISSUE TITLE
[BUG] ships fall through the ground 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3697]
### Short Description of the issue:
ships will fall through the ground on the ring world if you fly far enough away 
...

### Steps to reproduce the issue:
spawn in ship, fly ship, land ship, then fly away (1-2km) and look away when you look back the ship should have fallen through the ring
...

### Environment
- Starship EVO version: 21w12b

### Additional information:

https://user-images.githubusercontent.com/56371294/113076255-7d11e480-9183-11eb-9375-a75f8a6fc68e.mp4

**Comment by tsunamayo** [comment]
Indeed, I managed to reproduce that one

**Comment by tsunamayo** [comment]
Issue fixed for 21w13a. Thanks!
