### ISSUE TITLE
[Bug] All spaceships sound the same despite vast differences in size

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3700]
Version: 21w13a

I have tested the issue on [Kodashi](https://steamcommunity.com/sharedfiles/filedetails/?id=2303258817), [Corvus](https://steamcommunity.com/sharedfiles/filedetails/?id=2420779755), and [Agni](https://steamcommunity.com/sharedfiles/filedetails/?id=2297275555) - they all sound exactly the same when accelerating.

**Comment by tsunamayo** [comment]
That is no bug...
