### ISSUE TITLE
[Bug] Stickers flicker over distance

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3703]
Version: 21w31a

Steps to reproduce:
1. Spawn a ship ([Corvus](https://steamcommunity.com/sharedfiles/filedetails/?id=2420779755) in this case)
2. Restart the world
3. Do the same camera movement as I did in the video below:

https://user-images.githubusercontent.com/63756057/113311989-c25c2080-9301-11eb-8721-3fd733088161.mp4

**Comment by tsunamayo** [comment]
Yeah it is because of the decal density being too high. I will try to improve the situation by managing them better...

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil situtation is much better now but not perfect, it will never be with the current tech. Dont overdo decals (dont overdo anything btw).
