### ISSUE TITLE
Heat is going bonkers

### ISSUE THREAD

**Issue by Swiggzon** [tsunamayo/Starship-EVO#3705]
### Short Description of the issue: the heat "Generated over dissipated" was on 13% on the current stable build, but it skyrocketed to over 700% on experimental.

...

### Steps to reproduce the issue: simply have my ship in a world and test it on both regular build and experimental build and there will be a significant difference 

...

### Environment
- Starship EVO version: 21w07a  and experimental
[Beamus Gigantus.zip](https://github.com/tsunamayo/Starship-EVO/files/6245727/Beamus.Gigantus.zip)

- Graphics Card: 

### Additional information: i have tried removing heat generating items and adding more surface, but that changes nothing, not even in the stats. so I'm not sure what to do or what causes this other than something you made different in how heat is calculated? But that still does not seem like it would be that much of a drastic change.

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
HI, okay let me have a look at this.

**Comment by tsunamayo** [comment]
@Swiggzon It should be fixed now. Thanks
