### ISSUE TITLE
Decals don't "stick" to blast doors

### ISSUE THREAD

**Issue by Wolfie18** [tsunamayo/Starship-EVO#3706]
I love this game and this is just a very minor glitch to me...
But I wanted to try and do my part and do report it.
It's my first time posting anything on github so please forgive me if I made any mistakes ^_^"

### Short Description of the issue:
When you try to put decals on the sliding part of a blast door, it just dissapears when the door slides away.
The decal doesn't "stick" to the door.
It does turn visible again after sliding the door back.

### Steps to reproduce the issue:
- Place a "Blast door" (mine was 2,50x2,50)
- Add a decal (mine was 2.00x2.00)
- Open the door and watch the decal stay in place until it disappears when the door is past the last point of where the decal is.
- Close the door and watch the decal reappear
...

### Environment
- Starship EVO version: 21w07a (current stable build)
- Graphics Card: AMD R9 390

**Comment by tsunamayo** [comment]
@Wolfie18 Hi, thanks for taking time to book the case. Unfortunately it is not an issue although I agree it can be frustrating. It is because of the door technology used. Thanks
