### ISSUE TITLE
[Bug] Handheld weapon building is borked

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3709]
Version: 21w13b

Given our new glowing blocks (Thank you, Tsuna!) I wanted to grab a glowy pipe and build myself a lightsabre.
But, apparently, the whole building process is borked since the brick placement is very offset and the physics get crazy to the sound of collisions.

This gets especially noticeable if you dare trying to build a handheld on a ship, which starts drifting violently.

![image](https://user-images.githubusercontent.com/63756057/113447166-3b867100-93f1-11eb-96e7-65e6bc43886b.png)

**Comment by Hadn-Zodiac** [comment]
yeah i also have this problem

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Handheld are fixed for 21w49a. Thanks
