### ISSUE TITLE
The solution to side thrusters restriction on design. 

### ISSUE THREAD

**Issue by jupitervesselcorp** [tsunamayo/Starship-EVO#3710]
Add reactionless engines.  There a thing from many scifi.  The engines do not shoot thrust out and can move the ship in any direction.  So the play can choose between thrusters on the sides or reactionless engines.

**Comment by Kaiser-Indrasil** [comment]
Umm... You can hide your side thrusters inside the hull, you know? There's simply no need for reactionless engines.

**Comment by jupitervesselcorp** [comment]
The issue that it would address is not needing to place side thrusters in the ship at all for the great freedom of design.  He has been thinking about side thrusters in away that won't force us to use them.

**Comment by Kaiser-Indrasil** [comment]
Having them in the game is a way to quantify lateral thrust and maneuverability of your spaceship. Without them, the game would just be that much more shallow gameplay-wise.

**Comment by tsunamayo** [comment]
Hi, yes at the end it is not all about design, it is supposed to be a game... Cheers
