### ISSUE TITLE
[Bug] Wrong size on Window Arch

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#3711]
### Short Description of the issue:
The new block "Window Arch" has the wrong size.
It's 0,25 wide but shows up as 0,50 (screenshot).
You can not stretch the block up to a 4m long block, only up to 3.75
![20210402232538_1](https://user-images.githubusercontent.com/81495956/113455634-6ed5f980-940b-11eb-8cf0-1b312d078960.jpg)
![20210402233207_1](https://user-images.githubusercontent.com/81495956/113455719-a93f9680-940b-11eb-9eca-ebeb1d5c856b.jpg)

**Comment by tsunamayo** [comment]
@BigBadKangaroo Finally fixed for 21w28c. Thanks
