### ISSUE TITLE
[suggestion] Ball and socket

### ISSUE THREAD

**Issue by luckyrada** [tsunamayo/Starship-EVO#3713]
### Short Description of the issue:

a new child entity movment system, a ball and socket, it would allow for rotation in pretty much all directions, but limited to only a certain direction, so it can turn like 60 degrees in any direction, but from then on it cant

this would help with a bunch of builds, such as a way to make small ajustments in the aim of lasers for a long range sniper or something

**Comment by tsunamayo** [comment]
I will add them for only for mech and potentially turrets. How would you supposed to control them otherwise? Cheers

**Comment by Regnion** [comment]
Ball and socket for turrets would be tremendous- this would remove the need to use a hinge and a rotor (or combination / alternation thereof) entirely.
