### ISSUE TITLE
[BUG] Glass turns invisible and shows hexagonal broken texture when viewed from some angles 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3714]
### Short Description of the issue:
Some of the glass on my ship turned invisible and looks like the destroyed texture when viewed from certain angles 
...

### Steps to reproduce the issue:
im not entirely sure but it seemed to happen after copy pasting the new glass blocks on accident 
...

### Environment
- Starship EVO version: 21w13b
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:

https://user-images.githubusercontent.com/56371294/113481199-fc860900-944c-11eb-9767-be4d85ef8592.mp4

![Starship EVO 4_3_2021 7_20_13 AM](https://user-images.githubusercontent.com/56371294/113481208-0c055200-944d-11eb-987c-de8a2e3a3eb7.png)

**Comment by TIKIRobo** [comment]
Also the glass will stay invisible on new ships i spawn in and across restarts 
Here's the BP:
[New Entity.zip](https://github.com/tsunamayo/Starship-EVO/files/6252699/New.Entity.zip)

**Comment by TIKIRobo** [comment]
@tsunamayo i figured it out!, the new glass blocks are destructible! and so glitch out after a combat test

**Comment by tsunamayo** [comment]
@TIKIRobo Okay great!
