### ISSUE TITLE
[Bug] Frozen in place after placing block on starter block

### ISSUE THREAD

**Issue by Regnion** [tsunamayo/Starship-EVO#3715]
### Short Description of the issue:

I started building on the torus, with the starter block on the ground. I unspawned the entity, and flew a short distance out into space, and placed a starter block in space, then placed 1 block, and suddenly became stuck and unable to place more blocks. I could still use the menus, but I could not change my camera view, move, place blocks, or scroll through blocks in my inventory.

...

### Steps to reproduce the issue:

Unknown, this has never happened to me before. It might be tied to building on the torus, it might just be bad luck.
...

### Environment
- Starship EVO version: Experimental, 21w13b
- Graphics Card: GTX 3080 Laptop

### Additional information:

[Player.zip](https://github.com/tsunamayo/Starship-EVO/files/6253208/Player.zip)

https://user-images.githubusercontent.com/13087952/113487847-a4b0c780-9477-11eb-9405-25e08fa1b54a.mp4

I could not save the blueprint. The "New Entity" seen when I open the menu is actually the previous one on the torus, since I place the block on the "forward" face this time. The one seen in the menu is not forward.

**Comment by luckyrada** [comment]
this happened to me, restarting game fixed it, dunno how it happened i wasnt near the torus

**Comment by Swiggzon** [comment]
i can confirm that this has happened to me several times.

**Comment by tsunamayo** [comment]
@Regnion I think it should have been fixed in recent build, tell me if it is not the case! Thanks
