### ISSUE TITLE
Character Creation causes crash

### ISSUE THREAD

**Issue by JackOTHy** [tsunamayo/Starship-EVO#3718]
### Short Description of the issue:
 Heya! I cant get past Character Creation. Everytime I try to create character, the game closes. Which is even more weird: When I start the game again, it says the character with that name is already created, even tho it doesnt appear on character selection. I tried to hard-restart my laptop, switched to either both integrated and high powered GPU and none of it helped. 
...

### Steps to reproduce the issue:
Play - Create New Character - Fill in the Nickname - =Crash=
...

### Environment
- Starship EVO version: 21w07a 
- Graphics Card: NVIDIA GeForce RTX 2060 Max-Q 6GB GDDR6 (+Integrated Intel(R) UHD Graphics)

### Additional information:
![Bez názvu](https://user-images.githubusercontent.com/21199256/113516835-ca73c480-957c-11eb-8a65-dcc73a0dbb30.png)
![Bez_nazvu2](https://user-images.githubusercontent.com/21199256/113516963-833a0380-957d-11eb-9de7-894634bbc114.png)
![image](https://user-images.githubusercontent.com/21199256/113516975-977e0080-957d-11eb-906a-96199ed76396.png)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6255041/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
Hi, sorry to hear this. What is your PC brand and model, and the other spec? Is your windows up to date? Thanks

**Comment by JackOTHy** [comment]
My laptop is HP Pavilion Gaming 15-dk1009nc.
All other specs:
i7-10750H 6-core
16GB RAM DDR4
Windows 10 Home

And yes, it should be Up-to-date

**Comment by tsunamayo** [comment]
@JackOTHy could you test with V-sync on? You have to try with the RTX card. 
How are your GPU and CPU temperature ? ( if you can monitor this)
Also do you have stability issues with other games?
Thanks

**Comment by JackOTHy** [comment]
VSync on/off doesnt help. Temperature is 30°C-60°C. Any other games work just fine.

**Comment by David184** [comment]
same happening to me too. can't play on experimental and normal branch

**Comment by tsunamayo** [comment]
@David184 what is your PC spec?

**Comment by tsunamayo** [comment]
@David184 @JackOTHy Also you could you send me the content of the folder below?
Could you please also zip and send me the content of the folder below so I can investigate the crashes?

%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Crashes

Thanks

**Comment by David184** [comment]
i can't find the "crashes" folder. It seems that when it crashed, it didn't made the crashes folder.
my specs are
CPU: Intel Core i5-4590 CPU 3.30GHz
GPU: NVIDIA GeForce GTX 1660 Ti

**Comment by JackOTHy** [comment]
I can neither find it.

**Comment by JackOTHy** [comment]
Heya, I dont want to annoy you, but please fix the Character Creation Crash. I have the game for about 2 weeks and still cant play... -_-
