### ISSUE TITLE
[BUG] barrels do not paste properly 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3723]
### Short Description of the issue:
when copy pasting gun barrels they will not paste something that is super annoying when copy pasting turrets 
...

### Steps to reproduce the issue:
attempt to copy paste a gun barrel
...

### Environment
- Starship EVO version: 21w13b

### Additional information:

https://user-images.githubusercontent.com/56371294/113793134-71cb3580-96fc-11eb-8003-4eebbc15572d.mp4

**Comment by tsunamayo** [comment]
@TIKIRobo This works fine as of 21w47b. Thanks!
