### ISSUE TITLE
[BUG] improper collisions on 6 way connector large when adjacent to another block 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3725]
### Short Description of the issue:
6 way connector's hitboxes break when next to 3 other blocks
...

### Steps to reproduce the issue:
place down multiple 6 way connectors 
...

### Environment
- Starship EVO version: 21w13b

### Additional information:

https://user-images.githubusercontent.com/56371294/113946022-5cb5db80-97bc-11eb-9760-5b0fcb3c52f0.mp4

![image](https://user-images.githubusercontent.com/56371294/113946040-68a19d80-97bc-11eb-9041-b171fe3e2e11.png)

**Comment by tsunamayo** [comment]
@TIKIRobo Fixed in recent versions. Thanks
