### ISSUE TITLE
[SUGGESTION] Glow Tile with On and Off states and can be linked to logic. 

### ISSUE THREAD

**Issue by Servomotor** [tsunamayo/Starship-EVO#3726]
Thank you your highness, most glorious and wondrous of game developers for hearing the plight from many of us in regards to glowing bits/luminescent stuff. We are ecstatic and pleased with your creation. 

if I may approach you humbly and offer a minor suggestion, one I am sure you have already considered, but could we get the various glowing parts linkable to logic, to be turned on and off? 

Thank you for taking time out of your day to consider this suggestion. 

Faithfully, your most humble servant, 
Servo

**Comment by Kaiser-Indrasil** [comment]
I would love if the light was slowly fading in and out, just like the reactors do when you toggle them on and off. I could make a simple loop and a breathing light effect with that

**Comment by tsunamayo** [comment]
Hi ;) so while I understand this I have to be careful with that, it would mean that each block would be a command with the memory overload ect. I expect people to place quite a few of these... Also for the breathing effect this is not something the current command system is made for, it is not optimized for this.
I will just wait a bit and see what use of the block I see.
Cheers

**Comment by Servomotor** [comment]
Thank you your Highness for replying. Your have fair points. Perhaps we could just get the triangle flat and square flat glow tiles as ones that can be linked to.  This would allow for some custom freedom, but would also ensure that the logic is kept to a minimum. This of course could be tried out after you have seen how much glowing parts are abused and after your voxel elimination is done (I know that has to be a ton of work). 

Thank you!

**Comment by tsunamayo** [comment]
Sir @Servomotor , your wish has been granted. Thx
