### ISSUE TITLE
Suggestion: Tape measure. 

### ISSUE THREAD

**Issue by insanebotv21** [tsunamayo/Starship-EVO#3727]
Not just to measure blocks, but to also potentially place a visible distance measurement in 1-3 axis to make building easier.
It could actually work similarly to the old copy paste tool but instead of copying and pasting it just tells you the height width and depth.

**Comment by tsunamayo** [comment]
Hi, to be honest while it is a valid idea I wont have the bandwidth to work on that. So you will have to use blocks to measure something... Thanks
