### ISSUE TITLE
SUGGESTION : Wooden Bricks

### ISSUE THREAD

**Issue by Zodster** [tsunamayo/Starship-EVO#3728]
Hiya! 
I was thinking how much i liked the wooden blocks
tho you can do a lot of different things combining colours and and decals on normal blocks in order to make different textures and such, I felt that it would be an amazing and seemingly easy enough addition to add a wooden brick building block or to, same size and shape of the normal 1x1 building bricks or wedges but with a wooden texture.

I'd Honestly love to see it in game and i really hope you consider it!

-Zoda

**Comment by tsunamayo** [comment]
Hi, yes I will do a material wood paint in the next update. Thanks
