### ISSUE TITLE
[BUG] Landing Gear Collision Issue with Half bricks 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3730]
### Short Description of the issue:
my landing gear hover .25 m above the "ground" while docking. it does not do this when over terrain 
...

### Steps to reproduce the issue:
attempt to land this ship:
[New Entity with bugged landing gear.zip](https://github.com/tsunamayo/Starship-EVO/files/6298350/New.Entity.with.bugged.landing.gear.zip)

...

### Environment
- Starship EVO version: 21w13b

### Additional information:

https://user-images.githubusercontent.com/56371294/114429721-88491500-9b72-11eb-971d-5bd8fff8ad72.mp4

**Comment by tsunamayo** [comment]
@TIKIRobo Issue is fixed in recent build. I really like your form factor mate, very original. thx
