### ISSUE TITLE
[BUG] Ship Movement Bugged

### ISSUE THREAD

**Issue by Sidmoka7** [tsunamayo/Starship-EVO#3732]
### Short Description of the issue:

Have had this bug for months now and haven't reported it yet, basically when steering a ship left, ship also goes in reverse at full speed, and when turning right, the ship goes forward at full speed.  

### Steps to reproduce the issue:

I forgot which build of the game I first got it in, but it started when I interacted with a ship computer on a ship I was building, the game lagged and then when I got in the ship and it was bugged as described. At first it was only that ship bugged, but after restarting the game all ships had the bug.

### Environment
- Starship EVO version: 21w13b
- Graphics Card: Nvidia Geforce GTX

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Sidmoka7 Hi, sorry for the lack of update, my guess is that you had changed the keybind of vehicle control. Thanks
