### ISSUE TITLE
Entering a spacecraft and turret by the same yoke softlocks player input and view

### ISSUE THREAD

**Issue by insanebotv21** [tsunamayo/Starship-EVO#3735]
### Short Description of the issue:
The turret 
...

### Steps to reproduce the issue:
Set up a turret to follow spaceship cursor. 
Set up a spacecraft. 
Add a seat.
wire them to the same yoke. 
wire the weapon/pointer to a hotkey, then to the yoke(optional).
Sit in the seat(the seat is optional it softlocks either way) then enter the spacecraft. 
congratulations you have now softlocked all player input. This includes changing the view, trying to exit the yoke, moving the mouse, pressing f3, pressing any of the command keys such as f5, clicking, and anything shy of pressing escape to exit to menu. 
this persists and does not go away with time. 
reloading will often but not always free up player input allowing you to exit and/or control the craft normally. 
...

### Environment
- Starship EVO version: 21w13b
- Graphics Card: 1660 TI 

### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6305287/Player.log)

[Example blueprint because i guess it's better than nothing.zip](https://github.com/tsunamayo/Starship-EVO/files/6386097/Example.blueprint.because.i.guess.it.s.better.than.nothing.zip)

**Comment by tsunamayo** [comment]
Issue fixed in recent updates!
