### ISSUE TITLE
[BUG] ship bounds do not update in "reverse"

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3736]
### Short Description of the issue:
when deleting say large wings off of a ship the ships boundaries will not shrink, this effects not only the size of the mirror plane but also the measurements given in the codex, landing pads you are able to land on as well as camera zoom
 
...

### Steps to reproduce the issue:
build a large stick
delete half of it 
...

### Environment
- Starship EVO version: 21w13b

### Additional information:

https://user-images.githubusercontent.com/56371294/114629929-54ebb080-9c6e-11eb-8728-cfbd4f7777c2.mp4

**Comment by tsunamayo** [comment]
@TIKIRobo Actually fixed a few update back. Thanks
