### ISSUE TITLE
[FEEDBACK] On ship audio/sound effects. 

### ISSUE THREAD

**Issue by Servomotor** [tsunamayo/Starship-EVO#3737]
I love the ship sound effects and audio. I love the start up sound when you get into the yoke and the general movement sound when flying around. 

I know you have a lot of core/foundational work to do with the new stretch tech/voxel elimination/migration, planets, etc. But I would love to see a way to give ships sound bricks/blocks. Basically a vehicle effects brick that we can select either a number of presets (imagine voice selection for characters in games like Elder Scrolls Online), or a some sliders to tune our ships sound. 

I have never seen audio customization done and I think it could help Starship Evo to stand apart from the competition, on top of the already stellar building capabilities. I dont know if there would be a performance impact (i imagine not, just would increase the file size on our PC's). 

Thank you again.

**Comment by BigBadKangaroo** [comment]
100% agree on that. Having the option to give our ships a uniqe sound would be amazing! 
Doesn't need to be an audio mixer typ of thing, presets would do the job just fine for that.

**Comment by tsunamayo** [comment]
Hi, it would be amazing indeed but honestly I will never have time for this... I think I have done enough to stand out from the competition building wise, I need gameplay...
Cheers
