### ISSUE TITLE
artificial gravity doesn't allow you to disable jetpack in space

### ISSUE THREAD

**Issue by amplified1** [tsunamayo/Starship-EVO#3738]
it's all in the title, it just doesn't work, when you turn on gravity aligning jetpack you do align but there is no way to turn off the jetpack entirely unless you are in a habitat

**Comment by amplified1** [comment]
I also can't request landing on a landing pad

**Comment by amplified1** [comment]
Buttons also seem to randomly be much more prone to floating off of their blocks when child entities are moved

**Comment by tsunamayo** [comment]
Hi, all should be fixed now.
