### ISSUE TITLE
[BUG] Physics does not completely freeze when in camera mode 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3739]
### Short Description of the issue:
physics does not freeze completely and so some ships will touch something and then start moving very quickly, then once you unfreeze the ship will launch itself a few KM away  
...

### Steps to reproduce the issue:
land a ship, then go into f6 mode
...

### Environment
- Starship EVO version: 21w13b
 
### Additional information:

https://user-images.githubusercontent.com/56371294/114927708-a1f29280-9de6-11eb-958f-5051e3570288.mp4

**Comment by tsunamayo** [comment]
@TIKIRobo Hi, this will be fixed for 22w04a. Thanks!
