### ISSUE TITLE
Copy and paste doesn't work properly for logic blocks

### ISSUE THREAD

**Issue by Pharap** [tsunamayo/Starship-EVO#3740]
### Short Description of the issue:

When copying and pasting a circuit made of connected logic blocks:
* The logic blocks do not retain their gate type, they all revert to the default (an or gate)
* The connections between the blocks are not copied either

(I noticed this because I was attempting to chain a few full adders together in the hopes of building a small computer or calculator. Being able to copy circuit sections would reduce the manual work by nearly 1/8th.)

### Environment
- Starship EVO version: 21w13b (Experimental Branch)

**Comment by tsunamayo** [comment]
Yes it is still wip. Thanks
