### ISSUE TITLE
Handheld weapon building not working.

### ISSUE THREAD

**Issue by jealousdequan** [tsunamayo/Starship-EVO#3743]
### Short Description of the issue:
Handheld weapon building is broken due to the fact that you cannot place blocks on the handles at the moment.
...

### Steps to reproduce the issue:
Place down item stand, place handle in item stand, try to place block on handle.
...

### Environment
- Starship EVO version: 21w13b
- Graphics Card: Geforce GTX 1070

### Additional information:

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6326913/Player.log)

https://user-images.githubusercontent.com/72936878/115061404-23b1f100-9eb7-11eb-93ef-4568b611f61e.mp4

**Comment by Kaiser-Indrasil** [comment]
It was already reported in #3709

**Comment by tsunamayo** [comment]
@jealousdequan Handheld are fixed for 21w49a. Thanks
