### ISSUE TITLE
warp travel times

### ISSUE THREAD

**Issue by Dalekdozer** [tsunamayo/Starship-EVO#3744]
### Short Description of the issue:
For 15+ minutes across two sessions I have been at warp, with nothing else happening.
...

### Steps to reproduce the issue:
redo your interior while at warp?
...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by TIKIRobo** [comment]
from what i can tell the ships just kinda, stop, they go from 5mn/s to 0m/s and then get "stuck" mid warp
![image](https://user-images.githubusercontent.com/56371294/115326529-4277e800-a142-11eb-8900-b3e3a2d655b2.png)

**Comment by Xerma** [comment]
#3741

**Comment by Calvert4096** [comment]
I'm getting this too.  I made a bare-bones warp capable ship and still warp lasts indefinitely unless you quit/reload, at which point it drops you in interstellar space.

**Comment by tsunamayo** [comment]
@Dalekdozer Fixed for 21w47b. Thanks!
