### ISSUE TITLE
[BUGS] 

### ISSUE THREAD

**Issue by Zodster** [tsunamayo/Starship-EVO#3747]
[hoe.zip](https://github.com/tsunamayo/Starship-EVO/files/6344612/hoe.zip)

Changed to experimental, made anew world, loaded in my current spaceship im building, walked around in it a bit, bounced up into space at the speed of light for no reason, spawned in another ship to go get the other one, then got stuck in that and couldnt do anything, also apperantly this new voxel tech is supposed to help me out fps wise but it changed nothing for me.

**Comment by Kaiser-Indrasil** [comment]
You can press F5 to go into no-clip mode to un-stuck your character.
Also, the new tech is over at the 4th branch, not on the Experimental.

**Comment by Garrett-C** [comment]
The new voxel tech isn't in experimental as far as I know. It is in it's own preview branch.
