### ISSUE TITLE
bug: some newly made saves not appearing. 

### ISSUE THREAD

**Issue by insanebotv21** [tsunamayo/Starship-EVO#3748]
### Short Description of the issue:
When making a save and exiting to title from that save sometimes the save will not appear on  the list. Occasionally the save will reappear later. 

### Environment
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/6352400/Player-prev.log)
- Starship EVO version: 21w13b

**Comment by tsunamayo** [comment]
Hi, what do you mean, are you talking about a character save, or a blueprint save? Thanks
