### ISSUE TITLE
4-to-1 offsets have gone a bit weird

### ISSUE THREAD

**Issue by SovietSponge** [tsunamayo/Starship-EVO#3750]
### Short Description of the issue:
Tried to see how my hole-in-the-wall fast food place did through the conversion, 4-to-1 offsets went a tad weird but otherwise i've noticed no issues yet.
...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 21w15a
- Graphics Card: GTX 1050Ti

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/6359439/output_log.txt)
![image](https://user-images.githubusercontent.com/66131361/115741295-e6a29e80-a38f-11eb-8198-2787cf6c2e33.png)

[SSSS food.zip](https://github.com/tsunamayo/Starship-EVO/files/6359472/SSSS.food.zip)

**Comment by tsunamayo** [comment]
Indeed, issue fixed for the next preview. Cheers
