### ISSUE TITLE
Heavy visual artifacts.

### ISSUE THREAD

**Issue by SnowyBirdot** [tsunamayo/Starship-EVO#3752]
### Short Description of the issue:
Heavy visual artifacts assumed in response to high decal count.
...

### Steps to reproduce the issue:

High decal density I guess? I'm not actually sure what caused this.
...

### Environment
- Starship EVO version: 21w13b
- Graphics Card: GTX 1050 TI

### Additional information:

Video footage of glitch: https://imgur.com/a/CX1WS4J

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/6371825/output_log.txt)

[Rapier I or 2, or custom, I'll figure it out.zip](https://github.com/tsunamayo/Starship-EVO/files/6371827/Rapier.I.or.2.or.custom.I.ll.figure.it.out.zip)

This blueprint should be up to date as well.

**Comment by tsunamayo** [comment]
@SnowyBirdot Fixed in recent versions. Thanks
