### ISSUE TITLE
[Bug(s)] "Transcendence" camera bugs

### ISSUE THREAD

**Issue by AlienXtream** [tsunamayo/Starship-EVO#3755]
### Short Description of the issue:
"just tell Tsuna "Xeno's crap broke my Sevo!"" - Xenoprophet_Nail, STEVO discord.

got a looping sound bug
reloaded save (without exiting game, just to main menu)
camera broke and controls/camera (other than esc) became unresponsive on reload. abnormal FoV causing "out of body" effect
exited to main menu again, deleted "corrupt" save and created a new one
camera remained broken and starting structures failed to load (game is also unresponsive again other than esc)
attempted to exit to desktop and... well.... i dont really know how to explain it other than to reference portal 2's "space core" meme... take a look at the screenshot. there is the galaxy and what appear to be hud elements... i have NO idea what happened 

...
### Steps to reproduce the issue:
honestly it all happened so fast 
...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:
![image](https://user-images.githubusercontent.com/12606809/116569906-2bf53c00-a94d-11eb-8188-9d8edf952478.png)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/6399500/output_log.txt)

player.log too big

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@AlienXtream Hi, so regarding the log it is the log of the broken session after the reload? I am after what happen before the quit to title. Once you have a big issue it is always better to quit to title (and send me the log of course ;)
Thanks
