### ISSUE TITLE
menu sounds do not scale up or down with sound settings

### ISSUE THREAD

**Issue by gertvdwalt** [tsunamayo/Starship-EVO#3756]
### Short Description of the issue:

The "new" sounds added when pressing exit or opening the menus or build menu etc stays at the same volume even when changing game volume and music volume. 

### Steps to reproduce the issue:

Change volume in settings

### Environment
- Starship EVO version: latest experimental  
- Graphics Card:  n/a?

**Comment by Kaiser-Indrasil** [comment]
Yeah, it's a long-standing bug, still needs to be addressed.

**Comment by tsunamayo** [comment]
Hi, it was fixed a few build back. Thanks
