### ISSUE TITLE
No texture/graphic for blocks placed occasionally

### ISSUE THREAD

**Issue by Imzaphod** [tsunamayo/Starship-EVO#3760]
### Short Description of the issue:
About 8 out of 10 blocks I place have no textures or graphics depending on what you want to call it. They look invisible, however, their hit boxes are still in the game and blocks can be placed on them.
...

### Steps to reproduce the issue:
Just place a block
...

### Environment
- Starship EVO version:  Current stable
- Graphics Card:  I9-9880H CPU, 32GB ram, Nividia 2080

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by TIKIRobo** [comment]
Yeap this is a known bug, unfortunately it hasn't been fixed yet due to how inconsistent it is, i can play for hours and hour without seeing a single invisible block or i can see one with in the first 15 minutes of playing, your best bet is to restart as that will make the blocks visible again.

**Comment by ProPeach** [comment]
Can you upload your player.log file? It's super helpful in situations like this, the file path is in the Additional Information in your report
