### ISSUE TITLE
XInput

### ISSUE THREAD

**Issue by JackTSpade** [tsunamayo/Starship-EVO#3761]
### Short Description of the issue:
Suggestion:
Given that it's a vehicle-centric game, I suggest/request controller support. It's already bindable, but there are no defaults, and a lot of the menus are set up for keyboard and mouse. Some command wheels or shift keys would make the game completely playable with a gamepad. (Also, look isn't rebindable if I remember correctly)
...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by KINGrimson** [comment]
i do not get why you need a controler for game that is ment for pc and only pc where keyboard is the best choise to play it

**Comment by JackTSpade** [comment]
@KINGrimson

-Saying keyboard is the best choice is a circular argument. It's best because there's no controller support. If that changed, K&M wouldn't be best anymore.
-While K&M is superior in first-person shooters and real-time strategy, where quick and precise clicks decide the game, K&M provides inferior movement control. Any game where fine movement control is important, such as racing and flying games, benefits from joystick support. The standard XInput gamepad has triggers for throttle or yaw, and two sticks for orientation and movement. That's more important than quickscoping in Starship EVO.
-Having a few dozen individual buttons on a keyboard makes it easier to map every function to its own button, but with the right contextual inputs, that advantage disappears. Holding a button and selecting an option from a radial menu is slower than hitting a hotkey, but the difference is negligible as long as the primary functions-- the ones that must be accessed in a hurry, like shooting and sprinting-- are accessible from the default state.
-XInput support became standard in the 2010s, the K&M-only mentality is about as outdated as old shooters that only used the keyboard minus the mouse. A lot of PC gamers are coming to the platform from a console background, and controller support helps them adjust. But there's still a lot of vestigial K&M elitism from older PC players that want to feel superior to former console players (I grew up with both, so I don't take a side.)
-I sincerely believe that controller support affects sales. I don't have any numbers to back it up, so this is anecdotal, but I prefer to play certain genres with a gamepad and the presence or absence of controller support has often influenced my decision to buy or pass on many games. I've met many others in the same situation, so I know I'm not the only one. Go to the Steam forum for any game and I guarantee you'll find threads full of similar sentiments.

And besides all that, I'm old enough to remember when console controllers were digital and you had to play on PC if you wanted to use an analog flight stick or racing wheel, so the anti-controller sentiment is bizarre to me. It's a universal gaming input device that works reasonably well with most genres, and exceptional well in some, as long as the game is designed to support it. It's ergonomic, it allows the game to appeal to new PC gamers, it has its own mechanical advantages, and if the game ever makes its way to consoles (more sales), it'll need controller support anyway.

**Comment by XenZombie** [comment]
I use Keyboard and mouse AND a control. I have no idea why people have an issue with adding this functionality. 
It literally expands your fan base. AKA MORE MONEY..

I also have no idea why people take issue with how people play when it has no effect on them.

**Comment by Kaiser-Indrasil** [comment]
I, for one, would love a full controller support. It would help with cinematics to be able to pull off those smooth camera pans.

**Comment by tsunamayo** [comment]
Hi, I wont have time for this before a while unfortunately! Thanks

**Comment by XenZombie** [comment]
Doh.. I would think at least (if I was making a game) controls would be the first thing to nail down before your berried in work.
Considering it doesn't matter how good a game is if you cannot control it.

**Comment by Kaiser-Indrasil** [comment]
> 
> 
> Doh.. I would think at least (if I was making a game) controls would be the first thing to nail down before your berried in work.
> Considering it doesn't matter how good a game is if you cannot control it.

Wdym, "cannot control it"?

You can, just use M&K for now.

I want XInput too, but I can see it not being a priority right now.

Plus, there's literally just building and fighting, and the mouse steering is pretty alright on the mouse. The control scheme is a bit like from Elite: Dangerous, so you don't have to swipe your mouse all the time (_coughfreespace2cough_)

**Comment by JackTSpade** [comment]
I understand not finalizing the controls before you're even sure what's going to be in the game. It would suck having to do everything over again. I'd just like it to be on the list for later, when the game more or less looks like it's going to.

Movement controls mostly work, except for triggers and right stick. It's just a matter of getting some menus for building, toggles for jetpack, etc.

**Comment by XenZombie** [comment]
I know there is keyboard and mouse. Did you really think I believed he released a game with no control's whatsoever?

All I'm saying is; if your building a game, it's best to focus on the MAIN things that make it a game first. If you plan on using controls, then set it up.
Why? Because who knows what else will change in the future. If you leave core things for later it gets buried under a pile that just gets bigger. Also, once the basic control's are setup you can change and optimize as the game evolves rather than just duck taping it on later.

Whatever, do what you want.

**Comment by JackTSpade** [comment]
> 
> 
> I know there is keyboard and mouse. Did you really think I believed he released a game with no control's whatsoever?
> 
> All I'm saying is; if your building a game, it's best to focus on the MAIN things that make it a game first. If you plan on using controls, then set it up.
> Why? Because who knows what else will change in the future. If you leave core things for later it gets buried under a pile that just gets bigger. Also, once the basic control's are setup you can change and optimize as the game evolves rather than just duck taping it on later.
> 
> Whatever, do what you want.

Easy, we all want the same thing. I'm sure he meant no offense.

**Comment by tsunamayo** [comment]
Thanks all, I understand your position all. It is a big project, and unfortunately I cant spend much time on a feature that will take a lot of time to develop (it is not easy, if possible at all with all the button mapping we have), that would be used only by a small percentage of players. Dont hold your breath!
Cheers

**Comment by XenZombie** [comment]
@JackTSpade 
lol, I wasn't raging or anything. I think you need to relax not me lol.

@tsunamayo 
Yeah, 48 million people. That's a small amount of people. Sure.
It's hard? Damn, your right. Why do it at all. Lets just quit life.

Whatever, I love what you have done so far, but you have told me everything I need to hear. I'm done with this game.

**Comment by XenZombie** [comment]
> I understand not finalizing the controls before you're even sure what's going to be in the game. It would suck having to do everything over again. I'd just like it to be on the list for later, when the game is more or less finalized.
> 
> Movement controls mostly work, except for triggers and right stick. It's just a matter of getting some menus for building, toggles for jetpack, etc.

Yeah, simply adding the ability to use the control to rebind functions our selves would almost be enough. Vast majority of games on my steam list in alpha at least have that.
