### ISSUE TITLE
Ship Destroyed

### ISSUE THREAD

**Issue by Robin-SW** [tsunamayo/Starship-EVO#3762]
### Short Description of the issue:
Was on halo-ring like structure, and logged off
Now spawn in in space, sometimes without any skybox, othertimes you can see the skybox be rendered in in 'squares'
Spawn in ship using the 'starting block' (cant remember proper name, block used to start a build).
Ship declares it's destroyed as soon as flown (in that rectangle at bottom right of screen), despite no damage available.

...

### Steps to reproduce the issue:
Same occurs when i try make a makeshift ship and fly it away, it flies for a few moments then the little rectangle at the bottom right of the screen says it's destroyed
...

### Environment
- Starship EVO version: 
- Graphics Card: 
- 6gb gtx 1060

### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6423885/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/6423886/Player-prev.log)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by TIKIRobo** [comment]
I'm pretty sure you have just spawned in inside of the near-by star, hit F3 and enable fast move keys then use [ and ] to speed up and slow down, then fly out of the star, you can also enable teleport to anything then open your codex (tab menu) then click on the symbol that looks like a guy getting beamed up mid step, then find the thing labeled habitat then click on that
