### ISSUE TITLE
[Misc] Large SFX Library Download

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3763]
Just thought I'd share this huge free library of sound effects that was recently posted on r/gamedev as I'm not sure you browse that sub, happy Star Wars day!

https://www.reddit.com/r/gamedev/comments/n4vhcs/150gb_of_high_quality_sound_effects_for_game/?utm_medium=android_app&utm_source=share

Feel free to close this post when you've seen it o/

**Comment by AlienXtream** [comment]
well.... holy.... thats.... wow.... 150 gigs... ima download this myself. idk why i would need it but damn, i aint gunnu pass this up while i remember it exists... i have a feeling a fair few indi games are gunnu be sounding an awful lot alike, at least more so that before XD

**Comment by Zenti98** [comment]
Wow, thanks for posting this - happy Star Wars day! :-)

**Comment by Kaiser-Indrasil** [comment]
This will be a fine addition to my collection

**Comment by tsunamayo** [comment]
@ProPeach Thanks, I remember this give away from previous years. There is a lot of content, if you hear anything cool ping me! (it takes ages to navigate into everything...)
