### ISSUE TITLE
[BUG] Stuck after returning to a game from the title screen - No Voxel Preview #5

### ISSUE THREAD

**Issue by Viper287** [tsunamayo/Starship-EVO#3765]
### Short Description of the issue:

After quitting to title from my game I came back a while later and loaded into the same game as before. I was met with the empty image below. My ship also disappeared, and I can't seem to respawn it, however, the other ships in the world were fine when I came back.
...

### Steps to reproduce the issue:

I tried reproducing it, and it only happened when I had mirroring activated down the middle of the given blueprint (I didn't try it on any other ships though). 

My steps:
1. Load up a save
2. Place a mirroring on a ship (optional? I had it happen one time without any mirroring)
3. Quit to title
4. Re-load the save
...

### Environment
- Starship EVO version: voxel_removal_preview
- Graphics Card: RTX 2060 (Laptop version?)

### Additional information:

Here is a picture of me stuck after loading the world. I was standing inside a ship, but you obviously can't see it.
![20210505211100_1](https://user-images.githubusercontent.com/83744434/117396670-49775800-aeaf-11eb-9e7f-734c3d1926dc.jpg)

Here is a zip file with the player log and the ship blueprint:
[Bug report.zip](https://github.com/tsunamayo/Starship-EVO/files/6438959/Bug.report.zip)

**Comment by tsunamayo** [comment]
@Viper287 thanks a lot, I was able to reproduce the issue and fixed it. Will be in the upcoming experimental build. Thanks
