### ISSUE TITLE
[BUGS] issues on the voxel removal branch

### ISSUE THREAD

**Issue by matejkar** [tsunamayo/Starship-EVO#3766]
### Short Description of the issue:
After getting back into Sevo after some time i checked out the new branch. And first off i gotta say Amazing job tsuna, you just made a job for someone like me who lived off building capital ships primarily much easier. 
However there are tons of issues which i have not seen being adressed before.
I will be providing screenshots and ship files for all mentioned

Those would be:
1. After the new lighting update, the heat of the ships is all screwed up, and ships which had no issues before now cannot be piloted because of too much heat. Also currently, the lighting looks hideous compared to the stable build (i hope its still work in progress).
2. I am aware that ships in the voxel removal build are meant to take no damage, however while testing the firepower of some of my larger ships on some small ones, the small ones were getting destroyed while still appearing full HP, and with no visible damage on the ships.
3. From what i can see, large weapons cannot be inspected with 'F', as i was using that to check the damage being dealt by a larger laser or beam. Also weapon barrels seem to have graphical issues. 
4. Bizzare graphical glitches in lighted areas.

### Steps to reproduce the issue:

1. issue - Spawn a large ship with lots of lights, or a great amount of heat. The ship should be unpilotable now, as the lights for some reason screw up the heat on the ship (i dont believe it could be anything else except lights, since the ship had about %60 heat pre-test). The lights can be checked easily, and i hope that it is a Wip or a local issue. For confirmation spawn the ship in the stable build, and then in the voxel removal build.
the ship i used when i found the heat bug: 
[Kraftwerk - class super dreadnought.zip](https://github.com/tsunamayo/Starship-EVO/files/6444542/Kraftwerk.-.class.super.dreadnought.zip)
workshop: https://steamcommunity.com/sharedfiles/filedetails/?id=2362533645

![20210507234407_1](https://user-images.githubusercontent.com/69653738/117514055-4c4b7900-af93-11eb-9dc6-1728736b151d.jpg)
![image](https://user-images.githubusercontent.com/69653738/117514069-52415a00-af93-11eb-9e66-43a022802832.png)

2. issue - Simply have a very large ship attempt to destroy a significantly weaker one (capital vs strike craft for example). As i said previously, the smaller ship should get destroyed, but still appear full HP, and with no visible damage. Also the "destroyed" ship cannot be piloted after "destruction".
The ships i used:  - the destroyer: 
[Lacerator - class battlecruiser.zip](https://github.com/tsunamayo/Starship-EVO/files/6444557/Lacerator.-.class.battlecruiser.zip)
https://steamcommunity.com/sharedfiles/filedetails/?id=2374432676
                            - the destroyed: https://steamcommunity.com/sharedfiles/filedetails/?id=2465909652  (cannot do a .zip, workshop will have to do)
3. issue - spawn a size 4 weapon and try to inspect it.
the barrel bug: 
![20210508000153_1](https://user-images.githubusercontent.com/69653738/117514160-84eb5280-af93-11eb-929e-4f61773507d4.jpg)
(these are length 1 recoil barrels, if you want to find more of them yourself, the Lacerator i attached above is filled with the turrets as in the screenshot)

4. Not sure how to reproduce, happened when viewing large lighted areas in large warships. Try it on the Kraftwerk and the Lacerator i pinned above.
![20210507235316_1](https://user-images.githubusercontent.com/69653738/117514247-b3692d80-af93-11eb-8deb-9fb82360f2d3.jpg)
notice the weird graphical issue at around the center of the screen.

### Environment
- Starship EVO version: 21w15a
- Graphics Card: 1060ti

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6444593/Player.log)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/6444594/output_log.txt)
here are both player and output logs, idk now which ones are more or less important 

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.
ships attached above

**Comment by tsunamayo** [comment]
@matejkar Hi, all the issue will be addressed, and 4 already have. Now why do you think lighting looks hideous, is it because of the dark patches (its a bug - fixed), or because of something else? Thanks

**Comment by tsunamayo** [comment]
and if else can you give me some screenshot or place to compare? Thanks

**Comment by matejkar** [comment]
@tsunamayo Honestly, if that lighting as seen in the screenshots is the final look i have to say it maybe looks worse then the stable branch. To me the lighted areas seem way too dashed 
![20210508103316_1](https://user-images.githubusercontent.com/69653738/117532820-c6a6e800-afe9-11eb-8377-060a9b1f8b3e.jpg)
![20210508103809_1](https://user-images.githubusercontent.com/69653738/117532824-c7d81500-afe9-11eb-8bc4-7bcc64dc4614.jpg)

**Comment by matejkar** [comment]
Also, that ship i just looked at is seriously messed up now in the voxel removal branch:
![20210508104223_1](https://user-images.githubusercontent.com/69653738/117532914-256c6180-afea-11eb-8246-c4892baf9f20.jpg)
![20210508104229_1](https://user-images.githubusercontent.com/69653738/117532915-2604f800-afea-11eb-8fb1-c0a1e13a995c.jpg)
![20210508104235_1](https://user-images.githubusercontent.com/69653738/117532916-269d8e80-afea-11eb-8e6c-1f97e78d609b.jpg)
the stable build look...
![20210508103818_1](https://user-images.githubusercontent.com/69653738/117532936-3321e700-afea-11eb-982c-209f5419b851.jpg)
![20210508103825_1](https://user-images.githubusercontent.com/69653738/117532937-33ba7d80-afea-11eb-914d-2a04d9db6208.jpg)
![20210508103832_1](https://user-images.githubusercontent.com/69653738/117532938-34531400-afea-11eb-8608-650d631a624c.jpg)
the voxel removal build... yikes
the ship: https://steamcommunity.com/sharedfiles/filedetails/?id=2375511143
voxel's player log:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6445547/Player.log)

**Comment by AlienXtream** [comment]
> @tsunamayo Honestly, if that lighting as seen in the screenshots is the final look i have to say it maybe looks worse then the stable branch. To me the lighted areas seem way too dashed
> ![20210508103316_1](https://user-images.githubusercontent.com/69653738/117532820-c6a6e800-afe9-11eb-8377-060a9b1f8b3e.jpg)
> the stable build look
> ![20210508103809_1](https://user-images.githubusercontent.com/69653738/117532824-c7d81500-afe9-11eb-8bc4-7bcc64dc4614.jpg)
> the voxel removal look (after the recent update, so i agree that its better now)

i would say the bloom is a bit bright and wide, specular is a bit strong near the lights and the falloff needs to be softer (probably why it looks off to you). having things like the bloom and specular being variable sliders in the settings menu would probably be a good idea.

**Comment by tsunamayo** [comment]
@matejkar so I fixed the conversion issue, it was a regression of the latest preview. For the falloff, it is already nerfed compared to real life. New lighting is now correct, where before it had no real specular applied to it. Which means non painted surface looked okay with the old tech, but now they are very reflective in the new one, as it should be.
I would say paint your wall first, then use a grayer color for your light if it is still too strong. In a lot of other more finished interior the new lighting actually improved the look. I will tweak it if a lot more other people comes with the same feedback though.
Cheers

**Comment by matejkar** [comment]
@tsunamayo good job, glad to help
