### ISSUE TITLE
Game crashing on load

### ISSUE THREAD

**Issue by berrigo2** [tsunamayo/Starship-EVO#3767]
### Short Description of the issue:
Whenever I try and load one of my old game files or create a new character the game freezes and crashes. New character isnt created when I load back into the game.
...

### Steps to reproduce the issue:
start sevo
pick character
crash
...

### Environment
- Starship EVO version:  normal steam branch
from steam updates tab:
app id: 711980
build id: 6268529

- Graphics Card: gtx 960M

### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6444746/Player.log)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@berrigo2 Hi, thanks for booking the case, lets fix your issue.
First it seems that the game is running on a NVIDIA GeForce GTX 1050, not a 960M. 
Then it seems the error is related to your Directx install. Could you make sure that your windows and river are up to date?
What is your OS?
Thanks

**Comment by berrigo2** [comment]
I'm running win10. Also 1050 sounds right I forgot what kind of card I had.
Will attempt driver update soon

**Comment by tsunamayo** [comment]
@berrigo2 so attaching stuff to your mail wont work, you have to use the website to attach files. Thanks
