### ISSUE TITLE
Suggestion on LCD Windows

### ISSUE THREAD

**Issue by TheShadowSage** [tsunamayo/Starship-EVO#3772]
### Short Description of the issue:
Suggestion: Make a quick devblog about the LCD screens and how we can use html coding to make cool customized windows and all that!

**Comment by TheShadowSage** [comment]
> There's no HTML support in the game. However, you can use provided sprites by typing in "<sprite=xxx>" where xxx is the sprite's number.

Thank you! Are there more codes/commands you can use for the LCD displays? The tutorial didn't cover them much at all.

**Comment by Kaiser-Indrasil** [comment]
Nope, that's about the only one you can use.

**Comment by Kaiser-Indrasil** [comment]
@TIKIRobo Another thing I didn't know about LCDs. Thanks, Tiki!

**Comment by RockefellerDoctor** [comment]
> 
> 
> There's no HTML support in the game. However, you can use provided sprites by typing in "<sprite=xxx>" where xxx is the sprite's number.

imho the game SHOULD have html coding. The game is already all about absolute building freedom; the dev should lean into that idea fully and let us completely code our ships how we want.

**Comment by Xenoprophet-Nail** [comment]
I just want pages of text that can be accessed on the screen, I have a way of doing this but.. it may be too difficult for Tsuna
