### ISSUE TITLE
Game hangs indefinitely on launch

### ISSUE THREAD

**Issue by ClarkWalker** [tsunamayo/Starship-EVO#3774]
### Short Description of the issue:
* Summary: Game hangs indefinitely on launch at the loading screen after title menu.

### Steps to reproduce the issue:
* Happens every time I launch the game no matter how I launch it.

### Environment
Windows 10 guest running in VMware Player

- Starship EVO version: IDK, I just purchased it from steam mere hours ago so probably the latest as of this post.
- Graphics Card: 
        - Hardware: Intel Corporation [8086:9A49] 
        - Adapter type: VMware SVGA 3D

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: 
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6464061/Player.log)
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by Kaiser-Indrasil** [comment]
For now it's a tough cookie, because the game' minimum requirements for a graphics card feature a dedicated one - Geforce 750/Radeon R9 270X or higher - and Intel HD is an integrated GPU, not fitting this category.

It's probably not gonna run on it anyway. Maybe in the future when we're closer to release and lower graphics settings roll in.

**Comment by tsunamayo** [comment]
@ClarkWalker Sorry to not have answered sooner, I hope you managed to get a refund. Your GFX card has 128 MB, so I doubt you are playing a lot of 3D game on this! You are way way below the minimum spec.
Thanks
