### ISSUE TITLE
[Suggestion] Make blocks deletable from much farther away

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3776]
Version: 21w15a [NoVox preview round #8]

When stretching and placing down the biggest 32m blocks, the player can place them from as far away as ~460m.
However, we can only remove them from the distance of around half of that, ~230m.
It would be a handy QoL change if we could be able to remove the blocks from the same distance as we can place them.

**Comment by CurioInventorium** [comment]
I think maybe add a confirm button, or a click-and-hold to delete for further distances.
The amount of times I've accidentally deleted a floor section or some other large area because I accidentally right-clicked omg
Especially if I was recording a tutorial.

**Comment by Kaiser-Indrasil** [comment]
...or bring back the Undo function 😏 
But if not, a click-and-hold would do.

**Comment by tsunamayo** [comment]
It is done, it now depends on the block grid size. Thx
