### ISSUE TITLE
[question] approximate number of stars in the in-game universe

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3778]
Me and a few other members of the community were wondering about how many systems there were in the universe (also maybe how many "sectors" there were as well) while talking about how servers could work in the future

**Comment by ExodistSKY1** [comment]
I think it had been mentioned in a past video or so... but it is a massive number for systems... and I think technically each system could be considered a sector. Seeing as you have to warp from system to system

**Comment by tsunamayo** [comment]
Hi, there is 1.102.245 stars in the galaxy.
