### ISSUE TITLE
Blueprint menu dropping my fps at insane levels

### ISSUE THREAD

**Issue by Zodster** [tsunamayo/Starship-EVO#3779]
![image](https://user-images.githubusercontent.com/70779090/118477202-5a716600-b706-11eb-9ac9-9b6e2d359368.png)

Whenever i build something, could even just be a smaler fighter, and i open the ship menu my fps instantly halves itself or worse.
I lost a ship i spent over 100 hours on due to the game not being able to register me clicking the "export local blueprint" button.
Due to the same issue i can barely build anything now, in experimental at least.
[bruh.zip](https://github.com/tsunamayo/Starship-EVO/files/6493294/bruh.zip)

**Comment by Zodster** [comment]
The zip file just at the bottom is the world.
i created a new one to see if it always happens, and yes, yes it does.

**Comment by BigBadKangaroo** [comment]
I have a smiliar issue with a world that is made a long time ago. Sometimes i cant even spawn in new ships because the menu  wont open at all. However this issue is solved by creating a new world.

And yes, my frames drop while opening that menu, too.

**Comment by Zodster** [comment]
For me it happens no matter what world im in.

**Comment by tsunamayo** [comment]
@Zodster Hi, what is your CPU / GPU? I improved this issue in the upcoming patch. Also you cant really loose anything, your ship should still be saved in the character folder. Thanks

**Comment by tsunamayo** [comment]
Issue should be fixed in recent versions.
