### ISSUE TITLE
ghost collisions 

### ISSUE THREAD

**Issue by KINGrimson** [tsunamayo/Starship-EVO#3780]
### Short Description of the issue:
simple, i have a hole and a fighter, want to fit the fighter inside the hole, but cant, it bumps to something even tho their isnt anything to stop it, frame of issue is the right most front, on the right side of the ship, the collsion data is locked into thinking there is some brick thing here
...

### Steps to reproduce the issue:
spawn in provided ship and fly in the provided foghter

...

### Environment
- Starship EVO version: 21w13b
- Graphics Card: rtx 2060

### Additional information:
![image](https://user-images.githubusercontent.com/74992043/118543207-47858280-b754-11eb-9abf-ea2aabeeeb5f.png)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6496275/Player.log)
![image](https://user-images.githubusercontent.com/74992043/118548096-2fb0fd00-b75a-11eb-87fd-1d70c62ef2a0.png)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
![image](https://user-images.githubusercontent.com/74992043/118548073-2758c200-b75a-11eb-9bbc-a37d72c33b57.png)
If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

[ALL ENVOIRMENT FIGHTER (AEF).zip](https://github.com/tsunamayo/Starship-EVO/files/6496289/ALL.ENVOIRMENT.FIGHTER.AEF.zip)
[UWF-DOMINION 2.zip](https://github.com/tsunamayo/Starship-EVO/files/6496291/UWF-DOMINION.2.zip)

You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
Issue fixed for next experimental 21w21a! Thanks for spotting that one. Did you made those ships? Cheers

**Comment by KINGrimson** [comment]
> Issue fixed for next experimental 21w21a! Thanks for spotting that one. Did you made those ships? Cheers

yew i build these, the fighter is still up-to-date, but the big one has gone over a major face lift

**Comment by tsunamayo** [comment]
@KINGrimson tremendous job mate, really impressive ship!
