### ISSUE TITLE
[Sugestion] Few working mechanisms. 

### ISSUE THREAD

**Issue by ArthKriger** [tsunamayo/Starship-EVO#3781]
Hello, before I even begin, I want to thank. You gave birth a game that I was eager to find and play. I had my quote of space games only to find some like yours do. Allow me to build and use a full operating spaceship. So, thank you very much. This game will be my crownjuel of games. 

Now, my first suggestion is, please try to fix or improve the desync problem. After loosing a few hours working on my first ship me and my sister and at the very end we found out that we could flying it? That kill us. But we remain hopeful. So if you could patch it and see if there is anything you could do make it better I would be grateful. This game as the highest potential to become one of the games more playful in multiplayer I'm sure of it. So, with no more delays. A few things I would love see in the future. Hopping that this goes with you main goal or final aim.

2nd - as huge fun of startrek, I must ask you please, Put any kind of IA, a mainframe computer that will help us manage the ship.

3th - alert and alarms, make like IA alert us from hostile or unknown ships. Or alert us for O2 leak. Or fire location or damage location. Or even tell us how weakly our shield goes.

4th- security system. Keypad (pins), card readers, hand reader. To other players and NPC need to have in order to create a guild or group sistem or even create rankings in our on ship.

5th — O2 system or life support system. Very important in any spaceship.

As for now this are my suggestions. Hopefully I love to contribute. Ask u once again please fix the desync issue, for the alpha, beta experience get even greater.

With best regards

**Comment by ArthKriger** [comment]
Hello again, I ask you to nevermind the 1st suggestion, You are amazing and you already thought about it. I was the one dumb to not get at the first place. Thanks. Keep the work please. I will delete my 1st suggestion.

**Comment by AlienXtream** [comment]
fun fact. because of the logic system you can actually make your OWN pin system. no way of doing card readers as there aren't any "items" yet. no real point to them though as any player can break any block but its fun to make stuff. not bad ideas though :)

**Comment by Garrett-C** [comment]
1. Improved MP is definitely a must. Will happen eventually, hopefully soon.
2. Don't really know much about this
3. I believe with query gates and monitors you can sort of do some of this but some more depth to it eventually would certainly be great
4. I do love the idea of hand or card readers at some stage
5. Hopefully some day

**Comment by ArthKriger** [comment]
Upgrade to my suggestion:

I've been trying almust everthing I could until now. I found that if  we connect a camera a turrent control to a camera, we can use-te to control almust all mechanics. I even found a way to open a dor, and after a few sec if no other input hapens will automatic close it. few things I found a bit anoing. I create a escape pod, that only work for 3 people at time. 2 thing got wrong. first, mybe is a problem of mine, but I can't put inclinated like in slide position. I found that sad xD. the other thing I make this robotick arm inside the pod, that will bring the Yuke to one off the 3 members, but I can't connected directly becouse off be in a mechanich part. Says something like "You can't direct connect a Yuke to a children..." So I need to put other Yuke under the ship hide. but becouse of that when I try to drive the Pod, I don't see nothing couse make see the camera view where the hiden yuke are. so I see only metal xD need to drive it with 3rd person view. or with a camera I will try it today. other thing I try to make, but not found a way maybe becouse, still not possible. drones. U try too remote controle one of my fighters ships. but doesn't work. sadly :(

**Comment by tsunamayo** [comment]
Thanks, yes improving those area are planned. Not sure about the AI, and we will see for O2 management! Cheers
