### ISSUE TITLE
decal/sticker overlap issues 

### ISSUE THREAD

**Issue by KINGrimson** [tsunamayo/Starship-EVO#3783]
### Short Description of the issue:
when using the decals/stickers the overlap isnt smooth, it leaves weird edges

### Steps to reproduce the issue:
place some stickers ontop of eachother 
...

### Environment
- Starship EVO version: 21w13b
- Graphics Card: RTX 2060

### Additional information:
![image](https://user-images.githubusercontent.com/74992043/119054718-71df7600-b9c8-11eb-8737-a6569ec4f078.png)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@KINGrimson Hi, could you please send me the blueprint? Thanks
