### ISSUE TITLE
[Suggestion] Glow tile improvements 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3787]
The glow blocks as they are currently are quite good, but they still do have a few problems 
1. the mirror isn't set up properly on triangles, this is more of a bug than anything but still
2. It would be nice to be able to paint the backs of the glow tiles, especially if both sides are meant to be seen
3. the edges of the tiles have a slight bevel leading to an annoying line affect that can be quite annoying  
![image](https://user-images.githubusercontent.com/56371294/119236279-5d47ce80-baeb-11eb-9dd4-e96f72c33596.png)

**Comment by BigBadKangaroo** [comment]
I'd love to see these changes!

**Comment by Servomotor** [comment]
The beveled edges does not bother me that much, but it does seem like in practical use removing the beveled edge would be more beneficial in the majority of builds.

**Comment by tsunamayo** [comment]
Corner symmetry issue fixed. I cant have secondary paint anymore though. Also I still kinda wants to keep the darker side for now. Cheers
