### ISSUE TITLE
Suggestion (Eject system) 

### ISSUE THREAD

**Issue by ArthKriger** [tsunamayo/Starship-EVO#3789]
I have done almost all my Escaping pods Hangar, not sure if I will keep it that way, still not good as I wish. But, I really love be able to eject the podship like if Emergency was happening. So if you could think about it please do. Something to ejecte our escaping pods from our Mother ship.

**Comment by tsunamayo** [comment]
@ArthKriger Hi, I see. Have you tried to use a gravity field? I think it should works!
