### ISSUE TITLE
[SUGGESTION/BUG] quarter disc decal is not the "same" size as disc decal 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3790]
### Short Description of the issue:
The quarter disc decal is slightly larger than the disc decal making my decal work a little more difficult than it needs to be 

### Additional information:

https://user-images.githubusercontent.com/56371294/119281889-548af180-bbec-11eb-98fe-cde0067eae05.mp4

**Comment by Kaiser-Indrasil** [comment]
I've liked it for that very reason but since now we can not only stretch, but also scale decals, it would seem reasonable for the circle decal to grow to be the same size as the quarter circle.

**Comment by ProPeach** [comment]
I actually quite like the fact that the circle is slightly smaller, as it means you can easily create circles with different coloured trim at all different scales, especially small ones. You can scale decals for sure now, but you still wouldn't be able to get that fine a difference in diameter at small scales, or large scales as with the smallest scale decal you can only stretch them to 2m

**Comment by KINGrimson** [comment]
i agree with propeach, for smaller scales that the circle is smallers is bette

**Comment by Servomotor** [comment]
I am with peach. I like how you can stack them for the fine outline.

**Comment by tsunamayo** [comment]
The people have spoken.
