### ISSUE TITLE
[BUG] Newest update does not allow some builds to be spawned

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Starship-EVO#3791]
Most recent update does not allow certain builds that I had saved in the previous update to be spawned in

EDIT:  My apologies for the lack of info, it was a long day. 
Graphics: GTX 1080TI

-This is in reference to the NoVox branch, update 21w07a physics improvement,  as testing and reporting any bugs from any other branch would be useless 

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/6549341/output_log.txt)

BP's can be found here
https://github.com/tsunamayo/Starship-EVO/issues/3784#issuecomment-846500147

**Comment by CurioInventorium** [comment]
Which update are you referring too? The main early access version, the experimental branch or the No Vox branch?

It's much appreciated that you've taken the time to log an issue, but it doesn't help anyone when you don't supply the requested information asked for in the issue template.
Most importantly;
-The version number you're playing the game at.
-Attaching the output log file
-Attaching zipped up versions of the ship blueprints that you can't spawn in.

**Comment by tsunamayo** [comment]
@ExodistSKY1 Hi, I can load all your ship, so not sure what the issue is. It seems that the log file is not from the novox update. Thanks

**Comment by ExodistSKY1** [comment]
Thank you for the response, it seems Steam has removed the novox beta's tab completely and reverted my game to the original download. I will edit once I fix and retry
