### ISSUE TITLE
Death without respawn point (Medical bay) causes eternal loading screen SOFTLOCK.

### ISSUE THREAD

**Issue by EmperorOfJustice** [tsunamayo/Starship-EVO#3792]
### Short Description of the issue:

_Upon dying without a respawn point such as the medical bay, The game enters an Eternal loading screen. NOTE: The game is not frozen as you can hear sounds, and move the cursor, however a forced shut down of the game is needed to continue playing. Upon reload. The game will spawn you in a completely different system from where you died._

### Steps to reproduce the issue:

_1. Start the game in a new world, 
2. Remove all respawn points by un-spawning the tutorial base and ships. 
3. Kill yourself. (Easy way is through spawning a spaceship computer and press the respawn button.)
4. Now you are in an eternal loading screen. 
5. Restart the game, respawn your character on the same save.
6. Figure out where you are._

### Environment
- Starship EVO version: early-access 21w07a
- Graphics Card: MSI GTX 1080

### Additional information:
![Starship Evo Screenshot 2021 05 30 - 14 57 10 77](https://user-images.githubusercontent.com/85064673/120105403-02505000-c159-11eb-889d-fcdfd8e05063.png)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6566243/Player.log)

**Comment by tsunamayo** [comment]
Hi, this should be fixed in recent update. Thanks

**Comment by Kaiser-Indrasil** [comment]
Yup, I can confirm it's fixed.
Thanks a lot, Tsuna!
