### ISSUE TITLE
[Bug] Newest Novox build doesn't allow saving of some blueprints. 

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Starship-EVO#3793]
### Short Description of the issue:

So I have been doing some work on one of my larger builds in novox and I went to save it. 

What happened though was the ship became invisible and my player character lost the ability to move at all. The game was still clearly not frozen as I could access the codex, the menu, and the visual effects on the build tool were still playing. 

I am unsure if this is a bug where the game is just being unable to save the ship or if it's an issue where saving is just taking a long time. 

### Steps to reproduce the issue:

Load up the supplied world.
Select the Venator.
Try to export the blueprint.

### Environment
- Starship EVO version: 21w20a
- Graphics Card: RTX 3070

### Additional information:
Here is the player log and the world.
[Player.zip](https://github.com/tsunamayo/Starship-EVO/files/6566335/Player.zip)
[Era of no vox.zip](https://github.com/tsunamayo/Starship-EVO/files/6566345/Era.of.no.vox.zip)

**Comment by tsunamayo** [comment]
@Garrett-C thanks for booking that one, issue is now fixed. It was linked to the massive number of brick this ship had! (and what a ship!
