### ISSUE TITLE
Messy textures glitching throughout ship 

### ISSUE THREAD

**Issue by Zodster** [tsunamayo/Starship-EVO#3794]
Huge textures started appearing throughout and across my ship, i respawned it and they wouldnt go away.
and the Ship menu pulled up with tab still decreases my fps so much that i still cant save anything i work on.
![image](https://user-images.githubusercontent.com/70779090/120110076-1b123300-c164-11eb-98bb-b228c7505a56.png)
World zip file:
[buruh.zip](https://github.com/tsunamayo/Starship-EVO/files/6566430/buruh.zip)

**Comment by tsunamayo** [comment]
@Zodster Hi, could you please send me the player.log? I cant reproduce the issue.
The FPS issue in Codex was fixed.
What did you do when this happened, also can you reproduce all the time? 
Thanks
