### ISSUE TITLE
[Bug] Inter-entity collision checks

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3798]
Version: 21w21a

Soooo, this bug has been around for a long time, with the new physics mechanics aplifying it a little.
That's not to diss on the new physics system though, not at all!
Just wanna point you in the directions where the code at fault might possibly be hiding.

Anyway, up to this point I've been building in Legacy branch but ever since you introduced the Scale Tech, I just... stopped.
I couldn't live (Drama Queen Skill: 100) knowing that I'm missing out on the awesome 1/8m blocks, which would let me pull off so much more detail than 1/4m bricks on the Legacy branch.

I would happily start building on the Experimental branch - and despite my whining, I probably will 😉 - but

![Hades](https://user-images.githubusercontent.com/63756057/120184328-c1177900-c208-11eb-8874-15c34740b85a.jpg)

The inter-entity collision checks getting more and more ridiculous:

![Starship_EVO_wxLxHAitsu](https://user-images.githubusercontent.com/63756057/120184740-3b47fd80-c209-11eb-86f3-f48a92aec9b6.png)

Haha clipping go BRRRRR:

![Starship_EVO_nOtT4MyZ30](https://user-images.githubusercontent.com/63756057/120184755-3f741b00-c209-11eb-82c6-c96ad7b8cd45.jpg)

I'm pretty sure I should be able to build here 😏 :

![Starship_EVO_ADf7AvSQxJ](https://user-images.githubusercontent.com/63756057/120184761-413dde80-c209-11eb-9780-9bc60cfcde84.jpg)

I've left you [a world file](https://github.com/tsunamayo/Starship-EVO/files/6569865/Experimental.zip) so that you can playtest it yourself.
Here's the 2 areas you can check first:

![image](https://user-images.githubusercontent.com/63756057/120185478-2ae45280-c20a-11eb-82a5-2d126fc4de63.png)

**Comment by ExodistSKY1** [comment]
The checks are very weird as stated above, you can place where you should not be able to but not able to place where there is no visible collisions

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Hi, I had a quick look at it and it looks like the old wedge (or other non-cube check) + children entity combo just like before (still hard to fix, sorry). If there some culling authorized could you point me to it? thx

**Comment by Kaiser-Indrasil** [comment]
I didn't change anything in the Culling section if that's what you mean. It's all vanilla.

![image](https://user-images.githubusercontent.com/63756057/120253091-615bb500-c27e-11eb-98df-51fe8b9e2e0b.png)

**Comment by Kaiser-Indrasil** [comment]
Yeah, I built a child entity entirely in the Exp branch and it seems like collision boxes on the new blocks are very tight indeed.

![image](https://user-images.githubusercontent.com/63756057/120254871-b39ed500-c282-11eb-81c6-33e5e9d965d8.png)

Sometimes, they are a bit too generous though...

![image](https://user-images.githubusercontent.com/63756057/120255022-f95b9d80-c282-11eb-8290-83cf3350799d.png)

**Comment by Kaiser-Indrasil** [comment]
It shouldn't be happening, yet it does.
Here's the [world file](https://github.com/tsunamayo/Starship-EVO/files/6586990/Experimental.zip) for you to check out.

![image](https://user-images.githubusercontent.com/63756057/120540914-21611300-c3e1-11eb-8143-0a5d82136248.png)

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo Sometimes it works, sometimes it doesn't.
It seems to depends on the angle at which you look at it, of all things.

![image](https://user-images.githubusercontent.com/63756057/120541666-0fcc3b00-c3e2-11eb-9ca1-d93744883a79.png)
![image](https://user-images.githubusercontent.com/63756057/120541688-15c21c00-c3e2-11eb-99e8-9b22b7d56740.png)
![image](https://user-images.githubusercontent.com/63756057/120541710-21adde00-c3e2-11eb-8c0a-87df9c504c7e.png)
![image](https://user-images.githubusercontent.com/63756057/120541739-2b374600-c3e2-11eb-93c6-bc22643741df.png)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil this is a case where you clip inside the wedge bounds of another entity, which is not supported in the current check...

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil okay nvm I had a look at my code as the case shown was actually supposed to work (the one who dont is a trickier hopefully rarer one). I spotted an error, and the case in question is now fixed, so it should be better. Fix for 21w21b. Thanks, sorry for the mishap...

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo Don't worry, I've devised some... unusual bypasses for that issue 😉 And they don't use clipping!
They involve building from different angles (already mentioned), but also different starting points from which to stretch the block, moving away from the block and twitching the cursor all over the place while stretching the block until it doesn't detect a collision conflict 😄 

I'm very hopeful it's gonna be better in the 21b indeed! Very excited for that patch since you managed to fix so many bugs!
