### ISSUE TITLE
Copy/Paste is always offset by 1m

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#3800]
### Short Description of the issue:
When selecting an area and going to paste it, it is always offset by 1m.

In my case here I selected a 4m scaled block, copied it and am attempting to place it on top but it is offset by 1m and moves in 4m increments.

On the actual build itself where I noticed this issue I selected a much larger area to paste and had this same issue. Peach mentioned that it selects the smallest block within the selection to base how it moves. I had a few 1m blocks in the selection but it still moved by 4m
...

### Environment
- Starship EVO version: 21w21a
- Graphics Card: GTX 970

### Additional information:
![20210531123608_1](https://user-images.githubusercontent.com/32974671/120226657-3dac5680-c20d-11eb-839a-10e9a1da2a61.jpg)
![20210531123727_1](https://user-images.githubusercontent.com/32974671/120226660-3edd8380-c20d-11eb-91d2-742581597bcd.jpg)

**Comment by BruceLeedleLeedleLeedleLee** [comment]
I noticed it uses the largest block as its grid, and it seems here that your block that you want to build on is already offgrid, probably due to being placed on the spawner block

**Comment by BruceLeedleLeedleLeedleLee** [comment]
so if i build a corridor module for example and the largest block is a 1m itll always snap to the 1m grid

**Comment by tsunamayo** [comment]
Yes it looks at the largest grid size inside your selection. But you will be able  to tweak it there after in the upcoming build menu.
Not sure to understand the test case though. What do you mean it is offset by 1m? If you could send me a screenshot of your initial template and the pasted one near to hit so I can see how it placed. Thanks

**Comment by Xerma** [comment]
Here is the placement for a 4m block
![20210602002407_1](https://user-images.githubusercontent.com/32974671/120428301-08048c00-c339-11eb-9076-2cfcfa100a8f.jpg)

And in these 2 pictures I've copied that first 4m block and would like to place it on that same grid the 4m block is on but it doesn't line up properly (This is just an example, I don't actually want to paste 4m blocks lol)
![20210602002416_1](https://user-images.githubusercontent.com/32974671/120428453-4732dd00-c339-11eb-8325-e8d198346101.jpg)
![20210602002419_1](https://user-images.githubusercontent.com/32974671/120428456-47cb7380-c339-11eb-996b-afc8f6724720.jpg)

**Comment by tsunamayo** [comment]
@Xerma I see, it is because it has an offset. I will try to replicate the grid lock setting with copy / paste. I keep you posted!

**Comment by ProPeach** [comment]
Hey @tsunamayo! Do you have have any more info on this? I still see it often causing problems for players in experimental

**Comment by Dwarf-LordPangolin** [comment]
I have encountered this bug as well; in my case it is offset by 1/8m.

![20210704140634_1](https://user-images.githubusercontent.com/33041786/124396772-3c20f300-dcd1-11eb-9ca0-9ccaa65d68f6.jpg)

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Is the underlying surface built at an offset? Thanks
