### ISSUE TITLE
No world ring

### ISSUE THREAD

**Issue by quillblabe** [tsunamayo/Starship-EVO#3801]
### Short Description of the issue:

...when i open the game  to continue building all object are floating in space. the ring world a disapaered

### Steps to reproduce the issue:
after pressing play i get the tile screen then go into the game and there is no ring world
...

### Environment
- Starship EVO version:  app id 711980   build id 6268529  updated Feb 21, 2021
- Graphics Card: NVIDIA GeForce GTX1050 Ti
- 
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6572073/Player.log)q22222222222222

![no ring world](https://user-images.githubusercontent.com/79616854/120238600-9aad1880-c2b0-11eb-84bb-6f64659e9627.jpg)

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by Kaiser-Indrasil** [comment]
Ye, Tsuna moves the ring occasionally.
Backup your projects and create new world.

**Comment by tsunamayo** [comment]
@quillblabe how old was your save? Thanks
