### ISSUE TITLE
[Bug] Keybinding and block rotation keys

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3802]
Version: 21w21a

Rotate Left and Rotate Right both rotate the block counter-clockwise.
Plus, I can't map key combinations anymore, like Shift+R.

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil I dont think we where able to map combination aren't we? It was on my to-do.

**Comment by Kaiser-Indrasil** [comment]
Oh I'm... pretty sure we were able to rotate blocks clockwise using Shift-R?
Not sure if it was the default combo or did I remap it _somehow_.

**Comment by tsunamayo** [comment]
yeah it was the default combo, it might be broken I guess.

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Issue fixed for 21w21b. Thanks!
