### ISSUE TITLE
[Balancing] [Bug] Weapon modifier scaling and weak fighter meta

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3804]
Version: 21w21a

### First off, the bug.
The Cooling Barrel has a -22.5% heat generation modifier and so, on the 1m Laser it provides 22.5% better heat dissipation.
This is not the case for all other scales of Lasers.
For 1/2m it only provides -5.6% heat generation modifier.
For 1/4m it goes down to -1.41%.
And for 1/8m it reaches a negligible -0.35%.

By this time I think we can safely assume that there is an unnecessary factor of 1/4 for each subsequently smaller scale of Lasers.
I was curious and checked for a 2m Laser as well, and it seems the factor of 4 is still there
It doesn't even generate heat anymore. Instead, it DISSIPATES it 😆 

https://user-images.githubusercontent.com/63756057/120318926-59306380-c2d8-11eb-943c-07f05262c25c.mp4

Literally just switch, starter block, 4 reactors, 4 lasers, and 4 cooling barrels, almost all in 2m scale.

There are more weapons systems hit by this factor of 4:
### Basically, ALL the Weapon Addons suffer from this issue. Every modifier on them is either 4 times smaller or bigger than it's supposed to be at any scale other than 1m.
All the other barrels are fine though.
___

**BTW, Charge addon has much weaker DPS than its counterparts. I think in order to bring it in line, you should double both of its damage modifiers, and give it the 200h/s modifier all the other addons have.**
___
### The balancing issue

Basically, TTK (Time To Kill) for 1/4m weapons rose **massively** since the Neovox update on Experimental.
That's because the damage of 1/4m weapons dropped 4 times compared to pre-Neovox.

On every scale-up the following key attributes are modified like this:
- Damage (both Heat and Hull): 4x
- Power Drain (both idle and on charge): 4x
- Heat Generation (both idle and on cooldown): 2x

Since we get twice as much damage for each unit of heat generated at every up-scale, it's only logical to always get the biggest caliber guns you can, instead of spamming smaller ones.
That said, the current meta makes fighters really weak because the TTK is so long for their (formerly brick-sized) weapons.

- Solution A: Having the 1m weapon as the baseline, lower the factor of each up-scale for weapon damage, heat production, and power requirement. Instead of 4x damage, 2x heat, and 4x power, make it 2x damage, 2x heat, and 2x power.
Pros: more in-line with the pre-Neovox meta.
Cons: TTK for big ship VS big ship battle might be very long

- Solution B: Leave the 4x scale damage factor as is, but increase damage 4 times for every weapon scale instead.
Pros: <1m weapons more viable and in-line with the pre-Neovox meta.
Cons: Bigger ships with bigger weapons might get MASSIVELY OP.

*Might.* Not necessarily will, cos a battle of 2 big and heavily-armed ships on the pre-Neovox branches can last very long already.
Suffice it to say, I'm in favour of the Solution B.

![image](https://user-images.githubusercontent.com/63756057/120344224-4f672a00-c2f1-11eb-9296-d950bcd07501.png)

**Comment by ProPeach** [comment]
Yeah... the addons effect scaling is a bit funny lol, a 4m diameter gun has a hull damage stat of 4.4k per shot, then with hull damage addons it's 76k 😄 

In terms of solution A vs B, I'd prefer B
My only issue with A is that it means that you can achieve more damage by stacking lots of small guns in an area rather than using larger guns. Currently, there's a nice linear relationship between damage of a gun and its footprint area which I think is a good thing.

The other option would be to reduce hull points of hull blocks, but that has a near identical effect

Of course, there are a tonne of other factors that will change how weapons handle like reload time, but the DPS of 1/4 weapons is simply so low that they're far too weak at the moment

**Comment by tsunamayo** [comment]
So there is two issue here. The first scaling issue is fixed. Then there is the meta, which will need a lot of tuning anyway. I will bump up the power of all weapons. For sure I cant do A, it will make small weapon way too op... So I will go B for now. Fix for 21w21b.
