### ISSUE TITLE
[Bug] Block stats like mass or HP not substracted after block deletion

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3805]
Version: 21w21a

I think I know why ships fly so sluggishly now.
1. Build a Starter Block, starting new ship
2. Place down a Ship Computer and note the mass
3. Add a massive block, like 4m one
4. And delete it
5. Check mass in the Ship Computer again.

![image](https://user-images.githubusercontent.com/63756057/120347085-df0dd800-c2f3-11eb-945b-8fa22a4f810f.png)

![image](https://user-images.githubusercontent.com/63756057/120347141-edf48a80-c2f3-11eb-8df1-a3f45c756fc8.png)

**Comment by ProPeach** [comment]
To add to this, mass is not subtracted from child entities when you remove blocks either. 

To test this, place a hinge, then place blocks on you are warned that you're close to its mass limit.
Then delete the blocks you placed, and place some more. The game will warn you that you are now over the mass limit, despite having fewer blocks on the hinge than before

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Thanks mate, issue fixed for 21w21b.
