### ISSUE TITLE
[Performance] FPS massively reduced when "inside" of a damage decal

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3807]
Version: 21w21a

I can spawn a 1km-long ship and still maintain 100 FPS.
Meanwhile, sitting inside a hole costs half of these FPS.

"What are your specs?"
Yes. 😎 

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6577477/Player.log)

![Starship_EVO_Md40JH6hcW](https://user-images.githubusercontent.com/63756057/120354594-78d88380-c2fa-11eb-9795-34a4553496ea.jpg)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil I cant reproduce this. Do you get this all the time? If yes can you send me your world with the position saved? Thanks

**Comment by Kaiser-Indrasil** [comment]
Sure, here you go:
[Experimental.zip](https://github.com/tsunamayo/Starship-EVO/files/6581379/Experimental.zip)

**Comment by tsunamayo** [comment]
Okay fixed for 21w38a. Cheers
