### ISSUE TITLE
[Bug] Incorrent collision beneath a hinge

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3808]
### Short Description of the issue:
No blocks can be placed underneath a hinge (on the hinges parent entity)
![image](https://user-images.githubusercontent.com/27857711/120355430-32cfef80-c2fb-11eb-8e41-9ae50a721f26.png)

### Steps to reproduce the issue:
- Place a hinge
- Remove the block beneath it
- Try and replace the block beneath it 

### Environment
- Starship EVO version: 21w21a
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
Issue fixed for 21w21b. Thanks!
