### ISSUE TITLE
[Bug] Stickers have an incorrect height value

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3809]
### Short Description of the issue:
By default, stickers below 1x scale (1/2, 1/4 etc) have a height dimension which makes their hitbox huge
![image](https://user-images.githubusercontent.com/27857711/120355803-86dad400-c2fb-11eb-97ac-5b60429721f2.png)

You can see here I'm looking past the sticker, but it is still selected due to the tall hitbox
![image](https://user-images.githubusercontent.com/27857711/120355883-9d812b00-c2fb-11eb-980d-1b59979d8b11.png)

### Steps to reproduce the issue:
- Place a sticker of 1/2 or smaller

### Environment
- Starship EVO version: 21w21a
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
Issue fixed for 21w21b. Thanks!
