### ISSUE TITLE
[Bug] Sticker placement ghost is incorrect on slopes

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3810]
### Short Description of the issue:
When placing stickers on slopes (wedge, tetra blocks) the placement ghost phases between layers
https://i.imgur.com/qXjQDmr.mp4

### Steps to reproduce the issue:
- Place a sticker on a tetra or wedge

### Environment
- Starship EVO version: 21w21a
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
@ProPeach Good catch, thanks for being on the ball! Fixed for 21w21b.
