### ISSUE TITLE
[Bug] Sprinting does not increase speed

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3811]
### Short Description of the issue:
Pretty simple one, holding shift to sprint does not increase speed either when running or flying

### Steps to reproduce the issue:
Try to sprint

### Environment
- Starship EVO version: 21w21a
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
Yes I have removed it, I think it was a bit useless and will clash with the offset tech (still not 100% convinced though)
