### ISSUE TITLE
[Bug] Can't place addons on systems when in Local Grid mode

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3812]
### Short Description of the issue:
When the G padlock is unlocked, you can't place any addons on any systems e.g. barrels/addons for lasers, or capacitors for reactors.
![image](https://user-images.githubusercontent.com/27857711/120357216-192fa780-c2fd-11eb-8fab-ca56aec432f4.png)

### Steps to reproduce the issue:
- Place a system
- Unlock grid snapping
- Try and place an addon on the system

### Environment
- Starship EVO version: 21w21a
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
@ProPeach I think I fixed that one yesterday without knowing it. Fix in 21w21b. Thanks!
