### ISSUE TITLE
[Bug] Collision check failure when stretching

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3813]
### Short Description of the issue:
When placing a block, it's possible to clip into blocks even on the same sub entity.

It seems like there's a problem when you stretch the placement ghost _larger_, but when you stretch it _smaller_ then the collisions update correctly.
https://i.imgur.com/6iIGPDC.mp4

### Steps to reproduce the issue:
Follow the steps in the video

### Environment
- Starship EVO version: 21w21a
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
@ProPeach I cant reproduce this one. Can you 100% of the time? Can you send me your world if yes? Thanks

**Comment by ProPeach** [comment]
Hi there o/
I produce this every time I try it, in every world and every blueprint 
Here's the world -
[ClipTest.zip](https://github.com/tsunamayo/Starship-EVO/files/6588109/ClipTest.zip)

And the log -
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6588110/Player.log)

**Comment by tsunamayo** [comment]
@ProPeach Okay that might be something I already fixed, lets see in next update. thx

**Comment by tsunamayo** [comment]
@ProPeach could you tell me if it still dont work in 21w21b? thx!

**Comment by ProPeach** [comment]
@tsunamayo seems to be fixed! Nice one :)

**Comment by tsunamayo** [comment]
okay cool to hear! Cheers
