### ISSUE TITLE
[Bug] Disparity between reach when placing and removingblocks

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3814]
### Short Description of the issue:
Seems that the player has a longer reach for placing blocks, but cannot remove them at the same distance

https://user-images.githubusercontent.com/27857711/120369361-0e7c0f00-c30b-11eb-932a-80d48a9afbbe.mp4
The long reach is very useful to have, so I hope that the removal reach gets increased rather than the placing distance decreased

### Steps to reproduce the issue:
Place a block at the furthest reach, then try to remove it

### Environment
- Starship EVO version: 21w21a
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
It was an issue with the build range which was 4x too high. I bumped the range from 12m to 16m. Too high and I think it gets confusing, you could delete stuff without really seeing them.
Fixed for 21w21b.
