### ISSUE TITLE
[Bug] Rail Extenders cannot be attached to themselves

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3816]
### Short Description of the issue:
When placing a rail, you can extend the length by placing an extender on the rail. You then cannon extend the rail any further, because you can't build an extender on top of another extender. 
Before novox, you could place as many extender addons as you like on a rail to get the desired length

### Steps to reproduce the issue:
- Place a rail
- Place a rail extender on it
- Try to place an extender on the extender

### Environment
- Starship EVO version: 21w21a
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
Issue fixed for 21w21b. Thanks!
