### ISSUE TITLE
Steam blueprints post-neovox bugged and will not update.

### ISSUE THREAD

**Issue by JackBobS** [tsunamayo/Starship-EVO#3817]
### Short Description of the issue:

Models and exports will not update post-neovox update when reuploading to the workshop.
...

### Steps to reproduce the issue:

Take a model or export made before the neovox update. Edit it. Try to reupload it to the workshop with its new additions. Spawn it again. Notice none of the changes took effect. 
...

### Environment

- Starship EVO version: 21w21a
- Graphics Card: Intel Core I7

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

[Incom T-65 X-Wing.zip](https://github.com/tsunamayo/Starship-EVO/files/6580993/Incom.T-65.X-Wing.zip)

**Comment by tsunamayo** [comment]
Issue fixed for 21w22a. Although the update might take a while to come up it seems. Thanks!
