### ISSUE TITLE
[Bug] Starter Blocks spawning with Hinge Heads

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3818]
Version: 21w21a

At one point, when I started spawning Starter Blocks, they came with Hinge Heads which I couldn't delete.

Here's the [Player.log](https://github.com/tsunamayo/Starship-EVO/files/6580999/Player.log).
And here's the [world file](https://github.com/tsunamayo/Starship-EVO/files/6581003/Experimental.zip).

They will probably disappear on the world loading though...

![Starship_EVO_75FBJ5NxxR](https://user-images.githubusercontent.com/63756057/120400765-76941a80-c336-11eb-848a-3a91267395bf.png)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Hi, did you unspawned some ship at one point? Thanks

**Comment by Kaiser-Indrasil** [comment]
Yeah, a few actually.

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Hi, do you still saw this recently? Thanks

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo Nope, all clear for now

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil okay I had made some change to this part so hopefully it is gone for good. Dont hesitate to ping me if you see that again. Thanks mate
