### ISSUE TITLE
[Bug] Custom colours disappear from the toolbar upon re-entering the world

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3819]
Version: 21w21a

I'm assuming they are meant to be staying on the toolbar even on the game restart?
But yeah, you can just make a custom colour on a new custom list,
move it to one of the toolbars,
and re-load the world.

![image](https://user-images.githubusercontent.com/63756057/120491430-2312e280-c3b1-11eb-8392-442f3cf430b7.png)

**Comment by ExodistSKY1** [comment]
To add to Indrasil's report this affects for ALL colors and not just custom

**Comment by tsunamayo** [comment]
Indeed, issue fixed for 21w21b. Actually all color are custom colors, you can remove / tweak the base set if you dont like them. Cheers
