### ISSUE TITLE
[Bug] Emissives not visible in the Codex block list

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3820]
Version: 21w21a

Most of the blocks listed in the Codex have their emissive light not visible.
However, if you hover over their icon, you can see on the preview to the right that they've got their emissive meshes alright.
Listing all of them here would be unnecessary since you can hopefully reproduce this issue and see them for yourself.
Let me know if you can't, I'll compile you a list.

![image](https://user-images.githubusercontent.com/63756057/120494482-c49b3380-c3b3-11eb-9f38-6cfb00a8dbf1.png)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Thanks for booking all those issues! Fixed for 21w21b.
