### ISSUE TITLE
[Bug] Sharp hue transitions in light-emitting blocks

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3821]
Version: 21w21a

I've been playing around with the AWESOME custom colours functionality, trying to find a perfect hue for my thrusters and engines.
Went for sort of an icy shade of blue but when I changed the red value by literally 1, the hue shifted massively, totally out of proportion to the change I did.

`<Color32>
        <r>194</r>
        <g>232</g>
        <b>242</b>
        <a>255</a>
      </Color32>`:

![image](https://user-images.githubusercontent.com/63756057/120526090-bb6c8f80-c3d0-11eb-9777-a3db4dc33d2b.png)

`<Color32>
        <r>193</r>
        <g>232</g>
        <b>242</b>
        <a>255</a>
      </Color32>`:

![image](https://user-images.githubusercontent.com/63756057/120526140-cb846f00-c3d0-11eb-85ad-23b2fa18a75f.png)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Issue fixed for 21w21b. Thanks!
