### ISSUE TITLE
[Suggestion] weight limits improvments

### ISSUE THREAD

**Issue by COMICLER** [tsunamayo/Starship-EVO#3822]
Since the new novox its almost impossible to use the bigger blocks on hinges due to weight limits so. I would suggest instead of a weight limit it gets replaced with a speed limit depending on the blocks size. for example at the largest size rotor the max speed is reduced by 50% but it would still allow you to lower it if you want. not only does this remove the annoying weight system it also makes them look and feel really big machinery

**Comment by tsunamayo** [comment]
Yes correct it is not yet implemented. I will work on it for the next patch.

**Comment by tsunamayo** [comment]
@COMICLER So now the weight limit adjust for grid size. Thanks

**Comment by cloudrambler** [comment]
@tsunamayo 

From a brief test it seems that the mechanism moving mass limits scales nicely with mechanism block size. No complaints there. Also thank you.

I have noticed however that with each size rotator block loaded to maximum (96-98%), the larger ones move more quickly than the smaller ones. It seems a little strange and counter-intuitive to the thematic expectations of sci-fi mechanisms. Is this deliberate?
