### ISSUE TITLE
[Bug] Local Grid lock icon does not animate

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3823]
Version: 21w21a

Switching between the Local and Static Grids does not change the look of the UI icon in the lower right corner:

https://user-images.githubusercontent.com/63756057/120544995-fd540080-c3e5-11eb-93d5-aeb3f4e7e158.mp4

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil I cant reproduce that one, can you 100%? Could you send me your world save? Thanks

**Comment by Kaiser-Indrasil** [comment]
Sure, here you go:
[Experimental.zip](https://github.com/tsunamayo/Starship-EVO/files/6588113/Experimental.zip)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Sorry mate which block where you using? I actually nuked the inventory loading to fix the paint issue, so I lost your item bar.

**Comment by tsunamayo** [comment]
Maybe your game was already bugged?

**Comment by Kaiser-Indrasil** [comment]
Maybe! It's been behaving itself since then though, so I don't know. 🤷

**Comment by tsunamayo** [comment]
Yeah I would say it was another issue that made your game bug. If it happens again send me the log! Thx
