### ISSUE TITLE
[Bug] Stickers have brighter hue in the ship preview

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3824]
Version: 21w21a

Luckily, it happens consistently.
Just place a block, a sticker, paint both in the same colour and check the ship preview in the Building Drone menu.

![image](https://user-images.githubusercontent.com/63756057/120575577-407b9700-c419-11eb-9982-7a4c9b7ff252.png)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Issue fixed for 21w22a. Thanks!
