### ISSUE TITLE
[BUG] Gravity only works sometimes 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3826]
### Short Description of the issue:
Gravity gens will only effect you if you are standing on the "floor" of the ship
...

### Steps to reproduce the issue:
place grav gens down on a surface and see if you can walk around, if you can see what happens when you jump 
...

### Environment
- Starship EVO version: 21w21b

### Additional information:

https://user-images.githubusercontent.com/56371294/120666046-1fc73780-c441-11eb-9776-f7c97a605da8.mp4

**Comment by tsunamayo** [comment]
This is a bug that was already booked, you are outside the bound of the ship, so gravity dont apply here. I will close this as we have the issue somewhere else. Cheers
