### ISSUE TITLE
[BUG] Grey colors do not color lights properly 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3828]
### Short Description of the issue:
when painting a light with the grey and slightly off white colors it turns the light blue and red respectively

 
...

### Steps to reproduce the issue:
paint a light with the slightly grey white and the grey colors 
...

### Environment
- Starship EVO version: 21w21b

### Additional information:

https://user-images.githubusercontent.com/56371294/120670655-7b93bf80-c445-11eb-95b5-e9512da6b9fa.mp4

**Comment by Kaiser-Indrasil** [comment]
Can confirm it's also the case for pre-existing white lights (default white paint):

![image](https://user-images.githubusercontent.com/63756057/120673830-70638280-c48b-11eb-9110-27a5e067ce9d.png)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil yep it is because of the fix of the other color bug you booked... I will see what I can do... The default behaviour is to cramp up the saturation to get more pop.

**Comment by tsunamayo** [comment]
It should be better in 21w22a. I will soon give a toggle so you get the exact color if you need it.
