### ISSUE TITLE
Copy paste grid misalign

### ISSUE THREAD

**Issue by Zerefette** [tsunamayo/Starship-EVO#3832]
### Short Description of the issue:

Copy Paste pasting phase misaligns stuff.

### Steps to reproduce the issue:

Copy and paste, does not always work.
![iKaf6Fv - Imgur](https://user-images.githubusercontent.com/68450476/120731643-51450f00-c4e4-11eb-9f24-6d7ff7ceea84.png)
![lngHKqG - Imgur](https://user-images.githubusercontent.com/68450476/120731678-6326b200-c4e4-11eb-8f31-ab6957b9cf55.png)
![w1uaSld - Imgur](https://user-images.githubusercontent.com/68450476/120731683-64f07580-c4e4-11eb-8ade-543226759b20.png)

**Comment by Kaiser-Indrasil** [comment]
@Zerefette That might be happening because you're trying to place a bigger-sized grid blocks on a smaller-sized grid ones. Local grid offset doesn't work in such a case. But here the grid's aligned I see, to it's certainly not the issue.

However, it bight be happening because the copied group's inherent grid (which also gets copied) is misaligned with the grid you're trying to paste it onto.

If that's not the case either, you can upload the world file here, that will certainly help.

**Comment by tsunamayo** [comment]
@Zerefette Yes Kaiser is right, could you send me the blueprint highlighting the area you want to copy? Thanks

**Comment by Zerefette** [comment]
Highlited sample in red

[grid misalign.zip](https://github.com/tsunamayo/Starship-EVO/files/6608460/grid.misalign.zip)

**Comment by tsunamayo** [comment]
@Zerefette Thanks for the bp, I was able to copy-paste without offset, so I am not sure what the issue is...
![Uploading SNAG-0461.png…]()

**Comment by Zerefette** [comment]
I can't.
![mis](https://user-images.githubusercontent.com/68450476/121176397-76c37700-c85c-11eb-8591-7eb87943a24e.png)
![ali](https://user-images.githubusercontent.com/68450476/121176407-77f4a400-c85c-11eb-9f38-062f5b96d9fd.png)
![gn](https://user-images.githubusercontent.com/68450476/121176412-788d3a80-c85c-11eb-98e1-d8edfffee7d4.png)

**Comment by tsunamayo** [comment]
@Zerefette If you can could you record a video so I can reproduce that issue? It is weird I had no issue with that. Did it worked for other segment? Thanks

**Comment by Zerefette** [comment]
https://youtu.be/WoQdC3Lu040
Is this satisfying?

**Comment by tsunamayo** [comment]
@Zerefette Sorry I never answer to this. You need to copy from the bottom, not from the side. Otherwise you can adjust the offset to get the piece to fit correctly. Thanks
