### ISSUE TITLE
[Bug] Multitool tools not visible in the Item Stand

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3833]
Version: 21w21b

All the other items are visible, just not the Multitool tools.
The Item Stand casts the light VFX and you can pick up the tool off of it though.

![image](https://user-images.githubusercontent.com/63756057/120809005-8e8bba00-c541-11eb-9ada-8339ca1dc5c8.png)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Fixed for 21w22a. Thanks!
