### ISSUE TITLE
[BUG] Blueprint that corrupts every world its spawned on

### ISSUE THREAD

**Issue by zorozeenee** [tsunamayo/Starship-EVO#3834]
### Short Description of the issue:

I was working on a ground base, i was copying and pasting some small sections with lights on them, the base had a large amount of lights on it already (idk if this is related)

After copying the last section i became unable to interact with the base, i then restarted my game and was unable to load in the world, i created a new world then spawned in the blueprint was unable to interact with it then restarted made a new world and the same result

### Steps to reproduce the issue:

Open new world
Spawn in the Fortress Prototype blueprint, attempt to build blocks on it, restart game, attempt to load in to the previous world

### Environment
- Starship EVO version: Early access 21w07a
- Graphics Card: Nvidia GTX 1060 super

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Blueprint is attached below
[Fortress Blueprint.zip](https://github.com/tsunamayo/Starship-EVO/files/6598885/Fortress.Blueprint.zip)

**Comment by tsunamayo** [comment]
@zorozeenee Issue fixed for 21w21c. Thanks

**Comment by zorozeenee** [comment]
So next build the blueprint should work?
