### ISSUE TITLE
[Bug] Codex Repair function does not repair all the damage

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3835]
Version: 21w21b

It does repair **some** damage though. Just not all.
It's not only about visuals - it actually doesn't heal all the HP. Roughly only half of it.
I've tested it without any world reloading and the results are consistent across multiple blueprints.

The Repair tool can repair some damage but not all, regardless of the angle, distance, and amount I use.

![Starship_EVO_YuiAutXkMm](https://user-images.githubusercontent.com/63756057/120816984-2e991180-c549-11eb-9627-829ec0af5901.png)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Indeed, it was not working on children entity. Fixed for 21w22a. Cheers
