### ISSUE TITLE
[BUG] Strange lighting shades

### ISSUE THREAD

**Issue by zorozeenee** [tsunamayo/Starship-EVO#3837]
### Short Description of the issue:

Colors in the experimental version of the game are wrong, in the regular build they are correct
The pictures i linked show the difference in the experimental version red lights look almost like white pinkish white in the regular build they show to be truly red. 

![tie](https://user-images.githubusercontent.com/46616297/120883269-e4904a00-c5a1-11eb-9ba2-617266528573.jpg)
![tie - Copy (2)](https://user-images.githubusercontent.com/46616297/120883271-e528e080-c5a1-11eb-89d6-60cf20ead170.jpg)

### Environment
- Starship EVO version: 
- Graphics Card: gtx 1060 super

### Additional information:

This report may be slightly subjective but i think the colors need to be fixed

**Comment by Kaiser-Indrasil** [comment]
It's a known bug and has been already reported in #3828
We try to keep the GitHub organised, so please avoid posting duplicates. Unless last report about a particular bug was more than a few patches ago and remained unaddressed, that is 😏

**Comment by tsunamayo** [comment]
@zorozeenee Could you send me the blueprint? Thanks

**Comment by tsunamayo** [comment]
Situation will be better for next update 21w22a. Thanks
