### ISSUE TITLE
Experimental 21w21c - Lights and the volumetric sensors

### ISSUE THREAD

**Issue by zalexville** [tsunamayo/Starship-EVO#3840]
### Short Description of the issue:

...

### Steps to reproduce the issue:

...Spawned an old blueprint (Ulaan-class Escort, last updated in February) and all the angled and flat lighting fixtures were projecting red. They are all lights I did not change their basic color from the grey I was using to build the ship. The round lights don't seem to be affected by the update. 

...The volumetric sensors seems to have slow problems. It takes a minute or two (no exaggeration) to detect a player and then they dont even cloe the door, it just gets stuck in the "on" position. 

### Environment
- Starship EVO version: 21w21c
- Graphics Card: Nvidia GTX 1050ti

### Additional information:

...Created a new world and respawned the blueprint in to see if these issues persist, they do. It does not seem to care whether its an old world converted into the 21w21c updated or not. 

_(Screenshots, Videos, Error logs, Related issues)_

![20210606114924_1](https://user-images.githubusercontent.com/65626266/120930930-6aed7e80-c6bd-11eb-9c4e-04f08e8d9bb4.jpg)
![20210606115007_1](https://user-images.githubusercontent.com/65626266/120930931-6aed7e80-c6bd-11eb-990a-f746a447b369.jpg)
![20210606115016_1](https://user-images.githubusercontent.com/65626266/120930932-6b861500-c6bd-11eb-8c61-9290324d0475.jpg)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6604441/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.
[Ulaan-Class Escort (2).zip](https://github.com/tsunamayo/Starship-EVO/files/6604445/Ulaan-Class.Escort.2.zip)

**Comment by Kaiser-Indrasil** [comment]
In terms of lights - we know.
It's been reported already here #3837, here #3828, and here #3825.

When it comes to sensors - yeah, we still need them fixed because they straight up don't turn off and have trouble turning on.

**Comment by zalexville** [comment]
> 
> 
> In terms of lights - we know.
> It's been reported already here #3837, here #3828, and here #3825.
> 
> When it comes to sensors - yeah, we still need them fixed because they straight up don't turn off and have trouble turning on.

I
