### ISSUE TITLE
All ships spawned via blueprint spawn with AI

### ISSUE THREAD

**Issue by Vasillo** [tsunamayo/Starship-EVO#3841]
### Short Description of the issue:
All vehicles spawned via blueprint menu spawn with AI regardless of AI mode selection
...

### Steps to reproduce the issue:
1. Choose vehicle from blueprint selector
2. Spawn
3. AI activates shortly and flies away with lightcruise
...

### Environment
- Starship EVO version: Expiremental 21w21c
- Graphics Card: GTX 1060 6gb

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6605800/Player.log)

**Comment by Vasillo** [comment]
As a comment, apparently, this is common, I believe the AI mode option should be changed from "none" to "passive" for clarity towards newer players

**Comment by tsunamayo** [comment]
I see, yes this is a spawn AI test feature for now - I make that clear.
