### ISSUE TITLE
[BUG / LACK OF FEATURE] Ground structures automatic ai turrets cannot fire

### ISSUE THREAD

**Issue by zorozeenee** [tsunamayo/Starship-EVO#3842]
### Short Description of the issue:

Automatic turrets (when the turret computer is set to auto fire and auto targetting) require a ship computer which is activated by a player or ai in order to fire. Therefore since ground structures cannot be turned on like a ship is the automatic turrets will not fire or track enemies.

### Steps to reproduce the issue:

Build a ground structure with automatic turret
Make sure the turret has power to fire
Test the turret firing manually to check that it can rotate properly
Spawn in a pirate within its range

### Environment
- Starship EVO version: 21w07a
- Graphics Card: GTX 1060 super

### Additional information:

Potential solutions:

-Ground structure computer
-Keep automatic turrets always on

**Comment by CurioInventorium** [comment]
This is something that has always frustrated me, and I think has been lost along the way with other developments taking priority 😞

**Comment by zorozeenee** [comment]
> This is something that has always frustrated me, and I think has been lost along the way with other developments taking priority 😞

rip

**Comment by tsunamayo** [comment]
Yes it is still wip, but as I am doing a push on station it might come soon now. Thx

**Comment by tsunamayo** [comment]
@zorozeenee @CurioInventorium Actually it is done for 21w22b. You will have to toggle the feature in the Station Computer first. Thanks

**Comment by zorozeenee** [comment]
ARe ground structures considered stations?
