### ISSUE TITLE
[BUG] Slanted block color change 

### ISSUE THREAD

**Issue by Drillz007** [tsunamayo/Starship-EVO#3843]
### Short Description of the issue:

... block changes color after deleting different blocks 

### Steps to reproduce the issue:

...deleting slanted blocks close to eachother

![image](https://user-images.githubusercontent.com/63330810/121107525-b55e2080-c7cd-11eb-98ea-ef25d96d93bc.png)

![image](https://user-images.githubusercontent.com/63330810/121107602-d45cb280-c7cd-11eb-950e-410232d2c1a6.png)

![image](https://user-images.githubusercontent.com/63330810/121107647-e63e5580-c7cd-11eb-8263-d626a6bf1850.png)

**Comment by tsunamayo** [comment]
@Drillz007 What version do you use? Thanks

**Comment by Drillz007** [comment]
most current version of the game 21w07a

**Comment by tsunamayo** [comment]
@Drillz007 It is fixed in experimental already as Voxel paint were removed. Thanks
