### ISSUE TITLE
[BUG] Collision issues on the front of my ship 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3845]
### Short Description of the issue:
My ship does not collide with the ground or other ships, it seems only the back landing gears have collisions 
...

### Steps to reproduce the issue:
spawn in included BP, fly it into the ground 
[New Entity.zip](https://github.com/tsunamayo/Starship-EVO/files/6620435/New.Entity.zip)

...

### Environment
- Starship EVO version: 21w22a

### Additional information:

https://user-images.githubusercontent.com/56371294/121276637-d8e3a280-c883-11eb-8cbe-105716df95f9.mp4

**Comment by tsunamayo** [comment]
@TIKIRobo Hi, I cant reproduce the issue - it is all fine on my side. Btw I like your ships, do you put them on the workshop? Thanks

**Comment by TIKIRobo** [comment]
@tsunamayo sorry for responding so late but it fixed itself after a restart 
here's the link to that ship but finished 
https://steamcommunity.com/sharedfiles/filedetails/?id=2514320000
