### ISSUE TITLE
[Bug] I'm sorry... Yes, it's about light colours again

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3846]
Version: 21w22a

You're probably sick of me already for this 🤣 
Nevertheless, I can't help but notice the vast difference between the beautiful capabilities of custom-coloured blocks and very limited palette of custom light colours.

Here you can see a way to make a gradient. The differences are subtle but as they progress, they become to get noticeable.
Such variety is not at all possible with the colours of light emissive blocks.
There's just white, white... more white... and then a VERY sharp transition to blueish violet.
The lights were set to the same colours as the blocks they rest upon.
The gradient progresses towards blue like this:

![image](https://user-images.githubusercontent.com/63756057/121277665-00a92980-c8c9-11eb-9a23-591c1ca13a8d.png)

I'm trying to pull off this very pale shade of blue like this and I just can't because there's not nearly enough light colour variety:

![Starship_EVO_UjnfDIPY2l](https://user-images.githubusercontent.com/63756057/121278126-e3c12600-c8c9-11eb-90f4-b74cfe52f819.png)

(Oh god, it was actually perfect and I complained about it... just... why.)
(Maybe I just want good and subtle light colour transitions...)

**Comment by tsunamayo** [comment]
So you will have to wait for the Toggle Glow paint tweak inside the upcoming build menu. You will always be able to pinpoint a discontinuity point with the current formula otherwise. thx

**Comment by Kaiser-Indrasil** [comment]
Gotcha. Thanks for your amazing work!

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo Gotcha. Thanks for your amazing work!
