### ISSUE TITLE
Window Tile object is mirrored offset slightly

### ISSUE THREAD

**Issue by CurioInventorium** [tsunamayo/Starship-EVO#3847]
### Short Description of the issue:
The window tile block (and possibly others) is mirrored at an offset when placed. It appears to be offset along a particular direction depending on which way it is rotated when placed.
...

### Steps to reproduce the issue:
Set a mirror line down and then place a window tile down on one side of it. You'll see that it's 'mirror' is shifted along slightly.
I haven't checked its behaviour with other mirror directions applied.
...

### Environment
- Starship EVO version: 21w22a
- Graphics Card: Geforce RTX2060

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![20210608210348_1](https://user-images.githubusercontent.com/51359034/121418863-474b6200-c963-11eb-9cc0-012d91e6ba7b.jpg)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6626503/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@CurioInventorium Fixed for 21w37a. Thanks
