### ISSUE TITLE
The system star light is reflected on glass despite object blocking it.

### ISSUE THREAD

**Issue by CurioInventorium** [tsunamayo/Starship-EVO#3848]
### Short Description of the issue:
The glass used in the control area of my ship shows the system star's glare reflected on it, even though I'm in a room with a wall behind me and no windows to let the light through.
...

### Steps to reproduce the issue:
Have a room so there's a wall behind you and a large glass panel in front. Then orientate the room so that wall is in-between the star and the glass panel. Stand in the room and face the glass panel and you'll see the glare of the star reflected in it.
...

### Environment
- Starship EVO version: 22w21a
- Graphics Card: Geforce RTX2060

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
Here's my character look out the front of the ship, with the star behind
![20210608205224_1](https://user-images.githubusercontent.com/51359034/121420328-d73ddb80-c964-11eb-9eee-93689d8d840b.jpg)
And here's what is behind my character in the room. There should be no way for the stars glare to reach the glass.
![20210608205238_1](https://user-images.githubusercontent.com/51359034/121420426-f8063100-c964-11eb-90ec-3fe1e7956625.jpg)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
The player log is from a later session, but is added anyway.
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6626529/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@CurioInventorium unfortunately it is because of how shadow works in Unity. One day I might be able to improve that, but it is kinda low priority. Btw it work like that for plenty of games... Cheers
