### ISSUE TITLE
Experimental 21w22a - Canopy block collision issues

### ISSUE THREAD

**Issue by MrBester** [tsunamayo/Starship-EVO#3849]
### Short Description of the issue:

Hey Tsuna, I'm running into a issue with both the canopy and canopy wedge blocks, I upgraded to experimental and noticed that several of my ship builds cockpits are not closing fully, after further testing there seems to be a collision issue with objects inside the canopy empty space and the seats in the ship are colliding with them, I tried lowering the seats as a workround but ended up feeling like I was a 10yr old trying to drive dads car, aka really bad field of view. im assuming something in this update has added a collision box to the interior open space in the block but figured best to let you know just incaase youre not aware of the issue.
...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: Experimental 21w22a
- Graphics Card: asus RTX 3090

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@MrBester Hi, could you send me a blueprint so I can investigate the issue? Thanks

**Comment by MrBester** [comment]
Yeah no probs, heres one of my snub fighters you can see when it spawns the canopy is fully closed but if you press one of the buttons on the side just behind the canopy to open it then close it you will see that it comes to rest at an angle instead of fully closed.

[LF-21 Nemesis.zip](https://github.com/tsunamayo/Starship-EVO/files/6640272/LF-21.Nemesis.zip)

**Comment by tsunamayo** [comment]
@MrBester finally fixed for 21w39a. Thanks
