### ISSUE TITLE
[Bug] Can't build on handheld weapon handles

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3851]
### Short Description of the issue:
Nothing can be placed on a Handle when you place it into an item stand
![image](https://user-images.githubusercontent.com/27857711/121585407-75e04000-ca2a-11eb-9fd4-42091d8ed7d8.png)

### Steps to reproduce the issue:
- Place a Handle in an Item Stand and try to build on it

### Environment
- Starship EVO version: 21w22a
- Graphics Card: RX 580

**Comment by Dwarf-LordPangolin** [comment]
Wanted to add a couple notes to this:

The one spot you can add things is on the very bottom. Placement is wonky if placement by Global Origin Grid is on.
![20210728173546_1](https://user-images.githubusercontent.com/33041786/127405254-40e43a0e-2130-46ee-9b86-68af4a2e5234.jpg)

Switching to Targeted Brick Grid fixes the wonky placement.
![20210728173458_1](https://user-images.githubusercontent.com/33041786/127405277-549fb14b-2db4-494f-a6bd-66512199ae1d.jpg)

However, after placing one brick on that spot, you can't place any other pieces; you can only place the one.
![20210728174005_1](https://user-images.githubusercontent.com/33041786/127405303-dca5b7ab-b545-4c34-acb1-38981b484b56.jpg)

You can, however, paste things on it. The pasted part can then be built on, but the placement on it gets really weird.
![20210728174053_1](https://user-images.githubusercontent.com/33041786/127405544-60358ee7-385c-4b63-98dd-26d6e6740763.jpg)

**Comment by tsunamayo** [comment]
@ProPeach Issue fixed for 21w49a. Thanks
