### ISSUE TITLE
[Suggestion] Stretching ratios widget

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3852]
Quick little suggestion to help us out building with non 1x scale, which can be a little tough to keep track of when you want to build a certain ratio shape. Dividing by the stretch factor myself is fine, but not very relaxing :D

![Ratios](https://user-images.githubusercontent.com/27857711/121594475-04f25580-ca35-11eb-8ee7-2c637ed1ea7b.png)

The stretch ratio would just appear beneath the current length measurement

**Comment by tsunamayo** [comment]
yes I wanted to do that.

**Comment by tsunamayo** [comment]
@ProPeach Done for 21w38a!

**Comment by ProPeach** [comment]
Brilliant, thanks for getting back to this one!
