### ISSUE TITLE
Start problem

### ISSUE THREAD

**Issue by NicePerson1** [tsunamayo/Starship-EVO#3855]
### Short Description of the issue:

When i start it freeze

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version:  
- Graphics Card: 
1070
### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by Kaiser-Indrasil** [comment]
This literally gives us nothing to work with.
You really need to provide the Player.log file for this one.

**Comment by tsunamayo** [comment]
@NicePerson1 Hi, thanks for booking the issue. Could you send the player.log file so we can assist you? Thanks
