### ISSUE TITLE
[Spacestation spawn testing] Modules clipping into each other and station permanence

### ISSUE THREAD

**Issue by CurioInventorium** [tsunamayo/Starship-EVO#3856]
### Short Description of the issue:
I've been testing the spawning of space stations using more variety of pieces. Spawned stations will create their modules without (as far as I can tell) checks to see if they'll clip into an existing piece. 
On a rare occasion a really nice station will spawn.
Also on logging out and back into the game, any spawned stations disappear.
...

### Steps to reproduce the issue:
Place down space station spawner block, checkbox the modules to use and then select the module that will act as the centre.
The spawned station will appear, but most likely there will be some clipping with each other.
...

### Environment
- Starship EVO version: 21w22a
- Graphics Card: rtx2060

### Additional information:
I've added all the test pieces I've been using to this issue. Feel free to use them if they're useful.
I tried to make one of each type, and while I was a bit confused over the difference between "corridor" and "joint", I did assign corridors that had a turn in them as "joints", while the 4-way corridor is set as a "hub" and the straight corridor as a "corridor".
There are some "hubs" that are single decker and double decker too.

_(Screenshots, Videos, Error logs, Related issues)_
Some examples of the spawner behaving
![20210611103846_1](https://user-images.githubusercontent.com/51359034/121673627-fd6c9400-caa8-11eb-8f7c-847debe8079f.jpg)
![20210611103410_1](https://user-images.githubusercontent.com/51359034/121674503-0dd13e80-caaa-11eb-8a13-250a6834f4e2.jpg)

and some where it's not...
![20210611103909_1](https://user-images.githubusercontent.com/51359034/121673832-3b69b800-caa9-11eb-9876-37fb99710925.jpg)
![20210611104035_1](https://user-images.githubusercontent.com/51359034/121673861-458bb680-caa9-11eb-80e7-613fec209aa3.jpg)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.
[Spacestation PiecesBlueprints.zip](https://github.com/tsunamayo/Starship-EVO/files/6637722/Spacestation.PiecesBlueprints.zip)

**Comment by CurioInventorium** [comment]
Just remembered that I haven't tested manually adding modules to a spawned station and then pressing F7 to respawn. I know docked ships are released into space.

**Comment by CurioInventorium** [comment]
I can confirm that modules that are manually added to a generated station are deleted when you press F7.

ISSUE! When walking around the space station I have encountered on a few different spawns areas where the gravity stops working and the character is able to clip through the building. The two times this has happened has been while moving around the starting module (or hub the times this happened).
For clarity, all modules have gravity active on them.

**Comment by tsunamayo** [comment]
Collision issue fixed in recent build. Thanks
