### ISSUE TITLE
[BUG] Decal "hierarchy" is completely broken 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3857]
### Short Description of the issue:
What i am calling the decal hierarchy is the ability for a decal to be placed on top of another and obscure the one below it. In the video below you can see a video at 12 seconds in i place down a triangle decal and 31 seconds you can see that when i delete part of the circle the triangle is below it instead of on top as it should have been. Almost immediately you can see another problem that being that i am unable to paint decals "head on" or delete them (i later realized that i had be deleting and recoloring decals on the inside and other side of the ship)   

...

### Steps to reproduce the issue:
attempt to use decals on included world 
...

### Environment
- Starship EVO version: 21w22a

### Additional information:

https://user-images.githubusercontent.com/56371294/121739763-e92c9500-cab0-11eb-8f55-a9ab85178ad6.mp4

[TIKI-NOVOXONE.zip](https://github.com/tsunamayo/Starship-EVO/files/6640659/TIKI-NOVOXONE.zip)

**Comment by Kaiser-Indrasil** [comment]
Yep. All of these are happening to me as well.

**Comment by tsunamayo** [comment]
@TIKIRobo @Kaiser-Indrasil I would a better test case, it is really hard for me to understand on the video. I am not sure on how the triangle at 12 sec should be, it is white over white... thx

**Comment by tsunamayo** [comment]
I just fixed something that could have explained that hierarchy bug btw, so you will tell me if you still reproduce in 21w23a. Thanks!

**Comment by Kaiser-Indrasil** [comment]
> @TIKIRobo @Kaiser-Indrasil I would a better test case, it is really hard for me to understand on the video. I am not sure on how the triangle at 12 sec should be, it is white over white... Also lets take one issue at a time, it would make my life a lot easier to see what is going on ;)
> thx

@tsunamayo I can identify 2 outstanding issues based on my experience:
- hierarchy issue where oftentimes when you apply a decal on top of another one, it ends up underneath it instead
- selection box issue where oftentimes when you point at a decal, the game doesn't recognize it as your actively selected object. It's very noticeable when you try to colour or remove decals.

**Comment by tsunamayo** [comment]
Seems all good now!
