### ISSUE TITLE
[Bug] Ship movement problem

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#3858]
### Short Description of the issue:

I have noticed that my ship will not perform a roll command until I first issue a forward movement command. This "trigger" must be redone every time the ship is commanded and again if the view mode "F4/Tab" is changed/reset.

In previous versions, I recall being able to roll a ship (for sunlight) without having to change any other motion parameters.

### Steps to reproduce the issue:

Command a ship.
Try to roll it before any other motion.

### Environment
- Starship EVO version: 21w22a
- Graphics Card: GTX1070

**Comment by tsunamayo** [comment]
@cloudrambler I cant reproduce that one, it must have been fixed... Thanks
