### ISSUE TITLE
[Experimental][21w22a] Game freeze and entities erased from world on exit to menu

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#3860]
### Short Description of the issue:
When quitting to the main menu, world unloads except for the skybox, and then the game freezes. When the game is restarted and the world is reloaded, all entities are gone. Other objects like planets, stars, and torus are fine.

### Steps to reproduce the issue:
1. Start new world
2. Press Esc key
3. Click exit to title

### Environment
- Starship EVO version: 21w22a
- Graphics Card: Nvidia GeForce GTX 1060 6GB

### Additional information:
Here is a screenshot taken after the game has frozen. Everything except a skybox and text from displays are left.
![20210612015905_1](https://user-images.githubusercontent.com/51390907/121790876-0dbc6600-cbb2-11eb-89a7-e7a7d85c7eaa.jpg)
Here is the same world after reloading the game. Every entity including the starting area is gone.
![20210611205404_1](https://user-images.githubusercontent.com/51390907/121791021-532d6300-cbb3-11eb-8c33-684f69655333.jpg)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6643008/Player.log)

EDIT: I've confirmed that the bug does not happen to me on Stable branch version 21w07a, just on Experimental branch.

**Comment by tsunamayo** [comment]
Fixed for 21w23a. Thanks!
