### ISSUE TITLE
[MAJOR BUG] Save game corruption when flying(crashing) into planet.

### ISSUE THREAD

**Issue by AsageSoftworks** [tsunamayo/Starship-EVO#3861]
### Short Description of the issue:

If you fly a ship into a planet, it; bugs out the world; destroys the ship; crashes the game; corrupts the save so that it crashes every time you reload

### Steps to reproduce the issue:

fly a ship into any planet, tested with a planet called mistrel

### Environment
- Starship EVO version: newest exp branch
- Graphics Card: gtx 1070

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by TIKIRobo** [comment]
IIRC dying in this latest branch will cause the bug you are reporting and when you crash into a planet you die so they are probably linked 
See #3803

**Comment by tsunamayo** [comment]
@AsageSoftworks Sorry I slept on this, could you please send me your character save, I will do something so you can load it back.
