### ISSUE TITLE
Build Menu - Options don't save

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#3863]
### Short Description of the issue:
If you change these settings then restart your game, it all reverts back to the defaults
...

### Environment
- Starship EVO version: 21w23a
- Graphics Card: GTX 970

### Additional information:
![20210614094329_1](https://user-images.githubusercontent.com/32974671/121911286-43b63300-ccf5-11eb-8fdc-5ead1f1f6c2f.jpg)

**Comment by BigBadKangaroo** [comment]
Happens to me as well!

**Comment by tsunamayo** [comment]
@Xerma Are you sure you are closing the option tab first? It saves on closing.

**Comment by Xerma** [comment]
It's saves when you close the menu until you exit the game/session, then the next time you open the world again it reverts to the defaults

**Comment by tsunamayo** [comment]
@Xerma fixed for 21w24a. Thanks mate!
