### ISSUE TITLE
[Bug] GUI SFX are not counted as game sounds

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3864]
### Short Description of the issue:
When changing the sound levels in the Sound Settings, GUI SFX are unaffected.
Here I have set the Game and Music Volume to 0%, but I can still hear the GUI SFX at full volume
![image](https://user-images.githubusercontent.com/27857711/121933173-a29f9a80-cd3d-11eb-9997-662af5f376d4.png)

### Steps to reproduce the issue:
- Reduce Game and Music Volume to 0
- Use the Codex GUI

### Environment
- Starship EVO version: 21w23a
- Graphics Card: RX 580

**Comment by ProPeach** [comment]
I've just also found that laser hit SFX are also played at max volume with these settings

**Comment by tsunamayo** [comment]
@ProPeach Issue fixed. Thanks!
