### ISSUE TITLE
Suggestion: Soundtrack

### ISSUE THREAD

**Issue by Jorpis-Jorah** [tsunamayo/Starship-EVO#3865]
**Due to personal complications, this project has been postponed indefinitely** 
Hello, Francois
As you know, the game does not currently have a soundtrack. The only part of the "Soundtrack" is the song that plays in the main menu, and while fun and exciting, the game can seem at times quiet.  Well I would be happy to make a complete soundtrack for you. I have a sample of what to expect prepared on YouTube [Here](https://www.youtube.com/watch?v=7Yex8YT4Mxk&t=226s) Let me know what you think by messaging me on GitHub or by my Email: Bomb.guynoob@gmail.com.
Thank you for your time!
 -Jorah Morris

**Comment by cloudrambler** [comment]
@Jorpis-Jorah 

Nice work! There is nothing wrong with cyber-noir while playing STEVO. I would love to have an extended version of this, mixed with ship/engine noises etc. in game as a background for building to.

**Comment by RockefellerDoctor** [comment]
Tsun had indicated in his early access kickstarter that he wanted to bring on a composer once they hit a certain donation milestone. As far as I'm aware, that milestone was never hit.

**Comment by tsunamayo** [comment]
@Jorpis-Jorah Sorry I am only seeing this now - I cant access the video. I hope you are doing good!

**Comment by Jorpis-Jorah** [comment]
I have cleared my personal emergency, the link should be accessible now
