### ISSUE TITLE
[Bug] Damage decals show up in the codex

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3866]
### Short Description of the issue:
Two damage decals are visible in the codex, both labelled "Arrow"
![image](https://user-images.githubusercontent.com/27857711/122110268-40669880-ce16-11eb-9d77-f8d9557950ee.png)

### Steps to reproduce the issue:
- Open the Codex and look in the decals tab

### Environment
- Starship EVO version: 21w23a
- Graphics Card: RX 580

**Comment by Kaiser-Indrasil** [comment]
These are damage decals. Probably just a matter of being incorrectly flagged for visibility in the Codex

**Comment by ProPeach** [comment]
I know ; )

**Comment by tsunamayo** [comment]
Fixed for 21w24b. Cheers
