### ISSUE TITLE
Volumetric sensor

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#3867]
The volumetric sensor doesn't seem to interact in any way with the player.
Placing one and connecting it to a door or button doesn't activate any of these.
Even adding some logic doesn't help.
Changeing the settings of the VS does nothing.

I tried to connect a switch to the VS but that freezes my game!

**Comment by Servomotor** [comment]
any news on this issue?

I use volumetric sensors almost exclusively for triggering lights and doors. This is making it hard to complete anything.

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, this is fixed for 22w45a. Thanks
