### ISSUE TITLE
[Suggestion] Dynamic Cutaway Tools

### ISSUE THREAD

**Issue by NordicLink** [tsunamayo/Starship-EVO#3868]
I was wondering if it would be possible to add some sort of dynamic cutaway tools to cut out parts of a block without having to remove and rebuild them with existing blocks. This would make doing interiors much easier because you don't have to delete an entire hull block to modify a wall. Not to mention it could make for more interesting hull shapes.

Example: Chisel n bits mod for Minecraft

Visual Example: Images taken from the minecraft mod used to illustrate a 1m cubed block being chiseled to add detail by removing a chunk, rather then building the object by hand. Basically, it can cut a piece out of the block at varying depths in one cut, when this shape would normally take many separate blocks to make.
![Statue](https://user-images.githubusercontent.com/86028145/122310505-57b08f00-cec5-11eb-83e3-4e94a01d1cdd.png)
![minecraft chisel n bits 2](https://user-images.githubusercontent.com/86028145/122310510-5aab7f80-cec5-11eb-918a-d6f3e63e7315.jpg)
![minecraft chisel n bits 3](https://user-images.githubusercontent.com/86028145/122310513-5c754300-cec5-11eb-9e67-67020c10eb97.png)
![pillar](https://user-images.githubusercontent.com/86028145/122310529-6139f700-cec5-11eb-9264-4c41db201c75.png)

**Comment by tsunamayo** [comment]
@NordicLink Hi, this is not possible at all with the current tech, we moved away from voxel completely now...

**Comment by NordicLink** [comment]
@tsunamayo thanks for taking the time to review my suggestion, shame its not possible but it cant be helped. thank you for the amazing game.

**Comment by NordicLink** [comment]
@tsunamayo thanks for taking the time to review my suggestion, shame its not possible but it cant be helped. thank you for the amazing game.



> @NordicLink Hi, this is not possible at all with the current tech, we moved away from voxel completely now...
