### ISSUE TITLE
[Crash] Unsure what caused it

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Starship-EVO#3870]
### Short Description of the issue:

I was building some barrels onto guns on a turret and suddenly became unable to place or break blocks. I then tried to exit to main menu and the game crashed. I have attatched the files.

### Steps to reproduce the issue:

Unknown

### Environment
- Starship EVO version: 21w23a
- Graphics Card: 3070

### Additional information:
Files from the temp crash file:
[error.log](https://github.com/tsunamayo/Starship-EVO/files/6672553/error.log)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6672554/Player.log)
[crash.zip](https://github.com/tsunamayo/Starship-EVO/files/6672558/crash.zip)

File from the main directory:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6672559/Player.log)

**Comment by tsunamayo** [comment]
@Garrett-C I think that one was fixed some time ago. Thanks
