### ISSUE TITLE
[Bug] Slight Visual Stretch Difference

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#3871]
![image](https://user-images.githubusercontent.com/36980446/122541397-7191c500-cfde-11eb-9c3d-a0a595eeebec.png)
The stretching is the same and lines with with the relative sized grid, but the visual boundaries are a bit off

**Comment by tsunamayo** [comment]
Yeah because it has to be a bit greater so you can see it... Not a big deal surely.
