### ISSUE TITLE
[Experimental] World breaks after deleting hinge

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#3872]
### Short Description of the issue:
I deleted a hinge on a ship, and suddenly every entity would visually follow my character as if they were all somehow also part of my character, but their physical selves were in the same spot as before the hinge-breaking. The outline of targeted bricks and the text on screens, as well as bumping into entities confirmed it was just visual. After quitting to title and reloading the world, all entities were bugged out completely, with textures and brick shapes mangled almost beyond recognition. My character was invisible, but the multitool wasn’t, and player movement inputs were defunct. I couldn’t move or look around.

### Steps to reproduce the issue:
Delete a hinge mechanism

### Environment
- Starship EVO version: 21w23a
- Graphics Card: Nvidia GeForce GTX 1060 6gb

### Additional information:
I had changed the build settings in the F1 menu for the first time.

The blueprint I deleted the hinge from was a few versions old.
[novox_Majikmonster_ship_police_patrol.zip](https://github.com/tsunamayo/Starship-EVO/files/6678735/novox_Majikmonster_ship_police_patrol.zip)

After breaking the hinge, you can see that the entities would all follow my character (screenshot 1+2).
![20210618132558_1](https://user-images.githubusercontent.com/51390907/122601922-05e04400-d040-11eb-9bf8-0253a7e55c8c.jpg)
![20210618132737_1](https://user-images.githubusercontent.com/51390907/122601951-0d9fe880-d040-11eb-9979-ee5942ae2e72.jpg)
After reloading the world from the menu, every brick-based entity and my character is visually broken.
![20210618132816_1](https://user-images.githubusercontent.com/51390907/122602056-332cf200-d040-11eb-8789-3f4ca87d20b8.jpg)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6678715/Player.log)

**Comment by RockefellerDoctor** [comment]
Seems like a combo of the "random misshaped black brick" bug and the disappearing brick bug.

**Comment by tsunamayo** [comment]
@Majikmonster the bug is related to symmetry, you deleted an entity where symmetry was active on.

**Comment by tsunamayo** [comment]
Fixed for 21w24b. Thanks
