### ISSUE TITLE
[Question] Multistage sequencer

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Starship-EVO#3873]
With the new novox tech allowing people to build larger ships without harming performance as much, I was recently wondering how people and NPCs could traverse these larger ships and the two options that came to me were a monorail esc system for horizontal movement and elevators for vertical. As things stand building these methods of movement for more than 2 points requires a lot of mechanisms and a lot of logic. Which is fine but not the most intuitive or player-friendly. 

Now in the past, you could connect many sequencers to one system which allowed this function to work well and this is certainly one option for allowing the creation of these systems. That said I do agree that the sequencer acting this way does seem odd as it would be the only element of logic to behave like this. So perhaps a new specialised sequencer could be the solution. Maybe it allows the user to have multiple states. Now obviously the issue this presents is that it's tough to control a sequencer like this. On/off is an easy way to control a sequencer but one with say 10 states between is not as easy. I don't have an elegant solution to this but perhaps there could be another element added to logic, like channels for example. 

Channels could function by passing your on/off signal to a channel logic block, the channel can be configured in here. Then the output from the channel system would be an on/off signal with an assigned channel. This could then by passed to the advanced sequencer which has different states for different channels. 

Something like this:
![image](https://user-images.githubusercontent.com/43644633/122625974-c8ab9e80-d09f-11eb-8c7a-fe9a63676e9e.png)

I don't know that this is the best solution and am sure you have some ideas cooking but figured I would throw some ideas out there to see what the thoughts on this area are.

**Comment by tsunamayo** [comment]
Yep it is a major gap I need to address. I need to spend more time thinking about it, I also want to introduce a "Push config override" gate that could achieve this. Thx
