### ISSUE TITLE
[Bug] Logic and delay gate do not preserve new configuration

### ISSUE THREAD

**Issue by milan-t** [tsunamayo/Starship-EVO#3875]
### Short Description of the issue:
Logic and delay gate configuration is not preserved after closing configiration dialog.
Logic gate has always OR function and delay gate has default value 0.1.

### Steps to reproduce the issue:
1. Place logic or delay gate on hull block
2. Open configuration dialog 
3. Set different value (logic function or delay)
4. Close dialog and open it again

#### Expected result
- logic gate: selected logic function is still set
- delay gate: set delay value is preserved

#### Actual result
- logic gate: OR function is selected
- delay gate: delay is 0.1

### Environment
- Starship EVO version: 21w24a
- Graphics Card: NVIDIA GeForce GTX 1660 Ti

### Additional information:
After closing configuration for logic gate I see briefly flashing symbol of selected function then OR symbol is displayed again.

**Comment by milan-t** [comment]
Hi, 
I would like to add another fingding that may be somewhat linked to this issue. 

Source logic gate resets to default OR when is connected or disconnected from other blocks using link tool. If logic gate is link target it keeps its configuration.

#### Before disconnection of NOR gate from AND gate
![state_before_disconnection](https://user-images.githubusercontent.com/65783423/122672770-9304d380-d1cd-11eb-98dd-e4e77121a21c.png)

#### After disconnection of NOR gate from AND gate, NOR gate is now OR
![state_after_disconnection](https://user-images.githubusercontent.com/65783423/122672774-95672d80-d1cd-11eb-8f1a-7acc48f6f0b7.png)

**Comment by tsunamayo** [comment]
@milan-t fixed for 21w24b. Thanks
