### ISSUE TITLE
Logic gates don't change from OR

### ISSUE THREAD

**Issue by Malcho1234** [tsunamayo/Starship-EVO#3876]
### Short Description of the issue:

...Logic gates won't switch to AND or anything else.

### Steps to reproduce the issue:

...Place down a Logic gate, try to change it to AND or anything else but an OR.

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by RockefellerDoctor** [comment]
Seconded. All my logic gates change to OR regardless of what I click to set them to. Completely broke my entire ship because now everything that is supposed to be AND is now OR so everything is trying to engage at once.

**Comment by tsunamayo** [comment]
Fixed for 21w24b. Thanks
