### ISSUE TITLE
Child Entitys on BP don't spawn in 

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#3877]
Hi,

I was just working on a ship that has some logic linked to pistons which had some hinges and stuff on them. After restarting the game the blueprint spawns in without the child entitys from the pistons!
The preview in the codex however shows that the "wings" are there and are absolutely fine. They just don't spawn in.

That's how it spawns in:
![20210619184928_1](https://user-images.githubusercontent.com/81495956/122649858-46b78600-d130-11eb-876e-7321b30beabb.jpg)

That's the preview
![KF-Bulldog_preview](https://user-images.githubusercontent.com/81495956/122649934-8aaa8b00-d130-11eb-8f29-36fa53cbdd09.png)

That's how it is suposed to be!
![20210619185038_1](https://user-images.githubusercontent.com/81495956/122649863-49b27680-d130-11eb-86e7-4948ff16dffd.jpg)

**Comment by tsunamayo** [comment]
@BigBadKangaroo Could you send me the blueprint, it seems fine on my world...

**Comment by tsunamayo** [comment]
So fixed for 21w24b, except that your save are corrupted... I hope you had a recent backup. What is corrupted is the mechanism you manually edited at one point after the last update. Sorry mate...
