### ISSUE TITLE
Glow bricks are blinding white 

### ISSUE THREAD

**Issue by JackBobS** [tsunamayo/Starship-EVO#3878]
### Short Description of the issue:

All glow bricks after the 21w24a update are all bright white light regardless of what paint has been used on them (with the exception of black). Hooking them up to the new RGB logic bricks does somewhat fix the problem, but it is tedious to hook up so many and the color on the RGB logic brick will not match the glow brick itself, which will still always be significantly brighter. 

...

### Steps to reproduce the issue:

Place a glow brick. Try to paint it a different color. Attach it to an RGB logic brick. Change the color on there.

...

### Environment
- Starship EVO version: Experimental 21w24a 
- Graphics Card: Core i7

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@JackBobS Not sure to understand the issue, I paint them red and they are definitely red, not white. Or is it a blueprint loading issue? Thanks

**Comment by milan-t** [comment]
Hi,
I would like to present some examples that illustrates my understanding of the issue with glowing bricks.
The glow around brick has color but brick itself looks white. The RGB gate helps but when brick color is more noticeable glow effect almost disappeared.

![20210621190838_1](https://user-images.githubusercontent.com/65783423/122801319-3e904f80-d2c4-11eb-89fd-4f8784ae6000.jpg)

*Light bricks for comparison:*
![20210621194156_1](https://user-images.githubusercontent.com/65783423/122805090-f0317f80-d2c8-11eb-8a44-59d1ca12b199.jpg)

For me it is not big issue but I think glowing bricks will look nicer with bolder colors.
Anyway I like glowing bricks and possibility to control them.

**Comment by Kaiser-Indrasil** [comment]
Amazing illustration, @milan-t 
I see the problems with the light emissive blocks continue 😅

**Comment by tsunamayo** [comment]
@JackBobS Okay great description. Indeed the RGB controller changed a few things, so I need to simply recalibrate those blocks. I keep you guys posted!

**Comment by tsunamayo** [comment]
@JackBobS Okay so actually it was an issue in the shader code, the white was 1.7x too powerful. Now it is better, although you still need a darker color to get darker shades. It is a bit of a pain right now as you can really add custom color seamlessly - but that will be added soon. 
Fixed for 21w27b.
Thanks
