### ISSUE TITLE
[Bug] Unable to link/unlink yoke to/from spaceship computer

### ISSUE THREAD

**Issue by milan-t** [tsunamayo/Starship-EVO#3879]
### Short Description of the issue:
Link tool refuses connect or disconned yoke to/from spaceship computer.
Linking hoovercraft computer or turret computer works fine.

### Steps to reproduce the issue:
1. Build basic ship with yoke and spaceship computer
2. Try connect yoke with spaceship computer using link tool

#### Expected result
Link is created successully.

#### Actual result
Pointing link's end to spaceship computer changes link and computer highlight color to orange.

### Environment
- Starship EVO version: 21w24a
- Graphics Card: NVIDIA GeForce GTX 1660 Ti

#### Screenshots
![cannot_connect_yoke_to_spaceship_computer](https://user-images.githubusercontent.com/65783423/122673434-b9783e00-d1d0-11eb-9327-f0a349feff4f.png)

![cannot_disconnect_yoke_from_spaceship_computer](https://user-images.githubusercontent.com/65783423/122673436-baa96b00-d1d0-11eb-9cc7-42eaab7ee292.png)

**Comment by tsunamayo** [comment]
@milan-t  Issue fixed for 21w24b. thx!
