### ISSUE TITLE
[Bug] F1 build menu does not save settings across sessions

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3880]
### Short Description of the issue:
When you quit the game to desktop, the F1 menu settings are wiped so that you need to set them up again for every new session

### Steps to reproduce the issue:
- Modify F1 menu settings
- Quit the desktop
- Open the game again and check the menu

### Environment
- Starship EVO version: 21w24a
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
Hum this was supposed to be fixed...

**Comment by tsunamayo** [comment]
@ProPeach yeah mine are loading correctly, do you reproduce all the time?

**Comment by ProPeach** [comment]
Every time yeah, here's my log - 
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6683609/Player.log)
When I Exit to Title or Exit to Desktop, my F1 settings are not saved

**Comment by tsunamayo** [comment]
@ProPeach Can you tweak some settings, then exit the game. Then upload me the SETTINGS.ini from the save folder! thx

**Comment by ProPeach** [comment]
[SETTINGS.zip](https://github.com/tsunamayo/Starship-EVO/files/6686779/SETTINGS.zip)
Sure, here you go!

**Comment by tsunamayo** [comment]
So I think we should be good now for 21w47c! Thanks
