### ISSUE TITLE
[Bug?] Placement Grid Origin setting is backwards

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3881]
Not sure if this is a bug or a misunderstanding on my part

When the setting is set to Global Grid Origin, bricks will snap to the face of a similarly scaled brick
![image](https://user-images.githubusercontent.com/27857711/122679084-5a6ef500-d1e1-11eb-9266-c56860fde897.png)

When the setting is set to Targeted Brick Grid, bricks will snap to the global grid
![image](https://user-images.githubusercontent.com/27857711/122679078-54791400-d1e1-11eb-8bd5-23f303932e29.png)

This seems like it's backwards to me, but I may just be misunderstanding the terms

**Comment by tsunamayo** [comment]
Indeed, fixed for 21w24b. Thanks!
