### ISSUE TITLE
[Bug] Hull Damaged is present in the Codex

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3882]
### Short Description of the issue:
There seems to be a stowaway!
![image](https://user-images.githubusercontent.com/27857711/122679333-57283900-d1e2-11eb-960e-04d9831d79a8.png)
Both the slope and cube shape are here

### Steps to reproduce the issue:
- Open up the Codex

### Environment
- Starship EVO version: 21w24a
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
Good catch, these are removed for 21w24b. Cheers
