### ISSUE TITLE
Logic Gates and Handheld weapon building broken

### ISSUE THREAD

**Issue by jp8fluffy** [tsunamayo/Starship-EVO#3884]
### Short Description of the issue:
All logic gates revert to OR gates after closing the logic menu. 
After placing a handle into an item stand, no new bricks can be placed onto the weapon, with all bricks appearing red
...

### Steps to reproduce the issue:
Place down logic gate
select logic other than OR
exit menu
reopen menu

place item stand
Press f to insert weapon handle

...

### Environment
- Starship EVO version: 21w24a
- Graphics Card: GeForce rtx 1080 FE

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by zorozeenee** [comment]
have this bug too, handhelds completely broken rn

**Comment by tsunamayo** [comment]
@jp8fluffy Handheld are finally fixed in 21w49a. Thanks
