### ISSUE TITLE
Copy Paste Turret Bug

### ISSUE THREAD

**Issue by Sekiberius** [tsunamayo/Starship-EVO#3885]
### Short Description of the issue:
I used the copy paste tool to copy and paste my turrets and it broke so I couldn't place any more turret barrels so I exited the game to fix it, when I opened the level again some of my turrets disappeared and one of them moved to where one of my other turrets were.
...

### Steps to reproduce the issue: 
Use copy and paste tool to attach turret to rotor attached to ship then use copy and paste to attach turret weapon to rotor, if game bugs and doesn't allow you to place barrels exit the game and return.
...

### Environment
- Starship EVO version: 21w24a
- Graphics Card: RTX 3080

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\` 
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6683074/Player.log)
[Warship PROTO.zip](https://github.com/tsunamayo/Starship-EVO/files/6683076/Warship.PROTO.zip)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Sekiberius So fixed for 21w24b, except that your save are corrupted... I hope you had a recent backup. What is corrupted is the mechanism you manually edited at one point after the last update. Sorry mate...
