### ISSUE TITLE
Configurable max stretch for blocks

### ISSUE THREAD

**Issue by timethatswasted** [tsunamayo/Starship-EVO#3886]
It would be nice if we had the option to change the max stretch of blocks in the f1 menu. 

Unless there is some specific memory usage reason why blocks have a stretch limit.. or if it ties into how damage or collisions will be calculated in the future…

I would think it would be better for memory usage over all if we could stretch our 1/8 1/4 and 1/2 blocks beyond their base max size for large scale detailing.

**Comment by tsunamayo** [comment]
Hi, it is not possible because of engine reason. thx
