### ISSUE TITLE
[Question] Stretching bricks to 1 or 2 dimensions

### ISSUE THREAD

**Issue by Zenti98** [tsunamayo/Starship-EVO#3889]
Hello there!
i am pretty sure, that this has been asked already here but I really can't find the post and just would be happy to know your answer to this: will there be the possibility in future to stretch e. g. a 1x1x1 brick to e. g. 12x12x64m?

Because for some walls or floors it would be nice to build with bigger plates but they shouldnt be 4 or 8m thick.

Are you going to drop something like this? I think, it would make sence with the new building system- thank you and sorry if you answered this already, have a nice day!

**Comment by Kaiser-Indrasil** [comment]
Yep, sorry, it's been answered a few times before and due to how the building engine works, cannot be implemented.

**Comment by Zenti98** [comment]
> 
> 
> Yep, sorry, it's been answered a few times before and due to how the building engine works, cannot be implemented.

Ah thank you very much for the quick answer!
