### ISSUE TITLE
[Experimental] Wrong texture, wrong name on 2 bricks

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#3891]
### Short Description of the issue:
The texture for the pipe base/thin pipe and the round tile (round tile creased with wrong name) have wrong texture.

### Environment
- Starship EVO version: 21w24b
- Graphics Card: Nvidia GeForce GTX 1060 6gb

### Additional information:
![20210621172024_1](https://user-images.githubusercontent.com/51390907/122830758-ca02e400-d2b6-11eb-8c6a-171293c2a7aa.jpg)
![20210621174611_1](https://user-images.githubusercontent.com/51390907/122832141-edc72980-d2b8-11eb-9304-5c57ae10eb80.jpg)
![20210621174613_1](https://user-images.githubusercontent.com/51390907/122832142-edc72980-d2b8-11eb-939e-054293633117.jpg)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6689628/Player.log)

**Comment by BigBadKangaroo** [comment]
I actually like the new texture for the pipe base. But i'd like to have the option to get the old texture back. 
Maybe as a new block?

**Comment by Pawnp** [comment]
Naming isn't wrong on the two round tiles, they just both have the wrong texture. Older builds that use the round tile have that creased marking instead of the flat texture.

**Comment by tsunamayo** [comment]
@Majikmonster Thanks indeed, issue fixed for 21w27b. Cheers
