### ISSUE TITLE
[Experimental] Un-linking lights from logic bricks freezes game

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#3893]
### Short Description of the issue:
Attempting to remove a connection between a light and logic brick freezes the game and loops the link tool use sound

### Steps to reproduce the issue:
1. Link a light to any logic brick
2. Attempt to un-link that same light from the linked logic brick

### Environment
- Starship EVO version: 21w24b
- Graphics Card: Nvidia GeForce GTX 1060 6gb

### Additional information:

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6690017/Player.log)

**Comment by AurigaNexus** [comment]
Same

**Comment by Servomotor** [comment]
I had the game freeze trying to connect a switch to a second RGB logic brick.

**Comment by Rubaniac** [comment]
It only freezes if the lights are active. If they are inactive then it doesn't happen.

**Comment by tsunamayo** [comment]
@Majikmonster Issue fixed in 21w26b. Thanks
