### ISSUE TITLE
[EXP] RGB and Logic incompatible

### ISSUE THREAD

**Issue by AurigaNexus** [tsunamayo/Starship-EVO#3894]
As title states. Changing colors of light/glow blocks now requires an RGB module, however having the block connected to an RGB module prevents it from receiving logic connections. Hence, a logic-controlled light block cannot have its color changed from the default and a color-changed light/glow block cannot be controlled by logic. 

Possible solutions:

*Allow connections from both RGB and logic blocks on light blocks
*Allow logic switch connected to RGB module control connected lights (i.e. switch connected to RGB module controls lights on/off)
*Allow RGB settings to pass through logic chain *i.e. RGB -> AND gate -> lights, then wire switches to AND gate. (Would allow one RGB module to control color for several lights with independent on/off switches)

**Comment by tsunamayo** [comment]
@AurigaNexus so I havent tried but what you would need is simply:
- Paint your light pure black.
- Then connect a toggle to the RGB gate.
Once toggled off the light will turn off.
