### ISSUE TITLE
ship not spawning

### ISSUE THREAD

**Issue by arutus109** [tsunamayo/Starship-EVO#3895]
[ANPIF Aurora Battleship EXP2.zip](https://github.com/tsunamayo/Starship-EVO/files/6697553/ANPIF.Aurora.Battleship.EXP2.zip)

**Comment by arutus109** [comment]
Ive tried everything and the ship wont spawn, im hoping you can fix it

**Comment by tsunamayo** [comment]
@arutus109 Hi, what version are you using? Can you join a log file? Thanks

**Comment by arutus109** [comment]
not sure how to post a log file but this is from the most up to date and recent version of sevo's exp build

**Comment by arutus109** [comment]
im hoping you can somehow pull brick data of some sort and spawn the ship, as ive poured many hours into it

**Comment by tsunamayo** [comment]
@arutus109 Hi, do you have a slightly older version of that ship? Did it started after the RGB update?

**Comment by Arutus** [comment]
I do not that is the only file of it I have left everything else is gone. And yes it started during that update

**Comment by Arutus** [comment]
But I must ask can you salvage the ship from that sevo file? Its at this point the last of its kinds as all my other builds are gone.

**Comment by tsunamayo** [comment]
@Arutus No for some reason I cant. But could you send me your World save in its entirety? I may be able to find it in your world. Thanks

**Comment by Arutus** [comment]
i dont have my computer to give you the world file at the moment its away for repairs

**Comment by tsunamayo** [comment]
@Arutus Sure, please send me it once you have it back.

**Comment by Arutus** [comment]
Here ive the data
[ARUTU - Copy.zip](https://github.com/tsunamayo/Starship-EVO/files/6819502/ARUTU.-.Copy.zip)

**Comment by tsunamayo** [comment]
[Blueprints.zip](https://github.com/tsunamayo/Starship-EVO/files/6859990/Blueprints.zip)
@Arutus @arutus109 Hi here are the file I can get back. I hope it will do... Thanks
