### ISSUE TITLE
[BUG] linking lights mid rgb cycle causes crash 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3896]
### Short Description of the issue:
I turned on a red (150,0,0) to black (0,0,0) rgb gate and began linking it to lights after linking up a few the game locked up and then crashed 
...

### Steps to reproduce the issue:
link an RGB gate (that is on) to lights 
...

### Environment
- Starship EVO version: 21w24b
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6698200/Player.log)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6698204/Player.log)
(I checked the player logs myself and they didn't seem to show anything but maybe they will to your trained eye)

**Comment by TIKIRobo** [comment]
![image](https://user-images.githubusercontent.com/56371294/123023254-ef155680-d38b-11eb-922d-976c609d571b.png)
also after one of these crashes related to logic+RGB gate all of my ship except for the child entities turned invisible

**Comment by Uncle-Ulty** [comment]
I had the same problem and opened another issue.

![image](https://user-images.githubusercontent.com/73253472/123889951-d3322780-d92c-11eb-9f8c-9d44843e1ee2.png)

**Comment by tsunamayo** [comment]
Hi, this should be fixed in 21w26b. Thanks
