### ISSUE TITLE
[Video Essay] ? - Can We Make Better Tutorials for Complex Games?

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3900]
I highly encourage you to watch it in full, as it provides a really broad take on different aspects of tutorials, using examples from many different types of games.
I can see it addressing Stevo's UI and tutorial design issues and how to make them better.
I'd thought I had a pretty good idea on what makes tutorials either good or bad but this video has proven me wrong:
[Can We Make Better Tutorials for Complex Games?](https://www.youtube.com/watch?v=-GV814cWiAw)

**Comment by tsunamayo** [comment]
Thanks mate I have added to my to watch list. One of the best video about tutorial I watched was from the guy who made Plant vs Zombie,
https://www.youtube.com/watch?v=fbzhHSexzpY 
Cheers
