### ISSUE TITLE
[BUG] Ship Spawning Spawns Station Pieces Instead

### ISSUE THREAD

**Issue by DarthPeter0** [tsunamayo/Starship-EVO#3901]
### Short Description of the issue:
I experienced a crash while exporting a blueprint of a ship.  After restarting the game, I saw the ship in the world was made only of invisible blocks.  I tried to respawn the ship via its blueprint; however, it only spawned random pieces of the prefab stations.  There appears to be no pattern to it; it just spawns in different station pieces and, occasionally, nothing at all.  I tried to load the ship in a brand-new world as well, yet I experienced the same issue.  The only other thing I can say about the issue is that I was using the new RGB gate to color some glow bricks on the blueprint right before the export and crash.  I have included both the blueprint and the world file which first experienced the issue. 

If you are able to recover the craft file, I would be very grateful.  I have put a lot of time into this blueprint, and I would hate to lose it.
...

### Steps to reproduce the issue:
Load the attached blueprint into a world from a starter block.
...

### Environment
- Starship EVO version: Experimental 21w24a
- Graphics Card: NVIDIA GTX 1060

### Additional information:

[HeavyFighter2.zip](https://github.com/tsunamayo/Starship-EVO/files/6712754/HeavyFighter2.zip)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6712763/Player.log)
[Peter 3.zip](https://github.com/tsunamayo/Starship-EVO/files/6712766/Peter.3.zip)
 Image of what the ship is supposed to look like:
![20210624142827_1](https://user-images.githubusercontent.com/33942288/123352036-56114780-d513-11eb-8ea8-ec1247ed025e.jpg)

**Comment by tsunamayo** [comment]
@DarthPeter0 Hi, I can reproduce the issue, unfortunately I have a bad feeling about this as the save file is 0kb large... Do you have older version of this blueprint? Or a .mps (before the neovox)?
I will look into your character save.

**Comment by tsunamayo** [comment]
@DarthPeter0 Was it is inside your world at some place? Thanks

**Comment by tsunamayo** [comment]
[HeavyFighter.zip](https://github.com/tsunamayo/Starship-EVO/files/6752182/HeavyFighter.zip)
@DarthPeter0 So here it is. The trick is to go into this folder:
Starship EVO\Save_Data\Characters\Peter 3\PlayerEntities
Then look out for ship that might have been saved before, it was this one:
7093A7A9-D0D1C.sevo

Cheers

**Comment by DarthPeter0** [comment]
I appreciate the help.  Unfortunately, the file you found was the file of my old version of the ship.  The most recent one was nearly finished, while the version you found was about 20 hours in labor behind the ship I lost.  I can rebuild it, but it will take some time.
