### ISSUE TITLE
[suggestion] secondary mirror planes

### ISSUE THREAD

**Issue by elro0003** [tsunamayo/Starship-EVO#3903]
Often in ships there are symmetrical parts that are further mirrored. For example cylindrical engines on either side of the ship. So to make building these parts faster and less repetitive, it be nice to have primary, secondary, tertiary and so on mirror planes on the same axis. 

The idea is to have the primary mirror planes be the ones we currently have, but then being able to place a secondary mirror axis on the same plane (secondary mirror wouldn't be mirrored on other side, that might cause issues). Do when you place a block, it would be first mirrored on the secondary mirror, after which it would be mirrored by the primary mirror (or tertiary then secondary and then primary, along the same axis of course). This way you could build engine bays among many other things alot faster.

Not sure how well i explained this, but it would definitely save at least a bit time while building, and might have multiple uses. I'll answer questions and explain things further in comments if necessary.

**Comment by ProPeach** [comment]
Did you see #3836? Sounds like what you're after, unless I'm misunderstanding

**Comment by elro0003** [comment]
No, what I'm thinking about is having 2 or more mirror planes on a single axis, not having 1-3 mirror planes on 3 different axis. 
Here's a badly made example
![IMG_20210625_224629__01__01~2](https://user-images.githubusercontent.com/69245083/123484149-30b23580-d608-11eb-8057-146590af689d.jpg)
The red Line is the primary mirror and orange is secondary. The Green thing is the block placed, which gets mirrored along the orange (secondary) mirror, making the blue thing. Then both the green and the blue get mirrored along the red (primary) mirror, which makes the purple thing. So placing one block would result in 4 blocks along the same axis. Then you could have tertiary or even more mirrors, along with mirrors on other axis, and make some stuff very quickly.

**Comment by zorozeenee** [comment]
they already added this

**Comment by Uncle-Ulty** [comment]
when I need to make something like that, I build this object on an entirely new entity, then I copy/paste where I need. e.g. I build 4 identical turbines in the copper/tan ship, and 2 identical turbines on the silver ship. when I paste I can also put it on hinge/pistons.

![image](https://user-images.githubusercontent.com/73253472/123533393-8d3a5100-d6eb-11eb-958e-147fdaef643d.png)


but I got what you mean... actually, it would be nice to have some sort of array tool, to make what you are proposing, but more than two times.

**Comment by tsunamayo** [comment]
@elro0003 Hi, I understand the need. But I one point I need to stop somewhere :). I think you might be looking to the copy paste to do what you want - it might actually be more useful.
Thanks
