### ISSUE TITLE
[Bug] Q paint menu shows empty window [21w24b]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#3904]
### Short Description of the issue:
The paint selection menu accessed by pressing Q is currently empty.

### Steps to reproduce the issue:
Select a paint in the hotbar, then press Q. The paint selection window that shows up will have a bunch of empty categories.

### Environment
- Starship EVO version: 21w24b
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
![20210626170055_1](https://user-images.githubusercontent.com/33041786/123526830-13c94100-d6a0-11eb-81aa-db842f44fdeb.jpg)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6720748/Player.log)

**Comment by tsunamayo** [comment]
Yes indeed...

**Comment by tsunamayo** [comment]
This is fixed in recent version! Thanks!
