### ISSUE TITLE
[BUG] Ship become invisible after linking lights

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#3905]
### Short Description of the issue:

I was linking logic gates into lights when the game frozen. I saved the file and restarted the game. After that the ship became invisible. I tried to make a new save game but the ship file doesn't open properly anymore. It only shows some of the CE.

Id like to restore the file, cuz I've spent a lot of time on this since the last safe save

### Environment
- Starship EVO version: [experimental]
- Graphics Card: gtx 1660
- cpu: i7 3770
-  16Gb
- win 10

### Additional information:

transparent ship, only CE visible.
![image](https://user-images.githubusercontent.com/73253472/123530707-ded6e180-d6d3-11eb-8ac2-8a54b7a79bd1.png)

log:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/6720913/output_log.txt)

specific file:
[Highwind 169.zip](https://github.com/tsunamayo/Starship-EVO/files/6720916/Highwind.169.zip)

**Comment by tsunamayo** [comment]
@Uncle-Ulty Issue fixed for 21w26b. Cheers
