### ISSUE TITLE
[BUG] Ghost collisions stop mechanism from moving 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3907]
### Short Description of the issue:
Yesterday i made a folding toilet that worked fine, today it now is unable to fold in or out without getting caught on something 
...
Edit: When spawning in a new version of the ship it now works again  
### Steps to reproduce the issue:
load up bp and attempt to activate the toilet 
...

### Environment
- Starship EVO version: 21w24b

### Additional information:

https://user-images.githubusercontent.com/56371294/123665194-e4741a80-d7ec-11eb-8ef4-e902e6c6c149.mp4

[V'Zeer - Guppy Class.zip](https://github.com/tsunamayo/Starship-EVO/files/6727530/V.Zeer.-.Guppy.Class.zip)

**Comment by tsunamayo** [comment]
@TIKIRobo Hi, I have no problem with the mechanism. What is the test case? Did you saw that issue again?
Btw I like that little ship ;)

**Comment by TIKIRobo** [comment]
@tsunamayo sorry for getting back to you so late but idk what caused it, it fixed itself when i spawned in a new version, glad you like it!

**Comment by tsunamayo** [comment]
@TIKIRobo by the way are your build on the workshop? Do you have anything finished? Cheers

**Comment by TIKIRobo** [comment]
@tsunamayo i do have a few things up on the workshop (not as many as id like to though) 
This is an older version of the Guppy
https://steamcommunity.com/sharedfiles/filedetails/?id=2458853921
And this is a sort of shuttle, i do want to redo the interior a little bit to better match my style tho
https://steamcommunity.com/sharedfiles/filedetails/?id=2514320000
