### ISSUE TITLE
[Crash] Play with this character crash

### ISSUE THREAD

**Issue by milktyoon** [tsunamayo/Starship-EVO#3910]
### Short Description of the issue:

Tried to create a new character and play with it but everytime that happens I crash and i'm unable to play..

### Steps to reproduce the issue:

>launch starship
>click play
>create new character
>input name
>press play with this character
>thing pops up and loading bar loads like 1/4th of the way
>it crashes

### Environment
- Starship EVO version: Latest from steam. 
- App ID: 711980
- Build ID : 6268529
- Graphics Card: NVIDIA GTX 970

### Additional information:

[https://cdn.discordapp.com/attachments/342383722185883648/859258659355754516/422aadc078.png](url)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6735329/Player.log)

I also tried switching to experimental build but that didn't work.
My GPU drivers are up to date and i've also downloaded windows 10 updates just in case.
I tried switching from my hard drive to my SSD but that didn't work.

My CPU is cpu is i5-9600k 3.70ghz and does not have integrated graphics.
I have 16GB DDR4 RAM.

I tried going to settings, switching Vsync off and what not but doesn't work, I also tried turning to fullscreen and turning on windowless

**Comment by tsunamayo** [comment]
@milktyoon Hi, sorry to hear this. Lets fix that issue.
Could you try using the experimental branch to see if you still have the issue? Right click on the game in steam, then go to property, then Betas, then selected experimental. Wait for the game to download before launching it again. 
Thanks

**Comment by milktyoon** [comment]
@tsunamayo 

It unfortunately still crashed

**Comment by tsunamayo** [comment]
@milktyoon Do you have a desktop or laptop? If yes which brand / model?

**Comment by tsunamayo** [comment]
also could you please send me the content of the following folder:
C:/Users/kimminki/AppData/Local/Temp/Moonfire Entertainment/Starship EVO/Crashes

**Comment by milktyoon** [comment]
@tsunamayo I have a desktop

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6745088/Player.log)
[error.log](https://github.com/tsunamayo/Starship-EVO/files/6745089/error.log)

Also can't post the crash.dmp file on github cause it isn't supported(?)

**Comment by tsunamayo** [comment]
@milktyoon Yes, you will need to zip it! Thanks a lot

**Comment by milktyoon** [comment]
@tsunamayo ah okay, didn't know, here is the dmp file

[crash.zip](https://github.com/tsunamayo/Starship-EVO/files/6745403/crash.zip)

**Comment by tsunamayo** [comment]
@milktyoon It is linked to something with your NVidia drivers.

- Do you run some OC on your card (if so could you please deactivate it?)
- Could you do a clean install of nvidia drivers?
- Do you use Riva tuner?
- Could you exit all nvidia overlay (geforce experience, NVIDIA 3D Vision Driver)
- Is there anything specific running on your PC at the same time as the game?

Thanks

**Comment by milktyoon** [comment]
@tsunamayo Ah it fixed after a clean install of my nvidia drivers.
