### ISSUE TITLE
Paint related Bug Report

### ISSUE THREAD

**Issue by FluxenBoba** [tsunamayo/Starship-EVO#3911]
### Short Description of the issue:
Paint will not apply on some parts, or will only apply to parts at random (yet specific) distances and angels from the part.
...

### Steps to reproduce the issue:
just screw around with painting after building a ship of any size and it should happen
...

### Environment
- Starship EVO version: 21W24B
- Graphics Card: GTX 960M

### Additional information:
https://cdn.discordapp.com/attachments/271723356795961345/859893825958445066/unknown.png
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6743948/Player.log)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@FluxenBoba Hi, does the surface you are trying to paint has some decals over it? Thanks

**Comment by tsunamayo** [comment]
@FluxenBoba Also could you send me the blueprint?
