### ISSUE TITLE
Im stuck in space and cant spawn anything

### ISSUE THREAD

**Issue by Tuxedo155** [tsunamayo/Starship-EVO#3912]
### Short Description of the issue:
i was messing around with my spaceship above one of those halo ring things trying to build turrets then as i tried to move i was stuck but the line tools lines moved and the only thing that would move was my crosshair i looked  up and saw the outline of what i think was my ship and then i ended up stuck in a stuck in a star i used fast keys to get out but i cant place anything if  i place a starter block then try to build a ship it disappears and if i make a new game it just sticks me back in the star

...

### Steps to reproduce the issue:
im not sure

...

### Environment
- Starship EVO version: 
- Graphics Card: rx570

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![image](https://user-images.githubusercontent.com/86746712/124030624-feb02300-d9bb-11eb-8dcd-0638f45166ef.png)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
wont let me upload the file it says is not included in the list so maybe ill have to email it

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by Tuxedo155** [comment]
truth be told i could just install and reinstall the game

**Comment by tsunamayo** [comment]
@Tuxedo155 Hi, I would advocate starting a new character / wprld. You can import your blueprint in the new world. Thanks

**Comment by Tuxedo155** [comment]
so i did but it just did the same thing

**Comment by Tuxedo155** [comment]
alright thank you i restarted my computer and it works fine :)
