### ISSUE TITLE
Sequencer gates changing values randomly

### ISSUE THREAD

**Issue by JackBobS** [tsunamayo/Starship-EVO#3914]
### Short Description of the issue:
Sequencer gates will change the value of the number when exiting and opening a different sequencer gate. When returning to the original sequencer gate the value will have changed randomly to an extremely high or low number in the 10s of power.
...

### Steps to reproduce the issue:
Open game. Set up sequencer gate to piston, rotor, etc. Open second sequencer gate. Return to original sequencer gate. 
...

### Environment
- Starship EVO version: 21w24b and 21w26a 
- Graphics Card: Intel I7

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@JackBobS I cant reproduce this. Can you tell me if you can reproduce this right away after loading the game? Do you reproduce on a new minimal blueprint? Thanks

**Comment by tsunamayo** [comment]
@JackBobS also a player.log file would help to debug. Thanks

**Comment by milan-t** [comment]
Hello,
I think that problem has someting to do with ranges of connected actuators (mechanisms). I experienced issue when I was editing sequencer gate for 2 different type of rotary actuator in a row.

If I edit rotator sequencer and then hinge sequencer, hinge sequencer values get doubled. Then when I open setting for rotator again values are divided by 2. Also incorrect range is displayed. After opening settings of same sequencer gate again, now range is correct.

*Initial state*
![20210703204140_1](https://user-images.githubusercontent.com/65783423/124364062-5e6a3080-dc3f-11eb-84ee-e8e5e6b4e36b.jpg)

*Editing hinge sequencer after rototator sequencer*
![20210703204144_1](https://user-images.githubusercontent.com/65783423/124364065-61652100-dc3f-11eb-81fc-afa7e6d8b95a.jpg)

*Editing rotaror sequencer after hinge sequencer*
![20210703204150_1](https://user-images.githubusercontent.com/65783423/124364066-62964e00-dc3f-11eb-9635-664edad54a9c.jpg)

*Editing hinge sequencer...*
![20210703204242_1](https://user-images.githubusercontent.com/65783423/124364067-632ee480-dc3f-11eb-829b-ec7ef8b02c76.jpg)

*Editing hinge sequencer again*
![20210703204251_1](https://user-images.githubusercontent.com/65783423/124364068-64f8a800-dc3f-11eb-87e0-85c33eaf4047.jpg)

*Blueprint:*
[Sequencer range bug.zip](https://github.com/tsunamayo/Starship-EVO/files/6758894/Sequencer.range.bug.zip)

*Blueprint with all types of mechanisms*
[Sequencer gate bug all mechanisms.zip](https://github.com/tsunamayo/Starship-EVO/files/6758936/Sequencer.gate.bug.all.mechanisms.zip)

Unwanted recalculation of values occures also when editing sequencer gate for piston or sliding rail.

Kind of workaround is to have dummy actuators (hinge, rotator, ...) with sequencer gate connected.
So when you need to edit sequencer values for different type of actuator, open first dummy sequencer gate of desired actuators type.

**Comment by tsunamayo** [comment]
@milan-t Great investigation - thanks a lot for this! @JackBobS Issue fixed for 21w27b. Thanks all!
