### ISSUE TITLE
Infinite Handheld beam

### ISSUE THREAD

**Issue by KiloTheNeko** [tsunamayo/Starship-EVO#3915]
### Short Description of the issue:

When placed on a pedestal the beam weapon fires for an indefinite amount of time 

### Steps to reproduce the issue:

1. make a simple beam weapon with the reactor as the first block

2. surround it with some blocks and slap on a beam weapon at the end im not sure if the amount of attachments matters but
2 overheat addons , 2 charge

3. fire it at least once without connecting the beam to the handle

4. connect the handle and beam it should start firing indefinitely if not repeat steps 1 to 4

### Environment
- Starship EVO version: 21w07a
- Graphics Card:  RTX 2070 super

### Additional information:

https://cdn.discordapp.com/attachments/271723356795961345/860169243198750730/20210701164331_1.jpg
 ^ example of the infinite beam cannon
Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6749070/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.
[New Entity.zip](https://github.com/tsunamayo/Starship-EVO/files/6749095/New.Entity.zip)

**Comment by tsunamayo** [comment]
Hi, I can no longer reproduce that issue. Thanks
