### ISSUE TITLE
[Bug] Prefab Menu does not show prefab metadata

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3916]
### Short Description of the issue:
The box on the right does not show the prefab name or description data that you input when saving the prefab
![image](https://user-images.githubusercontent.com/27857711/124148666-c249f900-da87-11eb-9deb-2645d4a84adf.png)

This feature is _excellent_ btw, you've done a brilliant job!

### Steps to reproduce the issue:
- Save a prefab
- Look for it in the prefab tab of the codex and check for name/description/grid size/offset data

### Environment
- Starship EVO version: 21w26a
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
@ProPeach I know it was marked on my to-do list in the patch notes ;) Yep I am sure you guys will like it, but I wonder if I have just opened the gate of oblivion... Anyway this will be important to give some standard docking port / turret and landing gear for newcomer.

**Comment by ProPeach** [comment]
Ah my bad, I'm usually pretty good at that 😅
I suppose only time will tell! Copy paste has been around for a long while and it hasn't increased level of detail by itself a lot, but this patch has made it easier... I'm sure it'll be fine :D
