### ISSUE TITLE
No Holes Holes

### ISSUE THREAD

**Issue by KiloTheNeko** [tsunamayo/Starship-EVO#3918]
### Short Description of the issue:

Well... whenever a beam or laser pierces a thing in the newest 21w24a
 it doesn't show any changes on the pierced object.-. It … just... allows the beam to pass

### Steps to reproduce the issue:

point any beam or laser weapon at a ship or station until you stop hearing impact noises
and check if the beam comes out the other side

### Environment
- Starship EVO version: 21w24a
- Graphics Card:  RTX 2070 super

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6749283/Player.log)

**Comment by tsunamayo** [comment]
@KiloTheNeko Hi, Could you send a screenshot? There is no damage decal at all?

**Comment by KiloTheNeko** [comment]
Precisely it Tsuna no damage decal but everything functions as normal

**Comment by KiloTheNeko** [comment]
![20210701032820_1](https://user-images.githubusercontent.com/65069111/124212710-babe3a80-daef-11eb-89f5-8ca71395e5fd.jpg)

Here I include a screenie of this peculiar phenomenon

**Comment by tsunamayo** [comment]
@KiloTheNeko Thanks a lot, issue is now fixed for 21w27b. Cheers
