### ISSUE TITLE
[BUG] OR gates can cause issues in circuits 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3919]
### Short Description of the issue:
my ABBA gates work fine until i trigger them with an OR gate 
...

### Steps to reproduce the issue:
spawn in included BP and follow along with the video 
...

### Environment
- Starship EVO version: 21w26a

### Additional information:

https://user-images.githubusercontent.com/56371294/124150960-e9cca180-da46-11eb-9df4-0d95271f825f.mp4

[V'Zeer - Guppy Class.zip](https://github.com/tsunamayo/Starship-EVO/files/6749321/V.Zeer.-.Guppy.Class.zip)

**Comment by TIKIRobo** [comment]
#3921 is a better example as to why this is actually happening

**Comment by tsunamayo** [comment]
@TIKIRobo Issue fixed in 21w26b. Thanks
