### ISSUE TITLE
[Question] Logic across future docked entities 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3920]
if docking ports are added I'm wondering if we could use them to make semi modular ships that we could switch out the turrets on by just undocking and docking things to the ship or if when in an escape pod we could press a button that would trigger doors opening on the main ship. 

You could also use some sort of short range transmitter but im not sure if that entirely possible in the game currently

**Comment by tsunamayo** [comment]
@TIKIRobo Yes it is planned, we already had a dev asks about this a while back. Thanks
