### ISSUE TITLE
[BUG] Logic gates cannot send direct signals to other logic gates

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#3921]
### Short Description of the issue:
Logic gates are unable to directly send a signal to another logic gate, they can however be linked when interfaced by a timer. 
...

### Steps to reproduce the issue:
Spawn the attached blueprint
Observe logic behavior in the demonstration
...

### Environment
- Starship EVO version: 21w26a
- Graphics Card: RTX 3080

### Additional information:
_(Screenshots, Videos, Error logs, Related issues)_
log-

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6750626/Player.log)

bp-
[logic gate problem.zip](https://github.com/tsunamayo/Starship-EVO/files/6750627/logic.gate.problem.zip)

**Comment by TwoNiner29** [comment]
I'm here because nuclearlemon threatened me at gunpoint to bump this, but yes logic broken

**Comment by pinesh** [comment]
> 
> 
> I'm here because nuclearlemon threatened me at gunpoint to bump this, but yes logic broken

And I'll do it again >;)

**Comment by tsunamayo** [comment]
@pinesh Hi, issue fixed for 21w26b. Thanks ;)
