### ISSUE TITLE
[CRASH] Prefab causing Crash after reloading

### ISSUE THREAD

**Issue by BinHawkins42** [tsunamayo/Starship-EVO#3923]
My game crashes every time I try to load a save with a prefab in it. 

try pasting a prefab down and then reload the game and the game will crash when loading. I have tried this with multiple characters and tried resetting my universe. 

this can be anywhere in the game. just place a prefab and reload the game. 
- Starship EVO version: 21w26a
- Graphics Card: Nvidia GeForce GTX 1060 6gb

I have a screen shot of the earror message that pops up right before it crashes. 

![crash bug](https://user-images.githubusercontent.com/36099433/124200528-30e48200-da9b-11eb-849a-3207dc463a03.JPG)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6751266/Player.log)

I also found this if this helps

[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/6751284/Player-prev.log)

I hope this can be resolved soon as I would love to make a video of this awesome new update as soon as posable. this feature must be shown to the world.

**Comment by Garrett-C** [comment]
I too had this issue in post #3917. I assumed it was to do with overlapping with existing blocks but maybe not.

**Comment by tsunamayo** [comment]
@BinHawkins42 Hi, could you send me your blueprint?

**Comment by BinHawkins42** [comment]
[hallway prefab blueprints.zip](https://github.com/tsunamayo/Starship-EVO/files/6752217/hallway.prefab.blueprints.zip)
[the omega prebuild.zip](https://github.com/tsunamayo/Starship-EVO/files/6752227/the.omega.prebuild.zip)

the top zip is the prefabs and the bottom zip is the blue print of the ship that had the copied objects on it.

**Comment by tsunamayo** [comment]
@BinHawkins42 I cant reproduce the issue, it load fine over here. Maybe that one of the previous fixes, if not and you still reproduce in 21w26b, then reopen the case! Cheers
