### ISSUE TITLE
[BUG] sequencers can only hook into one block 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3925]
21w26b

https://user-images.githubusercontent.com/56371294/124299781-ac354a80-db12-11eb-8382-e247c44a31a7.mp4

**Comment by TIKIRobo** [comment]
https://user-images.githubusercontent.com/56371294/124302798-7d20d800-db16-11eb-92b6-7743919d6748.mp4

this appears to be true for all blocks

**Comment by tsunamayo** [comment]
@TIKIRobo  so I have fixed the issue and repushed the build. Sorry for the mishap!
