### ISSUE TITLE
[Bug] Audio seems louder than it used to [21w06b]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#3927]
### Short Description of the issue:
The audio in the current version seems louder than it used to. I have my system volume at 20%, and the game's volume at 20%, and it still feels a little too loud.

### Environment
- Starship EVO version: 21w06b
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6756450/Player.log)

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Hi, so I think it was linked to #3934. So it should be fixed for 21w27a. Thanks!
