### ISSUE TITLE
[Bug] Selected resolution is not saved

### ISSUE THREAD

**Issue by mxdanger** [tsunamayo/Starship-EVO#3928]
### Short Description of the issue:

Users with screen resolutions above 1920x1080 are unable to save the selected resolution persistently. IE: opening the graphics setting menu after the resolution has been set will reset the dropdown to the smallest resolution, resulting in that lowest resolution being used. Resolution does not appear to be saved in `SETTINGS.ini`.

### Steps to reproduce the issue:

1. From the menu open the settings menu
2. Open the graphics settings (at this point the resolution dropdown has been reset to the lowest option)
3. Set the Screen Resolution dropdown to any option
4. Close the graphics settings menu (resolution has been applied but does not appear save)
5. Open the graphics settings again (resolution dropdown will once again be set to the lowest option)

### Environment
- Starship EVO version: 21w07a
- Graphics Card: GTX 1660 Ti (Drivers: 471.11)

### Additional information:

Video demonstrating the issues:

https://user-images.githubusercontent.com/32040254/124333060-069cce00-db48-11eb-952a-db4c8e71124b.mp4

**Comment by daOyster** [comment]
I can confirm that I also experience this behavior. For me it loads the right resolution up on game start, but whenever I go into the graphics menu it always defaults to selecting a lower resolution and then if I don't change it back before closing the menu, it changes my resolution to the smaller one. I've got a 2560 x 1440 @ 144hz monitor. I don't experience this behavior if I run the game using my smaller 1920 x 1080 @ 60hz monitor.

**Comment by tsunamayo** [comment]
@daOyster @mxdanger Okay so I would say it is might be more linked to the high refresh rate. What is your refresh rate @mxdanger ? Also do always use Borderless mode? Thanks

**Comment by mxdanger** [comment]
> What is your refresh rate @mxdanger ? Also do always use Borderless mode? Thanks

My refresh rate is 164Hz and yes, I'm using borderless mode.

**Comment by tsunamayo** [comment]
@mxdanger This should be fixed in 21w27a. If it is not the case please ping me! (My monitor is 60hz, so I cant really test this...)
