### ISSUE TITLE
[Crash] Same crash when launching world as in #3917

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Starship-EVO#3929]
### Short Description of the issue:

Sorry if you already saw my update on this, just couldn't reopen it so I wanted to make a new report linking back to it to be sure.

Basically the bug/crash I reported in #3917 is still happening. I have updated what seems to cause it. 

### Steps to reproduce the issue:

1. Place prefab with child entities overlapping blocks.
2. Game no longer lets you place or delete blocks
3. Restart the game
4. Launch the previous character
5. World opens for a second then crash popup appears
6. Game crashes and closes.

### Environment
- Starship EVO version: 21w26b
- Graphics Card: RTX3070

### Additional information:

Also here is the player log from the time of the crash and a world having the issue. Hopefully, I uploaded it right this time. 
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6757648/Player.log)
[Testing123.zip](https://github.com/tsunamayo/Starship-EVO/files/6757649/Testing123.zip)

**Comment by tsunamayo** [comment]
@Garrett-C Hi, I can load your save fine. I had repushed a build early in the week-end, could you retry, you maybe had the first build... Thanks

**Comment by Garrett-C** [comment]
Hi,

Yeah no worries I will try it again tomorrow and get back to you on it.

**Comment by tsunamayo** [comment]
@Garrett-C Also I dont have any kind of issue when pasting overlap prefab, so if you could send me a test case (like send me the prefab you use, there might have something to do with this) Cheers

**Comment by Garrett-C** [comment]
@tsunamayo 

Ok so did some testing.

So, you are correct the world crashing bug seems to be fixed. 

There does still seem to be an issue with placing prefabs that overlap. It seems to half work as part of the prefab is deleted when overlapping however the game then prevents you from placing or deleting blocks. 

Here is the log file created and the prefab I was using. 
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6763900/Player.log)
[Venator door 2.zip](https://github.com/tsunamayo/Starship-EVO/files/6763901/Venator.door.2.zip)

**Comment by tsunamayo** [comment]
@Garrett-C Okay issue fixed for 21w27a. Thanks a lot ;)
