### ISSUE TITLE
[Experimental] Copy/paste tool breaks, prevents building after large paste fails

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#3930]
### Short Description of the issue:
When pasting a large selection (not a prefab), the paste fails and nothing is produced. Also, while the paste tool can be reset, any new copy is unable to be pasted, and does not show a preview for pasting. Breaking bricks is defunct after this.

### Steps to reproduce the issue:
1. Copy large selection (1000+ bricks)
2. Paste the selection
3. Clear the tool selection
4. Re-select anything of any size using the tool
5. Attempt to paste selection
6. Attempt to place and break bricks

### Environment
- Starship EVO version: 21w06b
- Graphics Card: Nvidia GeForce GTX 1060 6gb

### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6758158/Player.log)

**Comment by tsunamayo** [comment]
@Majikmonster Hi, I am not sure it linked to the number of bricks copied, but more with actually was inside. Could you please send me a blueprint file and show me what you tried to copy? There was some command / mechanism inside, what where they?  Thanks

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo I'm having a similar problem, but with a smaller prefab (663 blocks) and when trying to paste the prefab along a symmetry plane. You can do it yourself by placing down a symmetry plane and trying to mirror basically any turret from the Workshop.

![image](https://user-images.githubusercontent.com/63756057/124596340-107d4480-de5a-11eb-888d-6baa2fed3149.png)

**Comment by tsunamayo** [comment]
@Majikmonster @Kaiser-Indrasil Okay thanks, it was linked to turret and symmetry. It is all fixed for 21w27a. Cheers
