### ISSUE TITLE
Issues placing yoke on piston or rail

### ISSUE THREAD

**Issue by Sekiberius** [tsunamayo/Starship-EVO#3931]
### Short Description of the issue: When placing a yoke on a rail or piston it doesn't control the ship from the direction you place it. 
Example: placing a yoke facing forwards on a rail facing horizontally-upwards against the ship, the yoke controlled the ship from the right.

...

### Steps to reproduce the issue: Place a yoke on a piston or rail, I didn't test it on a rotor.

...

### Environment
- Starship EVO version: 21w24a
- Graphics Card: RTX 3080

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by ProPeach** [comment]
Are you still able to link the yoke on the rail directly to the ship computer? That's supposed to be impossible as far as I know.

What you can do is link the yoke on the rail to another yoke on the base entity of the ship, then link that yoke to the ship core

**Comment by Sekiberius** [comment]
yes I can, I linked the yoke on the rail directly onto the shup computer, I did it about a year ago on a turret design with a turret computer and it worked fine.

**Comment by Uncle-Ulty** [comment]
Well, ProPeach already answered, but every build requires the **main yoke** to be placed on the **main entity**, the main body, connected to the computer.
 You can place a second yoke on a rail/hinge/piston whatever and connect this yoke to the main yoke. 
 
 This happens cuz the main yoke defines the forward and up directions of the build.

**Comment by tsunamayo** [comment]
@Sekiberius Hi, thanks for booking the case. So Propeach and Uncle-Ulty are right, you were not supposed to do this, it was a bug. You have to link a yoke from the  main frame, then you can link a secondary yoke to the first one! Fixed for 21w27a. Thanks!
