### ISSUE TITLE
[BUG] Very odd crash after load

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#3933]
### Short Description of the issue:
This has happened twice now; the game loads where I left off, with my character still at the helm. Then after a few seconds I get chucked out of the helm and told the ship is overheating (which is not actually correct). The game then returns to the loading screen and stays there, seemingly indefinitely.

The first time this happened, I quit and re-loaded, but my world was completely empty, with zero entities or ringworld.

This second time I saved the player log file from the principle crash before re-loading the game; which again had stripped all the world content. Hopefully that will be of some use to you. 

Also note that I have previously had some problems with this "ship" (messy old geometry model that I keep changing) where it will occasionally claim to overheat to 200% or more for no reason. I know it's a false warning as a ship respawn or world reload both "fix" the problem, with the ship stats returning to what I assume is normal. Sometime the warning is power and sometimes it's overheat.

Also started a new world and the starter ships claim to overheat too.

Maybe these are two different problems or maybe they are related.

### Steps to reproduce the issue:
Load game with player at helm.

### Environment
- Starship EVO version: "21w06b" (It's the latest experimental which I think should be 21w26b)
- Graphics Card: GTX1070

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/6760135/output_log.txt)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6760136/Player.log)

**Comment by tsunamayo** [comment]
@cloudrambler Hi, I cant reproduce that issue, could you send me the character save? Thanks

**Comment by cloudrambler** [comment]
@tsunamayo I'm not familiar with that file. Do you mean the .mpc file?

**Comment by Kaiser-Indrasil** [comment]
@cloudrambler He means the world folder which you should zip up and upload here.

**Comment by cloudrambler** [comment]
@tsunamayo Here is the character folder: [Squiggle.zip](https://github.com/tsunamayo/Starship-EVO/files/6793853/Squiggle.zip)
@Kaiser-Indrasil 07

**Comment by tsunamayo** [comment]
@cloudrambler Okay I can reproduce your issue, it is because your ship is dead (maybe inside a planet?) and your character somehow was not linked to a medbay (which is another issue). I keep you posted.
