### ISSUE TITLE
[Bug] Sound muted doesn't mute all sounds

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#3934]
I turned the sound to 0 in the options menu, but at random the sound of turning on/off the codex still comes though. So does turning on and off the mirror, though it doesn't happen 100% of the time. Additionally, the sound setting doesn't seem to change the volume of the codex on/off sound

**Comment by ProPeach** [comment]
Seems to be all of the codex SFX at least yeah, #3864 can be closed when this is fixed too

**Comment by tsunamayo** [comment]
Hi, issue is fixed for 21w27a. Thanks ;)
