### ISSUE TITLE
[BUG] Freezing player when entering hovercraft

### ISSUE THREAD

**Issue by zorozeenee** [tsunamayo/Starship-EVO#3935]
### Short Description of the issue:
Upon entering a hovercraft it will freeze the players view, they will still be able to access the escape menu

### Steps to reproduce the issue:
build hovercraft
get in

### Environment
- Starship EVO version: 21w06b
- Graphics Card: GTX 1060 Super

**Comment by tsunamayo** [comment]
@zorozeenee Hi, this issue is fixed in the current experimental version.
This will soon land in the default branch, we just need to fix the starting zone now.
Thanks!

**Comment by zorozeenee** [comment]
This was on the experimental when i reported it

**Comment by zorozeenee** [comment]
Just recreated the bug again on the current version, even when i load back into the game im stuck on the yoke
