### ISSUE TITLE
[BUG] Turret copy paste makes some pasted parts invisible

### ISSUE THREAD

**Issue by matejkar** [tsunamayo/Starship-EVO#3936]
### Short Description of the issue:
title
one thing to add is that I was copying some turrets on my ships, and now only the turrets seen in the screenshots are having issues.
I will link a ship with the most of those turrets below
[Impulse - class support cruiser.zip](https://github.com/tsunamayo/Starship-EVO/files/6770221/Impulse.-.class.support.cruiser.zip)

...

### Steps to reproduce the issue:
Find a turret, Copy it, and try to paste it
...

### Environment
- Starship EVO version: 21w06b
- Graphics Card: 1060ti 6GB

### Additional information:
![20210706150429_1](https://user-images.githubusercontent.com/69653738/124604926-b5544d80-de6b-11eb-81c3-1dd0100e15a8.jpg)
![20210706150436_1](https://user-images.githubusercontent.com/69653738/124604934-b5ece400-de6b-11eb-8c87-78be9dab63e4.jpg)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6770207/Player.log)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by matejkar** [comment]
![20210706151556_1](https://user-images.githubusercontent.com/69653738/124606358-1af50980-de6d-11eb-8d75-228f161189f5.jpg)
one restart later.. still happens, tho now not everything is invisible

**Comment by tsunamayo** [comment]
@matejkar Hi, this issue will be fixed for 21w27a. It was when you want to paste overlapping mechanism on the wedge slope - now it is handling that issue better.
Thanks!
