### ISSUE TITLE
[Bug] "No Entity Selected" + Crash To Desktop [21w06b]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#3938]
### Short Description of the issue:
Blueprint shows name as "No Entity Selected," and trying to edit the name sometimes causes a crash to desktop. Exporting it at this stage does not seem to work. The game has also created a phantom copy of the blueprint that has no name; the files for this phantom copy have been created directly in the Blueprints directory.

### Steps to reproduce the issue:
Load the blueprint, place something on it, then open the Codex and view the blueprint to see the name.

### Environment
- Starship EVO version: 21w06b
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
The CTD cannot be reproduced reliably. It sometimes happens, and sometimes doesn't. I haven't worked out precisely what affects it yet, but it seems to be temporarily fixed by messing around with a different blueprint for a while, so whatever causes it might be connected to that.

![20210706162309_1](https://user-images.githubusercontent.com/33041786/124668467-855e7780-de76-11eb-91a6-37505a9a2159.jpg)

Phantom blueprint:
![20210706162929_1](https://user-images.githubusercontent.com/33041786/124669117-7a581700-de77-11eb-9e00-227291bdd7f0.jpg)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6772881/Player.log)

[DLP Station Module - Joint 100m.zip](https://github.com/tsunamayo/Starship-EVO/files/6772887/DLP.Station.Module.-.Joint.100m.zip)

Files for phantom blueprint:
[Phantom Blueprint.zip](https://github.com/tsunamayo/Starship-EVO/files/6772923/Phantom.Blueprint.zip)

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Hi, so it is fixed for 21w27a. There will be a new Entity menu too btw. I hope you like the prefabs!
Those beefier modules are really cool, I think the size is working very well compared to the ships outside.
Regarding those antenna sticking out: with the future docking tech you will be able to randomize them if it is something you would like to try. You will specify an antenna tag, a max size, then the algo would spawn a random antenna at that place (of course the docking port will be much smaller).
Cheers
