### ISSUE TITLE
[BUG] Minor UI glitches

### ISSUE THREAD

**Issue by matejkar** [tsunamayo/Starship-EVO#3949]
### Short Description of the issue:
title,
for some reason some elements of the UI are bugged, and the panel which usually shows a ship's center of mass, forward, up etc. is now allways visible.
...

### Steps to reproduce the issue:
Create a new turret copy, and export it, there is a bizzare white color in its place, instead of the turret. 
...

### Environment
- Starship EVO version: 21w27a
- Graphics Card: 1060ti 6GB

### Additional information:
![20210707092430_1](https://user-images.githubusercontent.com/69653738/124717541-84c0f200-df05-11eb-85ad-e4eb7b54b54b.jpg)
![20210707092437_1](https://user-images.githubusercontent.com/69653738/124717545-85598880-df05-11eb-80f2-47bf54ee47c8.jpg)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6775183/Player.log)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by matejkar** [comment]
notice the info panel of a ship visible in the second screenshot, even tho no ship is selected

**Comment by tsunamayo** [comment]
@matejkar yep the ship showing was already fixed actually.

**Comment by matejkar** [comment]
alright

**Comment by matejkar** [comment]
@tsunamayo  I will add some more stuff to it, still UI related.
For some reason, the turret blueprint is not correct, even if it can be placed normally.
here are some screenshots of how the turrets are placed correctly 
![20210707095001_1](https://user-images.githubusercontent.com/69653738/124720988-ffd7d780-df08-11eb-9579-cb069e588d5f.jpg)
![20210707095010_1](https://user-images.githubusercontent.com/69653738/124720993-00706e00-df09-11eb-8abe-96b806ca39e2.jpg)
however, this is what it looks like when being placed
![20210707095021_1](https://user-images.githubusercontent.com/69653738/124721043-0cf4c680-df09-11eb-8ff8-e0d0221f80cf.jpg)
and in the menu it once again is missing the actual turret
![20210707095028_1](https://user-images.githubusercontent.com/69653738/124721258-3d3c6500-df09-11eb-9a4f-abc3e2a4a651.jpg)
but the same turret can be placed normally, as seen here 
![20210707095037_1](https://user-images.githubusercontent.com/69653738/124721284-44fc0980-df09-11eb-8a3e-c6348dd38053.jpg)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6775352/Player.log)
let me know if you want the turret blueprint as well

**Comment by Garrett-C** [comment]
Anothee UI one I noticed is that when you leave the f6 camera mode the codex seems to open but slightly smaller than usual.

**Comment by matejkar** [comment]
@tsunamayo alright imma send the turret file if you want to check it out yourself
[[test] Imperial L4R4 Quad heavy laser cannon.zip](https://github.com/tsunamayo/Starship-EVO/files/6776759/test.Imperial.L4R4.Quad.heavy.laser.cannon.zip)

**Comment by tsunamayo** [comment]
@matejkar I cant reproduce your issues. It appears they might be related to some issue you had at one point while playing with the copy/paste. Could you send me your world at the location where there is the turret to copy? Thanks

**Comment by matejkar** [comment]
@tsunamayo il'l try hold on

**Comment by matejkar** [comment]
@tsunamayo unfortunately i deleted that world, however i found a bug where for some reason the links saved on a turret appear red as if they dont work, even tho everything is connected.

![20210708092814_1](https://user-images.githubusercontent.com/69653738/124881074-3bd57000-dfcf-11eb-9e98-437ab66bb277.jpg)
 
the turret:
[Imperial L4R4 Octouple heavy laser cannon.zip](https://github.com/tsunamayo/Starship-EVO/files/6782506/Imperial.L4R4.Octouple.heavy.laser.cannon.zip)

at least the white icons for turrets are fixed now, and this turret pasted normally

**Comment by Kaiser-Indrasil** [comment]
It's a widely spread bug which @matejkar described above - the one with the elevation axis mechanism seeming unlinked from the Turret Computer, until you re-link it manually or restart the world.

**Comment by tsunamayo** [comment]
@matejkar @Kaiser-Indrasil Okay I will close that one then, as Kaiser booked a bug for the other one. Thanks
