### ISSUE TITLE
[Bug] New entity menu has ghost buttons

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3951]
### Short Description of the issue:
You can see the Share on Steam button on the new entity menu now bleeds through to the bricks tab in the Codex
![image](https://user-images.githubusercontent.com/27857711/124770077-ed25c880-df31-11eb-9c94-19b06e51d9fb.png)

### Steps to reproduce the issue:
So far as I know, just exporting a blueprint locally will cause this

### Environment
- Starship EVO version: 21w27a
- Graphics Card: RX580

### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6777588/Player.log)

**Comment by tsunamayo** [comment]
@ProPeach Fixed for 21w27b. Thanks
