### ISSUE TITLE
[Bug] Round Tiles have stretched texture

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3952]
### Short Description of the issue:
![image](https://user-images.githubusercontent.com/27857711/124783083-b0130380-df3c-11eb-997f-f35a7bb7a909.png)
The flat face of the Round Tile brick has a stretched texture

### Steps to reproduce the issue:
Look at this brick in the codex or on a build

### Environment
- Starship EVO version: 21w27a
- Graphics Card: RX 580

**Comment by Pawnp** [comment]
[Will be fixed in 21w27b](https://github.com/tsunamayo/Starship-EVO/issues/3891#issuecomment-875338216) explained by tsun in a duplicate issue

**Comment by ProPeach** [comment]
Ah nice one 👌
