### ISSUE TITLE
[Bug] Piston shafts are invisible when the base is out of frame

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3953]
### Short Description of the issue:
https://user-images.githubusercontent.com/27857711/124783745-3596b380-df3d-11eb-9183-3b71b0b0e5e6.mp4

### Steps to reproduce the issue:
- Extend a Piston
- Move the base in and out of frame and notice the disappearing shaft

### Environment
- Starship EVO version: 21w27a
- Graphics Card: RX580

**Comment by CurioInventorium** [comment]
I've encountered this as well. I raised it during one of the NeoVox updates before it went to experimental. Even did screenshots.

**Comment by tsunamayo** [comment]
Yes, this is not new though, it is because the culling is done on GPU and the data is not passed to the compute shader. I will fix this it looks a bit stupid. Cheers

**Comment by tsunamayo** [comment]
@ProPeach Hi, this is finally fixed for 21w49a. Cheers
