### ISSUE TITLE
[Bug] Exiting Camera Mode opens the codex

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3954]
### Short Description of the issue:
After hitting F6 to exit Camera Mode, you're presented with this screen -
![image](https://user-images.githubusercontent.com/27857711/124786173-6bd53280-df3f-11eb-96cc-7e8642797450.png)
The Share on Steam bug is part of #3951 
This won't go away unless you hit tab to open the codex

### Steps to reproduce the issue:
- Hit F6 to enter Camera Mode, then hit F6 again
- The bugged screen will appear, and you can hit tab to solve it

### Environment
- Starship EVO version: 21w27a
- Graphics Card: RX580

**Comment by tsunamayo** [comment]
@ProPeach Thanks indeed, fixed for 21w27b.
