### ISSUE TITLE
[Bug] Ship preview does not update

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3956]
### Short Description of the issue:
Thumbnail ship preview does not update to show deleted bricks

### Steps to reproduce the issue:
- Start a new entity and build an easily identifiable shape using two bricks or more
![image](https://user-images.githubusercontent.com/27857711/124798892-d12f2080-df4b-11eb-99de-77e4ec3ce9f7.png)
- Delete some bricks of the structure, and check the previews
![image](https://user-images.githubusercontent.com/27857711/124799000-f02db280-df4b-11eb-9fef-f1924074bf4d.png)
The small thumbnail preview does not update, but the large interactable one does

### Environment
- Starship EVO version: 21w27a
- Graphics Card: RX580

**Comment by tsunamayo** [comment]
@ProPeach Issue fixed for 21w27b. Thanks as always...
