### ISSUE TITLE
Turrets no longer track/work

### ISSUE THREAD

**Issue by Sekiberius** [tsunamayo/Starship-EVO#3962]
### Short Description of the issue: When setting turrets to 'Spaceship target' they no longer track, also when connecting a hotkey gate to a turrets weapons it makes the entire turret follow your cursor.

...

### Steps to reproduce the issue: ^

...

### Environment
- Starship EVO version: 21w 27a
- Graphics Card: RTX 3080

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6780715/Player.log)

**Comment by tsunamayo** [comment]
@Sekiberius Hi, I cant reproduce this issue - it track fine on my side. Are you sure you are tracking a Hostile NPC?

**Comment by Dreamseizer36b** [comment]
Yeah, i tested it today after restarting my computer and it works fine now, so idk what was causing the issue.

**Comment by matejkar** [comment]
I confirm that my tracking works

**Comment by Sekiberius** [comment]
Sorry for taking so long to reply, it fixed itself after restarting the game so idk what was causing it.
