### ISSUE TITLE
Block previews in the Codex retain the scale icon

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3973]
Version: 21w27b

I don't think this is necessary anymore ;)
We can finally bid adieu to an old friend:

![image](https://user-images.githubusercontent.com/63756057/124917884-44886f00-dfec-11eb-9917-e338e243bf1e.png)

**Comment by tsunamayo** [comment]
True...

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Removed for 21w28b. Cheers
