### ISSUE TITLE
[Bug] No gravity on the ringworld for grids

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3974]
### Short Description of the issue:
Grids with no starter block do not feel the affects of gravity 

### Steps to reproduce the issue:
- Spawn a new grid, or create one with a starter block
- Remove any starter blocks on the grid

### Environment
- Starship EVO version: 21w27b
- Graphics Card: RX580

### Additional information:
A hull cube does not fall, even without a starter block
![image](https://user-images.githubusercontent.com/27857711/124963540-dd80af80-e017-11eb-83bc-e084d0747d8e.png)

**Comment by tsunamayo** [comment]
@ProPeach Issue fixed for 21w29b. Thanks
