### ISSUE TITLE
[BUG] Freezing player when entering hovercraft

### ISSUE THREAD

**Issue by zorozeenee** [tsunamayo/Starship-EVO#3975]
Short Description of the issue:
Upon entering a hovercraft it will freeze the players view, they will still be able to access the escape menu. When you log back into the game you will be stuck at the same place you logged out, causing you to have to delete your entire world and start over.

Steps to reproduce the issue:
build hovercraft
get in

Environment
Starship EVO version: 21w27b
Graphics Card: GTX 1060 Super
Additional information:

This is on the current experimental version, i was told that it was fixed on that version it is not.

**Comment by tsunamayo** [comment]
@zorozeenee Hi, I cant reproduce that issue. Could you send me your hovercraft blueprint? Do you reproduce this with the pre-built one? Thanks

**Comment by zorozeenee** [comment]
Sure, here you go. Good luck!
[Arbalest.zip](https://github.com/tsunamayo/Starship-EVO/files/6792067/Arbalest.zip)

**Comment by zorozeenee** [comment]
Also just a note it happens with all vehicles so really doesnt matter

**Comment by tsunamayo** [comment]
@zorozeenee I cant reproduce, it is working fine on my side. Can you send me the error.log like said when you open a case? 
Also what do you mean freeze view? You cant control the hovercraft?
Thanks
