### ISSUE TITLE
[Bug] Laser sensor does not detect vehicles [21w27b]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#3976]
### Short Description of the issue:
The laser sensor cannot detect when its path is interrupted by a vehicle.

### Steps to reproduce the issue:
Place laser sensor and link it to something (like an indicator light). Then move a vehicle into its path. Even at the default range, it will not detect the vehicle.

### Environment
- Starship EVO version: 21w27b
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
![20210708180011_1](https://user-images.githubusercontent.com/33041786/125000600-5979f800-e016-11eb-99a2-604e041006a6.jpg)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6787705/Player.log)

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin I dont think it ever worked, isnt it? Anyway with the new collisions tech I could have it work now.

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin So we finally have this working for 22w45a. Thanks
