### ISSUE TITLE
[Suggestion] Make the mirror apply to turret pasting

### ISSUE THREAD

**Issue by matejkar** [tsunamayo/Starship-EVO#3977]
### Short Description of the issue:
Currently, the mirror tool does not mirror the turret rotations on the other side
...

### Steps to reproduce the issue:
Place a mirror on an entity, and place a turret on one side
...

### Environment
- Starship EVO version: 21w27b
- Graphics Card: 1060ti 6GB

### Additional information:
![20210709163018_1](https://user-images.githubusercontent.com/69653738/125094122-48db8780-e0d3-11eb-86d4-fe3b7d9d1f7a.jpg)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6792088/Player.log)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by matejkar** [comment]
Interestingly enough, the actual turret is the only thing that was not mirrored, if you look at the "barbettes" of the turrets, you notice that those are mirrored properly

**Comment by tsunamayo** [comment]
@matejkar Yeah, it is because children entity are not mirrored. I am not sure how I am suppose to handle that it is quite complex if possible (as there are many case that dont line up), I would suggest to simply paste them with the prefab. I mean it takes 1 sec to paste a turret, right?

**Comment by matejkar** [comment]
Yea, i've managed without the proper mirror
