### ISSUE TITLE
Cross docking logic connections

### ISSUE THREAD

**Issue by NoxyNixie** [tsunamayo/Starship-EVO#398]
So far as I've tested there seems to be no way to have a logic connection go across a Docking Cone/Probe.

I'd like to request something that would allow me to send signals back and forth to docked craft.

My initial thought would be to make a transmitter logic tile in which you could enter a frequency (kinda like how you set the delay on a delay gate). If a docked entity has a receiver with the same frequency one could send signals through to it. If the docked entity separates the connection is then broken and further changes no longer transmit.

I'm not requesting wireless logic connections here, this is only an actual connection when the crafts are docked together.

**Comment by tsunamayo** [comment]
Yes for sure this is something needed as is wireless logic connection. I will check with a few builder and maybe do a post when I come to do that, just to see builder requirement. Cheers

**Comment by Crimix** [comment]
Any developments on this front?
