### ISSUE TITLE
[Bug] Copied girders can't be fully deleted

### ISSUE THREAD

**Issue by Womble-TC** [tsunamayo/Starship-EVO#3983]
If you copy and paste any of the girder pieces, then try and delete them, the lattice part of the block remains.

- Copy and paste a girder piece
- Place copied girder piece and try to delete it
- Part of the girder remains

![image](https://user-images.githubusercontent.com/29961381/125177693-cf788d80-e1d5-11eb-929a-0dfc01dd6546.png)
![image](https://user-images.githubusercontent.com/29961381/125177698-dd2e1300-e1d5-11eb-85bc-9e3525df3ef2.png)

- Starship EVO version: 21w17b
- Graphics Card:  RTX 3070 😎

**Comment by ZachZent** [comment]
Just want to add that resetting the game doesn't remove the bug nor does respawning the build.
![image](https://user-images.githubusercontent.com/36980446/125397970-87877100-e363-11eb-85bb-3dc9169c5fbe.png)

**Comment by tsunamayo** [comment]
@Womble-TC @ZachZent Issue fixed for 21w28b. Do you have a lot of blueprint like that? Could you send me one? Thanks

**Comment by tsunamayo** [comment]
Okay your save will load fine in the next update. Thanks

**Comment by ZachZent** [comment]
> 
> 
> Okay your save will load fine in the next update. Thanks


[Cool StationB.zip](https://github.com/tsunamayo/Starship-EVO/files/6813641/Cool.StationB.zip)
Not done yet and still have yet to make the attached station, but here it is
