### ISSUE TITLE
RGB gate game crash

### ISSUE THREAD

**Issue by Vetanenator** [tsunamayo/Starship-EVO#3984]
### Short Description of the issue:
Game crashes when using rgb gate ui for more than 10 seconds

### Steps to reproduce the issue:
1. Place rgb gate
2. Open rgb gate

### Environment
- Starship EVO version: experimental 21w26a
- Graphics Card: Radeon RX570

**Comment by BigBadKangaroo** [comment]
I tried to change the color setting from 0 /0 /0 to something else and then the game crashed ... for me it didn't crash after 10 sec's but RGB is still buggy

**Comment by Vetanenator** [comment]
It might be that when the rgb gate was connected to a glow part the game
crashes because the game crashes when I try to set the color of a glow
block.

**Comment by tsunamayo** [comment]
@Vetanenator finally the bug is fixed, for 21w28b. Thanks
