### ISSUE TITLE
Follow Up: Soundtrack

### ISSUE THREAD

**Issue by Jorpis-Jorah** [tsunamayo/Starship-EVO#3985]
Hello Again Everyone,

Last month I offered to compose the Soundtrack for Starship Evo, but was at the time caught in a Personal Crisis and couldn't continue. However, I am in the process of clearing things up while my offer still stands. I will create a full soundtrack for you, including ambient tracks, combat, and even lightcruise tracks. I have a few tracks ready on YouTube you can listen to [Right Here](https://www.youtube.com/watch?v=qEzjQ7-1hdY&t=95s) Oh, one last thing: I'll do it for free
Thanks!
-Jorah

**Comment by Gliese-832-c** [comment]
Wow, if this is legit you are awesome. Let's hope you manage to discuss this with Tsuna and make this happen!

**Comment by tsunamayo** [comment]
@Jorpis-Jorah Thanks for the offering, it is very kind of you. That music has an uplifting energy to it and is really cool - unfortunately I already have a plan and a composer for the game. It is still not in the game as we have to do a bit of work on the integration but should land in the near term.
Thanks!
