### ISSUE TITLE
[Bug] Starter and shipyard block have the same name/discription

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#3987]
![image](https://user-images.githubusercontent.com/36980446/125212683-fda4ae80-e263-11eb-946e-9a717aac0e19.png)
![image](https://user-images.githubusercontent.com/36980446/125212707-262ca880-e264-11eb-81e9-9d8ded9eb999.png)

Would it be possible to have the shipyard block have red and black stripes? Just to make it visually a little different besides the very small symbol

**Comment by tsunamayo** [comment]
@ZachZent Fixed. I wont bother changing the color as it will be removed when the new docking workflow is extended to station modules. Thanks
