### ISSUE TITLE
Ghost grids occur after using the zone delete tool and restarting the world

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3995]
Version: 21w28a

This is when happened when I tried to use the zone delete tool and reloaded the world, [and the Player.log file](https://github.com/tsunamayo/Starship-EVO/files/6810540/Player.log) which weighs 16 megs!

https://user-images.githubusercontent.com/63756057/125492203-d94faaf5-5aab-4a3b-88bb-a8cb2dc4b329.mp4

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil What do you mean reloading the world, was it after a quit to title or  quit to windows?

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo After a quit to title

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil I tested the quit to title it works fine as is. If it was after a delete I guess you deleted a children entity. If you still see the issue after the next patch please tell me!  Thanks
