### ISSUE TITLE
Box Delete Tool lacks de-select functionality

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3996]
Version: 21w28a

So far, we can only select zones for the Box Delete Tool, but we can't de-select them.
Maybe we could do this by selecting another position from the toolbar?

Also, it just stopped working for me the first time I used it, and after a few failed attempts I just restarted the world. Here's a [Player.log file](https://github.com/tsunamayo/Starship-EVO/files/6810567/Player.log) and a video showing the issue (might be the same one which caused the #3995 

https://user-images.githubusercontent.com/63756057/125493567-6e928efa-2177-4330-b54d-fe55f7f01f73.mp4

**Comment by tsunamayo** [comment]
Hi, There is a shitload of issues in that log, not sure it was the box delete at this point.

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo How do we de-select the areas selected by the Box Delete tool then?

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Indeed, just selected a box should be enough but it dont work. I was talking about not being sure all the error you got where linked to that, actually we had issue linked to the deletion of mechanism. I keep you posted.

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Fixed for 21w28b. Thanks
