### ISSUE TITLE
Game "freezes" and de-spawns the sub-module turret upon spawning aggressive AI

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3998]
Version: 21w28a

I've made a fresh-new turret and wanted to test if it's compatible with the sub-module spawning system.
It spawned but a second after I spawned an aggressive AI, the game froze in a way that would still render the fade-in and -out effect of the habitat's positional lights, but I could not move whatsoever, or do anything else for that matter.

[Here's the turret in question](https://github.com/tsunamayo/Starship-EVO/files/6812213/Light.Neutron.Blaster.zip)

[Here's a YT video showing the issue.](https://youtu.be/6SyI0Jr7nyI)

Also, here's a funny bug I encountered on re-joining the world
(and [a Player.log](https://github.com/tsunamayo/Starship-EVO/files/6812176/Player.log) containing at least some of the issues):

She started emitting her own light! 😄

![image](https://user-images.githubusercontent.com/63756057/125528915-2c9b545d-e644-451b-a560-3da510e71b2f.png)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil So I think this is again related to the children entity issue. I am pushing the fix asap! Cheers
