### ISSUE TITLE
Pirates are no longer targeted with automatic turrets

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3999]
Version: 21w28a

I think pirates became a little bit too docile in this patch. 😏 
I don't even have the "Peaceful pirates" option enabled.
My turrets are set to automatically attack targets I select, and, as you can see here, they are not doing that:

![image](https://user-images.githubusercontent.com/63756057/125532575-eed5ab3d-3176-4c09-84b9-3788622799e4.png)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil I cant reproduce the issue. A log file would be needed. Are you sure your game was not somehow broken? Thanks

**Comment by Kaiser-Indrasil** [comment]
It seems like my world was screwed after the update... What fixed the issue for me was, re-downloading the game and making a new world.

**Comment by SovietSponge** [comment]
Tried this too, starship target turrets really don't like the idea of targeting pirates.
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6813163/Player.log)
