### ISSUE TITLE
Teleport Menu no text

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#4012]
### Short Description of the issue:
The different options in the teleport menu don't show what they're called
...

### Environment
- Starship EVO version: 21w28b
- Graphics Card: GTX 970

### Additional information:
![20210714092608_1](https://user-images.githubusercontent.com/32974671/125639320-8f3b536e-b529-4ba0-b93a-5c6321adc7a1.jpg)

**Comment by tsunamayo** [comment]
@Xerma Indeed! No idea why it broke though, but it is fixed for 21w28c. Thanks
