### ISSUE TITLE
Turrets spawned by Docking Connectors disappear

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4013]
Version: 21w28b

I think you explained the issue before but I can't find it now, so just in case, here's a more concise report.
Looks like sub-modules which operate as turrets disappear shortly after being generated by the Docking Controller spawning mechanic.
The only thing physically remaining in game, is the top-most CE. In this case, the elevation section of the turret with the guns inside.
Parts of other CEs render as well but they seen to be ghost blocks.

![Starship_EVO_LQfq01VL50](https://user-images.githubusercontent.com/63756057/125641242-b402715d-62ba-4d25-92a0-1d9eba12426c.png)

[Here's the turret I used for this report](https://steamcommunity.com/sharedfiles/filedetails/?id=2546479834)

[And the player.log sourced after I returned to desktop](https://github.com/tsunamayo/Starship-EVO/files/6816873/Player.log)

Once I re-joined the world, the turret was completely gone.

[Here's the world file in case you want to test it](https://github.com/tsunamayo/Starship-EVO/files/6816900/Experimental.zip)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil So docking spawned entity are not supposed to be saved as part of the parent blueprint - that is a feature. Not sure what happened, I guess your entity is being saved as you worked on it. What are you trying to achieve?

**Comment by Kaiser-Indrasil** [comment]
I see - so they are only supposed to be saved with the automatically generated NPC stations, aren't they?
I wanted to test out if turrets could be spawned the same way as single-entity sub-modules, but it seems they can't.

**Comment by tsunamayo** [comment]
they should be able to be spawned though, I will check. NPCs are not saved in the game, they are regenerated at each load. I still need to work on having them spawn sub-modules. I could add some option if you want to bake them into your save.

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo For baking them into my save I'd personally use prefabs, although in survival making the docked entities carry over between game sessions might be needed.
