### ISSUE TITLE
[BUG] Ghost collisions stop mechanism from moving

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#4016]
### Short Description of the issue:
like the title says the issue i am having is much like the one in #3907 but way worse  
...

### Steps to reproduce the issue:
load up included BP and try and open the door, if it opens perfectly, restart your game and try again 
...

### Environment
- Starship EVO version: 21w28b
 

### Additional information:

https://user-images.githubusercontent.com/56371294/125679869-9993265c-fc55-4ea7-91cf-b503e4751e13.mp4

[HAB I.zip](https://github.com/tsunamayo/Starship-EVO/files/6818460/HAB.I.zip)

**Comment by tsunamayo** [comment]
@TIKIRobo Hi, it is not a bug, there is a wedge in the hinge axis that clip with your door - thats the culprit.
