### ISSUE TITLE
[Bug] Surface area changes after save-reload [21w28b]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#4039]
### Short Description of the issue:
The surface area for a ship changes after saving and reloading. The change can sometimes be quite large, and can change whether a ship's heat dissipation is adequate.

### Steps to reproduce the issue:
Load a ship, check the surface area stat, then save the game, quit and reload. Check the ship's surface area stat again.

### Environment
- Starship EVO version: 21w28b
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
Before save-reload:
![20210715105139_1](https://user-images.githubusercontent.com/33041786/125818800-fae95240-c26f-411f-85b0-809fda290df6.jpg)

After save-reload:
![20210715105223_1](https://user-images.githubusercontent.com/33041786/125818813-75efa484-5640-484a-adb1-f753f9109f55.jpg)

Before save-reload:
![20210715105740_1](https://user-images.githubusercontent.com/33041786/125819520-f7af074d-52f1-44df-9be1-23cec70bda48.jpg)

After save-reload:
![20210715105817_1](https://user-images.githubusercontent.com/33041786/125819531-3afd23e5-c116-4356-8d7c-c3e7108f053d.jpg)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6824569/Player.log)

**Comment by Dwarf-LordPangolin** [comment]
Note: this does not happen with every ship, nor does it always happen with the same ship. This makes it rather hard to pin down.

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Yes I also noticed that, it is rather elusive. It is linked to collisions point building, which needs a refactor using the new data oriented tech. Thanks

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Btw do you guys have slower FPS in latest version? I might have forgot to toggle burst jobs on...

**Comment by Dwarf-LordPangolin** [comment]
I haven't noticed slower FPS, though I haven't had my FPS counter on. I'll keep my eye on it, but everything seems very smooth.

**Comment by flori1994** [comment]
![20210717002647_1](https://user-images.githubusercontent.com/87566710/126033572-57cc4523-0eef-4f6b-a226-96e17ae63fc6.jpg)
Well, I had the surface area bug as well. As you can see in the picture the ship i spawned has a negative surface area.

**Comment by tsunamayo** [comment]
This was fixed some time ago. Thanks!
