### ISSUE TITLE
[Bug] Paste issue not mirroring and can no longer place after pasting

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Starship-EVO#4042]
### Short Description of the issue:

Attempted to paste a selection beside a mirror plane to try to mirror the copied region. Mirroring did not happen and I became unable to place blocks.

### Steps to reproduce the issue:

Copy region, place mirror plane, paste region. 

### Environment
- Starship EVO version: 21w28b
- Graphics Card: 3070

### Additional information:

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6831966/Player.log)
![image](https://user-images.githubusercontent.com/43644633/125976243-e1fbff2e-cdd0-4b7d-9d8b-06b824570b3c.png)

**Comment by tsunamayo** [comment]
@Garrett-C Hi, is it something you know how to reproduce again? If yes could you send me the blueprint and the way to do so? Otherwise it will be hard for me to investigate.
Especially I need to know what did the pasted region contained. 
thx

**Comment by Garrett-C** [comment]
> @Garrett-C Hi, is it something you know how to reproduce again? If yes could you send me the blueprint and the way to do so? Otherwise it will be hard for me to investigate.
> Especially I need to know what did the pasted region contained.
> thx

Good point. I will try and mess around with it today and see what's causing it. If I can get a region where it is easily reproducible I will send you a BP.

**Comment by Garrett-C** [comment]
Just wanted to point out I tried to replicate this but the issue did not occur a second time. Unfortunately this seems like one of those bugs that will be hard to reliably reproduce.

**Comment by tsunamayo** [comment]
@Garrett-C Okay weird think, if you ever see any issue please book another one with the blueprint. I had some issue with a previous selection so some bricks must still be a bit bugged... Thanks
