### ISSUE TITLE
Tsuna as requested

### ISSUE THREAD

**Issue by Arutus** [tsunamayo/Starship-EVO#4044]
Heres is the world save with the ship date hopefully in it
[ARUTU.-.Copy.zip](https://github.com/tsunamayo/Starship-EVO/files/6833063/ARUTU.-.Copy.zip)

**Comment by tsunamayo** [comment]
@Arutus Hi, sorry could you point me to the case related to refresh my mind? I follow a lot of case everyday, sorry I cant quite find it back...
Cheers

**Comment by tsunamayo** [comment]
[Blueprints.zip](https://github.com/tsunamayo/Starship-EVO/files/6859992/Blueprints.zip)
@Arutus @arutus109 Hi here are the file I can get back. I hope it will do... Thanks
