### ISSUE TITLE
[Bug] Paste duplication [21w28b]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#4045]
### Short Description of the issue:
Copy-pasting can result in overlapping duplicate bricks.

### Steps to reproduce the issue:
I was working on an area that had been mirrored from the other side of the creation, and noticed the lights were flickering. Checking it showed that the blocks in the area had become doubled at some point. The segments for the hallway were pasted on the original side, so it seems like either

1. the paste action can place two of each block sometimes, or
2. that I had turned off symmetry to delete the originals to change them and then repasted them with symmetry on again, and that the paste action did not properly check to see if those spaces were occupied.

### Environment
- Starship EVO version: 21w28b
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
https://gfycat.com/happygoluckysnivelingangelwingmussel

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6833124/Player.log)

**Comment by Dwarf-LordPangolin** [comment]
Update: this may be a broader symmetry bug than something related to copy-paste; I was making some doors without using copy-paste, and ended up with a double door. Not sure if it's related, but since it's another instance of duplicate blocks in the same space, I thought I'd mention it.

![20210716173325_1](https://user-images.githubusercontent.com/33041786/126014559-859fdf27-ed49-4963-9dc7-aa08ee4a0dc2.jpg)

**Comment by Dwarf-LordPangolin** [comment]
Update: this increasingly seems to be related to symmetry rather than copy-paste; whenever I have multiple planes of symmetry in use, this seems to happen.

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin okay thanks for the update.

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Issue fixed for 21w29b. Thanks a lot!
