### ISSUE TITLE
[BUG] Player Frozen when entering hovercraft (video demo attached)

### ISSUE THREAD

**Issue by zorozeenee** [tsunamayo/Starship-EVO#4046]
### Short Description of the issue:

Player freezes upon entering a hovercraft

### Steps to reproduce the issue:

Watch the video

### Environment
- Starship EVO version: 21w28b
- Graphics Card: GTX 1060 Super

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

https://www.youtube.com/watch?v=L4jQ68WHR8Q&ab_channel=SWINE

**Comment by tsunamayo** [comment]
@zorozeenee Hi, thanks for booking the bug and thanks for the video. As specified in the issue form could join the player.log and the blueprint so we can investigate that issue?
Thanks

**Comment by zorozeenee** [comment]
I gave you the blueprint already in my original report, but i dont think it matters since it happens on multiple vehicles
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6839554/Player.log)

**Comment by tsunamayo** [comment]
@zorozeenee Well I dont have issue with the two starting one... Can you reproduce with those two hovercraft... It seems linked to the turret isnt it? 
Also what original report? Sorry I have many issue to track, if you could simply give me the blueprint (or a link if it is a workshop thing) so I can investigate that would be cool
Thanks

**Comment by zorozeenee** [comment]
It cannot be the turret because even if a turret is stuck i can still use the f button to leave the yoke, but in this case i cannot
Not to mention the turret was working fine and has no collision issues
[MUV-1.zip](https://github.com/tsunamayo/Starship-EVO/files/6856225/MUV-1.zip)

**Comment by zorozeenee** [comment]
Btw if u need me to reproduce this for you live please dm me on discord SWINE#9554 and i can screenshare it to you

**Comment by tsunamayo** [comment]
@zorozeenee issue should be fixed for 21w31a. Thanks
