### ISSUE TITLE
Copy-Paste not reflecting across multiple mirror axes properly

### ISSUE THREAD

**Issue by JimStarluck** [tsunamayo/Starship-EVO#4048]
Was working on a construct using two axes of mirroring. Went to copy-paste an assembly, found it was only partially mirroring.

Placed the copy-paste in one corner. It mirrored horizontally, and it mirrored vertically, but it didn't mirror both vertically _and_ horizontally. It should have created four instances of the assembly, but only created three.

Placing a block without copy-paste worked fine; placed one block and ended up with four. Only copy-pasting seems to exhibit this behavior.

**Comment by tsunamayo** [comment]
Yes as it turn out my way of doing symmetry is not compatible with the way prefab works. I keep you posted.

**Comment by tsunamayo** [comment]
@JimStarluck Fixed for 21w29b. Thanks
