### ISSUE TITLE
Get locked in the pilot seat

### ISSUE THREAD

**Issue by guikaercher** [tsunamayo/Starship-EVO#4049]
### Short Description of the issue:

If you jump the chair of your starship and hold F to pilot and then hold F to sit you'll be forever locked.

### Steps to reproduce the issue:

Take the spaceship outside the base.
Jump over the chair and hold F for controlling it.
You cannot leave the ship anymore

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:
It's actually very simple

**Comment by tsunamayo** [comment]
@guikaercher Hi, I am not sure to understand the test case, what do you mean by jump over the chair?
Like do you see on the chair or not? If yes, before entering the ship or after? thx

**Comment by tsunamayo** [comment]
@guikaercher Also I will need to learn about the version you used and the player.log file. thanks!
