### ISSUE TITLE
Suggestion: Create Custom Star Systems

### ISSUE THREAD

**Issue by Jorpis-Jorah** [tsunamayo/Starship-EVO#4050]
Hey SEVO Community! I think you'll like this idea!
This amazing building game really stands out with its stretch tech building systems. A lot of other features are in this game that other games don't. I for one have a suggestion for something that I am certain will open eyes: Player Generated Star Systems! I have thought about it a lot and it could be done. Players could open the galaxy holomap and press a button that will start creating. You could choose where in the galaxy you want to put it, Once placed, you can start by choosing the star type, adding orbital bodies and moons and selecting it's orbital path.
This could take some time though, but it would sure make this game even more interesting!
-Jorah

**Comment by tsunamayo** [comment]
@Jorpis-Jorah Hi, it could be cool indeed for people who want to customize their galaxy. Realistically I am not likely to ever have time to work on this... Cheers
