### ISSUE TITLE
Suggestion: Light Cruise Logic Gate

### ISSUE THREAD

**Issue by LtDingus** [tsunamayo/Starship-EVO#4051]
Hello Tsuna,
I think that a really neat addition to the game could be a logic gate that is in an off state while flying a ship around like normal, but switches to an on state while the ship is in light cruise. This way ships could have animations for entering or dropping out of light cruise without any player input. Some examples include certain lights being turned on, turrets that retract during light cruise, antennas, wings, or other bits and bobs that fold up. Anyways, happy coding!
- P.S. Sorry if there's some sort of format I should be following for this.

**Comment by tsunamayo** [comment]
@LtDingus Yes a new "event" gate will be added that will achieve just that - so stay tuned. Thanks

**Comment by LtDingus** [comment]
Awesome, looking forwards to it!
