### ISSUE TITLE
[Bug] heat and power do not display when you spawn a ship

### ISSUE THREAD

**Issue by zorozeenee** [tsunamayo/Starship-EVO#4052]
### Short Description of the issue:

heat and power usage stats do not display when you first spawn in your ship, instead it reads 0% N/A

instead you have to restart your game to see it

### Steps to reproduce the issue:

spawn in ship
observe heat and power stats

### Environment
- Starship EVO version: 21w28b
- Graphics Card: GTX 1060 Super

**Comment by tsunamayo** [comment]
@zorozeenee Where are you looking at those stats?

**Comment by zorozeenee** [comment]
Bottom right of the screen

**Comment by tsunamayo** [comment]
Fixed for 21w31a. Thanks
