### ISSUE TITLE
unable to paint stickers

### ISSUE THREAD

**Issue by KINGrimson** [tsunamayo/Starship-EVO#4053]
### Short Description of the issue:
unable to paint stickers, 
...

### Steps to reproduce the issue:
dont know how to, 
...

### Environment
- Starship EVO version: 21w28b
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by Kaiser-Indrasil** [comment]
@KINGrimson I'm perfectly able to paint stickers on my end. Maybe it's a problem related to a borked save file, so try to repeat the process on a fresh save.
If the issue persists, I think screenshots, or ideally a video would massively help to pinpoint the issue.
Thanks!

**Comment by KINGrimson** [comment]
> @KINGrimson I'm perfectly able to paint stickers on my end. Maybe it's a problem related to a borked save file, so try to repeat the process on a fresh save.
> If the issue persists, I think screenshots, or ideally a video would massively help to pinpoint the issue.
> Thanks!

i would if i could, but i have the problem on any world, the world i am in now is only a week old and got it, made one yesterday and nothing cant paint them, ill try and get a vid but really i have no way on how to explain this one

**Comment by tsunamayo** [comment]
@KINGrimson okay I changed this for 21w29b. We now have a "Material Remove Paint" build option. As material are purely decorative for decals they will always remove the paint. Thanks

**Comment by Kaiser-Indrasil** [comment]
Funny things is, when you set a custom paint's RGB value to 0,0,0, it displays the specular steel material instead. It's such a cool feature, so please don't change it.
