### ISSUE TITLE
vehicle refuses to export locally

### ISSUE THREAD

**Issue by DELTACX10** [tsunamayo/Starship-EVO#4055]
### Short Description of the issue:

...the game will refuse to save/ locally export a vehicle

### Steps to reproduce the issue:

...unknown, i was just building my ship for a while and when i went to save i discovered it wouldnt let me.

### Environment
- Starship EVO version: newest experimental version as of 7/18/2021
- Graphics Card: and rx 550 2GB
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6836920/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/6836921/Player-prev.log)

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by SPECIALvaultguy** [comment]
I have the same issue with my ship. This problem is related with child entities.

**Comment by tsunamayo** [comment]
@DELTACX10 @SPECIALvaultguy Could you send me a blueprint so I can reproduce the issue? Do you get this with all blueprint, even a simple dummy one?

**Comment by SPECIALvaultguy** [comment]
> @DELTACX10 @SPECIALvaultguy Could you send me a blueprint so I can reproduce the issue? Do you get this with all blueprint, even a simple dummy one?

No, I have this problem with a specific build. When I try to put a single CE, it doesn't export. If I delete the entity, it can export again.

gonna send you the ship blueprint and the prefab that I'm trying to attach. I'm building this ship for the discord comp.

[new tanker 91.zip](https://github.com/tsunamayo/Starship-EVO/files/6839974/new.tanker.91.zip)
[Turbine outlet 02.zip](https://github.com/tsunamayo/Starship-EVO/files/6839989/Turbine.outlet.02.zip)

**Comment by tsunamayo** [comment]
@SPECIALvaultguy what prefab to attach? You did not mention this in the bug report...

**Comment by tsunamayo** [comment]
@DELTACX10 Okay it will be fine in 21w29b. Thanks

**Comment by SPECIALvaultguy** [comment]
> @SPECIALvaultguy what prefab to attach? You did not mention this in the bug report...

Cuz this problem occurs when I add any object with a child entity. I noticed this when I tried to add this prefab, so I began to investigate the problem. The prefab was ok on other objects, and the ship was exporting with no problems, but when I tried to put any objects with child entity on this ship, it didn't export correctly.
