### ISSUE TITLE
sequencer gate does not save negative numbers.

### ISSUE THREAD

**Issue by eageus** [tsunamayo/Starship-EVO#4056]
### Short Description of the issue:
idk if this is meant to be a thing but i cant do sertin things with hinges becouse the sequencer gate does not save negative numbers at all.
...

### Steps to reproduce the issue:
take a sequencer gate and try to put in a negative number. it does not work for me or a few other people. 
...

### Environment
- Starship EVO version: exparimental
- Graphics Card: gt 730
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6844067/Player.log)

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@eageus Hi, so hinger range of valid values is 0-180 deg, so no issue here. Thanks
