### ISSUE TITLE
[CRASH] docking controller +merge +changing module type 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#4058]
### Short Description of the issue:
after setting a docking port connecter gate to sub module the game froze up and crashed 
...

### Steps to reproduce the issue:
hook docking controller to 4 docking ports, set to merged, then switch the type to be sub module 
...

### Environment
- Starship EVO version: 21w29a

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6844839/Player.log)

**Comment by tsunamayo** [comment]
@TIKIRobo Fixed for 21w29b. Thanks!
