### ISSUE TITLE
[Bug] 21w29a - Multiple Bugs with Warping

### ISSUE THREAD

**Issue by zalexville** [tsunamayo/Starship-EVO#4061]
### Short Description of the issue:

Was doing a test flight of my ship (I'll attach the blueprint) when it never dropped out of warp. Then when it should have dropped out, a super bright light source appeared in my cockpit directly in front of my. I wen tinto 3rd person and saw that no planets or the star had spawned. I pulled up the starmap and it did read me in the system. I tested this by travelling to two different star systems on newly created worlds. 

The second time I tested this is just never moved my ship. I did not get screenshots of the issue the first time but I have ne of the second instance. 

### Steps to reproduce the issue:

Warp to another star system. 

### Environment
- Starship EVO version: 21w29a
- Graphics Card: Geforce GTX 1650 with Max-Q Design

Note: This is not my usual computer. This issue has ocurred with my laptop, but I am unable to also check on my desktop at home this week. 
### Additional information:

![20210720105855_1](https://user-images.githubusercontent.com/65626266/126347223-3bebd0f6-425e-4bfb-90a5-1ba1e76a9d52.jpg)

[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/6849270/Player-prev.log)

[BT-7 Thunderclap.zip](https://github.com/tsunamayo/Starship-EVO/files/6849310/BT-7.Thunderclap.zip)

**Comment by Jorpis-Jorah** [comment]
I have the same bug

**Comment by tsunamayo** [comment]
@zalexville fixed for 21w47b.
