### ISSUE TITLE
[Bug] Light sources do not retain their brightness values when re-entering the game

### ISSUE THREAD

**Issue by Pawnp** [tsunamayo/Starship-EVO#4062]
### Short Description of the issue:

Any light sources set to a specific brightness (through switches, sliders, and sequencer gates) do not retain it's last known value and reverts back to full brightness when re-entering the game.

### Steps to reproduce the issue:

Connect any light source with either a switch, slider, or sequencer gate; set the brightness to any value but full brightness; then rejoin the game and re-examine the light source.

### Environment
- Starship EVO version: 21w29a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

**Comment by tsunamayo** [comment]
Issue is fixed in recent update. thx
