### ISSUE TITLE
Gravity is whack, help

### ISSUE THREAD

**Issue by EndlessOats** [tsunamayo/Starship-EVO#4063]
### Short Description of the issue:
Gravity is really wonky when you try and place it in different directions, even if the fields aren't very near each other they can sometimes reverse or fall sideways or any number of random directions, usually they just default to the first one placed though, regardless of the fact that it's not touching the other field and is facing the complete opposite direction.

Also, just wanna say, absolutely amazing game, keep up the good work :)
...

### Steps to reproduce the issue:
Take two GU's and put them in opposite directions, only one will work. This comes in many variants and makes building large stations with multiple gravity points difficult.
...

### Environment
- Starship EVO version: 21w29a
- Graphics Card: NVIDIA GeForce GTX 1650 SUPER
...

### Additional information:
![20210720223940_1](https://user-images.githubusercontent.com/87742250/126423497-a3d44d6d-1f81-46de-8fb1-766d247a9356.jpg)
...

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6852468/Player.log)

**Comment by tsunamayo** [comment]
@EndlessOats Hi, thanks for booking the issue. Could you send me your blueprint so I am sure to reproduce? Thanks

**Comment by EndlessOats** [comment]
By all means, the gravity units are on opposite sides in the wall of the
main hallway, you enter through the doors on the bottom of the giant
shipyard in the center. The frame is very big, just a warning.

**Comment by tsunamayo** [comment]
@EndlessOats sorry for the late update, but I dont see any blueprint attached. Thanks
