### ISSUE TITLE
[BUG] custom colors act differently on some blocks 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#4065]
### Short Description of the issue:
When painting some blocks with a custom color the color will be different  
### Environment
- Starship EVO version: 21w29a

### Additional information:

https://user-images.githubusercontent.com/56371294/126509094-099600b8-8b71-4653-8d14-217ee972193a.mp4

[Colors.txt](https://github.com/tsunamayo/Starship-EVO/files/6856677/Colors.txt)
custom colors used^

**Comment by tsunamayo** [comment]
@TIKIRobo indeed, most command where a bit too dark. Fixed for 21w31a. Cheers
