### ISSUE TITLE
[BUG] Crash to destop when trying to delete block

### ISSUE THREAD

**Issue by flori1994** [tsunamayo/Starship-EVO#4066]
### Short Description of the issue
I experienced a bug where the game crashes when I click more than one time to delete a block.

### Steps to reproduce the issue:
Place a Block
delete the block by clicking twice
...

### Environment
- Starship EVO version: 21w29a
- Graphics Card: Intel HD 5500u

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
none needed, as the game just freezes and crashed a few seconds later
Please also include the `Player.log` file.
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6859040/Player.log)

**Comment by flori1994** [comment]
oops, the title was meant to be crash to desktop...

**Comment by tsunamayo** [comment]
@flori1994 sorry for the late answer. So it seems that the player.log is not the one from a session where the bug happened. Do you reproduce this often? Thanks

**Comment by flori1994** [comment]
It happens in stable de facto never.  But in experimental it happens every time when the game runs too slow. For me, it looks a little bit like that the player (=me) is clicking faster than the game can refresh which leads to a problem that I try to delete a block that has been already removed from the database of the ship.

**Comment by tsunamayo** [comment]
@flori1994
Have you tried F3 / Disable NPCs? It might improve FPS. 
In any case issue is you should not play with such a GFX card below recommended config. What is your CPU / memory?
