### ISSUE TITLE
[BUG] Interstellar Travel Never Arriving

### ISSUE THREAD

**Issue by Jorpis-Jorah** [tsunamayo/Starship-EVO#4069]
Short Description of the issue:
When Warping to another system, it will do so normally, it will move out of the current system, and does load into the new system, but once it has loaded, it will not move, and will stay stuck in deep space with a warp effect around the ship.
Possible things that could have caused this:
-There could be something wrong with the game's code, like a missing script.
-This bug does not appear in the 21w7a build but will have affect in the experimental build, so there might be something 
How to reproduce this problem:
-Spawn any blueprint
-Warp to a system (Any ly range)
interfering or overriding the code

### Environment
- Starship EVO version: 21w30a
- Graphics Card: Nvidia 770

Additional information:
As for the requested player log, as of the writing of this, I do not have time to go fetch it, I will bring it to you another time.
Cheers!

**Comment by tsunamayo** [comment]
@Jorpis-Jorah fixed for 21w47b.
