### ISSUE TITLE
[BUG] Game soft-locks upon entering yoke.

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#4070]
### Short Description of the issue:

Upon using the yoke of a particular blueprint,. the game locks up, preventing the character from leaving the yoke, or controlling the ship. Attempting to reload the game does not release the character and thus the world becomes unuseable. 
...

### Steps to reproduce the issue:

Start fresh world, 
Spawn attached BP,
Attempt to fly it. 

_If the game does not lock up, leave it, save it, and respawn from that save._
...

### Environment
- Starship EVO version: 21w29b
- Graphics Card: RTX 3080

### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6871306/Player.log)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/6871308/output_log.txt)
[Epsilon IX.zip](https://github.com/tsunamayo/Starship-EVO/files/6871312/Epsilon.IX.zip)
[breakme.zip](https://github.com/tsunamayo/Starship-EVO/files/6871314/breakme.zip)

_included is a copy of the "locked" character._

**Comment by Xenoprophet-Nail** [comment]
It seems from what I saw on the Discord, is there's a similar issue with hovercraft as well.

**Comment by tsunamayo** [comment]
@pinesh So I was not able to reproduce the issue but I have added a few safeguard in code that should prevent it. I guess it was a bit random... Fix for 21w31a.
Cheers
