### ISSUE TITLE
[BUG] All handheld blueprints not displayed in item stand, items dupe upon pressing f

### ISSUE THREAD

**Issue by zorozeenee** [tsunamayo/Starship-EVO#4073]
### Short Description of the issue:

Everytime i open the item stand to spawn a handheld all my blueprints are not displayed except for the first blueprint in the list (alphabetically)
then if i exit it and open it again it duplicates the first handheld
this continues duping everytime you open it

### Steps to reproduce the issue:
have a few handheld blueprints saved
place down an item stand
press f on it and wait for only the first one to appear
exit out and press f on it again

also once you spawn it in the handheld clips through the ground away from the item stand and you 

### Environment
- Starship EVO version:  21w29b
- Graphics Card: gtx 1060 super

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@zorozeenee issue fixed in recent updates. Thanks
