### ISSUE TITLE
[bug] docking to a shipyard makes ship move

### ISSUE THREAD

**Issue by KINGrimson** [tsunamayo/Starship-EVO#4080]
### Short Description of the issue:
when i want to enter a shipyard to dock to it my ship with the shipyard start moving down, i cant seem to fix the issue 
...

### Steps to reproduce the issue:
set up a shipyard on a ship and dock to it to see it move down
...

### Environment
- Starship EVO version: 21w30a
- Graphics Card: 

### Additional information:
![image](https://user-images.githubusercontent.com/74992043/127738662-6ad1e417-6586-4df4-90b8-fb71dfbdb7dc.png)
my setup, shipyard is on a child entities
_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@KINGrimson did you used a station computer and set the anchor at yes? Otherwise your ship will push against the landing pad... Thanks

**Comment by KINGrimson** [comment]
> @KINGrimson did you used a station computer and set the anchor at yes? Otherwise your ship will push against the landing pad... Thanks

no i didnt was on a ship and the shipyard was set to hover not landing pad

**Comment by tsunamayo** [comment]
@KINGrimson Okay as always if you can send me the blueprint... Thanks
