### ISSUE TITLE
window boarders stretching

### ISSUE THREAD

**Issue by Jackbeflippen** [tsunamayo/Starship-EVO#4081]
### Short Description of the issue:
window frames are stretching. also cant place window as the edge wants to clip through to the next block down from the "sill" I want to attach it too.
...

### Steps to reproduce the issue:
build a slanted window, put glass in it.  
...

### Environment
- Starship EVO version: 21w30a
- Graphics Card: GeForce GTX 1060 6gb

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![1](https://user-images.githubusercontent.com/77905434/127745354-e5d68cd6-4f7c-4178-a1b9-996647a41452.png)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6911435/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

[New WinRAR ZIP archive.zip](https://github.com/tsunamayo/Starship-EVO/files/6911429/New.WinRAR.ZIP.archive.zip)

You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Jackbeflippen Hi, issue is fixed for 22w04a. Thanks
