### ISSUE TITLE
BUG - Trouble with logic

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Starship-EVO#4082]
### Short Description of the issue:

Logic cant activate Laserweapon s
- Logicgate (AND, OR, etc) cant do ->savelock with AND-Condition for custom gattlings dont work
- timer can do
- Eventgate can do

### Steps to reproduce the issue:
Connect a button to a laser. Click it will fire. Now connect the Laser over a 1s-Timer to a second Laser.. Click both will fire. Now (first disconnect timer and Laser) connect the timer with a logicgate and the logicgate to the second laser. Only the first will fire.
Its permanent, tryed restart, create a new world etc.

### Environment
- Starship EVO version: 21W30a
[Log_File.zip](https://github.com/tsunamayo/Starship-EVO/files/6911799/Log_File.zip)

**Comment by tsunamayo** [comment]
@Battlepixel Hi, okay this test case is a bit confusing. Do I have to do all the working steps before in order to reproduce the issue? Or can I jump to the step that is not working?  In general to help me just mention the bare minimum I need to do for me to reproduce the case.
Thanks a lot!

**Comment by tsunamayo** [comment]
@Battlepixel also I am having some trouble to understand the wiring, could you please send me a screenshot or a blueprrint? Thanks

**Comment by Battlepixel** [comment]
![Starship EVO_2021_08_04_18_26_59_278](https://user-images.githubusercontent.com/43222403/128218834-5bd91083-3897-4154-9feb-69cd7c61a228.jpg)
![Starship EVO_2021_08_04_18_27_12_245](https://user-images.githubusercontent.com/43222403/128218851-23abb1a1-4cd4-423b-979c-4998733a1d2d.jpg)
![Starship EVO_2021_08_04_18_27_13_179](https://user-images.githubusercontent.com/43222403/128218867-d87afa05-6090-4b25-8ecc-fcbb856a5738.jpg)
![Starship EVO_2021_08_04_18_27_13_779](https://user-images.githubusercontent.com/43222403/128218881-897ee198-9bbd-4d9f-9cb0-dd29704245c2.jpg)
![Starship EVO_2021_08_04_18_27_25_379](https://user-images.githubusercontent.com/43222403/128218892-b297501f-d969-4f1c-b8c9-61ffe0019215.jpg)
![Starship EVO_2021_08_04_18_27_26_678](https://user-images.githubusercontent.com/43222403/128218907-cb5908cb-f323-4c85-8487-5d51f2a7c823.jpg)
![Starship EVO_2021_08_04_18_27_28_478](https://user-images.githubusercontent.com/43222403/128218918-8e946954-8d74-4178-83e1-d38fae2b1310.jpg)
![Starship EVO_2021_08_04_18_27_30_411](https://user-images.githubusercontent.com/43222403/128218932-17d2dcfa-83b2-411a-ab4f-0d2e0b5292a4.jpg)
Both simple logic-chains do not work, but they are the prerequisite to build a fuse, so that self-made gattlings interrupt the fire chain as soon as the turret computer stops firing (e.g. if it would shoot your own ship)

**Comment by tsunamayo** [comment]
@Battlepixel It is working now with the event gate, fix for 21w31a. You where not supposed to be allowed to link the laser directly to the delay gate, it was an issue. Also the the AND gate is not needed, you can remove it as it. Thanks
