### ISSUE TITLE
BUG Shields become permeable when gattlings are firing

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Starship-EVO#4084]
**Short Description of the issue:**

Shields become permeable as soon as logic-triggered lasers are firering.
(I need the self-made gattlings because the gattlingbarrels damage your own ship and are therefore useless. ->Lasersturrets with Rangebrarrels never hit the own ship. | In addition, Shots from gattlingabrarrels are visually not so nice because of the scattering, it looks more like someone is shooting around with a shotgun and not like a scifi-pointdefense)

Its permanent, tryed restart, create a new world etc.
**Steps to reproduce**

Spawn the Blueprint. Go inside. Spawn an enemy Corvette. Rotate the ship, so that the custom gattlings are firering. 
Although the shields hold, the ship takes damage where it is hit because some shots pass the shields and hit the hull directly. (Only if at the same moment the gattlings are firing)

The same blueprint dont take damage, if you turn of the turrets. And no, the Turrets dont hit the ships itself, i checked this.

Environment

Starship EVO version: 21W30a

[Rheinwehr Schlachtschiff vexp.zip](https://github.com/tsunamayo/Starship-EVO/files/6911810/Rheinwehr.Schlachtschiff.vexp.zip)

Log_File.zip

**Comment by tsunamayo** [comment]
@Battlepixel sorry mate again a few things are not clear. There is two ship in your test case: the gattling are on your ship, but then which shield are you talking, our ship or the other NPCs shield? Thanks

**Comment by Battlepixel** [comment]
Our ship with the custom gattlingturrets gets permeable shields, as long as the gattlings are firing.

**Comment by Battlepixel** [comment]
its fixed with the new patch
