### ISSUE TITLE
[BUG] Piston collision issues 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#4085]
### Short Description of the issue:
some of my pistons get stuck on nothing making it impossible to know if something is actually clipping or if its just being buggy 
...

### Steps to reproduce the issue:
use included bp and flick the switches as shown in video 
...

### Environment
- Starship EVO version: 21w30a
### Additional information:

https://user-images.githubusercontent.com/56371294/127754344-16d8c164-5f49-497e-8c91-02c60f888d14.mp4

[buggy pistons.zip](https://github.com/tsunamayo/Starship-EVO/files/6911928/buggy.pistons.zip)

**Comment by BigBadKangaroo** [comment]
Had the same issue. I was using pistons for a cargobay door and they suddenly stopped working. I had to restart the game and then it worked just fine.

**Comment by tsunamayo** [comment]
@TIKIRobo I think this is an issue you reported several time, as it seems to correct itself after a restart... thx

**Comment by TIKIRobo** [comment]
@tsunamayo this one hasn't been fixing itself after a restart which is why i made a new report, more specifically it may fix itself after a restart but if i edit anything on it (like what the piston is pushing) it breaks again and other times it doesn't fix itself at all

**Comment by tsunamayo** [comment]
@TIKIRobo okay I will have a look at it.

**Comment by tsunamayo** [comment]
@TIKIRobo Hi, I change a few things in recent version, do you still get this? Thanks
