### ISSUE TITLE
[BUG] Ship doesnt spawn

### ISSUE THREAD

**Issue by COMICLER** [tsunamayo/Starship-EVO#4086]
my ship doesnt spawn like normal when i spawn it it just generates a random station part every time left a zip of my ship if that helps
[Jack of most trades.zip](https://github.com/tsunamayo/Starship-EVO/files/6912009/Jack.of.most.trades.zip)

**Comment by tsunamayo** [comment]
@COMICLER indeed I can reproduce this. I keep you posted, thanks

**Comment by tsunamayo** [comment]
@COMICLER actually for a start your save file must have been corrupted as it is 0kb in size. 
Did you had any issue during an export? Thanks

**Comment by tsunamayo** [comment]
@COMICLER yes sorry there is nothing I cant do as it, I can try to restore your blueprint from your character save if you had no recent backup... Thanks

**Comment by COMICLER** [comment]
my ship got deleted when i left the game ill send over the save tho to see if theyres anything you can you

**Comment by tsunamayo** [comment]
@COMICLER Dont hesitate to send the save if you want me to do something...

**Comment by COMICLER** [comment]
[Jack of most trades.zip](https://github.com/tsunamayo/Starship-EVO/files/7035101/Jack.of.most.trades.zip)

**Comment by tsunamayo** [comment]
@COMICLER I am sorry I cant find the relevant blueprint unfortunately.
My trick only work if you have spawned / unspawned your blueprint in the past, it consist in looking into the folder 
Starship EVO\Save_Data\Characters\Jack of most trades\PlayerEntities
to find file with the right size. Then copy them in the blueprint folder and you can load it (if you want to try).
In latest patch I have introduced some safeguard so save corruption cant happen.
Thanks a sorry for the mishap...
