### ISSUE TITLE
[BUG] crash when activating piston

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#4089]
### Short Description of the issue:
my game kinda froze when activating a switch that was hooked to a piston, for whatever reason the fps counter was still working fine but i couldn't move and all i heard was the sound of a switch going crazy 
...

### Steps to reproduce the issue:
no clue, i highly doubt this is repeatable  
...

### Environment
- Starship EVO version: 21w30a

### Additional information:

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6913039/Player.log)

**Comment by TIKIRobo** [comment]
[TIKI-NEOVOXTWO.zip](https://github.com/tsunamayo/Starship-EVO/files/6913117/TIKI-NEOVOXTWO.zip)

![](https://cdn.discordapp.com/attachments/416013956331601930/871429994956595280/unknown.png)
this also caused my ship to vanish, it looked something like this, i tried looking for it in the files but i couldn't find it, maybe you'll have better luck

**Comment by tsunamayo** [comment]
@TIKIRobo it seems you deleted stacked children entity at one point. Do you confirm you did something like this? Aka remove a piston with another piston on top and so on several time. Thanks

**Comment by TIKIRobo** [comment]
@tsunamayo yes I did, the doors on the ship used two pistons per door and I deleted them a few times iirc

**Comment by tsunamayo** [comment]
@TIKIRobo  okay thanks mate, issue fixed for 21w31a. Cheers
