### ISSUE TITLE
Exporting Prefabs locally doesn't produce image thumbnails

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4091]
Version: 21w30a

Like the title says.
This is how the prefab directory looks like in this version:

![image](https://user-images.githubusercontent.com/63756057/127937040-d9caaf44-91ef-47fe-97f5-3991bb8c3f85.png)

This is how it's supposed to look:

![image](https://user-images.githubusercontent.com/63756057/127937057-cec10f93-5afc-4184-9c43-1eb87ca9d411.png)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil issue fixed for 21w31a. Thanks mate!
