### ISSUE TITLE
wheel physics optimization question. 

### ISSUE THREAD

**Issue by sed-and-awk** [tsunamayo/Starship-EVO#4096]
I was wondering how you plan to optimize the wheels once you add them. In space engineers (a similar game), wheels are one of the laggiest parts because they constantly calculate physics with the ground, even when they aren't moving. Do you plan on having a high sleep threshold? or is there some other optimization?

**Comment by tsunamayo** [comment]
@sed-and-awk I am not too worried about that as I have done some massive refactoring recently to the collision framework. There is a sleep state to my current physics implementation. Thanks

**Comment by sed-and-awk** [comment]
Thanks for answering!
