### ISSUE TITLE
[BUG] RBG gate's off color changed after restart 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#4100]
### Short Description of the issue:
on a build of mine I am using a RGB gate to have a sort of emergency light, when everything is normal it's green but then i can turn the RGB gate on and it'll turn red, but after a restart the normally bright green is now dull and dark   
...

### Steps to reproduce the issue:
load up included BP, Follow vid to find light and RGB gate, if it is a nice light green like shown in the first vid then restart  
...

### Environment
- Starship EVO version: 21w30a
### Additional information:
Before:

https://user-images.githubusercontent.com/56371294/128522570-5b808186-b6ce-40e3-9634-0636bf656ba5.mp4

After + Walkthrough:

https://user-images.githubusercontent.com/56371294/128523325-09460377-eb95-4965-b381-a092266416db.mp4

[Large WIP city tech.zip](https://github.com/tsunamayo/Starship-EVO/files/6946057/Large.WIP.city.tech.zip)

**Comment by tsunamayo** [comment]
@TIKIRobo Issue fixed for 21w34a. Thanks!
