### ISSUE TITLE
Request For Starship EVO

### ISSUE THREAD

**Issue by Arutus** [tsunamayo/Starship-EVO#4101]
Hello Tsuna if possible can we get a zoom control function for third person flight because as of right now while flying large ships the camera zooms out to much during movement and boosting, And also if possible a speed slider for rail blocks would be great for train/tram systems in large bases or ships.

(to reiterate I do not mean the look around zoom which is controllable, I mean the fight mode in which the camera is locked behind the ship in third person, I would like you to be able to set the zoom distance in that mode.)

**Comment by Jorpis-Jorah** [comment]
I think a zoom feature would be good in general, like star citizen
