### ISSUE TITLE
[bug] blueprint weirdness (have no better way to explain)

### ISSUE THREAD

**Issue by KINGrimson** [tsunamayo/Starship-EVO#4106]
### Short Description of the issue:
was buidling a small fighter, and the game got a bit weird when wiring some logic up, so i decided to leave the world and rejoin it, once i got in my fighter was gone and in its place was a station module, i though nothingof it so i deleded it, then went to spawn in a new one, then to  my surprice i got a station module again, didnt delete it, and went to spawn a new one, again station module, decided to leave to desktop and make a report

### Steps to reproduce the issue:

i have no idea how this even happend, 

### Environment
- Starship EVO version: 21w30a
- Graphics Card: 

### Additional information:

![image](https://user-images.githubusercontent.com/74992043/128736500-48fbc0e4-8606-470d-8921-b593a01dd6b2.png)

blueprint of the ship in question 
[triangle figher.zip](https://github.com/tsunamayo/Starship-EVO/files/6955777/triangle.figher.zip)

the worldfile if it helps
[dorito.zip](https://github.com/tsunamayo/Starship-EVO/files/6955780/dorito.zip)

and the log ofcours
[Uploading Player.log…]()

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by Battlepixel** [comment]
I can confirm, I had this bug several times, but I didnt know how to reproduce it.

**Comment by tsunamayo** [comment]
@KINGrimson  it is a blueprint corruption problem unfortunately... Your .sevo is 0kb... Do you remember when did that happened? Thanks

**Comment by tsunamayo** [comment]
@KINGrimson @Battlepixel So we have a anti-corruption system in the latest build. It does not fix the real issue, which is an exporting issue, but make sure you dont loose any save if it happens. When it happens could you send me your log and blueprint in a new case so I can fix the real save issue?
Thanks
