### ISSUE TITLE
When loading the new build, I try to join previous worlds or create new worlds and I am stuck on the home screen for is now 10 minutes

### ISSUE THREAD

**Issue by thatisjake** [tsunamayo/Starship-EVO#4108]
### Short Description of the issue:

Loading into a new world or loading into an old world will make me stuck in the loading screen.

### Steps to reproduce the issue:

Load into or generate a new world.

### Environment
- Starship EVO version: Experimental 21w32a
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6962092/Player.log)

**Comment by shirowkhan** [comment]
To add, this happens to me after i have to kill the game client with an alt+F4

**Comment by KINGrimson** [comment]
i have the porblem too, old or new world i cant load in, keeps being stuck at the loading screen

**Comment by zorozeenee** [comment]
Same problem here

**Comment by zorozeenee** [comment]
games busted

**Comment by PFSCommissar** [comment]
I have also experienced this issue after updating to 21w32a

**Comment by tsunamayo** [comment]
@thatisjake  Okay I have repushed the build with the fix... Sorry to all of you, the game was off for nearly a day...
