### ISSUE TITLE
EXPERIMENTAL] 21w29b: Hotfixes is broken

### ISSUE THREAD

**Issue by Reason147** [tsunamayo/Starship-EVO#4109]
### Short Description of the issue:

.....The game is not loading in after charter selection, waited 20mins even made a new charter. EXPERIMENTAL] 21w29b: Hotfixes is broken

### Steps to reproduce the issue:

...Log in like normal 

### Environment
- Starship EVO version: EXPERIMENTAL] 21w29b: Hotfixes

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Reason147  Okay I have repushed the build with the fix... Sorry to all of you, the game was off for nearly a day...
