### ISSUE TITLE
Sudden consistent lag

### ISSUE THREAD

**Issue by CarsonBecket** [tsunamayo/Starship-EVO#4113]
### Short Description of the issue:
whenever I interact with my larger builds my game drops to 0 fps and freezes for 1-5 seconds. This has only started in the last 2 days since the issue where experimental couldn't be loaded.
...

### Steps to reproduce the issue:
Interact with any of my larger builds in my world
...

### Environment
- Starship EVO version: 21w32a
- Graphics Card: RTX 2070s

### Additional information:
I do understand my builds are large, but some are brand new and of them are weeks to months old, and I have never had any lag with them until 2 days ago. I have tried new worlds, reinstalls, and this issue is still occurring with my large builds even on fresh worlds where they are the only entities loaded. 

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6980863/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

[Issue world.zip](https://github.com/tsunamayo/Starship-EVO/files/6980866/Issue.world.zip)

**Comment by Battlepixel** [comment]
I also experience lag, when spawning npcs corvettes and destroyers <100m. I didnt had this lag before. CPU usage <20%, GPU-usage 40-50% doesnt changes but the fps are dropping down to >10

**Comment by ExodistSKY1** [comment]
I am experiencing the lag when deleting blocks from a very large ship while mirrored

**Comment by tsunamayo** [comment]
@CarsonBecket this should be fixed for 21w33a. I am pushing the build very soon. Thanks
