### ISSUE TITLE
[BUG] Handhelds broken

### ISSUE THREAD

**Issue by zorozeenee** [tsunamayo/Starship-EVO#4117]
### Short Description of the issue:

Handheld menu on item stand menu broken
Only the first handheld blueprint is listed (first alphabetically)
Then when you open it again it will list the same weapon.

In addition once spawned the weapon will be far away from the itemstand visually but the physical blocks will be at the proper spot but are inviisible.

### Steps to reproduce the issue:

Place down item stand
Open item stand menu
Close it
Open it again
Repeat

### Environment
- Starship EVO version: 21w32a
- Graphics Card: gtx 1060 super

**Comment by Jorpis-Jorah** [comment]
Yep...got a simple problem too

**Comment by tsunamayo** [comment]
Hi, issue is fixed in recent builds. Thanks
