### ISSUE TITLE
event gate block and icon invisible

### ISSUE THREAD

**Issue by KINGrimson** [tsunamayo/Starship-EVO#4119]
### Short Description of the issue:

tital sais it all

### Steps to reproduce the issue:
place a event block
...

### Environment
- Starship EVO version: 21W33a
- Graphics Card: 

### Additional information:
![image](https://user-images.githubusercontent.com/74992043/129697681-e601f378-1ddb-4a0c-8890-08151a2d2aba.png)
![image](https://user-images.githubusercontent.com/74992043/129697708-902d6816-87aa-416a-92f4-3adff4614147.png)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6998599/Player.log)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@KINGrimson was it fine on the update before? Thanks

**Comment by KINGrimson** [comment]
> @KINGrimson was it fine on the update before? Thanks

yes before this update it was fine, its with 33a it became invisible

**Comment by TIKIRobo** [comment]
yeap, im noticing this as well

**Comment by PFSCommissar** [comment]
same here. it was fine before the present update

**Comment by tsunamayo** [comment]
Fixed for 21w33b. Thanks
