### ISSUE TITLE
Starting Building Disappears 

### ISSUE THREAD

**Issue by ExtantDragoon38** [tsunamayo/Starship-EVO#4127]
### Short Description of the issue:
When going thought the start tutorial, tying to place anything the base goes invisible. 
...

### Steps to reproduce the issue:
Just do the start. 
...

### Environment
- Starship EVO version: 
- 
![image](https://user-images.githubusercontent.com/89212118/130105902-b2279c24-41c6-46a5-b5a3-30f6549094ef.png)

- Graphics Card: Radeon RX580

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

was running in window mode 

![image](https://user-images.githubusercontent.com/89212118/130105932-b920c70b-a18c-492a-a687-57fa4c33400e.png)

Please also include the `Player.log` file. You can find the log file here: `[Player.zip](https://github.com/tsunamayo/Starship-EVO/files/7016041/Player.zip)`

[Player (2).zip](https://github.com/tsunamayo/Starship-EVO/files/7016077/Player.2.zip)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`[Player.zip](https://github.com/tsunamayo/Starship-EVO/files/7016041/Player.zip)Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@ExtantDragoon38 Hi, did you a quit to title before experiencing the bug? Thanks

**Comment by ExtantDragoon38** [comment]
> @ExtantDragoon38 Hi, did you a quit to title before experiencing the bug? Thanks

So what happened the first time I played right after I downloaded it.

I got to the decals section in the tutorial, right click deletes blocks. 
I accidentally deleted the floor of this section and fell through to the grass. 

After flying back up I quit to the main menu , deleted the game and the started a new one. 

I went straight back to the decal section and as soon as i started placing blocks or decals in he tutorial area the above issue happened. 

I did find that if i quite to Main menu and load back in, the building is completely back again. until i try and place something, which as you can image makes doing the tutorial a little difficult.

I hope his extra information helps you.

**Comment by tsunamayo** [comment]
@ExtantDragoon38 Really sorry for the lack of update I missed your answer. If you install the latest experimental version do you get the issue? Thanks
