### ISSUE TITLE
World randomly deleted

### ISSUE THREAD

**Issue by thatisjake** [tsunamayo/Starship-EVO#4131]
### Short Description of the issue:
Loaded up Sevo today, ready to join the world I have been building on and the world isn't there. I always save my stuff so I just made a new world, although if I didn't, it would have sucked.
### Steps to reproduce the issue:

1.Load up sevo
2.*bug*
3.no more sevo world

### Environment
- Starship EVO version: 21w33c
- Graphics Card: 

### Additional information:
World File wasn't deleted
[House.zip](https://github.com/tsunamayo/Starship-EVO/files/7025722/House.zip)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7025723/Player.log)

**Comment by tsunamayo** [comment]
@thatisjake I can load your save fine, I see a massive Deadknot ship in front of me. Not sure what I am supposed to reproduce...
What do you mean by bug - no more sevo world? Does the screen finish loading? Can you see the character / world in the menu after exiting the game? There is no error in the log file as far as I can tell. thx
