### ISSUE TITLE
[BUG] Logic connections not always copied properly 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#4132]
### Short Description of the issue:
when copying large amounts of logic not all connections are saved 
...

### Steps to reproduce the issue:
copy and paste a large amount of interconnected logic 
...

### Environment
- Starship EVO version: 21w33c
### Additional information:

https://user-images.githubusercontent.com/56371294/130330019-b4e44b7a-677e-450f-82d6-2819d54595f4.mp4

logic i used
https://steamcommunity.com/sharedfiles/filedetails/?id=2507469223

**Comment by tsunamayo** [comment]
@TIKIRobo Thanks, issue fixed for 21w34a. Cheers
