### ISSUE TITLE
[BUG] Entity Spawns Invisible and Despawns on Restart 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#4139]
### Short Description of the issue:
When restarting my game i noticed that my work area had despawned, when i spawned in a new version it was all invisible except for some child entities and the glow of the lights i then restarted but this time it just wasn't there 
...

### Steps to reproduce the issue:
load up included world and try and spawn in included bp

...

### Environment
- Starship EVO version: 21w33c

### Additional information:
[TIKI-NEOVOXTWO.zip](https://github.com/tsunamayo/Starship-EVO/files/7072637/TIKI-NEOVOXTWO.zip)
[Large WIP city tech.zip](https://github.com/tsunamayo/Starship-EVO/files/7072638/Large.WIP.city.tech.zip)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7072642/Player.log)

**Comment by tsunamayo** [comment]
@TIKIRobo I can spawn this bp with no issue, I fixed an issue with children entity recently so I think it should be good for next patch. Thanks
