### ISSUE TITLE
[Bug] Fuel Drains in a fraction of a second, Reactor pulses at negative energy stored

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4141]
### Short Description of the issue:
Retrofitted the Mistral to test out fuel, and it doesn't seem to be flowing freely from the tanks to the reactors. I also can't pilot it reliably, but I might be misunderstanding your new system

### Steps to reproduce the issue:
- Load attached Mistral BP
- Refill tanks, check auto-refill is off
- Check tanks are full
- Use the link tool on the reactor, and see power stored at 0%. This value will jump up to around 40% every 5 seconds then quickly drain back to 0%.
- Power stored will be a negative number

As an aside, the rate of fuel consumed seems much too high for a good balance. The Mistral BP attached has two large tanks (roughly 11,000 litres), and can only provide fuel for ~160 seconds at 70 litres a second usage. Personally, I'd say that should be more like 40 minutes of fuel before you have to refuel, maybe even more considering the low power usage of the Mistral. It depends on a lot of things, like the how quickly/how often you can refuel at a star or visit a station

Also, a more exact measure of how satisfied a reactor is in terms of fuel flow would be really useful. The "Piping Flow Sufficient" coloured marker is great, but a % indicator that colours green at 100% would be even better. Something like "Piping Flow 40%" etc

Great first implementation! With some balancing this could be perfect

### Environment
- Starship EVO version: 21w34a
- Graphics Card: RX580

### Additional information:
[Mistral - Fuel Test.zip](https://github.com/tsunamayo/Starship-EVO/files/7077283/Mistral.-.Fuel.Test.zip)

Video of the bug, notice the Power Level and Power Stored stat in the Reactor
https://user-images.githubusercontent.com/27857711/131352759-ebd36daa-06c2-434a-8743-65ffc079a97d.mp4

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7077288/Player.log)

**Comment by tsunamayo** [comment]
@ProPeach I am looking into it. Regarding the piping, you have to look into: Reactor Fuel Consumption, and Fuel Max Flow. Name are not optimum but I have to find a name that also make sense for pipe (as it displays the same info for pipe and reactor)

**Comment by tsunamayo** [comment]
@ProPeach btw I have an issue with making those bricks pipe: they rescale on the horizontal axis, thats is not compatible with the tech. I will have to make duplicate version that are true pipe...

**Comment by ProPeach** [comment]
> @ProPeach btw I have an issue with making those bricks pipe: they rescale on the horizontal axis, thats is not compatible with the tech. I will have to make duplicate version that are true pipe...

Ah darn, sorry to hear that one is causing issues :(
I guess duplicates are the best way to go about it if one piece can't fulfil both functions

**Comment by tsunamayo** [comment]
@ProPeach okay I fixed a bunch of bugs regarding pipe link broken and fuel consumption - so now things dont have such a fast drain. I will push an update soon. I will close this, we will do other post on balance. Btw the mistral seems way too packed with lightcruise thruster, so that one is gonna break again once lightcruise will require fuel... 
Cheers
