### ISSUE TITLE
[Suggestion] Consolidate all functional pipes in the codex

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4143]
In the Codex the Pipe subsection tells us which pipes can be used to move fuel around, but there are some pipes that are not in this category that still function as pipes.

![image](https://user-images.githubusercontent.com/27857711/131358313-e0892ae8-8650-43e5-b3c1-3304eea049b3.png)
These three pipes are in the Construction category, which is confusing as they're also functional pipes. I've met a few people who didn't know they could use these pipes which are essential for their different lengths.

I suggest moving these three pipes into the Pipe category to make it more clear they can be used as actual pipes.

--------------------------------------------------------------------------------------------------------------------------------------------

Also in regards to mixing pipes of separate diameters, will this count as a valid method to scale down a pipe? The player might want to do this when routing one large pipe into separate engines etc
![image](https://user-images.githubusercontent.com/27857711/131358954-a0d84c65-ef9a-4087-87eb-f61274daedb6.png)

Another option is to use the Cone piece. This is smoother looking, but a bit of a pain as you have to use the Placement Subgrid option in the F1 menu. If you wanted to go for this, I'd suggest enabling the player to place a pipe in the centre of it without using the subgrid option
![image](https://user-images.githubusercontent.com/27857711/131359179-d0e4a790-a33f-491e-b4c0-84735f14ae72.png)

**Comment by tsunamayo** [comment]
@ProPeach yes indeed I will move them around. Btw I dont think they can carry fuel yet. The 6 way connector is not yet functionnal but will basically works as a tank, so it should works.
Indeed for the cone it make sense to have it work like you explained... It is a bit of a dev so not sure when we will have it (for the placement part).
Thanks
