### ISSUE TITLE
[Bug] Removal FX on tank are misplaced

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4144]
### Short Description of the issue:
The red sparks that appear when you remove a tank appear above the tank, not on it. The FX appear at the centre of a 1m scaled tank, so any tank above or below this scale has the FX placed wrongly

### Steps to reproduce the issue:
- Place a tank at a scale other than 1x
- Remove it

### Environment
- Starship EVO version: 21w34a
- Graphics Card: RX 580

### Additional information:

https://user-images.githubusercontent.com/27857711/131365491-a62623db-92e6-4e06-bd42-63119856b2c5.mp4

**Comment by tsunamayo** [comment]
This FX is crap btw, I need to update it...

**Comment by tsunamayo** [comment]
Issue fixed for 21w35a. Thanks
