### ISSUE TITLE
[Bug/Suggestion] New long distance glow is visible from *too* far away

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4145]
### Short Description of the issue:
I absolutely love the sprite lighting on glow/engine blocks, it adds so much character to larger builds.
However, the glow has a huuuuge render distance, so large that you can often see the glow much further away than you can the actual ship.

I think we could solve this by having the glow render distance scale with the size of the brick which emits it. You can hardly see a ship that uses 1/8x scale from 5km away, but you can easily see a ship that would likely use 4x scale thrusters from the same distance for example

Here, you can see a cloud of small fighters because of the glow from their thrusters
https://user-images.githubusercontent.com/27857711/131366445-6954d9da-92f4-4363-a0c0-724024ceea61.mp4

You can even see them from over here!
![image](https://user-images.githubusercontent.com/27857711/131366535-822d8bb5-29eb-472d-b564-4e7b691fa094.png)

It'd be super cool to be able to see ships from this distance if they were flying in Lightcruise mode, but as it is I think the glow is a little *too* powerful! :D

**Comment by ExodistSKY1** [comment]
I would like to see the glow effect scale with the size, and if possible not bleed through solid bricks. Rendering or just visually seeing a blob(not just the glow) from extreme distances is a must

**Comment by tsunamayo** [comment]
@ProPeach so it is supposed to be the feature, these are not thruster glow but ship "glow" - each ship will render a blob at long distance. It needs more work, right now the color is a grey, I wanted to use the color of the ship and also light the ship depending on the sun direction. But the whole goal of this is to be seen further away from the brick, as brick dont look good once their are subpixel. thx

**Comment by ProPeach** [comment]
Oh never mind then, that sounds brilliant! Looking forward to seeing that progress further

**Comment by ExodistSKY1** [comment]
agreed!
