### ISSUE TITLE
Random Encounters with megastructures?

### ISSUE THREAD

**Issue by Jorpis-Jorah** [tsunamayo/Starship-EVO#4149]
Hello, I created a big alien structure, and it is absolutely massive! I placed it above a planet and it about a quarter of the size, it was cool. It gave me an idea that could be put in the game. Random Encounters with alien structures, it could be a part of survival, a part of a story.
I have the blueprint here if you're interseted
https://steamcommunity.com/sharedfiles/filedetails/?id=2580366280&searchtext=

**Comment by tsunamayo** [comment]
@Jorpis-Jorah yeah ultimately I want to replace the torus with player made structures... But having "alien" mysterious object is a great idea, I will definitely gonna consider it. 
Thanks
