### ISSUE TITLE
[BUG] all grandchild entities gone 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#4150]
### Short Description of the issue:
all of the grandchild entities have disappeared from my bp 
...

### Steps to reproduce the issue:
no clue but it happened when spawning my bp from #4139  in a new world  
...

### Environment
- Starship EVO version: 21w34a

### Additional information:

![image](https://user-images.githubusercontent.com/56371294/131591943-a1f7ea8f-6ada-43fb-b87c-c01c6ab33a36.png)

**Comment by tsunamayo** [comment]
@TIKIRobo Weird it seems like a save issue - do you have any backup? What is the story behind those, where they prefab copy, or maybe submodule?

**Comment by TIKIRobo** [comment]
Unfortunately idk if i have a back up (maybe there might be something in the world file?) and they were prefab type things for a colony i was working on

**Comment by tsunamayo** [comment]
@TIKIRobo to confirm  I mean did you used the prefab feature to paste them on? I am trying to understand what led to this issue, if I can reproduce it then I can fix it.

**Comment by TIKIRobo** [comment]
I didn't save any of the bits as prefabs and i copy pasted them on but that was a long time ago

**Comment by tsunamayo** [comment]
@TIKIRobo it was a long time ago, and did you continued to work on that build after that? Or did you just picked up again recently?

**Comment by TIKIRobo** [comment]
I've been working on it for i want to say the last two months but it has been a bit on and off

**Comment by TIKIRobo** [comment]
@tsunamayo after going thru the bp a bit more it also seems like all of my text screens that were on child entities have lost their text as well as the logic on my CEs have lost their connections. It also seems like some of my normal child entities also disappeared
