### ISSUE TITLE
[Bug] Submodules with lights not spawning on connectors [21w35a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#4152]
### Short Description of the issue:
Submodules with lights on them will not spawn from the docking connectors.

### Steps to reproduce the issue:
Make a blueprint as a submodule that has a light on it. Then try to spawn the submodule on a docking connector.

### Environment
- Starship EVO version: 21w35a
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7087781/Player.log)

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Hi, I have spawned several sub-modules in my test a few days ago, could you send me your blueprint? You are sure that your Tag and hitbox is fine? If there is a collision then it wont spawn the sub-module.

**Comment by Dwarf-LordPangolin** [comment]
Here you go; sorry it took me so long, we've started up homeschooling again for the year! Only the submodule without lights will spawn; since there's no other difference between them as far as I can tell, it seems to be the light.

[Submodule Light Bug.zip](https://github.com/tsunamayo/Starship-EVO/files/7148342/Submodule.Light.Bug.zip)

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin sorry mate I will have a look into this now...

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Okay issue finally fixed for 21w40a! Thanks
