### ISSUE TITLE
[Crash] Game crashes eventually with time

### ISSUE THREAD

**Issue by chacalik** [tsunamayo/Starship-EVO#4155]
### Short Description of the issue:
Playing for a while, the game simply crashes.

### Steps to reproduce the issue:
Just play the game for a while.

### Environment
- Starship EVO version: 21w35a
- Graphics Card: Radeon RX590

### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7110390/Player.log)

I haven't played the game for a while, like for 6 or 8 updates ago, all that I use is "enabled moving speed control" and "anticlip" to build around.

**Comment by tsunamayo** [comment]
@chacalik Hi, could you please send me the content of the folder:
C:/Users/copoe/AppData/Local/Temp/Moonfire Entertainment/Starship EVO/Crashes
Thanks a lot!

**Comment by tsunamayo** [comment]
@chacalik also how long did you waited before the crash to happen? Thanks

**Comment by chacalik** [comment]
@tsunamayo about the "Crashes" folder content, I know it seems weird but there are folders for each crash since september 1st, but every folder is empty.
For the time, can't confirm, but it happens while I actively play... So, I would say about 15 to 20 mins... 
Although I do think its related to the memory leak bug someone already reported... Any way, there it goes the crashes folder prints:
![image](https://user-images.githubusercontent.com/4794243/132111633-f598e00f-4478-49c4-9239-184f531183cf.png)
![image](https://user-images.githubusercontent.com/4794243/132111643-1ebf14fd-52a3-4777-a323-ab5f26053538.png)

**Comment by chacalik** [comment]
Since the last update, the issue seem to stopped. I believe it can be considered fixed.

**Comment by tsunamayo** [comment]
@chacalik Okay mate thanks for the update.
