### ISSUE TITLE
[BUG] Guns do not gimble when controlled by event gate 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#4156]
### Short Description of the issue:
as the title says weapons like beams will not gimbal when controlled by event gates, i tested this on a few ships and included one  
...

### Steps to reproduce the issue:
fire beams on included bp
...

### Environment
- Starship EVO version: 21w35a

https://steamcommunity.com/sharedfiles/filedetails/?id=2564266333

**Comment by tsunamayo** [comment]
@TIKIRobo Fixed for 22w33a. Thanks!
