### ISSUE TITLE
[BUG] Fuel not Flowing Properly 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#4157]
### Short Description of the issue:
On a ship of mine i was trying to do a test to see how long it could burn fuel even when under heavy use, instead what i found was that the reactor would only drain from the fuel tank it was attached to and the tank would not be refilled by its neighbors.

(this also might just be a confusing feature) 
...

### Steps to reproduce the issue:
load up BP and let it run for a few minutes 
...

### Environment
- Starship EVO version: 21w35a

### Additional information:
[New Entity2.zip](https://github.com/tsunamayo/Starship-EVO/files/7112333/New.Entity2.zip)

**Comment by tsunamayo** [comment]
@TIKIRobo Hi, yes it was not yet supported. In the next update it will be though: now tank linked together will try to adjust their fill % to form an equilibrium between them. 
Cheers
