### ISSUE TITLE
Stranded in space and can't get back

### ISSUE THREAD

**Issue by tofast10** [tsunamayo/Starship-EVO#4159]
### Short Description of the issue:
Getting lost in space when you start a new world
...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 21w07a
- Graphics Card: Radeon RX 580 Series

### Additional information: Every time i get in a star ship when this glitch happens it just breaks the ship.

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@tofast10 Hi, you can toggle the teleport anywhere option: press F3 then tick "Allow teleport to any ship".
Then open the codex and go to the teleport tab, then get back into the starting zone.
Thanks
