### ISSUE TITLE
[BUG] Blueprints are STILL being corrupted and spawning station pieces.

### ISSUE THREAD

**Issue by DarthPeter0** [tsunamayo/Starship-EVO#4161]
### Short Description of the issue:
The issue is the same as one I have posted previously: ships that have been saved to blueprints are having their "name".sevo files emptied of data.  This leads to the game spawning in random station pieces as a placeholder for the empty craft blueprint.  Sometimes station parts will spawn, and sometimes nothing will spawn.  What spawns seems random; the only thing that doesn't spawn is the intended craft.

The intriguing part of all of this is that the original corruption of the file occurred when I opened the included world to find that my frigate had been replaced with a small utility truck, called the "VQ09 Pekos B" (picture included).  This is not a blueprint I have in my craft files, or that I have ever seen before.  All other attempts to load the frigate, however, spawn either nothing or a station piece.  The truck is what the frigate turned into upon world load.  It also uses the name of the truck, not the frigate's name, which leads me to believe it is an entirely different blueprint.  Perhaps, with an empty .sevo file for the frigate, the game placed a random blueprint in the ship's place?  I honestly have no idea, but it could be a clue.  
...

### Steps to reproduce the issue:
To get this bug to occur naturally seems difficult to reproduce.  I cannot make the file corrupt on command.  However, to witness the result of this bug, install the included bugged blueprint and try to load the craft in-game.  Instead of the frigate which is supposed to load, either nothing or a random station component will spawn.  You can also take a look at the actual craft file and see that the "Frigate Mk1.1.sevo" file is completely empty.  It did not used to be, but it is now after experiencing the bug.
...

### Environment
- Starship EVO version: Experimental 21w35a
- Graphics Card: NVIDIA GTX 1060

### Additional information:
Screenshots:

The Frigate as it is supposed to be:  
![20210906165935_1](https://user-images.githubusercontent.com/33942288/132281614-ceb172a2-5728-4754-9aa0-dc1cf5c22440.jpg)
The Frigate as it was when I opened the world (the truck it turned into):
![20210906204516_1](https://user-images.githubusercontent.com/33942288/132281663-14493eef-2e70-49a6-8d4e-c06045b4c561.jpg)

Files:

The blueprint of the corrupted Frigate:
[Frigate Mk1.1.zip](https://github.com/tsunamayo/Starship-EVO/files/7118766/Frigate.Mk1.1.zip)
The save file of the corrupted world:  
[Peter 4.zip](https://github.com/tsunamayo/Starship-EVO/files/7118779/Peter.4.zip)
The player.log:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7118783/Player.log)

### Other Information:

I want to say that I know there are a lot of bugs to fix, and that I really appreciate everything you have done to make this game what it is today.  I have played over 1,000 hours of SEVO, was part of the first wave of backers, and have given you multiple builds to test the game.  SEVO has been one of my favorite games of all time.  

I also know that I have been playing on experimental, and with experimental comes an inherent risk of instability.  However, the gap between the experimental and stable branches is so wide that one cannot hope to build competitively in the stable branch. 
That said, this bug has been beyond game-breaking for me.  As building is the only fleshed-out system in the game right now, it needs to be perfect.  

The fact that I may pour dozens of hours into a build, only to have it disappear forever moments later, makes it difficult to continue building anything.  This is the second time this has happened to me; the first time I took a few months off from playing.  I finally made a return to the game a few days ago, only to experience the same bug a second time.  I cannot continue to invest my time into a game with these kinds of bugs.  I really do appreciate the work you have done to introduce other game loops into SEVO, but they should take a backseat to a stable blueprint system.

Thank you again for all you do and all you have done.  I am hopeful for the future of the game.

**Comment by tsunamayo** [comment]
@DarthPeter0 Hi, I agree 100% it is very much game breaking. This is a save corruption issue - there was an issue while exporting your ship, then it wrote a 0 kb invalid .sevo file.

Please find an older version of your build - sorry it is at a much earlier state.

I am not sure by what it is caused - what I would really need is a log file of the session where the issue happened. Which is the session before you see the spawn mismatch - there is a log called Player-prev.log so it should be possible.

I really would like to understand the issue, but I need a lead of some sort to investigate. Do you recall anything special from the session before the issue creeped in? Was it a "broken" session, where things stop to work and you need to restart? Was there anything special on the ship?

In the meantime I will try to work on a auto-backup system - and add safe guard so export cant be corrupted. I keep you posted on this. You would still loose the work made after the problem happened, so I need a way to tell the player to exit and report the issue.

I also agree my goal is to update the main build but I need to update the tutorial area first.
[Frigate_restored.zip](https://github.com/tsunamayo/Starship-EVO/files/7126501/Frigate_restored.zip)

Cheers, really sorry for that...

**Comment by tsunamayo** [comment]
@DarthPeter0 okay so for 21w36a we now have the following:

 1) A backup save called *.sevobu file will be created from the previous valid save
 2) The game will not attempt to save if it detect an issue or an 0 length save
 3) In that case a warning message will popup telling the player to book a case.

=> this wont save the corrupt issue but should prevent any significant loss of work. Please send your blueprint and player.log should this happen again, so I can fix the real issue!

Thanks and sorry again for the loss of work induced.

**Comment by tsunamayo** [comment]
@DarthPeter0 really sorry again it seems I previously joined the wrong blueprint:
[Frigate Mk1.1 Restored.zip](https://github.com/tsunamayo/Starship-EVO/files/7146859/Frigate.Mk1.1.Restored.zip)
cheers

**Comment by DarthPeter0** [comment]
I want to follow up with you to say I really appreciate you looking into this.  The safeguards added to the new build should hopefully alleviate future difficulties.  The blueprint you provided was also helpful; it was not the most recent version of the build, but it does save me some time in restoring it.  Should I experience this bug again, I will report it along with all the necessary files.

Thank you again for your quick response and fix.  Your dedication to both your game and its players is why I fully believe in this project.
