### ISSUE TITLE
[SUGGESTION] Box Delete Tool STICKER/DECAL ONLY delete. 

### ISSUE THREAD

**Issue by Servomotor** [tsunamayo/Starship-EVO#4162]
Good day your highness and most exalted!

Due to the nature of stickers being applied to builds in the voxel to neovoxel conversion, a lot of stickers are left behind on converted builds, hidden in between layers of blocks. Removing them is a tedious task for even smallish builds. 

Would it be possible to either get a left click option on the Box Delete Tool that would delete stickers only, or a new tool called Details/Markings Delete (only so people would not get confused and accidentally box delete their build when they just wanted to delete stickers). 

I have also run into scenarios a number of times now where I would like to delete all the stickers on a build and start from scratch to detail the build after its been complete, to see what is necessary and what is not necessary.  Of course removing all of them is again, a tedious task. A one box solution would speed up build time tremendously for these scenarios. 

Thank you your most holy of holies! We, your humble servants are eternally blessed by your creation.  👍

**Comment by 5URG3** [comment]
This would be very useful. I agree.

**Comment by BigBadKangaroo** [comment]
I agree!

**Comment by tsunamayo** [comment]
@Servomotor Hi mate, so yes I think I will go for the box / delete (and copy-paste) is decal only toggle. I dont really want to add a specific global remove UI though, but drawing a big box delete over your ship should do the trick. Thanks

**Comment by tsunamayo** [comment]
@Servomotor Implemented for 21w37a. Thanks!
