### ISSUE TITLE
Clipboard CE render bug

### ISSUE THREAD

**Issue by kynamats** [tsunamayo/Starship-EVO#4165]
### Short Description of the issue:
When you copy a Child Entity with its own Children Entities, a visual copy will appear centred on the character, which disappears when the object is deleted from the clipboard. If only a single CE (no grandchildren) is copied, only the lighting sprites will be duplicated. ** EDIT ** after further building i've found its not fully isolated to child entities, just copy paste in general..

...

### Steps to reproduce the issue:
Copy a child entity, with or without grandchildren entities, and/or anything else (?)
...

### Environment
- Starship EVO version: 21w36a
- Graphics Card: GTX 1070

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![20210910172558_1](https://user-images.githubusercontent.com/89156468/132888145-471df107-26ba-4dfd-b123-1d7e11f06132.jpg)
![20210910172601_1](https://user-images.githubusercontent.com/89156468/132888162-43e3ac72-0182-4ccd-b661-6c5b28dfe854.jpg)
![20210910172613_1](https://user-images.githubusercontent.com/89156468/132888192-a36eae53-7cda-46c3-a5e3-9fc396a32cd0.jpg)
![20210910172615_1](https://user-images.githubusercontent.com/89156468/132888230-36e99074-a2b8-474c-b410-f82e376c0b75.jpg)
![20210910172619_1](https://user-images.githubusercontent.com/89156468/132888240-c441ef4e-fb83-4bb7-a5a5-88d67ef38fd7.jpg)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7145235/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@kynamats Indeed I can reproduce that issue, it seems it is because of the rendering refactoring. I keep you posted.

**Comment by tsunamayo** [comment]
@kynamats Issue fixed for 21w37a. Thanks
