### ISSUE TITLE
[BUG] sudden lag when opening and closing codex 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#4166]
### Short Description of the issue:
like the title says i have a slight lag spike when opening the codex 
...

### Steps to reproduce the issue:
open and close codex 
...

### Environment
- Starship EVO version: 21w36a
### Additional information:

https://user-images.githubusercontent.com/56371294/132926148-45afbeef-7c4e-4d8b-acd2-1ce4ef8ec90a.mp4

in this video you can see a large spike in the graphs appear when opening/closing the codex

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7146805/Player.log)

**Comment by tsunamayo** [comment]
@TIKIRobo Hi, I cant play the video for some reason. Do you open the codex while you have been working on a large entity? Or do you get this even on small one? Thanks

**Comment by TIKIRobo** [comment]
I get this on both

**Comment by tsunamayo** [comment]
@TIKIRobo okay I think we are talking about a mini-lag, not a game breaking thing. It was always there as there need to compute a  few things on open, so I wont really spend much time on that. Thanks mate!
