### ISSUE TITLE
[BUG] Fuel transferring only partially  

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#4167]
### Short Description of the issue:
for whatever reason fuel coming out of a tank isn't going into two quarter pipes but not leaving them 
...

### Steps to reproduce the issue:
load up included bp
...

### Environment
- Starship EVO version: 21w36a

### Additional information:

![image](https://user-images.githubusercontent.com/56371294/132928607-496a37b9-42c5-4c83-8d1f-eee57bde5748.png)
fuel only going thru green pipes/tanks
[Fuel testbed 1.zip](https://github.com/tsunamayo/Starship-EVO/files/7146894/Fuel.testbed.1.zip)

**Comment by Servomotor** [comment]
I am having similar issues. Elbow does not transmit fuel, neither does the 6-Way. 

[Servo Fuel Test 21w36a.zip](https://github.com/tsunamayo/Starship-EVO/files/7146970/Servo.Fuel.Test.21w36a.zip)

**Comment by tsunamayo** [comment]
@Servomotor Hi, for 6-way it is normal at this stage. 6 way is gonna be a mini-tank actually when implemented.

**Comment by Servomotor** [comment]
A mini tank sounds cool!

**Comment by tsunamayo** [comment]
@TIKIRobo Okay issue fixed for 21w37a. Cheers
