### ISSUE TITLE
[BUG] Culling not working properly 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#4171]
### Short Description of the issue:
when getting near some walls in a building they begin to flicker rapidly, it doesn't show up well in video but in game it is quite obvious  
...

### Steps to reproduce the issue:
load up bp and go to wall shown 
...

### Environment
- Starship EVO version: 21w36a
### Additional information:

https://user-images.githubusercontent.com/56371294/132993229-3b11ee59-e397-494f-9f08-3b7ad0c012b9.mp4

https://user-images.githubusercontent.com/56371294/132993330-c9bfc439-fb75-45b9-9fb4-e732fbcf34bb.mp4

[Large WIP city tech.zip](https://github.com/tsunamayo/Starship-EVO/files/7149820/Large.WIP.city.tech.zip)

**Comment by tsunamayo** [comment]
@TIKIRobo Is it a new thing or has it going on for some time? Thanks

**Comment by TIKIRobo** [comment]
@tsunamayo its new, and i saw you mentioning something about changing rendering so i think it was caused by that

**Comment by tsunamayo** [comment]
@tsunamayo I see, I will see what it could have caused this (I havent touched the culling algo)
