### ISSUE TITLE
[BUG] Loading existing worlds

### ISSUE THREAD

**Issue by Dynamo121** [tsunamayo/Starship-EVO#4172]
Description:

Loading into an existing character save removes all object from that world
##

Steps to reproduce the issue:

Loading back into a save file I've already made (I've made about 6 and this issue is the same with all of them)
##

Environment:
- Starship EVO version: unsure
- Graphics Card: Radion Vega 11

Additional information:
as far as I'm aware my system is perfectly fine to run Starship Evo. But this problem's made the game pretty much unplayable 
##

![Screenshot 2021-09-12 181524](https://user-images.githubusercontent.com/90570170/132996770-912c9c68-ae66-4f6a-b3f7-ea780cf3af5c.png)

![Screenshot 2021-09-12 181627](https://user-images.githubusercontent.com/90570170/132996778-360d74fa-826a-4d72-b358-264ffd564a12.png)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7150018/Player.log)

**Comment by tsunamayo** [comment]
@Dynamo121Hi, I am not sure to understand the issue.
Could you describe what happen?
ie:
1) you create a character save => can you play fine at this point?
2) Do you Do a quit to title OR a quit to windows?
2) then you load back the save => has everything disappeared?

Can you hit F3 / Tick "Allow teleport to any ship". What do you see? (nothing or a list of ship?) If you see a list of ship could teleport to one of those? 
Thanks
