### ISSUE TITLE
[BUG] RGB Gate not working in 21w36a

### ISSUE THREAD

**Issue by Servomotor** [tsunamayo/Starship-EVO#4175]
### Short Description of the issue:
RGB Gate does not change colors. 

...

### Steps to reproduce the issue:
Blueprint included. Just turn on the switch to see the RGB gate not working.
...

### Environment
- Starship EVO version:  21w36a
- Graphics Card: RTX 2080

### Additional information:

[RGB Gate not working 21w36a.zip](https://github.com/tsunamayo/Starship-EVO/files/7151726/RGB.Gate.not.working.21w36a.zip)

**Comment by tsunamayo** [comment]
@Servomotor indeed, issue fixed for 21w37a. Thanks
