### ISSUE TITLE
[LONGSTANDING BUG] Volumetric Sensor not working for 6 months

### ISSUE THREAD

**Issue by Servomotor** [tsunamayo/Starship-EVO#4182]
### Short Description of the issue:
Volumetric sensor has been broken for a very long time. I don't recall the exact update that broke the Volumetric Sensor, but I think it was in March, 2021, so half a year now. 
...

### Steps to reproduce the issue:
Just walk into the Volumetric Sensor field in the test rig I have attached. 
...

### Environment
- Starship EVO version: 21w37a
- Graphics Card: RTX2080 (but everyone I know has this issue in game with the volumetric sensor)

### Additional information:

test file attached
[BUG Volumetric Sensor Not Working.zip](https://github.com/tsunamayo/Starship-EVO/files/7183597/BUG.Volumetric.Sensor.Not.Working.zip)

**Comment by CPCTC** [comment]
Reproduced in 22w07b.

**Comment by tsunamayo** [comment]
@Servomotor Well we waited a lot for that one, it is finally fixed for 22w45a. I had to do plenty of improvements.
