### ISSUE TITLE
Pipe connectors dont seem to work

### ISSUE THREAD

**Issue by crazynachos** [tsunamayo/Starship-EVO#4185]
### Short Description of the issue:

Trying to connect a pipe to another system using the connectors doesn't seem to work or do anything, I think it has to do with the connectors not having a tank value as they show "NaN"

### Steps to reproduce the issue:

simply recreate the pipe system shown

### Environment
- Starship EVO version: [New build - EXPERIMENTAL} 21w35a
- Graphics Card: Radeon RX Vega 10

### Additional information:

![image](https://user-images.githubusercontent.com/82737120/133907839-081b4525-2c33-48bf-a902-378d2f1a4292.png)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by Reason147** [comment]
I reported the same problem: https://github.com/tsunamayo/Starship-EVO/issues/4183

**Comment by tsunamayo** [comment]
@crazynachos @Reason147 issue fixed for 21w40a. Thanks!
