### ISSUE TITLE
Warning Message Gate doesn't work with Event Gate

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#4186]
Situation:

I've build a landing gear for my ship and I want to give the pilot a message that it is deployed/ retracted. So I used some logic for it in the following order:
ship controller - event gate (langingear is pressed) - switch - WM gate

The landing gear retracts/ deploys just fine, but the message doesn't show up on screen while piloting. however if I just press the button when not piloting the ship the message shows up!

I've tested some diffrent logic setups like other commands in the event gate (button 1-4), used variations of the base logic gate. All of them let the mechanism work but no message. I only get the message if I press some sort of button or so manually when not piloting.

I even checked the new option for showing help messages in the F1 menu - but nothing makes a difference.
![20210919012025_1](https://user-images.githubusercontent.com/81495956/133911156-cc3065b5-9f96-4a49-870c-de260154ed7d.jpg)
![20210919012326_1](https://user-images.githubusercontent.com/81495956/133911158-9f8f0b76-f257-47a2-8913-d0bee19a6a21.jpg)

**Comment by tsunamayo** [comment]
@BigBadKangaroo This will be fixed for 21w47c. Thanks!
