### ISSUE TITLE
Copy&Paste Artifacts

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#4187]
Copy&Paste creates artifacts of the copied objects on the spot where your character stands while copieing

![20210919014443_1](https://user-images.githubusercontent.com/81495956/133911240-eeda2e9c-5379-4ec1-a8f6-1f0a623871cf.jpg)

**Comment by 5URG3** [comment]
Can confirm this happens.

**Comment by tsunamayo** [comment]
@BigBadKangaroo @5URG3 I cant reproduce this, is this something you get all the time? Can you interact with entity (ie is there collisions). Cheers

**Comment by tsunamayo** [comment]
@BigBadKangaroo I manage to reproduce once but I cant get it to reproduce now. Are you able to reproduce on a new game? You just load your save, do a copy/paste and get the issue? If yes could you send me your save? 
Thanks
