### ISSUE TITLE
I need some info about Leosus

### ISSUE THREAD

**Issue by Jorpis-Jorah** [tsunamayo/Starship-EVO#4192]
Today I am making a wiki page for Leosus on the fandom, but first, I need to know some information about it, such as:
-System size (AU)
-Star type
-Factions present
-Some basic lore
**Pictures**
Pictures of the system are appreciated too since I am very busy this week.
Also, Tsuna, how come you named it Leosus?
(btw it's name isn't randomized, but Leoseus is very similar. And also its planets aren't randomized each seed)
Here is the [Wiki Page](https://starshipevo.fandom.com/wiki/Leosus)

**Comment by TIKIRobo** [comment]
I wouldn't make a wiki page dedicated to the system, as of rn there are not factions, no lore and the system names are randomly generated, there are probably 10 other leosus systems out there

**Comment by Jorpis-Jorah** [comment]
Of course, but it will obviously change overtime, and as for the system name, it is one of the only star systems that isn't randomized.

**Comment by Jorpis-Jorah** [comment]
@TIKIRobo haha that's interesting, the naming system should be tweaked... however I noticed this too, ive seen some systems named LEOSEUS not LEOSUS which is a different name, Leosus isn't a random name but Leoseus is, also the thing about leosus is that no matter what seed, the planets will not change, so technically it could be a part of the lore.
