### ISSUE TITLE
[Bug] Floodlight bricks produce lighting artefacts from a certain LOD

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4196]
### Short Description of the issue:
I was trying out the new floodlight blocks as a thruster trail like Bruce did, and noticed that past a certain range artefacts appear at the end of the floodlights stretched volume.

You can see a glowing ball at the end of the spotlight
![711980_20210924145938_1](https://user-images.githubusercontent.com/27857711/134687455-c2073bcf-f7dd-4700-8b04-19502534263b.png)

It looks like the ball appears when the camera is around 16m away

### Steps to reproduce the issue:
 - Stretch a floodlight to its max length (not required, but makes it easier to see the artefact
 - Fly away/zoom out in 3rd person view

### Environment
- Starship EVO version: 21w38a
- Graphics Card: RX580

**Comment by ProPeach** [comment]
Looks like the larger the scale of the floodlight, the further away the camera needs to be to show the glowing ball.

**Comment by tsunamayo** [comment]
@ProPeach thanks mate, issue fixed for 21w40a. Cheers

**Comment by tsunamayo** [comment]
@ProPeach btw sorry I messed up on your mail, I have just replied now...
