### ISSUE TITLE
[Bug] Tile Triangles produce glow

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4197]
### Short Description of the issue:
The new Tile Triangle bricks glow when the camera is 16m or so away, looks a lot like the new sprite glow effect on lights/glow bricks.
This effect is only present on bricks that are painted with a colour paint, not a material paint
![image](https://user-images.githubusercontent.com/27857711/134695587-2fe0af73-0bfe-491b-a8a1-cd957d4308fa.png)

### Steps to reproduce the issue:
 - Place down some Tile Triangles
 - Paint them
 - Fly away and note the glow

### Environment
- Starship EVO version: 21w38a
- Graphics Card: RX580

**Comment by DioTheCreative** [comment]
You can also link them to switches and computer blocks.

**Comment by BigBadKangaroo** [comment]
They don't seem to have a hitbox either. I've build an angled guardrail and you could walk right through it.

**Comment by tsunamayo** [comment]
@ProPeach indeed, fixed for 21w39a. Thanks
