### ISSUE TITLE
Barrel placement broken on movable turret

### ISSUE THREAD

**Issue by Doperwt** [tsunamayo/Starship-EVO#4199]
### Short Description of the issue:
When trying to place barrels on a turret that is on a piston the game bugs out and doesnt let me place anything anymore. 

### Steps to reproduce the issue:

Place piston, add 2 rotators on top of piston arranged for a turret. place laser weapon, try to place barrels (it doesnt always bug out on the first one.

### Environment
- Starship EVO version:  21w38a
- Graphics Card: gtx1070

### Additional information:
https://imgur.com/LaQXhss

if i copy/paste the weapon+barrel assembly onto the turret, the turret will fully rotate and all weapons will fire correctly.

if i restart the game i can work on the world again. Exit to menu doesn't help.

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed 
then drag the .zip onto your report to upload it.
[Player.zip](https://github.com/tsunamayo/Starship-EVO/files/7230296/Player.zip)
zip file]

**Comment by tsunamayo** [comment]
@Doperwt Issue fixed for 21w40a. Thanks!
