### ISSUE TITLE
Ship sizes can cause lag

### ISSUE THREAD

**Issue by DioTheCreative** [tsunamayo/Starship-EVO#4202]
### Short Description of the issue: When the ship size reaches a certain point the game will begin to lag. Seems to not have anything to do with complexity.

...

### Steps to reproduce the issue: Make a ship or structure about 2000x2000x2000 m 

...

### Environment
- Starship EVO version: 21w38a
- Graphics Card: GeForce GTX 960

### Additional information: I wanted to see how big I can make something, this seems to be the first limitation I came across. I was using max size blocks.

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by ProPeach** [comment]
Do you have a bp you could show for this? That helps narrow down a particular cause by a lot, even if you say complexity isn't always a factor

**Comment by tsunamayo** [comment]
@DioTheCreative Hi, yes could you please send the bp? thx
