### ISSUE TITLE
Hinge collision box issues again

### ISSUE THREAD

**Issue by CurioInventorium** [tsunamayo/Starship-EVO#4205]
### Short Description of the issue:
Hinges refuse to move to their set angle and hinges that previously did would stop moving once more blocks are added round them. Even if said blocks are removed again, the problem persists.
Ship blueprint added below.
...

### Steps to reproduce the issue:
The ship in question is a mirror built chassis with the landing gear intended to be incorporated into a large part of the ships superstructure.
Rails move sections either side of the ship forward and then a set of hinges (as child object) move the sections downwards to form landing feet.
During construction and initial testing, with no surrounding panels or greebles, the starboard side hinges would behave as intended, but the port side would refuse to move. Even when manually trying to set their values.
This is all similar to an issue raised before with hinges not behaving.
During further troubleshooting the issues eventually spread to the other hinges as I tried to build more of the ship.
...

### Environment
- Starship EVO version: 21w38a
- Graphics Card: RTX2060

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
Landing gear stowed
![20211003154726_1](https://user-images.githubusercontent.com/51359034/135761444-05809070-ae05-4e48-af50-cd502c8881a6.jpg)

Landing gear extended front, but hinges on both sides have partially worked
![20211003152915_1](https://user-images.githubusercontent.com/51359034/135761454-98a3da16-1848-4ef3-a00c-87b85da54341.jpg)

Landing gear rear, the starboard side has worked but the port side has glitched
![20211003152906_1](https://user-images.githubusercontent.com/51359034/135761470-7200ffac-8cab-43d5-946d-532ee6e3e669.jpg)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

Player log seems excessively large, but this was a decent length of time building session.
[Player.zip](https://github.com/tsunamayo/Starship-EVO/files/7273929/Player.zip)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

Here's the blueprint
[CrossPlanet Cargo Mk1.zip](https://github.com/tsunamayo/Starship-EVO/files/7273934/CrossPlanet.Cargo.Mk1.zip)
t

**Comment by Dwarf-LordPangolin** [comment]
I am also encountering this issue. In my case, the orange hinge is colliding with the blue block, which was a bit surprising.

![20211005205156_1](https://user-images.githubusercontent.com/33041786/136128425-ef123b6a-d407-4de4-a6cb-8ebccbde30ba.jpg)

**Comment by tsunamayo** [comment]
@CurioInventorium @Dwarf-LordPangolin Issue fixed for 21w40a. The whole children check move to full multi-threaded code very soon. Cheers
