### ISSUE TITLE
[BUG] Stretch indicator bugs out 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#4206]
### Short Description of the issue:
Sometimes the stretch indicator "loses count" and breaks
...

### Environment
- Starship EVO version: 21w38a

### Additional information:

https://user-images.githubusercontent.com/56371294/135770114-5f09cee2-e051-4957-a785-dec161ca1487.mp4

**Comment by tsunamayo** [comment]
@TIKIRobo Hi, fixed for 21w40a. Cheers
