### ISSUE TITLE
Ship Collision Not Working After update 21w40a

### ISSUE THREAD

**Issue by wagskydive** [tsunamayo/Starship-EVO#4209]
### Short Description of the issue:

Collision between the ship i am flying and another ship are not working, so the ships clips through the other ship.

### Steps to reproduce the issue:

Fly a ship into another ship.

### Environment
- Starship EVO version:  21w40a
- Graphics Card: GTX1070

### Additional information:

tested the vanilla build and the experimental and the bug is only in experimental.
Also started a new game and the problem persists.

https://user-images.githubusercontent.com/29782656/136619527-bf3cb0de-342d-4965-afcf-8a11d7863faf.mp4

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7313946/Player.log)

**Comment by CurioInventorium** [comment]
Same, plus maglock doesn't seem to be working. Strangely I was able to load a blueprint which had small maglocks activated via the old hotkey block, and they worked. But a maglock controlled by a switch, which is toggled via the new block doesn't work.
