### ISSUE TITLE
[BUG] Changing refresh rate broken 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#4212]
### Short Description of the issue:
As seen the the video when I set my refresh rate to 144 it just gets reset to 165

### Environment
- Starship EVO version:21w40a 
- Graphics Card: AMD Radeon RX 5600 XT
- I am also using two monitors with the game running in a 144hz monitor and the other monitor running at 60hz 

### Additional information:

https://user-images.githubusercontent.com/56371294/136673090-4822e6d0-3631-4b71-aaeb-688ccab90d16.mp4

**Comment by tsunamayo** [comment]
@TIKIRobo This should be fixed for 21w47c. Thanks
