### ISSUE TITLE
[Bugs] [Experimental] Weapon gimbal doesn't work and gun barrels disappear when i log back in

### ISSUE THREAD

**Issue by quelonio** [tsunamayo/Starship-EVO#4215]
First bug:
The gimbal for the weapons doesn't work when i use the event gate, it only works with old builds that have an input gate.

Second bug:
The barrels for the guns that i put on builds disappear after i log out and log back in to the world and alll that remain from them is their hitbox.

All of this is in the experimental build.

Output log:
[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/7325900/output_log.zip)
Character files:
[Characters.zip](https://github.com/tsunamayo/Starship-EVO/files/7325901/Characters.zip)

**Comment by tsunamayo** [comment]
Issue should be fixed in recent build. Thanks
