### ISSUE TITLE
[BUG] Invisible Blocks and Entity Despawn after Crash

### ISSUE THREAD

**Issue by Tocks13** [tsunamayo/Starship-EVO#4218]
### Short Description of the issue:

Most parts of the Spawn Base got invisible, with exception of lights and texts.
After reloading, the game got stuck on loading screen.
After forced shutdown and restart the Base has completely vanished

### Steps to reproduce the issue:

Reload multiple times in short succession, while using Xbox Gamebar (Windows+G) to make a video?

### Environment
- Starship EVO version: 21w40b
- Graphics Card: GTX 1080

### Additional information:

Was not yet able to reproduce.
Reloaded World 3 times, before I noticed.
Started moving before Game settled loading in.

Video where I noticed, the recording seems to lose a few seconds right after loading screen is finished:
https://user-images.githubusercontent.com/67311622/136963065-5a36a3dd-9d30-4439-a8b3-d62ba6107c4b.mp4

Log File (same file as in #4217):
[Player-Broken.log](https://github.com/tsunamayo/Starship-EVO/files/7330261/Player-Broken.log)

**Comment by jasonfogleman** [comment]
Can confirm this one as well. Was on a Halo and the base I was next to first went invisible, then completely despawned

**Comment by tsunamayo** [comment]
@Tocks13 Hi, this issue has been fixed in recent update. Thanks!
