### ISSUE TITLE
[BUG] fps drop for no reason

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#4219]
### Short Description of the issue:

The game is taking too much time to load, even on a new world, and the FPS is too low, even with idle gpu.
...

### Steps to reproduce the issue:
Load the game
...

### Environment
- Starship EVO version: [experimental]
- Graphics Card:  GTX1660

### Additional information:

![image](https://user-images.githubusercontent.com/73253472/137050877-8956e242-2e90-45b2-b34a-94f90cfb8d14.png)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/7334030/output_log.txt)

**Comment by TIKIRobo** [comment]
![image](https://user-images.githubusercontent.com/56371294/137631470-cec14f26-586a-424d-98a4-016fd790540c.png)
also having some wild performance issues in the 41a patch as well as a few small performance issues in the 40b patch
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7360090/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/7360091/Player-prev.log)

**Comment by Uncle-Ulty** [comment]
First I was having a low fps issue in the first second after loading a world (any world, new or old). Now this problem is continuous.

**Comment by Uncle-Ulty** [comment]
this happens moments after loading a new world

![image](https://user-images.githubusercontent.com/73253472/137639372-2c87cd6c-76fa-4667-9ea7-7175b45f8521.png)

**Comment by tsunamayo** [comment]
@Uncle-Ulty I think this should be fixed for next update 21w45b! Thanks
