### ISSUE TITLE
Second hitbox, offset, added to blueprint? Also disappearing barrel attachments.

### ISSUE THREAD

**Issue by Regnion** [tsunamayo/Starship-EVO#4220]
### Short Description of the issue:

I built a turret, and saved the blueprint. When I spawned it in again, the barrel attachments were invisible but apparently still present. Additionally, there appears to be a large collision box around the top of the turret, in a circular, spherical shape, about 1.5m away from the surface of the turret. However, this collision issue is not present another turret I made, nor have I encountered it before.

It's almost like a second, identical (but only the upper half) hitbox was created just offset above the actual build.

Note: This collision box is like a halo around the top. The very top of the turret is fine, standard hitbox, but around it there is some invisible wall there.

If there is a way to "fix" the blueprint without having to rebuild it entirely, I'd be really grateful, because these are a pain in the rear to build.

...

### Steps to reproduce the issue:

Unknown. Only appeared after spawning in blueprint, but the blueprint keeps this issue somehow. Blueprint is attached.

...

### Environment
- Starship EVO version: Experimental, 21w40b

### Additional information:

[Regnion Collision Bug.zip](https://github.com/tsunamayo/Starship-EVO/files/7334817/Regnion.Collision.Bug.zip)

**Comment by tsunamayo** [comment]
@Regnion There was an issue fixed sometime ago with barrel which looks like yours. Tell me if you still see this!
