### ISSUE TITLE
The Death Star Test

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#4225]
Heyo Tsuna, so Peach brought up that in the Q&A we had you almost seemed like you genuinely wanted a 1:1 Death Star to be built in order to fully test _**THIS FULLY OPERATIONAL BATTLESTA...**_ err, game engine. Being the insane person that I am, I'm happy to oblige! :D 

I did want to ask though what your thoughts or plans are on increasing the draw distance since I'll be building the shell of this monster at about 120km in diameter. I know there was talk about this topic elsewhere but just wanted to know how much the draw distance could be increased. In theory it _could_ almost be increased semi indefinitely by using the engine to create a few low quality PNG's for extreme distances. But that's just my thought on it.

Also, if we did get one built and it didn't crash the game or do anything terrible, would there be a possibility of adding fully functional lasers to this bad boy? It will likely be a very long time before it's even remotely close to ready for such a thing though. DaOyster has made a circle generator and is adding various features to make it more Starship EVO compatible so I'm working with him on that and Gmunga, of course, for interiors at this point. Once I'm ready for it I may ask Womble to work on the trench because it just seems fitting lol.

Anyhow, wish me luck! I'm sure you may see some posts about the Death Star progress and/or complications on this github from time to time.

**Comment by tsunamayo** [comment]
Wait it is 120km... We might have various issues with physics if it is a single entity actually ^^
Also I guess you would need larger block dont you think?
It would render on the second camera used for planets and torus, so it would be seen from very far away...
Wouldnt something like 10 or 20 km be better?

**Comment by Xerma** [comment]
What issues would it cause? Would it be problematic to have the shell be a single entity then have the interior on another? 32m blocks could work but yeah, larger blocks would make building the hull much easier. So would it render on the second camera for planets due to it's size then? If so that's very intriguing. I was meaning more of the view distance the player has around them, right now it seems close to 60km and the mirror planes get very wonky at the max distance:
![20211017175826_1](https://user-images.githubusercontent.com/32974671/137649095-6cd7d463-3a2c-4fb7-a4aa-412bacb91409.jpg)
![20211017183719_1](https://user-images.githubusercontent.com/32974671/137649102-0a74de6f-0b92-403e-be61-40ca1b8a0b1f.jpg)

**Comment by tsunamayo** [comment]
@Xerma each brick would choose its rendering cam depending on its distance to the player. 
We would have floating point issues with collisions (I guess). 
Yep the plane is gonna be f*** up, as many things...
I wont go too far in supporting this though, as my goal is mainly to redo the torus with bricks (not have player use that in survival for example)
Cheers

**Comment by tsunamayo** [comment]
@Xerma Interesting to know, thanks for the feedback! Torus will have to be made into segment, so I expect less issue that way (mainly floating point issues). Do you still get codex issues in 21w45a?

**Comment by tsunamayo** [comment]
@AlienXtream Well I am using long (and not double) for storing position inside the system. I deal with precision issue in the broadphase, but within a single entity I am using floats. It will work well for what I need honestly, no need to change it! If there is some issue for a particular build just chunk it yourself (ie use several docked entity to assemble the large one).
@Xerma Also I will give a special docking brick to allow recursive docking at an angle, to form Torus. You could build a circular station this way much more simply!
