### ISSUE TITLE
[BUG] FPS/Rendering/Physics Stuttering and glitches

### ISSUE THREAD

**Issue by Tocks13** [tsunamayo/Starship-EVO#4226]
### Short Description of the issue:

FPS: Random drops and extreme stuttering
Rendering: Glitches when looking at glas, even worse when inside Fighter Cockpit
Physics: At the same time as FPS Stuttering, phantom forces are moving the fighter around
### Steps to reproduce the issue:

Create new Game. 
Go to fighter.
Access yoke.
Leave yoke.
Look around and wait a little.

### Environment
- Starship EVO version: 21w41a
- Graphics Card:  GTX 1080
- Only one 16G RAM stick, second one broke recently, may be important?

### Additional information:
Is new with 21w41a, didn't happen in 21w40b
While it doesn't stutter, the FPS are smooth at 100+
It also happens after I leave the fighter.
It feels like the whole Engine is stuttering.
[Player-Stutter.log](https://github.com/tsunamayo/Starship-EVO/files/7365535/Player-Stutter.log)

One Video to show difference between before starting and after:
https://user-images.githubusercontent.com/67311622/137752265-cbd1928c-10c7-4329-b3cf-d1eda2a6cabd.mp4

One Video to show Bug highlights:
https://user-images.githubusercontent.com/67311622/137752329-35180dc3-cc78-46bc-beaf-a6f6471d08b7.mp4

**Comment by tsunamayo** [comment]
@Tocks13 I will unplug the transparency sorting as there are still some issues. Fixed for 21w42a. Cheers
