### ISSUE TITLE
[Bug] Gravity fields not correct [21w41a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#4227]
### Short Description of the issue:
When building a creation with multiple gravity fields, the angle of the combined fields does not match what it should. In particular, placing a shipwide generator on a creation with other, localized generators causes the shipwide field's angle to be off, even in areas where it does not overlap with any other fields.

### Steps to reproduce the issue:
I'm attaching the blueprint so you can see this for yourself.

### Environment
- Starship EVO version: 21w41a
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information
As you can see, "down" as indicated by the field arrows does not match the direction the player is actually pulled in.
![20211018235654_1](https://user-images.githubusercontent.com/33041786/137846565-195614ac-3193-41a3-947f-94d9003538f3.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/7370292/output_log.txt)

[Gravity Vector Bug Blueprint.zip](https://github.com/tsunamayo/Starship-EVO/files/7370293/Gravity.Vector.Bug.Blueprint.zip)

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Hi sorry I slept on this, it is finally fixed for 21w47c! Cheers
