### ISSUE TITLE
[BUG] Fuel flow is not working properly

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Starship-EVO#4229]
### Short Description of the issue:
Tanks run out of Fuel even though all valves are closed and the reactors are off.
- longstanding bug (since "attack of the valves")
- Not Blueprint related
- tried restarts
- tried clean worlds/ new Characters etc.

### Environment
- Starship EVO version: newest experimental 
- Graphics Card: rtx 3080

### Additional information:
[2 BP to test.zip](https://github.com/tsunamayo/Starship-EVO/files/7373632/2.BP.to.test.zip)
I tried to work arround the Bug in both blueprints unsuccessfully. Both BP have  switch to turn off the/all reactors and clos all valves at once

**Comment by tsunamayo** [comment]
@Battlepixel So the second ship was fine, on the first one (Defender) I noticed the issue. Problem is it is honestly a nightmare of pipe and linked tanked together. Did you manage to reproduce the issue on a way more simple case (I cant debug things that complex honestly). Also what is the meaning of all those circuit, was it purely for look or where you trying to make something work?
Cheers

**Comment by tsunamayo** [comment]
Okay you know what I will use this ship as a test to improve the fuel debug view. With a better preview it might be easier to debug! Cheers

**Comment by Battlepixel** [comment]
> @Battlepixel So the second ship was fine, on the first one (Defender) I noticed the issue. Problem is it is honestly a nightmare of pipe and linked tanked together. Did you manage to reproduce the issue on a way more simple case (I cant debug things that complex honestly). Also what is the meaning of all those circuit, was it purely for look or where you trying to make something work? Cheers

I tried to make it work. I have found a workaround the bug. It works only if I connect the tanks with a single pipe and the reactors and tanks with a single pipe and a valve. No other configuration is working for me. You can find the modified Blueprints in #4269

**Comment by tsunamayo** [comment]
Hi, this should be fixed in recent version. Cheers
