### ISSUE TITLE
gimble targeting is broken longstanding [Bug]- (18. Aug)

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Starship-EVO#4230]
### Short Description of the issue:
- since event-gate replaces hotkey-gate -,,-
- tried everything to work arround this bug, unsuccessfully

The bug was also posted by others, its not related to my files.

Before the bug I started a project that I have not been able to work on since two month because of this bug. It would be great if you could take care of this.
[2 BP to test.zip](https://github.com/tsunamayo/Starship-EVO/files/7373761/2.BP.to.test.zip)

**Comment by tsunamayo** [comment]
This issue was fixed some time ago. Thanks
