### ISSUE TITLE
[Bug] Beam weapons do no damage, get stuck in firing animation

### ISSUE THREAD

**Issue by Asnro** [tsunamayo/Starship-EVO#4233]
### Short Description of the issue:

See title. When firing, beam weapons' beams will appear to phase through and do zero damage to ships, and occasionally will get stuck in firing animation for much longer than 1.5 seconds. Issue only seems to affect player ships, pirate ships' beam weapons work fine.

### Environment
- Starship EVO version: 21w42a
- Graphics Card: RTX 3070

### Additional information:
Player ship firing
![kuva](https://user-images.githubusercontent.com/14952174/138111893-b23c553e-c77a-4547-a815-b6deec9606d9.png)

Pirate ship firing
![kuva](https://user-images.githubusercontent.com/14952174/138113118-fc128850-d287-4be9-8313-aefe5f35fffa.png)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7381085/Player.log)

**Comment by tsunamayo** [comment]
@Asnro Issue fixed for 21w44a. Thanks
