### ISSUE TITLE
Game causing BSoDs

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4234]
The game produces Blue Screen of Death 5-10 minutes after launch, almost every time.
I disabled the NPCs and limited the FPS displayed to 60, but it didn't alleviate the issue.

I don't do anything specific - it can BSoD even when completely idle.

GPU: 1080Ti
Version: 21w42a

[DxDiag.txt](https://github.com/tsunamayo/Starship-EVO/files/7381370/DxDiag.txt)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7381334/Player.log)

**Comment by TIKIRobo** [comment]
I haven't had this, maybe try uninstall/reinstall and updating your drivers?

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Hi, just to confirm you are still seeing this after a restart?
Other player have issues, but I am totally clean on my side - this will be a pain to investigate...
