### ISSUE TITLE
[Question] Can the size limit of fuel tanks be increased?

### ISSUE THREAD

**Issue by Jorpis-Jorah** [tsunamayo/Starship-EVO#4236]
When I spawned a ship of mine that had fuel tanks inside it, it looked weird because of its now smaller size, it also looks strange on Npc ships that has big tanks, it looks silly. Could we have the size limit increased? Or maybe have an identical tank that is dedicated as a larger tank?

**Comment by tsunamayo** [comment]
I see, let me fix this.

**Comment by tsunamayo** [comment]
Actually fixed for 21w45a. Thanks
