### ISSUE TITLE
[Bug] Player-spawned Station Modules spawn inside each other

### ISSUE THREAD

**Issue by Asnro** [tsunamayo/Starship-EVO#4237]
### Short Description of the issue:
Each time I try to spawn a station module while near a station, the module will spawn attached to an already occupied docking port, clipping into the previous module and at worst cases launching the station and module tumbling away. There's multiple identical docking ports available but the same singular one is always chosen.

### Steps to reproduce the issue:
- Have multiple docking ports available & identically configured
- Spawn a compatible module several times
- Each new module will spawn attached to the same port

### Environment
- Starship EVO version: 21w42a
- Graphics Card: RTX 3070

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
https://user-images.githubusercontent.com/14952174/138546507-43ba8dd1-89e3-452c-b5f6-7551eb50daa8.mp4
Note the 2 6-way modules, one with fuel pod already attached and one free.

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7402424/Player.log)

If you issue concerns a particular design please include 
any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.
[Station Modules.zip](https://github.com/tsunamayo/Starship-EVO/files/7402425/Station.Modules.zip)

**Comment by tsunamayo** [comment]
@Asnro I would say that module has been exported while being docked to that particular module. Could you try to re-export your module while not docked? Thanks

**Comment by tsunamayo** [comment]
@Asnro So for 21w48a I have made a change to clear the docking data upon blueprint export which should ensure this could not happen.
Thanks
