### ISSUE TITLE
Shipyard on child entity causes freezing & CtD on load

### ISSUE THREAD

**Issue by Asnro** [tsunamayo/Starship-EVO#4238]
### Short Description of the issue:

While experimenting with shipyard on a sliding rail I restared game and experienced a freeze/crash twice in a row while trying to load save.

### Steps to reproduce the issue:

- Put shipyard block on child entity
- Dock ship to shipyard
- Quit to title (freeze) or desktop (crash)
- Load game

### Environment
- Starship EVO version: 21w42a
- Graphics Card: RTX 3070

### Additional information:

[Crash_2021-10-24_163450201.zip](https://github.com/tsunamayo/Starship-EVO/files/7405904/Crash_2021-10-24_163450201.zip)

**Comment by tsunamayo** [comment]
@Asnro I didnt had any issues in my case. Could you send me your character save? Thanks
