### ISSUE TITLE
[Bug] Wood block not resizeable, stickers not visible on wood block

### ISSUE THREAD

**Issue by Regnion** [tsunamayo/Starship-EVO#4239]
### Short Description of the issue:

Wood blocks cannot be adjusted in size. Additionally, stickers placed on wood blocks are not visible.

...

### Steps to reproduce the issue:

Equip wood block, attempt to adjust sizes. Attempt to place stickers on placed wood block.

...

### Environment
- Starship EVO version: 21w42a

**Comment by tsunamayo** [comment]
The wood plank can now grid-scale. Thanks
