### ISSUE TITLE
[bug] steel material pain not working on decals

### ISSUE THREAD

**Issue by KINGrimson** [tsunamayo/Starship-EVO#4240]
### Short Description of the issue:
pretty simple the normal steel, like the hull doesnt work on stickers. others do work. 
...

### Steps to reproduce the issue:
place decal try to paint  with normal steel material paint
...

### Environment
- Starship EVO version: 21w42a
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@KINGrimson Fixed for 21w45b. Thanks
