### ISSUE TITLE
Long-distance glow for Switches misaligned

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4241]
Version: 21w42a

Long-distance glow for Switches is misaligned, both for the green and red lights.

![image](https://user-images.githubusercontent.com/63756057/138689693-ed571d0e-6566-4a15-81d1-c4c23f68faaa.png)

**Comment by zalexville** [comment]
I also have this issue. It tends to appear where my lights are when making prefabs. I am on the current build of the experimental branch, 21w46a

**Comment by tsunamayo** [comment]
@zalexville Yep I realized we had an issue with prefab and light, I will fix this.

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil @zalexville Issue fixed for 21w47c! Thanks
