### ISSUE TITLE
[BUG] Item stand completely broken when trying to spawn in handheld blueprints

### ISSUE THREAD

**Issue by zorozeenee** [tsunamayo/Starship-EVO#4243]
### Short Description of the issue:

When accessing the item stand in order to spawn a handheld gun, only the alphabetic first weapon appears and none others. Then if you access it again it duplicates it. This process can be repeated

### Steps to reproduce the issue:

1. Have at least 2 handheld blueprints stored
2. Access an item stand
3. Exit the item stand
4. access it again

### Environment
- Starship EVO version: 21w42a
- Graphics Card: GTX 1060 super

**Comment by tsunamayo** [comment]
@zorozeenee The UI issue when opening the stand was fixed in 21w45a. Thanks
