### ISSUE TITLE
Falling to the space

### ISSUE THREAD

**Issue by ElsonFX** [tsunamayo/Starship-EVO#4244]
### Short Description of the issue:
First i fall to the ground after using the jetpack, pass straight to the ground.
Second: i fall because i deleate the floor block, fall pass the terrain and ended in space.
Third i build a big block, not sure what happen, but it happen again.
No clipping command doesn't work.
...

### Steps to reproduce the issue:

...Just fall from somewhere high.

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@ElsonFX Hi, what version are you using? Thanks
