### ISSUE TITLE
Sticker preview broken 

### ISSUE THREAD

**Issue by timethatswasted** [tsunamayo/Starship-EVO#4245]
### Short Description of the issue:

Stickers don’t seem to preview properly on blocks over 4m.  You only see a little sliver of the sticker and if you stretch it, you can’t see the preview at all. Also stickers themselves large then 4m don’t really preview at all.

### Steps to reproduce the issue:

Place a 32m, 16m or 8m block.
Try and put any sticker on it of any size 4m and larger.

### Environment
- Starship EVO version: 21w42a
- Graphics Card: gtx 960m

**Comment by tsunamayo** [comment]
@timethatswasted I cant reproduce this. Do you see this in 21w45a? Thanks

**Comment by pinesh** [comment]
Can't reproduce this either, is the author referring instead to stickers on slopes?

**Comment by timethatswasted** [comment]
![20211112053648_1](https://user-images.githubusercontent.com/76059528/141462110-71d5c022-17f4-4c68-824d-4cc714f24f75.jpg)

21w45a
Here is a 32 sticker not previewing on a 32 block.  I placed a 32 starter block and put a 32 block on top of it.  Didn't matter how close or far away I was from it.  Though it does seems the game is very picky about how far/close you can be to a block when placing the sticker.  If I placed the sticker it would appear off center, switching to "target grid" seemed to fix the placement issue, but didn't fix the preview issue, but since its a fresh starter and block it should stick correctly using "global"

I am not getting the "only see a sliver" of the sticker effect on the square blocks since 21w45a, just on the angel blocks.

**Comment by tsunamayo** [comment]
@timethatswasted I can reproduce. It only show from afar, upclose indeed it dont show... I keep you posted.

**Comment by tsunamayo** [comment]
@timethatswasted Issue fixed for 21w47c. Thanks
