### ISSUE TITLE
Starship Evo bug

### ISSUE THREAD

**Issue by tofast10** [tsunamayo/Starship-EVO#4246]
### Short Description of the issue:

Can't access my world.

### Steps to reproduce the issue:

make sure to update your Gpu

### Environment
- Starship EVO version: early-access21w07a
- Graphics Card: Radeon RX 580 Series

### Additional information:

 You have to make a new world and play that world instead.

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@tofast10 Hi, sorry to hear about the bug.
So if you could give me data to investigate as for now I cant help you:
the log file:
Please also include the Player.log file. You can find the log file here: %UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\
The character save (zipped folder):
%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Characters\
