### ISSUE TITLE
Flood Light effect visible through blocks

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4249]
Version: 21w42a
GPU: 2080Ti

Flood Light effect is visible through blocks when the player is sat at any chair or yoke.
This happens on any chair and any grid, however, it's most profound when used with the grid in question.

[Here's a world file to replicate the issue.](https://github.com/tsunamayo/Starship-EVO/files/7492286/Experimental.zip)

![Starship_EVO_SKph027VSs](https://user-images.githubusercontent.com/63756057/140646230-5e08cd93-bb2d-4002-b137-b22af0857113.png)
![Starship_EVO_ra9yHZGry5](https://user-images.githubusercontent.com/63756057/140646237-18eb6483-a27f-4b48-8688-1d018553542f.png)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil well spotted, I spend a couple of hour on that I am still at loss on why this happens. I keep you posted once I fix that!

**Comment by pinesh** [comment]
The same issue occurs in photo mode.

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Woke up this morning and decided to fix that issue. Happy new year!

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo Haha, thanks! That is a very nice surprise! Happy New Year to you too!
