### ISSUE TITLE
[Problem] Heat dissipation seems off

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#4253]
### Short Description of the issue:

The surface heat dissipation feature appears to be turned off at present.

### Steps to reproduce the issue:

Build a ship and view stats within the codex.
Surface heat dissipation reads zero.

### Environment
- Starship EVO version: 21w45a
- Graphics Card: GTX1070

**Comment by tsunamayo** [comment]
Well I had some issues with it indeed, but I already refactored the system - it should be fixed in 21w45b. Thanks
