### ISSUE TITLE
[Suggestion] Damage sensor

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#4254]
With the new logic field element, I wonder if it is possible to detect damage within a region of a ship being piloted. That information could be displayed on a custom readout inside the flight deck (which I can build already). Alternatively the same process may be done more suitably with the sensor block, configured to detect damage to it's own grid entity.

So the use case is a live damage readout presented to the pilot/crew, which is then configurable within the ship design to identify damage to key areas.

I have been experimenting with display panels and Star Trek style ICARS displays, and the results are reasonable. It will be even better when the screen block formatting works properly within the actual screen size.

**Comment by tsunamayo** [comment]
Hi, well honestly dont hold your breath on that one, as it could performance heavy and I have plenty of more urgent things to do (gameplay....) Cheers
