### ISSUE TITLE
[QUESTION][BUG?] Generating custom stations

### ISSUE THREAD

**Issue by timethatswasted** [tsunamayo/Starship-EVO#4255]
Several experimental versions ago we had the ability to test the station spawning algorithm with our own modules, but that was removed  shortly after when the station starting block was removed.

I tried removing all the default SI station modules and replacing them with my own, but nothing generates at all.  All my docking connectors are good and I followed the same save settings for my modules as the SI stations use.

Are the SI stations just hard coded at the moment and the generation algorithm not able to accept custom stations? Or is this some kind of bug or error on my end?  I can provide a character save blueprints if needed.

Thanks

**Comment by tsunamayo** [comment]
@timethatswasted yep I plan to bring it back so you guys can test your station. stay tuned!
