### ISSUE TITLE
Fuel Consumption and Flow Rates/Experience So far. 

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#4256]
I've spent a reasonably large amount of time in Starship Evo and more recently with the new fuel system and I believe I'm ready to talk a bit about it.

![image](https://user-images.githubusercontent.com/14081996/141405123-7b92dabf-ca79-4cdd-bc78-c9bcbedee33a.png)
*whew, I could've learned the violin by now*

The primary struggle boils down to fuel consumption and thus flow rates. Currently, It's impractical, if not impossible to chain multiple fuel tanks around a ship. Hangers, Systems, and interior spaces be damned. 

![image](https://user-images.githubusercontent.com/14081996/141405714-0c4c4e77-215b-4aa4-9c8f-c5bd4dd56d7b.png)
As my crude mockup explains, the flow demands from a single tank to reactors present an inescapable issue when attempting to attach other tanks to the fuel lines. Since the pipe capacity is maxed out, the second tank needs to have twice the piping width to meet the demand of both tanks. Unless each ship is a perfect cube, there simply isn't any way to get fuel from one side to the other. 

Attaching each reactor to its own fuel tank doesn't help either as the total inter-tank demand doesn't change. 

In an example with 4 reactors, each needing 4, 4m diameter pipes (not unreasonable as I've encountered), the fuel network needed to connect the tanks to each other or to a connector would need to be 16m in diameter.  It is unreasonable to expect that any ship layout is capable of supporting a pipe of that diameter. 

![image](https://user-images.githubusercontent.com/14081996/141408164-76c94385-9b3c-40b9-aefb-97c5d8d4fe4d.png)
*21% heat and 175% power*

Here's a real-world example of my current ship. The top 2 reactors, which by themselves doesn't meet the power demands for an unfinished, mostly empty ship; require 5 8M pipes each, If I wanted to connect another fuel tank to the system. I'd need to use  at minimum, either 10 8m individual pipelines or 2 16m + 2 8m pipelines . Most of the available space for fuel tanks is _smaller_ than the space required for the pipes to meet demand. 

![image](https://user-images.githubusercontent.com/14081996/141408220-a1c6eb17-3353-4c07-a0fa-6a7780ba5718.png)
*This block wouldn't handle the full demand on its own*

in the case of my ship, despite having a 16x16m space more than 200m long, I cannot put a single fuel tank inside it as the pipe space required exceeds the available surface area. 

![image](https://user-images.githubusercontent.com/14081996/141408354-006f0153-9845-40ae-bd23-bcbe2191351b.png)
*this entire space can't even handle the pipe demand of half of the reactors needed for the ship to operate, fuel tanks couldn't be chained together, and using the space for anything else would escalate the problem*

I can only imagine this issue would escalate even more so if you finalize your plan to require LC thrust to be piped as well. 

The real kicker?
**There's only enough fuel for 28 minutes of flight**

I'm aware that you've previously stated that the current rates are subject to change and believe doing so is the simplest course of action. I propose at the very least, fuel consumption be reduced 8-fold. Doing so would reduce the pipe strain immensely.

Pipes should be a mechanic, not a design determining factor and I hope you'll consider adjusting this in the near future.

Thank you, 

Harry

**Comment by tsunamayo** [comment]
@pinesh Hi - thanks for the feedback (and for playing...) . So it seems it is a problem with the fuel flow being too low for pipes.
If I recall I calibrated the thing so that a single 0.25 pipe can fuel a 2x1m reactor at 1m grid scale.
Now I will need something more precise to understand what your did, ie the size of your reactor and most importantly the grid you used. Grid adds complexity as small grid reactor are much more powerful compared to large one, and of course would have much bigger fuel requirement relative to their size.
So if you build small grid reactor with a high stretch (ie a 4x4x4m with 0.25 grid) I am not surprise this needs big piping.

**Comment by pinesh** [comment]
@tsunamayo 
Thank you for getting back to me so quickly!

All the reactors in question used the 2/4m base, Attached is the ship blueprint, (It's quite large and is desperately awaiting a return of missiles!)

My best suggestion would be, using the blueprint, to try to build a fuel tank in a space at the front, and figure out how to pipe it to the back in such volume so as it doesn't starve the reactors.
[DH-Covenanter-67-t.zip](https://github.com/tsunamayo/Starship-EVO/files/7525575/DH-Covenanter-67-t.zip)
