### ISSUE TITLE
Arch bricks lighting issue

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#4258]
Pretty simple:

The blocks are white but the arch brick doesn't reflect light so it looks darker.

The arch brick is streched ... but even the non streched ones look darker!

![20211115185042_1](https://user-images.githubusercontent.com/81495956/141838513-aa4e3cf5-9a0c-4d90-9bb3-8814510a8053.jpg)

**Comment by tsunamayo** [comment]
@BigBadKangaroo This was fixed in 21w47b. Thanks!
