### ISSUE TITLE
[Bug] Surface area/Heat dissipation increases massively with each block placed

### ISSUE THREAD

**Issue by Asnro** [tsunamayo/Starship-EVO#4261]
### Short Description of the issue:

Each time a block is added to a blueprint the surface area increases by several hundred m2 and heat dissipation increases by several thousand h/s. Removing the added block does not reset this, spawning in a fresh blueprint sets surface area to 1m2 and heat dissipation to near zero.

### Steps to reproduce the issue:

Place and remove blocks from a blueprint several times while keeping an eye on heat stats

### Environment
- Starship EVO version: 21w46a
- Graphics Card: RTX 3070

### Additional information:

Note Surface Area
![pic1](https://user-images.githubusercontent.com/14952174/142338732-0d4becd7-7d39-4fe7-b47a-11f6b8e2eb79.png)

Note Heat Dissipated stat
![pic2](https://user-images.githubusercontent.com/14952174/142334760-792f73ec-171c-4e8b-b0aa-20f2a8fcd731.png)

[Player.zip](https://github.com/tsunamayo/Starship-EVO/files/7559156/Player.zip)

[Blueprint tested on](https://github.com/tsunamayo/Starship-EVO/files/7559161/GT.F-140.zip)

**Comment by tsunamayo** [comment]
@Asnro indeed, I have just repushed the build with the fix as it was a regression. Thanks!
