### ISSUE TITLE
[BUG] sound settings do not work 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#4263]
### Short Description of the issue:
despite my sound settings set to 0 i can still hear in-game audio  

EDIT: inventory sounds do get turned down but not all sounds do
### Environment
- Starship EVO version: 21w46a
### Additional information:

A bit loud

https://user-images.githubusercontent.com/56371294/142514489-5cc1ba17-5e18-4907-a785-95f2a2310251.mp4

**Comment by tsunamayo** [comment]
@TIKIRobo Indeed, issue fixed for 21w47c. Thanks
