### ISSUE TITLE
[Bug] Gatling barrels turn invisible when a blueprint is reloaded

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4264]
### Short Description of the issue:
When a laser brick with a gatling barrel is reloaded (load the world, or spawn a bp), the gatling barrel brick turns invisible and the gun unlinks itself from any event gate that was linked to it

### Steps to reproduce the issue:
- Place a laser brick with a galting barrel on it on a new grid
- Unspawn the bp
- Spawn the bp, the gatling barrel will be gone. Physically it is still there as the collision box is still present, but you must remove it before attaching a new barrel
![image](https://user-images.githubusercontent.com/27857711/142649939-fcd1f490-6947-4f50-9ea7-0c1e3e84e3e9.png)

### Environment
- Starship EVO version: 21w45a
- Graphics Card: RX 580

### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7571302/Player.log)

**Comment by tsunamayo** [comment]
@ProPeach This is fixed for 21w47c. Thanks!
