### ISSUE TITLE
Problems with pipes

### ISSUE THREAD

**Issue by Foofaspoon** [tsunamayo/Starship-EVO#4265]
Just come back to the game after a long while, wanted to play with the new pipes / fuel. Unsure if I am doing it wrong, or there is a problem. While trying to connect tanks to the reactor, fuel was not transfered unless there was a pipe connecting them (ie couldn't add fuel tank directly to the reactor). Also, the multi way pipe connector seems to show this too.. to get it work I had to do tank - pipe - connector - pipe - reactor. This made it complicated, and I came up with some convoluted system to connect four tanks together using the connectors. This sort of worked, except one of the fuel tanks didn't drain. Also, if fuel is left in the pipes after a tank has been drained, the reactor doesn't pull that through.

I am confused if I am doing it wrong or if this is a bug?

**Comment by Foofaspoon** [comment]
Another issue, sorry! When you have multiple fuel tanks connected separately to the reactor, the fuel is drained out of them much faster than a single fuel tank of equivalent total volume. What I think is happening is that the reactor calculates the fuel it needs - but then takes that from all of the connected fuel tanks each (rather than dividing that need between them all)

Build is 21w45a

**Comment by tsunamayo** [comment]
Hi, let me check those issues. For now you can link a tank to a reactor directly indeed, you need to use pipes. I will try to change this!

**Comment by Foofaspoon** [comment]
Hi, thank you! I worked out why only one of my tanks didn't get drained when I had set up my arrangement - it was touching the reactor. Even though it had a legitimate pipe route, that the other tanks all used, touching the reactor stopped it draining.
