### ISSUE TITLE
[Bug] Green damage overlay is always visible

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4266]
### Short Description of the issue:
Previously this green overlay was only shown when holding the repair tool. Now, it shows all the time including when piloting a ship shooting at the target which looks strange.

I'm guessing this was implemented for the new tutorial - Perhaps the green overlay could be enabled only when holding the repair tool, or when the ship you're flying has a repair beam hooked up to its hotkeys rather than always visible

### Steps to reproduce the issue:
Damage a ship 

### Environment
- Starship EVO version: 21w46a
- Graphics Card: RX580

### Additional information:
![image](https://user-images.githubusercontent.com/27857711/142766771-8f4123b7-f54a-45a1-933c-d4a354e1baa2.png)

**Comment by tsunamayo** [comment]
@ProPeach Yep this I reproduce! Cheers

**Comment by tsunamayo** [comment]
@ProPeach This was actually fixed for 21w47b. Cheers!
