### ISSUE TITLE
[Bug] F1 build menu settings do not save between game launches

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4267]
### Short Description of the issue:
Whenever you quit to desktop and relaunch the game, the settings in the F1 build menu reset to default. This means that the first thing I do whenever I load a world has to be opening up the menu to input my preferred settings again

### Steps to reproduce the issue:
- Open the F1 menu and change some settings
- Quit to desktop
- Launch the game, load a world and check the F1 settings

### Environment
- Starship EVO version: 21w46a
- Graphics Card: RX580

**Comment by tsunamayo** [comment]
Hi, weirdly it works fine for me... I will see if I can reproduce.

**Comment by ProPeach** [comment]
How strange! I'll get some player logs to see if they'll have anything in that could help

**Comment by ProPeach** [comment]
I should note, this bug also happens with all the settings in the F3 menu. Usually I always enable fast move keys and teleport to all ships options every session

Here's a log of booting the game, loading a world and changing the settings then quitting -
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7577376/Player.log)

And here's the log of the second session, loading up the world to find that the settings have reverted to default - 
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7577377/Player.log)
 
 @tsunamayo let me know if there's anything else I can do from my end o/

**Comment by CurioInventorium** [comment]
Setting up fast move in the F3 menu is something I've always done opening each session as well. And I think it's been raised before too.
I just figured other bugs had higher priority.

**Comment by tsunamayo** [comment]
@CurioInventorium  this is not a bug, F3 are debug options and debug options are not saved (and wont be !). But F1 is a proper bug.

**Comment by tsunamayo** [comment]
That being said I might move the fast move key to the F1 menu, as if you plan to build very large you kind of need those... But I would not allow those for survival (otherwise you can get anywhere you want easily...)

**Comment by ProPeach** [comment]
> That being said I might move the fast move key to the F1 menu, as if you plan to build very large you kind of need those... But I would not allow those for survival (otherwise you can get anywhere you want easily...)

I was going to suggest this too, the fast move keys are great as a build tool even if you're not making anything particularly large. It's just such a useful feature to use for moving around!

**Comment by tsunamayo** [comment]
@ProPeach Issue fixed for 21w47c. Thanks ^^
