### ISSUE TITLE
[Bug] Paint turning en-masse into decals after patch

### ISSUE THREAD

**Issue by Gallt** [tsunamayo/Starship-EVO#4271]
### Short Description of the issue:

... loaded in, and on all my large ships, most of the paint would have these little colorable sections. if i deleted the block and placed a new one, the decals would come back. Ships where i'd used 0 decals (such as my largest) had 75k. CAN mass delete, but the lag is tremendous. Tried new game, tried workshop and local spawning, all had same issue

### Steps to reproduce the issue:

... just load the blueprint

### Environment
- Starship EVO version: 21w47a
- Graphics Card: GeForce GTX 1660 Ti

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

![1](https://user-images.githubusercontent.com/94942440/143159602-a3f5be3c-699b-4dbb-9c45-6f91db0085f5.JPG)
![2](https://user-images.githubusercontent.com/94942440/143159606-e663c54e-ddda-4e7b-80ed-a4ad58b91f86.JPG)
![3](https://user-images.githubusercontent.com/94942440/143159607-181a6d4f-a7f3-405d-adbd-c7dd1d289c62.JPG)
![4](https://user-images.githubusercontent.com/94942440/143159609-a4a0138e-49bf-418b-a4b6-93e03c443708.JPG)
![5](https://user-images.githubusercontent.com/94942440/143159610-da19cd7e-0cd9-4ed5-baed-e0440ec134d0.JPG)
![6](https://user-images.githubusercontent.com/94942440/143159611-27acc762-0ae8-4854-9572-8a21e9f8a633.JPG)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7592272/Player.log)
[KeldableBAttle21NEARDONEHULL2.zip](https://github.com/tsunamayo/Starship-EVO/files/7592277/KeldableBAttle21NEARDONEHULL2.zip)

**Comment by Uncle-Ulty** [comment]
that's the novox conversion... the old voxel system is dead, and the way it was painted in the past (block by block) doesn't exist anymore. decals were created on the previously painted blocks. You can set the delete tool to work on decals only, if you want to remove them. Decals remain in the same place if they aren't deleted, even if there isn't any block for them to paint.

**Comment by Gallt** [comment]
yep, but wanted to submit anyway since it was so ubiquitous.

**Comment by tsunamayo** [comment]
@Gallt yes unfortunately this is not great for such massive ship... There is nothing I can do at this stage. You should be able to mass delete with the Box Delete on Decal Only option in the F1 option... That being said it should not lag too much if you do it on reasonable selection...
Thanks
