### ISSUE TITLE
[Bug] Warning messages dont show up while controlling the ship

### ISSUE THREAD

**Issue by Slyack** [tsunamayo/Starship-EVO#4274]
I have connected an yoke to event gate and this event gate pushes a piston once activated. However the same event gate is as well connected to a warning message which doesn't show up. Same message tho shows up if I just use button for example to activate it.

Starship EVO Experiemental

**Comment by tsunamayo** [comment]
@Slyack Hi, thanks for booking the issue. Fix will be available in 21w47c. Thanks!
