### ISSUE TITLE
Overheating And Cooling

### ISSUE THREAD

**Issue by Reason147** [tsunamayo/Starship-EVO#4276]
### Short Description of the issue:

I...Not sure if this is a bug or something wrong with my builds, I have a few ships that are now unuseable because of overheating those ones worked fine.  Before the new builds This ship I linked below never overheated at spawn now it's become useless, I don't have time to rebuild a bunch of ships with this problem worst comes to worst I'll just delete them altogether, I don't need useless junk. I need useful crafts.

Sub Class Cargo Lift Ship
https://steamcommunity.com/sharedfiles/filedetails/?id=2596989234

SCTA Combat Shuttle T1 2 & 3
https://steamcommunity.com/sharedfiles/filedetails/?id=2595232648

SAC Fuel Ship
https://steamcommunity.com/sharedfiles/filedetails/?id=2593248700

### Steps to reproduce the issue:

... Need a better cooling system or a fix? A Cooling Core

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Reason147 Hi, what kind of heat generated / dissipated % did you had before the patch? The computation changed a bit but the effect should not be too drastic though.
Thanks

**Comment by Reason147** [comment]
Normally I keep the heat below 75 - 60% on all ships Now I'm seeing spikes as high as 125%, 105% 118% high numbers when it shode be around 65% or so. I'm not sure if it's the builds themselves or a bug.  At spawn in the heats spiked bout after a few scenes, it drops down to the 50 60 or 70% norm. I'm not seeing that now it stays over 100%.

Here are 2 screenshots of the same ship you can clearly see the different one is pre-update, the ship has been tweaked a bit after the first screenshot was taken.
[https://steamcommunity.com/sharedfiles/filedetails/?id=2663663658](url)
Pre update
[https://steamcommunity.com/sharedfiles/filedetails/?id=2663661454](url)
after update 

I noticed this on a few of my builts.

**Comment by tsunamayo** [comment]
@Reason147 yes small block are much less thermal efficient, they will create a lot of heat compared to larger system.
I will wait from other builder feedback to see if we really have an issue - if yes I will bump up the surface values. The way the older system was working was too kind with mini children entity, now it is more accurate, that might explain the gap as those are not big ships. 
Thanks

**Comment by Reason147** [comment]
Just an Idea perhaps smaller ships will need some kind of cooling unit to help with the heating problem building a decent small ship like a shuttle and having it useable is hard without it cooking its self to death.  larger ships don't have this problem. At some point, I'm going to make a video explaining this a better in building small crafts.

**Comment by Kadzar** [comment]
I've also noticed this with my Harlequin Fighter [KSE Harlequin Fighter 1.1.zip](https://github.com/tsunamayo/Starship-EVO/files/7611066/KSE.Harlequin.Fighter.1.1.zip)

I'm not sure how much the heat has increased for it, but I do have a screenshot from my Sunfish Fighter from before:
![20200726001026_1](https://user-images.githubusercontent.com/66035211/143665370-16871c93-c544-4454-bd7f-460dd6cb5cfc.jpg)

And here's where it is now:
![20211126202939_1](https://user-images.githubusercontent.com/66035211/143665402-9623b200-c45b-468f-8ec7-dc39a94d5724.jpg)

And, if necessary, here's the Sunfish blueprint, which hasn't changed between those two screenshots
[KSE Sunfish Starfighter.zip](https://github.com/tsunamayo/Starship-EVO/files/7611076/KSE.Sunfish.Starfighter.zip)

I also noticed that the Canis-Class Interceptor on the ringworld also has this overheating problem.

**Comment by tsunamayo** [comment]
@Kadzar yes it has been reported - I will do something about it.

**Comment by tsunamayo** [comment]
@Reason147 Fixed for 21w48a. The sad truth is I had to revert it to the wrong and slower older way to ensure blueprint compatibility as people dont want to retouch their ship.
Cheers
