### ISSUE TITLE
Graphics Options: Framerate Returns to 165 htz when set manually to another (lower) framerate

### ISSUE THREAD

**Issue by MystLeissa** [tsunamayo/Starship-EVO#4277]
### Short Description of the issue:

I'm trying to set my refresh rate to 59 hz, to prevent my Desktop's Fan from running constantly (It's a bit loud), but every time I lower the refresh rate in options it resets to 165hz after i reopen the dialog
...

### Steps to reproduce the issue:

1. Open Options
2. Change Display Settings to 1280 x 800 @ 59hz
3. Exit Options (X Button)
4. Open Options again
5. Note that the refresh rate is now @ 165 hz
...

### Environment
- Starship EVO version: earlyaccess21w74b
- Graphics Card: AMD Radeon 5700 XT 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player.txt](https://github.com/tsunamayo/Starship-EVO/files/7598047/Player.txt)

**Comment by tsunamayo** [comment]
@MystLeissa Hi, this should be fixed for 21w47c. I cant test though as my monitor only support one resolution. Thanks
