### ISSUE TITLE
World not fully loading

### ISSUE THREAD

**Issue by FsFireFly** [tsunamayo/Starship-EVO#4278]
### Short Description of the issue:

ship built in previous version before todays update now does not fully load and disables most of the game features. Please note: Ship is very big and takes time to load. Ship is also available on steam workshop titled USS Darlington

### Steps to reproduce the issue:
Loading any of the files I have attached in latest version of the game causes issue.

### Environment
- Starship EVO version: 21w4b
- Graphics Card: NVIDIA GeForce GTX 960

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.
[World1.zip](https://github.com/tsunamayo/Starship-EVO/files/7599036/World1.zip)
[World1-20211104.zip](https://github.com/tsunamayo/Starship-EVO/files/7599037/World1-20211104.zip)
[Blueprints.zip](https://github.com/tsunamayo/Starship-EVO/file
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7599049/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/7599050/Player-prev.log)
s/7599038/Blueprints.zip)

**Comment by tsunamayo** [comment]
@FsFireFly Hi, I cant find the ship on the workshop, do you have a link? (the zip was not uploaded successfully too)
Thanks

**Comment by FsFireFly** [comment]
@tsunamayo Hey, Here is the link to it: https://steamcommunity.com/sharedfiles/filedetails/?id=2629553091
[World1.zip](https://github.com/tsunamayo/Starship-EVO/files/7599519/World1.zip)

**Comment by tsunamayo** [comment]
@FsFireFly Hi, the ship can now load in 21w47c. This ship is honestly way too much, it lag like crazy. It is all because of over-use of text-screen and system screen. There are over 40000 of them!. This will be optimized at one point which will help, but still you are using way too much of these and thruster too.
I can optimize things only so much, but at the end it is the responsibility of the builder to do something that dont lag too much!
Cheers
