### ISSUE TITLE
Can't place items on item stand

### ISSUE THREAD

**Issue by PizzaKing32000** [tsunamayo/Starship-EVO#4279]
### Short Description of the issue:

I cannot place items on the item stand

### Steps to reproduce the issue:

Try to place an item on the item stand

### Environment
- Starship EVO version: early-access 21w47b
- Graphics Card: NVIDIA GeForce RTX 2070

### Additional information:

The game did not crash, I just can't put things on the item stand, every time I try, it just goes to the next empty slot, even if it is on another hot bar, the only way I have been able to place an item on the stand is by filling every slot of every bar and then placing the item on it.

**Comment by tsunamayo** [comment]
@PizzaKing32000 Issue fixed for 21w47c. Thanks
