### ISSUE TITLE
Lobby area corner collision

### ISSUE THREAD

**Issue by Tisdag1** [tsunamayo/Starship-EVO#4280]
### Short Description of the issue: There is an issue in the lobby area with all the shops/kiosks. In all four corner areas there seems to be an invisible barrier that you bump into and can't get past unless you jump or press F5. I am assuming it's probably be a collision issue.

...

### Steps to reproduce the issue: When you get to the lobby area with all the kiosk & shops try walking into the corners with the pillars.

...

### Environment
- Starship EVO version: 21w47b
- Graphics Card: 

### Additional information:
![Sevo Corner Bug](https://user-images.githubusercontent.com/95005604/143366291-31e82147-4170-4335-8673-10839f6ed992.jpg)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7599700/Player.log)
 include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Tisdag1 Hi, thanks for booking the issue. Fixed for 21w47c. Cheers
