### ISSUE TITLE
Tutorial and Medbay sounds still audible

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4281]
Version: 21w46b

Hey, Tsuna!

I've noticed that the Medbay "body printing" and Tutorial sounds are still there despite the fact that I turned them all down to 0.

**Comment by Kaiser-Indrasil** [comment]
Same deal with the Repair Beam sounds

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Indeed, those where newly implemented in FMOD and I didnt routed them. Fixed for 21w47c. Cheers
