### ISSUE TITLE
Blueprint Failed to Save

### ISSUE THREAD

**Issue by DarthPeter0** [tsunamayo/Starship-EVO#4284]
### Short Description of the issue:

I received an error message that my ship was unable to save.  I believe this is the same bug that has been deleting ship saves in the past.

### Steps to reproduce the issue:

Load the attached blueprint.  Before I received this error, I was attempting to paste in some thruster prefabs onto a pair of rotors.  They were not lining up with the ship grid (no matter which settings I chose or what grid size I selected, the thrusters were always a tiny bit off.  After pasting the thrusters on incorrectly, I deleted the rotors to clear the prefabs and try again.  The prefabs left behind some ghost entities (they appeared to be rotor and hinge heads).  When I tried to delete these ghost blocks, I received the error that the ship was unable to save.

The good news is that it appears the game did a rollback to right before I deleted the rotors, and it looks like my blueprint is still intact.  I deleted the rotors AGAIN after a game reload, but this time nothing weird happened.

### Environment
- Starship EVO version:  Experimental 21w47c 
- Graphics Card: Nvidia GTX 1060

### Additional information:

Grid not lining up:  

![20211126194116_1](https://user-images.githubusercontent.com/33942288/143667366-15aa8c4a-dde4-4b10-90cd-1b510beb988f.jpg)

Log:

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7611158/Player.log)

[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/7611162/Player-prev.log)

Blueprint: 
[StealthyBoi1.zip](https://github.com/tsunamayo/Starship-EVO/files/7611163/StealthyBoi1.zip)

**Comment by tsunamayo** [comment]
@DarthPeter0 Okay that for booking this I will have a look.
I guess the good news is that safe-guard did their job as you did loose any major work here unlike last time...
So I take that as a plus.
I will try to reproduce and get back to you!
Thanks

**Comment by tsunamayo** [comment]
@DarthPeter0 well actually I just fixed that exact same issue here #4286. Nice plane with a YF-23 look, which is one of the all time best looking plane! Cheers
