### ISSUE TITLE
Bevel collision is off

### ISSUE THREAD

**Issue by thatisjake** [tsunamayo/Starship-EVO#4285]
The "Bevel" brick collision is the whole block instead of being reduced.

### Steps to reproduce the issue:

-

### Additional information:
![image](https://user-images.githubusercontent.com/40440275/143669866-cb73a6e7-74e8-410a-9fbb-a19e84fe4867.png)

Blue is the moving part stopped by the red, which should clearly be able to rotate up.

**Comment by Kaiser-Indrasil** [comment]
That's because the collision mesh of the bevel block is a cube, so if you need proper collision detection there, use the ramp blocks of the smaller scale instead.

**Comment by tsunamayo** [comment]
@thatisjake Hi, this is fixed for 21w48a.
