### ISSUE TITLE
Hinge Visual Bug

### ISSUE THREAD

**Issue by thatisjake** [tsunamayo/Starship-EVO#4286]
### Short Description of the issue:
When a hinge is on a child entity, and the hinge is copy pasted, (onto same CE) there is a small visual bug.

### Steps to reproduce the issue:

Hinge on CE, copy and paste.

### Additional information:

![image](https://user-images.githubusercontent.com/40440275/143670823-7a6b0185-d95b-42e4-8667-7b6e9909b44c.png)
Blue is on the hinge, and the red part should be facing into the blue. (from original part). When I pasted, it looked like this about 50% of the time.

**Comment by tsunamayo** [comment]
@thatisjake Hi, thanks for booking this! Issue fixed for 21w48a. Cheers
