### ISSUE TITLE
Gravity Generator not working

### ISSUE THREAD

**Issue by Asnro** [tsunamayo/Starship-EVO#4287]
### Short Description of the issue:

Entering a gravity field does nothing - no reorienting, walk mode or matching ship speed

### Steps to reproduce the issue:

- Place gravity generator
- Enter field in gravity-orient jetpack mode

### Environment
- Starship EVO version: 21w47c
- Graphics Card: RTX 3070

### Additional information:

![kuva](https://user-images.githubusercontent.com/14952174/143672181-bb3981b9-8d95-4bfd-9bca-19231d43859d.png)

[Player.zip](https://github.com/tsunamayo/Starship-EVO/files/7611365/Player.zip)

**Comment by TIKIRobo** [comment]
this is because gravity gens only effect you when you are in the ship's bounds
its a bit weird but gravity still works for me

**Comment by Asnro** [comment]
> this is because gravity gens only effect you when you are in the ship's bounds its a bit weird but gravity still works for me

This was happening inside a ship, the screenshot is simply demonstrating the gravity field's range.

However, unspawning a ship without a gravity generator suddenly made gravity generators work, not sure how or why

**Comment by tsunamayo** [comment]
@Asnro Do you reproduce this all the time after loading a new world? If yes could you send me the world? Thanks

**Comment by commche** [comment]
I'm having the same issue. I don't know if gravity is always on regardless of the on / off state of the gravity generator, or if gravity is not on at all. Either way, switching gravity on or off has no effect. This is the case for all the ships in the attached world. Both ships were built in the old default build. The world was created yesterday with the latest version.

[test 1.zip](https://github.com/tsunamayo/Starship-EVO/files/7630799/test.1.zip)

**Comment by commche** [comment]
I just started a new save and now gravity works. Wierd. Went back to the test 1 world. Not working at all.

[test 2.zip](https://github.com/tsunamayo/Starship-EVO/files/7631001/test.2.zip)

**Comment by tsunamayo** [comment]
@commche Where those ship built by you? The issue is that their gravity units are deactivated, so no gravity is applied at all.
The gravity test platform works fine for me on the other side... 
Are you 100% sure that you can boot the game, jump into test 1 world, and dont have gravity for the platform?

**Comment by tsunamayo** [comment]
@Asnro @commche so I finally spotted a flaw in the code that explained the issue. Fixed for 21w48b!
