### ISSUE TITLE
Heat system unintended changes?

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Starship-EVO#4288]
There has been a change to the heat system, either intended or unintended, this greatly impacts medium to smaller ships and aircraft. 
Something was adjusted that caused all of my small ships to gain anywhere from 80% to 110% of heat generation. I have not built since the industrial screenshot comp of which all of my ships heat balance were perfectly laid out including fuel tanks and every other update to the systems, of which the heat was balanced perfectly.    

Now having some free time to log in and relax a bit while building something, I see I cant fly any of my ships due to the heat being improperly balanced yet again. This is very disheartening and has had me loose all motivation to even build in the game. 

If the heat system is to remain in the game it needs to be solidified as a core integral part of the game and then never touched again. That way our builds are not a waste of time due to a major component of the game not being solidified. 

The heat system in its current form is a stressful cage for those of us that have finished ships and worked around the heat balance. Getting this solidified as a core aspect of the game, having a hybrid system implemented, or just getting rid of it entirely should be a top priority. 

Personally, I truly do love this game I have been here since 2017, but if something is going to be this frustrating to continue to have to refit my ships every time the heat system has a slight change, its not worth the stress.  I do hope this is a bug and not an intended change that was not mentioned

...

- Starship EVO version: 21w47c
- Graphics Card: 1080ti

**Comment by tsunamayo** [comment]
@ExodistSKY1 Hi, the way surface is computed has been improved and optimized a week ago. 
The old way was being too generous for small children entity.
If you can send me blueprint with the value you had before I will have a look at it. No need to be dramatic about it, there are bugs, I will make sure to have your ship compatible again. Thanks

**Comment by ExodistSKY1** [comment]
Hi Tsuna, coming off of a stressful month and a half, I finally found some time to play the game a bit, and then every ship I get in turned into a paperweight. It is kind of funny now, but yes the post was dramatic, probably should have waited a bit and thought it through before posting. 

The dates for certainty on correct heat is September 18th, could be later as you had stated a recent change this past week.

The BP's are being emailed to you via your Gmail, in a zipped file

**Comment by tsunamayo** [comment]
@ExodistSKY1  Fixed for 21w48a. The sad truth is I had to revert it to the wrong and slower older way to ensure blueprint compatibility as people dont want to retouch their ship.
Cheers
