### ISSUE TITLE
[bug] mysterious paste object

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#4290]
For some unknown reason, 5URG3's station dead-end cap appeared as a "copied" object, and I can place it.

![image](https://user-images.githubusercontent.com/73253472/143726369-e1e5c9e7-559f-4ce3-9558-f99d4bd8c235.png)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7612695/Player.log)

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hi, well you will need to give more info on how this happened, what did you do before that? Thanks

**Comment by Uncle-Ulty** [comment]
I was building a ship... I have no idea why this happened and what triggered it...

sometimes I think this game is haunted, due to some very strange bugs xD

**Comment by tsunamayo** [comment]
@Uncle-Ulty well you must have lest been using copy-paste right?

**Comment by Uncle-Ulty** [comment]
ofc, I guarantee you that I didn't copy a station entire module... I was building a ship, no way I'd copy a station module.

I will pay attention to this in the future...
