### ISSUE TITLE
[Suggestion] Mission menu in codex

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#4291]
Something that be nice for the codex is a mission bar with all your current/active, tracked, and maybe even completed in some sub archive. It would also be nice to have some controls like canceling a current mission or even accepting one from say a nearby source so you don't have to walk to the mission board each time

**Comment by Kaiser-Indrasil** [comment]
So like a mission journal

**Comment by ZachZent** [comment]
Essentially, though mission menu does have alliteration

**Comment by tsunamayo** [comment]
@ZachZent Yep this is planned of course, there is even a button in the codex already (but the hard wip part is to save the mission state) Thanks
