### ISSUE TITLE
Can't build handheld weapons

### ISSUE THREAD

**Issue by Murkorus** [tsunamayo/Starship-EVO#4292]
### Short Description of the issue:

When trying to build a handheld weapon, the handle appears in an unreachable place, and cannot be interacted with, except for picking it up. When picking it up, you just get an empty slot and 2 bars for energy and heat when selected, but it can't do anything.

### Steps to reproduce the issue:

Build an item stand, select handle in your hotbar, press f on the item stand with handle selected.

### Environment
- Starship EVO version: early-access 21w47c
- Graphics Card: NVIDIA GeForce GTX 1650

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![image](https://user-images.githubusercontent.com/95182180/143782170-3c682b77-d80f-4604-a32b-36bfb6cb81f2.png)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7614166/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by ProPeach** [comment]
I have nothing to add to the bug report - but when handhelds come back, will we be able to scale the bricks down to 1/8th on top of the handhelds inherent half scale? Previously, handhelds already felt cartoonishly large and unpractical. Halving their scale compared to how they were before neovox with the 1/8th scale would help this out a lot!

**Comment by KieroVance** [comment]
OOF, I was hoping this was something normal and fixable, but it also persists for me to new worlds, I hope this gets fixed, because I legitimately cannot make handhelds at all, good to know others are having it(since that means it's not something mainly on my end)

**Comment by KieroVance** [comment]
![image](https://user-images.githubusercontent.com/20882155/144511385-09327d0e-0d4e-44f8-b174-6ae1b4ad1ccb.png)
screenshot showing that it also has its outlines(the hitboxes maybe? I dunno sorry)

figured this could also help, as it shows it out of line to what is showing visibly

**Comment by tsunamayo** [comment]
@Murkorus @KieroVance Handheld issues fixed for 21w49a. Thanks!
