### ISSUE TITLE
lights don't change visible color when painted, only emitting light

### ISSUE THREAD

**Issue by commche** [tsunamayo/Starship-EVO#4295]
![image](https://user-images.githubusercontent.com/92918376/143809662-a20c45d7-fc6a-453a-8604-646fa473364a.png)

**Comment by commche** [comment]
so you're getting the white light as well. this is especially bad with cylinder lights. the white drowns out any other color

**Comment by commche** [comment]
also, if you paint over a coating with a paint, you can't paint the coating back

**Comment by commche** [comment]
and you can't remove coatings once they are painted. maybe that's the bug. You can remove paint, but not coatings. Only way is to delete and rebuild the block

**Comment by tsunamayo** [comment]
@commche Hi, I see indeed the glow was too strong. I tweaked the texture, it will be better in 21w48a. Thanks!
