### ISSUE TITLE
can't delete coating paint

### ISSUE THREAD

**Issue by commche** [tsunamayo/Starship-EVO#4296]
you can't remove coatings. you can remove paint, but not coating. Only way is to delete the block and repaint it.

**Comment by commche** [comment]
there's something really  weird going on with the painting system. you can 'unpaint' colors and coatings that don't exist. You can't unpaint the 'steel' coating unless you first unpaint another coating - even though none of them were actually painted in the first place..lol something is not right here

**Comment by tsunamayo** [comment]
@commche Hi, these are not coating, these are material. When you "paint" a new material you swap its material.
Material will have real world cost and different property once the survival element is more advanced.

It is a bit confusing as we are using the same effect as the paint, so I will improve this.
Maybe also removing a material should means get it back to steel!

**Comment by tsunamayo** [comment]
@commche So for 21w48a you can "unpaint" material, which means making them back to steel.
You have to think about material:
- you can paint over a piece of gold. If you remove that paint you see the gold back
- It does not make sense to have no material, it always have to be made of something. Whereas you can have no paint.
 
 Thanks
