### ISSUE TITLE
volumetric sensors are not working at all

### ISSUE THREAD

**Issue by commche** [tsunamayo/Starship-EVO#4297]
### Short Description of the issue:

volumetric blocks not triggering sequencer blocks or bulkheads

### Steps to reproduce the issue:

connect volumetric to sequencer to any moving block 

### Environment
- Starship EVO version: latest update nov 29 2021
- Graphics Card: radeon armor rx570

### Additional information:

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7615762/Player.log)

**Comment by cloisterbell** [comment]
I have the same problem after Nov 29 update. My ship has a lot of opening doors controlled with volumetric sensors or beam sensors. Now neither works for any door.

**Comment by tsunamayo** [comment]
@commche @cloisterbell well it is working fine on my side, so could you please send me your blueprint so I can have a look? Thanks

**Comment by commche** [comment]
I've sent you my ship which has sensors for nearly every door, and I set up a little test area with various applications of the sensors. None of the sensors on my ship or in the test area work. The ship was created using the old default build. The test area was built today in the latest version. Hope this helps. 

[Daedelus Mk II.zip](https://github.com/tsunamayo/Starship-EVO/files/7630751/Daedelus.Mk.II.zip)
[sensor test.zip](https://github.com/tsunamayo/Starship-EVO/files/7630755/sensor.test.zip)

**Comment by commche** [comment]
Okay in this new world (test 2) some of the sensors work in the Daedelus ship, but only if you stand or hover in certain positions. Not all of the detection field area seems active. Some doors respond on the top floor and the server room door to the back cargo bay responds if you stand in a certain place within the detection field, most of the others don't respond at all. I can't really see any pattern of any kind. On a nearby platform in space, I've set up a door and a sensor, but it doesn't work at all, no matter where in the detection field you stand. Is this like emergent AI fucking with us? lol! Anyway I uploaded the world for you to test.

Also, I hate to say, but no matter where I save the game, when I reload the world, Im materializing in the med-bay. I didn't finish the tutorial in this save, so maybe that's why. But it looks like the tutorial code fires if you re-enter a world having not completed it previously. (gravity is working in this save too)

[test 2.zip](https://github.com/tsunamayo/Starship-EVO/files/7631092/test.2.zip)

**Comment by commche** [comment]
Standing in the detection field in the back left. door not opening
![image](https://user-images.githubusercontent.com/92918376/144177903-5197aabd-ab81-4b29-9bbc-80b7b56a1958.png)
Standing in the back right. Door opens
![image](https://user-images.githubusercontent.com/92918376/144177935-4dd8b412-b885-4b19-a4cd-d2e62d6686ad.png)
Standing in front of the door. door not opening
![image](https://user-images.githubusercontent.com/92918376/144178060-da0453f3-c146-4ddc-8782-40a5a3b6bbb6.png)

**Comment by commche** [comment]
out of field
![image](https://user-images.githubusercontent.com/92918376/144178373-9370464e-d9ee-42eb-863e-ed42663e078c.png)
back left corner - open
![image](https://user-images.githubusercontent.com/92918376/144178439-0eb8f152-1a48-4f29-be97-6e5f22d649d9.png)
Hover up over one block - door close (below 1 block, hover or standing - sensor fires)
![image](https://user-images.githubusercontent.com/92918376/144179152-191b79bd-b2d1-4c3f-9eb2-a0ae62644a5d.png)
back down and move slightly right - door close
![image](https://user-images.githubusercontent.com/92918376/144178509-fb6c7caf-5b84-491f-b712-8ee1e4a456e0.png)
back left corner on other side of door - nothing
![image](https://user-images.githubusercontent.com/92918376/144178787-e1640445-a2ff-4424-b1d4-db1061a105bf.png)
in mid of field on other side of door - no response
![image](https://user-images.githubusercontent.com/92918376/144179254-27caa22b-08c2-4e06-b37e-b70e71fe5df5.png)

**Comment by commche** [comment]
Here's a video from Remy on discord outlining the issue. Hopefully this can lead to a reproduction of the prob.

https://www.youtube.com/watch?v=EKvQcb7KitU

**Comment by commche** [comment]
This problem still persists as far as I know

**Comment by tsunamayo** [comment]
Hi, this should be fixed in latest experimental branch 22w45a. Thanks
