### ISSUE TITLE
prefabs wont align to any grid.

### ISSUE THREAD

**Issue by eageus** [tsunamayo/Starship-EVO#4298]
### Short Description of the issue:
this is a ongoing problem. even small prefabs wont align to a grid no mater how you mess around with the offset... i included a platform i was working on. i went to prefab the airlock and it started to give me the problem.
...

### Steps to reproduce the issue:
idk exactly what starts it. i have had it happen on 7 builds now that i use small and larger prefabs on. happens more often on 4m builds for some reason.
...

### Environment
- Starship EVO version: exparimental
- Graphics Card: gtx 1050ti

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it
[interier test platform.zip](https://github.com/tsunamayo/Starship-EVO/files/7616216/interier.test.platform.zip)
.

**Comment by commche** [comment]
I can confirm this issue too. maybe we should be able to mark out 'snap' areas on prefabs or something?

**Comment by tsunamayo** [comment]
Okay I will have a look at it. Thanks

**Comment by milan-t** [comment]
Hello,

I have similar issue while using Copy-paste Tool. Copied entity is shifted 1/2 size of the placement grid.

Here are examples:
_Same orientation as the original (Placement grid size: 1 m)_
![20211130213514_1](https://user-images.githubusercontent.com/65783423/144125171-3c267baf-e3f5-4ad7-b0bd-1661af4bb813.jpg)

_Rotated 90° (Placement grid size: 1 m)_
![20211130213537_1](https://user-images.githubusercontent.com/65783423/144125177-e4c784c3-ffcc-4d22-a07b-1aad5b8a9869.jpg)

_Same orientation as the original (Placement grid size: 0.5 m)_
![20211130213556_1](https://user-images.githubusercontent.com/65783423/144125181-10b743d1-50f2-447d-8e94-1e230c481fd3.jpg)

_Rotated 90° (Placement grid size: 0.5 m)_
![20211130213605_1](https://user-images.githubusercontent.com/65783423/144125182-1cff9150-94c0-4d74-89c9-21d84f1d11c0.jpg)

_Source spaceship fragment (red blocks are C&P helpers):_
![20211130213651_1](https://user-images.githubusercontent.com/65783423/144125753-12a028d1-5560-41f5-b506-a48c721d1a5b.jpg)

In version 21w45 I didn't noticed problem but may be I luckily matched dimension of the target entity with shifted placement grid.
The prefab I made still works well (has 0.25 placement grid aligned with the target entity):
![20211130220417_1](https://user-images.githubusercontent.com/65783423/144128661-03b81008-646b-4165-9114-c7f541090193.jpg)
![20211130221015_1](https://user-images.githubusercontent.com/65783423/144128665-89de776c-35cf-40ad-aca4-7d61d6f37514.jpg)

Interesting... I can clone old prefab with C-p Tool and it works but If I try to do the same with newer version of cargo hold floor that contains bricks of different scale (from 0.125 to 1 m), I cannot align the clipboard entity on the target entity.

![20211130223047_1](https://user-images.githubusercontent.com/65783423/144131633-d9926cd8-11f4-4dea-9b4b-0d053cad362a.jpg)

One thing is that Mag-Locks have scale 1m and 1/2 placement grid. If I remove them then I can place prefab/clipboard entity where I want. 

_(Placement grid size 0.5 m)_
![20211130223740_1](https://user-images.githubusercontent.com/65783423/144132427-3bd7ec02-5e94-46c3-a091-0e868017c7d6.jpg)

As long as I don't change original placement grid size :(

_Same clipboard, placement grid size 0.25 m:_
![20211130223938_1](https://user-images.githubusercontent.com/65783423/144132463-016bbc20-caa6-4305-9d1e-2e1b11d92ff4.jpg)

There is another issue with scale of fuel tanks when they are copied but that probably should be in separate report:
![20211130212116_1](https://user-images.githubusercontent.com/65783423/144134007-4bccc911-4843-4897-af10-68e15629792d.jpg)

Sorry for long and messy comment. I hope it helps.

**Comment by milan-t** [comment]
I forgot mention that I'm playing experimental version.

**Comment by Uncle-Ulty** [comment]
You need to adjust paste offset

**Comment by tsunamayo** [comment]
@eageus Hi, I went on to test and it was fine on my side. If the issue was not fixed please re-open a test with some more detail on what to copy.
@milan-t If you still have an issue please open a dedicated case with a blueprint. The fewer the screenshots and step to repduce the better. 
Thanks
