### ISSUE TITLE
Autopilot landing is very slow and janky, sometimes failing to land

### ISSUE THREAD

**Issue by commche** [tsunamayo/Starship-EVO#4303]
### Short Description of the issue:

Sometimes auto landing takes up to 5 minutes by the auto pilot
Its worse and sometimes gets stuck in an endless loop if you use 'force enter  direction'
The larger the ship, the longer autopilot gets confused 
Its very choppy and it seems like the autopilot is making many small jerky movements instead of moving smoothly to land
I think the AI needs a different approach because its current mechanics are pretty inefficient and not so "intelligent"
Shipyard computers on large ships seems to get even more confused and often can not complete landing

Its equally bad for 'is landing pad' set as on or off

### Steps to reproduce the issue:

Request landing and dock various ship sizes with various landing pad sizes
Obviously ideal conditions are a ship well within the landing pad max parameters in terms of size
Try landing on a large ship (i.e. a carrier)

### Environment
- Starship EVO version: [New build - DEFAULT] 21w47c
- Graphics Card: Radeon Armor rx570

### Additional information:

![dock3](https://user-images.githubusercontent.com/92918376/143993861-ab52160b-c576-46d4-8ce0-028ea7591755.jpg)
![dock2](https://user-images.githubusercontent.com/92918376/143993868-e1d7868a-2a62-4559-b509-e2c6d08bcc48.jpg)

Trying to upload player.log kept returning an error. I can resubmit another way if necessary.

**Comment by tsunamayo** [comment]
@commche Hi, could you send me your ship? Thanks

**Comment by quinchinno** [comment]
Having the same issue

**Comment by commche** [comment]
I also noticed that in the landing pad info window (bottom right) when landing, its says 'cat: 1' and 'maximum size 30m', but there's nowhere in the shipyard to specify these parameters.
My old save kept crashing the game, so I started a new one and made new pads. Testing was the same. Took about 5 mins to land the supercarrier. 
Landing the Cobra on the supercarrier was about 1 minute, but still quite janky. Both landing modes (floating and landing) completed successfully,but there's a gap between the landing feet and the pad. You can see in the screenshot that the pad configuration has it flush with the surface of the pad. (screenshot included)
Landing on the small pad took about a minute and was quite janky
I used the Mistral to test the small pad. It went into a collision loop, failing to complete landing - maybe because of low landing leg clearance? Wasn't a problem in the old default build.

blueprints zipped and attached
[landing test.zip](https://github.com/tsunamayo/Starship-EVO/files/7626457/landing.test.zip)

![image](https://user-images.githubusercontent.com/92918376/144067480-287917a3-9a25-4607-81fa-97e774b72d06.png)

**Comment by tsunamayo** [comment]
@quinchinno Hi, issue is fixed for 22w05a. Thanks
