### ISSUE TITLE
[Bug] Turrets lock up on intital creation and loose connection on prefab "Pasting"

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#4306]
### Short Description of the issue:
Hiya, 

Newly built turrets won't start moving under player control until the player has interacted with each moving component as demonstrated in the attached video.

In addition, pasting a prefab turret will be unusable until all links are reconnected.

Video demonstrations and an example prefab are provided, 

Best, Harry

### Steps to reproduce the issue:
Follow the same steps as the example video performed:
- Create a new entity
- Construct a turret, computer, and joystick.
- Link together as expected.
- Attempt to control the turret, exit, and press F on each of the rotors/hinges (same trouble for both)
- Control the turret again, It should now be working. 

As to the prefab issue:

- Copy the structure from the first steps
- Save the clipboard as a new prefab
- Paste that prefab down on a new entity.
- Attempt to control turret

### Environment
- Starship EVO version: 21w48a
- Graphics Card: RTX 3080

### Additional information:

Screenshots:
![image](https://user-images.githubusercontent.com/14081996/144287579-42a82353-0253-4de8-b064-984a55d68914.png)

Video Demonstrations:
https://user-images.githubusercontent.com/14081996/144287517-3e811fed-abd3-4ae8-9dec-6a5d1da01f7a.mp4
https://user-images.githubusercontent.com/14081996/144287525-9f00cc62-0c39-4bfc-892a-5f07d309a985.mp4

Player Log:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7636152/Player.log)

Prefab blueprint
[testturret.zip](https://github.com/tsunamayo/Starship-EVO/files/7636153/testturret.zip)

**Comment by tsunamayo** [comment]
@pinesh Hi, issue will be fixed for 21w49a. Thanks!

**Comment by pinesh** [comment]
Thank's for the quick fix!
