### ISSUE TITLE
Landing pads don't work

### ISSUE THREAD

**Issue by quinchinno** [tsunamayo/Starship-EVO#4309]
### Short Description of the issue:
Whenever I start a new entity and use the shipyard block I can never land ships on it.  I've added the shipyard to other entities and it works fine, for some reason I can never get it to work on a new entity that I created.  Ships will land, but no dialog will come up (the one that says "repair/undock") it just keeps going on autopilot.  Then when I turn off and get out of my ship, the ship comes off of the landing pad.  Canceling autopilot also doesn't work.

### Steps to reproduce the issue:
Place a starter block
Build a flat landing pad (any scale)
Add a shipyard block
Set parameters for shipyard and set to landing pad = true
Set forward and up directions
Request a landing from any ship

### Environment
- Starship EVO version: 21w48a
- Graphics Card: MSI GTX 1660 Super

https://user-images.githubusercontent.com/75867571/144341420-aab2e6d9-0746-492f-a774-c43bf0e1c7cd.mp4

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7638233/Pla
[Landing Pad.zip](https://github.com/tsunamayo/Starship-EVO/files/7638237/Landing.Pad.zip)
yer.log)
hip-EVO/files/7638232/output_log.txt)

**Comment by Reason147** [comment]
They have been broken for a while now landing is always been buggy. shipyard block  is broken landing on using it is impossible.

**Comment by tsunamayo** [comment]
@quinchinno Hi, issue is fixed for 22w05a. Thanks
