### ISSUE TITLE
Prefab icon in library displaying white block

### ISSUE THREAD

**Issue by commche** [tsunamayo/Starship-EVO#4313]
### Short Description of the issue:

-After saving a copied prefab, the library shows it as a white block instead of an icon representing the prefab
-the prefab names are now showing up either

### Steps to reproduce the issue:

copy some blocks
go to prefab library (or just straight to save)
click save (clipboard) icon
name and then export to local

### Environment
- Starship EVO version: 
- Graphics Card: radeon rx series

![image](https://user-images.githubusercontent.com/92918376/144536067-d9df04c2-c551-47ab-816f-c68b08bbfa3c.png)

**Comment by tsunamayo** [comment]
Hi, issue is fixed for 21w49a. Thanks!
