### ISSUE TITLE
Piston not visible when the base is not on camera

### ISSUE THREAD

**Issue by Thibdumont** [tsunamayo/Starship-EVO#4315]
### Short Description of the issue:
Piston is not visible (in extended position) when not viewing the base.

### Steps to reproduce the issue:
Simply put a piston, extend it and look at it but without the "base" visible. (See video below)

### Environment
- Starship EVO version:  21w48b
- Graphics Card: EVGA GTX 1070 FTW

### Additional information:
[Youtube video](https://youtu.be/HqjAsZdMrzU)

**Comment by commche** [comment]
I can confirm this

**Comment by tsunamayo** [comment]
Hi, yes the culling algorithm is not taking into account the size of the piston - I will address this!

**Comment by tsunamayo** [comment]
@Thibdumont That long standing issue have finally been fixed. Thanks!
