### ISSUE TITLE
Turret not turning if we don't interact with rotors

### ISSUE THREAD

**Issue by Thibdumont** [tsunamayo/Starship-EVO#4316]
### Short Description of the issue:
When building a new turret, we have to interact with rotors if we want the turret to turn when controlling it with a yoke.
Don't know if it's the expected behaviour  but as a newcomer, it took me a while to understand that.

### Steps to reproduce the issue:
Build a new turret : 2 rotors, 1 laser brick, link all these bricks to the turret computer, link the yoke to the event gate, link the gate to the laser. See video below for the whole process.

### Environment
- Starship EVO version: 21w48b
- Graphics Card: EVGA GTX 1070 FTW

### Additional information:
[Youtube video](https://youtu.be/IO2TpSrNxas)

**Comment by pinesh** [comment]
Hiya, I believe this is the same issue as the one documented in #4306

**Comment by tsunamayo** [comment]
@Thibdumont Hi, thanks for booking those bugs, the video is also useful. Indeed it seems the same issue, I keep you guys posted! thx

**Comment by tsunamayo** [comment]
@Thibdumont Hi, issue will be fixed for 21w49a. Thanks
