### ISSUE TITLE
Huge lag when placing blocks

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#4317]
### Short Description of the issue:
Large builds seem horribly unoptimized on the stable branch. Granted this ship is a 9km sphere but it all ran perfectly fine in the experimental branch before the Neovox update was pushed to stable. When I place a singular block, no matter the scale, on the 9km sphere the game goes to a standstill(complete fps loss) for 7 seconds then finally places the block. This happens no matter how many blocks you place afterwards.

This issue does not occur on smaller builds and doesn't seem to occur on my 1:1 Core Ship build ~(700 x 1000 x 700)

### Environment
- Starship EVO version: 21w48b
- Graphics Card: GTX 970

### Additional information
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7654590/Player.log)
The bp:
[The DUST Star.zip](https://github.com/tsunamayo/Starship-EVO/files/7654630/The.DUST.Star.zip)

**Comment by tsunamayo** [comment]
@Xerma Hi, okay thanks for the build I keep you posted.

**Comment by tsunamayo** [comment]
@Xerma Haha what a build mate - I am gonna keep this to test mega structure now.  I still need to give you the far away rendering, stay tuned...
Issue is fixed for 21w49a!
Cheers
