### ISSUE TITLE
Strange Rendering Lines

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#4318]
### Short Description of the issue:
I keep seeing these lines on blocks in various builds
https://imgur.com/gallery/8m0gDUj

### Environment
- Starship EVO version: 21w48b
- Graphics Card: GTX 970

**Comment by tsunamayo** [comment]
@Hi, well unfortunately those are shadow artifact. I tried to tweak it further but making it disappear would introduce more severe artifact elsewhere... Other game dont have this problem because there is no geometry beneath. As we have scalable bricks I am kinda stuck with that...
Cheers
