### ISSUE TITLE
Mechanisms reset to initial position/settings on game reload.

### ISSUE THREAD

**Issue by CurioInventorium** [tsunamayo/Starship-EVO#4324]
### Short Description of the issue:
The landing gear on my ship resets to stowed when the game relaunches. I've noticed this before in experimental, but haven't had the time to properly confirm it.
...

### Steps to reproduce the issue:
1. Build ship with deployable landing gear where the default position (or built position) is stowed away.
2. Deploy the landing gear and rest the ship on the ring (I haven't tried this while docked on a shipyard block).
3. Quit to title screen or out of the game.
4. Reload game and the ship will have the landing gear stowed away and will drop to the ground.
...

### Environment
- Starship EVO version: 21w48b
- Graphics Card: RTX2060

### Additional information:
I'm thinking it's all mechanism types that may be effected, as the landing gear is built up of pistons, rails and rotators.

_(Screenshots, Videos, Error logs, Related issues)_
Here's the ship with landing gear deployed.
![20211205130006_1](https://user-images.githubusercontent.com/51359034/144747962-47e432fd-4451-458b-a87a-30dad86edddd.jpg)

And here's the ship just after I've logged back into the game save.
![20211205130035_1](https://user-images.githubusercontent.com/51359034/144747978-1cb0fa0f-b264-4541-a603-5957edbb5135.jpg)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7655898/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

Here's the blueprint to the ship I'm using.
[CrossPlanet Cargo Mk2.zip](https://github.com/tsunamayo/Starship-EVO/files/7655897/CrossPlanet.Cargo.Mk2.zip)

**Comment by tsunamayo** [comment]
@CurioInventorium Hi, issue is fixed for 21w49a. Cheers!
