### ISSUE TITLE
Long-distance glow bubbles persist after blueprint de-spawn

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4328]
Version: 21w48b
GPU: 2080Ti

You just need to spawn and de-spawn any blueprint that uses lights.

![image](https://user-images.githubusercontent.com/63756057/144761999-3cbda9f5-4d13-4c46-8145-e3cf46301f1a.png)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Indeed! Fixed for 21w49a. Thanks
