### ISSUE TITLE
Ring gravity not working

### ISSUE THREAD

**Issue by PizzaKing32000** [tsunamayo/Starship-EVO#4329]
### Short Description of the issue:

when I am on the ring, gravity does not work.

### Steps to reproduce the issue:

go on a ring, and try to turn off you jetpack

### Environment
- Starship EVO version: early-access 21w48b
- Graphics Card: NVIDIA GeForce RTX 2070

### Additional information:

Whenever I go to a ring, leave my ship, and try to turn off my jetpack, it does not give me the option to disable the jetpack, I know it is not just that the game isn't letting me turn it off because I am able to turn it off in ship and station gravity, and also my orientation can be manipulated in -g mode. another thing, ships and other objects are effected by ring gravity, it is just me that is not.

**Comment by tsunamayo** [comment]
@PizzaKing32000 Hi, it will be fixed for 21w49a. Thanks!
