### ISSUE TITLE
No follow-up mission after game re-boot.

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4330]
Version: 21w48b
GPU: 2080Ti

I completed the block building, rotating, and scaling tutorial, but then there was no follow-up mission after I completed this part.
I remember the game crashed mid-tutorial and I had to re-take it from the Training Center Board but once I was done, there was no follow-up mission.

![image](https://user-images.githubusercontent.com/63756057/144765652-ff3ed805-09b0-4127-8637-75f2496fe65a.png)

**Comment by ProPeach** [comment]
Did the crash produce a crash dump?

**Comment by Kaiser-Indrasil** [comment]
Indeed it has:
[Crash_2021-12-05_212350597.zip](https://github.com/tsunamayo/Starship-EVO/files/7656981/Crash_2021-12-05_212350597.zip)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Thanks, yep I know the mission framework dont deal with save for now. I keep this open to fix your crash!
