### ISSUE TITLE
[BUG] Prefabs: Fuel tanks are smaller on the prefab than the original model

### ISSUE THREAD

**Issue by SlimSumo** [tsunamayo/Starship-EVO#4332]
Short Description of the issue:

Doesn't affect the transparent fuel tank.
The fuel tank on the prefabs are smaller than on the original model. (Every block sizes included.)

Steps to reproduce the issue:

Simply build a fuel tank and copy it.

Environment

    Starship EVO version: 21w48b
    Graphics Card: GTX 1070 ti

![20211206132305_1](https://user-images.githubusercontent.com/95624474/144846246-f0665b6e-1063-4830-bb8e-feddef85b345.jpg)

**Comment by tsunamayo** [comment]
@SlimSumo Hi, thanks a lot for booking this. Issue fix for 21w49a. Cheers
