### ISSUE TITLE
Volumetric sensors don't display the bounding box

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4340]
Version: 21w48b
GPU: 2080Ti

Looks like volumetric sensors do work, but they don't display their detection box, which makes them next to impossible to troubleshoot and work with in general.

![image](https://user-images.githubusercontent.com/63756057/145071409-fe6cf4c9-e0cf-453e-9bc1-54131a6b9d02.png)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Hi, you have to have a volumetric sensor equipped, I know it is not ideal, I will come up with something better. Thanks
