### ISSUE TITLE
Event Gate doesn't invert signals

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4341]
Version: 21w48b
GPU: 2080Ti

I have to use the NOR gates to bypass this bug.

[Main 21w48b.zip](https://github.com/tsunamayo/Starship-EVO/files/7670226/Main.21w48b.zip)

![image](https://user-images.githubusercontent.com/63756057/145074021-767a8e08-48c5-4e7f-84b0-111ec0308b31.png)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Well the reason is that you can choose Inferior or Superior, which yield the same thing as Invert signal.
So I will now hide invert signal in 21w49a. Thanks!
