### ISSUE TITLE
Deleting blocks obstructing a hinge leaves phantom collision points that continue to invisibly obstruct the hinge

### ISSUE THREAD

**Issue by commche** [tsunamayo/Starship-EVO#4342]
### Short Description of the issue:

When a block is stopping a hinge from opening or closing properly, after deleting the offending block, a phantom collision area is left behind causing the hinge to remain blocked. (credit to Double Botch on Github for both thinking to use the debug menu to view collision points, and solving the mystery of the phantom collision point)

### Steps to reproduce the issue:

![image](https://user-images.githubusercontent.com/92918376/145161982-07a5f27c-e09e-4629-bb9f-fe7cbae7634e.png)
I reproduced the issue with this set up. Interestingly, the collision area only appeared when I attached the 1/2m square blocks to the 1m size wedge block.

![image](https://user-images.githubusercontent.com/92918376/145162166-18cce230-72b4-40a8-a684-15af429e2d4b.png)
Closed and positioned as intended

![image](https://user-images.githubusercontent.com/92918376/145162470-44fbf8a5-e5f2-434c-ba0d-da965c62fd75.png)
These new obstructing blocks have updated the collision area...
![image](https://user-images.githubusercontent.com/92918376/145162612-ed829edd-2af2-47fc-8145-226a61997a42.png)
...now the hinge can't close properly
![image](https://user-images.githubusercontent.com/92918376/145162724-49818efe-47fb-48bc-b585-9cfcd1dcfecb.png)
The offending blocks are deleted, but the collision points remain...(aka phantom collision point)
![image](https://user-images.githubusercontent.com/92918376/145162775-618ac070-0c08-44eb-bcdc-eb6fd5aa69c2.png)
...and the hinge still can't close properly
![image](https://user-images.githubusercontent.com/92918376/145162865-4b3d99ac-9525-40e0-a3d5-cfeb604c5de1.png)
Placing another block in the phantom collision area actually removes the area...
![image](https://user-images.githubusercontent.com/92918376/145163141-2322d91e-97b8-42bb-a037-4abdaa6bb489.png)
After removing the block, the hinge now closes as intended.

### Environment
- Starship EVO version:  [New build - DEFAULT] 21w47c
- Graphics Card: Radeon Armor rx570

### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7673977/Player.log)

I figured the screenies should be enough. Otherwise if you need any other files / blueprints, I'm sure you will ask.

**Comment by tsunamayo** [comment]
@commche Hi, so actually I already fixed that bug prior to the case. So fixed for 21w49a! Thanks
