### ISSUE TITLE
[BUG] Handhelds completely broken in many ways

### ISSUE THREAD

**Issue by zorozeenee** [tsunamayo/Starship-EVO#4345]
### Short Description of the issue:

Starting a handheld weapon doesnt work, the handle will not be at the item stand but instead be far off, probably into the ground and wont have physics

Spawning in an existing handheld will cause a physics issue, while the handhelds sometimes appears its physics location is different then what is displayed, or sometimes they wont even spawn at all

Holding a handheld and firing it creates the projectiles or beam far away from where the barrels are located

### Steps to reproduce the issue:

1. Put down an item stand
2. Place a handle on the item stand
3. Spawn in an existing handheld weapon

### Environment
- Starship EVO version: 21w49a
- Graphics Card: GTX 1060 super

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7682985/Player.log)

**Comment by tsunamayo** [comment]
Well this is weird it was fine for me... I spend a lot of time fixing those bugs...

**Comment by tsunamayo** [comment]
@zorozeenee Well I just tested this is fine for me. I dont know if you can record or show me a screenshot this is weird. Also this logs dont seems to contains any gameplay at all...

**Comment by CurioInventorium** [comment]
I'm able to build a weapon on the item stand okay. @zorozeenee have you switched back to the main branch of the game on steam? As this is where the current updates are being placed. Item stands were broken on the experimental branch, I think.

Here's a start of a rifle being built in my game
![20211209110113_1](https://user-images.githubusercontent.com/51359034/145385973-b19c44ce-e9dd-4e36-bd53-318018cbfc43.jpg)

And here it is completed
![20211209110414_1](https://user-images.githubusercontent.com/51359034/145385990-8671f09b-77d4-411f-91a2-e6272b301faa.jpg)

It fires okay, but the rate of fire is poor.

@tsunamayo An issue I have found is that my old weapon blueprints won't spawn in on a weapons stand, but the one I created a few moments ago does.
These are some of the ones that don't spawn anymore...
[Auto-Sniper.zip](https://github.com/tsunamayo/Starship-EVO/files/7684576/Auto-Sniper.zip)
[Chonk Repeater.zip](https://github.com/tsunamayo/Starship-EVO/files/7684577/Chonk.Repeater.zip)

And this is the one I was just building...
[Test Gatling Rifle.zip](https://github.com/tsunamayo/Starship-EVO/files/7684578/Test.Gatling.Rifle.zip)

**Comment by tsunamayo** [comment]
@zorozeenee It might be some shenanigan with the steam update. Make sure to restart your steam or uninstall and re-install the game if it continues!

**Comment by tsunamayo** [comment]
@CurioInventorium I am sorry to bring the news to you: your blueprints are too old! Indeed it is impossible for me to manage an absolute compatibility of way older blueprints - I do as much as I can but several format behind dont works. I guess you can rebuild them. Also please be aware we are currently discussing reducing the size reduction factor to create more detailed weapons. Thanks

**Comment by CurioInventorium** [comment]
@tsunamayo lol, I figured that may be the case. Handhelds haven't behaved properly since the neovox update anyway.
Once things have settled more I'll rebuild them :)
