### ISSUE TITLE
[Bug] Player "tied" to a dropped handheld weapon

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4346]
### Short Description of the issue:
Player gets bonded to a dropped handheld weapon, and can't get away. Here I'm moving the character away from the dropped weapon, but I can only get so far, and when I stop moving I get attracted back to it as if I'm on an elastic band
https://i.imgur.com/BtwDRIp.mp4

### Steps to reproduce the issue:
- Enable noclip mode with F5 (not sure if this is required to produce, but this is what I did)
- Start a handheld weapon by placing a handle on an item stand
- Grab the weapon
- Drop the weapon close to you
- Initially, I couldn't move at all
- Disable noclip mode, now you can move a small amount but still get pinged back to the dropped weapon when you stop moving

### Environment
- Starship EVO version: 21w49a
- Graphics Card: RX580

### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7685535/Player.log)

**Comment by ProPeach** [comment]
Just reloaded the world, and it seems like all the movement I did while tied to the weapon stacked up and acted all at once, as I loaded in very far away from the weapon I was previously stuck to

**Comment by ProPeach** [comment]
Actually, it seems like the bug happens when you unspawn a weapon too. I just had a weapon on the itemstand and unspawned it and it reproduced the bug

**Comment by tsunamayo** [comment]
@ProPeach Hi, so the issue is that your blaster had a secondary handle and no primary. I added a few failsafe so that it cant happen anymore. If there is no handle at all you cant equip the weapon. Fix for 21w50a. Thanks!
