### ISSUE TITLE
[Bug] Character does not hold handhelds correctly

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4348]
### Short Description of the issue:
The character tries to grab a handheld weapon with two hands, even though only one handle is on the gun
![image](https://user-images.githubusercontent.com/27857711/145411828-5e65ee7e-5ba0-427a-a480-0700a22c48fc.png)
![image](https://user-images.githubusercontent.com/27857711/145412455-24a36e08-d749-4227-9268-748d10d5c6e8.png)
![image](https://user-images.githubusercontent.com/27857711/145412483-686810f1-e7b8-4a4b-ae71-bb5ae3d54f7f.png)

Also, changing the handle settings to fit the left hand doesn't seem to change anything

Two handed weapons seem much closer to being correct, but the second hand doesn't always grip the handle correctly
![image](https://user-images.githubusercontent.com/27857711/145414482-733e4d22-4002-456b-93b0-6b033710ee25.png)

### Steps to reproduce the issue:
- Load the attached blueprint
- Hold it in your hand and have a look
- Put it back in the item stand and change the handle settings to left handed 

### Environment
- Starship EVO version: 21w49a
- Graphics Card: RX580

### Additional information:
[DL-44.zip](https://github.com/tsunamayo/Starship-EVO/files/7685735/DL-44.zip)

**Comment by tsunamayo** [comment]
@ProPeach Well you need to have the first handle set to Right hand (main). There was also a bug for when you re-assign. Now if you only have a handle at secondary it will still be assigned as a primary so no issue.
All fixed for 21w50a!
