### ISSUE TITLE
Shipyard block and event gate incorrect behaviour. Ship landing overshooting and glitching. Plus event not untriggering.

### ISSUE THREAD

**Issue by CurioInventorium** [tsunamayo/Starship-EVO#4351]
### Short Description of the issue:
Ship landing on autopilot keeps overshooting the centre of the defined shipyard area. Even if shipyard area is extended, the ship will still move further forward. On further testing the ship wouldn't land correctly and kept glitch-colliding with the platform.
The event block linked to the shipyard block to trigger the "Is Docked" event works when the ship finally docks, but does not un-toggle once the ship leaves.
...

### Steps to reproduce the issue:
1. Define a shipyard zone and land a ship, most times the ship will overshoot. In the past I've had ships bounce of buildings before settling.
2. Attach a event block that monitors the "Is Docked" event and attach that to a rail or mechanism.
3. Attempt to land a ship.
4. Observe if "Is Docked" trigger works.
5. Undock ship from shipyard

...

### Environment
- Starship EVO version: 21w49a
- Graphics Card: RTX2060

### Additional information:
I'm also using the "Is Docking requested" event block and I'm not sure if the lights attached should switch off once the ship has docked. But they do switch of if docking is cancelled.

_(Screenshots, Videos, Error logs, Related issues)_
Here's my ship glitching around while autopilot is landing it.
![20211210124156_1](https://user-images.githubusercontent.com/51359034/145577402-e36c9932-a445-4ea5-a7e0-c4c6124df953.jpg)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
Played log attached just in case.
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7692826/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

Here's the blueprints for the ship and the landing area. The expected behaviour of the shipyard is that the lights around the landing platform switch on when docking is requested. Once the ship has landed a refuelling platform should rise up and only drop once the ship takes off.
 
[CrossPlanet Cargo Mk2.zip](https://github.com/tsunamayo/Starship-EVO/files/7692820/CrossPlanet.Cargo.Mk2.zip)
[Test Landing and Build Platform.zip](https://github.com/tsunamayo/Starship-EVO/files/7692821/Test.Landing.and.Build.Platform.zip)

**Comment by tsunamayo** [comment]
@CurioInventorium It should be fixed in current update. Thanks
