### ISSUE TITLE
large ships spawn instantly colliding with other large ships

### ISSUE THREAD

**Issue by commche** [tsunamayo/Starship-EVO#4352]
### Short Description of the issue:

when spawning in a large ship from a large ship, the spawn distance from the ship isn't far enough resulting in a 'stuck' collision situation. 

### Steps to reproduce the issue:

spawn in a large ship while piloting another large ship. Perhaps the spawn distance from a ship could be relative to size rather than fixed?

### Environment
- Starship EVO version: [New build - DEFAULT] 21w49a
- Graphics Card:  Radeon Armor rx570

### Additional information:
![image](https://user-images.githubusercontent.com/92918376/145608961-b9f0b24a-516f-4b4e-add4-90b7b338dec9.png)

**Comment by tsunamayo** [comment]
Yep true! How big is your ship?

**Comment by commche** [comment]
403 x 80 x136 m. She's a thicc gal!

**Comment by tsunamayo** [comment]
@commche Issue fixed for 21w50a! Thanks
