### ISSUE TITLE
Aggressive ships don't spawn as pirates

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4353]
Version: 21w49a
GPU: 2080Ti

Steps:
1. Open the F8 menu
2. Set the AI mode to Aggressive
3. Spawn anything in

This forklift refuses to be evil:
![image](https://user-images.githubusercontent.com/63756057/145684748-5159a9ea-daa0-4e22-ae12-e00acd895168.png)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil But they are still attacking you? Thanks

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo No, they are not. They don't even have a pilot NPC, much like the passive AI ships.

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Where you in the new Station safe-zone?

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo No, I was way outside the zone

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil okay, well it is fixed anyway as I have been doing some work regarding npc before this case... For 21w50a. Thanks
