### ISSUE TITLE
FPS Lag - Not so explainable

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#4364]
### Short Description of the issue:
So I've been getting some fps loss while building the hangar in the Core Ship (seen below) and I believe the average framerate within that area is about 54 fps. Just recently I flew maybe 1km away from the Core Ship to design a much smaller ship. In that area I started getting the same framerate as I was when inside the hangar. When I'm outside the Core Ship looking at the hangar behind the door the fps seems stable. So I'm led to believe that something isn't right somewhere but I can't seem to pinpoint it. 

I should note that when in the same areas the fps stabilizes at 60 while looking away into empty space. Lastly, the fps drops are much more noticeable while moving around those areas.
...

### Environment
- Starship EVO version: 21w49a
- Graphics Card: GTX 970

### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7716785/Player.log)

![20211214233511_1](https://user-images.githubusercontent.com/32974671/146131569-d2183c4a-47dc-45e0-ae48-672af71b8d87.jpg)
![20211214233519_1](https://user-images.githubusercontent.com/32974671/146131584-7a4abe1c-a83b-4d40-a79d-024f950b1595.jpg)
![20211214233537_1](https://user-images.githubusercontent.com/32974671/146131588-2e2e87c7-8679-4924-9adb-9fa554735b42.jpg)
![20211214233601_1](https://user-images.githubusercontent.com/32974671/146131600-4b05321e-954b-4e1b-9ac8-2feeab60374a.jpg)
![20211214233611_1](https://user-images.githubusercontent.com/32974671/146131612-1c56c0a9-1787-4d2b-a667-ab256a609609.jpg)
![20211214233636_1](https://user-images.githubusercontent.com/32974671/146131620-395b5429-b5a5-43b8-a89a-88546513e79c.jpg)
![20211214233916_1](https://user-images.githubusercontent.com/32974671/146131646-76bd6366-ff9e-49fa-b4e6-f31042a94493.jpg)

**Comment by tsunamayo** [comment]
@Xerma Hi, could you send me the blueprint so I can have a look at it? thx

**Comment by Xerma** [comment]
For sure, here are the 2 blueprints. 
Although I just loaded into the game very briefly to do another quick test on the issue. I was zooming around both the small ship and the core ship and was getting a nice 59 fps. So perhaps my fps loss was due to me having the game open for an extended period of time?
[Blueprints.zip](https://github.com/tsunamayo/Starship-EVO/files/7723457/Blueprints.zip)
