### ISSUE TITLE
FPS Lag - Entity Information/Preview

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#4365]
### Short Description of the issue:
Tis the return of fps lag while having the entity preview/information screen up
...

### Environment
- Starship EVO version: 21w49a
- Graphics Card: GTX 970

### Additional information:
![20211215000402_1](https://user-images.githubusercontent.com/32974671/146132471-5922da9a-a4b6-44ce-a958-853768d9a6cf.jpg)
![20211215000408_1](https://user-images.githubusercontent.com/32974671/146132474-0b94e995-8f99-4289-acec-802aa9196e68.jpg)

**Comment by tsunamayo** [comment]
@Xerma but it is lagging only when viewing the preview or even after once the codex closed?

**Comment by Xerma** [comment]
the fps only drop to that while the preview is open

**Comment by tsunamayo** [comment]
@Xerma Hi, I dont really reproduce, could you send me the blueprint? Do you still get this in 21w52b?
 Thanks
