### ISSUE TITLE
[Question] - Ship to Ship/Station stats sharing

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#4366]
I asked this in the "New Docking Logic" Discussion just a few days ago but am a bit anxious to know about this as it will determine how I build the interior of this ship.

Will docking ship to ship/station be able to transfer stats to the parent? This could be an option in the docking/ship computer ( [x] Allow stat transfer to docked entity). Of course my reasoning is for my beloved Lucrehulk/Core Ship from Star Wars (the core ship/sphere can dock/undock from the ring to deploy to planets) it could make for interesting gameplay choices but I'll be honest, I don't see it as terribly necessary. Either way just curious so have some WIP pics 😄

![20210615114842_1](https://user-images.githubusercontent.com/32974671/146133254-412b29d4-701a-4a2b-8611-4b21f94e24e6.jpg)
![20211214112932_1](https://user-images.githubusercontent.com/32974671/146133326-6cbc5387-46d3-410d-96ad-4bac006c0391.jpg)

**Comment by tsunamayo** [comment]
Yes I want to work on that, and also allow inventory transfer... Thanks

**Comment by tsunamayo** [comment]
@Xerma nice big boy ^^
