### ISSUE TITLE
Problem with Tutorial

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#4367]
### Short Description of the issue:

This was my first run through of the new tutorial and when I got to the small ship to repair, I found it a little inconvenient having it already buried in the floor. I'm guessing that's not part of the challenge!

Really like the station and the layout. The scale of it is great.

### Steps to reproduce the issue:

I did not follow the tutorial "path" exactly and had a look around the station before doing this mission. Perhaps my actions affected the mission logic.

### Environment
- Starship EVO version: 21w49a
- Graphics Card: GTX1070

### Additional information:

![20211216191511_1](https://user-images.githubusercontent.com/70821082/146435221-1f451908-5d93-46d3-a060-8c9958bd6487.jpg)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7729907/Player.log)

**Comment by tsunamayo** [comment]
@cloudrambler This should be fixed in latest versions. Thanks
