### ISSUE TITLE
Handheld weapon issuses

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#4370]
Hi,

Tested out handhelds for a long time and found 3 bugs:

1.Guns don't allaign with the item stand
![20211217221119_1](https://user-images.githubusercontent.com/81495956/146609068-0149cb47-76d0-4068-a3a9-a4bfacc5b539.jpg)

2.After deleting the 2nd grip I can't place a new one. The one I deleted doesn't seem to be really deleted
![20211217221145_1](https://user-images.githubusercontent.com/81495956/146609177-2ae10234-8a3a-40d6-a19e-b75dc67a439e.jpg)

3.If I use a screen for a custom crosshair, the letters appear in front of the gun, not on the height of the screen. Also the letters are not able to be set down on the right height for the screen - they are too high (I hope you'll understand what I mean
![20211217221209_1](https://user-images.githubusercontent.com/81495956/146609368-9b0aea08-64c6-4b69-b5bc-fdbc0ad5bdec.jpg)
That's how low I can get the text before it's getting invisible
![20211217222314_1](https://user-images.githubusercontent.com/81495956/146609575-15dd7dd6-1c15-45f0-8902-b6de9d966731.jpg)

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, could you send me your blueprint? Thanks

**Comment by BigBadKangaroo** [comment]
[Test gun.zip](https://github.com/tsunamayo/Starship-EVO/files/7764778/Test.gun.zip)
There you go.

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, so I cant reproduce the align issue. Do you still get this? If yes could you send me your world? Thanks

**Comment by tsunamayo** [comment]
The text issue is fixed, at least the part relative to the offset because of the weapon scale. This whole text is not made for the stretchable display up until the refactor. Thanks

**Comment by tsunamayo** [comment]
Issue 2 was also fixed, so I think all tree are actually fixed. Ping me if it is not the case! Cheers
