### ISSUE TITLE
BVH Anomaly

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#4374]
The new tutorial station has been inadvertently built next to a subspace rift.

https://user-images.githubusercontent.com/70821082/146653050-feb67bd9-d226-4864-b340-9bddb0a99553.mp4

This is the result of turning on World BVH, in the area of the new station (just off centre in the view). I had turned off NPCs and only loaded a couple of small ships myself. So it looks like some structures have been built and deleted prior to the world generation, or as part of the world spawn, without their existence being fully nulled from the world.

**Comment by cloudrambler** [comment]
The same situation occurs in a different (older) world, this time at the ringworld.

https://user-images.githubusercontent.com/70821082/146654488-d6544922-3829-415d-8761-6d08947f313d.mp4

It looks like the anomalous bounding boxes are copies of real entity bounds that are projected into space along orthographic axes, but their existence is more randomised than appearing to be an actual logical pattern.

**Comment by tsunamayo** [comment]
@cloudrambler yep I noticed I havent time to investigate this yet (it has no impact on the game though, I suspect it is just a bug of the debug feature)

**Comment by tsunamayo** [comment]
@cloudrambler Finally fixed, it was just an issue with the debug algo. Thanks
