### ISSUE TITLE
[BUG] Multiplayer broken

### ISSUE THREAD

**Issue by matejkar** [tsunamayo/Starship-EVO#4376]
### Short Description of the issue:
title. Also continuation on my previous topic on Multiplayer
basically, the multiplayer doesn't work even with ZeroTier now.
What happens is that the player clicks the join button, the game behaves as if its loading the world, the world starts loading for a bit, sometimes it loads in just to show a black void. But every time the game fails to load the character in, and is brought back to main menu (as seen in the video).
...

### Steps to reproduce the issue:
try joining a multiplayer world
...

### Environment
- Starship EVO version: 21w49a
- Graphics Card: 1060ti 6GB

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

https://user-images.githubusercontent.com/69653738/146670983-6ba6ae2d-b563-4edb-bba4-cdfbeb467c57.mp4

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by matejkar** [comment]
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7740599/Player.log)
player log

**Comment by tsunamayo** [comment]
@matejkar Hi, so I have finally made some fixes for 22w04a. I think we will still find a lot of issues but I was able to connect, build, see npcs ship moving, fly and spawn ships. Please book any issue you might find!
Thanks
