### ISSUE TITLE
Warning message gates not firing when activated from event gate keybinds

### ISSUE THREAD

**Issue by commche** [tsunamayo/Starship-EVO#4378]
### Short Description of the issue:

Warning message not showing when a keybound action through an event gate is activated
note: this setup was working before the update, and I only encountered this problem after the update

### Steps to reproduce the issue:

connect a warning message gate to any button (button A) that connects to a switch that is connected to a sequencer gate that does anything
connect a yolk to an event gate and then set the event gate to [signal] hotkey 1 is pressed (normal mode)
connect the event gate to the aforementioned button (button A)

press the button, the message fires
activate the yolk, press the hotkey. the action is done, but no message fires

### Environment
- Starship EVO version: [New build - DEFAULT] 21w50b
- Graphics Card: Radeon Armor 570 

### Additional information:
message fires when button is pressed manually
![image](https://user-images.githubusercontent.com/92918376/146810858-ca95f449-832a-497b-bd3f-357e0ffc0ce1.png)

button pressed via event gate (1 key). piston moves, but no message
![image](https://user-images.githubusercontent.com/92918376/146810947-85ed41a0-9588-46f5-aa21-3d80882a66d9.png)

I have attached the player log, ship where the problem was first encountered, and a demo to replicate the problem.
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7747131/Player.log)
[warning message bug test.zip](https://github.com/tsunamayo/Starship-EVO/files/7747132/warning.message.bug.test.zip)
[Salamander Mk I.zip](https://github.com/tsunamayo/Starship-EVO/files/7747138/Salamander.Mk.I.zip)

**Comment by tsunamayo** [comment]
@commche Thanks for the solid test case. Fixed for 21w51a! Cheers
