### ISSUE TITLE
[Bug]query gates dont work

### ISSUE THREAD

**Issue by COMICLER** [tsunamayo/Starship-EVO#4379]
Query gates dont work when connected to a seat or a chair

**Comment by COMICLER** [comment]
Actually after messing around a bit it seems its only message blocks that dont work when connected to a command block connected to a seat or control stick

**Comment by commche** [comment]
yep. I can confirm that
https://github.com/tsunamayo/Starship-EVO/issues/4378

**Comment by tsunamayo** [comment]
@COMICLER Hi, yes issue is fixed for 21w51a. Thanks!
