### ISSUE TITLE
Issue when copy/paste a cannon with gatling

### ISSUE THREAD

**Issue by Leidz** [tsunamayo/Starship-EVO#4381]
When i copy/paste a cannon with a gatling barrel attached to it, when i paste into the world, the barrel are not here and i need to quit the game and enter again to spawn it.

Steps to reproduce the issue:

Copy paste a cannon with gatling barrel addon

- Starship EVO version: 21w50b
- Graphics Card: RTX 3070 Laptop GPU

![copypaste bug](https://user-images.githubusercontent.com/47060013/146906282-a9edc170-33c8-4153-95e0-0667891a5778.PNG)

**Comment by tsunamayo** [comment]
@Leidz Issue fixed for 21w52b. Thanks!
