### ISSUE TITLE
Copy paste issue with cannon (inactive cannon barrel addon)

### ISSUE THREAD

**Issue by Leidz** [tsunamayo/Starship-EVO#4382]
I noticed when you copy paste a cannon with barrel attachment and use it, the barrel addon part become inactive, and the cannon fire by his original output and not by the output of the barrel addon, i need to leave the game and join again to make it work.

Steps to reproduce the issue:

Copy paste a cannon with barrel addon and fire with it.

Starship EVO version: 21w50b
Graphics Card: RTX 3070 Laptop GPU

![bugcannon](https://user-images.githubusercontent.com/47060013/146907775-506976f4-ca2d-4a38-9afe-03a062884a2d.PNG)

**Comment by tsunamayo** [comment]
@Leidz Issue fixed for 21w52b. Thanks!
