### ISSUE TITLE
"Complex"Logic for weapon don't seem to work when copy/paste

### ISSUE THREAD

**Issue by Leidz** [tsunamayo/Starship-EVO#4383]
I copy pasted a logic cannon with rotator, logic and all, and dont work (The rotator work, but dont seem to give the rotation data to the Event gate) until i leave and join the game.

Steps to reproduce the issue:

Copy paste a cannon with logic, rotator, event gate and event gate connected to cannon.

Starship EVO version: 21w50b
Graphics Card: RTX 3070 Laptop GPU

The current cannon i tried:

[[8DC]ClockGauss-1.zip](https://github.com/tsunamayo/Starship-EVO/files/7751379/8DC.ClockGauss-1.zip)

![gatling](https://user-images.githubusercontent.com/47060013/146909818-28c0910c-25a6-4c7d-a67c-3db94703f9bf.PNG)

**Comment by tsunamayo** [comment]
@Leidz Hi, issue will be fixed for 21w52b. Thanks!
