### ISSUE TITLE
Prefab thumbnails fail to load in the Codex

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4385]
Version: 21w51a
GPU: 2080Ti

Happened in 21w50a, too.
I'd thought that re-uploading it will fix the issue but sadly, it didn't.

![image](https://user-images.githubusercontent.com/63756057/147022021-f79ac580-0026-4cf2-8b15-7eaedd88898e.png)

**Comment by quinchinno** [comment]
Happens for me too

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Thanks, issue fixed for 21w52b. Cheers
