### ISSUE TITLE
Logic is bugged for prefabs and copy-pasted items

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4386]
Version: 21w51a
GPU: 2080Ti

[Here's the link for the BP in question](https://steamcommunity.com/sharedfiles/filedetails/?id=2566927098)
So I tried to update one of my turrets and the game refuses to run logic circuit number 1 in the screenshot below.
It straight up doesn't work at all, and it should.
It happens only when I paste the turret containing the circuit from the Workshop

![image](https://user-images.githubusercontent.com/63756057/147029278-655dfd35-339e-4baa-a13c-00f26bf41266.png)

Even when I totally re-made the whole circuit (in blue, buttons are acting as signal indicators), it just refuses to work.

![image](https://user-images.githubusercontent.com/63756057/147029728-3f5eb0d1-f0c7-46ef-a1f7-57eeaaf3be70.png)

**Comment by Kaiser-Indrasil** [comment]
Seems connected to #4383

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Hi, issue will be fixed for 21w52b. 
Thanks!
