### ISSUE TITLE
Existing Save Game Unable to Load

### ISSUE THREAD

**Issue by jasonfogleman** [tsunamayo/Starship-EVO#4387]
### Short Description of the issue:

Version 21w51a following most recent hotfix. Upon attempting to load existing save game will reach loading screen and never finish loading. Game does not crash, but will not finish loading. Am able to begin new world. 

### Steps to reproduce the issue:

receive hotfix, load existing world. 

### Environment
- Starship EVO version: 21w51a
- Graphics Card: NVIDIA GeForce GTX 1060 3GB

### Additional information:

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7760023/Player.log)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by Kaiser-Indrasil** [comment]
Same here.
Many new versions of the game seem to be incompatible with older worlds, so my solution would be to create a new world for every new version of the game.

**Comment by tsunamayo** [comment]
@jasonfogleman Hi, how old is this save?
Could you send me the character save? The log file seems to be the one from a new character, not your older one.
When you create a new character and exit, can you load back?
Thanks

@Kaiser-Indrasil well if there is a serious bug with the last update I need to know and fit it asap! We are still on Default some beginner will have this one...

Cheers all

**Comment by jasonfogleman** [comment]
The attached save was my original save from when I bought the game a few
weeks ago.

I can load the new save I created.

**Comment by tsunamayo** [comment]
@jasonfogleman Hi, I dont see the save attached. If you are using mail I think attaching files dont work! Thanks

**Comment by jasonfogleman** [comment]
[Double Botch (2).zip](https://github.com/tsunamayo/Starship-EVO/files/7765696/Double.Botch.2.zip)

**Comment by tsunamayo** [comment]
@jasonfogleman It is fixed for 21w51b! It was linked to being in another system. Cheers

**Comment by jasonfogleman** [comment]
Thanks!
