### ISSUE TITLE
Event gates with pistons are broken

### ISSUE THREAD

**Issue by thatisjake** [tsunamayo/Starship-EVO#4388]
### Short Description of the issue:

Event gates reading pistons are broken
### Steps to reproduce the issue:

Link piston into event gate, into indicator light (or anything).
Pistons don't work with event gate.
### Environment
- Starship EVO version: 21w51a

**Comment by tsunamayo** [comment]
@thatisjake Hi, was it after a new blueprint load by any chance? It is working fine on my side, but I fixed an issue regarding freshly loaded blueprints. Thanks
