### ISSUE TITLE
Spawned in ships are locked in firing pattern until event gate reset

### ISSUE THREAD

**Issue by commche** [tsunamayo/Starship-EVO#4390]
### Short Description of the issue:
After spawning in a ship, activating the yolk results in the ship auto firing pilot weapons and hotkey gate actions firing automatically
This started happening after the last fix
Simply disconnecting any hotkey block from the yolk and then reconnecting it resets the hotkey event gates back to normal

### Steps to reproduce the issue:
Spawn in any ship with hotkey event gates or weapons and activate the control yolk
The ship will immediately start firing and hotkey gated actions will activate automatically

I tested this 3 times with 3 different ships and I was able to reproduce the issue each time

### Environment
- Starship EVO version: [New build - DEFAULT] 21w51a

- Graphics Card: Radeon Armor 570

### Additional information:

attached is a test ship I made, the player log and world save
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7767560/Player.log)
[hotkey test.zip](https://github.com/tsunamayo/Starship-EVO/files/7767561/hotkey.test.zip)
[New Character.zip](https://github.com/tsunamayo/Starship-EVO/files/7767562/New.Character.zip)

**Comment by tsunamayo** [comment]
Yep I saw that, this was already fixed for 21w51b ;)
