### ISSUE TITLE
Stations not always identical

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#4395]
I created a new world using the 21w51b build and went about my business spawning in ships to work on. I then ETD and reloaded the world, hoping that it would clear the mission listings; it did. :)

However I noticed that the starting station was now configured differently to the first time I loaded the world. I think it's quite important that when something procedural spawns, that it stays the same; otherwise it will disorient players and ruin the otherwise high level of immersion that the game is capable of.

Sadly I did not have the logs and when I tried to replicate the problem, the station remained constant.

**Comment by tsunamayo** [comment]
@cloudrambler Hi, was it after a quit to title? Spawning will be different for version to version (it is a feature actually), but should not be from a session to the next, so it must be a bug.

**Comment by cloudrambler** [comment]
@tsunamayo It was a quit to desktop.

**Comment by tsunamayo** [comment]
@cloudrambler Hi, do you recall what part was different? Thanks

**Comment by cloudrambler** [comment]
From memory;
First instance = three fuel modules under main intersection, one single landing pad, and one double landing pad.
Changed instance = two fuel modules under and one above, and now both landing pads are doubles.

I did not go inside so I don't know if the concourse area changed.

**Comment by Tisdag1** [comment]
I just logged back into my game & it has changed again. This one is very close to what the station was originally. But the "repaired" module is on the bottom under the fuel tanks. Where I am pretty sure it was on the top extension originally. And I don't remember there being fuel tanks on the top extension as well.

![Tutorial Station 2](https://user-images.githubusercontent.com/95005604/153770091-4db8c2b9-7f1f-4f57-8c9b-185e4d069768.jpg)
