### ISSUE TITLE
[BUG] - Player getting stuck in open space

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#4396]
I have noticed for the last week or so that the player character (blue cat in my case) sometimes gets stuck in open space. It happens similarly to when I get stuck inside a ship, but in these cases I am tens of metres from the nearest object. It has happened in several worlds, and in proximity to several blueprints, but it is a sporadic problem.

It does seem to happen regularly at some points away from certain ships.

The resolution seems to be to wait for a few seconds, until movement is restored. I also find that if I am holding down a movement key, then when I move it will suddenly jump quite a distance in that direction.

Present build: 21w51b
Card: GTX1070

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/7771749/output_log.txt)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7771750/Player.log)

**Comment by cloudrambler** [comment]
There seem to be a few bugs popping up regarding the symmetry tool. One stating that just holding the tool will make movement  erratic. So I should point out that I would have been holding a symmetry tool when the above getting stuck happened; at least this last time anyway. So maybe these problems are related.

**Comment by tsunamayo** [comment]
@cloudrambler Yep correct it was the symmetry tool. Fixed for next update! (I will push it asap!)

**Comment by cloudrambler** [comment]
@tsunamayo I am still getting stuck in free space, using build 21w52a. It seems to happen most near the corners if the ship's bounding box.
