### ISSUE TITLE
Symetry causing weird lag

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#4397]
Hi,

so in the recent build 21w51b I get a weird bug/lag when I try to place down a symetry on my ship. 

It first happend in an older world I made in 21w50a but after creating a new world I could reproduce it. The way I can reproduce it is to spawn a ship or a starter block, place a symetry on it. Spawn in a new starterblock or ship and place a symetry on it. The second you try to place a second symetry on any of the two things I get this bug/lag!

The game does not allow me to place a symetry, and if I try I get stuck mid air and can't move at all (I can't even scroll through my toolbar) and it just teleports me away from my ship - sometimes even some kilometers! I don't get stuck forever - after a few seconds I get teleported away anyways

**Comment by BigBadKangaroo** [comment]
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7771769/Player.log)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/7771770/output_log.txt)
And the world, but the bug happend in other worlds as well.
[21w51b.zip](https://github.com/tsunamayo/Starship-EVO/files/7771772/21w51b.zip)

**Comment by commche** [comment]
I can confirm this

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, it is fixed for 21w52a. Cheers!
