### ISSUE TITLE
Off screen object locators not working at 4K

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#4398]
I keep seeing small circles at the edges of the screen in other peoples images of STEVO. I had not seen them in game before until yesterday. I was messing around with the graphics settings to see if I would get better performance in a lower resolution than 3840x2160 (I did not). What I did notice is that in lower resolutions I get these nice circles to tell me where stuff is behind me.

So it would be great if the circles also worked at 4K resolution too. It's a minor point, and I'm just logging it as otherwise I will forget.

PS. I have great admiration for your determination and excellent achievement. This game is a real work of effort and good judgement. I know there are plenty of admirers who want to see this completed well and are happy to wait and support you. We believe in you!

**Comment by tsunamayo** [comment]
@cloudrambler Thanks a lot mate ^^
Do you not see them while flying a ship, or when doing the tutorial? Or maybe both...
I will see if I can find a way to reproduce and keep you posted.

**Comment by tsunamayo** [comment]
@cloudrambler So issue is fixed for 21w52b. Thanks a lot!
