### ISSUE TITLE
Symmetry tool breaks physics a bit.

### ISSUE THREAD

**Issue by thatisjake** [tsunamayo/Starship-EVO#4399]
### Short Description of the issue:

When holding the symmetry tool, physics goes weird.

### Steps to reproduce the issue:

Hold the symmetry tool, approach this blueprint, and watch.

### Environment
- Starship EVO version: 21w51b

### Additional information:

https://streamable.com/kiuke9
Blueprint I first noticed it on
[New Entity.zip](https://github.com/tsunamayo/Starship-EVO/files/7771867/New.Entity.zip)

**Comment by thatisjake** [comment]
Let me add: Once you hold the symmetry tool it makes it so you cannot move, and also cannot swap what item you are holding. You can still look around, and excess the inventory.

**Comment by commche** [comment]
I've been noticing small lag spikes (mini freezes) when my block selection box in the action bar passes over the symmetry tool. Only since the most recent update

**Comment by tsunamayo** [comment]
@thatisjake Yep I reproduced. Fixed for 21w52a. Cheers!
