### ISSUE TITLE
Cant walk around ringworld 

### ISSUE THREAD

**Issue by ADDexia** [tsunamayo/Starship-EVO#4401]
### Short Description of the issue:
I was starting a new world to checkout all the new updates and teleported to the ringworld . I decided I would for fun run around the ringworld. After reaching the halfway point or directly upside down from the normal starting area in the world I hit an invisible wall that made my character get stuck. I could leave with F5 BUT I would still be stuck for a decent distance away from the initial invisible wall before I would be unstuck. Keep in mind the previously traversable area would become un-traversable until I get far enough away and then it would be fine again. 
...

### Steps to reproduce the issue:
Run or fly up the ringworld at ground level, not in the sky at any reasonable speed, I was flying at around x243  on debug mode.  
...

### Environment
- Starship EVO version: current version as of 12/24/2021 
- Graphics Card: nvidia geforce gtx 1060 6gb

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@ADDexia Hi, this is weird indeed. I will check if I can reproduce.

**Comment by tsunamayo** [comment]
@ADDexia Issue fixed in 21w52b. Thanks!
