### ISSUE TITLE
Stuck in warp

### ISSUE THREAD

**Issue by Spaceguy142** [tsunamayo/Starship-EVO#4402]
### Short Description of the issue:
every time I try to warp to a new system, it gets me stuck in warp, and if i get back in it after exiting, i am stranded in the middle of space.
...

### Steps to reproduce the issue:
warp
...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Spaceguy142 Hi, warp is working fine for me. Could you please send me the log file as specified?
Thanks!

Please also include the Player.log file. You can find the log file here: %UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\

**Comment by BigBadKangaroo** [comment]
I had this issue too. It happend to me after warping a couple of times. If you are too close to a planet the warp doesn't warp you in a straight line, it warps you around the planet and you will never arrive at the system you wanted to warp to.

**Comment by Spaceguy142** [comment]
> I had this issue too. It happend to me after warping a couple of times. If you are too close to a planet the warp doesn't warp you in a straight line, it warps you around the planet and you will never arrive at the system you wanted to warp to.
It happens to me no matter what when I try to warp.

**Comment by Spaceguy142** [comment]
> @Spaceguy142 Hi, warp is working fine for me. Could you please send me the log file as specified? Thanks!
> 
> Please also include the Player.log file. You can find the log file here: %UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\

Here is my log:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7795936/Player.log)
:

**Comment by tsunamayo** [comment]
@Spaceguy142 @BigBadKangaroo Hi, this issue should be fixed in 22w02a. Thanks!
