### ISSUE TITLE
docking connector placement bug on a child entity

### ISSUE THREAD

**Issue by OvercomeDruid** [tsunamayo/Starship-EVO#4405]
### Short Description of the issue:

Hello :) I want to connect my capsule ( Picture 1) to my ship ( Picture 2) with a docking connector but when I connect them together (Picture 3), the capsule is placed in another place ( Picture 4). the parent docking connector is located on a child entity placed on a hinge. 
...

### Steps to reproduce the issue:

take the  ''Capsule republic cruiser 2'' blueprint  ( Picture 1) and connect the docking connector to that of the `` republic cruiser 9 '' blueprint located just before the front right landing gear ( Picture 2)
...

### Environment
- Starship EVO version: 
- Graphics Card: Nvidia GeForce GTX 1070 Ti
### Additional information:

Pictures :

![269832712_285462180213168_7151109201969092076_n](https://user-images.githubusercontent.com/96711786/147436093-ec002210-db8f-467c-8739-dde04168895d.png)

![269784385_288597613107112_4854679439495037020_n](https://user-images.githubusercontent.com/96711786/147436123-f2ddb8a0-721b-4584-ae36-8e71ad7df978.png)

![269874629_463222605191771_5414513640717397300_n](https://user-images.githubusercontent.com/96711786/147436141-9548a8ff-c24a-4bc8-acc2-f950e83910c6.png)

![269973406_648058083016342_165865270820582715_n](https://user-images.githubusercontent.com/96711786/147436159-331dbbc0-9137-4c9c-b093-41430f25ccde.png)

`Player.log` file :

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7778480/Player.log)

Blueprints :

[republic cruiser 9.zip](https://github.com/tsunamayo/Starship-EVO/files/7778406/republic.cruiser.9.zip)

[Capsule republic cruiser 2.zip](https://github.com/tsunamayo/Starship-EVO/files/7778405/Capsule.republic.cruiser.2.zip)

Thank you for your help et un grand merci de la part d'un compatriote linguistique  pour ce jeu génial ;)  !!!

**Comment by tsunamayo** [comment]
@OvercomeDruid Hi, this is fixed for 21w52b.
Merci beaucoup pour les encouragements! Bonne annee a toi ^^!

**Comment by OvercomeDruid** [comment]
@tsunamayo  Ok , thank you for being quick ! 

Merci bonne année à toi aussi ;) !
