### ISSUE TITLE
Game Breaks at 700 logic gates

### ISSUE THREAD

**Issue by thatisjake** [tsunamayo/Starship-EVO#4406]
### Short Description of the issue:

I'm not sure if it is the actual just amount of my logic gates, or if theres something else going on entirely here.

### Steps to reproduce the issue:

Try to link the logic gates on the right (cyan and an arrow pointing at them) into the indicator lights to the left (also an arrow pointing at them)

the system you see here it a 4 digit binary subtractor, repeated multiple times in order to find which of the 4 binary numbers is closest to the other binary number. I was planning on using it for a 16 floor elevator, which travels to the closest of the inputs.
### Environment
- Starship EVO version: 21w51b

### Additional information:
Tried restarting sevo, making new worlds, everything really. Its when I connect the cyan gates to the right into the indactors that it breaks the game.

[Binary Rounder.zip](https://github.com/tsunamayo/Starship-EVO/files/7778639/Binary.Rounder.zip)

**Comment by tsunamayo** [comment]
@thatisjake Hi, I can reproduce the bug, I keep you posted.

**Comment by tsunamayo** [comment]
@thatisjake Hi, are you 100% positive there is no circular loop in those gates?

**Comment by tsunamayo** [comment]
@thatisjake Okay this will be fixed for 21w52b. I had to optimized my check so the PC dont die on checking your link chain... cheers
