### ISSUE TITLE
[BUG] Copy Paste Issues 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#4419]
### Short Description of the issue:
when attempting to paste a child entity into its "housing" it is not pasted and i am unable to place blocks in certain orientations on that entity  
...

### Steps to reproduce the issue:
load up bp, copy the one of the smaller front "wings" and paste it into the "housing" shown in video 
...

### Environment
- Starship EVO version: 21w52a

### Additional information:

https://user-images.githubusercontent.com/56371294/147837586-86655f75-79fe-4aeb-ba2a-35c47925d0d7.mp4

BP:
[naming things is hard.zip](https://github.com/tsunamayo/Starship-EVO/files/7796958/naming.things.is.hard.zip)
Log:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7796963/Player.log)

**Comment by TIKIRobo** [comment]
I figured out why it wasn't pasting, there was a small block in the way however the weird inability to place blocks after is still an issue

**Comment by tsunamayo** [comment]
@TIKIRobo Hi, indeed I was able to reproduce the second issue. Issue fixed for 22w02a. Thanks
