### ISSUE TITLE
Collision Points on Fence Corner do not match shape of Fence Corner

### ISSUE THREAD

**Issue by jasonfogleman** [tsunamayo/Starship-EVO#4432]
### Short Description of the issue:
Collision Points of Fence Corner piece extend beyond the visible fence corner. 
...

### Steps to reproduce the issue:
enable View Collision Points and look at a Fence Corner piece. 
...

### Environment
- Starship EVO version: 21w52a
- Graphics Card: NVIDIA GeForce GTX 1060 3GB

### Additional information:

Issue is visible in this screenshot where the fence corner was intended to be used as a landing gear. Craft won't land level due to collision of the corner being cubic instead of matching the visual of the Fence Corner. 

![image](https://user-images.githubusercontent.com/87847101/147862526-fe1e5c07-8536-41f3-be47-a278f3d05a5b.png)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@jasonfogleman Hi, thanks for booking these. Now I understand that it is not great but I wont fix those I am afraid =(...
There are plenty of slightly angled brick out there that have a basic collision shape, it would be too complicated / costly to make a perfect collision shape out of them. This works like that for plenty of game btw!
I would suggest make a similar shape with an hull arch brick, you could even make a prefab out of it if you plan to re-use that often.
Thanks!
