### ISSUE TITLE
[BUG] Fuel Scoops can't be painted 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#4434]
### Short Description of the issue:
Fuel scoops will remain the default steel even after being painted 
...

### Steps to reproduce the issue:
paint a fuel scoop
...

### Environment
- Starship EVO version: 21w52a

### Additional information:

https://user-images.githubusercontent.com/56371294/147884266-2e8232f3-db60-4186-b3c4-6348ebe6fa50.mp4

**Comment by tsunamayo** [comment]
@TIKIRobo Hi, yeah I know they are still wip ^^
