### ISSUE TITLE
[Bug] Event Gate does not output signals from mechanisms

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4443]
### Short Description of the issue:
When linking a mechanism to an Event Gate, the gate does not output a logic signal when its conditions are satisfied.

Also a question, I'm writing up the Wiki page for the Event Gate but I'm not sure what the Command Label field does. Does it have a function at the moment?

Happy New Year!

### Steps to reproduce the issue:
- Load the attached bp and toggle the red Switch for an easy test
Or - 
- Link a Piston to an Event Gate
- Link the Event Gate to an indicator light/button
- Configure the Event Gate to activate halfway along the Piston
- Toggle the Piston and note no signal is outputted by the Event Gate

### Environment
- Starship EVO version: 22w01a
- Graphics Card: RX 580 8GB

### Additional information:
[Wiki Tests.zip](https://github.com/tsunamayo/Starship-EVO/files/7803230/Wiki.Tests.zip)

**Comment by tsunamayo** [comment]
@ProPeach Sorry yeah I will remove the Command Label as it was an aborted attempt as I elected to use the Tag tool.

Happy New Year! ^^

**Comment by tsunamayo** [comment]
@ProPeach Hi, issue is fixed for 22w02a. Thanks!
