### ISSUE TITLE
[Bug] Computer -> Event Gate percentages do not enter correctly

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4446]
### Short Description of the issue:
More a readability problem than a bug perhaps. When entering a percentage into this menu, the text field seems to ask to enter the percentage directly. Say I want to enter 45 percent, I type 45 into the field:

![image](https://user-images.githubusercontent.com/27857711/147978131-36bdf4de-87bb-48da-b2ad-750662b05da9.png)
The resulting percentage is multiplied by 100 to make 4500%

Seems like the text field wants the player to enter their percentage as a fraction of 1, so if I wanted to enter 45% I would need to type 0.45
So either the text field label needs to reflect this and ask for a fraction, or the players input needs to be divided by 100

### Steps to reproduce the issue:
- Link a Spaceship core to the Event Gate and select a percentage based event
- Type a percentage into the field

### Environment
- Starship EVO version: 22w01a
- Graphics Card: RX 580 8GB

**Comment by tsunamayo** [comment]
@ProPeach Hi, issue fixed for 22w02a, now you can input 45 and it will do the conversion. Cheers
