### ISSUE TITLE
please recover my ship 🙇‍♂️ (blueprint/entity data corruption on system crash)

### ISSUE THREAD

**Issue by kynamats** [tsunamayo/Starship-EVO#4450]
### Short Description of the issue:
I've been having issues with my PC, except I'm dumb and still play games on it..
Long story short my ship's entity data is corrupted. I've recovered lost work before by copying the .sevo and .xml files from the entity list over to a new blueprint folder, which has always worked. except this time. when I checked the .xml it was blank, and the .sevo and .sevobu files won't spawn anything.

When I loaded back into the world the 2nd time after crashing (the 1st was a pure black void) I could see parts of the ship dancing around and was briefly affected by its gravity generator before it fully vanished. (I have no idea if this is relevant)

I'm aware this doesn't really qualify as an Issue with your game (which I ADORE and will keep playing for years to come) but I was hoping if I share the .sevo and .sevobu files you could have a look at them? Included below :) (7B66A..) I've also attached the whole character file of the crashed world. (W005)

Thanks - Jake
...

### Steps to reproduce the issue:
pull out the power cord while building? yank out a RAM stick? 
...

### Environment
- Starship EVO version: 22w01a
- Graphics Card: 3070ti

### Additional information:
I think my PC's issues are RAM related?
_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.
[7B66AAE1-D2B49.zip](https://github.com/tsunamayo/Starship-EVO/files/7817976/7B66AAE1-D2B49.zip)
[W005.zip](https://github.com/tsunamayo/Starship-EVO/files/7817979/W005.zip)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7818013/Player.log)

**Comment by tsunamayo** [comment]
Hi, okay let me check this, I will keep you posted.

**Comment by tsunamayo** [comment]
@kynamats Hi, well I have some bad news unfortunately but it seems a low level corruption, there is simply no longer any relevant data in those files. And it seems it also affected the backup save and the xml too...
Now I would like to know what happened, so I can see if it is a game issue, and also improve the backup system.
So it was a crash, do you think it was game related or does your PC game crash often?
I hope you had this blueprint exported somewhere before...
Thanks

**Comment by kynamats** [comment]
@tsunamayo Ah thats too bad, thanks so much for taking a look though!
yeah my pc crashes sometimes while gaming - its a new build and i'm 90% sure the RAM is broken, but i need to buy some more components to check. Regardless of what's causing it, its an instant black screen, like if you held down the power button to force power off. It crashes so quickly that Windows can't register what's caused it, so it just comes up as a kernel power event 41, but not all games cause it equally; for example any Vulcan based game will crash much more often. I have noticed, since the 22w01a update, that its been crashing more often (once a day vs once a week before) 

Unfortunately I was getting back into the game after a while off, and i always forget frequent saving until something like this happens to remind me, so no backup blueprints :( its gone...
Thanks again for taking a look, it's really going above and beyond :)
