### ISSUE TITLE
Police Interceptors attacking each other

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4456]
Version: 22w01a
GPU: 970M

It happened when I attacked the station and my guess is, at least one of them shot at the station by accident when shooting at me and then, started attacking each other instead:

https://user-images.githubusercontent.com/63756057/148448140-bc4fe173-01fd-4264-896c-6820b83b652f.mp4

**Comment by tsunamayo** [comment]
Hah funny enough, I will fix those.

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Hi, this is fixed for 22w03a. Thanks!
