### ISSUE TITLE
[bug] Trap Door hitbox

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#4457]
The game isn't allowing me to place a brick next to one of the trap door's edge

![image](https://user-images.githubusercontent.com/73253472/148471402-b7730436-6438-47ef-a85e-18c1ce901538.png)

**Comment by cloudrambler** [comment]
For reference, this appears to be a related problem to #3420, where the Trap Door hitbox prevents player movement to one side.

**Comment by tsunamayo** [comment]
@Uncle-Ulty Issue fixed for 22w03a. Now door uses children entity, so there is less bug and you can add decals on them. Thanks

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo Oh, CE-based trap door is something I've always wanted to have!
