### ISSUE TITLE
[Probable BUG] Thrusters not mirroring perfectly

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#4459]
The round thrusters have visual details with a rotational symmetry of three, meaning that if you rotate it 90 degrees, it looks different. Presently a mirrored round thruster will mostly be oriented differently to a true mirror.

As far as I can see, the game is differentiating between thruster mirrors that need to be reoriented 180 degrees, and those that need to be oriented as per the original. Except that it appears to be applying those two cases incorrectly (inverted outcome). Thrusters that should be reoriented are being kept as per the original and thrusters and thrusters that should retain the original's orientation are being reoriented 180 degrees. So I suspect a swap of the two logical outcomes will correct the problem.

Note that for a double mirror (X and Y), the outcomes are correct, as in that case ALL round thrusters need to be reoriented 180 degrees regardless of their starting orientation, so the present logic works for that special case (for the wrong reason).

**Comment by tsunamayo** [comment]
@cloudrambler issue fixed for 22w02a. Thanks!
