### ISSUE TITLE
[BUG] Round thruster texture scaling

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#4461]
There seems to be a scaling problem with the round thruster outside texture. When the round thrusters are stretched longitudinally, the grey detail ring at the nozzle end gets shorter as the thruster gets longer. As a guess I would say the texture scale is the reciprocal of the length, so a 2m long thruster has a texture that is 1/2 the length of the 1m version.

To replicate:
Place some round thrusters of different lengths but the same diameter.
The textures will appear cramped for the longer instances.

Effective of version: 22w01a
Graphics card: GTX1070

**Comment by tsunamayo** [comment]
@cloudrambler Hi, issue is fixed for 22w03a. Thanks!
