### ISSUE TITLE
Symetry not in center of block

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#4463]
Hi there,

I can't place symetry in the center of the block on any grid larger than the 1m!
I tested some options in the F1 menu but nothing changes.
None of the 3 possible axes are able to be placed in the center of the block.

![20220109180416_1](https://user-images.githubusercontent.com/81495956/148692611-dad99cd5-64fb-40d3-92dd-bb3633a7fba9.jpg)

**Comment by Kaiser-Indrasil** [comment]
I've noticed that symmetry can adhere to the grid size now, even as small as 1/8m, so maybe that will help.

**Comment by Uncle-Ulty** [comment]
you can change the symmetry grid for finner adjustment

**Comment by tsunamayo** [comment]
@BigBadKangaroo Yes, indeed, Kaiser is right you can get away with mini grid but that is not very user friendly... I will fix it. thx

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, this will be fixed for 22w03a. Thanks!
