### ISSUE TITLE
[Suggestion] Beginner Tutorial Idea

### ISSUE THREAD

**Issue by daver100** [tsunamayo/Starship-EVO#4468]
Heyo, new here.

@tsunamayo 

I've been enjoying checking out this game and seeing it's evolution for a bit and after seeing some posts on mechanics and how the tutorial should be I have been thinking about how a beginning tutorial could look like where it taught the new player how everything kind of works.

My current rough idea plays as  follows:

- Player spawns in a teleporter that's tucked away inside a hangar cargo area. This is where we'd do the initial jetpack tutorial where you fly over a stack of cargo containers and then through slanted support beams, very similar to what François has made, then touch ground where big hangar doors reside.

- Player then proceeds to open these hangar doors to a large room with very little in it except for a cargo vehicle to the side.

- Unless we go completely text based for this game, a voice would come on and say something akin to "Hey what are you doing down there, no one's supposed to be here, this facility isn't supposed to open for another month! Who are you, what's your name?" = cue character creation

- The voice then goes "I don't know how you got in here but, no one told me someone was supposed to be coming in." voice talks away from microphone "Did you know about this?" microphone cuts out, then back in "Well this is news to me, whatever... I didn't know we hired contractors now. I've got some good news and some bad news... Good news is your on the clock, you start working now. Bad news is we haven't gotten the new mining rigs in but you can make one to start you off. Hope you got a Multitool on you 'cause there ain't any extra and I'm not lending you mine!" = cue multitool pop up, "Oh good, you do"

- "Get on that cargo vehicle and we'll get you started." Player gets into vehicle, "You'll want to head on down the mine shaft "Start laserin' away at those rocks down there. On you go!" Player drives a short distance to a rock wall and starts to mine out rocks/ore. Once the player inventory is full, the voice would say "Now load that all up in to the cargo containers at the back." do this until cargo containers are full then drive back. "Put all that there ore in the refinery... What?! There isn't any refinery down there -*sigh*- Check in the containers around there, there should be materials for one... Oh and a crafter" (crafter being whatever the basic bench is going to be called if we're going in that direction rather than building whatever you need on your person) Player then goes to a container box in the corner of the room and takes out all the materials in it to make what is needed. "Build a conveyer between the two so you don't have to keep throwing stuff from one side into the other" Player then builds a small conveyer pipe between both blocks to link them ala Space Engineers where both could be operated through the same menus.

- "Throw your ore in there." Player now puts the ore in the refinery and then proceeds to make hull blocks (unless, again, we only need the refinery and build things directly out of pocket more like Valheim). A sliding door then opens to reveal an incomplete vehicle which is where you learn to make one, also similar to what is already in the game with the flying repair shuttle but it then asks you to make a cockpit as well out of the hull blocks you made. Now you have a drilling rig. "What a nice little drilling machine you made... Now go do some real work!" The voice shouts.

- You head on down and drill some ore, much faster than before, and then are instructed to head back and send in your collection. You sell your ore at a station, make some money, and learn a little bit about commerce. As you back out the machine starts smoking and malfunctioning. "What did you do? Did you just break it?.. well... fix it!" = cue how to repair things with the multitool.

- Bell rings overhead, "Well that's the end of my shift, feel free to exit whenever you want. Keep going or head out, your choice." Mic cuts out and the player can either continue mining for fun and make a little bit of money or leave the hangar and enter the world above (putting a loading screen here and then you have your first walking out moment for the game, similar to Bethesda games)

END OF THE BASIC TUTORIAL

**Comment by THE-SIMPLE-MARK** [comment]
This sounds like a really good idea!

**Comment by tsunamayo** [comment]
@daver100 Hi, haha thanks I enjoyed reading it, it could be a nice introduction indeed. If I had 20 people working for me I would do something like this.
I will add LUA mission so that the player-base can come up with stuff like this...
But to be honest if I change the tutorial again it will be to make it simplier, not more advanced. There is just too much fail point, and some people have trouble even with basic stuff so as I dont have an army of basic tester (I only have advanced tester), I cant make it work reliably.
Cheers!

**Comment by daver100** [comment]
> @daver100 Hi, haha thanks I enjoyed reading it, it could be a nice introduction indeed. If I had 20 people working for me I would do something like this. I will add LUA mission so that the player-base can come up with stuff like this... But to be honest if I change the tutorial again it will be to make it simplier, not more advanced. There is just too much fail point, and some people have trouble even with basic stuff so as I dont have an army of basic tester (I only have advanced tester), I cant make it work reliably. Cheers!

Alrighty, thanks for checking out my idea anyways. Keep doing what you're doing, it's shaping up to be awesome.
Cheers ;)
