### ISSUE TITLE
A delay between input and outputs of logic gates.

### ISSUE THREAD

**Issue by thatisjake** [tsunamayo/Starship-EVO#4469]
### Short Description of the issue:

A delay between input and outputs. Keep in mind, no timers here. (Its a binary subtractor)

### Steps to reproduce the issue:

Play with the switches, there is a small delay between the inputs and outputs. (most noticeable when the bottom row of switches are pressed like this
![image](https://user-images.githubusercontent.com/40440275/149440799-4e242c71-4aa3-411a-9235-9ad91097678d.png)
)

### Environment
- Starship EVO version: www01a

### Additional information:
[4-Bit Binary Subtractor.zip](https://github.com/tsunamayo/Starship-EVO/files/7867185/4-Bit.Binary.Subtractor.zip)

**Comment by tsunamayo** [comment]
@thatisjake Hi, yes I think it is normal, the logic gate only execute once per frame to make sure that all its input are set correctly. So it will have a frame delay.

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo Have you introduced any kind of change recently to the logic refresh rate? I feel like it changed in the last one or two patches.
Before, [this turret](https://steamcommunity.com/sharedfiles/filedetails/?id=2566927098) would shoot at a fairly consistent rate but recently, it started to act strangely and shoot noticeably more inconsistently.
It's especially noticeable at low fps (30).
Pay attention to the upper right button which doubles as a gun firing indicator.
Sometimes it fires once but then there are times when it fires twice in a quick succession:

https://user-images.githubusercontent.com/63756057/149764062-77f772d5-fdd3-4c7f-adb6-14042401f4d4.mp4
