### ISSUE TITLE
[BUG] Repair problem

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#4475]
There is a problem with repair... Once the brick is destroyed, even if you fix it (manually or at the dock), the brick won't work again... In this situation, I lost both light cruise thrusters, and even after repairing, I couldn't use light cruise mode

![image](https://user-images.githubusercontent.com/73253472/149648143-0c44cfbb-247e-4e59-b850-0c22e92ea85e.png)
[Excelência - MR Interceptor (damaged).zip](https://github.com/tsunamayo/Starship-EVO/files/7876433/Excelencia.-.MR.Interceptor.damaged.zip)
[Excelência - MR Interceptor (brand new).zip](https://github.com/tsunamayo/Starship-EVO/files/7876434/Excelencia.-.MR.Interceptor.brand.new.zip)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7876435/Player.log)
[Bounty.zip](https://github.com/tsunamayo/Starship-EVO/files/7876436/Bounty.zip)

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hi, both your ship have thrusters and lightcruise...

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hi, I have fixed an issue on system that explained the lack of lightcruise after repaired. But I cant reproduce the brick not showing... Fix for 22w03a. Thanks!
