### ISSUE TITLE
Not respawning after death

### ISSUE THREAD

**Issue by Tisdag1** [tsunamayo/Starship-EVO#4477]
### Short Description of the issue:

When I die on the new bounty missions I cannot respawn. I sit there floating in space unable to move or open the codex using tab. Before heading out I made sure to Scan myself at the station Medbay for the inevitable demise that was coming. After dying, instead of spawning back at the station, I just sat there floating unable to do anything. So I exited to desktop, relaunched the game & loaded up my file to see if that would help. After that failed, I deleted my game & started a new one. But this time I loaded in a blueprint of a ship that had a Medbay on board, Scanned myself into the Medbay, got a bounty mission & promptly died. Again floating in space unable to respawn, move, or access the codex by hitting tab. I have tried this 3-4 times now, all with the same results. 

### Steps to reproduce the issue:

Scan yourself into the Medbay, hop into a ship & proceed to let someone take out their frustration on you. :P

### Environment
- Starship EVO version: 22w02a
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![20220116133114_1](https://user-images.githubusercontent.com/95005604/149677105-db57145a-3eab-44bc-b341-1287a5a0a6cc.jpg)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7877898/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Tisdag1 This should be fixed in recent version. Thanks
