### ISSUE TITLE
Hypersonic hovercraft

### ISSUE THREAD

**Issue by KiloTheNeko** [tsunamayo/Starship-EVO#4478]
### Short Description of the issue:
hovercraft becomes a catapult to space launching itself at about 446 m/s
...

### Steps to reproduce the issue:
make a hovercraft

enter hovercraft

enter photo mode

move camera around

exit photo mode once the sound of the engines whirrs at unbearable sound levels
...

### Environment
- Starship EVO version: 22w0a
- Graphics Card:  RTX 2070 Super

### Additional information:

![20220116235551_1](https://user-images.githubuserc
[Hovercraft platform.zip](https://github.com/tsunamayo/Starship-EVO/files/7878125/Hovercraft.platform.zip)
ontent.com/65069111/149681720-07844cf7-b4eb-41d4-9a51-f90f40e1b203.jpg)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7878127/Player.log)

![20220116235537_1](https://user-images.githubusercontent.com/65069111/149681819-3e171d3e-33a8-4b82-aa3b-4eb6fe82bac3.jpg)

**Comment by Uncle-Ulty** [comment]
everything can be launched into space after you enter the photo mode... character, hovercraft, spaceship, etc

**Comment by tsunamayo** [comment]
@KiloTheNeko Hi, issue will be fixed for 22w04a. Thanks!
