### ISSUE TITLE
Warp jump bug 

### ISSUE THREAD

**Issue by Silvermaster35** [tsunamayo/Starship-EVO#4479]
### Short Description of the issue: the warp jump is broken. when i activate it gets stuck in a loop and i have to exit the game. it fixes it self when i go back in the game but the warp still dose not work. i tryed it in (none) version. i tryed it in the (experimental ) Version still dose not work.

...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 
https://youtu.be/wg8itnz7d6Q
### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
https://youtu.be/wg8itnz7d6Q
Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Silvermaster35 Hi, issue is fixed for 22w03a. Thanks
