### ISSUE TITLE
[BUG] Trap Door and Blast Door Error Message

### ISSUE THREAD

**Issue by Servomotor** [tsunamayo/Starship-EVO#4481]
### Short Description of the issue:
I am getting an error message when I place a sticker on the Trap Door or Blast door. You can see the error message in the screenshots.
The error message reads "The mass on this children entity is beyond the maximum: Infinity. This mechanism wont be able to move."

Functionally, both doors seem to work right, its just the error message that seems to be the issue.
...

### Steps to reproduce the issue:
Place sticker on Trap Door and/or Blast Door
...

### Environment
- Starship EVO version:  22w03a
- Graphics Card: RTX 2080

### Additional information:
![20220118042920_1](https://user-images.githubusercontent.com/65745916/149920869-363beb5b-c849-47aa-98e7-f4313fa4d2dd.jpg)
![20220118042933_1](https://user-images.githubusercontent.com/65745916/149920884-cd1b0464-19b3-43a2-919a-3c18956611a6.jpg)

![20220118043153_1](https://user-images.githubusercontent.com/65745916/149920899-ded01053-07e5-472f-b405-d7927aabed76.jpg)
![20220118043201_1](https://user-images.githubusercontent.com/65745916/149920906-7e1e4ef0-44bd-4675-b634-3e7ff3c75839.jpg)

**Comment by tsunamayo** [comment]
@Servomotor Hi, issues is fixed for 22w03b. Thanks
