### ISSUE TITLE
[Bug] Mirror planes not placing right

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Starship-EVO#4482]
### Short Description of the issue:

So it appears that in build 22w03a there was an attempt to fix bu #4463 However now the symmetry tool appears to actively avoid the edge of some bounds. 

![image](https://user-images.githubusercontent.com/43644633/149957313-8d04d8b2-b683-4026-89a7-276c6e74a8f9.png)
As you can see here it locks to the middle of a block and won't apply to the seam of the block. 

![image](https://user-images.githubusercontent.com/43644633/149957494-a0a418c1-c27e-4aa7-bb71-cb6947bdd6b5.png)
This issue continues to persist at all scales

![image](https://user-images.githubusercontent.com/43644633/149957712-d3b0cfaf-d056-4244-9f5c-da9abb211719.png)

### Steps to reproduce the issue:

Try to use the mirror tool on the edge of the grid. 

### Environment
- Starship EVO version: 22w03a

**Comment by ProPeach** [comment]
I actually think that the way mirror planes placed before the #4463 report came in was much more useful, having the planes snap to the edge of a grid feels nicer to me - you can just drop down a scale if you want the plane in the middle of the a brick. I do see some limited use cases for this new method, like building an odd width ship out of 1/8th bricks, but I've never found myself in a situation where I've wanted the mirror planes to snap to the center of every brick grid like they do now.

Maybe if the mirror tool also reacted to the Placement Sub Grid setting, that would allow some players to center their mirror plane without reducing the scale? That would allow the plane to snap to the edge of the grid for most applications like before todays patch, but with the setting there if players wanted it

**Comment by PopkaAkula** [comment]
Like what Peach said, the only real solution here would be letting the mirror plane work in 1/2 increments so you can have it snap on the edge or the middle of a block. 
Personally, I only ever build in 1/8th scale so I have never been in a situation where I need to have it snap to the middle of blocks.

**Comment by Servomotor** [comment]
I don't know what is going on, all I know is that I can no longer snap to the middle of my builds with the most recent patch. I prefer the old what.

**Comment by Rocinantus** [comment]
After spawning a ship of mine with turrets on it I tested to see if I could get the symmetry centred on the turret.
For some reason it could be centred on the turret by changing the scale but nothing could be done on the main ship.

**Comment by Regnion** [comment]
Please allow changing the scale size to also change the placement of the mirroring. It was working before, it works, it's a great feature, it causes no harm, and it's extremely useful.

**Comment by Kaiser-Indrasil** [comment]
The old way of symmetry snapping was the best one IMO - when we could snap the plane to the middle or to the edge of a block.

**Comment by Uncle-Ulty** [comment]
The old symmetry system was way better...

Also, I'd suggest adding more tooltips on certain features, so the new players don't get totally lost.

**Comment by cloudrambler** [comment]
@tsunamayo The present build (22w03a) ONLY allows the mirror plane to be at the centre of the blocks, for any selected scale. This prevents us from creating mirrors on the grid lines, so builds of even block symmetry are not possible. This is a BIG problem and IMO breaks the game for all serious builders.

I think we need the symmetry placement to work as stated above, where it will allow middle or edge placement at all build scales.

**Comment by tsunamayo** [comment]
@cloudrambler yep I agree, I am on it and will get a fix out asap.

**Comment by tsunamayo** [comment]
@Garrett-C Okay, issue is fixed for 22w03b. It works also for large grid-scale. Thanks
