### ISSUE TITLE
Arch not full size

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#4484]
The "Arch" block scales to 15x16x16, rather than 16x16x16. This seems to be at odds with the general trend of block scaling; and also the "Window Tile Wedge" which does scale fully to 16x16x16.

Found using build: 22w03a

**Comment by pinesh** [comment]
It should be clarified that the 15x stretch is in width.

**Comment by tsunamayo** [comment]
@cloudrambler Hi, issue fixed for 22w03b. Thanks
