### ISSUE TITLE
Pasting Child Entities Breaks The Game/Main Entity

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#4485]
### Short Description of the issue:
I copied a hinge that also had 1 other hinge on the copied child entity(was literally a total of: 2 hinges, 6 blocks), pasted it then I could build or break anything. I restarted my game and now I have a super odd interaction on the parent entity. I can't place any regular blocks and other blocks can only be placed at certain rotations for whatever reason. But I can build on other entities just fine it seems but this entity is now broken. (I shouldn't need you to fix it as I just began framing it out)

### Environment
- Starship EVO version: 22w03a
- Graphics Card: GTX 970

### Additional information:

I restarted my game forgetting about the player.log file so this one is the aftermath (odd placement issues upon restart)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7891608/Player.log)

![20220118124627_1](https://user-images.githubusercontent.com/32974671/150000120-4641869c-2e39-4d16-84d9-985b27b9cf15.jpg)
![20220118124625_1](https://user-images.githubusercontent.com/32974671/150000134-2910c2d8-586f-4b26-85bf-4be22c2cfe51.jpg)
![20220118124623_1](https://user-images.githubusercontent.com/32974671/150000145-19a9a3c6-3e52-4643-bd32-8cca517ac77f.jpg)

**Comment by pinesh** [comment]
The same experience here when pasting something that contains CE's. 

_Here, 3 turrets were supposed to be pasted_

![image](https://user-images.githubusercontent.com/14081996/150001546-ca858b34-1649-4fc7-bc54-16e222ec99cc.png)
After pasting, all the base rotors appeared, and one of the hinges for elevation. the other entities failed to render.
![image](https://user-images.githubusercontent.com/14081996/150001614-434e7c84-5ed3-4ca8-ad5a-ecbee06fa8bd.png)

After pasting, I was unable to place or delete blocks until restarting my game. 

Player Log(s)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7891663/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/7891667/Player-prev.log)
.

**Comment by tsunamayo** [comment]
@Xerma @pinesh Thanks for reporting this, issue fixed for 22w03b. I am uploading the build soon. Cheers
