### ISSUE TITLE
[BUG] Thruster texture again :P

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#4486]
Thank you @tsunamayo for attending to #4461. Unfortunately the fix has caused another problem. The outer now texture scales correctly along the round thruster axis, but the lateral texture scaling is weird. It's normal if the thruster is 1x1xLength, but for 2x2xLength and above, the texture is unevenly distributed and it looks a little messy.

Effective of build:22w03a

To replicate:

Place a round thruster (any scale) with a base diameter >1.

At first I thought you had added extra details for the larger scale thruster blocks, but then I realised it's not a controlled pattern, just the same texture being misapplied in additional instances.

**Comment by tsunamayo** [comment]
@cloudrambler Hi, issue is fixed for 22w03b. Thanks!
