### ISSUE TITLE
[bug] Wrongly mirrored decals

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#4488]
The most recent added decals are turning upside down when mirrored.

![image](https://user-images.githubusercontent.com/73253472/150037463-719a611f-56dc-4ec5-b3ef-756cb0e7164d.png)

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hi, issue is fixed for 22w03c. Thanks!
