### ISSUE TITLE
[BUG] Rotor replaced hinge head after copy&paste and restart

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#4489]
### Short Description of the issue:
i really have no way else to describe it than:
![Starship EVO 1_18_2022 5_13_57 PM](https://user-images.githubusercontent.com/56371294/150039479-bc83f7da-7f43-46e3-8620-2db99e0387c3.png)

### Steps to reproduce the issue:
no clue
...

### Environment
- Starship EVO version: 22w03a-b
### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7893175/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/7893176/Player-prev.log)

**Comment by tsunamayo** [comment]
Hi, is it a new entity? Or something you started before the last two update?

**Comment by TIKIRobo** [comment]
I started this in 22w03a, i pasted the rotor and hinge set-up and then was unable to delete blocks so i restarted, the game updated to 22w03b and then this happened

**Comment by tsunamayo** [comment]
@TIKIRobo Well looking at your player-prev.log you had the copy-pasting issue. It was fixed in the last update, but your save is still corrupted. I hope it was not something too big!
Cheers
