### ISSUE TITLE
[BUG] chairs dont work when connected to event gates

### ISSUE THREAD

**Issue by COMICLER** [tsunamayo/Starship-EVO#4490]
when ever i try the use an event gate with a chair it doesnt work, ive tried multiple times on old and new ships and it doesnt work.

**Comment by tsunamayo** [comment]
@COMICLER Hi, I have tried it and it works fine for me.
Can you give me a complete test case: what event did you used, and what are you trying to trigger.
You can give me a blueprint instead.
Thanks

**Comment by tsunamayo** [comment]
@COMICLER I think the proper test case was with the message gate as output as it was not working. Issue fixed for 22w04a. Thanks

**Comment by COMICLER** [comment]
yeah ill, send over a blueprint, after messing around a but i cant tell weather its a bug or weird logic, or both
