### ISSUE TITLE
[Bug] Rotor placement ghost offset

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4491]
### Short Description of the issue:
The moveable part of the rotor is offset in the placement ghost
![image](https://user-images.githubusercontent.com/27857711/150180729-fd423f1b-ccba-4424-b65e-a939f8a93b2f.png)

### Steps to reproduce the issue:
Hold a rotor in your hand and aim it at a block

### Environment
- Starship EVO version: 22w03b
- Graphics Card: rx 580

**Comment by tsunamayo** [comment]
@ProPeach Hi, issue is fixed for 22w03c. Thanks!
