### ISSUE TITLE
Inconsistent Mirroring On Child Entities

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#4493]
### Short Description of the issue:
This seems somewhat similar to #4482 

I can't seem to place any mirror planes centered on blocks that are on child entities and the placement seems pretty irregular

### Environment
- Starship EVO version: 22w03b
- Graphics Card: GTX 970

### Additional information:
![20220119184031_1](https://user-images.githubusercontent.com/32974671/150241585-5366ed20-82e0-4377-8bb8-39653fcbeb6a.jpg)
![20220119184021_1](https://user-images.githubusercontent.com/32974671/150241587-d8d757db-c93c-4077-a274-29e0ff37a6b1.jpg)
![20220119183547_1](https://user-images.githubusercontent.com/32974671/150241589-ad7ec53e-02fd-411f-bdbc-09dd838e114a.jpg)

**Comment by tsunamayo** [comment]
@Xerma Hi, I dont have any issues... Could you send me the blueprint? Do you build at an offset? Also is this ship an old one (pre-neovox?) Thanks

**Comment by tsunamayo** [comment]
nevermind I think I reproduced with CE with a grid size > 1m.

**Comment by tsunamayo** [comment]
@Xerma Okay issue fixed for 22w04a. Thanks!
