### ISSUE TITLE
[Question] Child Entities 

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#4494]
Hi Tsuna! I have a quick question regarding child entities and how much or little lag impact they have nowadays. I've started building the ring part of the Lucrehulk from Star Wars and I think using entities would speed up some parts of building.

The one arm I started already has 12 child entities.
How much impact do you think an extra 40 child entities (static) would have on the game?
(between both arms the total, static, child entities would be around 64 --- Before elevators, doors, turrets, etc.)

![20220119194937_1](https://user-images.githubusercontent.com/32974671/150247766-8495e016-dee9-4983-8509-8ff01bbdb634.jpg)

**Comment by tsunamayo** [comment]
@XermaHi, well for a big boi like what you are doing 64 dont seems like a lot at all.
There are a few things left to be optimized but it will impact more higher count CE that this.
I would say it all depends on the size of what your are building, and if you plan to submit it as an official ship (I dont think that is the case). If your PC can handle it then I would say fine!
If you only plan to drop 1 in a world, then you can go much higher than that.

**Comment by Xerma** [comment]
Awesome! I just wasn't sure how much impact they have anymore. Especially from the old times where everyone used nothing but child entities to build things. Plus my GPU is getting rather outdated anymore...
