### ISSUE TITLE
Child entities spawning in the wrong places

### ISSUE THREAD

**Issue by TwoNiner29** [tsunamayo/Starship-EVO#4496]
### Short Description of the issue:
When spawning blueprints, the child entities are spawning in the wrong places. The issue can be temporarily fixed by restarting the game, but after spawning a few blueprints, it happens again.
...

### Steps to reproduce the issue:
save and spawn several blueprints
...

### Environment
- Starship EVO version: 22w03b
- Graphics Card: GTX 1060

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![20220120180034_1](https://user-images.githubusercontent.com/66531332/150318294-1b8f382b-72da-4270-8f36-43fc5ffc9e4f.jpg)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7904212/Player.log)

**Comment by tsunamayo** [comment]
@TwoNiner29 Hi, issue was already fixed for 22w03c, I am uploading the build now. Thanks
