### ISSUE TITLE
[Bug] Exclamation Mark Decal Mirror

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4497]
### Short Description of the issue:
The Exclamation mark decal does not mirror correctly
![image](https://user-images.githubusercontent.com/27857711/150391564-68d3b619-9635-4eb2-b4b5-0db310d34da3.png)

### Steps to reproduce the issue:
- Place a mirror plane
- Place an exclamation mark decal

### Environment
- Starship EVO version: 21w03b
- Graphics Card: RX 580

**Comment by Uncle-Ulty** [comment]
Look for #4488 issue please

**Comment by ProPeach** [comment]
I actually saw that report, but then thought it'd already gone live and this particular decal had missed the fix lol, that's my bad for missing the version number

**Comment by Uncle-Ulty** [comment]
it's not live yet, it will be live on 22w03c, and we already on 22w03b. Lets hope all decals are fixed

**Comment by tsunamayo** [comment]
@ProPeach Yep it is fixed in current 22w03c. Thanks
