### ISSUE TITLE
[Suggestion] Docking Connector Orientation Indicator

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4501]
### Short Description of the issue:
On the placement ghost of the Docking Connector, you can't tell which side the small red arrow will face when placed
![image](https://user-images.githubusercontent.com/27857711/150556044-3216c268-dfee-4c3f-b93a-53e1b6a639fd.png)
![image](https://user-images.githubusercontent.com/27857711/150556058-50c7a8a9-3d71-4e1c-a40e-362efe9785fb.png)
I'm not sure how or if this orientation will come into play, but it determines the docking orientation like back in the Skywanderers days then it'd be great to know the orientation before placing it down to avoid some trial and error

**Comment by ProPeach** [comment]
Just noticed an actual bug with them, the orientation does not mirror correctly either

**Comment by CurioInventorium** [comment]
Also have Docking connectors been completed yet? The description gives me the impression that I'd be able to fly a ship up to another and then dock with it, creating a solid connection. Likewise a ship docking with station.
At the moment it seems to me to only be something for spawning other pieces.

**Comment by cloudrambler** [comment]
When I tried it, they can be connected with the manual docking tool. But there does not appear to be any way of disconnecting them. In fact once connected it looks like both objects become one grid, even if both connectors are deleted.

**Comment by tsunamayo** [comment]
Yep it needs some love...

**Comment by tsunamayo** [comment]
@ProPeach Actually it was a bug, we were supposed to see gizmo arrow. Fixed for 22w04a. Thanks
