### ISSUE TITLE
Export to Workshop Button needs to go somewhere else.

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#4502]
### Short Description of the issue:

![image](https://user-images.githubusercontent.com/14081996/150614217-edd54431-d7b7-497b-af1a-9b98b560f477.png)
![image](https://user-images.githubusercontent.com/14081996/150614895-62fc36bf-297f-41db-97b3-2d65aebb9d6a.png)

Right now, I think there's a bit of confusion for new players as to what the export locally and export to workshop actually do. The workshop is filling up with "New entities" and copies of exiting ships and assets in the game. We're even getting duplicates when people try to re-upload the same ships as one would normally do when trying to save

### Presenting:
123 New Entities:
![image](https://user-images.githubusercontent.com/14081996/150615623-e7302ed2-2765-4761-884d-f37a6c0079ca.png)

The starting zone has been uploaded to the workshop 16 times.
![image](https://user-images.githubusercontent.com/14081996/150615095-8536cbf4-e64d-4017-8d38-b0aba14e1f50.png)

We can enjoy multiple copies of the tutorial template.
![image](https://user-images.githubusercontent.com/14081996/150615186-33953ca8-0aab-4c2e-9283-5bbe1527003c.png)

Hoverbikes
![image](https://user-images.githubusercontent.com/14081996/150615824-420e0191-4064-4eba-9e86-188ed5d6979a.png)

5 Mistrals
![image](https://user-images.githubusercontent.com/14081996/150615973-f664ddb6-6339-4c38-8be6-dddd60a885fc.png)

6 Canis- Interceptors
![image](https://user-images.githubusercontent.com/14081996/150615950-b95d3830-4c66-4d2e-afb5-cff4cf36b249.png)

Reuploads of the same work as people try to resave:
![image](https://user-images.githubusercontent.com/14081996/150615262-9263da1b-3093-4ef9-af05-e93799c8ed6f.png)
![image](https://user-images.githubusercontent.com/14081996/150615395-aff74574-856d-47bf-ba32-47313c60b239.png)
![image](https://user-images.githubusercontent.com/14081996/150615434-38d6a346-a921-4e1a-a454-b9312773ee1a.png)
![image](https://user-images.githubusercontent.com/14081996/150615293-1fecc55b-8ac0-41a8-b91d-60a96833c804.png)
_Even a copy of the hot wing there!_

### To fix the uploads
Renaming _Export Locally_ to _Save Entity_ might be enough to handle most cases. The other option involves moving, hiding, or making the export to workshop button less accessible.

### To fix New Entity 
Put some sort of block in place that doesn't let people upload things called New Entity.

![image](https://user-images.githubusercontent.com/14081996/150614901-23ad223e-a1ce-4e68-8097-e32fe6f72fc0.png)
![image](https://user-images.githubusercontent.com/14081996/150614914-517a88d7-6735-416f-b913-8a2fbc831c4d.png)

...

**Comment by ProPeach** [comment]
Changing the Export button to something like "Save Blueprint" etc seems like the best solution to me, as well as perhaps some confirmation that pressing the button did actually save the ship like a dialog box saying "Save Complete!" flashing up. At the moment I can imagine a newer player getting anxious if they didn't think they actually saved their bp and then exporting it to the Workshop just in case.

In general, another quality of life change would be a check to see if you are about to override a file with the same name, with a dialog option warning the player and asking if they're sure to help minimise lost work. Maybe a reminder alert to save their ship with a name if the player has been working on a new entity for a while without renaming/exporting it?

**Comment by Kaiser-Indrasil** [comment]
@pinesh Quality memes, sir, great job on them.

Maybe there could be a tutorial in game to teach players to click a proper button to save their blueprints?

**Comment by tsunamayo** [comment]
@pinesh Haha thanks for the solid contribution, you made my day. Indeed I think the current layout is awful, I will update it as suggested! Cheers

**Comment by pinesh** [comment]
> 

And thanks for making mine!

**Comment by tsunamayo** [comment]
@pinesh Changed for 22w04a. Thanks!
