### ISSUE TITLE
[Bug] Fuel Pipes cannot clip through Construction Bricks

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4503]
### Short Description of the issue:
Fuel Pipes can clip through all Hull type shapes, but cannot clip through any brick type in the Construction section of the Codex apart from the Girder type bricks it seems.

In my experience this becomes a problem most often when using the Tile and Thin Tile bricks as they are very often used alongside Hull bricks, but it'd be fantastic if pipes could clip through the rest of the bricks in that section too

### Steps to reproduce the issue:
 - Place down a brick from the Construction section
 - Drag a Pipe through it

### Environment
- Starship EVO version: 22w03c
- Graphics Card: RX 580

**Comment by Servomotor** [comment]
Agreed. I often use the 1/2 tile to save brick spam because it will stretch farther than a 1/4 cube brick. The issue however being that pipes will not go through the tiles. 

I don't personally understand why the building bricks and construction bricks are in separate categories to start with.

**Comment by tsunamayo** [comment]
@ProPeach Done for 22w04a. Thanks

**Comment by tsunamayo** [comment]
> Agreed. I often use the 1/2 tile to save brick spam because it will stretch farther than a 1/4 cube brick. The issue however being that pipes will not go through the tiles.
> 
> I don't personally understand why the building bricks and construction bricks are in separate categories to start with.

Because I havent really figured how hull, material and co will pan out for survival. I dont know if those shape will work the same. A lot of those shapes dont really make sense anymore, like the bevel and the tiles...
