### ISSUE TITLE
Paints in Codec do not exist

### ISSUE THREAD

**Issue by TrashLambo** [tsunamayo/Starship-EVO#4507]
### Short Description of the issue:
Paints are empty by default, even on new characters.
...

### Steps to reproduce the issue:
Literally just exist, as far as I'm aware. I've had this issue since the first time I've launched the game, so I don't really have anything helpful there, aside from files.
...

### Environment
- Starship EVO version: 
22w03c DEFAULT
- Graphics Card: 

### Additional information:
Manually editing the Paint.XML file revealed an empty space, filled with several lines of spaces as if you held the spacebar on your keyboard for several hours. I don't have a copy of a file with those empty spaces, as I attempted to delete all text characters in the file and replace it with a copy of the wiki's paint file text to see if that would fix the issue, to no avail.

_(Screenshots, Videos, Error logs, Related issues)_
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/7920532/Player-prev.log)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7920526/Player.log)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7920526/Player.log)

**Comment by tsunamayo** [comment]
@TrashLambo This is pretty bad, when did you first started playing the game? Thanks

**Comment by tsunamayo** [comment]
@TrashLambo Hi, could you please confirm you where looking at PaintPalettes.xml, not Paint.xml ? thx

**Comment by TrashLambo** [comment]
My apologies, was busy with work. There is no such file as Paint.xml in my game's files, unfortunately. I'm assuming there is an interaction between those two files that dictates functionality of painting within the game?
![image](https://user-images.githubusercontent.com/64238009/150936577-50bad740-f21e-42a6-ac6c-bc0974c80fc7.png)

**Comment by tsunamayo** [comment]
@TrashLambo Not sure what happened, you could have also deleted that file it is supposed to be copied from the install in case it isn't there.
Maybe some steam install shenanigan...
Cheers
