### ISSUE TITLE
ship explodes on spawn

### ISSUE THREAD

**Issue by Tuxedo1551** [tsunamayo/Starship-EVO#4509]
### Short Description of the issue:

...

### Steps to reproduce the issue:
shoot a ship until it explodes and no longer flies (considered destroyed by game)
upload it to steam
download it off steam
spawn it
ship now will no longer fly
...

### Environment
- Starship EVO version: 22w03c
- Graphics Card: rx 570

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7921831/Player.log)
If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

[New Entity.zip](https://github.com/tsunamayo/Starship-EVO/files/7921837/New.Entity.zip)

**Comment by Tuxedo1551** [comment]
So a temporary fix ive found is just to switch versions

**Comment by CurioInventorium** [comment]
Still a bit of a bug to be able to download an exploding ship from the workshop tho 🤣

**Comment by tsunamayo** [comment]
@Tuxedo1551 Hi, is the entity attached supposed to be destroyed?

**Comment by tsunamayo** [comment]
@Tuxedo1551 Also could you please send me your steam workshop link? I can save a destroyed ship, I just need to repair it it is all fine.
