### ISSUE TITLE
Ships don't explode when their HP reach 0

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4512]
Version: 22w04a
GPU: 970M

It's a no-brainer.
Just spawn any pirate ship and battle it until one of you loses all their HP.

![Starship_EVO_dhStBmIutm](https://user-images.githubusercontent.com/63756057/151010757-792f0833-593e-4382-bebb-1a2926cc9cdd.png)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Hi, this is fixed for 22w04b. Thanks!
