### ISSUE TITLE
[SUGGESTION] Make Monitor Wedge brick clip to surrounding blocks (just the face of it)

### ISSUE THREAD

**Issue by Servomotor** [tsunamayo/Starship-EVO#4513]
### Short Description of the issue:

Not sure if this files under a BUG or suggestion. But the Monitor Wedged brick clips with itself. It also clips with surrounding bricks.

The screenshots should show what I mean. 

22w04a
RTX 2080
![20220125105305_1](https://user-images.githubusercontent.com/65745916/151023057-ec7dae6a-f863-40d9-bc94-1ddf11a723c4.jpg)
![20220125105230_1](https://user-images.githubusercontent.com/65745916/151023072-7210e43a-5b5b-4930-a632-d8e679449f18.jpg)

**Comment by tsunamayo** [comment]
@Servomotor indeed! Fixed for 22w04b. Thanks
