### ISSUE TITLE
Tetra Hull light bug

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#4514]
Hi there,

the new tetra hull block has the same issue that the arch brick had after it's release.
Same as #4258 
![20220125204618_1](https://user-images.githubusercontent.com/81495956/151049155-3c68a78f-2b9d-45e7-85f7-1361cf533ca6.jpg)
![20220125204622_1](https://user-images.githubusercontent.com/81495956/151049168-07a41d0f-6ec3-4c2c-9b3a-632f16fc048e.jpg)
![20220125204628_1](https://user-images.githubusercontent.com/81495956/151049174-6e630a3f-97f4-4490-a07d-bf306cc04ef2.jpg)
![20220125204632_1](https://user-images.githubusercontent.com/81495956/151049181-cd46dd20-240d-4bb4-adf6-39c82987e23d.jpg)

**Comment by ProPeach** [comment]
The half tile wedge also has this problem

**Comment by tsunamayo** [comment]
@ProPeach Hi, I cant figure out which brick is the half tile wedge ^^
@BigBadKangaroo Issue fixed for 22w04b. Thanks

**Comment by ProPeach** [comment]
> @ProPeach Hi, I cant figure out which brick is the half tile wedge ^^ @BigBadKangaroo Issue fixed for 22w04b. Thanks

Ah sorry, the Tile Triangle!
![image](https://user-images.githubusercontent.com/27857711/151080849-af6574ed-5912-404a-85c9-58af99464d07.png)

**Comment by tsunamayo** [comment]
Okay got it ^^ Fixed too. cheers
