### ISSUE TITLE
[SUGGESTION/CHANGE] SCREEN (both of them)

### ISSUE THREAD

**Issue by Servomotor** [tsunamayo/Starship-EVO#4520]
The Screen in game has a weird offset. It does not flush with the edge of blocks/bricks, its sits back some. 

I am not sure what the design decision was behind this implementation, but in game it seems to be more of a hindrance than a benefit. 

I would like to suggest making the screen sit flush with the edge of a block/brick. 

I use the Screen with some rich text commands to float text off the Screen itself. That text currently DOES sit on the edge of a Block/Brick. 

As you can see in my examples. The orange text that says "Airlock" has some red anomalies because the text clips/sits on the same plane as the Brick Block.

If you choose NOT to move the screens forward to the edge of Blocks/Bricks, can you at least move the actual text 1 pixel forward (towards the front of the screen) so that it does not ride on the exact edge of a Block/Brick?

I hope this makes sense, I am not sure how to explain this more clearly. 

TY

![20220126085648_1](https://user-images.githubusercontent.com/65745916/151195522-0771e29f-25fd-45ed-80cb-5ee36efb7a50.jpg)

V This image is from the top view, looking down onto a block with the Screen sitting on it.
![20220126085729_1](https://user-images.githubusercontent.com/65745916/151195527-1ba328be-0e32-4a3d-a845-b68cb29b8951.jpg)
![20220126085735_1](https://user-images.githubusercontent.com/65745916/151195539-412f28b8-9e39-453e-8606-af67d81463af.jpg)
![20220126085754_1](https://user-images.githubusercontent.com/65745916/151195548-5a1eae4d-ec5c-47e5-9620-883316bcf087.jpg)

**Comment by Servomotor** [comment]
Ohh and in this example. The Red "Airlock" Text is not actually red, its orange...but its clipping on the same plane as the block. 
![20220126083914_1](https://user-images.githubusercontent.com/65745916/151195868-611f3630-5314-43e4-b8ce-2ff3505b1a6c.jpg)

**Comment by tsunamayo** [comment]
@Hi, so I will nuke the screen text implementation so I am gonna close this. Dont use them too much in the ship you want to submit as their perf impact is awful! 
Also when I will switch the tech it might break things. And you are using a bug to make the text float, and the fate of bugs is to be fixed one day... (But I might give you text decals and proper holo display at one point).
Thanks

**Comment by Servomotor** [comment]
Sounds good. I know you have a ton of game play stuff to work on, I just really like to see lots of words and signage as I feel they not only communicate if used properly, but make builds come alive. 

A holo display would be very nice. 

That is a bummer the screens performance impact is bad.

**Comment by tsunamayo** [comment]
Yeah their perf impact is much worse than CE on the rendering side for example. One day I spawn a ship were a guys put 40000 screens (not kidding, that was the number). I had like 7 fps on my RTX3060ti. 
But the new implementation will be much much faster, single pass for all the ships at once just like the rest (right now it is a pass PER screen, hence why it is awful)

**Comment by Servomotor** [comment]
Holy cow. That is insane! 

Well, enjoy these screenshots while they last, LOL. 

Thanks for all your hard work!
![20220126181650_1](https://user-images.githubusercontent.com/65745916/151268789-fa19ba97-e99f-4104-bfc9-318a66c884bf.jpg)


![20220126181532_1](https://user-images.githubusercontent.com/65745916/151268801-8cdf5b63-85ba-4cb7-92f1-1367ae993cbf.jpg)
![20220126181544_1](https://user-images.githubusercontent.com/65745916/151268809-effa043c-40ed-4ca9-bc1c-a9419e1d4b47.jpg)
![20220126181555_1](https://user-images.githubusercontent.com/65745916/151268814-4aa7026b-fe2a-4bc9-bbb0-cdc9201171c1.jpg)
