### ISSUE TITLE
Decals disappear too soon when pulling camera away from them

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4521]
Version: 22w04b
GPU: 970M
Resolution: 1920x1080

This is very apparent with long and thin decals which in this case double as armour seams.
It's especially concerning since I can see them disappear even before I get to the other side, and it's a 60m-wide ship.
[Here's my blueprint used in the video below if you wanted to troubleshoot it.](https://github.com/tsunamayo/Starship-EVO/files/7945204/Astero.Neovox.zip)

https://user-images.githubusercontent.com/63756057/151237917-e67725b5-0f65-4f32-ae48-315a74356df3.mp4

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Hi - thanks for the vid. I cant really fix this without introducing other issues and impacting performance. The reason I have to do this is because you guys are using way too much decals...

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo Okay, maybe later when the game's closer to the release version and once we have more advanced graphics options.
