### ISSUE TITLE
[Dev Asks] Can someone tell me if they see / dont see the .gif on the store?

### ISSUE THREAD

**Issue by tsunamayo** [tsunamayo/Starship-EVO#4522]
The store is there https://store.steampowered.com/app/711980/Starship_EVO/
This is quite urgent!
Thanks

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo I can only see the three videos in the photo reel.
I'm assuming you've placed GIFs in the description, right?
If so, I cannot see them.

**Comment by tsunamayo** [comment]
great...

**Comment by tsunamayo** [comment]
you can see some tiny empty box?

**Comment by Kaiser-Indrasil** [comment]
No boxes whatsoever.
All that catched my attention was big spaces between paragraphs here and there:

![obraz](https://user-images.githubusercontent.com/63756057/151321044-73c0495e-bf38-495b-9c1b-9520f970fb6e.png)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil you can see the one here?
https://store.steampowered.com/app/244850/Space_Engineers/

**Comment by Kaiser-Indrasil** [comment]
Yeah, I can see those alright.

I recommend ShareX to grab reliable links for GIFs.
I had this one for years now and it's still working:

https://steamcommunity.com/sharedfiles/filedetails/?id=1646745111

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil And now does it work? It work earlier this week I made the change on monday, but it seems it went mia today...

**Comment by BigBadKangaroo** [comment]
> The store is there https://store.steampowered.com/app/711980/Starship_EVO/ This is quite urgent! Thanks

I can see the gif where you build and wire stuff on some ships! I'm on my phone r n, dont know if that makes a difference?

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo Yep! I can see all the 3 GIFs now both on phone and on desktop Firefox.

**Comment by tsunamayo** [comment]
Where you seing them on the iphone before? Those are hosted on steam side.

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo I only checked the website on my desktop before the GIFs worked, so I can't tell, sorry

**Comment by tsunamayo** [comment]
yeah iphones where fine on my side...

**Comment by ProPeach** [comment]
A little late, but I can see the gifs perfectly on an android phone. Snazzy!

**Comment by Tisdag1** [comment]
I just checked on my pc and I don't see them. All I see are little white boxes.

**Comment by ProPeach** [comment]
Checking on pc now and yeah, I only see white boxes too in the Steam app browser and just blank spaces on Chrome : (

**Comment by Uncle-Ulty** [comment]
Everything is ok here, on PC and iphone

**Comment by ProPeach** [comment]
Checked again 5 hours later, and all the gifs are now showing on Chrome and the Steam app browser, super weird. Must be Steam doing odd things!

**Comment by tsunamayo** [comment]
@ProPeach @Kaiser-Indrasil If that happen again could you please do the following (on chrome if you are using that)
Right click on the blank gif and do Inspect Element, then copy the HTML element.

This is the good one:
<img src="https://cdn.cloudflare.steamstatic.com/steam/apps/711980/extras/gif_build.gif?t=1643272518">

The wrong one was messed up, I wish I kept the copy.
Thanks

**Comment by Tisdag1** [comment]
Yup I can see them now too.

**Comment by ProPeach** [comment]
Will do, glad it's sorted now

> PS2 : did we notice easily the nice fat Sprite=-1 in the gif?

Only now that you pointed it out! I didn't notice it at all, but might be worth fixing if it's gonna keep you up at night ;)
