### ISSUE TITLE
Using Windows Screen Snip via shortcut and dragging while in full screen mode causes crash

### ISSUE THREAD

**Issue by TrashLambo** [tsunamayo/Starship-EVO#4523]
### Short Description of the issue:
Using Windows' built-in screen snip via its shortcut (Widnows Key + Shift + S) with the game in full-screen mode and dragging the cursor after beginning a snip causes the game to crash. After restarting the game, I was unable to get back in until after verifying the integrity of the cache. However, after doing so, I am unable to reproduce the crash., so perhaps it was a one-time thing. In addition, the shortcut worked without causing a crash after verifying integrity of cache. I cannot find any crash logs for Microsoft Visual C++, despite the screenshot. My apologies.
...

### Steps to reproduce the issue:
1) Enable full screen mode
2) while playing in-game, hold Windows Key + Shift + S
3) Drag from one point to another
...

### Environment
- Starship EVO version: early-access 22w04b (steam)
- Graphics Card: Radeon RX 580 Series (ID=0x67df)

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

![image](https://user-images.githubusercontent.com/64238009/151666083-38909532-e1a6-42ee-b5aa-bd04afda711a.png)

[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/7963939/Player-prev.log)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by CurioInventorium** [comment]
An odd error certainly, but for screenshots I have the Steam Overlay active and can just press F12.
Plus if you have the Xbox game bar active on windows you can press WinKey+Alt+PrtScrn

**Comment by TrashLambo** [comment]
I'm aware of those, but I was curious if I could just directly get a screenshot and have it in my clipboard instead of having to navigate to the screenshots folder for steam and share it like that. That, and it worked normally without crashing after verifying integrity of cache

**Comment by tsunamayo** [comment]
@TrashLambo Hi, thanks for letting me now. Full Screen mode is always a bit more dangerous for doing alt-tab and co, so I dont think I cant change anything. I use Snaggit (in full screen too, and often the region too), I never had any issue too. I think that Print Screen also should copy it to the clipboard, then you can open it in Photoshop (or paint), although that is quite inconvenient. Thanks!
