### ISSUE TITLE
Can't find starter block 

### ISSUE THREAD

**Issue by Tuxedo1551** [tsunamayo/Starship-EVO#4530]
### Short Description of the issue:
I took my entire ship apart too see if i could get rid of the starter block but it just disappeared the reason I want it removed is so I can have gravity in the ring
...

### Steps to reproduce the issue:
Im not sure
...

### Environment
- Starship EVO version: 
- Graphics Card: rx 570

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7990524/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

You will need to zip the folder to upload it. 
[cool ship.zip](https://github.com/tsunamayo/Starship-EVO/files/7990518/cool.ship.zip)

To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by Uncle-Ulty** [comment]
hum... it would be a good idea to add an option in F3 window to highlight certain system bricks such as starter block

**Comment by tsunamayo** [comment]
Yes I can understand it is not very friendly...

**Comment by Tuxedo1551** [comment]
Agreed but its not like the game is unplayable just a bit annoying

**Comment by Tuxedo1551** [comment]
So I figured out the problem wasn't the starter block because there wasn't one
my ship just doesn't like ring gravity
