### ISSUE TITLE
Landing in tutorial is bugged

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#4534]
Hi,

I played the tutorial and tried to land the repair ship.
Here's where it's landed:
![20220205114249_1](https://user-images.githubusercontent.com/81495956/152639265-94f75257-32ab-451f-8f58-f4140a64c656.jpg)
![20220205114847_1](https://user-images.githubusercontent.com/81495956/152639270-af6ef76a-cde4-4313-acff-4bfcca554261.jpg)

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, it was fixed in 22w05b! Thanks
