### ISSUE TITLE
Preview windows are bugged

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#4535]
Hi,

the screenshots pretty much explain what happens:
I don't get a preview of what i'm building/saving/copying

![20220205114910_1](https://user-images.githubusercontent.com/81495956/152639338-fa77fdca-56a8-4af0-8698-9ff0bbe9a1a0.jpg)
![20220205115211_1](https://user-images.githubusercontent.com/81495956/152639344-ce8f6dc0-b177-4c96-854d-e942dab2518e.jpg)
![20220205115232_1](https://user-images.githubusercontent.com/81495956/152639349-159af65c-be6b-4fdf-a315-6a3232ee51b2.jpg)

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, issue is fixed for 22w06b. cheers
