### ISSUE TITLE
Copy&Paste bugged again

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#4536]
Hi,

I don't get a preview where I'm pasteing stuff, it's just floating mid air:

![20220205115153_1](https://user-images.githubusercontent.com/81495956/152639470-2c7f130b-b22f-4ce7-ba78-dc383760f8d0.jpg)

**Comment by Briaireous** [comment]
im starting to get a similar issue
![Starship EVO 2_6_2022 11_45_28 AM](https://user-images.githubusercontent.com/23586866/152691473-da06b826-9424-42c8-8cdd-d9b255f077eb.png)
e

**Comment by tsunamayo** [comment]
@Hi, issue is fixed for 22w06b. Thanks
