### ISSUE TITLE
[bug] I can't exit the ship in the exit menu

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#4537]
I'm using Surge's blockhead (the green one) and I can't exit it. Idk if it's a problem due to the fact the seat is connected to the yoke.

![image](https://user-images.githubusercontent.com/73253472/152645700-7f3835a3-f718-4031-88c6-345c0dbf5362.png)

[2729744532.zip](https://github.com/tsunamayo/Starship-EVO/files/8008175/2729744532.zip)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8008176/Player.log)

**Comment by Reason147** [comment]
I'm having the same problem with the new set up it's too complexed.

**Comment by Uncle-Ulty** [comment]
When I press to exit, the bar extends and nothing happens 

![image](https://user-images.githubusercontent.com/73253472/152663329-20935a4e-b925-484d-b5b3-3a60bbda8824.png)

**Comment by Reason147** [comment]
killing yourself is the only exit

**Comment by Uncle-Ulty** [comment]
yes, I did that...

**Comment by tsunamayo** [comment]
Fixed in 22w06a! Thanks
