### ISSUE TITLE
wood planks block does not align to correct grid/ is offset 

### ISSUE THREAD

**Issue by darkvoid305** [tsunamayo/Starship-EVO#4539]
### Short Description of the issue:

...

### Steps to reproduce the issue:
 place a wooden block

...
![bug](https://user-images.githubusercontent.com/44634108/152657357-48b4e9d3-c8a1-4114-808a-544c776548bd.png)

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@darkvoid305 Hi, fixed for 22w06b. Also the wood plank can now grid-scale. Thanks
