### ISSUE TITLE
[Experimental] Targetting has trouble with determining which target is the closest

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4542]
Version: 22w06a
GPU: 970M

When using R to switch to the closest target, I expected it to switch to the police interceptor I followed closely.
Instead, it kept targetting the station which was +500m away from me, while the interceptor was 10 times closer to me.
I waited 6 seconds between my targetting attempts.

https://user-images.githubusercontent.com/63756057/152754176-5c329580-d700-4311-926f-46efddde4f7e.mp4

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Yep my bad I screwed it when I added the cycle back option, it was selecting the second closest. Fixed for 22w06b. Thanks!
