### ISSUE TITLE
Long-distance entity widgets don't appear on the HUD

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4543]
Version: 22w06a
GPU: 970M

When I select a station on the map, I can see its miniature in the lower right corner of the screen, but I cannot see its targetting widget on the HUD.
Moreover, if another long-distance entity was selected (like another station for example), this entity's widget would remain selected.

https://user-images.githubusercontent.com/63756057/152766405-cff56615-fb8d-4092-911f-eb8785906f0d.mp4

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Hi, issue fixed for 22w06b. Cheers, thanks for spotting all those!
