### ISSUE TITLE
Game is still simulating in the pause menu

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4544]
Version: 22w06a
GPU: 970M

I'm in a single-player offline world, and when I click Esc to access the pause menu, the ships are still moving, and the game overall is still simulating.

https://user-images.githubusercontent.com/63756057/152768125-e2499ecd-5926-4542-bb2a-17900f0fc504.mp4

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil So I made the change for 22w06b. Cheers
