### ISSUE TITLE
Long-range widget doesn't update range dynamically

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4545]
Version: 22w06a
GPU: 970M

When in Lightcruise, when I target the habitat, the widget in the lower right corner doesn't display the minuature, which is a problem in and of itself, but the bigger issue is, the range remains constant despite me moving in relation to the entity.

https://user-images.githubusercontent.com/63756057/152768793-fc611647-c84a-4e1c-86fb-232f5422e377.mp4

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil issue fixed for 22w06b. I wont fix the rendering one as this will be taken care of when I will ask you to make them out of bricks. I need a couple of things first (long-range rendering and the slanted docking port). Thanks
