### ISSUE TITLE
Player HP widget has a black bar

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4546]
Version: 22w06a
GPU: 970M

Like the title says, I believe it should be white (also displays the shield sprite for some reason?)

![obraz](https://user-images.githubusercontent.com/63756057/152793150-e2fbad27-660c-44a3-95a8-00a0d490879c.png)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Hi, fixed for 22w06b. Thanks!
