### ISSUE TITLE
Copy & Paste tool no longer working correctly

### ISSUE THREAD

**Issue by CurioInventorium** [tsunamayo/Starship-EVO#4547]
### Short Description of the issue:
Seems something has gone wrong on the last update that was pushed out, when I use the Copy/Paste tool to select something the Paste ghost appears nearby at an angle and doesn't move. While the orientation widget moves around where the player is looking.
...

### Steps to reproduce the issue:
Use Copy/Paste tool to select a random shape. In my test case just some blocks on the floor.
See screenshot below
...

### Environment
- Starship EVO version: 22w06a
- Graphics Card: RTX2060

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![20220207163715_1](https://user-images.githubusercontent.com/51359034/152832000-bd063cb2-1a1a-4d72-9b78-58e866b23e59.jpg)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by CurioInventorium** [comment]
Also it seems that the recent update was sent to main branch and not experimental. So everyone has the controversial new control system changes. I'd be happier if connection blocks, fuel and cargo blocks where completed before new things added. Everything has a loose thread feel to it :(

**Comment by Kaiser-Indrasil** [comment]
Yeah, pusing the 06a to the main branch was by mistake.
Hopefully, it will be resolved soon!

**Comment by tsunamayo** [comment]
No I wanted it on the main branch. I am doing a push on combat. It is not new things added as it is a refactoring of the old control that where clumsy for beginner too. Functional cargo is of course planned (and is a new thing), I added the block because people where requested it.

**Comment by tsunamayo** [comment]
@CurioInventorium Issue fixed for 22w06b. Cheers
