### ISSUE TITLE
landing is bugged... again

### ISSUE THREAD

**Issue by Spaceguy142** [tsunamayo/Starship-EVO#4548]
### Short Description of the issue:
when I try landing, the ship just seems to freeze in place, until I cancel it.
...

### Steps to reproduce the issue:
try and repeat the landing process, and freeze in place until canceled
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8018798/Player.log)

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Spaceguy142 Well it is working fine for me, so could you please give me for details on what ship do you use are where do you try to land? Thanks

**Comment by Spaceguy142** [comment]
> @Spaceguy142 Well it is working fine for me, so could you please give me for details on what ship do you use are where do you try to land? Thanks

I used the repair ship, so that's the only one as far a I know, but it probably is other ones aswell.

**Comment by Kaiser-Indrasil** [comment]
@Spaceguy142 https://www.google.com/search?client=firefox-b-d&q=tokyo+time

**Comment by tsunamayo** [comment]
@Spaceguy142 So I managed to reproduce it, it was an edge case. Fixed for 22w06c. Thanks
