### ISSUE TITLE
The Starship Evo Editor [.obl/stl & Starmade Importer] (Currently v2.1) 

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#4552]
### Short Description of the issue:
First and foremost, this isn't an issue, The community and I just wanted to share what we've been working on. Feel free to close this whenever.

We've built a tool to port Starmade ships and 3d objects into Starship Evo. 
https://github.com/pinesh/EvoEdit/releases/

### What do you stand to benefit?
The wealth of content from Starmade and beyond is now available to you. Quick and easy assets for any measure of testing and improvements from a massive swarth of build styles. 

The hope is that this tool might help drum up further Interest in Starship EVO. All publicity is good publicity.
Many former Starmade players want to get involved in projects like Starship EVO, but they've put so much time into making them that the sunk cost sinks in, and they're hesitant to leave it. There's already been positive activity in this regard on the Discord. 

### Why tell you:
_Because we'd love your blessing_. 

Unobscurifating the blueprints was a positive step forward into getting more people playing with Starship Evo outside of the game and acts as an early move to all-out modding. I hope this encourages you to keep letting us tinker in the future. 

### Full Voxel Porting
-Starmade ships are almost entirely translated. Blocks, wedges, and all are translated into Stevo with the correct rotations. 3D objects are now portable too.
![image](https://user-images.githubusercontent.com/14081996/152931772-f66fe8b6-2457-4098-a626-3cdb5dcd7f82.png)
_Community member Crusade renovating a Starmade blueprint_
![image](https://user-images.githubusercontent.com/14081996/152932053-320def1a-7de9-4b08-9b3b-57a84a785e00.png)
_Even stations are portable, paint and all_
![image](https://user-images.githubusercontent.com/14081996/152932647-db3b9fc4-5047-406d-a82c-9e077561388b.png)
_A 32km Titan from a 3d model file_

### Block Optimizing
Similar to the merge feature of Avorion, the optimizer can levy your stretch tech to reduce the impact of these imports drastically. Often reducing brick counts more than 10-fold. 

### Variable Scaling
-Thanks to the voxel translation from both 3d and Starmade, imports can be rescaled across any of the scales present in-game.
![image](https://user-images.githubusercontent.com/14081996/152929999-6aaac62d-db0e-460c-822a-220b9428229d.png)
_Fast and easy set pieces for all your dramatic battle needs_
![image](https://user-images.githubusercontent.com/14081996/152932816-cd32e0b6-142e-4c45-816e-d52be42bf6b4.png)
_How many meters in infinity? Pick a scale and find out!_

It's been a pleasure to give back to this community, and I hope you'll keep up the fantastic work.

All the best, 
Pinesh

**Comment by tsunamayo** [comment]
@pinesh It is really impressive! I had no idea it was possible, how did manage to read the save file?
The fact that it merge the block is really really cool, must save tons of blocks indeed. Does it deal with children entity?
Do you have a few blueprint to share - just being curious?

I can help you by giving more info on my format if you want but I guess you must have figure many things already. I am using Message Pack which serialize and compress the save. 
No problem on my side of course! But the save file format is moving quite often unfortunately, so expect it to break at regular point.

Cheers and nicely done!

**Comment by pinesh** [comment]
@tsunamayo Thank you for your enthusiasm! 

>how did manage to read the save file?
Using the same  Message Pack package, I deserialized a blueprint into a matching key structure, replicating your blueprint properties to ensure bytes went to the right places. I had to decompile the game to get the right formats and replicate some functionality (including a full Vector3i!).  It works by opening an existing Starship Evo blueprint and attaching its own BrickInstanceData into the BrickDataSave object.

>The fact that it merges the block is really really cool, must save tons of blocks indeed.
It. 
saves. 
thousands. 
This never would have been possible without your stretch tech. I've seen it reduce 3 million to less than 100k.

>Does it deal with children entity?
Not really, I let the user import them if they want, but they get saved as their own blueprints. Most Starmade child entities aren't worth importing, and attempting to attach them back on might have gotten messy since their turrets don't care about collisions!

I'm prepared to move with the times.. every blueprint you change just makes the entire thing better.

A bunch of blueprints I have on hand, you can get more at https://starmadedock.net/content/:

[Blueprints.zip](https://github.com/tsunamayo/Starship-EVO/files/8027323/Blueprints.zip)

**Comment by ProPeach** [comment]
It's quite fun going back to some of Starship EVOs inspirations! 😄 It'll take a lot of work to get it up to sevo standard though....
![711980_20220208205024_1](https://user-images.githubusercontent.com/27857711/153073459-00488b09-027f-4f1c-9b26-e2b27422a88a.png)
[Sidewinder.zip](https://github.com/tsunamayo/Starship-EVO/files/8027388/Sidewinder.zip)
