### ISSUE TITLE
[Suggestion] Slightly higher camera in 3rd person view

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4553]
I've been flying around and shooting at things a lot more recently, and one of the things I've noticed is that often your ship gets in the way of your view as it's quite close to the centre of the screen -
![711980_20220208205649_1](https://user-images.githubusercontent.com/27857711/153074871-085cb7e5-2e72-4e89-97c7-acfe8892be71.png)

Looking around at some other games, they often have the camera sitting quite far above your ship/vehicle
Everspace 2
![image](https://user-images.githubusercontent.com/27857711/153074955-78343b75-7a84-4379-8b86-d9062de7a96e.png)
Star Conflict
![image](https://user-images.githubusercontent.com/27857711/153076059-54555f99-729a-4b38-b4bf-06217b473382.png)
Warthunder
![image](https://user-images.githubusercontent.com/27857711/153075006-d9f9b24c-3c14-4f16-a400-3037a4ac6e86.png)

This makes it much easier to see what you're shooting at or flying towards
You can try it out in sevo by just putting a block up high on the blueprint so it moves the ship itself down in 3rd person
![711980_20220208210336_1](https://user-images.githubusercontent.com/27857711/153075251-00bb1c3e-3aa6-4755-ace2-c5060ba508f7.png)

Another example using the converted Sidewinder blueprint, notice the ship is actually touching your centre reticle
Default
![711980_20220208204655_1](https://user-images.githubusercontent.com/27857711/153075305-bd7c9610-a895-4cab-ad0d-7986e2948e21.png)
With a block ~10m above the build
![711980_20220208204633_1](https://user-images.githubusercontent.com/27857711/153075312-57a38184-cca3-4814-9f1a-49c7fdecf823.png)

I'm not sure what kind of value this would equate to, but the cameras always seem to be actually above the ships bounding box in these examples. It's easy to test ingame to try out different elevations at least

Here are the bps featured -
[Sidewinder.zip](https://github.com/tsunamayo/Starship-EVO/files/8027478/Sidewinder.zip)
[Sidewinder New 3rd Person.zip](https://github.com/tsunamayo/Starship-EVO/files/8027479/Sidewinder.New.3rd.Person.zip)
[Spitfire F Mk IX.zip](https://github.com/tsunamayo/Starship-EVO/files/8027481/Spitfire.F.Mk.IX.zip)
[Spitfire F Mk IX New 3rd Person.zip](https://github.com/tsunamayo/Starship-EVO/files/8027482/Spitfire.F.Mk.IX.New.3rd.Person.zip)

**Comment by Kaiser-Indrasil** [comment]
Avorion even has a separate hotkey for this (Alt, I think) to pan the TPP camera left, right, up, down, back, and forward (XY mouse movements + scroll wheel) so that you can have your ship below the camera, flanking it on either side, or wherever you want it.
And I've gotta say, it's really convenient.

**Comment by PopkaAkula** [comment]
"yes" 👍

**Comment by ProPeach** [comment]
Also just noticed in that first picture, the HUD indicators for systems in your own ship should be hidden as they're a bit messy and unnecessary

**Comment by tsunamayo** [comment]
Hi, yes it make sense. Thanks for the solid post!

**Comment by cloudrambler** [comment]
@tsunamayo A related problem is that the new MMB freelook is tricky to use with the scroll wheel zoom for external ship viewing. My suggestion is that the scroll zoom function could also work for the default external ship view. That could potentially give a simple range of options for the default view position and allow the freelook to be used more easily.

**Comment by tsunamayo** [comment]
@ProPeach Hi, I improved this for 22w45a. Please open a new case or give feedback in the upcoming patch note as I am closing that one! Cheers

**Comment by ProPeach** [comment]
Fantastic, thank you! Looking forward to trying it out
