### ISSUE TITLE
Let us help you make decals

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#4556]
There has been a fair few requests for additional decals for quite awhile now. Of course making them is low priority, but I was wondering if decal making isn't too difficult (presumably compared to blocks and whatever else), would you be able to teach us the "heavy labor" of making decals? What program, file format, and general sizes that would allow for scaling? That way we may be able to fulfill some of the sticker requests and, pending approval, get them in game. For example a star decal, or a straight line. That sort of thing

**Comment by Tourist50** [comment]
definitely agree with this, I've been trying to make something that I've desperately wanted to have a star decal, and making a perfect star with the available decals is basically impossible. We've had a few people modify the game already, and if it's a simple enough process, I'd love to see people do stuff like adding custom decals that could maybe become official.

**Comment by tsunamayo** [comment]
Yes we can try, I still wanted to do a few change on the decal tech to get truly stretchable one. I could think about modding a bit too, as I guess it wont get any simplier than a decal... I will keep you posted.

**Comment by SL-Nokz** [comment]
I’ve been able to add my own custom colors with editing the pallets file. I haven’t found a “file location” for decals. Is this not in the directory installed on my computer? I don’t want to take away from the developer, I love this game, I just want to add custom things for myself :) or others, it it helps!
