### ISSUE TITLE
[Bug] Impossible to target your own landing pad

### ISSUE THREAD

**Issue by SlimSumo** [tsunamayo/Starship-EVO#4558]
### Short Description of the issue:

I made a custom landing pad but it's impossible to target it. The big ring is always targeted.

### Steps to reproduce the issue:

Simply build a landing pad.

### Environment
- Starship EVO version: 22w06b
- Graphics Card: gtx1071ti

Here's the blueprint.

[Space port.zip](https://github.com/tsunamayo/Starship-EVO/files/8034064/Space.port.zip)

**Comment by SlimSumo** [comment]
I tried but it didn't work. The base is on the ground of the ring so it's always the ring "Space habitat" that is selected...

**Comment by Tourist50** [comment]
I've had this same issue trying to make shipyard landing pads specifically on the ring, they seem to be unselectable or overridden by the ring itself.

**Comment by tsunamayo** [comment]
@SlimSumo @Tourist50 Issue fixed for 22w09b. Thanks a lot!
