### ISSUE TITLE
Transporter pads don't work

### ISSUE THREAD

**Issue by Reason147** [tsunamayo/Starship-EVO#4559]
### Short Description of the issue:

...Just noticed this with the teleporting for the ship to ship it just doesn't work anymore, when I teleport to my ship it gets teleported into nowhere and the ship has vanished completely. Very waired bug. Does anyone have a silmer problem?

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by kynamats** [comment]
I haven't been able to teleport anywhere today, but it hasn't been deleting entities. I just click the entity in the list and nothing happens

**Comment by Reason147** [comment]
I see multiple players saying the same on steam.

**Comment by tsunamayo** [comment]
@Reason147 Hi, the issue was fixed for 22w07a. Thanks
