### ISSUE TITLE
[Bug follow up] Game simulation during menus

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4560]
Following the fix of #4544 in 22w06b, the game pauses when you enter any many. This makes sense for things like the esc menu, but it also included logic menus too.

It was really handy that the game still simulated when using the menu in a hinge for example, as you could change the hinge angle, see the hinge turn in real time, and then tweak the angle again if the first wasn't to your liking. Now you need to exit the menu for the hinge to start moving - not a huge inconvenience, but a less smooth experience than before. This is also the case for changing settings such as field dimensions in shipyards etc

Would it be possible to limit the simulation pause to only the escape menu, so all other ingame menus can update the world in real time?

**Comment by CurioInventorium** [comment]
I've also found that there is still subtle movement of the character when a menu is open, such that sometimes the character will be bounced up in the air if they'd been standing on a flat surface before a menu was opened.

**Comment by tsunamayo** [comment]
Hi, yes it make sense I will try to change that. And yes the simulation is not really paused it is just slowed down greatly. thx

**Comment by ProPeach** [comment]
Thank you!

**Comment by tsunamayo** [comment]
No longer applicable
