### ISSUE TITLE
Box Delete Tool Lag

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4563]
### Short Description of the issue:
When using the box delete tool, the destruction FX is played for every single brick that is removed at once. This can quite often cause a drop in fps on even small parts that have high brick count. I suggest that either one big FX node is spawned, or simply no FX at all to save on fps

### Steps to reproduce the issue:
- Use box delete tool on a ship. The more bricks you delete, the higher the fps hit

### Environment
- Starship EVO version: 22w06c
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
@ProPeach Fixed for 22w09b. Thanks!
