### ISSUE TITLE
[Bug] New GUI Disappears on Prefab Menu

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4564]
### Short Description of the issue:
If you navigate to the Prefab tab in the new Codex, the widgets on the left side will disappear.
![image](https://user-images.githubusercontent.com/27857711/153630354-0ef053b2-9bb8-4bb0-bba6-13a791107a24.png)

https://user-images.githubusercontent.com/27857711/153630279-ac43ecf0-9843-4cee-9fe8-34acd96993ba.mp4

### Steps to reproduce the issue:
- Click on the Prefab tab in the Codex

### Environment
- Starship EVO version: 22w06c
- Graphics Card: RX 580

**Comment by ProPeach** [comment]
Also to save us a click, it would be great to have the column of tabs on the left that show different build categories visible when in the Entity menu as you often flip between these two menus

**Comment by tsunamayo** [comment]
@ProPeach Hi, fixed for 22w06d. Unfortunately the entity will have its own subtab, like system chips, inventory, fuel ect...
So you will have to do that click ^^
Thanks
