### ISSUE TITLE
Holomap Unusable.

### ISSUE THREAD

**Issue by CysOrion** [tsunamayo/Starship-EVO#4566]
### Short Description of the issue:

I don't know if it is only happening to me but the holomap is unusable. From the video I saw from YouTube, the galaxy map suppose to be draggable, mine will not respond to any drag and zoom control. When I select "zoom to current position" the map will then zoom into the stars but incredibly slow. Also, there are other issue seen in the system map, such as targeting does not work, cannot zoom in or zoom out etc. 

Later I found that in the holomap menu If I tab F3 once and tab again the holomap will be usable. All the issues mentioned above are gone, but the cursor (pointer) is no longer visible and while I am looking at the holomap menu but I was able to control the ship.

I am playing the normal version not the betas. 
...

### Steps to reproduce the issue:

Press H to open the map.

When the problem occurs, tab F3.

...

### Environment
- Starship EVO version: 
- Graphics Card: GTX1650ti

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8050427/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:

`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@CysOrion Hi, fixed for 22w06d. Thanks!

**Comment by CysOrion** [comment]
That's great! Keep up the good work!
