### ISSUE TITLE
[BUG] New build wrong size

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#4567]
Starting a new ship in a new world inside 22w06c (default), I was unable to add blocks to the rear part of the ship. The grid was not shown past a certain limit unless I moved to a few places where the grid would show again and then I could add blocks.

Also the size of the ship was incorrectly listed in the codex, as 38m long instead of the correct 60m.

When I exited the game (direct to desktop) and reloaded the world, the ship was now correctly covered in grid and was correctly listed for size in the codex.

Log files attached from the first instance, when it was incorrect.

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8051484/Player.log)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/8051486/output_log.txt)

**Comment by cloudrambler** [comment]
Update: the reloaded world still has some problems as when I add to the size of the ship in other axes, the codex dimensions do not update.

**Comment by tsunamayo** [comment]
@cloudrambler thanks, now as it might be linked to other  stuff around it could you send the character folder too? Thanks

**Comment by cloudrambler** [comment]
@tsunamayo Here is the character folder. Again it's been updated since the bug was spotted
[Ship Core.zip](https://github.com/tsunamayo/Starship-EVO/files/8052338/Ship.Core.zip)
.

**Comment by tsunamayo** [comment]
@cloudrambler Hi, I think it was the same as #4582, so it should be fixed for 22w07b. Thanks!
