### ISSUE TITLE
Cant land bigger ships in new update

### ISSUE THREAD

**Issue by Neeenaw** [tsunamayo/Starship-EVO#4570]
I was just playing with the new targeting update and got damaged so I went to starting station and tried to land, I targeted the station but when I pressed f the (request landing) prompt did not pop up.

when I tried with my fighter it did and I landed.

build 22w06d       

The ship I was using: G-450 Marlin Starcruiser

**Comment by tsunamayo** [comment]
@Neeenaw Hi, it is simply because your ship is too big! Thanks
