### ISSUE TITLE
Long-distance light FX shines through blocks

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4572]
Version: 22w06d
GPU: 2080Ti

Not a high-priority thing but it would look better if long-distance shine effects used block occlusion pass, too.

![Starship_EVO_TUEe3C32l1](https://user-images.githubusercontent.com/63756057/153719915-171c3e5d-3c65-4716-bdbd-e75989f96416.png)
![Starship_EVO_tmnALkxn0b](https://user-images.githubusercontent.com/63756057/153719917-e080749e-67f4-48ca-af97-8d2e30495a26.png)

It's these thrusters inside that produce the light visible on the tiny screenshot above.

![image](https://user-images.githubusercontent.com/63756057/153719957-ae555258-d433-43ac-93d5-2c612c3d1295.png)

**Comment by tsunamayo** [comment]
Hi, I am not sure these sprite are actually using the Depth culling, but they do have an offset. They are not using the occlusion pass, although yes I should add this for optimization purpose. Thanks

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Sorry I havent had a look at it, do you still get this? Could you send the bp (Which I must have received 100x but I am not sure if this is the right one)
Cheers

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo Yeah, it's still there. Luckily, I've found a workaround where I just paint the light-emitting blocks in an almost complete black (1, 1, 1 RGB because 0, 0, 0 gives you steel).

[Here's the BP](https://github.com/tsunamayo/Starship-EVO/files/9951165/Astero.Neovox.-.4572.zip)

![Starship_EVO_QEIjU5rM0f](https://user-images.githubusercontent.com/63756057/200304576-02a23288-681e-42ac-82aa-8143a92c9a1c.png)
![Starship_EVO_dDSRB1C7fo](https://user-images.githubusercontent.com/63756057/200304594-367787d6-188f-49d5-a91c-e7b9baf3a3b0.png)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Hi, I didnt really managed to see anything!

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo Hey, I've updated the BP so it's way brighter across the starboard half-ring!
Remember that it's most visible from the rear and it's best if the rear is shaded.
FOV = 50 degrees btw

![image](https://user-images.githubusercontent.com/63756057/200524361-6c83284c-0447-471f-be07-0564fdb1c52b.png)

[Astero Neovox - 4572.zip](https://github.com/tsunamayo/Starship-EVO/files/9959532/Astero.Neovox.-.4572.zip)
