### ISSUE TITLE
Block discoloration depending on their orientation

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4573]
Version: 22w06d
GPU: 2080Ti

It's especially noticeable in poor lighting conditions.
Affects all the paints, materials, and blocks.
The same face can receive different exposure values, depending on its orientation, as seen in the video below:

https://user-images.githubusercontent.com/63756057/153750749-137ae57b-ea7d-42db-bb49-2da79d962280.mp4

**Comment by tsunamayo** [comment]
Hi, is it the same tile brick? If you could send me the character save at the exact place that would help me to reproduce. Thx

**Comment by Kaiser-Indrasil** [comment]
It affects all the bricks, not only the tiles.
I admit, it's a fringe case, but at the right lighting conditions it's really noticeable.

[Here's the zipped up character save](https://github.com/tsunamayo/Starship-EVO/files/8056984/Main.22w06d.zip)

![image](https://user-images.githubusercontent.com/63756057/153781734-8071edfd-e1e3-460e-8d8d-c6811e639e87.png)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil I still havent understood the root of the issue, but it seems that it is linked to the orientation of the brick. Bottom, left and back face are darker than up, right and forward faces. Now if you look at F3 / view normal, gbuffer0 and gbuffer1 everything is normal... It is really weird...
I keep you posted.

**Comment by tsunamayo** [comment]
actually there is an absolutely tiny difference in the normal, so we are making progress...

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Okay issue is fixed... It was linked to the normal map sampling. Thanks
