### ISSUE TITLE
Question: How do we make missions?

### ISSUE THREAD

**Issue by Reason147** [tsunamayo/Starship-EVO#4574]
### Short Description of the issue:

...After a few attempts, I yet haven't figured out how the mission editor works my question "sorry for asking a noob question" How do we make our own custom missions.

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Reason147 What mission editor ^^? In all seriousness it is yet to be added. Thanks
