### ISSUE TITLE
Teleport not working

### ISSUE THREAD

**Issue by commche** [tsunamayo/Starship-EVO#4575]
### Short Description of the issue:
Right clicking to access menu, then selecting teleport, then clicking on teleport location: selection highlights but then nothing happens

### Steps to reproduce the issue:

Try to teleport anywhere

### Environment
- Starship EVO version: 22w06d version
- Graphics Card: radeon armor 570 series

### Additional information:

tried on two existing saves and a new start game - same result: no teleport

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8056075/Player.log)

**Comment by Lsutehall** [comment]
I can confirm that I have this issue as well

**Comment by tsunamayo** [comment]
@commche Hi, this was bad so I will repush a build very soon. Fixed for 22w07a. Thanks
