### ISSUE TITLE
TAB not working in Multiplayer

### ISSUE THREAD

**Issue by TwoNiner29** [tsunamayo/Starship-EVO#4576]
### Short Description of the issue:
when you press TAB in multiplayer, only a cursor comes up, the menu is missing
...

### Steps to reproduce the issue:
press tab in multiplayer
...

### Environment
- Starship EVO version: 22w06d
- Graphics Card: RTX 3070

### Additional information:

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8056241/Player.log)

**Comment by tsunamayo** [comment]
@TwoNiner29 Hi, issue should be fixed for 22w07a. Thanks!
