### ISSUE TITLE
Blocks periodically not registering right on new builds

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#4582]
### Short Description of the issue:
It seems early on in new blueprints, you'll sometimes put down a block that can't be built off certain faces. This doesn't seem to be limited to just stretched blocks. The issue is resolved by placing another block elsewhere on the entity or respawning the blueprint. I don't believe this happens more than once on any blueprint. 
...

### Steps to reproduce the issue:
You'll need to start a new entity and place blocks until you experience it. 
It seems to have something to do with how block-entity registration is handled. When the next block is placed, it seems to resolve, as does saving and respawning the entity. 
...

### Environment
- Starship EVO version: 22w07a
- Graphics Card: RTX 3080

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
Video of the described behavior
https://user-images.githubusercontent.com/14081996/154185900-255d505e-c830-4d83-a37f-db300471342f.mp4

Another player in the community who has experienced this issue has generously provided me with their Log.
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8076269/Player.log)

**Comment by tsunamayo** [comment]
@pinesh Hi, thanks if that happens again could you please take a screenshot with F3 / Physics / View Entity Bounds enabled? I would like to see if the bound is correct.

**Comment by pinesh** [comment]
Certainly. I'll try and catch it

**Comment by pinesh** [comment]
Caught it!
@tsunamayo entity bounds seem right but I've actually found it's reproducible. 

Place a stretched block along the x-axis from the left side relative to a new starter block (I think this is the negative x-direction) and it will immediately have the issue.

You can do the same with a single block, but this issue is less pronounced as the bounds work for only the block that represents the start of the stretch
![image](https://user-images.githubusercontent.com/14081996/154192064-c32c10a0-5fba-4fa4-a46f-27b2685c4f11.png)
![image](https://user-images.githubusercontent.com/14081996/154192109-8172486a-806a-4a39-9022-2898b07ce2f7.png)

**Comment by tsunamayo** [comment]
@pinesh Hi, thanks a lot for the input, it is now fixed for 22w07b. Thanks
