### ISSUE TITLE
[Suggestion] Light shouldn't reflect off the placement ghost of glass

### ISSUE THREAD

**Issue by Facest4b** [tsunamayo/Starship-EVO#4583]
### Short Description of the issue:

While building, occasionally the placement ghost of glass will reflect light into the player which can be quite annoying when building, since it's not an actual placed block.

The placement ghost shouldn't reflect any light to avoid this.

### Environment
- Starship EVO version: 22w07a
- Graphics Card: RTX 2070 Super

### Additional information:

![image](https://user-images.githubusercontent.com/67114230/154337672-35bd5b5f-44e6-401e-affc-8a42c975b993.png)

**Comment by tsunamayo** [comment]
@Facest4b Hi, fixed for 22w09b. FYI the preview never reflected any light, it just strong when viewed from the side. There was a bug in the shader formula. Thanks
