### ISSUE TITLE
2375% Internal Performance Boost, Vector3i hash function.

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#4584]
### Not a bug, but a big speed boost!
Hiya, I've been fiddling with larger models stored in hashmaps in EvoEdit and found a big potential performance boost for your vector handling. 
I suspect the current function is creating a lot of duplicate values leading to long construction and access times when faced with larger block counts (over a few hundred thousand). 

Changing the Vector3i  override from this:
```
public override int GetHashCode()
        {

            return this.x ^ this.y << 2 ^ this.z >> 2;
        }

```
to this:
```
public override int GetHashCode()
        {
            unchecked 
            {
                int hash = 17;
                hash = hash * 23 + this.x.GetHashCode();
                hash = hash * 23 + this.y.GetHashCode();
                hash = hash * 23 + this.z.GetHashCode();
                return hash;
            }
        }
```

Improved my hash speed by more than 2300%.  

In my testing, I found that a ship with more than a million blocks took 95 seconds to optimize. With this change, it took less than 4. 

This change should only require replacing the function.

Thanks for all the updates!

**Comment by tsunamayo** [comment]
@pinesh Thanks I can try this indeed, I dont even how I came up with mine it was such a long time ago. But I dont see any real performance gain in neovox, now I am accessing bricks by a simple id, and physics query are using bvh.
I guess you are using a dico/hashtable to check voxels merging?
Have you considered using a fixed-size 3d array (or a flat one for that matter)? As the size size stays constant you dont even needs chunk. This could be even faster, but I guess 4 secs is acceptable now...

Thanks

**Comment by pinesh** [comment]
> @pinesh Thanks I can try this indeed, I dont even how I came up with mine it was such a long time ago. But I dont see any real performance gain in neovox, now I am accessing bricks by a simple id, and physics query are using bvh. I guess you are using a dico/hashtable to check voxels merging? Have you considered using a fixed-size 3d array (or a flat one for that matter)? As the size size stays constant you dont even needs chunk. This could be even faster, but I guess 4 secs is acceptable now...
> 
> Thanks

Thanks for taking it into consideration.  Bricks by ID and bvh sound nice and fast!

You're absolutely right about what I'm using them for. I've been considering a fixed-size array for a while now but I'm facing some hurdles. 

I figured that in order to use a 3d matrix, I'd have to make an object that was however many bricks long in each dimension. ex. for a million brick ship, to ensure I can handle all shapes I'd need a million^3 array! while most of that stays empty, I figured a dictionary gets me to the same place and provides some nice, fast ways to get all my vectors in the order I need for the merging to work right, removing previously handled bricks and looking up their values quickly.

**Comment by tsunamayo** [comment]
Well it all depends on how starmade format is stored, as it is voxel based I would guess it uses chunks. 
So you could either parse the chunk and get the size, or just allocate your own chunks that mirror the original format and use that to your data. Or just even work directly on the original data: you find a block, then you look directly for stretched blocks by looking at adjancents voxel. If you found some you modify the original data and set it at void.
Anyway I guess if you got something working just dont worry about this!

**Comment by pinesh** [comment]
Don't worry, I love talking about algorithms!

I did consider chunks, but I lose out on some merge performance across chunk boundaries and made getting it working with your symmetry a bit funky.

Thanks for taking me seriously anyhow. If I find anything more relevant to how you're currently handling blocks, I'll be sure to let you know!
