### ISSUE TITLE
Game freezes but... doesn't

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4585]
Version: 22w07a
GPU: 2080Ti

I honestly have no idea what might have caused this, since I didn't do anything in particular.
BUT, I'm gonna give you all the resources to peruse.

[Ship I piloted](https://github.com/tsunamayo/Starship-EVO/files/8097510/Astero.Neovox.Turret.Test.zip)

[Character save](https://github.com/tsunamayo/Starship-EVO/files/8097514/Main.22w07a.zip)

[The enormous 12MB Player Log](https://github.com/tsunamayo/Starship-EVO/files/8097401/Player.log)

https://user-images.githubusercontent.com/63756057/154689272-73585d8d-c784-4300-a8d2-e00d6dd508aa.mp4

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Okay I managed to reproduce that one, it will be fixed for 22w09b. Thanks!
