### ISSUE TITLE
[Not really a bug, but a problem] Mass delete lag from effect

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#4586]
When messing with EvoEdit, I was using the mass delete tool to get rid of some extra blocks. Then the game froze for a solid minute, the delete purpleish flashy effect coming from a hundred blocks or so lagging up the computer. Is there a way to turn off or minimize that effect when using the mass delete tool as since the stretch distance for the tool is large enough to probably crash the game if you get enough blocks in its zone.

**Comment by tsunamayo** [comment]
@ZachZent @ProPeach Where you using symmetry at the same time? Thanks

**Comment by tsunamayo** [comment]
@ZachZent @ProPeach I have just tested, no lag without symmetry, big lag with 2 symmetry planes...

**Comment by tsunamayo** [comment]
@ZachZent @ProPeach Okay I have just added a delay between each delete, this now looks like a complete fireworks it is quite an experience but at least it does not lag. For 22w09b. Thanks!
