### ISSUE TITLE
[BUG] F1 Menu looks weird

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#4588]
The F1 menu now has a pull-down feature (22w07b), however the window formatting seems a bit wonky. Maybe it's my screen resolution (3840x2160) that has messed it up. Graphics card is GTX1070.

![20220219163751_1](https://user-images.githubusercontent.com/70821082/154810131-d6d2cd35-caea-4699-8dbc-501b88cf0d0d.jpg)

**Comment by tsunamayo** [comment]
I repushed 22w07b with the fix. Thanks!
