### ISSUE TITLE
[Suggestion/fix] Walk/"run" speeds

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#4589]
Since the player movement modes are at least somewhat more defined, could you have a set defined walk/run speed that times with the current animation? Not changing 6dof or "creative mode" movement modes, just one speed for walking and another for sprinting? As much as we all like sass cat, it looks really weird on camera 

https://cdn.discordapp.com/attachments/416013956331601930/861804376355635240/Sass-1.gif

**Comment by ProPeach** [comment]
Wasn't sass cat caused by walking in 0.3x movement speed using the creative move speed options? The default 1x walk and run speeds seem to match up OK

**Comment by tsunamayo** [comment]
@ZachZent Yeah it was an artifact due to low walking speed. Thanks
