### ISSUE TITLE
Text Displaying Improperly on Wedged Monitor

### ISSUE THREAD

**Issue by Kadzar** [tsunamayo/Starship-EVO#4590]
### Short Description of the issue:
When linking a wedged monitor to a shield brick, the text displayed flat with the bottom of the monitor instead of on the face of  the monitor as expected.

### Steps to reproduce the issue:
I tried rotating and relinking the monitor the shield, and it still had the same issue. Have not yet tested if there are issues with other monitor types. (EDIT: Flat monitor seems to be displaying on the monitor face correctly, although not very well centered, but that's possibly a different issue)
EDIT: Can confirm that bug persists on a relog

### Environment
- Starship EVO version: 22w07b
- Graphics Card: NVIDIA GeForce GTX 1080

### Additional information:

![20220220021609_1](https://user-images.githubusercontent.com/66035211/154834608-cc65b682-2853-4276-a8d4-905ce213d8dd.jpg)

Player.log file:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8103633/Player.log)

Blueprint, in case it's needed:
[Saucer Shuttle mk 2 v 0.10 Weird monitor bug.zip](https://github.com/tsunamayo/Starship-EVO/files/8103636/Saucer.Shuttle.mk.2.v.0.10.Weird.monitor.bug.zip)

**Comment by tsunamayo** [comment]
@Kadzar Sorry the text screen will be complete refactored at one point. It is not high on the list though... Thanks
