### ISSUE TITLE
[BUG] I think the build options menu might be broken

### ISSUE THREAD

**Issue by PopkaAkula** [tsunamayo/Starship-EVO#4591]
### Short Description of the issue:

I think it might be broken
![image](https://user-images.githubusercontent.com/37738021/154838616-71e5433c-73d6-4140-ba68-52abaeceb6b3.png)

### Steps to reproduce the issue:

open the build options menu

### Environment
- Starship EVO version: 22w07b
- Graphics Card: RTX 3070

**Comment by tsunamayo** [comment]
I repushed 22w07b with the fix. Thanks!
