### ISSUE TITLE
Event Gate listening to mechanism won't activate Warning Message Gate

### ISSUE THREAD

**Issue by kynamats** [tsunamayo/Starship-EVO#4593]
### Short Description of the issue:
See video - when the button is 'pressed' by the event gate it won't activate the warning gate - when pressed manually it will

...

### Steps to reproduce the issue:
See setup in video
...

### Environment
- Starship EVO version: 22w07b
- Graphics Card: 3070ti

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
https://user-images.githubusercontent.com/89156468/155015433-87889869-a6bc-4cae-9785-fbbafd87aefc.mp4
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8111657/Player.log)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@kynamats Hi, well it is perfectly normal, otherwise that gate would then send a message to some buddy 100km away and feel weird. Messages are a HUD things, it needs to know to what player to send it.
Thanks
