### ISSUE TITLE
Objects close to the camera are not illuminated by the flashlight.

### ISSUE THREAD

**Issue by CPCTC** [tsunamayo/Starship-EVO#4594]
### Short Description of the issue:

Minor visual bug when using the flashlight. It seems to only illuminate surfaces that are a certain distance away from the camera. If a surface is far away from the camera, then it is illuminated properly. But, if the camera moves close enough to the surface, the surface is not illuminated, even though the flashlight is on. I've attached some screenshots to show the spacing at which this occurs.

### Steps to reproduce the issue:

1. Stand reasonably nearby an object, and look at it.
2. Turn on the flashlight.
3. Walk towards the object until you are almost touching it.
4. The object will not be illuminated by the flashlight.

### Environment
- Starship EVO version: early-access 22w07b
- Graphics Card: AMD Radeon R9 380

### Additional information:

This is the repair ship from the tutorial, landed on it's side. Notice that at this distance, the back side of the yolk is illuminated, as expected.
![far](https://user-images.githubusercontent.com/63987003/155048927-dfccbace-f827-430e-bbf3-bc3760408d63.jpg)
However, if I step closer, then the back of the yolk is no longer illuminated by the flashlight. You can see the seat further behind the yolk is still illuminated, but the yolk is not.
![near](https://user-images.githubusercontent.com/63987003/155048943-ce6c5184-c843-4b16-b42a-c27346ff50d4.jpg)

**Comment by ZachZent** [comment]
As an aside, the flashlight radius is rather small. Would there be a way to make it have a bit larger diameter?

**Comment by tsunamayo** [comment]
> As an aside, the flashlight radius is rather small. Would there be a way to make it have a bit larger diameter?

Hi, what FOV are you using?

**Comment by tsunamayo** [comment]
@CPCTC Hi, fixed for 22w09b! Thanks
