### ISSUE TITLE
Cannot land on pads of player-generated stations

### ISSUE THREAD

**Issue by Asnro** [tsunamayo/Starship-EVO#4595]
### Short Description of the issue:

The option to dock with landing pads of player-generated stations cannot be found in target menu.

### Steps to reproduce the issue:

- Generate station with landing pads
- Attempt to dock

### Environment
- Starship EVO version: 22w07b
- Graphics Card: RTX 3070

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

![kuva](https://user-images.githubusercontent.com/14952174/155131767-5a167b01-d1da-4d80-8d05-451d27368b08.png)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8116553/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by quinchinno** [comment]
A little annoyed that this issue still exists. Supposedly it was "fixed" a few patches ago. This same thing still happens for me as well

**Comment by tsunamayo** [comment]
@Asnro @quinchinno So the correct test case was it does not work on newly spawned blueprint. The previous fix was working just fine on existing blueprints. Anyway fixed for 22w09b.
