### ISSUE TITLE
can't request docking at starting station

### ISSUE THREAD

**Issue by Spaceguy142** [tsunamayo/Starship-EVO#4597]
### Short Description of the issue: title says it mostly, but I CAN dock at civilian ships

...

### Steps to reproduce the issue:
try to request docking
...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8120886/Player.log)

**Comment by tsunamayo** [comment]
@Spaceguy142 Hi, could you tell me more as I dont reproduce that issue?
What kind of ship are you using (how big it is). When you open the menu you dont see the docking choice available? 
Thanks

**Comment by CurioInventorium** [comment]
I've had a similar issue with the docking option not showing up after I've warped back into the star system.

Also, I've a related issue that I've been meaning log, but the "Request docking" and "Autopilot" options seem to be swapped round when you're at a distance that both shown up in the menu.

**Comment by Spaceguy142** [comment]
> @Spaceguy142 Hi, could you tell me more as I dont reproduce that issue? What kind of ship are you using (how big it is). When you open the menu you dont see the docking choice available? Thanks

the ship is big enough to land there with lots of room left, I'm sure, but it doesn't let me request docking. (you knoe the menu where you request docking? I get that up when I'm targeting the station and NO request landing there.)

**Comment by tsunamayo** [comment]
@Spaceguy142 hi, could you send me the blueprint? Thanks

**Comment by Spaceguy142** [comment]
> @Spaceguy142 hi, could you send me the blueprint? Thanks

here:https://steamcommunity.com/workshop/browse/?appid=711980&searchtext=x+wing&childpublishedfileid=0&browsesort=textsearch&section=home

**Comment by Spaceguy142** [comment]
> > @Spaceguy142 hi, could you send me the blueprint? Thanks
> 
> here:https://steamcommunity.com/workshop/browse/?appid=711980&searchtext=x+wing&childpublishedfileid=0&browsesort=textsearch&section=home

first thing on the top right

**Comment by Spaceguy142** [comment]
it seems to have fixed itself.

**Comment by tsunamayo** [comment]
@Spaceguy142 So I have just fixed a bug that should have explained this one, it was only on a fresh blueprint load. So it means it will have been broken too after a warp. Fix for 22w09b. Thanks!
