### ISSUE TITLE
Player followed by large shadow

### ISSUE THREAD

**Issue by Asnro** [tsunamayo/Starship-EVO#4598]
### Short Description of the issue:

See video. The shadow is always between player and sunlight.

### Steps to reproduce the issue:

???

### Environment
- Starship EVO version: 22w07b
- Graphics Card: RTX 3070

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

https://user-images.githubusercontent.com/14952174/155262890-1e189119-0867-459f-b844-3961190ce9ae.mp4

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8121951/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by Kaiser-Indrasil** [comment]
Did you jump to another system in that play session?

**Comment by Asnro** [comment]
It's an older save so I can't remember if I've jumped back and forth, but I'm in the starting system.

**Comment by tsunamayo** [comment]
@Asnro Hi, by play sessions you mean after a quit to title or a quit to windows?
Also I would need you character world directory (zipped) to investigate further.
Thanks!

**Comment by Asnro** [comment]
@tsunamayo Hi, I mean quit to windows. Here's the save file:

[50.zip](https://github.com/tsunamayo/Starship-EVO/files/8176987/50.zip)

**Comment by tsunamayo** [comment]
@Asnro Hi, I think it was because of the prefab / copy-paste. It should be fixed in recent update. Thanks!
