### ISSUE TITLE
Copy And Paste isn't working

### ISSUE THREAD

**Issue by Reason147** [tsunamayo/Starship-EVO#4600]
### Short Description of the issue:
Seems to be a bug with the copy and paste, I can copy a part fine but when I paste it only part of it is pasted 
https://www.youtube.com/watch?v=cBVWQ94HKHE

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: Build 22w07b
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by Kaiser-Indrasil** [comment]
That's an invalid link.
Also, a video would be much more useful.

**Comment by Reason147** [comment]
[https://www.youtube.com/watch?v=cBVWQ94HKHE](url)

**Comment by tsunamayo** [comment]
@Reason147 Hi, I cant investigate the issue without the blueprint... Are you sure there is no collisions on the pasted area? Thanks
