### ISSUE TITLE
[Bug] Targeting icons do not hide with F2

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4601]
### Short Description of the issue:
As shown in the gif, the white circles that show nearby entities do not hide when you press the hide HUD button, F2

![F2 Bug](https://user-images.githubusercontent.com/27857711/155850088-4813ce9a-5ea1-4f2b-9858-621e9085849b.gif)

Also a small suggestion - When cycling through targets, these circles for the targeted ship are shown with a red indicator regardless of whether they are hostile, neutral or friendly. It'd be nice if the indicator was green for friendlies, red for hostiles and maybe blue for neutrals like the stations?

### Steps to reproduce the issue:
- Pilot a ship
- Press F2

### Environment
- Starship EVO version: 22w07b
- Graphics Card: RX580

**Comment by tsunamayo** [comment]
@ProPeach Hi, indeed this will be fixed for 22w09b. Thanks!
