### ISSUE TITLE
[Bug] Weapon spread is only in one plane

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4602]
### Short Description of the issue:
Same bug as #1704
![Barrel Spread Bug](https://user-images.githubusercontent.com/27857711/155850060-794c0a6e-b4be-44a4-969e-895a5c1f3a61.gif)

### Steps to reproduce the issue:
- Fire a gatling gun and observe the spread

### Environment
- Starship EVO version: 22w07b
- Graphics Card: RX580

**Comment by zorozeenee** [comment]
CONFIRMED

**Comment by Kaiser-Indrasil** [comment]
Also reported in #3215 and still present

**Comment by tsunamayo** [comment]
@ProPeach Fixed for 22w09b. Thanks!
