### ISSUE TITLE
Ship Yards Nonfunctional

### ISSUE THREAD

**Issue by Arutus** [tsunamayo/Starship-EVO#4608]
Shipyards placed on my ship appear to not function and cannot be docked with, Ive also seen others with the same issue, but to add some context I am unable to select my ship and request docking with the shipyard. I'm unsure as to why this occurs as it is done properly but I shall provide the ship in question so that hopefully a solution may be found
[ANPIF Grand Dominance ver 3.4 - Copy.zip](https://github.com/tsunamayo/Starship-EVO/files/8158355/ANPIF.Grand.Dominance.ver.3.4.-.Copy.zip)

**Comment by tsunamayo** [comment]
@Arutus Hi, issue is fixed, it was only on a fresh load. Fixed for 22w09b. Nice big boi of a ship! Cheers
