### ISSUE TITLE
Performing certain functions during the tutorial can lock the cursor and make proceeding impossible

### ISSUE THREAD

**Issue by Kadzar** [tsunamayo/Starship-EVO#4612]
### Short Description of the issue:
I did the tutorial for a new world, and, when I was bringing the repair ship in at the end, I hit the repair button (probably not connected to the bug) and then accidentally hit the undock button, and when I docked again the end of tutorial message popped up but I couldn't use the cursor to close it out because I was still in the ship.

Edit: restarting the world seems to free the player, but the repair ship is gone
### Steps to reproduce the issue:

Probably just do what I did again

### Environment
- Starship EVO version: 22w09a
- Graphics Card:  Nvidia GeForce GTX 1080

### Additional information:

![20220302080430_1](https://user-images.githubusercontent.com/66035211/156378420-0fbe6826-715e-4a72-9476-da3b5e1df5e2.jpg)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8170081/Player.log)

**Comment by tsunamayo** [comment]
I think this issue should be fixed now. Thanks
