### ISSUE TITLE
Game freezes but... doesn't

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4613]
Version: 22w09a
GPU: 2080Ti

It happened to me a few times already but I wanted to test-case this bug in a few different scenarios.
So, this bug introduces a very weird behavior:
When flying around in my ship, with turrets spawned and merged via the docking ports, the game sometimes just freezes during combat.
The freeze doesn't encompass all the games subroutines though, as the audiovisual effects are still playing and I can move my cursor.
The damage doesn't register, the ships are frozen in place, everything else is basically frozen.

I've sent you the character file and the ship file on your email.

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8171097/Player.zip)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Hi, well if it is supposed to spawn turrets with the docking sub-module feature I will need the turret blueprint too!
Cheers

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo 

You're right!
Here you go:

https://steamcommunity.com/sharedfiles/filedetails/?id=2566927098

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil well I am sub to this blueprint, but it dont works with the workshop folder. If you can send me your local blueprint so I can spawn those...

**Comment by tsunamayo** [comment]
PS: it is just impossible to find the right workshop folder it is all numbers...

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo That's weird. Anyway, [here's the local prefab for that blueprint](https://github.com/tsunamayo/Starship-EVO/files/8174226/Longbow.-.Small.Focused.Pulse.Laser.-.EVE.Online.Amarr.Turret.zip) and [the standalone local blueprint of that turret](https://github.com/tsunamayo/Starship-EVO/files/8174231/longbow.blueprint.zip), whichever version you need.

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Okay I cant reproduce, but I have added a bunch of check that should avoid the issue. Cheers
