### ISSUE TITLE
[Bug] Gimbal isn't working

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4614]
### Short Description of the issue:
Mouse gimbal for fixed weapons isn't working for ships

### Steps to reproduce the issue:
- Pilot a ship
- Fire the guns, they fire straight forward rather than following your mouse

### Environment
- Starship EVO version: 22w09a
- Graphics Card: RX580

**Comment by tsunamayo** [comment]
Hi, yes it is on my to-do list for a while, I will tackle it soon. Cheers

**Comment by tsunamayo** [comment]
Finally fixed for 22w33a. Thanks
