### ISSUE TITLE
Falling through floor right after leaving med bay

### ISSUE THREAD

**Issue by douglas-moyes** [tsunamayo/Starship-EVO#4621]
### Short Description of the issue:

Good news! This game now works on Linux under Proton... performance is crap compared to games like No  Man's Sky though. The other issue is, clipping appears to be stuck "off" the moment I left the medbay, I fell through the floor into space.

### Steps to reproduce the issue:

Start new game in Linux, fix video settings to keep the game from killing my system (vsync off, 1080p instead of 4k), and step off the med bay... and down you go. Hitting F5 had no effect. Everything else seemed to work though.
...

### Environment
- Starship EVO version: latest build as of March 8th 2022
- Graphics Card:  nVidia 1660 Ti

**Comment by tsunamayo** [comment]
@douglas-moyes Hi, well low fps have clipping issues. What is your FPS? Thanks

**Comment by douglas-moyes** [comment]
Probably around 12-15fps. I didn't have metrics running at the time.

**Comment by tsunamayo** [comment]
@douglas-moyes You can toggle them with F3 - Show FPS counter. I am pretty much sure it is linked to low fps. So I will close this as that issue must be booked somewhere! I need to update my character collision logic first. Thanks!
