### ISSUE TITLE
[Bug] Tank Join Pieces Appearing in Pipes

### ISSUE THREAD

**Issue by PFSCommissar** [tsunamayo/Starship-EVO#4625]
I've noticed tank join blocks appearing in pipes since the new update. 

In the First screenshot below, the pieces have appeared on both sides of fuel scoop blocks. The pieces are not physically there, and thus cannot be deleted or interacted with. The only way to remove them is to remove the fuel scoop they're attached to. 

I tried replacing the fuel scoops, saving, and then respawning the ship, but the issue returns whenever the ship is respawned. 

The second screenshot shows how it appears on both sides of the fuel scoop, and you can also see where it is appearing at pipe ends.
The third screenshot is of a different ship where it's appearing in a pipe joint

![20220311174305_1](https://user-images.githubusercontent.com/67161181/157984830-bd270814-154e-4379-a0b0-1a1e09670725.jpg)
![20220311174352_1](https://user-images.githubusercontent.com/67161181/157985031-da8aaab8-f2e6-4a1b-b865-5ac2a3807856.jpg)
![20220311174505_1](https://user-images.githubusercontent.com/67161181/157985036-02d347b4-8fe7-4869-aac6-2895fff918e9.jpg)

### Environment
- Starship EVO version:  22w10a
- Graphics Card: Nvidia Geforce GTX 1650

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/8236328/output_log.txt)

**Comment by tsunamayo** [comment]
@PFSCommissar Hi, did it appeared in this update or the previous fuel update? I didnt really touched pipe in the latest one.
Also btw have you tried to generate stations with your modules (sorry I havent had the time on my side...)
Cheers

**Comment by PFSCommissar** [comment]
I only noticed it today, but I can’t say for sure. 

For the station generator, honestly i never figured out where to find it.

**Comment by tsunamayo** [comment]
@PFSCommissar Thanks for the info I will have a look at it.
So the station generator is inside the Codex Entity info tab at the end hiding under a tab.
In your station as stuff is built sideways I might need to code a new feature to unforce correct vertical alignment, we will see (it was on my to-do anyway)

**Comment by PFSCommissar** [comment]
> @PFSCommissar Thanks for the info I will have a look at it. So the station generator is inside the Codex Entity info tab at the end hiding under a tab. In your station as stuff is built sideways I might need to code a new feature to unforce correct vertical alignment, we will see (it was on my to-do anyway)

thanks, i found it but can't get anything to generate when i hit the button. also, it looks like the hub has the correct up position, so if you start with that everything should theoretically come out ok as the docking connectors will force the modules into a certain direction. Sorry about the mix-up, though. 

![image](https://user-images.githubusercontent.com/67161181/158019121-42357418-d5fc-4bdc-9b67-5b645e71e1a8.png)

**Comment by Uncle-Ulty** [comment]
I can't generate station...

**Comment by PFSCommissar** [comment]
> @PFSCommissar Hi, did it appeared in this update or the previous fuel update? I didnt really touched pipe in the latest one. Also btw have you tried to generate stations with your modules (sorry I havent had the time on my side...) Cheers

Returning to the original issue, i just noticed it on the ship i've been working on the past few weeks. So i can say it's shown up since the new update

**Comment by jasonfogleman** [comment]
I think I can add to this as well. I don't know which update it appeared in, but fuel scoops are also subject to tank connectors appearing. 

If I remove and then replace the fuel scoops then the tank connectors are removed. 

However, when I reload the game, the tank connectors reappear and I have to replace the fuel scoops all over again to remove them. 

![image](https://user-images.githubusercontent.com/87847101/158301706-025f8d1b-4d8e-46aa-a9b7-5972c6c9f7ee.png)

**Comment by tsunamayo** [comment]
@PFSCommissar That issue will finally be fixed for 22w31b. On the topic of station, sorry still haven't had time to properly integrate! I am doing a big push to get crafting into the game. Cheers
