### ISSUE TITLE
world loading problem???

### ISSUE THREAD

**Issue by eageus** [tsunamayo/Starship-EVO#4627]
### Short Description of the issue: 
 i was having some strange lag so i rebooted the game and then wen i loaded back into my world it would not let me move or press anything but esc. i will have some pics posted. sometimes rebooting the game again will fix it. but wen i load back in all the ships i have in the world are just gone. 
will also include a world file that this is happening on. 

...

### Steps to reproduce the issue:
i sadly have no idea it just randomly started to happen. 
...

### Environment
- Starship EVO version: exparimental
- Graphics Card: gtx 1050ti

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular desig
[planet 2.zip](https://github.com/tsunamayo/Starship-EVO/files/8240719/planet.2.zip)
n please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalL
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8240709/Player.log)

![20220313151228_1](https://user-images.githubusercontent.com/87349714/158081643-98be75fb-7b1e-4248-8842-001ff68587f4.jpg)
ow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
![20220313151434_1](https://user-images.githubusercontent.com/87349714/158081640-c91f8f5a-eb5d-4d8c-8fcf-aa9db0f43031.jpg)

You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@eageus Sorry I missed that bug, your world was corrupted. There is a way to transfer ship manually if you want to get back some ships. Tell me if you need to (You can open a new case if needed) Cheers
