### ISSUE TITLE
[suggestion] camera zoom and UI

### ISSUE THREAD

**Issue by probka** [tsunamayo/Starship-EVO#463]
interesting to have ZOOM ability and if possible to add UI overlay to camera view so we can for example connect laser detector to camera and have distance in overlay screen
or just edit UI as text like existing transparent screen block

![camerazoom](https://user-images.githubusercontent.com/16438515/33022932-57862ba8-ce0f-11e7-81fe-4cc8c3a1faa2.gif)

**Comment by tsunamayo** [comment]
Yes I wanted to do that one day, but it will be a bit low priority. Thanks for the nice gif! Cheers

**Comment by tsunamayo** [comment]
@probka Hey howdy! Do you have a mail to be in touch? Thanks

**Comment by probka** [comment]
hey! s.probka@gmail.com
