### ISSUE TITLE
[Bug] Tank Join Placement Issues

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4631]
### Short Description of the issue:
I can't place a Tank Join on or between a Reactor or Lightcruise thruster to enable them to share fuel between them

https://user-images.githubusercontent.com/27857711/158869090-7e50e174-bd2d-4127-9393-99def47617eb.mp4

### Steps to reproduce the issue:
- Place a Reactor
- Try to place a Tank Join

### Environment
- Starship EVO version: 22w10b
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
@ProPeach Okay so right now I dont think this can works. I dont think you can link them with a normal pipe either (you can build the pipe but it wont work). Reactor wont send fuel elsewhere, do you think they should? Is this that blocking for other people?
Thanks

**Comment by ProPeach** [comment]
As a quality of life thing it would be nice if you could enable adjacent systems to share fuel with the Tank Join yes.
Admittedly I think this is a bigger issue with Tanks as the Tank Join doesn't allow placement on those either, I should have added that to the report too
https://media.discordapp.net/attachments/271723356795961345/986690575422095420/unknown.png

**Comment by tsunamayo** [comment]
@ProPeach Fixed for 22w43a. Thanks
