### ISSUE TITLE
[Bug] Weapon SFX do not reactor to volume slider

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4632]
### Short Description of the issue:
Even with the "Game Volume" set to 0, 

### Steps to reproduce the issue:
- Set Game Volume slider to 0
- Fire a weapon

### Environment
- Starship EVO version: 22w10b
- Graphics Card: RX 580

The new SFX sound great by the way! Any chance the SFX could get deeper/more bassy depending on the damage of the shot? A little like how larger ships have a deeper sound to their thrusters

**Comment by ProPeach** [comment]
@tsunamayo the new Fuel Scoops sounds are also unaffected by the volume sliders

**Comment by tsunamayo** [comment]
@ProPeach Hi, so this should have been fixed as of 22w19a. Thanks
