### ISSUE TITLE
When leaving the game, the "Game" Settings get reverted back to default.

### ISSUE THREAD

**Issue by thatisjake** [tsunamayo/Starship-EVO#4633]
### Short Description of the issue:

When closing SEVO and rejoining, the game settings get reverted.
"Game" settings I believe might also be misnamed, and probably should be renamed to character settings.

### Steps to reproduce the issue:

Set the "Game" Settings to something besides default.
Close game, and rejoin.

**Comment by tsunamayo** [comment]
@thatisjake This will finally be fixed for 22w45a. Thanks
