### ISSUE TITLE
Tank Hovers Bobbing

### ISSUE THREAD

**Issue by Arutus** [tsunamayo/Starship-EVO#4637]
This seems to be a recurring issue in which the tank bobs up and down every time you rotate the turret, what is odd is it stays level when not rotating and has adequate lift. Im not sure whats causing It and was hopping you could figure it out as it may be a bug

**Comment by tsunamayo** [comment]
@Arutus Hi, what tank? thx

**Comment by tsunamayo** [comment]
@Arutus Hi, I didnt noticed any issues. Please re-open a case with a video or a screenshot if there is still an issue on your side! Thanks
