### ISSUE TITLE
Main Game Blanks Out at Starting Menu

### ISSUE THREAD

**Issue by Tokarus-Saliron** [tsunamayo/Starship-EVO#4638]
### Short Description of the issue:
My game will not run on my computer. The problem is that, while it is able to run the start-up menu, it doesn't get much farther than that. I can only make it to naming my character and adjusting the map seed for the main game because it crashes after I try to proceed. The error that keeps appearing is that the game has stopped working, and it sometimes reports the issue to Microsoft.

I have been able to adjust the settings to my liking (except for the character settings in the game settings section, which doesn't save at all).
...

### Steps to reproduce the issue:
1. Run the game.
2. Click any key on start menu.
3. Press the "Play" button for the main game.
4. Fill out information.
5. Hit the button that proceeds.
6. Watch the game blank out to a black screen for around 6 seconds (with the audio sometimes cutting out).
7. Watch as the computer's main screen pops up with said error message.
...

### Environment
- Starship EVO version: Early Access
- Graphics Card: Intel(R) HD Graphics 620

### Additional information:
It may be because I currently have a computer that (while having been made around the year 2020) does not have the ideal hardware for playing a Windows 10 only game. (I've seen the option to upgrade to Windows 11 in the update section of the settings app, but it has told me that the system will most likely be unable to run that version of Windows. However, I am currently able to use and have been using the Windows 10 OS.)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by Kaiser-Indrasil** [comment]
Thanks for sharing your concerns.
Unfortunately, your GPU doesn't meet the minimum requirements to run the game.
As of now, Starship EVO needs at least a Geforce 750, a Radeon R9 270X or higher, so an integrated GPU in a processor is completely insufficient to run the game.
The developer is constantly optimising the game. However, the proper optimisation will probably come at a later date, when the game is closer to completion.

You can learn more about the game's requirements on its Steam Store page here:
https://store.steampowered.com/app/711980/Starship_EVO/

**Comment by tsunamayo** [comment]
@Tokarus-Saliron Unfortunately I think Kaiser is right, your gpu is way (way) too low, even if you could start the game that would not be playable. I would need a log file to confirm though.
Thanks, I hope you can refund!
