### ISSUE TITLE
[SUGGESTION] Custom metal colors.

### ISSUE THREAD

**Issue by Servomotor** [tsunamayo/Starship-EVO#4639]
Is it possible for us to change the color for metals/materials? 

Been really craving some oxidized titanium and bronze lately. Is there a relatively simple way for us to create different metal colors?

![1428_Metallic Color Samples](https://user-images.githubusercontent.com/65745916/159389401-438dd670-b786-437c-9ad8-4b333f5e2240.jpg)

**Comment by tsunamayo** [comment]
@Servomotor Hi, nope as metal is not for decoration, it will be linked to gameplay... Cheers

**Comment by Servomotor** [comment]
Check your email for a present.
