### ISSUE TITLE
[Suggestion] Minor tweak for tank labels

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4640]
Fuel is really coming along! The consumption rate feels much better, and we have better tools to track idle and full power uptime estimates.

I wanted to talk a bit about these labels in the tank-
![image](https://user-images.githubusercontent.com/27857711/159591247-ca34981a-ace1-4d78-8d99-4e43f13d0eb7.png)

Being able to set aside some tanks as pure storage is a really fun idea, maybe for an emergency tank or fuel tankers. But I suggest changing the default selection a bit. At the moment we need to manually set every tank to available for the ship to consume, otherwise the estimated uptime is very low. Players that missed that patch note are confused or annoyed that despite adding lots of tanks, their uptime estimates are still in the low minutes because it only looks at Reactor and Engine internal tanks.

Also, I'm not sure we need separate settings for each of the listings. A selection of...

**Active**
_(fuel tank supply's fuel to engines and reactors. This is the default setting for all newly placed tanks)_
and
**Storage**
_(Fuel tank does not supply fuel to systems, but can be transferred through docking)_

...is simple enough

Players can use the valves if they want a more complex relationship as right now they don't have much use, although maybe that'll change later with more fuel types and perhaps liquid crafting.

But yeah, this way by default all tanks are set as Active and supply fuel so the estimate uptime is correct, and if players want to store the fuel instead there is one simple option.

There might have been other uses for the more specialist settings that I missed, so it'd be super interesting to hear about what you had in mind for them
Thanks for reading o/

**Comment by PFSCommissar** [comment]
agree with this, especially the point on valves. with tanks as they currently are, i can't see a use for those blocks. However the active/storage dichotomy could bring such an incentive.

**Comment by tsunamayo** [comment]
Hi, so yes I agree it is a bit confusing. I wanted to have multi-fuel, and have some type of fuel more effective for engine for example, so advanced builder can use a separate tank for reactor and engine.
But I havent made my mind about multi-fuel, I fear it is gonna be a real bother to harvest or to display the correct fuel level for example,
Storage is really for tanker, if you want to harvest / sell fuel.
I hope what is clear is that this is a setting used for fuel range only, it has no impact on how the fuel is used.
cheers

**Comment by ProPeach** [comment]
> I hope what is clear is that this is a setting used for fuel range only, it has no impact on how the fuel is used.

So this wasn't clear to me at all, seeing the menu I thought I had to choose a label and that tank would only supply fuel based on that label. It's part of the reason why I suggested that the tank be "readable" by default without having to touch (or know about) the menu, as everyone will want to see an estimated fuel range, but not everyone will want to choose a more advanced option. This way a new player can still get a fuel estimate without having to learn about the menu in the tank too, then come back to it later

With regards to multi-fuel, man that's a can of worms.
Personally, I would move the gameplay choices from different fuel types optimised for reactor/thruster into choices of addons on those systems. You can still have different grades of fuel, but that fuel would flow into both systems and then the addons would act as a customisable aspect for how quickly that system burns fuel/it's efficiently/output etc.


Different fuels for different systems might cause a lot of compatibility problems as you say, so giving the player the same fuel related choices using addons instead sidesteps those neatly.

Thanks for explaining your thought process as always o/

**Comment by tsunamayo** [comment]
Updated in recent build. Thanks
