### ISSUE TITLE
GUI Fuel Gauge

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4641]
The current fuel gauge in the ship GUI could use some tweaks for readability.
![image](https://user-images.githubusercontent.com/27857711/159592778-bc6c54ca-1058-449b-972a-c259ba1ba7e9.png)

With the three bars system, it simply doesn't have the required information on show - Here I have no idea if I have 30% fuel remaining, or 3%! :D
The gauge is never show as full either, as the tanks are never at exactly 100% so you only ever see 2 bars or less.

A simple percentage indicator, perhaps colour coded so that it turns the value red when below 20% would be much more useful to a pilot. 

Maybe a classic fuel needle gauge if you wanted it a bit more retro, although that might take up more space
![image](https://user-images.githubusercontent.com/27857711/159592686-858f446b-7cdf-4659-b6c5-7ea801e7a7b5.png)

Or perhaps a longer fuel bar that shows the fuel remaining in more increments than 3 discrete bars
![image](https://user-images.githubusercontent.com/27857711/159593023-25b01232-8aa9-4ae5-9497-10ff522bccc4.png)

**Comment by tsunamayo** [comment]
Hi, yeah I know I already changed it for the next update, it was one of my wip point from previous.
Next update is fuel harvesting...
Cheers

**Comment by ProPeach** [comment]
Should have know you'd be on it already o7
