### ISSUE TITLE
[Suggestion] fuel travel through child entities

### ISSUE THREAD

**Issue by schlid** [tsunamayo/Starship-EVO#4644]
The fuel system is looking great - the latest fuel vacuum block is a good addition.

This also seems like a great point to address the issue of fuel travelling between child entities.

Farming/collecting fuel quickly would be a much faster process if you had the collectors spread out across a wider area, so naturally people will want to create ships with arms that spread out to collect a large quantity at once.

This doesn't even explore the other benefits such as being able to place fuel tanks on child entities amongst your fuel network and so on.

I suppose the most logical way to do this would be to allow a pipe to interact through a child entity by placing one connecting into either side of a hinge, piston or rail. as pipes can clip through blocks this shouldn't affect building too much.

**Comment by ProPeach** [comment]
Praying for the Return of the Hose for this 🙏🙏

**Comment by tsunamayo** [comment]
Hi, yes I want to tackle that at one point. 
For hose it will take more time as I need to make it super fast to render (unlike to older implementation), as people will like to use 100s of those like everything I give...
Note that you dont need to extend the volume at all, you can have the scoops close together, there is also no check on whether they are obstructed (yet).
Thanks

**Comment by tsunamayo** [comment]
@schlid Implemented in recent build with the hose too. Thanks
