### ISSUE TITLE
Can't turn off Jetpack even with gravity

### ISSUE THREAD

**Issue by Zanbatos** [tsunamayo/Starship-EVO#4649]
### Short Description of the issue:

Turning off jetpack doesn't work, even with gravity. Pressing J only cycles the jetpack modes

### Steps to reproduce the issue:

Just try to turn off jetpack in the tutorial, or any place that have gravity

### Environment
- Starship EVO version: 22w11a
- Graphics Card: GTX 1080

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8352273/Player.log)

**Comment by Tisdag1** [comment]
I also have this problem. Can't finish the jetpack part of the tutorial because it only cycles between the two jetpack modes & won't turn off the jetpack.

**Comment by tsunamayo** [comment]
@Zanbatos @Tisdag1 Hi, thanks I am on it and will release a fix asap!

**Comment by tsunamayo** [comment]
Okay guys issue is fixed and the patch is live. Thanks!
