### ISSUE TITLE
[Bug] New Delete Bug

### ISSUE THREAD

**Issue by thatisjake** [tsunamayo/Starship-EVO#4651]
### Short Description of the issue:

Doing some funky stuff with delete causes world to go weird and deleting to not work
### Steps to reproduce the issue:

Select Box Delete, and delete a bunch of small bricks (just so that you have time for step 2)

while its deleting, select another brick, and try to press delete again.

At this point, you can no longer use the delete tool (even when removing from inventory and replacing)
When leaving and rejoining, you are placed into the sun, and gravity's all funky (basically a world corrupted)

**Comment by tsunamayo** [comment]
@thatisjake Hi, I cant reproduce this unfortunately. Do you have a log file to show? Thanks
