### ISSUE TITLE
Add Frz solar system (BEP20) #19244 marge

### ISSUE THREAD

**Issue by smart2022** [tsunamayo/Starship-EVO#4652]
Hello
I don't know how but you merged [Fwc #19241](https://github.com/trustwallet/assets/pull/19241)   this is not our token and we are not pay for fwc  we paid for 
Add Frz solar system (BEP20) #19244
please fix it  

fee paid with memo 19244 : [https://explorer.binance.org/tx/1BB848FB02ADF595B046ED1E53802FBF992F29CFF1F3EC514873082F34F8C70A](url)
<https://github.com/trustwallet/assets/pull/url>
please fix it & merge Add Frz solar system (BEP20) #19244  

thank you so much  for your Attention.

**Comment by smart2022** [comment]
![Uploading Screenshot (3).png…]()

**Comment by smart2022** [comment]
![Uploading Screenshot (3).png…]()

**Comment by smart2022** [comment]
![Uploading Screenshot (3).png…]()

**Comment by smart2022** [comment]
![WhatsApp Image 2022-03-26 at 6 07 26 PM](https://user-images.githubusercontent.com/97367238/160242028-89735e32-8bad-4f19-bb10-487d3497273c.jpeg)

**Comment by smart2022** [comment]
I think there is big mistake 
I can revert [Add Logo Fwc](https://github.com/trustwallet/assets/pull/19241#)
#19241  but its not our token , and I cant revert ours [Add Frz solar system (BEP20)](https://github.com/trustwallet/assets/pull/19244#) may be they could and its not good for us please fix it .
 thank you so much
#19244

**Comment by Kaiser-Indrasil** [comment]
@smart2022 Starship EVO is not a crypto game.
It's a normal game.
I think you came to a wrong neighbourhood.

**Comment by PopkaAkula** [comment]
mental degradation
