### ISSUE TITLE
[Bug] Fuel Indicators do not show correct fuel level

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4653]
### Short Description of the issue:
Both the new GUI icon for the fuel gauge and the indicator in the Entity Menu do not update their fuel levels even when tanks are full

### Steps to reproduce the issue:
- Fill a ship with fuel, either with the fuel scoops or with the "refill tanks" button
- Check the HUD indicator for fuel whilst flying
- Check the fuel indicator in the entity menu, both show as empty
- Check tanks with a pipe in hand and they show fuel inside them

Great to see the new HUD fuel indicator!

### Environment
- Starship EVO version: 22w11a
- Graphics Card: RX580
![image](https://user-images.githubusercontent.com/27857711/160259536-41b78719-d208-433f-8aef-ed6a68c279b9.png)

![image](https://user-images.githubusercontent.com/27857711/160259531-8fb8f4f6-d25c-408e-8a81-87a57b6d4b31.png)

![image](https://user-images.githubusercontent.com/27857711/160259527-da7364cc-a746-44ac-b230-2ec2255e91a6.png)

**Comment by tsunamayo** [comment]
@ProPeach Hi, is the tank correctly set up (ie not at storage?). Thanks

**Comment by ProPeach** [comment]
> @ProPeach Hi, is the tank correctly set up (ie not at storage?). Thanks

Ah, that was the problem! Duh, silly me, the indicators work fine now yes

**Comment by ProPeach** [comment]
I guess that just goes to show it'd be useful if the tanks weren't set to Storage mode by default, whoops...
