### ISSUE TITLE
[Bug?] Ships do not explode when killed

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4656]
### Short Description of the issue:
When ships take enough damage to be counted as a "wreck", the explosions FX do not occur. Not sure if you've disabled it in the meantime to refactor it with the new VFX so this might be expected

### Steps to reproduce the issue:
-Damage a ship enough to kill it

### Environment
- Starship EVO version: 22w11a
- Graphics Card: RX580

**Comment by tsunamayo** [comment]
Yes this is normal for now. Thx
