### ISSUE TITLE
Bugged world / shadow-ghost realm 

### ISSUE THREAD

**Issue by Drillz007** [tsunamayo/Starship-EVO#4664]
### Short Description of the issue:
World became bugged while building all projects moved to an unknown space where you cant interact and no collision exists (cool planet in distance though) i am also trying to rescue a hover vehicle that i never saved called zeus from there but  i will dig around and see if i can pull it out on my own
...

### Steps to reproduce the issue: enter world 

...

### Environment
- Starship EVO version: 22wa11
- Graphics Card: Asus geforce 1080 ti

![image](https://user-images.githubusercontent.com/63330810/161163049-d47354ac-c7d8-45a4-b84d-fdf2bbe820ab.png)

[Development World - Copy.zip](https://github.com/tsunamayo/Starship-EVO/files/8393519/Development.World.-.Copy.zip)

**Comment by tsunamayo** [comment]
Hi, do you have the log file for this? My guess is that you are now inside the sun. Can you see the sun from there? 
Thanks

**Comment by Drillz007** [comment]
I dont have the log but i had the world file right underneath the image (i hope that works)

**Comment by tsunamayo** [comment]
@Drillz007 Sorry for the late reply, yes indeed your world was corrupted, all build are still there but you are now in the center of the sun. You can manually reimport blueprint to a fresh world. Thanks!
