### ISSUE TITLE
[Question] What is the ultimate plan for generation, factional and natural?

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#4667]
So with the planet sizes/system sizes being reduced, what is the plan for generation both "natural" and "constructed"

Currently the natural generation of the galaxy is the same for everyone. Same planets, same systems. Is that still the plan and where does the buck stop? Systems will be the same, planets will be the same, what about the land generated on it? Asteroids, phenomena like comets and whatever else? And of course the green star.

And what about "constructed" items like the stations and cities on planets and rings. Will those be generated and placed randomly?

And finally NPC factions. Now what I assume/hope it would be is that different factions randomly generated and given various territory across the galaxy. Different primary motives which will determine the availability of resources/information and attitudes which will determine initial faction reputation such as the below alignment which would determine what ships they generate
![image](https://user-images.githubusercontent.com/36980446/161404947-d9e93118-5856-4a0a-ba8e-79222a333333.png)
However now we have the galactic police (how about a rename to the Star Core? Sounds cooler :D) and that reputation system. So what is the plan for NPC factions? Will there be the police as well as a sort of order keeper for non-factional space? Am I making sense lol

Also change Won to Clips

**Comment by TIKIRobo** [comment]
I think it would be cool if the space police were their own faction (with their own planets, stations, etc.) that way:
1. you could theoretically take over or completely remove the police making your criminal empire even stronger!
2. xenophobic factions or maybe expansionist factions would have to have their own police force as the galactic police wouldn't want to/be able to enter their territory

**Comment by tsunamayo** [comment]
@ZachZent Hi, so I want to have the world to be the same at each generation, so hopefully a player that find a cool planet can share it with another. Regarding faction on the other side I would like it to be per character, so it might add a bit of randomness to each playthrough. Cheers
