### ISSUE TITLE
Stickers are not visible when placed on wood and glass blocks.

### ISSUE THREAD

**Issue by Regnion** [tsunamayo/Starship-EVO#4669]
### Short Description of the issue:

Stickers are not visible when placed on wood and glass blocks.

### Steps to reproduce the issue:

Place a sticker on a wood or glass block.

### Environment
- Starship EVO version: Literally any since forever.

### Additional information:

Please allow sticker placement on wood and glass blocks. There are things we can do with this capability that are strictly impossible without this.

Wood floors? I have to use a off-color dark brown sticker and different sized blocks to make a janky corner work, and it's not at all satisfactory. It would be totally possible to do this corner cleanly, if the basic systems we enjoy with every other block were functional with wood blocks. The stickers are on metal blocks. If we could stickers on wood, this wouldn't be necessary at all.

Glass, for example. You know those glass panes in Star Wars with charts and stuff on it? Can't do that here. Here's a cheap example with the little slab blocks.

![20220403112042_1](https://user-images.githubusercontent.com/13087952/161440161-2c296ca7-eafd-4403-ad19-741cd227dfc5.jpg)

![20220403112334_1](https://user-images.githubusercontent.com/13087952/161440150-e24651bf-975c-430f-a95f-a53db9ff4d64.jpg)

**Comment by tsunamayo** [comment]
@Regnion Hi, so wood will be promoted to a material in the future. And it is not possible to apply decal with the tech currently, it have to be an opaque surface. Thanks
