### ISSUE TITLE
Are shipyards still broken for large vessels?

### ISSUE THREAD

**Issue by Arutus** [tsunamayo/Starship-EVO#4670]
Shipyards still do not work as of right now for large ships

**Comment by ProPeach** [comment]
@Arutus you mean #4608? It's marked as fixed, have you tested in a recent version?

**Comment by Arutus** [comment]
yes its still broken shipyards do not seem to function for 100m+ vessels. I was asked in the last the patch for BPs for the very same issue and it has not been resolved. Here are the BPs
[ANPIF Grand Dominance ver 3.5.zip](https://github.com/tsunamayo/Starship-EVO/files/8454506/ANPIF.Grand.Dominance.ver.3.5.zip)
[ANPIF Orion Corvette.zip](https://github.com/tsunamayo/Starship-EVO/files/8454509/ANPIF.Orion.Corvette.zip)

**Comment by Arutus** [comment]
Attempt to dock the corvette with the dread this is also on the stable ver of the game btw

**Comment by tsunamayo** [comment]
@Arutus Hi, issue will be fixed for 22w45a. Thanks
