### ISSUE TITLE
[Bug] Line pattern on mid-range lighting

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4674]
### Short Description of the issue:
Outside of the close LOD lighting and inside the range that shadows appear, there is a repeating line pattern of shadows on all hull. Here you can see the line pattern clearly as it is compared to the close LOD sphere. Pretty sure this is new to 22w14a
![image](https://user-images.githubusercontent.com/27857711/162674237-a448006b-aeee-4586-b0d3-3ec717c13ee6.png)

Ranges from no shadow range - no lines
Shadow range - lines
Within 20m - no lines
https://user-images.githubusercontent.com/27857711/162674584-b94fa15e-9a66-463b-aa2b-705ef1fba633.mp4

### Steps to reproduce the issue:
- Look at hull at different ranges, it's visible from around 20m+

### Environment
- Starship EVO version: 22w14a
- Graphics Card: RX580

**Comment by ProPeach** [comment]
Looks like the striped shadow effect is also visible at close ranges too, especially as it flickers when the character moves
![image](https://user-images.githubusercontent.com/27857711/162721990-1909e674-fa75-4364-a659-8b3aee8e37db.png)

**Comment by tsunamayo** [comment]
@ProPeach I think we always had this, you are sure it is new? It depends on much inclination to the sun your surface is, so you might not always see it as strongly. Thanks

**Comment by ProPeach** [comment]
@tsunamayo yes you're right, hopped back to a backup from a couple weeks ago and it's still there. My bad!
![image](https://user-images.githubusercontent.com/27857711/162978380-a2377261-75e2-43c1-bc6c-2ff764025767.png)
It's this kind of angle from the sun
![image](https://user-images.githubusercontent.com/27857711/162978449-a52bef72-a354-401a-bb5d-b3f116ac31a5.png)
Do you have plans to combat this eventually then? I wouldn't mind sacrificing a few frames with a higher shadow detail setting in the options to reduce this effect

**Comment by tsunamayo** [comment]
@ProPeach Unfortunately shadow are very costly, it would not be just a few frames and will never really get rid of it entirely. Thanks
