### ISSUE TITLE
[Bug] Pipe X-ray tools not working

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4675]
### Short Description of the issue:
Both the "Pipe See Through" effect that you disable in the F3 menu, as well as the "Fuel Piping Overlay View" in the F1 menu don't seem to function, I see no overlay for either one when they're turned on

### Steps to reproduce the issue:
- Enable Fuel Piping Overlay View and look at a ship with systems/fuel
- Hold a pipe in your hand and check for the Pipe See Through effect

### Environment
- Starship EVO version: 22w14a
- Graphics Card: RX580

### Additional information:
![image](https://user-images.githubusercontent.com/27857711/162681084-5ca80671-fc0f-4772-a6b9-e2f761c32d13.png)
Pipe See Through not working (it is not disabled in the F3 menu, I checked twice 😝)

**Comment by CurioInventorium** [comment]
I've been finding that the pipe connectors are appearing at every connection between pipes. I've been meaning to raise an issue but haven't got round to it yet.

**Comment by tsunamayo** [comment]
@ProPeach Hi, this will be fixed for 22w24a. Cheers
