### ISSUE TITLE
[Bug] Flood light flickering when moving the camera

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4677]
### Short Description of the issue:
When the players view is moving, the spotlight will flicker. The spotlight does not flicker when you keep still

https://user-images.githubusercontent.com/27857711/163001389-d86d8224-7db2-48e0-be53-a97f14808047.mp4

### Steps to reproduce the issue:
- Place a Flood light
- Move the camera

### Environment
- Starship EVO version: 22w14a
- Graphics Card: RX580

**Comment by tsunamayo** [comment]
@ProPeach Hi, not sure if I reproduced the issue beforehand but I think it should be fixed for next update. Happy new year!
