### ISSUE TITLE
[Bug] Windows flickering

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#4679]
https://media.giphy.com/media/oNRhdvGpoLV3wOeiZc/giphy.gif

As an aside, window tinting would be cool. Maybe a new window that has one sided tinting?

Currency name Won to Clips

**Comment by tsunamayo** [comment]
Yes it is because transparent surface are not sorted atm unfortunately. I gave a shot at it but it was too buggy and complicated. It is on my to-do list but as it is not game-braking and very tricky it is quite low tbh.
Clips sounds good but can be confusing... (sounds like ammo)
Thanks

**Comment by tsunamayo** [comment]
This was actually another bug, but it was fixed sometime ago. Thanks
