### ISSUE TITLE
[Question] Terrain + Heat

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#4682]
Hey Tsuna, just had a thought in a brief conversation about terrain. How would the heat mechanic work on structures or things built on terrain? IE planets, the torus, asteroids, etc. I know the whole premise was that there are things that produce heat and the rest of the ship/station acts as a giant radiator, dispersing the heat. Would there be some heat reduction for ground bases at all? It could give an incentive to build planetary bases. Just a thought!

**Comment by tsunamayo** [comment]
Hi, sorry I am not too active here lately guys. So yes I guess what make the most sense is to either dont give any heat penalty or add a boost for points in contact with terrain and not space.
I could also give a higher heat dissipation to points inside atmosphere and water. You can check those points in the F3 menu (Physics / View Collision points or something). 
Thanks

**Comment by LoganDark** [comment]
I think heat would be less affected by the ground itself and more affected by the fact that you're in an atmosphere
