### ISSUE TITLE
Pickup of Hull Wedge block in tutorial crashes my game.

### ISSUE THREAD

**Issue by Teizan0** [tsunamayo/Starship-EVO#4683]
### Short Description of the issue:

Pickup of Hull Wedge block in tutorial crashes my game.

### Steps to reproduce the issue:

Proceed through tutorial until the point where you are told to pick up the hull wedge block.
Pick up the hull wedge block.

### Environment
- Starship EVO version: 22w12a
- Graphics Card: RX 580

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8552361/Player.log)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Teizan0 Hi, this sounds bad. Do you reproduce all the time? Thanks

**Comment by Teizan0** [comment]
The issue was repeatable, yes.

**Comment by tsunamayo** [comment]
@Teizan0 Hi, the log file doesnt look like it is from a crash. Are you sure you send the log from just after the crash? Thanks

**Comment by Teizan0** [comment]
Yes, I sent the player.log after the second (identical) crash.

**Comment by tsunamayo** [comment]
@Teizan0 Hi, could you please try to drag an item in your toolbar? Press  TAB to open the codex, click on the cube icon and drag any brick. Tell me if it crashed.
Are you drivers up to date?
Thanks

**Comment by Teizan0** [comment]
My Driver Version was (taken from Radeon Software):
21.30.23.04-211216a-376209C

I've updated to Driver Version:
21.50.02.01-220309a-377495C-AMD-Software-Adrenalin-Edition

and the issue now seems to be resolved.
