### ISSUE TITLE
Accidentally adding ":7777" to an IP address causes an exception

### ISSUE THREAD

**Issue by LoganDark** [tsunamayo/Starship-EVO#4685]
### Short Description of the issue:

Since the game uses port 7777, my friend gave me their IP with `:7777` appended to the end - force of habit from other games like Minecraft. However, trying to join that server results in an exception in the logs, and then all multiplayer completely stops working due to "Client already started."

### Steps to reproduce the issue:

1. Try to connect to a multiplayer server with `:7777` at the end of the IP address

### Environment
- Starship EVO version: 22w14a
- Graphics Card: N/A

### Additional information:

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8565873/Player.log) - contains the initial exception as well as 2 additional attempts to reconnect:

1. with the `:7777` still present;
2. with the `:7777` removed

Restarting the game is required in order to connect to the IP without `:7777`, in which case joining the server works correctly.

**Comment by tsunamayo** [comment]
@LoganDark Hi, this issue will be fixed for 22w51a. Thanks!
