### ISSUE TITLE
Can't see friends in multiplayer

### ISSUE THREAD

**Issue by Famous5000** [tsunamayo/Starship-EVO#4686]
### Short Description of the issue:
When trying to host multiplayer and having my friend join, they are able to connect however I can't see them but they can interact as if they were in the game, and that properly replicates to my end.
...

### Steps to reproduce the issue:
Host a game, open to multiplayer, have your friend join.
...

### Environment
- Starship EVO version: 22w14a
- Graphics Card: Direct3D 11.0 [level 11.1] {not graphics issue}

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8565888/Player.log) {server, friend will post client log in a few}

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
Hi, this should be fixed in recent version. Thanks
