### ISSUE TITLE
[Bug] Despawning things held by active mag-locks causing issues

### ISSUE THREAD

**Issue by Skenfinarres** [tsunamayo/Starship-EVO#4687]
### Short Description of the issue:

Technically a two part issue.
Despawning something held by an active mag-lock causes the camera to effectively lock in place; However, if you place a starter block while this is happening and then exit to title, loading any saves causes you to be unable to move or do anything except access the menus. After closing the game and reloading the save, the hovercraft platform and the other things around it, as well as anything the player has spawned in is moved to a single point in space. None of the entities have collision, and their shadows follow the player. Additionally, spawning something in near the point and trying to pilot it causes it to be effectively destroyed despite no actual damage and can't be repaired.

### Steps to reproduce the issue:

Part 1:
1. Despawn an entity held by an active mag-lock, after a couple seconds the bug occurs.

Part 2:
1. Place a started block
2. Exit to title
3. Open any save, if multiple are opened in one session it affects all of them (bug can be avoided by exiting to desktop without opening any save)
4. Close the game and relaunch it. Any of the saves opened in step 3 have had the bug occur to them.

### Environment
- Starship EVO version: 22w14a
- Graphics Card: NVIDIA GeForce GTX 1650

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

What the screen looks like during step 3:
![20220427214538_1](https://user-images.githubusercontent.com/104476664/165666505-ca61abbc-434f-4c27-b1ac-843a00aaba9b.jpg)

Screenshot of the mass of ships:
![20220427213225_1](https://user-images.githubusercontent.com/104476664/165664896-a24229d5-286f-4058-b177-350174a82a9c.jpg)

Screenshot with no additional ships:
![20220427213603_1](https://user-images.githubusercontent.com/104476664/165665564-ad235617-3494-423e-90eb-c3e6422d18b5.jpg)

A NPC also caught inside the mess?
![20220427213637_1](https://user-images.githubusercontent.com/104476664/165665618-68fcfefb-f6db-4e10-912e-32f1ffb08c27.jpg)

Player log of triggering the bug:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8579136/Player.log)

**Comment by tsunamayo** [comment]
@Skenfinarres Hi, this issue will be fixed for 22w51a. Thanks!
