### ISSUE TITLE
Exit to title -> create new world causes break

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4688]
### Short Description of the issue:
While trying to create a repeatable case for another bug, I exited to title and created a new world which resulted in this -

https://user-images.githubusercontent.com/27857711/165766128-e33efccb-cfd9-4782-9893-9b934deaddc8.mp4

### Steps to reproduce the issue:
Sadly I am unable to reproduce this with additional new worlds, I hope there's something useful in the log
- Load a world
- Exit to Title
- Create new world and load it

### Environment
- Starship EVO version: 22w14a 
- Graphics Card: RX580

### Additional information
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8583241/Player.log)

This was the new world created, it seems fine now when I load it up again
[Flickering Bug.zip](https://github.com/tsunamayo/Starship-EVO/files/8583249/Flickering.Bug.zip)

**Comment by ProPeach** [comment]
Actually, I can reproduce it. Looks like I need to load up a specific world > exit to title > create new world for the bug to occur.

I've emailed you the .zip of the world separately, sorry to be a pain but it's a really huge world and there's a lot of stuff in there that's not ready to be shared yet

**Comment by ProPeach** [comment]
Seems that somehow through all this troubleshooting my controls got reset to default which is kinda awkward

**Comment by tsunamayo** [comment]
@ProPeach Hi, this will be finally fixed for 22w24a. Thanks!

**Comment by ProPeach** [comment]
Thank you for following this one up! : )
