### ISSUE TITLE
Flicker graphics in ship 

### ISSUE THREAD

**Issue by wolfen51** [tsunamayo/Starship-EVO#4690]
### Short Description of the issue:
Spartically the effect in the video occurs during game play. This video has shadow and collision turned off and its still occurring. 
...

### Steps to reproduce the issue:
Get in a ship and fly around. 

...

### Environment
- Starship EVO version: 22w14a
- Graphics Card: Nvidia 1050ti

### Additional information:

https://user-images.githubusercontent.com/104575479/166072453-678299a8-bf9c-48b1-aca9-2c2d98d19f7f.mp4

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@wolfen51 Hi, thanks for the video, I think it must be another issue (it is different from the culling one from ProPeach). It must be related to the large rendering distance update. I keep you posted!

**Comment by tsunamayo** [comment]
@wolfen51 Hi, this will be fixed for 22w25a. Thanks
