### ISSUE TITLE
decals cant be painted

### ISSUE THREAD

**Issue by KINGrimson** [tsunamayo/Starship-EVO#4696]
### Short Description of the issue:
simple really, decals cant be painted

### Steps to reproduce the issue:
place decal and paint it
...

### Environment
- Starship EVO version: 22w19a
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@KINGrimson Hi, issue will be fixed for 22w21b. Cheers
