### ISSUE TITLE
[BUG] Being near asteroids crashes the game

### ISSUE THREAD

**Issue by zorozeenee** [tsunamayo/Starship-EVO#4697]
### Short Description of the issue:
Went to check out the new asteroids, crashes by game consistently 

### Steps to reproduce the issue:
stand near or on an asteroid

### Environment
- Starship EVO version:  22w18a
- Graphics Card: nvidia gtx 1660 super

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8677409/Player.log)

**Comment by tsunamayo** [comment]
@zorozeenee Hi, could you tell me your CPU and RAM? Thanks

**Comment by tsunamayo** [comment]
I fixed several crash linked to asteroids. Hopefully this one is fixed, otherwise I will need more info to investigate. thx
