### ISSUE TITLE
[Bug] Game freezes then crashes while in vicinity of Asteroid rings

### ISSUE THREAD

**Issue by zalexville** [tsunamayo/Starship-EVO#4699]
### Short Description of the issue:

When I approach the rings to the gas giant fast or slow, I freeze and then crash. I tested this 3 or 4 times. I did notice that when it froze, the asteroids seemed to have some missing spots from when it was loading the closer LOD.

### Steps to reproduce the issue:

1. Fly into the asteroid rings.
2. Game crashes.

### Environment
- Starship EVO version: 22w18a
- Graphics Card: Nvidia GeForce RTX 3060 

### Additional information:

[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/8682812/Player-prev.log)

**Comment by zalexville** [comment]
To add to your headache, none of the coatings are working as well:
_Before update:_ 
![20220501134555_1](https://user-images.githubusercontent.com/65626266/168176162-11da2f95-4d21-48d7-b37f-847b99082462.jpg)

_After update:_ 
![20220512180921_1](https://user-images.githubusercontent.com/65626266/168176172-614841b0-b29b-4ef0-8d94-56dd962cce89.jpg)

**Comment by tsunamayo** [comment]
@zalexville Hi, could you tell me your CPU config? Thanks

**Comment by zalexville** [comment]
I haven't edited the basic settings on my CPU. It is a AMD Ryzen 7 2700 Eight-Core Processor 3.20 GHz

**Comment by tsunamayo** [comment]
@zalexville So asteroid have just been improved perf wise in 22w21a. Can you tell me if you still crash? Thanks

**Comment by zalexville** [comment]
Crash seems to be gone, FPS is stable when in the middle of the rings and near a large asteroid. Seems like the performance improvements managed to catch whatever was causing the crash. Thanks!

**Comment by tsunamayo** [comment]
@zalexville Hi, so the decals issue is fixed for 22w24a. Thanks for the update on the crash! Cheers
