### ISSUE TITLE
[bug] Green Stream effect

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#4700]
### Short Description of the issue:

A strange green stream effect is being emanated by the character
...

### Steps to reproduce the issue:
 I don't have any idea how to reproduce it
...

### Environment
- Starship EVO version: 
experimental (current version)
- Graphics Card: 
gtx 1660
i7-3770

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

https://user-images.githubusercontent.com/73253472/168407095-8fc2d1c1-fbe9-4752-8a1e-bb090338c52b.mp4

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
playerlog:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8691989/Player.log)
world:
[Racer.zip](https://github.com/tsunamayo/Starship-EVO/files/8691990/Racer.zip)
blueprint:
[Racer 3.zip](https://github.com/tsunamayo/Starship-EVO/files/8691992/Racer.3.zip)

**Comment by BigBadKangaroo** [comment]
happened to me aswell ...

![20220513233952_1](https://user-images.githubusercontent.com/81495956/168418879-3c1a9ad5-0efb-4b51-8152-4bae65ba3133.jpg)

**Comment by tsunamayo** [comment]
hum hum, this is quite a sight to behold... I it related to the paint sfx, I will try to reproduce. Thx!

**Comment by ProPeach** [comment]
Happens to me almost every time I use the paint tool, with colours or coatings

**Comment by Uncle-Ulty** [comment]
> happened to me aswell ...
> 
> ![20220513233952_1](https://user-images.githubusercontent.com/81495956/168418879-3c1a9ad5-0efb-4b51-8152-4bae65ba3133.jpg)

-sir, please, use the toilet!

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hi, this should be fixed in 22w24a. Thanks!
