### ISSUE TITLE
[Bug] Killing ships gives you super powers

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4702]
### Short Description of the issue:
I was messing around shooting at ships, when suddenly my character gained a strange power...

![SuperSevo](https://user-images.githubusercontent.com/27857711/168451065-41d466c3-5b1c-4ef2-a1c0-e3e4bc99f856.gif)
3 different coloured streams of particle effects shooting out in different direction from the player

### Steps to reproduce the issue:
- Pilot a ship
- Shoot another ship until it is dead
- The character will now be magical

### Environment
- Starship EVO version: 22w19a (Marked as 22w18a in game, I assume in error)
- Graphics Card: RX580

### Additional information:
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/8694032/Player-prev.log)

**Comment by tsunamayo** [comment]
Hi, it looks related to system chip drop. Let me try to reproduce!

**Comment by tsunamayo** [comment]
@ProPeach Hi, this will be fixed for 22w24a. Thanks!
