### ISSUE TITLE
FPS drop in asteroid filed

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#4703]
1.I was zipping through the asteroid field with a small and fast ship, and my FPS dropped down pretty hard when flying near an asteroid.
I can't reproduce this when I'm flying slower.

2.In addition to that; after zipping though the  asteroid field my camera got offset. After using lightcruise everything went back to normal.
However my FPS stayed lower than usual - only a restart of the game fixed this.

Player.Log:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/8694531/output_log.txt)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8694536/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/8694537/Player-prev.log)

1 .![20220515090757_1](https://user-images.githubusercontent.com/81495956/168463524-1045d488-105b-4f1a-b5c7-01d0a456b4bd.jpg)
![20220515090807_1](https://user-images.githubusercontent.com/81495956/168463531-1d20f748-3458-406b-8729-6fe0d7cd4d34.jpg)
![20220515090859_1](https://user-images.githubusercontent.com/81495956/168463534-95e056de-2576-4496-9a52-75470047b75e.jpg)
![20220515090924_1](https://user-images.githubusercontent.com/81495956/168463537-bcbb520a-f0a8-44f1-b435-198dccddbf8e.jpg)

2. ![20220515091012_1](https://user-images.githubusercontent.com/81495956/168463606-954bc757-7dae-42fe-ab71-ae641dcb1550.jpg)
![20220515091020_1](https://user-images.githubusercontent.com/81495956/168463614-30e0a3e7-3310-474c-b540-b7c04a10fad1.jpg)

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, is this something you reproduce everytime? If yes can you try in the new build (perf have been improved)
Thanks

**Comment by BigBadKangaroo** [comment]
@tsunamayo in the new build 22w21a the performance is no longer an issue for me.
