### ISSUE TITLE
Clipboard Shadows

### ISSUE THREAD

**Issue by OgasaRD** [tsunamayo/Starship-EVO#4706]
a shadow remains on surfaces then things are saved in clipboard. 

...

Use Copy/paste to put save item to clipboard. shadow appears. 

...

Ring
- Starship EVO version: 22w18a
- Graphics Card: GeForce 1070ftw SLI Configured

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\Loca
![20220516144842_1](https://user-images.githubusercontent.com/105675319/168673924-04273ac6-7ed3-424e-83a8-1947e365f1bb.jpg)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8703113/Player.log)

![20220516144700_1](https://user-images.githubusercontent.com/105675319/168674091-39b70ad4-cf58-4f8a-a61f-1d2b737b278e.jpg)
![20220516144842_1](https://user-images.githubusercontent.com/105675319/168674094-277da10c-9aeb-40f2-a67c-0aa521e24847.jpg)
lLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by OgasaRD** [comment]
if you empty the clipboard ghost shadow disappears.

**Comment by ProPeach** [comment]
You should leave this one open, it's a good report for a bug!
