### ISSUE TITLE
Crash, no crash report

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4707]
### Short Description of the issue:
The game crashed, but there was no crash folder created in /Moonfire Entertainment/StarshipEvo. All I have is the player log, I hope it has some clues

### Steps to reproduce the issue:
At the time of the crash, I was copying a small part ready to paste it somewhere else. The crash happened a few seconds after the copy completed
I've tried copying the same part again and the game did not crash, so it might not have been related

### Environment
- Starship EVO version: 22w18a
- Graphics Card: RX 580

### Additional information:
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/8709669/Player-prev.log)

**Comment by tsunamayo** [comment]
Sorry I am closing this as I cant really investigate... Cheers
