### ISSUE TITLE
[BUG] Floaty hologram stuff particularly on older builds

### ISSUE THREAD

**Issue by SnowyBirdot** [tsunamayo/Starship-EVO#4709]
### Short Description of the issue:
When loading old blueprints, holograms just tend to show up from some angles, or just, big slabs of textures, which is exampled in what I've seen with my chair included.
...

### Steps to reproduce the issue:

Load very old blueprint (Last I was on was Dec 21st 2021, blueprints I think are much older.)

Enjoy
...

### Environment
- Starship EVO version: 22w18a
- Graphics Card: GTX 1050 Ti

### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8735002/Player.log)
![20220519190024_1](https://user-images.githubusercontent.com/72358669/169428395-47a2fa0b-aec9-4933-b039-2f863e5d5a00.jpg)
[Blueprints for example!.zip](https://github.com/tsunamayo/Starship-EVO/files/8735014/Blueprints.for.example.zip)

Also, doing good work Tsuna, tons of progress over these last months!

**Comment by SnowyBirdot** [comment]
Hopping back on, this might not persist after a restart, which is interesting.

**Comment by tsunamayo** [comment]
@SnowyBirdot Hi, thanks for the bp I will check this out.

**Comment by tsunamayo** [comment]
@SnowyBirdot Hi, I think this should have been fixed in 22w21a. Please re-open the case if you see that again! Thanks
