### ISSUE TITLE
Logic/Blueprint casues game freeze

### ISSUE THREAD

**Issue by piotmetans** [tsunamayo/Starship-EVO#4711]
Something about this logic circuit/blueprint causes the game to freeze, but all menus can still be interacted with.

Blueprint:
[buggylogic.zip](https://github.com/tsunamayo/Starship-EVO/files/8754761/buggylogic.zip)

Here's the button that causes the game freeze:
![bugss](https://user-images.githubusercontent.com/660015/169826792-0556f44c-5a19-433a-9896-a78f0ece8c10.png)

Game version: 22w14a Default
GPU: RTX2070 Super
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8754757/Player.log)

**Comment by tsunamayo** [comment]
@piotmetans Sorry for the long delay, it will be fixed for 22w45a. Thanks!
