### ISSUE TITLE
[Crash] Various causes

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4712]
### Short Description of the issue:
When flying in to a cloud of loot chip to pick them up, I crashed. I can repeat the crash whenever I fly in to these chips

Again there was no Crash folder created, so all I have is the .log for it

### Steps to reproduce the issue:
Fly in to a cloud of loot chips

### Environment
- Starship EVO version: 22w14a
- Graphics Card: RX 580

### Additional information:
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/8755992/Player-prev.log)

Another log from another crash, this time I think I only picked up a single chip

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8756003/Player.log)

**Comment by ProPeach** [comment]
Actually just crashed again, while just building and with no interaction with loot chips
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/8757968/Player-prev.log)

**Comment by tsunamayo** [comment]
@ProPeach Hi, so this should have been fixed in 22w19a (the asteroid build). Do you get crash there too? Thanks
