### ISSUE TITLE
Bugged asteroids

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#4714]
1.There's a bug with the larger asteroids where they show up as intended by far, but if you come closer they just disapear.
2.Smaller asteroids can just be clipped through:
![20220524203109_1](https://user-images.githubusercontent.com/81495956/170109190-ba213db5-adc3-4f90-bc5b-1caa93280dbc.jpg)

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, it seems that the higher res LOD are not showing. Could you please send me your log?

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, can you send me the bp? Thanks

**Comment by zorozeenee** [comment]
When i mine asteroids the section i shot with a mining beam teleports 100m away from the asteroid (the whole chunk)
Then if i hang around for more than 30 seconds it crashes my game

**Comment by tsunamayo** [comment]
@BigBadKangaroo So the entity collision issue is fixed for 22w25a. Thanks!
