### ISSUE TITLE
Decals can't be painted

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#4715]
Pretty simple:

Decals can't be painted. Neither with colors or materials.

**Comment by daOyster** [comment]
I've also been experiencing this since the previous patch too.

**Comment by SL-Nokz** [comment]
I am able to paint decals, but the hot box to paint them seems rather excessive. Sometimes to paint the block underneath I have to move through it while spamming the paint color. Not game breaking, but for sure annoying.

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, issue is fixed for 22w21b. Thanks
