### ISSUE TITLE
[bug] Terrain gaps

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#4716]
### Short Description of the issue:
These fractures/gaps appear when you load or get closer to some sections of the terrain.
...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: current
- Graphics Card: 
gtx 1660
i7-3770
16Gb (1600Mhz ddr3)

### Additional information:
![image](https://user-images.githubusercontent.com/73253472/170385078-a12b6054-a375-4e99-aab4-459025b60d8e.png)

![image](https://user-images.githubusercontent.com/73253472/170385176-2f9b4b1c-2d93-4b32-8c34-15f875dba496.png)

![image](https://user-images.githubusercontent.com/73253472/170385213-06e25267-2fc6-43c1-96e6-581e0a74cc47.png)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/8775156/Player-prev.log)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8775157/Player.log)

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hi, yes it is the known issue in my latest patch note. It is because of the tesselation, I will need to change the way I patch the border between LODs. thanks
