### ISSUE TITLE
[bug]  Super Saiyan effect

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#4717]
### Short Description of the issue:

Super Saiyan effect.
...

### Steps to reproduce the issue:
I don't know how to recreate it
...

### Environment
- Starship EVO version: current
- Graphics Card: 
gtx 1660
i7-3770
Ram: 16Gb
### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

![image](https://user-images.githubusercontent.com/73253472/170386450-6e2777a2-afad-42a3-ab9e-4672fd92f2d5.png)

video:

https://user-images.githubusercontent.com/73253472/170387098-523c80d7-41cf-4c35-846a-fa66c4462a44.mp4

[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/8775185/Player-prev.log)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8775186/Player.log)

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hi, well what were you doing before that happened? If nothing it might have been some NPC battle...
Thanks

**Comment by Uncle-Ulty** [comment]
Yes, I was shooting at the pirates close to the stations, and suddenly it started to happen

**Comment by Uncle-Ulty** [comment]
@tsunamayo , I think there is something stacking all effects on the character:

https://user-images.githubusercontent.com/73253472/170838176-352b6516-8ee4-4f77-854e-f1dde0821360.mp4

**Comment by BigBadKangaroo** [comment]
I don't even know what happend ... 
![20220528150458_1](https://user-images.githubusercontent.com/81495956/170840460-3f8b085b-9007-4f14-9e9a-89e753abe71f.jpg)

**Comment by Uncle-Ulty** [comment]
> I don't even know what happend ... ![20220528150458_1](https://user-images.githubusercontent.com/81495956/170840460-3f8b085b-9007-4f14-9e9a-89e753abe71f.jpg)

it seems you now can bend all four elements. We found the Avatar!

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hi, this will be fixed for 22w24. Thanks!
