### ISSUE TITLE
Visual Glitch caused by Pipes on Handhelds & Item stands

### ISSUE THREAD

**Issue by RL055** [tsunamayo/Starship-EVO#4720]
### Short Description of the issue:

Using Fuel Tanks/Pipes (Most Fuel pieces) on a Handheld weapon on the Item Stand will cause some parts to turn invisible and flicker, including a black cylindrical texture to flicker on the item stand. These visual glitches will not disappear until you create a new character and delete the old one.

### Steps to reproduce the issue:

Place Pipes from the Fuel Section onto Handheld on any Item stand

### Environment
- Starship EVO version: 22w21b Experimental
- Graphics Card: GTX 1660ti MSI GamingX
  CPU: i5 8600k
  32GB RAM

### Additional information:
I have included a screenshot in the ZIP file
[Starship EVO.zip](https://github.com/tsunamayo/Starship-EVO/files/8789210/Starship.EVO.zip)

**Comment by tsunamayo** [comment]
@RL055 Hi, this will be fixed for 22w24a. I dont think it was related to pipes, it was a culling issue on handhelds. Thanks

**Comment by RL055** [comment]
Thanks for your hard work!
