### ISSUE TITLE
[bug] Big mining gun makes asteroid's sections to disapear 

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#4721]
### Short Description of the issue:
Big mining gun is making huge sections disappear. 
...

### Steps to reproduce the issue:

When I reloaded the game, the bug stopped, so I really don't know what caused it.
...

### Environment
- Starship EVO version: current
- Graphics Card: 
gtx-1660
i7-3770
ram 16Gb

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You

https://user-images.githubusercontent.com/73253472/170800190-7e50eb1a-f391-4adb-8539-ce0c3e486e36.mp4

 can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[DIGGER.zip](https://github.com/tsunamayo/Starship-EVO/files/8790074/DIGGER.zip)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/8790075/Player-prev.log)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8790076/Player.log)
[HIGHWIND - Final Fantasy VII Airship.zip](https://github.com/tsunamayo/Starship-EVO/files/8790080/HIGHWIND.-.Final.Fantasy.VII.Airship.zip)

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hi, this should be fixed in current version. Thanks!
