### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#4722]
I placed an item stand and hit F on it to spawn a handheld blueprint. After that my character stopped moving but I could still move the camera around. 
I then went back to the tilte screen and reloaded the world.
The bug still occured!
I then restarted the game and now the game crashes everytime when I try to load into this world

World:
[22w21a.zip](https://github.com/tsunamayo/Starship-EVO/files/8791149/22w21a.zip)

Log:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8791146/Player.log)

**Comment by BigBadKangaroo** [comment]
Edit:
After createing a new world and then going back to the old one, I managed to get back into the world.
This is what I faced:

Every ship spawned in this world was sucked up into one "blob-ship" and I guess they are all destroyed as seen on the upgrade  chips
![20220528145714_1](https://user-images.githubusercontent.com/81495956/170826584-de0d4f28-e7a7-45eb-a00a-7a0230405f35.jpg)
![20220528145726_1](https://user-images.githubusercontent.com/81495956/170826587-d93d000e-be4b-4018-b188-332c2722a88f.jpg)

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, sorry I guess this world is corrupted by the crash. You should still be able to get back your blueprint.
Could you send me the content of the following folder (which match the crash date)? 
 * C:/Users/Anwender/AppData/Local/Temp/Moonfire Entertainment/Starship EVO/Crashes
  Also as it seems linked to handheld blueprint, do you reproduce that issue everytime?
Thanks
