### ISSUE TITLE
[Bug] Landing Pads on Child Entities not showing up in F menu [22w21b]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#4724]
### Short Description of the issue:
Landing pads that have been placed on child entities do not show up when interacting with the target using the F menu.

### Steps to reproduce the issue:
Spawn a ship that uses landing pads on child entities, target it, then press F. The docking option will be absent.

### Environment
- Starship EVO version: 22w21b
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
This problem occurs across multiple blueprints, but here is an example of the one I was using when I found this for convenience. :3
[Firestorm Prototype.zip](https://github.com/tsunamayo/Starship-EVO/files/8810033/Firestorm.Prototype.zip)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8810029/Player.log)

**Comment by SL-Nokz** [comment]
I think this is a known issue. I've searched this before, but I have the same issue as well on one of my ships that I was configuring to be a carrier. 

I placed a shipyard block onto my current ship. Made it big enough for the spaceship I wanted to land there, and no target at all. Nothing pops up as being targetable to land on. 


Ryzen 9 5900HS 
RTX 3070
Game version:22w14a

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Hi, okay let me look into it. thx

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Hi, so I tested it is working fine. You can now make the request, if it is invalid it will tell you why, so that will be more convenient to debug. Nice ship, is it a larger one?
Thanks
