### ISSUE TITLE
generating invisible entities / collisions

### ISSUE THREAD

**Issue by Azathoh-the-blind-idiot-god** [tsunamayo/Starship-EVO#4725]
### Short Description of the issue:
The game generates collision points in a location without there being an entity there.
The collision points appear to correspond with those on another entity in the same world but none of those have ever been in that position.
### Steps to reproduce the issue:

I don't know exactly how it happened  because I don't know when the issues first appeared but I suspect it has to do with me copy/pasting a large object consisting of 78 CEs onto a rotor.

### Environment
version: 22w14a
GPU: RX 5700XT

### Additional information:

Attached are 2 screenshots showing collision points and entity BVH, the world in which this happened, and the player.log file
[astrotech 1.zip](https://github.com/tsunamayo/Starship-EVO/files/8819242/astrotech.1.zip)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8819244/Player.log)
![20220602004723_1](https://user-images.githubusercontent.com/70778117/171515533-855f4f74-ecbc-4e3a-8a45-3401552599c5.jpg)
![20220602004952_1](https://user-images.githubusercontent.com/70778117/171515542-513ec06a-fba0-488c-b1a7-190606a0a5ec.jpg)

**Comment by tsunamayo** [comment]
@Azathoh-the-blind-idiot-god Hi, yeah it is not really a bug as it only impact the debugging feature, not the game. The prefab / copy/pasted entity leave somewhere in the world. It would require more code to ask them to not be drawn!
Cheers
