### ISSUE TITLE
[bug] Metallic paint on decals

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#4726]
Hi Tsuna!

I noticed a change in decal paints. It seems the decals aren't showing the metallic colors anymore. Instead, they are all black. It's happening on all builds

Before
![image](https://user-images.githubusercontent.com/73253472/171746128-792c544e-cd20-421e-b843-1d99d5b7f9ec.png)

After
![image](https://user-images.githubusercontent.com/73253472/171746167-9c3483c0-f1b7-4874-85c8-1f5e2275ae19.png)

**Comment by Uncle-Ulty** [comment]
it's on experimental version of the game*

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hi, so this will be fixed for 22w24a. Thanks!
