### ISSUE TITLE
[Bug] Glass flickering [22w23a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#4730]
### Short Description of the issue:
Glass (canopies, windows) flickers when looking through it. The effect is similar to z-fighting.

### Steps to reproduce the issue:
Place a brick that has glass on it, and then move around it. The flicker should be evident.

### Environment
- Starship EVO version: 22w23a
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8882595/Player.log)

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Hi, is it when you view several glass brick, or does it happens with single brick? 
Unfortunately with several it is normal as it (there is no depth sorting for transparent surface yet), but not the single one.
I am having a lot of trouble to reproduce the single brick case, it doesnt appears that frequently at all for me.
Thanks

**Comment by Dwarf-LordPangolin** [comment]
Hi Tsuna! It can happen with even a single brick. Example below:

https://gfycat.com/solidpositivehydatidtapeworm

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Okay this should be fixed for 22w25a. Thanks a lot!
