### ISSUE TITLE
[Bug] Disappearing Hinge Child Side [22w23a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#4731]
### Short Description of the issue:
Hinges can lose their child entity half and some attached bricks; this blocks placement where the missing bricks were.

### Steps to reproduce the issue:
Unknown as yet, I am including the blueprint I found this on as an example.

### Environment
- Starship EVO version: 22w23a
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
![20220610175818_1](https://user-images.githubusercontent.com/33041786/173160765-519182a8-c844-4993-bd56-c691c4aa6ea0.jpg)

[Firestorm Prototype.zip](https://github.com/tsunamayo/Starship-EVO/files/8882644/Firestorm.Prototype.zip)

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Hi, so I loaded the bp (amazing btw!), and it was because those bricks where damaged. We had issues with damage decals not showing, but it was fixed in 22w24a. So you can repair those block on the entire ship.
Thanks!
