### ISSUE TITLE
[Bug] Pipes do not draw fuel from tank until reloading [22w23a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#4732]
### Short Description of the issue:
When connecting a pipe to a fuel tank, the pipe will not start drawing fuel from the tank until either the game has been saved and reloaded, or the blueprint has been respawned.

### Steps to reproduce the issue:
Create a new ship, place a fuel tank. Fill it. Place something like a reactor, then place a pipe between them. The pipe will not start drawing fuel until the game is save/loaded, or the BP is respawned.

### Environment
- Starship EVO version: 22w23a
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8886870/Player.log)

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Hi, I think it should be fixed since now fuel is using the new inventory system. Thanks
