### ISSUE TITLE
[Bug] Fuel connection widget remaining after connected brick removed [22w23a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#4734]
### Short Description of the issue:
When deleting system brick that is connected to a pipe, the connection element remains where the brick was. This can lead to confusion over what is actually connected.

### Steps to reproduce the issue:
Place a fuel tank and a system brick that requires fuel (e.g., reactor). Connect them with a pipe, then delete the system brick. The pipe connection bit will still be there.

### Environment
- Starship EVO version: 22w23a
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
![20220612171642_1](https://user-images.githubusercontent.com/33041786/173255884-f5a706ca-057a-427f-afd5-7157ca84c63f.jpg)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8886902/Player.log)

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Hi, this will be fixed in 22w25a. Thanks!
