### ISSUE TITLE
[Bug] Pipe Connecting piece inconsistent behaviour

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4737]
### Short Description of the issue:
See the attached video, there are a couple of little things here-
https://i.imgur.com/Vs5J72p.mp4
- Pipe Connector spawns on the top of the Cubic Tank instead of the side facing the rounded Tank to connect the two
- Pipe Connector spawns only when the rounded Tank is placed with the mouse on the Cubic Tank, not when the rounded Tank is placed in the same position but with the mouse pointed at the ground (Does the Pipe Connector being there indicate that these adjacent tanks will share fuel, even without a Tank Join? That would be a brilliant feature to have across all tanks if true!)
- Pipe Connectors do not despawn when attached bricks are removed. These connectors cannot be removed by the player unless the blueprint is respawned
- When the blueprint is unspawned, all new entities spawned with the Starter Block still show the Pipe Connectors

I really like the look and feel of the new Cubic Tank, nice one of that!

### Steps to reproduce the issue:
- Follow the steps in the video

### Environment
- Starship EVO version: 22w24a
- Graphics Card: RX580

**Comment by ProPeach** [comment]
The residual Pipe Connectors from the 3rd bullet point actually don't seem to completely disappear even after reloading a blueprint. They're still visible at certain LoDs, and weirdly in certain orientations

https://user-images.githubusercontent.com/27857711/174115571-885c8cf5-51c7-450f-9e96-9f68943479b5.mp4


https://user-images.githubusercontent.com/27857711/174115699-b582180b-be1a-4149-bb35-813b1d64c6d3.mp4

**Comment by tsunamayo** [comment]
@ProPeach Hi, issue is fixed for 22w25a. Thanks for the detailed case! Cheers
