### ISSUE TITLE
[BUG] De-spawn not working

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#4740]
As of build 22w14a, I cannot get the ship de-spawn function to work. It seems to delete a few blocks, then leaves the rest of the ship visible. I think the physicality of the ship is gone (collisions etc.).

**Comment by tsunamayo** [comment]
@cloudrambler Okay I cant reproduce that issue also. Do you get this 100% of the time? Can you give me a log file to investigate?
Thanks

**Comment by cloudrambler** [comment]
This particular de-spawn failure only happened once and I cannot replicate it either.

**Comment by tsunamayo** [comment]
@cloudrambler Okay I will close this as I cant investigate. If it happen again can you send the error.log too? Thanks
