### ISSUE TITLE
[BUG] Hatch door visibility

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#4744]
When placing a hatch, the door is not immediately visible. Reloading the world makes it visible.

Build: 22w14a
Graphics: GTX1070

**Comment by cloudrambler** [comment]
I experienced the same thing again, except this time the whole ship flickered on/of at maybe 10hz. Again, the problem resolved by reloading the world from the main menu.

**Comment by tsunamayo** [comment]
@cloudrambler Hi, have you some more info on how to reproduce the second issue? Thanks

**Comment by cloudrambler** [comment]
The ship I am working on is fairly new, and so far mainly just hull blocks. So I doubt it's that.

I have noticed that a few items cause graphical instabilities when first placed, which resolve when the world is reloaded.

If I find any further patters or triggers, I will update here.
