### ISSUE TITLE
Light Flickering ( #4704 is back)

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#4746]
Hi,

seems like #4704 is back again.
I deleted quite a few blocks in the same spot with the box delete tool after rebuilding them for my BP a few times.
This happend:
![20220619215759_1](https://user-images.githubusercontent.com/81495956/174498405-5655786a-883c-4e76-9df0-556701506a71.jpg)

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, can you send me a blueprint where I can reproduce easily (if it is something you manage to create easily). As it was fine last time I checked.
Thanks

**Comment by BigBadKangaroo** [comment]
@tsunamayo Hi, so I made a BP that can reproduce the bug. I made some small and simple instructions on how to do it on the BP. The only thing I want to add is that you need to position the BP just like in this screenshot (It makes more sense when looking at the instructions)

BP:
[Bugtest 22w24a.zip](https://github.com/tsunamayo/Starship-EVO/files/8943356/Bugtest.22w24a.zip)
World:
[LFBUG.zip](https://github.com/tsunamayo/Starship-EVO/files/8943357/LFBUG.zip)

![20220620215719_1](https://user-images.githubusercontent.com/81495956/174670682-120a33f6-c8b6-4d6b-8d65-928410b985ff.jpg)

**Comment by tsunamayo** [comment]
@BigBadKangaroo Thanks for the test case, unfortunately I cant reproduce. I need to make sure you are loading the game, then loading this save, then doing the test (that you are not doing the test after 10 min of gameplay for example, or after a quit to title).  Thanks!

**Comment by zorozeenee** [comment]
Confirmed i have this bug all the time on experimental

**Comment by tsunamayo** [comment]
@BigBadKangaroo Still cant reproduce. You will try to reproduce in the next update, if you still reproduce then could you make a video? I might not be doing the right thing. Cheers

**Comment by BigBadKangaroo** [comment]
@tsunamayo Hi, I can reproduce it 100% even in the new update. I even made a video for you :D
Had to upload it to youtube though:
https://www.youtube.com/watch?v=30p5sv85R4o

**Comment by tsunamayo** [comment]
@BigBadKangaroo okay I finally reproduced! The wrong instruction was on the delete part: we have to delete both the copy and the pasted, not either one. I would say it might try to delete brick twice or something like that, I keep you posted.

**Comment by tsunamayo** [comment]
@BigBadKangaroo So it will be finally fixed for 22w25b! So it was coming from the VFX light effect, not the brick, so in the end I dont think the area for the box delete really mattered, we just had to delete a lot of brick and get (un)lucky... 
Cheers thanks a lot for the detailed test case
