### ISSUE TITLE
[SUGGESTION] Block painting selection priority vs stickers

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#4747]
When a block has a sticker applied to it, trying to paint the base block is often quite difficult. I suspect that is because the sticker has three-dimensional bounds, which can often be identical to or larger than the physical block. So the sticker entity is often more selectable than the block itself, even from directions where the sticker graphic is not visible.

Sometimes I have to delete stickers, paint the block, and reapply the stickers. Given that stickers often have to be carefully layered in sequence, the need to ever delete them is quite frustrating.

Suggestion 1: Reduce the selection box size for stickers, so that it is just smaller than that of the physical blocks. Hopefully that would allow blocks to be selected with the paint tool from at least some directions.

Suggestion 2: Provide a method for the painting too to select only blocks. I think this will work, as selecting blocks for deletion is not affected by stickers, so it's a problem unique to the paint tool, which is looking for blocks and stickers.

**Comment by tsunamayo** [comment]
So actually this is a bug / missing feature, it should look up the decal texture, and if the raycast does not intersect the texture it should not paint the decal. Thanks

**Comment by tsunamayo** [comment]
@cloudrambler Hi, this will be implemented for 22w45a. Thanks!
