### ISSUE TITLE
[SUGGESTION] Slow player roll

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#4748]
As far as I can tell, the player roll rate in 6-DOF mode is not affected by the movement speed.

Please can the roll rate be reduced for movement speeds less than 1. Using the same factors (0.5, 0.25, 0.125) should be fine.

**Comment by tsunamayo** [comment]
@cloudrambler Hi, I dont see why, player turning is also not affected by the movement speed. It is not a rotation thing, only a translation thing. Thanks

**Comment by cloudrambler** [comment]
@tsunamayo Maybe I was not clear to start with. I find the player rotation too fast most of the time and quite difficult to stop at the desired orientation. So I would like a method of rotating more slowly. I figured a simple way to do that is to link it with movement speed, but only at the low end (below 1). I think it would be a useful feature.
