### ISSUE TITLE
Glass flickering still present in latest default branch.

### ISSUE THREAD

**Issue by VaporScape** [tsunamayo/Starship-EVO#4750]
### Short Description of the issue:
Glass flickering continues into patch 22w25a.

### Steps to reproduce the issue:
Placed down any glass type block.

### Environment
- Starship EVO version:  22w25a
- Graphics Card:  Nvidia RTX 3060 Ti

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8967146/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@VaporScape Hi, there is two type of flickering. Is it the one you get in a cockpit for example? The second type happens when you look through two layers of glass, and this will be much harder to fix. Thanks

**Comment by VaporScape** [comment]
This issue is occurring when looking at single layers of glass, and persists when looking at glass through another layer of glass

https://user-images.githubusercontent.com/108071406/175465905-e568ec44-ef38-410a-be7f-5484923a3d2a.mp4

though I did not record it, cockpit glass pieces also have the same issue.

**Comment by VaporScape** [comment]
@tsunamayo

**Comment by tsunamayo** [comment]
@VaporScape Hi, so the single layer issue was fixed in 22w32a. The dual + layer issue will take more time unfortunately, it need a heavy tech improvement. Thanks!
