### ISSUE TITLE
[BUG] Asteroid terrain chunks teleport when being mined, game crashes sometimes

### ISSUE THREAD

**Issue by zorozeenee** [tsunamayo/Starship-EVO#4751]
### Short Description of the issue:

I approached an asteroid with my mining ship
i shot the asteroid with a mining beam
the chunk i shot at teleported below the rest of the asteroid

sometimes this crashes the game

### Steps to reproduce the issue:

shoot an asteroid with a mining laser

### Environment
- Starship EVO version: 22w25a (experimental)
- Graphics Card: nvidia gtx 1660 super

### Additional information:

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8969925/Player.log)
![9k](https://user-images.githubusercontent.com/46616297/175369436-89687a4a-e9c0-42c5-b837-ce9713083b1e.png)

**Comment by tsunamayo** [comment]
@zorozeenee Hi, if there is a crash I would really need the error.log from that session, and the crash dump. I will tell you where to find it once I get my hand on the log (it is written inside)

**Comment by zorozeenee** [comment]
most of the time it doesnt crash
