### ISSUE TITLE
[Bug] Gradual Drop in Framerate

### ISSUE THREAD

**Issue by PopkaAkula** [tsunamayo/Starship-EVO#4752]
### Short Description of the issue:

After loading into a save I experience a consistent and gradual frame drop that bottoms out to about 20-30 fps.

### Steps to reproduce the issue:

Load a save

### Environment
- Starship EVO version: 22w25a
- Graphics Card: RTX 3070

### Additional information:

https://user-images.githubusercontent.com/37738021/175399683-73ddbdc5-64db-4e52-a67b-6cc39cf15ffd.mp4

Here's the playerlog if it helps: [Player.log](https://github.com/tsunamayo/Starship-EVO/files/8970972/Player.log)

**Comment by tsunamayo** [comment]
@PopkaAkula Could you please send me your world? Thanks a lot!

**Comment by tsunamayo** [comment]
Also do you this with all your save? Thanks

**Comment by Uncle-Ulty** [comment]
the same is happening in my game. I thought It was an outdated driver, but the problem happens even with GPU on 40% load. But the fps doesn't drop every time, it seems it drops for no apparent reason...

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hi, does it happen on every world? Does it happen on a blank one? Also what are the start and end value, is it a smooth gradual drop like PopkaAkula is mentioning or is it some drop from time to time? Thanks

**Comment by tsunamayo** [comment]
Can other player could tell me if they have issues with fps too? I am trying to see if I have a nasty important issue on my hands. Thanks

**Comment by VaporScape** [comment]
I did find a massive framerate drop when hovering over placed blocks with the camera positioned very close, but this stopped after reloading the game and is probably unrelated to this issue.

**Comment by Uncle-Ulty** [comment]
Yes, it's a smooth gradual drop. It starts to drop and it keeps dropping till very low values. In order to restore 60 fps, I need to restart the game. 

Gonna check on a new world.

![image](https://user-images.githubusercontent.com/73253472/175464655-ce381c63-a74e-4e77-979b-5d7022f5a60a.png)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8973282/Player.log)

**Comment by Uncle-Ulty** [comment]
> @Uncle-Ulty Hi, does it happen on every world? Does it happen on a blank one? Also what are the start and end value, is it a smooth gradual drop like PopkaAkula is mentioning or is it some drop from time to time? Thanks

yes, and it also happens in a new world... and it seems when the fps reach a very low level, the game crashes.

![image](https://user-images.githubusercontent.com/73253472/175467230-46a31f7c-5379-4e3e-83a5-2f0bf380a08a.png)

**Comment by tsunamayo** [comment]
@Uncle-Ulty So I spotted in another world with a lot more children entity. I fixed the issue, it is now live in 22w25b. Thanks for being quick in reporting that one!
