### ISSUE TITLE
[MULTIPLAYER CONNECTION ISSUE] Crashing while connect to friend

### ISSUE THREAD

**Issue by Slyreus** [tsunamayo/Starship-EVO#4756]
### Short Description of the issue:

I'm having trouble connecting to a friend.
When we try with the host IPv4, I have this attached screen then the closing of the game. ![crash](https://user-images.githubusercontent.com/24406610/175699157-e43aceb7-6790-40b7-80b6-ae92e8f85647.png)
We tested both ways.
Ports 7777 are open, and on both sides, the firewall is also open. ![port](https://user-images.githubusercontent.com/24406610/175699161-67aee907-673e-4353-b144-70b948778a00.PNG)
No anti-virus.
Multiplayer was open.

### Steps to reproduce the issue:

We followed steps described at this [address ](https://starshipevo.fandom.com/wiki/Multiplayer)

### Environment

- Starship EVO version: early-access 22w25b
- Graphics Card: NVIDIA GeForce GTX 970

### Additional information:

[Crash_2022-06-24_213827018.zip](https://github.com/tsunamayo/Starship-EVO/files/8981698/Crash_2022-06-24_213827018.zip) 
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8981700/Player.log)

**Comment by tsunamayo** [comment]
@Slyreus Hi, thanks a lot for reporting the issue, and sending me the log and crash dump.
I will investigate and keep you posted!
Francois

**Comment by Briaireous** [comment]
i too am crashing when trying to join TwoNiner for laidai builds

**Comment by TwoNiner29** [comment]
> @Slyreus Hi, thanks a lot for reporting the issue, and sending me the log and crash dump.
> I will investigate and keep you posted!
> Francois

Hey tsuna, I know you’re probably busy with other stuff, but a few players and I would appreciate if you could get multiplayer back soon. We do a lot of multiplayer building and this update has stopped our group projects. 

Perhaps we could have a multiplayer stable version as well incase this happens in future?

**Comment by Korbalt83** [comment]
Hi,

Me and my friend have exactly the same problem.

**Comment by tsunamayo** [comment]
@Slyreus @TwoNiner29  Hi, sorry yes I was trapped into the crafting #1 update. It was fixed a few ago. Yes I will do a specific branch for mp. Thanks!
