### ISSUE TITLE
[Bug] Placing more than one fuel tank makes other tanks invisible.

### ISSUE THREAD

**Issue by TheWanderer05** [tsunamayo/Starship-EVO#4760]
### Short Description of the issue:
When placing fuel tanks on a ship, placing more than one fuel tank on the same grid will make other fuel tanks invisible. The only visible fuel tank is the last one placed. All types of fuel tanks cause this issue, and it does not matter if symmetry is enabled or disabled. Deleting tanks does not make previously placed tanks reappear, and sometimes leaves floating black textures if the cylindrical tank is used . When placing two tanks that are different, e.g. one cubic tank and one pipe tank, both will become invisible.
...

### Steps to reproduce the issue:
To reproduce the main issue:
1) Start building a vessel. Place one fuel tank of any type on the ship.
2) Place another fuel tank. The first tank will become invisible.
3) Delete one of the fuel tanks. The other will become invisible, regardless of the order of which it was placed.

To reproduce the floating black texture issue:
1) Place one cylindrical fuel tank. Place another. One will be invisible.
2) Delete one or both of the fuel tanks. Floating black textures should appear where one of the tanks was.
...

### Environment
- Starship EVO version: 22w25b
- Graphics Card: EVGA Geforce RTX 3070

### Additional information:

Screenshots of issue:

1. Invisible fuel tank with outline next to second, visible fuel tank.
![image](https://user-images.githubusercontent.com/37814712/176039704-709fd015-1a96-4a5f-bd53-6dd2ad98a662.png)

2. Invisible fuel tank after first fuel tank is deleted.
![image](https://user-images.githubusercontent.com/37814712/176039749-bd14d385-2434-47c0-b88d-315929bf4dd6.png)

3. Floating black textures after cylindrical tanks are deleted.
![image](https://user-images.githubusercontent.com/37814712/176039823-d0b7f6ea-f71a-47ce-97d1-2bcf6e808742.png)

Player Log file:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8995771/Player.log)

Relevant ship blueprint:
[Light Fighter 1 INCOMPLETE.zip](https://github.com/tsunamayo/Starship-EVO/files/8995764/Light.Fighter.1.INCOMPLETE.zip)

**Comment by tsunamayo** [comment]
@TheWanderer05 Hi, thanks for booking the case. I cant reproduce unfortunately.
Do you reproduce right away after a fresh load, or is after having played a while? 
Thanks

**Comment by TheWanderer05** [comment]
> @TheWanderer05 Hi, thanks for booking the case. I cant reproduce unfortunately. Do you reproduce right away after a fresh load, or is after having played a while? Thanks

@tsunamayo Hello, I launched the game a few minutes ago and tried to reproduce the issue and found something that may help. I've had the game open for 3 minutes. While trying to reproduce the bug by placing multiple fuel tanks, the bug did not occur again. However, when I placed two reactors with symmetry after placing the main fuel tank (cubic), the fuel tank became invisible, as seen in the first image below. When placing more reactors on the wall between the fuel tank and the flight computer, the wall became invisible, as seen in the second image. The fuel tank is also still invisible. Reloading the save appears to have solved the problem for now, as I am unable to reproduce this. I'll write more if I find anything else.

![image](https://user-images.githubusercontent.com/37814712/176197123-9e5f30db-c7d1-44e0-b001-d7eaa19483f7.png)

![image](https://user-images.githubusercontent.com/37814712/176197563-ceacfcc7-4ae5-42ab-bacc-499e1de01b35.png)


Here is the log file:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/9001745/Player.log)

**Comment by tsunamayo** [comment]
@TheWanderer05 Hi, thanks for the further details. Unfortunately I still cant reproduce! Could you tell me if you can reproduce after a game start straight away? Or does it seems a bit more random (in which case it might be linked to previous block added or deleted). 
Thanks!

**Comment by TheWanderer05** [comment]
@tsunamayo Hello, I tried to reproduce the bugs today with a new game start and the previous one, but I am also unable to reproduce them as of now. I can post an update here if anything happens again, but hopefully that doesn't happen.

**Comment by tsunamayo** [comment]
@TheWanderer05 So I was able to reproduce, it was linked to transparent pipe. Fixed for 22w31a. Thanks!
