### ISSUE TITLE
Crash when trying to join a multiplayer game

### ISSUE THREAD

**Issue by Ebbakatten** [tsunamayo/Starship-EVO#4761]
### Short Description of the issue:
Crash when trying to join a friend (multiplayer)
I've double checked so that my ports are open.
...

### Steps to reproduce the issue:
1.Start the game
2.Join a friend
3.Crash to desktop (In loading screen)
...

### Environment
- Starship EVO version: 22w25b
- Graphics Card: RTX 2070 Super

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/9031832/Player.log)

**Comment by schlid** [comment]
Also happens to me too :)

**Comment by tsunamayo** [comment]
@Ebbakatten Hi, multiplayer should now be fixed in Default. Thanks!
