### ISSUE TITLE
Crash/Soft Lock on placing Starter Block

### ISSUE THREAD

**Issue by kynamats** [tsunamayo/Starship-EVO#4763]
### Short Description of the issue:
My world has crashed in the exact same way twice when placing a starter block - this almost softlocks the PC, making starship evo the only thing on screen regardless of the active window. the only workaround is to win+tab and send the sevo window to a new desktop, then shut it down in task manager.
Never had this issue before - I've even been using the starter block in the past few hours, with no issues up to now.
+Update: This crash replaced the prefab I had in the 5th slot of my 2nd hotbar with a station module? tested after removing this from the hotbar - still crashes in the same way.
...

### Steps to reproduce the issue:
Load the included world, place a starter block.
...

### Environment
- Starship EVO version: 22w25b
- Graphics Card: 3070ti

### Additional information:

[W014.zip](https://github.com/tsunamayo/Starship-EVO/files/9034749/W014.zip)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/9034752/Player-prev.log)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/9034753/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by kynamats** [comment]
Update 2 - after working on these same blueprints again for a while in a different world, i've had some really strange crashing behaviour that seems to be triggered by character movement. this seems to be intrinsic to the world/character save as well so i've included it, and the relevant logs, here:
[W015.zip](https://github.com/tsunamayo/Starship-EVO/files/9066126/W015.zip)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/9066128/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/9066129/Player-prev.log)
.

**Comment by cyberjasse** [comment]
I experienced the same crash systematically when placing a starter block in my world. it also happened after I placed a prefab from the Steam workshop. I fixed my save by deleting all inventory bars then quitted the game and unsuscribe to all subscribed article for sevo in Steam workshop . I don't know if deleting inventory bars was necessary . I can try to reproduce it when I have time

**Comment by cyberjasse** [comment]
I experienced the same crash systematically when placing a starter block in my world. it also happened after I placed a prefab from the Steam workshop. I fixed my save by deleting . Version 22w30c

**Comment by cyberjasse** [comment]
This bug is probably fixed in the new build : https://github.com/tsunamayo/Starship-EVO/issues/4824

**Comment by tsunamayo** [comment]
I Think this should have been fixed! Thanks
