### ISSUE TITLE
[suggestion] Turret mode: on/off and auto turret for repair and mining

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#4765]
I think there should be a way to turn on and off any turret, manual turret or automatic turret.

What does it mean? There should be a way to force the turret to cease attack and return to its resting position, even when controlling the ship and under enemy attack, with this "forcing" rest position.  It would be possible to put the turret in a position that you can use it to conceal de turret inside the hull.

I tried to make a ship with several concealed turrets in the past, but they keep tracking the enemy even when they are inside the ship, and this behavior can result in some mechanism jamming. Also, sometimes the turret keeps firing from inside the ship, even in concealed mode.

Also, I bought Elite Dangerous in the summer sale ( I played it for research purposes since it seems this game influences Starship Evo a lot), and I loved the idea of a "hardpoints" setup, where you can change your weapons/tools and etc. And most of these tools and weapons are mounted on turrets, concealed inside the ship. I'd love to be able to reproduce the same mechanism in starship evo, and it's probably very easy to implement. But in order to work, these turrets cannot be allowed to move/track targets once inside the ship.

I think a link signal into the turret computer is enough to make this idea work.

no input link on turret computer = turret on (it can move and shot)
input link: 0ff = turret off
input link on = turret on

Also, we have an "auto" option for weaponized turrets, and it targets the enemies... is it possible to make an "auto" turret for repairing and mining? An auto turret to repair would target damaged objects/ships/builds and so on. An auto mining turret would target the nearest ore vein.

**Comment by nokturnihs** [comment]
Love the idea.

**Comment by nokturnihs** [comment]
One other comment, we'll need a way for those autoturrets to have a friend/foe detection system, so maybe a faction block where you can edit what factions are friendly/neutral/enemy. Basically a toggle of friend/foe in the block that you link to the turret or link to an input link to disengage friendly fire control in the case of betrayal or whatever. If you set up factions for "as found" so it autopopulates that computer database should be easy enough. Basically what the starmade faction block does but with a little more flexibility.

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hi, finally there for 24w42a... I hope you are doing good, take care!

**Comment by Uncle-Ulty** [comment]
Great news, Tsuna! Also, the range configuration, that's great!

I need to continue my old projects in stevo :D

cheers!

**Comment by tsunamayo** [comment]
@Uncle-Ulty Thanks, well if you are up to it I will need some community made build as I am resuming work on faction / stations and so on. I will need a traders ship for example... Cheers

**Comment by Uncle-Ulty** [comment]
> @Uncle-Ulty Thanks, well if you are up to it I will need some community made build as I am resuming work on faction / stations and so on. I will need a traders ship for example... Cheers

Count on me!!!

I sent you a sample of trader ship 2 years ago, do you remember? I don't know If It needs some adjustments.


https://steamcommunity.com/sharedfiles/filedetails/?id=2923603425

https://steamcommunity.com/sharedfiles/filedetails/?id=2923603702

Also, I wrote a piece of lore about my "faction" some time ago.

ping me if you need me! Also, I'm using "Admiral Fray" nick in steam!

CHEERS!
