### ISSUE TITLE
[BUG] Shipyard Zone size issues

### ISSUE THREAD

**Issue by Asnro** [tsunamayo/Starship-EVO#4769]
### Short Description of the issue:

The Shipyard zone needs to be larger in *both* length and width than the landing ship's longest side (see pictures)

### Steps to reproduce the issue:

- Create shipyard
- Adjust size
- Try to land

### Environment
- Starship EVO version: 22w25b
- Graphics Card: RTX 3070

### Additional information:

![kuva](https://user-images.githubusercontent.com/14952174/178549985-98d2c8bf-cfae-4c8b-832b-c6cc094b43a6.png)
Shipyard 40m wide, 50m ship can't land

![kuva](https://user-images.githubusercontent.com/14952174/178550046-c50d23d1-d3e4-4752-b8e6-2197511bde50.png)
Shipyard 60m wide, 50m ship can land

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Player.zip](https://github.com/tsunamayo/Starship-EVO/files/9095268/Player.zip)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Asnro I see, indeed I look at the max dimension and see if it fit. I will try to improve the logic, I keep you posted. Thanks

**Comment by tsunamayo** [comment]
@Asnro Bug is fixed for 22w45a. Thanks
