### ISSUE TITLE
Cut Tool? Combo copy & delete tools

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#4772]
We have the copy/past tool and the region delete tool with function on the same principle of drag a square region. Could it be possible to combine the two into a cut tool? Copies a region and deletes the old.

**Comment by tsunamayo** [comment]
Hum in the sake of simplicity I think I prefer to keep it like this, I dont think this should be used at a high frequency enough to make justifiable. Cheers
