### ISSUE TITLE
[Bug] Mirroring issues

### ISSUE THREAD

**Issue by HigureKomori** [tsunamayo/Starship-EVO#4776]
### Short Description of the issue:

Larger grid blocks dont mirror

### Steps to reproduce the issue:

havent tested other girds but 32 grid blocks dont mirror so set your block to the highest and mirror

**Comment by tsunamayo** [comment]
@HigureKomori Hi, thanks for booking the bug.
I cant reproduce unfortunately, it is working fine on my side.
Could you give me more details? What version are you using?
Thanks

**Comment by HigureKomori** [comment]
i think it was jsut a me issue i eventually got it to work again

**Comment by tsunamayo** [comment]
@HigureKomori Okay thanks good to know.
