### ISSUE TITLE
[bug] Conveyor belt move direction

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#4781]
### Short Description of the issue:
The game shows the conveyor moving in one direction, but it's in fact moving in the opposite direction.

In the current escalator (video below), the conveyor animation shows it moving down when the conveyor is in fact moving up.

...

### Environment
- Starship EVO version: 22w301
- Graphics Card: gtx 1660

### Additional information:

https://user-images.githubusercontent.com/73253472/181850341-2f7a45c8-f1fa-4636-8b0f-0a03bafcc23e.mp4

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/9223481/Player.log)
[craft and more.zip](https://github.com/tsunamayo/Starship-EVO/files/9223484/craft.and.more.zip)

**Comment by tsunamayo** [comment]
@Uncle-Ulty Indeed! It is fixed now. Thanks
