### ISSUE TITLE
[suggestion] Light dots on glowing tiles

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#4782]
Is it possible to remove these light dots that show when you use glowing tiles? this "round glowing effect" ruins ships at close. I know they look good at far distances, but up close it doesn't make much sense and looks ugly. 

I think the best solution would be to make they appear only at great distances (5km~10km)

![image](https://user-images.githubusercontent.com/73253472/181852754-6984e8d9-6d6d-47b8-9487-addb61f5ac84.png)

**Comment by PopkaAkula** [comment]
Yea the effect is really exaggerated at times, it would be better to have it fade in more gradually.

To piggyback off of this, it would also look better if the long distance glow wasn't just a dot but would display across the whole length of the glow brick.

**Comment by Uncle-Ulty** [comment]
It makes sense, but at great distances (1km~5km), a glowing point or a stretched glow in a 1~4m brick won't make much difference I guess. But, if you are using a 32m glowing brick, yeah, it makes total sense to have a stretched glowing (a sample below).




![image](https://user-images.githubusercontent.com/73253472/181925948-2d854b8d-7286-466e-aaa8-8e7d10d5166b.png)

**Comment by tsunamayo** [comment]
@Uncle-Ulty Okay I will try to tweak it further. The problem is that you use them in a very specific way it seems. Can you send me the bp?
Also I remember your warp gate (I still need to work on that!) Amazing design, but I think we will need to tone down the glow a bit to not be too taxing on the eyes! 
Cheers

**Comment by Uncle-Ulty** [comment]
> @Uncle-Ulty Okay I will try to tweak it further. The problem is that you use them in a very specific way it seems. Can you send me the bp? Also I remember your warp gate (I still need to work on that!) Amazing design, but I think we will need to tone down the glow a bit to not be too taxing on the eyes! Cheers

Gonna send it asap. About the Stargate, I toned it down and sent it again. But don't worry, gonna send it too!

**Comment by Uncle-Ulty** [comment]
build with glowing tile:
[TEC - Magnificente Fighter.zip](https://github.com/tsunamayo/Starship-EVO/files/9230486/TEC.-.Magnificente.Fighter.zip)

toned down warp gate:
[TEC - Travessia Stargate v2.zip](https://github.com/tsunamayo/Starship-EVO/files/9230487/TEC.-.Travessia.Stargate.v2.zip)

**Comment by tsunamayo** [comment]
@Uncle-Ulty Okay so I toned down the effect, fixed the transition and added a normal check. It looks better now.
Cheers

**Comment by Uncle-Ulty** [comment]
Thanks!
