### ISSUE TITLE
[suggestion] dedicated BETA version for Multiplayer

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#4784]
Hi Tsuna!

I see a recurrent complaint in the SEVO community and steam downvotes reviews: lack or unstable multiplayer mode.

I understand you have lots of work coding the game, and that multiplayer isn't so important atm. But, a good evaluation in steam and a "content" to keep the players busy are also important in this early access stage.

So, I think it would be advisable to have a constant BETA version dedicated to multiplayer only. This version wouldn't require frequent updates, and this could ensure stability. 
The dedicated version would cause no further compatibility and stability problems, in the standard version and/or the experimental version for multiplayer games. It would keep everyone happy playing with friends and would avoid further bad reviews on steam.

I don't play on multiplayer in SEVO, but I'm noticing lots of complaints about it recently.

ps: recently, Fromsoft turned off multiplayer servers for all games but Elden Ring, and that annoyed lots of soulsborne players (me included), which resulted in several bad reviews on steam. To play a darksouls remaster without co-op? kinda frustrating... also a nightmare...

![image](https://user-images.githubusercontent.com/73253472/181941775-345d8ebc-2e50-4642-ac8d-f85497da5a67.png)

**Comment by Vincent14** [comment]
Hi, I strongly agree with this issue: the Steam page assert the multiplayer experience is part of the game. But it's still unstable, lack of a proper dedicated server executable that could be used to have a community server list, or just to start playing with friends.

Short story: I'm exploring this kind of games and really search for a multiplayer experience in priority. My goal is to play from coop up to 50 players on a french No Man's Sky community already frustrated by the multiplayer experience of this game. There isn't a real sandbox game (allowing base building, ship building and so on, with blueprints etc) on this style of games, and we would really appreciate to be able to play Starship Evo as it would be possible on a regular minecraft server for example. You can meet us if needed to have some feedbacks of our expectations, it could help to brainstorm about the multiplayer feature (just ask on this thread if so).

Thanks to care about multiplayer, even if it's not for a short time period!

**Comment by Vincent14** [comment]
This issue could be linked to https://github.com/tsunamayo/Starship-EVO/issues/2795

**Comment by tsunamayo** [comment]
@Uncle-Ulty I think it should be better in default now.I get bad review because people need to port forward, so I guess having to change version wont help my case either.  I just need to check more carefully basic connection issue. 
@Vincent14 Okay merci, je te poserai surement quelque questions si tu es d accord.

**Comment by Vincent14** [comment]
Avec plaisir ! : )
