### ISSUE TITLE
Proposed change to the Fuel System

### ISSUE THREAD

**Issue by tsunamayo** [tsunamayo/Starship-EVO#4787]
So following the conveyor update I am now in a position to do a paradigm change to the fuel system by simply using the conveyor logic.
I think a few of you found the current fuel logic a bit hard to grasp, so I have been thinking about this switch.
I still need to go deeper to see any other potential drawbacks but the idea has been growing on me, slowing reaching the point where I am thinking, f*** I should have started with conveyor first (it went quite smoother to implement)

Here are the main difference:

**Current fuel logic: the equilibrium paradigm:**
-  Tank and pipe forms equilibrium, they will exchange their fuel in order to reach the same level of % fill, to make sure that [Reactor = Tank 1 = Tank 2] design are also emptying Tank 2.
- The logic only examine each pipe and tank locally, trying to make an equilibrium (or feeding a reactor) with their immediate adjacent neighbor.
- It means that fuel is actually physically transported in pipe.

**Proposed and Conveyor logic; the pull and push paradigm**
- In this model request are completed instantly, as the conveyor link chain is unrolled on the go. 
- It means there is never really something inside a conveyor pipe.
- The fuel system would simply do a conveyor like request on a bigger amount of fuel, say 10% of its capacity every second or so (as doing it every frame would make the game lag).
- 6 way to  6-way is working, as is tank to tank as long as each tank has 6 connection max!

Now the minus of this system is that it looks less natural and less fluid, but it might actually be easier to understand and design for.
Transparent pipe would have to work differently, but I can still convey the information that fuel has been transferred (like for conveyor). 
One big plus is that it would make multi-fuel much easier to manage. Each tank would be able to store several type of fuel. Okay it is far less realistic, but multi-fuel with the current system seems too hard from a player interaction and design perspective.
Another plus for me: while it would take me a bit of time to do the switch (not the end of the world though), as I would only have to maintain and improve one code so it would actually be faster long term.

Tell me what you guys thing of it!

Ps: I still need to work on children entity and docking port.

**Comment by Asnro** [comment]
Would thruster-to-thruster/reactor-to-reactor connections work? My one complaint with the proposed system would be the 6-connection limit, but that would be a moot point if I needed fewer connections from tanks to thrusters/reactors.

**Comment by Zouzeug** [comment]
Franchement , je pense que la décision te reviens , je joue énormément et uniquement a stevo et je ne crois pas que le changement que tu veux instaurer bouleverserai complètement la conception qui est tant amusante dans ce jeu . 
Ce que je veux dire , c'est que si cela représente une meilleure base pour toi , en avant .

**Comment by kynamats** [comment]
I think we're still early enough in fuel for you to do what you like with the system, although I do like how the equilibrium mode is analogous to real fluids. I'm a bit torn about the concept of having multiple fuels in a single tank as it feels very un-intuitive to me, but that could be changed quite easily with nomenclature - just call the new fuel types 'additives' rather than them being a fundamentally different fuel - this makes more sense with a reactor, for example, as one would expect a reactor to only be able to use one type of fuel.
I would ask that any changes take the existing balance into mind, so as to minimise re-designs... but we still need lower consumption, or some other way to power smaller craft in particular (batteries?)

**Comment by Womble-TC** [comment]
I agree with kynamats, since we are pretty early on with fuel and system development, its difficult to really say if mixing fuel in tanks is a good or bad thing in terms of gameplay. It could be a good incentive to use valves/filters to prevent certain fuels going to certain tanks/systems.

**Comment by ZachZent** [comment]
I don't have any comments about the fuel system itself, but I think it would be helpful to get the general pathways of how fuel works on paper as it will. What requires fuel, what doesn't. Do engines require fuel and if so which types? The reactor, does it require fuel? How will fuel (conceptually) work on planets versus space given how the former doesn't have gas clouds to suck up (hint hint, geothermal ;) ). What if reactors or engines are spread around the ship? Does each need a fuel hookup if they do? What about those one CEs? does each CE need basically an independent system? 

I'd recommend mapping it out on a flow chart or something. Besides answering many questions about fuel system, it may help with your question here.

_______________

Also as an aside, especially for the question about multiple reactors/engines, I really recommend a new "core" block, or better named a "controller" block. This doesn't remove the need to place many reactor blocks, but rather gives a centralized place for such to be controlled. Needing to pipe fuel to ever cluster of reactors could be rather annoying since most are scattered around the ship by default. Maybe with a "controller" block, fuel can be pumped into the single point vastly simplifying the system. Or if not, it is still helpful for configuration and control, for example switching between different fuel types

Bonus, can work as a place to target and if destroyed, the entire system goes off line.

**Comment by pinesh** [comment]
I like the idea. While you've addressed several of the bugs affecting how fuel was getting through longer networks, a strongly typed link chain sounds far more robust.

**Comment by Kadzar** [comment]
When you brought out the new conveyor system, I was actually thinking of asking if some of its functionality could be applied to fuel, so I think I'm in favor of this!

I guess it's more realistic to have fluids try to reach an equilibrium, but I didn't even realize this was how the current system works, and isn't really how I'd been trying to design fuel systems in the ships I've worked on since fuel was added, having more of an approach of pumping it from place to place, so I feel like the proposed new system would work out much better for me, personally.

I will say that I do, however, feel a little weird about the concept of pulling multiple individual fluids from the same container unless there's a good explanation for it (filters, different densities, distillation, etc.)

**Comment by Dwarf-LordPangolin** [comment]
My initial thoughts are that I _**really**_ like the pull-push system. It sounds like it would simplify the game's code for development, probably be more performance friendly (I can't imagine that having _every_ tank and pipe checking its neighbor is convenient), and would be a bit more intuitive for players.

I can understand the appeal of a more realistic method of simulating fluid movement to some players, but I don't think that a majority are going to want that kind of accuracy; most probably just want the fuel to get where it needs to go automatically as long as the pipes are connected.

I agree with Asnro that it would be a big quality of life feature if fuel could travel through system blocks. It would make building a lot simpler, and as they point out it would make the 6-connection limit less of a problem.

I agree with Zach that a diagram or chart of precisely how the fuel system is meant to work would help us in giving better feedback.

The "multiple fuel types in one tank" aspect could mess with immersion a little bit, but it's not that hard to handwave; maybe the tank has internal divisions within it. Split fuel tanks are [apparently a thing IRL](http://convault.com/Content/images/multi-compartment-2.jpg). Ditto for pipes; what _looks_ like a single pipe could arguably be multiple pipes enclosed within a single protective cover. In a setting with teleporters, that is honestly not something that bothers me much.

**Comment by tsunamayo** [comment]
> I don't have any comments about the fuel system itself, but I think it would be helpful to get the general pathways of how fuel works on paper as it will. What requires fuel, what doesn't. Do engines require fuel and if so which types? The reactor, does it require fuel? How will fuel (conceptually) work on planets versus space given how the former doesn't have gas clouds to suck up (hint hint, geothermal ;) ). What if reactors or engines are spread around the ship? Does each need a fuel hookup if they do? What about those on CEs? Does each CE need basically an independent system?
> 
> I'd recommend mapping it out on a flow chart or something. Besides answering many questions about fuel system, it may help with your question here.
> 
> Also as an aside, especially for the question about multiple reactors/engines, I really recommend a new "core" block, or better named a "controller" block. This doesn't remove the need to place many reactor blocks, but rather gives a centralized place for such to be controlled. Needing to pipe fuel to ever cluster of reactors could be rather annoying since most are scattered around the ship by default. Maybe with a "controller" block, fuel can be pumped into the single point vastly simplifying the system. Or if not, it is still helpful for configuration and control, for example switching between different fuel types
> 
> Bonus, can work as a place to target and if destroyed, the entire system goes off line.

Not sure what I am supposed to write on that chart ^^ ([Lightcruise Engine] == [Tank] == [Reactor] ?)
Anyway the things that require fuel for now are Lightcruise Engine and Reactor. The smaller thruster wont require fuel.
That being said I am considering to extend that to weapons for example, to replace the current addon system as people are not happy with it.
A weapon would have different buff depending on the fuel used - it would have more synergy for survival.
A controller dont really make sense tbh, it kinda defeat the purpose of having fuel and piping.
I will add the ability to link a pipe/tube to a mechanism in order to give fuel or items to Children Entities.
Thanks

**Comment by tsunamayo** [comment]
> Would thruster-to-thruster/reactor-to-reactor connections work? My one complaint with the proposed system would be the 6-connection limit, but that would be a moot point if I needed fewer connections from tanks to thrusters/reactors.

Yes that could work, although if you get over the 6 limit things get random (ie you might get a different result after a blueprint load on which connection works and which does not)

**Comment by tsunamayo** [comment]
> I think we're still early enough in fuel for you to do what you like with the system, although I do like how the equilibrium mode is analogous to real fluids. I'm a bit torn about the concept of having multiple fuels in a single tank as it feels very un-intuitive to me, but that could be changed quite easily with nomenclature - just call the new fuel types 'additives' rather than them being a fundamentally different fuel - this makes more sense with a reactor, for example, as one would expect a reactor to only be able to use one type of fuel. I would ask that any changes take the existing balance into mind, so as to minimise re-designs... but we still need lower consumption, or some other way to power smaller craft in particular (batteries?)

So the change should not break any design. It should give you the same result, except that instead of emptying all connected tank at once, it will empty them in sequence.
As for multi-fuel, it means that tank would be like cargo, you open them and see what fuels are inside. I could force them to only accept a single fuel though, it would still be easier compared to the current method as you could share pipe route between tank of different fuel.
Reactor / engine would like only burn a single type of fuel at a given time.

**Comment by ZachZent** [comment]
- I was thinking something like this, but better going over each possible case. Like if there are two segments of reactors. Will each need piping, that sort of thing. But it sounds simple enough.
![image](https://user-images.githubusercontent.com/36980446/182524069-9e155d07-8fcc-42c2-8d4f-f0a42a5a39d3.png)

- Fuel for weapons sounds kind of strange honestly. Or even just weapon effects. As a crafting recipe maybe, but that should probably go though a different post

- Understood that fuel going through a controller would be a little simplified. However I still must highly recommend a controller block, similar to a ship core. Something you can interface with/link to be interfaced to more easily use the fuel transfer, or "calibrate" engines, or like a weapon's controller, shields, life support. Think the enterprise bridge with each console controlling one aspect. As much as I like the valves and such, it is a bit impractical to be constantly opening and closing pipes. And as stated, they can be a specific target to disable that entire system if destroyed versus needing to whittle down reactors one group at a time making it a major combat element.

**Comment by tsunamayo** [comment]
> My initial thoughts are that I _**really**_ like the pull-push system. It sounds like it would simplify the game's code for development, probably be more performance friendly (I can't imagine that having _every_ tank and pipe checking its neighbor is convenient), and would be a bit more intuitive for players.
> 
> I can understand the appeal of a more realistic method of simulating fluid movement to some players, but I don't think that a majority are going to want that kind of accuracy; most probably just want the fuel to get where it needs to go automatically as long as the pipes are connected.
> 
> I agree with Asnro that it would be a big quality of life feature if fuel could travel through system blocks. It would make building a lot simpler, and as they point out it would make the 6-connection limit less of a problem.
> 
> I agree with Zach that a diagram or chart of precisely how the fuel system is meant to work would help us in giving better feedback.
> 
> The "multiple fuel types in one tank" aspect could mess with immersion a little bit, but it's not that hard to handwave; maybe the tank has internal divisions within it. Split fuel tanks are [apparently a thing IRL](http://convault.com/Content/images/multi-compartment-2.jpg). Ditto for pipes; what _looks_ like a single pipe could arguably be multiple pipes enclosed within a single protective cover. In a setting with teleporters, that is honestly not something that bothers me much.

Thanks, I didnt knew it existed! Even if I dont allow multi-fuel tanks you could still share the same piping route (as there is really no fuel in pipe), making design a lot easier.
My worry was for example: you stumble unto a cloud of fuel A. How are you supposed to harvest it with the current system? Maybe have another tank and another route, and do some on the fly setting for the harvester? Seems like a nightmare to me.
With multi-fuel you dont really need to worry about this.

Yes it the new system fuel could traverse other system as they would be considered as pipe.

**Comment by tsunamayo** [comment]
@pinesh Well the current system has the advantage of scaling well, it will always be proportional to the number of pipe in the game, not how complex each chain is.
With the new system on the other side, you could create a massive loop, with tons of system requesting fuel, and get bad performance. It is hard to compare.

**Comment by pinesh** [comment]
> @pinesh Well the current system has the advantage of scaling well, it will always be proportional to the number of pipe in the game, not how complex each chain is.
> With the new system on the other side, you could create a massive loop, with tons of system requesting fuel, and get bad performance. It is hard to compare, I think for a normal use the request system will be faster, but can get worse for massive one.

It’s starting to sound like a big ole networking problem!

My graph theory isn’t as good as it should be, but I’m sure there’s a good way to lay out and service all those potential nodes !

**Comment by tsunamayo** [comment]
@pinesh well I am also supposed to have studied that back in the day, for now I do something quite simple, I visit every node, stop when the first valid is found. I only keep a stack of nodes with entries > 2 to not revisit them. Pretty brute force.

If perf is an issue I could always simply bake those loop and keep a linked list of all containers (excluding pipe). But has a few drawback (you might ping far away containers first for example).

**Comment by pinesh** [comment]
> @pinesh well I am also supposed to have studied that back in the day, for now I do something quite simple, I visit every node, stop when the first valid is found. I only keep a stack of nodes with entries > 2 to not revisit them. Pretty brute force.
> 
> If perf is an issue I could always simply bake those loop and keep a linked list of all containers (excluding pipe). But has a few drawback (you might ping far away containers first for example).

Push-pull connections and pinging far away containers, it's starting to sound like you're describing a weighted directed graph!
If that's the case, you might be able to handle this very efficiently.

Thank's for sharing some of your pseudocode! Always great to get some insight under the hood!

**Comment by tsunamayo** [comment]
So I have done the change as discussed. Thanks a lot!
