### ISSUE TITLE
shadow bug w/ any tool out

### ISSUE THREAD

**Issue by ChromeMeme** [tsunamayo/Starship-EVO#4788]
### Short Description of the issue:
shadows only show up when any tool is out (might have to do with the tool model being out
also severely degrades performance when the shadows do show up w my 1650 ti bringing in 120 fps without the shadows and 80 with
### Steps to reproduce the issue:
unsure. This happened after getting into the tutorial ship(or at least when i realized) and persists after game restarts so it may just always happen
...

### Environment
- Starship EVO version: 22w30b (latest)
- Graphics Card: gtx 1650 ti (mobile)

### Additional information:
one image with the tool and shadows and one without. seems to effect shadows for the entire station from afar as well
![20220802033807_1](https://user-images.githubusercontent.com/110463622/182355596-caafea2a-8c3a-41fd-b901-aade5eea353f.jpg)

![20220802033811_1](https://user-images.githubusercontent.com/110463622/182355600-18673e7b-4ea9-446b-a030-77f5c44305d2.jpg)

here is another comparison in a brand new world w/ new character
![20220802034642_1](https://user-images.githubusercontent.com/110463622/182356934-e2f25722-ac93-4d72-9820-1f59245a004c.jpg)
![20220802034640_1](https://user-images.githubusercontent.com/110463622/182356940-95fd0003-285c-411a-b418-0a19f6c6f73c.jpg)

player log:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/9241415/Player.log)

**Comment by ChromeMeme** [comment]
feel free to let me know if you need more screenshots or if I missed any additional information that I should put

**Comment by tsunamayo** [comment]
@ChromeMeme Thanks a lot, I have just fixed the bug and repushed it as 22w30b. Thanks
