### ISSUE TITLE
Conveyor Tubes can't clip

### ISSUE THREAD

**Issue by Asnro** [tsunamayo/Starship-EVO#4789]
### Short Description of the issue:

Conveyor tubes cannot be clipped into blocks like fuel pipes can be.

### Steps to reproduce the issue:

Attempt to place conveyor tube clipping into a block

### Environment
- Starship EVO version: 22w30b
- Graphics Card: RTX 3070

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Player.zip](https://github.com/tsunamayo/Starship-EVO/files/9242204/Player.zip)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Asnro Yes I havent implemented it yet, I will add it though.

**Comment by tsunamayo** [comment]
@Asnro it is now implemented. Thanks!
