### ISSUE TITLE
[Bug/Crash] Small ship clips into large ship

### ISSUE THREAD

**Issue by Asnro** [tsunamayo/Starship-EVO#4790]
### Short Description of the issue:

Small (10m) ship clips into large ship (2,4km). Landing does not work. Flying around inside lage ship and colliding into blocks caused crash to desktop.

### Steps to reproduce the issue:
- Spawn both included ships 
- Attempt to land Minnie on Cominus
- Abort landing and fly around inside Cominus until crash happens

### Environment
- Starship EVO version: 22w30b
- Graphics Card: RTX 3070

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Player.zip](https://github.com/tsunamayo/Starship-EVO/files/9242299/Player.zip)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

[GTS Cominus.zip](https://github.com/tsunamayo/Starship-EVO/files/9242305/GTS.Cominus.zip)
[GTS Minnie.zip](https://github.com/tsunamayo/Starship-EVO/files/9242307/GTS.Minnie.zip)

**Comment by tsunamayo** [comment]
@Asnro Hi, I have just repushed 22w30b3 with a fix concerning entity collisions. Could you check if you reproduce? Does it happens quickly? Thanks

**Comment by tsunamayo** [comment]
@Asnro Crash and clipping issue should be fixed. I am uploading the build 22w30c very soon. Thanks!
