### ISSUE TITLE
Multiple Crashes

### ISSUE THREAD

**Issue by Asnro** [tsunamayo/Starship-EVO#4791]
### Short Description of the issue:

Chrashes can occur as early as 5 minutes into session. Related seemingly mostly to logic and combat. Occurred with multiple different ships.

### Steps to reproduce the issue:

- Fiddle with logic
- Engage pirates in combat

### Environment
- Starship EVO version: 22w30b
- Graphics Card: RTX 3070

### Additional information:

[Crashes.zip](https://github.com/tsunamayo/Starship-EVO/files/9244413/Crashes.zip)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Asnro So I have just released a build, could you tell me if you still have issues (I have no pb on my side). Thanks

**Comment by Asnro** [comment]
> @Asnro So I have just released a build, could you tell me if you still have issues (I have no pb on my side). Thanks

Hi, I believe the crashes have been fixed, thank you!
