### ISSUE TITLE
Unable to move/ place blocks 22w30b [non-experimental branch]

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#4792]
Hi,

this is a strange one.

I made a short video clip of what I experienced, but here's the text form first:

I'm not in the experimental branch right now, and after getting into my current building char I started my normal routine for starting a game session - activating F1 and F3 menu settings that I prefer to run - after that I couldn't move in any way or form and I'm unable to place any blocks. However I'm able to open up the menus and while doing that, any movement input I gave before executed in that moment. I got teleported.

I can't get around it without restarting the whole game. 
The same thing happens in every other world/ char I made.
This does not happen until I opend the F3 menu!
The F1 menu works fine for me.

Save: 
[22w30b.zip](https://github.com/tsunamayo/Starship-EVO/files/9244837/22w30b.zip)

Player log:
[Player.zip](https://github.com/tsunamayo/Starship-EVO/files/9244833/Player.zip)

Video clip:
https://www.youtube.com/watch?v=wdw7gPbO5c8

**Comment by BigBadKangaroo** [comment]
Edit: After some further testing I found out that this bug only occures after I selected the option "disable NPC's"!
If I don't activate this option I can play just fine, but activating it will cause this bug!

**Comment by tsunamayo** [comment]
Okay thanks for the lead on the option, I will try to reproduce and keep you posted. Thanks

**Comment by tsunamayo** [comment]
@BigBadKangaroo I have just fixed the issue in 22w30b3. The build is already live.
Thanks for letting me now asap! I had to push the previous multi fix a bit in a hurry, and some bugs slipped through. I am going into several refactor on the item side for crafting. Tell me if you find anymore thing!
