### ISSUE TITLE
Random Crashes

### ISSUE THREAD

**Issue by Arutus** [tsunamayo/Starship-EVO#4793]
Game Crashes less than 1 minute regardless of world, not sure as to the cause but Its quite infuriating.

Specs 
RTX 2060 GPU
RYZEN 7 CPU

Here are the worlds
[dirt.zip](https://github.com/tsunamayo/Starship-EVO/files/9246793/dirt.zip)
[dirty.zip](https://github.com/tsunamayo/Starship-EVO/files/9246794/dirty.zip)

**Comment by Arutus** [comment]
[Player.zip](https://github.com/tsunamayo/Starship-EVO/files/9246896/Player.zip)

**Comment by tsunamayo** [comment]
@Arutus Hi, thanks for reporting this. Lets get this fixed asap!
Could you send me the content of 
* C:/Users/zionv/AppData/Local/Temp/Moonfire Entertainment/Starship EVO/Crashes

Thanks

**Comment by Arutus** [comment]
[Crashes.zip](https://github.com/tsunamayo/Starship-EVO/files/9246997/Crashes.zip)

**Comment by Arutus** [comment]
done

**Comment by tsunamayo** [comment]
@Arutus Thanks a lot, I am on it.

**Comment by tsunamayo** [comment]
@Arutus Hi, the crash should be fixed for 22w30c, I can now load your save fine. Are those ship/station yours? They are massive...
I will release this fix as soon as I fix a few more issues.
Cheers

**Comment by Arutus** [comment]
Yeah they are mine, part of a system project. Thanks for the fix
