### ISSUE TITLE
[Bug] Shipyard "Is Docked" Event Gate doesn't work

### ISSUE THREAD

**Issue by Asnro** [tsunamayo/Starship-EVO#4797]
### Short Description of the issue:

Event gate linked to shipyard block with "Is Docked" condition does not send logic signal when ship is landed on shipyard

### Steps to reproduce the issue:

- Link indicator light or other logic to event gate linked to shipyard block
- Land on shipyard

### Environment
- Starship EVO version: 22w30c (has persisted across multiple versions)
- Graphics Card: RTX 3070

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Player.zip](https://github.com/tsunamayo/Starship-EVO/files/9248114/Player.zip)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Asnro Issue will be fixed for 22w31a. Thanks!
