### ISSUE TITLE
Ship with Shipyard can target itself

### ISSUE THREAD

**Issue by Asnro** [tsunamayo/Starship-EVO#4798]
### Short Description of the issue:

Ship with shipyard block can target itself, which makes manual target selection (free look + R) impossible to use.

### Steps to reproduce the issue:

- Add shipyard block to ship
- Pilot ship and attempt to target things

### Environment
- Starship EVO version: 22w30c
- Graphics Card: RTX 3070

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Asnro Hi, was it working before? Thanks

**Comment by Asnro** [comment]
> @Asnro Hi, was it working before? Thanks

Hi, I don't recall it ever working differently.

**Comment by Asnro** [comment]
> > @Asnro Hi, was it working before? Thanks
> 
> Hi, I don't recall it ever working differently.

Now that I think about it I do recall this changed with the targeting overhaul - previously a ship could target its own individual shipyards, but that did not affect target selection.

**Comment by tsunamayo** [comment]
@Asnro Indeed, it is now fixed for 22w31a. Thanks!
