### ISSUE TITLE
Hovercraft keeps go up

### ISSUE THREAD

**Issue by cyberjasse** [tsunamayo/Starship-EVO#4801]
### Short Description of the issue:
I correctly made an hovercraft following tutorial on youtube. I can pilot it and it behaves like a hovercraft excepted that it doesnt stop going up. Also i cant break. I am on the habitat.

I tried to quit the game and reload it. I tried to save the blueprint, despawn and respawn it.
...

### Steps to reproduce the issue:

Join the habitat. Build that hovercraft (blueprint below), try to pilot it.

...

### Environment
- Starship EVO version: 22w30c The default branch
- Graphics Card: RTX 2070 super

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

The player.log file
[hoverKeepsGoUp_playerlog.log](https://github.com/tsunamayo/Starship-EVO/files/9262603/hoverKeepsGoUp_playerlog.log)

The blueprint of the hovercraft
[hoverWhoKeepGoUpBlueprint.zip](https://github.com/tsunamayo/Starship-EVO/files/9262604/hoverWhoKeepGoUpBlueprint.zip)

**Comment by cyberjasse** [comment]
I started a new world, joined the habitat, tried the hovercraft there and they work fine. I spawn mine and mine still going up. Looks like the problem is on my hovercraft only

**Comment by cyberjasse** [comment]
After a help from the community, the culprit was the starter block that disable gravity.

**Comment by ProPeach** [comment]
If you still see this Tsuna, it might be useful to have a popup message like the ones on the Ship core for lack of thrusters etc that checks to see if a Starter block is present when you enter a Yoke connected to a Hover computer and instructs you to remove it
