### ISSUE TITLE
Can no longer exit menus with [ESC] after state change

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#4803]
### Short Description of the issue:
Hiya, as per the title. noticed some change with how menus are left. Was this intentional? It doesn't seem to trigger unless leaving a menu unchanged
...

### Steps to reproduce the issue:
open the [F3] menu, and then pressing [ESC] after will close it. 
open the [F3] menu, change the fast move key setting and then try pressing [ESC], it won't do anything.

Same behavior with the codex, clicking on a block will prevent [ESC] from closing.
...

### Environment
- Starship EVO version: 22w30c
- Graphics Card: RTX 3080.

**Comment by cloudrambler** [comment]
I have seen the same new problem.

**Comment by tsunamayo** [comment]
@pinesh I see, yes I did some change to the ESC menu as I got a bad review mentioning a bug where you lost your input if you pressed ESC on a rotator for example. So now it exit the input first, then the rotator window. I guess my check also prevent those case for some reason, I will fix them.

**Comment by pinesh** [comment]
I always understood [ESC] to mean cancel, not just save and exit. I suppose that reviewer must’ve had a different train of thought.  Does that mean the X buttons now cancel the menu without saving? Or is there no way to undo a change now?

**Comment by tsunamayo** [comment]
@pinesh No X button will close the window, as ESC, it wont cancel anywthing. But pressing ESC while editing an input will cancel the input, not close the windows.
Issue is fixed, for 22w31a. Cheers
