### ISSUE TITLE
Handhelds spawn from starter block and vice versa

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#4806]
### Short Description of the issue:
Potentially unexpected behavior. 

depending on the order of interaction, workshop subscribed ship blueprints will appear in the item stand spawn screen, and handhelds can appear in the starter block screen. 
This can lead to some entertaining behavior with handheld-sized ships spawning.

![image](https://user-images.githubusercontent.com/14081996/183021281-c07a589e-c542-4241-a255-9bb281d6ae4b.png)
*Honey I shrunk the ship!*
...

### Steps to reproduce the issue:
Open a starter block on a new game boot. then try to open an item stand. 
Perform the inverse for the alt behavior. 
...

### Environment
- Starship EVO version: 22w30c
- Graphics Card: RTX 3080

**Comment by tsunamayo** [comment]
@pinesh Funny one indeed! Fixed for 22w31b. Thanks
