### ISSUE TITLE
Skywanderers site down. Propose git redirect to steam store page instead. 

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#4807]
### Short Description of the issue:
Looks like the skywanderers domain is down presently. 

Since there's two hyperlinks set to it on the main Readme. In the interest of not detracting from the experience of new visitors. they should be altered to go to the games store page instead as it contains a much better outline of the current game state, and is less likely to go down in the future. 
...

### Steps to reproduce the issue:
Attempt to navigate to the hyperlinks [Starship Evo] or [Main Website].
...

**Comment by tsunamayo** [comment]
Yes indeed

**Comment by tsunamayo** [comment]
Done! Thx

**Comment by SaphireLattice** [comment]
Still seems to be the issue? The site redirects to some generic spam/ad farm thing
