### ISSUE TITLE
22w30c - Placed blocks make previously placed blocks disappear randomly after attaching a translucent pipe to a fuel tank

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4808]
### Short Description of the issue:

It has been noticed that on the version 22w30c of the game player can make previously placed blocks disappear by placing a new block somewhere on a build after attaching a translucent pipe to a fuel tank.

This behavior occurs only towards the block which was placed previously.

Once a block becomes invisible, it stays invisible until being deleted.

### Steps to reproduce the issue:

1. Boot up the game
2. Load the save provided
3. Place a translucent pipe on a fuel tank in front of you
4. Delete the pipe you have just placed
5. Pick any block from the list
6. Place it a few times (5) on the spaceship provided
7. Notice the previous blocks disappearing as you place new blocks

### Environment
Starship EVO Version | Graphics Card | GPU Driver Version
--- | --- | ---
22w30c | 970M | 516.59

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Okay so I was able to reproduce the issue finally! Indeed it is linked to fuel pipe. I keep you posted. Thanks

**Comment by CaptainKronos** [comment]
Yeah, I was getting this issue as well. Respawning the BP from a new starter block seems to fix the issue on my end, but it was rather unsettling having blocks just go invisible at seemingly random intervals.

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil So thanks a lot, I was able to fix this. For 22w31a. Cheers
