### ISSUE TITLE
Unspawn handled weapon in inventory and you can be stuck

### ISSUE THREAD

**Issue by cyberjasse** [tsunamayo/Starship-EVO#4810]
### Short Description of the issue:
I unspawn an handled weapon that I had in my inventory. The weapon icon still in the inventory bar. If I select it, then I am stuck.
Unloading the world and reload it fixes everything.
...

### Steps to reproduce the issue:
- have a handled weapon on an item stand
- Place a block on it to have it as current entity
- Take the weapon
- Press tab -> current entity -> unspawn Entity
The weapon icon does not disappear from inventory
- Select the weapon
Now you are stuck.
...

### Environment
- Starship EVO version: 22w30c  default branch
- Graphics Card: rtx 2070 super

### Additional information:

The player.log file
[unspawnHandledWeaponInInventory_playerlog.log](https://github.com/tsunamayo/Starship-EVO/files/9273903/unspawnHandledWeaponInInventory_playerlog.log)

**Comment by tsunamayo** [comment]
@cyberjasse Hi, thanks for booking this. Issue will be fixed for 22w31b. Cheers
