### ISSUE TITLE
Teleport list doesn't unload when Exiting to title

### ISSUE THREAD

**Issue by cyberjasse** [tsunamayo/Starship-EVO#4811]
### Short Description of the issue:
The Teleport menu in codex still have same entries from another saves that I played before without rebooting the game.
...

### Steps to reproduce the issue:
- Load a save
- have a teleport station reachable so you have it in the Teleport menu in the codex . I was in the habitat
- Go to main menu -> Exit to Title . Don't quit the game
- Load a save . It can be the same save or another one.
- have a teleport station reachable
- Check the Teleport menu in the codex. You still have the entries from the previous save.
...

### Environment
- Starship EVO version: 22w30c
- Graphics Card: rtx 2070 super

### Additional information:

The player.log file
[TeleportList_keeplast_playerlog.log](https://github.com/tsunamayo/Starship-EVO/files/9273917/TeleportList_keeplast_playerlog.log)

**Comment by tsunamayo** [comment]
@cyberjasse Hi, issue will be fixed in 22w31b. Thanks a lot!
