### ISSUE TITLE
Invisible Blocks

### ISSUE THREAD

**Issue by JnkyX** [tsunamayo/Starship-EVO#4812]
### Short Description of the issue:
Invisible blocks. May be due to clipping.
...

### Steps to reproduce the issue:
Placed a 2x1 engine onto a block with a yoke that was clipping through. Then placed two capacitors onto it, upon placing the second the engine turned invisible.  Can also happen with small tanks in the same location. In the screenshots you can see the outline of it of the invisible block.
...

### Environment
- Starship EVO version: 22w30c
- Graphics Card: 1660ti

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/9274232/Player.log)
![20220805195532_1](https://user-images.githubusercontent.com/93474959/183229230-d4904e5c-28a1-4584-8f2f-270eeefa666c.jpg)
![20220805194827_1](https://user-images.githubusercontent.com/93474959/183229231-5bcd8f69-3dd2-4423-9cbd-3d3ba573ab90.jpg)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@JnkyX Hi, thanks for booking this. Actually I just managed to fix that issue a few hours ago, it will be in upcoming 22w31a to be released today. Thanks for your help!

**Comment by tsunamayo** [comment]
Btw it was linked to deleting a transparent pipe. Cheers
