### ISSUE TITLE
Question about conveyor belts

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#4814]
Hi,

I'm building a larger cargo/ vehicle freighter right now, and I was wondering if the new conveyor belt block could be a great addition to it. So I tested it and found out that conveyor belts don't interact with vehicles/ ships that are landed on it within a gravity field.

However, I think conveyor belts should do that. It would be really cool if I could load vehicles in a larger ship by landing them on a conveyor belt and push them into the ship that way. 
Another cool thing for using conveyor belts could be changeable sizes. I don't see a reaosn for a 32m conveyor belt ... but there's nothing wrong with a 1/4th or even a 1m conveyor for smaller interior functions or larger hangar functions (pushing players from A to B like the things at an airport or pushing a landed ship for efficient storage in a hangar bay. - Perhabs even cargo containers for the future? 

Btw: the conveyors push a player in the wrong direction - see vid 1 

https://user-images.githubusercontent.com/81495956/183245533-9865e2b5-809e-46e7-9058-02d427837e9e.mp4

https://user-images.githubusercontent.com/81495956/183245032-072b4007-7d70-461b-9bc3-951560eb833f.mp4

**Comment by cloudrambler** [comment]
On a similar note, I wondered if conveyor belts could be used in reverse, to make a Johny5 robot crawl around on flat surfaces. It probably needs a few changes to the physics of surface interactions, but I have seen those changes requested elsewhere.

Ni harm in asking. :)

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, so I fixed the player issue. For me entity pushing is working fine though. Also what you are asking is not supported, I guess it will be better if I can use proper track instead.
Regarding the size I think 1m is good, I dont really want to go smaller, and if you want bigger you can always scale.
Cheers mate!
