### ISSUE TITLE
22w31a - Crash dumps

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4816]
### Short Description of the issue:

Hey, Tsuna, I'm not sure where can I post various crash dumps, so I will just leave them here.
They happened completely randomly - sometimes during a game, sometimes at the start of the game, and sometimes when I tried to exit to desktop.

### Steps to reproduce the issue:

n/a

### Environment
Starship EVO version | Graphics Card | GPU Driver Version
--- | --- | ---
22w31a | 970M | 516.59

### Additional information:

[Crashes.zip](https://github.com/tsunamayo/Starship-EVO/files/9275383/Crashes.zip)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Okay thanks a lot, it seems we have a lot of instability issue lately... Thanks
