### ISSUE TITLE
22w31a - "Material Remove Paint" option colors blocks black when using a material coating

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4817]
### Short Description of the issue:

It has been noticed that when the "Material Remove Paint" option in the F1 menu is enabled, it is possible to paint blocks black (0,0,0 RGB) when applying a material to the block.

The material coating changes the material but it also covers it with a black paint on top.

Once the "Material Remove Paint" option is disabled, and once a player removes paint manually, the material change on a block is visible again.

### Steps to reproduce the issue:

1. Boot up the game
2. Load the provided save
3. Open the F1 menu and switch on the "Material Remove Paint" option
4. Change a material of the block in front of you
5. Notice that the block has been colored black

### Environment

Starship EVO version:  | Graphics Card | GPU Driver Version
--- | --- | ---
22w31a | GTX 970M | 516.59

### Additional information:
[4817 character.zip](https://github.com/tsunamayo/Starship-EVO/files/9275459/4817.character.zip)
[4817 Player.log](https://github.com/tsunamayo/Starship-EVO/files/9275462/Player.log)

https://user-images.githubusercontent.com/63756057/183258584-7d11dff4-b017-46da-8d22-b5e0b51ac0ad.mp4

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Hi, issue will be fixed for 22w31b. Thanks a lot!
