### ISSUE TITLE
Placing a weapon on a half block breaks it

### ISSUE THREAD

**Issue by Turtlrpups** [tsunamayo/Starship-EVO#4818]
### Short Description of the issue:
Placing a weapon on a 4x1x1 1/2m square prevents me from adding a add-ons 
...

### Steps to reproduce the issue:
Place 4 1/2m squares into a square place any weapon and presto u can't add add-ons 
...

### Environment
- Starship EVO version:  22w30c
- Graphics Card: 

### Additional information:
![Uploading 20220807_013713.jpg…]()
![Uploading 20220807_013701.jpg…]()

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by ProPeach** [comment]
If it's on a half block it means the weapon is now offset on the grid you were originally working on. Try opening the F1 menu and toggling the "Global Origin Grid" setting to "Local Targetted Grid". That's a useful tool that helps snap to the Grid you're looking at provided you're working in the same scale

**Comment by tsunamayo** [comment]
@Turtlrpups ProPeach is correct. This is why I dont really like that whole offset shenanigan, still not convince by it...

**Comment by ProPeach** [comment]
I think some of the problem lies in how "secret" the F1 menu is, you see it a lot on Discord where newer/returning old players are told about the menu and love it. But they would have had no idea it exists without bring told first by another player. Perhaps keep the F1 key as a shortcut to open it, but have a button on the normal Codex to open it too? In general new players seem to have trouble finding the tools they need

**Comment by Uncle-Ulty** [comment]
this is strange... I have no problem on putting an addon on a 1m weapon even when it's offset on one-quarter of 1/8 bricks (1/32).

But, I noticed that if you don't select the same scale (T) of the weapon, you can't place an addon.

**Comment by tsunamayo** [comment]
@Turtlrpups @ProPeach @Uncle-Ulty So now addon will default to the local build mode, which will avoid any confusion. Thanks

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo Brilliant! Thank you!
