### ISSUE TITLE
22w31a - Tank Joins appear between pipe segments upon blueprint spawn or rejoining the world

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4819]
### Short Description of the issue:

It has been noticed that Tank Joins can incorrectly appear between pipe segments on spawned blueprints or upon re-joining a world.

The correct behavior for them would be to spawn only between pipes and system blocks like Reactors, Warp Cores, Lightcruise Engines, and Fuel Tanks.

### Steps to reproduce the issue:

1. Boot up the game
2. Load the provided save
3. Spawn the provided blueprint
4. Notice that the Tank Joins spawn between pipe segments

### Environment

Starship EVO version:  | Graphics Card | GPU Driver Version
--- | --- | ---
22w31a | GTX 970M | 516.59

### Additional information:

Related issue: #4625

[4819 - blueprint.zip](https://github.com/tsunamayo/Starship-EVO/files/9276387/4819.-.blueprint.zip)
[4819 - save.zip](https://github.com/tsunamayo/Starship-EVO/files/9276392/4819.-.save.zip)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/9276401/Player.log)

![4819](https://user-images.githubusercontent.com/63756057/183280914-ea5b9296-be23-40d4-8b86-9d98a45c6927.png)

https://user-images.githubusercontent.com/63756057/183280929-9b985748-74c7-45e4-bd36-a6b256a8ea71.mp4

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Thanks for the detailed case, issue will be fixed for 22w31b. Cheers!
