### ISSUE TITLE
[Bug] Prefab menu non-functional

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4820]
### Short Description of the issue:
The prefabs in the menu are invisible, and don't appear when you use them in your hand

![image](https://user-images.githubusercontent.com/27857711/183298814-58212d6c-5c0e-4442-a38e-fd85f70aaffa.png)

### Steps to reproduce the issue:
- Open the prefab menu

### Environment
- Starship EVO version: 22w31a
- Graphics Card: RX 580

**Comment by Uncle-Ulty** [comment]
I have the same problem...

**Comment by HigureKomori** [comment]
ive gotten prefabs from the workshop and its always stayed empty

**Comment by tsunamayo** [comment]
@ProPeach Hi, issue will be fixed for 22w31b. Thanks!
