### ISSUE TITLE
[BUG] Shield capacitor blocks not behaving normally

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#4822]
The shield capacitor blocks start out lit up (default blue) when placed, but when the blueprint is spawned, those capacitors change to black. This does not appear to affect their function, though as I am still working on the ship, I cannot really test it out yet. It does not appear possible to recolour the capacitors once this has occurred.

Edit: the same loss of colour occurs when loading the world from desktop.

Version: 22w31a
Graphics: GTX1070

![20220807165105_1](https://user-images.githubusercontent.com/70821082/183299472-346dc482-3130-4be3-be4d-b444830edf03.jpg)

**Comment by BigBadKangaroo** [comment]
Got this as well ... but they work just fine for me, it's just the color / lights

**Comment by Uncle-Ulty** [comment]
I have the same problem

**Comment by tsunamayo** [comment]
@cloudrambler Hi, this issue will be fixed for 22w31b. Thanks!
