### ISSUE TITLE
Readme - The Hyperlinks 2, Electric Boogaloo

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#4825]
### Short Description of the issue:
Sorry to come back so soon!

While I appreciate you getting to the hyperlinks so soon, I'm afraid you missed another link to the skywanderers site, and the discord/steam links go nowhere.

I don't want to detract your time from the main focus, so I've made the relevant changes here in this report; you can just replace the readme with this copy instead.

Best, Harry.

<pre># Starship EVO

Welcome to [Starship EVO](https://steamcommunity.com/app/711980) bug tracking repository!

# Submit a Blueprint
- Go over to our submission page: https://github.com/tsunamayo/Starship-EVO-Backers-Ships

# How to report issues

- Please provide as much relevant information as possible.
- Please submit one issue at a time so that we can indivually work on them.
- When creating a new issue you will have a template to fill in. You are **not** required to do so but it will help.
- [Create a new issue](https://github.com/tsunamayo/Starship-EVO/issues/new)

# About

Build **spaceships** and wander among the **stars**!

**Starship EVO** is a voxel **construction** game set in a procedural **galaxy** made of billions of stars.

Play with your **friends**, use **blocks**, **bricks** and **paints** to create the **spaceship** of your dreams and discover a galaxy full of wonders.

The game offers to merge the **excitement of exploring** uncharted worlds as in Elite, with the **elegant and simple joy of building** of Minecraft.

# Links

[Wiki](https://starshipevo.fandom.com/wiki/Starship_EVO_Wiki)

[Kickstarter](https://www.kickstarter.com/projects/skywanderers/skywanderers)

[Twitter](https://twitter.com/TransNeonOrange)

[Steam](https://store.steampowered.com/app/711980/Starship_EVO/)

[Youtube](https://www.youtube.com/channel/UCITNnomMkqQv1aNi_8dxVBQ)

[Reddit](https://www.reddit.com/r/StarshipEVO/)

[Discord](https://discord.gg/starshipevo)</pre>

**Comment by tsunamayo** [comment]
Ok thanks a lot, done!
