### ISSUE TITLE
Flickering Windows

### ISSUE THREAD

**Issue by tsunamayo** [tsunamayo/Starship-EVO#4826]
One issue that is bugging me is the high speed flickering of windows especially visible from a cockpit for example.
I am not talking about transparency order issue, when viewing through two windows can result in them being drawn in different order from frame to frame (this is still normal with my current tech).
It popup very randomly for me, what is your experience with this?
It depends on the player camera orientation.
I have also noticed normal decal having flickering reflection too, it seems linked to this bug.

Thanks

**Comment by ProPeach** [comment]
I've also found that the flickering is very random, some blueprints feature it more than others.
Here's a world where the windows flicker, you spawn right in front of the window. For this instance it doesn't seem to be linked to either player orientation, or the windows orientation as there's an identical blueprint in a different position next to the first that still shows flickering.
[Performance Test.zip](https://github.com/tsunamayo/Starship-EVO/files/9291402/Performance.Test.zip)

https://user-images.githubusercontent.com/27857711/183669642-41309aa6-1819-4300-bb69-f8b75ff7ee19.mp4

I haven't noticed flickering on normal decals yet, but I'll keep an eye out

**Comment by BigBadKangaroo** [comment]
I haven't noticed flickering on decals at all, but the window flickering is bugging me every single time I build with glass blocks ... 

https://user-images.githubusercontent.com/81495956/183748534-9c05a71c-dd4d-453c-a76b-6efdf56bd5f8.mp4


https://user-images.githubusercontent.com/81495956/183748567-8a7c0faf-5d6f-405c-9808-3bd05d347af2.mp4

**Comment by cloudrambler** [comment]
Ignoring the two windows scenario, the next most obvious flickering problem is lit system blocks viewed through a window. They seem to flicker all the time.

Regarding decals, I have noticed this on my builds and workshop builds where numerous decals are close or overlapping. Firstly the edges are inconsistently rendered when viewed up close, but then when viewed from further away, they can start to flicker to the point that at some distances, the flickering is more visible than the decals themselves.

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, this is a case of several transparent surface being rendered in a different order.

**Comment by BigBadKangaroo** [comment]
@tsunamayo sorry for the confusion. I haven't had any other issues with glass blocks so far except the ones I showed in the video

**Comment by Horkas** [comment]
@tsunamayo To me, it looks like the window is being over-ridden by a duplicate window mesh on the same exact vertices coordinates. As in, it looks like flashing mesh textures when the computer can't figure out which one to render "ontop". So you must have a shader or something rendering at the exact same time as another. Also, this reminds me ALLOT of the issue this guy had in this video starting @ 5:40 https://www.youtube.com/watch?v=7PpkAhVZMDc

**Comment by tsunamayo** [comment]
@Horkas Yeah this is what I suspected too, but I can get the same issue with a flat door. Geo is not duplicated, the shader pass is Cull Back. When I do shader recompile within Unity the problem is completely gone, until I reload the game. It is one of those that is really killing me.
Didnt watch the video yet, it seems pretty accurate lol...

**Comment by Horkas** [comment]
@tsunamayo The only other thing I can think of is that the object culling code is bugging out because it is trying to hide the back of the windows, but the verts can be seen through them, so are getting rendered back in, causing the infinite loop of flashing. 

SOMETHING is causing them to render and de-render over and over again.

**Comment by tsunamayo** [comment]
@Horkas yeah I just made progress on this, it only appears on newly spawned blueprint, and indeed culling seems to be linked as if I deactivate it it no longer flicker. I cant work on that this week-end, but I will fix it on monday. 
Cheers

**Comment by Horkas** [comment]
Very nice!

**Comment by tsunamayo** [comment]
That issue is finally fixed for 22w32a!
