### ISSUE TITLE
[Bug] Toolbar contents not saved on Exit to Desktop

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4828]
### Short Description of the issue:
Any changes to items on your toolbar are not saved when you restart the game

### Steps to reproduce the issue:
- Load a world
- Add some memorable items to your toolbar
- Quit to Desktop
- Load the same world and check your toolbar

### Environment
- Starship EVO version: 22w31b
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
@ProPeach Nope I nuked the toolbar save during one of the past update focusing on items. It might still happens a few times as the save format is evolving. Unlike ship blueprint I do not think the item bar warrant the additional code overhead of managing the conversion ;)
