### ISSUE TITLE
[Suggestion] Decal grouping

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#4829]
This relates to the decal flickering problem, but I wanted to expand the subject onto a possible solution and general upgrade.

Closely spaced and overlapping decals are (for me) very visually unstable. I once loaded a blueprint and was curious about the glowing ember effect that had been created under a mock meteor strike pattern, to realise that there was no intended glow or flicker, but that it was all just a random artefact from the (all black) embossed decals.

I have since seen similar problems on many decal arrangements and often rearrange them (where possible) to minimise the distortions.

Since this problem seems to occur mainly where there are several decals overlaid, I wondered if a better solution might be to combine multiple decals into a single image. This could work similarly to the copy/prefab method, except that the copied group of decals could be reduced to a single inseparable image. An unlimited amount of detail could be reduced to a single bitmap, without needing to support modding textures.

This could reduce the task for the computer graphics and remove any variation of interpretation. It would allow us to add more surface details without the cost or losses of using many separate decals.

**Comment by Kaiser-Indrasil** [comment]
Just for reference, the decal flickering problem occurs when there's 3 or more stickers overlapping each other.

Save file where the issue is immediately visible: [22w31a.zip](https://github.com/tsunamayo/Starship-EVO/files/9299817/22w31a.zip)

![image](https://user-images.githubusercontent.com/63756057/183897176-3b466e57-dbd3-427a-a5cd-15b4ae52d43a.png)

**Comment by tsunamayo** [comment]
@cloudrambler Hi mate! So that is a quite big dev, and it would not really fix the issue at hand. When the workaround is taking you 10x the amount of work compared to the real fix and is only fixing 5% of the issue I think it is not really worth it unfortunately!
Cheers
