### ISSUE TITLE
[bug] The game crashes when I mine

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#4830]
### Short Description of the issue:

The game freezes and crashes when I try to mine. I don't know if this problem is caused by several mining lasers working at the same time,  or if it's something related to the storage/collector system. I really don't know why this happens.
...

### Steps to reproduce the issue:
-after some time mining with mining tool
...

### Environment
- Starship EVO version:  22w31b
- Graphics Card: GTX 1660

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Miner.zip](https://github.com/tsunamayo/Starship-EVO/files/9295480/Miner.zip)
[TEC - Mineratec 20.zip](https://github.com/tsunamayo/Starship-EVO/files/9295483/TEC.-.Mineratec.20.zip)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/9295484/Player.log)

**Comment by tsunamayo** [comment]
@Uncle-Ulty It should be fixed in latest build. Thanks
