### ISSUE TITLE
Fuel Capacity not showing up correctly

### ISSUE THREAD

**Issue by LucasStraub** [tsunamayo/Starship-EVO#4833]
Fuel Capacity status on Current Entity is not showing up the correct value.

### Steps to Reproduce:

1. Add start a new ship with Start Block, and add tank, pipe and reactor
2. Check Fuel Capacity on the Current Entity
3. Repeat the process for the different tank and reactor sizes

### Environment
- Starship EVO version: early-access 22w31b
- Graphics Card: GTX 3060

### Additional information:
Log file: [Player.log](https://github.com/tsunamayo/Starship-EVO/files/9312619/Player.log)
![Starship_EVO_JSQNkyAPA1](https://user-images.githubusercontent.com/40873682/184258676-e62c5e06-547a-492b-8e58-56c10bdf3063.png)
![Starship_EVO_Or72I04iuc](https://user-images.githubusercontent.com/40873682/184258701-965fc54f-1f54-47b1-b172-720d8396af37.png)
![Starship_EVO_RDtqjeBZpK](https://user-images.githubusercontent.com/40873682/184258986-fa0b1398-d082-4469-8e4a-f27f9ce5e0f6.png)

**Comment by ProPeach** [comment]
This might be to do with the settings in the Tank - you need to press F on the Tank and select how you want the fuel to be used, or else it won't show up on these stats.

It's a bit of a pain having to remember to do this for every Tank, and it's also not very obvious to players who don't know about it. It would be great if tanks were configured to "Thrusters and Reactors" by default to sidestep this issue. Players can then configure it to "Storage" mode if they want, but most of the time when you place a Tank you want the fuel in it to be used

**Comment by tsunamayo** [comment]
@LucasStraub Thanks for booking this. I think @ProPeach is correct! I will change the default tank setting. Cheers

**Comment by tsunamayo** [comment]
@LucasStraub @ProPeach So this change was made in recent update with the updated system. By default it is now at mixed and will show unless you change it at storage. Thanks!
