### ISSUE TITLE
[Visual "Bug"] Hard to see hotbars

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#4834]
The grey hotbars are about the same color as standard hull grey and hard to see if there are no blocks selected
![image](https://user-images.githubusercontent.com/36980446/184517063-3ecd7977-8a07-4257-9d66-e54713f1a661.png)

**Comment by tsunamayo** [comment]
@ZachZent Yes I have been experimenting with it, as the previous one was colliding with the material and quantity text. I am not satisfied too, I will find something else!

**Comment by ZachZent** [comment]
Nothing wrong is going classic Minecraft style. Aka, nice boarders
![image](https://user-images.githubusercontent.com/36980446/184724671-307b478d-d698-46c0-bdc0-7cf8c2722b9a.png)

**Comment by tsunamayo** [comment]
@ZachZent It is a bit what I had, but it was too white, making the quantity number hard to read. I have plenty of option, I will improve it!

**Comment by tsunamayo** [comment]
@ZachZent Okay this should be acceptable in the next build. It is closer to what we have, a bit like minecraft. The boarder is less bright, and there is a shadow for the text so we can read it fine.
