### ISSUE TITLE
[Bug] Glass bricks are placed with a steel texture by default

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4837]
### Short Description of the issue:
When you place a glass brick, it is not transparent, it has the same steel material as a hull brick
![image](https://user-images.githubusercontent.com/27857711/184711736-dcace0ce-a2d6-40e1-adb3-91a5cc70802e.png)

As #4836 mentions, you can also paint the glass with a different coating to get a different colour, although it will still be opaque

You can revert the glass back to transparent by painting it with a colour, which overrules the material coating

### Steps to reproduce the issue:
 - Place a glass brick
 - Paint it with a colour
 - Remove the colour, change the material coating

### Environment
- Starship EVO version: 22w32a
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
@ProPeach Fixed for 22w32b. Thanks!
