### ISSUE TITLE
[Bug] Fuel tanks leaking into the void. 

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#4839]
### Short Description of the issue:
Not sure what's causing it, but fuel tanks will drain themselves as fast as possible without actually filling anything. 
I've attached a blueprint. Even with no destinations, tanks will drain at their maximum flow rate. 

This example blueprint has a reported fuel time of 3 minutes under full load. It lasts 15 seconds while idling without a player in control.

My best guess is systems are draining at max potential flow, not actual consumption. 
...

### Steps to reproduce the issue:
Spawn in the blueprint, 
Hit refill tanks
Observe the yellow tank drain despite no fuel moving. 

...

### Environment
- Starship EVO version: 22w32a
- Graphics Card: RTX 3080

### Additional information:
[FuelBug.zip](https://github.com/tsunamayo/Starship-EVO/files/9355535/FuelBug.zip)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/9355536/Player.log)

**Comment by tsunamayo** [comment]
Well as I will use the new cargo tech to deprecate the current fuel logic I am not gonna investigate this bug, as it is clearly linked to how fuel work... Cheers

**Comment by pinesh** [comment]
I’m happy with the resolution strategy. Thank you!

**Comment by tsunamayo** [comment]
@pinesh So we have the new logic live now in default. Thanks!
