### ISSUE TITLE
[BUG] Fuel connection blocks persist after the pipes have been removed

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#4841]
### Short Description of the issue:
Hiya, Fuel connections seem to persist even after breaking in some scenarios. 
...

### Steps to reproduce the issue:
Build a stretched pipe
Place a box fuel tank on the end
break the pipe, 
observe
...
### Environment
- Starship EVO version: 22w32a
- Graphics Card: RTX3080
### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![image](https://user-images.githubusercontent.com/14081996/185249544-0c81917b-007e-43c9-806f-2a6ebb544265.png)

**Comment by Starwhip** [comment]
![20220910202416_1](https://user-images.githubusercontent.com/36343006/189506258-ad68c446-d170-40a0-9707-1286f8d35fe1.jpg)

Yea I am getting this too. Easy to replicate:
Any time you place a **fuel tank of any kind** onto a pipe, and then delete the pipe, it will spawn the pipe connector piece. Probably a logic check to spawn the piece when the fuel tank is updated by the deletion.

This does **not happen** if you place a pipe on a fuel tank and then delete either piece. The fuel tank must be touching the pipe without being connected to it, and then the **pipe** must be deleted, it does not spawn the piece if the tank is deleted.

**Comment by tsunamayo** [comment]
@pinesh Is should be good now with the current build! Thanks
