### ISSUE TITLE
[BUG] Resolution selection resets to first in list.

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#4842]
### Short Description of the issue:
When opening the graphics menu, change any setting. Closing it will change the resolution to the first option in the resolution list unless it's manually set back.
...

### Steps to reproduce the issue:
Open the graphics menu while in a resolution that isn't defaulted.
Change your fov and close the menu.
observe the resolution change. 
...

### Environment
- Starship EVO version: 22w32a
- Graphics Card: RTX3080

**Comment by tsunamayo** [comment]
@pinesh Hi, yes, I never managed to reproduce (and fix) that issue...
