### ISSUE TITLE
[Bug] Camera perspective not aligned with brick

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#4843]
### Short Description of the issue:
The camera perspective sits at bottom of the camera lens, not the center of the brick. as detailed in the image.
...

### Environment
- Starship EVO version: 22w32a
- Graphics Card: RTX3080

### Additional information:
![image](https://user-images.githubusercontent.com/14081996/185250296-d545d227-978d-4fdb-bd72-03d7bb0e8175.png)
![image](https://user-images.githubusercontent.com/14081996/185250330-e3eed4e9-3a45-40ad-ad36-ff4779d2a881.png)

**Comment by tsunamayo** [comment]
@pinesh Indeed! Fixed for 22w32b. Cheers
