### ISSUE TITLE
[Bug] Blocks with inconsistent hitboxes

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#4844]
### Short Description of the issue:
Hiya, neither the rounded block nor the bevel block have the expected hitbox.
...

### Environment
- Starship EVO version: 22w32a
- Graphics Card: RTX3080
- 
### Additional information:
![image](https://user-images.githubusercontent.com/14081996/185250498-ba2ffbaa-4b2a-4bca-bf0c-dc6a0349b4ad.png)

**Comment by tsunamayo** [comment]
@pinesh Bevel should be fine, for that one unfortunately we will have to live with it for the time being, one day I might have time to improve the tech a bit for now many shape will simply be boxes. Thx
