### ISSUE TITLE
[Inconsitency] Missing Blocks

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#4845]
### Short Description of the issue:
Hiya, since we have the thin tile, It's odd that we lack the"Thin tile triangle". Should be a quick addition, we have a thin triangle block already for the glow version so this feels inconsistent. 

The same logic goes for the glow pipes with the absence of "Glow Pipe Thin"

### Environment
- Starship EVO version: 22w32a
- Graphics Card: RTX3080

Best,
Harry

**Comment by 5URG3** [comment]
+1 for thin tile triangle. Achieving the same effect uses way more bricks than necessary. There are multiple examples of this in-game within the Standard Interplanetary station.

**Comment by tsunamayo** [comment]
@pinesh Added for 22w32b.
@5URG3 Now that we have a much higher camera far-plane tell me if you see any Z-fighting issue if used at low-grid. (as they would have a 3cm height). You have to be far from the brick to start to see some Z-fighting.
If you are using them inside, or if you paint them the same as the underlying surface you will be all good though.
