### ISSUE TITLE
[SUGGESTION] Make the resolution and refresh rate separate options  

### ISSUE THREAD

**Issue by Womble-TC** [tsunamayo/Starship-EVO#4846]
### Short Description of the issue:

Right now, every combination of screen resolution and refresh rate are listed on one drop down menu, which can be a bit tedious to scroll through:
![image](https://user-images.githubusercontent.com/29961381/185251204-4c7fdfa3-e836-440d-9508-ac06b898006b.png)

Would it be possible to have the screen resolution and refresh rate be separate options in the graphics menu? 

### Environment
- Starship EVO version: 22w 32a

**Comment by tsunamayo** [comment]
@Womble-TC Hi mate. This how unity works unfortunately... Honestly it would be big dev, so I better of spend my time on other stuff for now. It is a bit silly for you because you have a high refresh rate monitor... Cheers
