### ISSUE TITLE
[Bug] Entity computers have incorrect hitboxes.

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#4848]
### Short Description of the issue:
Howdy, ship computers, turret computers etc are slightly taller than their logic counterparts, despite being visually the same.
...

### Environment
- Starship EVO version: 22w32a
- Graphics Card: RTX3080
- 
### Additional information:
![image](https://user-images.githubusercontent.com/14081996/185251880-6541049b-4b2c-4ac7-8e85-e51650299150.png)

**Comment by tsunamayo** [comment]
@pinesh Indeed! Fixed for 22w32b. Cheers
