### ISSUE TITLE
[BUG] Duplicate names in codex

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#4849]
### Short Description of the issue:
hiya, 
Two blocks share the name “Pipe thin”;  change one to pipe cover?
Furthermore, can we get the cover to be scale-able down to 1/4 or 1/8th?
...

### Environment
- Starship EVO version: 22w32a
- Graphics Card: RTX3080

### Additional information:
![image](https://user-images.githubusercontent.com/14081996/185252177-af6fa957-52b1-4587-9926-525809c87988.png)
![image](https://user-images.githubusercontent.com/14081996/185252248-4727efe6-7a61-40cc-a3f7-bcffc901d770.png)

**Comment by tsunamayo** [comment]
@pinesh Done for 22w32b. Thanks
