### ISSUE TITLE
[Minor Issue] Player camera clips through close objects

### ISSUE THREAD

**Issue by piotmetans** [tsunamayo/Starship-EVO#4850]
### Short Description of the issue:

The player camera can sometimes clip through blocks that are close enough to it, though from the 3rd person view there's clearly plenty of room for the player to sit. It's especially noticeable on higher FOV settings, these screenshots in particular were taken at 90.

### Environment
- Starship EVO version: 22w32a
- Graphics Card: RTX2070 Super

![window clipping](https://user-images.githubusercontent.com/660015/185250694-5056cf4b-91a7-4517-8b27-2bcf3343ba37.png)

**Comment by pinesh** [comment]
it appears the player camera might sit further forwards than expected on the model.

**Comment by tsunamayo** [comment]
@piotmetans Hi, unfortunately it is because of the very high camera near plane... I have to put a high near plane because of Z-fighting issues, we need a large far plane (even if I use dual cam). So we will have to live with it unfortunately! Cheers
