### ISSUE TITLE
[Bug] Thin tile triangle has incorect description in codex

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#4851]
### Short Description of the issue:
As the title describes
...

### Environment
- Starship EVO version: 22w32a
- Graphics Card: RTX3080

### Additional information:
![image](https://user-images.githubusercontent.com/14081996/185252726-d4be5184-1f56-4181-891a-c68ccedf35c2.png)

**Comment by tsunamayo** [comment]
@pinesh Fixed!
