### ISSUE TITLE
[Suggestion] Deadzone setting rename

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4852]
I was flying around today and found that my ship had a very large deadzone with the mouse controls. I remembered us talking about improving it in the past before, so went searching for a setting to make it smaller but I guess my settings got reset at some point.

Eventually I found the "Mouse Power Vehicle" setting and discovered that to be the deadzone setting. The name of this is **not** clear for its actual function. I suggest it's renamed to something with Deadzone in the actual name. Like "Mouse Deadzone on spaceship" etc

_________________________________________________________

Also, the default setting for new players has the deadzone set to very high. I recommend reducing it to less than 10 on that scale as that is generally the standard, it's the minority of players that like to tweak it and increase it

**Comment by tsunamayo** [comment]
@ProPeach Let me check, I dont think this setting should be the deadzone, but more the power curve applied to mouse movement.

**Comment by 5URG3** [comment]
Whatever this setting is called, it helps a bit. I find the deadzone infuriating.

I recommend the player be able to toggle the deadzone on and off in the menus. 

The current flight controls are not particularly fun to use in combat, an issue that is made worse by the lack of gimballed direct weapons.

**Comment by ProPeach** [comment]
> @ProPeach Let me check, I dont think this setting should be the deadzone, but more the power curve applied to mouse movement.

Is there a dedicated deadzone setting that I missed? Configuring the setting to a value of 1 did the trick for me at least, all I wanted was for the ship to start moving the moment that my mouse left the neutral middle of the screen rather than having to over exaggerate mouse movements to get the ship to move. Otherwise it's pretty much impossible to get any fine degree of control

**Comment by tsunamayo** [comment]
So "Mouse Power Vehicle" is not a deadzone, it is a Power curve setting: 
You input goes from 0 to 1. Applying a power curve of 100% means that if you apply an input of 0.5 the output value will be (0.5)^(1 + setting) = (0.5)^(1 + 1) = 0.25. 
So it means you get a more precise / slower control at first, then it kicks in more as you get further away from the center. I think that setting was requested back in the day.

We might have a misunderstanding on the terminology, or I might be missing something else. I call Deadzone the minimum mouse offset to the center before any rotation happen. If it starts to move, but not enough, then it is no longer a deadzone issue but another problem. Tell me if I am wrong, it might be something else in other game I dont know.
The current deadzone is calibrated to the tiny circle in the middle of the screen, as soon as the cursor leave it the ship will start to move, even by a tiny bit. 
If I give no deadzone then it is no longer possible to hold steady (which might not be that much of a big deal).

@5URG3 @ProPeach Now it might very well be another issue, lets try to get to the bottom of it. Could you confirm the following:
1) your screen resolution
2) what is your framerate
3) does the ship start to move when just outside the tiny circle? It should move, but by a tiny bit.
4) What is your Mouse Sensitivity Vehicle / Mouse Power Vehicle settings.
5) (Just to confirm) are you using a mouse not a joystick
6) Are you testing at rest, with no rotation when starting to move, or are you talking about a reversal of steering (which is typical in combat)? It might be a ship physics issue.
7)Is it with all blueprint or specific? I am using the Razorface for example.

Thanks!

**Comment by Kaiser-Indrasil** [comment]
It is by no means an easy concept to summarize in a few words.

I would change it to "Vehicle Turn Rate Curve" and introduce a mouse hover pop-up saying "0% makes the turn rate linear. 100% makes the turn rate more precise for low attack vector, and faster for high attack vector."

**Comment by ProPeach** [comment]
Thanks for looking in to this one a bit more!
@tsunamayo I agree with your definition of a deadzone, now that we've talked about it more I do think that my issue was that the ship doesn't turn enough compared to how much you move the mouse - With Mouse Power Vehicle at 50% by default, it feels like there's a large deadzone because of how slow the ship moves with small input values. Especially when flying something fast like a fighter, you find yourself not really turning at all compared to how much distance you travel. With the Mouse Power Vehicle setting on something very low like 0-3 this feels much better.

1. 1920x1080
2. Stable 60fps, with v-sync (apart from that world I gave you lol)
3. The ship moves a _tiny_ amount at this output, very slowly
![image](https://user-images.githubusercontent.com/27857711/185591103-7ac41e31-75c0-4bed-a358-6a8b6fd6e5e9.png)
4. The above screenshot is with these settings
![image](https://user-images.githubusercontent.com/27857711/185586971-a3270c9f-8da1-4fa5-bed5-4f5d135c846f.png)
My preferred setting for MPV is now 0-3
5. I'm using a mouse
6. I've tested both - I don't _think_ there's a difference here in terms of the effect of the mouse, but in motion the negative experience for me is pronounced, perhaps partly due to the drift factor we were talking about in another thread. The larger the value for MPV, the more erratically you need to move your mouse for the steering reversal you mention
7. It's a great point that you made to test this, I had mostly been using fighters...
![image](https://user-images.githubusercontent.com/27857711/185589921-c0059836-d29d-4eca-925c-3f0c15fff9e9.png)
This ship is 150m long, and with the same settings as the above screenshot for 3. I have to move the mouse this much for the ship to move at an equivalent rate. It seems that the lower the agility factor, the lower the "actual" MPV, or at least it makes it feel like your mouse has less power. Perhaps this is just a perspective thing when your point of reference is a larger ship?


All in all the MPV setting does seem to do what you want it too, it was mostly just an issue of labelling and a poor default setting for me. I do wonder if we might need to revisit this once gimbals are back so we can get some combat experience, I have a feeling that matching the power curve to the gimbal curve might be tough. Also the increasing the anti drift values as per #4861 would also help the experience of ships when they're moving, so it might be a number of factors that lead to the poorer default experience

**Comment by tsunamayo** [comment]
@ProPeach Now that I remember, ironically this power curve was implemented because with gimbal it was too hard to shoot precisely at something near the center of your ship as the ship was moving too fast. Having a bit of power applied made for a smoother targeting experience.

**Comment by tsunamayo** [comment]
@ProPeach @Kaiser-Indrasil @5URG3 So how is the targeting feel now that we have gimbal back? 
Thanks

**Comment by ProPeach** [comment]
Targeting feels pretty good! I'm able to dial in a Mouse Power Vehicle setting I like, and gimbal makes up for the rest of the difference in aiming. I still can't hit a thing with gatling barrels though lol

On a similar note, I am finding that my ship often blocks my view forward. Have you thought much more about the changes suggested in #4553?

**Comment by tsunamayo** [comment]
@ProPeach I will check this again. Cheers
