### ISSUE TITLE
[Bug] Gimbal for lasers

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4853]
### Short Description of the issue:
I don't mean to nag, but #4614 for gimbals on laser bricks not working is still an issue. This, combined with the large default deadzone as per #4852 make it very difficult and frustrating to actually hit a target with fixed laser weapons which impacts the bounty hunting gameplay loop. It'd be awesome if the gimbal could be fixed, even if it doesn't work for weapons hooked up to timers yet.

### Steps to reproduce the issue:
- Fly a ship with fixed laser weapons
- Fire the weapons

### Environment
- Starship EVO version: 22w32a
- Graphics Card: RX580

**Comment by 5URG3** [comment]
I 100% agree. Combat with fixed weapons is pretty bad right now. It's more irritating than fun.

Please fix gimballed weapons. If this is difficult, then please allow the player to kill the deadzone entirely so the ship piloted immediately responds to mouse movement. 

Infact, please let us kill the deadzone in all scenarios. Combat is not dynamic and fun right now.

**Comment by Womble-TC** [comment]
I agree too. While the flight model itself is pretty good, actually aiming and shooting at stuff feels very floaty an unsatisfying.

**Comment by tsunamayo** [comment]
Copy I am putting this on top of the list. 
Now I have just tried, there is **very little** deadzone, I am not sure your trouble is coming from that. As soon as the cursor is beyond the mini circle the ship start moving.
I cant remove that entirely, as it would mean it would be impossible to keep the ship steady.

Like @ProPeach said in another post, maybe the trouble steam from the "Mouse Power Vehicle", by default it is at 50%. A higher value means that the ship will turn slower when close to the center. It is a power curve, so when the setting is at 100% an input of half = 0.5 become 0.25. You can put it a 0 entirely, then it will be linear.

That being said no amount of deadzone or sensitivity will replace a gimbal, any ship has a max turn rate that is a lot smaller than the gimbal turn rate, this is why we need that fix to make hardpoint weapon viable. It is even more important with mining now, I keep you posted.
Cheers

**Comment by tsunamayo** [comment]
@ProPeach @5URG3 @Womble-TC Okay issue will be finally fixed for 22w33b. Thanks!
