### ISSUE TITLE
Ladder has an incorrect description

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4854]
### Short Description of the issue:
Just a quick one, the Codex says that the Ladder brick allows you to climb it, but that isn't the case. It'd be nice if it told the player that it was decorative for now, we've had a couple of new players ask about how to use ladders as they were confused that the Codex says they are functional
![image](https://user-images.githubusercontent.com/27857711/185254348-7ae9e850-d6a9-4ad2-b0fb-9540e19c3d84.png)

**Comment by tsunamayo** [comment]
@ProPeach   Yeah true! Done for 22w32b. Thanks
