### ISSUE TITLE
[BUG] Can't disable headlamp when seated

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#4855]
### Short Description of the issue:
As described, the player cannot turn ON/OFF their torch when seated. 
...
### Environment
- Starship EVO version: 22w32a
- Graphics Card: RTX3080

**Comment by ProPeach** [comment]
The key conflicts with the Lightcruise key when piloting, so perhaps a solution would be to turn off the torch when you pilot a ship

**Comment by tsunamayo** [comment]
@ProPeach @pinesh Head lamp is already deactivated when you pilot a ship. Yes it is because it collide, and headlight is not necessary inside your ship. Thanks

**Comment by pinesh** [comment]
@tsunamayo the issue pertains when the character sits in any chair, not just piloting . 

I think this should be re-opened .
