### ISSUE TITLE
Old screens are still present in the codex. 

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#4857]
### Short Description of the issue:

Hiya, the new screens are brilliant, so why can we still see the old ones?
let's get them out of the codex, a clean codex is a clean mind. 

### Environment
- Starship EVO version: 22w32a
- Graphics Card: RTX3080
- 
### Additional information:
![image](https://user-images.githubusercontent.com/14081996/185255483-31a67e77-aa87-4d8e-ae3b-c104638a5ff4.png)

**Comment by tsunamayo** [comment]
Yeah I wanted I forgot to do this. The new screen dont quite replace the old yet, but it will be better that way. Done for next build.
