### ISSUE TITLE
[Suggestion] [UI/UX] Freelook toggle

### ISSUE THREAD

**Issue by piotmetans** [tsunamayo/Starship-EVO#4859]
A while back we were able to use freelook without needing to hold a button down the whole time. Personally, I find that option a lot more comfortable to use, but we don't have the ability to do that at all any more.

I think we need an option in the settings to switch between freelook hold and freelook toggle so people can choose for themselves.

**Comment by ProPeach** [comment]
I'd love to see this option returned as a toggle too

**Comment by Kaiser-Indrasil** [comment]
Same, I'd like myself a toggleable freecam, too!

**Comment by 5URG3** [comment]
Agreed, combat with player made turrets would benefit greatly from this.

**Comment by tsunamayo** [comment]
@piotmetans @ProPeach @Kaiser-Indrasil @5URG3 Done for 22w32b. Thanks!
