### ISSUE TITLE
FOV changes not applied in photo mode

### ISSUE THREAD

**Issue by kynamats** [tsunamayo/Starship-EVO#4870]
### Short Description of the issue:
FOV can't be changed in photo mode - any changes have to be made while time is passing. Its a pretty minor inconvenience to exit photo mode, make the changes, and go back; but since I only really change FOV when taking screenshots it would be great to have the changes apply without exiting - even better to have a slider available in photo mode to change it without having to open the main graphics options.
...

### Steps to reproduce the issue:
Enter photo mode, open graphics options and attempt to change the FOV. changes will not apply until time is resumed.
...

### Environment
- Starship EVO version: 22w32b
- Graphics Card: 3070ti

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by ProPeach** [comment]
In the same vein, would it be possible to lower the minimum FOV range? I remember a couple years back you could lower it to 5 minimum which gave a really lovely isometric effect for ship screenshots, the current minimum 30 is nice but it'd be sweet if we had the option to go lower

**Comment by tsunamayo** [comment]
@kynamats @ProPeach Both suggestion are implemented for 22w45a. Thanks!
