### ISSUE TITLE
[Suggestion] Paint Tool Decal Bypass Mode

### ISSUE THREAD

**Issue by Facest4b** [tsunamayo/Starship-EVO#4871]
### Short Description of the issue:

Decals have very large hitboxes, which can make painting ships incredibly frustrating.

This is particularly notable when using decals that have transparency, as seen here.

![Decal Hitbox](https://user-images.githubusercontent.com/67114230/185626803-72718662-6eeb-40ef-bfe8-706e09620926.png)

These hitboxes make it impossible to paint the blocks behind, unless approached from behind

Instead of having custom hitboxes for each decal, I propose a decal bypass mode for the paint gun. When activated, this would exclude decals from being painted at all and allow painting of blocks covered by decals.

The key binding could be the same button that changes your block grid size.

**Comment by Uncle-Ulty** [comment]
I'd like to propose 3 modes for painting tool:
- brick and decal
- brick only
- decal only

**Comment by ProPeach** [comment]
This would be pretty cool. We are getting a little crowded with options though which is becoming a bit of a problem to manage, if at all possible the most elegant solution would be tighter hit boxes on the decals in the first place. iirc hit boxes used to be a lot more accurate, but we have had a couple of tech changes that might have messed with it.

**Comment by Facest4b** [comment]
I think that would also be a good solution, although personally I still think being able to paint underneath decals would be very valuable for repainting entire ships without disrupting things like markings and vents.

**Comment by tsunamayo** [comment]
@ProPeach @Facest4b Yes, this actually a bug as it should only paint like you said.

**Comment by tsunamayo** [comment]
@Facest4b @ProPeach Okay for 22w45a we will get a better decal targeting system, targeting what you painted in red wont select the decal!
Thanks
