### ISSUE TITLE
[Bug] Thin Tile Triangles are transparent

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4872]
### Short Description of the issue:
The new Tile piece is invisible when placed
![image](https://user-images.githubusercontent.com/27857711/185645244-81cd4878-ab51-48ef-b2f7-013a29b387d8.png)
![image](https://user-images.githubusercontent.com/27857711/185645263-06472cdc-0d7a-4124-a45a-ac88df8b1849.png)

### Steps to reproduce the issue:
- Place a Thin Tile Triangle
- _Where did it go_

### Environment
- Starship EVO version: 
- Graphics Card: RX 580

**Comment by pinesh** [comment]
Encountered this too!

**Comment by tsunamayo** [comment]
@pinesh Hi, this is fixed for 22w32b2. Thanks
