### ISSUE TITLE
Missing previous ship-sized system models

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#4874]
Hiya, 

Before dropping big and small ship systems with the advent of the excellent scale tool, we had some really nice reactor and capacitor models.  When the change came, you made the understandable decision of going with the more performance-friendly option.

Is there any chance we can get them back in some form? It would be a shame to let them go to waste.

![image](https://user-images.githubusercontent.com/14081996/185672788-9375e7e9-193c-4ebd-9dea-ab57de404885.png)

![image](https://user-images.githubusercontent.com/14081996/185672766-34313b52-5791-4c5c-9a4e-ac43b1e220b1.png)

**Comment by tsunamayo** [comment]
Haha, waste in the name of the game. It is not even close to being the worst thing I have trashed compared to all the code deprecated.

**Comment by pinesh** [comment]
oh good grief, enough to make a second game!
