### ISSUE TITLE
[Bug] Codex items become stuck to the cursor when moved over toolbar. Infinite stacking in codex.

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#4876]
### Short Description of the issue:
Codex items are misbehaving, sometimes becoming locked to the cursor when dragged.
items can be stacked on the codex, then onto themselves, creating a semi-infinite loop in the codex. The game can't render the full stack size. Potential overflow?
...

### Steps to reproduce the issue:
Interact with the codex, dragging elements as seen in the video.
...

### Environment
- Starship EVO version: 22w32b
- Graphics Card: RTX 3080

### Additional information:
https://user-images.githubusercontent.com/14081996/185700302-a2e76847-92d1-4d06-99ff-eee8c158c4fe.mp4
https://user-images.githubusercontent.com/14081996/185700613-5f0112e8-ba84-4f6f-a7dc-671759978755.mp4
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/9385159/Player.log)

**Comment by tsunamayo** [comment]
@pinesh Hi, this is fixed, I am repushing the build in 22w32b2 as it is a regressin. Thanks
