### ISSUE TITLE
Shipyard issue

### ISSUE THREAD

**Issue by nosfo** [tsunamayo/Starship-EVO#4879]
### Short Description of the issue:

Ship with childrens can select the option : request landing.

### Steps to reproduce the issue:

1 set a shipyard
2 try to land with a very basid ship : no prob
3 add 2 or more pistons on the ship, the optin : request landind disappears

### Environment
- Starship EVO version: 
- Graphics Card: 

_(Screenshots, Videos, Error logs, Related issues)_

Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce RTX 3060 Ti (ID=0x2489)

**Comment by cyberjasse** [comment]
I faced this bug some times . I tried to reproduce but I didn't succeed to reproduce . However, I succeeded to park even if the ship, with its child entities taken into account, is way larger than the configured shipyard area .  I wonder how the ship size is calculated when it has child entities .

**Comment by tsunamayo** [comment]
@nosfo Hi, well if your ship was bigger because of the piston then it is normal it cannot land. In the next update there will be a message explaining the issue. Thanks
