### ISSUE TITLE
[Bug] Thin tile triangle and glow pipe thin is missing UI sprite

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#4883]
### Short Description of the issue:
As indicated by the image, both the selected sprite image for the thin tile triangle and glow pipe thin is missing.
...

### Environment
- Starship EVO version: 22w33a
- Graphics Card: RTX 3080

### Additional information:
![image](https://user-images.githubusercontent.com/14081996/186236685-e1a4e6a1-6d9a-442e-84a4-8213ba8cbb16.png)

**Comment by tsunamayo** [comment]
@pinesh Fixed for 22w45a. Thanks!
