### ISSUE TITLE
Thin Tile Triangle light bug

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#4886]
Hi there,

when zooming out with the camera, the Thin Tile Tirangle has a small little light that glows up:

https://user-images.githubusercontent.com/81495956/187026773-7326ead5-4924-4525-b359-922487078236.mp4

It's the same zooming out with camera light that you can see like the ones from the thrusters - just smaller.

**Comment by BigBadKangaroo** [comment]
In addition to the light bug; I'm unable to place a pipe through a Thin Tile Triangle even though it is in the hull block section of the codex. The normal Tile Tirangle is able to do that:

![20220828215640_1](https://user-images.githubusercontent.com/81495956/187092194-9f83b577-9f49-46c8-bcf2-b5a72a2da312.jpg)

**Comment by tsunamayo** [comment]
@BigBadKangaroo I think both bugs have been fixed recently. Very nice ship btw!
