### ISSUE TITLE
[Inconsistency] Pipes cannot pass through Thin Tile Triangles 

### ISSUE THREAD

**Issue by Pawnp** [tsunamayo/Starship-EVO#4889]
Compared to the other tile variants the Thin Tile Triangles does not allow pipes to pass through it.

![image](https://user-images.githubusercontent.com/72423251/187097131-1a3e81da-225e-4379-986e-244fcebcc6a8.png)

**Comment by tsunamayo** [comment]
@Pawnp Hi, fixed for 22w38c. Thanks a lot!
