### ISSUE TITLE
[BUG] handheld and copy/paste

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#4890]
I was trying to load some handheld items and copy them as props on my ship. 
As soon as I copied and pasted the first gun, several bugs started

-my character started to glow
-I couldn't place more bricks
-the game started to freeze
-I couldn't paste a second time

I tried to close the game and open it again, and the problems spread.

-The prefab entity where I put all my prefabs and props disappeared...
- The original entity where I put all the item stand disappeared, but the weapons remained there, floating in the void

I tried to close the game and open it again Now my world is corrupted and I can't load the ship I've been working on for some months...

Something is super broken with handheld...

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/9441382/Player.log)
[Fragata.zip](https://github.com/tsunamayo/Starship-EVO/files/9441391/Fragata.zip)

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hi, do you know how to get your ship back even without custom save?

**Comment by pinesh** [comment]
More specifically, this is an issue with attempting to copy paste the handheld grip brick onto a non handheld entity, not an issue when the paste doesn't contain it

**Comment by Uncle-Ulty** [comment]
> @Uncle-Ulty Hi, do you know how to get your ship back even without custom save?

Yeah, in player entities.

the save uncorrupted itself and I rescued the ship, thanks!

But don't worry, I have lots of savestates of every build!

As Pinesh says, it's a bug related to copy/paste the handheld grip. Maybe the copy tool should ignore the handheld grip brick.

**Comment by tsunamayo** [comment]
@Uncle-Ulty @pinesh @Uncle-Ulty Hi, issue will be fixed for 23w45a. Thanks!
