### ISSUE TITLE
Character Creation

### ISSUE THREAD

**Issue by Sckiz1** [tsunamayo/Starship-EVO#4893]
### Short Description of the issue:
I feel there should be more depth to human creation such as skin tone
...

### Steps to reproduce the issue:
Creating character does not give any options for skin tone
...

### Environment
- Starship EVO version: 
- Graphics Card: RTX 3070ti

### Additional information:
Just Bought the game thinking there was the option to add skin tone.
_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
Yes this will be added at one point! Thanks

**Comment by CaptainKronos** [comment]
ALSO in regards to that, is there any reason why the game resets the character model to default every time you load into a world?
Or is that just my install being frakked?

**Comment by cyberjasse** [comment]
@CaptainKronos I have this too but I guess character customization save is not implemented yet.

**Comment by tsunamayo** [comment]
Nope it seems to be a bug!

**Comment by tsunamayo** [comment]
Bug was fixed for 22w45a. Thanks
