### ISSUE TITLE
[Suggestion] Weapon Handles as alternatives to Yokes

### ISSUE THREAD

**Issue by Crimson-Artist** [tsunamayo/Starship-EVO#4894]
Since yokes can be quite large and cumbersome I thought that weapon handles could be a great alternative.

Right now we can only place them on item stands to make handhelds but what if they were place able on ships and used as joysticks. They would function exactly the same way yokes do.  It would save on a lot of space and would look ascetically pleasing for various builds

**Comment by ZachZent** [comment]
Or just bring back stick yokes
![image](https://user-images.githubusercontent.com/36980446/187972955-61cf3c4a-32c9-4698-a0ad-bd150fa58640.png)

**Comment by Kaiser-Indrasil** [comment]
Having weapon handles as a yoke would be an awesome idea, especially since they already have left and right hand holding coded in

**Comment by tsunamayo** [comment]
@Crimson-Artist Done for 22w50a. Thanks
