### ISSUE TITLE
Game crash when deleting blocks

### ISSUE THREAD

**Issue by IgortheGrumpy** [tsunamayo/Starship-EVO#4896]
### Short Description of the issue:

... Deleting blocks that have been placed inside the starter station the game crashes

### Steps to reproduce the issue:

...Place a starter block in the station then delete it.

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/9482754/Player.log)

**Comment by tsunamayo** [comment]
@IgortheGrumpy Hi, I think the real issue was deleting a starter block overlapping (colliding) with another starter block. I have just fixed that issue for 22w45a. Thanks a lot!
