### ISSUE TITLE
[Suggestion] Panel Material

### ISSUE THREAD

**Issue by PopkaAkula** [tsunamayo/Starship-EVO#4898]
### Short Description of the suggestion:

This has been a issue I've had for a long time but only now have I gained the motivation to complain about it.
Simply put, it would be nice if we got a material that matched the gloss and color of the panel bricks.

![image](https://user-images.githubusercontent.com/37738021/188289421-a573d928-705d-48ef-8984-ae8897b5cc57.png)

_[fig. 1] Here we see a Panel brick in comparison to steel, dark steel, and matte steel_

![image](https://user-images.githubusercontent.com/37738021/188289476-3dbec00a-c625-4d1b-93f2-419097713ec3.png)

_[fig. 2] The same Panel brick and materials under a light condition that puts emphasis on the glossiness_

The Panel bricks fall under a weird non-replicable material zone where matte steel is dark enough to almost match, but isn't nearly glossy enough, and steel is glossy enough to almost match, but isn't dark enough. Paints are out as they aren't glossy enough to come close to replicating the color of the Panel bricks. I don't know how difficult of a feature this would be to implement into the game but surely since the game shows this color on Panel bricks and the lot, we could get it as a material to paint with.

**Comment by BigBadKangaroo** [comment]
Another way to solve the problem could be to allow us to paint these type of blocks with the already existing materials such as steel, copper, etc. And give the additional option to paint the part of the block with normal colors

**Comment by tsunamayo** [comment]
@PopkaAkula Hi, yes I think I should simply update those panel, they are supposed to match the hull color. Thanks

**Comment by tsunamayo** [comment]
@PopkaAkula @BigBadKangaroo 

![image](https://user-images.githubusercontent.com/6604318/199883482-cf1efcac-c420-4380-a39f-48972fe12cb6.png)

![image](https://user-images.githubusercontent.com/6604318/199883520-1bdf70e7-7bc3-47f5-917e-e9e37a96a311.png)

**Comment by tsunamayo** [comment]
@PopkaAkula @BigBadKangaroo So this will be released for 22w45a. Thanks!
