### ISSUE TITLE
[Blocker] - 22w33a - Undeletable blocks can remain on select child entities

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4899]
### Short Description of the issue:

It has been observed that after placing down a few blocks on select CEs and trying to delete or paint them, these blocks can become undeletable and leave a "ghost block" behind.

This ghost cannot be deleted, painted, or built upon, but its physical collision mesh remains as well, since it's not possible to build a block next to it, clipping into it.

@pinesh made some excellent points as to why this behavior might occur:
> Because I had something like that, and found it was to do with the recycle list on the child entity itself
Somehow the bp listed an index that was currently occupied as “ok to recycle”
I had to either rebuild the CE or use a custom evoedit script to purge the recycle list

> The recycle list incorrectly marking an occupied index as free to reuse

As for repeatability, it seems to occur on random CEs and I have not discovered a way to reliably cause this issue.
It always occurs on the same CE after a game reload though.
Respawning the BP solves the issue for a particular CE.

### Steps to reproduce the issue:

1. Boot up the game on the Default branch
2. Load up the save
3. Build a few blocks on top of the CE in front of the character
4. Try to delete or paint the blocks you've just built
5. Notice that the blocks cannot be deleted / are replaced by different blocks / leave "ghost blocks" behind

### Environment
- Starship EVO version: 22w33a
- Graphics Card: 970M

### Additional information:

Issue was found to occur weeks ago but went unnoticed for a few patches and now reappeared again.
Therefore it is **not** a regression.

[Character save](https://github.com/tsunamayo/Starship-EVO/files/9484470/22w33a.zip)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/9484472/Player.log)

https://user-images.githubusercontent.com/63756057/188308850-1478f1d3-68fc-41f9-a128-7b5c0d0e450f.mp4

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo This bug is extremely infuriating since if a CE becomes corrupted, it can easily add a few hours of work to replace it, and then it's only a matter of time before next CE becomes corrupted.

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo I've also noticed that it's sometimes possible for this bug to completely prevent building or deleting blocks on the entity whose CE became corrupted. Please make fixing this bug a priority.

**Comment by ProPeach** [comment]
I experience this too. If I try to remove the problem bricks, then respawn the entity using the starter block the bricks appear as ghosts, only visible through certain angles
https://user-images.githubusercontent.com/27857711/188941538-6d147b52-b5db-4dda-8431-9dcd463b57fb.mp4

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo Here's a [sample CE](https://github.com/tsunamayo/Starship-EVO/files/9525315/Indraplz.zip) that clearly displays the issue. You can follow the steps I took in the video below in order to reproduce the issue.

https://user-images.githubusercontent.com/63756057/189079717-04407741-94f3-4e74-96ab-1cd43896d625.mp4

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo Could you please prioritize fixing this bug?
It's been sabotaging me to such a degree that I can't even continue to work on my project anymore.

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Sorry I completely missed that bug, it must have happened during crunch time... (Daughter was about to be born too). I am having a look at it now. I guess I misunderstood what Blocker meant...
If I dont add a tag, it means I havent read it. So dont hesitate to open another thread if you think I have missed it and it is really urgent. 
Cheers I am keeping you posted.

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo No worries mate! NuclearLemons managed to sort it out for me with his EvoEdit tool. :)

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo Oh and yeah, at my QA company we use the term 'blocker' for labelling bugs that block the player from progressing further ^^

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Well I can find that issue on reload (I just fixed it actually), but I need to understand how we got to have corrupted ids. When did you made this entity? Did you use any special feature to do it (copy-paste, prefab, symmetry)?
Otherwise we can still get this issue during gameplay.

**Comment by pinesh** [comment]
> @Kaiser-Indrasil Well I can find that issue on reload (I just fixed it actually), but I need to understand how we got to have corrupted ids. When did you made this entity? Did you use any special feature to do it (copy-paste, prefab, symmetry)?
> Otherwise we can still get this issue during gameplay.

I’m just as confounded. I had symmetry going at the time, but only on the main entity. I think I’d pasted something with an item connector and my game crashed , the issue appeared after reloading. Is it possible to just perform some sort of integrity check when a blueprint loads ? Even if we can’t catch it happening, something like that could at least provide a simple solution

**Comment by tsunamayo** [comment]
@pinesh Well this now what I have done, it is not even an integrity check (which I do for other stuff like deprecated brick ect), I just rebuild the Recyclable Ids list from scratch, so no corruption is possible on reload. Now I guess the issue is to understand and fix the crash. If you have any lead please tell me! Thanks

**Comment by pinesh** [comment]
I certainly wish I did! Like indrasil, I’ve got a problematic blueprint. But I’ve had no luck triggering it on a new build since. You’ll be the first one to know if I encounter it again. In the meantime. Knowing that I can just restart locally and have it fixed is good for my single player experience

**Comment by tsunamayo** [comment]
@pinesh @Kaiser-Indrasil Okay I will close that bug, lest open a new one when you get some lead on a crash during building. It might have been fixed since then for what is worth! Cheers all

**Comment by pinesh** [comment]
Sounds like a plan! Thanks for all the hard work!

**Comment by Kaiser-Indrasil** [comment]
Same here, I'll let you know if I encounter it again. Thanks for investigating!
