### ISSUE TITLE
[Bug] Lag when near CEs

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#4902]
When near the bounds of CEs, frame rate can drop by up to half

https://imgur.com/a/Yqzsq6n

**Comment by ZachZent** [comment]
[Single Occupancy Prison Pod.zip](https://github.com/tsunamayo/Starship-EVO/files/9493711/Single.Occupancy.Prison.Pod.zip)

**Comment by cyberjasse** [comment]
@ZachZent What do you mean by CE ?

**Comment by Kaiser-Indrasil** [comment]
@cyberjasse Child Entities

**Comment by tsunamayo** [comment]
@ZachZent Hi, so I havent been able to reproduce unfortunately, it is steady for me... Could you try to delete a few things around to see what it could be? Not sure it is the CE, it could be the flood light or something else. Thanks

**Comment by tsunamayo** [comment]
@ZachZent Hey mate I hope you are doing good! 
Tell me if you have any news on this. Cheers

**Comment by ZachZent** [comment]
I wish I did because had to factory reset my computer and lost every build since the pre-alpha days...

**Comment by tsunamayo** [comment]
@ZachZent Shit mate that really sucks...
