### ISSUE TITLE
[Inconsistent Behaviour] Thin Tile Triangle cannot clip through pipes

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4905]
### Short Description of the issue:
Unlike the Thin Tile and the Tile Triangle, the Thin Tile Triangle cannon be clipped through by pipes

![image](https://user-images.githubusercontent.com/27857711/188912107-f78689ae-64ef-4249-9143-22a87a581e26.png)

### Steps to reproduce the issue:
- Clip a pipe though a Thin Tile and a Tile Triangle, it works
- Try the same with a Thin Tile Triangle, it cannot

### Environment
- Starship EVO version: 22w33a
- Graphics Card: RX 580

**Comment by Pawnp** [comment]
https://github.com/tsunamayo/Starship-EVO/issues/4889

**Comment by tsunamayo** [comment]
@ProPeach Fixed for 22w38c. Thanks!
