### ISSUE TITLE
Game crashes on every attempt to load a universe

### ISSUE THREAD

**Issue by IKindaCrashAlot** [tsunamayo/Starship-EVO#4906]
### Short Description of the issue:
Game exits out and crashes whenever I try to play 
...

### Steps to reproduce the issue:
Pressed Play- then asked to create new character. Then play with this character. Game goes to loading screen then inevitably crashes on every attempt
...

### Environment
- Starship EVO version: 22w33a
- Graphics Card:  Intel(R) HD Graphics 4400

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@IKindaCrashAlot Hi, sorry to bring you the bad new but your GPU is way below the minimum requirement (it is a 10 year old integrated GPU). Do you confirm it is your normal GPU (sometime people with a dedicated GPU still run the game on their integrated GPU on some portable).
Thanks
