### ISSUE TITLE
[Bug] Basic Building Training - Clipping or Crashing

### ISSUE THREAD

**Issue by Tawapah9** [tsunamayo/Starship-EVO#4911]
### Short Description of the issue:

1. Crashed after deleting two Starter Blocks placed floating halfways into the ground
2. Tried again without crashing but instead clipped throuhg the floor after walking into multiple Starter Blocks placed floating halfways into the ground

### Steps to reproduce the issue:

1. Start the Basic Building Training

2. Continue until learning to use the Codex using tap.

4. Open the Codex under Bricks and drag a Starter Block into slot 2 and close the Codex with tap.

5. Use the largest grid size

6. Start building and deleting multiple Starter Block simultaneously

7a. Game crashed after deleting two Starter Blocks floating half way through the floor.
7b. Walked into the Starter Blocks floating half way through the floor, then falling through the floor / station

### Environment
- Starship EVO version: early-access 22w33a
- Graphics Card: RX 6600 8GB

### Additional information:

Data has been attached
[crash.zip](https://github.com/tsunamayo/Starship-EVO/files/9591796/crash.zip)
[clipping.zip](https://github.com/tsunamayo/Starship-EVO/files/9591834/clipping.zip)

**Comment by tsunamayo** [comment]
@Tawapah9 Thanks for posting this! I keep you posted if I need more information. Cheers

**Comment by tsunamayo** [comment]
@Tawapah9 Hi, so I was able to partly reproduce the issue. It will be fixed for 22w45a. Thanks a lot!
