### ISSUE TITLE
[BUG] Using the middle click menu to copy a brick/paint color does not check if it exists in the toolbar

### ISSUE THREAD

**Issue by daOyster** [tsunamayo/Starship-EVO#4914]
### Short Description of the issue:
When you use the middle-click context menu to select a brick / color from the one you are looking at, the game no longer checks to see if it's already in your toolbar before overwriting your current toolbar selection. This leads to those who are used to that feature ending up with toolbars completely different than what we started off with and if you're like me, 5-6 copies of the same color in my toolbar.

### Environment
- Starship EVO version:  early-access 22w33a
- Graphics Card: RTX 2080 Super

**Comment by cyberjasse** [comment]
What happened before when the selected brick or color was in a toolbar ?

**Comment by daOyster** [comment]
Before it would just select the one that already existed in your toolbar. It made it a lot faster to build since you didn't have to constantly keep scrolling through your toolbars if the brick/color needed was near by. If you do it now, it's easy to end up with a toolbar full of the same couple of bricks / colors.

**Comment by tsunamayo** [comment]
@daOyster Hi, that issue will be fixed for 22w38c. Thanks!
