### ISSUE TITLE
[Suggestion] Allow parameters for hotbar scrolling

### ISSUE THREAD

**Issue by Pawnp** [tsunamayo/Starship-EVO#4916]
When building in Starship EVO, some players will have a set hotbar layout that they're most comfortable with, myself included. However while scrolling through the hotbar of the latest build it will scroll through the various multi-shapes in a single hotbar space. When scrolling from one end to the other it will reset all the blocks to the furthest of the multi-shape group disarranging any preset layout.

![image](https://user-images.githubusercontent.com/72423251/191396942-a80b54cd-2e80-467e-bc0b-fd2acf7aeb89.png)
Above is a set hotbar layout | Below is after scrolling through the hotbar

Although the argument can be made of using just two hotbar spaces for scrolling instead of an entire hotbar row, I personally utilize the scroll and the number pad to navigate through my own hotbar. And when all the blocks are changed from their preset space it becomes rather annoying using the number pad after scrolling the hotbar.

Adding a way to lock a hotbar space or a toggle to disable multi-shape scrolling within the hotbar would be greatly appreciated.

### Environment
- Starship EVO version: 22w38a

**Comment by tsunamayo** [comment]
@Pawnp Hi, thanks for trying the new features. I am not sure to understand, you want to lock a single shape instead of using the multishape? You can from the codex by dragging the little round button on the shape needed to your item bar, it will then always use that shape.
Thanks

**Comment by Pawnp** [comment]
@tsunamayo Oh! That I mistakenly read past that on the new release update list. Thank you for clarifying this, I can rescind this suggest.

**Comment by tsunamayo** [comment]
@Pawnp yeah no problem, I need to add a few explanation somewhere, I think the drag-drop works well but it needs to be discovered by the player.
