### ISSUE TITLE
[BUG] Bevel, Side Rounded, and Hollow Wedge cannot be selected when changed to a Tile variant

### ISSUE THREAD

**Issue by Pawnp** [tsunamayo/Starship-EVO#4917]
### Short Description of the issue:

The Bevel, Side Rounded, and Hollow Wedge within the codex are in the same multi-shape group with the Tiles variants but not in the list of the Tile multi-shape group. Changing the mentioned blocks to a tile variant will cause blocks to become unselectable as they are now Tiles instead. They will only revert back when the game is reset.

![image](https://user-images.githubusercontent.com/72423251/191401136-898c9e5c-7d66-4b02-928b-78cc28bfec2d.png)

### Steps to reproduce the issue:

- Change the Bevel, Side Rounded, or Hollow Wedge within the codex to a Tile variant.
- Attempt to change it back (You can't).

### Environment
- Starship EVO version: 22w38a

**Comment by tsunamayo** [comment]
@Hi, issue is fixed for 22w38b. Thanks!
