### ISSUE TITLE
[Bug] 4 Identical brick sub menus in the codex

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4919]
### Short Description of the issue:
![image](https://user-images.githubusercontent.com/27857711/191516491-a341230f-fcec-4ac0-aa75-e936d9859082.png)
These all contain the same bricks. Also, the bevelled corner brick is missing from the new codex.
Can't remember the exact name, but this one
![image](https://user-images.githubusercontent.com/27857711/191516720-db8d506b-aa99-4bb6-9573-b964dd1b8e41.png)

### Steps to reproduce the issue:
- Open up the new codex and check the Construction tab
- Search for the bevelled corner brick

### Environment
- Starship EVO version: 22w38a
- Graphics Card: RX580

**Comment by COMICLER** [comment]
yeah it seems like some blocks dont even exist in the menus as well, personally i prefer the old way better

**Comment by ProPeach** [comment]
@COMICLER which missing bricks did you notice? It'd be useful to know so they can be put back

**Comment by COMICLER** [comment]
So ik the hollow wedge isnt in the menu anymore it just defaults the the 4 identical stacks, thats the one ik for sure, but it fells like more are missing

**Comment by Pawnp** [comment]
already fixed
https://github.com/tsunamayo/Starship-EVO/issues/4917

**Comment by tsunamayo** [comment]
@ProPeach Yes sorry that bug was fixed yesterday, I will upload the fix asap. Thanks!
