### ISSUE TITLE
[Bug?] Cannot drop 10x or 100x into inventory

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4920]
### Short Description of the issue:

Regarding this part of the patch notes -
_**Right click while dragging an item to drop a single unit. SHIFT-right click to drop 10x, ALT-right click to drop 100x.
=> it become a bit unwieldy to do while holding left button. Should we move to no hold needed to drag, like in minecraft?**_

I can't get it to drop off 10x or 100x. When holding shift right click, it drops off a single brick then clears that slot on the toolbar instantly. When holding alt right click, it only drops off 1. It's possibly that I'm just not doing it correctly, but it doesn't feel very good to hold/hit all those buttons at once. I agree with the move to not need to hold click to drag, like Minecraft.

Also, I noticed that when dragging items on to the hotbar, they're always dropped as 1/8th bricks. If I was working in say 2m scale, I would have to drop hundreds of 1/8th bricks to be able to place a single 2m brick. I suggest that the amount you drop off on to your hotbar scales with the current selected scale, so if I'm working in 2m bricks it drops off 1 x 2m brick rather than 1 x 1/8th brick.

### Steps to reproduce the issue:
- Attempt to drop off 10x or 100x on to a toolbar

### Environment
- Starship EVO version: 22w38a
- Graphics Card: RX580

### Additional information:
Here's my settings file, wondered if that might have anything to do with it
[SETTINGS.zip](https://github.com/tsunamayo/Starship-EVO/files/9617095/SETTINGS.zip)

**Comment by tsunamayo** [comment]
@ProPeach Okay I will check this, indeed the change you mention is necessary. Thanks!

**Comment by tsunamayo** [comment]
@ProPeach Hi, it works fine on my side, I am not sure what is happening on your side... I just hold LMB to drag the item, then press SHIFT or ALT, then finally the RMB to do the drag (I can do the last step multiple time to drop several time). Thanks

**Comment by tsunamayo** [comment]
The suggested change is done. Thanks

**Comment by ProPeach** [comment]
It's probably just user error then, but I still can't quite get it. I tried to take a video with a key logger, but windows didn't record it...
https://user-images.githubusercontent.com/27857711/191719797-a3723781-d095-46b7-bca5-d9218dc8c567.mp4
Slot 1 is just holding LMB to drag the block as normal, slot 2 is holding LMB, then shift+RMB. Slot 3 is holding LMB then alt+RMB.

I'm not sure how you can do the last step multiple times, as whenever I press RMB even with a modifier the block is dropped in to the toolbar

**Comment by ProPeach** [comment]
Also you mentioned the Minecraft like change was done, is it live on 22w38b? I still have to click and drag to grab bricks

**Comment by tsunamayo** [comment]
@ProPeach Nope I havent done that change, it is much bigger to do and will likely cause issues. I put it on my to-do though.
Your issue is when dragging from the codex, indeed I didnt consider that part as Codex is for creative, and toying with quantity is when manipulating items from storage unit / assembler ect.
I will see how I can fix that simply (when you drag from the codex, you drag 1 unit only - this allow qty to not be displayed, which works when you dont consume anything).
Thanks

**Comment by tsunamayo** [comment]
@ProPeach okay I managed to do a quick and not so dirty trick to get it working with the codex without messing the quantities label by default. Fixed for 22w38c. Cheers

**Comment by ProPeach** [comment]
Ah fantastic, thank you!
I did wonder if it was only something related to the codex so I tried dragging from the toolbar in to the assembler inventory and it didn't work there either, I'll try in the new hotfix build and get back to you on that
