### ISSUE TITLE
[Bug] Teleporting to Hovland results in the player underground

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4921]
### Short Description of the issue:
Made a new world for this patch because of #4918 affecting new worlds and teleported to Hovland, only to find myself underground
![image](https://user-images.githubusercontent.com/27857711/191521809-87d95efa-2909-45f0-b885-07331731aaf4.png)
![image](https://user-images.githubusercontent.com/27857711/191521864-93d67eca-6e4b-4a79-8b05-51e3e3020735.png)

### Steps to reproduce the issue:
- Start a new world
- Teleport to Hovland

### Environment
- Starship EVO version: 22w38a
- Graphics Card: RX580

**Comment by tsunamayo** [comment]
@ProPeach Hi, could you confirm you can teleport to  the hovercraft platform fine?

**Comment by ProPeach** [comment]
@tsunamayo I can now teleport to the platform fine in 22w38b. Thanks!

**Comment by cyberjasse** [comment]
hovland is actually not a teleportation destination but an entity

**Comment by tsunamayo** [comment]
@cyberjasse @ProPeach yes correct, teleporting to entity is a debug feature - so I wont really "fix" it. Cheers
