### ISSUE TITLE
[Bug] 22w38b - Fuel tanks on NPC stations and ships 

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4925]
### Short Description of the issue:

It has been discovered that the NPC stations and NPC ships that are generated along with the world upon its creation, spawn with their fuel tanks either severely shrinked or non-existant at all.

### Steps to reproduce the issue:

1. Make a new world
2. Get outside the Starting Station
3. Notice that her orange fuel tanks are way smaller than they should be
4. Find an NPC tanker ship orbiting the station, preferably a Narwhal
5. Notice its fuel tanks completely gone

### Environment
- Starship EVO version: 22w38b
- Graphics Card: 970M

### Additional information:

[Save files](https://github.com/tsunamayo/Starship-EVO/files/9623226/22w38a.zip)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/9623227/Player.log)

![image](https://user-images.githubusercontent.com/63756057/191681074-b40a5d17-7723-4836-84f4-09fcc54731e8.png)
![image](https://user-images.githubusercontent.com/63756057/191681214-005596b1-c79b-458d-bdd6-ae5cbb1b44a0.png)
![image](https://user-images.githubusercontent.com/63756057/191684096-771aef42-db3d-4799-ad27-e93775dfa3f2.png)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Indeed I missed that. Fixed for 22w38c. Thanks a lot!
