### ISSUE TITLE
[BUG] Mining crashes the game 22w38b experimental

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#4926]
The game crashes when I try to mine something...

I believe this is a problem caused by more than one mining beam firing at the same time...

game beta version: experimental
win 10 home basic
gpu gtx 1660
i7-3770
16Gb

https://user-images.githubusercontent.com/73253472/191783264-98564e49-7997-40fb-a4f6-a3e772f9f6db.mp4

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/9627054/Player.log)
[experimental craft.zip](https://github.com/tsunamayo/Starship-EVO/files/9627059/experimental.craft.zip)

**Comment by tsunamayo** [comment]
@Uncle-Ulty Do you get this 100% of the time? I didnt had any issues with several beams last time I checked. 
Thanks

**Comment by Uncle-Ulty** [comment]
yeah. It crashes when I fire multiple mining beams. If I remove all but one, it works ok

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hi, okay I managed to reproduce a crash. I keep you posted!

**Comment by tsunamayo** [comment]
@Uncle-Ulty Okay I managed to fix the issue. Something wrong with Unity unfortunately, so I had to roll my own workaround.
Cheers
