### ISSUE TITLE
[BUG] Crash logs (mining, storage,craft) 22w38b experimental

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#4928]
I had two crashes in this current version, I hope it helps you!

[Crashes.zip](https://github.com/tsunamayo/Starship-EVO/files/9627987/Crashes.zip)

22w38b experimental
win10 home basic 64 bits
i7 - 3770
gtx 1660
ram ddr3 16Gb

**Comment by tsunamayo** [comment]
@Uncle-Ulty Thanks a lot, I am having a look at those! Where those related to mining, UI item drag and drop, or something else?

**Comment by Uncle-Ulty** [comment]
With mining, inventory, ore, crafting, melting, everything.

In this world I built a ship with all current features: mining, storage, conveyor belt, melting, and crafting.

My goal was to make a chain production, from mining to final product in a single ship, with all these devices. But I had several problems that I plan to report piece by piece.

Gonna send you the world

[experimental craft.zip](https://github.com/tsunamayo/Starship-EVO/files/9630663/experimental.craft.zip)

**Comment by tsunamayo** [comment]
@Uncle-Ulty I think it is should be fixed in 22w42a. Thanks a lot, that mining / inventory is proving to be a real pain! Cheers
