### ISSUE TITLE
Put less than 8 stones in furnace storage output infinite stones then crash

### ISSUE THREAD

**Issue by cyberjasse** [tsunamayo/Starship-EVO#4929]
### Short Description of the issue:
I put 7 stones in the furnace storage capacity and stones does not stop to go out of the furnace and it finishes with a crash.

( I have to put the video cursor a bit after the beginning to launch the video on this player )
https://user-images.githubusercontent.com/15956751/191832096-5c6e54fe-6756-44d3-8f9c-2129ddddfe3e.mp4

Just after I stopped the record , a crash happened. see the log file below.

### Steps to reproduce the issue:

- have less than 8 stones in the toolbar
- Open the furnace menu
- Place the stones in the Storage Capacity
- See what goes out
- wait crash. It took 1 or 2 minutes for me.

### Environment
- Starship EVO version: 22w38b [experimental]
- Graphics Card: RTX2070 super
- logfile
[InfiniteOutputStonePlayerlog.log](https://github.com/tsunamayo/Starship-EVO/files/9628792/InfiniteOutputStonePlayerlog.log)

**Comment by tsunamayo** [comment]
@cyberjasse Indeed, it is fixed for 22w39a. Cheers!
