### ISSUE TITLE
Silver word not in the recipes in assembler menu

### ISSUE THREAD

**Issue by cyberjasse** [tsunamayo/Starship-EVO#4930]
### Short Description of the issue:
In the assembler menu, in the required item list, the silver ingot label is just "ingot" .

![missingSilverLabel](https://user-images.githubusercontent.com/15956751/191838136-ab0cb8c4-e27d-4745-9b31-a12e6f2752a2.png)

### Environment
- Starship EVO version: 22w38b
- Graphics Card:

**Comment by tsunamayo** [comment]
@cyberjasse fixed for 22w38c. Thanks for being so active lately! Cheers
