### ISSUE TITLE
[Suggestion] Use "k" to indicate thousands of bricks in inventories

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4933]
### Short Description of the issue:
Thanks for fixing up the 10x and 100x drop off, it's a breeze to do now
One issue I have with readability, is that you can't easily see how many bricks you have when the number is large
![image](https://user-images.githubusercontent.com/27857711/191954281-f79aa3de-d3a3-40eb-bc17-3fb35d4b62c3.png)
Slot 1 holds 35,000 bricks, slot 3 holds 352 but at a quick glance it looks like 35 and 352 due to 35,000 being cut off by the GUI.

Same thing with the Assembler and cargo inventories, it'd be great if this showed 1.2k
![image](https://user-images.githubusercontent.com/27857711/191955577-f58e7d22-9786-407d-a0d3-fbc8c0314efc.png)

I suggest that bricks in the count of thousands have a "k" indicator, so 35,000 would become 35k. For larger, you could show 35m for 35 million, b for billion etc (although a bit excessive for sure).

### Steps to reproduce the issue:
- Drop bricks in the toolbar to a number greater than ~1000

### Environment
- Starship EVO version: 22w38c
- Graphics Card: RX 580

**Comment by tsunamayo** [comment]
@ProPeach Hi, it is done for 22w39a. Thanks
