### ISSUE TITLE
[BUG] Collector blocks affected by 'Tweak Glow Color' option

### ISSUE THREAD

**Issue by Pawnp** [tsunamayo/Starship-EVO#4934]
### Short Description of the issue:

Collector blocks are affected by the 'Tweak Glow Color' option when enabled, thus altering the color to a vibrant shade when painted. Unless the Collector block was intentionally to be considered as a glow block, the Collector block shouldn't be affected by the 'Tweak Glow Color' option.

![image](https://user-images.githubusercontent.com/72423251/192047298-6f508378-51ac-44af-a429-641e6dbc7857.png)

### Steps to reproduce the issue:

- Color a Collector block with the 'Tweak Glow Color' option enabled with a darker variant of a color

### Environment
- Starship EVO version: 22w38c

**Comment by tsunamayo** [comment]
@Pawnp Thanks for the catch. It is fixed for 22w39a. Cheers!
