### ISSUE TITLE
[Suggestion] Add some kind of conveyor belt direction indicator

### ISSUE THREAD

**Issue by Womble-TC** [tsunamayo/Starship-EVO#4935]
Currently there is no way to indicate which way the conveyor belt will move objects when placing them.

Here are some possible ways to maybe indicate direction:

![image](https://user-images.githubusercontent.com/29961381/192057396-ec77478e-1be5-4168-9a88-b77630a9c9f0.png)
![image](https://user-images.githubusercontent.com/29961381/192057409-d04366ed-d1e7-4f8e-8650-799597f24510.png)

**Comment by tsunamayo** [comment]
@Womble-TC Hi, well I wanted to add a small screen on the side with an arrow. I will add the arrow preview, but just note that you can reverse the direction in the brick UI.

**Comment by Womble-TC** [comment]
I know about changing the direction in the UI, but for a new player, it might not be that obvious

**Comment by tsunamayo** [comment]
@Womble-TC So I just added the little preview arrow, for 22w39a. Thanks!
