### ISSUE TITLE
[Suggestion] Add some kind of 'cap' similar to the pipe for the tube

### ISSUE THREAD

**Issue by Womble-TC** [tsunamayo/Starship-EVO#4937]
### Short Description of the issue:

The current tube lacks any way to bridge the gap between it and the tube and the object its connecting to. (Sorry for yet another QOL feature request)

### Environment
- Starship EVO version: 22w38c

### Additional information:

![image](https://user-images.githubusercontent.com/29961381/192062178-5564d6cb-bedc-4b1c-bf1a-766a4d187398.png)

**Comment by tsunamayo** [comment]
@Womble-TC Added for 22w39a. Thanks!
