### ISSUE TITLE
[Bug] 22w38c - Thin Tile Triangle armor block produces a long-distance glow effect

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4941]
### Short Description of the issue:

The Thin Tile Triangle block which you carried over from its glowing counterpart, doesn't indeed glow when viewed in close distance.
However, when painted in a bright color, it still produces the long-distance glow circle sprite when viewed at a distance.

### Steps to reproduce the issue:

1. Boot up the game and load the save provided
2. Build a Thin Tile Triangle block and paint it some vibrant, bright hue
3. Get away from it and notice the glow sprite fading in, having the color of the block itself

### Environment
- Starship EVO version: 22w38c
- Graphics Card: 970M

### Additional information:

[22w38c.zip](https://github.com/tsunamayo/Starship-EVO/files/9645864/22w38c.zip)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/9645870/Player.log)

![image](https://user-images.githubusercontent.com/63756057/192266439-7f14312e-7302-4b29-ac64-6b30af1e38cf.png)
![image](https://user-images.githubusercontent.com/63756057/192266503-6cd2cd5c-ab5c-4421-a195-c4b8522db3ed.png)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Indeed! Fixed for 22w39a. Cheers
