### ISSUE TITLE
[suggestion] crasg logs and frozen screen

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#4942]
In recent tests to check for bugs, I noticed that frozen screens don't create "crash logs". If the game freezes but doesn't close/crash, no crash report is created...

I'd recommend creating "freeze reports" also, or just considerate freezing as a different kind of crash.

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hi, unfortunately I dont get to decide what Unity/Windows is doing when this happens...
