### ISSUE TITLE
[Bug] [Regression] 22w39a - Light emission formula changed for tile blocks

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4944]
### Short Description of the issue:

There's two issues with this bug:

1. The light emission formula changed for the tile blocks, which results in a different lighting compared to 22w38c. This might be linked either to #4941 or to the introduction of hoses.
2. The glow tiles cannot be turned off using logic OR their state changes to 'off' but their lighting doesn't.

### Steps to reproduce the issue:

1. Launch the game in the version 22w38c or on the default branch
2. Load the save provided
3. Notice the lighting on the glow tiles on the spaceship
4. Close the game and change the version to the Experimental 22w39a
5. Load the save provided
6. Notice the change in the saturation and bloom on the glow tiles on the spaceship

### Environment
- Starship EVO version: 22w39a
- Graphics Card: 970M

### Additional information:

[22w39a.zip](https://github.com/tsunamayo/Starship-EVO/files/9683544/22w39a.zip)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/9683546/Player.log)

A - 22w38c

![A - 22w38c](https://user-images.githubusercontent.com/63756057/193256515-5e8cfeae-891d-4823-b175-ada220086912.png)

A - 22w39a

![A - 22w39a](https://user-images.githubusercontent.com/63756057/193256567-efc8c40d-ae83-437c-b3ac-2945ea446aaa.png)

B - 22w38c

![B - 22w38c](https://user-images.githubusercontent.com/63756057/193256611-2adf7dae-25d1-4a23-8cf3-b5d26e8c7aef.png)

B - 22w39a

![B - 22w39a](https://user-images.githubusercontent.com/63756057/193256654-75eaac31-cb3a-4861-923e-1a4e866ce1e9.png)

C - 22w38c

![C - 22w38c](https://user-images.githubusercontent.com/63756057/193256685-ea0a3715-b269-4f73-8e70-25e20fdc2dea.png)

C - 22w39a

![C - 22w39a](https://user-images.githubusercontent.com/63756057/193256752-1f3285ab-1fc1-498b-b5e9-03a294766cf4.png)

D - 22w38c

![D - 22w38c](https://user-images.githubusercontent.com/63756057/193256768-d2ca2124-cc5c-4a5c-97e1-e9a0b89dd865.png)

D - 22w39a

![D - 22w39a](https://user-images.githubusercontent.com/63756057/193256783-4c88c695-6efe-4cca-a128-00b03ddb1c16.png)

**Comment by zalexville** [comment]
I also noticed this when pulling a build into experimental to check the changes made to the game. 
The warp nacells (engines using glow tiles) became very dark and you can see the sun glinting off the glow tiles in the engines. 

22w33a (Stable):
![20220926180755_1](https://user-images.githubusercontent.com/65626266/193417169-075dd538-e238-4a07-bed6-77c50860e63f.jpg)

22w39a (Experimental):
![20220930213449_1](https://user-images.githubusercontent.com/65626266/193417168-85df6930-3868-43cc-8d90-d79ba57a42dd.jpg)

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo I've decided to work on the glow tiles on the Experimental and while I've gotta put in some work, I actually like the new formula better, because it's way more predictable, linear, and it allows for some very wide color range compared to the previous formula.

Pre-change:

![image](https://user-images.githubusercontent.com/63756057/193442809-29eba2ef-74fe-4300-9f98-07f61c3ad990.png)

Post-change:

![image](https://user-images.githubusercontent.com/63756057/193442814-4edf2ad8-d272-4b22-ba2e-6136762524fe.png)

**Comment by Kaiser-Indrasil** [comment]
Duplicated by #4949

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Hi, this is fixed for 22w41a. Thanks!

**Comment by Kaiser-Indrasil** [comment]
As per my suggestion in #4954 could you please revert this change?
