### ISSUE TITLE
[bug] Experimental mode doesn't open

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#4945]
Since the last update, the game doesn't open. The menu song plays, but I can't interact with the game itself. It bugs my computer and I'm forced to restart it...

gtx 1660
i7 3770
16Gb ram
win 10 home basic
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/9686899/Player.log)

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hi, well the log seems to indicate it load something. Is the log the one from the freeze? Maybe it didnt generate any?
In any case it might be because of your character save as other people are fine, so could you please zip me all your character, I will see if I can reproduce. Thanks!

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hi, I know, it is just that it might be possible that an error happen when just simply building the list of character you can load, before any proper save load. This is why I asked all of them, but I guess it might not have been that, and simply some Steam shenanigan. 
Cheers
