### ISSUE TITLE
[BUG] Hose connection points disappear after disconnecting

### ISSUE THREAD

**Issue by Pawnp** [tsunamayo/Starship-EVO#4946]
### Short Description of the issue:

Hose connection points disappear after disconnecting, specifically when one or both points are on a child-entity.
![image](https://user-images.githubusercontent.com/72423251/193342779-1ff31bd2-bf93-4847-a1e7-011d81ce6f25.png)

### Steps to reproduce the issue:

- Place one or both hose points on a child-entity
- Connect both points
- Disconnect the points by either deleting a point or manually disconnecting

### Environment
- Starship EVO version: 22w39a

**Comment by tsunamayo** [comment]
@Pawnp Indeed, this will be fixed for 22w41a. Cheers!
