### ISSUE TITLE
[SUGGESTION] setting for adjusting how scrolling works

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#4947]
I recently sat down and actually built something in game for the first time in probably months and I love all of the new changes except for the multiple blocks in one slot 
thats kind of an exaggeration I think its great i just find that it slows down my building process too much
if possible it would be nice to be able to check a box in the game settings that makes it so that i have the option of holding down a button like ctrl and only then will it let me scroll through block options  

Congrats on the baby btw!

**Comment by Kaiser-Indrasil** [comment]
You can drag and drop individual bricks to the toolbar by dragging of the dot icons underneath the block in the codex, rather than the block itself.

**Comment by ProPeach** [comment]
I still mostly use individual bricks for hull types and most shapes, but I do like the new multi slot feature for less used bricks like thrusters or pipe types.

I think the existing option to use single bricks like before could be made more obvious though. Perhaps like the old Skywanderers codex GUI, where you click on/mouse over a brick and then a window appear with all the different sub types to choose from?

**Comment by TIKIRobo** [comment]
for me i like to scroll up and down my hotbar instead of reaching for my number keys, are you saying there's a way to scroll without switching though blocks or that you use the number keys to switch blocks avoiding the annoying scrolling?

**Comment by ProPeach** [comment]
The method Indrasil mentions is a way to grab the individual bricks from the codex like we did before, rather than grabbing the icon for 5 armour blocks and having to scroll through all of them. This way you can choose which bricks you want directly on your toolbar, and which you want condensed into a stack that you have to scroll through

**Comment by TIKIRobo** [comment]
oh thank you! i had tried to do that but it didn't work the first time so i didn't think that was an option
