### ISSUE TITLE
[Bug] [Experimental] Invisible large ships

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Starship-EVO#4948]
### Short Description of the issue:

I recently tried to load a large blueprint in experimental and it went invisible, except for the lights. After some experimentation we believe it looks like the game has developed a ~400k brick limit between stable and experimental.

### Steps to reproduce the issue:

Load a blueprint for a large ship like the one attached at the bottom of this post.

### Environment
- Starship EVO version: 22w39a
- Graphics Card: RTX 3060

### Additional information:

![image](https://user-images.githubusercontent.com/43644633/193636945-29a360e0-155c-41f1-ae25-c86d22304c67.png)
![image](https://user-images.githubusercontent.com/43644633/193637010-67059234-0639-4350-b145-5fa5ffb8626d.png)
![image](https://user-images.githubusercontent.com/43644633/193637049-bbf5fa26-2ebb-49d7-a472-d12ff327e25b.png)

[ISD Some progress has been made 20.zip](https://github.com/tsunamayo/Starship-EVO/files/9699463/ISD.Some.progress.has.been.made.20.zip)

**Comment by ProPeach** [comment]
I reproduced this too. Seems like as soon as around 400k bricks are present in the world, all bricks on all entities in the world turn invisible. You can revert this by unspawning some blueprints to lower the global brick count and then reloading. As Gmunga notes the issue is only present in Experimental, there is no issue in the Default branch

**Comment by tsunamayo** [comment]
@Garrett-C Hi, nice progress indeed! Issue is fixed for 22w41a. Cheers ;)
@DrizztCode Okay thanks for reporting this, it might be the same issue or something else it seems hard to replicate. Could you test again once 22w41a is out and tell me the outcome? If do not work you can book a new case!  Thanks for your help

**Comment by DrizztCode** [comment]
@tsunamayo - thanks - yes i will let you know once 22w41a is out - i have also had the conveyor belt turn invisible on occasion - but again, no solid replication strategy yet - i shall keep you posted - thanks for all the awesome work :-)
