### ISSUE TITLE
Glow tiles can’t be turned off and don’t work with RGBs

### ISSUE THREAD

**Issue by TwoNiner29** [tsunamayo/Starship-EVO#4949]
### Short Description of the issue:

The glow tiles can’t be turned off anymore and don’t work with RGB controllers
...

### Steps to reproduce the issue:

Put down a glow tile and try to turn it off with a switch or control it with a RGB gate

**Comment by tsunamayo** [comment]
@TwoNiner29 Hi, indeed that was a regression, this will be fixed for 22w41a. Cheers
