### ISSUE TITLE
small bug with multi-shape bullets after we close the codex or container

### ISSUE THREAD

**Issue by cyberjasse** [tsunamayo/Starship-EVO#4950]
### Short Description of the issue:

The video below is more understandable.
When we have a multi-shape in a access bar (the switch in the video) , we select it, we change the access bar, we open the codex or the inventory of a container then we close it, there are bullets under where the multi-shape icon was even if it is not in the current access bar. There are other multi-shape in my inventory so it seems that the issue is only for the last multi-shape selected.

[video](https://youtu.be/VQnUH0XoPk8)

### Steps to reproduce the issue:

- put a multi-shape in the access bar
- select it
- move on another slot
- switch to another access bar
- open the codex or the inventory of a container
- close it
- The bullets to select the shape of the previously selected multi-shape reappear even if you are not in the access bar containing the multi-shape.

### Environment
- Starship EVO version: 22w39a
- Graphics Card: 

### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/9718631/Player.log)

**Comment by cyberjasse** [comment]
My video recordings seems to not load on github. I try to fix it

**Comment by cyberjasse** [comment]
The recording plays well on youtube. I changed the video with a youtube link

**Comment by tsunamayo** [comment]
@cyberjasse Hi, thanks issue is fixed for 22w41a. Cheers
