### ISSUE TITLE
[Bug] [22w39a] Handheld Beam Weapon Graphical Glitch (and drop on reload)

### ISSUE THREAD

**Issue by DrizztCode** [tsunamayo/Starship-EVO#4952]
a picture paints a thousand words (and since i have a habit of using too many words, this is probably for the best lol):

![20221009025516_1](https://user-images.githubusercontent.com/104569043/194735019-40faafec-cb00-4207-b8fb-e3abdd91c562.jpg)

happens with mining beam or beam weapon

other issue is that on a reload all my handheld weapons are getting dropped in the world, even if none of them were equipped

anyone else seeing these issues? or is there something weird going on at my end (can't imagine what that might be though)

just to confirm, i'm on experimental build 22w39a

thanks :-)

UPDATE: the beam offset issue is not present on the default branch (22w33a):

![20221009134258_1](https://user-images.githubusercontent.com/104569043/194757804-0749bf05-6116-4c90-9e24-91732a9c31db.jpg)

so probably not just me then :-)

**Comment by cyberjasse** [comment]
the issue where the handheld is dropped on reload, yes i have it too systematically

**Comment by DrizztCode** [comment]
> the issue where the handheld is dropped on reload, yes i have it too systematically

that's good to know - by systematically, do you mean sometimes? or all of the time?

and are you not getting the laser beam offset for handheld weapons then? coz if not then there must be something weird going on in my game! i might try going back to each of the available earlier builds and see if i get it on those

thanks for the reply :-)

**Comment by cyberjasse** [comment]
@DrizztCode systematically means everytime.

I tested my handelheld mining tool today in 22w39a and the beam has on offset too like in your screenshot . I did not observerd that in the 22w38 versions.

**Comment by DrizztCode** [comment]
> @DrizztCode systematically means everytime.
> 
> I tested my handelheld mining tool today in 22w39a and the beam has on offset too like in your screenshot . I did not observerd that in the 22w38 versions.

ah - cool - good to know (both bits) - glad that it is simply a bug in the game and not a bug with me or my system lol :-)

**Comment by tsunamayo** [comment]
@DrizztCode @cyberjasse The beam starting point, end point and floating weapon bug are fixed for 22w41a. Thanks!

**Comment by DrizztCode** [comment]
@tsunamayo - awesome! - thanks! :-)
