### ISSUE TITLE
[Bug] [22w39a] Furnace not accepting stone in the input hopper

### ISSUE THREAD

**Issue by DrizztCode** [tsunamayo/Starship-EVO#4953]
so i  can manually place stone in a furnace - but it won't accept it through the input hopper on a belt

i am suspecting that the issue may be that it is the only recipe that requires multiple counts of an ore, and so is refusing to accept anything other than exactly 8 ore through the input hopper maybe? (which is of course impossible to give it)

sorry if i am misunderstanding stuff - but i can't see a way to pipe stuff into the furnace so the only way to feed it is through the input with a belt, or manual insertion through the interface - and we can't filter stone (so far as i am aware) so that it doesn't block the belt

anyway - apologies if i am missing stuff

thanks again for the awesome game and all the hard work - i'm excited to play the new build! :-)

**Comment by tsunamayo** [comment]
@DrizztCode Indeed, issue is fixed for 22w41a. Thanks a lot!
