### ISSUE TITLE
Furnace progress bar stay full

### ISSUE THREAD

**Issue by cyberjasse** [tsunamayo/Starship-EVO#4955]
### Short Description of the issue:

The progress bar in the furnace UI stay full. This bug is recent.

### Steps to reproduce the issue:

- Interact with a furnace. the progress bar is already full.
- put ore in furnace. The progress bar stay full but the furnace works.

### Environment
- Starship EVO version: 22w41a
- Graphics Card: RTX2070 super

**Comment by tsunamayo** [comment]
@cyberjasse Indeed, this is fixed for 22w42a. Thanks!
