### ISSUE TITLE
[Bug] [22w41a] - inventory freeze when items are flowing through the inventory

### ISSUE THREAD

**Issue by DrizztCode** [tsunamayo/Starship-EVO#4956]
when inserting items into an inventory when stuff is flowing through that inventory the game will freeze

i have tested with a furnace and a collector

with the furnace it was quick just need to put 8 rocks in and then continue clicking stuff into the inventory slots

with the collector it will be fine while not collecting, you can insert stuff in the inventory as much as you want - but as soon as it is collecting it is quick to freeze while inserting

i made 2 short videos (less than 30 seconds each):
https://youtu.be/D9NHtreW7TI (furnace)
https://youtu.be/sd20Ezwod1o (collector)

i hope this helps

thanks as always :-)

[NOTE FOR PEOPLE GETTING FREEZES]
for anyone who encounters freezing there are two ways to get out of it without signing out (which is the only way if you give the game enough time to switch its picture after it freezes - it seems to revert to the last saved frame or something, but not for a few seconds)

so - if your game freezes

1. immediately alt-tab - do not ctrl-alt-escape or ctrl-alt-delete since they don't seem to force the game to relinquish its lock on the fullscreen mode
2. if you do it in time you will be back at windows, but without your mouse pointer
3. now ctrl-alt-escape to open task manager
4. use the down arrow key to highlight SEVO
5. hit delete to close it

if you don't manage to catch it before it locks the system then you will need to use the Windows key to sign out

but, if you have an unsaved notepad document that will allow you to cancel the sign out but SEVO will have closed - as well as some other things - but it shouldn't have closed Steam for example

**Comment by tsunamayo** [comment]
@DrizztCode Hi, thanks for being so active lately! So I can reproduce the bug, I keep you posted.

**Comment by tsunamayo** [comment]
@DrizztCode Thanks a lot for that one, I was able to finally fix it, I think it was the bulk of the "hard to reproduce" issue we had for some time. Fixed for 22w42a. Thanks!

**Comment by DrizztCode** [comment]
> @DrizztCode Hi, thanks for being so active lately! So I can reproduce the bug, I keep you posted.

ironically i was not so active the past few days and so missed this post! :-)

i shall be loading up the new build in the next few moments and look forward to actively helping out while having some fun :-)

**Comment by DrizztCode** [comment]
> @DrizztCode Thanks a lot for that one, I was able to finally fix it, I think it was the bulk of the "hard to reproduce" issue we had for some time. Fixed for 22w42a. Thanks!

always happy to help - thanks for all the hard work and the awesome game :-)
