### ISSUE TITLE
[Bug] [22w41a] Inventory emptying on reload and being inaccessible until activated 9 times (yes i'm not joking, it's 9)

### ISSUE THREAD

**Issue by DrizztCode** [tsunamayo/Starship-EVO#4957]
so this is two bugs - but they may be related - since from a cold start (from windows), inventory seems to be immediately accessible and its contents preserved - but on reloads the inventory is not accessible until it has been activated 9 times (yes, really), at which point it is available but empty

i made a video:
https://youtu.be/xcWUsHVVl-0

recreation steps:

1. mine some ore
2. check it's there (was purely a coincidence that i mined 22 each time)
3. exit to title
4. reload (i cut out most of the loading time)
5. activate the collector
6. if inventory UI isn't there, repeat step 5, eight more times
7. inventory UI will show up, but will be empty

repeat if required to confirm that it really is always 9 times 

weird right? (may be something to do with the cargo inventory starting with 8 slots)

i haven't made a video for cold starting, but it seems to be pretty consistent - if you mine a little ore then exit to desktop and reload - inventory is accessible immediately and ore is there - then exit to title and reload - inventory inaccessible until activated 9 times - and will then be empty

still loving the game - gonna be the best survival mode ever when we get there :-)

**Comment by DrizztCode** [comment]
sorry i had the video private - is now unlisted so can be viewed

**Comment by tsunamayo** [comment]
@DrizztCode Hi, issue is fixed for 22w42a. Thanks again!
