### ISSUE TITLE
[Bug] [22w41a] Big load of ore will jam the collector, and more of the rule of 9 (spread across multiple blocks)

### ISSUE THREAD

**Issue by DrizztCode** [tsunamayo/Starship-EVO#4958]
2 more bugs - one i think was reported by Uncle-Ulty in their big mining post - but i thought i would give it its own post - and its own video

when you mine a big load of ore the collector stops collecting it - but keeps it trapped in its field - and keeps playing the collecting sound - and will even drag the ore around when you move - and even when you lose some of it, the collector still seems to be internally tracking it - since even when the field wasn't visible, and the sound wasn't playing, i have had a freeze when interacting with the inventory (which is a pretty good indication that an inventory has stuff flowing around under the hood)

and the other bit is a continuation of the 9 activations required to make inventory accessible on reload (albeit empty) - but showing that the 9 activations can be spread between blocks - but is still 9

anyway - video here:
https://youtu.be/ZoivBXzRz-U

recreation steps:

1. mine a big load of ore with a collector with a big enough range
2. wait till the ore has all been scooped but the collecting sound is still playing
3. look in the inventory and see how much is there
4. go see the ore bouncing in and out of the collector
5. check the inventory and see it not change
6. fly away and watch the ore follow you, but not get collected

and for the rule of 9

7. exit to title
8. reload
9. open the collector
10. if the inventory isn't shown, repeat step 9 twice (= 3)
11. open the furnace
12. repeat step 11, three more times (= 7)
13. repeat step 9 twice (= 9)

boom - inventory shown - but probably empty

also - i'm pretty sure the mixed rock types aren't relevant for the collector jamming - i have had it jam with mixed types or single types

anyway - as ever - still loving the game - and i hope this helps :-)

**Comment by DrizztCode** [comment]
sorry i had the video private - is now unlisted so can be viewed

**Comment by tsunamayo** [comment]
@DrizztCode I think this issue will be fixed for 22w42a, please re-open the case if you still see this after the patch is live! Thanks

**Comment by DrizztCode** [comment]
> @DrizztCode I think this issue will be fixed for 22w42a, please re-open the case if you still see this after the patch is live! Thanks

cool - i will do - although i am unsure if i am able to reopen closed issues - but if i can't i will raise a  new issue which we can then delete if you want to reopen this one - but hopefully it won't come to that and everything will be perfect :-)

thanks again for all the hard work! :-)
