### ISSUE TITLE
[Bug] [22w41a] Infinite ingots, copper to iron, ingots as furnace inputs, clicking can delete hotbar inventory

### ISSUE THREAD

**Issue by DrizztCode** [tsunamayo/Starship-EVO#4960]
so a bunch of furnace things - the ingot stuff is in the video - the clicking a hotbar item and having it disappear is just something that i have noticed happen and happened while i was testing this, but not on the video

https://youtu.be/KLjvDUpvp3Y

1. put one coper ore in the furnace
2. most of the time two ingots will come out, both labelled iron
3. one will be infinite
4. put an ingot in the furnace input (any ingot, i tried with silicon and the copper/iron thing)
5. it will be expelled as an infinite ingot

good luck on this one - hope it doesn't stress you out! (it seems like there's just so much going on under the hood!)

thanks again for all the hard work :-)

**Comment by cyberjasse** [comment]
It can be the same error than one of the error reported in https://github.com/tsunamayo/Starship-EVO/issues/4922  where I had a silver ingot that I can grab an infinite time. I did not find a way to reproduce it. Its perhaps my way to feed the furnace wich is different from yours : I launch a bunch of ores to its entry.

**Comment by DrizztCode** [comment]
> It can be the same error than one of the error reported in #4922 where I had a silver ingot that I can grab an infinite time. I did not find a way to reproduce it. Its perhaps my way to feed the furnace wich is different from yours : I launch a bunch of ores to its entry.

yeah - there is definitely some overlap with your post

hopefully the steps and the video will help to show how it can be reproduced

and yes - i am feeding the furnace directly by placing items in its inventory (you can see in the video)

i have had similar results with items flowing through the system using conveyor tubes and collectors and cargo containers - but there are currently many additional issues with those systems that can cause items to disappear - so direct insertion seemed the best way to isolate this one

hopefully it will help in resolving this bit of the puzzle! :-)

**Comment by tsunamayo** [comment]
@DrizztCode Hi, as I fixed several issue and cannot reproduce this one, I think it should be good for 22w42a. Tell me if it is not the case! Cheers
