### ISSUE TITLE
[Suggestion] Bring back the glow tile light formula from 22w39a

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4961]
(Making a separate ticket for the sake of clarity)

Hey, this is kind of awkward but regarding the #4944 I came around to really liking the new light formula for the tiles introduced in 22w39a. ^^

And I liked it so much, I would love to see its comeback.

I know this sounds like a fix reversion, especially since I was the one to report the issue, but please hear me out.

Sadly, I don't have any screenshots of glow tiles from 22w39a but I can describe them as properly vibrant and providing a linear, predictable color range outcome.
Aside from a slight vignette in case of very dark hues, that formula was perfect.

However, when I started experimenting on the color values in today's hotfix (22w41a), not only was I unable to reproduce the very nice and vibrant hues back from 22w39a, but also I noticed an unexplicable tonal shift towards purples?? In a completely blue color without any reds?

Not to mention, I've never noticed this, but the new-old formula from 22w41a makes the colors bland and washed out:

![195282246-c74ff61e-a395-4d66-bd37-04fa23e802f1.png](https://user-images.githubusercontent.com/63756057/195473420-ba0ec173-edfd-48fd-9b05-dc1b813b3f68.png)

All that said, despite the fact that you essentially brought back the old light formula for the glow tiles, I really came around to the one you introduced in 22w39a and would love to have it back, especially since it was more in line with the other light emittables.

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Hi, I will have a look at it but from what I recall it was a bug with the formula. Now I think that the current (and correct) formula will "boost" the color and make it more white-ish, as used for light. Could we have the opinion of other people as will also impact their build! 
Cheers

**Comment by ProPeach** [comment]
Looking at the comparison images from #4944, I do actually like the formula from 22w39a and how it is closer to the regular paint colour. Perhaps the Tweak Glow Coloir setting could be used to differential between the truer to colour look and the more whitish look?

**Comment by Kaiser-Indrasil** [comment]
I would be fully satisfied with @ProPeach suggestion.

On one hand, we can keep the Tweak Glow Color OFF formula as is, so that most players' spaceships remain unchanged.

On the other hand, the current Tweak Glow Color ON option makes the tiles almost white and even more washed out, and this is where the glow formula from 22w39a could replace it, making the tiles more vibrant.

It's a win-win I think

**Comment by tsunamayo** [comment]
@ProPeach @Kaiser-Indrasil I cant use a different shader code depending on what setting you used when placing the brick unfortunately. I updated the shader formula though, so they will look less white and more like the color you input like you requested.
Cheers
