### ISSUE TITLE
[Bug] Various issues with the Quick Select tool

### ISSUE THREAD

**Issue by piotmetans** [tsunamayo/Starship-EVO#4962]
Heya! I've been messing around a bit with the new "multi-shape" function to try maximizing my item bars, and noticed a few issues.

Case 1:
Using the quick select menu (middle mouse clicking a block) to select either a block or a color/material no longer replaces the current item bar selection when all item bar slots are already occupied.

Case 2:
I've noticed this issue also applies to any "multi-shape" stacks that are in my item bars. Let's say my item bars are completely filled with various items, including the generic hull multi-shape stack, which has the normal cube block selected. My current item selection is a color, and I'm ready to switch to a sloped hull block with the quick-select menu. When I do so, the item bar selection switches to the hull multi-shape, but does not switch to the slope automatically, it still is showing the normal cube selection.

### Steps to reproduce the issue:

Fill all of your item bars with differing items until completely full, including some multi-shape stacks if you'd like. Select an item in the world that is not located on your item bars (except perhaps items in the multi-shapes, but are not selected) through the middle-mouse quick select tool. The item will neither replace your current item or swap to the correct item in the multi-shape.

### Environment

- Starship EVO version: 22w41a
- Graphics Card: RTX 2070 Super

**Comment by tsunamayo** [comment]
@piotmetans Indeed, this will be fixed for 22w42a. Thanks a lot!
