### ISSUE TITLE
[Bug] 22w42a - Glow Tile Triangles are the only ones to receive the light formula update

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4965]
### Short Description of the issue:

I've noticed that you've rolled back the old light formula for the newer glow elements as per #4961.
Thank you for that, Tsuna!
However, only the Glow Tile Triangles seem to have received the update.
All the other 5 elements - Glow Squares and all 4 kinds of the Glow Pipe - still use the glow tile formula from 22w41a.

### Steps to reproduce the issue:

1. Launch the game in 22w42a Experimental version
2. Launch the save provided
3. Play around with different colors and notice that only the Glow Tile Triangles have the newer, more vibrant color

### Environment
- Starship EVO version: 22w42a
- Graphics Card: 970M

### Additional information:

[Save files](https://github.com/tsunamayo/Starship-EVO/files/9827977/22w42a.zip)

![image](https://user-images.githubusercontent.com/63756057/196900312-ebac1c52-fbf7-4d7c-92bb-a7792b57df07.png)

**Comment by tsunamayo** [comment]
Yes sorry I did the change in code but I forgot to rebuild my material definition asset, I will repush a patch today.

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil I am repushing the build now. Thanks for the heads up!
