### ISSUE TITLE
[Bug] 22w42a - Tank Joints cannot be placed on reactors, warp cores, and lightcruise engines

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4966]
### Short Description of the issue:

I've noticed that it's not possible to place down Tank Joints on and between:
- Reactors
- Warp Cores
- Lightcruise Engines

### Environment
- Starship EVO version: 22w42a
- Graphics Card: 970M

### Additional information:

Lightcruise Engine:
![image](https://user-images.githubusercontent.com/63756057/196926543-95017d48-68e2-4afc-bba2-5fdd3baa3f4a.png)

Reactor:
![image](https://user-images.githubusercontent.com/63756057/196926670-ae329b5d-2541-4e7a-b718-f6a0305b22dd.png)

Warp Core:
![image](https://user-images.githubusercontent.com/63756057/196926728-6a36baaa-9564-43c3-9764-c618e28cc308.png)

Tank 1:
![image](https://user-images.githubusercontent.com/63756057/196927879-baccdd04-a247-4951-aef3-965d6b63e6c9.png)

Tank 2:
![image](https://user-images.githubusercontent.com/63756057/196927948-3223293a-7777-4824-96a9-66bf6bd03fbd.png)

**Comment by ProPeach** [comment]
When this case is closed #4631 can be closed too 👍

**Comment by Kaiser-Indrasil** [comment]
Woops! Sorry for the duplicate!

**Comment by ProPeach** [comment]
That issue is half a year old lol, safe to say it was time for a refresher

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Hi, thanks it is now fixed for 22w43a. Cheers!
