### ISSUE TITLE
[Bug] [22w42a] Collector Freeze If Bugged Out From Heavy Mining

### ISSUE THREAD

**Issue by DrizztCode** [tsunamayo/Starship-EVO#4968]
Sorry :-(

But mostly things are much much better - can interact with the inventories while stuff is flowing - but once the collector bugs out things go crazy!

so - i made 2 videos - first one is after the collector is already bugged out, and i go in and you see the inventory going crazy and then i interact and we get the freeze - second one i show the inventory working fine, then i do the mining to show the amount needing to be done and the sound to listen for, then i show the inventory going crazy, then i fly far enough away that the inventory stops going visibly or aurally crazy, and the collector field disappears - and then i interact with the inventory and we get the freeze

each video has the steps to reproduce in the description - but i will repeat them here:

https://youtu.be/OERG4cgNaR8 (24 seconds)

(please ignore the ingots - i already had them in there - they are not relevant lol)

steps to reproduce:
1. mine ore until the collecting sound frequency becomes faster
2. stop mining - you should find that the sound keeps repeating
3. if not repeat from step 1
4. go into the collector inventory and the sound will go crazy (possibly visuals too)
5. interact with it for a few moments
6. freeze

https://youtu.be/Z4laAOlPIKo (1 min 9 seconds)

steps to reproduce:
1. mine ore until the collecting sound gets faster
2. stop mining and the sound should continue indefinitely
3. if not repeat from step 1
4. fly away from the ore that is stuck in the collector until it stops following you and the collector field disappears
5. interact with the collector inventory for a few moments
6. freeze

apologies as always to be the bearer of bug reports (especially this one) - but like i said - inventory is so much more stable now - only got these freezes when the collector bugged out like this

as always, love the game, and massive thanks for all the hard work :-)

**Comment by tsunamayo** [comment]
@DrizztCode Hi, I cant really reproduce the inital issue (the only one that matters, once things start to bugs all sort of weird stuff can happen). Do you reproduce this easily? If you could you please send me your player save? Thanks

**Comment by DrizztCode** [comment]
> @DrizztCode Hi, I cant really reproduce the inital issue (the only one that matters, once things start to bugs all sort of weird stuff can happen). Do you reproduce this easily? If you could you please send me your player save? Thanks

hi - i can reproduce it easily - but the the collector stops being bugged on a reload (so you won't see it on a save until you manage to bug out the collector yourself by mining)

i can always bug out a collector though - just need to keep mining till the collecting sound becomes a regular "beat" and then when you stop mining it will continue - at which point accessing the collector will get the crazy bugged sounds etc - and if the inventory slots are interacted with a freeze will occur

but if you don't interact with the inventory slots and instead exit the collector and exit to the title screen and reload the save - the collector will not be bugged anymore and the slots can be interacted with

here is the blueprint of the ship i am using:
[Ship01.zip](https://github.com/tsunamayo/Starship-EVO/files/9903378/Ship01.zip)

if you really need a specific save i can post one - but i am able to replicate the bug every time by simply spawning that ship into any game and doing some heavy mining

i can also do it when building a fresh ship

as i said - the collector will un bug on a reload - but if you are unable to get it to bug out then that is odd - since i can do it every time - although sometimes may take a little longer than others - so maybe it's processor dependent? and so if you have a super fast processor maybe it would take you longer? or maybe not even occur if it is not possible to mine faster than the collector can handle on your processor?  (i am running a Ryzen 5 3600 at stock speeds, with 16GB DDR4 3200 and an unmodified Gigabyte RTX 2060 OC 6GB, on an MSI B450 TOMAHAWK MAX II)

i hope this helps - let me know if you do need a save - or some more videos - i can show it from a new game consistently

thanks for all the great work :-)

(and sorry if this one is weird - maybe we can wait and see if i can still replicate it on the new build?)

**Comment by tsunamayo** [comment]
@DrizztCode So I have fixed some issue with heavy mining, it was lagging a lot. Maybe that could have explained it?

**Comment by tsunamayo** [comment]
@DrizztCode Hi, tell me if you can reproduce in 22w44a. Thanks

**Comment by DrizztCode** [comment]
> @DrizztCode So I have fixed some issue with heavy mining, it was lagging a lot. Maybe that could have explained it?
> @DrizztCode Hi, tell me if you can reproduce in 22w44a. Thanks

hi - sorry for the short delay in replying

i have installed 22w44a, and unfortunately i was still able to bug out the collector :-(

i did seem to notice a difference in how the ore was generating, which is maybe something to do with the changes? or maybe i was imagining it!

but suffice to say, i will do some proper testing and give you a proper report

i will use 22w44b so i can have some chilled music while i do it though :-)

and while i have also noticed some issues with the flow of inventory - i am also seeing the great fixes and improvements

thanks for all the continued hard work - and i will keep you informed about this issue

Cheers!

**Comment by DrizztCode** [comment]
actually i just noticed that while 22w44b is tagged as default, i believe it is experimental - so i will do the testing on the default branch before i move to the experimental

**Comment by DrizztCode** [comment]
quick update - i just loaded up 22w44b and pasted in my ship and did some heavy mining and got no bugged collector (several hundred rocks over 30 seconds or so of sustained mining laser) - so that's a great sign!

but as i said i did get the bug on 22w44a when i briefly tried it out very recently

so i will keep you posted - since maybe it was linked to something weird in the blueprint - or due to a reload or related to another bug etc

thanks again! :-)

**Comment by DrizztCode** [comment]
hi - i'm sorry to say that it is still happening - possibly it now requires a bit more mining for it to happen

but i also had it happen without the obvious sound cue before or in the inventory - that time i only knew it had happened when i played with the inventory and got a freeze

here is a short video after the collector bugged out the first time (i heard it happen and then started recording):

https://youtu.be/X4lAj5u2RiE

i just open the inventory to show the weird sounds and the load of invisible ore and then stop the video and do a reload

the next video follows on from the previous after the reload - i show the bugged collector and then delete it and make a new one (also - please note that the grid settings have reset themselves since i always have them on quarter grid and 0.125 smallest) - and then i do a load of heavy mining - and there are only some small cues that something weird might be happening - but none of the regular audio cues - so i go into the inventory and all seems normal until i play with the slots - and it froze

https://youtu.be/NmHT7R03Etc

this is all in a new save with a new ship, built from scratch


i will keep doing testing - but i can replicate it consistently usually within 30 seconds or a minute of heavy mining


am i really the only one?


thanks for all the work and i hope i can continue to help

**Comment by DrizztCode** [comment]
is it possible it's related to another issue? that rocks/ore will often clip through blocks when travelling at speed? since the collector accelerates blocks to high speed, it is possible that some are clipping through either the collector or other blocks before making it to the "collection zone" - and maybe this is causing problems?

i will raise that clipping issue now that i have mentioned it, once i get a video together

cheers!

**Comment by tsunamayo** [comment]
@DrizztCode Hi, I was able to reproduce, the issue has been fixed for 22w45a! Thanks a lot on that one! Cheers

**Comment by DrizztCode** [comment]
> @DrizztCode Hi, I was able to reproduce, the issue has been fixed for 22w45a! Thanks a lot on that one! Cheers

awesome! - happy to have been of help - and i am excited to play the new build (i haven't been as active recently - but i will be sure to get some proper playtesting done once this build releases)

Cheers! :-)
