### ISSUE TITLE
[Bug] [22w42a] Furnace Inventory Won't Subtract Mass When Finished (or during) Smelting (and 6th ore maths issue)

### ISSUE THREAD

**Issue by DrizztCode** [tsunamayo/Starship-EVO#4969]
yes, me again :-)

So:

1. it looks like the furnace isn't subtracting the mass of the ore that it is smelting once it is finished smelting it

or while it is smelting it

basically it will only reset to zero if you manually interact with or empty the inventory

i have only tested with rocks so far - i will update when i have tested with other ores

is easiest to see on a video:

https://youtu.be/tqFHPzh1hBA

(i do the same thing 4 times - so just need to watch the first 2 really - it wasn't till after i made the video that i played around with different ways of resetting the inventory - you can add or subtract or split - anything will do it)

no steps needed - just feed a furnace any way other than manually and watch it jam

then just interact with the inventory manually in any way to get it to recalculate

also:

2. after the 5th rock it goes weird with some kind of rounding error (i guess, lol) - 5 rocks are 750, 8 rocks are 899, and it is always 1 out till it gets reset with 5 rocks or less

as always - thanks for everything :-)

**Comment by DrizztCode** [comment]
quick update - similar kind of stuff happening with other ores - as well as some weird disappearances

i assume you have probably seen this stuff by now  - but do let me know if you'd like me to capture some video or need any more information

thanks :-)

**Comment by tsunamayo** [comment]
@DrizztCode fixed for 22w43a. Thanks!

**Comment by DrizztCode** [comment]
> @DrizztCode fixed for 22w43a. Thanks!

awesome! thanks! :-)
