### ISSUE TITLE
[Bug] [22w42a] Fuel Scoop Not Detecting Fuel (and fuel overlay gone?)

### ISSUE THREAD

**Issue by DrizztCode** [tsunamayo/Starship-EVO#4970]
hi - sorry if i am missing something vital here - but i can't get the fuel scoop (either one) to work in the middle of a gas cloud

i have connected a pipe to my reactor, and a scoop to the end of it, and it will expel fuel, but won't harvest any
same with lightcruise engine
tried with a tank too

i made a video - it's a bit long - but the beginning should show what i'm seeing

https://youtu.be/pL_Mob2Fc4A

also - is the fuel overlay now deliberately gone? or is that a bug?

apologies if i'm missing something obvious!

thanks again for the great game - am looking forward to fueling - and using those awesome hoses :-)

**Comment by DrizztCode** [comment]
sorry  - video is still processing the HD - i will post another comment when it's done

**Comment by DrizztCode** [comment]
ok - it's processed now - sorry about that!

**Comment by tsunamayo** [comment]
@DrizztCode Hi, issue is fixed for 22w43a. Thanks a lot for booking all those issues!

**Comment by DrizztCode** [comment]
> @DrizztCode Hi, issue is fixed for 22w43a. Thanks a lot for booking all those issues!

happy to help! :-)

thanks for all the great work - and i'm looking forward to playing with the new build once it's ready :-)

**Comment by DrizztCode** [comment]
hi - fuel scoop seems to be working now (at least with regular pipes) - but i did notice still no fuel overlay while trying to debug getting fuel to flow from a scoop using the hoses

so is the fuel overlay gone for good?

thanks :-)
