### ISSUE TITLE
[Bug] cant place block in hotbar

### ISSUE THREAD

**Issue by COMICLER** [tsunamayo/Starship-EVO#4972]
When ever i place blocks in the hotbar the block disappears and i cant add blocks to the hotbar anymore. 
All you have to do it just start the game and after you add 2-3 block it starts happening.
this is on the default branch so idk if this is fixed in the new version but i might as well report it 
this is the player info
[leave if broken.zip](https://github.com/tsunamayo/Starship-EVO/files/9853758/leave.if.broken.zip)

**Comment by tsunamayo** [comment]
@COMICLER Do you have a log file to show?
Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
Do you reproduce this all the time?
Thanks

**Comment by COMICLER** [comment]
so the file i attached is the player file, and it happens every time i play, but i did try experimental and it doesnt seem to be a problem anymore if that means anything.

**Comment by tsunamayo** [comment]
@COMICLER Hi, The file attached is the world directory, not the player.log (which is the log file, I know it can be confusing)!

**Comment by COMICLER** [comment]
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/9865828/Player.log)
Oh sorry here ya go

**Comment by tsunamayo** [comment]
@COMICLER So now the default branch has the fix! Thanks
