### ISSUE TITLE
reactor fuel bug

### ISSUE THREAD

**Issue by eageus** [tsunamayo/Starship-EVO#4977]
### Short Description of the issue: just started happening for no reason but now i cant get rid of it. the reactor in my ship drains all its fuel and then wont refit itself. even on full reboot of game. i have to physically replace the rectors themselves then they will work for a split second and then do the same thing over again. 

...

### Steps to reproduce the issue:no idea what could make this happen. going to leave you a blueprint of the ship it happens on. 

...

### Environment
- Starship EVO version: experimental 
- Graphics Card: rx 590 8gb

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Se
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/9923975/Player.log)
nd to -> compressed zip file] then drag the .zip onto your report to upload it.
[advanced human fighter prototype.zip](https://github.com/tsunamayo/Starship-EVO/files/9923974/advanced.human.fighter.prototype.zip)

**Comment by tsunamayo** [comment]
@eageus Hi, I have fixed that issue. But I didnt see the "split seconds" part of it, are you sure it was not at least several seconds?

**Comment by eageus** [comment]
it is possible it took a few seconds. and i just did not notice until right then.,
