### ISSUE TITLE
[Bug] Child Entity movement impeded by (legal) clipping

### ISSUE THREAD

**Issue by Pawnp** [tsunamayo/Starship-EVO#4978]
### Short Description of the issue:

When a sub child entity (orange) on a main child entity (yellow) is clipping into/being clipped into by the main CE, the main CE cannot move. Theoretically the sub CE should move with the main CE, however the main CE interprets the (legal) clipping as an obstruction and will remain in position.

![image](https://user-images.githubusercontent.com/72423251/199603162-66f98860-b232-45b3-89b9-27379c66974c.png)

### Steps to reproduce the issue:

-Recreate either or both structure shown in the diagram
-Attempt to turn the bottom hinge

### Environment
- Starship EVO version: 22w44b

**Comment by tsunamayo** [comment]
@Pawnp Hi, I understand your issue, but the "pipe clips through hull" feature is not made to cover this case. When you think of it, the legal clipping means you carve a hole through the hull and pass the pipe inside. It make sense physically, hull are empty inside. This is why you cant do it for system block for example. 
In your case, we would loose the believability of it as the pipe would move over time, and hull are not some kind of jelly ^^. So I wont spend time fixing this!
Cheers

**Comment by Pawnp** [comment]
@tsunamayo Just for clarification, the orange hinge on the diagram does not move, only the yellow hinge.
And when the yellow hinge moves it should not move any of the blocks it carries through any pipes.
I still fail to understand the justification on why the yellow hinge won't move, as nothing is "moving" through any pipe.

![image](https://user-images.githubusercontent.com/72423251/199621168-7f88cafc-8227-4df1-864b-e6b32fa8e2cc.png)

**Comment by tsunamayo** [comment]
@Pawnp Ah I see sorry, yes I get it, unfortunately the collision system do not check whether the other child entity is moving relative to them or not - that would be to complex and costly to do.
What I will do is to forbid clipping when not on the same entity. 
Thanks

**Comment by tsunamayo** [comment]
@Pawnp So I fixed the fact that you could build with clip on other entities. Thanks!
