### ISSUE TITLE
[Bug] Fuel Scoop's model is double the indicated size

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4981]
### Short Description of the issue:

It seems that the Fuel Scoop has a problem with its model being twice as big as it says it is.
At the smallest scale - 1/8m it takes up a space comparable to other 1/4m blocks and so on.

### Environment
- Starship EVO version: 22w44b
- Graphics Card: GTX 970M

### Additional information:

![Starship_EVO_7cFjuhqL1R](https://user-images.githubusercontent.com/63756057/199950485-2613862f-cd80-421a-a917-f268ca8bcf51.png)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Indeed, fixed for 22w44c. Thanks!
