### ISSUE TITLE
[Bug] Unspawning an entity while the box delete tool is working causes all entities in the world to move to origin

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4982]
### Short Description of the issue:
While using the delete tool, I unspawned an entity while the tool was mid way through removing bricks. I tried to use the tool again, but it could select bricks fine but would not remove them. So I exited to desktop and tried to reload the world.
Upon reloading the world, all the ships seemed to be missing. I teleported to one of them, and found them all clumped up in one space. I can't interact with these entities either, they seem non-physical.
![711980_20221104143322_1](https://user-images.githubusercontent.com/27857711/200000825-edf6767f-fe18-457b-ac22-6825bb0312bf.png)
![711980_20221104143054_1](https://user-images.githubusercontent.com/27857711/200000843-7d1c1693-9545-4d71-9c6b-914c7d46569b.png)

### Steps to reproduce the issue:
- Use the box delete tool, unspawn the entity the tool was used on while the tool is deleting bricks
- Quit to desktop
- Load the world again

### Environment
- Starship EVO version: 22w44b
- Graphics Card: RX 580

### Additional information:
Log (session in which I was using the box delete tool)
[Player-prev (Delete Tool Lock).log](https://github.com/tsunamayo/Starship-EVO/files/9939298/Player-prev.Delete.Tool.Lock.log)
Log (loading the world after a quit to desktop)
[Player (Entities clumped).log](https://github.com/tsunamayo/Starship-EVO/files/9939304/Player.Entities.clumped.log)
World file - [Crafting Update.zip](https://github.com/tsunamayo/Starship-EVO/files/9939307/Crafting.Update.zip)

**Comment by tsunamayo** [comment]
@ProPeach Hi, this will be fixed for 22w45a. Thanks!
