### ISSUE TITLE
Block Browser items can be deleted

### ISSUE THREAD

**Issue by KevinGelkingSviper** [tsunamayo/Starship-EVO#4983]
### Short Description of the issue:
Since many games have this functionality, I attempted to 'quick transfer' (shift + click) a tool from the block browser to my hotbar.
This instead removed the tools and blocks from the block browser with seemingly no way to recover them.

Even if it doesn't transfer it to the first empty slot, it should probably not delete anything from the block browser. :)

NOTE: Building mode is fantastic! Great work <3

### Steps to reproduce the issue:

- Start game
- Press TAB to open block browser
- SHIFT+LMB block or tool
- notice the block/tool disappears

### Environment
- Starship EVO version: 22w44b
- Graphics Card: nVidia 3070 Ti

### Additional information:

https://user-images.githubusercontent.com/103119563/200058497-67a8fdc0-6157-45fc-8588-c92728b56ac8.mp4

_

[Player - Copy.log](https://github.com/tsunamayo/Starship-EVO/files/9941414/Player.-.Copy.log)

**Comment by tsunamayo** [comment]
Yes indeed, I will release a patch asap! Thanks!

**Comment by tsunamayo** [comment]
@KevinGelkingSviper Fixed for 22w44c. I will upload the patch soon. Thanks!
