### ISSUE TITLE
Game Crashed When Deleting a Block

### ISSUE THREAD

**Issue by Kadzar** [tsunamayo/Starship-EVO#4986]
Started a fresh world on the latest version, went through the tutorial, and, during the initial building tutorial, when it told me to delete a block, I did so, and the game crashed to desktop.

...

Do the tutorial mission on a fresh world and delete block when the tutorial first tells you do do so.

...

### Environment
- Starship EVO version: 22w44c
- Graphics Card: NVIDIA GeForce GTX 1080

### Additional information:

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/9942562/Player.log)

**Comment by Kadzar** [comment]
Also, when I started up that save again, for some reason I was back in the hallway before the elevator instead of up in the observation deck where I was before the crash.

**Comment by tsunamayo** [comment]
@Kadzar I have just fixing the issue, thanks for pointing that out. I will repush the build asap!

**Comment by tsunamayo** [comment]
@Kadzar Build is up, as it is quite a major issue(blocking for tutorial) could you please test again and tell me how it went? So I can sleep better ^^

**Comment by Kadzar** [comment]
I tried making a new world, and it didn't crash this time when I deleted the block, but now the tutorial keeps telling me to place blocks of different grid sizes even though I already have.

Also, a possibly weird thing I did the first time around and did again for consistency was scan my character in the medbay after starting in the world.
![20221105181312_1](https://user-images.githubusercontent.com/66035211/200145869-24291718-157a-4e80-8706-3556f1ac8047.jpg)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/9944854/Player.log)
