### ISSUE TITLE
[Bug] 22w44c - Volumetric sensor not working

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#4988]
### Short Description of the issue:
The volumetric sensor does not trigger in response to the player. I'm aware that this has been previously mentioned, but I thought it would help to have a complete, fresh report with the most recent information, as well as logs, blueprint, and video.

### Steps to reproduce the issue:
Place a volumetric sensor. Link it to something. Enter the sensor's volume.

### Environment
- Starship EVO version: 22w44c
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
Video:
https://gfycat.com/hauntingacademicgrayfox

Log:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/9964733/Player.log)

Blueprint:
[Volumetric Sensor Bug BP.zip](https://github.com/tsunamayo/Starship-EVO/files/9964736/Volumetric.Sensor.Bug.BP.zip)

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Hi, thanks a lot, yes I have been going through older bugs and it was on top of the list. I need to almost rewrite them from scratch, so they use the new physics, give a few ouputs for the event gate, and detect spaceship. Same for the Laser sensor.
Cheers

**Comment by Dwarf-LordPangolin** [comment]
Good to know, thank you! I hope the re-write isn't too arduous.

I don't know if this matters since you have to rewrite them anyway, but I just found what the problem is: the sensor will trigger, but only if the player is in a specific corner of the field, just like CurioInventorium noted in #4435 . As he noted, whatever dimensions the field has, it only triggers in the negative-most corner.

The corner may not be the same per BP though; I checked this on the bug BP I sent you, and it doesn't produce the same results.

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Hi, this is now fixed for 22w45a, with all the new stuff added (support for entity and item, event gate ect). Thanks
