### ISSUE TITLE
[Bug] 22w44c- Fuel hoes do not transfer fuel through mechanisms

### ISSUE THREAD

**Issue by Crimson-Artist** [tsunamayo/Starship-EVO#4993]
Fuel being piped through a mechanism will only get to its destination if normal pipes are used. Using fuel hoes do not transfer fuel.
![20221111113923_1](https://user-images.githubusercontent.com/112352428/201436172-ed3b7420-627d-4d82-ad97-eec8532f8e45.jpg)
![20221111113936_1](https://user-images.githubusercontent.com/112352428/201436184-6b1e3098-c390-41bc-8af5-f95ca5dfa9f1.jpg)

**Comment by tsunamayo** [comment]
@Crimson-Artist Hi, issue is fixed for 22w46a. Thanks!
