### ISSUE TITLE
game thinks ship is larger than it is.

### ISSUE THREAD

**Issue by eageus** [tsunamayo/Starship-EVO#4995]
### Short Description of the issue:  the game is telling me the ship is 53m long when it is actually 23m long. i did delete some of the length of the ship but normally it updates. 

...

### Steps to reproduce the issue:  no idea

...

### Environment
- Starship EVO version: experimental 
- Graphics Card: rx 590

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.
![20221111233700_1](https://user-images.githubusercontent.com/87349714/201463101-94bb1475-00f8-455b-b037-7ba0950383fa.jpg)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/9
[epa patrol ship.zip](https://github.com/tsunamayo/Starship-EVO/files/9994458/epa.patrol.ship.zip)
994457/Player.log)

**Comment by tsunamayo** [comment]
@eageus Hi, issue will be fixed in 22w46a. Thanks!
