### ISSUE TITLE
[Bug] Exiting spaceship control under lightdrive speed and auto pilot (Dude, Where's My Car?)

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#5003]
### Short Description of the issue:
If you exit spaceship control under lightdrive speed and auto pilot, the ship continues its trajectory, and you end up being ejected into space, and left being behind.
...

### Steps to reproduce the issue:

- enter into lightspeed mode
- chose a target and select autopilot
- select exit spaceship control
- get up from seat
- be left behind

### Environment
- Starship EVO version: 22w44c
- Graphics Card:  gtx 1660

### Additional information:

https://user-images.githubusercontent.com/73253472/202919520-9a8dfc72-d3f6-474c-b851-dcc9f8d31807.mp4

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/10050427/Player.log)

[Station.zip](https://github.com/tsunamayo/Starship-EVO/files/10050429/Station.zip)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hi, is there a gravity field on your ship? Thanks

**Comment by Uncle-Ulty** [comment]
Yes, there is gravity. I tried again to repeat the situation, and the ship continues flying in light drive straightforwardly. I tried to hunt down the ship, but it's hard to match the speed

**Comment by tsunamayo** [comment]
@Uncle-Ulty If you dont have autopilot does it continue to fly? Thanks

**Comment by Uncle-Ulty** [comment]
When you engage hyperdrive autopilot you can exit ship control without disabling the ship autopilot. This makes the ship autonomous even when you aren't on ship command

**Comment by Uncle-Ulty** [comment]
No, it doesn't.

This bug only happens if autopilot and light drive are both in effect.

If I'm on the light drive but not on autopilot, and I exit the ship control, it cancels light drive immediately.

**Comment by tsunamayo** [comment]
@Uncle-Ulty Okay I can reproduce indeed. For some reason it is something that is hard to do, it is not the first time I have to debug this... Thanks

**Comment by tsunamayo** [comment]
@Uncle-Ulty Issue is fixed for 22w48a. Thanks!
