### ISSUE TITLE
[Bug] Request landing and Autopilot (Switched options in F menu)

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#5004]
### Short Description of the issue:
If you select autopilot, the ship asks for landing. If you request landing, the ship starts autopilot to the destination

### Steps to reproduce the issue:
- get in the ship's yoke (the ship must be smaller than the destination shipyard volume)
- select either option, requesting landing or autopilot (the game gonna recognize the other option)

Observation: this only happens when both options are available. 
- If the ship is too big, it doesn't happen. 
- If the destination doesn't have a shipyard, this doesn't happen. 
- If the ship is too close to the destination with an available shipyard, it doesn't happen

### Environment
- Starship EVO version: 22w44c
- Graphics Card: gtx 1660

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

https://user-images.githubusercontent.com/73253472/202920250-2d56134f-4e1f-4c92-8d2b-fff8219fbcb1.mp4

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Station.zip](https://github.com/tsunamayo/Starship-EVO/files/10050448/Station.zip)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/10050449/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hi, issue is fixed for 22w48a. Thanks!
