### ISSUE TITLE
[Suggestion/QOL] Disable interactable bricks when flying a ship or hover in 3rd person.

### ISSUE THREAD

**Issue by kynamats** [tsunamayo/Starship-EVO#5005]
### Short Description of the issue:
Currently, when flying a ship or hover in 3rd person, there are occasions when the camera position allows you to press buttons outside of the cockpit, or interact with hidden logic elements. This can get confusing, especially when panning your camera around a ship.
...

### Steps to reproduce the issue:
Pilot a ship in freelook with interactable bricks close to the camera's centre. this can be particularly pronounced on hoverbikes. 
...

### Environment
- Starship EVO version: 22w45a
- Graphics Card: 3070ti

### Additional information:
Note that in the following video, I am constantly in control of the starship, and my character is seated in the cockpit, but I can interact with the buttons inside the cargo bay due to these being close to the freelook camera's centre.

https://user-images.githubusercontent.com/89156468/203589173-f341b9fb-4f89-4309-84ee-e6a6b242da80.mp4

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@kynamats Hi, so I was not able to reproduce that issue, but I have made some change that should prevent it from happening anyway... For 22w48a. Thanks!
