### ISSUE TITLE
[Bug] Cannot go into light cruise -- "You need to add a light cruise engine"

### ISSUE THREAD

**Issue by CysOrion** [tsunamayo/Starship-EVO#5007]
### Short Description of the issue:

When try to go into light cruise, a notification pops up says that "you need to add a light cruise engine", but I already did, with fuel connected. Sometimes the message will be changed to "light cruise engine ran out of fuel"

### Steps to reproduce the issue:

Add light cruise engine to a new ship.

### Environment
- Starship EVO version: 22w44c
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

![image](https://user-images.githubusercontent.com/93535602/203814807-cc6599f3-cc61-4167-a095-1ccb8d3bafe7.png)

![image](https://user-images.githubusercontent.com/93535602/203815311-4f50c354-4f87-4678-865c-f5da43de9fbd.png)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/10085592/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@CysOrion Hi, did you build the engine in the right direction (pointing to the rear?) Thanks.

**Comment by tsunamayo** [comment]
@CysOrion So I have added a new warning message for case when there are lightcruise engine but not built in the right direction. Thanks!

**Comment by CysOrion** [comment]
Thanks a lot, it worked. I followed the guide on Starship evo Fandom Wiki lol.

Maybe it should be changed because it is a bit confusing. "Once placed, they will provide forward thrust regardless of the exhaust's direction."
https://starshipevo.fandom.com/wiki/Lightcruise_Engine

**Comment by ProPeach** [comment]
Looks like the wiki needs a bit of editing, I'll fix that
