### ISSUE TITLE
[Bug] Interstellar travel generates a glitchy shadow around player

### ISSUE THREAD

**Issue by kynamats** [tsunamayo/Starship-EVO#5013]
### Short Description of the issue:
Traveling from one system to another creates a flickering shadow around the player.
...

### Steps to reproduce the issue:
Use a ship with warp to travel between systems. Inspect player shadow afterwards. (Cannot reproduce reliably after system restart, sometimes takes a few jumps to occur)
...

### Environment
- Starship EVO version: 22w47a
- Graphics Card: 3070ti

### Additional information:
![image](https://user-images.githubusercontent.com/89156468/205514011-e940b463-6b8c-4208-b1b8-9619a0e2ef3d.png)
![image](https://user-images.githubusercontent.com/89156468/205514027-d05923a8-6466-44f5-982f-d11072652320.png)

_(Screenshots, Videos, Error logs, Related issues)_
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/10149404/Player-prev.log)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/10149405/Player.log)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@kynamats This one should be fixed in current version of the game. Thanks
