### ISSUE TITLE
New and old rounded blocks have a different number of faces

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#5017]
### Short Description of the issue:
The old Rounded Hull shapes had a curve made up of 4 segments, whereas the new rounded shapes (wedge rounded, arch rounded etc) have curves made up of 5 segments. This causes a mismatch when they are placed together.
Here you can see the mismatch, I realize it might be partly my fault as I didn't check the models I sent you were in line with the curves already in game. Oops!
![image](https://user-images.githubusercontent.com/27857711/207646924-d70ebf34-1bf0-4f79-a726-5d825ee11d75.png)

It's be awesome to have the older shapes match the smoother curve of the newer ones

### Steps to reproduce the issue:
- Compare old and new rounded shapes

### Environment
- Starship EVO version: 22w50b
- Graphics Card: RX580

**Comment by tsunamayo** [comment]
@ProPeach Indeed, implemented for 22w50c, with update collider too (it is now super fast to do)! 
I didnt used your model btw they might have been different also. Do you remember where you send them? Sorry it is hard to keep track ^^
Cheers

**Comment by ProPeach** [comment]
@tsunamayo oh yes I see, my models have again a different number of faces. No biggie! They're pretty simple after all and you handled them well so far, I think you've recreated pretty much all of these apart from the infamous hepta
https://github.com/tsunamayo/Starship-EVO/issues/4882#issuecomment-1303155495


Your new tech for new shapes and colliders seems like it was a great investment, the fixes and new shapes have been so quick this week!
