### ISSUE TITLE
Can't go through sliding doors.

### ISSUE THREAD

**Issue by FergorH** [tsunamayo/Starship-EVO#5018]
### Short Description of the issue:
Can't seem to be able to go through the sliding doors inside the tutorial station, like an invisible barrier blocks me. Haven't tested it with other sliding doors somewhere else or that i have built.

...

### Steps to reproduce the issue:
Just... try going through a sliding door, i guess?
...

### Environment
- Starship EVO version: 22w50b
- Graphics Card: GTX 1050

https://user-images.githubusercontent.com/95005485/207674933-76fd775a-6f9c-4908-9832-ca1cce0c457a.mp4

Player.log: 
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/10230595/Player.log)

**Comment by tsunamayo** [comment]
@FergorH Thanks for booking the bug. It is fixed for 22w50c. Cheers
