### ISSUE TITLE
[Bug] Canopy collision box issue

### ISSUE THREAD

**Issue by PopkaAkula** [tsunamayo/Starship-EVO#5020]
### Short Description of the issue:

Prior to the recent update 22w50a canopy blocks could move when there were bricks within their bounding box but now that it seems that many blocks have had their collision box changed the canopy has started misbehaving once more.

https://user-images.githubusercontent.com/37738021/207970231-85b34eef-0ea9-4bd9-b639-7d182581f684.mp4

### Steps to reproduce the issue:

Try building a mechanism with a canopy and it'll get stuck if there's a brick inside of it's bounding box.

### Environment
- Starship EVO version: 22w50b

**Comment by tsunamayo** [comment]
@PopkaAkula I should have fixed that issue yesterday actually, I will upload the fix soon! Thanks
