### ISSUE TITLE
Mineral resource gitches.

### ISSUE THREAD

**Issue by Khast0** [tsunamayo/Starship-EVO#5042]
### Short Description of the issue:
Trying out mining the asteroids for the first time ithe resource patch model is glitching into big black cube. The cubes have physics, the ship actually get stuck in them. 
Happened all the time but no indication what's triggers it. Seems random both frequent. 
Also game freezes and don't recover. While mining, Also random but frequent not directly connected to the cube thing.

I was using this workshop ship:
[SI] M1010 Light Mining Craft.
javascript:ShowEnlargedImagePreview( 'https://steamuserimages-a.akamaihd.net/ugc/1907856497759224010/B48100408EE35EDA9E8AC6A81E2570D8CD9D87AD/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false' );

### Steps to reproduce the issue:
Just mining for me, no indication of a trigger.
...

### Environment
- Starship EVO version: Steam, Experimental, 22w50c
- Graphics Card:  NVIDIA GeForce GTX 1650 (latest drivers), DirectX 12, Win 10

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![Evo3](https://user-images.githubusercontent.com/125976095/220550082-ad6a81b7-3223-429f-a85b-a561c68b3cb7.png)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by Uncle-Ulty** [comment]
I faced the same problem some time ago. But I couldn't record this cuz the game crashed moments after. The asteroids, mining, and inventory have many bugs and I don't know how to identify them. I posted a bug reported some months ago, but I couldn't know for sure the source of the bug... I think the community should make more tests with mining on asteroids in order to create more player reports.

**Comment by tsunamayo** [comment]
@Uncle-Ulty @Khast0 Hi, so I made many improvements to the tech and fix many bugs, do you still get that?
Thanks

**Comment by tsunamayo** [comment]
Okay I did some extensive mining with no issue, please rebook or re-open this case if you still get issues!
