### ISSUE TITLE
[Question] Planet Atmosphere Heights

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#5043]
Hey Tsuna,

Exciting stuff coming! 

Would you be able to share what the atmosphere heights would be of the planets? I'm planning a build with Nuc1earLemons(pinesh) and we're curious because we'd like to work on a large base, but don't want to make it too big and stick out of the planet.

Just based on some rough estimating with math, we're getting about a 1km atmosphere height for a planet that is 132km in diameter. This is purely based on Earth's atmosphere and relating it to our diameter vs in-game planet diameter so it could be completely off from what you're doing.

**Comment by tsunamayo** [comment]
@Xerma Hi sorry for the delay. So the atmosphere bounds is at 20%, but it has a logarithmic drop-off, so it is close to 0 much before that. Clouds for example are only at 2% of the radius, so you can take 2x 3x this to get a nice approximation.
Cheers
