### ISSUE TITLE
Fuelscoop broken? 

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#5045]
Hi there,

seems like the Fuels scoop doesn't work quite right.

In this case my ship has 4 - 4meter fuelscoops that are connected correctly with 4meter pipes and they are just collecting 4liters/second in total.
The ship istelf has just 1big fueltank with a 512.000 liter cap. 
So refueling it would take about 35 hours ... this can't be right.

https://user-images.githubusercontent.com/81495956/221252561-653a8d01-abb1-46d3-866e-56617582a88f.mp4

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, do you still get this issue? From the code and my test you get 10% of the block capacity each second, so for a 1m harvester thats 100L, which sounds reasonable.

**Comment by BigBadKangaroo** [comment]
@tsunamayo Hi there, just tested it and it works fine ... four of my 4m fuel scoops filled my 288000liter tank in a few seconds. Seems to be fixed!

**Comment by tsunamayo** [comment]
@BigBadKangaroo Good thanks for the update. Your ships are getting a lot of love lately!
