### ISSUE TITLE
[bug] Lightcruise thruster  on CE isn't recognized

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#5048]
### Short Description of the issue:
Lightcruise engine mounted on CE isn't recognized and the ship doesn't allow to enter in lightcruise mode. 
...

### Steps to reproduce the issue:
-I have 6 lightcruise engines on 6 different CE, and the game doesn't recognize them, thus it shows lightcruise rating as 0%. But, if I delete the engines and place again, they work normally.  However it returns to 0% some time after for unknown reason.

-all engines are connected to fuel tank
...

### Environment
- Starship EVO version: experimental [current]
- Graphics Card:  gtx 1660

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![image](https://user-images.githubusercontent.com/73253472/221440533-5a3fd6fd-3115-4480-8a68-ba6e71c70741.png)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
log
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/10834858/Player.log)
world
[Multi role.zip](https://github.com/tsunamayo/Starship-EVO/files/10834859/Multi.role.zip)
blueprint
[Multi role 67.zip](https://github.com/tsunamayo/Starship-EVO/files/10834861/Multi.role.67.zip)

**Comment by Vincent14** [comment]
Hi, what is CE please?

**Comment by Uncle-Ulty** [comment]
> Hi, what is CE please?

Child Entity

**Comment by tsunamayo** [comment]
@Uncle-Ulty So this issue is fixed for 23w34b. Sorry for the delay I was crunching on planets!
Cheers

**Comment by Uncle-Ulty** [comment]
perfect! <3
