### ISSUE TITLE
Bug: Can't move when you reach a planet or a star

### ISSUE THREAD

**Issue by Vincent14** [tsunamayo/Starship-EVO#5051]
### Short Description of the issue:

Game is not crashed or frozen but I can't move, I'm stuck. When I want to add a new block to my ship stuck in the star or planet, an error message appear: "The mass on this children entity is beyond the maximum [...] This mechanism wont be able to move"

### Steps to reproduce the issue:

I took a random ship on the workshop and fly into a star, then a random planet, always same behaviour

### Environment
- Starship EVO version: 22w50c
- Graphics Card: Geforce 2070 RTX

### Additional information:

[Video](https://youtu.be/tgEyW79auzM)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/10876140/Player.log)

**Comment by tsunamayo** [comment]
@Vincent14 I, thanks for booking all the bug, I am currently on a big planet update it will take me a bit of time to catch up. I keep you posted. Thanks

**Comment by Vincent14** [comment]
Thanks to you @tsunamayo : )

**Comment by tsunamayo** [comment]
@Vincent14 I think it was just a case of dying inside a planet. Now you will die properly and will respawn at the station. Thanks
