### ISSUE TITLE
Bug: Collector in "expel" mode still "collect"

### ISSUE THREAD

**Issue by Vincent14** [tsunamayo/Starship-EVO#5052]
### Short Description of the issue:

The collector expel & collect at the same time.

I dunno if it's the same bug or not, but it expels only blocs from its own inventory, and not from containers, this is an issue, it should be able to load or unload a container

### Steps to reproduce the issue:

[Video](https://youtu.be/pb2CYOzr34c)

### Environment
- Starship EVO version: 22w50c
- Graphics Card: Geforce 2070 RTX

**Comment by Uncle-Ulty** [comment]
Old problem, I reported that some months ago. It's good to see more players reporting it

**Comment by tsunamayo** [comment]
@Vincent14 @Uncle-Ulty Issue was fixed some time ago, also the pulling feature was a bit confusing, you had to set the Range property to 0 so that in no longer pull for a standard expel usage (now you cant pull when set at expel). Thanks

**Comment by Uncle-Ulty** [comment]
> @Vincent14 @Uncle-Ulty Issue was fixed some time ago, also the pulling feature was a bit confusing, you had to set the Range property to 0 so that in no longer pull for a standard expel usage (now you cant pull when set at expel). Thanks

hum.... some people won't set it to zero... I think it's advisable to add a "help description" in this cas
