### ISSUE TITLE
Bug: Collector in "expel" mode... collect on the block above and "destroy" items

### ISSUE THREAD

**Issue by Vincent14** [tsunamayo/Starship-EVO#5053]
### Short Description of the issue:

It could be because of different scales I used, the collector is collecting on top of it, then items suddenly disappear.
It could be also when a collector has been placed, removed and place close to the previous place, but not exactly

### Steps to reproduce the issue:

[Video](https://youtu.be/EicPrsZYoTg)

### Environment

Starship EVO version: 22w50c
Graphics Card: Geforce 2070 RTX

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Vincent14 So there has been many fix regarding items in recent build, I cant reproduce so I will consider it closed, hopefully it does not come back. Thanks
