### ISSUE TITLE
Bug: Can't grab again ores I throw on the ground

### ISSUE THREAD

**Issue by Vincent14** [tsunamayo/Starship-EVO#5054]
### Short Description of the issue:

When I throw an ore, it's not always possible to grab it back to my inventory, I can't use the action key to take it

### Steps to reproduce the issue:

Throw a collected rock on the ground or hull blocs

### Environment
- Starship EVO version: 22w50c
- Graphics Card: Geforce 2070 RTX

**Comment by tsunamayo** [comment]
@Vincent14 Hi, I think this issue should be fixed in current build. Thanks

**Comment by Vincent14** [comment]
Thanks!
