### ISSUE TITLE
Bug: Ores stay stuck on the coveyor

### ISSUE THREAD

**Issue by Vincent14** [tsunamayo/Starship-EVO#5056]
### Short Description of the issue:

Ores don't move on a conveyor

### Steps to reproduce the issue:

[Video](https://youtu.be/bj31fOqDvd0)

### Environment
- Starship EVO version: 22w50c
- Graphics Card: RTX 2070

**Comment by tsunamayo** [comment]
@Vincent14 Merci pour la video, tres utile je vais essayer de reproduire et je te tiens au courant.

**Comment by tsunamayo** [comment]
@Vincent14 Okay I cant no longer reproduce this, I think the issue should be fixed.
