### ISSUE TITLE
Bug: Stacking things below/above fuel tank create a visual ghost (disappear after restarting the savegame)

### ISSUE THREAD

**Issue by Vincent14** [tsunamayo/Starship-EVO#5057]
### Short Description of the issue:

Visual glitch

### Steps to reproduce the issue:

[Video](https://youtu.be/FK2FhxasJNo)

### Environment
- Starship EVO version: 22w50c
- Graphics Card: 2070

**Comment by tsunamayo** [comment]
@Vincent14 Hi, this was fixed in 23w34b. Thanks
