### ISSUE TITLE
Bug: Exiting the ship commands while warping... do the animation but the ship doesn't travel!

### ISSUE THREAD

**Issue by Vincent14** [tsunamayo/Starship-EVO#5058]
### Short Description of the issue:

Visual warp effect without moving

### Steps to reproduce the issue:

[Video](https://youtu.be/K86yLE4dcCg)

### Environment
- Starship EVO version: 22w50c
- Graphics Card: 2070

**Comment by tsunamayo** [comment]
@Vincent14 Indeed good catch.

**Comment by tsunamayo** [comment]
@Vincent14 Actually the issue should have been fixed already, I cant reproduce that one. thx
