### ISSUE TITLE
Suggestion: mining another ship could allow to recycle enemy ships

### ISSUE THREAD

**Issue by Vincent14** [tsunamayo/Starship-EVO#5059]
### Short Description of the issue:

Currently it's not possible to collect ores or ingots/plates/bars from another ship. That could allow to get resources from wrecks

**Comment by Uncle-Ulty** [comment]
it will be able in the future, don't worry.

**Comment by tsunamayo** [comment]
@Vincent14 Yes scrapping will be a thing.
