### ISSUE TITLE
Bug: Grab one ore giving infinite multiple ores at the same time!

### ISSUE THREAD

**Issue by Vincent14** [tsunamayo/Starship-EVO#5060]
### Short Description of the issue:

I can infinitly grab a single ore!

### Steps to reproduce the issue:

I threw some ores on conveyor belts. Some felt on hull blocks (on the ground). Each time I tried to grab, the amount of given ores increase a LOT

![Capture d’écran (475)](https://user-images.githubusercontent.com/1963080/222715686-1deeb4a6-fcb3-4174-b410-0b696e089f26.png)

![Capture d’écran (476)](https://user-images.githubusercontent.com/1963080/222715699-789e446c-0ba7-4a50-895a-230b96cd9aac.png)

![Capture d’écran (477)](https://user-images.githubusercontent.com/1963080/222715719-33a58cf0-9555-4de7-82a5-9c5446a11e30.png)

### Environment
- Starship EVO version: 22w50c
- Graphics Card: 

### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/10881709/Player.log)

**Comment by Vincent14** [comment]
It could be possible that ores hit togethers before I remove the furnace that didn't "eat" them because the furnace was in the wrong direction

**Comment by tsunamayo** [comment]
@Vincent14 Hi, I have no idea how to reproduce this, let's open again if you ever get this again with a reproductible case. Sometime if there has been a previous error it can cause all sort of weird thing thereafter, in which ase I need to focus the base error only!
