### ISSUE TITLE
Pack of 6 bugs in the furnace inventory

### ISSUE THREAD

**Issue by Vincent14** [tsunamayo/Starship-EVO#5061]
### Short Description of the issue:

All those bugs happen around the furnace inventory:

- counter issues on resources used in input
- first item of storage is overwritten
- infinite output if draging before it's finished

### Steps to reproduce the issue:

[Bug 1](https://youtu.be/ZhK1OcwcZNY)
[Bug 2](https://youtu.be/S9jX0KabQqE)
[Bug 3](https://youtu.be/EIwEG-bYmXs)
[Bug 4](https://youtu.be/AS9tkvEDM_o)
[Bug 5](https://youtu.be/ZxGviEYMsgg)
[Bug 6](https://youtu.be/IYDT46jjPpQ)

### Environment
- Starship EVO version: 22w50c
- Graphics Card: 2070 RTX

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/10881822/Player.log)

**Comment by tsunamayo** [comment]
@Vincent14 Hi, I think the root issue was really being able to pick the input / output while processed. It is now fixed, same for the assembler. Thanks a lot for booking all these!

**Comment by Vincent14** [comment]
At some point it's going to be stable, thanks a lot !
