### ISSUE TITLE
Suggestion: Be able to connect tubes/hoses to furnaces

### ISSUE THREAD

**Issue by Vincent14** [tsunamayo/Starship-EVO#5062]
### Short Description of the issue:

That would be cool to be able to connect hoses/tubes when your furnace is built in a ship that doesn't have a working gravity generator. 

That would be useful when belt or collector in expel mode are buggy, because for now there isn't a proper way to use furnaces.

Tubes or hoses can take far less place and looks more organized when you build a factory

**Comment by tsunamayo** [comment]
@Vincent14 Yes it was planned and it is finally there for 24w35a. Thanks!

**Comment by Vincent14** [comment]
Thanks a lot for every single answer, that's motivating to report bugs!
