### ISSUE TITLE
Bug: free hose base often refuse to connect to another free base

### ISSUE THREAD

**Issue by Vincent14** [tsunamayo/Starship-EVO#5063]
### Short Description of the issue:

Two free hose "starting blocks" should always be connectable

### Steps to reproduce the issue:

[Video ](https://youtu.be/x4IXeXiRXAc)

### Environment
- Starship EVO version: 22w50c
- Graphics Card: 2070 rtx

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by Uncle-Ulty** [comment]
It happens because they are of different types. hose, corrugated hose and glowing hose must match the same type on both ends to be able to connect them.

**Comment by Vincent14** [comment]
I'd suggest that the final pipe style should be the one where the link starts 🤷‍♂️

**Comment by tsunamayo** [comment]
@Vincent14 This is not possible. I might add an icon, one is for inventory and one is for fuel. Thanks

**Comment by tsunamayo** [comment]
@Vincent14 Sorry I misunderstood that one, it was from same category but different brick. yes I think you are right they should be compatible or have a different style to the base so we can differentiate.

**Comment by tsunamayo** [comment]
@Vincent14 Fixed for 34w35a. Thanks
