### ISSUE TITLE
Bug: Spawned ships with AI onboard (passive or agressive) warp out as soon as possible

### ISSUE THREAD

**Issue by Vincent14** [tsunamayo/Starship-EVO#5065]
### Short Description of the issue:

AI ships warp out as soon as possible when spawned from F8 menu OR from starting cube, anywhere else than around the space station. This happen anywhere in space or on a space habitat ring

### Steps to reproduce the issue:

[Video](https://youtu.be/-93syDCyElk)

### Environment
- Starship EVO version: 22w50c
- Graphics Card: 2070 rtx

**Comment by tsunamayo** [comment]
@Vincent14 Well for now it is normal, their behavior is to navigate between stations, sometime trying to land, sometime just orbiting.
