### ISSUE TITLE
[BUG] Ghostbricks after copy/paste and ship respawn. Tankjoin Brick. 

### ISSUE THREAD

**Issue by CoasterBlock** [tsunamayo/Starship-EVO#5070]
### Short Description of the issue:
When you delete a ship with a fuel system, the bricks that connect pipes to the tanks remain behind. There is also a visual bug with copy and paste functions. When you select a fuel system with pipe attachments, all the connectors will show up as ghost blocks. They will dissapear once the clipboard has been emptied. 

### Steps to reproduce the issue:

1. Spawn in ship
2. delete it
3. connectors will be left in the world.

Bug 2: 
1. Select a fuel system with the copy/paste tool
2. once the clipboard is active, a floating copy of the Tankjoin Brick will float nearby
3. once clipboard has been emptied, the ghost blocks vanish.

 Environment
- Starship EVO version: 22W50C EXPERIMENTAL
- Graphics Card: RTX 2080 Super

### Additional information:
In my testing conditions I was using 16m fuel-system blocks, as my ship is very large. (32,4km long) So a physical scale factor of the ship/base grid is likely also an issue. However the clipboard effect is visible across all scales I have tested. So its likely the other bug applies to small ships too. 

Screenshot attached is of the pipe-connectors still remaining after I removed and replaced the ship to showcase the issue. 

![20230308213154_1](https://user-images.githubusercontent.com/126499309/223845446-e2679956-3efe-400a-8460-13c5b56ee18b.jpg)

**Comment by tsunamayo** [comment]
@CoasterBlock Hi, issue is fixed for 23w34b. Thanks
