### ISSUE TITLE
Suggestion: EMP mechanics

### ISSUE THREAD

**Issue by MrSquid1** [tsunamayo/Starship-EVO#5074]
Maybe on future combat, kinetics could have multiple different types of rounds each with it's own properties, for example EMP rounds:

EMP rounds disable the enemy's reactor, and can be countered by capacitors adding a use for them as currently there's no reason to use them over reactors. There are 2 posible aproaches that could be used:

-EMP rounds turning off a reactor and require a reboot to turn back on, this means that your ship needs a minimun amount of capacitors to turn back on after being downed by EMP rounds, larger ships could even have enough capacitors to reboot multiple times in a row.
**Pros:**
Can disable ships permanently, maybe could be used as a bonus objective when bounty hunting to get more money
**Cons:**
Hard to balance when dealing with fast firing EMP weapons

-The second aproach would be to have EMP rounds disable a reactor for a very small time, say 0.1 seconds, after which it will turn back on.

**Pros:**
It's easier to fight against EMP equipped ships without being specialised against them
**Cons:**
You can't permanently disable ships as a "non letal" method of combat

**Comment by tsunamayo** [comment]
@MrSquid1 Hi, yes indeed I want to do something like that for the weapon refactor. Yes I want you to be able to craft bullets / missile and add various type of damage type. Thanks
