### ISSUE TITLE
[Suggestion] Measurement tool

### ISSUE THREAD

**Issue by CoasterBlock** [tsunamayo/Starship-EVO#5075]
The measurement tool would work like the connection tool, but you would set two points first my right/left clicking point A and B respectively. You would then see a ghost-line like with the connection tool. The HUD would then display the distance between the points in meters and blocks. 

The tool would measure between A and B. So if you have a 52 block distance, A and B would sit at the "1st" block and the 52nd. 

**Little Text Example:**

[  ][ 1 ][**A**]---------------(50m | (Brickcount))---------------[**B**][52][  ]

The tool would also work in diagonals, it would be a simple way to measure distances on a grid and connected CE's without having to place "scaffolds" made out of bricks. You would also be able to place multiple of these. Maybe with a maximum value. 

Toogle options would include:

**show/hide:** 
Show/hide all active measurements "H"

**cycle/hightlight:**
Cycle and highlight individual measuremeants like you cycle autopilot. Hotkey would be "Z" for example. 
Hightlighted measurement would appear brighter on the HUD, and in Orange instead of Blue. 

**Focus:**             
Make one measurement stand out, and hide the rest. Focus would be hovering on a measurement and hitting "R"
Focus would be affected by cycle/hightlight, by hitting "Z" you would cylce the focused measurement. Hitting "R"   -                                                              again would switch focus mode off. Focused measurements appear in Blue, all other measurements are hidden but not deleted.   

Chain Measurement:
Personally id like "chain" selection. Select up to 16 points to able to be linked with their point to point measurements and their total distance. This option would be activated by pressing a different hotkey. "X" for example.  

The HUD distance would be dependent on the Grid size. If the grid is made from 32m bricks, the maximum distance for visibility would lets say be 3x the grids longest direction. So a 1kmx3kmx5km grid would have its measurements visible up to 15km away.

**Comment by tsunamayo** [comment]
I get the idea but dev time is limited and I want to keep the tool selection as minimum as possible, to not overwhelm newcomers. Thanks

**Comment by CoasterBlock** [comment]
That makes sense, thanks anway!
