### ISSUE TITLE
Bug: Warp to the system where you already are

### ISSUE THREAD

**Issue by Vincent14** [tsunamayo/Starship-EVO#5076]
### Short Description of the issue:

Warp to the system where you are kill the player and disappear the ship

### Steps to reproduce the issue:

I tried to travel in super-luminic speed out of the system, but finally realized I was far from anything and was going into an empty space, but I was far from anything, so I decided to warp using the holomap to the solar system where the map already localised me

### Environment
- Starship EVO version: 22w50c
- Graphics Card: 2070 rtx

### Additional information:

[Video](https://youtu.be/CNG-UWbYj4U)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/10984135/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/10984136/Player-prev.log)

**Comment by tsunamayo** [comment]
@Vincent14 Haha merci pour la video, fixe pour 23w35a.

**Comment by Vincent14** [comment]
Ah ah j'avais oublié ça 😅 bon courage !
