### ISSUE TITLE
[Bug] 22w50c - Revenge of the Event Gate Percentages Bug

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#5077]
### Short Description of the issue:
Percentages entered in Event Gate divide themselves by 100 each time the brick's interface is opened.

### Steps to reproduce the issue:
Place an Event Gate and link a Ship Core to it. Set the Event Registered to Power Usage Percentage. Then enter a value in the field, and exit the Event Gate's interface. Open it again, and you will see the value has been divided by 100. This bug appears to be the mirror image of [this earlier bug](https://github.com/tsunamayo/Starship-EVO/issues/4446).

### Environment
- Starship EVO version: 22w50c
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
Entering the initial value:
![20230315161357_1](https://user-images.githubusercontent.com/33041786/225446482-89e5142c-c246-48ec-9d0d-513b67dde3a9.jpg)

Opening the UI for the Event Gate, the value has been divided by 100:
![20230315161359_1](https://user-images.githubusercontent.com/33041786/225446527-b323485f-64a7-4e5d-92d1-cfe32066a85c.jpg)

And opening it again, it's been divided again:
![20230315161401_1](https://user-images.githubusercontent.com/33041786/225446576-3b53757e-cc21-4aac-871e-49446cd88cde.jpg)

This continues; I'm guessing the actual value here is .001, but the game won't display that:
![20230315161404_1](https://user-images.githubusercontent.com/33041786/225446777-758226c9-d645-4857-b50f-538194fd5a94.jpg)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/10984614/Player.log)

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Hi, this is fixed for 23w35b, although now you need to input 0.5 for 50%, so people will find it a bit confusing but will get used to it hopefully. Thanks
