### ISSUE TITLE
[Bug/Oversight] "0 Part" entities

### ISSUE THREAD

**Issue by AlienXtream** [tsunamayo/Starship-EVO#5081]
### Short Description of the issue:
entities with less than one part still "exist".

### Steps to reproduce the issue:
place starter block. remove starter block with no additional changes.
optional: place a mirror plane to "see" entity.

entities that have no parts in them should be automatically deleted

### Environment
- Starship EVO version: N/A
- Graphics Card: N/A

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![image](https://user-images.githubusercontent.com/12606809/226853281-15d2bcb4-c9b2-4252-9831-296e7c78a262.png)
![image](https://user-images.githubusercontent.com/12606809/226853406-34794484-50fe-4e89-8ffb-f5a114a3b738.png)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@AlienXtream They should not be saved though, which is decent enough (it wont create long term clutter). Thanks
