### ISSUE TITLE
Unable to turn off gimbal

### ISSUE THREAD

**Issue by TwoNiner29** [tsunamayo/Starship-EVO#5084]
### Short Description of the issue:
I have a turret that uses logic to fire the barrels, the barrels gimbal according to the pilots cursor which I don’t want because I want the turret to be able to shoot in other directions without my cursor affecting the aim

I have tried turning the gimbal value in the hot key block to zero, however it resets to 100 whenever I close the menu

I have also tried removing any hot key blocks linked to the barrels and they still gimbal, so it seems they do that by default.

note the barrels are not connected to the turret computer because I want to fire them manually with logic
...

### Steps to reproduce the issue:
 Build a turret without connecting the barrels to the turret computer 
...

### Environment
- Starship EVO version: experimental 
- Graphics Card: GTX 3060

**Comment by tsunamayo** [comment]
@TwoNiner29 Hi, so I have tested it now works fine. Thanks a lot!
