### ISSUE TITLE
François please

### ISSUE THREAD

**Issue by omrwcs** [tsunamayo/Starship-EVO#5085]
### Short Description of the issue:
François please emploid peoples to  build the  game lol
...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by omrwcs** [comment]
I would like to help you but do not know how, you had good ideas, I see that you need support and help

**Comment by tsunamayo** [comment]
@omrwcs Thanks you you know it is money problem!

**Comment by naoseiousername** [comment]
In this case, you can accept volunteers who aim to collaborate without any profit, aiming to help you and see the game running. I know how to make pages in html, make 3d models, sounds, could help in this.
