### ISSUE TITLE
Alt-tab on elevator causes no-clip

### ISSUE THREAD

**Issue by Kazosky** [tsunamayo/Starship-EVO#5086]
### Short Description of the issue:

Alt-tabbing out of the game on the tutorial elevators causes the player to phase through them and be stuck

### Steps to reproduce the issue:

Main elevator: Either with or without the jetpack, alt-tab whilst the elevator is moving up or down. Depending on the direction the player phases through the elevator ceiling or floor

Hangar elevator: Either with or without the jetpack, alt-tab whilst the elevator is moving upwards. Causes the player to phase through the floor

### Environment

- Starship EVO version: 22w44c

### Additional information:

https://user-images.githubusercontent.com/115942934/231188873-1e514d90-6e69-426a-a6c5-8a4d37d955dd.mp4

**Comment by tsunamayo** [comment]
@Kazosky This should be fixed in the current version. Thanks
