### ISSUE TITLE
cargo overfill

### ISSUE THREAD

**Issue by Starface420** [tsunamayo/Starship-EVO#5087]
### Short Description of the issue:
I connected a collector to a cargo storage, and did some mining... i connected a conveyor from that cargo, to another cargo to increase capacity.  the first cargo ( i think this happened before i messed with connecting to another cargo) is at 130% capacity.. I assume this is not supposed to happen?
...

### Steps to reproduce the issue:
connect a collector to a cargo hold.
...

### Environment
- Starship EVO version: latest I assume..i just got the game
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Starface420 This should be fixed in recent version of the game. Thanks
