### ISSUE TITLE
hand held weapons

### ISSUE THREAD

**Issue by Starface420** [tsunamayo/Starship-EVO#5089]
### Short Description of the issue:
After making a handheld weapon, and using it a bit, I switched back to the build tool, and a ghost of the handheld gun was left behind.
...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Starface420 Hi, I am not reproducing this issue. Thanks
