### ISSUE TITLE
Power/fuel

### ISSUE THREAD

**Issue by Starface420** [tsunamayo/Starship-EVO#5090]
### Short Description of the issue:
it doesnt seam to make any difference if you have auto-fill on or not.  if you have auto-fill tanks off, and have nothing connected to a fuel tank, everything still works... if you hover on a reactor, and it says "insufficient flow" you can jhust connect a tank join, and a pipe section on it, then delete it, and its "sufficient"
...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Starface420 This issue is fixed for 23w35a. Thanks
