### ISSUE TITLE
energy meter

### ISSUE THREAD

**Issue by Starface420** [tsunamayo/Starship-EVO#5094]
### Short Description of the issue:
doesnt appear to work? i grab ship controls, and the bar is halfway up, and drains quickly....let go of controls, and it shows it halfway up again, and drains quickly...but at no time does it seem to matter what the indicator says, everything always works the same.. 
...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
this should be fixed in recent version of the game. Thanks
