### ISSUE TITLE
Fuel tanks do not reach maximum capacity.

### ISSUE THREAD

**Issue by SethRaeder** [tsunamayo/Starship-EVO#5100]
### Short Description of the issue:

After building the ship seen below, the fuel scoop ran for approximately 8 seconds before stopping. The blueprint screen listed the ship as being 1% full with 5 liters of fuel.

### Steps to reproduce the issue:

Test build:
![image](https://user-images.githubusercontent.com/104173918/236939795-7363a0f8-6c9a-4797-b99d-80371be0a99d.png)

### Environment
- Starship EVO version: 22w44c

### Additional information:

Player log file (Unsure if needed)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/11425293/Player.log)

**Comment by tsunamayo** [comment]
@SethRaeder It is should be fixed in current version of the game. Thanks
