### ISSUE TITLE
[Bug] hinge/rotor angle value resets to strange numbers

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#5102]
### Description of the issue:
When inputting some values into a hinge/rotor, the mechanism resets or "reinterprets" the value and never reaches the original setting.

### Steps to reproduce the issue:
1. Interact with and manually input a number between -180 and 180 on a hinge or 1 and 360 on a rotor.
2. Close the UI.
3. Interact with the same mechanism. The value may be changed.

### Environment
- Starship EVO version: 22w50c [experimental]

### Additional information:
![Majikmonster_2023 5 10_bug_hinge and rotor values](https://github.com/tsunamayo/Starship-EVO/assets/51390907/6bce1a83-5f2b-4840-8d4c-558d3ccbd860)

Possibly related:
#5077 

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/11447412/Player.log)

**Comment by tsunamayo** [comment]
@Majikmonster This is just some float precision issue, so not a real issue. I have round the number displayed for the next build. Thanks
