### ISSUE TITLE
[Bug] game throws player stuck message while standing on/adjacent to surfaces

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#5103]
### Description of the issue:
While standing on/near bricks or terrain, sometimes the game will produce the warning that the player is stuck and must activate no clip mode. The game will not stop reproducing the message until F5 is pressed.

### Steps to reproduce the issue:
1. Stand on the habitat ring's terrain or on/in a built structure (more frequent with uneven surfaces and tight spaces).
2. Wait until game displays the warning message.

### Environment
- Starship EVO version: 22w50c

### Additional information:
![20230421123736_1](https://github.com/tsunamayo/Starship-EVO/assets/51390907/6ab11603-1e35-4412-8600-8a600257ef00)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/11447576/Player.log)

**Comment by tsunamayo** [comment]
@tsunamayo Hi, this should have been addressed in recent version of the game. Thanks
