### ISSUE TITLE
[Bug] player character shadow monster

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#5107]
### Short Description of the issue:
A buggy shadow ...thing... appears, cast by the player's avatar.

### Steps to reproduce the issue:
???
Maybe it's time-based or happens when the player travels too far too fast (I was warping from the starter system to the center of the galaxy when it happened).

### Environment
- Starship EVO version: 22w50c [experimental]
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![SEVO_Majikmonster_22w50c_shadow1](https://github.com/tsunamayo/Starship-EVO/assets/51390907/45048cfa-9bc5-48f0-a53a-98f923f4a9c5)
![SEVO_Majikmonster_22w50c_shadow2](https://github.com/tsunamayo/Starship-EVO/assets/51390907/c86c74ce-c038-4639-bc6e-168f9de4865f)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/11483115/Player.log)

**Comment by tsunamayo** [comment]
@Majikmonster This issue should be fixed in current version of the game. Thanks!
