### ISSUE TITLE
Fuel Blocks only spawn 6 Connectors

### ISSUE THREAD

**Issue by kynamats** [tsunamayo/Starship-EVO#5109]
### Short Description of the issue:
Fuel tanks, reactors & light cruise engines only spawn 6 fuel connector for piping, hoses or tank connectors. See image & note that each tank only has 6 pipes with connectors spawned.
![image](https://github.com/tsunamayo/Starship-EVO/assets/89156468/55950124-c4fc-4d25-aa8d-91502fd81f23)

...

### Steps to reproduce the issue:
Build a fuel tank/reactor/engine & attach 7 or more pipes & note connections
...

### Environment
- Starship EVO version: 22w50c
- Graphics Card: 3070ti

### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/11521178/Player.log)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@kynamats Hi, this is normal and a limitation of the system, only a maximum of 6 connection is allowed. I will make it clear inside the game. Thanks
