### ISSUE TITLE
[Bug] Can see asteroid ring through planetary body

### ISSUE THREAD

**Issue by NerArth** [tsunamayo/Starship-EVO#5112]
### Short Description of the issue:

![20230610163456_1](https://github.com/tsunamayo/Starship-EVO/assets/2742875/4e70e5c8-b071-4a3d-ad22-d617df321a83)

Asteroid ring visible through planet

### Steps to reproduce the issue:

Get close to the planet with the ring as shown in screenshot above.

Issue reproducible at least in this system for the tested version:

ursaphego
1382:2590
P2

### Environment
- Starship EVO version: 22w44c
- Graphics Card: Nvidia GTX 980 Ti

### Additional information:

Example where this issue **does not** happen, in my starter system:

![image](https://github.com/tsunamayo/Starship-EVO/assets/2742875/483e24b4-4d4c-49bd-8489-b15ed36aa1dd)

**Log file:**

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/11712848/Player.log)

**Comment by tsunamayo** [comment]
@NerArth This should be fixed in recent update.
