### ISSUE TITLE
[Bug] 22w50c - Ghost Decals

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#5113]
### Short Description of the issue:
With Debug Decals Volume enabled, a free-floating copy decals from the entity that is being worked on may appear. Additionally, another such copy may appear that does not move relative to the player. Beginning work on another entity causes the first copy to disappear, but the one that does not move relative to the player remains there.

### Steps to reproduce the issue:
This one is really weird, and I'm not sure what caused it in the first place, so I attached a video clip. It doesn't show up unless Debug Decals Volume is on, so this is probably low priority.

### Environment
- Starship EVO version: 22w50c
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
https://github.com/tsunamayo/Starship-EVO/assets/33041786/e8bf216b-3054-40f8-a302-2d22bb9ceb1e

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/11729187/Player.log)

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Indeed, it was fixed for 23w35a. Thanks
