### ISSUE TITLE
Ships stop working when near planets

### ISSUE THREAD

**Issue by ThePapit** [tsunamayo/Starship-EVO#5114]
I spent several hours creating a ship to finally fly it around. I went to explore a nearby planet and the entire ship froze and I was kicked form it as it carried on several hundred meters ahead of me. As I got to the ship I couldn't open my ships doors or anything that used a piston or rotation. After using no clip to enter, I tried entering the seat and yoke, but nothing would happen. I spawned a ship in and tried to fly away but it had the same problems. 

I created a new character to try and replicate the issue and was able to do it twice. On the second try, I recorded a video. The issue is roughly at the 4:50 mark. I left it long so you can see that it was a new character.

...

Spawn ship
Fly towards planet
Within some range, the ship will break

...

### Environment
- Starship EVO version: Latest Version on Steam (No Betas)
- Graphics Card: EVGA Geforce RTX 2080 Ti

### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/11834145/Player.log)

https://github.com/tsunamayo/Starship-EVO/assets/117874133/ae2850cb-741e-4802-924f-70144d0e4fb5

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by Kaiser-Indrasil** [comment]
That's by design, planets are a work in progress and you can't visit them yet.

**Comment by ThePapit** [comment]
Ah. Then I apologize for the report. It's a fantastic game.

**Comment by tsunamayo** [comment]
@ThePapit Hi, so your ship was being destroyed when running inside the gas giant.
In the current version there are a few differences though:
- the player not respawning bug was fixed.
- there are several warning message you are about to die if you go inside the planet
- you can now land on proper telluric planets!

Thanks
