### ISSUE TITLE
23w28a Planet terrain mining bug

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#5118]
Hi there,

I just tested how the terrain deformation would work and it has some bugs:

1. When the terrain was mined with a large mining beam, it doesn't stay like that when you move away from it and come back to it.

https://github.com/tsunamayo/Starship-EVO/assets/81495956/8561c896-bf2e-430e-b451-0c216dc8b8bd

2. When mining terrain with the hand tool and creating a deeper hole, you will sink through the ground and bounce up and down. 

https://github.com/tsunamayo/Starship-EVO/assets/81495956/2cb92ba0-3f62-4113-8d69-0a7f2f974397

I also noticed that the player sometimes gets stuck when walking inside a mined hole. Seems random and I can't make out how to recreate it.

**Comment by tsunamayo** [comment]
@BigBadKangaroo I have just fixed the mining issue, I keep you posted when I upload the build. Thanks

**Comment by tsunamayo** [comment]
@BigBadKangaroo Actually I only fixed the player falling through for 23w34b. Thanks
