### ISSUE TITLE
[Bug] Paint Menu is disorganized

### ISSUE THREAD

**Issue by Alkaliii** [tsunamayo/Starship-EVO#5119]
### Short Description of the issue:
The colors in the paint menu are no longer orderly.

...

### Steps to reproduce the issue:
Launch Game
Open Menu
Go to Paints
...

### Environment
- Starship EVO version: 23w28a
- Graphics Card: Nvidia GeForce RTX 3060

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12031034/Player.log)

![image](https://github.com/tsunamayo/Starship-EVO/assets/53021785/69e9c952-d849-4cb3-af7b-20888fe26be6)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by Alkaliii** [comment]
@Kaiser-Indrasil I believe this is a new world

**Comment by Alkaliii** [comment]
Restarting the program fixed the disorganization

**Comment by tsunamayo** [comment]
@Alkaliii Hi, can you reproduce on a fresh world? I had no issues.

**Comment by Alkaliii** [comment]
Currently no, I'll try to figure out what I did
