### ISSUE TITLE
23w28a - Ships don't like water

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#5121]
Hi there,

I flew my ship into the water, this is what happend: 

### ***epilepsy warning***

https://github.com/tsunamayo/Starship-EVO/assets/81495956/58655885-eaad-4306-bd92-d4b4157c908a

I can't interact with it anymore and can't even build on it

**Comment by Kaiser-Indrasil** [comment]
What are your computer specs?
Does it happen to every ship or just this one?
If it only happens to this one, can you please upload the blueprint here? Thanks

**Comment by BigBadKangaroo** [comment]
AMD Ryzen 7 3700x
Geforce RTX 2080Super

It happend just once with this ship after flying with full speed.
It also happend a second time, but I was using a different ship and I hoverd above the water and was leaving the pilot seat so the ship just dropped down. 

I can't replicate it reliably

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, it should be fixed for 23w28b. Thanks
