### ISSUE TITLE
[Bug] Copy-paste tool preview bugged

### ISSUE THREAD

**Issue by Alkaliii** [tsunamayo/Starship-EVO#5122]
### Short Description of the issue:
The copy-paste tool doesn't preview what you're pasting at all.

...

### Steps to reproduce the issue:
Launch Game
Select Copy-paste tool
Copy something
...

### Environment
- Starship EVO version: 23w28a
- Graphics Card: Nvidia Geforce RTX 3060

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12031088/Player.log)

https://github.com/tsunamayo/Starship-EVO/assets/53021785/5ea31da8-ae7b-46b0-986a-fc89173a4f4a

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by OvercomeDruid** [comment]
I have the same problem. However the update is really great, a lot of bugs have disappeared and very good work on the planets. THANKS :)

**Comment by tsunamayo** [comment]
Bug was fixed in 23w29c. Thanks
