### ISSUE TITLE
23w28a - weird lighting on planet

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#5123]
Hi there,

I flew around in one of my hovercrafts and found this weird lighting bug:

From afar the trees are withe and when getting closer they will reveal their real color:

https://github.com/tsunamayo/Starship-EVO/assets/81495956/68ae5e38-7069-4eb3-87c4-f4128f7705d7

**Comment by Alkaliii** [comment]
Are you underneath a cloud?

**Comment by BigBadKangaroo** [comment]
Nope, there were no clouds above while recording it.

**Comment by Kaiser-Indrasil** [comment]
Does it happen even after a game restart?
If so, could you provide a world archive saved at the location where the bug's occuring?

**Comment by BigBadKangaroo** [comment]
Even after a restart I can recreate this.

Here's the world save: 
[Planetos!!!.zip](https://github.com/tsunamayo/Starship-EVO/files/12031268/Planetos.zip)

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, thanks for the world, unfortunately not much I can do as it as it is limited by the shadow distance. The color change when the shadow starts to apply. 
This would need a massive refactor, so it is not really planned for now.
Thanks
