### ISSUE TITLE
[Suggestion] Shadow Render Distance

### ISSUE THREAD

**Issue by piotmetans** [tsunamayo/Starship-EVO#5125]
With the advent of planets, we really need a farther shadow render distance. Not only is it really helpful for taking pretty pictures, but it is also (imo) essential for planet-side gameplay. Here's one example: when flying along a ridge, I can't judge the distance I am from the ground. I find myself bumping into it far too often because it looks like I am much higher than I am.

In the first example, I am around 200m-300m away from the surface:
![image](https://github.com/tsunamayo/Starship-EVO/assets/660015/f459a728-94a3-4cc3-835b-4aa181661b74)

In this second example, I am on the ground:
![image](https://github.com/tsunamayo/Starship-EVO/assets/660015/128eb309-968d-4873-ae34-6ba1729c9ba8)

**Comment by COMICLER** [comment]
ive been thinking about this for a while

**Comment by tsunamayo** [comment]
Hi, yes I know it just really tricky tech wise. Game is already heavy GPU wise, so many ppl complains of FPS.

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo Maybe set it up as a drop down list in the graphics options for the shadow rendering distance like most games do?
