### ISSUE TITLE
23w28a - Warping crash

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#5127]
Hi there,

After warping a few times to find some interesting planets my game crashed, here's the log:
[Crash_2023-07-12_194711801.zip](https://github.com/tsunamayo/Starship-EVO/files/12032404/Crash_2023-07-12_194711801.zip)

**Comment by tsunamayo** [comment]
@BigBadKangaroo unfortunately I cant open this, the file is too big (2GB). Did you had weird stuff before the crash? It will be hard to investigate.

**Comment by BigBadKangaroo** [comment]
Yeah, I was flying around with high movement speed to check out some planets. And I warped to a few new systems while doing that. Might just be too much exploring in too short of a time

**Comment by tsunamayo** [comment]
@BigBadKangaroo Okay please tell me again if you get this again with a smaller log!
