### ISSUE TITLE
[BUG] [Planets] AMD issues MEGATHREAD

### ISSUE THREAD

**Issue by AfterRebelion** [tsunamayo/Starship-EVO#5129]
Created this issue, to track issues specific to users with AMD Graphics cards.
This way, we can leave #5117 , as there are several other issues being reported there, making following a single conversation difficult.

For general issues affecting all platforms, please validate if there is someone that has already reported that issue before, and if not, create a new issue report.

### Working:
- Sun, and fake gas planet.
- Torus ring.

### Issues

- [X] ~~AMD Users can't load a new world, infinite loading~~ -> Already fixed both in `experimental`, and `planets_amd`
- [ ] Bricks are not rendering (translucent), when launching a new save.
- [ ] Planets are not rendering on they're correct spot, only with a white halo visible from afar.
- [ ] Planet surface cuboids render individually, at a fixed distance from the player.

### Workarounds:
- If you use "Exit to Desktop", and reload the game with a previously generated save, bricks will render.
  - However, you will be stuck inside the medbay.

###### Screenshots of the issues:
<img width="235" alt="image" src="https://github.com/tsunamayo/Starship-EVO/assets/559819/60134a53-7366-4095-a026-9297ceb8a61d">
<img width="411" alt="image" src="https://github.com/tsunamayo/Starship-EVO/assets/559819/1bd032ae-6f0c-47d0-b46e-bfb46c2ba67a">
<img width="411" alt="image" src="https://github.com/tsunamayo/Starship-EVO/assets/559819/339aa8ff-afb7-441d-a6ed-9b4cd555c502">

###### Videos:
https://github.com/tsunamayo/Starship-EVO/assets/559819/6a3cce9b-4cc7-4e25-b969-06385d8ce4bd

###### Logs:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12038564/Player.log)

**Comment by AfterRebelion** [comment]
Adding a video, to show the "Planet surfaces are rendering at a fixed distance" issue.
https://github.com/tsunamayo/Starship-EVO/assets/559819/6a3cce9b-4cc7-4e25-b969-06385d8ce4bd

**Comment by AfterRebelion** [comment]
Enabling "View Octree Bounds" and "View Ocean Quadtrie Bounds" options in F3 Debug Menu shows that the game at least thinks the planet is in the correct spot, even if it's rendering elsewhere.
**Both options enabled.**
<img width="300" alt="image" src="https://github.com/tsunamayo/Starship-EVO/assets/559819/c168d593-03e8-410a-a7e6-02032086d42f">
**Only "View Ocean Quadtrie" enabled.**
<img width="300" alt="image" src="https://github.com/tsunamayo/Starship-EVO/assets/559819/436e8785-8f10-46ed-b261-6926bfc85dc2">
**Only "View Octree Bounds" enabled.**
<img width="300" alt="image" src="https://github.com/tsunamayo/Starship-EVO/assets/559819/1894e8c1-cc86-4b5c-b0b3-579aa7f4f3dc">

**Comment by Dwarf-LordPangolin** [comment]
I can confirm that I am also having these issues as an AMD user. Here's my log for them.

- Graphics Card: AMD Radeon RX 5600 XT

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12043927/Player.log)

**Comment by tsunamayo** [comment]
@AfterRebelion @Dwarf-LordPangolin Yeah sorry, today I can get my hand on an AMD laptop so hopefully it will be much faster to debug. I am pretty sure it must be something inside the compute shader, I will have to randomly search for it, now with access to a GPU it will just long, not painfully long. 
Cheers

**Comment by tsunamayo** [comment]
@AfterRebelion @Dwarf-LordPangolin Hi, so finally this should be fixed in current version 23w28b. Thanks!
