### ISSUE TITLE
Game won't start in experimental

### ISSUE THREAD

**Issue by SlimSumo** [tsunamayo/Starship-EVO#5134]
### Short Description of the issue:

When I want to launch the game, I have a white screen and then I see my desktop with the game cursor and the game doesn't respond anymore. It does it only with the experimental version. 

### Environment
- Starship EVO version: 23w28a
- Graphics Card: Nvidia gtx 1070 ti

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12051709/Player.log)

**Comment by tsunamayo** [comment]
@SlimSumo Hi, sorry to hear that. So are you created a new character or using an existing one?
The log is very short and not really useful unfortunately.
Could make sure your driver are up to date?

**Comment by SlimSumo** [comment]
Hello, that was the driver ! I completely forgot to check this, thank you ! :)

**Comment by tsunamayo** [comment]
@SlimSumo Okay good to know thanks!
