### ISSUE TITLE
 Previously built ships 'Die' due to power shortage in planetary gravity fields

### ISSUE THREAD

**Issue by kynamats** [tsunamayo/Starship-EVO#5136]
### Short Description of the issue:
Ships that have previously been fine in the ring gravity field now slowly drain their power when within planetary grav fields,  resulting in a complete loss of control. this ultimately results in the ship needing to be respawned to be piloted.
...

### Steps to reproduce the issue:
Pilot a ship (example provided) > https://steamcommunity.com/sharedfiles/filedetails/?id=2897677186
inside a planets gravity. after ~5mins the ship will drain its power reserves and become unresponsive, despite fuel being available and reactors being on. This cannot be worked around by using the 'refill all tanks' or 'force systems online' options in the entity menu.
...

### Environment
- Starship EVO version: 23w28b
- Graphics Card: RTX 3070ti

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12058984/Player.log)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by Dwarf-LordPangolin** [comment]
I've also encountered this issue. It may actually be affecting ships at the level of their blueprints. The reason I suspect this is that I tried to resolve the issue by unspawning the ship and respawning it elsewhere where it was not affected by gravity. Doing so did not resolve the power drain, and attempting to respawn the ship more than once caused the game to crash.

Ironically, the ship in question is the updated backer ship I just uploaded to the other repository. 🤣 

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12065146/Player.log)

Ship in question:
[Mistral.zip](https://github.com/tsunamayo/Starship-EVO/files/12065145/Mistral.zip)

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin @kynamats  So I indeed reproduced the crash on the mistral.
It seems related to fuel. If you use the auto-fuel option the ship is working fine. Now the fuel meter is not whether your reactors have fuel, its the level of the fuel tank that you flagged at reactor. So if they are not connected to the any reactor your ship will drain out. Are you sure there is not plumbing issues? 
Thanks

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Okay I have finally spotted the issue in the fuel logic. Fixed for 23w29a. Thanks!

**Comment by tsunamayo** [comment]
@kynamats Incredible ship by the way, but I dont seems I am able to make it start. HUD, interior, the weapons are incredible. There is a strong starwars vibe with this one!

**Comment by kynamats** [comment]
@tsunamayo Thanks for the kind words on the ship!! It was working when I last checked, so when I have some time i'll make sure it's working for the current build. Sorry for not following up with more testing, I'm currently moving house and country so I have a lot on my plate atm!!
