### ISSUE TITLE
Asteroid rings are all grey and do not generate in different colors

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#5138]
### Short Description of the issue:

Planet generation algorithm has an issue where it doesn't produce colorful asteroid rings, and instead makes them all default white-grey.
The reason I think it's an issue is, the new game trailer and planet feature previews showed colorful rings, and the ones that are in the game are all grey.

### Steps to reproduce the issue:
1. Boot up the title
2. Create a new world
3. Get outside the base and roam the star system
4. Warp to other star systems and notice that all planetary rings have a grey tint

### Environment
- Starship EVO version: 23w28b (base)
- Graphics Card: RTX 3070

### Additional information:
(Screenshots sourced from Steam Community Page and Discord server)

![image](https://github.com/tsunamayo/Starship-EVO/assets/63756057/26ac7abd-8638-4304-972b-7d6377b26f43)
![image](https://github.com/tsunamayo/Starship-EVO/assets/63756057/c8a63dce-efbb-4f39-b9e1-a85ae4b11f07)
![image](https://github.com/tsunamayo/Starship-EVO/assets/63756057/0941ef8d-b3d9-495b-a3e7-414ebccfcbb7)
![image](https://github.com/tsunamayo/Starship-EVO/assets/63756057/3d987468-8925-4c8d-ab47-095fc1e1ac00)
![image](https://github.com/tsunamayo/Starship-EVO/assets/63756057/4aebd956-9d32-427e-a334-bb11fb7fc1da)
![image](https://github.com/tsunamayo/Starship-EVO/assets/63756057/dc208b7e-a12f-47db-a860-23b9c077c58b)
![image](https://github.com/tsunamayo/Starship-EVO/assets/63756057/c5cb06af-b638-4508-b4ab-3f16f03738f8)
![image](https://github.com/tsunamayo/Starship-EVO/assets/63756057/67529920-c783-47f1-b1bb-c979cc3b3d2c)
![image](https://github.com/tsunamayo/Starship-EVO/assets/63756057/28e26b34-d3a4-4eeb-bcd8-b21dd2c2940c)

**Comment by tsunamayo** [comment]
Indeed. I repushed the build with the fix. Thanks!
