### ISSUE TITLE
Ascending from planets makes them look blurry and LOD changes are visible

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#5139]
### Short Description of the issue:

There are two similar issues within this ~~jira~~ report.
One pertains to my observation that the consecutive LODs load in a bit too late upon the player getting closer to a planet, which makes the LOD changes fairly noticeable.
Possible fix could be to make the LOD distances longer for every LOD.
Alternatively, this could be a candidate for one of the graphics options where the player can set LOD quality from high (long distances and more seamless LOD switching) to low (short distances, more visible switching, but smaller resource use).

The other issue pertains to a bad blend of terrain patches, especially when the player gets away from the planet, which make them look like a misaligned mosaic, with visible seams in between.
Also possibly the 2D mesh loads too late upon ascent? I'm thinking that because the planets look noticeably more blurry upon ascent than during descent.

### Steps to reproduce the issue:

1. Boot up the title 
2. Create a new world
3. Pick a solid planet, slowly get closer to it, and notice the visible LOD switches
4. Get away from the planet and notice terrain patches with very visible edges and mesh blurriness

### Environment
- Starship EVO version: 23w28b (base)
- Graphics Card: RTX 3070

### Additional information:

https://github.com/tsunamayo/Starship-EVO/assets/63756057/29ae9e9e-c03d-453c-a4c8-0faf16035ce5

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Yes, it is because there is no cross-fading on LOD-out of those textures. I think it is more of a nitpick than a bug, I will do when/if I have time ^^
Cheers
