### ISSUE TITLE
[BUG/SUGGESTION] Planet's atmospheres obscure the stars too much 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#5144]
https://github.com/tsunamayo/Starship-EVO/assets/56371294/d1f08801-4b5c-46b5-95e8-ad922ad55b88

video attached should show what i mean, I'm standing on a planet with little to no atmosphere and it looks like im standing on the edge of the universe (video below shows the view from the edge of the universe) and yet when I fly a bit away from the planet's surface it shows that I'm actually at the center of the universe, it would be cooler and make more sense if you could see the other stars in the sky, especially if there is no atmosphere. if this was done for performance reasons then i guess its fine but if possible it would be amazing if we could look up and see the stars (during day and night).    
Game version 23w28b

https://github.com/tsunamayo/Starship-EVO/assets/56371294/9157f248-965a-43f4-a09e-0bed11e8cb57

**Comment by tsunamayo** [comment]
@TIKIRobo Yes indeed it is something I need to fix.

**Comment by tsunamayo** [comment]
@TIKIRobo Fixed for 23w29a. Thanks
