### ISSUE TITLE
[BUG] Activating seccond yoke while controlling first yoke seems to break game and locks you in ship

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#5145]
### Short Description of the issue:
https://steamcommunity.com/sharedfiles/filedetails/?id=2976270234
using this ship I sat in the seat, activated the first joystick in front of me and then activated the second joystick next to me, then when i tried to exit the ship it let me exit the first joystick but not the second or the seat

### Environment
- Starship EVO version: 23w28b

### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12064726/Player.log)

**Comment by tsunamayo** [comment]
@TIKIRobo Hi, I was able to reproduce with another bp, the issue is fixed for 23w29a. Thanks
