### ISSUE TITLE
[Bug] 23w29a - Return of the Power Drain Bug

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#5152]
### Short Description of the issue:
Power still mysteriously drains from ships occasionally. Since the issue's back I thought I'd put the feedback here instead of cluttering the version thread with it.

### Steps to reproduce the issue:
Ships randomly drain their power. It might be related to spending time in a planet's gravity or area near it in space; whenever it's started happening to a ship, it's been in one of those two kinds of areas. Sometimes you have to run the ship in flight mode for a bit for it to trigger.

A simultaneous and possibly related issue is that the fuel capacity of the ship appears to be much greater than it should be, at over 3,000% of its capacity. I was wondering if maybe there's some kind of integer overflow error going on that's causing the fuel system to get confused, but I'm not a programmer so I dunno if that's a possibility here. :/

### Environment
- Starship EVO version: 23w29a
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
Note that the fuel value changes between the two screenshots, but only for the percent.
![20230717033157_1](https://github.com/tsunamayo/Starship-EVO/assets/33041786/f30593d9-44b9-412d-b4db-78aab0a89ed6)

![20230717033350_1](https://github.com/tsunamayo/Starship-EVO/assets/33041786/aa6bd265-1a20-494c-b428-506f4bc4a379)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12067539/Player.log)

[Mistral.zip](https://github.com/tsunamayo/Starship-EVO/files/12067546/Mistral.zip)

**Comment by Dwarf-LordPangolin** [comment]
### Update

OK. I think I've got this miserable little bug's number now.

I started with the fact that the cause of the elevated fuel level for the ship (which had risen to literally [over 99,000%](https://www.youtube.com/watch?v=SiMHTK15Pik)) was that the fuel level for some of the blocks in question was much higher than it should have been; one lightcruise engine had stored 2,213,873% of its total capacity.

I deleted all elements of the fuel system and rebuilt them, in case somehow the blocks themselves had gotten bugged. Then I rebuilt all the fuel systems and filled the tanks.

Filling the tanks only filled the ship's fuel to 55%. Even weirder though, the ship's fuel started growing after that, even though the auto-refill option was off. (That might be because it has two small fuel scoops for emergencies, but I wasn't near any gas clouds, and it filled the tanks very quickly). Regardless, the ship filled all the way up to 100%, where it stopped. I flew the ship around, staying out of the planet's gravity, and the power drain problem didn't surface. I saved this version of the blueprint as its own, "cleaned" instance. I then saved and restarted the game. I did a full lap of the planet, and both the power and the fuel stayed normal. This meant the cleaning had worked.

I then went down to the planet, flew around, landed, and saved the blueprint as a separate instance. I then saved and restarted the game, got in the ship, and tried to fly it. The second I took control of the ship, the power started draining. I exited the ship and went back outside of the planet's gravity, loaded up the cleaned instance of the blueprint, and did a full lap around the planet's ring system. Again, the cleaned version had no issues with power drain, meaning it is specific to the blueprint and not the player's state or anything.

I then saved and restarted the game again just to be sure. Once again, the cleaned blueprint made a lap around the planet with no issues, and the version that had been to the planet started losing power as soon as I took control of it.

I did one final check. I took the unclean version from the planet, and loaded another copy of it outside the planet's gravity. I checked the fuel level, and it once again had an impossibly large value of fuel, and had no power to fly with. I saved and restarted the game, took control of it, and it still had no power. I then saved yet another version, and once more removed all fuel system blocks, and rebuilt them. I saved this blueprint as a second "cleaned" instance, then saved and restarted the game.

On loading the game, I took the second "cleaned" version, and filled its fuel tanks. Once again, this only filled them about halfway (54%). Once again, they then began filling themselves up to full. Once they were filled, I took control of the ship and flew it around the planet, staying outside the gravity area. It made a full lap of the planet without suffering from the power drain.

### 
Summary

1. The power drain bug occurs in ships that have visited planets.
2. It is also somehow related to the fuel system, because removing all fuel system blocks from a ship afflicted with the bug and rebuilding them causes the ship to no longer have the issue.
3. It's _possible_ this bug has been present in some form since before the planet update. I've had power issues with my ships in the past, but I always attributed it to having forgotten to hook a reactor up somewhere, since my interiors tend to be asymmetric and pretty squirrely. It might be worth looking into whether there's a deeper issue with the fuel system blocks beyond the planet gravity element.


The two clean instances of the blueprint from testing:
[Mistral - Fuel Bug 4 (Clean).zip](https://github.com/tsunamayo/Starship-EVO/files/12073470/Mistral.-.Fuel.Bug.4.Clean.zip)
[Mistral - Fuel Bug 7 (Clean).zip](https://github.com/tsunamayo/Starship-EVO/files/12073471/Mistral.-.Fuel.Bug.7.Clean.zip)


The two unclean instances of the blueprint from testing:
[Mistral - Fuel Bug 5 (Unclean).zip](https://github.com/tsunamayo/Starship-EVO/files/12073472/Mistral.-.Fuel.Bug.5.Unclean.zip)
[Mistral - Fuel Bug 6 (Unclean).zip](https://github.com/tsunamayo/Starship-EVO/files/12073473/Mistral.-.Fuel.Bug.6.Unclean.zip)

**Comment by Dwarf-LordPangolin** [comment]
### Update

ProPeach had an excellent question, which was whether the act of visiting the planets alone is enough to cause this, or if it only affects BPs that are saved on them. I loaded another clean copy of the blueprint, flew down to the planet, landed, then flew around some more and went outside the planet's gravity. I then saved and restarted.

On reloading and taking control of the ship again, the power started draining, but stopped draining at 50%. I checked the fuel system blocks, and they all showed normal amounts of fuel, but the reactors were only at 50% for some reason. I got back in the ship and started flying around the planet, and after a little while the power started draining again, all the way down to zero.

So this seems to occur when a ship has been to a planet at some point, regardless of whether the ship is saved while on it or not.

**Comment by therhappy** [comment]
I experienced similar problems and tried to replicate the above situation (Loaded a "fresh" blueprint, landed, escaped the planet and restarted).

For some reason I do not experience a capped power drain, it will drain all down to zero when I fly it and recharge as soon as I let go of the yoke. However I experience a maximum power cap: the ship won't recharge above 70% of its energy, no matter how long I wait.

![image_waited_far_more_than_17s](https://github.com/tsunamayo/Starship-EVO/assets/29476405/d65979f2-54c5-4b13-b5a5-a2856a5990f3)

I looked at my different Reactor blocks and most of them are at 100% except for a few that are < 10% charged and not charging up nor discharging.
Here's one of them's description by the Link tool:
![image](https://github.com/tsunamayo/Starship-EVO/assets/29476405/95bc81d4-c329-4c03-9c54-896283a1d8b0)
This seemed to only affect small reactors with huge capacitors and piping flows > 10000% of required piping flow.


This might be a tangential problem? I'm biased to think it is related since I ran into it while investigating this issue. I will keep an eye on power levels and see if some other situations or details can help linking this with known issues.

**Comment by tsunamayo** [comment]
Thanks guys I am on the issue atm. It seems it is likely to be several issues we will see, indeed I can see on the mistral that one reactor seems okay and not the other. I keep you posted.

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Okay it was a real pain to track down for was likely a stupid code mistake (and which turned out to be the case), but it is finally fixed for 23w29b.
Cheers

**Comment by Dwarf-LordPangolin** [comment]
Awesome! Thank you so much for taking care of that, it sounds like it was hard to nail down.
