### ISSUE TITLE
[BUG] Chained yokes teleport to source 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#5154]
### Short Description of the issue:
same problem as #4436, i just wanted to bring it up again as it is still a problem  

### Environment
- Starship EVO version: 23w29a

https://github.com/tsunamayo/Starship-EVO/assets/56371294/2614fd64-595c-4077-8ffa-200668fc55bd

this second video shows a variation of the bug on a new entity (also if you turn the sound on you can hear an audio bug caused by me linking the second yoke to the first)

https://github.com/tsunamayo/Starship-EVO/assets/56371294/66f29a10-8359-43e7-8668-a3349f0e3b17

**Comment by TIKIRobo** [comment]
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12071827/Player.log)
including player log and both bps here
[broken yoke platform.zip](https://github.com/tsunamayo/Starship-EVO/files/12071832/broken.yoke.platform.zip)
[La'Pai - Airship.zip](https://github.com/tsunamayo/Starship-EVO/files/12071855/La.Pai.-.Airship.zip)

**Comment by tsunamayo** [comment]
@TIKIRobo Hi, this will be fixed for 23w29c. Thanks
