### ISSUE TITLE
Hose tool semifrequently spawns undeletable connectors

### ISSUE THREAD

**Issue by Hahahavana** [tsunamayo/Starship-EVO#5158]
The hose tool will sometimes spawn connectors that aren't deleted with the hose, and sometimes not spawn connectors at all. 
...

Step one: Use Hose on Reactor/Fuel Tank/etc.
Step two: delete hose

...

### Environment
- Starship EVO version: 23w29b
- Graphics Card: Nvidia 1660 Ti

### Additional information:
![20230718161426_1](https://github.com/tsunamayo/Starship-EVO/assets/69177015/05e8265d-e954-44a6-82e2-b7fa23ba9611)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12078719/Player.log)

**Comment by tsunamayo** [comment]
@Hahahavana This should be fixed for 23w34b. Thanks
