### ISSUE TITLE
Thruster visuals incorrect when pitching up

### ISSUE THREAD

**Issue by Starwhip** [tsunamayo/Starship-EVO#5161]
### Short Description of the issue:

When pitching up, the thrusters on the top of the craft ahead of the center of mass fire, when it should be the opposite. Other pairs of thrusters may do similar things, but it is hard to see when piloting.

### Steps to reproduce the issue:

Control ship, pitch up.

### Environment
- Starship EVO version: 23w29b
- Graphics Card: Radeon RX 6900XT

### Additional information:
![image](https://github.com/tsunamayo/Starship-EVO/assets/36343006/641d4862-c5e6-44f5-a70b-49a1a90d73fc)

Blueprint: 
[Dagger Class Jumpship.zip](https://github.com/tsunamayo/Starship-EVO/files/12083871/Dagger.Class.Jumpship.zip)

**Comment by tsunamayo** [comment]
@Starwhip Well those are not supposed to be realistic, on top of that you are incorrect, if you want to pitch up, the bottom thruster needs to fire a bit then stop, then the ship move, and when you want to stop the move the upper thruster needs to fire to cancel the move.
