### ISSUE TITLE
Twitter hacked

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#5162]
Hey @tsunamayo your Twitter got hacked and is promoting crypto, tagging lots of people in the post.
![Screenshot_20230718_203908_Twitter.jpg](https://github.com/tsunamayo/Starship-EVO/assets/63756057/540e6cde-241e-40c5-8322-17040f8d38d0)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Shit thanks for the heads-up!

**Comment by tsunamayo** [comment]
Should be good now!
