### ISSUE TITLE
23w29b - Assembler Production Queue Hiding Transfer Items Window

### ISSUE THREAD

**Issue by DrizztCode** [tsunamayo/Starship-EVO#5163]
### Short Description of the issue:

hi - as in the title - the transfer items window is behind the assembler production queue - and since we can't move windows or close the production queue it is basically hidden
...

### Steps to reproduce the issue:
just hit the transfer items button with the assembler open
...

### Environment
- Starship EVO version: 23w29b
- Graphics Card: RTX 2060

### Additional information:
if needed

thanks for all the great work :-)

**Comment by tsunamayo** [comment]
Hi, thanks I will check this out!

**Comment by tsunamayo** [comment]
@DrizztCode Fixed for 23w29e. Thanks

**Comment by DrizztCode** [comment]
> @DrizztCode Fixed for 23w29e. Thanks

awesome - works great now - thanks :-)
