### ISSUE TITLE
[Bug] 23w29b - Power drain bug still present

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#5164]
### Short Description of the issue:
I really hate to be the bearer of bad news, but the power drain issue is still present.

### Steps to reproduce the issue:
Same as before, ships in a planet's area can start losing power. I've included the blueprint of the Mistral this happened on.

I wanted to see if this was blueprint-specific, maybe there's something really weird about the Mistral, so I tried this on a couple different ships. Despite flying around on the planet for a while, I can't get the power to drain completely from the second ship, meaning that for some reason this is ship specific.

However, the second ship's power output is way less than it should be; even after shutting off the shields and warp core it doesn't get above 53% charge. Some of the blocks also have the same kind of impossibly large fuel storage that was present before (for example one reactor has), so I'm guessing this is either a different manifestation of the same bug, or a related bug.

### Environment
- Starship EVO version: 23w29b
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12088267/Player.log)

[Mistral - Son of Fuel Bug.zip](https://github.com/tsunamayo/Starship-EVO/files/12088307/Mistral.-.Son.of.Fuel.Bug.zip)

This second blueprint is the one that doesn't drain fully:
[Akula - Power Drain Testing.zip](https://github.com/tsunamayo/Starship-EVO/files/12089058/Akula.-.Power.Drain.Testing.zip)

**Comment by tsunamayo** [comment]
Yeah weird when I fixed two real bug already, and when I tested it was fine... I will retest again and keep you posted if I reproduce.
Thanks

**Comment by Dwarf-LordPangolin** [comment]
Yeah, this is a very uncooperative bug.

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Hi, so I have found another flaw - hopefully it should be good this time. I can fly on the ship for a long time. Funny enough I think there was never a relation to planet, I guess it was coincidental.
Cheers

**Comment by Dwarf-LordPangolin** [comment]
_Thank_ you! That's very interesting; earlier today someone else said they ran into the bug while away from the planets too. It sounds like that was indeed a coincidence. I'm sorry this bug has proven so troublesome for you.

**Comment by tsunamayo** [comment]
yeah no no worry, it was painful to track down the first time, the second time went much smoother but still time consuming. Hopefully we can bulletproof the inventory system, I know I have still a few other bugs related to crafting / inventory manipulation.
Cheers

**Comment by Gfauf** [comment]
I can confirm it doesn't have relation to being in a planet, it happened to me in the tutorial with the tutorial ship, also when putting new reactors those reactors run out of power too and never generates any power.

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Is it fixed on your side? I just had a burst of intermittent shut-down with the Mistral!
