### ISSUE TITLE
Collector still collecting when expelling 

### ISSUE THREAD

**Issue by Drillz007** [tsunamayo/Starship-EVO#5170]
### Steps to reproduce the issue: Place collector set to expel and have some ore inside it (if you have range set to anything more than a 0 it will still try to attract items again causing jams)

if possible having a foldered block (to split controls between blocks so we dont have both on the same menu) or separate skin to help show what the block is set to would also be helpful 

![image](https://github.com/tsunamayo/Starship-EVO/assets/63330810/f0d45e2c-012a-438d-b912-5905927a609b)

### Environment
- Starship EVO version: 23w29c

**Comment by tsunamayo** [comment]
Yes actually it was intentional, but I agree it might be confusing if you forgot, so I think I will get rid of that. Thanks

**Comment by tsunamayo** [comment]
@Drillz007 Hi, this is changed for 23w29e. Thanks
