### ISSUE TITLE
floating ingots [ BUG ]

### ISSUE THREAD

**Issue by Drillz007** [tsunamayo/Starship-EVO#5171]
### Short Description of the issue: Ingots from refined ores not following the local gravity 

...

### Steps to reproduce the issue: load ingots into range of a collector but set the collector range to be smaller (2m about) then load a bunch of ingots into that area as the ingots hit each other and bounce they inside the collectors pulling range they have a chance to bounce on the edge and leave the range but they continue to ignore the gravity in the area and go 0 G instead of falling (i can not get it to work for just raw ore only ingots)

...

### Environment
- Starship EVO version: 23w29c
![image](https://github.com/tsunamayo/Starship-EVO/assets/63330810/7faa21c4-2af7-4876-9fde-2ba3e4997180)

**Comment by Drillz007** [comment]
![image](https://github.com/tsunamayo/Starship-EVO/assets/63330810/0b98aee9-dfed-444e-8d99-45a36f2ede7e)

**Comment by tsunamayo** [comment]
@Drillz007 Thanks, issue is fixed for 23w29d. Cheers
