### ISSUE TITLE
[23w29d] Warping Broken

### ISSUE THREAD

**Issue by DrizztCode** [tsunamayo/Starship-EVO#5179]
### Short Description of the issue:
hi - not sure when this happened - but i can't warp anywhere

it initiates and start moving - but never accelerates enough for the old system to disappear completely into the distance, and then initiate the load of the new system - just seems to engage lightcruise and continue in that state (so the old system gets further and further away but never unload, with the ship travelling at hundreds of km/s)

i tried on multiple new games

and i was getting a lot of shaking for most attempts as well - not sure what that's about (edit: shaking stopped when i tested with one of the stock ships - so probably is related to something else)
...

### Steps to reproduce the issue:
try to warp somewhere on 23w29d
...

### Environment
- Starship EVO version: 23w29d
- Graphics Card: RTX 2060

### Additional information:
if requested

thanks :-)

**Comment by ProPeach** [comment]
Which ship were you using? Some players have been able to warp around and see planets OK so it'd help narrow down the cause. Could be something to do with the Light cruise engines

**Comment by DrizztCode** [comment]
> Which ship were you using? Some players have been able to warp around and see planets OK so it'd help narrow down the cause. Could be something to do with the Light cruise engines

i couldn't do it in any ship - i built a new one just now

i will try with one of the stock blueprints now

and this is on the latest build - i have been able to warp since planets were introduced - but i can't on 23w29d

**Comment by DrizztCode** [comment]
ok - i tried it with the Nazehzda Raider and got the same result

when i engage warp the ship acellerates to lightcruise but then just stays in lightcruise - it doesn't switch to the stage where the old system shoots off into the distance and then the game unloads the old system and loads the new (there is always a stutter for me at that point)

all i can do is exit the ship and unspawn it (otherwise afterwards it is not unspawnable since we are so far from a system) - and can only do that for a ship with an interior, since the ship continues in lightcruise/warp - with no interior the ship is lost (can warp to it after a reload but it is non interactable/selectable etc)

pretty sure this is just something that has cropped up in this build - but if people are able to warp successfully in 23w29d then of course please do let me know :-)

i did notice that various ships seem to spawn with an already selected warp location - on my next game i will try and warp to that location - but i can't imagine that would be the fix

is probably a puzzle only Tsuna can solve - if he is also getting this issue

**Comment by DrizztCode** [comment]
> i did notice that various ships seem to spawn with an already selected warp location - on my next game i will try and warp to that location - but i can't imagine that would be the fix
didn't work - but i did notice that i was able to spawn a ship way out in deep space and interact with it - which was cool :-)

but still no successful warp :-(

**Comment by tsunamayo** [comment]
@DrizztCode Hi, I have repushed a new build with the fix as it was a regression. Thanks for booking the issue quickly! Cheers

**Comment by DrizztCode** [comment]
> @DrizztCode Hi, I have repushed a new build with the fix as it was a regression. Thanks for booking the issue quickly! Cheers

awesome stuff :-)

always happy to help :-)

is working again now (i'm still getting some weird shaking with my own ships but that is clearly something else - i think it may be to do with a thrusters issue - i will post something if i can isolate it a bit more)

Cheers! :-)
