### ISSUE TITLE
Block Select Menu Wouldn't Work Bug

### ISSUE THREAD

**Issue by REsaY01451** [tsunamayo/Starship-EVO#5184]
### Short Description of the issue:
At some point, the menu to add blocks and tools to your hotbar stopped functioning. I could not select anything, and whenever I clicked on a slot it would count up a number like I was adding quantities to the slot.
...

### Steps to reproduce the issue:
I have no clue how this happened.
...

### Environment
- Starship EVO version: 
- Graphics Card: AMD RX 6800

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12135733/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by DrizztCode** [comment]
yeah - i have had stuff like this happen occasionally

either not being able to add stuff to the hotbar

or it doing the count thing

i also have no idea how to actually replicate - but i think it was often associated with other inventory related bugs

**Comment by Alkaliii** [comment]
I believe this relates to the new items that can be picked up on planets but don't have inventory sprites or data that appears in the UI.

**Comment by tsunamayo** [comment]
If you guys manage to reproduce consistently please tell me!
