### ISSUE TITLE
Visual Bug - "Ghost" Tank Joins

### ISSUE THREAD

**Issue by NEURALDELVERM** [tsunamayo/Starship-EVO#5187]
### Short Description of the issue:

Ghost Tank Joins that I can't delete or remove are plaguing an old build I am trying to update with the new fuel mechanics. It's covered in pipes, because they used to only be decorative. 
...

### Steps to reproduce the issue:

Spawn my ship that I was attempting to add a fuel system to. Delete one of the unjoined pipe ends on the round tanks, the one pointed at in the image, and left behind is a visual artifact. Then, delete the ship, those other tank join ghosts will probably still be there, until you reload the game/save.

...

### Environment
- Starship EVO version: 23w29d
- Graphics Card: Radeon RX 480 4GB

### Additional information:
[NDM - DxDiag - JUL-22-23.txt](https://github.com/tsunamayo/Starship-EVO/files/12137592/NDM.-.DxDiag.-.JUL-22-23.txt)

_(Screenshots, Videos, Error logs, Related issues)_
![](https://cdn.discordapp.com/attachments/342383722185883648/1132500680234516500/image.png)

![](https://cdn.discordapp.com/attachments/342383722185883648/1132500367469453462/image.png)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12137591/Player.log)

[[NDM] FIGHTER - SLEEK DEATH V3.1.zip](https://github.com/tsunamayo/Starship-EVO/files/12137589/NDM.FIGHTER.-.SLEEK.DEATH.V3.1.zip)

**Comment by tsunamayo** [comment]
@NEURALDELVERM Hi, this is finally fixed for 23w34b. Thanks
