### ISSUE TITLE
[BUG/SUGGESTION] Cargo and convayor blocks state "fuel flow"

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#5192]
![image](https://github.com/tsunamayo/Starship-EVO/assets/56371294/2a929d83-40ac-406b-a1f1-75bcb22ddad8)
Cargo blocks, conveyor tubes and other assorted blocks say fuel flow instead of something more proper like "item flow"
also fuel is measured in what I assume is liters but a lowercase L looks a lot like an uppercase i my suggestion is to make it say L and to change cargo to be Kg^2 and Kg^2/s when measuring volume so that there is a more clear difference between fuel tanks and cargo containers at a quick glance

**Comment by tsunamayo** [comment]
@TIKIRobo Hi, this will be fixed for 23w33a. Cheers
