### ISSUE TITLE
[BUG] LC engines and reactors read improper fuel flow 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#5193]
23w29d:
![image](https://github.com/tsunamayo/Starship-EVO/assets/56371294/01cdcf03-7ee4-4468-b36a-5c60d9879c57)
this lc engine is not attached to anything and yet it says that it has 25000% fuel flow, even after turning auto refuel off it remains this way 

![image](https://github.com/tsunamayo/Starship-EVO/assets/56371294/7478014e-04ed-4684-99ce-9ac6463e3c0c)
same for this reactor

**Comment by tsunamayo** [comment]
@TIKIRobo Hi, issue is fixed for 23w33a. Thanks ;)
