### ISSUE TITLE
Pistons don't transfer inventories to/from CE's?

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#5199]
### Short Description of the issue:

It looks like pistons don't allow the passage of inventories? The wiki suggests all mechanisms should be able to transport items but the piston seems to be the exception.

Combinations I've tried:
ore in space > collector > piston > hinge > conveyor cargo
ore in space > short pipe > collector > short pipe > piston > short pipe > hinge > short pipe > cargo

The collectors cannot see other inventories on the ship if you check them.

I've noticed that adjacent cargo boxes cannot see each other's inventories unless you connect them with a conveyor. This makes sense to me, you might want them together to save space but also you'd want to keep their items separate. So I tried putting conveyors on both ends of the piston but it seemed to have no effect.

Similar setups _without_ the piston have worked on the same ship. Attaching the collector to the cargo directly with a hose works as well.

### Environment
- Starship EVO version: 23w30a
- Graphics Card: GTX 1070 TI (don't think the issue is graphics-related)

### Additional information:
What I'm trying to do: (press button 1 to move the arms out)
![20230725164145_1](https://github.com/tsunamayo/Starship-EVO/assets/10069469/1423ccbd-6747-4080-8ff4-cedfdd1bc20e)
Works great except for transferring items from the collector arms to the main inventory.

Alternate attempt with conveyors:
![image](https://github.com/tsunamayo/Starship-EVO/assets/10069469/d32f1298-7bc2-48d5-a400-c477e50eb3a2)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12166197/Player.log)

I don't think the issue is specific to the blueprint but here it is just in case
[Nautilus.zip](https://github.com/tsunamayo/Starship-EVO/files/12166231/Nautilus.zip)

**Comment by Crimson-Artist** [comment]
This might be a general bug for all mechanisms. I just tested hinges and they also cant transfer items

**Comment by tsunamayo** [comment]
@asanagi-sae @Crimson-Artist Hi, I tested on a custom build, it was fine. It might be blueprint related? I keep you posted.

**Comment by tsunamayo** [comment]
Hi, I havent yet checked your build, but your assumption are incorrect:

ore in space > collector > piston > hinge > conveyor cargo
This wont work, you need a conveyor tube between the collector and the piston. I will try to make that more clear in an upcoming help and with warning message.
You also need a conveyor tube between the piston and hinge

ore in space > short pipe > collector > short pipe > piston > short pipe > hinge > short pipe > cargo
the first pipe is not necessary, then it should be correct (make sure those are conveyor tube and not fuel pipe though!)

**Comment by tsunamayo** [comment]
@asanagi-sae Okay thanks, I am on it.

**Comment by tsunamayo** [comment]
@asanagi-sae So I tested it, it was working fine with the short tube. Also I tested your ship, it seems it was fine...
I will push the current build and you will tell me if it works fine.
