### ISSUE TITLE
Screen just shows a single color and has no depth

### ISSUE THREAD

**Issue by Hypnoticsda14** [tsunamayo/Starship-EVO#5201]
### Short Description of the issue:
My game is fucked and I cant see anything
...

### Steps to reproduce the issue:
Load into game
...

### Environment
- Starship EVO version: early-access 23w30a
- Graphics Card: NVIDIA GeForce RTX 3060

### Additional information:
Im sure its from the workshop stuff I downloaded but I deleted it all and the issue is still happening also something with file validation because  single file keeps failing to validate

_(Screenshots, Videos, Error logs, Related issues)_
https://steamcommunity.com/profiles/76561199210015292/screenshot/2008093744118582466/
Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
I can not find it in my pc ive made sure i copy and pasted correctly 3x and could not find it
If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.
[Player.zip](https://github.com/tsunamayo/Starship-EVO/files/12198071/Player.zip)

**Comment by TIKIRobo** [comment]
turns out the bug was that the game was starting with an FOV of 0

**Comment by Hypnoticsda14** [comment]
yeah
