### ISSUE TITLE
Save botton crashs game

### ISSUE THREAD

**Issue by Reason147** [tsunamayo/Starship-EVO#5207]
### Short Description of the issue:

...After I go to save my project the game crash and gives me a hardware error popup notice.

### Steps to reproduce the issue:

...unknown, never happened before or in any other game.

### Environment
- Starship EVO version: 23w30a
- Graphics Card: AMD Ryzen 3 3300U with Radeon Vega Mobile Gfx   2.10 GHz, 16.0 GB (13.9 GB usable

### Additional information:
non-avable
_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Reason147 Hi, next time this happens could you please send me the log and the crash dump? Thanks
