### ISSUE TITLE
LC-Engine on CE doesn't work

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#5209]
Hi there,

Ships that have LC engines on a CE cannot enter LC and don't have an LC rating inside the ship computer.

LC engine has fuel and is connected.

![grafik](https://github.com/tsunamayo/Starship-EVO/assets/81495956/6b28c48c-0bc6-4450-9962-d0bacd22addb)
![grafik](https://github.com/tsunamayo/Starship-EVO/assets/81495956/1b7efe1d-b09a-4a20-8201-bc3ba338ab1c)

[LC-Bug.zip](https://github.com/tsunamayo/Starship-EVO/files/12216289/LC-Bug.zip)

https://github.com/tsunamayo/Starship-EVO/assets/81495956/69a63102-6da2-4bc4-8d16-59e0d954e016

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, the issue is fixed for 23w34b. Love all your ships btw, amazing job!
