### ISSUE TITLE
Rounded Corners broken at scale 4m+

### ISSUE THREAD

**Issue by Britanniczilla** [tsunamayo/Starship-EVO#5211]
### Short Description of the issue:

Rounded corners have a max scale value of 4m.

### Steps to reproduce the issue:

Use rounded corners above 4m scale

### Environment
- Starship EVO version: e-a 23w30a

**Comment by Britanniczilla** [comment]
Above 4m scale you cant place them at all, its weird.

**Comment by Majikmonster** [comment]
Is the bottom face of this brick invisible, too, or is my install just broken?

**Comment by CoasterBlock** [comment]
@Majikmonster  I encoutered invisible blocks as well. In my case its when you build using multiple rotors that are stacked on a piston. Sometimes it happens with too many bricks in the local area.

**Comment by Majikmonster** [comment]
@CoasterBlock I was unaware of that bug. What I mean is that the rounded corner brick specifically has a missing bottom face. I've encountered no other brick (that I can recall) having a missing face. I'm wondering if anyone else has this problem, or if it is only my game's install that is missing the texture.

**Comment by TIKIRobo** [comment]
@Majikmonster i also have the bottom face invisible bug

**Comment by Britanniczilla** [comment]
the block is bugged in multiple ways, its missing its bottom face, it cant be scaled above 4m, there's probably something else we haven't encountered yet.

**Comment by CoasterBlock** [comment]
To be honest, all the curved/rounded bricks are buggy. The hollow arches and domes, have solid hitbox for example. There is inconsistency with the physical shape of bricks and their hitboxes.
