### ISSUE TITLE
23w30a-[BUG] Wedge Sliders do not work

### ISSUE THREAD

**Issue by Crimson-Artist** [tsunamayo/Starship-EVO#5213]
As the title says. The wedged version of the sliders won't move. The normal version works perfectly.  

### Steps to reproduce the issue:

*Place a wedged slider down and link it to a mechanism.
*Try to move the slider portion

**Comment by tsunamayo** [comment]
@Crimson-Artist Hi, this is fixed for 23w35b. Thanks!
