### ISSUE TITLE
[BUG]character reaches for wrong yoke

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#5226]
https://github.com/tsunamayo/Starship-EVO/assets/56371294/0b084307-2b06-45bc-ba99-cafc0d661aa0

as you can see in this video the character reaches for the internal control stick instead of the much closer one i actually want to grab, this could be fixed by having the option to choose if yokes are grabbable or not

**Comment by tsunamayo** [comment]
@TIKIRobo Well you cant really have setting on a yoke, as you can only enter them. The game is doing its best to find the closest yoke, maybe I could add more test but honestly for now just put the second close further away! Thanks
