### ISSUE TITLE
Messed up models

### ISSUE THREAD

**Issue by ElNico56** [tsunamayo/Starship-EVO#5228]
### Short Description of the issue:

Rounded blocks seem to have missing faces and skewed normal vectors

### Steps to reproduce the issue:

Just place rounded corners and the sort and view them from different angles to appreciate the seams

### Environment
- Starship EVO version: 23w30a
- Graphics Card: nvidia 1650

### Additional information:

![image](https://github.com/tsunamayo/Starship-EVO/assets/18220871/8bdee0ec-a19e-4eea-9bea-89810b9dba6d)

![image](https://github.com/tsunamayo/Starship-EVO/assets/18220871/e8fb97eb-eda6-4a56-bc0d-b826f6a7d230)

**Comment by tsunamayo** [comment]
@ElNico56 Hi, this is fixed for 23w34b. Thanks
