### ISSUE TITLE
[Bug] Link Tool Tip for mechanisms does not show if mechanism is connected to Turret Computer

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#5229]
### Short Description of the issue:
Normally if you click on a mechanism with the link tool, it shows this helpful GUI.
![image](https://github.com/tsunamayo/Starship-EVO/assets/27857711/5846630c-3303-40c2-8938-1aedaf082aa4)
However if you link a Turret Computer to this Hinge, that GUI element does not show. Instead you see this.
![image](https://github.com/tsunamayo/Starship-EVO/assets/27857711/38ce8544-2dcb-4dae-9a9a-9c3e2ea562f1)

### Steps to reproduce the issue:
- Use the Link Tool on a Hinge to show the Mass Limit GUI
- Link a Turret Computer to the same Hinge
- Check with the Link Tool again
- Even if you unlink from the Computer, the Mass Limit GUI will never show for that Hinge again until you replace it

### Environment
- Starship EVO version: 20w30a
- Graphics Card: RX 6700XT

**Comment by tsunamayo** [comment]
@ProPeach Issue fixed for 23w34b. Thanks!
