### ISSUE TITLE
[BUG] Game Crashes on world start up

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#5232]
When trying to load into a world the game crashes, so i verified file integrity and it found one bad file, but when trying again my game crashes and I have one bad file 
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12360954/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/12360955/Player-prev.log)
does not generate crash dump somehow 
may be related to AMD card and the fact that I logged out in orbit of a planet looking down at it?

**Comment by TIKIRobo** [comment]
after a few tries (and not validating the files through steam) i can load into the world again, very strange

**Comment by tsunamayo** [comment]
@TIKIRobo Did you restarted windows in the meantime?

**Comment by TIKIRobo** [comment]
Nope, i didn't restart my pc or anything

**Comment by tsunamayo** [comment]
@TIKIRobo Okay closing this unfortunately as I have no way to investigate...
