### ISSUE TITLE
Flashing decals/ interferences

### ISSUE THREAD

**Issue by Citronix** [tsunamayo/Starship-EVO#5233]
### Short Description of the issue:

I lunched a fresh save, did the tutorial and noticed some artefacts with decals above a door.
It's directly linked to FOV and the player orientation.
it happens with every FOV settings, but the higher the FOV, the closer the artefacts apears.

### Steps to reproduce the issue:

- Set your FOV between 60 and 80
- go through the second slit wall of the tutorial (that's how i noticed the bug) 
Note that you will have a 45° ish angle compared to the ground
- look at the door frame in front of you, the black outline will desapear with square artefacts

### Environment
- Starship EVO version: EA 23w30a (not experimental)
- Graphics Card: NVIDIA Geforce GTX 1660 Ti

### Additional information:

Screenshots :

![711980_20230816232147_1](https://github.com/tsunamayo/Starship-EVO/assets/33103748/aa700357-7eda-4d7d-bcf4-feeaca54af71)
![711980_20230816232137_1](https://github.com/tsunamayo/Starship-EVO/assets/33103748/fcd51722-67ca-474b-a1c7-00d4d74646d2)

> Notice on the second screenshot, the artefacts are smaller because the player isn't tilted as much as in the first one.

![711980_20230816231956_1](https://github.com/tsunamayo/Starship-EVO/assets/33103748/88df6469-ee63-42b6-a697-5293c3e54195)
![711980_20230816231934_1](https://github.com/tsunamayo/Starship-EVO/assets/33103748/3d40d0ac-0421-44a7-8f88-ea5f62067e27)

> The FOV is greater on the fourth screenshot (100) and is about 50 on the third one. The distances aren't the same, the 4th is closer to the door frame then the 3rd. 

![711980_20230816232040_1](https://github.com/tsunamayo/Starship-EVO/assets/33103748/461bdce8-8731-4682-9acb-15df13219a6d)

> You can also notice some weird thing happening on the screen border due too a high FOV (100) in the last picture

Videos :
https://youtu.be/_qHqbV1vR_M
https://youtu.be/i9pbXEmrxmo

Player log :
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12363732/Player.log)

**Comment by tsunamayo** [comment]
@Citronix Hi, issue is fixed for 23w34b, although it will always creep back when many decals are being used and viewed in the same region of the screen. Thanks
