### ISSUE TITLE
[Bug] 23w30a- Simple Chairs and Gravity units have incorrect hitboxes 

### ISSUE THREAD

**Issue by Crimson-Artist** [tsunamayo/Starship-EVO#5234]
As the title says. The area above the back rest on simple chairs won't allow blocks to be placed there. 
![20230818104500_1](https://github.com/tsunamayo/Starship-EVO/assets/112352428/d9e81a75-94f2-4eca-aa8c-da79acadba6b)

A similar issue is with gravity units. blocks can not be placed on its "Face". 
![20230818104454_1](https://github.com/tsunamayo/Starship-EVO/assets/112352428/fdec6954-07c4-4a6f-9546-1018b14cfba2)

**Comment by CoasterBlock** [comment]
Gravity generators and shipyards share the same model, so to add to this bug-report: Shipyards have the same issue. The hitbox seems to be slightly taller than the brick suggests.

**Comment by tsunamayo** [comment]
@Crimson-Artist Hi, issue is fixed for 23w34a. Cheers
