### ISSUE TITLE
[Bug] Landing Gear Hotkey does not display on HUD

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#5237]
### Short Description of the issue:
1) When using a Yoke hooked up to an Event Gate, you can write custom HUD labels for many of the events using these options in the gate GUI
![image](https://github.com/tsunamayo/Starship-EVO/assets/27857711/83597720-83bb-444d-8c29-6fcd91d5e8ec)

However, when you select the "Landing Gear Is Pressed" event, these options disappear. Nothing shows on the ship HUD either
![image](https://github.com/tsunamayo/Starship-EVO/assets/27857711/d5672bb5-e136-4c9d-833b-3db586555cc3)

Suggestion - Either enable custom labels for this event too, OR have a default label "Landing Gear". Or both! Maybe have the custom label enabled by default with the label already filled out as "Landing Gear" when you select this event.

### Steps to reproduce the issue:
- Use a Yoke connected to an Event Gate with the "Landing Gear Is Pressed" event
- Check the HUD

### Environment
- Starship EVO version: 23w30a
- Graphics Card: RX 6700XT

**Comment by tsunamayo** [comment]
@ProPeach Yes apparently it was never really working since the event gate I presume? I also guess that you guys must be using it this way?
yoke -> event gate -> switch -> mechanism
How about I add an auto-switch function to the event gate, it would be more robust.
Thanks

**Comment by ProPeach** [comment]
Yeah it's not something I really thought about until recently when I was polishing up a ship for the Workshop so I guess I missed it till now. An inbuilt switch would be great for the event gate!

**Comment by tsunamayo** [comment]
okay I will add that.
