### ISSUE TITLE
[Suggestion] Allow Sliders to be turned off and on with other logic inputs

### ISSUE THREAD

**Issue by Crimson-Artist** [tsunamayo/Starship-EVO#5238]
Sliders occupy an extreme niche when it comes to contraptions. They have great potential stopped only by the fact that they are manual use only. If they're On state remembers at what value their were at then they could be used in all sorts of creations.

For better illustration. imagine this set up. You want to use a slider to make a piston extend or retract along its maximum length but you also want to just be able to turn the whole thing off to pack it away. Just link the Slider to the piston and then link a switch to the slider.
 ![20230820020603_1](https://github.com/tsunamayo/Starship-EVO/assets/112352428/3e30e6a1-5a4c-4e3e-ba64-6e41a0598714)

From there when the switch is on, the slider will always remember the value its currently at. 
![20230820020641_1](https://github.com/tsunamayo/Starship-EVO/assets/112352428/62f9cb7f-dabe-42fe-97b7-4320acbb614c)

Turning the switch off will return the slider to its lowest value/off. This allows players to come up with all kinds of circuits that allow for unique player input.
![20230820020651_1](https://github.com/tsunamayo/Starship-EVO/assets/112352428/b8957cdd-759d-425d-8bfd-f5b13be38284)

**Comment by tsunamayo** [comment]
@Crimson-Artist Hum I kinda get your idea but it is redundant with the sequence, where you can specify ON and OFF values.

**Comment by Crimson-Artist** [comment]
the switch, as well as any other logic input connected to the slider, will act as an absolute off. Since the slider remembers at what value its at the idea is you will be able to to move the slider back and forth to achieve an arbitrary value while the switch is on but when you turn the switch off the sliders value immediately goes to 0.

Imagine a crane where you can control its length and position with sliders and instead of having to pull every slider all the way back to 0 just to return it to a resting position you can just hit a switch linked to every slider. when you turn it back on the sliders remember their values and the crane returns to its previous position. 

this would also work incredibly well with lights as you can use a slider to specify how bright you want them to be and while also being able to turn them all the way off easily.
