### ISSUE TITLE
[Bug] Pipe Joins do not unspawn when blueprints are unspawned

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#5242]
### Short Description of the issue:
When you unspawn a ship, not all Pipe Join bricks despawn with it
![image](https://github.com/tsunamayo/Starship-EVO/assets/27857711/25000db7-298f-4c74-95aa-fd9974efffe5)

![image](https://github.com/tsunamayo/Starship-EVO/assets/27857711/0a9f86d0-714b-40ef-90d2-a94cbdfd8e38)

There is no way to remove these bricks, you have to restart the game. It happens on many different BPs but I've attached this particular one just in case

### Steps to reproduce the issue:
- Spawn BP
- Unspawn BP
- See the remaining bricks

### Environment
- Starship EVO version: 23w33a
- Graphics Card: RX 6700XT

### Additional information:
https://steamcommunity.com/sharedfiles/filedetails/?id=3024293235

**Comment by CoasterBlock** [comment]
Yeah, I encountered that iussue too, I reported it a while ago, so it is a long stading bug. #5070 was it I belive

**Comment by tsunamayo** [comment]
@ProPeach Hi, issue fixed for 23w34b. Thanks
