### ISSUE TITLE
[Newbie Trap] Bricks that come with a default colour

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#5243]
Some bricks, like Tanks and Hoses, have a default colour when you place them down unlike nearly every other brick in the Codex.
![image](https://github.com/tsunamayo/Starship-EVO/assets/27857711/f65738eb-d2e3-4dd6-abff-a0f6daeccf88)
Chatting in Discord today it seemed that some players, particularly newer ones, wanted to paint these bricks with a metallic colour but thought they could not. After all, if you try and apply a material to these bricks with default settings, nothing appears to happen.

More experienced players may know that in fact they are changing the material separately, but it won't show due to the default paint colour existing over the top of it. They might know to use the "Material Remove Paint" option in the F1 menu which will apply the material and clear the paint successfully, but to a newer player who doesn't know about that setting, it will appear that they cannot apply a material colour to these bricks.

This is actually also true of the Mug! 😄 

It would be great if these bricks were placed with a steel appearance by default, like every other brick, to help prevent this situation. They can still keep their unique colour in the Codex like other bricks to keep the Codex colourful though, better than it all being the same steel!

**Comment by tsunamayo** [comment]
Hi, I would rather say to update the material remove paint default setting...

**Comment by tsunamayo** [comment]
I just update the default setting for next update. Cheers

**Comment by ProPeach** [comment]
> I just update the default setting for next update. Cheers

What did you do to change the setting? I felt that changing the default appearance to steel was the best option as it didn't require any knowledge of the setting for newbies to get the benefit. For a player that doesn't interact with the community on say Discord, it can be tough to find little tips and tricks like that otherwise
