### ISSUE TITLE
[Bug] Pick Paint Colour duplicates paint in inventory, does not snap to existing paint on hotbar

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#5244]
### Short Description of the issue:
When using the Middle Mouse Button command to pick a block, the game will search your hotbars to see if the block already exists there and snap to it, otherwise it will place the block on your hotbar in the current slot.

When using the same command for paint colours, a new paint colour will be placed on your hotbar, even if it already exists on your hotbar. This can quickly lead to all your empty slots filling up with duplicate paint colours.

https://github.com/tsunamayo/Starship-EVO/assets/27857711/bab28204-b427-4f10-a2b0-fa469d706cc4

### Steps to reproduce the issue:
- Grab a paint, and paint a brick.
- Switch to an empty slot on your hotbar
- Use the MMB to Pick the colour from the painted brick
- A new hotbar slot will be created with a duplicate paint

### Environment
- Starship EVO version: 23w33a
- Graphics Card: RX 6700XT

**Comment by tsunamayo** [comment]
@ProPeach Thanks, issue is fixed for 23w34b. Cheers
