### ISSUE TITLE
[Bug] Rounded Corner brick cannot stretch more than 4m in the Y direction

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#5246]
### Short Description of the issue:
This brick becomes unplacable if it is stretched more than 4m up, no matter what scale you use. This means that if you use a scale larger than 4m, it is cannot be placed at all

https://github.com/tsunamayo/Starship-EVO/assets/27857711/e8a5fde2-e794-4800-954c-b6c073db0ff7

 Stretching in directions X or Z is working as normal. 

### Steps to reproduce the issue:
- Attempt to stretch the Rounded Corner hull brick more than 4m in the Y direction

### Environment
- Starship EVO version: 23w33A
- Graphics Card: RX 6700XT

**Comment by ProPeach** [comment]
This has also been reported in issue #5211, along with other related bugs like missing faces and inaccurate collisions.

**Comment by tsunamayo** [comment]
@ProPeach Fixed for 23w34b. Thanks!
