### ISSUE TITLE
Event Gate, listen to space computer, Heat balance percentage

### ISSUE THREAD

**Issue by Tackietacktack** [tsunamayo/Starship-EVO#5250]
Short Description of the issue:

Event Gate, listen to space computer, Heat balance percentage. 
I change Value threshhold: 100% but get 1%.
When I open the event gate windows now, is the value by 1%, if I close the windows and open it again value 0,01% and get 0,01 %.

**Comment by tsunamayo** [comment]
@Tackietacktack Hi, the issue will be fixed for 23w35b. Thanks
