### ISSUE TITLE
Refueling is problematic - bugs with harvesting and expelling gas

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#5251]
### Short Description of the issue:

As the title says.
The game has no problem harvesting fuel from pre-generated gas clouds, but it does have a problem with clouds generated with the Expel function of the ship-mounted fuel scoops.

Sometimes the Expel function generates a cloud visually, but doesn't transfer the fuel to it from the ship and is not visible on radar.
Sometimes it doesn't generate a cloud visually, but it can be detected by the targeting system, but cannot be harvested from, even though it has, say, 250L of fuel inside.

I didn't manage to find any consistency to their behavior.

### Environment
- Starship EVO version: 23w34b
- Graphics Card: RTX 3070

### Additional information:

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12450632/Player.log)
[Blueprint](https://github.com/tsunamayo/Starship-EVO/files/12450608/Mako.Mk1.zip)
[World file](https://github.com/tsunamayo/Starship-EVO/files/12450610/Release.23w30a.zip)

![image](https://github.com/tsunamayo/Starship-EVO/assets/63756057/546c8721-ee4d-4dc7-b720-5ee9456ae8e8)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Hi, to have a tracking widget it should needs at least 5000L of fuel. I tried to reproduce with your blueprint but it has no fuel system. With another ship it was working fine... I did a few fixes recently so I will ask you to retry with the new patch 23w35a. Cheers

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo Hey, it's working flawlessly now, thanks!

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Cool good to know!
