### ISSUE TITLE
Fuel Scoop expel effects persist after entity deletion

### ISSUE THREAD

**Issue by Janssendel** [tsunamayo/Starship-EVO#5252]
### Short Descriptor:

Fuel Scoop expel effects do not despawn on entity deletion (either through manually deleting the block or deleting the whole ship/mechanism) 

### Steps to reproduce the issue:

Place a fuel scoop, then connect a fuel tank to it (full or not doesn't matter). Set the Fuel Scoop to Expel mode, and the fuel within the fuel tank won't be expelled at all

### Environment
- Starship EVO version: 23w34b
- Graphics Card: Intel(R) HD Graphics P630 and NVIDIA Quadro M1200

### Additional information:

![image](https://github.com/tsunamayo/Starship-EVO/assets/61640498/2f732921-497a-4c59-a434-f6b7700ca6b7)
![image](https://github.com/tsunamayo/Starship-EVO/assets/61640498/b37c3cc6-6d01-4065-bc79-b761ccf0531e)
(these two show how even after deleting the fuel scoops, the expelling effect persists)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12452897/Player.log)

**Comment by tsunamayo** [comment]
@Janssendel Hi, this is fixed for 23w35a. Thanks

**Comment by Janssendel** [comment]
Thanks for letting me know!
