### ISSUE TITLE
Major bug: Handhelds have unstable behaviour and drift from player position during use and blue plumes appear for no apparent reason

### ISSUE THREAD

**Issue by Janssendel** [tsunamayo/Starship-EVO#5265]
### Short Description of the issue:

Handheld weapons will drift out of a player's hand during movement and become stationary. Reselecting the weapon does not work. The blue plume bug happens when you have 20 or more barrels on a handheld.

### Steps to reproduce the issue:

Place an item stand and select the gun you want to use. Using it after a while will start the bug. This isn't guaranteed but will sometimes happen if you use any weapon that is spawned using the item stand 

The Blue plume bug was encounted on this blueprint: 
[KSID-LMG - Copy.zip](https://github.com/tsunamayo/Starship-EVO/files/12497562/KSID-LMG.-.Copy.zip)

### Environment
- Starship EVO version: 23w35b
- Graphics Card: Intel(R) Graphics HD P630 and NVIDIA Quadro M1200

### Additional information:

![image](https://github.com/tsunamayo/Starship-EVO/assets/61640498/293dfc4c-6a06-4f40-a9bb-fc78622506c1)

[KSID-LMG - Copy.zip](https://github.com/tsunamayo/Starship-EVO/files/12497562/KSID-LMG.-.Copy.zip)

https://github.com/tsunamayo/Starship-EVO/assets/61640498/a67345e2-a0e5-42d3-9738-00127f97780a

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12497578/Player.log)

**Comment by tsunamayo** [comment]
@Janssendel Hi, issue will be fixed for 24w03a. Thanks!
