### ISSUE TITLE
[Second Hand Bug Report] Newcomers FOV is set to 0 by default

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#5270]
### Short Description of the issue:
This is something I haven't experienced, but it's something that some newbies seem to have happened to them. When they first boot up the game and load into a world, their FOV is set to 0. This means that the screen shows pretty much nothing useful and looks blank, making it hard to diagnose the issue if you don't know to check the settings. I haven't heard of any established players suffering from this particular bug, so I can't really give much more info sadly. Hope you're able to find something!

e.g.
![image](https://github.com/tsunamayo/Starship-EVO/assets/27857711/43da5997-464f-467e-9f37-3c38ea486343)

### Steps to reproduce the issue:
- Install the game for the first time (?)

### Environment
- Starship EVO version: 23w35b
- Graphics Card: RX6700XT

**Comment by tsunamayo** [comment]
@ProPeach Thanks a lot for letting me now. I have added a bunch of fail-safe code to prevent that.
