### ISSUE TITLE
[BUG] 23w35b- Planets without water still produce underwater effect

### ISSUE THREAD

**Issue by Crimson-Artist** [tsunamayo/Starship-EVO#5274]
Apparently every planet still has a water layer even if they are rocky moons. If the terrain of the planet goes below the invisible water layer then you will still get the underwater fog effect when you pass below said layer. 

In the video I demonstrate this happening on a small moon.
https://github.com/tsunamayo/Starship-EVO/assets/112352428/fd4089e5-00c2-4711-90ef-aee1b7c33632

**Comment by tsunamayo** [comment]
@Crimson-Artist Hi, this updated was fixed sometime ago! Cheers
