### ISSUE TITLE
[CRASH] Crash minutes after world load

### ISSUE THREAD

**Issue by Alkaliii** [tsunamayo/Starship-EVO#5288]
### Short Description of the issue:
The game crashes shortly after I load into a world. It's an old one but it was made after the Planet update and was working fine before the recent patch. It may relate to the other process I had running on my computer and a lack of ram but I attached the world file I'm having trobles with specifically

...

### Steps to reproduce the issue:
Load [World](https://drive.google.com/file/d/1G75qC2Urg_bblGZWx8NSQUI-3CVf9ALN/view?usp=sharing)
Wait

...

### Environment
- Starship EVO version: 23w38a
- Graphics Card: NVIDIA GeForce RTX 3060

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/12705514/output_log.txt)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12705515/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/12705516/Player-prev.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Alkaliii Hi, it seems related to memory, could you try to run the game alone to see if it is linked? Thanks

**Comment by Alkaliii** [comment]
It looks like it was indeed due to memory. After closing the other programs I had open I was able to load into the world fine. Sorry! Thanks!
