### ISSUE TITLE
Solar panels don't work

### ISSUE THREAD

**Issue by SovietSponge** [tsunamayo/Starship-EVO#5289]
### Short Description of the issue:
Solar panels appear to not generate any power whatsoever.

### Steps to reproduce the issue:
Place solar panel.

### Environment
- Starship EVO version: 23w38a
- Graphics Card: RTX 3060Ti

### Additional information:
[example ship.zip](https://github.com/tsunamayo/Starship-EVO/files/12706024/example.ship.zip)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12706026/Player.log)

**Comment by tsunamayo** [comment]
@SovietSponge Hi, issue is fixed for 23w39a. Thanks
