### ISSUE TITLE
Electrolyser missing model

### ISSUE THREAD

**Issue by Janssendel** [tsunamayo/Starship-EVO#5293]
### Short Description of the issue:

Electrolyser missing ingame model as well as toolbar icon

### Steps to reproduce the issue:

open inventory or drag it into the hotbar. when placing there will be no model, and it doesn't have any icons

### Environment
- Starship EVO version: 23w39a
- Graphics Card: Intel(R) Graphics HD P630 and NVIDIA Quadro M1200

### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12763170/Player.log)
![image](https://github.com/tsunamayo/Starship-EVO/assets/61640498/d14704ee-0a70-4423-b762-5f6ef0f81045)

**Comment by Kaiser-Indrasil** [comment]
Duplicate of #5292

**Comment by tsunamayo** [comment]
@Janssendel Hi, issue was fixed and the build repushed, ty
