### ISSUE TITLE
[BUG] Powering electrolysers can cause crashes or huge frame drop

### ISSUE THREAD

**Issue by zorozeenee** [tsunamayo/Starship-EVO#5300]
### Short Description of the issue:

When electrolysers get powered it generates stutters, lag, frame drops etc

### Steps to reproduce the issue:

Throw down a 20 to 30 electrolysers on a building or ship, then drop a power block

or

Throw down power on a ship or building
Then start placing electrolysers until your game freezes

### Environment
- Starship EVO version:  23w29a
- Graphics Card: gtx 1660 super

### Additional information:

Recreated the bug on video for you here
https://www.youtube.com/watch?v=i_x09alYyHo&ab_channel=SWINE

**Comment by tsunamayo** [comment]
@zorozeenee Hi, I would say it is not the electrolyser, it is the crazy amount of pipe and joint you are using. You can send me your blueprint, but honestly the game is made for a more reasonable amount of pipe (6 joints also will be a massive offender), you will always find the limit if you decide to copy-paste enough stuff.
