### ISSUE TITLE
[BUG] Power is broken

### ISSUE THREAD

**Issue by fellow-starmadian** [tsunamayo/Starship-EVO#5305]
### Short Description of the issue:
An issue cropped up after updating the game, where power appears to not work for new craft.  unsure if it applies to blueprinted ships, but for ships built from scratch, it's unreliable to get them to actually produce any power.
it's not just visual, cannot move with thrusters, or generate shields.
I did this multiple times, three to be sure it wasn't just me.  A ship I had sitting nearby worked fine.
EDIT: At proPeach's questioning on the discord, I discovered that this does not apply to newly spawned ships either.  Only ones built manually in this build of the game experience the power issue.
EDIT2: Upon further testing, the troubled ships have their issue fixed when they are reloaded,, either through spawning as a BP or reloading the game by exiting to desktop, so sending a BP to showcase the issue is impossible.
### Steps to reproduce the issue:
update to 23w41a
place builder block
yoke + ship core + reactor
get in ship and see you do not have any power.
### Environment
- Starship EVO version: 23w41a
- Graphics Card: RTX 2080TI

### Additional information:
it seems to be somehow intermittent, I managed to get it to give me some power for a short while using a fuel tank connected to the reactors.
I do not suspect the issue is related directly to my brief fix using a fuel tank.
I ensured that the reactors were fueled beforehand as well.  
_(Screenshots, Videos, Error logs, Related issues)_

This image is from after initially trying to fly
![2023-10-13 10_40_22-Starship EVO](https://github.com/tsunamayo/Starship-EVO/assets/13528733/5de3ba9f-c880-4d65-bf37-3e762e0a6b1e)

This one is what I managed to do briefly by connecting a pipe between a full tank and reactor.
![2023-10-13 11_24_20-Starship EVO](https://github.com/tsunamayo/Starship-EVO/assets/13528733/4d5fc027-f6e4-42ea-9f0f-b287d6c82ea0)

log file:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12895197/Player.log)

**Comment by ProPeach** [comment]
Got home from work and managed to test this myself, I actually can't reproduce it. A new ship created just like this behaves as expected with regards to power/flight etc, so I'm out of ideas for this one 🤔
![image](https://github.com/tsunamayo/Starship-EVO/assets/27857711/08f62f97-c045-4ae5-bb92-56fdff5d1e27)

**Comment by tsunamayo** [comment]
@fellow-starmadian Hi, same as propeach I cant reproduce my little ship (very similar to propeach) is working fine. Could you send a screenshot of your ship? Thanks

**Comment by tsunamayo** [comment]
@fellow-starmadian Actually I have fixed an issue that happen close to the space station. Could you retry now?

**Comment by ProPeach** [comment]
@tsunamayo I'm chatting to them on Discord, after the update they still produce the bug

**Comment by fellow-starmadian** [comment]
Do I put the video here or.. well I'll put it here for now at least.  Yes I am not near a space station, just in the area around the ring in the home system.  And double confirming: All the ships that don't work in the first video, I restarted the game, they work now, and new ships have the same issue again.  There's more rapid fire testing in the second half of the first video, the first half is a lot of setup, checking discord, and repeating the process to make sure it's repeatable at all.

One other important thing to note, the ship I had just added as a blueprint and spawned, didnt work as a spawned build until I removed an instance of the bped ship? it could just be I had to spawn it twice for it to work, I didn't check.  And unfortunately other people are reporting they do not have the same issue.  

On some more testing, I've found some other weird issues, something to do about the starter block.. somehow.  in the second video, you see the boot up to the gameplay, in the third video, I booted up and built the quarter block vessel without recording, then when I built the 1m I noticed it was working while the quarter block to it's left wasn't, so I then rushed to record.
https://cdn.discordapp.com/attachments/342383722185883648/1162520416535969872/2023-10-13_18-25-16.mp4?ex=653c3c81&is=6529c781&hm=8fc74f211c94d1da17c5c82907cf588d74c00663e8653c2f8cd246e206ecd741&

https://cdn.discordapp.com/attachments/342383722185883648/1162524982027497492/2023-10-13_18-53-32_2.mp4?ex=653c40c2&is=6529cbc2&hm=370b0dac568e2c94ea57e864545c29c2787d3c2c4cfae01c4dc29eb463750aa9&

https://cdn.discordapp.com/attachments/342383722185883648/1162526723288612926/2023-10-13_19-02-50.mp4?ex=653c4261&is=6529cd61&hm=b26d9aa14514ff5c73db5cc4510760592f395d3f62d568bf01fd73a9dd544b10&

**Comment by fellow-starmadian** [comment]
new update: it's world specific..  "fellow" is the world it happens in, and "new character" does not.  bonus issue, if there's no power on the vessel the life support bounding box can't tell that there's a wall removed, evident by the box build.  I was thinking there might have been a bug initialization via messing with the life support block, but at least for now no doesn't seem so.
[New Character.zip](https://github.com/tsunamayo/Starship-EVO/files/12900532/New.Character.zip)
(also I never expected someone to obtain this world file so if I have some random ass note somewhere with a swear or something in it no getting mad at me lol)

**Comment by tsunamayo** [comment]
@fellow-starmadian Sorry for the late update, I tried to reproduce but it is working fine on my side...

**Comment by tsunamayo** [comment]
Okay lol as I wrote this I manage to reproduce once, but this time by spawning a blueprint. I keep you posted.

**Comment by tsunamayo** [comment]
@fellow-starmadian Hi, so I managed to track down the issue, it is a corruption within the reactor storage container. Now I could fix ship already corrupted but I would also prefer to understand while that corruption happened in the first pace.
@fellow-starmadian Could you tell me if you still reproduce on a new ship in your "corrupted" save world, and if you could you send me the player.log file? I was not able to reproduce on a new ship unfortunately. 
Thanks
