### ISSUE TITLE
cant open game beyond menu

### ISSUE THREAD

**Issue by skelecthulu** [tsunamayo/Starship-EVO#5308]
### Short Description of the issue:

i can open a game to the menu but i cant make a new world and cant join my friend

### Steps to reproduce the issue:

i just down the game and it didnt work

### Environment
- Starship EVO version: 
- Graphics Card: Nvidia GeForce RTX 3060

### Additional information:

it just plays the sound and presses the button but doesnt work

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.
[starship evo player log.zip](https://github.com/tsunamayo/Starship-EVO/files/12922551/starship.evo.player.log.zip)

**Comment by tsunamayo** [comment]
@skelecthulu Hi, are you sure you are creating a character correctly?
Press Play
Press Create a new Character 
Give it a name (optional)
Press play with this character

If yes then which button is not working ?
Thanks!
