### ISSUE TITLE
[Suggestion] New sensor block: O2 detector

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#5311]
A new block that detects if there is O2, either from the life support block or atmosphere. Very simple, super useful if you want to program in emergency bulkheads and forcefields.

**Comment by ProPeach** [comment]
There are some cool event gate settings for the Life Support brick which might fit the bill for these cases. Great to see event gate support for the new bricks from the start

**Comment by tsunamayo** [comment]
@ZachZent Yes I think propeach is right, if you want to detect a depressurization plug an event gate on the life support. Thanks
