### ISSUE TITLE
[Suggestion] Life Support Thread

### ISSUE THREAD

**Issue by Crimson-Artist** [tsunamayo/Starship-EVO#5313]
Now that Air is going to be a thing in this game I have several suggestions regarding the life support block.

1. **Use Vents and Fans as proxies for Life support blocks.** Right now air comes directly from the Life support unit. This is fine when you have a small room but when it comes to big rooms the actual life support block does not look right. Having the ability to link vents and fans to a life support block will allow us to design rooms without the life support block ruining the aesthetic.
2. **Have non-airtight blocks.**  All blocks right now are airtight meaning that they can block off air even when it looks like they shouldn't. The grates are a good example of this along with the hollow wedge, girders and fences. Being able to build methods for air to seep into rooms without a life support unit being present will help immensely.
3. **Option to toggle off air flowing animation.** Every time I open a door every Life support Unit present goes off filling each room with air again. This flowing air animation gets distracting so I want the ability to turn it off or at least make it more subtle. This option should also effect links vent/fan blocks too.

**Comment by CoasterBlock** [comment]
The idea with bricks that let air pass through is great. That way we could make proper air-ducts. I also wrote a posts about some changes/additions in #5304

**Comment by tsunamayo** [comment]
@Crimson-Artist Hi, so yes 2) is a miss, some block should obviously let air pass through. For the rest I am not a fan (no pun intended)
1) 3) seems a bit too complex. If you think it runs the aesthetic then use an helmet or hide those. I will add a few block that could be used as cover while being non-airtight (like an air duct cover). This is intended for survival.

Thanks

**Comment by Crimson-Artist** [comment]
> @Crimson-Artist Hi, so yes 2) is a miss, some block should obviously let air pass through. For the rest I am not a fan (no pun intended)
> 
> 1. 3. seems a bit too complex. If you think it runs the aesthetic then use an helmet or hide those. I will add a few block that could be used as cover while being non-airtight (like an air duct cover). This is intended for survival.
> 
> Thanks

Will covering the front of the life support unit with these non-airtight blocks cancel the air flowing animation?

**Comment by tsunamayo** [comment]
@Crimson-Artist Nope...

**Comment by tsunamayo** [comment]
@Crimson-Artist If it bugs out a lot of people I could work on a solution though, lets see what other thinks.

**Comment by tsunamayo** [comment]
What I plan to do is:
 there will only be pressurization animation if you go from empty to pressurized, (ie pressurized => pressurized shows nothing).
What I could also do is to add a config screen with an anim off toggle, or try to detect if there a cover in front.
Cheers
