### ISSUE TITLE
[Bug] Electrolyzers stop working if any single "fuel" in storage hits 1k

### ISSUE THREAD

**Issue by Gallt** [tsunamayo/Starship-EVO#5319]
### Short Description of the issue:

If i have an electrolyzer feeding a hydrogen or oxygen storage tanks, if either one fills up to full, the electrolyzer will fill to 1k of that specific fuel and hen stop working regardless of what the other fuels storage fill % is at. Oxygen production is always much lmuch ower than hydrogen production so it locks up quick

### Steps to reproduce the issue:

Setup a fuel collector under water, hook it to an electrolyzer. Hook the electorlyzer up to 2 tanks, one set to hydrogen, 1 to oxygen. once hydrogen tank is full, the electrolyzer will start to fill with Hydrogen. Once the electrolyzers Hydrogen storage is up to 1000 (and the Oxygen is probably at or under 50%) the production will stop.

### Environment
- Starship EVO version: Experimental 23w41a
- Graphics Card: NVIDIA GeForce GTX 1660 Ti

### Additional information:

https://youtu.be/tnLVbR2YoNk?si=0x7GjYycl0yOnNlX

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/13211209/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Gallt Hi, thanks for the case. I dont think it is an issue, it is by design. If the Electrolyzer cant send the hydrogen anywhere then it will stops as it cant dump fuel on its own.

**Comment by Gallt** [comment]
cool. It just can hold up oxygen production is all with how slow it produces compared to Hydrogen. Worst case we just make a release valve system for hydrogen to keep oxygen producing.
