### ISSUE TITLE
[Bug] Crafting Issues

### ISSUE THREAD

**Issue by Briaireous** [tsunamayo/Starship-EVO#5320]
### Short Description of the issue:

Crafting is a bit buggy/unresponsive and can result in crashes when used. Automated transfer of inventory of furnaces and assemblies can push the item to storage through the input piping and not the output piping. sometimes the game will crash in the process of setting up different crafting setups, sometimes it will crash when selecting different items to craft, and other times it will just simply crash for no apparent reason after the setup is running. 
...

### Steps to reproduce the issue:

1. Set up a simple collector
2. pipe it into a storage container
3. Connect a assembly and a furnace to the storage container (reason being that the only way i was able to get automated crafting to 
    work was using this sort of setup)
4. have both the settings to not expel the crafted items but allow it to auto pull, auto queue sub components, and auto push to connected storage
...
This occurred in the experimental branch.

**Comment by tsunamayo** [comment]
@Briaireous Hi, I didnt have any crash with a similar setup, could you send me your save?
Also do you have a 100% reproductible case or is it a bit random?
Also there is no such things as input or output piping. Any connected inventory can be input or output.

Thanks

**Comment by Briaireous** [comment]
Sofar its random, ill send world files once it get home

**Comment by ProPeach** [comment]
I've been having some seemingly random crashes in the latest patch (#5306) too, usually within the first 20 minutes of a session. Could it be that these crashes only happened to be while you were playing with the crafting setup?

**Comment by Briaireous** [comment]
[World file.zip](https://github.com/tsunamayo/Starship-EVO/files/13234654/World.file.zip)
[World file 2.zip](https://github.com/tsunamayo/Starship-EVO/files/13234659/World.file.2.zip)
[World file 3.zip](https://github.com/tsunamayo/Starship-EVO/files/13234665/World.file.3.zip)

sadly i am unable to send the player entity file die to the size of it
same for the output log

**Comment by tsunamayo** [comment]
@Briaireous Hi, the save file is not complete. Also if you could send the player.log after the crash so I can investigate. Thanks!

**Comment by Briaireous** [comment]
I am unable to send it on github due to the size of the file even when compressed

**Comment by tsunamayo** [comment]
@Briaireous @ProPeach  Hi, I finally managed to reproduce and track it down (which was a pain), but no crash so far in my play survival session. Will be for 23w51a. Thanks

**Comment by Briaireous** [comment]
> @Briaireous @ProPeach  Hi, I finally managed to reproduce and track it down (which was a pain), but no crash so far in my play survival session. Will be for 23w51a. Thanks

Thanks tsuna, u're the best.
