### ISSUE TITLE
[Bug] Dropped Handheld Weapons Fall Through Planet Surface

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#5325]
### Short Description of the issue:
As in the title, any dropped weapon will fall and phase right through the planet voxels

### Steps to reproduce the issue:
- Spawn a handheld weapon
- Open the Codex and drag it out of your inventory so it falls
- The weapon will fall through the surface. Follow it in F5 mode and it just keeps on going 

### Environment
- Starship EVO version: 23w41a
- Graphics Card: RX 6700XT

**Comment by tsunamayo** [comment]
@ProPeach Hi, this will be fixed for 23w45a. Thanks!
