### ISSUE TITLE
[Bug] Pipe Joins not Despawning (Regression)

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#5328]
### Short Description of the issue:
A regression of #5242, Pipe Joins do not consistently despawn with their parent ship.

I made this bp to see if there was a pattern in which particular Join bricks, but if you spawn/unspawn it a couple times you will see different Joins persisting every time.

The Join bricks persist until you reload the game.

https://github.com/tsunamayo/Starship-EVO/assets/27857711/6c3974c2-5c6e-44b5-9603-7adc8280d518

### Steps to reproduce the issue:
- Load attached bp (It happens on every bp I have, including the one from the previous report)
- Unspawn it
- Note the Pipe Joins remaining

### Environment
- Starship EVO version: 23w41a
- Graphics Card: RX 6700XT

### Additional information:
[Pipe Connector Bug Showcase.zip](https://github.com/tsunamayo/Starship-EVO/files/13260773/Pipe.Connector.Bug.Showcase.zip)

**Comment by tsunamayo** [comment]
@ProPeach Thanks, for some reason it is a pain to make it work...

**Comment by tsunamayo** [comment]
@ProPeach Hi, do you still get on 44b? I cant reproduce the bug...

**Comment by ProPeach** [comment]
@tsunamayo I thought for a moment it was fixed haha, that test bp I sent you no longer produces the bug. However, I tried the bp from the previous report and that still leaves behind this little fella in 44b
![image](https://github.com/tsunamayo/Starship-EVO/assets/27857711/ca48e57f-4042-4f52-8d10-d493a9103d68)

This bp - https://steamcommunity.com/sharedfiles/filedetails/?id=3024293235

**Comment by Janssendel** [comment]
seems like we'd have to update our BPs by deleting the old pipes and resaving them

**Comment by ProPeach** [comment]
> seems like we'd have to update our BPs by deleting the old pipes and resaving them

I'm not sure this is the case, the blueprint attached first produced the bug, then after 44b it doesn't even without rebuilding the pipes on it. Unless 44b fixed pipes built only in 41a? Doesn't seem likely but maybe 🤷‍♂️

**Comment by tsunamayo** [comment]
@ProPeach Hi, so I have finally tracked down the issue.
It was a pipe placed against a mix of a lightcruise and a tank, so now I updated the code to make this invalid as would likely cause all sort of other issues. 
Cheers
