### ISSUE TITLE
after update 23w44a

### ISSUE THREAD

**Issue by Tackietacktack** [tsunamayo/Starship-EVO#5332]
### Short Description of the issue:

after update, i canot place bricks

https://youtu.be/XZSkUOetCjc

### Environment
- Starship EVO version: 23w44a
- Graphics Card: geforce rtx

**Comment by Gallt** [comment]
same. I have to reboot the game to properly interact with anything i spawn/place. Had to revert the build to non experimental to continue builds.

**Comment by Tackietacktack** [comment]
Yes, that works. Any people have wrote that they can't interact with systems. I can load old blueprints control this, maybe it helps.

**Comment by tsunamayo** [comment]
@Tackietacktack Hi, so I have repushed the build with the fix as it is a regression. Thanks

**Comment by ProPeach** [comment]
Huge thanks for the quick fix!
