### ISSUE TITLE
Slide rails not working

### ISSUE THREAD

**Issue by Angelus139** [tsunamayo/Starship-EVO#5334]
### Short Description of the issue:

I can't place blocks on the slide mechanism of the slide rail. Placement preview shows red like its invalid.

### Steps to reproduce the issue:

unknown

### Environment
- Starship EVO version: Experimental
- Graphics Card: Nvidia GeForce RTX3060

### Additional information:

![image_2023-11-07_094605783](https://github.com/tsunamayo/Starship-EVO/assets/95190711/d136d2fc-5749-4a07-83ae-a496a0dc127b)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/13283724/Player.log)

**Comment by zorozeenee** [comment]
its the same for all child entity blocks

**Comment by tsunamayo** [comment]
@Angelus139 @zorozeenee Hi, this was fixed for 23w44b. Thanks!
