### ISSUE TITLE
Copy & Paste for Rails still broken

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Starship-EVO#5336]
Steps to reproduce the issue:
If you try to copy paste a Rail with its subentity, the preview shows everything on the rail, but if you place it, the rail appears without subentity.

Environment
Starship EVO version: 23w44b
Graphics Card: 4080

**Comment by tsunamayo** [comment]
@Battlepixel Hi, thanks for reporting that, issue is now fixed. Thanks
