### ISSUE TITLE
copy / paste all mechanisme still broken

### ISSUE THREAD

**Issue by Tackietacktack** [tsunamayo/Starship-EVO#5337]
### Short Description of the issue:

all mechanism with children are not to copy /paste in 25cm in all size ( 25cm and 1m tested)

https://youtu.be/7ZdXa7p-CUA

### Environment
- Starship EVO version: 23w44b
- Graphics Card: Geforce RTX 2060

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/13300136/Player.log)

https://youtu.be/7ZdXa7p-CUA

**Comment by tsunamayo** [comment]
@Tackietacktack I fixed the issue, the patch is now live. Thanks
