### ISSUE TITLE
Cannot get past tutorial step of turning jetpack off

### ISSUE THREAD

**Issue by MatCat** [tsunamayo/Starship-EVO#5338]
### Short Description of the issue:

In the tutorial when it gets to the step of turning the jetpack off with J nothing happens, I see it toggle between -G and 3 way spoke symbol at the bottom but the tutorial step does not fullfill.
...

### Steps to reproduce the issue:

Start a new character, follow the tutorial until the step where you go at a 45 degree angle through the slot to the next checkpoint.
...

### Environment
- Starship EVO version:  23w44b
- Graphics Card:  Radeon 5600M

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `[%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

Player.log: (https://www.dropbox.com/scl/fi/lcqv3hg444p4oy2wg25yc/Player.log?rlkey=7f2qz7gch0nh4j4sbvwx30mrp&raw=1)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by MatCat** [comment]
I was able to continue the tutorial by building a ship core with a reactor and a gravity block and hitting J while within it's gravitational area, however there is no gravity on the starting station it seems (though when holding the gravity block you can see the outlines of the field area).

**Comment by tsunamayo** [comment]
@MatCat Hi, thanks for the heads up I am looking into it. Did you tried on the Default branch first?

**Comment by MatCat** [comment]
Sorry I did not, I hadn't touched the game in about a year and wanted to see what was new since then, was still in the experimental branch.

**Comment by tsunamayo** [comment]
@MatCat Gotcha, I tried in Default it is fine, so if that is blocking for you you can always hop over there! I will fix this asap.

**Comment by tsunamayo** [comment]
Hi, issue is fixed for 23w45a. It is now because the gravity system will check an entity power level, and there is no reactors on those stations modules...  Thanks
