### ISSUE TITLE
Monitor is now displaying shield information incorrectly

### ISSUE THREAD

**Issue by MatCat** [tsunamayo/Starship-EVO#5347]
### Short Description of the issue:

When linking a monitor to a shield generator it is improperly scaled on the display.

### Steps to reproduce the issue:

Link a monitor to a shield generator.

### Environment
- Starship EVO version:  23w45a
- Graphics Card:  Radeon 5600M

### Additional information:

Screenshot:

[Screenshot](https://www.dropbox.com/scl/fi/91jdy6eva0t5dst18m1he/20231114014549_1.jpg?rlkey=yinzu981oydc6d4oa1yzycvgx&raw=1)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@MatCat Hi, yes it is a known issue, these tech needs a complete refactor. I think I am gonna have to remove it for the time being. Thanks
