### ISSUE TITLE
Monitor will not link to reactor

### ISSUE THREAD

**Issue by MatCat** [tsunamayo/Starship-EVO#5348]
### Short Description of the issue:

I tried to link a monitor to a reactor but it would not connect.

### Steps to reproduce the issue:

Try to link a monitor to a reactor.

### Environment
- Starship EVO version:  23w45a
- Graphics Card:  5600M

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@MatCat Hi, yes it is normal for now.
