### ISSUE TITLE
Monitor linked to an oxygen tank shows H2

### ISSUE THREAD

**Issue by MatCat** [tsunamayo/Starship-EVO#5349]
### Short Description of the issue:

I tried to link a monitor to an oxygen tank however it shows H2 (may not be a feature yet?)

### Steps to reproduce the issue:

Link monitor to a tank set to oxygen

### Environment
- Starship EVO version: 23w45a
- Graphics Card:  5600M

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@MatCat Nope it should work. I will check this out!

**Comment by tsunamayo** [comment]
@MatCat Hi, I cant reproduce, it is working fine on my side. Could you send me your world save? Thanks

**Comment by MatCat** [comment]
I checked in game  to double check, said H2 on the screen, I looked at the tank with a link tool, turned around, and it said O2!   Since it changed to O2 I now cannot reproduce and my save world is saved with it showing right now, so its some sort of edge case.

**Comment by MatCat** [comment]
Actually, I think I have the blueprint saved with it saying H2!!  I will check after I am done eating and if so I will attach that.

**Comment by MatCat** [comment]
Here is a link to that designs blueprint, when you load it you will see the screen inside says H2, but when you inspect the oxygen tank its linked to it will turn into O2 on the display, don't know how it showed H2 to begin with as I had changed the tank to oxygen before I linked it, but maybe a clue will be in the blueprint.


[Steam Workshop Blueprint](https://steamcommunity.com/sharedfiles/filedetails/?id=3087250756)

**Comment by tsunamayo** [comment]
@MatCat Hi, I will have fixed the issue for 23w50c. The reason is that the auto refuel function was ignoring the ship setting and filling the tank with h2. Thanks
