### ISSUE TITLE
Arc Rounded Corners do not align properly in symmetry 

### ISSUE THREAD

**Issue by MatCat** [tsunamayo/Starship-EVO#5350]
### Short Description of the issue:

I discovered that the arc rounded corner pieces have a bug when places in symmetry. 

### Steps to reproduce the issue:

Place the piece in symmetry mode.

### Environment
- Starship EVO version:  23w45a
- Graphics Card:  5600M

### Additional information:

[Screenshot](https://www.dropbox.com/scl/fi/j6ky1ku5sb4k05xhkerzy/20231114020547_1.jpg?rlkey=aok0t7zpi88pm3glmsa3ootx2&raw=1)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@MatCat Hi, issue is fixed for 23w51a. Thanks!
