### ISSUE TITLE
Suggestion: A decal that works just like a screen

### ISSUE THREAD

**Issue by MatCat** [tsunamayo/Starship-EVO#5355]
I would like to suggest making a decal that works just like the text screen does, this would make adding text and sprites on surfaces very easy, instead of being centered in the monitor block could be flat on the surface like other decals.

**Comment by tsunamayo** [comment]
@MatCat Hi, the screen tech needs a complete overhaul as what you propose would eat up too much performance. Letter decals was already in the scope of that tech - it is just lower priority. Thanks
