### ISSUE TITLE
[BUG] Many indent decals no longer have transparent backgrounds 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#5356]
![Starship EVO 11_18_2023 2_57_30 PM](https://github.com/tsunamayo/Starship-EVO/assets/56371294/817f81cd-c264-43d3-8d41-044cbec74fdd)
as you can see in this image here these decal's color is larger than the indent itself causing issues 

version: 23w45a

**Comment by tsunamayo** [comment]
@TIKIRobo Hi, this will be fixed for 23w50c. Thanks!
