### ISSUE TITLE
[BUG] Can't Paint Vent Block

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#5357]
https://github.com/tsunamayo/Starship-EVO/assets/56371294/3bf61f9f-2834-4d86-bcc2-2ab9b743d843

23w45a
as you can see I paint the vent but it does not change color.

**Comment by BigBadKangaroo** [comment]
Still happens in 23w50a

**Comment by tsunamayo** [comment]
@BigBadKangaroo @TIKIRobo Hi, issue is fixed for 23w50c. Cheers
