### ISSUE TITLE
[BUG] Plant hitbox change

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#5358]
![Starship EVO 11_20_2023 7_03_01 PM](https://github.com/tsunamayo/Starship-EVO/assets/56371294/f22bb94a-5603-47bb-90fa-35b709a58d91)
as you can see it is impossible to place these flowers close together, however in prior versions of the game flowers would clip into almost every block, while this may seem a major oversite to some players most actual builders found it fun as it allowed them to create a splash of nature in an otherwise bland location (intentionally or otherwise)
![Starship EVO 11_20_2023 7_04_21 PM](https://github.com/tsunamayo/Starship-EVO/assets/56371294/8fe9f1a4-4b11-4a4a-96dc-894aae3250a2)
it would be nice to see the hitboxes reverted, also for whatever reason seat backs (but not bottoms) now clip
![Starship EVO 11_20_2023 7_07_13 PM](https://github.com/tsunamayo/Starship-EVO/assets/56371294/04362e97-b6c0-49d7-9b5a-8eee2e9dfbea)

**Comment by tsunamayo** [comment]
@TIKIRobo Hi, issue is fixed for 23w50c. Thanks!
