### ISSUE TITLE
missing blocks make unplaceable spaces

### ISSUE THREAD

**Issue by desolence** [tsunamayo/Starship-EVO#5360]
### Short Description of the issue:

...       _______(there are missing blocks on my ship that just disappeared one day and where they were no other blocks can be placed its )

### Steps to reproduce the issue: _______(its on my ship and on every blueprint i load of that ship no matter if i change the name or not)

...

### Environment ______all
- Starship EVO version: _____23w41a
- Graphics Card: ______nividia geforce rtx 2060

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
_______ ![Screenshot 2023-11-25 103506](https://github.com/tsunamayo/Starship-EVO/assets/152018327/26430e66-34c4-4317-be87-ecd18a8e7762)
r
________ [Player.log](https://github.com/tsunamayo/Starship-EVO/files/13464528/Player.log)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

________ [Player.log](https://github.com/tsunamayo/Starship-EVO/files/13464528/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

______ [UNSC INFINITY Type B.zip](https://github.com/tsunamayo/Starship-EVO/files/13464547/UNSC.INFINITY.Type.B.zip)

**Comment by TIKIRobo** [comment]
try going into the codex (tab menu) and under the spaceship section hit the "repair entity" button

**Comment by ProPeach** [comment]
Yeah try Tiki's fix, you can see from the damage decals that area has been shot up by something. When blocks are damaged and disappear, they aren't *actually* removed from the build so that you can use the repair beam or that button to fix the ship without needing to replace every single block by hand.

**Comment by tsunamayo** [comment]
@desolence Hi, you can also equip the repair tool, you will see those blocks as a green hologram. You can fire the tool to actually repair this. Thanks

**Comment by desolence** [comment]
THANK YOU SO MUCH  the repair tool worked perfectly
