### ISSUE TITLE
blueprint refusing to save

### ISSUE THREAD

**Issue by Azathoh-the-blind-idiot-god** [tsunamayo/Starship-EVO#5366]
### Short Description of the issue:
When entering a world I get a message stating that this blueprint, Main engine layout (thrustlights), refuses to save.
Attempting to manually save the blueprint results in the same error message.
### Steps to reproduce the issue:

Attempt to save the blueprint.

### Environment
- Starship EVO version: 23w48a
- Graphics Card: RX5700

### Additional information:
[Main engine layout (thrustlights).zip](https://github.com/tsunamayo/Starship-EVO/files/13527185/Main.engine.layout.thrustlights.zip)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/13527186/Player.log)

**Comment by tsunamayo** [comment]
@Azathoh-the-blind-idiot-god This will be fixed for next update. Thanks
