### ISSUE TITLE
[Suggestion] new block materials limit block choice, more shapes? 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#5368]
Currently with the new blocks such as the scrappy hull there are only options for the basic shapes, it would be nice to have more options for block choice such as 1/2 1/4 slabs and triangles 
![image](https://github.com/tsunamayo/Starship-EVO/assets/56371294/e3115cf5-2687-4829-b2b2-b4b79a540817)
i quickly replaced all the red panels on this old ship of mine but as you can see in the red circled areas that some blocks such as the slabs and 1:2 offset blocks stand out due to their lack of texture 

one suggestion (that would also allow for replacement of blocks easily, such as upgrading a ship in survival) would be to be able to "paint" blocks this new material keeping their shape and color but changing their texture and stats. im not sure how possible that is though and I'd like to hear back from you Tsuna

**Comment by tsunamayo** [comment]
@TIKIRobo Hi, thanks for the suggestion, unfortunately it dont really fit with the technology, those are not just "paint" but different block, so it is not really possible. Honestly you should not worry about that your ship look amazing this way anyway!
Cheers
