### ISSUE TITLE
[Suggestion] Crafting Bench stretchable?

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#5370]
Hi there,

would it be possible that we can strecht the Crafting Bench, so there will be a "longer table" section instead of two "end caps"?

I'd love to build tables that have a function, but the CB has a wierd shape that is hard to rebuild. So when I want to build a longer table I'd have to use either two "end caps" or build a complete custom one without a function.
![20231203182456_1](https://github.com/tsunamayo/Starship-EVO/assets/81495956/80cd43e9-397f-496d-99b9-2dd05eac1d88)

So it would end up looking somewhat like this: (but in good) 
![20231203183241_1](https://github.com/tsunamayo/Starship-EVO/assets/81495956/097be1f5-9d0c-4541-b6f3-f81935e8e5ba)

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, I was thinking of giving a flat with bevel (straight and corner) instead for that. With maybe a rounded look instead.
