### ISSUE TITLE
[Bug] Silicon depostis seeming to not spawn

### ISSUE THREAD

**Issue by Gallt** [tsunamayo/Starship-EVO#5372]
Not much specific detail i can do, but on a new game after 23w48a i was doing a "mock survival" to see if i could help find bugs and whatnot (will post the other bugs I've found later). I ended up looking over 2 planets and over 150 deposits and never found any silicon deposits. It really seems they have stopped spawning once coal was added.

**Comment by Crimson-Artist** [comment]
can confirm. silicon seems to have disappeared since the planet update. before the regular rocks could be smelted into silicon but now that we officially have stone blocks im guessing silicon will get its own ore vein.

**Comment by tsunamayo** [comment]
@Gallt Hi, thanks a lot for doing this, as a matter of fact I will do a closed beta test of the survival soon (I already have it on my side). 
There was never any silicon ore, you craft silicon from 8 rocks. I will make that clear in a guide!
Thanks
