### ISSUE TITLE
[Bug] Heavy camera stutter while moving on planets.

### ISSUE THREAD

**Issue by Leha44581** [tsunamayo/Starship-EVO#5374]
### Short Description of the issue:

Camera gets a seizure if i move on planets, both on foot and in a hovercraft, doesn't get fixed by a restart.

### Steps to reproduce the issue:
Get down on a planet
Move.

### Environment
- Starship EVO version: 23w49a
- Graphics Card: GTX 1070

### Additional information:

Doesn't seem to happen on the ringworld
Tested on the 0.2g and 1.2g planets, hovercraft blueprint attached

https://youtu.be/q6pMaf9Wiog
[Player.log.txt](https://github.com/tsunamayo/Starship-EVO/files/13560121/Player.log.txt)
[LH-Tetra.zip](https://github.com/tsunamayo/Starship-EVO/files/13560141/LH-Tetra.zip)

**Comment by ProPeach** [comment]
I get the same thing, although I also produce the bug in space too

In the -g jetpack mode, I get the stutters only when I look ~5 degrees up/down from my players orientation and move forward/back

Side to side is unaffected, and if I look straight "ahead" according to my players orientation in space and move forward/back, then the stuttering doesn't occur either.

**Comment by Gallt** [comment]
Third'd. Cant figure out how to reproduce, but i do notice it mainly on planets.

**Comment by tsunamayo** [comment]
@Leha44581 Hi, I managed to reproduce by dropping my FPS. Will be fixed for 23w49b. Thanks
