### ISSUE TITLE
[BUG] improper mirror on some stone blocks

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#5375]
Some stone blocks do not mirror properly such the tris, heptas and the other one thats name i can't remember.
23w49a

https://github.com/tsunamayo/Starship-EVO/assets/56371294/302e2011-2234-41d3-8efb-0802af81d389

**Comment by tsunamayo** [comment]
@TIKIRobo Hi, issue is fixed for 23w50a. Thanks!
