### ISSUE TITLE
[suggestiopn] more event gate options and [bug] event gate not triggered by player cant activate a message block

### ISSUE THREAD

**Issue by KINGrimson** [tsunamayo/Starship-EVO#5376]
### Short Description of the issue:
suggestions first - i was building a warp system and wanted to have a system that would tell you if your warp was on or of before you go to warp, but without a "warp is requested" option i cant do that

bug second - if you want a message to display on the hud with the use of a event gate or any other system, it can only be triggered by a player,  with that i mean, the player is the only thing that can trigger the message gate from displaying the message, lets say if the signal to display the message came from a event gate listening to a treshhold value of a hinge it wont trigger the message gate, which really kinde sucks cause it would open up so much more things for us builders that want to utilize more of the blocks funtionalty but is heavily limited due to the way its been setup
...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 23w49a
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by CoasterBlock** [comment]
The issue about players and the message bricks is something I encountered too. Its been around for a while. It only seems to affect volumetric sensors and laser sensors. Event-gates with things like chairs or yokes work.

**Comment by tsunamayo** [comment]
@CoasterBlock Hi, well it is not a bug it is by design, otherwise how that would work in multiplayer? Do you I have to display something on the screen of every player once a system activate? This is why it is only limited to chairs or yoke when there is a player concerned by the event. 
I will add more event indeed it is a valid request. 
Thanks
