### ISSUE TITLE
[suggestion] make life support be piped up

### ISSUE THREAD

**Issue by KINGrimson** [tsunamayo/Starship-EVO#5377]
### Short Description of the issue:
really simple thing. make the life support block able to havea pipe be run to it from a tankl filled with air, then y ou dont need to mretock the lifespurot every 5 minuts as it runs out quick with eachtime it has o restock the air in the room. 
...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 23w49a
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by ProPeach** [comment]
I'd prefer that oxygen be supplied to the Life Support block automagically without the need for pipes to be honest, that's a lot of piping to do on medium-large ships with a Life Support block in every room

**Comment by tsunamayo** [comment]
@KINGrimson Hi, yes I agree with ProPeach I dont want the player to have to piper smaller system. I will provide some magic refill from a tank. Thanks
