### ISSUE TITLE
[BUG] Flood lights and glow tiles do not illuminate the area.

### ISSUE THREAD

**Issue by Leha44581** [tsunamayo/Starship-EVO#5378]
Flood lights and glow tiles don't illuminate the area in front of, and around them.
Flat lights, light wedges and light tubes can't be scaled down to 1/8m
![20231208025356_1](https://github.com/tsunamayo/Starship-EVO/assets/70238465/d3d81fcd-a5e2-467a-85cf-99268697772f)
![20231208025414_1](https://github.com/tsunamayo/Starship-EVO/assets/70238465/9a097996-5a81-4991-962d-5dad7c55609f)
![20231208025438_1](https://github.com/tsunamayo/Starship-EVO/assets/70238465/023cf3e0-7d8a-428a-9560-5919e3988f6a)

**Comment by ProPeach** [comment]
This is intentional, perhaps the description in the Codex could be improved, especially for the flood **light**

**Comment by tsunamayo** [comment]
@Leha44581 Yes it is intentional those are decorative "light". Not sure how I should call them @ProPeach haha.
Also no I dont want to make mini scale of every blocks out there.

**Comment by ProPeach** [comment]
@tsunamayo I was just thinking the description in the Codex could clarify that the brick does not produce actual light, hopefully that could help reduce the chance that players think that something is wrong
