### ISSUE TITLE
[bug] the fan block doesnt remember their settings on a world reload

### ISSUE THREAD

**Issue by KINGrimson** [tsunamayo/Starship-EVO#5382]
### Short Description of the issue:
simple really, the fan block if you change the setting and go out and in the game the setting will go back to 500 instead of what it was set too
...

### Steps to reproduce the issue:
1: place fan block
2: change setting
3: leave world
4: enter world
5: see the setting is back to 500
...

### Environment
- Starship EVO version: 23w49a
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@KINGrimson Hi, this is fixed for 23w40a. Thanks
