### ISSUE TITLE
ship refusing to save (again)

### ISSUE THREAD

**Issue by Azathoh-the-blind-idiot-god** [tsunamayo/Starship-EVO#5384]
### Short Description of the issue:
blueprint refusing to save, same as last time. (https://github.com/tsunamayo/Starship-EVO/issues/5366)
included files are the bugged blueprint, the player.log file, and the world that I am working it

### Steps to reproduce the issue:

1; having this blueprint in your world,
2; building on it

### Environment
- Starship EVO version: 23w49a
- Graphics Card: RX5700

### Additional information:

[Frigate Combined Hull V16 (rear VTOL) 1.zip](https://github.com/tsunamayo/Starship-EVO/files/13629355/Frigate.Combined.Hull.V16.rear.VTOL.1.zip)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/13629357/Player.log)

[Azathoth frigate 2.zip](https://github.com/tsunamayo/Starship-EVO/files/13629360/Azathoth.frigate.2.zip)

**Comment by tsunamayo** [comment]
@Azathoh-the-blind-idiot-god Hi, so I can reproduce, I keep you posted thanks for booking the case.

**Comment by tsunamayo** [comment]
@Azathoh-the-blind-idiot-god Hi, issue will be fixed for 23w50c. Thanks! (and that ship is amazing, it is quite an achievement!)
