### ISSUE TITLE
[Bug]23w50a- Crash on login

### ISSUE THREAD

**Issue by Crimson-Artist** [tsunamayo/Starship-EVO#5386]
After updating the game I can't log into a specific world. This is my normal testing/building world so It might have something to do with the amount of entities that surround the character when I last logged out. I can confirm that I can log into a world that I use for photo ops which is barren in comparison.

Heres the player log.
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/13649953/Player.log)

**Comment by Tackietacktack** [comment]
I have the same.
The last save doesn't work and an older save works. I don't think I finished the game at any critical moment.

**Comment by tsunamayo** [comment]
@Crimson-Artist @Tackietacktack Hi, as it is world specific could you please send me your world so I can reproduce? Thanks

**Comment by tsunamayo** [comment]
@Crimson-Artist @Tackietacktack Okay no worries I managed to reproduce the crash on my own and understood the root of the issue.

**Comment by tsunamayo** [comment]
@Crimson-Artist Hi, issues is fixed for 23w50b. Thanks!
