### ISSUE TITLE
[23w50a] Crash when fast moving over planet surface

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#5387]
Hi there,

after 23w50a my game has crashed multiple times after moving via fast move keys close to the planet surface.

Here the crash logs:
(there are multiple ones, that's why it's zipped) 
[Crashes.zip](https://github.com/tsunamayo/Starship-EVO/files/13652834/Crashes.zip)

**Comment by BigBadKangaroo** [comment]
This video shows how it crashed. It's reproducable for me 100%. I use the fast move keys to zap around my base to get to the different blueprints.
https://github.com/tsunamayo/Starship-EVO/assets/81495956/093584e3-a884-4502-9aa1-a54ed8435285

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, issue is fixed for 23w50b. Thanks!
