### ISSUE TITLE
[23w50a] Light following cursor

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#5388]
Hi there,

video pretty much sums it up
https://github.com/tsunamayo/Starship-EVO/assets/81495956/4bef9004-00e2-4d25-aabd-384141755e48

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, it was already fixed, will in the next build. In the meantime if you equip the mining tool it should diseapear. Thanks

**Comment by kynamats** [comment]
If the light wasn't blinking this would be a very useful feature, since atm the player torch is often too bright for building in dark areas. If at all possible i'd love this to be added as an f1 or f3 option!

**Comment by tsunamayo** [comment]
@kynamats Hi, well I can town down the torch, the pb being it will light up from closer!
@BigBadKangaroo Issue should be fixed in the build from yesterday. Thanks
