### ISSUE TITLE
[Bug]23w50b- Collector "None" setting not holding objects

### ISSUE THREAD

**Issue by Crimson-Artist** [tsunamayo/Starship-EVO#5391]
This is a bug for some time but the collector's "none" setting does nothing right now. Its suppose to gather objects and hold them in front of it. 

### Steps to reproduce the issue:

1. place down a collector
2. set it to "none"
3. place some objects in front of it.

**Comment by tsunamayo** [comment]
@Crimson-Artist Hi, it is fixed for 24w01a. Happy new year!
