### ISSUE TITLE
Crash after flying over planet surface

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#5393]
Hi there,

I just loading into my current world, flew around over the planet surface (for like 2 minutes) to my base with a shipyard. I then requested to land, got into the landing animation and then the game crashed.

- Starship EVO version: 23w50b
- Graphics Card: - Nvidia Geforce RTX 2080 Super

Crashlog: 
[crash.dmp](https://github.com/tsunamayo/Starship-EVO/files/13697511/crash.dmp)
[error.log](https://github.com/tsunamayo/Starship-EVO/files/13697513/error.log)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/13697514/Player.log)

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, I have fix a reason for a terrain crash recently, so tell me if you ever get other crash! Cheers
