### ISSUE TITLE
[BUG(?)] Small issues with wrecks

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#5395]
![Starship EVO 12_27_2023 5_21_09 PM](https://github.com/tsunamayo/Starship-EVO/assets/56371294/c3e6c17d-16a7-45a5-9124-5c1b4c3bcc1e)
screen is destroyed but text is not 
buttons and switches are still intractable but mechanisms are frozen so if you interact with a switch that triggers a mechanism the movement sound will begin to play and not stop 
also quick question would it be possible to add a wreck generator similar to the battle editor where you can spawn in your own ships or workshop ships as wrecks for screenshots or whatever?

**Comment by tsunamayo** [comment]
@TIKIRobo Hi, so it is fixed for 24w01a. You can generate custom wreck if you put your blueprint in the install folder of the game, in \Starship EVO_Data\StreamingAssets
 Happy new year!
