### ISSUE TITLE
{BUG] Copy and Paste not Working

### ISSUE THREAD

**Issue by CoasterBlock** [tsunamayo/Starship-EVO#5402]
### Short Description of the issue:

So I wanted to copy and paste a child-entity / a grid with a few CEs, the Copy/paste tool simply refuses to confirm the selection. Its specifically the control room on the entity that is causing this issue. Deleting it causes all the bricks to go invisible, after re-loading and deleting it again, it seems to get removed just fine. I will include the blueprint for you. 

### Steps to reproduce the issue:

Load the provided bluebrint, try to delete the piston for the control room (it wont work) 

### Environment
![20240104133534_1](https://github.com/tsunamayo/Starship-EVO/assets/126499309/2ee51d9d-f976-40ed-9a4b-f03cfc02dbd5)

- Starship EVO version: 23W52B Experimental
- Graphics Card: 2080 Super
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/13829974/Player.log)

### Additional information:
![20240104133534_1](https://github.com/tsunamayo/Starship-EVO/assets/126499309/eca659a1-a
![20240104134734_1](https://github.com/tsunamayo/Starship-EVO/assets/126499309/f6d4b64c-21c0-4485-bdcd-e982091ec4ae)
5de-4d04-b209-10c61a3b5327)

This does not seem to be an issue with the entity size, it just seems the entity wont be copied it if contains  child entities. I am really unsure, I can copy and paste things just fine, but this perticular use case is just broken. 

[Futuristic Trusses Blueprint.zip](https://github.com/tsunamayo/Starship-EVO/files/13830333/Futuristic.Trusses.Blueprint.zip)
The Control room is the circular space mounted on the piston. I am not sure what the issue is caused by.

**Comment by tsunamayo** [comment]
@CoasterBlock Hi, I am sorry I just dont understand what I am supposed to delete to reproduce. Could you please send me screen shot of the area in question? Thanks

**Comment by CoasterBlock** [comment]
![20240126103708_1](https://github.com/tsunamayo/Starship-EVO/assets/126499309/ababc6eb-0040-481c-8a36-e517f26fa9b8)
![20240126103737_1](https://github.com/tsunamayo/Starship-EVO/assets/126499309/4bd6835e-c914-4aaa-8a5e-10a96f0d682c)

Hi, @tsunamayo, This is the area in question. The structure you see in the image is connected to the ship using a piston. I cannot copy the piston, but I can copy the structure itself. Selecting the piston simply doesnt work. Its wierd, because when you copy a hinge, and object on the hinge is copied as well. The piston is hidden inside the diagonal arm above the structure.

**Comment by tsunamayo** [comment]
@CoasterBlock I am sorry this is not helping, can you put a little arrow on the first screenshot to tell me where is this piston. Second screenshot is too empty I just dont understand where it is. What structure are you talking about: the room or the ensemble room + arm (which is visually not connected to the main ship, so I just dont know where is the link)
Thanks
