### ISSUE TITLE
Strange Performance Issue

### ISSUE THREAD

**Issue by CoasterBlock** [tsunamayo/Starship-EVO#5403]
### Short Description of the issue:

The game seems to unreasonably task the GPU and RAM, caussing reving of the fans  to maximum RPM. 
I am on the EXPERIMENTAL branch 23W52b, 
HOWEVER: The FPS is high, (capped at 120FPS) So the game performes well, but it seems to flood the GPU to the point of hiccups. 

Specs:
32GB ram
R9 3900x AMD CPU
2080 Super NVIDIA GPU
Game is on a 500gb SSD. 

This is really strange, because even intensive renders in Blender do not seem to task the GPU this extremely. Entities seem to be the primary cause of this, especially if they are long. 
The GPU sits at 100% despite the game sitting in the background. 
After some more testing, just loading a new world and spawning on a default station, causes the GPU to jump to 100%, the cpu to 75% and the temperature to jump to 88C instantly....despite water cooling. 

There seems to be a major overflow issue here.

**Comment by tsunamayo** [comment]
@CoasterBlock Hi, try to limit FPS to a lower value.
If you are GPU bound then asking 120fps might be too much. Put 60 and tell me how it go!
Thanks

**Comment by CoasterBlock** [comment]
Hi, yeah thats exactly what I ended up doing. I used the Nvidia control panel to limit FPS that way. Now it works :)

**Comment by tsunamayo** [comment]
@CoasterBlock Hi, was the in-game option not working? Thanks

**Comment by CoasterBlock** [comment]
@tsunamayo Hi, I checked, and  it at least seems it did, as toggling the option changed the max FPS. However, only when I set a limit in my drivers it seems to have made a difference. I am not sure if this is just on my end.

**Comment by tsunamayo** [comment]
@CoasterBlock Okay thanks for the update.
