### ISSUE TITLE
Stuck, can't open Tab menu. 

### ISSUE THREAD

**Issue by Neo210** [tsunamayo/Starship-EVO#5404]
### Short Description of the issue:
I haven't played in a long time. I did an update then got on my ship.  Checking out new things and my character is stuck activating something.  A teleport pad maybe? I can not no clip I can not "unactivate" I can't open the TAB menu.  "Screen says [F] No system linked "
...

### Steps to reproduce the issue:
I'm unsure what I did to create it. I've read of others stuck attached to a yoke somewhere. But for me I'm unsure.
...

### Environment
- Starship EVO version:  23w41a
- Graphics Card:  Nvidia 2080 super

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/13830671/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

I am unsure about design. it was a ship I was making myself. but I'm not sure about it's blueprint name.

**Comment by ProPeach** [comment]
Could you send a screenshot? What did you do just before getting stuck? You might have to hold F to get yourself out of a system if you've entered one through a yoke or screen

**Comment by Neo210** [comment]
I had walked up to a teleport pad and pressed F.  That's where I'm stuck. CHaracter stopped moving and holding F does nothing and pressing TAB does nothing.
![20240104083243_1](https://github.com/tsunamayo/Starship-EVO/assets/1034226/c19feec6-955f-44da-a2cf-2da28cdb1939)

**Comment by tsunamayo** [comment]
@Neo210 Hi, could you send me your character save so I can investigate? Thanks

**Comment by Neo210** [comment]
Sure. I just zipped the whole character folder since I'm unsure which file you need. Also if there is something I can edit with like notepad or whatever to fix it just let me know. 
[tester02.zip](https://github.com/tsunamayo/Starship-EVO/files/13838198/tester02.zip)

**Comment by Neo210** [comment]
I don't know if it helps, but the view in my screenshot is definitely from a camera I have mounted to the third floor. Since I just realized that, the last steps I did were: make a RGB and a light connected them and activated them. THen jumped down and tried to activate my teleporter. F6 will allow the camera to get free but I still can't move.

**Comment by Neo210** [comment]
@tsunamayo Thank you. Whatever was in the update that fixed the mechanism not working unstuck my character! :D

**Comment by tsunamayo** [comment]
@Neo210 I dont think it was fixed I just reproduced in the latest update. I keep you posted.

**Comment by tsunamayo** [comment]
@Neo210 Hi, so the issue will be fixed for 24w03a. Thanks!
