### ISSUE TITLE
Force Field Graphics Bug

### ISSUE THREAD

**Issue by Tassyr** [tsunamayo/Starship-EVO#5406]
### Short Description of the issue:
The Force Field block, when placed at an angle in a series instead of one single block, causes possibly visual only bugs where the fields don't properly line up with the hole, often creating diagonal cuts. 

https://i.imgur.com/rrtQ3vC.png

### Steps to reproduce the issue:

Build more than one Force Field bar at the edge of a hole cut in the hull.

### Environment
- Experimental 23W52B
- Graphics Card: RTX 2080 Super

### Additional information:
![rrtQ3vC](https://github.com/tsunamayo/Starship-EVO/assets/31582275/e50d24a5-97bf-4894-9a71-96cbb9532b4f)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/13852378/Player.log)

**Comment by CoasterBlock** [comment]
I noticed that the the graphics for the field dont actually depict the area it seals. So while the field can eben be invisible, the field is still airtight. In some cases if the gap has complex geometry, the raycast will seal, but not draw the effect.

**Comment by tsunamayo** [comment]
@Tassyr Hi, I am not sure how to reproduce, could you send me your blueprint? Thanks

**Comment by tsunamayo** [comment]
@Tassyr Hi, again I need a blueprint to reproduce, @CoasterBlock If you have something I can look at please send it my way. Cheers
