### ISSUE TITLE
mechanism bug

### ISSUE THREAD

**Issue by Tackietacktack** [tsunamayo/Starship-EVO#5409]
### Short Description of the issue:

The door is built on a child by a child from a child. The first mechanism, where all children are created, works

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 24w02a
- Graphics Card: 

https://github.com/tsunamayo/Starship-EVO/assets/97230091/125098de-248c-4cae-9481-4b34cec02686

**Comment by KINGrimson** [comment]
yeah am seeing this too,  got a docking tube build that worked before the update now i cant move it anymore

**Comment by thriple** [comment]
Same. No mechanisms working. New, old, or loaded from blueprint.

**Comment by tsunamayo** [comment]
@thriple @Tackietacktack @KINGrimson Hi, could you please send me your blueprint? Also since this update you need your entity to be powered otherwise mechanism will not work.

**Comment by KINGrimson** [comment]
[Orion-v 2 interior stage hallways.zip](https://github.com/tsunamayo/Starship-EVO/files/13895589/Orion-v.2.interior.stage.hallways.zip)
here is the ship i am working on, has docking tubes and a hangar door on rails i cant get to move it has power

**Comment by tsunamayo** [comment]
@KINGrimson Thanks, actually I have just reproduced and fixed the issue, will push a build asap.

**Comment by tsunamayo** [comment]
@KINGrimson Hi, the build is up, if you guys could confirm all is well on your side!

**Comment by KINGrimson** [comment]
> @KINGrimson Hi, the build is up, if you guys could confirm all is well on your side!

its working thanks for the quick fix
