### ISSUE TITLE
[Bug] Infinite Save Loop [18w04a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#541]
Sometimes, when attempting to save, the "saving" disk icon will appear, and not go away. When this happens, the game does not save when the save key is pressed. Additionally, further attempts to save afterwards will have no effect. Attempting to exit the game to desktop via the menu will not work; the game must be closed with the Task Manager.

I haven't been able to determine what causes this bug in the first place. It doesn't seem to be related to how long the game's been running, or how much has been built in the world.

**Comment by Vicomt** [comment]
Oojimaflip saw this as well while we were playing MP, it also did NOT save at least one of the ships in the savegame, resulting in loss of work.

**Comment by oojimaflip** [comment]
I could exit to main menu after this happened, but trying to exit to desktop while the game is running did not work.

**Comment by tsunamayo** [comment]
Okay thanks for report this issue. Could you send me the output.log as it seems that the game did broke, so I can inverstigate? Thanks!

**Comment by Dwarf-LordPangolin** [comment]
Unfortunately, I don't have that output.log anymore; I had to reinstall the game after the recent update, and that got deleted with the rest; it hasn't come up yet since the reinstallation. The next time I see the error come up, I'll grab the output.log and put it up.

**Comment by Dwarf-LordPangolin** [comment]
I managed to get the infinite save loop again. I'll have to email the output.log to you, since it's almost 43 mb. Almost all of that is a loop of this, though:

```
NullReferenceException
  at (wrapper managed-to-native) UnityEngine.Material:Internal_CreateWithShader (UnityEngine.Material,UnityEngine.Shader)
  at UnityEngine.Material..ctor (UnityEngine.Shader shader) [0x00000] in <filename unknown>:0 
  at DistortEffect.OnRenderImage (UnityEngine.RenderTexture source, UnityEngine.RenderTexture destination) [0x00000] in <filename unknown>:0 
UnityEngine.Camera:Render()
Common.Rendering.RenderingPipeline:RenderCamera(Camera)
Common.Rendering.RenderingPipeline:OnPreRender()
 
(Filename:  Line: -1)
```
That starts at Line 377 of the log file, and just repeats again and again for over 794,000 lines.

I don't know if this is connected, but I was also running Space Engineers at the same time while porting one of my ships over; maybe this bug comes up when the computer is using a lot of memory or something?

**Comment by tsunamayo** [comment]
Hi, thanks for spotting that, it seems related to a new Unity plugin I have added, I will investigate. Cheers

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin hi, sorry could you please tell me your GPU spec, and also tell me if you see the shockwave blur effect when jumping in hyperspeed or when dropping out? Thanks

**Comment by Dwarf-LordPangolin** [comment]
No problem! GPU is an Nvidia GeForce GTX 1060 6GB. There is a camera shift effect when jumping in and dropping out of hyperspeed, where the camera slides back and forth.

**Comment by tsunamayo** [comment]
hey @Dwarf-LordPangolin as you are still active, could you just confirm this issue is no longer happening ;) Thanks mate
