### ISSUE TITLE
The mechanisms have stopped working

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5410]
### Short Description of the issue: The Mechanisms have stopped working for some reason, even the switches have stopped animating except for the green and red light

...

### Steps to reproduce the issue: 
Build the ship for more than 2 weeks
 Once a pop up message that says ship has no reactor ( which in my case they were there but did not detect) 
Then moved to press the switch to the elevator I created, does not function

### Environment
- Starship EVO version: early-access 24w02a
- Graphics Card: Nvidia GForce GTX  1060 6gb

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/13888917/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
[Battle Ship Nairobi.zip](https://github.com/tsunamayo/Starship-EVO/files/13888957/Battle.Ship.Nairobi.zip)

To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by Battlepixel** [comment]
Same here.

**Comment by Neo210** [comment]
I thought it was a sub issue with my issue of being stuck. My steps:

Make new save
skip tutorial
drop starter block
add piston
Press F

Pressing F is actually opening the label settings or something. Has label and length for the piston.

**Comment by tsunamayo** [comment]
Hi all, so I think what happens is you need some power to make mechanism works. Could you try with some functioning reactor on your build? Thanks

**Comment by tsunamayo** [comment]
@Neo210 Hi, yes this is normal, you need to link a button to your mechanism. Also you will need to add a reactor so your entity is powered.

**Comment by tsunamayo** [comment]
@surajnairpv Hi, sorry for that it was a regression, issue is now fixed and live. Thanks!

**Comment by surajnairpv** [comment]
> @surajnairpv Hi, sorry for that it was a regression, issue is now fixed and live. Thanks!

No need to thank me, Love the game !!!! Thanks for fixing it!!! :D

**Comment by tsunamayo** [comment]
@surajnairpv Haha, unfortunately people reporting issues are the minority, so I need to thanks them!
