### ISSUE TITLE
Fuel systems not working

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Starship-EVO#5412]
### Short Description of the issue:

Tanks are not transfering fuel to reactors in any case. I realy tried everything to get around tis bug, but no way. I have this problem with every blueprint for a while.

### Steps to reproduce the issue:
disable autofill reactors
Use your Entity and see how reactor fuel level goes to 0 despite the connected tank is full (but no fuel transfer is happening)

### Environment
- Starship EVO version: 24w02a and before
- Graphics Card: rtx4080

### Additional information:
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/13891686/Player-prev.log)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/13891689/Player.log)

https://github.com/tsunamayo/Starship-EVO/assets/43222403/ed98ac5e-7964-4bcd-acdd-2189f76c5fe7

[New Entity.zip](https://github.com/tsunamayo/Starship-EVO/files/13891600/New.Entity.zip)

**Comment by Gallt** [comment]
already marked as a bug, but yeah, I'm getting this too when i was testing my ships fuel lines.

**Comment by tsunamayo** [comment]
@Battlepixel @Gallt Hi, issue is fixed for 24w04a. Cheers
