### ISSUE TITLE
Rotate Left and Rotate Right now rotate in the same direction

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#5413]
### Short Description of the issue:
While building in creative, Rotate Left and Rotate Right keys now rotate in the same direction.
They correctly rotated in opposite directions in the previous main build, 23w41a.
It does not appear to be related to any blueprint in particular.
...

### Steps to reproduce the issue:
Equip a block that clearly indicates 4 different orientations when rotated before placement on a flat surface (like the wedge).
Hover the "block" tool over a buildable surface within normal proximity.
Press the shortcut for Rotate Left, then press the shortcut for Rotate Right.
The block should rotate 90 degrees, then rotate back to the original rotation.
It does not. Instead, it rotates 180 degrees, or two turns in the same direction (one per button press).
I think it's using the "rotate left" function for both buttons right now.
...

### Environment
- Starship EVO version: 24w02a
- Graphics Card: 1070ti (likely not related)

### Additional information:
![image](https://github.com/tsunamayo/Starship-EVO/assets/10069469/27f70aeb-4711-4e66-9fd7-ebd1b393cf33)

_(Screenshots, Videos, Error logs, Related issues)_

**Comment by tsunamayo** [comment]
@asanagisae Indeed, that was a regression so I pushed a fix already. Thanks
