### ISSUE TITLE
New FPS camera wobble

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#5414]
### Short Description of the issue:
As of 24w02a, when set to 1x movement speed, moving up/down/forward/backward will cause your on-foot FPS camera to wobble up and down (simulating head movement?).

Using fast move keys is a work-around. However, if those are not available in survival mode, this involuntary camera movement may prove problematic.

Also, if you have changed the character's speed (higher or lower), moved, then change back to 1x, the instant you set it to 1x your head will wobble even before you move.

Would it be possible to add an option to reduce or disable this? It is slightly disorienting when building for an extended period of time and can cause you to place a block where you didn't intend to.

This does not appear to be related to any specific graphics card, game save, or blueprint (as you don't need to be interacting with a blueprint to trigger it).
...

### Steps to reproduce the issue:
Don't use fast-move keys to adjust speed, leave speed at 1x
Ensure you are not seated or controlling a ship
Move up, down, forward, or backward.
Observe that there is also an associated and uncontrollable vertical camera movement up and down even without touching your mouse.
...

### Environment
- Starship EVO version: 24w02a
- Graphics Card: n/a

**Comment by tsunamayo** [comment]
@asanagisae Hi, this feature is deactivated for the anti-g /6 dof mode for 24w05a. Cheers
