### ISSUE TITLE
Inventory / Codex shortcut key interrupts ship rename if key is mapped to a letter

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#5415]
### Short Description of the issue:
When attempting to rename a ship, if the Codex key is mapped to a letter, the window will abruptly close if the ship contains that letter in its name. You have to open the window again to continue typing in the name.

The shortcut key should probably be ignored if a text field is in focus.

This is true for the faction and description fields as well.
...

### Steps to reproduce the issue:
Go to keymapping options, change "Inventory / Codex" to a letter - I use G to emulate Space Engineers
Interact with a ship to make it the "current entity"
Open the codex (with G), navigate to the "current entity" tab
Attempt to type in the full name for a ship that contains the letter G, for example "Engineering Vessel"
Observe that typing in the letter G causes the window to close, and any further letters in the ship name are ignored (because the window is now closed)
...

### Environment
- Starship EVO version: has always been, but is still true in 24w02a
- Graphics Card: n/a

### Additional information:
![image](https://github.com/tsunamayo/Starship-EVO/assets/10069469/f3234e56-ab80-44f0-8e0b-83b91354aec8)

![image](https://github.com/tsunamayo/Starship-EVO/assets/10069469/9258c19c-6008-42b0-84ad-bc1bb9f5b988)

**Comment by tsunamayo** [comment]
@asanagisae Hi, good catch, this will be fixed for 24w03a. Cheers
