### ISSUE TITLE
Character helmet light ignores sound settings

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#5416]
### Short Description of the issue:
The FPS light (default: L key) ignores sound settings. You hear the toggle "click" when turning the light on and off.
...

### Steps to reproduce the issue:
Press L key to toggle helmet light a few times. Hear the toggle sound.
Change the sound options to have 0 game volume.
Press L key to toggle helmet light a few times. The toggle sound is still active.
...

### Environment
- Starship EVO version: Present in earlier versions, but still true in 24w02a
- Graphics Card: n/a

### Additional information:
![image](https://github.com/tsunamayo/Starship-EVO/assets/10069469/2b445396-09e1-4dd7-91f0-e06bd692ff86)

**Comment by tsunamayo** [comment]
@asanagisae Hi, this is fixed for 24w02b. Thanks for the late surge of cases btw! Cheers
