### ISSUE TITLE
Game crashes on loading screen

### ISSUE THREAD

**Issue by jar101293** [tsunamayo/Starship-EVO#5418]
### Short Description of the issue:

Game crashes at the loading screen.

### Steps to reproduce the issue:

Start the game.

### Environment
- Starship EVO version: Early Access 24w02a
- Graphics Card: Intel Iris XE Graphics 31.0.101.4146

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Player.zip](https://github.com/tsunamayo/Starship-EVO/files/13895768/Player.zip)

**Comment by TIKIRobo** [comment]
unless im misreading this i think the cause of your crash may be your integrated graphics card, the game requires a dedicated gpu to run and people often find that it cannot run on integrated graphics.

**Comment by tsunamayo** [comment]
@jar101293 Hi, could you please open the Graphic option and select your preferred resolution and retry again? Thanks

**Comment by tsunamayo** [comment]
But tbh yes I fear your GFX card will be too low to run the game.
