### ISSUE TITLE
MagLock can not be activated via logic/sensors

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Starship-EVO#5419]
This is an older Problem/ or Suggestion and doesnt refers only to the last build.
MagLoc blocks only work when a player flips the connected switch. With the LaserSensor, rails and pistons, it is easy to build clamps that approach a landed/parked vehicle until shortly before contact and could then reposition or store it if the maglock blocks would also work when activated by logic. You could want to build similar systems to keep the landing-Area clear. Could you please implemntize that magLoc blocks also fulfill their function when they are activated by a sensor block, for example.

**Comment by tsunamayo** [comment]
@Battlepixel Hi, this will be fixed for 24w04a. Cheers!
