### ISSUE TITLE
[Gameplay/Bug] Inconsistent Scrapping

### ISSUE THREAD

**Issue by piotmetans** [tsunamayo/Starship-EVO#5420]
Scrapping seems a bit inconsistent, almost as if bigger blocks are made of smaller voxels but there is no visual representation of them breaking down, so the beam just goes through the shipwreck. 

https://github.com/tsunamayo/Starship-EVO/assets/660015/299c83ba-4aa2-4477-8bff-3c0aa7843d84

I also had a really bad bug testing this where the environment went entirely wacky, The ship would not stop slowing down or shooting the beam, and I couldn't leave the ship either. I'll include a player log and BP if there's anything useful there, but I'm not sure how to recreate it.

BP: 
[testscrap.zip](https://github.com/tsunamayo/Starship-EVO/files/13907725/testscrap.zip)

Log:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/13907734/Player.log)

- Starship EVO version: 24w02a
- Graphics Card: RTX 2070 Super

**Comment by tsunamayo** [comment]
@piotmetans Hi, I manage to reproduce the pass through and saw a few more issues related to scrapping. It is all fixed for 24w04a. Thanks!
