### ISSUE TITLE
Light Cruise Engine wrong direction, when it is at the correct Direction

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5422]
### Short Description of the issue: The light cruise Engine is placed at the rear just like the thrusters, was working fine...... I was light cruising but now there is an issue I cant lightcruise as its saying its in the wrong Direction. It started when I did Autopilot and then got off the controls. Also the game started lagging/sturttering like crazy after this error came.

...

### Steps to reproduce the issue:
1) get in to the controls of the ship
2) select starting station and autopilot there.
3) while traveling get out of the controls.
4) the ship starts traveling on autopilot without you being on the controls.
5) now after a brief moment the ship stops, and gives the error Lightcruise is at the wrong direction.And you cannot initiate autopilot.

...

### Environment
- Starship EVO version: early-access 24w02a
- Graphics Card:  Nvidia GForce GTX 1060 6gb

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

![Starship_EVO_Vpvkl8rIp7](https://github.com/tsunamayo/Starship-EVO/assets/93534629/788bbb1a-3006-4707-8113-0dfabd7b8b9b)
![Starship_EVO_VwT5i3tIQR](https://github.com/tsunamayo/Starship-EVO/assets/93534629/b2cf09cd-2c06-44f3-8126-1ea8918313da)
![Starship_EVO_TqF3E6ZadO](https://github.com/tsunamayo/Starship-EVO/assets/93534629/da6499c7-7ce3-49a8-8839-2cb8ce394464)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/13918111/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

[Battle Ship Nairobi.zip](https://github.com/tsunamayo/Starship-EVO/files/13918128/Battle.Ship.Nairobi.zip)

**Comment by tsunamayo** [comment]
@surajnairpv Hi, could you also send me your character file? There was an error during loading, I want to check it also, it might have a relation. thx!

**Comment by surajnairpv** [comment]
@tsunamayo I hope this is the character file 
[Suraj Nair.zip](https://github.com/tsunamayo/Starship-EVO/files/13934610/Suraj.Nair.zip)
if its not let me know where to get the correct file.

**Comment by tsunamayo** [comment]
@surajnairpv Hi, both error are fixed, it was a fuel issue. I have added a warning message so it is more clear to the player.
Cheers

**Comment by surajnairpv** [comment]
Awesome 👍 thankyou..... Was stuck in space due to this, finally I can continue the trip 😁
