### ISSUE TITLE
Gravity units don´t works ship wide

### ISSUE THREAD

**Issue by Tackietacktack** [tsunamayo/Starship-EVO#5423]
### Short Description of the issue:

I'm currently building a ship with several child entries, and I noticed that I have gaps in the gravity.
everywhere, where no bricks have been built by the children in the gravitation area.s

### Steps to reproduce the issue:

https://github.com/tsunamayo/Starship-EVO/assets/97230091/c733fc9e-83a1-4a99-88a9-855367200156

In the last few seconds you can see (1g, to the left of the hotbar) where I leave the main body and lose gravity.
### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by Crimson-Artist** [comment]
Gravity only applies to the entity that the unit is on. If you want to use just one gravity unit then you will have to either build the parent entity around the child entities or artificially extend the parent entity so its dimensions encompass its child entities. If you're doing the latter i'd suggest using Logic fields blocks. They're the blue transparent blocks in the codex. They're normally invisible and intangible

**Comment by tsunamayo** [comment]
@Tackietacktack Yes Crimson is right, also thanks for the tip. I am sorry indeed it is a limit of the engine.
