### ISSUE TITLE
Issue with the spawining of a big ship

### ISSUE THREAD

**Issue by Thomasbusson** [tsunamayo/Starship-EVO#5424]
### Short Description of the issue:

The ship spawn but it's invisible. The collisions still alright, the ship still drivable, just the blocks textures doesn't load in game
The ship worked well until the 10/01/2024 then it's stoped working since the 11/01/2024
...

### Steps to reproduce the issue:
Make the ship spawn
...

### Environment
- Starship EVO version: Experimental , 24w02a
- Graphics Card: 3070 geforce rtx ti

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Big ship : 540 000+ blocks, 5000+ chidren entities

![20240111214536_1](https://github.com/tsunamayo/Starship-EVO/assets/75631390/e2591ba5-f17a-4c16-83be-140cdd752fcc)

The ship look like this usually:

![20230516230110_1](https://github.com/tsunamayo/Starship-EVO/assets/75631390/4f915231-3da1-4608-8cf3-87feafc79c39)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/13924521/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

[GALAXIE INDUSTRIE - STAR LINER 1.15.zip](https://github.com/tsunamayo/Starship-EVO/files/13924515/GALAXIE.INDUSTRIE.-.STAR.LINER.1.15.zip)

**Comment by OvercomeDruid** [comment]
Hello and happy new year !!! Same type of problem except that others are added to mine (a full interior star destroyer of 611531 blocks).

 I have much longer loading times (like really much) when launching the map. 

Disappearance of the model on the original map (I deleted the map unfortunately).

Disappearance of complete parts of the blueprint (my entire back disappears visually and physically even if I re-download it to the map or another).

 Inability to make it fly (the model spins around at crazy speeds as soon as I start flying, so I have to redo a new map).

 Ultra long loading time when I make the ship appear in a map (a few minutes). That's it, this is a list of problems that occurred a few days ago. 

Before it worked very well: no display problems, no loading problems, no flight problems (this crazy guy could even land on the planets!).
 If necessary I can post the different problems with supporting maps and blueprints as well as my configuration if that would be useful. At the end, I think I've done the trick, thank you again for the hard work and good luck for the future!! :)

**Comment by tsunamayo** [comment]
@Thomasbusson Hi, this ship is incredible! Once finished it will be one of the most ridiculous ship ever made for the game. Anyway the issue is fixed, will be for the next build.
@OvercomeDruid Hi, you book a new case and send me the blueprint? I will investigate.
Thanks!

**Comment by OvercomeDruid** [comment]
@tsunamayo  OK perfect ! I grouped you into one. It's the : Display and piloting problems with a large ship + bug with child entities on large ship #5431


Thank you for your answer ! :)

**Comment by Thomasbusson** [comment]
Sorry for the late answer, thank you so much for the quick update, the ship spawn correctly now ! I hope peple will enjoy this ship when it will be finished :)

**Comment by Dolan-online** [comment]
The hotfix had also resolved this same issue for me but it's back as of  24w05a with identical symptoms to Thomasbusson's original post

I wasn't sure if I should make a new case since it's exactly the same as this one; invisible large ship with working collision, no textures.

I'm happy to post log and blueprint too if needed!
