### ISSUE TITLE
npc ships don´t have a captian

### ISSUE THREAD

**Issue by Tackietacktack** [tsunamayo/Starship-EVO#5426]
### Short Description of the issue:

when you look in a npc bridge you don´t found a captain who controlls the ship

**Comment by tsunamayo** [comment]
@Tackietacktack There are npc at the command of the ship from where I checked. Could you give me more info, like a screenshot of the ship?
Thanks

**Comment by Tackietacktack** [comment]
That's fine with me, has thinked, it has to do with Wracks and is lost-------- Ursprüngliche Nachricht --------Von: Francois Duret ***@***.***>Datum: Di., 23. Jan. 2024, 04:59An: tsunamayo/Starship-EVO ***@***.***>Cc: Tackietacktack ***@***.***>, Mention ***@***.***>Betreff: Re: [tsunamayo/Starship-EVO] npc ships don´t have a captian (Issue #5426)
@Tackietacktack There are npc at the command of the ship from where I checked. Could you give me more info, like a screenshot of the ship?
Thanks

**Comment by tsunamayo** [comment]
Okay thanks!
