### ISSUE TITLE
[BUG] crashed wrecks play switch noise 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#5427]
24w02a
I was flying around on a planets surface trying to see if I could get any of my own ships to spawn (only one is spawning, is there a size cap for wrecks?) and as I flew around the wrecks would play the switch click sound effect when they spawned in

**Comment by TIKIRobo** [comment]
![image](https://github.com/tsunamayo/Starship-EVO/assets/56371294/1401a701-c51e-4002-8b14-b002763236ac)
figured out why i wasn't seeing some of my wrecks, they got obliterated lol
![image](https://github.com/tsunamayo/Starship-EVO/assets/56371294/4ed27e44-4125-4660-b7b9-efc056aa2306)

**Comment by tsunamayo** [comment]
@TIKIRobo Hi, yes there is a limit of size and brick count. I am not sure to understand, it is just a one shot sound when the entity is loaded? Then it stops? thx

**Comment by TIKIRobo** [comment]
Yes, when the wrecks first load i hear what sounds like multiple switch sfx but they only go off one time and all at once

**Comment by tsunamayo** [comment]
@TIKIRobo Okay I will pass on that one then ^^
