### ISSUE TITLE
[BUG] "switch the stretch axis" tool tip remains on screen

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#5428]
24w02a

![image](https://github.com/tsunamayo/Starship-EVO/assets/56371294/e5a25f0a-bc81-433e-ae94-407f66c37385)
 
it never goes away

**Comment by tsunamayo** [comment]
hi, okay that is stupid I am fixing that asap!

**Comment by tsunamayo** [comment]
actually it stays up until the first time you build something, but I am pushing a new build atm.

**Comment by TIKIRobo** [comment]
Oh yay thank you! I think that is a good compromise

**Comment by tsunamayo** [comment]
@TIKIRobo Build is up!
