### ISSUE TITLE
[BUG] Entity power level over 100% and rising rapidly 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#5429]
![image](https://github.com/tsunamayo/Starship-EVO/assets/56371294/024eb2da-58a9-44d0-b597-73e50a591a2e)
as you can see my entity power level is 17,307 and this number is going up by a percent every half second, i believe this is only happening because of the solar panels 
24w02a
[Griffin - Aircar.zip](https://github.com/tsunamayo/Starship-EVO/files/13934865/Griffin.-.Aircar.zip)

**Comment by ProPeach** [comment]
If the high Entity Power Level is the issue, it seems that it's not limited to Solar Panel bricks.
https://media.discordapp.net/attachments/416013956331601930/1196743480249167902/image.png?ex=65b8bd38&is=65a64838&hm=acbfe6c9127927670ccd8059d45020d2f4ec225fd669a9203a2ec16d232fd2ff&
This is from a player on Discord who was having trouble with fuel so I don't have a bp sadly. 
To be completely honest, I'm not sure what the Entity Power Level/Capacity is showing. Is it the amount of energy stored in that system, compared to the whole ships output? A few of the stats in that menu could be better explained I think - the Stalled indicator also doesn't give any info on how to help a stalled system for example.


On another note, I didn't actually realise Solar Panels stored energy which is nice. Are you also thinking about adding a Battery brick so we can adjust the energy generation/storage ratio on ships Tsuna?

**Comment by tsunamayo** [comment]
@ProPeach Yes I want to add a swappable battery.

**Comment by tsunamayo** [comment]
@TIKIRobo Hi, issue is fixed for 24w03b. Thanks!
