### ISSUE TITLE
Uncontrollable ship drift - due to strong thrusters on mechanisms?

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#5432]
### Short Description of the issue:
A ship I built is drifting uncontrollably once any strafe movement (WASD) is inputted. All thrusters flicker rapidly, pushing the ship randomly in some diagonal direction, changing direction every now and then.

The ship has flown perfectly for weeks prior to this patch, and this bug has never occurred with this ship (or any other) prior to this patch.

### Steps to reproduce the issue:
Spawn the provided blueprint into a world. Sit in the seat, and take control of the stick. (F5 no-clip is recommended, as the main door is not complete.)

At this point, the ship behavior is still normal.

The issue is triggered when you strafe - forwards, backwards, sideways, it doesn't matter. Once you do, the ship will uncontrollably jitter in a random direction, changing directions periodically. This continues even if you leave the seat and stop controlling the ship, it will move on its own.

Movement stops only when you close the game and restart.

### Environment
- Starship EVO version: 24w02a, although I don't recall the issue being present last week (which was also 24w02a)
- Graphics Card: 1070 Ti (but likely not related)

### Additional information:
Demonstration of the issue. My only strafe input is at 0:05 seconds in, the rest is uncontrollable movement from the game itself. Free-look was used to show the thrusters flickering. I did exit this session with Alt+F4.
https://github.com/tsunamayo/Starship-EVO/assets/10069469/64137e41-cf32-40a7-8bb5-a55fc659a6a2

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/13996702/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it.
[Revolt.zip](https://github.com/tsunamayo/Starship-EVO/files/13996707/Revolt.zip)

**Comment by Tackietacktack** [comment]
hi, i have similar bug.

https://github.com/tsunamayo/Starship-EVO/assets/97230091/5adbfc18-198e-4b63-9d6b-b0316f47c165

[cockpit 6.4.zip](https://github.com/tsunamayo/Starship-EVO/files/13998952/cockpit.6.4.zip)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/13998953/Player.log)

**Comment by Tackietacktack** [comment]
forgotten, I think it may have something to do with the speed. After I installed the thick thrusters it started.

**Comment by tsunamayo** [comment]
@asanagisae Hi, it was linked to a massive amount of thruster. I have a cap now to apply the force, so it will be fixed for 24w04a. Cheers!
