### ISSUE TITLE
ship spawn only with ship computer and yoke all the rest is loosing

### ISSUE THREAD

**Issue by Tackietacktack** [tsunamayo/Starship-EVO#5434]
### Short Description of the issue:

My ship look like that after restart the game. i reload it , repair and starts a  new game and every time the same.
the save before runs. 
I built new 40 rounded shield generator(with hinge circle) with extensions , glowing hoses and lightcruise, tank and genator. the entire structure is on one hinge with ~1800% mass.
could it be that the two giant thrusters shine too much with all the glowing elements (lights, thruster, glowing tile, loosing shield and losing glowing hoses)

### Steps to reproduce the issue:
https://youtu.be/ytwkh1RgE1o
...
[cockpit 6.5 and 7.zip](https://github.com/tsunamayo/Starship-EVO/files/14000672/cockpit.6.5.and.7.zip)
[Player.zip](https://github.com/tsunamayo/Starship-EVO/files/14000673/Player.zip)

### Environment
-Starship EVO version: 24w02a
-Graphics Card: NVIDIA GeForce RTX 2060

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by Tackietacktack** [comment]
another end after loading the blueprint.
https://github.com/tsunamayo/Starship-EVO/assets/97230091/0f634734-70ce-4781-9da8-1e7bd84d5c4b

**Comment by tsunamayo** [comment]
@Tackietacktack Hi, thanks for booking the issue.
There is a corruption with children entity, Cockpit 7 will load incorrectly. I would like to understand what triggered it in order to fix the issue.
Could you please tell me what you did between the 6.5 and 7 version (with regard to mechanism, hinge ect). Like did you added some, removed, used symmetry ect? Thanks

**Comment by tsunamayo** [comment]
@Tackietacktack So the issue should be fixed for 24w03a. Cheers

**Comment by Tackietacktack** [comment]
That's great, Thank you
