### ISSUE TITLE
hinge with child entity ID: -1 has blocked the copy mode.

### ISSUE THREAD

**Issue by Tackietacktack** [tsunamayo/Starship-EVO#5436]
the hinge has blocked the copy mode.

I don't know if it's helpful, but it's better to tell you.
I would assume it's the rest of the bug from yesterday.

![Screenshot (53)](https://github.com/tsunamayo/Starship-EVO/assets/97230091/19dfaf4a-560a-4494-b015-86e253dbfb43)
![Screenshot (57)](https://github.com/tsunamayo/Starship-EVO/assets/97230091/07db9b90-30d0-43b3-b012-03505f98ac27)
### Short Description of the issue:

...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Tackietacktack Hi, starting from next build corrupted mechanism will get deleted on load, so this issue should no longer appear.
Cheers
