### ISSUE TITLE
Light Cruise still doesn't Work

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5437]
### Short Description of the issue: 
based on a previous issue raised the light cruise engine still says its at the wrong direction.
I have connected them to the fuel tanks via pipes and it says fuel is sufficient just don't know whether its a bug or I am doing something wrong.
I was told previously its a fuel issue so thought it was a setup issue. Not sure what's wrong.

...

### Steps to reproduce the issue:
Set up multiple light cruise engines connected with separate tanks full of fuel via the pipes.
...

### Environment
- Starship EVO version: early-access 24w03a
- Graphics Card: GForce GTX 1060 6gb

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

![Starship_EVO_UEbWPr3bhv](https://github.com/tsunamayo/Starship-EVO/assets/93534629/2b22879b-3285-481c-b3f5-323b0a59c3a8)

![Starship_EVO_O75awh4OPV](https://github.com/tsunamayo/Starship-EVO/assets/93534629/7eda82d7-2503-4997-b405-42f4d6e11ce0)

![Starship_EVO_nQBUpgh1O7](https://github.com/tsunamayo/Starship-EVO/assets/93534629/d35b9dc1-2440-4ff3-9903-c01dedc9b8cd)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14037626/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

[Battle Ship Nairobi.zip](https://github.com/tsunamayo/Starship-EVO/files/14037631/Battle.Ship.Nairobi.zip)

Also sending my character file here
[Suraj Nair.zip](https://github.com/tsunamayo/Starship-EVO/files/14037644/Suraj.Nair.zip)

**Comment by tsunamayo** [comment]
@surajnairpv Hi, yes the patch is still not yet live. Wait for the new build to come, it will be called 24w04a. Cheers

**Comment by surajnairpv** [comment]
Oohhh sorry, I thought I was doing something wrong.
Thank you  for letting me know
😁👍
