### ISSUE TITLE
[EXPERIMENTAL] Hyperspeed accelerates to maximum speed instantly 

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Starship-EVO#544]
This makes flying perilous if you are far away from any stellar body. There needs to be a "warming up period" as the drive slowly accellerates at first to a few kilometres/second, then slowly increase from there, especially in an area of Void away from planets or the star as these bodies are currently the ONLY brakes we have to slowing down Hyperspeed cruise.

**Comment by tsunamayo** [comment]
Yes I agree for deep space station it will be an issue - I might need to introduce some kind of beacon to make travel easier. You can reduce your throttle to go slower also, but it might not be convenient and takes time to slow down.
But really hyperspeed is not supposed to be a boost, what was the use you had in mind ? To move faster around a station?

**Comment by Napther** [comment]
I was stuck in the Void a little after the game updated with experimental, after only a few seconds of flying I was hit with the plaid-space bug and unable to continue because the game very quickly accelerated up to 1000+ C/Speed of light and shot me straight out the system. But it does need some form of navigation-lock sensitivity, locking onto a planet will scale your speed down in its vicinity.

There also needs to be some way to see and target stellar bodies without resorting to hopping out the ship and going to the Holomaps, but I assume further HUD elements are in the works. Perhaps this requires a scanner to do at some point on the fly.

Perhaps to also help distinguish the 2 flight modes, HYP cruise will highlight planets and stellar bodies, while STD will not.

**Comment by tsunamayo** [comment]
Hi, yes more HUD elements are planned, like orbits, selectable body ect. 
For the speed adjustment it is already there, close to a planet (whether it is selected or not) the speed will decrease. 
There is also a little HYP in the UI, but it is not enough I agree.
Also as I reduced the size of the systems, you might be very out of the system already, hence the massive speed you got. But I will add a cap of some sort in the next build. 
Thanks
