### ISSUE TITLE
Deleting bricks increases the hull points

### ISSUE THREAD

**Issue by Tackietacktack** [tsunamayo/Starship-EVO#5440]
### Short Description of the issue:
I have now built a new ship from which I build an engine and it gets hull point. Next I delete the engine and the ship does not lose hull points but gains hull points. I can repeat that. But when I save and load the ship I get correct amount of hull points.
​

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 24w03a
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Tackietacktack Hi, good catch, issue will be fixed for 24w05a. Cheers
