### ISSUE TITLE
Ships are sluggish in newest patch

### ISSUE THREAD

**Issue by RafaelLima235** [tsunamayo/Starship-EVO#5442]
### Short Description of the issue:
Following the 24w04a hotfix patch, all my ships seem to have much less thrust available outside of lightcruise, but top speed seems unaffected. 

### Steps to reproduce the issue:
Update to newest version of Starship EVO
Choose a ship who's handling you're normally familiar with
Feel how different it is

### Environment
- Starship EVO version: 24w04a Experimental branch
- Graphics Card: NVIDIA GeForce RTX 2070 SUPER

### Additional information:

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14054596/Player.log)

This patch also seems to have effected the collision system, making my ships phase through each other and voxels more easily

**Comment by tsunamayo** [comment]
@RafaelLima235 Hi, yes I have just noticed that, I am working on it.

**Comment by tsunamayo** [comment]
@RafaelLima235 Hi, issue is fixed, I am repushing the build asap. Thanks!
