### ISSUE TITLE
New CollisionBug - Ships sinking into Landingpads

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Starship-EVO#5443]
Landing this ship on the landing pad was never a problem before.
->Video
### Environment
- Starship EVO version: 24w04a

### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14057014/Player.log)

https://github.com/tsunamayo/Starship-EVO/assets/43222403/4b75647d-19be-45e2-b907-e1932e9e484a

Blueprint:
[Sparrow Typ D.zip](https://github.com/tsunamayo/Starship-EVO/files/14057034/Sparrow.Typ.D.zip)

**Comment by tsunamayo** [comment]
@Battlepixel Hi, I am looking at it right now. Can I ask a quick question? The entity you sent me was destroyed. It happened a lot recently, like every ship I look seems destroyed (while visually being intact). I suspect a bug, do you confirm you never destroyed that entity?
Thanks

**Comment by tsunamayo** [comment]
@Battlepixel Hi, issue is fixed, I have repushed the build. Thanks

**Comment by Battlepixel** [comment]
> @Battlepixel Hi, I am looking at it right now. Can I ask a quick question? The entity you sent me was destroyed. It happened a lot recently, like every ship I look seems destroyed (while visually being intact). I suspect a bug, do you confirm you never destroyed that entity? Thanks

I despawned the fighters, but the big entity is a ship that has a bug with one inner hangardoor. The a part of the (two sectioned) door only spawns if you use the door the first time after restart. Despite this bug the corvette and the little ship should were at full health.
