### ISSUE TITLE
cant undock form shipyards

### ISSUE THREAD

**Issue by KINGrimson** [tsunamayo/Starship-EVO#5444]
### Short Description of the issue:

in the latest patch when docked to a shipyard your unable to undock until a game reload

### Steps to reproduce the issue:

place shipyard dock to it and try to undock to see it not working

### Environment
- Starship EVO version: 24w04a
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@KINGrimson I think the issue should have been fixed (at least it was fine for me). The patch is up, can you retry? Thanks
