### ISSUE TITLE
changing scale keybinding restricts movement

### ISSUE THREAD

**Issue by COMICLER** [tsunamayo/Starship-EVO#5449]
when I change the rescale keybinding im no longer able to move

**Comment by tsunamayo** [comment]
@COMICLER Hi, what key did you rebinded? Can you reproduce? When you get a freeze like that I really need to have a look at your player.log file to investigate.

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

Thanks

**Comment by COMICLER** [comment]
i believe this is actually just a bug from using a older character. once i made a new one the problem was fixed. i attached the player log just in case it still might be of use 
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14156704/Player.log)

**Comment by tsunamayo** [comment]
@COMICLER Hi, did you redid the keybind assignment with the new character? What was the key you binded?
Thanks

**Comment by COMICLER** [comment]
After the update the defult key was binded to G, so i rebinded it to T and i couldnt move until i switched it back. on the new character the problem doesn't occur
