### ISSUE TITLE
[Bug] Ship description does not save

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#5451]
### Short Description of the issue:
In the codex, with a ship selected, the description of the ship does not save. There doesn't appear to be a description element in the ship's blueprint XML (where the ship name and faction are saved). I checked the files stored locally in (Windows) appdata using Notepad. This has been true for every ship I've looked at.

### Steps to reproduce the issue:
1. Create a new ship, or select an existing ship.
2. Open the codex to the page with the ship name, then add a description
3. Save the blueprint (optional)
4. Close the game, then run the game again
5. Note that the description you entered on the ship is no longer there

### Environment
- Starship EVO version: 24w04a (but has been an issue for as long as I remember)

### Additional information:
![image](https://github.com/tsunamayo/Starship-EVO/assets/10069469/abb87f88-e519-48f9-955a-6130ea3e39cd)

**Comment by tsunamayo** [comment]
@asanagisae Hi, good spot, I dont know why it was not reported sooner! Fixed for 24w05a. Thanks!
