### ISSUE TITLE
Low FPS makes the ship shake

### ISSUE THREAD

**Issue by Aranhanauta** [tsunamayo/Starship-EVO#5453]
### Short Description of the issue:

My computer's video card is not suitable for running the game. The Starship Evo is running at a minimum of 4 frames per second and a maximum of 17. At this rate, any ship I use, even basic-shaped ones, starts shaking violently when I lock onto a destination on autopilot.

### Steps to reproduce the issue:

Cannot be repeated unless the FPS is low.

### Environment

- Starship EVO version: 24w04a

- Graphics Card: AMD Radeon HD 8370D

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Aranhanauta Hi, is it only auto-pilot that does this, or also normal manual flight? Thanks

**Comment by Aranhanauta** [comment]
Hello goodnight. I'm not sure, but most of the tests I did happened when I engaged the autopilot.

Perhaps it could be the same problem that is influencing the warp jump.

**Comment by tsunamayo** [comment]
@Aranhanauta Hi, it should be fixed in the current update! Thanks
