### ISSUE TITLE
losing max. Speed

### ISSUE THREAD

**Issue by Tackietacktack** [tsunamayo/Starship-EVO#5454]
### Short Description of the issue:
I don´t know if it is bug or if you works on the speed balance. But I noticed that the max speed by a old ship (flaminger has a screenshot from his stats)  goes from 286m/s to now 178m/s.
by my actually build goes down from 370m/s to 190 m/s.

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 24w04a
- Graphics Card:

**Comment by BigBadKangaroo** [comment]
I've noticed that the ship will move a bit slower, but I didn't check for max. speed. 
But yeah, seems like the max. speed is lower than before!

**Comment by Tackietacktack** [comment]
I'm working on an Excel to understand the difference between the thruster scales. I worked out a graph and wanted to test it with new data and then I got other data as before. It seens like karma 😅

**Comment by tsunamayo** [comment]
@Tackietacktack @BigBadKangaroo Hi, I spotted a fat finger mistake in the previous update, so I think it should be all good for 24w05a. Cheers
