### ISSUE TITLE
Escape key to close popups

### ISSUE THREAD

**Issue by javoire** [tsunamayo/Starship-EVO#5457]
### Short Description of the issue:

Escape key to close popups

![image](https://github.com/tsunamayo/Starship-EVO/assets/642869/bde2ea27-34a2-4448-8fe0-23cf7d44b668)

The only way to close is to click the X with the mouse. Pretty standard stuff, cheers :)

### Steps to reproduce the issue:

Interact eg with refueling station

### Environment
- Starship EVO version: 
- 24w04a

**Comment by tsunamayo** [comment]
@javoire Kiosk is the only window you notice cannot close with ESC?

**Comment by tsunamayo** [comment]
@javoire Hi, this will be fixed for 24w05a. Thanks
