### ISSUE TITLE
[Bug] Laser Muzzle Flash FX plays in slow motion

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#5458]
### Short Description of the issue:
The flash FX when a Laser brick is fired shows for a full 1 second, and seems to be in slow motion rather than a quick flash like it should be.
Could be related to the new motion of the Recoil barrel? (Which is a big improvement btw, thank you!)

### Steps to reproduce the issue:
- Fire a Laser brick and look at the flash FX

### Environment
- Starship EVO version: 24w04a
- Graphics Card: RX 6700XT

**Comment by tsunamayo** [comment]
@ProPeach Indeed, it is fixed for 24w05a. Cheers!
