### ISSUE TITLE
Trees vanishes

### ISSUE THREAD

**Issue by Huttrem** [tsunamayo/Starship-EVO#5460]
### Short Description of the issue:

... went mine trees this one vishis leving nothing behind

### Steps to reproduce the issue:

... find a tree, mine it.

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Huttrem Hi, issue was fixed a few update ago. Thanks
