### ISSUE TITLE
Is it possible to reach another system traveling only with light cruiser engines?

### ISSUE THREAD

**Issue by Aranhanauta** [tsunamayo/Starship-EVO#5466]
### Short Description of the issue:

It's just a question.

I can't trigger warp jump, so I was wondering if I could travel to another star with just light cruiser engines. I know it will take HOURS to reach another system, but I would like to know if this is at least possible.

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by ProPeach** [comment]
I don't think so, they're different instances as far as I know. Why can't you initiate a warp jump? That sounds like a possible bug unless there's a misunderstanding

**Comment by Aranhanauta** [comment]
Its a bug

**Comment by tsunamayo** [comment]
@Aranhanauta Hi, nope it is not possible. I still need to check your issue sorry let me get back to you. It is a problem linked to FPS being too low.
