### ISSUE TITLE
assembler can´t produce sequencer gate

### ISSUE THREAD

**Issue by Tackietacktack** [tsunamayo/Starship-EVO#5468]
### Short Description of the issue:

i don´t find a sequencer gate in the schematics menu from assembler.
same by capacitor, tank join, rounded block, arch rounded, wedge rounded, round glases, hoses, teleporter, medbay, warpcore, fan, vent cover, force field, joystick and MUG.

 also All weapons can´t built also repair and mining beam

suggestion:
I think it might be easier if we produce one typ of hull brick.
so i do produce a hull brick and get standard hull block, rounded block, tile, arch, arch round , ... .
and not all separately. but just a idea

**Comment by tsunamayo** [comment]
@Tackietacktack Thanks, indeed there is plenty of schematics to be added. I can only bundle block by 5 shapes maximum, so I wont be able to bundle things that much. Also I will add different variant of the hull (like I already did with the scrap hull), but for the smaller shape to keep it simple.

**Comment by tsunamayo** [comment]
@Tackietacktack Hi, this is fixed for 24w10a. Cheers
