### ISSUE TITLE
Child entity refusing to copy

### ISSUE THREAD

**Issue by Azathoh-the-blind-idiot-god** [tsunamayo/Starship-EVO#5469]
### Short Description of the issue:
Child entity refusing to copy.
Persists in newly created worlds.

### Steps to reproduce the issue:
1: attempt to use the copy/paste tool on the pink hinge
2: nothing, it does not copy
### Environment
- Starship EVO version: 24w05A
- Graphics Card: RX5700

### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14230560/Player.log)
[Frigate outer hull 2 (broken).zip](https://github.com/tsunamayo/Starship-EVO/files/14230562/Frigate.outer.hull.2.broken.zip)

**Comment by tsunamayo** [comment]
@Azathoh-the-blind-idiot-god Hi, issue will be fixed for 24w07b. Btw you are using tons of children entity, and some overlapping which seems like a bug (so it might get fixed at one point)
