### ISSUE TITLE
[Survival Beta] Breaking Blocks on wrecked ships

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#5472]
Turns out, if you craft any block, you can start breaking wrecked ships to take those blocks. After I broke some amount of blocks, I was unable to do anything in the game so I restarted it and every block I broke was back on the ship (as well as my inventory) so I can essentially already create a ship with infinite blocks so to speak.

All while never making a crafting bench

![20240211200118_1](https://github.com/tsunamayo/Starship-EVO/assets/32974671/2279e860-4fe6-4c67-a795-284923a33cf2)

**Comment by Xerma** [comment]
I should also add that you can break blocks, then repair the ship and break them again for free

**Comment by Uncle-Ulty** [comment]
Yeah, I've built a provisional ship doing that. It lacks fuel though. 

![image](https://github.com/tsunamayo/Starship-EVO/assets/73253472/95974e6e-5407-4f82-bfb9-8d336cbe9504)

**Comment by tsunamayo** [comment]
Hi, okay so the first bug is that you should not be able to delete those blocks ^^. Let me check this.

**Comment by tsunamayo** [comment]
@Xerma Issue fixed for 24w06b. Thanks for the report mate!
