### ISSUE TITLE
[Survival Beta] Block Icons in Inventory

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#5473]
A good amount of blocks seem to have the starter block icon when they are broken in survival and go to the players inventory:

![20240211200434_1](https://github.com/tsunamayo/Starship-EVO/assets/32974671/f7a0adaa-a247-4086-a860-c0914a62e4fa)
![20240211200443_1](https://github.com/tsunamayo/Starship-EVO/assets/32974671/847aba90-3c21-4cc2-b345-b9abc1f9e9ba)
![20240211200442_1](https://github.com/tsunamayo/Starship-EVO/assets/32974671/a50073c5-476c-4fc7-9add-205e9ed27c36)
![20240211200440_1](https://github.com/tsunamayo/Starship-EVO/assets/32974671/4a4d6144-6737-44d2-9635-3b66a58ee72e)
![20240211200439_1](https://github.com/tsunamayo/Starship-EVO/assets/32974671/509337ac-6267-45f3-a400-bb059653e87b)
![20240211200438_1](https://github.com/tsunamayo/Starship-EVO/assets/32974671/fbdc434d-0cdf-4bd8-a800-4047e1d4b92b)
![20240211200437_1](https://github.com/tsunamayo/Starship-EVO/assets/32974671/fa0eb74b-bfbd-4e62-a7b9-8a0715387343)
![20240211200436_1](https://github.com/tsunamayo/Starship-EVO/assets/32974671/8d7ab63c-e244-4197-aa19-7d6c5038d834)

**Comment by tsunamayo** [comment]
@Xerma Hi, how did you got those blocks? Cheers

**Comment by Xerma** [comment]
Those are from the previous bug report of breaking blocks on the wrecked ships

**Comment by tsunamayo** [comment]
@Xerma Okay it is fixed, I upload the build soon. This was linked to legacy bricks. Cheers
