### ISSUE TITLE
[Survival Beta - Suggestion] Indicator for how many items a block takes

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#5476]
I see that there is already an indicator for how many of X item a block will take out of your inventory and how much you have. But, I feel like it should be simplified to [20/230] and should also be below where it says "x5 : x1 : x5 to make it a little more readable. I also don't feel it's necessary to say "@.025m" since there is already an indicator of what scale it's at.

It may also be easier to read if there is a translucent "bubble" around the text like this (no left aligned of course):

`1.25m : 0.25m : 1.25m`
`x5 : x1 : x5`
`[25/21]`

![20240211202958_1](https://github.com/tsunamayo/Starship-EVO/assets/32974671/b5877ea5-00d2-489e-831b-7ec7c9a98385)

**Comment by tsunamayo** [comment]
@Xerma I agree with those changes.

**Comment by tsunamayo** [comment]
@Xerma Hi, this is done for 24w10a! Cheers
