### ISSUE TITLE
[Survival Beta] Rocks / Minerals

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#5477]
It appears rocks cannot be placed in the backpack. Also, is it intended for there to be multiple different stacks of rocks even when they appear to be the same? Rocks and Minerals also do not have any information when you hover your mouse over them

![20240211205718_1](https://github.com/tsunamayo/Starship-EVO/assets/32974671/e658ae4b-cbfe-479d-b6aa-8aef0bb7effb)

**Comment by Huttrem** [comment]
> It appears rocks cannot be placed in the backpack. Also, is it intended for there to be multiple different stacks of rocks even when they appear to be the same? Rocks and Minerals also do not have any information when you hover your mouse over them
> 
> ![20240211205718_1](https://private-user-images.githubusercontent.com/32974671/303964994-e658ae4b-cbfe-479d-b6aa-8aef0bb7effb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MDkyODUsIm5iZiI6MTcwNzcwODk4NSwicGF0aCI6Ii8zMjk3NDY3MS8zMDM5NjQ5OTQtZTY1OGFlNGItY2JmZS00NzlkLWI2YWEtOGFlZjBiYjdlZmZiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDAzMzYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwMzk2N2MxNGU2ODMwOTdiNTAyYjUyZjg5MzcwNjE1MDBjYTlkMjViZTkwODE2MmJhZTA0YTdlYWQ2Yjg0ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Io2L_Vd6iRwrR9BtmMdzk4pZW-3qwo7mtMbfj_2SyM8)

rock are heavy, so it won't go in huge stack in backpack, every rock have diferent color, so you can craft diferent rock block with it, the info is it a bug

**Comment by tsunamayo** [comment]
@Xerma I think @Huttrem is correct. I will check for 1) though. For 2) I can use a wider color check if that is confusing.
Yes I still need to work on 3).
Cheers

**Comment by tsunamayo** [comment]
@Xerma So actually the way I am fixing 2) is through spawning the same color for every rock in the same biome. Because even with a wider color check you would always end up with different brick depending on how you merged your stack.  For 3) there is another case booked. Cheers!
