### ISSUE TITLE
[survival beta] No name or icon in some items (trees, ores and crystal)

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#5478]
some items, such as crystal, doesn't show their names in inventory menu

(I built this ship with  bricks removed from the wreck ship)

![image](https://github.com/tsunamayo/Starship-EVO/assets/73253472/1bf42d49-288a-41f9-a4ed-e130085440b6)

![image](https://github.com/tsunamayo/Starship-EVO/assets/73253472/f2ee8330-b1ac-41bf-996e-a64648d46cb6)

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hi, this is fixed for 24w07a. Cheers
