### ISSUE TITLE
[SURVIVAL BETA] Made of crystal...

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#5479]
I got some crystal on asteroids, and when I started to pilot, character's hand and head became crystal!

![image](https://github.com/tsunamayo/Starship-EVO/assets/73253472/53afccba-660a-41b2-a42d-0a4b9ead0979)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14235043/Player.log)
[ULTY 01.zip](https://github.com/tsunamayo/Starship-EVO/files/14235045/ULTY.01.zip)

**Comment by Huttrem** [comment]
![image](https://github.com/tsunamayo/Starship-EVO/assets/159193324/0e26c3ed-acaf-4538-afc3-296886d7fd4c)
 hi here i got my hand with the gold and a iron ingot overlaping

**Comment by tsunamayo** [comment]
Yes I saw that a few time, I need to understand how to reproduce...

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hi, this issue should be fixed in 24w08a. Cheers
