### ISSUE TITLE
[survival beta] Assembler input inventory

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#5486]
A bug happened when I put material on assembler input.

I put Iron, gold and silver ingots into the assembler's input. But, since I did not have power to make it work, I closed the assembler's menu. When I opened it again, all the material was lost (gold, silver, iron)...

Now I need to gather and melt make all the material once again (cry...)

![image](https://github.com/tsunamayo/Starship-EVO/assets/73253472/934b3672-6ef8-4cd8-994a-efdf1d48fa1a)

**Comment by asanagisae** [comment]
I ran into the exact same issue. The materials were no longer in the assembler, my backpack, or my shortcut rows.

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hi, so the bug is you should not be able to drag item into the input slots. They are there for display only. You just pick a schematic and the assembler will do the rest, I will fix the bug asap.

**Comment by tsunamayo** [comment]
@Uncle-Ulty Issue is fixed for 24w07b. Thanks!
