### ISSUE TITLE
[Survival Beta] Player stuck in a wreck upon spawning in a newly-created world

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#5491]
### Short Description of the issue:

As per title, I had an unlucky coincidence spawning stuck in a wreck when I first created the world.
It only happened on one occasion.
I tried to reproduce but the character spawned very close to the wreck (around 1 meter outside of it) and didn't get stuck.

Still, it has a chance of occurring for someone, so a failsafe for such a scenario might be needed, so that either the player cannot spawn near a wreck's location, or that wrecks cannot spawn at the player's spawn location.

### Steps to reproduce the issue:

1. Launch the game in the production environment
2. Create a new world using the default seed OTKMCCB
3. Enter the world

### Environment
- Starship EVO version: 24w06b
- Graphics Card: RTX 3070

### Additional information:

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14249741/Player.log)

https://github.com/tsunamayo/Starship-EVO/assets/63756057/a1c6e879-3ad3-4062-abe9-a081061a4e4d

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Okay thanks for letting me know! This is the survival wreck, not a random one, but I will add a distance buffer.

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Issue is fixed for 24w07a. Thanks!
