### ISSUE TITLE
[survival beta - bug] Items disapeared from inventory

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#5492]
After exiting to desktop, and opening the game again, all items from the inventory disappeared. The same happened to some assembler inventory

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14250585/Player.log)
[Survival 2.zip](https://github.com/tsunamayo/Starship-EVO/files/14250588/Survival.2.zip)

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hi, do you mean the player inventory?

**Comment by Uncle-Ulty** [comment]
yeah

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hi, issue is fixed for 24w08a. Cheers
