### ISSUE TITLE
[Survival Beta] First Base  = Destroyed Entity

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#5494]
Hi there,

it seems like my newly build base is destroyed from the beginning: 
![20240212214748_1](https://github.com/tsunamayo/Starship-EVO/assets/81495956/cb58cbe3-668b-4422-a2bc-eb3ce80d8fb1)

My Assembler didn't work until I pressed "repair entity" in the codex tab. 
After I pressed "repair entity" in the codex tab, everything worked fine.

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, I made a tentative fix for this in 24w07b. Tell me if you ever saw this again!
