### ISSUE TITLE
[survival beta] Copy - paste cheating

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#5497]
When you copy-paste something, every pasted brick is free and requires no material to build.

You can observe it in this video.

I copied several "hull" bricks, and as you can see in the red circle, the total hull bricks count doesn't change when I paste several bricks

the symmetry tool does the same.

https://github.com/tsunamayo/Starship-EVO/assets/73253472/7b1a1e97-8e6f-4b09-a6e3-801bfd337df9

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hi, issue is fixed for 24w07a. Cheers
