### ISSUE TITLE
[Survival Beta] Starter Block Duplication

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#5500]
Starter blocks don't get consumed when placed so you can place an infinite amount and break them to get even more

![20240212205334_1](https://github.com/tsunamayo/Starship-EVO/assets/32974671/0a0f9317-fac3-4f84-a50a-62941fe4dfc5)

**Comment by tsunamayo** [comment]
@Xerma Indeed, it is fixed for 24w07a. Cheers
