### ISSUE TITLE
[Survival beta] Arc furnace attempts to process coal

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#5502]
### Short Description of the issue:
Arc furnace will keep pulling coal from connected cargo even if it doesn't use it. It can get clogged up trying to process the coal, and won't attempt to process any ores or stone.

### Steps to reproduce the issue:
Create a cargo container and arc furnace. Connect the two with a conveyor tube.
Configure the arc furnace to automatically pull input from connected inventories and push output to connected inventories.
Place ore in the cargo container, observe that the arc furnace processes it and puts the ore in the cargo container.
Place coal in the cargo container, observe that the arc furnace puts coal in its own storage.
When the arc furnace is done processing whatever ore, if there is coal in its storage, it will stop processing and refuse to pull any ores.

### Environment
- Starship EVO version: 24w06b

### Additional information:
![image](https://github.com/tsunamayo/Starship-EVO/assets/10069469/d3516791-99cb-4e91-a320-479c10cef10b)

**Comment by tsunamayo** [comment]
@asanagisae Hi, issue is fixed for 24w07b. Thanks for being active! Cheers

**Comment by asanagisae** [comment]
It's a pleasure when the developer is so responsive~
