### ISSUE TITLE
[Survival beta] Lasers/beams and girders leave visual artifacts when salvaged (after game restart)

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#5503]
### Short Description of the issue:
On wrecks, certain blocks leave visual artifacts when you close the game and return to the world. This includes lasers/beams, and girders.

### Steps to reproduce the issue:
Find a wreck with lasers, beams, or girders.
Use the mining tool to mine those blocks until they're destroyed.
The blocks will disappear entirely as expected.
Close the game.
Start the game and load the world again.
Observe that certain visual artifacts return on these destroyed blocks.

### Environment
- Starship EVO version: 24w06b

### Additional information:
![image](https://github.com/tsunamayo/Starship-EVO/assets/10069469/6897514c-8b3d-44ad-8a0a-a5b2e6bb2ce8)

**Comment by tsunamayo** [comment]
@asanagisae Hi, issue will be fixed for 24w07a. Cheers
