### ISSUE TITLE
Repair tool stuck on mouse 

### ISSUE THREAD

**Issue by Tackietacktack** [tsunamayo/Starship-EVO#5504]
### Short Description of the issue:
You see the repair tool by closed codex. 

### Steps to reproduce the issue:

Open codex take repair tool and don't put it in your hotbar, now close the codex. You see the repair tool by closed codex

**Comment by tsunamayo** [comment]
@Tackietacktack Hi, I am not sure to understand what "You see the repair tool by closed codex" means, I tried to reproduce but everything was normal. Could you send a screenshot if possible? Thanks

**Comment by Tackietacktack** [comment]
The icon stuck on mouse
https://github.com/tsunamayo/Starship-EVO/assets/97230091/6b9ec435-8737-4ca9-8130-ae9b2714201c

**Comment by tsunamayo** [comment]
@Tackietacktack Thanks it was useful, issue is now fixed for 24w07b. Cheers
