### ISSUE TITLE
Power Outage bricked the game

### ISSUE THREAD

**Issue by Sad-Lonely** [tsunamayo/Starship-EVO#5507]
Had a power outage while playing, had to wipe the entire game after being unable to load worlds or start new ones

Have a power cut to desktop while playing (Maybe? I don't know how easy it is to replicate)

- Starship EVO version: 24w06b
- Graphics Card: Geforce RTX 4070

There is no log, as I had to entirely wipe the game in order the fix the issue

**Comment by Huttrem** [comment]
@Sad-Lonely this is weird i have outage all the time and my game work well after it, wonder if other ppl had something similar at your's

**Comment by tsunamayo** [comment]
@Sad-Lonely Hi, sorry to hear this, you also had to trash older save? It does not make sense, you should at least be able to load previous save, it should have only corrupted the current save. Unfortunately it dont think many games are power outage proof, if it happens during a save you are screwed. That is why most game says dont power off your console while the save icon is flashing.
Cheers
