### ISSUE TITLE
[Survival beta] Can't craft gravity unit

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#5510]
### Short Description of the issue:
The assembler cannot craft the gravity unit, which is required for light cruise engines.

I've placed all the required materials in a cargo container piped to the assembler. The assembler is set to pull from it automatically, which it does for every other recipe. If I put the materials into the assembler manually (pictured), it still doesn't build.

If I cancel the gravity unit and queue up a different recipe, the assembler produces that recipe as normal. It's only refusing to build the gravity unit specifically.

### Steps to reproduce the issue:
Fly to space. Obtain these lava-like crystals. Return to base.
Place crystals in cargo, piped up to assembler.
Ask the assembler to create a light cruise engine.
It will get stuck on the "gravity unit" step. The same issue occurs if you queue up the gravity unit specifically.

### Environment
- Starship EVO version: 24w06b

### Additional information:
![image](https://github.com/tsunamayo/Starship-EVO/assets/10069469/6406d5d4-d006-44c7-aae7-97f725da0734)

**Comment by asanagisae** [comment]
It's possible the "crystals" I picked weren't the right ingredient. The world save is 34 MB zipped, but Github has a limit of 25 MB. Are the files in the "Terrain" folder necessary? I could delete that before zipping.

**Comment by Uncle-Ulty** [comment]
the crystal is the problem

**Comment by asanagisae** [comment]
Ah thanks. I see your issue #5493. I then flew back to the asteroid, used F to pick up the crystals (instead of mining them), and then I was able to craft the gravity units with these crystals.

They do have a different icon than the mined ones. For most other things, "mining" has usually produced the correct materials. Odd.

![image](https://github.com/tsunamayo/Starship-EVO/assets/10069469/7ebe936d-7ce9-4cbc-8d2f-9ae58fd24156)

**Comment by tsunamayo** [comment]
@asanagisae well it is a bug it should be the opposite!

**Comment by tsunamayo** [comment]
Okay issue is fixed for 24w07a. Cheers
