### ISSUE TITLE
[surviaval beta] assambler replicanting infinite items

### ISSUE THREAD

**Issue by Huttrem** [tsunamayo/Starship-EVO#5511]
### Short Description of the issue:
while attenting to craft some electrical components it got stuck in mouse and began to fills inventary, stuck in my cursor and went try to leave in storage it keep leaving it staking more but still in cursor as i where holding it
...

### Steps to reproduce the issue:
it happend while i was crafting some normal tanks
...

### Environment
- Starship EVO version: survival beta 24w06b
- Graphics Card: Procesador	AMD Ryzen 3 3250U with Radeon Graphics, 2600 Mhz, 2 procesadores principales, 4 procesadores lógicos

### Additional information:

https://github.com/tsunamayo/Starship-EVO/assets/159193324/53768bba-883f-4023-8bf6-3b50d1e25f9c

_(Screenshots, Videos, Error logs, Related issues)_

https://github.com/tsunamayo/Starship-EVO/assets/159193324/33598739-7485-49b2-b4ef-cb0d33c1b54e

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14272211/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
Hi, that issue should have been fixed in the last update. Thanks
