### ISSUE TITLE
Game has a chance to crash while interacting with the cargo blocks

### ISSUE THREAD

**Issue by Janssendel** [tsunamayo/Starship-EVO#5513]
### Short Description of the issue:

Game has a chance to crash while interacting with the cargo blocks. If arc furnaces are on, then the game will shuffle items around, causing a crash and you to revert to the nearest save and lose most items.

### Steps to reproduce the issue:

Unknown, but similar to description

### Environment
- Starship EVO version: survival test (latest)
- Graphics Card: Intel(R) Graphics HD P630 and NVIDIA Quadro M1200

### Additional information:

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14274941/Player.log)

**Comment by tsunamayo** [comment]
If think that issue should have been fixed in the last update. Thanks
