### ISSUE TITLE
[Survival Beta] Item Loss after re-joining game.

### ISSUE THREAD

**Issue by Janssendel** [tsunamayo/Starship-EVO#5514]
### Short Description of the issue:

Items will randomly disappear from cargo blocks for no reason after re-opening the game.

### Steps to reproduce the issue:

1. Put items into cargo block in survival mode
2. Exit to Desktop
3. Rejoin and check cargo block.

### Environment
- Starship EVO version: Experimental Branch (Latest)
- Graphics Card: Intel(R) Graphics HD P630 and NVIDIA Quadro M1200

### Additional information:

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14279945/Player.log)

**Comment by Tackietacktack** [comment]
i think we get this bug when the first field from cargo is free.

befor restart, assembler has inventory but first field is free

https://github.com/tsunamayo/Starship-EVO/assets/97230091/a99e3e1c-4fc1-43e6-bffe-67512a0a43cc

after restart, assembler completly clear

https://github.com/tsunamayo/Starship-EVO/assets/97230091/121bf50d-7f0a-4bde-af10-53a24c0288ec

**Comment by Janssendel** [comment]
> i think we get this bug when the first field from cargo is free.
> 
> befor restart, assembler has inventory but first field is free
> 
>  Unbenanntes.Video.Mit.Clipchamp.erstellt.2.mp4 
> after restart, assembler completly clear
> 
>  Unbenanntes.Video.Mit.Clipchamp.erstellt.3.mp4

for me, it happens to all blocks, more often in the cargo boxes than assemblers, arc furnaces or crucibles.

**Comment by tsunamayo** [comment]
@Janssendel Hi, how many blocks / items where in that cargo? A lot or just a few? I am talking in number of slots taken, not in term of real item quantity.
