### ISSUE TITLE
[Survival mode] Rocks turned to plant

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5516]
### Short Description of the issue:
Was working on the furnace and the Rock I had turned into a Plant
...

### Steps to reproduce the issue:
Built the furnance
tried to add some rocks
tried adding few more rocks but got the beep sound saying it full so placed it back into the inventory.
once I placed back the rock turned into a plant icon
and now I am holding it
there is also a small rock on screen as well on the right hand
...

_(Screenshots, Videos, Error logs, Related issues)_

![Starship_EVO_DewCEomrqr](https://github.com/tsunamayo/Starship-EVO/assets/93534629/a4044963-62d7-4586-85f8-4a6403de1d1b)

**Comment by tsunamayo** [comment]
@surajnairpv Hi, I really need the log to investigate, as it I cant do anything. Next time please share the log! Thanks

**Comment by surajnairpv** [comment]
@tsunamayo sorry about that will surely keep that in mind next time
