### ISSUE TITLE
[Survival Mode] Furnace Silicon Bug

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5517]
### Short Description of the issue:
The silicon is getting multiplied in the furnace and after taking in one the duplicates disappear.
also the right hand as a rock and silicon held together.
The game also hung for some reason so had to force close the application. 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

https://github.com/tsunamayo/Starship-EVO/assets/93534629/61f08522-1f66-494e-8b8b-b2a97b0860bc

**Comment by tsunamayo** [comment]
@surajnairpv Hi, please in case like that I need the error log to investigate.

**Comment by surajnairpv** [comment]
@tsunamayo sure next time something like that happens will keep that in mind.
