### ISSUE TITLE
[survival beta] game crashed

### ISSUE THREAD

**Issue by Tackietacktack** [tsunamayo/Starship-EVO#5518]
### Short Description of the issue:
i´m Minimize the game and going back to windows.
windows says: no respond 

### Steps to reproduce the issue:

copy by running game

[Player-prev.zip](https://github.com/tsunamayo/Starship-EVO/files/14284343/Player-prev.zip)

but after closing  i have forgot

this one is from new session

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14284393/Player.log)

### Environment
- Starship EVO version: 24w06b
- Graphics Card: RTX 2060

**Comment by tsunamayo** [comment]
If think that issue should have been fixed in the last update. Thanks
