### ISSUE TITLE
[survival beta] I'm one with nature, nature is one with me

### ISSUE THREAD

**Issue by Huttrem** [tsunamayo/Starship-EVO#5519]
### Short Description of the issue:
there are some small trees atached to my character, also some started to spawn around me a little furter

### Steps to reproduce the issue:
not sure i was mining cobalt and change screen to check discord, went come back i was surrounded by trees
...

### Environment
- Starship EVO version: beta test 24w06b
- Graphics Card: Procesador AMD Ryzen 3 3250U with Radeon Graphics, 2600 Mhz, 2 procesadores principales, 4 procesadores lógicos

### Additional information:
![Captura de pantalla (885)](https://github.com/tsunamayo/Starship-EVO/assets/159193324/f891b0e4-e40e-4f8b-8042-cc30e35ff84f)
![Captura de pantalla (887)](https://github.com/tsunamayo/Starship-EVO/assets/159193324/87eb77e6-e1d1-4187-ba0a-4695aca43479)
![Captura de pantalla (888)](https://github.com/tsunamayo/Starship-EVO/assets/159193324/64957fa2-5e2e-4bea-80d8-5330179fda17)
![Captura de pantalla (889)](https://github.com/tsunamayo/Starship-EVO/assets/159193324/1927cccb-6281-4127-b49b-25c38c34b02c)

![Captura de pantalla (884)](https://github.com/tsunamayo/Starship-EVO/assets/159193324/3adeb9a7-4171-4a81-b787-d62484c00d7c)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14284559/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by Uncle-Ulty** [comment]
my plants: "I can't stand the sun, water or air"

Tsuna's plants: "nhanham, fuel clouds, delicious!"

**Comment by tsunamayo** [comment]
humm maybe I could leave that as a feature ...

**Comment by tsunamayo** [comment]
@Huttrem Hi, so I think this bug should be fixed for 24w08a. Cheers
