### ISSUE TITLE
Typos in the backpack Codex crafting window tooltip

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#5520]
### Short Description of the issue:

As per the title, there are typos (switched letters, "packback") in the Codex backpack tooltip in the crafting window.

### Steps to reproduce the issue:

1. Open the Codex
2. Pick the Crafting tab
3. Hover the cursor over the backpack icons in one of the lines

### Environment
- Starship EVO version: 24w06b
- Graphics Card: RTX 3070

### Additional information:

![image](https://github.com/tsunamayo/Starship-EVO/assets/63756057/023fe655-2e4d-464d-a44a-ff1ebc3d7cac)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Fixed for next build. Thanks
