### ISSUE TITLE
No tooltip upon hovering cursor over the stone/pebble icons

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#5521]
### Short Description of the issue:

Hovering the cursor over various elements in the crafting window produces tooltips.
This however does not happen for the stone/pebble elements which produce no tooltip upon cursor hover.

### Steps to reproduce the issue:

1. Open the Codex
2. Pick the crafting window
3. Hover the cursor over one of the stone/pebble elements

### Environment
- Starship EVO version: 24w06b
- Graphics Card: RTX 3070

### Additional information:

![image](https://github.com/tsunamayo/Starship-EVO/assets/63756057/55e1eb95-a20e-4d3b-b410-33de34170313)

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Hi, issue fixed for 24w07b. Thanks
