### ISSUE TITLE
Scrap metal acquirement rate feels inconsistent and unpredictable

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#5528]
I found that I could spend a few minutes trying to tear down a few sections of armor and not get a single unit of scrap, only to then destroy a small piece and get several units.

This presents a problem when a player desperately needs a single piece of scrap ASAP, but instead they have to wait several minutes while tearing down the wreck for the scraps units to pile together and be salvaged in a big chunk.

I think the visual effect of the scraps travelling towards the player character should be more visible.
This can be improved by making the destination point of the effect's spline in the lower right corner to make them look like they travel towards the mining tool itself.

Also, the scrap pieces could be placed on a layer above the mining tool, so that they cover it for a split second when completing the spline, clearly telegraphing their presence in the player's peripheral vision.

https://github.com/tsunamayo/Starship-EVO/assets/63756057/60b426a1-3b10-41e8-88f6-edb27fab8dce

**Comment by tsunamayo** [comment]
Hi, yes I noticed that too, I need to check from what block those missing chunk where. Issue is deprecated block dont spawn any scrap. It might block who miss a schematic too.
Thanks

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil Hi, I think it should good now, for 24w08a. Cheers
