### ISSUE TITLE
[Survival Beta] 24w06b - Items disappear from assembler's input.

### ISSUE THREAD

**Issue by dean-proca** [tsunamayo/Starship-EVO#5530]
### Short Description of the issue:

Any items placed in assembler's input disappear.

### Steps to reproduce the issue:

Construct an assembler and place it down.
Open the assembler's UI and place any item in the input section.
Close the assembler UI.
Open the assembler UI.
Observe that items previously placed into the UI are gone.

### Environment
- Starship EVO version:  24w06b
- Graphics Card:  RTX 3080ti

### Additional information:

https://www.youtube.com/watch?v=a0tTvbxgdvY

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by surajnairpv** [comment]
I had the same issue I had placed some gold ingots there and lost them after I closed the UI.

**Comment by Huttrem** [comment]
@dean-proca, @surajnairpv, this is know bug, it happends went the assambler have no power to prevent this bug while is fixed, don't store in the input UI, power with wing turbine firts

**Comment by dean-proca** [comment]
@Huttrem I have two wind generators on that platform. How do I connect it?

**Comment by Huttrem** [comment]
@dean-proca you just place over hull and they should magically transfer energy to it

**Comment by dean-proca** [comment]
@Huttrem Thanks. So I had two wind generators on the same platform (hull) as the assembler and it's still deleting items in that video. You just don't see the wind generators because they are behind me.

**Comment by tsunamayo** [comment]
@dean-proca Hi, no the bug is that you should not be able to drag thing in the input slot. You need to click on a receipe and the assemble will pull the necessary input from its inventory or connected inventories.

**Comment by dean-proca** [comment]
Thanks everyone for the info.

**Comment by tsunamayo** [comment]
Issue is fixed for 24w07b. Thanks!
