### ISSUE TITLE
Placing gravity block caused BP corruption

### ISSUE THREAD

**Issue by fellow-starmadian** [tsunamayo/Starship-EVO#5533]
### Short Description of the issue:
Gravity block set to ship wide, made ship invisible on reload and broke entities which had volumetric sensors with massive volumes on them.

### Steps to reproduce the issue:
I set a gravity unit to ship wide, on a ship where there are 99,999m long stretches of volumetric sensors on a mechanism entity.  the bounds were only set to the entity the gravity unit was placed on however.  could not align myself to the ship with gravity unit, so closed the game.  hotfix was installed as well.  upon reloading the game, ship was invisible.  further inspection via copy and paste tool revealed that only this ship was affected, and everything could be copied except for the mechanisms which had the volumetric sensors in their chain.  finding the invisible gravity block and deleting it, then renaming and respawning the newly renamed blueprint, caused the ship to be visible again, allowing me to see that only the volumetric sensor mechanism entities had been deleted, including the small turntable on the rotors.  

"radar v4" is the broken, pre edit BP.
"radar v4 broken" is the one where I deleted the gravity unit, which means ironically it's the one that works.
I'll also attach a few images to show how things looked.

Another note, I have restarted the game far more times than I have player log files. "player-prev.log" being one game load before I made the "v4 broken" blueprint, the other log file being when the issue was fixed.

### Environment
- Starship EVO version: 24w07a
- Graphics Card: RTX 2080TI

### Additional information:

![2024-02-15 21_36_49-Window](https://github.com/tsunamayo/Starship-EVO/assets/13528733/7ae8d4e3-d033-4d85-ba2d-7c74e5501b75)
![2024-02-15 21_51_11-Window](https://github.com/tsunamayo/Starship-EVO/assets/13528733/f5ca3659-33a0-44ca-afa5-65651322c7fe)
![2024-02-15 21_51_21-Window](https://github.com/tsunamayo/Starship-EVO/assets/13528733/12c1b703-61c5-48a7-a34e-a7a0a2ce2f9a)

Blueprints:
[radar v4.zip](https://github.com/tsunamayo/Starship-EVO/files/14305234/radar.v4.zip)
[radar v4 broken.zip](https://github.com/tsunamayo/Starship-EVO/files/14305235/radar.v4.broken.zip)

Log files:
[Player (2).zip](https://github.com/tsunamayo/Starship-EVO/files/14305242/Player.2.zip)

**Comment by tsunamayo** [comment]
@fellow-starmadian I am sorry I can load Radar broken fine, what I am supposed to do to reproduce?
Do you still get this is the latest build? Thanks
