### ISSUE TITLE
[Survival Beta] Player will inherit the freecam speed of Camera Mode (F6) 

### ISSUE THREAD

**Issue by Janssendel** [tsunamayo/Starship-EVO#5534]
### Short Description of the issue:

The player will inherit the speed of the freecam mode (f6) if they press [ or ] to increase their speed as they would in creative. This means that, if you are in freecam mode and then go back to normal camera mode, you will inherit the speed at which the camera travels. 

What I would suggest is turning on the teleportating tab and BP spawning mechanic for the survival playtest for a while, so that testers can better deal with bugs causing their progress to reset (Item Loss) or their ships being flung into space for no reason and losing them.

### Steps to reproduce the issue:

1. Go into freecam mode (f6)
2. Press [ or ] to increase velocity
3. Exit out of freecam mode

### Environment
- Starship EVO version: Experimental Branch (Latest)
- Graphics Card: Intel(R) Graphics HD P630 and NVIDIA Quadro M1200

### Additional information:

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14305463/Player.log)

**Comment by tsunamayo** [comment]
@Janssendel Hi, issue fixed for 24w08a. I agree I will add them back for the time being. By the way I am not sure about that F6 thing, as it allows the player to cheat for scouting for minerals for example...
