### ISSUE TITLE
Minor text corrections - deaths

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#5535]
### Short Description of the issue:
Just suggesting some minor spelling and grammar tweaks to some default messages in English.

![image](https://github.com/tsunamayo/Starship-EVO/assets/10069469/f24fd36b-6095-49ea-9b76-f845146788da)

`You went too close to a star and got roasted to death. Bring a higher UV index cream next time!`

Changes:
- "to" should be "too"
- Missing space after the period

![image](https://github.com/tsunamayo/Starship-EVO/assets/10069469/3eb5514e-89e5-48ac-872f-8a1d5dcd7393)

`You went too close to a gas giant planet and were crushed by the pressure. Told you carbon was not good enough!`

Changes:
- "to" should be "too"
- "where" should be "were"

### Environment
- Starship EVO version: 24w07a

**Comment by tsunamayo** [comment]
@asanagisae Thanks a lot! Dont hesitate to report more of those if you spot any. Cheers
