### ISSUE TITLE
[Survival Mode] Assembler stops constructing

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5536]
### Short Description of the issue:
The assembler stops construction though it has all the required materials and components
...

### Steps to reproduce the issue:
stack multiple solarpanels for the assembler to construct.
close the assemblers ui
eventually it will stop.

### Additional information:

https://github.com/tsunamayo/Starship-EVO/assets/93534629/6446a40c-1d18-4878-a314-cd985e035823

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14308561/Player.log)

My Base file
[Outpost.zip](https://github.com/tsunamayo/Starship-EVO/files/14308584/Outpost.zip)

**Comment by surajnairpv** [comment]
My character file is above 25 mb, if you need it do let me know if there is any other way to upload it.

**Comment by dean-proca** [comment]
I think I've reproduced this issue. You don't even have to close the assembler UI, you can watch it. I think the key is to queue up multiple clicks, whether single clicks or shift clicks for stacks of 10. Eventually the assembler no longer understand that prerequisite parts need to be built and will sit there not constructing until the current queue is cancelled and a new queue is started.

**Comment by tsunamayo** [comment]
@surajnairpv @dean-proca I did a big pass on assembler, they should now be much more resilient, with several locks cause now avoided, and if that is not enough they are able to reset themself when stuck. Cheers

**Comment by surajnairpv** [comment]
@tsunamayo awesome 😎👍
Thanks for the update
