### ISSUE TITLE
[Survival Beta] 24w07a - Only the most recently place Arc Furnace has particle effects (assuming multiple Arc Furnaces filled with resources)

### ISSUE THREAD

**Issue by dean-proca** [tsunamayo/Starship-EVO#5540]
### Short Description of the issue:

Only the most recently placed Arc Furnace has particle effects (assuming multiple Arc Furnaces filled with resources)

### Steps to reproduce the issue:

Construct and place an Arc Furnace.
Construct and place a second Arc Furnace.
Place rocks in both Arc Furnaces to produce Silicone.
Notice only the most recently placed Arc Furnace (assuming multiple Arc Furnaces filled with resources) has smoke particle effects.

### Environment
- Starship EVO version: 24w07a
- Graphics Card: RTX 3080ti

### Additional information:

![ArcFurnace](https://github.com/tsunamayo/Starship-EVO/assets/38061647/56b2e63a-4178-4818-be1d-f67a40449120)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@dean-proca Hi, I think it might be related to the fact they are close, let me check.
