### ISSUE TITLE
[bug] starterblock don´t hold the ship by building

### ISSUE THREAD

**Issue by Tackietacktack** [tsunamayo/Starship-EVO#5541]
### Short Description of the issue:

start a new build with a starterblock, then build a second starterblock and delete the first. the starterblock rotated now.

https://github.com/tsunamayo/Starship-EVO/assets/97230091/2a2dfb65-d9ec-45b4-8932-cbafb06d93cd

### Environment
- Starship EVO version: 24w07a
- Graphics Card:

**Comment by tsunamayo** [comment]
@Tackietacktack Hi, that feature of the starter block is not supposed to "hold" the ship, but is supposed to just apply anti-gravity to it. Cheers
