### ISSUE TITLE
[BUG] Constant power drops from 100% to 90%

### ISSUE THREAD

**Issue by SovietSponge** [tsunamayo/Starship-EVO#5543]
### Short Description of the issue:
Power spikes from full to about 90%, causing reactors to constantly consume fuel.
Nothing on the ship should be consuming power, I've either removed or turned off all power consuming components.
### Environment
- Starship EVO version: 24w07a
- Graphics Card: RTX 3060 Ti

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

https://github.com/tsunamayo/Starship-EVO/assets/66131361/52c0c643-c340-48ad-8290-622e477a1f89

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14316791/Player.log)

[AE.zip](https://github.com/tsunamayo/Starship-EVO/files/14316815/AE.zip)
I've attached the world file as I've no clue if this is survival specific, ship specific or world specific and I unfortunately don't have the time to test for each of these variables.

**Comment by ProPeach** [comment]
I've just tried to load the attached world, but placing it in my Characters folder does not make it show up in the Characters list ingame. Usually I can just put the folder in there and load it, but since this CBT it seems there's an issue

**Comment by tsunamayo** [comment]
@SovietSponge Hi, I have tried it and it seems the culprit is the o2 life support system, which has some power requirement. Cheers
