### ISSUE TITLE
[BUG] [SURVIVAL] Helmet doesn't stay on between reloads

### ISSUE THREAD

**Issue by SovietSponge** [tsunamayo/Starship-EVO#5545]
### Short Description of the issue:
I loaded into a world which I left while outside of my ship's life support system. I immediately started taking damage as my helmet wasn't on despite me having it on when I left the world.
### Steps to reproduce the issue:
Exit world while in space without life support., load into world.
### Environment
- Starship EVO version: 24w07a
- Graphics Card: RTX 3060 Ti

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14316878/Player.log)

**Comment by tsunamayo** [comment]
@SovietSponge Hi, good catch, issue is fixed for 24w07b. Cheers
