### ISSUE TITLE
Game sometimes crashes when attempting to use either light cruise or regular full speed cruise from complete stand still

### ISSUE THREAD

**Issue by Timtee** [tsunamayo/Starship-EVO#5551]
### Short Description of the issue:

The game crashes whenever I press L or TAB whilst at a stand still sometimes.

### Steps to reproduce the issue:

Press L or TAB whilst at standstill. Not entirely guaranteed to cause the issue due to the randomness of when it does and doesn't occur.

### Environment
- Starship EVO version: 24w07a
- Graphics Card: GTX 1650

### Additional information:

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14324266/Player.log)
[error.log](https://github.com/tsunamayo/Starship-EVO/files/14324265/error.log)
Both player and error logs provided due to the fact that I... don't really know what within the game's code is making this happen, and hopefully with both, this issue can be truly resolved for good.

**Comment by Aranhanauta** [comment]
Yes, I have been the same troble some times.

**Comment by tsunamayo** [comment]
@Timtee Hi, thanks for booking the bug. Could you please send me the content of the folder:
C:/Users/TimTee/AppData/Local/Temp/Moonfire Entertainment/Starship EVO/Crashes
Cheers

**Comment by Timtee** [comment]
> @Timtee Hi, thanks for booking the bug. Could you please send me the content of the folder: C:/Users/TimTee/AppData/Local/Temp/Moonfire Entertainment/Starship EVO/Crashes Cheers
The log files I had linked in the primary post are from there. Though if you need the other file in the most recent one related to this issue, aka the crash dump file, then I can send that. otherwise i've already sent what was asked of me to send.

**Comment by tsunamayo** [comment]
@Timtee This issue was fixed a few patches ago. Thanks!
