### ISSUE TITLE
[survival beta] Can't grab ore

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#5552]
I can't grab any ores I've dropped. I believe it's related to the "crystal grab bug" that you solved before

![image](https://github.com/tsunamayo/Starship-EVO/assets/73253472/0e5a9411-51f6-43a2-b7ff-73977654a9fe)

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hi, issue is fixed for 24w07b. Cheers
