### ISSUE TITLE
[survival beta] First ship - destroyed entity

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#5553]
I've built my first ship in a new world and the game says it's destroyed, so I can't use it

![image](https://github.com/tsunamayo/Starship-EVO/assets/73253472/12bca272-fd8e-4099-a193-006070024e00)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14325556/Player.log)
[Survival 3.zip](https://github.com/tsunamayo/Starship-EVO/files/14325558/Survival.3.zip)

**Comment by tsunamayo** [comment]
@Uncle-Ulty Yes I have seen this bug, I cant understand what is triggering it though. I will get back to you.

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hi, do you remember if you created that entity during that session? Thanks

**Comment by tsunamayo** [comment]
Okay so I have made a change for the next update, it is a tentative fix as I cant reproduce that issue (I saw it a few time though)

**Comment by tsunamayo** [comment]
That bug should gone now. Thanks
