### ISSUE TITLE
[survival - suggestions] Power Generation on planets - Steam Engine

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#5555]
I was wondering if Coal is subutilized for survival.

In our first base, we depend solely on wind turbines. But since we have water, oxygen and coal, why don't we use this coal to generate power?

So my idea is the following: a new _steam engine brick_ that produces power, but requires Coal to fuel it, a water source, and oxygen. 

This _steam engine brick_ would be optimized for bases, but it could work on hovercraft also with a tank full of water.

This brick would not work properly in space, cuz the player would have to build a huge tank of water and oxygen.

**Comment by Crimson-Artist** [comment]
cool! I actually suggested something similar not too long ago.

Your idea to use water is nice but it adds another resource to something that will ultimately be made obsolete when we start to make hydrogen reactors, which only requires one. Also moving large quantities of water around is kind of difficult especially in the early game.

Imagine trying to power a base with your steam engine on a planet without water. You'd have to ship in water AND use coal just to power everything. This gets really redundant if this is an output mean you have access to space travel thus access to hydrogen.

Keeping it to just coal allows it to be more straight forward and potentially keep it useful in the future as coal is nearly as abundant as iron.

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hi, yep there has been another thread on that already, lets discuss that over there. thx
