### ISSUE TITLE
[Sugestion] Stations on the surfaces of planets and moons.

### ISSUE THREAD

**Issue by Aranhanauta** [tsunamayo/Starship-EVO#5557]
### Short Description of the issue:

We currently only have space stations orbiting planets and moons, with an average of two to three stations per star system.

I think if there were ground stations positioned on the surface of planets and moons, that would be a cool addition, plus it would be a reason to go to the surface of one other than just collecting ores.

Note: Stations within ring systems would also be interesting, or even within asteroids.

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Aranhanauta Yes of course, this is something I have in mind! Cheers
