### ISSUE TITLE
[Survival Beta] 24w07b - Certain geometry on a vehicle/base grid causes unexpected physics interactions with player avatar

### ISSUE THREAD

**Issue by dean-proca** [tsunamayo/Starship-EVO#5559]
### Short Description of the issue:

Certain geometry on a vehicle/base grid causes unexpected physics interactions with player avatar

### Steps to reproduce the issue:

Place a flat grid of 1m blocks.
Place a speedometer.
Approach the speedometer from it's back.
Observe player avatar is thrown into the air.

Some other cases based on sharp edges seem to throw the player avatar. Please see video.

### Environment
- Starship EVO version: 24w07b
- Graphics Card: RTX 3080ti

### Additional information:

https://www.youtube.com/watch?v=lNdaEycAK-A

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@dean-proca Hi, issue will be fixed for 24w11a. Cheers
