### ISSUE TITLE
[Survival Mode] Ship Glitch

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5560]
### Short Description of the issue:
I was flying  the ship around space all of a sudden the ship begins to shake.
after few seconds I eject out of the ship, I guess there was  dying animation and then get teleported to my base.
I had forgotten to deactivate F5 before getting into the ship.
This has happen twice the same way, lost 2 ships.
...

### Steps to reproduce the issue:
activate no clip mode F5
fly the ship Out in space
eventually the glitch will start
...

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

https://github.com/tsunamayo/Starship-EVO/assets/93534629/3e22c3a3-7248-4753-b411-3c91432262e4

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14335926/Player.log)

**Comment by surajnairpv** [comment]
@tsunamayo is there anyway I can teleport back to my ships?

**Comment by tsunamayo** [comment]
@surajnairpv You just died of lack of oxygen. This is survival! I still need to make more clear that the player is taking damage and it is coming from a lack of oxygen, I will improve that!
Nope you cant get back to your ship unless you put a teleporter on them and you are close enough.

**Comment by surajnairpv** [comment]
I didn't mention this clearly at the start I was ejected out of the ship by force. I did not come out willingly.

**Comment by tsunamayo** [comment]
@surajnairpv You got ejected from the ship by the force of death ^^

**Comment by surajnairpv** [comment]
Yes I later played and understood that but forgot to update it here , thanks for letting me know though. 😁  👍
