### ISSUE TITLE
[Survival Beta] 24w07b -  Assemblers stealing components from eachother disrupt their production queue

### ISSUE THREAD

**Issue by dean-proca** [tsunamayo/Starship-EVO#5561]
### Short Description of the issue:

Assemblers connected to the same inventory system steal components from eachother's inventory and disrupt eachother's construction queue. Sometimes to the point where the disrupted assembler needs to be removed from the grid and replaced.

There are two disruptions in the video, one near the start of the video where the assembler completely breaks and needs to be removed from the grid then replaced, and one near the end of the video where the first assembler finishes it's work first then the second assembler is unable to finish due to no components to steal from the first assembler, but is still working if the production queue is reset.

### Steps to reproduce the issue:

Have a platform ready for assemblers to begin building.
Place a large container down.
Place two assemblers down.
Connect both assemblers to the large container with conveyor tubes.
Start assembly of products that use some of the same components to build. In this case using the same product in both assemblers is easiest but this can occur if two different products have at least one component in common.
Assembly must begin at different times so one assembler will request components that are already in the other assembler's inventory.

Timing can be tricky, please watch the video until the end. Two different type of failures can be seen. The first failure is near the start of the video and disrupts the second assembler so much that clearing the production queue and restarting it doesn't work. It has to be completely removed from the grid and replaced in order to get it working again.
The second disruption occurs near the end of the video where the first assembler finishes it's production queue and therefore doesn't make components for the second assembler to steal. Being unable to steal components from the first assembler, the second assembler is unable to finish it's production queue. Production failure of this type can be restored by either canceling the production queue and restarting it, or placing the component it was expecting in it's inventory.

Suggestion: Assemblers shouldn't be able to steal components from eachother's inventories. In the case where the user wants to use one assembler to produce components for finished products on another assembler these should be pushed to a connected container.

### Environment
- Starship EVO version: 24w07b
- Graphics Card: RTX 3080ti

### Additional information:

https://www.youtube.com/watch?v=M24XY-BPYnw

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@dean-proca Hi, okay good catch I will do something so we cant pull from an assembler inventory.

**Comment by tsunamayo** [comment]
@dean-proca Hi, this is fixed for 24w09c. Cheers
