### ISSUE TITLE
[Survival Beta] Character spews out ingots

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#5562]
Hi there,

my character spews out iron ingots and I don't know why ... I was just crafting some basic stuff for my hovercraft and got in and out of inventorys of the assembler and arc furnace to get the resources.
I couldn't let go of the iron ingot inside of the inventory and as soon as I got out of the inventory, the spewing began ... 

After a relog,  **_ALL_** of my crafted items are gone! In every inventory! 

https://github.com/tsunamayo/Starship-EVO/assets/81495956/41697425-6c78-4475-bc7b-86e56c0e2cfe

[Survival #2.zip](https://github.com/tsunamayo/Starship-EVO/files/14336561/Survival.2.zip)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14336566/Player.log)

**Comment by tsunamayo** [comment]
@BigBadKangaroo Yep sorry about that, it seems that something somewhere is triggering an inventory corruption. I need to find a way to replicate. I dont think that log is from the play session though, do you still have the Player-prev.log?. 
I keep you posted

**Comment by BigBadKangaroo** [comment]
Hi,

you mean this one?

[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/14349170/Player-prev.log)

**Comment by tsunamayo** [comment]
@BigBadKangaroo Yep exactly! I can see the error, thanks!

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, so I think the issue might be fixed for 24w09a. I am not 100% sure though, so lets keep our eye open if it happens again. thx
