### ISSUE TITLE
[Suggestions]  Jet bag idea and O² boddle's extend breathing air

### ISSUE THREAD

**Issue by Tackietacktack** [tsunamayo/Starship-EVO#5563]
### Short Description of the issue:

The idea is, thank we get more breathing air, if we have a O² boddle in our inventory. 
That can help, if our life support or energy system is broken or we are on a Unlivable planet. 

Same with H² boddle it can make, that we get more fly time and Hover with jet bag.

Aah, don't want to make a new issue,

What do you think, if our jet bag is something like a handheld, But we have it everytime.
This jet bag has thruster, battery or tank for energy, tank for life support and cargo. And we can configurate it self.

![Screenshot 2024-02-20 221216](https://github.com/tsunamayo/Starship-EVO/assets/97230091/04a0e6b9-d8ef-4e2a-a27c-229620940049)

If we want a greater inventory, we building more cargo of the jet bag.

![Screenshot 2024-02-20 221536](https://github.com/tsunamayo/Starship-EVO/assets/97230091/d49fdd8e-df80-4100-81c1-38f77c9b0f76)

If we want more thrust, we build more thruster of it.

![Screenshot 2024-02-20 221935](https://github.com/tsunamayo/Starship-EVO/assets/97230091/3e888c46-d493-459f-95ee-60ee2ffe28f2)

If we want longer thrust we build more battery on it.

![Screenshot 2024-02-20 222206](https://github.com/tsunamayo/Starship-EVO/assets/97230091/25f2b5f3-0258-43c4-aebb-579b460172df)

If we want more O² we make a greater O²tank.

![Screenshot 2024-02-20 222407](https://github.com/tsunamayo/Starship-EVO/assets/97230091/b067c131-ca05-4531-8e19-75382f7e7eba)

One possibility is That is have a antenna for navigation which we can upgrade for more range and other special things (player updates). 

![Screenshot 2024-02-20 223228](https://github.com/tsunamayo/Starship-EVO/assets/97230091/73168496-1267-42c9-bb02-b8c989e54aaa)

**Comment by surajnairpv** [comment]
This looks like a nice addon, would love this feature if it can get implemented.
