### ISSUE TITLE
Asteroid belt in star systems.

### ISSUE THREAD

**Issue by Aranhanauta** [tsunamayo/Starship-EVO#5564]
### Short Description of the issue:

It's just a suggestion, but something that would make the game more immersive would be the presence of asteroid belts around the stars of some solar systems.

In my ignorant point of view, it would even be easy to insert it, perhaps using the same mechanics used to generate rings around planets and moons, the difference is that it would be around stars and on a larger scale.

I would like to know other people's opinions on this matter.

**Comment by tsunamayo** [comment]
@Aranhanauta Hi, yes I have thought about it but there are several problem related to this, both on gameplay and tech. For example how the speed scaling system should works? In the end I dont think I will be able to do it. sorry ^^

**Comment by Aranhanauta** [comment]
No problem. It was just a suggestion. The game is already amazing as it is.
