### ISSUE TITLE
[SURVIVAL MODE] Hovercraft NO Sound

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5566]
### Short Description of the issue:
The hovercraft won't have any sound if you add a switch and turn it off  and then on.
...

### Steps to reproduce the issue:
Create a hover craft vehicle
create an on off switch
connect the switch to all the hover pods, reactors and thrusters.
get into the hover craft when its on, there will b sound.
now switch off the hover craft an let it fall to the ground.
get off the hover craft
now get in the hovercraft seat
switch on the hover craft
there will be no sound of the vehicle.

You can try my vehicle blueprint attached here and test it

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14360844/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.
[HoverBike.zip](https://github.com/tsunamayo/Starship-EVO/files/14360863/HoverBike.zip)

**Comment by tsunamayo** [comment]
@surajnairpv Hi, I cant reproduce this, it works fine on my side.
