### ISSUE TITLE
[Survival Mode] Sliding Rail not functioning

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5567]
### Short Description of the issue:
Constructing a ship and was trying to create a sliding door but for some reason the sliding rail does not work, it worked previously in other builds but does not work on the new build
...

### Steps to reproduce the issue:
Build a ship
place sliding Rail
...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

https://github.com/tsunamayo/Starship-EVO/assets/93534629/638bc330-7450-4d03-add3-0c3e6b6caccf

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14361672/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

[SpaceSHip.zip](https://github.com/tsunamayo/Starship-EVO/files/14361679/SpaceSHip.zip)

**Comment by surajnairpv** [comment]
is it because of the Starter Block?

**Comment by Tackietacktack** [comment]
Have you tested to repair your ship? Yesterday I have it with piston because the ship was marked as destroyed. After repair has it worked.

**Comment by tsunamayo** [comment]
@surajnairpv Was is it a new entity (did you created it in that build session)>
 Could you send me also the player-prev.log? Thanks

**Comment by surajnairpv** [comment]
> Have you tested to repair your ship? Yesterday I have it with piston because the ship was marked as destroyed. After repair has it worked. 

Thanks for the info will try this out and update you

**Comment by surajnairpv** [comment]
> @surajnairpv Was is it a new entity (did you created it in that build session)>
>  Could you send me also the player-prev.log? Thanks

Yes I did create the entity at that build session.
Sure will send you the player-prev logs

**Comment by surajnairpv** [comment]
> @surajnairpv On my side it works fine on your blueprint, do you have the problem after a restart? I also suspect the entity was destroyed (This is a bug I having trouble to reproduce and fix)

When I start the game again will update you on that

**Comment by surajnairpv** [comment]
@tsunamayo 
here is the player prev you asked for
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/14372193/Player-prev.log)

**Comment by surajnairpv** [comment]
@tsunamayo @Tackietacktack 
Started the game today and now it works fine. It seems a restart fixes this bug.

**Comment by tsunamayo** [comment]
@surajnairpv Thanks, btw the destroyed entity issue is fixed. Thanks
