### ISSUE TITLE
[Survival Mode] Conveyer belt  collision issue

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5568]
### Short Description of the issue:
The conveyor belt seems to have no collision when ingots are expelled out.
This is happening with Silicon Ingot and rocks.
with Iron ingot it works fine

### Steps to reproduce the issue:

Create conveyor belts leading from the the furnace to the cargo box.
build collectors on the furnace and cargo box
connect the collectors to the furnace and cargo box respectively via conveyor tubes
set the collector attached to the furnace to expel and the collector connected to the cargo box to collect
reduce the pull range of the collectors
Puts some rocks and wait for the furnace to do its process.

you will see the ingot going through the conveyors the minute they expel out of the furnace.
...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

https://github.com/tsunamayo/Starship-EVO/assets/93534629/4b23b635-227e-4681-9e90-e798d17bf184

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14363425/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.
[Outpost.zip](https://github.com/tsunamayo/Starship-EVO/files/14363446/Outpost.zip)

**Comment by tsunamayo** [comment]
@surajnairpv Hi, issue is currently fixed. Thanks
