### ISSUE TITLE
[Survival Mode] Thrusters when built look small

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5572]
### Short Description of the issue:
When the assembler is constructing the thrusters, the pieces come together but the final product 'thrusters' looks tiny, smaller than the parts.
...

### Steps to reproduce the issue:
Build the thrusters
...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

https://github.com/tsunamayo/Starship-EVO/assets/93534629/bd2d8c94-da9d-482b-a8b2-d1efa2bedaf4

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14375810/Player.log)

[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/14375815/Player-prev.log)

[Outpost.zip](https://github.com/tsunamayo/Starship-EVO/files/14375825/Outpost.zip)

**Comment by tsunamayo** [comment]
@surajnairpv Hi, issue is fixed for 24w11a. Cheers
