### ISSUE TITLE
[Bug] Open world, close world, crash

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#5573]
### Short Description of the issue:
Exiting the game causes a crash.

I've had this happen with every creative and survival world I've opened since 24w08a. Occurrence rate is 100%. It does not appear to cause any lost progress when I open the world again later.

The repro steps can be as simple as "open a world, esc, exit to desktop, crash". You can do other things while the game is open and the game otherwise behaves normally, it doesn't seem to affect whether the crash occurs.

### Steps to reproduce the issue:
1. Open the game, load an existing world, wait for loading to complete (I haven't tested newly created worlds)
2. Optionally do normal things in the world (like move around, build, etc.), but this is entirely optional
3. Press ESC, click "Exit to desktop"
4. Observe that the game crashes before closing

### Environment
- Starship EVO version: 24w08a

### Additional information:
Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14377700/Player.log)
[Crash_2024-02-22_175638776.zip](https://github.com/tsunamayo/Starship-EVO/files/14377732/Crash_2024-02-22_175638776.zip)

**Comment by SovietSponge** [comment]
Noticed this happening too

**Comment by asanagisae** [comment]
A slight amendment. It appears it may actually be preventing save on exit world, at least in some situations.

I closed a gate just prior to exiting (and crashing) earlier today. Visiting the world now, the gate is open again, probably taking the state from an earlier auto-save (the silent ones).

**Comment by tsunamayo** [comment]
@asanagisae Hi, I repushed the build with the fix, it should be all good now. Thanks!
