### ISSUE TITLE
[SurvivalMode] [Query]

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5574]
I noticed that one of the logic bricks called 'Sequencer Gate' is missing from the Assembler building menu.
Is it because that would be available at an advanced stage or some kind of advanced assembler that would be later introduced?
![Starship_EVO_luLGk82Xyw](https://github.com/tsunamayo/Starship-EVO/assets/93534629/57fc4fa3-8ee8-4bd1-85e7-acbbbbe94ce7)

**Comment by tsunamayo** [comment]
@surajnairpv Hi, issue is fixed for 24w10a. Cheers
