### ISSUE TITLE
[Survival Mode] Piston inner stem disappears when coming close

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5575]
### Short Description of the issue:
Piston inner stem disappears when you come close to it
...

### Steps to reproduce the issue:
Place a Piston Mechanism
Extend the pistons
you will see the Pistons disappearing when you come close
...

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

https://github.com/tsunamayo/Starship-EVO/assets/93534629/72d7afd6-ded7-49c7-9d8b-a5838ca01bb4

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14378254/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/14378256/Player-prev.log)
[SpaceSHip.zip](https://github.com/tsunamayo/Starship-EVO/files/14378262/SpaceSHip.zip)

**Comment by surajnairpv** [comment]
Update: the issue has got resolved when the game restarted.

**Comment by tsunamayo** [comment]
@surajnairpv Hi, thanks for the logs. it seems there was a lot of other issues from the log, maybe it had a link. If you see anything strange please book cases again, I am adding more info for the log so it is useful for me to have a look at it. Thanks

**Comment by surajnairpv** [comment]
> @surajnairpv Hi, thanks for the logs. it seems there was a lot of other issues from the log, maybe it had a link. If you see anything strange please book cases again, I am adding more info for the log so it is useful for me to have a look at it. Thanks

Sure will do so 😁👍
