### ISSUE TITLE
[Survival mode] Conveyor does not stop

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5576]
### Short Description of the issue:
Conveyor does not stop even when connected to the switch.
you can see the speed changing as you switch on and off

Second issue:
the iron ingot stuck in the hand is the result of picking up the fallen  ingots as mentioned in #5568
...

### Steps to reproduce the issue:
construct the conveyor
connect it to the switch

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

https://github.com/tsunamayo/Starship-EVO/assets/93534629/57f560a1-c1ed-4a0f-bcff-5f0bdab1ea72

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14378492/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/14378493/Player-prev.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.
[Outpost.zip](https://github.com/tsunamayo/Starship-EVO/files/14378500/Outpost.zip)

**Comment by surajnairpv** [comment]
Update: after a restart of the game this fixed itself

**Comment by tsunamayo** [comment]
@surajnairpv Okay thanks for letting me know.
