### ISSUE TITLE
provoked "destroyed entity"

### ISSUE THREAD

**Issue by Tackietacktack** [tsunamayo/Starship-EVO#5577]
### Short Description of the issue:
i don´t know if it help.

### Steps to reproduce the issue:
build a many starter blocks

https://youtu.be/MZ-k5b9DSJk

can it be ,that the bug have to do with id:1308 and "1757starter block" , the oldest starter blocks is id:1314, "2226starter block" and the next is id: 1309, 2227starterblock.

https://youtu.be/-3ytDu6SVJI

here you have many destroyed entity.
to the end the game crashed and i copy the player.log
Both video are cuts, today I have build a many starter blocks around 3h and I have often spawn destroyed entity. 
did you need the blueprints?

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/14378588/Player-prev.log)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14378585/Player.log)

**Comment by tsunamayo** [comment]
@Tackietacktack Hi, thanks to your help I think I just fixed the issue. For 24w09a. Cheers
