### ISSUE TITLE
Doubts regarding the "Sectors" on the holomap.

### ISSUE THREAD

**Issue by Aranhanauta** [tsunamayo/Starship-EVO#5580]
### Short Description of the issue:

After completing survival mode, I'm wandering the galaxy, and before each warp jump, the target system displays which "sector" it appears in.

I didn't understand how to visualize these "Sectors" on the holomap. If anyone understands how to visualize the sectors on the holomap, I would like to be able to understand.

**Comment by tsunamayo** [comment]
@Aranhanauta Hi, the galaxy is divided into 128x128 grids on horizontal and 4 on the vertical. Each cell or element is a sector. For now you cant visualize that on the galaxy map, but I will add that information. Thanks
