### ISSUE TITLE
[Survivor beta] life support infinite oxygen suppler

### ISSUE THREAD

**Issue by Huttrem** [tsunamayo/Starship-EVO#5582]
### Short Description of the issue:
life support is already full of oxygen went placed first time, also empty the life support and breaking it will make oxygen replenish, would you make oxygen be more consistent in future like no resetting every time we place a block, but that if you open or place anything it his current area it keep looking for breach for scape.
...

### Steps to reproduce the issue:
place life support, wait it for empty or take oxygen with tank, break life support and place again, is full again
...

### Environment
- Starship EVO version: 24w08a
- Graphics Card: 

### Additional information:

Uploading 2024-02-23 12-07-08.mp4…

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Huttrem Hi, yes it is the same with reactor, I need to address this. thx

**Comment by tsunamayo** [comment]
@Huttrem Hi, issue is fixed for 24w09b. Cheers
