### ISSUE TITLE
[Survivor beta] copy item with scroll funtion

### ISSUE THREAD

**Issue by Huttrem** [tsunamayo/Starship-EVO#5584]
### Short Description of the issue:
is possible to replicate certain item with the scroll button function
...

### Steps to reproduce the issue:
use scroll button to pick block, some item will copy making posible to have unlimited of them
...

### Environment
- Starship EVO version: 24w08a
- Graphics Card: 

### Additional information:

https://github.com/tsunamayo/Starship-EVO/assets/159193324/d338a47e-9680-40d3-918d-0cf4dbe78922

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Huttrem Hi, issue is fixed for 24w09b. Cheers
