### ISSUE TITLE
[Survival Beta] 24w08a - Made a destroyed entity

### ISSUE THREAD

**Issue by dean-proca** [tsunamayo/Starship-EVO#5585]
### Short Description of the issue:

Was able to replicate a destroyed entity.

### Steps to reproduce the issue:

Unable to determine exact steps. Appears to occur after several starter blocks are placed.
See full unedited video below. Destroyed entity appears at the very end. Exited to desktop and immediately retrieved log files.
Unedited video included for full context.
Feb 23, 2024 12:00PM GMT -8 : YouTube is still processing the video, roughly 40 minutes until the HD version will be available.

### Environment
- Starship EVO version: 24w08a
- Graphics Card: RTX 3080ti

### Additional information:

https://www.youtube.com/watch?v=RK7pK1S-CBA

[Player_Destroyed.log](https://github.com/tsunamayo/Starship-EVO/files/14389611/Player_Destroyed.log)

[Player-prev_Destroyed.log](https://github.com/tsunamayo/Starship-EVO/files/14389613/Player-prev_Destroyed.log)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@dean-proca Hi, thanks to your help this issue should be fixed for 24w09a. Cheers
