### ISSUE TITLE
[Survival Mode] Assembler stops working when constructing Scrappy hull via Container inventory

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5586]
### Short Description of the issue:
After keeping all the resources( iron ingots and scrap parts)  in a Container connected to the assembler, I started to construct the Scrappy hull , the assembler will not take the scrap parts from the Container inventory so the build does not start.
After canceling the scrappy hull order it won't construct the hull later when you order it
Assembler just stops working
I have to delete the assembler and replace it for it to start constructing hull again.

### Steps to reproduce the issue:
Place all resources in a Container connect it with the assembler.
Order the assembler to construct 10 scrappy hull first
it  won't construct
then cancel the order and now set for 10 hull 
that also won't function despite resources available in the Container 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

https://github.com/tsunamayo/Starship-EVO/assets/93534629/9c640cae-c4cc-46a1-a754-05138bf0e719

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14391980/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/14391981/Player-prev.log)

[Outpost.zip](https://github.com/tsunamayo/Starship-EVO/files/14391976/Outpost.zip)

**Comment by tsunamayo** [comment]
@surajnairpv Great catch, there was actually two separate issues, it is all good now for 24w09c. Cheers
