### ISSUE TITLE
[Survival Beta] 24w08a - Inventory testing, inventory "corruption", crash.

### ISSUE THREAD

**Issue by dean-proca** [tsunamayo/Starship-EVO#5587]
### Short Description of the issue:

Testing and trying to reproduce inventory corruption. Several issues are noted.
1) Items appear to be duplicated, but in fact it looks like pointers to items are mixed up? (Not sure if pointers are used for inventory).
2) Items can be presumably destroyed if items are placed in expanded inventory then the item from the inventory spot that causes expansion/shrinkage is removed.
3) Crash at the end.

I'm fairly confident assemblers can cause this issue if they're rapidly adding and taking things from inventories.

### Steps to reproduce the issue:

Problems seem to be linked to SHIFT + RIGHT CLICK certain items into inventory spots 10 at a time. Will continue testing.

EDIT: By 26:49 when the second and third ingots are shift right clicked into inventory spots ingots are already duplicated and something has gone wrong. If you look very carefully you can see when the second 10 are shift right clicked in both the groups of 10 ingots have blinked a bit. This does not happen other times groups of 10 are being put in the container.

Full unedited video included for context. Please see video starting at 26:00. Link in video description for time of interest.
HD video needs time to process. SD version available until then.

Unintentionally destroying items can be caused by-
Putting an item into the inventory spot that causes inventory expansion.
Place various items into the expanded inventory spots.
Shift click the item in the spot that made inventory expand to collect it to character inventory.
Items should now be destroyed.
Attempt to verify this by expanding inventory again causes a crash.

### Environment
- Starship EVO version: 24w08a
- Graphics Card: RTX 3080ti

### Additional information:

https://www.youtube.com/watch?v=o6puT5wv5kQ

[Player_Inventory01.log](https://github.com/tsunamayo/Starship-EVO/files/14393763/Player_Inventory01.log)

[Player-prev_Inventory01.log](https://github.com/tsunamayo/Starship-EVO/files/14393766/Player-prev_Inventory01.log)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@tsunamayo Thanks a lot for your help, this is really helpful. I can already reproduce a freeze by the look of it - I keep you posted once I fix this!

**Comment by tsunamayo** [comment]
@dean-proca So the issue was SHIFT- click to transfert items. It will be all fixed for 24w09a. Massive thanks for the help on this, the video is extremely useful. They might be more inventory bug related so lets keep our eyes open!
Cheers

**Comment by tsunamayo** [comment]
@dean-proca and to answer your question yes custom pointer are being used, the whole inventory system uses a custom data oriented implementation so it can be used with Unity DOTS tech.
