### ISSUE TITLE
[Survival Beta] 24w08a - Continued inventory testing. Crash

### ISSUE THREAD

**Issue by dean-proca** [tsunamayo/Starship-EVO#5589]
### Short Description of the issue:

Attempting to reproduce the results from #5587 with the same save file yields a crash.

### Steps to reproduce the issue:

Load the save file produced from #5587.
Open cargo container.
Shift right click iron ingots into container to deposit 10 at a time.
When the second stack is attempted, the game locks up. Had to force log out of Windows to stop game (ctrl + alt + del -> log out -> log back in to regain input focus in Windows).

### Environment
- Starship EVO version: 24w08a
- Graphics Card: RTX 3080ti

### Additional information:

https://www.youtube.com/watch?v=0XHJ7AybNEM

Unable to upload original log file. It is ~457MB

![Original_Log_Properties](https://github.com/tsunamayo/Starship-EVO/assets/38061647/d5dc73d9-cae1-4ff1-8301-2e643dc3eafa)

![PlayerLog_Statistics](https://github.com/tsunamayo/Starship-EVO/assets/38061647/285351da-8c64-46e4-9d1f-02d095f4fdd4)

I'll have to upload a modified version where I remove the vast majority of statements which are spammed over and over.
There were no runtime exception trace statements detected in the file. Notepad++ was used to search for "Stacktrace" , "UnityEngine.StackTraceUtility" , and "UnityEngine".

[Player_Inventory02_MODIFIED.log](https://github.com/tsunamayo/Starship-EVO/files/14397512/Player_Inventory02_MODIFIED.log)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by dean-proca** [comment]
@tsunamayo Is it this folder? Let me know if this is ok.

[ds24w08a_InventoryTest.zip](https://github.com/tsunamayo/Starship-EVO/files/14398978/ds24w08a_InventoryTest.zip)

**Comment by tsunamayo** [comment]
@dean-proca Thanks, so issue is fixed for 24w09b.
