### ISSUE TITLE
[24w08a] Tutorial ship sinks into floor when operating hinges

### ISSUE THREAD

**Issue by DrizztCode** [tsunamayo/Starship-EVO#5590]
NOTE: this is probably the same as issue 5571 - but is a specific situation that 2 people raised on Steam - and i then encountered - and also has more specifics about when it happens (issue 5571 says spawned ships start sinking immediately - but my experience was it happens when removing pieces or using hinges) - anyway - apologies if it is too much of a duplicate
------------------------------------------------------

i think it may be an artificial gravity thing

it happened again when i reloaded the game (which ended the tutorial and despawned the repair ship) and spawned in a random ship - and when i started deleting pieces it sank a little for each piece

here is a video of what happened with the tutorial ship
https://www.youtube.com/watch?v=iUysq_pO_Ug

i know you are busy with the survival beta (which i sadly missed) - and so i did not want to bug you with this until that is over - but the Steam mod insisted - and i do what i can to help :-)

i hope the beta is going well - and now that i am back playing the game i am very excited to play the beta when it becomes public - and am enjoying the various new features that have been added since i last played

i am also finding various bugs as usual - and i will endeavour to post them unless you would prefer i hold off - since i am sure you have a lot of systems under work with the survival beta in progress

anyway - i hope everything is going well - and as ever this game continues to be something unique, and special, and overflowing with potential

Many Thanks! :-)

**Comment by tsunamayo** [comment]
@DrizztCode Hi, thanks a lot for booking the case, the issue is now fix for 24w09a. I am pushing the build in a few minutes.

**Comment by DrizztCode** [comment]
> @DrizztCode Hi, thanks a lot for booking the case, the issue is now fix for 24w09a. I am pushing the build in a few minutes.

happy to help :-)

i ran through the whole tutorial and all is working properly

i will have a nice long play when i finish work and report anything i find

thanks for all the awesome work - and i am very excited to try out survival when it becomes public

i assume you are not having any more people join now, since it has been going for several weeks - but if you are looking for more input then i am happy to make sure i play Starship Evo in all of my free time until the beta is complete :-)

either way i will be playing a lot of the default build this week and will report back with any issues

thanks again - and best wishes with all the new features in these exciting times :-)
