### ISSUE TITLE
[24w09a] Helmet Auto Equip Logic Backwards

### ISSUE THREAD

**Issue by DrizztCode** [tsunamayo/Starship-EVO#5592]
i couldn't see another report of this

so - the helmet auto equips when getting near a ship or base, and auto un equips when moving away

here is the vid:
https://www.youtube.com/watch?v=5TbFrh7YOIk

first i just move near and then away - then i stay away and toggle the helmet a few times, leaving it equipped - and then i move near and it plays the equip sound even though it doesn't toggle the helmet (it stays equipped) - and when i move away it auto unequips again

and then i checked with the station

so yeah - logic seems backwards

and once that's sorted we can see about it toggling before the player is actually in a fully oxygenated environment ;-)

thanks again for all the awesomeness :-)

**Comment by tsunamayo** [comment]
@DrizztCode Indeed! Thanks a lot for booking those cases. Issue fixed for 24w09b. Cheers
