### ISSUE TITLE
[Bug?] Connector blocks missing from codex 

### ISSUE THREAD

**Issue by Crimson-Artist** [tsunamayo/Starship-EVO#5595]
This is something that I've noticed awhile back but the 2 large connector blocks that are used in the NPC stations are no longer in the codex. This means we can't use them period. Neither in survival nor creative. Not sure if this is intentional or not but I don't see why they are gone unless it is simple oversight. For context these are the blocks I am talking about.
![Connector hires](https://github.com/tsunamayo/Starship-EVO/assets/112352428/8a057046-027a-425a-9e8b-1eaefca5eb52)
![Connector 3x3 hires](https://github.com/tsunamayo/Starship-EVO/assets/112352428/9433c020-3376-4af9-b54d-fbf803f9801f)

**Comment by tsunamayo** [comment]
@Crimson-Artist Yeah I removed them, they are being replaced by custom docking port, you get to make your own port now. I was never satisfied with that solution.
