### ISSUE TITLE
[survival beta] Fluid problems

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#5599]
I believe this bug/problem is related to fluid in general

my life support shows "empty tank" problem

![image](https://github.com/tsunamayo/Starship-EVO/assets/73253472/7819432a-623b-4487-bbc0-f3b8fae4697b)

And my electrolyzer doesn't produce oxygen and/or hydrogen

![image](https://github.com/tsunamayo/Starship-EVO/assets/73253472/217d9c09-0e84-4719-8873-5a55ea67ff81)
![image](https://github.com/tsunamayo/Starship-EVO/assets/73253472/b54bb2e2-8f36-430e-a2c1-907ba2aa1701)
![image](https://github.com/tsunamayo/Starship-EVO/assets/73253472/75620292-cc0c-4d31-aa5c-9941a174a902)

So I'm stuck at the planet's surface :(

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14411925/Player.log)
[survival 5.zip](https://github.com/tsunamayo/Starship-EVO/files/14411927/survival.5.zip)

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hum I dont see the harvester to pump water. You dont need to put the Electrolyser into the water, but you need a pipe with the harvester underwater. thx

**Comment by Huttrem** [comment]
@tsunamayo 
![Uploading image.png…]()
hey tsuna qwq yo uhavent fix this

**Comment by Uncle-Ulty** [comment]
I forgot to use the fuel harvester, that was the problem.

I believe the "help" tab should have some information about the survival mode

**Comment by surajnairpv** [comment]
@Uncle-Ulty  just incase:
*Construct the fuel scoop in water and set it to collect water.
*Connect the fuel scoop to a tank, set the tank to store water.
*Connect the tank to the electrolyzer.
* Connect the electrolyzer to another tank.
* Set the tank to collect hydrogen or oxygen, or you can construct 2 tanks one collecting hydrogen while the other oxygen.
* Connect them with a power source 

 If you wish to transport the hydrogen or oxygen.
*create a bottle on the assembler.
*Go to the tank and aim at it with the bottle in hand and press R. That will store it in the bottle.
Pressing R again will send the gas back into the tank. 
If you wish to empty the bottle without storing in the tanks, aim anywhere other than the tank to empty the bottle .

Hope this helps 😁

**Comment by tsunamayo** [comment]
> I forgot to use the fuel harvester, that was the problem.
> 
> I believe the "help" tab should have some information about the survival mode

Yes this is of course planned, this phases is also useful for me to see what is confusing and needs good explaining. Bricks description are lacking too.
