### ISSUE TITLE
[Sugg.] Sensitivity of rotators and turrets

### ISSUE THREAD

**Issue by Name11ess** [tsunamayo/Starship-EVO#560]
Hello,

Would that be possible to have a slider somewhere that would allows us to reduce the sensitivity of the rotators? 

Either to allow a better control when making an animation (for landing gears for example, instead of using a timed rotor) or simply to give a feel of heaviness when controlling a turret or any other object.

**Comment by tsunamayo** [comment]
I am not sure to understand what you want to do, it dont seems to be a legitimate test case for turret on ball join. It is made to track object in space, not really for that vectoring thrust (if this is what you want to do here). If you could give more info on what you want to do that would help. Thanks!

**Comment by Name11ess** [comment]
Yeah the post was clearly messy, my bad.

I don't really remember what I meant, so I'll edit the original post to keep the second part, which is the only part that has a sense:

Would that be possible to have a slider somewhere that would allows us to reduce the sensitivity of the rotators?

**Comment by tsunamayo** [comment]
We now have this. Thanks
