### ISSUE TITLE
[24w09b] Can't crouch

### ISSUE THREAD

**Issue by DrizztCode** [tsunamayo/Starship-EVO#5600]
hi - apologies if this one is well known (i did try a search for crouch and didn't see anything recent) - but my player does not seem to want to crouch - i currently have to use the 6 degrees jetpack mode to get to the underside of small landed ships

thanks :-)

**Comment by tsunamayo** [comment]
Yeah there is no crouch atm.

**Comment by tsunamayo** [comment]
I changed the key name, we will see if we really need a crouch key, it is not a stealth game lol
