### ISSUE TITLE
[Survival Beta] 24w09b - Inventory retest. New observations. NullReferenceException and other traces in log.

### ISSUE THREAD

**Issue by dean-proca** [tsunamayo/Starship-EVO#5603]
### Short Description of the issue:

Retesting previous inventory problems with slightly different methods revealed problems.

### Steps to reproduce the issue:

Seems to be right clicking single items into container inventory caused the problem.
Please see video at starting at 39:15. Link to times of interest in video description.

### Environment
- Starship EVO version: 24w09b
- Graphics Card: RTX 3080ti

### Additional information:

https://www.youtube.com/watch?v=wealxm5QgZ8

[Player_Inventory03.log](https://github.com/tsunamayo/Starship-EVO/files/14424895/Player_Inventory03.log)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@dean-proca Thanks it is super useful, especially you recording your play session.
The null ref was fixed, it was just some issue when the game was shutting down.
I can see some error related to terrain props, which might have triggered the later issue.
I keep you posted!

**Comment by tsunamayo** [comment]
nevermind I also reproduce the inventory right click one, I am working on it.

**Comment by tsunamayo** [comment]
@dean-proca Hi, so I think I fixed the issue, not 100% sure as I the second one was really feeling like random. Please tell me if you ever see them again!
