### ISSUE TITLE
[Bug] Action Wheel SFX are not affected by the Game Volume Slider

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#5605]
### Short Description of the issue:
Even with Game Volume set to 0, the SFX when you select an option in the Action Wheel still play at full volume

### Steps to reproduce the issue:
- Set Game Volume to 0
- Use the Action Wheel

![image](https://github.com/tsunamayo/Starship-EVO/assets/27857711/12e50362-11a8-4c43-a2d9-d4497d0d6c61)
![image](https://github.com/tsunamayo/Starship-EVO/assets/27857711/d931f62a-9039-4a69-b157-fca6309cb462)

### Environment
- Starship EVO version: 24w09b
- Graphics Card: RX6700XT

**Comment by tsunamayo** [comment]
@ProPeach Indeed, it is fixed for 24w09c. Thanks !
