### ISSUE TITLE
[Question] Is The Survival Beta Accepting New Players?

### ISSUE THREAD

**Issue by DrizztCode** [tsunamayo/Starship-EVO#5606]
I just wanted to ask since i missed the opening of the beta, and have instead been playing with the survival features on the standard game. And i have feedback on a lot of those features - but i assume a lot of it will be out of date or somewhat nullified by what is happening in the beta.

To clarify i am playing with finite oxygen, finite fuel, crafting requiring resources and i am only salvaging scrap from wrecks (since salvaging parts makes things too easy since there are currently a lot of wrecks - and even with fewer, a player would just need a simple ship to get to one pretty quick, presuming they are on a planet with them - so i guess it would make sense for the player to start with the only nearby wrecks being just hull fragments)

i am also only using the jump pack on planets (only using jet pack to rotate to place things on the underside of stuff - due to no crouch lol)

so anyway - with all of that - i was able to get into space and find some crystals and build a lightcruise engine and get to the sun for refuelling reasonably quickly - utilising the jump pack to get to ore patches, and collecting the necessary ores (100 or so of each, with extra iron and a bunch of scrap - presumably this will be less possible with a finite inventory) before setting up base on the beach and smelting everything down, and assembling parts, and gathering fuel and making my ship

and while the trip to the asteroid ring was quite long - it wasn't insanely long - and i was only going at 100m/s or so, so with a few more thrusters i could have likely got there in a 3rd of the time

i noticed the beta post talking about it taking 2 mins - and i seem to recall another post where you said you have shrunk things down for survival - so i am wondering how that went down - since like i say on the standard build it was not unbearable to get to an asteroid even at 100m/s - so did you shrink things down for the standard game already? or is it even smaller in the survival mode?

anyway - i don't want to meander too far off the point here - since the main question is:  can i possibly get in on the beta please? :-)

and if not (which i totally understand, since you may have decided on a limit by time or number of participants etc) - do you have a feel for how long you expect the closed beta to continue for?

since if it is only a few more weeks then that is a short time to wait before i can offer any feedback - but if you expect it to stretch to months then i will be rather sad that i will have missed the opportunity to provide feedback on what is arguably my favourite kind of gameplay, during the stages when you may be making big changes based on player feedback - and many of which will be somewhat locked in by the time you release the mode to the public

however - i am sure you have many veteran players of many space survival and building games, as well as veterans of this game giving you plenty of feedback - in addition to your own experience and judgement

but obviously we all have our own perspectives and different players will focus on different aspects etc, so it's possible that every extra set of eyes, hands and brain may help :-)

anyway - i figured i would ask up front - since the original beta post is 3 or 4 pages back now

and whatever happens - i am excited for the public release of the survival mode, and i hope the beta is going well

many thanks for all the awesome work :-)

**Comment by tsunamayo** [comment]
@DrizztCode Hi, sure give me your steam player id!

**Comment by DrizztCode** [comment]
> @DrizztCode Hi, sure give me your steam player id!

awesome! thanks! :-)
76561197977040058

(guess i'm gonna be late for work tomorrow lol :-))

**Comment by DrizztCode** [comment]
> @DrizztCode You are added, now you can book me some nice cases ^^

Challenge Accepted! :-)

Thanks again :-)
