### ISSUE TITLE
[Survival Mode] Receiving damage when not fully submerged in water

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5607]
### Short Description of the issue:
Moved to a new planet, built the starter block.
had issues with placing it previously, it was just not getting placed.
then restarted the game, which allowed me to place the starter block.
now as I am building on water, I am receiving damage when I am not fully submerged in water

### Additional information:

https://github.com/tsunamayo/Starship-EVO/assets/93534629/9d074c4c-5081-4248-8837-f353505c2173

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14429720/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/14429721/Player-prev.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by Crimson-Artist** [comment]
had the same thing happen to me. The game thinks you are submerged in water and is treating it like you are suffocating. Putting your helmet on fixes this but we need a warning when we are taking suffocation damage

**Comment by tsunamayo** [comment]
@surajnairpv Hi, issue is fixed for 24w09c. Cheers
