### ISSUE TITLE
[Survival Mode] Assembler stops working

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5608]
### Short Description of the issue:
Its a lot better than the last time, the assembler stops when you stack about 30+ or 40+ more items
### Steps to reproduce the issue:
Start stacking up to do builds in the assembler

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

https://github.com/tsunamayo/Starship-EVO/assets/93534629/5a22ab15-2b06-42d4-a0f5-ca9de8c84019

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14430081/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/14430082/Player-prev.log)

[Hydragen station.zip](https://github.com/tsunamayo/Starship-EVO/files/14430090/Hydragen.station.zip)

**Comment by tsunamayo** [comment]
@surajnairpv Hi, I have plenty of fix for assembler in the upcoming release, lets see how it works with those. Thanks
