### ISSUE TITLE
[Survival Mode] Assemblers can't work simultaneously ( repeated issue #5581)

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5610]
### Short Description of the issue:
Came back to the same issue #5581 where the assemblers won't work together 
As suggested I placed a bigger piping and kept it independent but connected to 1 container.
should the containers also be independent for this to work?

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

https://github.com/tsunamayo/Starship-EVO/assets/93534629/05a827f3-4eb7-4fb7-8d56-beeb2a316993

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14432897/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/14432899/Player-prev.log)
[Hydragen station.zip](https://github.com/tsunamayo/Starship-EVO/files/14432908/Hydragen.station.zip)

**Comment by surajnairpv** [comment]
After restrating the game the issue gets fixed, but again comes back later after 1 hr  of play time.

**Comment by tsunamayo** [comment]
@surajnairpv Hi, I have plenty of fix for assembler in the upcoming release, lets see how it works with those. Thanks
