### ISSUE TITLE
[Survival Mode] Shield status display not aligned with shape of Display monitor 

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5611]
### Short Description of the issue:
The status details of the shield appear in another angle  when you connect the monitor to the shield.
...

### Steps to reproduce the issue:
Make the monitor shape based on the below screen shot and connect it with the shield
![20240228212657_1](https://github.com/tsunamayo/Starship-EVO/assets/93534629/6fb26681-e886-4424-89c9-448a45ad283a)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14436643/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/14436644/Player-prev.log)
[SpaceSHip.zip](https://github.com/tsunamayo/Starship-EVO/files/14436661/SpaceSHip.zip)

**Comment by tsunamayo** [comment]
Yes this is still wip, it needs a total refactor. thx
