### ISSUE TITLE
[Survival Beta] 24w09c - [Suggestion] Allow assemblers to build assemblers.

### ISSUE THREAD

**Issue by dean-proca** [tsunamayo/Starship-EVO#5614]
### Short Description of the issue:

Only a workbench can build an assembler.

### Steps to reproduce the issue:

Interact with an assembler and try to build an assembler.
See video at 35:22.

### Environment
- Starship EVO version: 24w09c
- Graphics Card: RTX 3080ti

### Additional information:

https://www.youtube.com/watch?v=Xa05IBeTY38

[Player_24w09c_InventoryRetest01.log](https://github.com/tsunamayo/Starship-EVO/files/14442540/Player_24w09c_InventoryRetest01.log)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@dean-proca Hi, issue is fixed for 24w10a. Cheers
