### ISSUE TITLE
[Survival Mode] Entity Starts floating in air when you edit them with the starter block

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5617]
### Short Description of the issue:
was working on a new hovercraft.
started with the starter block so that the entity remains frozen in place while i work on it.
after a few alterations ( deleting blocks and creating new ones)
the entity unfreezes an begins to float.

### Steps to reproduce the issue:
create an entity with the starter block.
start creating and deleting the blocks eventually it will start to fall then float around.

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

https://github.com/tsunamayo/Starship-EVO/assets/93534629/bc78bc2a-972d-430b-9edf-6469d42b1604

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14450889/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/14450890/Player-prev.log)

I had later deleted the entity without saving so no blueprint.

**Comment by Tackietacktack** [comment]
Is the same like this #5433

**Comment by tsunamayo** [comment]
@surajnairpv Yes they are only supposed to cancel gravity. It seems it is confusing, maybe I should remove that feature...

**Comment by ProPeach** [comment]
Is it possible that the item floating towards the player when you break the hull blocks is impacting the ship and nudging it? 

We definitely need some way of keeping a ship airborne when working on it... Have you considered allowing ships to hover under their own power even after you exit the yoke @tsunamayo? Games like Space Engineers do this, then you can power down the thrusters when you land so it drops freely

**Comment by surajnairpv** [comment]
Yes I agree with @ProPeach we need some way of keeping the ships afloat when working on gravity.
I do understand the scaffolding idea of building  mentioned in #5618.
Yet to try out the mag lock and piston combo if that can help lift up the entity while constructing

**Comment by Tackietacktack** [comment]
Hmm, before the beta it has worked. You could change the position from starterblock and if you push this entity it move 10 seconds and stand.
But now, when you change a starterblock the entity move by every brick which you build. Like in the videos.

**Comment by surajnairpv** [comment]
Just to give an update on this, this setup works quite well for lifting up your builds to work on it.

https://github.com/tsunamayo/Starship-EVO/assets/93534629/5cc2b82f-aa28-42d6-aa23-0f27d2ddd92c
