### ISSUE TITLE
[Survival Beta] 24w09c: Items get stuck in hand till reload

### ISSUE THREAD

**Issue by DrizztCode** [tsunamayo/Starship-EVO#5619]
Hi!
My first bug report since joining the beta :-)

i shall show it first:
![20240229141134_1](https://github.com/tsunamayo/Starship-EVO/assets/104569043/ddc32263-a0de-4b49-bd20-8d38b0835aa7)
![20240228132227_1](https://github.com/tsunamayo/Starship-EVO/assets/104569043/e1f88fc4-8025-41ad-8f47-2a7980bc6fab)

so - this happens when items get launched with the menu open by shift clicking a slot or clicking with a stack in your hand in some empty space

also it manifests when two other bugs happen - one where shift clicking does not transfer between inventories, and the other where you click on an empty slot with a stack in your hand and it behaves like it is not there (someone mentioned they thought it was coz the player slightly misses, but i am pretty sure i have had it happen when dead on, while also not happening when i deliberately click between slots)

also i think it only affects non tools items - i.e. items that replace the tool and are held by the player (so not blocks since they are projected by the tool)
so ingots, ores, components etc

### Steps to recreate
1. have a stack of items that are not projected by the tool
2. open the menu and shift click them (or pick them up and manually click on empty space) to throw the stack
3. pick one or more of them up again
4. equip something else

et voila - multiple equipped items (visually, can't actually use the glitched one)

this is one of the various bugs that disappears after a reload

thanks :-)

**Comment by tsunamayo** [comment]
@DrizztCode Hi, thanks for booking the case, could you share the player.log as explained when creating a new case? Thanks

**Comment by DrizztCode** [comment]
> @DrizztCode Hi, thanks for booking the case, could you share the player.log as explained when creating a new case? Thanks

absolutely - here is the log from a new survival game where i picked up a couple of rocks, threw them away with the shift click, picked one up, and then it was stuck on me: 
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14454704/Player.log)
![20240229235219_1](https://github.com/tsunamayo/Starship-EVO/assets/104569043/d18e9339-1f99-418d-b3cf-ba7231096c57)

**Comment by DrizztCode** [comment]
additional note - i just had it happen on my current game when i did not do the throwing
so it may even happen when things get transferred into the toolbar to the currently equipped slot - but i will need to do some more tests to replicate it

either way - here is the log for where it just happened with some gold, probably when i shift clicked to move it from the crucible to the toolbar:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14471208/Player.log)

**Comment by dean-proca** [comment]
@tsunamayo
I reproduced this accidentally in this video:
https://www.youtube.com/watch?v=0WPFFYxU1Fc
At 14:40.

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14475816/Player.log)

**Comment by tsunamayo** [comment]
@DrizztCode Hi, thanks a lot for the case, it is now finally fixed. Cheers!
