### ISSUE TITLE
[Survival Mode] Missing Curved hulls

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5623]
### Short Description of the issue:
Don't know if its for a reason but it seems the curved hull block are missing from the assembler's building menu.
...

### Steps to reproduce the issue:
open up the assemble build menu

![brave_jMUAOmYXL2](https://github.com/tsunamayo/Starship-EVO/assets/93534629/929c74e6-794d-4836-9060-f7eb4f875ca4)
![Starship_EVO_g6cGNYNhzh](https://github.com/tsunamayo/Starship-EVO/assets/93534629/b80fcd83-246f-4a46-8f96-014ec12f560e)

...

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14463543/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/14463545/Player-prev.log)

**Comment by tsunamayo** [comment]
@surajnairpv Hi, the first 2 shapes are added for 24w10a. The last one is already present, it is bundled with the bevel. Cheers
