### ISSUE TITLE
Ships bounce when landing on space station

### ISSUE THREAD

**Issue by MattJohno3** [tsunamayo/Starship-EVO#5627]
### Short Description of the issue:
Spacecraft seem to bounce when landing on the station, it may be caused by uneven landing legs on the ship, although trying to land via artificial gravity also causes this issue. Planetary landings are fine for me. Attached is a short clip. 
...

### Steps to reproduce the issue:

...

https://github.com/tsunamayo/Starship-EVO/assets/161900993/386bd14a-e027-45ea-92b6-7fe7af8ec0c4

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by surajnairpv** [comment]
Yes it will be difficult when doing it manually, why don't you try to request landing with the station. It will auto dock your ship.
Have the station selected by cycling selection with R, then press F and select 'request Landing' . this will select the dock that fits your ship by surrounding it with the selection brackets, then  fly your ship and move closer to the selected dock and the auto dock will automatically turn your ship if required and dock your ship.

**Comment by MattJohno3** [comment]
> Yes that bounce is quite a lot, it will be difficult when trying to land it manually, I try to request landing with the station. It will auto dock your ship.

I did that in this clip. I was just pointing out that it also happens without autopilot, as if the ship gets thrown off every time it makes contact.
