### ISSUE TITLE
[Survival Beta] 24w09c - Can't shift click to transfer to/from some inventories (particularly backpack)

### ISSUE THREAD

**Issue by DrizztCode** [tsunamayo/Starship-EVO#5630]
so as the title says - this is particularly prevalent with the backpack, where shift clicking an item in the backpack always throws the stack (which can lead to issue #5619)

it will also happen when trying to transfer to the backpack from the toolbar when in the backpack screen in the Tab menu

i have also had it happen sometimes when trying to transfer items from the toolbar into machines - but i can't confirm the exact circumstances for that one

i would suggest preventing shift click from throwing from the inventory screens - limiting a stack throw to being executed by having the stack in the player's hand and them clicking in empty space

that would at least prevent the throwing when people try to transfer in a way that the game does not allow (which in some cases is currently sensible, since there can be more than 2 inventories open at the same time, meaning the transfer target can be ambiguous)

and then maybe if there are more than 2 inventories open that could accept the item shift-clicked, always transfer to the last inventory that was clicked on - basically the players "activates" an inventory by interacting with it - and the active inventory is always the default target for a shift click if it can accept the shift clicked item

thanks for all the great work :-)

**Comment by tsunamayo** [comment]
@DrizztCode Hi, issue is fixed for 24w10a. Cheers

**Comment by DrizztCode** [comment]
> @DrizztCode Hi, issue is fixed for 24w10a. Cheers

awesome! :-)
