### ISSUE TITLE
[Survival Beta] 24w09c - Bug - Floating Land

### ISSUE THREAD

**Issue by DrizztCode** [tsunamayo/Starship-EVO#5633]
![20240302235318_1](https://github.com/tsunamayo/Starship-EVO/assets/104569043/3072d69c-b212-4c04-a5c6-fa08496857d3)
here is the log:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14471109/Player.log)
and the save (i continued from the previous one with the floating trees):
[Drizzt24w09c_05_Survival.zip](https://github.com/tsunamayo/Starship-EVO/files/14471110/Drizzt24w09c_05_Survival.zip)
thanks :-)

**Comment by tsunamayo** [comment]
@DrizztCode Well unfortunately due to the nature of the beast it will always happens to some degree.

**Comment by DrizztCode** [comment]
> @DrizztCode Well unfortunately due to the nature of the beast it will always happens to some degree.

understood! :-)
