### ISSUE TITLE
[Suggestion] Require ships to have at least one thruster in all 6 directions

### ISSUE THREAD

**Issue by DrizztCode** [tsunamayo/Starship-EVO#5634]
Since the ships currently have permanent inertial dampening - it seems sensible to require any ship to have at least one thruster for each direction where thrust would be needed to keep the ship still.

wow - i finally kept a suggestion short and sweet! :-)

thanks :-)

**Comment by tsunamayo** [comment]
@DrizztCode Hum that is not planned, I think I dont want the game to be realistic, and it would break also all the current blueprint, so it is no longer an option!

**Comment by DrizztCode** [comment]
> @DrizztCode Hum that is not planned, I think I dont want the game to be realistic, and it would break also all the current blueprint, so it is no longer an option!

all good - i shall just make it a rule for myself that i am not allowed to fly a ship unless it has all the thrusters! ;-)

thanks for all the awesomeness :-)
