### ISSUE TITLE
[Survival Beta] 24w09c - Bug - deconstructing destroys any items in block's inventory

### ISSUE THREAD

**Issue by DrizztCode** [tsunamayo/Starship-EVO#5635]
as title says - if we right click (with a held block) any object with an inventory we lose all of the inventory forever (tested with assembler and container just now, have seen with crucible - assume is the same for all blocks with inventory)

since we can't quick save or that kind of thing, one misclick on a container could lose hours (or more) of items

i can see the logic of not wanting to try to move all the inventory to the player (since that could cause issues)

so maybe prevent the player from deconstructing any block with a non empty inventory?
with a message telling them what happened - maybe even with a yes/no dialog to go ahead anyway? (allowing the player to destroy unwanted items)

thanks :-)

**Comment by tsunamayo** [comment]
@DrizztCode Hi, issue is fixed for 24w10a. Cheers

**Comment by DrizztCode** [comment]
> @DrizztCode Hi, issue is fixed for 24w10a. Cheers

cool :-)
