### ISSUE TITLE
[Survival Beta] Suggestion - Add a "depressurize" command to the life support

### ISSUE THREAD

**Issue by DrizztCode** [tsunamayo/Starship-EVO#5638]
as the title says - this would allow the life support to suck the air back out of the pressurized space (and would only work in a pressurized space) - saving the O2 and allowing for proper airlocks - instead of losing the air when we open the door

thanks :-)

**Comment by tsunamayo** [comment]
@DrizztCode Hi, what do you mean a command? How would that work?

**Comment by DrizztCode** [comment]
> @DrizztCode Hi, what do you mean a command? How would that work?

so when we select the Life Support with F it could have a drop down that select "Pressurize" or "Depressurise" - and we could link that to a switch and then we have an airlock :-)
(and if the tank is full then either the life support sucks up and loses the extra air - or it just says "Tank Full" and we have to vent the air when we open the door - or we could even play around with tanks if we are desperate to save every drop lol)

**Comment by tsunamayo** [comment]
well the part where you link a switch to an option / feature of a command is just simply something that does not exists in the game.
Beside this is not how life-support works. If your room is 100m3 it wont empty 100m3 from tank of oxygen once it replenish, it will empty 0. Only over time the drain starts to occur. That is less punishing, so dont worry about that!

**Comment by DrizztCode** [comment]
> well the part where you link a switch to an option / feature of a command is just simply something that does not exists in the game.
i was thinking of it the way we can link a switch to a door or a laser - so when we flip the switch it flips the life support unit between pressurizing and depressurizing

> Beside this is not how life-support works. If your room is 100m3 it wont empty 100m3 from tank of oxygen once it replenish, it will empty 0. Only over time the drain starts to occur. That is less punishing, so dont worry about that!

ok - so for sure i do not know how the internals of the system work lol :-)
i have only tried with small rooms, and certainly it does not seem like the O2 runs down too quickly even with lots of EVAs letting a cabin full of O2 into space :-)

i do think it would be a good feature for immersion though - especially if players are on long voyages where they haven't found a planet with water for a while, and start to run out of oxygen - then they will be invested in saving every drop of the stuff! :-)

plus i think players will appreciate having actual airlocks on their ships

but for sure it is not an urgent need! :-)
especially if the unit is very generous about its O2 usage

definitely more important that it is consistent in detecting the current airtightness state :-)

thanks for taking the time to discuss this :-)
