### ISSUE TITLE
[Survival Beta] Suggestion - Can we have hoses please? Pretty Please? :-)

### ISSUE THREAD

**Issue by DrizztCode** [tsunamayo/Starship-EVO#5640]
hi - i am sure hoses provide a bit of a problem when it comes to deciding how to determine how many to use from a block count perspective, since they can twist and bend, and likely their length is not calculated the same as for other blocks

so i totally understand that they may well be last in the queue for being added

but i just wanted to mention them - because i love them :-)

thanks for everything - very excited to see what comes next :-)

**Comment by tsunamayo** [comment]
Hi, yes sorry I have many block still to add. thx

**Comment by DrizztCode** [comment]
> Hi, yes sorry I have many block still to add. thx

all good - whatever pace you move at is cool :-)

i just wanted to mention hoses because
a) i love them :-)
and
b) they are so much easier to hook up in various situations where getting the pipes in the right place is a hassle

but most importantly they are really really cool ;-)

thanks for all the awesome work :-)

**Comment by tsunamayo** [comment]
@DrizztCode Hi, issue is fixed for 24w10a. Cheers

**Comment by DrizztCode** [comment]
awesome :-)
