### ISSUE TITLE
[Survival Beta] Suggestion - Allow engines to be drained

### ISSUE THREAD

**Issue by DrizztCode** [tsunamayo/Starship-EVO#5641]
so if we want to rebuild our engines we lose all the fuel in them

would be good to be able to set an engine to drain, which would have it push fuel to any block with spare fuel space in the same fuel network (that isn't also set to drain)

thanks :-)

**Comment by tsunamayo** [comment]
Hi, I dont see how I could to do that, that seems too specific to spend time making this work. At first there is no fuel in the engine when you design it. Later in the game fuel is cheap, seems like a no issue to me. thx

**Comment by DrizztCode** [comment]
> Hi, I dont see how I could to do that, that seems too specific to spend time making this work. At first there is no fuel in the engine when you design it. Later in the game fuel is cheap, seems like a no issue to me. thx

fair enough yes - i think not even if/when the survival gets deeper and the early stages last a little longer - since in the early stages we are on a planet with water - and in the later stages we will either be heading for the star or a station for fuel

so yes - is a suggestion for a more punishing kind of survival where fuel is more valuable

so not something for now - maybe in a few years when we have lots of configuration options for the mode and can make things really hard lol ;-)

thanks :-)
