### ISSUE TITLE
Invisible Ships

### ISSUE THREAD

**Issue by Dolan-online** [tsunamayo/Starship-EVO#5642]
### Short Description of the issue:

...

Blueprints spawning invisible, lights and collisions only but no textures. Can be tossed around via the Anti-Grav Tool but phases through any other entities. Blocks can be deleted from the ship but any added also turn invisible. The entity vanishes completely upon world reload

Issue appears same as https://github.com/tsunamayo/Starship-EVO/issues/5424

### Steps to reproduce the issue:

... 

Spawn the ship blueprint attached below

### Environment
- Starship EVO version: 24w09c
- Graphics Card: NVIDIA GeForce RTX 2070

### Additional information:

![20240303203746_1](https://github.com/tsunamayo/Starship-EVO/assets/159722427/c03a21ae-ee43-4dfc-b34f-b533261b3806)

Ship preview still appears

![20240303203729_1](https://github.com/tsunamayo/Starship-EVO/assets/159722427/fe9f2166-854e-4264-9c87-2fecbefd3694)

What it's supposed to look like (slightly older pic)

![20240217223536_1](https://github.com/tsunamayo/Starship-EVO/assets/159722427/a6f148bd-5f9f-4362-969b-3200c90bdb6a)

The blueprint shared below (890) is an identical copy of backup blueprint (865) saved within seconds of the other with both experiencing the same bug (in case saving in rapid succession is what has been breaking   them). The previous backup (860) spawns normally

![blueprints](https://github.com/tsunamayo/Starship-EVO/assets/159722427/c144d873-ba7d-4964-91f7-f9acb1da1214)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14475572/Player.log)
[CZRN Strike Cruiser 890.zip](https://github.com/tsunamayo/Starship-EVO/files/14475576/CZRN.Strike.Cruiser.890.zip)

**Comment by tsunamayo** [comment]
@Dolan-online Hey Nolan welcome here! Mindblowing stuff as always.
Issue is fixed for the upcoming 24w10a.
Cheers

**Comment by Dolan-online** [comment]
Awesome! Thank you very much for the update!
