### ISSUE TITLE
[Survival Beta] 24w09c - Expanded assembler inventory spaces are not removed

### ISSUE THREAD

**Issue by dean-proca** [tsunamayo/Starship-EVO#5643]
### Short Description of the issue:

While trying to reproduce #5624, manually expanded assembler inventory with iron ingots.
When last iron ingot is used by the assembler, expanded inventory spaces are not removed.

### Steps to reproduce the issue:

Assuming construction of an item that takes iron ingots.
Place an iron ingot in the last row to expand inventory space.
Place an iron ingot in expanded inventory space somewhere beyond the first expanded spot.
When the assembler uses all iron ingots in inventory the expanded spaces are not removed.
See video at 8:13.
Several other observations are noted in video description.
Some observations in log file:
circular reference spotted
warning invalid container links
Infinite loop detected

### Environment
- Starship EVO version: 24w09c
- Graphics Card: RTX 3080ti

### Additional information:

https://youtu.be/3gvrM1FgpBk

[Player_AssemblerTest_InventoryManipulation.log](https://github.com/tsunamayo/Starship-EVO/files/14476278/Player_AssemblerTest_InventoryManipulation.log)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@dean-proca Hi, issue is fixed for 24w11a. Thanks
