### ISSUE TITLE
[Survival Beta] Feedback - I like the screen shake when taking damage

### ISSUE THREAD

**Issue by DrizztCode** [tsunamayo/Starship-EVO#5644]
just wanted to mention - is very useful when playing without sound - especially helps avoiding suffocating while messing around outside fitting pretty lights to the reactors ;-)
(pic taken when returning after the warning shakes sent me diving back into the control room :-))
![20240304185100_1](https://github.com/tsunamayo/Starship-EVO/assets/104569043/130bf1c3-6e14-4fc6-ab5e-09a24d69b750)

and yes - i am aware that my building skills are tiny lol ;-)
but look at this nice airtight control room - how very functional ;-)
![20240304185415_1](https://github.com/tsunamayo/Starship-EVO/assets/104569043/33c8823d-0783-45da-8a27-3f5bccfba8ad)

also - i just noticed that my shadow is not wearing a helmet...... ;-)

**Comment by DrizztCode** [comment]
but as it turns out the shadow helmet is there in 3rd person....
![20240304192556_1](https://github.com/tsunamayo/Starship-EVO/assets/104569043/2394eacf-b0ea-4e98-a6db-9ec549772cbc)
maybe i shall raise this one - but not exactly an urgent one lol :-)

**Comment by tsunamayo** [comment]
@DrizztCode Thanks for the feedback
