### ISSUE TITLE
Codex crafting, schematics disappeared

### ISSUE THREAD

**Issue by Tackietacktack** [tsunamayo/Starship-EVO#5647]
### Short Description of the issue:

![Screenshot 2024-03-07 174426](https://github.com/tsunamayo/Starship-EVO/assets/97230091/24f4db6b-90b0-499a-a686-0c8db8cc4c84)

you can only craft a starterblock and and the crafting menu say i have 24124 starterblock in my  bag.

### Environment
- Starship EVO version: 24w10a
- Graphics Card:

**Comment by tsunamayo** [comment]
@Tackietacktack Indeed, the issue is now fixed, I pushed the build already. Thanks
