### ISSUE TITLE
[Beta Survival] build back from wreck, Bricks hold their color in hotbar

### ISSUE THREAD

**Issue by Tackietacktack** [tsunamayo/Starship-EVO#5648]
### Short Description of the issue:
I don't know if you wanted to do it.

build back weapons, lightcruise or switch from wreck. in your hotbar it has their own color.
you can change the color if you painting it befor build back.

![Screenshot 2024-03-07 175543](https://github.com/tsunamayo/Starship-EVO/assets/97230091/fbd65693-53f4-46c8-85ac-a9cb3b942d03)

### Environment
- Starship EVO version: 24w10a
- Graphics Card:

**Comment by tsunamayo** [comment]
@Tackietacktack Hi, but you are able to interact with the wreck? I cant do it. Can you send me your world at this location?

**Comment by Tackietacktack** [comment]
I can send it, but it was a new started survival world. In creative mode it doesn't work.

**Comment by Tackietacktack** [comment]
jet, i can´t build back from wrecks.

https://github.com/tsunamayo/Starship-EVO/assets/97230091/5081b5f8-778e-4710-a481-98c9fc7410b9

look at the item color in the hotbar from the beam first blue, than yellow.

some screenshot from the hotbar because in the video is the video timeline in front of it

![Screenshot 2024-03-08 170805](https://github.com/tsunamayo/Starship-EVO/assets/97230091/148933a8-3a08-4018-aa52-b6150aaa370d)


![Screenshot 2024-03-08 170852](https://github.com/tsunamayo/Starship-EVO/assets/97230091/ee273ca9-755d-445d-b2a0-d447f19a0f21)

![Screenshot 2024-03-08 170926](https://github.com/tsunamayo/Starship-EVO/assets/97230091/0da91343-7005-4715-9120-af8ff479198f)

charakter save:

[survivaler.zip](https://github.com/tsunamayo/Starship-EVO/files/14540343/survivaler.zip)

**Comment by tsunamayo** [comment]
@Tackietacktack I see now! Issue fixed for 24w11a. Cheers
