### ISSUE TITLE
[Bug] Force-field forgets its last known state after restarting the game

### ISSUE THREAD

**Issue by Pawnp** [tsunamayo/Starship-EVO#5649]
### Short Description of the issue:

Force-fields that were toggled off will turn back on after exiting and starting up the game.

### Steps to reproduce the issue:

1. Build a force-field generator and a switch
2. Connect the switch to the force-field and turn it off
3. Exit the game and re-enter
4. Examine

### Environment
- Starship EVO version: 24w010a

**Comment by tsunamayo** [comment]
@Pawnp Hi, issue is fixed for 24w11a. Cheers
