### ISSUE TITLE
[Bug] Force-field beams become obstructed by parallel walls

### ISSUE THREAD

**Issue by Pawnp** [tsunamayo/Starship-EVO#5650]
### Short Description of the issue:

Force-field beams that are beside parallel blocks can get caught on the block despite there being no obstruction. However this obstruction only occurs on a single side of the field while the other side behaves normally.

![image](https://github.com/tsunamayo/Starship-EVO/assets/72423251/4d9f3e93-7bf3-47ef-a4aa-0230d3808f4a)

Other points to note are:

If the parallel block extends from behind the field projector the obstruction does not occur
> ![image](https://github.com/tsunamayo/Starship-EVO/assets/72423251/4e840c6d-c230-4347-9112-142af6f8e242)

The issue is not consistent and occasionally behaves normally on different spots of an entity despite having identical conditions
> ![image](https://github.com/tsunamayo/Starship-EVO/assets/72423251/38f34ec6-0d89-414f-8b14-ff690d9fb54c)

If the blocks around the force-field are messed around enough the one side of the force-field does not project at all
>![image](https://github.com/tsunamayo/Starship-EVO/assets/72423251/e79b255f-3344-47d2-b95e-9bb50300bfb2)

Similar to issue #5406

### Steps to reproduce the issue:

1. Place a force-field projector
2. Place blocks parallel to the field but not extending from behind the projector
3. Examine

Or download the blueprint from below and examine

### Environment
- Starship EVO version: 24w010a

### Additional information:

[Blueprint Link](https://drive.google.com/file/d/1LIrF7UYoRt8h61fJso9UldQloapB-Mlr/view?usp=sharing)

**Comment by tsunamayo** [comment]
@Pawnp Hi, issue is fixed for 24w11a. Cheers
