### ISSUE TITLE
Antenna fails to mirror when using symmetry 

### ISSUE THREAD

**Issue by drimmel247** [tsunamayo/Starship-EVO#5651]
### Short Description of the issue:

**When placing Antennas down with symmetry turned on the other locations will still be in the same orientation and not be the mirrored version.** 

### Steps to reproduce the issue:

**1. Place down a block and set symmetry tool for both x and y axis of the flat block. I always put the symmetry at the center point. 
2. place down antenna on the corner with symmetry on 
3. review the view of the other antennas.** 

### Environment
- Starship EVO version: **24w10a**
- Graphics Card: **3060** 

### Additional information:

**Please feel free to test on my station. Though it occurs on other blueprints besides this and think this is just a general issue occurring on all entities.** 

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

![20240307190729_1](https://github.com/tsunamayo/Starship-EVO/assets/32307665/6f0a8db0-fb2e-4917-a260-2b64b29a58c1)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14531555/Player.log)

[guardian Station.zip](https://github.com/tsunamayo/Starship-EVO/files/14531570/guardian.Station.zip)

**Comment by tsunamayo** [comment]
@drimmel247 Hi, issue is fixed for 24w11a. thanks
