### ISSUE TITLE
[steam bug] New achievement ? !

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#5653]
I believe there is something wrong here...

The new achievement lacks a proper name

![image](https://github.com/tsunamayo/Starship-EVO/assets/73253472/337f8554-93dd-4c3c-abbf-b6a176d201c1)

**Comment by Aranhanauta** [comment]
I saw this too

**Comment by tsunamayo** [comment]
@Uncle-Ulty Well it is just a test for now. thx
