### ISSUE TITLE
[crash report] The game crashes with a specific build

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#5654]
Hi Tsuna

The game crashes in creative mode when I pilot a specific build: Highwind airship replica

I believe it's related to "boost" mode...

Since the FFVIIR release I'm feeling nostalgic and playing with this replica that took me 4 months to build

![image](https://github.com/tsunamayo/Starship-EVO/assets/73253472/0cf9d290-1cc3-4a69-8d74-9b3c083e7f5c)

GTX 1660
version: creative, current one

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14538580/Player.log)
[Highwind rebirth.zip](https://github.com/tsunamayo/Starship-EVO/files/14538584/Highwind.rebirth.zip)
[HIGHWIND - Final Fantasy VII Airship.zip](https://github.com/tsunamayo/Starship-EVO/files/14538594/HIGHWIND.-.Final.Fantasy.VII.Airship.zip)

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hi, actually this issue was fixed in experimental. Thanks
