### ISSUE TITLE
Suggestion : Find gold easier 

### ISSUE THREAD

**Issue by Tackietacktack** [tsunamayo/Starship-EVO#5655]
Did you have thinking about, to made Gold deposits very smaller so that we get 20-50 pieces from one Gold deposits and it give the same chance for Gold deposits in relation to iron, silver,....? 
Is it understandable what I mean?

**Comment by Huttrem** [comment]
@Tackietacktack he mentioned a scan to find ores easier, so went he got time will add it

**Comment by Tackietacktack** [comment]
I know, but do we have the scanner at the beginning? Or do we need gold to build it?
