### ISSUE TITLE
"Part of Survival closed beta test" but unable to create Survival world

### ISSUE THREAD

**Issue by Asnro** [tsunamayo/Starship-EVO#5660]
I have the red "Part of Survival closed beta test" text on the bottom left of my menu screen but am unable to create a Survival world. Clicking the game mode button in character creation does nothing.

**Comment by tsunamayo** [comment]
@Asnro Hi, was it working before? Thanks

**Comment by Asnro** [comment]
No, yesterday was the first time I saw the notification and tried to create a survival game. I asked on Discord and was told by other players how accessing survival should work, but had no luck.

**Comment by tsunamayo** [comment]
@Asnro Are you connected to internet and steam?

**Comment by Asnro** [comment]
I have port 7777 open on TCP and UDP, but cannot confirm if it works in game. I assumed the notification only shows up because I am online?

**Comment by tsunamayo** [comment]
@Asnro Can you send me a player.log file? thanks

**Comment by Asnro** [comment]
[Player.zip](https://github.com/tsunamayo/Starship-EVO/files/14594911/Player.zip)

**Comment by tsunamayo** [comment]
@Asnro Hi, you did not gave me the right steam id, I have just uploaded your id, tell me if it is good now!

**Comment by Asnro** [comment]
Hi, it works now! Sorry for giving the wrong ID, thanks for being patient with me!
