### ISSUE TITLE
Question - When will the Mark Book option be working in the game?

### ISSUE THREAD

**Issue by Aranhanauta** [tsunamayo/Starship-EVO#5662]
### Short Description of the issue:

Hello, I'm doing an expedition through the Statship Evo galaxy, and I have no way of knowing which star systems I've been to, and finding my home system is very difficult, as I have to look from system to system by name.

I know that efforts are now focused on other areas of the game, but I would just like to know a stipulated forecast of when this function will be available.

Thank you very much in advance.

**Comment by tsunamayo** [comment]
@Aranhanauta as soon as I get a more stable and polished survival experience I will do a big pass on the space side of the game.

**Comment by Aranhanauta** [comment]
Thank you.
