### ISSUE TITLE
[Survival Mode] No friction, Character doesn't move along with Moving platform

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5663]
### Short Description of the issue:
Created a Moving platform in order to construct a Landing pad for my ship.
But when the platform moves my character stays in 1 place
...

### Steps to reproduce the issue:
Create a Moving platform with rails on your base

https://github.com/tsunamayo/Starship-EVO/assets/93534629/0d8e9b88-6264-4298-9bc0-28652e2317f7

[Hydrogen Base.zip](https://github.com/tsunamayo/Starship-EVO/files/14576695/Hydrogen.Base.zip)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14576696/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/14576697/Player-prev.log)

`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@surajnairpv Hi, this will be implemented for 24w11a. Cheers
