### ISSUE TITLE
Change in heat and power values

### ISSUE THREAD

**Issue by Sithware** [tsunamayo/Starship-EVO#5672]
### Short Description of the issue:

Ships that previously were fully functional and under their maximum heat and power capacity are now above capacity and thus non-functional. 

### Steps to reproduce the issue:

This occured when updating to the latest version as these ships were under capacity when i built them last week.

### Environment
- Starship EVO version: 24w011b
- Graphics Card: Nvidia Geforce GTX 1060

### Player log
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14612921/Player.log)

I believe this to be a deliberate nerf, but I will report it anyway since I do not agree with it especially as it breaks carefully optimised ships built before the latest updates.

**Comment by tsunamayo** [comment]
@Sithware Hi, nope I didnt change anything, it must be a bug. Can you send me your ship in question?

**Comment by Sithware** [comment]
Well, it happened to more than this ship(file attached) including some from the workshop. On my machine it's above capacity in both heat and power, when it was below on both accounts during construction.

[Copperdrop pleasure ship.zip](https://github.com/tsunamayo/Starship-EVO/files/14647501/Copperdrop.pleasure.ship.zip)

**Comment by tsunamayo** [comment]
@Sithware How much below?

**Comment by Sithware** [comment]
~5-10%,if my memory serves me right.

**Comment by Tackietacktack** [comment]
Can it be, that it is the same like this #5685 and  the problem came from life support or electrolyser?

**Comment by tsunamayo** [comment]
![image](https://github.com/tsunamayo/Starship-EVO/assets/6604318/c71473e0-e352-4362-9382-406ba9d528de)
@Sithware Well I went on an loaded your ship with an older build, it is the same.
By the look of it it really has too much systems crammed on for such a small body.
I will let you fix it ;)
Cheers

**Comment by ProPeach** [comment]
Heat and power load can sometimes be quite high when you first spawn a ship in while it charges its shields, perhaps that is what you were seeing @Sithware? The levels should drop down to normal once the shields are charged, perhaps newly spawned ships could start with their shields full to avoid this surge
