### ISSUE TITLE
Starting block does not align with gravity well

### ISSUE THREAD

**Issue by Sithware** [tsunamayo/Starship-EVO#5673]
### Short Description of the issue:

When placing a starting block, the block does not align itself with the current gravity well correctly. 

### Steps to reproduce the issue:

1. Go into a world.
2. Place starting block

### Environment
- Starship EVO version: 24w011b
- Graphics Card: Nvidia Geforce GTX 1060

### Additional information:

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14613044/Player.log)

This issue has occured both near stations and planets.

**Comment by Xerma** [comment]
I have this too, seems that it's rotation is based on a global rotation and not based on the player rotation. The preview shows what the correct rotation should be, until you place it

**Comment by Sithware** [comment]
>The preview shows what the correct rotation should be, until you place it

I forgot to mention this, but the exact same thing occured in my game.

**Comment by Tisdag1** [comment]
I have also been having this issue.

**Comment by tsunamayo** [comment]
@Sithware Hi, issue is fixed for 24w12a. Cheers
