### ISSUE TITLE
[Survival Mode] Ship disappears when getting off the seat

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5675]
### Short Description of the issue:
When I get off the ship after flying for some time the ship disappears. I tried restarting the game but still faced with this bug

...

### Steps to reproduce the issue:
Have a look at the video.
Guessing the mechanics with the seat does not work well.

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

https://github.com/tsunamayo/Starship-EVO/assets/93534629/1b1d6532-447e-4a47-a003-8bd0c7190d64

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14624165/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/14624166/Player-prev.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

[SpaceSHip.zip](https://github.com/tsunamayo/Starship-EVO/files/14624180/SpaceSHip.zip)

**Comment by Tackietacktack** [comment]
same by me

**Comment by tsunamayo** [comment]
@surajnairpv Hi, issue will be fixed for 24w12a. Cheers
