### ISSUE TITLE
I can't enter the game after installing the new video card.

### ISSUE THREAD

**Issue by Aranhanauta** [tsunamayo/Starship-EVO#5677]
### Short Description of the issue:

I installed a new video card in my computer and now I can't play the game, it doesn't leave the initial screen, no commands are responded to.

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 24w011b
- Graphics Card: GTX550Ti Graphics Card, 4GB

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Aranhanauta Hi, can you send the player.log file as requested? This GFX card seems below the minimum spec unfortunately. What was the previous GFX card, and how many FPS did you did back then?
 Thanks

**Comment by Aranhanauta** [comment]
My previous graphics card was an integrated AMD Radeon HD 8370D.

My game ran at a minimum of 4 frames per second and a maximum of 17.

**Comment by Aranhanauta** [comment]
The driver for this video card is from 2018, I can't update it any further than that.

**Comment by Aranhanauta** [comment]
I couldn't find %User Profile%

**Comment by ProPeach** [comment]
> I couldn't find %User Profile%

That means your profile, whatever that name is 

You can copy and paste this >
%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\
Into this box to get you to the folder
![image](https://github.com/tsunamayo/Starship-EVO/assets/27857711/33e45566-c3c3-416a-95b9-8aabb745f196)

**Comment by Aranhanauta** [comment]
I uninstalled the video card and returned to the old one, and the game started running normally again, the error actually seems to be with the new video card.

**Comment by tsunamayo** [comment]
@Aranhanauta Yes, unfortunately both your GFX cards are under the minimum spec.

**Comment by Aranhanauta** [comment]
Ok, thank you.
