### ISSUE TITLE
Hovercraft Hover Pod Bug?

### ISSUE THREAD

**Issue by Tisdag1** [tsunamayo/Starship-EVO#5678]
### Short Description of the issue:

I built a hovercraft today for the first time in survival. Built 4 hover pods to put on it. But when I placed the first pod I noticed that it took all 4 pods just to place the smallest size pod. So I took it off, got and got all 4 back. Went and had 4 more made for a total of 8. Again placed the hover pod but made it twice the size & it used up all 8 for just the one hover pod. I had to do that for all four pods on the hovercraft.

So, there are 4 smallish hover pods on the bottom of the hovercraft (two on each side), but I had to make 32 hover pods total to build those 4 small pods.

Wasn't sure if I was missing something, as I really don't do much with the hovercrafts. (they are the next size up from the smallest)

### Steps to reproduce the issue:

Build hover pods & place them on a hovercraft.

### Environment
Version 24w11b

### Additional information:
![711980_20240319023917_1](https://github.com/tsunamayo/Starship-EVO/assets/95005604/0d431e26-bb64-4557-b6f0-35cb841b3a1f)

_(Screenshots, Videos, Error logs, Related issue

Please also include the `Player.log` file. You
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14647656/Player.log)
 can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by Tisdag1** [comment]
My apologies. I don't know why it's showing up so small. I have taken several and they are all small, bad quality pics.

**Comment by tsunamayo** [comment]
@Tisdag1 Hi, I cant reproduce what you are describing. Could you record a video if you are able to reproduce that issue? Thanks

**Comment by Tisdag1** [comment]
Hmmm... Oddly, it seems to have worked itself out. I am no longer having the issue. I don't have a way to record a video, but maybe these really rough pictures will help.

![Single Pod](https://github.com/tsunamayo/Starship-EVO/assets/95005604/60b1ac4a-ba78-4d3b-a9e4-5abde574e9e2)
The issue that I was having was that one pod wasn't enough to place the single 1x1x1 pod on the hovercraft. The ghost image was red, indicating that I did not have enough pods. I built 4 pods. One for each corner of the hovercraft. But when I placed the first one on the hovercraft, it used up all 4 pods, instead of just one.

![4 Pod](https://github.com/tsunamayo/Starship-EVO/assets/95005604/b1c4a520-8832-40a8-a23c-7fc7d911fa02)
I needed a stack of 4 pods for the ghost image to turn white, indicating that I had enough to place it. It also used up all 4 pods when I placed the smallest 1x1x1 size. And when I removed the pod, I got all 4 back into my inventory. Also, I think the part that says [x1/4] was showing up as [x4/4]<---( With the second 4 just being the quantity I have available in inventory to use.)

![8 Pod](https://github.com/tsunamayo/Starship-EVO/assets/95005604/8e7a535b-24a6-4e4a-bc4f-0e3d9bcd74fc)
This image shows that it is using the correct amount of 8 pods to build the next size up of 2x2x2.

But oddly enough, I am no longer having that problem. As you can see in the photos, everything looks like it should, with one pod being enough to build the small 1x1x1 pod. (As apposed to the 4 that I was needing before.)

**Comment by tsunamayo** [comment]
@Tisdag1 Okay thanks for the details.
