### ISSUE TITLE
[Spelling] Steam Achievements - Hovercraft Enthusiast

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#5679]
### Short Description of the issue:

Just a spelling mistake on the Steam achievements. The second word is spelled incorrectly in English. It should be:

Hovercraft Enthusiast

![image](https://github.com/tsunamayo/Starship-EVO/assets/10069469/47f7936f-0213-43e3-8bad-056f9d0423d5)

I don't think the Steam Achievements are linked to a specific build of the game, but it happened shortly after 24w11b was made available in the experimental branch.

Can't wait to start earning these, btw. 😃

**Comment by tsunamayo** [comment]
@asanagisae Fixed, thanks. Btw I will likely changed this name, it is a bit bland. Cheers

**Comment by asanagisae** [comment]
Sometimes brilliant ideas come much later.

I wasn't sure if there was an intended pun that I just didn't get, and the spelling was actually "correct".

But also, since it's an easy achievement, it might be ok to be a little bland.
