### ISSUE TITLE
[Bug] [Survival] Planet vanished

### ISSUE THREAD

**Issue by Asnro** [tsunamayo/Starship-EVO#5680]
### Short Description of the issue:

I was working on a starter base in survival, when I suddenly found myself floating in space. Trying to teleport back to base with the "Teleport to any entity" option showed the baase was gone, or at least nott visible in list of entities. I assume the planet and all entities on it vanished, but do not know for sure.

### Steps to reproduce the issue:

Unknown

### Environment
- Starship EVO version: 24w11b
- Graphics Card: RTX4090

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Player&Player-prev.zip](https://github.com/tsunamayo/Starship-EVO/files/14692034/Player.Player-prev.zip)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Asnro Hi, this will be fixed for 24w14a. Cheers
