### ISSUE TITLE
energy problem with life support system

### ISSUE THREAD

**Issue by Tackietacktack** [tsunamayo/Starship-EVO#5685]
### Short Description of the issue:

if you install a life support system you get a very high power draw.
problem is by ships and hover but by ships its very heavy.

same problem  is if you use electrolyser on a ship.

### Steps to reproduce the issue:

look at the video the stats says:
heat: 49%
power:20%

but the power draw is too high i can´t fly

https://github.com/tsunamayo/Starship-EVO/assets/97230091/e17596ec-e592-4182-a1bf-a84867f5a978

### Environment
- Starship EVO version: 24w11b
- Graphics Card:

**Comment by tsunamayo** [comment]
@Tackietacktack Well in case like that I really need your blueprint to see if there is something wrong. Thanks

**Comment by Tackietacktack** [comment]
[life support.zip](https://github.com/tsunamayo/Starship-EVO/files/14761611/life.support.zip)
here is the blueprint

**Comment by tsunamayo** [comment]
@Tackietacktack Btw I havent had a look at it yet but electrolyser have a very high power consumption, they are not really made for ship, as ships can simply refuel nearby stars for h2.

**Comment by tsunamayo** [comment]
@Tackietacktack Hi, issue is fixed for 24w13a. Cheers
