### ISSUE TITLE
[Survival Mode] Getting blasted out to space, from my hovercraft seat

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5689]
### Short Description of the issue:
Was driving the  Hovercraft around and after that I switched of the reactor, get off the Yoke, reverse the seat back so that I can come out easily and right when I have to get off the seat I get sent into space. This bug was there in the previous version also. Didn't report it as it was similar to my previous report #5675.

### Steps to reproduce the issue:
As mentioned above, I suspect mechanisms with seat causes this. 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

https://github.com/tsunamayo/Starship-EVO/assets/93534629/3a9d9de0-e933-4092-a106-5f34852aebe3

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14775611/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/14775613/Player-prev.log)

**Comment by tsunamayo** [comment]
@surajnairpv Hi, as always when it is related to a particular build can you send me the blueprint so I can reproduce? Thanks

**Comment by surajnairpv** [comment]
sure here it is 
[Transport Truck.zip](https://github.com/tsunamayo/Starship-EVO/files/14790795/Transport.Truck.zip)

**Comment by tsunamayo** [comment]
@surajnairpv Great, issue is fixed for 24w14a. Cheers
