### ISSUE TITLE
Can't get off the drive menu?

### ISSUE THREAD

**Issue by DragonCalme** [tsunamayo/Starship-EVO#5691]
In two words, I can't get off the TAB menu while flying.
(Drive Warp menu).
Is this normal? 
Regards, Dragon.

**Comment by tsunamayo** [comment]
@DragonCalme, Hi could you send the player.log as explained when creating a case? Thanks

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
@DragonCalme Hi, what menu are you talking about? The galaxy map where you assign your warp target, or the in-flight command, where you can get the warp going? Thanks
