### ISSUE TITLE
[Survival Mode] BUG: Shaking during idle animation on moving platform. SUGGESTION: can we add speed control on the sliding rails?

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5693]
### Short Description of the issue:
Trying to create a space elevator, as I go up and down on the elevator platform the character shakes a lot in third person. It does not shake during walking animations.

### Steps to reproduce the issue:
Build an elevator with Sliding rail

### Additional information:

https://github.com/tsunamayo/Starship-EVO/assets/93534629/eef241b7-20db-4433-9653-cd02c513a40e

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14807284/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/14807286/Player-prev.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

[HydroBase.zip](https://github.com/tsunamayo/Starship-EVO/files/14807361/HydroBase.zip)

**Suggestion:**
Can we add speed control on the sliding rails so I can make the elevator travel faster?
...

**Comment by tsunamayo** [comment]
@surajnairpv Hi, issue is fixed for 24w14a. Cheers
