### ISSUE TITLE
Random teleport of character after piloting bug (ship specific?)

### ISSUE THREAD

**Issue by kynamats** [tsunamayo/Starship-EVO#5694]
### Short Description of the issue:
Flew a ship around for 20mins (in an oldish world), went into freeview to land, accidentally pressed boost - craft was rotated upside down and all orientation controls locked out. I then got out of the ship to try and solve this, and was immediately teleported to the edge of the system. Manually teleported back to buildyard, to another ship in the same area, and as soon as I got close, got teleported again, although this time not to the edge of the system. Exited and recorded playerlog at this point.

Rebooted game and tried to replicate, this time was teleported beyond the edge of the system (no visible planets or sun) with a 'ghost' of the ship I was flying, rendering every other frame. Exited to record playerlog, found this short 3min play session had produced a 244MB log (!) so unable to share.

Rebooted again, found that it was blueprint specific (https://steamcommunity.com/sharedfiles/filedetails/?id=2884188563)
Playerlog again a reasonable size.
...

### Steps to reproduce the issue:
enter freeview while flying the ship, press boost & get rotated, then stop flying, get out of the seat & get teleported
...

### Environment
- Starship EVO version: 24w13a
- Graphics Card: 3070ti

### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14808422/Player.log) - first instance
 second try to identify caused 244MB player log from 3 minutes of play....
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14808623/Player.log) - third instance

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@kynamats Hi, actually I fixed this yesterday, will be in in next patch. Thanks
