### ISSUE TITLE
[Suggestions] Minor achievement corrections

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#5698]
### Short Description of the issue:
I've been playing on the main branch exclusively. Now that achievements are available outside of the experimental branch, a few things stood out.

**Green Energy**
A minor grammar change specific to English: "a" should be "an" when preceding a word that starts with a vowel. Result:
```
Produce 1000 e/s on an entity with only wind or solar.
```

**Industrialized**
The achievement text says it requires a "crate", but I got the achievement using "containers". Does this achievement trigger also on "wooden crates"? If not, would it help to reword this?

**Home Sweet Home**
The achievement text says it requires a "furnace". The arc furnace did not trigger the achievement, but a crucible did. Perhaps the achievement text should say "crucible" instead?

----

In general, I'd say the achievements are a success. Most of them are straight-forward and take relatively little time investment: _or so it seems._ Once you start, you lose track of time as you attempt to solve puzzles one after another.

It would be nice to have the "Global Achievements" stats working to know how many other players have gotten the same achievements we have and how we rank in the world. That feeling when you're instantly better than 5% of the world just by completing this _one_ achievement: it's incredibly addictive.

### Environment
- Starship EVO version: 24w014a

**Comment by tsunamayo** [comment]
@asanagisae Hi, thanks I fixed the text. There is global achievements in the steam UI, but not in the game. Was your comment requesting them to be visible in game? Or just implemented? Thanks

**Comment by asanagisae** [comment]
![image](https://github.com/tsunamayo/Starship-EVO/assets/10069469/cca79ae4-c5b2-499c-a84e-502603881fd4)

The Steam built-in global achievements are fine. However, it seems that for some reason, it isn't reporting any other players having earned any of the achievements. Usually, it'll sort this list by the number of players who earned them, with the "easiest" ones at the top and the rarest ones at the bottom.

![image](https://github.com/tsunamayo/Starship-EVO/assets/10069469/0852d2eb-62e4-4f09-8ce4-a9521216ff83)

I haven't worked with achievements from the game development side before. Is there any additional reporting you need to do to have the totals appear?

**Comment by tsunamayo** [comment]
@asanagisae Nope lol it is because nobody earned those yet, the percentage are minuscule as those are survival only. thx
