### ISSUE TITLE
[Suggestion] Better painting tool and more material/color options. 

### ISSUE THREAD

**Issue by CoasterBlock** [tsunamayo/Starship-EVO#5699]
In SEVO you can paint brick-by-brick, so repaining large surfaces or an entire ship can be quite difficult. My suggestion is to add a better method or "modes" or painting an entity. 

You would be able to "cycle" the regular paint tool with the middle mouse button, it would allow you to switch between following modes:

**Modes:**

1. "Normal" Mode: Paint brick-by-brick 
2. "Surface" Mode: Paint a 2x2 to 16x16 brick area around the targeted brick. If you use 16m bricks, the paint tool will scale the area accordingly. 
3. "Cover" Mode: Paint the entirey entity in one color or material.
4. "Adjecent" Only paint what is next to (x/y axis) or above or below (z axis) to the targeted brick. 
5. "Connections" Fully paint all connected pipes, hoses and tanks with one color. This would make pipe organisation much easier
6. etc
Alternatively, you could set the "base paint" for the whole entity in the TAB menu of the entity. It would ONLY affect bricks, NOT glass, windows, or glowing/decorative/machinery bricks. Only Hulls and related bricks. 

**Filters:** 
Just like toggeling symmetry or other functions, the paint tool would now also be able to "include" or "exclude" certain bricks. 
Settings for the filter would include:

1. "Light filter" Only paint lights or bricks that have emissive textures such as certain hose and pipe times, lamps and glow-bricks. 
2. "Hoses" Only paint hoses
3. "Functional" Only paint functional bricks such as the mechanisms.
4. "Brick" Only paint certain bricks specifically (slopes/slabs/blocks etc)
5. etc

**Materials:** 
There would now be more materials to choose from.  Materials would also be able to have their color changed. So metal could be any color and retain its sheen. 

1. Regular metals (already in the game)
2. Wood
3. Stone, (Brick, Slabs, Tiles, Mosaics)
4. Grass
7. Liquid 
8. Metal surfaces, scratched, polished, dented, matt, etc.
9. Plastic
10. Chrome
11. Fabric
12. etc

**Comment by tsunamayo** [comment]
@CoasterBlock Hi, sorry to shit down such a well written suggestion, but unfortunately it is not compatible with the technology as we no longer use voxel. Using automatic decal placement for that  also could trigger some performance issues.
Cheers
