### ISSUE TITLE
[SURVIVAL] Turret Issues.

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5700]
### Short Description of the issue:
I have created a panel that holds all the logics of the turret so I can keep them hidden away, but for some reason I cannot connect the yoke to the turret computer.
I have also created some turret unfolding  logics as well but these mechanics are separate from the turret logics.
Let me know if this is something to be worked at or I am doing something wrong

### Steps to reproduce the issue:
Create a folding turret that unfolds when activated.
...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

**This is the Folding/unfolding logics at work**
https://github.com/tsunamayo/Starship-EVO/assets/93534629/65f5d957-92fe-4f11-b176-35d3a15aecba

**This is the turret logics at work but cant connect the yoke**
https://github.com/tsunamayo/Starship-EVO/assets/93534629/d063e2f2-e31d-498d-b234-a71fa586572c

...

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14893278/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/14893279/Player-prev.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.
[Starship.zip](https://github.com/tsunamayo/Starship-EVO/files/14893287/Starship.zip)

**Comment by surajnairpv** [comment]
Update: I shifted the turret computer by placing it on the turret itself, that allowed the yoke to get connected but the Turret cannot be controlled ( it does not move despite assigning both the axis.
The turret recognizes the second axis only if the pointer is assigned( in this the camera).
Have a look at the vids below

https://github.com/tsunamayo/Starship-EVO/assets/93534629/4286fde8-904e-4b92-a500-7ab2bb6480ef
Here you can clearly see after assigning the second axis it only recognizes when you set a pointer.


https://github.com/tsunamayo/Starship-EVO/assets/93534629/757b60f3-ac68-4447-9532-2317a25eec78
In this case I have connect all the logics but cannot move or control the turret.

**Comment by TIKIRobo** [comment]
so first, unlink that switch to the turret core, the core is only allow one in signal. second make sure you have power, without it the turret can't move. if that doesn't help it could just be that the turret is bugged

hope that helps!

**Comment by surajnairpv** [comment]
@TIKIRobo I didn't get which switch you mentioned to unlink is it that folding unfolding switch?
Yeah will try adding a power source as you suggested and check.
Thanks for replying.

**Comment by TIKIRobo** [comment]
@surajnairpv in the second video you can see a switch linked to the turret core
![image](https://github.com/tsunamayo/Starship-EVO/assets/56371294/23319b88-c67a-4289-9cb6-0fbe01bcf754)
nothing can be linked to the core except for the yoke

**Comment by surajnairpv** [comment]
@TIKIRobo thanks for screenshot.
 Currently was working on the frame of the ship that holds a big fuel tank.
I had placed solar panels and unlinked the switch as well but the turret still doesn't move.
Will try filling up the tank and connect with the reactors and try again.

**Comment by TIKIRobo** [comment]
yeah no problem, if it ends up being a power issue awesome, but at this point i think its probably just a bug

**Comment by surajnairpv** [comment]
@TIKIRobo I have some hydrogen fuel, a big reactor generating the power( big reactor not just for the turret, planning some other stuff as well) along with solar panels but still no movement on the turret. Here is the video for this setup

https://github.com/tsunamayo/Starship-EVO/assets/93534629/55a71686-5895-4049-8415-3be1309402e8

Now will try rebuilding the turret as per @Tackietacktack suggestion. Will update here once its setup.

**Comment by surajnairpv** [comment]
@Tackietacktack @TIKIRobo  It worked!!! thanks a lot. 
Here is the folding turret.

https://github.com/tsunamayo/Starship-EVO/assets/93534629/3871fade-3344-47f8-a333-2e545ff3c189
