### ISSUE TITLE
[BUG} Significant performance drop when looking in a specific direction.

### ISSUE THREAD

**Issue by CoasterBlock** [tsunamayo/Starship-EVO#5702]
### Short Description of the issue:

Regardless of ship size, when near a ship or grid, the performance of the game goes down significantly when looking in a particular direction. Its so severe that the game becomes unplayble quiokly. However, it seems the ship needs to have child entities present. 

### Steps to reproduce the issue:

Spawn a ship
get close to ship or enter
Look around
You may notice a performance drop when looking into a specific cardinal direction

### Environment
- Starship EVO version: Latest Experimental
- Graphics Card: RTX 2080 Super

### Additional information:
This seems to concern entities with hinges. It also affects entities regardless of size or complexity, and regardless if near or far from a planet. However, it is inconsistent, sometimes the bug occurs sometimes it does not. I have not found the reason why this is. It does become more common the longer the play session lasts.

**Comment by COMICLER** [comment]
Im having this one too

**Comment by tsunamayo** [comment]
@CoasterBlock @COMICLER  Well I dont reproduce this, can you send me a character save looking in the offending direction? thanks

**Comment by tsunamayo** [comment]
@CoasterBlock Actually I have just reproduced that, it seems GPU related. It is pretty bad I will fix it asap!

**Comment by tsunamayo** [comment]
@COMICLER @CoasterBlock So the issue is fixed for 24w15a. I will push the build asap.
