### ISSUE TITLE
[Query] Is there a way to have multiple monitors connected to 1 tank?

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5704]
I am creating a ship that has 3 floors, I want to have 2 floors with monitors showing the fuel/oxygen information but only 1 monitor can get connected to 1 tank.

If that is not possible could it be added as a feature?
thanks

**Comment by tsunamayo** [comment]
@surajnairpv Hi, implemented for 24w16a. Cheers
