### ISSUE TITLE
Trees can't be harvested

### ISSUE THREAD

**Issue by Tisdag1** [tsunamayo/Starship-EVO#5707]
### Short Description of the issue:

Trees can no longer be harvested

### Steps to reproduce the issue:

Equip the mining tool and try harvesting a tree

### Environment
- Starship EVO version: 24w15a
- Graphics Card: 

### Additional information:

https://github.com/tsunamayo/Starship-EVO/assets/95005604/768f1ccf-8d66-4559-b134-97ba5fdc3360

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/14940313/Player-prev.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by Uncle-Ulty** [comment]
I have the same problem.


[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14998234/Player.log)

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hi, issue is fixed in 24w18b. Cheers
