### ISSUE TITLE
Issue when starting a new game (Memory 0x000000000000000F9 cannot be read.)

### ISSUE THREAD

**Issue by masalaempire** [tsunamayo/Starship-EVO#5708]
### Short Description of the issue:
When I try to start a new game, the game loads fine for like 10 seconds and I see a nice artwork. But, after that, the game just freezes and blacks out. Then, this annoying error box just pops out and says some 0x something memory is using/pointing 0x0000000000000000F9 and that memory cannot be 'read'. 

### Steps to reproduce the issue:
Load the game

### Environment
- Starship EVO version: 24w15a
- Graphics Card: Intel integrated CPU. 

### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14958681/Player.log)

**Comment by tsunamayo** [comment]
@masalaempire I am sorry by the look of it it seems that your GPU is not powerful enough. What chip is it actually? Integrated GPU are rarely up to the task.
