### ISSUE TITLE
[BUG] Crashes when trying to Boost, LC or Warp. 

### ISSUE THREAD

**Issue by CoasterBlock** [tsunamayo/Starship-EVO#5709]
### Short Description of the issue:

This is a collective bug report. When trying to fly a ship, the game crashes upon pressing the boost key (tab) or the LC key. It also happens when trying to warp to a new system.

### Steps to reproduce the issue:

Spawn a ship
Enter the ships controls
try to boost, light cruise or warp.
The game will crash. 

Alternatively:
Select a destination in the holomap and select it in the F menu in your ship.
try to boost or LC
The game will likely crash.

### Environment
- Starship EVO version: Latest experimental build. 24w015a Experimental
- Graphics Card: 2080 Super

### Additional information:

This is happening regardless of ship size or complexity. It also doessnt seem to depend if youre close to a planet or a station.
The crash often happens when you have a destination selected for warp, but try to boost or lightcruie instead. 

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by asanagisae** [comment]
As of a few builds ago, I've seen this error quite frequently (more than half the time?). I learned to never boost or LC from a standstill, as a workaround.

In 24w15a [default], I only ran into this issue once (in a deliberate attempt to reproduce the above and contribute to this issue). However, once I got OBS ready to record the issue occurring, I started getting the issues described in #5711 exclusively.

**Comment by tsunamayo** [comment]
@CoasterBlock Hi, is the problem only happening when boosting from a standstill? I never got crash while boosting or warping. Thanks

**Comment by tsunamayo** [comment]
@CoasterBlock Yep I just confirmed I dont reproduce at all. As always I need a log file and in this case a ship or a world so I can investigate. Thanks!

**Comment by asanagisae** [comment]
Heya Tsuna, another player ran into the "press tab and crash immediately" bug. It may affect certain ships more than others.

They tried this ship from the workshop:
https://steamcommunity.com/workshop/filedetails/?id=3219823598

I also tried this ship. First time loading it in a world and pressing tab from standstill, the game crashes.
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14998689/Player.log)

**Comment by tsunamayo** [comment]
@CoasterBlock @asanagisae Hi, do you still reproduce this in the current build? Thanks

**Comment by asanagisae** [comment]
Hello @tsunamayo, the issue appears to be resolved in 24w17a. Boosting or using LC from standstill and using F4 does not crash the game. The controls also do not lock up anymore (the other issue). Cheers! \o/

**Comment by tsunamayo** [comment]
@asanagisae Hi, cool thanks for the update!
