### ISSUE TITLE
[Bug] Boost turns craft in "random" direction and locks turning

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#5711]
### Short Description of the issue:

When you press "boost" from a standstill, the ship immediately changes its direction and rotation before moving.

When you stop boosting, the mouse is no longer able to steer the ship. The side thrusters are still powered and the ship is able to strafe. There does not appear to be any issues with power fluctuation, which is the usual culprit for a ship becoming unresponsive.

The direction and rotation the ship ends up in appears to always be the same, perhaps based on the world's XYZ axis? However, to the user, it will almost never be what's expected.

In the current build, the reproduction rate of the bug appears to be 100% if the steps are followed.

I believe the same issue occurs when initiating Lightcruise from a standstill.

### Steps to reproduce the issue:

1. Note the orientation of your ship relative to the world.
2. Take control of the ship.
3. From standstill, press the key to toggle boost (tab by default)
4. Note that your ship's orientation has changed randomly.
5. Stop boosting.
6. Note that moving the mouse no longer steers your ship.

### Environment
- Starship EVO version: 24w15a [default]
- It may be important to note that this is tested in Creative mode

### Additional information:

https://github.com/tsunamayo/Starship-EVO/assets/10069469/c0393967-b417-4e10-94ee-a3c36b05923b

0:00 - Note the ship orientation relative to the other structures.
0:03 - The ship turns when I move the mouse, as expected.
0:05 - I press boost and immediately stop boost. The ship direction has changed upon initiating boost.
0:07 to 0:11 - I move my mouse around but I cannot turn the ship.
0:14 - I leave the ship. Note that the ship orientation has clearly changed without my intervention (moving the mouse).

The world below appears to facilitate the bug reliably:

[Bug Testing.zip](https://github.com/tsunamayo/Starship-EVO/files/14967954/Bug.Testing.zip)

**Comment by CoasterBlock** [comment]
I encountered this bug as well. Sometimes respawning the ship can fix it.

**Comment by tsunamayo** [comment]
@asanagisae Hi, issue is fixed for 24w16a. Cheers
