### ISSUE TITLE
fuel tanks dont save use settings

### ISSUE THREAD

**Issue by king32109** [tsunamayo/Starship-EVO#5713]
### Short Description of the issue:
the tanks for fuel do not save the use status, if i set a tank to only have reactor fuel it auto goes back to reactor and engines
...

### Steps to reproduce the issue:
place tanks press F on it and change from reactor and egines to something else leave and go back in to see its still on reactor and engines
...

### Environment
- Starship EVO version: 24w15a
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@king32109 Hi, thanks for booking the issue. Fixed for 24w16a. Cheers
