### ISSUE TITLE
[bug] Windows defender is blocking Starship EVO

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#5714]
### Short Description of the issue:
 When I try to start Starship Evo the windows Defender blocks the application and puts it into quarantine.
...

### Steps to reproduce the issue:

starts Starship EVO
...

### Environment
- Starship EVO version: current one: 24w015a
- Graphics Card: gtx1660
-win 10 home basic

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![image](https://github.com/tsunamayo/Starship-EVO/assets/73253472/783283e2-ffa8-4af6-a284-9c6f22f84d14)
![image](https://github.com/tsunamayo/Starship-EVO/assets/73253472/f83e9500-b42e-4444-87db-aec0a0b4241b)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by ProPeach** [comment]
I've seen this happen to a few other players recently, you definitely see the odd instance happen but it's been more common in the last 2 weeks perhaps.

Generally it seems that Steam games often get false positives like this, you can search around and people just suggest making an exception for the .exe file in the antivirus setting as it's nothing to worry about. It's just a bit strange that there has been an increase in this happening recently

**Comment by asanagisae** [comment]
Could it be that the executable is reaching out to a game server with our Steam ID to verify if we're part of the survival beta, and this call out to the internet is being flagged by the antivirus as potentially malicious?

**Comment by Uncle-Ulty** [comment]
> I've seen this happen to a few other players recently, you definitely see the odd instance happen but it's been more common in the last 2 weeks perhaps.
> 
> Generally it seems that Steam games often get false positives like this, you can search around and people just suggest making an exception for the .exe file in the antivirus setting as it's nothing to worry about. It's just a bit strange that there has been an increase in this happening recently

Thanks, gonna try this solution

**Comment by tsunamayo** [comment]
Thanks, @ProPeach @asanagisae I guess it could be the survival closed beta check indeed, it tries to connect to a google spreadsheet. But I guess many games are doing the same, what I plan for localization will be similar too.
Cheers
