### ISSUE TITLE
(24w15a) Very low framerate 

### ISSUE THREAD

**Issue by Camerun28** [tsunamayo/Starship-EVO#5718]
### Short Description of the issue:
My frame rate useally hovers around 120 with small drops never below 70, but I'm getting drop to around 15 or even 5 for short periods of time useally a couple second never anything longer than 10 
seconds

UPDATE: it's gotten worse I'm not stuck mostly on 5fps with short spike back to 120 or whatever I have set as my maximum frame rate
...

### Steps to reproduce the issue:
Nothing in particular just happens when wandering around, but it is most likely to occur inside a ship
...

### Environment
- Starship EVO version: 24w15a
- Graphics Card: Nvidia 1660TI

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/15054547/Player.log)

**Comment by tsunamayo** [comment]
@Camerun28 Hi, did you played the game fine for a long time before that? Could you send me your character folder zipped so I can try to reproduce? Thanks

**Comment by Camerun28** [comment]
yes here is my character file (there's a good amount of stuff in the world but the lag is persistent no matter how many entities)
[Character file lag.zip](https://github.com/tsunamayo/Starship-EVO/files/15085019/Character.file.lag.zip)
additionally the lag isn't immediate it take a minute or 2 to get going 

its also not thermal throttling I'm getting good GPU temps (though I am at 100% GPU)

**Comment by Camerun28** [comment]
@tsunamayo problem is no longer present in 24w17a update, thank you for game update I can finally get back to building :)

**Comment by tsunamayo** [comment]
@Camerun28 Yes there was a performance issue fixed recently, but it was just before you booked that issue so I was confused at first. Glad it was that. Cheers
