### ISSUE TITLE
[Bug] 24w15a- Prefabs placed on Item stands do not give the same prefab when removed

### ISSUE THREAD

**Issue by Crimson-Artist** [tsunamayo/Starship-EVO#5719]
Apparently we can place prefabs on item stands and much like blocks they will be saved with the entity blueprint. However it seems that that prefabs are bugged and don't give the same prefab that is placed in the first place. The prefab that is retrieved will usually be the first prefab alphabetically in your prefab library.

Steps to recreate:
1. Place down a Item Stand.
2. Place any prefab in the stand.
3. Immediately retrieve the prefab.

**Comment by tsunamayo** [comment]
Well the bug unfortunately is that it was not made to work with prefab in the first place. thx

**Comment by tsunamayo** [comment]
@Crimson-Artist Issue fixed for 24w17b. Cheers
