### ISSUE TITLE
Receiving Error Code 3:0000065432

### ISSUE THREAD

**Issue by DisC0arse** [tsunamayo/Starship-EVO#5720]
### Short Description of the issue:
Attempting to launch game through Steam, receive Application Load Error 3:0000065432
...

### Steps to reproduce the issue:
Launch game
Receive Error
...

### Environment
- Starship EVO version: Latest
- Graphics Card: NVIDIA GeForce RTX 3070 Ti

### Additional information:
I have tried everything I can to get it to work, including a full Windows 10 reset, and it still won't launch, I can't include the "Player.log" since the game needs to launch for it to be added, and the game won't launch.
I'm aware that online forums say the error is related to Antivirus, but I've tried turning off antivirus and I still receive the error.
_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.
![steamerror](https://github.com/tsunamayo/Starship-EVO/assets/167782308/0e36f8a2-d72a-437d-accc-ce4c8e1766af)

**Comment by tsunamayo** [comment]
@DisC0arse I, sorry to hear that, do you have trouble with other games on steam?
Can you check this?
https://www.partitionwizard.com/partitionmagic/application-load-error-3-0000065432.html
Unfortunately it is steam related so I cant really do anything for you...
Cheers
