### ISSUE TITLE
[Bug] 24w15a - Pressing Tab locks all ships on random heading, sometimes crashes

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#5721]
### Short Description of the issue:
When attempting to move a ship with Tab, the ship will snap to a random heading and cannot turn. Sometimes it crashes on pressing Tab.

This seems to be a universal bug on my computer; it applies to new and old entities, new and old worlds, and even applies after doing a complete uninstall/reinstall of the game.

### Steps to reproduce the issue:
Take control of any of the ships in the attached world and press Tab. The ship will snap to point in some random direction and cannot be turned. The direction is usually the same for multiple ships, which makes me wonder if it's one of the game's axes. Sometimes getting out and back in can fix this, sometimes not. It also seems that if the ship is turning when Tab is pressed, that bypasses the issue sometimes. Occasionally the game will crash after pressing Tab.

### Environment
- Starship EVO version: 24w15a 
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/15067870/Player.log)

[Dwarf-Lord Pangolin.zip](https://github.com/tsunamayo/Starship-EVO/files/15067654/Dwarf-Lord.Pangolin.zip)

**Comment by Dwarf-LordPangolin** [comment]
Update: I'm adding a log from one of the sessions where the game crashed for additional information; hope it helps.

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/15068419/Player.log)

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Hi, sorry that issue was fixed already, I will upload the patch now (I was in the middle of some big refactors)
Cheers
