### ISSUE TITLE
[Bug] Invisible items in codex 

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#5723]
### Short Description of the issue:
Just had a user report this on Discord, seems pretty serious so I thought I'd pass it on as they aren't responding. @tsunamayo 

All items in the codex are invisible after today's update

https://media.discordapp.net/attachments/342383722185883648/1232256507874115604/Starship_EVO_2024-04-23_19-05-17.mp4?ex=6628cbcd&is=66277a4d&hm=99168189c0e13ebae8e2c7beebe61b02d23a2f9dcbe73da92fd0bbab2d164825&
### Steps to reproduce the issue:
According to the user it happens everytime the open the codex, and persists after a restart

### Environment
- Starship EVO version: 20w17
- Graphics Card: NA

### Additional information:
No logs as I'm away from home to test this one, sorry!

**Comment by tsunamayo** [comment]
@ProPeach Thanks for letting me know! It is fine now.
