### ISSUE TITLE
[SURVIVAL] the collector that expels ores has an unlimited inventory

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5725]
### Short Description of the issue:
I have two collectors, a large one thats connected to my base that is set to collect ores and a smaller one attached to my truck that expels the ores out of the truck. The inventory space in the expel one seems to be unlimited.
...

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

https://github.com/tsunamayo/Starship-EVO/assets/93534629/77192316-f644-4ef9-99ed-1792efcc2fea

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/15080570/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/15080572/Player-prev.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.
**The truck**
[Transport Truck.zip](https://github.com/tsunamayo/Starship-EVO/files/15080604/Transport.Truck.zip)
**The Base**
[HydroBase.zip](https://github.com/tsunamayo/Starship-EVO/files/15080611/HydroBase.zip)

**Comment by tsunamayo** [comment]
@surajnairpv Hi, I dont see your collector set at expel in the build. When I do set it one myself it works fine. Could you send me your world so I can investigate? Thanks

**Comment by surajnairpv** [comment]
How do I send the world?

**Comment by tsunamayo** [comment]
@surajnairpv Zip your character folder.

**Comment by surajnairpv** [comment]
@tsunamayo sure, the file is big( 25.5mb) so here is the link
https://file.io/IWkkrakMjONZ

**Comment by tsunamayo** [comment]
@surajnairpv Sorry I dont see where is the collector you are showing, and when I try to setup one myself it works fine.

**Comment by surajnairpv** [comment]
Same here, It somehow got  fixed while reloading the game. But thanks for checking up.
