### ISSUE TITLE
[CRASH] Game crashes when Editing Slider in motion

### ISSUE THREAD

**Issue by drimmel247** [tsunamayo/Starship-EVO#5726]
### Short Description of the issue:

- **Game crashes when adding/removing block to slider in motion.** 

### Steps to reproduce the issue:

**1. starter block
2. slider block of any length greater than 1(I usually do like 6-8 for length)
3. put a door slab up/ big enough surface to put things on when its moving
4. press 'f' on the slider to get it to slide
5. while its moving add a block
6. game should crash.** 

### Environment
- Starship EVO version: **24w15a**
- Graphics Card: **Asus 3060 Strix 12 gig**

### Additional information:

**Logs:** [Player.log](https://github.com/tsunamayo/Starship-EVO/files/15083761/Player.log)

**Blue Print:** [Super Destroyer.zip](https://github.com/tsunamayo/Starship-EVO/files/15083775/Super.Destroyer.zip)

**Comment by tsunamayo** [comment]
@drimmel247 Hi, I do not reproduce  the crash but I indeed see an error logged, I will get back to you.

**Comment by tsunamayo** [comment]
@drimmel247 Hi, could you please send me the content of the folder : 
C:/Users/Daniel/AppData/Local/Temp/Moonfire Entertainment/Starship EVO/Crashes

**Comment by tsunamayo** [comment]
@drimmel247 Hi, actually I managed to reproduce the crash outside the editor. Issue is fixed for 24w17b. Cheers
