### ISSUE TITLE
[Bug] 24w17a- Human Male hair overrides all other character model's hair

### ISSUE THREAD

**Issue by Crimson-Artist** [tsunamayo/Starship-EVO#5728]
For some reason the human male's hair appears on every model. It also overrides the hair on the female model. The male's hair is also the only that can be customized. 
![20240424021148_1](https://github.com/tsunamayo/Starship-EVO/assets/112352428/b2f94af8-4546-4e4b-8170-d06b1265ed93)

**Comment by ProPeach** [comment]
What a handsome fella!

**Comment by tsunamayo** [comment]
hum, okay ^^

**Comment by tsunamayo** [comment]
@Crimson-Artist Hi, issue is fixed for 24w17b. Cheers
