### ISSUE TITLE
game freeze when copy/pasting

### ISSUE THREAD

**Issue by Azathoh-the-blind-idiot-god** [tsunamayo/Starship-EVO#5731]
### Short Description of the issue:

When pasting onto a ship twice or more in a row, the game freezes for ~30 seconds.
When alternating between two (2) or more ships the pasting works fine and does not freeze.  
The second method is not fully reliable and sometimes causes freezes anyway.                          

### Steps to reproduce the issue:

1 - take any ship
2 - take any object
3 - copy the object onto the ship twice or more in a row
4- freezes

### Environment
- Starship EVO version: 24W017A
- Graphics Card: RX5700

### Additional information:

Frigate segments is the world in which I encountered the bug last. The bug can be replicated in any world

[IRDS module.zip](https://github.com/tsunamayo/Starship-EVO/files/15142335/IRDS.module.zip)
[IRDF & RHMS.zip](https://github.com/tsunamayo/Starship-EVO/files/15142336/IRDF.RHMS.zip)

[Frigate segments.zip](https://github.com/tsunamayo/Starship-EVO/files/15142340/Frigate.segments.zip)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/15142341/Player.log)

**Comment by ProPeach** [comment]
I've just got the same bug, an usuaully long paste delay on the second time. About 10 seconds for 1500 bricks
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/15154178/Player.log)

**Comment by Camerun28** [comment]
I've also experienced this bug

**Comment by tsunamayo** [comment]
@Azathoh-the-blind-idiot-god Hi, so I found an issue and fixed it for 24w18b. I am still having some hiccup though after several pastes with your prefab, as it has a lot of bricks (200). Now this is not really something I want to fix unfortunately, as I dont want to make ship with an overwhelming large numbers of pieces too easy to build for now (I still need need to implement a performance score).
Cheers
