### ISSUE TITLE
completely broken blueprint

### ISSUE THREAD

**Issue by Azathoh-the-blind-idiot-god** [tsunamayo/Starship-EVO#5732]
### Short Description of the issue:

Game freezes with increasing frequency after spawning the blueprint.
Game has somehow duplicated every child entity on the blueprint and rendered the duplicates invisible.
The Codex shows 3995 Child entities on a ship that should have ~2000, after removing every visible child entity still shows over 2000 left.
Cannot noclip through the front half of the ship.

### Steps to reproduce the issue:

1 spawn blueprint
2 wait until the freezing becomes unbearable

### Environment
- Starship EVO version: 24W17A
- Graphics Card: RX5700

### Additional information:

[Frigate Combined Hull V19 (RHMS) 1.zip](https://github.com/tsunamayo/Starship-EVO/files/15143593/Frigate.Combined.Hull.V19.RHMS.1.zip)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/15143594/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/15143595/Player-prev.log)

**Comment by tsunamayo** [comment]
@Azathoh-the-blind-idiot-god Hi, thanks I can see the issue indeed, it is linked to physics. I keep you posted. You are really pushing the engine thats great!

**Comment by tsunamayo** [comment]
@Azathoh-the-blind-idiot-god Hi, issue will be fixed in 24w19a. It was linked to the other children entity issues, I will work on that too.
