### ISSUE TITLE
[BUG] 24w18a- Solar Panels do not save their link to event gates in Prefabs

### ISSUE THREAD

**Issue by Crimson-Artist** [tsunamayo/Starship-EVO#5734]
Solar panels when they are linked to event gates don't save their links when copy/pasted. I'm trying to build a solar array prefab with a panel efficiency meter using event gate triggers and the meter kept breaking cuz of this bug. 

### Steps to reproduce the issue:

1.place down a solar panel
2. link it to a event gate
3. copy both the solar panel and the event gate
4. paste it anywhere.

Edit- Found out that the link also breaks when booting up the game

**Comment by tsunamayo** [comment]
@Crimson-Artist Hi, issue is fixed for 24w19a. Cheers
