### ISSUE TITLE
[BUG] 24w18a- Female Hair not rendering

### ISSUE THREAD

**Issue by Crimson-Artist** [tsunamayo/Starship-EVO#5735]
Look at how they massacred my girl. None of the hair styles will render.
![20240430094030_1](https://github.com/tsunamayo/Starship-EVO/assets/112352428/0e84ef67-1ad9-429d-81ed-0f5794daa48d)

**Comment by surajnairpv** [comment]
lol, it could be a really bad shampoo....

**Comment by tsunamayo** [comment]
@Crimson-Artist Indeed, thanks it is fixed for 24w19a. Cheers
