### ISSUE TITLE
Pipe see through broken

### ISSUE THREAD

**Issue by Azathoh-the-blind-idiot-god** [tsunamayo/Starship-EVO#5737]
### Short Description of the issue:

the pipe see through does not work

### Steps to reproduce the issue:

1 place a pipe behind a wall.
2 hold a pipe in your hand
3 pipe see through does not work

### Environment
- Starship EVO version: 27w18a
- Graphics Card: RX5700

### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/15209978/Player.log)

**Comment by tsunamayo** [comment]
@Azathoh-the-blind-idiot-god Hi, issue is fixed for 24w19a. Cheers
