### ISSUE TITLE
[Survival] Life support has no connection with the oxygen tank

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5738]
### Short Description of the issue:
The Life support although connected with the oxygen tank does not take the oxygen from the tank. Guessing its still a work in progress.
...

### Steps to reproduce the issue:
connect a life support with a tank filled with oxygen via pipes
...

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/15209994/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/15209995/Player-prev.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.
[Starship.zip](https://github.com/tsunamayo/Starship-EVO/files/15209998/Starship.zip)

**Comment by tsunamayo** [comment]
@surajnairpv Hi, no they are not compatible with piping, as I dont want to player to have to pipe them that would be way too tedius.

**Comment by surajnairpv** [comment]
@tsunamayo 
Understood, so since there is not going to be any pipping connected to the Life support, we may have to manually transfer oxygen from the tanks to the life support via Bottles.
Which means I will have to place Oxygen tanks near the Life support for the easier transfer.
If there is any other way or tip do let me know.
Just wanted to know about this as my ship design depends on this.
