### ISSUE TITLE
[survival] [suggestion] can we connect the life support display to the monitors?

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5739]
### Short Description of the issue:
I like the oxygen coming out from the ceiling of the ship but would love the display of the oxygen levels on a monitor below.
Could that be possible?
please check the screen shot.

![Starship_EVO_hYLIbe7jsM](https://github.com/tsunamayo/Starship-EVO/assets/93534629/a0c64267-9c99-4249-8112-0744df782e91)

**Comment by tsunamayo** [comment]
Hi, it would make sense indeed.

**Comment by tsunamayo** [comment]
@surajnairpv Hi, this is implemented for 24w19a. Cheers
