### ISSUE TITLE
[Bug] Roll Keybinds do not working in freelook

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#5741]
### Short Description of the issue:
I have my roll keys mapped to Q and E whick work for ships and the player. When you enter freelook in a ship, these keybinds do not work. Other strafe keys up/down/left/right/forward/back work fine
![image](https://github.com/tsunamayo/Starship-EVO/assets/27857711/9023ce0c-3c8c-4585-ba63-8aefec6defb7)

### Steps to reproduce the issue:
- Enter freelook
- Roll a ship with keybinds 

### Environment
- Starship EVO version: 24w18a
- Graphics Card: RX 6700XT

**Comment by tsunamayo** [comment]
@ProPeach Indeed, issue fixed for 24w19a. Cheers
