### ISSUE TITLE
[BUG] Ship Launched Upwards When Docking

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#5744]
### Short Description of the issue:
when attempting to dock with a platform I try to activate the docking port before letting go of control so that my ship wont crash, this then forces my ship to move upwards until i let go of the yoke. The ship will then fall and if in range of the docking port will attempt to dock with it again
...

### Steps to reproduce the issue:
be in control of a ship and attempt to dock while in gravity/on the ring
...

### Environment
- Starship EVO version: 24w18a

### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/15211650/Player.log)

https://github.com/tsunamayo/Starship-EVO/assets/56371294/f852b8f8-5de2-4361-9928-b4132fe3c556

[Griffin Docking TEST BPs.zip](https://github.com/tsunamayo/Starship-EVO/files/15211665/Griffin.Docking.TEST.BPs.zip)
ships used

**Comment by TIKIRobo** [comment]
Update: this also happens to ships with starter blocks on them

**Comment by tsunamayo** [comment]
@TIKIRobo Hi, I think the issue should be fixed for 24w19a. Tell me if it is not the case when the update is up!
