### ISSUE TITLE
docking connectors not saving their status

### ISSUE THREAD

**Issue by king32109** [tsunamayo/Starship-EVO#5745]
### Short Description of the issue:
as the tital sais, they dont save their settings
...

### Steps to reproduce the issue:
place docking conector, set to anyhing else, then locked, delete and respawns and see it back to locked
...

### Environment
- Starship EVO version: 24w18a
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@king32109 Hi, I am not sure to understand your test case. What are you deleting, the entity or the brick? Thanks

**Comment by king32109** [comment]
Everything´ i delted the entire ship via the unspawn button then place a starter block. And respawn the same ship yo see the docking block not having saved its setting

**Comment by tsunamayo** [comment]
@king32109 Indeed I reproduced the bug. Fixed for 24w19a. Cheers!
