### ISSUE TITLE
[Bug] Symmetry plane does not update when using F2

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#5746]
### Short Description of the issue:
There's a couple interactions between the mirror plane and F2 that don't work as expected - they work differently than when F2 isn't used. They don't appear to be related to any specific world or blueprint.

### Setup procedure:
1. Have a ship in the world, then add a mirror to it by using: codex > tools > symmetry tool. I've been using the blue plane but this affects yellow and green as well.
2. Set slot 1 in your hotbar to a hull block. Any block should be valid for this test. Using a paint works too.
3. Set slot 2 in your hotbar to empty. When you press 2, you should stow your multitool away.

### Expected behaviors (how the game works without F2):
- M should always be able to toggle symmetry on and off (if there's at least one symmetry plane on a ship)
- If a block is selected in your hotbar, any symmetry planes should become visible on ships you're building.
- If no block is selected in your hotbar (you used the empty slot), all symmetry planes disappear from your ships.

### Issues with F2:
You cannot turn symmetry **off** with M while using F2.
1. Ensure the UI is showing.
2. Press slot 1 to equip a hull block and make the symmetry plane appear.
3. If symmetry is off, press M to toggle symmetry **on.** The symmetry preview turns white to indicate that it is active.
4. Press F2 to hide the UI.
5. Press M to turn symmetry **off.** Bug: The symmetry plane remains **on.**
6. Place a block on the ship. Effect: The symmetry plane still applies, the game ignored your request to turn symmetry off with M.

You cannot turn symmetry **on** with M while using F2.
1. Ensure the UI is showing.
2. Press slot 1 to equip a hull block and make the symmetry plane appear.
3. If symmetry is on, press M to toggle symmetry **off.** The symmetry preview turns red to indicate that it is inactive.
4. Press F2 to hide the UI.
5. Press M to turn symmetry **on.** Bug: The symmetry plane remains **off.**
6. Place a block on the ship. Effect: The symmetry plane does not apply. The game ignored your request to turn symmetry on with M.

The symmetry plane doesn't **disappear** when expected.
1. Ensure UI is showing (not using F2).
8. Press slot 1 to hold a block if you aren't already. The symmetry plane should appear on the ship.
9. Press F2 to hide the UI. The symmetry plane should still be visible [ok].
10. Press slot 2 to stow your multitool. *The symmetry plane is still visible.* It should not be.
11. Press F2 to show the UI. The UI appears [ok], and then the symmetry plane disappears [late].

The symmetry plane doesn't **appear** when expected. (Symmetry itself does appear to apply correctly when you place a block in this state.)
1. Ensure UI is showing (not using F2).
7. Press slot 2 to ensure you are not holding the multitool. The symmetry plane should not be visible on the ship.
8. Press F2 to hide the UI.
9. Press slot 1 to equip the hull block. *The symmetry plane should appear at this step, but it does not.*
10. Press F2 to show the UI. The symmetry plane appears [late].

### Environment
- Starship EVO version: 24w18a

**Comment by tsunamayo** [comment]
@asanagisae Hi, issue is ifxed for 24w19a. Cheers!
