### ISSUE TITLE
[BUG] Volumetric sensor doesn't work as expected 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#5747]
### Short Description of the issue:
volumetric sensor is detecting me outside of its bounds but only on the right, front, and top sides
...

### Steps to reproduce the issue:
follow the video
...

### Environment
- Starship EVO version: 24w18a

### Additional information:

[Landing Pad for Griffin Aircar .zip](https://github.com/tsunamayo/Starship-EVO/files/15228304/Landing.Pad.for.Griffin.Aircar.zip)

https://github.com/tsunamayo/Starship-EVO/assets/56371294/9ce66e8a-c387-4ef8-affe-f9381e53d8d4

**Comment by tsunamayo** [comment]
@TIKIRobo Hi, good catch, issue is fixed for 24w19a. Cheers
