### ISSUE TITLE
[QUESTION] New Files When Saving Ships?

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#5750]
Experimental version 
a few days ago my ship's files would look something like this
![image](https://github.com/tsunamayo/Starship-EVO/assets/56371294/556971f2-420f-49cb-aed5-ad4359209b7b)
and I would only need to send the .sevo file if i wanted to share a BP
now the files look like this 
![image](https://github.com/tsunamayo/Starship-EVO/assets/56371294/da4c5588-5516-4363-96f5-19d8d8c9eb37)
and i'm not sure if this is intentional as these are the old file types used and now its more confusing as I don't know what type of file to share anymore

**Comment by tsunamayo** [comment]
@TIKIRobo When you want to share something share the folder entirely. Yes the .sevobu is the backup, the good save is the .sevo.
