### ISSUE TITLE
[Survival] Container won't connect with more than 4 conveyors

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5757]
### Short Description of the issue:
The container shows 4/6 connected tubes which means I can connect 2 more but it does not connect with the 5th conveyor as shown in video

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

https://github.com/tsunamayo/Starship-EVO/assets/93534629/043f8c18-2b4b-41ba-927c-6c1d19bb59af

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/15286482/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/15286483/Player-prev.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

[HydroBase.zip](https://github.com/tsunamayo/Starship-EVO/files/15286485/HydroBase.zip)

My world
https://file.io/PJmexiSCJNQl

**Comment by tsunamayo** [comment]
@surajnairpv I can link these with no issue, it might be related to your game breaking for some reason, it seems that you have the item in hand not refreshing. I will try to fix that pb first. Thanks

**Comment by surajnairpv** [comment]
Yeah Your right, it got connected when I started playing the game again, seems restart is the fix for this
