### ISSUE TITLE
[Item Description] Turbine, Antenna share description with Capacitor

### ISSUE THREAD

**Issue by drimmel247** [tsunamayo/Starship-EVO#5762]
### Short Description of the issue:

The descriptions for Turbine and Antenna are the same as capacitor.

### Steps to reproduce the issue:

1. open items tab
2. hover over Antenna
3. hover over wind Turbine
4. hover over Capacitor

### Environment
- Starship EVO version: 24w20a & 42w18a
- Graphics Card: Asus 3060 12gb Strix

### Additional information:

Screenshots:

**Antenna:** ![20240508203315_1](https://github.com/tsunamayo/Starship-EVO/assets/32307665/a5dc0f53-845c-4ca8-bc9d-b2a278d4c056)
**Wind Turbine:** ![20240508203327_1](https://github.com/tsunamayo/Starship-EVO/assets/32307665/f28d57a4-dd49-4524-be30-1e0268737e4c)

**Capacitor:** ![20240513234122_1](https://github.com/tsunamayo/Starship-EVO/assets/32307665/dbc67df9-f26b-4978-9fb8-273d24f42942)

**Comment by tsunamayo** [comment]
@drimmel247 Thanks, issue fixed for 24w20b. Cheers
