### ISSUE TITLE
Character slides down slopes

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#5763]
### Short Description of the issue:
Testing out the new locomotion I tried walking around a planet and found myself sliding down a moderate slope

In this video I only hit the space bar to jump, the character walking down the slope is not caused by me using the arrow keys, but by the sliding that I'm talking about
https://github.com/tsunamayo/Starship-EVO/assets/27857711/b4ffcb2b-6938-4afb-b211-e3bafdb21421

### Steps to reproduce the issue:
- Jump on a slope of aroun 30 degrees

### Environment
- Starship EVO version: 24w20a
- Graphics Card: RX 6700XT

**Comment by tsunamayo** [comment]
@ProPeach You are talking about the slide after the jump landing? I can only reproduce a slide after a jump.

**Comment by ProPeach** [comment]
@tsunamayo yes exactly

**Comment by tsunamayo** [comment]
@ProPeach Okay it is fixed for 24w20b. Cheers
