### ISSUE TITLE
[Survival] [Suggestion] Can we have a status display for the amount of content in the container

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5765]
### Short Description of the issue:
We can have monitor connections that show us Oxygen level, Hydrogen levels and water levels  in tank within the monitor display.
Why not have a Status on Container display, just a simple percentage filled is enough.
Once we have the mining vehicles we can add this display on the cockpit like how much ores have been collected 
or we can keep track of stacked resources in the base or the ship as well

### Additional information

_(Screenshots, Videos, Error logs, Related issues)

Just to show what I mean
![Starship_EVO_7bKJXvt3UR](https://github.com/tsunamayo/Starship-EVO/assets/93534629/229baf6e-aa24-47c6-816c-293ae9b12b62)

**Comment by tsunamayo** [comment]
@surajnairpv Yes it makes a lot of sense.

**Comment by tsunamayo** [comment]
@surajnairpv Done for 24w20b. Cheers

**Comment by surajnairpv** [comment]
Awesome 👍
