### ISSUE TITLE
Docking alignment broken

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Starship-EVO#5766]
### Short Description of the issue:
If you place a docking connector on a childentity (piston hinge) the alignment fails completely
### Steps to reproduce the issue:
->Video
I ve tried with different constructions and all combinations or orientation settings in the connector but i did not found a workaround
If the connector is placed on the mainentity, the orientation is correct and docking works as expected (the first example in the video was docked correct-> connector shows only blue because of restart)
### Environment
- Starship EVO version: 24w20a

https://github.com/tsunamayo/Starship-EVO/assets/43222403/8eff1acd-fbdd-406a-9646-d28adc841135

**Comment by D345x0** [comment]
Somehow I experienced this too and I still have no other god given reason on why it has happened other than untiy engine being, well.. Unity Engine.

**Comment by tsunamayo** [comment]
> Somehow I experienced this too and I still have no other god given reason on why it has happened other than untiy engine being, well.. Unity Engine.

99% sure it has nothing to do with the Unity engine, it must be my code, let me check and get back to you guys.

**Comment by tsunamayo** [comment]
@Battlepixel @D345x0 Sorry I should have done something to prevent you from doing that, but docking from a children entity is not working and cannot work in the current physics logic. I will prevent you from trying to do that.
It works well if the other dock you are docking to is on a children entity though.

I hope it is clear!
