### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Starship-EVO#5768]
### Short Description of the issue:
The game crashes if I fly to the gasplanet rings.
### Steps to reproduce the issue:
Fly to the gasplanet rings.
I tried different ships, restart and creating a new world, but there is no workaround for me. It always happend in lightcruise, when there where only a few(10-50) km left to reach the asteroids.
I experienced this bug also from previous versions, but dont know when exactly it starts.

### Environment
- Starship EVO version: latest
- Graphics Card: 4080RTX newest drivers

### Additional information:

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/15325343/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/15325345/Player-prev.log)
[Test3.zip](https://github.com/tsunamayo/Starship-EVO/files/15325352/Test3.zip)
Test 3 is last character I created only to derectly reproduce the bug.

**Comment by tsunamayo** [comment]
@Battlepixel Hi, I didnt reproduce a crash but I see an error popping. I keep you posted!

**Comment by tsunamayo** [comment]
@Battlepixel So issue is fixed for 24w21a. Cheers
