### ISSUE TITLE
[bug][24w20a] attack of the giant hair

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#5770]
### Short Description of the issue:
An NPC character's disembodied hair will sometimes appear gigantic and encircle their ship.

### Steps to reproduce the issue:
1. load a world (creative mode? preexisting player builds?)
2. find an NPC ship
3. observe

### Environment
- Starship EVO version: 24w20a
- Graphics Card: Nvidia GeForce GTX 1060 6gb

### Additional information:

https://github.com/tsunamayo/Starship-EVO/assets/51390907/f015f27f-c460-4c29-bcbf-3fb3d0359be7

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/15366009/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/15366010/Player-prev.log)

**Comment by tsunamayo** [comment]
@Majikmonster Hi, issue is fixed for 24w21a. Cheers
