### ISSUE TITLE
Game crashes shortly after booting up

### ISSUE THREAD

**Issue by darkskull8** [tsunamayo/Starship-EVO#5771]
### Short Description of the issue:

Whenever I boot up the game I get to the "press any key" screen then it crashes, without me doing anything, sometimes taking steam down with it. (I can get the main menu if I spam keys before the "press any key" screen shows up, but the same thing happens just with a different screen showing.)

### Steps to reproduce the issue:

Boot up starship evo
Wait for the window to pop up
Optional- spam a key when a black screen shows up that is grayed out due to the window not responding
the menu shows up with the window not doing the not responding graying
a few moments later the window becomes transparent
then the window becomes black before closing entirely

### Environment
- Starship EVO version: 24w20a
- Graphics Card: RX 580

### Additional information:

[Player.zip](https://github.com/tsunamayo/Starship-EVO/files/15393910/Player.zip)

**Comment by tsunamayo** [comment]
@darkskull8 Hi, sorry to hear that, it seems to be a GFX driver issue.
Could you make sure that your windows and GFX driver are up to date? Thanks
