### ISSUE TITLE
Docking Connector Bug - Its impossible to build a working dock

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Starship-EVO#5774]
### Short Description of the issue:

Fuel refill broken if also used for both cargo and Fueltransfer.

### Steps to reproduce the issue:
If I connect a docking connector to a fuel line and a cargo line, **the refill function no longer works** but fuel is sometimes transported into the cargo containers, and under the transferferCargoWindow it is shown that the Carogo containers are also connected to all tanks. 

I wanted to build a dock to be able to refuel the small ship at the big one and to be able to load and unload cargo between hangar storage and small ship at the same time.
I tried all kinds of things, but couldn't find a solution to get around the error and get the dock to work.

I didn found a workaround to make it working.
### Environment
- Starship EVO version: latest
- Graphics Card: 

https://github.com/tsunamayo/Starship-EVO/assets/43222403/cab68426-8eb8-4080-a11a-5341f62ffa56

(The Item with the amount of 104 in the cargo is fuel)
I also uploaded the charcter, so you can check for yourself. 
Follow the steps shown in the video to reproduce the error.
[Test1.zip](https://github.com/tsunamayo/Starship-EVO/files/15437115/Test1.zip)
You will find youself dicectly inside the hangar.
![Starship EVO_2024_05_24_18_07_32_460](https://github.com/tsunamayo/Starship-EVO/assets/43222403/b4741a81-51c7-4693-8826-1ad9665bb429)

**Comment by tsunamayo** [comment]
@Battlepixel Hi, issue is fixed for 24w24a. Cheers
