### ISSUE TITLE
Entities are immune to gravity after undocking until grid update

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#5775]
### Short Description of the issue:
When a ship undocks from a Connector, it is not affected by gravity. The player has to update the ship by placing a brick on it for gravity to start affecting it.

In the video below, the gravity field is generated by the mothership and the docked pod does not fall when undocked, until I place a brick on it
https://imgur.com/a/x5UcsAF

### Steps to reproduce the issue:
- Dock ships in a gravity field
- Undock them, the ship will not fall
- Place a block on the undocked ship, it will now fall

### Environment
- Starship EVO version: 24w20b
- Graphics Card: RX6700XT

### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/15448030/Player.log)

**Comment by tsunamayo** [comment]
@ProPeach Hi, issue is fixed for 24w24a. Cheers
