### ISSUE TITLE
Docking Connector struggles to align the last few degrees when docking

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#5776]
### Short Description of the issue:
The most common failure I see when attempting to dock is where the Connectors *almost* line up perfectly, and seem to give up at about this stage
![image](https://github.com/tsunamayo/Starship-EVO/assets/27857711/2a93c349-8a1f-4483-ae29-9aed84a393de)
Sometimes they can rotate down to complete the connection, but it can take a while (10 seconds-ish) to finish up those last few degrees.
Here's a "simple" scenario where the Connectors are aligned well to start with, and it takes 15 seconds to finish after the initial movements.
https://imgur.com/ma4Zw1C

I don't suppose the Connector forces could be given a little more torque to speed up this stage? Apart from this the connectors seem very capable now. This video shows a very tough situation for the Connectors and they do a great job, apart from those last few degrees again
https://imgur.com/MjOICDp

### Steps to reproduce the issue:
- Align two Docking Connectors at a ~5 degree angle and initial docking
- The Connectors will often do a great job aligning apart from the last stage

### Environment
- Starship EVO version: 24w20b
- Graphics Card: RX6700XT

### Additional information:
[Docking Test Dummy.zip](https://github.com/tsunamayo/Starship-EVO/files/15448056/Docking.Test.Dummy.zip)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/15448061/Player.log)

**Comment by tsunamayo** [comment]
Yes I have noticed it too, I will improve it. thx

**Comment by tsunamayo** [comment]
@ProPeach Hi, issue fixed for 24w25b. Cheers
