### ISSUE TITLE
[BUG] ship collidies with its own power cells

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#5777]
### Steps to reproduce the issue:
build a small ship and power it using a power cell, then fly it around
...
Also deleting a power cell base before picking the power cell up leave behind a power cell you can't interact with

### Environment
- Starship EVO version:  24w21a (in game it says 20b)

### Additional information:

https://github.com/tsunamayo/Starship-EVO/assets/56371294/85100c1b-a3e8-44b2-8907-3d5c228e96ed

once the power cell was removed the ship flew fine

**Comment by tsunamayo** [comment]
@TIKIRobo Hi, issue is fixed for 24w24a. Cheers
