### ISSUE TITLE
[BUG] inconsistencies in power generation 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#5779]
[Batt test bed.zip](https://github.com/tsunamayo/Starship-EVO/files/15449886/Batt.test.bed.zip)
[reactor test bed 2.zip](https://github.com/tsunamayo/Starship-EVO/files/15449887/reactor.test.bed.2.zip)
^the ships used

these are just some inconsistencies ive noticed with many of the numbers given for power generation

first the battery ship:
![image](https://github.com/tsunamayo/Starship-EVO/assets/56371294/98bdb070-3502-4715-a892-6dc6887e6234)
![image](https://github.com/tsunamayo/Starship-EVO/assets/56371294/4ad6e249-c9f4-4d48-8e2b-c15e10869b26)
![image](https://github.com/tsunamayo/Starship-EVO/assets/56371294/1adc6d81-5fc6-4694-a454-c908d335f3e5)
![image](https://github.com/tsunamayo/Starship-EVO/assets/56371294/3c7a92cb-d6e9-495f-bf38-4837c458c277)
first the ship says its generating 10 e/s, in the codex it agrees that power cell base's should generated 10e/s however when i click on the base with a link tool it says it's generating 200 e/s, also some blocks like thrusters say what power they use/heat they generate but not at what scale
a fix for this could be a bar at the top of the codex that shows your active scales then once you click on one it'll only show you blocks that are in that scale and their stats at that scale
![image](https://github.com/tsunamayo/Starship-EVO/assets/56371294/f91271f4-477f-483a-a146-a4c00d3ddc3d)

next the reactor ship:
![image](https://github.com/tsunamayo/Starship-EVO/assets/56371294/a9bdebff-b80f-476f-a2de-8eb57acbbff5)
![image](https://github.com/tsunamayo/Starship-EVO/assets/56371294/4733bf34-a669-48a6-a2ed-3dbcdb514e73)
![image](https://github.com/tsunamayo/Starship-EVO/assets/56371294/9d51c3d1-24f0-4f8b-bbd8-c5b8b762a083)
again the ship reports an incorrect power generated, power stored and max capacity, the only block on that ship that can store power is the reactor (max 63) but for some reason it says 16,063, this may be because the ship used to have a power cell base on it but that number shouldn't stick around

restarting the game did actually fix one of the issues and the reactor ship's power gen dropped down to the 13 e/s it was supposed to be so the ships should look more like this and the max capacity also dropped to 63 as it should be
![image](https://github.com/tsunamayo/Starship-EVO/assets/56371294/b00684e5-7a2e-49b7-b63b-1ea7a7f6dc4f)

**Comment by tsunamayo** [comment]
@Hi, all issues regarding the power cell are fixed for 24w38a. Thanks

**Comment by tsunamayo** [comment]
@TIKIRobo Hi, the rest of the issues are also fixed. Thanks
