### ISSUE TITLE
Inaccurate controls directions in tutorial

### ISSUE THREAD

**Issue by CyberSiren** [tsunamayo/Starship-EVO#5780]
### Short Description of the issue:

on default settings, the player can't drag and drop items from the tab menu into their hotbar, however, directions to link the yoke and the computer in the tutorial tell the player to drag and drop the link tool into their inventory. 
...

### Steps to reproduce the issue:
get to the portion of the tutorial where the player is instructed to use the link tool for the first time
...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

![image](https://github.com/tsunamayo/Starship-EVO/assets/7178906/229d2f51-19e4-4d50-aacc-c4829df48fab)

**Comment by tsunamayo** [comment]
@CyberSiren Hi, what do you mean by "player cant drag items to the item bar"? You cant use the codex at all? Thanks

**Comment by asanagisae** [comment]
I believe I've run into this situation before. To move something to the item bar, you first _click and release_ on the item from the codex, then you _click and release_ on a spot in the item bar.

This is not dragging, where you _click and hold_ an item from the codex, then you _release_ the item over a spot on the item bar.

The tutorial hint in the screenshot is telling you to do the latter. The game won't respond if you do the latter. You must do the former.

**Comment by tsunamayo** [comment]
@asanagisae I see, make sense, I will update it. Not 100% sure it was the issue though.
