### ISSUE TITLE
[Suggestion] Auto Power Mode for Power Cell Base

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#5783]
For the new Power Cell Base, I think an "Auto" setting that is selected by default could be useful

This setting would charge the Power Cell if there is spare energy on the grid, and discharge it if there is higher draw than production.
![image](https://github.com/tsunamayo/Starship-EVO/assets/27857711/bf8f15cb-36b6-4979-9957-1f1f0671f3b7)

In practice, this would mean that for the majority of the time the player would not need to change the settings in the Power Cell Base GUI. A Cell Base on a players Solar/Wind powered grid would always charge its Cells, and the Cell Base on their hovercraft would always automatically draw its charge.
I think it's important that wherever possible in the game, systems should work with minimal setup and fiddling from the player, so the default setting should be the one that is used most often. As it currently stands without this Auto Option, the player will always have to remember to enter the Cell Base's GUI and change the setting which can be easily missed for a new player learning the ropes, or an experienced player simply forgetting to do it.

**Comment by tsunamayo** [comment]
@ProPeach Hi, so I managed to improve this for 24w38a (when I added a small cell too). It was my intent at the beginning but for some reason it was a bit counter-intuitive to pull out. Cheers
