### ISSUE TITLE
Antenna and Triangular Girder block have mismatched minimum scales

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#5788]
### Short Description of the issue:
It seems like the Antenna and Triangular Girder are meant to be used together due to their similar shapes, but their minimum scales do not match. The Antenna can go down to 1/4th, whereas the Girder can only go down to 1/2 scale

![image](https://github.com/tsunamayo/Starship-EVO/assets/27857711/8f05666c-6db6-4cd9-96c3-d81b6a668ab9)

It'd be great if all the girder bricks went down to 1/4th scale too

### Environment
- Starship EVO version: 24w20b
- Graphics Card: RX6700X

**Comment by tsunamayo** [comment]
@ProPeach Fixed for 24w24a. Cheers
