### ISSUE TITLE
[Suggestion] Add a TRUE "When Docked" Event Gate Trigger for Docking Ports

### ISSUE THREAD

**Issue by Crimson-Artist** [tsunamayo/Starship-EVO#5789]
For some reason the current **"When Docked"** event gate trigger sends out a logic signal during the docking process (When the lights flash yellow) as well as during a successful dock. This can cause problems for circuits that depend on one or the other event as the docking process is not definate and can be interrupted.

Thats why we need a true **"When Docked"** event trigger that only triggers when the docking is successful (Green lights) and change the current **"When docked"** setting to **"In Docking Sequence"** and have it only trigger when the docking ports have yellow lights.

**Comment by tsunamayo** [comment]
Seems more like a bug to me!

**Comment by Crimson-Artist** [comment]
> Seems more like a bug to me!

probably. but I think theres merit in adding a specific event gate trigger for the docking sequence. certain inbetween actions need an event gate trigger like this and Lightcruse charging

**Comment by tsunamayo** [comment]
@Crimson-Artist Hi, it is fixed for 24w24a. Cheers
