### ISSUE TITLE
[Bug] Tutorial - "Open codex" step does not use custom keybindings

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#5793]
### Short Description of the issue:

The "open codex" step of the tutorial does not show your custom keybinds. It uses the default binding of [TAB].

I've remapped my [tab] key to change block scale, which the rest of the tutorial acknowledges. I mapped [G] to the codex.

This is a purely visual bug. The [G] key indeed opens the codex during normal game play for me, as expected.

### Steps to reproduce the issue:

1. Open "options > key mapping" and change the codex key to something other than [tab].
2. Progress through the tutorial to the basic building training, and proceed to the "open codex" step.
3. Observe that your keybinding is not displayed here.

### Environment
- Starship EVO version: 24w20b (mech branch, if it matters)

### Additional information:
![image](https://github.com/tsunamayo/Starship-EVO/assets/10069469/3ad727bc-d9fd-43d1-a85d-3db2326fb91c)

I remapped rotation to the [delete] key. This is correct.
I remapped grid size to [tab]. This is correct.
I remapped codex to [G]. The hint here should say [G] but it says [tab] instead.

**Comment by tsunamayo** [comment]
@asanagisae Hi, issue is fixed for 24w25a. Cheers
