### ISSUE TITLE
~50 terrain textures free on the Unity Store

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#5794]
You might have already seen this, thought I'd ping it across anyway! Looks like you use the promo code RAYGEAS, hope they're useful to you.

https://github.com/tsunamayo/Starship-EVO/assets/27857711/479ea699-a681-48fe-9ae4-b36f863c3ee4

https://www.reddit.com/r/Unity3D/s/4RU9iE4UWV

**Comment by BigBadKangaroo** [comment]
They look really nice!

**Comment by COMICLER** [comment]
these would fit right in with the games style

**Comment by tsunamayo** [comment]
@ProPeach Thanks yep they look nice, not sure if I will be able to use them as I use a special adobe substance format as I need plenty of tweaks, I will see. Cheers
