### ISSUE TITLE
[Mechs] Joint of 1/4th size cannot be built on

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#5796]
### Short Description of the issue:
Due to the unusual height of the Mech Joint brick, they cannot be built on at 1/4th size. Reducing the Joints overall height to 1m would solve this.

https://imgur.com/a/CzFn6Lg

### Steps to reproduce the issue:
- Place a Joint at 1/4th scale
- Attempt to place a brick on it

### Environment
- Starship EVO version: Mech Preview
- Graphics Card: RX 6700XT

**Comment by tsunamayo** [comment]
@ProPeach So yes I update the current mesh, I have yet to update the texture though. Cheers
