### ISSUE TITLE
[MECH] connecting a ball join arm block to turret computer causes screen to freeze

### ISSUE THREAD

**Issue by drimmel247** [tsunamayo/Starship-EVO#5797]
### Short Description of the issue:

After adding a ball join arm block to the turret computer the screen will freeze when selecting the turret computer with connector tool. 

### Steps to reproduce the issue:

1. build mech
2. add turret computer
3. connect turret computer to rotator > ball join arm block
4. try to connect turret computer to camera or repair beam - this step should cause screen to freeze
5. click anywhere and screen goes back to normal
6. now just select turret computer - this should also cause screen freeze

### Environment
- Starship EVO version: 24w20b - experimental mech
- Graphics Card: 3060 12gb Asus strix

### Additional information:

video: https://github.com/tsunamayo/Starship-EVO/assets/32307665/57a5bc9e-c068-4d4b-b56b-ed0431c6976d
Player log:  [Player.log](https://github.com/user-attachments/files/15750578/Player.log)
Blue Print: [Gundam Exia.zip](https://github.com/user-attachments/files/15750579/Gundam.Exia.zip)

**Comment by tsunamayo** [comment]
@drimmel247 Hi, issue is fixed for 24w25a. Cheers
