### ISSUE TITLE
[Survival] Mirror does not invert the assembler

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5798]
### Short Description of the issue:
Most objects invert their positions across the Mirror plane but the assembler does not

...

### Steps to reproduce the issue:
use the mirror feature and try mirroring the assembler

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

https://github.com/tsunamayo/Starship-EVO/assets/93534629/0a8881a4-d3e1-4443-bd13-54c9b587ae13

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Player.log](https://github.com/user-attachments/files/15750779/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/15750780/Player-prev.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

[Starship.zip](https://github.com/user-attachments/files/15750781/Starship.zip)

**Comment by tsunamayo** [comment]
@surajnairpv Hi, issue is fixed for 24w24a. Cheers
