### ISSUE TITLE
[MECH] mech walk wants to fall forward and still launches to space

### ISSUE THREAD

**Issue by drimmel247** [tsunamayo/Starship-EVO#5800]
### Short Description of the issue:

When testing mech walk the mech wants to fall forward when encountering terrain. On occasion the mech will still get launched at 30Km+ off planet. 

### Steps to reproduce the issue:

1. choose a mech
2. pilot mech 
3. try walking up
3a. if you have a starter block aim for uphill terrain
3b. remove the starter block and hope you don't launch on mech start - this could partially be because I have my mech in a kneeling position during idle
4. when walking you should topple forward

### Environment
- Starship EVO version: 24w20B - Mech Preview
- Graphics Card: 3060 Asus Strix 12 gig

### Additional information:

Player Log: [Player.log](https://github.com/user-attachments/files/15795334/Player.log)
Blue Print:  [Gundam Exia.zip](https://github.com/user-attachments/files/15795337/Gundam.Exia.zip)

**Comment by tsunamayo** [comment]
@drimmel247 This has been fixed for the upcoming mech update. Thanks
