### ISSUE TITLE
[Mechs] Removing a Key in the Mech Computer can break the preview animation

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#5801]
### Short Description of the issue:
See video, the Key deleted from the Foot Left Joint causes the preview animation to break. It cannnot be restarted again until you respawn the blueprint
https://imgur.com/a/cbDlpbO

The first few times I removed a Key, the bug did not occur. This makes me think the Key removed must be being played at the time it is removed for it to cause the bug, although I'm not certain about that. I've attached the bp, although it happens with any bp from what I've seen

### Steps to reproduce the issue:
- Open the Mech Computer and navigate to the Walk menu
- Remove Key

### Environment
- Starship EVO version: RX 6700XT
- Graphics Card: Mech Preview

### Additional information:
[Player.log](https://github.com/user-attachments/files/15802256/Player.log)
[Leg Piston Test.zip](https://github.com/user-attachments/files/15802263/Leg.Piston.Test.zip)

**Comment by drimmel247** [comment]
I have also seen this, if the preview screen freezes and then you try to test via the yoke the game will prevent you from doing anything except for hitting 'escape' to exit game. Restarting the game fixes it.

**Comment by tsunamayo** [comment]
@ProPeach I think it should be fixed in the current version, as the playback logic was changed. Cheers
