### ISSUE TITLE
[Mech] Mechanisms cannot be manually assigned angles

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#5805]
### Short Description of the issue:

When you interact with a mechanism and assign it an angle, as soon as you close the mechanism's window, the angle resets to what it was previously.

I have experienced this with the old hinges and rotors, as well as the new ball join. 

Pistons appear to be unaffected.

### Steps to reproduce the issue:

1. Start the game, load a world
2. Find a ship with a mechanism, or place a new mechanism
3. Attempt to change the angle of the mechanism
4. Close the mechanism window
5. Observe that the mechanism moves back to the original angle

### Environment
- Starship EVO version: 24w24b [mech preview] (in game, is still labeled as 24w20b)

### Additional information:

https://github.com/tsunamayo/Starship-EVO/assets/10069469/60a46bd3-5a26-476c-8b71-8d985b3616fb

**Comment by tsunamayo** [comment]
@asanagisae Hi, issue is fixed for 24w25a. Cheers
