### ISSUE TITLE
[MECH] limb menu the 'r' on "shoulder" got dropped so in the menu it shows "shoulde"

### ISSUE THREAD

**Issue by drimmel247** [tsunamayo/Starship-EVO#5806]
### Short Description of the issue:

In the limb menu the 'r' on "shoulder" got dropped so in the menu it shows "shoulde". Just a small typo, Thank you for all your hard work. 

### Steps to reproduce the issue:

1. place starter block
2. place functional block
3. go to limb select

![20240614112918_1](https://github.com/tsunamayo/Starship-EVO/assets/32307665/82eb5198-7675-4564-ad92-8d731b7d8d60)

### Environment
- Starship EVO version: 20w24b - mech preview
- Graphics Card: NVIDIA 3060 Strix

**Comment by tsunamayo** [comment]
@drimmel247 It was a bug on the display code, so it could have impacted other dropdown setting too. Thanks!
