### ISSUE TITLE
[Survival] Rotator and Hinges cannot duplicate

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5807]
### Short Description of the issue:
was trying to create a Vtol engine with the use of hinges and rotator, but for some reason it doesn't get copy pasted using the copy paste tool though I had enough resources, As shown in the video I tried separating each parts to test it out, it seems the rotator and Hinge have the issue of not duplicating with the copy-paste tool
...

### Steps to reproduce the issue:
try using the copy-paste tool on hinges and rotators

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

added the video here
https://file.io/rm1N3yfvYWCN

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player.log](https://github.com/user-attachments/files/15841286/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/15841287/Player-prev.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.
[Starship.zip](https://github.com/user-attachments/files/15841299/Starship.zip)

**Comment by tsunamayo** [comment]
@surajnairpv Hi, thanks for spotting that, issue is fixed in 24w25a. Cheers
