### ISSUE TITLE
[Mech] after run wrong idle position 

### ISSUE THREAD

**Issue by Tackietacktack** [tsunamayo/Starship-EVO#5808]
### Short Description of the issue:
run and stop, now  you get a wrong idle position.
the forward feet get the bug. if the left feet is forward it get in left feet a bug and if the right feet is forward it get in right feet a bug. middle position both.

mech was build before  24w24a.

https://github.com/tsunamayo/Starship-EVO/assets/97230091/b3538871-07ea-477b-83cc-311512b37235

### Steps to reproduce the issue:
run ,stop, run, stop

### Environment
- Starship EVO version:  24w24b
- Graphics Card:  NVIDIA GeForce RTX 2060

Blueprint:
[mechi 8.zip](https://github.com/user-attachments/files/15841495/mechi.8.zip)

**Comment by tsunamayo** [comment]
@Tackietacktack I see you built the rotator pointing upward and not downward, I guess that would be the culprit. I will see what I can do.

**Comment by tsunamayo** [comment]
@Tackietacktack Hi, issue is fixed for 24w25a. Cheers
