### ISSUE TITLE
[Bug] Ship spins out of control when spawned (ship specific)

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#5809]
### Short Description of the issue:

When spawned from a starter block near a ring habitat, a planet, or in space, this ship will spin out of control.

I have been building the ship across many play sessions. The version existing in the world behaves properly, like any other ship.

Based on brief testing, this does not appear to affect other ships.

### Steps to reproduce the issue:

1. Place a starter block in space (not on terrain)
2. Choose this blueprint and spawn it
3. Attempt to observe the ship as it spirals out of control

### Environment
- Starship EVO version: 24w24b (default branch - still incorrectly labeled in game as 24w20b)

### Additional information:

Habitat:

https://github.com/tsunamayo/Starship-EVO/assets/10069469/299b9743-9c34-4c6b-9219-b0d3be8ac078

Planet:

https://github.com/tsunamayo/Starship-EVO/assets/10069469/69ddd14b-a48a-4cbd-9b66-e2b0fba27f7a

BP:

[Galapagos.zip](https://github.com/user-attachments/files/15847883/Galapagos.zip)

A crash, unsure if related:

[Player.log](https://github.com/user-attachments/files/15847901/Player.log)

**Comment by Haakon-0** [comment]
In my case, this only happens under the influence of gravity, not in space.
It happens with all ships, all sizes.
Ships spawned with the starter block on ground do also get launched.
I'm currently playing in the 24w20b early-access version.

https://github.com/tsunamayo/Starship-EVO/assets/172929497/827f41a5-4dad-4e30-9a66-551a56f3bd37

https://github.com/tsunamayo/Starship-EVO/assets/172929497/0b0220e6-d83b-417e-9774-84c4f25abeec

**Comment by tsunamayo** [comment]
@asanagisae Hi, does this ship have anything specific or out of the ordinary? weapon stand, weird mechanism or else?

**Comment by tsunamayo** [comment]
@asanagisae Nevermind I have found the culprit, the power cell. This issue should have been fixed, so I am looking into it.

**Comment by tsunamayo** [comment]
@asanagisae Issue fixed for 24w25a. It was because you built it on a children entity, and it was colliding with the main entity. Cheers
