### ISSUE TITLE
[MECH] start time set to .16

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#5810]
### Short Description of the issue:
the whole right limb is automatically off by .16
![image](https://github.com/tsunamayo/Starship-EVO/assets/56371294/6c9eddb3-805a-473e-ae7d-fcf48b274dd0)

### Steps to reproduce the issue:
might have something to do with toggling animation symmetry? 

### Environment
- Starship EVO version: 24w20b

### Additional information:
![image](https://github.com/tsunamayo/Starship-EVO/assets/56371294/b9680123-5089-4150-9bb5-18d2df3ee44b)
typing 0 for the second time does this, not sure why
[Player.log](https://github.com/user-attachments/files/15854973/Player.log)

**Comment by tsunamayo** [comment]
@TIKIRobo Hi, issue is fixed for 24w25b. We need a key at 0.5 so that the other side is garanted to start at 0.
