### ISSUE TITLE
[MECH] Bug causes timing issues in animation leading to "kick"

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#5811]
### Short Description of the issue:

#5810 again but there's no visible change in the timing, at time less than .25 the right leg of the mech resets to the default position (0) making it look like its kicking back

### Steps to reproduce the issue:
not sure but it does seem to be some sort of issue with the mirror function 
...

### Environment
- Starship EVO version: 24w20b

### Additional information:

https://github.com/tsunamayo/Starship-EVO/assets/56371294/3c044f69-0ba5-442d-9bd0-f687b2bde250

[Test Farm Mech 1.zip](https://github.com/user-attachments/files/15855688/Test.Farm.Mech.1.zip)
[Player.log](https://github.com/user-attachments/files/15855690/Player.log)

**Comment by TIKIRobo** [comment]
![image](https://github.com/tsunamayo/Starship-EVO/assets/56371294/1d4b14d7-a181-482d-9075-fa602a26947f)
after a restart these .25 appeared which i believe may be messing things up since we cannot edit the greyed out boxes (what im thinking is that the game just assumes everything between T:0-.25 must be 0)

**Comment by tsunamayo** [comment]
@TIKIRobo Hi, same bug as your other one, it is now fixed. Thanks!
