### ISSUE TITLE
[Mech] Idle key frames overwrite walk key frames

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#5812]
### Short Description of the issue:

Once conditions are met, you can no longer edit the walk animations for a particular mech.

This issue persists after a restart.

If you delete the mech computer and go through the steps again, the issue persists and is identical/repeatable.

### Steps to reproduce the issue:

I don't know if other steps can cause the issue, but I have documented the steps in the video below.

1. Load this BP, or perhaps another that is affected
2. Note: the vehicle is functionally complete and mechanisms will already be in place
3. Place the mech computer
4. Set the symmetry mode to "none"
5. Link mech computer to the joints in order: arm left, hip left, hip right, knee left, knee right, foot left, foot right, shoulder left, shoulder right.
6. Configure the animation as follows:
7. Walk: arm left to 20
8. Idle: hip right, knee right, foot right, shoulder right to 90
9. Walk: hip right, knee right, foot right, shoulder right to 22 (this is where it fails)
10. Observe that the walk preview in this step no longer updates to the new value

At this point, changes to idle tracks will overwrite what's in their walking counterparts.

Note: When you select "walk" from the dropdown the last time, both "walk" and "idle" have checkmarks. Very odd.

### Environment
- Starship EVO version: 24w24b (mislabeled as 24w20b in game still)

### Additional information:

https://github.com/tsunamayo/Starship-EVO/assets/10069469/02ed35d3-4232-4238-ab48-0b21e4f6c942

[Mechaseat.zip](https://github.com/user-attachments/files/15855849/Mechaseat.zip)

**Comment by TIKIRobo** [comment]
Can verify this is an isssue with other mechs

**Comment by tsunamayo** [comment]
@asanagisae I am sorry the rotator limb setting are not making sense, also I am not sure how I should set them up.
Can your reproduce the issue when the config is done after a reload?
If yes just send me the blueprint already setup.
same for @TIKIRobo if you have such a corrupted bp send it my way.
Thanks

**Comment by TIKIRobo** [comment]
@tsunamayo i just tested it with a random mech off the workshop

specifically this one:
https://steamcommunity.com/sharedfiles/filedetails/?id=3266152473

**Comment by asanagisae** [comment]
Hello @tsunamayo

Yes.

This version of the bp should have the mech computer with everything linked up. The issue persists after a reload of the game, and it also presents itself when the bp is spawned from a fresh starter block.

[Mechaseat.zip](https://github.com/user-attachments/files/15871079/Mechaseat.zip)

**Comment by tsunamayo** [comment]
@asanagisae @TIKIRobo Hi, issue is fixed for 24w25a. Cheers
