### ISSUE TITLE
[Mech] Cannot add keyframes to walk animation

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#5817]
### Short Description of the issue:

Under certain conditions, you cannot add keyframes to the walk animation for a mech.

### Steps to reproduce the issue:

1. Spawn this mechaseat blueprint if it is not currently in the world.
2. Open the mech computer in the back, switch to walk animation.
3. Follow these steps for the "knee right" track:
4. If there is a frame for 0.75, add a frame for 0.65 - the one at 0.75 will disappear.
5. If there is a frame for 0.65, add a frame for 0.75 - the one at 0.65 will disappear.
6. Repeat steps 4 and 5 as much as you like.

### Environment
- Starship EVO version: 24w25a [mech preview]

### Additional information:

https://github.com/tsunamayo/Starship-EVO/assets/10069469/4f4d56a5-bdb5-424e-8463-56420fbfd26a

The blueprint:
[Mechaseat.zip](https://github.com/user-attachments/files/15906160/Mechaseat.zip)

**Comment by asanagisae** [comment]
With a little more testing, it appears that the issue is this: If you want a 0.5 frame in your animation, it must be the _last_ frame you add.

**Comment by tsunamayo** [comment]
@asanagisae Indeed, this is fixed for 24w25b. I ll try to push asap as it is rather blocking.
