### ISSUE TITLE
[Mech] Max time on animation changed from 1 to .75

### ISSUE THREAD

**Issue by drimmel247** [tsunamayo/Starship-EVO#5819]
### Short Description of the issue:

while adding and removing key frames, I noticed that the 1 second keyframe got changed to 0.75 frame. Additionally if you exit the menu and go back the 1.0 key frame will show up again in addition to the new keyframe. 

### Steps to reproduce the issue:

1. spawn mech
2. add and remove key frames changing values for both angle and time. 

### Environment
- Starship EVO version: 24w25a - mech preview
- Graphics Card: NVIDIA 3060 Asus Strix

### Additional information:
Please look at left hip. 
Screenshot:  ![20240619230924_1](https://github.com/tsunamayo/Starship-EVO/assets/32307665/ef91a749-301e-45d0-bf5d-0deb04d59900)
player log:  [Player.log](https://github.com/user-attachments/files/15908302/Player.log)

testable blueprints:

[Gundam Exia.zip](https://github.com/user-attachments/files/15908315/Gundam.Exia.zip)
[Gundam Frame.zip](https://github.com/user-attachments/files/15908316/Gundam.Frame.zip)

animations: 
Exia run animation: [exia run.txt](https://github.com/user-attachments/files/15908334/exia.run.txt)
frame run animation: [run.txt](https://github.com/user-attachments/files/15908335/run.txt)

**Comment by tsunamayo** [comment]
@drimmel247 I cant reproduce that bug, I think it might have been correct. Thanks
