### ISSUE TITLE
[Suggestion] Mech leg movement order option

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#5821]
Hi there,

so I build this 8 legged prototype. Right now all the legs move at the same time for each side, see this vid of it's walking animation:

https://github.com/tsunamayo/Starship-EVO/assets/81495956/be69ae10-64d4-4fe1-b0c5-1bf1abbd3c19

However, I want the legs to move in a different order (with an offset). See this pic: 

![8LegMech_1](https://github.com/tsunamayo/Starship-EVO/assets/81495956/83d1500a-a44d-45d2-be8e-5db747aea76f)

I either don't know how to set my Mech up to achive this, or this is just not a feature yet.
Maybe we could get another option for Rotors/ Hinges that would let us set the order for this leg manually? We could use this just like the custom label for the event gate, i.e. 1,2,3,4 etc. This could look something like this: 

![8LegMech_2](https://github.com/tsunamayo/Starship-EVO/assets/81495956/be7e23f0-9bf2-4c53-a8f1-5cff2a00a06a)

I think this could become a great option for more-legged walkers to make their movement more relatable.

Here's the BP for this prototype:
[MEch5.zip](https://github.com/user-attachments/files/15918942/MEch5.zip)

**Comment by tsunamayo** [comment]
@BigBadKangaroo Well I am not sure to understand what you need, I will support the standard case for biped, but give the manual animation edit for case like that. I dont really see what you mean by order or 4, does that mean a feet stays on the ground for 0.75t and then move for 0.25t? 
I think there is plenty of way to move a walker with 4+ legs, honestly I dont really plan to support those. What you can do for now is to set them up like this for example: 
Right side: 1) Right 2) Left 3) Left 4) Right
Left Side: 1) Left 2) Right 3) Right 4) Left

But the beauty of the animation template is that if you dont want to spend time creating a walk you can simply re-use an animation made by somebody else. All you need to do is imput the right idle stance and the game will adjust the rest.

Cheers

**Comment by asanagisae** [comment]
When you do "Left to Right" mirroring, you take the left animation, shift the frames over by 0.5t, and label that "right". I believe Kangaroo is asking for the ability to have more than just left and right, to have sets labeled 1 to 4, and have sets 2-4 be offset from set 1 by 0.25, 0.5, and 0.75 respectively.

This type of feature would help in many ways, such as for a horse's gallop. Horses will hit the ground with all four feet in succession, then, float through the air for a time, then hit the ground with all four feet again. Offsets of 0, 0.2, 0.4, and 0.6 for the legs would very easily replicate a gallop, only needing to animate one or two legs.

**Comment by tsunamayo** [comment]
@asanagisae well as it it seems a bit complicated, I will see if I can change my symmetry implementation.
It would means we would have to import the symmetry setting of the template pattern as animation for the other side would not be generated by the algo, the symmetry would be computed on the fly. I dont think it is a big deal.

**Comment by BigBadKangaroo** [comment]
Yeah, I think I didn't really explain all that great what I meant. I'll just try to get more comfortable with animating to get what I try to achive.
My bad, sorry for the confusion then.
