### ISSUE TITLE
[Suggestion(Maybe?)] Potential fix to the CE Disappearing "glitch"

### ISSUE THREAD

**Issue by Timtee** [tsunamayo/Starship-EVO#5825]
I make this issue as of today mostly cause I may have hit a bit of a brainwave moment in regards to what may be causing the issue with child entities disappearing upon world load(especially when there are a bunch of them present.)

My thought is that, it's not anything to do with blueprints persay, but rather, how the game handles loading in ships upon world load, which is to say, If the game tries to load all child entities present all at once upon world load, that then such may be the source of the fault.
A way to fix this would be to individually load each child entity at a time, which.... could take a bit longer to do, but depending on the speed of the physical drive the game is installed and running on, would affect how long that takes.

Additionally is a suggestion for protection against child entities disappearing from both a ship in a world, and in a saved blueprint by the same name or entity uid or whatever. Which is - If the blueprint is older than said version of the ship in the world, then the blueprint should have an automatic protection against the child entity or entities, being removed off of it by the game. Thus saving many hours of work for many people.
This would also have to ensure that if a given copy of the ship is older than the blueprint, that a check has to be put in place to compare the blueprint and ship, to ensure that it isn't just a corruption on one version and not both or otherwise.

The primary reason why I even have typed all of this out, is because... I'd love to make a unique ship idea I got today in Sevo but... due to the CE disappearing issue, I can't exactly risk it with the size of the ship, Besides, if you can figure out how to implement/fix all of this Tsuna, then all of us, every single player who has had to deal with the issue, or fears having to deal with it, will be grateful for your work to fix it once and for all.

Also relative to the original report on the issue since well... yeah.
https://github.com/tsunamayo/Starship-EVO/issues/5695

**Comment by ProPeach** [comment]
Could this issues covered in #5695 be caused by the fix for #5436? That talks about deleting child entities if they showed that corruption bug, which could explain why so many builders are getting disappearing CEs recently and losing progress

**Comment by Timtee** [comment]
It might be yeah, that might be part of what is causing it to, is that it's not... really a good solution. Since it more often than not, just randomly will yeet a given child entity upon world load anyways. That and since Unity is Unity... Anything that such a thing would see as a potential corrupted bit, it will yeet. Even stuff that isn't actually corrupted.

**Comment by tsunamayo** [comment]
@ProPeach Hi, so there has been a lot more CE deleted recently?

**Comment by ProPeach** [comment]
@tsunamayo it's affected quite a few builders as you can see in the replies to #5695 yeah. It still seems relatively rare, it's only happened to me once as far as I know but as you can imagine it is very disheartening to people to have the potential to lose a big chunk of their build, so people are hearing about it and getting concerned

**Comment by asanagisae** [comment]
I've lost parts from 2 ships in the last 2 weeks, one in a mech preview world and one in a default branch world. They were parts of medium complexity with more attached entities.

Recently, we've had high profile players just give up and stop playing (like Coconut) because of this bug.

**Comment by tsunamayo** [comment]
> I've lost parts from 2 ships in the last 2 weeks, one in a mech preview world and one in a default branch world. They were parts of medium complexity with more attached entities.
> 
> Recently, we've had high profile players just give up and stop playing (like Coconut) because of this bug.

Okay dont hesitate to bring that kind of info to me when there is a serious bug. I was not aware that was a regression. It is fixed for 24w26a. Cheers
