### ISSUE TITLE
Ship becomes uncontrollable

### ISSUE THREAD

**Issue by thriple** [tsunamayo/Starship-EVO#5827]
### Short Description of the issue:

Adding new block causes ship to teleport a short distance away. Trying to fly ship causes it to warp to Mm or C speeds. Leaving controls after that, ship becomes un-interactable. 

Removing power cells > save blueprint > update ship by adding random block - seems to fix it.

...

### Steps to reproduce the issue:

Add powercell chargers / powercells
Save blueprint
Restart game
Fly current ship / respawn ship and try to add new blocks

...

### Environment
- Starship EVO version: 24w25b
- Graphics Card: RTX 3050

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

https://www.youtube.com/watch?v=XSDSccQMFg8 - unlisted

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Shuttle.zip](https://github.com/user-attachments/files/15948777/Shuttle.zip)

[Player.log](https://github.com/user-attachments/files/15948778/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/15948779/Player-prev.log)

**Comment by tsunamayo** [comment]
@thriple Hi, actually it was not related to power cell but to the new center of gravity logic. Issue fixed for 24w26a. Cheers
