### ISSUE TITLE
[Mech] Feet vibrating while trying to auto level

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#5828]
### Short Description of the issue:
See videoes, when the mech is stationary the feet are vibrating between positions. The first video shows that even on quite flat terrain, the feet vibrate

https://imgur.com/DwRPb0a
https://i.imgur.com/a4wPpK4.mp4

In this screenshot, the feet are still vibrating while trying to level with the ground. But this results in the foot on higher ground attempting to sit at a strange angle as shown. 
![711980_20240624143429_1](https://github.com/tsunamayo/Starship-EVO/assets/27857711/e89e9ae6-8a74-4927-8b10-a1680a251eae)

A more "natural" looking stance that took into account would require the hip joint to change its angle and raise the knee, like in this image.
![image](https://github.com/tsunamayo/Starship-EVO/assets/27857711/c64faa11-3426-41f1-9c17-210f987d9ebf)

Is this kind of thing possible to work into the auto leveling feature? It seems like some of the issues with the current angle IK are caused by the fact that the knee cannot move up/down to allow the foot to stay in contact with the ground. So the foot cannot actually find a nice angle to rest at because the height of the foot off the ground is fixed

### Steps to reproduce the issue:
- Load attached bp
- Control it on a surface

### Environment
- Starship EVO version: 24w25b
- Graphics Card: RX 6700XT

### Additional information:

[TIEm Mech Heavy Legs Walkin'.zip](https://github.com/user-attachments/files/15956529/TIEm.Mech.Heavy.Legs.Walkin.zip)

**Comment by asanagisae** [comment]
I think the auto leveling feature should be opt-in per joint.

The UI doesn't tell you that it will try to level feet joints for terrain, and only feet joints. Plus, for true IK, you need to have more than one joint available for inverse kinematic calculations. A checkbox per joint type would solve both problems.

As Peach said, sometimes you want the hips to assist with raising the leg on uneven terrain.

**Comment by BigBadKangaroo** [comment]
Can confirm, this happend to me aswell:

https://github.com/tsunamayo/Starship-EVO/assets/81495956/bbf038cb-d337-416e-80d7-aabf7e9df4cd

**Comment by tsunamayo** [comment]
@BigBadKangaroo @TIKIRobo Please send me your bp so I can check.
Yes I will add an option for the feet auto-adjust for custom join.
I still need to work on the auto-leveling of feet for uneven terrain, it is not really IK, it is more flexing the feet until both legs hit the ground. 
Not sure if it explains all of your issues, actually pretty sure it doesnt, hence I want to have a look at your mechs.

**Comment by BigBadKangaroo** [comment]
@tsunamayo Hi there, here it is:
[KF-Hover-Cart II MECH.zip](https://github.com/user-attachments/files/15975372/KF-Hover-Cart.II.MECH.zip)

**Comment by tsunamayo** [comment]
@ProPeach and all, issue is fixed for 24w26a. No more vibrations, better feet orientation that works with any rotator orientation (like your mech @ProPeach), and one leg will squat to level up the mech.


Uploading AF97F410-A937-40E1-8A7B-DE6B7721B247.MP4…

Cheers
