### ISSUE TITLE
[Mechs] Mech aims down, walks into the ground

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#5829]
### Short Description of the issue:
Testing out TwoNiners fantastic starter mechs, and this Strider likes to nosedive into the ground when walking up a slope
https://imgur.com/a/RO0xcNt

### Steps to reproduce the issue:
- Spawn the Attached mech
- Walk up a hill 

### Environment
- Starship EVO version:  24w25b
- Graphics Card: RX 6700XT

### Additional information:
[Starter.mechs.zip](https://github.com/user-attachments/files/15956826/Starter.mechs.zip)

**Comment by TwoNiner29** [comment]
Hey Peach, I've noticed the same issue too, however, I've also noticed that pointing the camera up seems to prevent that, not sure if it's consistent on your end, but overall, it's a weird bug. Could you try and see if it happens for you too?

**Comment by ProPeach** [comment]
Cheers TwoNiner, I gave it a try but aiming up with the mouse didn't seem to change anything, at least with this angle on the terrain. It still pitched down and forced the camera under the terrain.

For referenece to the gravity point, this is the "Earthlike" planet in the starter system which is at 0.8g, so pretty weak on average I suppose, I can definitely believe the affect is worse with stronger gravity

**Comment by tsunamayo** [comment]
@ProPeach Okay I am gonna have a look at it.
@asanagisae As it is related to gravity can you send me your world too?
Also did both of you did not enter a seat before controlling the mech? I know I have a player seating position issue to fix but that seems worse...

thanks

**Comment by asanagisae** [comment]
Hey, here's the world with a vehicle and planet set up. 

[Mechatro WeGo.zip](https://github.com/user-attachments/files/15962624/Mechatro.WeGo.zip)

The blueprint from 2 messages up seems like an older copy with the speed set to 0. It's fixed in this world.

The mech control stick is the one on the right. Just move forward for 5 seconds in a random direction, slightly uphill works better.

**Comment by tsunamayo** [comment]
@ProPeach Hi issue is fixed for 24w26a. @asanagisae I dont think it is the same issue, it seems to just be a normal physics behaviour, as there is no animation and no foot logic on the mech you sent me. 
Cheers
