### ISSUE TITLE
[24w20b] Incorrect door opening orientation in Starting Space Station

### ISSUE THREAD

**Issue by Gorwyn** [tsunamayo/Starship-EVO#5837]
### Short Description of the issue:

When opening a specific door on the Starter Space Station, it opens downwards into the ground instead of upwards like the rest of the doors in the prebuilt station. 

### Steps to reproduce the issue:

⦁	Start a new Creative world
⦁	Skip the tutorial
⦁	At the first junction, turn left
⦁	Open both sets of doors and pass through the airlock
⦁	Open the door directly across from the coffee stand
⦁	Observe that the door opens downwards into the ground

### Reproduction rate:
3 out of 3.

### Environment
- Starship EVO version: 24w20b
- Graphics Card: 3080ti

### Additional information:

[Player.log](https://github.com/user-attachments/files/16024468/Player.log)

https://github.com/tsunamayo/Starship-EVO/assets/171508159/2a663847-9376-42ae-95dc-5ba815318903

P.s. I realise several versions may have gone by, but I did this bug report for a QA Job application and forgot to send it to you as well. I hope it helps!

**Comment by Crimson-Artist** [comment]
It might be a problem with that specific station segment. The door orientations are dependent on the what side of a block you are looking at when you place the door. whoever built the prefab stations bits probably forgot to keep them all consistent

**Comment by tsunamayo** [comment]
Yes sorry thanks for pointing out, I wont fix it though we will have to live with that!
