### ISSUE TITLE
No survival mode option

### ISSUE THREAD

**Issue by MushDropRevive** [tsunamayo/Starship-EVO#5838]
### Short Description of the issue:
Can't switch to survival mode on character creation

### Environment
- Starship EVO version: betas [experamental] on steam settings

**Comment by TIKIRobo** [comment]
you have to be in the survival beta to gain access to the survival mode #5464 
i see you have since posted a request so you'll just have to be patient, Tsuna works on japan time so he's just gone to sleep

**Comment by MushDropRevive** [comment]
> you have to be in the survival beta to gain access to the survival mode #5464 i see you have since posted a request so you'll just have to be patient, Tsuna works on japan time so he's just gone to sleep

Thank you 
Blessed !

**Comment by tsunamayo** [comment]
@MushDropRevive Sorry I will do a second wave of survival tester shortly, I need to add a few things first, I will keep you posted. Thanks

**Comment by MushDropRevive** [comment]
> @MushDropRevive Sorry I will do a second wave of survival tester shortly, I need to add a few things first, I will keep you posted. Thanks

Hi, 
Hope you're well,
I can't wait until then,
sounds great.

thank you
