### ISSUE TITLE
[Mechs] Imported Walk Template has missing/broken keys

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#5841]
### Short Description of the issue:
I made a silly mistake, and placed my Mech Computer below the mech for easy access while working out the walk cycle, now it's time to move it into the main body.

But there is missing key information when I export/import the MechAnimation file into the newly placed Mech Computer

Here is the original Mech Animation
![image](https://github.com/tsunamayo/Starship-EVO/assets/27857711/199a761a-757c-4aa0-b6a8-6beb09ca6135)

Here is the same Animation file, after being exported and loaded into the new Mech Computer
![image](https://github.com/tsunamayo/Starship-EVO/assets/27857711/a9782c5a-4395-47b1-b0f8-4fd949ca9d64)

Keys are missing and angles have been changed, meaning the resulting animation is wrong. I have only linked up one leg for this video for ease, but the same issue occurs if you link up all joints
https://imgur.com/InciBF8

This is what the mech animation should look like
https://imgur.com/a/OXBGATJ

### Steps to reproduce the issue:
- Load attached bp
- Export the Animation in the Mech Computer, or you could use the attached MechAnimation file
- Delete the Mech Computer
- Place another Mech Computer, link up one leg (9 Joints per leg)
- Select the MechAnimation file in the Computer to import it and view the broken/missing keys  

### Environment
- Starship EVO version: 24w26a
- Graphics Card: RX6700XT

### Additional information:
bp
[Dwarf Spider Droid.zip](https://github.com/user-attachments/files/16034599/Dwarf.Spider.Droid.zip)
Animation File
[Dwarf Spider Droid Test.zip](https://github.com/user-attachments/files/16034604/Dwarf.Spider.Droid.Test.zip)

**Comment by BigBadKangaroo** [comment]
Can confirm, this happend to me aswell

**Comment by tsunamayo** [comment]
@ProPeach @BigBadKangaroo I think the issue might lies with the idle position. You must make sure that your idle position is matching the older one first.

This is because this is a walk animation import tool made to be retargeted to a different mech with potentially a very different idle position. 

I was thinking of storing the idle position inside the rotator, and having a button to fetch idle position from current rotator angle, I think it would facilitate what your are doing, what is your take on that?
We would get: a field "mech idle angle" inside the rotator, and a "Assign idle position from current rotator angle" button inside the mech computer window, so you would press that button first, and then import the walk anim.

**Comment by ProPeach** [comment]
@tsunamayo being able to import the idle position from a rotators current angle was actually something I was wondering about too, so I would definitely support it. So far, I've been manually setting each joint to an angle to work out what looks nice for the leg, and then once happy copying these angles into the Mech Computer for the Idle stance. An import button to do that copying for me would be brilliant

**Comment by BigBadKangaroo** [comment]
@tsunamayo Hi there,

to be able to set the idle position of each limb by just pushing a button in the menu sounds great. Could be a nice QoL thing.

But wouldn't it be possible to import/export the idle position of the animation that you're saving, too? 
I mean, you can already save the walking animation, why not saving the idle position within the same animation save?
So you can import a complete animation for a mech, export it to the new/different mech, load it in and everything (idle+walking) is ready to go. Wouldn't that be easier?

**Comment by tsunamayo** [comment]
> @tsunamayo Hi there,
> 
> to be able to set the idle position of each limb by just pushing a button in the menu sounds great. Could be a nice QoL thing.
> 
> But wouldn't it be possible to import/export the idle position of the animation that you're saving, too? I mean, you can already save the walking animation, why not saving the idle position within the same animation save? So you can import a complete animation for a mech, export it to the new/different mech, load it in and everything (idle+walking) is ready to go. Wouldn't that be easier?

Nope that is more complicated to do from my side, also the use seems really niche and not what it was designed for. If I understand correctly you want to destroy your computer and place it elsewhere while keeping the animation? Cant copy/paste do the job?

**Comment by tsunamayo** [comment]
@ProPeach @BigBadKangaroo Okay I have made the button change for 24w27b. Cheers

**Comment by BigBadKangaroo** [comment]
> > @tsunamayo Hi there,
> > to be able to set the idle position of each limb by just pushing a button in the menu sounds great. Could be a nice QoL thing.
> > But wouldn't it be possible to import/export the idle position of the animation that you're saving, too? I mean, you can already save the walking animation, why not saving the idle position within the same animation save? So you can import a complete animation for a mech, export it to the new/different mech, load it in and everything (idle+walking) is ready to go. Wouldn't that be easier?
> 
> Nope that is more complicated to do from my side, also the use seems really niche and not what it was designed for. If I understand correctly you want to destroy your computer and place it elsewhere while keeping the animation? Cant copy/paste do the job?

Hi there,

well, this is somewhat correct.
However, I mainly thought of:
-building a mech 
-saving the "done" animation
-build a new mech with the same leg layout (hinges at the same place, but maybe a longer leg / different leg design while the "skeleton" of the mech stays the same, so every moving part has the same way of moving) 
-import the animation
-"ready-to-use" the old animation for the new (bigger, better) mech

But if it is more complicated on your end, then don't bother too much about it. Simply saving the entire BP and copying the walking animation by looking it up in the mech computer and switching between the old and new mech works fine for me. Just takes some time.
