### ISSUE TITLE
[[Bug] Pipe GUI info is missing

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#5842]
### Short Description of the issue:
Talking about flow rate in Discord and I realized that this gui item on the right of this old screenshot - 
![image](https://github.com/tsunamayo/Starship-EVO/assets/27857711/bffcbd2d-9b10-499d-8140-56af4062f94c)
Is now missing - when you look at a pipe with a pipe in your hand, it does not show. Same with a link tool
![image](https://github.com/tsunamayo/Starship-EVO/assets/27857711/6ca2838a-8c4f-4ec3-9027-12ceb963121d)

### Steps to reproduce the issue:
- Place a pipe
- Look at it with a pipe in your hand

### Environment
- Starship EVO version: 24w26a
- Graphics Card: RX6700XT

**Comment by tsunamayo** [comment]
@ProPeach Hi, issue fixed for 24w27b. Cheers
