### ISSUE TITLE
Missing screen resolution values after initial resize.

### ISSUE THREAD

**Issue by TipJar420** [tsunamayo/Starship-EVO#5844]
### Short Description of the issue:
From Options > Graphics > Screen Resolution >  - Screen Sizes - 
The Screen sizes disappear when switching to Windowed, making it harder to choose the correct numbers.
...

### Steps to reproduce the issue:
Try and Choose a Screen Resolution after picking one originally. < I just mean it normally happens when you do not like the original size and try to re-size again. The first time it does show up yes,...
...

### Environment
- Starship EVO version: 24w26
- Graphics Card:  nVidia 3070 Lappy

### Additional information:
Not a huge thing, just professional.

_(Screenshots, Videos, Error logs, Related issues)_
![Screenshot 2024-06-29 092448](https://github.com/tsunamayo/Starship-EVO/assets/33830011/4804b684-f7fa-43de-ab6c-3dc8096baa01)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Player.log](https://github.com/user-attachments/files/16039472/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@TipJar420 Hi, issue is fixed for 24w40a. Cheers

**Comment by najlitarvan** [comment]
so the drop down for resolution not showing up is fixed, but dropdowns in block UIs not showing up still persists even in the newest experimental
![image](https://github.com/user-attachments/assets/f5e39a4f-6e74-4a1f-b9f1-23646f4a8ddf)
