### ISSUE TITLE
[Bug] F4 mech third person camera settings are ignored + maximum zoom is incorrect

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#5845]
### Short Description of the issue:

A few features related to third person (F4) do not fully function for mechs as they do with space ships.

**Issue 1**: The third person camera distance numbers (configured on the ship codex page) are ignored for mechs.

**Issue 2**: The maximum distance you can move back with the scroll wheel in third person camera is short, and cannot accommodate horizontally-larger mechs (around 30m long from head to tail, or more). I am unsure if this affects all mechs or just mechs that have a tiny parent entity, consisting of mostly child entities on mechanisms.

I checked space ships for comparison. Space ships don't let you scroll to zoom in/out, they use the configured third person camera distance in the codex.

### Steps to reproduce the issue:

Issue 1:

1. Spawn a mech with a starter block, or place a block on a mech to make it the current entity
2. Open its details in the codex, adjust the third person camera distance forward/up with values greater than zero
3. Control the mech and switch to third person (F4), observe that your settings are ignored
4. Try a few more setting combinations to confirm that your settings are ignored

Issue 2 might not need to be addressed if issue 1 is fixed (and the codex settings take over), but this is how to test:

1. Take control of a mech, switch to third person (F4)
2. Use the mouse wheel to scroll down, moving the camera as far back as possible
3. Observe that the maximum distance is not far enough for longer mechs (30m long or longer)

### Environment
- Starship EVO version: 24w26a

### Additional information:

![image](https://github.com/tsunamayo/Starship-EVO/assets/10069469/c50ac055-9621-4d7d-89c4-c16fd11c5505)

**Comment by tsunamayo** [comment]
@asanagisae Yes I noticed that too, I will fix it. We also dont have any freelook.

**Comment by asanagisae** [comment]
Now you have an issue number to tie to the release notes 😄

**Comment by tsunamayo** [comment]
@asanagisae Thanks indeed, issue fixed for 24w27a. Cheers
