### ISSUE TITLE
symbol scale looks wrong

### ISSUE THREAD

**Issue by Tackietacktack** [tsunamayo/Starship-EVO#5850]
### Short Description of the issue:
Some symbols have pixels that feel large.

![Starship EVO 02 07 2024 16_24_14](https://github.com/tsunamayo/Starship-EVO/assets/97230091/6670ce06-73af-4d68-9f89-05ab6b94ce94)

![Starship EVO 02 07 2024 16_31_14](https://github.com/tsunamayo/Starship-EVO/assets/97230091/eb8e2f58-4b45-43b9-9b2b-b587d7cd0f8e)

### Steps to reproduce the issue:

- Starship EVO version: 24w27a
- Graphics Card:

**Comment by asanagisae** [comment]
I can confirm that symbols appear distorted in the latest build - 24w27a

![image](https://github.com/tsunamayo/Starship-EVO/assets/10069469/963db8f2-feaa-44ea-9dc5-88a8beac9f42)

These symbols were smooth in previous builds.

**Comment by tsunamayo** [comment]
Yeah it is a weird issue I will repush a build.

**Comment by tsunamayo** [comment]
done!
