### ISSUE TITLE
[Bug] Mech Joints Can't be Painted

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#5853]
### Short Description of the issue:
Painting a Mech Joint does not change its colour

### Steps to reproduce the issue:
- Place a Mech Joint
- Try and paint it

### Environment
- Starship EVO version: 24w27a
- Graphics Card: RX 6700XT

**Comment by tsunamayo** [comment]
@ProPeach Issue fixed for 24w27b. Cheers
