### ISSUE TITLE
[Bug] mech pulls knee up unnecessarily

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#5855]
Hi there,

the mech pulls up it's knee to adjust to the terrain, even when the terrain is flat.
It's always either one of the legs, left or right (full set of hip, knee, ankle)
I couldn't get this repilcated with a mech that uses only custom joins.
I tested a few mechs:

https://github.com/tsunamayo/Starship-EVO/assets/81495956/17e61bd4-3d11-4f61-ad52-665d09b4169d

![20240703205536_1](https://github.com/tsunamayo/Starship-EVO/assets/81495956/eec730d9-6cd8-480e-a8ec-4b8bcdd9d5ef)
![20240703205634_1](https://github.com/tsunamayo/Starship-EVO/assets/81495956/86321ce5-4ced-4976-8011-f96c4b8ef638)
![20240703210026_1](https://github.com/tsunamayo/Starship-EVO/assets/81495956/1d6b5bf3-bfba-46d9-b4cb-750ed7b959e1)
![20240703210159_1](https://github.com/tsunamayo/Starship-EVO/assets/81495956/8a0b24ed-c68a-482b-9375-33082a5a70f5)
![20240703210211_1](https://github.com/tsunamayo/Starship-EVO/assets/81495956/11e20e17-3d0a-4954-8c30-8a5cd83c351f)
![20240703210328_1](https://github.com/tsunamayo/Starship-EVO/assets/81495956/6459f699-653c-4ff1-a665-31f9fd10a964)

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, issue is fixed for 24w27b. Cheers
