### ISSUE TITLE
[Suggestion] Orientation indicator for Saddle Seat

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#5860]
Thanks for tweaking the Saddle Seat pose! It's a lot more natural and energectic now

One thing that would help use it is an orientation wiget in the placement ghost, as you can't tell which way the player will sit forward on it just by looking at the seat. Something like the arrows on a Yoke.

The Ottoman could also benefit from this as it is also symmetrical

**Comment by tsunamayo** [comment]
@ProPeach Indeed, done for 24w28a. Cheers
