### ISSUE TITLE
[Bug] 24w27b- Standing Seat + Joystick teleports the player into the parent entity

### ISSUE THREAD

**Issue by Crimson-Artist** [tsunamayo/Starship-EVO#5861]
A weird bug with the standing seat. Apparently when you link it to a joystick and try to enter it the player will be teleported inside of the parent entity. clipping through it. This bug is exclusive to the joystick cuz linking the standing seat with a yoke works just fine.

### Steps to reproduce the issue:
1. Place down Standing Seat
2. Place down joystick
3. Link standing seat to joystick
4. enter standing seat

**Comment by tsunamayo** [comment]
@Crimson-Artist Hi, fixed for 24w28a. Cheers
