### ISSUE TITLE
Cannot place capacitor

### ISSUE THREAD

**Issue by Disaster226** [tsunamayo/Starship-EVO#5863]
### Short Description of the issue:

Capacitor cannot be placed, doesn't show up when selected.

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 24w27b
- Graphics Card: 3060

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Disaster226 Hi, this is because I adding a new addon type for warp core, and the capacitor will be deprecated for warp core.
