### ISSUE TITLE
Box delete tool odd interaction, Cant build after using.

### ISSUE THREAD

**Issue by DareBearWerner** [tsunamayo/Starship-EVO#5864]
After using the box delete tool you cannot place or remove any blocks, following that after restarting the game my craft was gone, not just invisible.
Additionally i believe it is caused with a weird interaction with itemstands since it worked perfectly fine previously
...

### Steps to reproduce the issue:
Using the Box delete tool on a whole room, in this case it was 4x8x12m
...

### Environment
- Starship EVO version: early-access 24w27b
- Graphics Card: rtx3070

### Additional information:
[Player-prev.log](https://github.com/user-attachments/files/16120642/Player-prev.log)
Im sending my Prefab room aswell on wich i used the box delete tool.
[REACTOR ROOM.zip](https://github.com/user-attachments/files/16120649/REACTOR.ROOM.zip)

**Comment by tsunamayo** [comment]
@DareBearWerner Hi, thanks for reporting this. Issue is fixed for 24w28a. Cheers
