### ISSUE TITLE
[Bug] 24w28a- Void pearls don't fill warp core additional void pearl canisters

### ISSUE THREAD

**Issue by Crimson-Artist** [tsunamayo/Starship-EVO#5866]
Found within a few minutes of playing. If you stretch out a warp core and place void pearl canisters on all its slots then place multiple void pearls into the warp core the pearls will act as if there is only one canister and fill vertically.
![20240710070400_1](https://github.com/tsunamayo/Starship-EVO/assets/112352428/0e83694d-8a12-4b3e-8ca7-fa9088385cad)

**Comment by tsunamayo** [comment]
@Crimson-Artist Hi, issue fixed for 24w28b. Cheers
