### ISSUE TITLE
[Bug] 24w28a- Saddle orientation arrow in wrong direction

### ISSUE THREAD

**Issue by Crimson-Artist** [tsunamayo/Starship-EVO#5867]
The new orientation arrow displays on the sides of the saddle rather than the proper direction. 
![20240710100930_1](https://github.com/tsunamayo/Starship-EVO/assets/112352428/a958de33-492f-4b54-8620-080a817e8bc2)

**Comment by tsunamayo** [comment]
@Crimson-Artist Issue fixed for 24w28b. Thanks
