### ISSUE TITLE
[Bug] Can't retrieve void pearls from item stands

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#5868]
### Short Description of the issue:

You can place a void pearl on an item stand, but when you take it out, it doesn't occupy the slot in the hotbar properly, and you can't put it back on the item stand.

### Steps to reproduce the issue:

1. Find void pearl
2. Place it on an item stand, observe how pretty it is
3. Retrieve it from the item stand - it doesn't show up in your hotbar, but it still kinda acts like an item you can use
4. Try to put it back on the item stand

When you pick it up in step 3, you can only place it back on an item stand. You can't take the one from step 3 and put it in a warp block.

### Environment
- Starship EVO version: 24w28a

### Additional information:

Probably not ship-dependent.

![image](https://github.com/tsunamayo/Starship-EVO/assets/10069469/94d3dd6a-f84f-4a6e-a73b-bb44f5c213b2)

![image](https://github.com/tsunamayo/Starship-EVO/assets/10069469/b97a58b1-3d2f-4076-b92f-8587e460a717)

**Comment by tsunamayo** [comment]
@asanagisae Hi, issue is fixed for 24w28b. Cheers
