### ISSUE TITLE
Legacy Ships with Capacitors on Warp Cores Broken

### ISSUE THREAD

**Issue by kynamats** [tsunamayo/Starship-EVO#5870]
### Short Description of the issue:
As of the Void Pearl update, any ships from older builds with capacitors on warp cores spawn only as emissives (glow tiles, lights, text on screens etc)
![image](https://github.com/tsunamayo/Starship-EVO/assets/89156468/6a0be991-720e-4212-9ffe-83a320b242f2)
This makes these blueprints uneditable in the current build, as attempting to save a new blueprint off of the 'ghost' ship will result in 90% of child entities getting deleted.
I've checked with others and the same ships are reliably affected. 
...

### Steps to reproduce the issue:
Spawn a ship with capacitors on warp cores.
examples of affected workshop ships:
https://steamcommunity.com/sharedfiles/filedetails/?id=3267804840
https://steamcommunity.com/sharedfiles/filedetails/?id=3055041951
https://steamcommunity.com/sharedfiles/filedetails/?id=2878381574
...

### Environment
- Starship EVO version: 24w28a
- Graphics Card: 3070ti

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
[Player-prev.log](https://github.com/user-attachments/files/16175788/Player-prev.log)
[Player-prev1.log](https://github.com/user-attachments/files/16175790/Player-prev1.log)
[Player.log](https://github.com/user-attachments/files/16175791/Player.log)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by asanagisae** [comment]
I can confirm. I had a world with the Aquilla Trident in it. After the void pearls update, the ships were gone.

Using a GTX 1070ti.

Although the game did not crash, there's a few NullReferenceExceptions in the log:

[Player.log](https://github.com/user-attachments/files/16176968/Player.log)

![image](https://github.com/tsunamayo/Starship-EVO/assets/10069469/2dcf43ff-73f2-4491-854a-6b48b9d6c770)

**Comment by BigBadKangaroo** [comment]
Can confirm it happens to some of my ships aswell, not to all tho.
The ship is spawned in ... but invisible.

I'll check some more of my ships, but for now this one is corrupted:
https://steamcommunity.com/sharedfiles/filedetails/?id=3012784640&searchtext=leski
![20240711222120_1](https://github.com/user-attachments/assets/3b5b48ea-3ce1-4820-9227-6dc25888c683)
![20240711222132_1](https://github.com/user-attachments/assets/f422df96-9506-4665-a895-53028fe3a375)

**Comment by tsunamayo** [comment]
@kynamats Hi, issue fixed for 24w28b. Btw it had nothing to do with warp core, issue was a new feature on event gate.
Your ships are amazing mate!
