### ISSUE TITLE
[Bug] Lag when exiting spaceship control

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#5872]
Hi there,

everytime I'll press "Exit Spaceship Control" to exit my ship, I get a massive lag where I'm unable to move completely. However, the game doesn't lag (see stats in top right corner in the video), it's just me freezing in position unable to do anything.
I tested a lot of different ships, some from the workshop, some of my own. Happens to me in **_every_** ship! 
Game version: 24w28b

https://github.com/user-attachments/assets/7934e714-cffd-4861-aef1-f32d9334b9e1

**Comment by tsunamayo** [comment]
@BigBadKangaroo Thanks for the swift report, I am on it.

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, issue is fixed and patch is live, still 24w28b. Cheers
