### ISSUE TITLE
[Bug] 24w28b- Accessing a newly linked event gate soft locks the game then turns ship invisible on relaunch

### ISSUE THREAD

**Issue by Crimson-Artist** [tsunamayo/Starship-EVO#5874]
Trying to access a newly placed and linked event gate in the experimental branch update causes my character to freeze in place. I can open my codex and other actions but I simply cant move or look away. I can quit to desktop alright. However on relaunch the ship that I was looking at suddenly turned invisible. It was still there as I can highlight blocks on it but it is just invisible. Trying to access the event gate again soft locks me again
![20240712195723_1](https://github.com/user-attachments/assets/935f8963-31ff-4c26-9d44-1f09efa23f43)

### Steps to reproduce the issue:
1. Place down event gate.
2. Link event gate to starship computer or something else compatible
3. try to access the event gate to configure it.

**Comment by tsunamayo** [comment]
@Crimson-Artist I am looking into it.

**Comment by totalvectors** [comment]
I have the same soft lock issue from simply interacting with an item/block on an item stand. As soon as I press F to grab it the controls for the character freezes. Escape key and Tab key still work and I can exit the game just fine. But my character is stuck until relaunching the game where I can move and interact until I grab something from the item stand again. Upon reload the item from the item stand is on the floor. Note: this is in the tutorial station (haven't been able to get past that point)
I wonder if these bugs are related.

**Comment by tsunamayo** [comment]
@totalvectors you play on experimental?

**Comment by tsunamayo** [comment]
@Crimson-Artist Issue is fixed, I have just reuploaded the build.

**Comment by tsunamayo** [comment]
@totalvectors Issue is also fixed. Thanks

**Comment by totalvectors** [comment]
I can confirm that that also fixed my issue (on experimental as well) Thanks!
