### ISSUE TITLE
[Bug] hinged force field air-tightness

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#5878]
Hi there,

when a force field block is placed on a hinge, the room will not become air-tight.
The room with a non-hinged force field block will become air-tight.
(most recent game version 24w28b)

Here's a small test BP: 
[Air-leak.zip](https://github.com/user-attachments/files/16241191/Air-leak.zip)

![20240716011310_1](https://github.com/user-attachments/assets/f686d674-15db-403a-aaf7-fbf99fc1968d)

**Comment by vortenian** [comment]
i don't think that is a bug i don't think doors are air tight that's what the force field is for, to make up for that fact it would be very difficult to implement custom airtight closeable openings space engineers cant even do it they have hanger door blocks and merging.

**Comment by ProPeach** [comment]
@vortenian custom doors on hinges are actually airtight, it's one of the great things about the airtightness solution for sevo. Force fields usually keep air in, so putting one on a hinge shouldn't change that - hull blocks on hinges do keep in air as you'd expect as well as when not on a hinge, so force fields should act the same hence the bug

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, issue is fixed for 24w34a. Cheers
