### ISSUE TITLE
[Bug] Ship spinning out of control when adding/removing blocks (Part III)

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#5882]
### Short Description of the issue:

This ship will be thrown around in random directions when you add or remove a block.

Also, if you sit in the seat and take control of the ship, it will drift uncontrollably on its own.

Also, there was a crash.

[Player.log](https://github.com/user-attachments/files/16250567/Player.log)

[Crash_2024-07-16_142950061.zip](https://github.com/user-attachments/files/16250586/Crash_2024-07-16_142950061.zip)

It was mentioned before that this may have something to do with power cells in power cell bases on hinges and other mechanisms.

The ship has a starting block, an upside down conveyor belt, and a disproportionally giant black void pearl on an item stand on a rotor (please leave this feature in the game!).

I also noticed that the blueprint was saved with 2 void pearls in each warp container, but when I start the game, each warp container is reduced to only 1 pearl. This still happens after I move more pearls into the empty slots and restart the game.

### Steps to reproduce the issue:

First, spawn the ship in the world. Then, _restart the game_. The bug does not appear during the session that the blueprint was spawned in.

Then, try any of the following. They all trigger the uncontrolled spinning.

1. Place a block on the ship
2. Remove a block from the ship
3. Sit in the seat (sometimes this is enough to send the ship spinning)
4. Sit in the seat, then take control of the ship (left stick)
5. Sit in the seat, then get out of the seat

Observe as it spins out of control. Restart the game to stop the ship and try another trigger.

### Environment
- Starship EVO version: 24w29a [default]
- Graphics Card: GTX 1070 ti

This issue did not occur in the previous default build of 24w27a. I did not test the experimental build 28a.

### Additional information:

https://github.com/user-attachments/assets/6058da33-ee91-4ea5-97f5-47ee65169f84

https://github.com/user-attachments/assets/541d1766-d5ca-4536-ba37-a8f7e69fa105

[Toad.zip](https://github.com/user-attachments/files/16250564/Toad.zip)

**Comment by tsunamayo** [comment]
@asanagisae Hi, it was linked to item stands. Issue fixed for 24w29b. Cheers
