### ISSUE TITLE
[Bug] Warp containers will delete all pearls except one after restart

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#5883]
### Short Description of the issue:

If you build a warp core with a warp container add-on longer than 1, and you fill it with void pearls, then restart the game, the game will delete all but the last one.

### Steps to reproduce the issue:

1. Create warp core on a ship
2. Attach a warp container to it, of length 2 or greater
3. Fill it so that there are at least 2 warp pearl slots visible
4. Restart the game

### Environment
- Starship EVO version: 24w29a

### Additional information:

![image](https://github.com/user-attachments/assets/d52bf84b-4826-41b8-bfa8-767c5eee482a)

**Comment by tsunamayo** [comment]
Let me check if I can reproduce, it seems it was fine when I tested...

**Comment by tsunamayo** [comment]
@asanagisae Hi, issue is fixed for 24w29b. Cheers
