### ISSUE TITLE
[Bug] Using a player-owned fuel kiosk causes controls to freeze

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#5886]
### Short Description of the issue:

If you attempt to use a refuelling kiosk (via a monitor) on a player-made station, your controls freeze. You are unable to look around or move until you reload the game.

The game itself appears to still be running. This only affects your controls, as if accessing a cargo block's inventory.

Tested in creative mode.

This issue occurs in the session where you place all the necessary blocks, and it also occurs if you restart the game and access the monitor again. (If you reload the world, things are fine until you press F on the monitor.)

### Steps to reproduce the issue:

1. Build a station
2. Optionally (?) place a shipyard on it, configure it for a suitable ship, and dock the ship to it
3. Place a kiosk block on the station
4. Set the kiosk to "fuel" mode
5. Place a monitor block on the station
6. Link the monitor to the kiosk block
7. Access the monitor block by pressing "F"
8. Observe as your mouse and movement controls are locked indefinitely
9. Press Esc - note that it does not exit the locking state (as it would when you access working menus like cargo inventory)

I don't know how much of step 2 is necessary to trigger the bug. I had the shipyard configured and docked a ship to it, see the screenshot.

### Environment
- Starship EVO version: 24w29b [default]

### Additional information:

![image](https://github.com/user-attachments/assets/6bbf68d0-c680-415b-9dbb-dbef79ee7580)

This string of null reference exceptions gets appended to the log every few seconds:
[Player.log](https://github.com/user-attachments/files/16265714/Player.log)

**Comment by tsunamayo** [comment]
@asanagisae Hi, unfortunately I cant reproduce - even after docking. In case like that where the steps to reproduce are complex can you also join a copy of your world? Cheers

**Comment by asanagisae** [comment]
I'm not sure the steps are complex, but here's the world:

[Wendel S'jet.zip](https://github.com/user-attachments/files/16301471/Wendel.S.jet.zip)

And here are the steps, just press F:

https://github.com/user-attachments/assets/4a06e33d-1fc6-40f5-b586-d9fee8a0a4f9

**Comment by tsunamayo** [comment]
@asanagisae Thanks issue is fixed for 24w29c. No pb ^^. It was linked to docked ship being unspawned or something like that.
