### ISSUE TITLE
[Bug] [Survival] Ship-based electrolyzer cannot fill tanks/reactors/LC

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#5889]
### Short Description of the issue:

I've experienced this issue in 2 separate survival worlds on 2 different ships built by hand, on the starter planet.

Basically, I am unable to store any significant amount of hydrogen fuel for light cruise aboard a space ship.

Side note: I have had success with using electrolysers on bases. However, I cannot connect ships to the base. The connector block refuses to connect. Shipyards work, but shipyards require a kiosk in order to supply fuel to docked ships, and kiosks are not available in survival. I therefore am not able to fill a ship with hydrogen from a base. Removing the ship computer from the ship does not solve the issue. Putting a station computer on the ship does not solve the issue.

### Steps to reproduce the issue:

1. Spawn the ship below into the world
2. Take control of it and dip the fuel scoop into water (if the water tank is empty)
3. Wait about 2 minutes
4. Use the link tool to observe the hydrogen/water levels of the various blocks: fuel scoop, hydrogen tank, light cruise engine, electrolyzer
5. Note that the light cruise engine and hydrogen tank will never fill with any significant amount of fuel

### Environment
- Starship EVO version: 24w29b (but it has occurred for several patches now)
- Graphics Card: GTX 1070 ti

### Additional information:

Here, I inspect the fuel scoop, the water tank, the hydrogen tank, the light cruise engine, and the electrolyzer.

https://github.com/user-attachments/assets/2fb19edf-9a81-4d11-ad5d-ad0bbddff4fb

Here are a few observations:

- The light cruise engine may gain some hydrogen fuel in the first 2 minutes, but very quickly it is reduced to 0 and never increases
- The hydrogen tank remains at 0 (empty)
- The water tank depletes slowly when out of water, and fills slowly when the fuel scoop is in water, as expected
- The fuel scoop will pick up water as expected (on planets), it tends to scoop until its full and it stays near full
- The electrolyzer fills up on water and produces hydrogen and oxygen, the hydrogen and oxygen levels go up and down rapidly indicating activity
- This issue also occurs if there are reactors hooked to the piping system: reactors will also never fill
- Changing the hydrogen tank's storage type (to oxygen for example) then changing it back to hydrogen does not fix the issue: it still will not fill with hydrogen
- There are no oxygen tanks or life support systems aboard the ship

Here's the first few minutes after launching the world and putting water into the system:

https://github.com/user-attachments/assets/e03865d4-68f3-4a61-a71b-86925be23283

The LC engine manages to fill up to 2%, then all the fuel goes poof. Rinse, repeat.

Where does all the hydrogen go?

Here is one of the crafts that exhibit the issue:

[Hoover.zip](https://github.com/user-attachments/files/16287473/Hoover.zip)

I also realized that both ships with the problem were built with mirroring. The bases I built to harvest hydrogen were _not_ built with mirroring. I'm not sure if that's relevant.

**Comment by asanagisae** [comment]
After manually travelling to a gas cloud near a star without the use of light cruise, I can confirm that fuel scoops can scoop enough hydrogen to fill light cruise engines and hydrogen tanks. However, getting to this point without LC does not seem like a valid workaround. 😄

![image](https://github.com/user-attachments/assets/984b52dd-ee80-481d-a96c-a981cf630571)

**Comment by tsunamayo** [comment]
@asanagisae By the look of it, it seems that your O2 has nowhere to go, hence stalling the production. The big right tank should be set at 02, not H20. thanks

**Comment by tsunamayo** [comment]
@asanagisae So for next update I have added a new Fuel Filter setting for harvester, so you can safely dump oxygen to not stall your H2 farm.

**Comment by asanagisae** [comment]
@tsunamayo I don't think you're correct about the O2. As you can see in the pictures above, the left tank for this ship is dedicated to O2. It fills correctly while the electrolyzer works. It has never been fully filled because it's a really big tank, but it works as expected.

With this O2 tank in place, the LC engine still does not fill.

Water is being consumed. The electrolyzer is creating both H2 and O2. Both H2 and O2 are being drained from the electrolyzer. The O2 is going to the O2 tank correctly. The H2 is disappearing entirely.

**Comment by tsunamayo** [comment]
@asanagisae So thanks for not giving up on this, issue should be fixed for next patch. Cheers
