### ISSUE TITLE
[Bug] [Survival] Warp crystals can't be picked up anymore

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#5890]
### Short Description of the issue:

Warp crystals can no longer be mined or picked up directly.

They appear the usual red from a distance, but when you get close, they turn black.

### Steps to reproduce the issue:

1. Create a space-capable ship
2. Fly to the asteroid rings
3. Attempt to mine warp crystals with your hand mining beam

### Environment
- Starship EVO version: 24w29b
- Graphics Card: GTX 1070 ti

### Additional information:

![image](https://github.com/user-attachments/assets/60869289-a936-4fbc-bde2-efa5745ad2e8)

https://github.com/user-attachments/assets/3927cfba-b2ae-4282-a1a5-f404ced0af34

**Comment by tsunamayo** [comment]
@asanagisae Hi, issue is fixed for 24w29c. Cheers
