### ISSUE TITLE
[Bug] [Survival] Light Cruise engines drain fuel abnormally from the entire ship

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#5892]
### Short Description of the issue:

This is related to #5889: If this is fixed, both can be closed. It was recommended that new issues be created for important incidents because replies to existing issues may be lost. After further testing, it was clear that the Light Cruise engines are the cause of the issues, so this new ticket is created to reflect that.

There was an attempt to fix this issue with #5891. However, 5891 does not resolve the issue. H2 production is _not_ stalled by having too much O2. Having a fuel scoop expel O2 does not resolve the issue.

### Environment
- Starship EVO version: 24w29c [default] [survival]
- Graphics Card: GTX 1070 ti

### Additional information:

The testing was done with this basic starting base, built entirely in survival mode by hand, featuring a few production facilities. Most importantly, it is capable of electrolyzing water into H2 and O2.

![image](https://github.com/user-attachments/assets/a7f0ab91-76d9-4691-b564-0ef8246c81ff)

The H2 tank fills twice as fast as the O2 tank. When the H2 tank is full, the O2 tank stops filling at about half full.

This situation is working as expected. O2 production is "stalled" when H2 is full.

----

However, the instant you add a Light Cruise engine to the mix, the hydrogen begins to drain from the system rapidly.

https://github.com/user-attachments/assets/1243e55e-b061-47a9-b658-aa6f7ada3d18

Because of the 10mb upload limit on Github, I can't show the entire process, just the general idea of how to test. Results should be clear within 5 minutes. Once the LC block is added, the H2 tank begins to empty (slowly), and the electrolyzer block begins to drain its H2 reserves. If you wait long enough, all the H2 vanishes from the system. The LC block remains empty or near empty.

If you remove the LC block, the fuel system returns to normal and H2 begins to stockpile in the H2 tank again.

This behavior happens during the session the base is built and the steps are performed, as well as after restarting the game and reloading the world.

----

With this context, please look at this world file:

[Sky Wanderer.zip](https://github.com/user-attachments/files/16317668/Sky.Wanderer.zip)

The setup is done, and the LC block is in place. The H2 is currently draining from the H2 tank. In about 5-10 minutes, the H2 tank will be completely empty.

You can stop this by removing the LC block from the base. The H2 tank will then begin to fill as normal again. You can place and remove the LC block as much as you like. The bug occurs when the LC is connected to the pipe system, the system returns to normal when the LC block is not present.

This is the same behavior as the previous 2 survival ships I had. After the current test, I've confirmed that this bug affects both static structures (the starter block was green and placed on terrain) and free floating ships (the starter block was blue). Having an established "forward" direction on the ship (with a ship computer and yoke) is not necessary for this bug to manifest and does not prevent the bug from occurring.

Note that the LC block is not on a CE, it is placed on the parent entity of the starter base. However, any solution to the problem should account for LC blocks being on mechanisms, including mechanisms that cause the LC engine to not point directly backwards (relative to the ship controls).

### Reproduction steps:

If you wish to recreate the situation, these steps should suffice. It may take a while to do so in survival from scratch.

1. Begin by creating a base near water on a planet - can be attached to terrain or free floating (like a ship)
2. Add a sufficient power source, such as a wind turbine or solar panel
3. Place 1 fuel scoop on the base, submerged
4. Place 3 large tanks on the base - assign one to water, one to oxygen, and one to hydrogen
5. Connect the fuel scoop and the tanks with fluid pipes
6. Place a large/stretched electrolyzer on the pipes
7. Wait for a significant amount of H2 and O2 to be generated
8. Observe that the H2 tank fills with H2, and the O2 tank stops filling once the electrolyzer is also full of H2
9. Assert that the previous situation aligns with normal game behavior
10. Place a large Light Cruise engine connected to the pipes
11. Observe that the LC engine remains near empty, and the H2 tank begins to drain - this may take upwards of 10 minutes to empty, but the trend is observable almost immediately
12. The H2 is vanishing inexplicably from the system - this is the bug
13. Remove the LC engine
14. Observe that the fluid system begins to work as expected again

**Comment by tsunamayo** [comment]
@asanagisae Hi, thanks for the detailed investigation. So indeed there it was linked to the electrolyser pushing O2 to the lightcruise engine (it could have happened with reactors too), and then being cleaned up (along with some h2) by some safeguard.
Fixed for 24w30c. Cheers
