### ISSUE TITLE
[Survival] Crucible draws immense power

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#5895]
Hi there,

the Crucible block draws power when smelting ores ... a lot of power.
Isn't the Crucible suppossed to be used without power - that's why it uses coal? 

Without anything running my power level is at 55%, when smeltung ore it goes up to 855%

https://github.com/user-attachments/assets/d4553b31-c539-4a80-b7d4-38707c376880

**Comment by tsunamayo** [comment]
Yes it should use no power!

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, issue is fixed for 24w30b. Cheers
