### ISSUE TITLE
[Survival] Ore vs Ingot inventory capacity

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#5896]
Hi there,

the inventory gets filled up really quickly when mining ore. A single Iron ore takes up 136l of inventory space - a smelted Iron Ingot only uses up 16l of inventory space.

That way a full inventory would end up with either:
3000l / 136l = 22.05~ Iron ores
or
3000l / 16l = 187.5 Iron Ingots

Wouldn't it be more logical that a smelted ingot is denser / heavier and so it takes up more space? 
So when a smelted ingot takes up 16l, a single ore would be more logical to take up around half of it? Maybe even 1/4th of the ingot piece?

That way we would end up with:
3000 / 16l = 187.5 Iron Ingots
or
3000/ 8l = 375 Iron ores

That way the inventory space would make more sense and would be much more survival friendly.
Being able to carry ~188 smelted ingots is a good amount to carry by hand / 375 raw ores would be good as well. If you need to carry around more then it would make sense to use a vehilce for that with a large storage container on top.

By the way, an Arc Furnace takes up 64l of inventory space, and that thing is 3x3 meters in size and labeld with 300Kg in mass. Right now I can choose between 1 Arc Furnace or 3 raw iron ores to fill the same inventory space ... 

https://github.com/user-attachments/assets/fcceec25-e3b9-48e5-8245-a72592c43bb2

**Comment by asanagisae** [comment]
"Denser" means it takes up _less_ space/volume for the same amount of mass/weight/heaviness. Smelting is the process of separating metal from unwanted rock and minerals in the ore, and the metal left over is shaped into ingots. It's like boiling sugar water to get the sugar out of the water. So ore _should_ take up more space because of the unwanted material.

I think there's one key point you're missing about density from a game play perspective. Using your numbers, if you take sixteen 8L ores and smelt it into one 16L ingot, you get that feeling of density you're looking for.

In this case, you always want ores in batches of sixteen. So instead of having huge numbers on your ore stacks in your inventory, why not just bunch the stacks together? Instead of sixteen 8L ore items, why not just have one 136L ore item? And that's exactly what we have in game right now.

**Comment by BigBadKangaroo** [comment]
Well, I might've gotten the density thing wrong. My bad I guess. However, the main issues I have with the inventory still remains in it's current form. I'll try again to explain what I mean:

When I go out mining to get some iron, my inventory will be full when I get ~ 22 ores ... that's literally nothing to what I would need to build anything more than just a few basic resources. To get those 22 ores I'm not even one minute actively mining. 
I'm concerned about the gameplay aspect of that, because it massively limits your abillity to gather ores - especially when compared to what "normal items" you can carry right now.

I think it would make much more sense for the overall survival experience, if the raw resources you farm manually will be more profitable/ less volumetric. The most simple way I can think about this, is to make the raw ore much lighter for the inventory functionality. Yes it's less realistic, but adds a lot of value to user experience. 

We need to mine a lot of resources to get along in this game, and no other game has such a small capacity for the raw materials you need to farm. 

If we look at other games like No Man's Sky, Space Engineers, Minecraft etc. you will always be able to gather lots of resources before your inventory capacity is maxed out. It's just a good gameplay decission to make the players life easier. 

And no, using a vehicle to carry your ores with a larger storage container doesn't solve this issue. In my current world I have a Hovercraft with an 8000l Cargo Container. It's 2x2x2 meters and with the current system, this thing can only hold ~ 59 raw ores ... that's just way to little to be used as an effective mining vehicle. That's not even 59 1m Hull blocks, because you need the frame and the plates as well which will be crafted from your 59 ores you will smelt. 
I don't think it's reasonable to make the player craft a storage container that is 10+ meters just to slap it on a hovercraft so the mining can be done without worrying about the inventory for raw ore. 

The player will be out mining a lot and right now I don't really have fun constantly moving between my base and the ore patches, just because the raw ores take up sooo much space. The inventory space is not a problem with any other buildable blocks right now. I can move my whole base with this little hovercraft I've build. Seriously, everything fits inside it's storage - except the raw ores.  

I just think, that the raw ores should not take up that much space inside the inventory, when **_nothing else in this game_** does so.

**Comment by tsunamayo** [comment]
Yes I agree with the discussion, yep the density bit was off but the fact is I think ore are taking too much volume, I had planned to reduce that. Cheers

**Comment by tsunamayo** [comment]
@BigBadKangaroo It should be better in newer update - it should store 360 raw ore, 45 for a 1m storage. I will boost up the container cargo size, to the hell with the realistic constraints, it is a scifi-game after all.

**Comment by BigBadKangaroo** [comment]
> @BigBadKangaroo It should be better in newer update - it should store 360 raw ore, 45 for a 1m storage. I will boost up the container cargo size, to the hell with the realistic constraints, it is a scifi-game after all.

That's literally the best answer you could give! I love it! :D
