### ISSUE TITLE
[Survival] Crafting queue QoL 

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#5897]
Hi there,

so I gathered enough resources to start my first spaceship in survival. Therefore I need a lot of hull blocks. So when I get into the Assembler menu to craft my Hull blocks (and let's say I want 50 Hull blocks), I'd have to click 50 times to queue all those up.

It would be a really good QoL change if we could select how many blocks we want to build, when we first want to queue them up.
I.e.:
-get into Assembler
-search "Hull"
-click on hull
-a window pops up that ask how many blocks you want to build (doesn't need to be anything special - a small window with a number field or a slider would be enough)
-after getting the number in on how many I want to build, the Assembler starts working

Something like this:
![Stevo_Crafting](https://github.com/user-attachments/assets/15a00971-40d4-4d7a-a333-f9aef3d51006)

**Comment by asanagisae** [comment]
I think it's like Space Engineers (right now). There's no menu, but shift+click will queue 10 of an item, and alt+click will queue 100 of an item.

**Comment by BigBadKangaroo** [comment]
Just tested it ... this would've saved me quite some time. I didn't know about this, thanks a lot!

**Comment by tsunamayo** [comment]
@BigBadKangaroo Yes I need to write this somewhere, I will do a help section on crafting.
