### ISSUE TITLE
[Survival] Ore scanner : Copper symbol on scanner should be "Cu", not "Cp"

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#5906]
Hi Tsuna,

Just a small detail. When you scan for resources, Copper is abbreviated into "Cp", and not "Cu"

Cheers!
![image](https://github.com/user-attachments/assets/b39106ce-30ae-4735-aacc-bd08c56faa7f)

**Comment by tsunamayo** [comment]
Hi, yes we discussed the miss in the other post.

**Comment by tsunamayo** [comment]
@Uncle-Ulty Fixed for 24w34a! Cheers
