### ISSUE TITLE
fuel not transfered thru child enties 

### ISSUE THREAD

**Issue by king32109** [tsunamayo/Starship-EVO#5908]
### Short Description of the issue:
if you want to use a ce for fuel transfer, it doesnt work using the indicator pipe doesnt show a green light when conectred to a piston in my test case, when i used a cargo pipe that did show a conection light so i think something for fuel needs to be looked at
added 2 screen shots of one with a normal fuel pipe not working and one with a cargo pipe that does work

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 24w30b
- Graphics Card: 

### Additional information:
![image](https://github.com/user-attachments/assets/66994fe4-62c1-48c5-8a62-dd284f5ca97c)
![image](https://github.com/user-attachments/assets/b68bd22c-dc55-433e-9710-912e827df9f9)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@king32109 Thanks, I will have a look at it!

**Comment by tsunamayo** [comment]
@king32109 Hi, issue is fixed for 24w34a. Cheers
