### ISSUE TITLE
[Bug] Event Gates not updating or saving settings

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#5909]
### Short Description of the issue:

There are two issues I noticed with Event Gates in this patch.

One, when you link a block to an Event Gate, the icon on the Event Gate does not update immediately. This behavior is different from previous patches, where the icon updates to indicate what you linked to the Event Gate.

https://github.com/user-attachments/assets/1d84f687-5bd5-4ffa-b3cc-22c25a945a24

Two, if you link an Oxygen Tank to an Event Gate and configure it like this, save the blueprint, then restart the game, this link and the event registered will be forgotten on the next world load.

https://github.com/user-attachments/assets/de5c7a58-0a74-4abb-8dd7-b8307eba47f7

This second issue appears to be limited to Oxygen Tanks.

### Steps to reproduce the issue:

For item 1, please see the video.

For item 2, please see the video, then restart the game and reload the world, then observe that the link is missing.

### Environment
- Starship EVO version: 24w30b [default]
- Graphics Card: GTX 1070ti

**Comment by tsunamayo** [comment]
@asanagisae Hi, issues is fixed for 24w31a. Cheers!
