### ISSUE TITLE
[Survival] Starter planet bug after warp jumping

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#5912]
Hi there,

after jumping from the starter system to the nearest star and then jumping back, the starter planet has lost it's asteroid belt (physically and on the holomap) 
After landing back on it near my base, I even suffocated because apparently the planet has lost all it's o2 while I was gone.

However, after using the medbay to heal myself, I could walk around without a helmet again - seems like the medbay fixed that one.
I wasn't able to refill my oxygen with bottles filled with o2.

https://github.com/user-attachments/assets/a41dfd8c-4a43-4cba-a29b-af8671512cdb

After a restart of the game, everything went back to normal and worked fine again. 

Here's the Player log:
https://github.com/user-attachments/assets/d0b195e4-0334-46ff-a910-7916cec0b2f7
Sadly I can't attach the world because even when zipped it's file size is too large (32MB)

No more asteroid belt: 
![20240725201528_1](https://github.com/user-attachments/assets/03dac687-a065-4917-9bfc-85ac7a7b77e5)
![20240725195858_1](https://github.com/user-attachments/assets/659a0aca-63ba-4dd1-bc67-b2fc60c52e98)
![20240725201020_1](https://github.com/user-attachments/assets/42b818bd-8de2-440a-8751-3eaf460d53e8)

After game restart:
![20240725204053_1](https://github.com/user-attachments/assets/9df7d764-f5cb-4389-ac05-fcc0eca5ad10)

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, issue will be fixed for 2w37b. Cheers
