### ISSUE TITLE
[Survival] Stone Blocks have no weight

### ISSUE THREAD

**Issue by Tisdag1** [tsunamayo/Starship-EVO#5915]
### Short Description of the issue:

Stone blocks do not have any weight

### Steps to reproduce the issue:

Create stone blocks

### Environment
- Starship EVO version: 24w30b
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Weight with stones
![20240727171212_1](https://github.com/user-attachments/assets/28bb1c8a-6665-450d-91cc-486688841f9a)

Weight after crafting stone blocks
![20240727171347_1](https://github.com/user-attachments/assets/133f1359-e8df-40cf-8f15-4f08578663ba)

Here you can see the capacity of this container does not change when adding the stone blocks.
![20240727171415_1](https://github.com/user-attachments/assets/82011f81-5e53-4c15-8ff7-9530e7e0f7d3)
![20240727171422_1](https://github.com/user-attachments/assets/ac318e40-93b3-4f4c-a07d-6b64673d603f)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Player.log](https://github.com/user-attachments/files/16401707/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Tisdag1 actually building blocks have a very small volume. It is by design, so you can carry plenty of them to build what you want. Also how many of them you have do not impact, so 10 blocks as the same volume as 1.
Cheers
