### ISSUE TITLE
[bug] fuelscoop wrong produce scale

### ISSUE THREAD

**Issue by Tackietacktack** [tsunamayo/Starship-EVO#5917]
### Short Description of the issue:
hi tsuna,

![Starship EVO 02 08 2024 14_53_22](https://github.com/user-attachments/assets/552c6ffa-2f45-4f88-90ee-d6df72a98ade)
To the picture:
In codex one fuelscoop______________ Scale 1/2

in survival,
one produced fuel scoop is one 1/8 fuelscoop
4 produced fuelscoop are one 1/4 fuelscoop

correct is:
one produce fuelscoop is 1m scale

And if you put the fuelscoop on the ground it is very small. 

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 24w30b
- Graphics Card:

**Comment by ProPeach** [comment]
I might be misunderstanding, but -
1 scoop item making 1 1/8 scale scoop
4 scoop items making 1 1/4 scale scoop

Isn't that the same as rule as hull and other bricks? Larger scale ones require more materials to place down on your base

**Comment by tsunamayo** [comment]
@Tackietacktack Hi, I dont reproduce that issue, for me producing a fuel scoop give a correct 1 qty for 1m. 
=> Do you reproduce that again?
On the ground how small is it really, can you post a screenshot? 
All blocks dropped will be smaller than 1m, more like 0.5m, so it might be normal.

**Comment by Tackietacktack** [comment]
hi,
I have reproduce it in the same world and now its fine. 
I get a correct scale and can build correct scale.
crazy, that was real bugy. i have produced one scoop and could only build 1/8.
but good, now works.
