### ISSUE TITLE
Hinged Force Field issues with Life Support

### ISSUE THREAD

**Issue by RussianBoo** [tsunamayo/Starship-EVO#5918]
### Short Description of the issue:

I have found an issue between the Life Support Systems and Force Fields on angled Hinges. When in a mid to large sized room that has an opening that is at an angle a Force Field on a hinge at the same angle does not seem to have any effect. The Life Support block does not register the Force Field and claims that there are Leaks.

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:
![20240802115054_1](https://github.com/user-attachments/assets/9cd6d731-ffef-4820-90cb-a71d3a6b0184)
![20240802115115_1](https://github.com/user-attachments/assets/f59684b7-2a4a-4f37-932d-f75cb6a022cb)
![20240802115126_1](https://github.com/user-attachments/assets/1ce3bbff-ad47-4722-adbf-8ee007d05a4d)
![20240802115039_1](https://github.com/user-attachments/assets/3ebeadf9-2e93-43b3-8a5a-487883c6cfd1)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by BigBadKangaroo** [comment]
Hi there, this one has already been reported #5878

**Comment by tsunamayo** [comment]
@RussianBoo Hi, issue is fixed for 24w34a. Cheers
