### ISSUE TITLE
[Bug] "Sofa" block wrong hitbox

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#5919]
Hi there,

the backside hitbox of the "Sofa" block doesn't allow the player to build.
The type of block doesn't matter as far as I tesetd it.

https://github.com/user-attachments/assets/f292dc29-2754-4c47-b294-f98934abeca1

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, issue is fixed for 24w34a. Cheers1
