### ISSUE TITLE
[BUG] My game wont start 

### ISSUE THREAD

**Issue by COMICLER** [tsunamayo/Starship-EVO#5925]
My game wont start anymore, it doesn't show any of my saves exept one and when i try to play it it doesnt event load.
When i try to make a new game it wont start either. I have tryed validating and reinstalling and neither have worked. 
### Environment
- Starship EVO version: Current 
- Graphics Card: Geforce rtx 2070

[Player.log](https://github.com/user-attachments/files/16514693/Player.log)

Edit: i fixed my problem by doing a full reinstall

**Comment by tsunamayo** [comment]
@COMICLER Okay, glad to see you sorted it out! Cheers
