### ISSUE TITLE
[Survival] [Bug] Docking to ground platform causes platform to tip over [24w30b]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#5927]
### Short Description of the issue:
While attempt to fuel my ship at my H2 farm, I undocked then redocked to it, and this caused my platform to become detached from the ground and tip over.

I think what happened is that deactivating/reactivating the connector from the platform side made the game think that the platform was the child entity, which then meant that when I moved the ship's canopy, it lost its balance and the platform tipped with it.

### Steps to reproduce the issue:

1. Make ground platform with connector.
2. Land ship and dock with connector.
3. Deactivate platform connector.
4. Reactivate platform connector.

### Environment
- Starship EVO version: 24w30b
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
[Player.log](https://github.com/user-attachments/files/16556020/Player.log)

[Second Impact Testing.zip](https://github.com/user-attachments/files/16556024/Second.Impact.Testing.zip)

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Hi, thanks, I think that bug was reported but I didnt managed to replicate it. Will try again this time with the steps indicated. Thanks

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Hi, I think I fixed it when I did the #5943 fix.
