### ISSUE TITLE
[Bug] Warpcore not connecting to pipes

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#5928]
Hi there,

when placing a Warpcore and then connecting some inventory pipes, the pipes do not connect to the Warpcore.
However, when you first place the inventory pipes and then the Warpcore, the pipes do connect.

https://github.com/user-attachments/assets/a75bc8d3-00a8-477c-8a43-45494c11f318

**Comment by tsunamayo** [comment]
Hi, this feature has not yet been added, so I guess the real issue is why it can connect when placing the pipe first!

**Comment by tsunamayo** [comment]
@BigBadKangaroo Fixed for 24w34a. Cheers
