### ISSUE TITLE
"Ball Joint" name suggests more than one axis for the brick

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#5930]
Just a text change I guess was left over from early mech testing, but the current mech joint brick is still called a "Ball Joint Arm" and the description lists 2 axis of motion, whereas it only actually functions with 1 axis

![image](https://github.com/user-attachments/assets/a8fc266c-55c4-4a4f-beb6-929d2bce974c)

Unless you plan on giving it an extra degree of motion for mech ankles to allow them to roll on angled ground perhaps?

**Comment by tsunamayo** [comment]
Hi, yes indeed it was a leftover from the first version I did. I still plan to add a ball join at a later point though, I will rename this one.

**Comment by tsunamayo** [comment]
@ProPeach Fixed for 24w34a. thx
