### ISSUE TITLE
 undo button

### ISSUE THREAD

**Issue by hobnob321** [tsunamayo/Starship-EVO#5934]
Any chance we can have an **undo button** it's far too easy to accidentally delete things with right click when building

### Short Description of the issue:

...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by ProPeach** [comment]
This would be pretty awesome

**Comment by tsunamayo** [comment]
Hi, unfortunately it would be too complex to make it works with all the features, like delete systems or mechanism. Thanks
