### ISSUE TITLE
Fuel Scoop Fluid Type does not match set Fuel Filter (namely Oxygen)

### ISSUE THREAD

**Issue by StingerTheRaven** [tsunamayo/Starship-EVO#5939]
Title. Though the block interaction menu shows "expel oxygen", the fuel scoop tooltip shows H2 instead of O2. This is a functional bug as, of course, there is no oxygen being expelled. The expulsion functionality seems fine, as shown in the screenshot where hydrogen is being vented out of the yellow tanks.
This is in creative mode, I am not in the survival beta.
...

On a static base(? At the very least, a starter block over some water):
-Electrolyze some water, pipe output to an oxygen storage tank
-Place a pipe and fuel scoop from that tank, set it to expel oxygen
-No oxygen expels

...

- Starship EVO version: 24w30b
- Graphics Card: RTX 3060

![711980_20240822205446_1](https://github.com/user-attachments/assets/9f4a3a9d-9de8-4161-8b53-8f9c833f763b)
[Player.log](https://github.com/user-attachments/files/16720675/Player.log)
[Bugged Oxygen Valve.zip](https://github.com/user-attachments/files/16720677/Bugged.Oxygen.Valve.zip)

**Comment by tsunamayo** [comment]
@StingerTheRaven Hi, issue is fixed for 24w34a. Cheers
