### ISSUE TITLE
Cant smelt copper, cobalt or stone in cruicible

### ISSUE THREAD

**Issue by Antonyvw** [tsunamayo/Starship-EVO#5942]
### Short Description of the issue:
Unable to inert copper, coblat or stone into crucible to smelt it
...

### Steps to reproduce the issue:
open up the crucible menu, select ore, (copper, cobalt or stone), attempt to insert into crucible, but crucible refuses to accept it. Iron, silver and gold are able to be smelted as normal.
...

### Environment
- Starship EVO version:  24w34b
- Graphics Card: Nvidia Geforce RTX 3060 laptop GPU

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Antonyvw Hi, this is not an issue, but the normal thing. Use an arc furnace to craft more advanced ore.
That being said I agree the crucible should smelt rock, that would make more sense. Thanks
