### ISSUE TITLE
[Survival] [Bug] Attempting to disconnect ship causes CTD [24w34b]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#5943]
### Short Description of the issue:
In my survival testing world, my ship was docked to my H2 refinery. However, attempting to disconnect it from the ship causes a crash to desktop.

### Steps to reproduce the issue:
1. Load the attached save.
2. Use the switch in the attached screenshot (it's to you left in the cockpit).

### Environment
- Starship EVO version: 24w34b
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
![20240824212526_1](https://github.com/user-attachments/assets/c20c5283-6dc4-4e5f-b216-19d71a8a4d26)

[Player.log](https://github.com/user-attachments/files/16738531/Player.log)

[Second Impact Testing.zip](https://github.com/user-attachments/files/16738530/Second.Impact.Testing.zip)

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Hi, thanks I can reproduce a freeze. Also it seems I was able to take off dragging the base me...

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Hi, issue is fixed for 24w35a. Cheers
