### ISSUE TITLE
[Bug] Valves forget direct connections after (re)loading an entity

### ISSUE THREAD

**Issue by StingerTheRaven** [tsunamayo/Starship-EVO#5945]
### Short Description of the issue:
After closing and opening the game, or spawning a new blueprint that uses such a connection, valves that were placed directly on a tank or scoop "forget" their connection.
...

### Steps to reproduce the issue:
Build a tank and/or scoop, place a valve *directly* on them - no intermediary pipes (which seem to make a system safe from this bug)
Save the blueprint and spawn it in elsewhere
Observe that the valve connection has disappeared
...

### Environment
- Starship EVO version: 24w34a
- Graphics Card: RTX 3060

### Additional information:
![711980_20240825192705_1](https://github.com/user-attachments/assets/549f1577-d56f-4207-8b13-c14991d46585)
In the above image: red-painted valves will forget their connections when the entity is re-loaded. The green valve is unaffected
![711980_20240825192545_1](https://github.com/user-attachments/assets/d6a49c78-846d-49ff-816d-a45b643e46ec)

[Player.log](https://github.com/user-attachments/files/16742354/Player.log)

Blueprint: [Valve Bug.zip](https://github.com/user-attachments/files/16742355/Valve.Bug.zip)

**Comment by tsunamayo** [comment]
@StingerTheRaven Hi, issue is fixed for 24w35a. Thanks for booking those!
