### ISSUE TITLE
[Bug] Fuel Scoops (especially oxygen) forget their Fuel Filter when entity is reloaded

### ISSUE THREAD

**Issue by StingerTheRaven** [tsunamayo/Starship-EVO#5946]
### Short Description of the issue:
Similar to #5939, while fuel scoops now obey their fuel filter immediately after you set it, they forget this setting when the entity is next loaded via savegame or blueprint.
Pressing F to set the fuel scoop again, your settings are apparently stored in the blueprint, and the scoop immediately starts obeying the setting when you close the menu. However it forgets again when the entity is reloaded, instead defaulting to hydrogen, and you must "remind" the scoop every time you load its parent entity by pressing F and ESC on it.
For water harvesting and expulsion this does not pose an issue, as a hydrogen scoop will accept water.
A hydrogen scoop will refuse to expel oxygen.

...

### Steps to reproduce the issue:
Create an electrolyser structure, set a scoop to expel its oxygen output
Save blueprint, spawn a new one in
On the newly-spawned structure, no oxygen will expel until you press F on that scoop again
Alternatively, see blueprint below.

...

### Environment
- Starship EVO version: 24w34a
- Graphics Card: RTX 3060

### Additional information:

![711980_20240825204100_1](https://github.com/user-attachments/assets/38e894d2-f2af-470c-aa48-0632bc46b3a0)

[Player.log](https://github.com/user-attachments/files/16742678/Player.log)

Example blueprint: [Floating Hydrogen Refinery.zip](https://github.com/user-attachments/files/16742680/Floating.Hydrogen.Refinery.zip)
In creative mode, drop this refinery into a planetary lake and watch it electrolyse. The hydrogen (yellow) scoop will expel its tank, and the oxygen (red) tank will fill up... until you press F on the red fuel scoop.

**Comment by tsunamayo** [comment]
@StingerTheRaven Hi, thanks for booking the issue. Issue is fixed for 24w35a. Cheers
