### ISSUE TITLE
[Bug/Survival] Void Pearls and Crystals can spawn on top of each other

### ISSUE THREAD

**Issue by Asnro** [tsunamayo/Starship-EVO#5947]
### Short Description of the issue:

If a planet spawns both Crystals and Void Pearls, they will share the exact same spawn locations, effectively spawning inside each other. See screenshot below. Issue seems to affect every crystal/pearl on the planet.

![kuva](https://github.com/user-attachments/assets/9cc397ee-09ae-42ef-aead-b7d486fe5876)

### Steps to reproduce the issue:

Find a planet that spawns both Crystals and Void Pearls

### Environment
- Starship EVO version: 24w30b
- Graphics Card: RTX 4090

### Additional information:

[Player.zip](https://github.com/user-attachments/files/16744753/Player.zip)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Asnro Hi, issue is fixed for 24w35a. Cheers!
