### ISSUE TITLE
[Bug/Survival] Cargo Collector can pick up fallen trees

### ISSUE THREAD

**Issue by Asnro** [tsunamayo/Starship-EVO#5950]
### Short Description of the issue:

Sometimes when flying around with a ship you can run into trees and knock them over. These fallen trees are treated as physical inventory objects, which can be picked up and pushed into inventory by collectors on the ship.

### Steps to reproduce the issue:

- Knock over trees with a ship
- Pick trees up with collector
- Check ship inventory

### Environment
- Starship EVO version: 24w34b
- Graphics Card: RTX4090

### Additional information:

![kuva](https://github.com/user-attachments/assets/9facfca1-5d9c-428a-9100-835ecfd04b45)

[Player.zip](https://github.com/user-attachments/files/16753742/Player.zip)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Asnro Hi, so this issue will be finally fixed in 24w35a. Cheers
