### ISSUE TITLE
Trying to land on certain planets causes the game to crash.

### ISSUE THREAD

**Issue by Aranhanauta** [tsunamayo/Starship-EVO#5951]
### Short Description of the issue:

Hello, this has been happening for a while, when I try to land on a certain planet, especially planets that have a lot of vegetation, my game crashes and doesn't come back. When I try to restart the game, the save keeps loading forever. The only way is to create an entirely new save.

At first I thought this could be a problem related to my computer (which is not very powerful) but on other planets I can land normally.

For example, in the initial system there is a planet with a lot of vegetation and I can land on it calmly, however, there are at least three other planets in different star systems where I only approach the surface at a certain height and the game crashes.

I don't know what files I can download to improve the identification of the problem, nor do I know if I could, as the saves completely freeze and I can no longer access them.

I would like to know if anyone else has this problem or if it's just me. Thank you in advance.

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by ProPeach** [comment]
The Player.log file would be helpful here, there are instructions on how to find it in the Additional Information part of your report. Could you list your PC specs too? Like your GPU, CPU and RAM amount, that'd help a bunch. I havent heard of anyone else having this issue so those would help a bunch, thanks!

**Comment by Asnro** [comment]
There are also crash reports located in "AppData\Local\Temp\Moonfire Entertainment\Starship EVO\Crashes" that could be useful here.

**Comment by tsunamayo** [comment]
@Aranhanauta Hi, could you please send me your character save file located at: %UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Characters
Thanks

**Comment by Aranhanauta** [comment]
[Uploading Aranhanauta.zip…]()

**Comment by Aranhanauta** [comment]
[Aranhanauta.zip](https://github.com/user-attachments/files/16789556/Aranhanauta.zip)

**Comment by tsunamayo** [comment]
@Aranhanauta How much VRAM does your gfx card has? It might be related to that indeed.

**Comment by tsunamayo** [comment]
@Aranhanauta Also like said if you could send me a crash dump and error log to investigate that would be great!

**Comment by Aranhanauta** [comment]
My VRAM is 736 MB.

I couldn't find the Crashes folder according to the direction indicated.

**Comment by tsunamayo** [comment]
@Aranhanauta Hi, yes unfortunately I think it will be the culprit, the terrain tech needs a lot of memory in the GPU to store the voxel data and the geometry generated.

**Comment by Aranhanauta** [comment]
Hello, thank you for responding, but I would like to know why I can land normally on some planets while on others I cannot.
