### ISSUE TITLE
[Bug/Survival] Arc Furnaces do not pick up Scrap

### ISSUE THREAD

**Issue by Asnro** [tsunamayo/Starship-EVO#5952]
### Short Description of the issue:

Arc Furnace inventory logic ignores Scrap. It will not be pulled from inventory, it will not be picked up from belts. Attempting to feed Scrap into a furnace via belt makes it pile up at the feed hole. Furnaces are set up correctly, they can pull any other ore from belts and connected inventories.

### Steps to reproduce the issue:

Set up a furnace with belt and conveyor pipe connections, make sure direction and settings are correct, place scrap on belt and in connected inventories

### Environment
- Starship EVO version: 24w34b
- Graphics Card: RTX4090

### Additional information:

[Player.zip](https://github.com/user-attachments/files/16763723/Player.zip)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Asnro Hi, issue is fixed for 24w35a. Cheers
