### ISSUE TITLE
[Suggestion] Assembler Master Control: interact with multiple assemblers at once

### ISSUE THREAD

**Issue by Asnro** [tsunamayo/Starship-EVO#5955]
Currently, managing a large factory can be tedious. Even three assemblers can be hard to keep queued and working full time, nevermind a larger amount. What if there was a logic block that could be connected to multiple assemblers to copy orders from one "master" assembler to multiple "slave" assemblers? This could also be used to extend assembler interface in new and convenient ways:
- Repeat queue: have assemblers create same item(s) on loop, especially common necessities like hull blocks and their components
- Bulk pull: instead of assemblers idling between each order because they're waiting to pull an item from inventory, an order of "pull 10 iron ingots" could be issued across the connected network.
- Error messages: if an individual assembler can't comply with an order, it could send an error to the interface. Messages like "Inventory full" or "No materials available" would quickly let a player know that an assembler in their factory has stopped working.

**Comment by tsunamayo** [comment]
@Asnro Hi, not sure why we need a dedicated control for this.
1) could be on the main one, altough you can already use SHIFT and ALT to queue 100x of hull if you want, so I do not wish to code that
2) this is a limitation of the inventory system, not assembler, item are being pulled one by one. I could change that if necessary
3) There are already message when something happen, hover you mouse over the little i sign to see what is up.

Thanks

**Comment by Asnro** [comment]
> @Asnro Hi, not sure why we need a dedicated control for this.

The reason is that multiple assemblers working at once is faster than a single assembler, but queueing items on multiple assemblers is tedious. As a practical example, I built a simple 50x50m platform in survival which required over a thousand blocks. Would you want to wait for a single assembler to complete that order? I didn't, so I made multiple. Each time I had to restart the game (for bugs or breaks) the assemblers would empty their queues and I had to redo the orders _on each assembler_. This made me want a system to make bulk orders easier to issue and faster to complete. The factor holding back scaling up industry should be resources and creativity, not tedium.

**Comment by ProPeach** [comment]
I agree that Assemblers sharing jobs is an important feature - otherwise you'd need to manually divide up a task in your head and input each fragment into any number of assemblers, I can't imagine crafting components for a medium sized ship like that.

Space Engineers solves this with a "Cooperative Mode" for its Assemblers, where one designated Master divides tasks given to it between itself and other Slaved Assemblers.
https://youtu.be/fjRz-QNfcig?si=IoxgrX3wBWqDjwnG

This functionality may well pay dividends in the future too, if a Shipyard needs to be able to command multiple Assemblers to create missing components for a ship being spawned in - like we were talking about in that other thread.

**Comment by tsunamayo** [comment]
Would a solution where an assembler with an empty queue would be able to steal a job from a connected assembler? So you would just queue your stuff as usual in the "Master" assembler, then let the other one steal some jobs from it.
What I dont like is creating a new block or new UI for that. Here I only need to add one setting ("allow sharing of queue")

**Comment by Asnro** [comment]
That sounds perfect! I do understand not wanting to code extra blocks and UIs. Thank you for considering the idea.

**Comment by ProPeach** [comment]
One setting is all you need for sure, sounds ideal 👌

**Comment by Crimson-Artist** [comment]
having an auto build option would be very helpful as we ramp up our production. Spaming hundreds of build orders to achieve the same result seems overly complicated. being able to say right click on a recipe in order to set it to auto build would make single block production lines a reality.

**Comment by ProPeach** [comment]
That's brilliant, thanks a lot Tsuna!
