### ISSUE TITLE
Activating Piston after Placing Copied Hull Block Causes Crash

### ISSUE THREAD

**Issue by Muddledde** [tsunamayo/Starship-EVO#5963]
### Short Description of the issue:

Attempting to activate piston after placing 1x1x8 Hull Block (square) causes game to crash.

Game does not crash with smaller hull shape, nor various other blocks.

### Steps to reproduce the issue:

Create 8 tall Hull Pillar
Add two pistons to one side of pillar (one at 4 from below, and one at 5 from below)

Create Switch
Connect Switch to bottom Piston

Create 1x1x8 Hull block
Copy block with Copy/Paste Tool
Paste Copied block onto bottom piston (any orientation)

Activate switch

### Environment
- Starship EVO version: early-access 24w35a
- Graphics Card: NVIDIA GeForce RTX 2070 SUPER

### Additional information:

The game crashed when activating the switch to extend the piston while the block was attached.

Fiddled around to see if:

- Orientation
- Positioning
- Contact with adjacent blocks
- Other blocks (copied and not)
- Presence of second piston
- 1x1x8 block pasted onto different piston

caused a similar crash, and none did.

After the fiddling around, was able to extend the piston, but retracting the piston caused a crash.

It looks like it has something to do with the copied block?

Did some more fiddling, and placed the copied block onto the top piston, and no crash.

Removed the block from the top piston and placed it on the bottom piston, and no crash.

![Screenshot (533)](https://github.com/user-attachments/assets/bb9cb88e-4af2-4a0e-b855-6ef46cc99bdc)
![Screenshot (534)](https://github.com/user-attachments/assets/9bc7ea4b-46c6-405e-af54-cc49a7d48c55)
<img width="1920" alt="Screenshot (534)" src="https://github.com/user-attachments/assets/34f73993-54d9-4c8e-a717-ae8c67e140ae">

[Player.log](https://github.com/user-attachments/files/16819626/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/16819627/Player-prev.log)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

If you issue concerns a particular location please send your character save here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Characters\`

You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Muddledde Hi, thanks for reporting the issue, as the test case seems a bit specific could you also join the blueprint as expained in the case?
Thanks
