### ISSUE TITLE
[Bug/Suggestion] 24w35a- Fuel Scoop "Inside Gas Cloud" Event Gate trigger does not activate for Water

### ISSUE THREAD

**Issue by Crimson-Artist** [tsunamayo/Starship-EVO#5964]
While doing some tests with water I noticed that there is no event trigger for when a fuel scoop is within water. Since we have a event trigger for when a fuel scoop is inside of a hydrogen fuel cloud I think this event trigger should either be changed to trigger whenever the fuel scoop is within the source it has been set to or simply add event triggers for both water and air.

**Comment by tsunamayo** [comment]
@Crimson-Artist Hi, yep it makes sense.

**Comment by tsunamayo** [comment]
@Crimson-Artist Hi, done for 24w36a. Cheers
