### ISSUE TITLE
[BUG] Copy/Paste doesn't select any bricks and selection box freezes in place

### ISSUE THREAD

**Issue by daOyster** [tsunamayo/Starship-EVO#5966]
### Short Description of the issue:
Copy/Paste is currently refusing to copy bricks 95% of the time in creative mode, unknown if it happens in survival. The selection bounding box freezes in place after letting go of left click. Clicking again makes the bounding box go away, but ends up selecting a flat plane from where you started instead of the full box.
...

### Steps to reproduce the issue:
Try to copy/paste a random stack of bricks.
...

### Environment
- Starship EVO version: 24w35a
- Graphics Card: RTX 4070 Ti

### Additional information:

This error repeats in the plaer.log file everytime I try to use the copy/paste in game:

> ArgumentException: An item with the same key has already been added. Key: 58765
>   at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x000c1] in <44afb4564e9347cf99a1865351ea8f4a>:0 
>   at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <44afb4564e9347cf99a1865351ea8f4a>:0 
>   at VoxelEngine.ActionCopyPaste.CopySelection () [0x00312] in <4036089354f24ef780f25424b46e1eca>:0 
>   at VoxelEngine.ActionCopyPaste.LeftClickUp () [0x00013] in <4036089354f24ef780f25424b46e1eca>:0 
>   at VoxelEngine.VoxelActionTool`1[T].LeftClickUp (Game.PlayerCommandManager playerManager) [0x00012] in <4036089354f24ef780f25424b46e1eca>:0 
>   at PlayerActions.UpdateCommand () [0x002d0] in <4036089354f24ef780f25424b46e1eca>:0 
>   at Game.PlayerCommandManager.OnUpdate () [0x000ca] in <4036089354f24ef780f25424b46e1eca>:0 
>   at Manager.GameloopManager.UpdatePlayerCommands () [0x00014] in <4036089354f24ef780f25424b46e1eca>:0 
>   at Manager.GameloopManager.LateUpdate () [0x000bc] in <4036089354f24ef780f25424b46e1eca>:0 
>  
> (Filename: <44afb4564e9347cf99a1865351ea8f4a> Line: 0)
> 
>

**Comment by tsunamayo** [comment]
@daOyster Hi, I manage to reproduce (and I fixed) a different issue related to copy-paste.
It is not the same issue though.
I thank you for pasting the log but what I really need is the complete player.log and a proper test case so I can reproduce. Can you give me the blueprint and indicate me the area you where copying?

Cheers

**Comment by daOyster** [comment]
@tsunamayo Hi, sorry I should have included that originally, it's a weird one to replicate. It seems when 1/8th bricks are offset using plates, and sometimes with pipes it causes the behavior. In the included blueprint, the red painted stacks of bricks were able to consistently cause it for me. However I did notice some of the things that weren't able to be copied before started allowing me to on a world reload so if that happens, try to build a stack of 1/8th scale bricks, use the quarter sized plates to offset a 1/8th scale brick, and then try to copy that.

[Player.log](https://github.com/user-attachments/files/16852954/Player.log)

[Test copy paste BP For Tsuna.zip](https://github.com/user-attachments/files/16852959/Test.copy.paste.BP.For.Tsuna.zip)

**Comment by Tackietacktack** [comment]
Hi, same issu.
I can't copy something. All times the copy/paste tool freezing.
I think all have this issue.

**Comment by tsunamayo** [comment]
@daOyster Hi, I still cant reproduce. Can you reproduce in 24w36a? Thanks

**Comment by tsunamayo** [comment]
@daOyster So I managed to reproduced, it was linked to delete, you need to delete a block before for it to happens. Fixed for 24w37a. Cheers
