### ISSUE TITLE
hinge crash issue

### ISSUE THREAD

**Issue by boxfoxscoot** [tsunamayo/Starship-EVO#5968]
### Short Description of the issue: when hinges are moved by any means switch controller or manually through the menu the game will consistently crash

...

### Steps to reproduce the issue:
place hing move hinge game crashes
...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information: this hinge is connected to a switch which may or may not be relevant to the crashes 

https://github.com/user-attachments/assets/d7a884ad-9091-4502-9b60-116fcf80efbf

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player.log](https://github.com/user-attachments/files/16898389/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

If you issue concerns a particular location please send your character save here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Characters\`

You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by boxfoxscoot** [comment]
(sorry for any mispellings)

**Comment by tsunamayo** [comment]
@boxfoxscoot Hi, I cant reproduce on my side, could you send me your blueprint? Thanks

**Comment by boxfoxscoot** [comment]
[Furgon(1).zip](https://github.com/user-attachments/files/16929001/Furgon.1.zip)

**Comment by boxfoxscoot** [comment]
> [Furgon(1).zip](https://github.com/user-attachments/files/16929001/Furgon.1.zip)

also heres my pc specs 
Device name
Processor	12th Gen Intel(R) Core(TM) i7-12650H   2.30 GHz
Installed RAM	16.0 GB (15.7 GB usable)
Device ID
Product ID	00342-20930-88584-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
Edition	Windows 11 Home
Version	21H2
Installed on	
OS build	22000.2057
Experience	Windows Feature Experience Pack 1000.22001.1000.0

**Comment by tsunamayo** [comment]
@boxfoxscoot Hi, are you reproducing this in the latest build 24w37a?

**Comment by boxfoxscoot** [comment]
> @boxfoxscoot Hi, are you reproducing this in the latest build 24w37a?

it seems to be fixed although i should probably check with the original blueprint just to be sure so far nothing else has crashed

**Comment by tsunamayo** [comment]
@boxfoxscoot Hi, okay thanks for letting me know!

**Comment by boxfoxscoot** [comment]
ive checked it out and it seems to be fixed although I am getting a lag spike the first time I move the hinge after spawning the grid in but that is a minor issue
