### ISSUE TITLE
[Bug] Two small tutorial issues

### ISSUE THREAD

**Issue by DrEnzyme** [tsunamayo/Starship-EVO#5970]
### Short Description of the issue:

1) The repair beam is wired up to the tutorial ship's landing gear.
2) One of the modules makes progress towards two of the objectives when repaired

### Steps to reproduce the issue:

1&2) Progress the tutorial mission to the point where you need to repair the spaceship modules, get in your spaceship and fly out.
1) Observe that pressing "G" will activate your repair beam. It is not made clear how you are supposed to use it normally.
2) Fix the modules one by one (you do not need to repair them fully), observe that one of the modules will grant progress towards two of the objectives

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

If you issue concerns a particular location please send your character save here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Characters\`

You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@DrEnzyme Hi, thanks a lot for letting me know. I am currently working on it.

**Comment by tsunamayo** [comment]
@DrEnzyme I forgot to update you, the issue was fixed a few hours ago with the patch 24w36a. Thanks a lot, dont hesitate to post more issue if you encounter them it is very helpful.
