### ISSUE TITLE
[Bug] Conveyor filter resets

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#5975]
Hi there,

when placing down the new Conveyor Filter and setting a filter option, the set sub-filter resets back to the default filter option when creating a new filter:

This applies to:
-World Items
-Ore
-Ingots

https://github.com/user-attachments/assets/059592a9-278f-43fe-9db5-4ed7d3bd7bc4
(Sorry for the bad resolution, otherwise the vid will be more than 10mb) 

And on a side note: I really don't like that when creating a second / third / fourth etc option, the newest option will be on top. I think a new filter should be added on the bottom row, not on the top row. It just feels "unnatural" to get the newest option on top imo.

**Comment by BigBadKangaroo** [comment]
Addition: The sprites of the new conveyor tubes and not working

![20240910185602_1](https://github.com/user-attachments/assets/1256fb6d-ea18-4f2a-af3f-c039146a781a)

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, thanks this is fixed for 24w37b. Cheers
