### ISSUE TITLE
[Bug] Jumping multitool

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#5976]
Hi there,

when pressing any type of button / switch, the player model (the multitool) in first person jumps up and down. This does not occure when interacting with any mechanisms or blocks directly.
When in third person the player model doesn't jump up or down when doing the same thing.

https://github.com/user-attachments/assets/a068fdd6-ab8f-42e0-92a7-e1b8328a65a0

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, I am not sure to understand, what is the issue? That it is not doing that for everything?

**Comment by tsunamayo** [comment]
@BigBadKangaroo Yes it is intended, it is like you are reaching something with your hand, like in minecraft or other games.

**Comment by BigBadKangaroo** [comment]
@tsunamayo Oh, if this is intended then everything's fine. I thought it wasn't lol. 

But does that mean we will have a first-person hand model with an animation at some point?

**Comment by tsunamayo** [comment]
@BigBadKangaroo Not really planned tbh!
