### ISSUE TITLE
[Bug] Advanced Conveyor Tubes wrong names

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#5977]
Hi there,

when linking buttons / switches to the new conveyor blocks and looking at the connected button / switch, the displayed text of whats connected is inconsistent:

"Conveyor One Way" shows "One way conveyor tube"
"Conveyor Valve" shows "Conveyor Valve" 
"Conveyor Filter" shows "One way conveyor tube"
"Conveyor One Way" (the T-piece) shows "Conveyor Valve" 

... I just now realised, that the update-post says their names were "One-Way, Router, Valve, Filter". So even more inconsistency.

https://github.com/user-attachments/assets/b08da7fd-8bba-4291-8ab4-2821adfcb0cf

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, issue fixed for 24w37b. Thanks for helping me cleaning those, I know there are still plenty left...
