### ISSUE TITLE
[Experimental/Public Branch] Helmet Open/Close Hotkey Toggles Flashlight UI HUD.

### ISSUE THREAD

**Issue by MystLeissa** [tsunamayo/Starship-EVO#5979]
### Short Description of the issue:

Toggling your helmet with the keyboard toggles the "wrong" icon. Instead of the helmet it toggled the Light UI HUD, and the Light UI Hud doesn't respond when you press the Lights Hotkey.

### Steps to reproduce the issue:

1. Open Experimental Public Branch
2. Complete Tutorial
3. Press H
4. Notice the Flashlight Lights up instead of the Helmet
5. Press L
6. Notice the light turns on but the flashlight icon doesn't engage.

### Environment
- Starship EVO version: Early Access,24w37a
- Graphics Card: AMD Radeon RX 5700 XT
- Operating System: Windows 10 (home/64x/en-us) Build: 19045
- RAM: 64 GB (DDR4 I believe, but don't quote me on that...)
- HDD: 500 GB Main SDD Drive with a 3 TB HDD Data Drive 
- Free Space: Approximately ~150 GB Free on Windows Drive, and ~700 GB Free on 3TB HDD
- Platform: Steam
- Running Programs: Starship Evo, Steam, Google Chrome, File Explorer, Windows 10
- AMD Adrenline Version: 24.7.1

### Additional information:

[Player-prev.log](https://github.com/user-attachments/files/16956499/Player-prev.log)

[Player.log](https://github.com/user-attachments/files/16956497/Player.log)

If you issue concerns a particular location please send your character save here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Characters\`

You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.
[Nysch.zip](https://github.com/user-attachments/files/16956503/Nysch.zip)
[SETTINGS.zip](https://github.com/user-attachments/files/16956514/SETTINGS.zip)

**Comment by tsunamayo** [comment]
@MystLeissa Hi, issue is fixed for 24w37b. Thanks
