### ISSUE TITLE
Constant collisions while piloting craft

### ISSUE THREAD

**Issue by Gristle0** [tsunamayo/Starship-EVO#5991]
Constant collisions while piloting craft, sparks and collision noises.  Also on some craft wierd physics issues because of collisions
...

pilot something

...

### Environment
- Starship EVO version: latest Experimental
- Graphics Card: Nvidia Gforce RTX 4080

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

If you issue concerns a particular location please send your character save here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Characters\`

You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Gristle0 Hi, thanks for reporting the issue. Unfortunately I dont have any issues on my side so I am gonna need more info on this:
- What ship did you used exactly, could you send me the blueprint?
- Also could you join the player.log (not copy-paste its content into the case).

Thanks

**Comment by Gristle0** [comment]
[Player.log](https://github.com/user-attachments/files/17021796/Player.log)

Near constant collision in 2 different vehicles.

https://steamcommunity.com/sharedfiles/filedetails/?id=3313284023

https://steamcommunity.com/sharedfiles/filedetails/?id=3313256942

**Comment by tsunamayo** [comment]
@Gristle0 Hi, those are mech. 
Are you referring to the sound made when the step hit a metal ground? Or is it something else?

**Comment by Gristle0** [comment]
Constant collision sounds and sparks.  I'll record a video and post it later today.

**Comment by BigBadKangaroo** [comment]
@Gristle0 Hi there,

so I tested the two Mechs you mentioned. Please check the videos below and tell us if that's what you mean by "Constant collision sounds and sparks". However, when a Mech walks over a metal surface there will be sounds. It would be odd if a heavy mech walks over metal ground and you hear nothing - there needs to be at least some sound. 

@tsunamayo I tested a few more mechs to check this and yes, all of them have this "issue".All mechs I tried create sparks and collision sounds when on metal ground. In fact, even when walking on Stone and Wood blocks.
Maybe the sounds the mechs make when walking on player-made objects should be reduced? When walking over the planet surface everything feels nice. But walking on player-made objects makes this a bit more "clunky" than it needs to be? 

https://github.com/user-attachments/assets/6927ef13-5429-4156-8588-9edec7e8dc1d


https://github.com/user-attachments/assets/4c5c40c2-6a58-4fcf-8323-a92e98d888de


https://github.com/user-attachments/assets/f188387c-3e3a-4e55-8cef-5f2f159845b4

**Comment by tsunamayo** [comment]
@BigBadKangaroo Yes I will improve that! Can you point me toward the third mech? Thanks

**Comment by Gristle0** [comment]
Here is an example with a non mech flying machine.  Collisions are seen when looking around and when walking in the ship.

https://youtu.be/4VhhyGkZwFo

Link to craft: https://steamcommunity.com/sharedfiles/filedetails/?id=3313393204

**Comment by BigBadKangaroo** [comment]
@tsunamayo I wanted to give you this Mech anyways ... ^^

[KF-Kaiva.zip](https://github.com/user-attachments/files/17061627/KF-Kaiva.zip)

**Comment by tsunamayo** [comment]
@Gristle0 Hi, I dont have any issues with that blueprint. Where you carrying a handheld weapon by any chance? Could you send me your character save at the moment you are having the issue?  Thanks

**Comment by Gristle0** [comment]
> @Gristle0 Hi, I dont have any issues with that blueprint. Where you carrying a handheld weapon by any chance? Could you send me your character save at the moment you are having the issue? Thanks

I did have a weapon on the hotbar, but it was not being held.

**Comment by tsunamayo** [comment]
@Gristle0 Hi, so I managed to reproduce, this issue is fixed for 24w40a. Cheers!

**Comment by Gristle0** [comment]
Thanks!
