### ISSUE TITLE
suggestion additions to power cell interactions

### ISSUE THREAD

**Issue by najlitarvan** [tsunamayo/Starship-EVO#5995]
ability to set a auto mode that would swap between charge and discharge based on current power state
event gate interactions with a smaller, bigger, equal  comparision and abilitity to set a fill % that it would compare to.
ability to charge from docked entities or send power to docked entities, should probably be a new dropdown menu below the current charge setting to allow for separation on interactions between just the sole grid and between grids, docking connectors should also probably get a setting to allow or to not allow sharing of electricity

**Comment by tsunamayo** [comment]
@najlitarvan Hi,
auto mode: this actually was already done for the next update
event gate: this can already be done in current update.
for the docking part it is much more complex and is on the long-term to-do list.
Thanks
