### ISSUE TITLE
[Bug] Holding item while closing menu

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#5997]
Hi there,

when holding an intem while closing a menu, the item will be deleted from your inventory.
I tested it with a few different items, all get the same result.
And no, the items are not dropped next to the player.

https://github.com/user-attachments/assets/4990d4c5-4281-4d02-9e1f-9c492416bbd6

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, are you in survival or creative?

**Comment by BigBadKangaroo** [comment]
@tsunamayo Hi, sorry for the late reply.

I encountered this problem in survival mode.

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, are you sure it was in survival? I am cannot reproduce in survival, but can in creative. Thanks

**Comment by BigBadKangaroo** [comment]
@tsunamayo yes, I first encountered this issue in survival. I then made a video while in creative.

I cannot reproduce it right now (just tested it again), so it might be just a one-time-thing. If I encounter this one again, I'll let you know with more information.

Just in case you want to take a look at this save:
[Surv'5.zip](https://github.com/user-attachments/files/17215106/Surv.5.zip)
