### ISSUE TITLE
Worlds wont show up 

### ISSUE THREAD

**Issue by COMICLER** [tsunamayo/Starship-EVO#5999]
My world wont load or even show up and i cant recover the ships 
here the world file incase it help you 
[Legacy.zip](https://github.com/user-attachments/files/17067977/Legacy.zip)

**Comment by tsunamayo** [comment]
@COMICLER Hi, is it just this world? Thanks

**Comment by tsunamayo** [comment]
@COMICLER Hi, there was a space at the end of the save. By any chance did you rename it? I can load it fine, just remove the space at the end. Thanks
