### ISSUE TITLE
Collector doesn't collect

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#6004]
Hi there, 

I just made a mining test regarding the collector pull range.
See my post on that here (#6000 )
While testing I noticed that the collector doesn't collect ores it pulled in. It just pull them towards the collector and pushes them around.
The ore floating in front of the collector even has the power to push my ship around ...

I also noticed that once I leave my ship and the ship "is landed" on the ground, the collector collects the blob of ores in front of it just fine.

Addition: I made this test with a "small" mined area, this is not an "excessive" test with tons of ores. This is a normal amount of ore to be mined at once. 

https://github.com/user-attachments/assets/1276b8e5-413b-4906-802a-b2e6a10f3be3

https://github.com/user-attachments/assets/d03d60e3-9888-4185-8291-ff10565e03e5

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, I fixed various issue related to collector for next update. Please tell me if it is not fixed in 24w39a! 
Btw the new behaviour is that you cant collect crystal before breaking them (otherwise they would be a bit useless).
Cheers
