### ISSUE TITLE
fuel overlay not working

### ISSUE THREAD

**Issue by king32109** [tsunamayo/Starship-EVO#6005]
### Short Description of the issue:

i rememer having the abilty to look at fuel lines to see how they run and wich way it flows but its not wroking, the f1 option

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

If you issue concerns a particular location please send your character save here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Characters\`

You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@king32109 Hi, the fuel logic no longer works like that, it is now request based just like the item. It is much simpler to wrap your head around it I think. It flows both way! Thanks
