### ISSUE TITLE
Please make the game playable

### ISSUE THREAD

**Issue by Wagncs** [tsunamayo/Starship-EVO#6006]
### Short Description of the issue:
Please make the game playable, is impossible play online. My internet provider tell my is impossible found you connection multiplayer of game.
The single player no found, have one little tutorial, and creative. No more!
...

### Steps to reproduce the issue:
Please make the game playable, it is impossible to enjoy, and play. There are only creative and weak tutorials in the single plaer. The internet provider's technician said it was impossible for your game's multiplayer to work. Not even if you open the door you ask for. It's a lot of talk, updates and nothing about the game being playable. Enough of the deception. Please play the wolf game.
...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

If you issue concerns a particular location please send your character save here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Characters\`

You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by ProPeach** [comment]
Does the game crash when you try and join a server? As far as I know nobody has been able to join another player in multiplayer recently due to this bug #5935, before that it worked if the host opened the port 7777

**Comment by Reason147** [comment]
As long as I have been playing, multiplayer has never properly worked. This has been a thing for years, or at least the last time I tempted it. I never got it to work and gave up on it.

**Comment by Wagncs** [comment]
BUg is a programmer's error, tsunamayo, the owner who produced the game is misleading us, releasing small things and after YEARS, the result is the same as at the beginning: The game cannot be played in single player or multiplayer, it is just a studio in creative mode and a small tutorial with no more functions. Lack of love, respect and fear of the most high God, and of men, is corrected in the word tsunami so as not to suffer at the hands of the devil and his angels.

**Comment by tsunamayo** [comment]
@Wagncs Hi, sorry you dont like the game. As stated in the store page it is in early access (meaning it is not finished) and creative only for now. You can build ships, some player are spending 100s of hours on this game, so I wouldnot say it does not work. I would suggest applying for a refund, and sticking to non early access game.
Thanks

**Comment by Wagncs** [comment]
My friend, I love you and God loves you very much, thanks 
 yes pay for your game, every byte, you have the gift to make games 
 You know how to connect with technology, keep going. Most game producers make a single player or multiplayer game that you can use even in early access. The only problem is not being able to play it, as it only has creative and multiplayer which doesn't work on providers in Brazil. I have so much talent and good work and I can't use it by playing! But I would buy the game again if I need to support you. Sorry i used google traduction.

**Comment by tsunamayo** [comment]
@Wagncs Thanks a lot for the kind words, survival is in the works, so hopefully you can enjoy the full game soon. Cheers
