### ISSUE TITLE
[SUGGESTION] An option to disable ship rename and 30 minute reminder

### ISSUE THREAD

**Issue by Pawnp** [tsunamayo/Starship-EVO#6008]
Resurfacing this suggestion again:
https://github.com/tsunamayo/Starship-EVO/issues/5197

**Comment by Alkaliii** [comment]
The remainder, while helpful, blocks part of the UI making it hard to work around and it can't be dismissed quickly. Turning off newcomer messages doesn't disable it. If you believe the message should remain how it is, it would at least be nice to change the frequency or something.

**Comment by ProPeach** [comment]
Similar situation to #5953 yeah, it's the location that is the main issue for me. Ideally it should be in a position that does not block any UI you may have open

**Comment by tsunamayo** [comment]
@ProPeach @Alkaliii But this should have been fixed in a recent udpate. Do you still get message while in a UI?
I will make this a newcomer message.
