### ISSUE TITLE
[Bug] Filters and one-way tubes incorrectly allow non-matching items through

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#6012]
### Short Description of the issue:

The newly added filter tubes and one-way tubes appear to let items through that they should not.

I'm using a simple test bed:
![image](https://github.com/user-attachments/assets/4424e8c2-ade5-43a1-9409-47b8e7deb9dc)

There are four containers: gold, silver, copper, and iron. Each has a one-way output tube, and a filter input tube. The filter is configured to accept ores and ingots of the corresponding type. For example, the iron container is supposed to fill with iron ores, then eventually have them replaced with iron ingots:
![image](https://github.com/user-attachments/assets/16744cdd-9044-47a5-9826-006bed1cf1af)

I have the furnace configured as follows, although it was already pulling the ores in for processing before I activated the option to "pull automatically from connected inventories":
![image](https://github.com/user-attachments/assets/bb4ec025-1c14-41a9-b9b6-68be0e8449e1)

Silicon rods and copper ingots are pushed to the iron container through the iron filter: (**this is the main issue**)
![image](https://github.com/user-attachments/assets/05ea33fa-37c3-4947-88f4-eda1faa08a29)

To summarize the issue: The intended ores and ingots do not go into their designated cargo containers, and unintended items end up in the wrong container.

### Steps to reproduce the issue:

1. Spawn the attached blueprint in, or recreate a similar build.
2. Take control of the ship, find a patch of copper on a planet, mine a small sample of ores, then quickly jump out of the ship so you can start observing the flow of items
3. Due to another bug, you may have to fly your character near the ores (so they feel your pull) then quickly fly away (to avoid collecting ores in your backpack/hotbar) before the ship's collector will take ores in
4. Once the collector has taken in the ores, observe the flow of items

The items move something like this, you should verify this yourself while it happens:

1. The collector takes them in
2. The stones and copper ores move through the _iron filter_ and into the iron container
3. The arc furnace pulls the stones and copper ores from the iron container and smelts both
4. The arc furnace then pushes the refined silicon rods and copper ingots to the _iron container_ through the _iron filter_

Either the filters are not working, or the one-way tubes are allowing items to pass both ways.

### Environment
- Starship EVO version: 24w38a
- Graphics Card: 1070 ti

### Additional information:

The ship used: 
[Filter Test.zip](https://github.com/user-attachments/files/17152456/Filter.Test.zip)

**Comment by asanagisae** [comment]
As recommended by Peach, I removed the blue line connecting the arc furnace. As a result, the ores and rocks stay in the collector and do not move.

This suggests that the presence of a one-way tube causes items to "teleport" through the entire conveyor system?

![image](https://github.com/user-attachments/assets/3c71100c-78c5-4054-abd8-e2007d999db0)

**Comment by asanagisae** [comment]
If I remove the filter to the gold box, the ores end up in the gold box. The collector is "pushing" items correctly.

However, from the gold box, the arc furnace no longer pulls the ores for processing....

![image](https://github.com/user-attachments/assets/735f0dfe-8f9d-4ec8-98a8-5cac303783bf)

**Comment by asanagisae** [comment]
The one-way tubes are definitely bugged. After removing the red line exit, the arc furnace still pushes smelted copper into the iron container:

![image](https://github.com/user-attachments/assets/2dcbe8d9-af91-45fb-a144-9b0c56fadc9e)

**Comment by asanagisae** [comment]
Also, the "Create a new filter" button should be at the bottom of the modal window and below any newly added rows, not at the top.

In your current implementation, when you click the button at the top, it adds a new row at the bottom of the window, which is far away from where you clicked and not where you'd expect it to be. This leaves the user confused at first, it's a bad impression.

**Comment by tsunamayo** [comment]
@asanagisae Hi, thanks, both one-way and conveyor are fixed. For one-way it was not working in the case of push (like with the collector), and filter was not working in the case of ore/ingot set at something else than any.
Thanks for booking the issue!
