### ISSUE TITLE
[Bug] Dimensioning from ships with shipyard

### ISSUE THREAD

**Issue by Tackietacktack** [tsunamayo/Starship-EVO#6015]
### Short Description of the issue:

hi, some ship from me have wrong Dimensionings. after deleting the shipyard all is fine.

both shipyard have very small dimensions. something like 10x8x8 or smaller.

### Steps to reproduce the issue:
before

![Starship EVO 30 09 2024 17_50_38](https://github.com/user-attachments/assets/e66608b1-579c-4e2c-b13c-42b6dc3cb533)

video

https://github.com/user-attachments/assets/cd0974fb-6d07-4e1c-8c33-3b57e9d5bd97

after

![Starship EVO 30 09 2024 17_51_39](https://github.com/user-attachments/assets/96454768-8fbf-4d0c-8a19-3a7e0349fe11)

before

![Starship EVO 30 09 2024 17_52_07](https://github.com/user-attachments/assets/93068cec-9ad4-4f25-b6b0-f0e44aacaac4)

video

https://github.com/user-attachments/assets/85256a5b-b423-4b53-82b0-ec8b943f6f01

after

![Starship EVO 30 09 2024 17_52_33](https://github.com/user-attachments/assets/bdba419d-d816-49da-895a-edc2d875819b)

Blueprints:

[luftschiff v5.1 v38 luftschleuse.zip](https://github.com/user-attachments/files/17193134/luftschiff.v5.1.v38.luftschleuse.zip)

[Galandinger.zip](https://github.com/user-attachments/files/17193135/Galandinger.zip)

- Starship EVO version: 24w38a
- Graphics Card:

**Comment by tsunamayo** [comment]
@Tackietacktack Hi, this is unfortunately normal, as the dimension also encompass any gravity field or other field on your ship. It is for the physics engine, that would otherwise not get triggered.

**Comment by Tackietacktack** [comment]
I think, i understand you, its possible to make ship bounds greater with shipyard, gravity and logic field.
 but the shipyard dimensions are inside the ship bounds (don't leave the ship bounds). The air ship has the shipyard at top.
So i don't think thats normal, could you make a second view to it?
