### ISSUE TITLE
fix volumetric sensors

### ISSUE THREAD

**Issue by najlitarvan** [tsunamayo/Starship-EVO#6016]
as name indicates, the current sensors are extremely hard to work with, since they do not properly seem to detect if a thing in their bounds
https://cdn.discordapp.com/attachments/271723356795961345/1290683670361018449/image.png?ex=66fd5a56&is=66fc08d6&hm=a8a8a5667890a8fecf11150d71180f7222b681d59297aed83d4b3341140c2bfc&
https://cdn.discordapp.com/attachments/271723356795961345/1290683670918729771/image.png?ex=66fd5a56&is=66fc08d6&hm=07dabc002f29278b29defef662840c59c62623d5207e87dee6d258e00dfc3c90&
The light is connected to the volumetric sensor and the second entity is in the volumetric's detection volume, which should mean it should be lit up, the detect entity was on
[docking tester.zip](https://github.com/user-attachments/files/17212547/docking.tester.zip)
[satelite volumetric.zip](https://github.com/user-attachments/files/17212549/satelite.volumetric.zip)

**Comment by Crimson-Artist** [comment]
what are you settings for the volumetric sensor? in order to detect entities the trigger on entity enter needs to be set to true.

**Comment by najlitarvan** [comment]
> what are you settings for the volumetric sensor? in order to detect entities the trigger on entity enter needs to be set to true.

Yes, as stated in the original post at the end, the volume also tends to fail with player as well

**Comment by najlitarvan** [comment]
> I just tested it. Its working fine on my end. Does it persist after exiting the game and reentering?

turns out i needed to cycle the setting when palced give it the goold old fashioned off/on for it to register

**Comment by tsunamayo** [comment]
@najlitarvan Hi, so the problem was that the max bounds was inferior to the min bounds. I think the real issue is that it was showing well in the preview, so this is the thing I fixed for next build. I will also add some gizmo to improve the bound editing experience. Thanks

**Comment by najlitarvan** [comment]
@tsunamayo thank you
