### ISSUE TITLE
[Bug] Conveyor Router Issues

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#6017]
### Short Description of the issue:

There's a few issues affecting the new T-shaped Conveyor Router Pipes. These may not necessarily be "bugs", but they are not the behaviors that players would expect when looking at these setups.

The core "issue" is as follows. The arrow on the block points left or right. If it points left, then the connection point on the right does not allow items to flow in or out. However, visually that's not what players would expect, as it looks like the "one-way" tube, which points in the direction that items should flow.

Honestly, a free-flowing T-shaped tube (without the reversible arrow) would be much simpler. You can customize the flow direction you want, working in the way you expect, by using the new one-way tubes (after they're fixed with #6012).

One:

In this build, the ores should go from `collector > red cargo box > furnace`, but it does not. The ores are deposited to the red cargo box and stay there. Looking at this setup, players would expect the ores to freely move from the red cargo box to the furnace because the arrows point in that direction.

![image](https://github.com/user-attachments/assets/52295647-e302-4e66-a2b6-1d411e1a1fe5)

Two:

When you reload the world, the router pipes forget the left-right state they were set to (if you click them to make them different from when they were initially placed). If you save the blueprint and spawn a new one with a starter block, it also forgets the left-right arrow state.

![image](https://github.com/user-attachments/assets/c7b0e970-a234-4b1a-a7fb-72545c91558f)

Three:

You cannot rotate the router tube block to change the initial direction of the arrow to bypass issue two above, it always points the same way. However, it appears this may be because of issue four....

https://github.com/user-attachments/assets/75ae58e5-f0e2-437e-a8d2-638b538c6fa5

Four:

The router reads different directions from above and below (or front and back). *It simultaneously points in both directions.*

https://github.com/user-attachments/assets/04b7071c-a361-4f66-8e4f-4d4e06f243c6

Five:

After the pipes were reversed, the furnace pulled ores from the red cargo box, through the router tubes (against the direction of the arrow), and began smelting them.

This may be related to #6012, which was reporting on one-way tubes, but may also affect the T-shaped router tubes.

![image](https://github.com/user-attachments/assets/c77447d0-7ac3-410e-b693-530ea10332a4)

Six:

With the reversed pipes and the state from point five, the furnace then pushes the smelted iron ingots into the black cargo box. This means that the items moved _against_ the arrow when going from the red cargo to the furnace, then the items moved _in the same direction as_ the arrow when going from the furnace to the black cargo.

![image](https://github.com/user-attachments/assets/17519df4-a715-4da7-9eec-671e2f1ba317)

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 24w38a

### Additional information:

The ship used:

[Tee Test.zip](https://github.com/user-attachments/files/17251246/Tee.Test.zip)

The conveyor router tubes are "backwards" from their intended direction, as per point two above, because the game refused to allow me to place them in the correct orientation using the rotation key.

**Comment by tsunamayo** [comment]
@asanagisae Hi, thanks I am looking into this.

**Comment by tsunamayo** [comment]
@asanagisae Hi, so all should be fixed for 24w41a. Cheers!
