### ISSUE TITLE
Event gates resetting to default values in two cases

### ISSUE THREAD

**Issue by fellow-starmadian** [tsunamayo/Starship-EVO#6018]
### Short Description of the issue:
This issue is different from the prior bug report about event gates resetting on world reload when connected to an o2 system, which was made by a different user.

There are two cases I and other users on the discord have compiled here, where event gates will reset to their default values in their settings menu.  This means the dropdown changes to the top option, and the buttons for true and false and such are set back.  It's as if it's a fresh event gate placed from your hotbar.  I have verified that they are reproducible, steps and a video showcasing the bug below.
The two cases are: 
Event gates connected from a docking port when the port completes a docking procedure and connects to another port.
Event gates connected from a computer block (the orange block for ships stations and whatnot), reset to their default values when another event gate is connected from the same computer.  I have not verified if this happens if you connect an event gate to a DIFFERENT computer on the same blueprint.

### Steps to reproduce the issue:

Following the two cases above, the way to verify that this is happening is to change what the event gate is looking for from the dropdown menu inside the settings menu for the event gate in question.

### Environment
- Starship EVO version: early-access 24w38a
- Graphics Card: geforce RTX 2080TI

### Additional information:
video showing both bug cases and steps to reproduce (dont care to get it within 10MB)
https://youtu.be/k827vLGuPAc
player-prev and player.log files:
[Player (3).zip](https://github.com/user-attachments/files/17251432/Player.3.zip)
the ship I use in the video:
[tsuna fix plz event gate errors.zip](https://github.com/user-attachments/files/17251437/tsuna.fix.plz.event.gate.errors.zip)

**Comment by Tackietacktack** [comment]
Yoke and event gate have the same issu. Event gate is set of hotkey 1 but after some time in game is sets to left mouse klick. I dont must close the game for this issu.

**Comment by tsunamayo** [comment]
@fellow-starmadian Hi, issue is fixed for 24w42b. Cheers
