### ISSUE TITLE
[Bug] paint menu broken

### ISSUE THREAD

**Issue by Tackietacktack** [tsunamayo/Starship-EVO#6020]
### Short Description of the issue:
Its not possible to change colors with R

### Steps to reproduce the issue:

put a color in your hotbar 
close the tab menu
choose the color in your hotbar
change the color with R

### Environment

- Starship EVO version: 24w40a
- Graphics Card: 

### Additional information:

![Starship EVO 04 10 2024 16_45_45](https://github.com/user-attachments/assets/3279a042-3afe-4c27-bed6-e8c2f61f5daf)

![Starship EVO 04 10 2024 16_45_56](https://github.com/user-attachments/assets/192c2020-7951-4fb4-882c-4f22b96d7239)

**Comment by tsunamayo** [comment]
@Tackietacktack Okay I am working on it asap!

**Comment by tsunamayo** [comment]
@Tackietacktack Hi, issue is fixed for 24w40b. Cheers
