### ISSUE TITLE
New backpack

### ISSUE THREAD

**Issue by Tackietacktack** [tsunamayo/Starship-EVO#6022]
Hi, 
I have two small point, but i think that its not unknown points for you. 
1.
If i look to my feet i can see the thrust light.
But that isn't bad.
I think the thruster light is placed wrong. It must a little bit back under tje backpack.

2.
If you take out the helmet from equitment place and put it to the ground, Is it lost.

**Comment by tsunamayo** [comment]
@Tackietacktack Hi, issue fixed for 24w41a. Chers
