### ISSUE TITLE
suggestion data reader when using link tool

### ISSUE THREAD

**Issue by najlitarvan** [tsunamayo/Starship-EVO#6026]
![image](https://github.com/user-attachments/assets/2ee46785-4a4c-47ad-9754-2318d3658e93)

in my opinion gates (both logic and event gates)
should display the state of inputs (if the inputs have been tagged, their tags should show)
and show the value of the input
and show what setting it is on
suggested idea visual implementation
![image](https://github.com/user-attachments/assets/074f2a79-28df-4451-8dd4-826ebd850cce)
would imo heavily help with dealing with logic and debugging and seeing what is wrong

**Comment by tsunamayo** [comment]
@najlitarvan Hi, first idea implemented for next update.

**Comment by ProPeach** [comment]
This is a really cool idea! Thanks for putting it through Tsuna 🫡

**Comment by tsunamayo** [comment]
@najlitarvan Done for 24w41b. Cheers
