### ISSUE TITLE
[Bug] 24w40a- Prefabs do not work

### ISSUE THREAD

**Issue by Crimson-Artist** [tsunamayo/Starship-EVO#6027]
I am not able to paste the prefabs that I had made in previous versions. I can drag the prefab icon into my hotbar but when I try to paste them nothing happens, not even a preview ghost.

Strangely, the copy/paste tool works just fine.

**Comment by tsunamayo** [comment]
@Crimson-Artist Hi, issue is fixed for 24w42a. Cheers
