### ISSUE TITLE
Prefabs don't render wend placement onto a build

### ISSUE THREAD

**Issue by Reason147** [tsunamayo/Starship-EVO#6029]
### Short Description of the issue:

...as the title states, the prefab items do not render or are unplaceable on a ship 

### Steps to reproduce the issue: unknown

...

### Environment
- Starship EVO version: Build 24w41a
- Graphics Card: Nvidia GeForce RTX2050

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![20241007091042_1](https://github.com/user-attachments/assets/69bef854-acfe-456c-9bbf-3c9440a83801)

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

If you issue concerns a particular location please send your character save here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Characters\`

You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by chillshock** [comment]
im experiancing the same issue in game

**Comment by tsunamayo** [comment]
@Reason147 @chillshock Can you guys send me your prefab? Thanks

**Comment by ProPeach** [comment]
Could this be the same bug as #6027 but the fix just hasn't hit live yet?

**Comment by chillshock** [comment]
hi i was playing experimental and could not get prefabs to work. so i reverted back to normal game and there working.

im admit this all confuses me. took me ages to find prefab folder. however i downloaded a prefab from steam workshop [Player height reference] and its not in there. but i can use ingame. same a ship blueprints from workshop.

**Comment by tsunamayo** [comment]
It should be fixed in experimental since last update.

**Comment by tsunamayo** [comment]
@chillshock Sorry yes I cant push to default for now, so the bug was only concerning experimental, but it is fixed for next update. Thanks

**Comment by chillshock** [comment]
still a very good game keep up the good work :)
