### ISSUE TITLE
[Suggestion] Climbable ladders

### ISSUE THREAD

**Issue by COMICLER** [tsunamayo/Starship-EVO#6031]
currently ladders aren't climbable and are just a decoration. it would be nice if that changed so we have for functional blocks

**Comment by Reason147** [comment]
kindy useless scents we can just use are jetpack to get one floor to floor.

**Comment by ProPeach** [comment]
The last update added a jetpack as a separate item, what if you're in survival and don't have one?

**Comment by COMICLER** [comment]
> kindy useless scents we can just use are jetpack to get one floor to floor.

I have no problem getting from one floor to the other. There's just a ladder block, and id like to use it

**Comment by BigBadKangaroo** [comment]
> > kindy useless scents we can just use are jetpack to get one floor to floor.
> 
> The last update added a jetpack as a separate item, what if you're in survival and don't have one? Especially with how hard it is to make multi-floor elevators, ladders would help

Especially for Survival gameplay this will become a useful feature. If a player has no Jetpack (maybe even no more jetpack fuel for future updates), then we will need manual ways to cross our ships. When the power's out and your ship only has an elevator, you'll be stuck on one floor.

... and it's just a game thing, I mean, nearly every game has a ladder ...

**Comment by Reason147** [comment]
you pary your ship is one floor

**Comment by Reason147** [comment]
> > kindy useless scents we can just use are jetpack to get one floor to floor.
> 
> The last update added a jetpack as a separate item, what if you're in survival and don't have one? Especially with how hard it is to make multi-floor elevators, ladders would help

Jetpack has been in the game for a while. Yeah, I agree with you that the latter is unseable; it's just a prop right now.
