### ISSUE TITLE
[Bug] Item collector collecting "oxygen" and depositing into cargo

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#6032]
### Short Description of the issue:

The item collector, which normally collects ores, is able to collect gas (presumably oxygen) and deposit invisible items into connected cargo containers.

### Steps to reproduce the issue:

1. Load the attached world
2. Take control of the square-shaped ship
3. Lower the ship so that the fuel scoop collects a decent amount of water
4. Raise the ship out of the water (to prevent the currents from moving the ship while you inspect the ship)
5. Observe that oxygen is being generated and expelled by the ship (in the blue area)
6. Observe that the item collector (yellow) appears to be collecting gas
7. Observe that the cargo container is slowly filling up with some unknown item

### Environment
- Starship EVO version: 24w38a
- Graphics Card: 1070ti

### Additional information:

Here's the world, hopefully immediately ready for reproducing the issue:

[Meridian.zip](https://github.com/user-attachments/files/17280421/Meridian.zip)

Here, it appears that the item collector is collecting some kind of liquid/gas:

https://github.com/user-attachments/assets/f94e4303-3ec6-427f-a76a-186c5def6ba5

Here, the collected gas is filling up the cargo box:

https://github.com/user-attachments/assets/baeecf0b-4042-42ab-bd70-b3e590af16d5

**Comment by tsunamayo** [comment]
@asanagisae Thanks for the test case. By the look of it it is the h2 farm that is pushing fuel to the cargo through the docking port. I will fix that! I am not sure the collector is collecting gas though. Beside the VFX did you saw actual fuel inside the collector inventory? Thanks

**Comment by asanagisae** [comment]
When I checked the collector, it was always empty. I thought maybe it could be pushing stuff instantly as soon as it collected it, but your theory sounds more plausible. I can't think of why the VFX would trigger if it wasn't collecting. Maybe the code hides some strange secrets. 😉

So, if the docking port can push things through conveyor tubes, when can we expect to transfer regular cargo items through the docking ports? 😄

**Comment by tsunamayo** [comment]
@asanagisae You should already be able to transfer stuff through docking port? It must be a bug I will check.
The collector was simply trying to collect a rock blocked beneath the platform ^^.
Btw issue fixed for 24w41b. Cheers

**Comment by tsunamayo** [comment]
@asanagisae So I tested and you can transfer Items through docking ports (at least manually - maybe you were talking about auto-transfer?)

**Comment by asanagisae** [comment]
I might be remembering some very old information. I haven't been able to dock two entities together at all for the last few patches. Remember when I was trying to get the mech chair to dock to a grounded port? I've never successfully connected docks together since, so I haven't confirmed for myself when they started working with cargo.

I also assumed because the "tank join" for squared tube connectors (yellow) does not appear on the docking port, but the "tank join" does appear for the rounded pipes (blue).

![image](https://github.com/user-attachments/assets/e1f8335c-8890-4b34-b475-d0479e312638)

Thanks for checking!
