### ISSUE TITLE
turret qol

### ISSUE THREAD

**Issue by najlitarvan** [tsunamayo/Starship-EVO#6033]
a turret controller could have a logic switch hooked to it, if the switch is on the turret will work normally
if the switch is off, the turret will no long react to inputs, if the turret has a resting position it will return back to it
new event gate events to listen to
is turret on/off
is turret in resting position

**Comment by ProPeach** [comment]
On/off for the Turret Computer would be fantastic indeed.

I'm not sure the Event for on/off is needed, as you can use the logic signal from the Switch for that

**Comment by najlitarvan** [comment]
> On/off for the Turret Computer would be fantastic indeed.
> 
> I'm not sure the Event for on/off is needed, as you can use the logic signal from the Switch for that

true, though the rest position one would be nice, especially for deploying turrets

**Comment by tsunamayo** [comment]
Yes I plan on adding that. thx

**Comment by najlitarvan** [comment]
> Yes I plan on adding that. thx

Is it planned to come alongside the reworked turret rotation bounds system or later?

**Comment by tsunamayo** [comment]
Added for 24w42a. Cheers
