### ISSUE TITLE
[Suggestion] Exemples how to start a survival game

### ISSUE THREAD

**Issue by Vincent14** [tsunamayo/Starship-EVO#6035]
I'd share some feedbacks we can discuss, let me know if that's not the right place, I'll move it somewhere else.

About how to start the survival, good examples to me are:

1. I played No Man's Sky where you start by fixing an existing damaged ship. The ship tells you "My engine is broken, insert 50 cobalt to fix this". You'll have to grab ores around, & discover the survival mecanics you'll have to perform all along the game (e.g: reload air filters, survival system of the suit, oxygen to breath, why not hydrogen or electricity for the jetpack). Then the damaged ship will require basic crafted stuff like metal plates in order to let you take off. The starting planed is hostile since it act like a natural countdown to death if you ignore the survival things, & let you the pleasure to find comfort on another planet you chose yourself.
2. I played Craftopia, where absolutely everything you nudge (tree, rock, animal) bring a success notification with progress bar like "You took 5 wood [==        ] 5/100" then you unlock an achievement like "Congrats! You now have 100 wood". You have a list of achievements to unlock, the new one will be a tool requiring 100 wood. It's not technically a tech tree because you can bypass it if another player give you a tool, but that's just the reward mechanism
3. I played Eco where dedicated rooms are required to place some blocks & have them working. E.g. I want to add a bed. The bed will check it is placed in a box of blocks, and the box only contains bedroom elements. If so, I get a big bonus of permanent experience points **multiplicator**. Everything that give experience points will grow faster, because I have a house with a proper bedroom. Everytime I unlock a room type by placing only meaningful blocks inside, I can use the related blocks, e.g. the hoven will only work in a kitchen. Could be transposed for medbay/medical stuff, enginee room, electric locker, cockpit etc, and adjusted if we only want bonuses or require this to be able to turn it on. This really give a logic to build bases in that game. **In Eco, it's a tech tree where you unlock parts on a announced time bar basis you can speed up by following rules giving experience multiplicators**. Let's say the game tells you whatever you do, you'll unlock thrusters in 5 days, earning 5 XP points every minutes, you can unlock them in 2 days if you build a ship with a cockpit room (door, seat, joystick & screen) because you now earn 10 XP points by minute

**Comment by tsunamayo** [comment]
Thanks for the examples.
I wont do a ship fix as the goal is to build stuff although you will scavenged your crashed ship.
Yes it is a bit how I am doing, I have a few achievements to give hint to the player on what to do next.
I wont do the explerience system of Eco (at least like that), but it is an interesting one. The system of "room" should be implemented a bit similarly when it is time for crew management.
Cheers

**Comment by Vincent14** [comment]
Thanks you for your feedback 👌
