### ISSUE TITLE
[BUG] broken Character save

### ISSUE THREAD

**Issue by Tackietacktack** [tsunamayo/Starship-EVO#6036]
### Short Description of the issue:
hi tsuna,

i have worked on my hanse station and have generate one station and repeat this two times.
station generation has worked.
after a zigarett break the game was frozen.

now, i can´t load the world. i have named the world: galaxy

i dont need the character save, but that is f**cking hammer Bug if we get it with a survival save

![Starship EVO 12 10 2024 12_12_20](https://github.com/user-attachments/assets/17dccd39-14da-4f5f-88e3-63875deb5acc)

![Starship EVO 12 10 2024 12_25_33](https://github.com/user-attachments/assets/5597ee12-c689-4fe2-a69c-c006b3500a3a)

### Environment

- Starship EVO version: 24w41a
- Graphics Card: 
[galaxy.zip](https://github.com/user-attachments/files/17349676/galaxy.zip)
[Player.log](https://github.com/user-attachments/files/17349677/Player.log)
i don´t know if this help
[output_log.txt](https://github.com/user-attachments/files/17349693/output_log.txt)

**Comment by Tackietacktack** [comment]
Could be the problem, i have a event gate linked to a docking connector. That quest after" is docked" but the docking connector works for a station modul.
So, i have the idea, that event gate to docking connector with station generation don't works?

**Comment by tsunamayo** [comment]
@Tackietacktack Hi, I can load the world just fine, you forgot to remove a space at the end of the name it seems. It should be "galaxy.mpc" no "galaxy .mpc". Cheers
