### ISSUE TITLE
[Suggestion] Allow Antennas to be turned on/off with logic

### ISSUE THREAD

**Issue by Crimson-Artist** [tsunamayo/Starship-EVO#6037]
Something that I've been thinking of since antennas were added. Since they tag an entity as targetable by ships we should be able to turn them off with logic. This would allow us to hide things or draw attention to it when we want. 

This should also include an entity's ability to be used as a lightcruse autopilot target from the map screen. The fact that everything shows up on our maps is bad enough but also being able to target it for lightscruse prevents us from building secret facilities. 

To keep this from being overpowered, when scanners are added they should be able to force an entity to be targetable even if all its antennas are off. taking damage should also make an entity targetable for a time.

**Comment by tsunamayo** [comment]
@Crimson-Artist Hi, done for 24w42a. Cheers
