### ISSUE TITLE
[Bug] Can't interact with entity after spawning it in

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#6038]
### Short Description of the issue:
When spawning in an Entity using the Starter Block, I can't interact with it until I restart the game.

This can happen with existing ships or new Entities created by just placing the Starter Block down,

The trigger seems to be related to unspawning an Entity, I can't nail it down exactly. Check this video to see the bug in action, you can see some Starter Blocks spawn without the blue outline around them.

https://imgur.com/SXY46mb

### Steps to reproduce the issue:
- Place a Starter Block to create a new Entity
- Unspawn Entities
- Place new Starter Blocks
- Try to interact with the new Entity

### Environment
- Starship EVO version: 24w41a
- Graphics Card: RX6700XT

### Additional information:
[Player.log](https://github.com/user-attachments/files/17365180/Player.log)

**Comment by tsunamayo** [comment]
@ProPeach Hi, I managed to reproduce, I keep you posted.

**Comment by tsunamayo** [comment]
@ProPeach Hi, fixed for 24w42b. It was only if the unspawned entity had the same hitbox size as the new one, so pretty much limited to starting block in practice, but that explains a few bugs that where booked previously.
Cheers
