### ISSUE TITLE
[Suggestion] Smaller turret axis holograms

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#6042]
Just a quick suggestion - The white and green and red arrow overlays are quite large when working on smaller turrets so the addition of the new gizmo makes it quite cluttered. Could the overlays be scaled down a little bit, maybe scaling with rotor/hinge size?

![376578495-2c88a421-92d4-4574-bca5-53c5057e6a8c](https://github.com/user-attachments/assets/db0095b2-4a82-4eb8-8b58-87804c4b176d)
This is quite a small turret, only 1.5m long so you can see the issue is significant at smaller scales.

![image](https://github.com/user-attachments/assets/f4818c46-5538-4402-af68-12571ba39c1c)
With 1m scaled components, it's not as bad but it is still quite busy in the middle as there are many bits of information overlapping eachother

As a side note, it's such a joy to have such smooth moving turrets! No longer getting snagged into hull or tiny amounts of clipping, great move ditching the collision prebaking from before

**Comment by BigBadKangaroo** [comment]
Yes, indeed smaller icons for smaller turrets would be great. Ideally they would scale up/down with the CE size.
![20241015205630_1](https://github.com/user-attachments/assets/590d7349-fe49-456a-9ce7-0408db1db063)
![20241015205636_1](https://github.com/user-attachments/assets/bcbaf785-fec3-41d4-a64b-f71dba22aff5)

**Comment by tsunamayo** [comment]
yep indeed, I also forgot to remove a few axis I had for debugging.

**Comment by tsunamayo** [comment]
@ProPeach Hi, fixed for 24w42b. Right now the gizmo scale with the rotator grid size. Cheers
