### ISSUE TITLE
Save-bound performance issues after new update

### ISSUE THREAD

**Issue by kynamats** [tsunamayo/Starship-EVO#6044]
### Short Description of the issue:
After the 24w42a update, I loaded up my 'current' world, started in August, and while trying to work on a new turret, found some awful performance issues, with framerates dropping into the single digits while moving the character or cursor. With community help, I've established both that no such problems exist in a new save with the same blueprints loaded up, and that the performance issues are replicable with the world save.
I'm not sure what's triggered this, but I wanted to share so that maybe such issues can be avoided in future - for me being a creative player moving to a new save with each update is no big deal, but if this happened to someone's long-term survival worldsave it would be a terrible experience.

I've attached images of the 'normal' framerate graph and the framerate graph while moving the cursor around in the affected save.
...

### Steps to reproduce the issue:
Load up the attached save and look at the nearby entities with a block/tool in hand. 
...

### Environment
- Starship EVO version: 24w42a
- Graphics Card: 3070ti

### Additional information:
![image](https://github.com/user-attachments/assets/f62a229f-0a0f-45c6-9846-8300d428235a)(normal framerate)
![image](https://github.com/user-attachments/assets/c353c906-0c54-49f4-a6c7-57757a728280)(affected framerate)
[w032.zip](https://github.com/user-attachments/files/17381832/w032.zip) (affected world save)

[Player.log](https://github.com/user-attachments/files/17381816/Player.log)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

If you issue concerns a particular location please send your character save here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Characters\`

You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by ProPeach** [comment]
I was able to reproduce this consistently too by loading up the attached world. It seemed like it happened most often when the Turret Collection blueprint was in frame (did not lag when that bp was unloaded via freezing occlusion culling), but it might not be the exact cause as loading that bp into a new world does not produce the issue as Kyna says o7

**Comment by BigBadKangaroo** [comment]
Can confirm this happend in my "old" world save as well. I tested my new mech on a planet and the framerate dropped drasticly. 
As you mentioned, new world save, same old BP, no problems -> old world save, same old BP, massive performance issues.

For a survival world this could be a really frustrating way to lose progress if the world becomes unplayable.

**Comment by tsunamayo** [comment]
@kynamats Hi, thanks for the heads up I am looking into this asap.

**Comment by tsunamayo** [comment]
@kynamats Hi, I manage to reproduce with your world. It is coming from the decals pass on the GPU. Are you 100% sure it started to freak out after the last update? First where you in default or experimental (if in default then it might be one of the last 3 update that broke something).
Amazing turrets btw!
I keep you posted.

**Comment by kynamats** [comment]
@tsunamayo I've been in default for a while since it seems that's where you push updates nowadays, and I can't be sure it was the most recent update, no. I've been busy with other games since around 24w38a , but the new turret tech has been on my Wishlist of features for a long time so I wanted to try it out and build some deployable turrets. Sorry, this probably doesn't help narrow it down much!

**Comment by tsunamayo** [comment]
@kynamats Okay issue is fixed for 24w42b. Cheers
