### ISSUE TITLE
[Dev Asks] Help with Lord Commissar's PFS station Hub.

### ISSUE THREAD

**Issue by tsunamayo** [tsunamayo/Starship-EVO#6046]
Hello there,
So I am doing a pass on the deep-space gameplay, I want to work on stations, factions and consortium.

I finally managed to have Lord Commissar station generate (I had to change the code, add a new Station Up params as they where built sideways)
![SNAG-0905](https://github.com/user-attachments/assets/2670545b-5533-4338-923f-33791583df21)

I realized that the hub spaces for medium Kiosks are too small: 8m vs the standard size of 12m.

So first up do you guy know him, I know he is no longer active but I would just need his permission to tweak the interior layout.
Then if somebody would be up to tweak the interior (with his approval hopefully).
It should not be a heavy work.

Cheers

**Comment by ProPeach** [comment]
@tsunamayo got a response from Lord Commissar, he's very happy for his station be be used an modified!
![image](https://github.com/user-attachments/assets/90a4f3b8-9fef-4bce-b2f7-19a23f8bc120)

**Comment by tsunamayo** [comment]
@ProPeach Okay great! I will send a few screenshot, I think we will have to clean the first floor (I mean ground zero) as even the little kiosks feel too cramped.

@5URG3 Glad to see you here, I hope you are doing good! I will ping you by mail to ask a few things about SI and Hyperion, as I will add corpos outpost and Factions soon. Also are there still some active builder on Stellar Shipyard? I will need some build, like a trader ship, I was about to make a post here.

**Comment by tsunamayo** [comment]
@ProPeach So here the empty layout.
![SNAG-0906](https://github.com/user-attachments/assets/19d78dc6-abe2-4c11-a211-47257b544449)
4 spot for the large kiosks in never gonna fit unfortunately. I think we can afford only one.
=> I think we need to remove the ramp that cross the inside space, then put a single 12x12 kiosks inside, and then 4 smaller kiosks on the corner. On idea I had was to put the docking connector on a rotator at 45deg angle, so we still get some space on the side.
If you have other ideas on how to do it please don't hesitate. The goal is not to have the maximum number of kiosks though, it has to not feel too cramped.

Even the smaller one feels a bit cramped atm:
![SNAG-0907](https://github.com/user-attachments/assets/c31df10f-6f10-4374-9166-75ae645034b8)

Second floor is perfect though:
![SNAG-0908](https://github.com/user-attachments/assets/ba1398db-5673-4493-ae83-824ace72af8c)

=> tell me if you have trouble with the kiosk auto-spawning, it should work as it (the station module wont work until I push the changes I made)

Here are the modules with correct settings (again still need the update to spawn properly):
[PFS Station Modules.zip](https://github.com/user-attachments/files/17426320/PFS.Station.Modules.zip)

Thanks a lot for the help!

**Comment by 5URG3** [comment]
@tsunamayo Hello! Yeah, please let me know what you need. I've asked on the server and we have a handful of builders that would like to help.

Can you define what you mean by a "trader ship"? 
How will the player interact with this ship? Will it be by remote communication, with a pop up menu? Or will the player dock with the trader ship and interact via kiosks? Or did you have something else in mind? 

Please send us a specification and we'll see what we can do.

**Comment by tsunamayo** [comment]
@ProPeach Thanks a lot I am having a lot at it. Yes this is what I feared for the 45 angle thing.

**Comment by tsunamayo** [comment]
@ProPeach Okay thats is perfect, thanks for the help! I can finally integrate this bad boy! The pathway are very clean so I am totally keeping them.
Yeah it was a bit dark but actually it does not prevent the player from seeing, it was quite moody so I like it overall.
I noticed it had a toilet ;). I remember the bar it was nice.

Thanks a lot to Lord Commissar, soon I can integration the full faction too.

**Comment by ProPeach** [comment]
Great to hear, glad it worked out!
