### ISSUE TITLE
[question] in regards to volumetric gizmo tool

### ISSUE THREAD

**Issue by fellow-starmadian** [tsunamayo/Starship-EVO#6047]
as per this comment: https://github.com/tsunamayo/Starship-EVO/issues/6016#issuecomment-2415362338

would this mean that you still allow the menu editing of the volumetric sensor, and the gizmos are an addition to this?  
Being able to copy and paste values, or even set them to high values like 99,999 for logic based radars, or any other number of uses, is a lot easier without having to drag out the dimensions manually.

**Comment by najlitarvan** [comment]
Seconded, having both in here would be better then just gizmoz

**Comment by tsunamayo** [comment]
Yes I still want to allow access to the normal setting. Thanks
