### ISSUE TITLE
[Bug] Missaligned texture on the Rotor Brick

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#6055]
### Short Description of the issue:
The Rotor Head has a misaligned texture, offset from the Rotors centre axis

### Steps to reproduce the issue:
- Place a Rotor
- Inspect the Rotor Head

### Environment
- Starship EVO version: 24w42b
- Graphics Card: RX6700XT

### Additional information:

![image](https://github.com/user-attachments/assets/9ebd1eb5-09f2-40de-a786-c3794a697185)

**Comment by tsunamayo** [comment]
@ProPeach working on it, I think this bad boy also needs a visual reference of the 0 angle.

**Comment by ProPeach** [comment]
I 100% Agree! It would be especially useful to have a reference on the placement ghost too

**Comment by tsunamayo** [comment]
@ProPeach Done for 24w43a. We already have a gizmo on the placement ghost that shows that. Maybe it is not clear where is the 0?

![image](https://github.com/user-attachments/assets/1149903d-03a0-4a83-9cd7-2956769aa175)

**Comment by ProPeach** [comment]
Now you say it seems obvious haha, I suppose I never made the connection. Is it possible to have a different colour on the gizmo element to give it more contrast? 
![image](https://github.com/user-attachments/assets/5896897c-5dd6-400f-b2d3-71c48a0857dd)

**Comment by tsunamayo** [comment]
![image](https://github.com/user-attachments/assets/f92ed4a9-ff5e-4a19-b4f5-0abe58f87f97)
Done
