### ISSUE TITLE
Tank Joins protruding through Connector Blocks

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#6056]
### Short Description of the issue:
When connecting a Pipe to a Connector, the resulting Tank Join brick that spawn pokes through the Connector. Even if the pipe is significantly smaller than the Connector
![image](https://github.com/user-attachments/assets/31bd9370-5cc1-426c-8c1f-e080834392db)

### Steps to reproduce the issue:
- Place a Pipe
- Place a Connector on the pipe

### Environment
- Starship EVO version: 24w42b
- Graphics Card: RX6700XT

**Comment by tsunamayo** [comment]
@ProPeach Yep I have seen that on spawning some module, I will fix it!

**Comment by tsunamayo** [comment]
@ProPeach Fixed for 24w43a. Cheers
