### ISSUE TITLE
event gates missing toggle/pulse

### ISSUE THREAD

**Issue by najlitarvan** [tsunamayo/Starship-EVO#6062]
so i have noticed that some event gate option do have a toggle/pulse option and some don't, would be nice if all event gates possesed this ability
mechanism listening event gates suffer from this 
![image](https://github.com/user-attachments/assets/b55d22ef-bfcf-4bb0-a6fa-dc52e29236b8)

**Comment by tsunamayo** [comment]
@najlitarvan it depends on the nature of what you listen to. If you listen to a pulse then you can pick toggle or pulse.
If you listen to a value then it will only trigger once the condition is met.
Thanks
