### ISSUE TITLE
suggestion truth table calculator block / programable microcontroller

### ISSUE THREAD

**Issue by najlitarvan** [tsunamayo/Starship-EVO#6063]
a block that would allow for multiple inputs and would show their tagged names and multiple outputs, would allow the player to add entries for truth table diagrams, imo this blocks would help heavily decrase the amount of physical logic needed and would also help satisfy those who ask for a programing block
if i imagine the ui
on the top be the input names and the output names 
entries could be added where inputs are defined and what would the outputs look like for said set of inputs
default for a combination would be all inputs are zero

**Comment by tsunamayo** [comment]
@najlitarvan Hi, yes this has been talked and suggested many time ^^
