### ISSUE TITLE
[Suggestion] Npc for our builds? 

### ISSUE THREAD

**Issue by Tackietacktack** [tsunamayo/Starship-EVO#6069]
Tsuna, could we get deco npc?
Idea is, that we get for creative mode something like a eventgate to spawn npc on seats.
Then we can get a co-pilot or with the stand seat a standing guard or someone who stand in a kiosk or passengers in huge ships.
I'm so lonely😉
Cheers

**Comment by tsunamayo** [comment]
@Tackietacktack Well yeah I want to work on that but that is a big dev...
