### ISSUE TITLE
[Bug] Sound bug while using linking tool

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#6071]
Hi there,

I finally found out why this bug happend to me, so here's the report.

When linking two connectable blocks together with the link tool, the "linking sound" keeps playing even when you stop using the tool.
However, this only happens when you press Shift (in order to connect multiple blocks to one single block, i.e. turret computer) and simultaniously (or accedential) switch to a different hotbar with the mouse wheel while pressing shift.

I noticed that bug a few times and actually quite a long time ago, but I never figured out what it caused. I now can reliable reproduce this in the above mentioned way.

https://github.com/user-attachments/assets/244dbbcd-ca7d-4672-9b34-fb19cea2fd1a

*I just noticed that when pressing shift and scrooling to the next hotbar, the hotbar doesn't change visually, but the multitool/ link tool disapears.

And there's no way of getting rid of this sound except a game restart. I tested to reset the sound options ingame, but that doesn't change anything.

**Comment by najlitarvan** [comment]
happens to me very often as well

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, issue is fixed for 24w44b. Cheers
