### ISSUE TITLE
New station's landing pad too small

### ISSUE THREAD

**Issue by SlimSumo** [tsunamayo/Starship-EVO#6079]
### Short Description of the issue:

Hello. I can't land my ship on the new station even though my ship is small enough to land.

### Environment
- Starship EVO version: 24w44a

### Additional information:

![Pad](https://github.com/user-attachments/assets/d612d09a-bf1d-40d7-95bb-c55cecfbf857)
![Pad2](https://github.com/user-attachments/assets/21bf1f99-7f5c-4652-91ed-6c6e476f1290)
I'm just hovering the landing pad on the screenshot.
[Smuggler.zip](https://github.com/user-attachments/files/17576125/Smuggler.zip)

P.S. The new station style is beautiful !

**Comment by tsunamayo** [comment]
@SlimSumo Hi, the shipyard is much bigger that what is indicated in the text. Can you send me your player save? I need to test it in the wild. Thanks

**Comment by tsunamayo** [comment]
@SlimSumo Hi, issue is fixed for 24w44b. I like your ship, I want to integrate it but we need to give it a proper name ^^
Cheers
