### ISSUE TITLE
[BUG] URGENT! Event gate corrupting entity! 

### ISSUE THREAD

**Issue by CoasterBlock** [tsunamayo/Starship-EVO#6080]
### Short Description of the issue:

Placing an event gate and connecting it to a rotor, can sometimes cause it to not register that it has been connected, bricking your save., 

### Steps to reproduce the issue:
Build a ship:

- Place an event-gate
- Try to link it to a rotor
- Watch to see if the icon of the gate changes
- the gate will appear to be connected
- interact with the "pseudo connected" gate
- you will freeze
- force close the game
- relog
- your entity will now be transparent, but can still be interacted with

If you DID NOT save your ship after this has happened, you can safetly respawn it, nothing will be broken. HOWEVER,
if you save the ship in the invisible and corrupted state it is unrecoverable. 

...

### Environment
- Starship EVO version: 24W44a
- Graphics Card:  2080 Super

### Additional information:

[Player.log](https://github.com/user-attachments/files/17576667/Player.log)

**Comment by najlitarvan** [comment]
> If you DID NOT save your ship after this has happened, you can safetly respawn it, nothing will be broken. HOWEVER,
> if you save the ship in the invisible and corrupted state it is recoverable.

i think you meant unrecoverable?

**Comment by CoasterBlock** [comment]
@najlitarvan Oh yeah, thanks for that. I overlooked that typo.

**Comment by tsunamayo** [comment]
@CoasterBlock Hi, thanks I am looking into it!

**Comment by tsunamayo** [comment]
@CoasterBlock I am doing your test case, I dont have any issue. Questions:
1) do you mean connect the rotator to the event gate (event gate works that way if you want to listen to the rotator)
2) can you detail: interact with the "pseudo connected" gate. Do you mean open the config screen?

I do see an error in your log though, so I would like to reproduce it!

Thanks

**Comment by tsunamayo** [comment]
@CoasterBlock Can you send me your ship, error happens when your ship is loading. Thanks

**Comment by CoasterBlock** [comment]
@tsunamayo Hello tsuna, the circuit was indeed connected to a slider a long time ago, its a prefab of a cuircuit I used to make a slider go back and forth continuously. It also works on rotors and pistons. In the blueprint I use it to make a rotor move from 0 to 360 and back. With "pseudo connected" I mean that the rotor was visibly attached to the gate. A logic tool showed a line from the rotor to the gate, but the gate still showed "?" instead of the "<->" symbol.  Trying to open the confic screen in this state caused the gate to lock my game. 
I dont think I have the BP anymore, as I unspawned it, and thankfully, it wasnt saved so my build was still fine. 
I can send you a setup that was identical to the one that caused the bug. 


The blueprint is the setup I had when I experienced the bug, it is all setup, all you need to do is interact with the gate, and it will lock up your game. Once you force close and rejoin the world, the entity will be invisible and it wont load. You can even add something to the end of the rotor. But anything connected to the rotor or the main entity will be bugged. 
[Bug Report Event gate wierdness.zip](https://github.com/user-attachments/files/17584649/Bug.Report.Event.gate.wierdness.zip)
