### ISSUE TITLE
[Bug] Old debugging blueprint spawning in-game [24w44a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#6081]
### Short Description of the issue:
One of the versions of the Mistral that I sent to you as part of a bug report is present in the game. 😄 

I am currently updating the Mistral so all systems are working, so you should be able to add the newest version soon.

### Environment
- Starship EVO version: 24w44a
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
![20241030152515_1](https://github.com/user-attachments/assets/a9584f09-30c9-4182-9d10-ecb04fed8bd4)

[Player.log](https://github.com/user-attachments/files/17578064/Player.log)

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Hi, gotcha, I am not sure how it ended up here... Cant wait for the new stuff! We have to put some more AAM in the game, especially the whirlwind as it is on the game cover after all. I have the v5 version, not sure if it was missing something. 
Cheers

**Comment by tsunamayo** [comment]
Fixed for next update.
