### ISSUE TITLE
[Bug] Loose station modules

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#6082]
### Short Description of the issue:

After the recent update some stations modules seem to be loose in space, with incomplete stations. 

![image](https://github.com/user-attachments/assets/4f25de11-aee6-43cc-b67f-b26da686e872)
fig1: incomplete station sample

![image](https://github.com/user-attachments/assets/8e153483-b517-4098-a8f6-d65c73f974c2)
fig2: there are 4 scattered loose modules close to this planet
...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 24ww4a (experimental)
- Graphics Card: gtx 1660 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[Player.log](https://github.com/user-attachments/files/17579417/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

If you issue concerns a particular location please send your character save here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Characters\`
[RING STATION.zip](https://github.com/user-attachments/files/17579421/RING.STATION.zip)

You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by ProPeach** [comment]
These look like the smaller station hubs outlined in the patchnotes, I'm not sure they're fragments of larger stations
![image](https://github.com/user-attachments/assets/a19f8b11-d15f-42b9-81ee-d5bb9dd80866)

**Comment by tsunamayo** [comment]
@Uncle-Ulty Yep those are smaller corpo hub. There are even smaller fuel hub and cache. I need to add plenty of smaller POIs for missions and for NPCs to wander around (and hopefully dock to)

**Comment by Uncle-Ulty** [comment]
But how do I access them? There aren't landing pads, I'm kinda confused
