### ISSUE TITLE
[Bug] After 24w44a station generation

### ISSUE THREAD

**Issue by Tackietacktack** [tsunamayo/Starship-EVO#6083]
### Short Description of the issue:
to build stations is impossible at the moment.
3 point i have found:

1. in entity menu you have not the same station modul typs like the docking controller.
 no shipyard inside entity menu and new ones landing pad , fuel hub, cargo cache are not in docking controller

same in: entity menu station /generation/add a new modul type ;  there are not the same modul types

![Starship EVO 30 10 2024 21_43_20](https://github.com/user-attachments/assets/28e864cd-56ec-4503-9a06-f2be5795b34d)
![Starship EVO 30 10 2024 21_43_38](https://github.com/user-attachments/assets/af60058f-babd-4a98-a2ff-4ac4c76c3c60)

2. old builds have high values by  Station modul count min/max range old was 63 now 6300. the  value by max range make no sense

![Starship EVO 30 10 2024 22_16_32](https://github.com/user-attachments/assets/6d0cb104-0e0b-4900-9099-46202bd7d473)

3. is in the video at the end i spawn a station modul ship, this biuld has works befor the update and now its crazy

[Video](https://youtu.be/BNVNUYBB7pk)

here a test to build a station
https://www.youtube.com/watch?v=lk1Tu3XCO2o

### Environment
- Starship EVO version: 24w44a
- Graphics Card:

**Comment by tsunamayo** [comment]
@Tackietacktack Thanks, I fixed the first mismatch issues.

**Comment by tsunamayo** [comment]
@Tackietacktack Issue fixed for 24w44b. Cheers
