### ISSUE TITLE
Multiplayer currently doesn't work

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#6085]
Hey Tsuna, just a gentle reminder that mp currently isn't functioning. I know peer to peer is often pretty flaky for some people, but back since #5935 I haven't heard of anyone successfully hosting/joining an mp game, they always crash.

I recently tried again to confirm and failed to host, just making sure you're aware of the situation!

**Comment by tsunamayo** [comment]
@ProPeach Thanks I will have a look at it

**Comment by tsunamayo** [comment]
@ProPeach Hi, issue is fixed for 24w46a. I am pushing the build now. Cheers

**Comment by ProPeach** [comment]
Fantastic, thanks!
