### ISSUE TITLE
station generation 

### ISSUE THREAD

**Issue by Tackietacktack** [tsunamayo/Starship-EVO#6089]
### Short Description of the issue:

no issue, its only information.

after 24w44a, i have had a not working station generation.
the issue was that the main ship connected to itself in loop.
before it was no problem because the ship has a spawnweight=0.

now, i dont use universal docking connector, main ship are male and all moduls are female and all works fine.

old Blueprint (all moduls) with loop
[Platin with loop.zip](https://github.com/user-attachments/files/17610141/Platin.with.loop.zip)

new Blueprint (all moduls) male and female:
[platin male.zip](https://github.com/user-attachments/files/17608060/platin.male.zip)

### Environment
- Starship EVO version: 24w44a
- Graphics Card:

**Comment by tsunamayo** [comment]
@Tackietacktack Hi, I made a change with the spawn weight, as I always forgot to put it at something other than 0, now 0 means 1. If you dont want to spawn that module, put it at -1 or something negative.

**Comment by Tackietacktack** [comment]
Ahh, thanks for the info, that helps.
