### ISSUE TITLE
watercloud has some targeting indicator

### ISSUE THREAD

**Issue by Tackietacktack** [tsunamayo/Starship-EVO#6097]
### Short Description of the issue:
https://github.com/user-attachments/assets/92788bb0-9a0d-4aed-b74d-647dc0fa0394

here is a scoop who expel water in intervalls.
with a ship, i get a many clouds indicator and heavy lags.

### Steps to reproduce the issue:

let a scoop gas expel in intervall
wait some time 
take a ship controll 
look at it

### Environment
- Starship EVO version: 24w44a
- Graphics Card: 

### Additional information:
[Player.log](https://github.com/user-attachments/files/17623655/Player.log)

**Comment by tsunamayo** [comment]
@Tackietacktack can you send me your character save? Thanks

**Comment by tsunamayo** [comment]
@Tackietacktack Okay I will try to see if I can reproduce, but last time this bug was reported I was not able. 
As you book a lot of bugs (thanks for that ! ;)), always  keep in mind that I cant reproduce things 100% of the time, so it is better to send blueprint / character save to help.
Cheers

**Comment by Tackietacktack** [comment]
[gascloud.zip](https://github.com/user-attachments/files/17635221/gascloud.zip)

hi,
i have make a new world with this bug.

you must activate the pump logic (its a bad logic build disable waite 4 sec and enable) and wait 1 minute in this time you could fly a round with the updated tradership. now, you get some target indicator. could be that you must leave the ship control and take it again.
i get indicator after 1-2 min.
cheers

**Comment by tsunamayo** [comment]
@Tackietacktack Thanks, I managed to reproduce! I keep you posted.

**Comment by tsunamayo** [comment]
@Tackietacktack Great, issue fixed for 24w44b. Cheers
