### ISSUE TITLE
question: is the ability to read control inputs planned?

### ISSUE THREAD

**Issue by najlitarvan** [tsunamayo/Starship-EVO#6101]
is the ability to read control inputs planned?
if yes, what are the reasons why it doesn't seem to be planned atm?
is it focus on survival? 
if it is hard to do in terms of code, what is the reason? the eventgates can already read hotbar 1-4 so , control inputs don't seem to be such a stretch to me.

**Comment by tsunamayo** [comment]
yeah of course the focus is survival. There are tons of equally valid nice stuff to add for creative, why this one in particular I might counter? Also it would not be a continuous input, but threshold, like the other stuff. Because of multiplayer.

**Comment by najlitarvan** [comment]
Why? 
Thrust vectoring
Visually responsive cockpit,  that would have controls moving a bit to make it sell as if the character was moving the controls, 
Not sure of the viability but potentially being able to on the fly disable and enable thruster groups based on inputs as a form of saving power

**Comment by tsunamayo** [comment]
@najlitarvan Yeah that is what I though, you seems to think that the current tech handle continuous signal, it is not the case, for now it is threshold based. Maybe one day, but continuous signal it is a big dev. Closing this as it was suggested many time already. Thanks
