### ISSUE TITLE
Hovercraft heigh and speed variation inside station that is built with different size blocks

### ISSUE THREAD

**Issue by Snakeyes81** [tsunamayo/Starship-EVO#6102]
### Short Description of the issue:

When using HV inside my own built station, it keeps going down to the ground even when its flat, and in some parts it even goes into reverse by itself.

### Steps to reproduce the issue:

Just drive inside the station over places with different block sizes

### Environment
- Starship EVO version: 24w44a
- Graphics Card: RTX 4070 ti

### Additional information:

The save file is in front of the area of my station that it's happening this, with the HV already spawned

[Snakeyes.zip](https://github.com/user-attachments/files/17688499/Snakeyes.zip)

**Comment by tsunamayo** [comment]
@Snakeyes81 Hi, interesting I can reproduce the issue indeed, I keep you posted. Cheers

**Comment by tsunamayo** [comment]
@Snakeyes81 Hi, issue is fixed for 24w46b. Cheers
