### ISSUE TITLE
[Bug]Docking module won't dock

### ISSUE THREAD

**Issue by Leidz** [tsunamayo/Starship-EVO#6116]
### Short Description of the issue:

I try to dock a crate to a ship wall. But no matter how many times a try, the crate do  some manoeuver then the docking module just stare at the other docking module and do nothing.

### Steps to reproduce the issue:

Docking a entity on a docking port on a wall. On a big ship with gravity on, set to 1 (default), none of the entity have a starter block.

The crate have nothing special in it. (only 2 docking module, 1 at each extremity.  Each one have a switch, in the video, only the one with yellow light have the switch on. No reactor, No thruster, no vehicle computer)

The docking port of the big ship dont have any switch linked to him.

- Starship EVO version: 24w46a
- Graphics Card: Nvidia RTX 3070

### Additional information:

https://github.com/user-attachments/assets/334b4dba-f442-4da1-b1c6-5ae62b79c399

Original world: 
[lEID2.zip](https://github.com/user-attachments/files/17804740/lEID2.zip)

Fresh test world: 
[test.zip](https://github.com/user-attachments/files/17804745/test.zip)

**Comment by Leidz** [comment]
> does it persist across save loads? does it happen with other entities?

Yeah, i tried to dock the crate to another entity in space and got the same result, i tried saving and reloading the game , and deleting then spawning the crate again, i got the same problem

**Comment by najlitarvan** [comment]
does it happen if you were to copy the stuff into another world, also please provide word savefile

**Comment by Leidz** [comment]
Yeah it happen, in the two worlds i tested, crates seem to struggle with gravity while docking.
(I uploaded the two world and edited my first post with download links)

**Comment by Reason147** [comment]
I noticed it myself; I had to reinstall the ports to get it working, hook up both ports to a switch and keep one on for it to work. The docking is more of a pain in the ass the using maglocks.

**Comment by tsunamayo** [comment]
@Leidz Hi, it should be better for 24w48a. Cheers
