### ISSUE TITLE
Questions about new Stations and NPCs.

### ISSUE THREAD

**Issue by Aranhanauta** [tsunamayo/Starship-EVO#6118]
### Short Description of the issue:

- What is the purpose of Chach Hub?

- Is it possible to establish contact with NPC ships?

- Are the salvage and repair stations just decorative or really functional?

- Are there missions to collect fuel for the fuel stations?

- Are police stations just decorative or do they have some functionality?

**Comment by tsunamayo** [comment]
@Aranhanauta Hi,

What is the purpose of Chach Hub? => what's that? Large hub maybe?

Is it possible to establish contact with NPC ships? => not yet

Are the salvage and repair stations just decorative or really functional? => decorative for now, although you can fix your ship at a repair kiosk.

Are there missions to collect fuel for the fuel stations? => a refuel mission is currently being added, for next update.

Are police stations just decorative or do they have some functionality? => decorative although the police ship will hunt you if you start shooting at the station.

**Comment by Aranhanauta** [comment]
Yes, there is a space station similar to the Fuel Hub, called the Cache Hub, which is practically a container orbiting a planet with station decorations, however, it is empty and as far as I saw there are no ways to interact with it.

**Comment by tsunamayo** [comment]
yes it is a cargo cache. It store cargo, it is used as a POI for NPCs to travel to. Soon they will also dock to it, and we will get missions based on them.
