### ISSUE TITLE
[Bug] 2 craftble backpack storage issues

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#6119]
### Short Description of the issue:

Two craftable storage backpack addons have minor issues to fix.

### Steps to reproduce the issue:

"Storage Backpack Addon II" is incorrectly labeled as "Storage Backpack Addon I". Additionally, it appears it cannot be crafted currently (as it requires 2x of a "null" item).

![image](https://github.com/user-attachments/assets/b43c77bc-441a-4485-83c7-995ea62cd628)

"Storage Backpack Addon III", when crafted, produces a helmet instead.

![image](https://github.com/user-attachments/assets/fc400f1d-3f9c-4d09-bc5c-ebe9ebe9f99f)

### Environment
- Starship EVO version: 24w46

**Comment by tsunamayo** [comment]
@asanagisae Hi, issue is fixed for 24w48a. Cheers
