### ISSUE TITLE
[Bug] Crafting backpack Addon 3 gives helmet instead

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#6120]
### Short Description of the issue:
Trying to craft a Backpack Addon III in an Assembler instead produces a Helmet, not the addon

### Steps to reproduce the issue:
- Craft a Backpack III in an Assembler

### Environment
- Starship EVO version: 
- Graphics Card: RX6700XT

**Comment by tsunamayo** [comment]
@ProPeach Hi, fixed for 24w48a. Cheers
