### ISSUE TITLE
[Suggestion] Hovering over items in any inventory shows a tooltip of their name

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#6121]
I have no way to tell what these items are :D 
![image](https://github.com/user-attachments/assets/617f5ab1-6899-42bd-be07-bbefa2812275)

A tooltip like this in the Schematics GUI of the Assembler would be great. This would show when you mouse over items in a cargo container, your backpack or your hotbars etc
![image](https://github.com/user-attachments/assets/366818d5-2beb-4030-910e-68f5e8769819)

**Comment by tsunamayo** [comment]
@ProPeach Hi, added for next update! Cheers
