### ISSUE TITLE
[Bug/Suggestion?] Can't put items into backpack if backpack is overloaded, dispite those items already being counted as mass in the backpack

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#6123]
I have a lot of stone on my hotbar, which has made me overencumbered
![image](https://github.com/user-attachments/assets/7729bb2e-2f8d-48be-ada7-a5e493f9afca)
I tried to place the stone from my hotbar into my backpack to get it out the way, but the operation fails. This feels weird to me, as the items on my hotbar are already counted as "in my backpack" because they are adding to the overencumbered effect as shown by the Volume 2022/1500L count.
I think I should be able to put them in my backpack or on my hotbar even if I'm overencumbered. I get "logically" that the backpack on my back has a set volume, but that logic doesn't really mesh nicely to the hotbar and the items on it. The backpack volume and the upgrade addons to it should more simply be seen as upgrades to the characters volume limit, not a distinctly different space than the hotbars.

**Comment by tsunamayo** [comment]
Yes it is just a bug, as I changed the logic to now allows being overencumbered, I must have forgot a check for the backpack slot.

**Comment by tsunamayo** [comment]
@ProPeach Hi, fixed for 24w48a. Cheers
