### ISSUE TITLE
[Bug] Can't put stone in the Crucible to smelt into Silicon

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#6124]
### Short Description of the issue:
Trying to add stone into the Crucible results in an error SFX and the operation failing. I might be going mad here, but this is how you're supposed to get Silicon right?

### Steps to reproduce the issue:
- Try to add stone into the Crucible

### Environment
- Starship EVO version: 24w46a
- Graphics Card: RX6700XT

### Additional information:
![image](https://github.com/user-attachments/assets/98725bd6-c269-4736-8cf4-a48926c32ca6)

**Comment by ProPeach** [comment]
So looks like you've got to use an Arc Furnace, then it works! That's fine in terms of progression, it would be nice to have a little guidance/explanation that you need an Arc Furnace if a player tries to do as I did

**Comment by tsunamayo** [comment]
I can add a help message in such a case indeed.

**Comment by tsunamayo** [comment]
@ProPeach Sorry actually I cant show up help messages while in a UI.
