### ISSUE TITLE
[Bug] Mech and Hovercraft distance achivements are not tracking

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#6126]
### Short Description of the issue:
Dispite travelling around multiple km in a hovercraft and mech, the Steam acheivements still show 0% progress
![image](https://github.com/user-attachments/assets/eb88fa3f-9cc6-48f4-b15a-62d30a37a757)
![image](https://github.com/user-attachments/assets/b90c71e3-128f-4e72-b7cc-56ee4555b96f)
The testing was done in Creative Mode, are these Survival only acheivements? I wanted to test that but haven't reached Hovercrafts yet as I got distracted by making all these posts lol. If so then I think clarifying in the Acheivement discription "Travel 500m in Survival Mode" etc would be useful, same goes for any other Acheivements that are Survival Only.

### Steps to reproduce the issue:
- Travel in a Mech/Hovercraft, check Achievement Progress

### Environment
- Starship EVO version: 24w46a
- Graphics Card: RX6700XT

**Comment by Crimson-Artist** [comment]
I believe all the achievements are survival only. I only started getting them when I played the second survival test. The only non survival achievement seems to be related to saving a blueprint or uploading a blueprint

**Comment by tsunamayo** [comment]
@ProPeach All achievements are survival only. I guess that should be pretty standard in all building game? I didnt want to put "in survival" in every achievement description.

**Comment by ProPeach** [comment]
Makes sense! Yes to be fair I think most games disable Acheivements when you enable "cheaty" features like a Creative mode or mods The one for saving a bp can be gotten in Creative mode so I supposed some others must be obtainable in Creative too, but I guess it's the odd one out.
