### ISSUE TITLE
[Bug] Storage Backpack Addon II has the wrong name, and incomplete Schematic information

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#6129]
### Short Description of the issue:
In the Schematics GUI, the Storage Backpack Addon II is actually named "Storage Backpack Addon **_I_**". It also does not show the full recipe, with the second item missing the name and just having the number of items " x 2".
![image](https://github.com/user-attachments/assets/4ba60236-b488-43ed-88b1-3ceac57ff2b8)

Also a side note, could the "Plate" be renamed "Iron Plate"? For consistencey and clarity

### Steps to reproduce the issue:
- Open the Schematics GUI and check the name/recipe

### Environment
- Starship EVO version: 24w46a
- Graphics Card: RX 6700XT

**Comment by tsunamayo** [comment]
@ProPeach Hi, fixed for 24w48a. Cheers
