### ISSUE TITLE
Changing Keybind for scrolling through Brick subtypes

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#6131]
Scrolling through brick subtypes is currently done with only the scroll wheel, which I have tried to get used to but still haven't managed to.
![image](https://github.com/user-attachments/assets/95ea71b8-7073-460f-b0f9-5aaeba7622a9)
My issue is that the scroll wheel is used for both scrolling along the hotbar sideways, _and_ scrolling through the brick subtypes. Hitting a subtype halfway through scrolling to another brick on the hotbar messes with my perception of where I am on the bar - I expect to scroll 3 times to move 3 across the hotbar, but actually I need to scroll 7 times because there was a subtype on the hotbar in between and it started scrolling through that.

I'd really appreciate if we could rebind the keys to scroll through the subtypes. I think I would really love the feature if I could scroll across the hotbar, then use ctrl + scroll for the subtypes for example.

Thanks for looking o/

**Comment by tsunamayo** [comment]
Yes true, this is why I started to use the numpad to jump between items, but I should improve that.

**Comment by ProPeach** [comment]
That'd be brilliant yeah, I also like to use the number keys if I need to jump across most of the hotbar, then just the scrollwheel for 1 or 2 jumps.

**Comment by tsunamayo** [comment]
@ProPeach Hi, done for 24w48a. Cheers

**Comment by ProPeach** [comment]
Fantastic, thank you!
