### ISSUE TITLE
[Bug] Rotor on Assembler is massively oversize

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#6132]
### Short Description of the issue:
When tasking an Assembler to craft a Rotor, the preview in the animation is full 1m scale, much larger than it should be

### Steps to reproduce the issue:
- Craft a Rotor in an Assembler

### Environment
- Starship EVO version: 24w46a
- Graphics Card: RX 6700XT

### Additional information:
![image](https://github.com/user-attachments/assets/eb0235f8-be1a-4609-81f8-4c1c7ae28ce2)

**Comment by tsunamayo** [comment]
@ProPeach Hi, issue fixed for 24w48a. Cheers
