### ISSUE TITLE
Frozen Planets

### ISSUE THREAD

**Issue by Aranhanauta** [tsunamayo/Starship-EVO#6138]
### Short Description of the issue:

Since the last update, I noticed that some, if not many planets and moons in different star systems have changed their texture, and now they resemble planets, or moons, covered in ice or with a completely white surface.

I would like to know if this change was intentional, or if it was a bug in the update, or maybe it was a bug in my save. 

If anyone else has seen the same thing as me, please let me know. Thank you in advance.

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

If you issue concerns a particular location please send your character save here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Characters\`

You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by ProPeach** [comment]
Can you take some pictures? 100% white sounds like a bug, do you see it in a new world too?

**Comment by Aranhanauta** [comment]
![711980_27](https://github.com/user-attachments/assets/ec3103d5-bbe1-47e6-8132-fe98ca9b56a7)
![711980_27](https://github.com/user-attachments/assets/ed0608b0-daf6-4f4f-9da7-4e2feeec3b91)

The photo in which the planet appears with its normal texture was taken nine months ago, the photo in which it is all white (yes, it is the same planet, in the same star system, in the same save), was taken today.

I haven't tested whether this could be a bug in my save yet, I'll check.

**Comment by Aranhanauta** [comment]
I just created a new save and traveled to the same system. 

The planet still has the same bug, that is, it is not a save problem.
