### ISSUE TITLE
camera view incorrect if you enter it from a chair

### ISSUE THREAD

**Issue by boxfoxscoot** [tsunamayo/Starship-EVO#6144]
[sniper chair.zip](https://github.com/user-attachments/files/18048296/sniper.chair.zip)
camera view incorrect if you enter it from a chair (camera is on a child entity and that my be part of the issue) 

https://github.com/user-attachments/assets/07147074-0b7f-4fcb-9e16-a62421ccc912

(also thank you for your tireless work creating this game and patching the various bugs it is truly awe inspiring how hard you work)

**Comment by tsunamayo** [comment]
@boxfoxscoot Hi, issue is fixed for 24w49a. Cheers
