### ISSUE TITLE
micro sturrets and lag spikes while moving large amount of CE's

### ISSUE THREAD

**Issue by king32109** [tsunamayo/Starship-EVO#6148]
### Short Description of the issue:
i am building a ship with alot of retractable turrets, but when deploying them i suspect he amount of ce's is causing it, a friend (naj77 on discord) helped me to test it and so did others and they all get the micro stutters when deploying and retracting the mechanisems.
the blue print is of the ship in question so you can test and see if  for your self. 
...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 24w46b
- Graphics Card: rtc 3060

### Additional information:
[dominion v5 red platform.zip](https://github.com/user-attachments/files/18052700/dominion.v5.red.platform.zip)

**Comment by najlitarvan** [comment]
do not know if it something that could cause it, but the circuits in the turrets are abba circuits driven by eventgates rather then timers, we tried offsetting the amount of moving CE by staggering the deployment, the microstutters still persist

**Comment by tsunamayo** [comment]
@king32109 Hi, how many CE do you have? How many turrets? Thanks

**Comment by tsunamayo** [comment]
@king32109 Hi, I don't have an issue when entering command, what I am supposed to do to reproduce the issue? Thanks

**Comment by king32109** [comment]
The problem is when deploying the turrets and your moving around you get micro stuters until its fully deployed

**Comment by tsunamayo** [comment]
@king32109 What do you mean deploying the turrets? How do I do that?

**Comment by king32109** [comment]
In the blueprint their should be a platfrom on the back end of the ship with a button on it to deploy them

**Comment by tsunamayo** [comment]
@king32109 Look I cant find this button, can help me with a screenshot? I am not familiar with this build as you are... thx

**Comment by najlitarvan** [comment]
@tsunamayo there is a red platform on the back of the build and on that platform is a black button

**Comment by king32109** [comment]
![image](https://github.com/user-attachments/assets/47df3eed-6adb-4db5-8cae-ef79073f6040)
this is  the location

**Comment by najlitarvan** [comment]
i tend to run with solid 60 but the microstutters make it go to around 30 or even 20 fps for a moment

**Comment by tsunamayo** [comment]
@king32109 Hi, issue will be fixed for 24w40a. It was like to life support system being updated when the CE started moving. Cheers
