### ISSUE TITLE
Hover Craft Green Arrow

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#6149]
Hi there,

I was testing some of the patch notes when I noticed that the hover craft spawns a green arrow pointing towards the ground. 
The arrow always stays level to the ground and only appears when entering a hover craft.
I tested multiple differents hover vehicles too. It happend to everyone of them.

This would be a really cool feature tho, when it's not a green arrow somehwere on the vehicle but an indicator line in the hud. 
Most useful position would be right underneath the mouse cursor. 
Or maybe a symbol next to the survival hud in the bottom left corner.

https://github.com/user-attachments/assets/3ad12115-a71b-4ac9-99a2-af83c73a41b2

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, this will be fixed for 24w49b. Cheers

**Comment by tsunamayo** [comment]
and yes that could make for a nice HUD element, not sure how to integrate it neatly though.
