### ISSUE TITLE
Item count visually blocked 

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#6150]
Hi there,

when holding an item while in the inventory hud, you're unable to see the amount of items you're currently holding because the amount is visually blocked by the items description itself.

https://github.com/user-attachments/assets/9774ee33-43bd-417f-90f9-cf5921ba221c

**Comment by Tackietacktack** [comment]
another variant

https://github.com/user-attachments/assets/3d7ee5f8-7340-4abc-a39f-84ac27c86b8c

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, indeed, this is fixed for 24w39b. Cheers
