### ISSUE TITLE
[Bug] Shields entity-centric [18w11a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#620]
Shields currently create a bubble that only surrounds the entity they are placed on, rather than protecting the entire ship that they're meant to protect. This is particularly problematic for craft that have a narrow body but wide wings.

![20180323203528_1](https://user-images.githubusercontent.com/33041786/37858932-47390546-2eda-11e8-825e-62caa4ba9fb6.jpg)

**Comment by tsunamayo** [comment]
Shields adapth to the body shape, I think issue comes from the fact that you might have used children entity, if you can confirm that. Could you send me your blueprint? Cheers

**Comment by Dwarf-LordPangolin** [comment]
This does indeed use child entities. That's the bug I was referring to; the shield is only adapting to the body of the parent entity, rather than the body of the entire ship, making any bits that stick out vulnerable (for example, if a player made an X-Wing, the wings would stick out through the shields). The only way to shield the wings is to mount separate generators on them, which looks really bad.

![20180323204744_1](https://user-images.githubusercontent.com/33041786/37860985-851acc90-2efe-11e8-8b92-7e84193ab4e0.jpg)

Here is the blueprint.

[AAM Hammerhead.zip](https://github.com/tsunamayo/Skywanderers/files/1844089/AAM.Hammerhead.zip)

**Comment by tsunamayo** [comment]
I think this should still be an issue...

**Comment by tsunamayo** [comment]
Feature finally added for 20w24d, yay! Cheers
