### ISSUE TITLE
SUGGESTION - Weapon convergence.

### ISSUE THREAD

**Issue by BrickMacklin** [tsunamayo/Starship-EVO#657]
Specifically for blasters. Many players will make crafts with wing-mounted weaponry. Unfortunately the area of attack becomes too large with the guns firing straight. A small craft with wing weapons could be useless for hitting anything. Converging weapon projectiles at a distance would make a range of builds far more useful.

**Comment by tsunamayo** [comment]
Yes I will most likely add a built-it auto gimbal to make shooting easier, but I want to make progress on combat to see how it goes first. Thanks

**Comment by tsunamayo** [comment]
We now have gimbal. Thanks
