### ISSUE TITLE
[Suggestion] Meme Block

### ISSUE THREAD

**Issue by Varraka** [tsunamayo/Starship-EVO#666]
Any way we can get a block that displays a gif in holographic format on our ships? :D Might be a little risky with url`s from the interwebs but maby a collection directly on game severs, green lighted by admins would work. This could add some seriously wierd flair when making 5th element worlds, or advertizing co-related things/factions/build brousing in game. . . Or maby that crosses to many dimensions of reality. lol. Thought the tag issue # needed something fitting. >XD

**Comment by Napther** [comment]
![image](https://user-images.githubusercontent.com/33023316/38057964-10b0a1b6-32d9-11e8-9dfd-2ee1c80c93a0.png)

**Comment by schlid** [comment]
A less far fetched suggestion might be to allow custom stickers with Vector uploads. The quality wouldn't degrade at a huge size and the file size is relatively small.

**Comment by Varraka** [comment]
:D Custom art stickers! Yes!

**Comment by tsunamayo** [comment]
I see lol, I had some similar idea in mind, but its kinda low priority for now! Cheers

**Comment by Varraka** [comment]
Nice, definately low priority, late dev would be great finishing touch. :)
Was thinking you`ve got most of the work already done for it, if u use the
line link system to draw with on the mini-board block base for vectors to
compression sticker state. Question left would be, to identity block custom
decals or not.. Guess save decal 1-6 like custom colors would be even
cooler! Raise the flag mayetey! Avast! Weve won the day!
