### ISSUE TITLE
[Suggestion] [Multi-tool] Phase function

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Starship-EVO#696]
It might sound weird, especially since we don't have the multi-tool yet - but basically, it would work similar to destroying a block and repairing it.

For example, in a role-play situation, you need to access a doors logic circuits, instead of actually breaking the panel covering it, or perhaps needing to create some logic circuit to make it retract - the phase function would temporarily 'destroy' a block/brick and allow you to access what is behind it ('send it out of phase'). To bring it back, perhaps right clicking with the phase function of the multitool causes it to rematerialise, and 'come back into phase'.

Just a simple way of making sure you don't properly destroy the way something is built, without the need to currently shoot a wall to get behind it. :P 
Hope you like the idea :) - if indeed this is something that fits with the theme of the multi-tool being developed.

**Comment by tsunamayo** [comment]
Ha, I like this idea, not sure if I will have the time to work on this though ;-)
