### ISSUE TITLE
[EXPERIMENTAL] Unable to leave pilot seat/ship controls if Activate-able block is directly ahead of viewpoint

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Starship-EVO#699]
![image](https://user-images.githubusercontent.com/33023316/38447582-19fc152e-39f6-11e8-8d37-2e29b1017b30.png)

>>>I think its rather... specific to say the least. Was unable to exit by pressing my binding (r), I was able >>>to middle-mouse and look towards the holomap in order to disable it, and then I was free to exit >>>with R.

>>>This is in a Hyperspace/cruise.

EDIT: Wow it was... a lot simpler than I thought. Its just any block that can be toggled with the keybind when sat down piloting a ship will cause you to be unable to leave the controls, as activating takes priority,
It didnt click at first as the Holomap was directly on me and hiding a tooltip.

https://puu.sh/A1cw2/acb9e6cf34.mp4

**Comment by JRL101** [comment]
Have you re-tried this in version **18w15**? 
Im assuming Tsuna was able to recreate it in the current version if he marked it as bug. 
Confirm?

**Comment by Napther** [comment]
Updated the occurrence case to reflect more accurately on situation/bug

**Comment by tsunamayo** [comment]
This is still not fixed in 20w12a. Thanks

**Comment by tsunamayo** [comment]
Finally fixed for 22w05a...
