### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Sloooth** [tsunamayo/Starship-EVO#735]
[error.log](https://github.com/tsunamayo/Skywanderers/files/1909428/error.log)

Wasn't doing anything except watching a stream and had the game in the background

**Comment by tsunamayo** [comment]
Hi, could you please send also the file output_log.txt ? Thanks!

**Comment by Sloooth** [comment]
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1910306/output_log.txt)

**Comment by tsunamayo** [comment]
Sorry I slept on this one, but the output_log dont seems to match the crash. Is it something you reproduced? Thanks
