### ISSUE TITLE
[Suggestion] allow data input into the white nodes on both constants and mix gates.

### ISSUE THREAD

**Issue by schlid** [tsunamayo/Starship-EVO#746]
![image](https://user-images.githubusercontent.com/31857052/38842962-d0bb52de-41e4-11e8-8fe7-cbc3c04a3c03.png)
If we were able to send a signal into the white node on a constant or mix, we'd be able to update the values stored in them, and therefore have a way of retrieving this value later on by sending a signal through the constant or mix normally. 

This would allow for more simplicity in logic circuit design, and also due to the fact it would allow a constant gate to act as a full range memory cell it reduces the needs for complex and large footprint memory cell circuit designs.

Since we can already connect logic into the white node, but it does nothing, we're already on our way to this being a reality, but having this logic feature sooner rather than later would help a lot of builders out.

**Comment by talrey** [comment]
This would be really helpful, I support this. It would be useful for saving the state of switches and slider controls, for simple ships as well as more advanced projects. I've built memory cells before, but they're at least 10 studs (vs a Constant gate's mere 2) and they get reset whenever the blueprint is reloaded.

It's not a necessity, by any stretch, but it would be a lovely quality-of-life improvement for logic :)

**Comment by JRL101** [comment]
I think you can link logic into the white nodes to change their values. (havent tried to in a while.)

**Comment by talrey** [comment]
Please don't comment on things like this with speculation. I just tested it in Experimental and it is not working, so if it is already implemented then this is a bug rather than a suggestion.

**Comment by JRL101** [comment]
This is a bug fixing forum. I wasnt speculating i was making a suggestion to try different logic. BUT i dont know _what_ you've tried. So instead of assuming its been tried, i suggest linking logic to it.
Currently Tsuna is reworking how logic and blocks are interacted with. 
Previously it was possible to link **some logic** to the values on certain bits of logic. 
It is unknown to me when it was taken out, or if it was taken out on purpose. 


It would be an awesome feature for logic.

**Comment by schlid** [comment]
![image](https://user-images.githubusercontent.com/31857052/39097031-90e6483a-464e-11e8-9c30-1accd2f51aa7.png)
If you had thoroughly read the original post before commenting that, your speculative/unconfirmed post wouldn't have been necessary at all.


After linking something into the white node, it has **never updated the value within the mix or constant gates**, similar to how linking an output to an output will do nothing. It didn't update the value in each logic block in the 100 man tester phase, and it has never worked throughout the duration kickstarter backers have had access either.

Please don't leave none-verified, speculative posts like the one below in the future. It just adds unnecessary clutter to the **github**. Bug reports and suggestions here should be concise to aid Tsuna, and also to prevent others from accidentally double posting.
![image](https://user-images.githubusercontent.com/31857052/39097133-2cc3ab3e-4650-11e8-8b1f-a59a3bfa7f0b.png)

(As a final note, please don't claim to have knowledge about topics you either haven't researched or are not in a place to know about, for example;
The portions of the game tsuna is currently developing
Features you *think* were in the game previously that in fact were not.) - as shown below.

![image](https://user-images.githubusercontent.com/31857052/39097289-42d31d86-4652-11e8-888e-56b20a9414e8.png)


Back on topic though, I agree. It would be an awesome feature for logic

**Comment by tsunamayo** [comment]
Yes, I agree I think it was already suggested at one point. I will add it, thanks!

**Comment by CyaNox** [comment]
This has indeed been mentioned in #335 and #493.
