### ISSUE TITLE
[Suggestion] Experimental Text Overlay Changes

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Starship-EVO#769]
### Environment
- Skywanderers version: Experimental
- Graphics Card: Nvidia GTX 980Ti

### Expected behavior:

The white text that appears when looking at something that can be interacted with, should be toggle-able. In the options menu, making it so the white text that appears can be turned off for those who don't wish to see it. See below for image example.

Alternatively, have the text that appears not show the button required to interact with it, but rather show the label assigned to it. For example, if I name a button 'Fire Missile' then the white text that appears over it should be 'Fire Missile'. Otherwise having it tell the player what button to use to interact with it seems a bit unnecessary.

### Actual behavior:

White text appears over interactable objects and takes up an annoying portion of screen.

### Additional information:
![711980_20180430085931_1](https://user-images.githubusercontent.com/33239800/39411926-ac0c81f2-4c56-11e8-92ca-5fcf0f60244b.png)

**Comment by tsunamayo** [comment]
Yes I agree they are a bit too much, I dont want to get rid of them though, at first I will have them fade in after a bit of time, I think that will help a lot. The text generation will be improved for sure, there is actually quite a lot of cases to deal with ^^. Thanks
