### ISSUE TITLE
[Experimental 18w18a] [Visual Glitch] Hyperspeed (jump) and hyperspace (warp) visual glitch

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#789]
### Short Description of the issue:
While in hyperspeed and space, it appears the animation has been rotated. The light "streaks" while in jump are moving to the left. In warp, the ship is also rotated to the left. These are two different ships with normal, front facing cores in the gif to show it isn't just one ship with some mistake.

### Steps to reproduce the issue:
Go to warp (duh)
Go to jump (duh)

### Environment
- Skywanderers version: [EXPERIMENTAL 18w18a]
- Graphics Card: Intel(R) HD Graphics 5500
(Integrated)

### Additional information:
https://gfycat.com/InfamousRightArabianhorse - Jump
https://gfycat.com/EasygoingReliableImperialeagle - Warp

**Comment by tsunamayo** [comment]
Issue was fixed some time ago.
