### ISSUE TITLE
[Experimental] [Bug] Model dissapear, multitool frozen, block UI dissapear, crash

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#794]
### Short Description of the issue:
As said, my playermodel turned invisible where only the arms and legs were visible, the multi tool was frozen in place away from the player, the block US dissipated where you couldn't turn a block (only place it on the right angle,) and finally when I closed the game a crash message came up. 
...

### Steps to reproduce the issue:
I have no clue, just the crashlog
...

### Environment
- Skywanderers version: 18w19a
- Graphics Card: Intel(R) HD Graphics 5500

### Additional information:

[error.log](https://github.com/tsunamayo/Skywanderers/files/1994617/error.log)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
I guess you no longer have issue of that sort ;)
