### ISSUE TITLE
[BUG] Unable to exit ship core

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#800]
About 25% of the time, holding F to exit a ship core though either a joystick or direct activation will fail, with the progress wheel paused at 100% as shown:
<a href="https://imgur.com/6kNE6dp"><img src="https://i.imgur.com/6kNE6dp.png" title="source: imgur.com" /></a>

Steps to reproduce the issue:
Unfortuantely, I have not been able to determine an exact cause, it seems like a random chance with any ship core on any ship. If anyone else has had any luck finding a cause, let me know!

Enviroment:
Singleplayer and multiplayer

- Skywanderers version: 18w19a
- Graphics Card: Nvidia 1050M

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2002270/output_log.txt)

**Comment by tsunamayo** [comment]
Hi @ProPeach, I am going back through my (very) old cases, as I know you are still active I dont know if this is something you saw again or not. Thanks ;)
