### ISSUE TITLE
[Bug] [Experimental] Unable to place blocks/spawn entities/Controls reset

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#807]
Shortly after being in a MP session I exited to main menu and clicked on my SP world which gave infinite loading screen. After force closing and restarting the game I jumped right into my SP world which reset all controls to default and I was unable to place blocks and spawn entities/ships.

Not sure if repeatable.

- Skywanderers version: 18w20a
- Graphics Card: Nvidia GTX 970

![20180521194247_1](https://user-images.githubusercontent.com/32974671/40336643-6db4f052-5d30-11e8-8f3a-11fd16451874.jpg)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2024516/output_log.txt)

EDIT: After restarting my game again it turns out it was just a complete reset of controls. I can indeed play the game as normal.

**Comment by tsunamayo** [comment]
Thanks, it seems that there is indeed some weird glitch and reset happening with the settings, this might help me to reproduce. I keep you posted.
