### ISSUE TITLE
[Bug] Turret Camera config can lock up build mode

### ISSUE THREAD

**Issue by DirectorBright** [tsunamayo/Starship-EVO#812]
### Short Description of the issue: Attempting to bind a turret's camera to a camera that is already bound to a screen breaks the ability to place and remove blocks.

...

### Steps to reproduce the issue:
Place a camera and a screen
Link the camera to the screen
Construct a turret
Attempt to link the turret control's Camera feature to the Camera linked to the screen

...

### Environment
- Skywanderers version: 18w18a
- Graphics Card: NVIDIA GeForce GTX 1070

I would upload my output log but it's 50 MB, and there is a limit of 10 MB.

**Comment by tsunamayo** [comment]
No longer an issue in recent versions. Thanks
