### ISSUE TITLE
[Suggestion] Ability to quickly clear a hotbar

### ISSUE THREAD

**Issue by cmcarey** [tsunamayo/Starship-EVO#814]
Clearing a hotbar is a slightly tedious process as you have to click each item and then click somewhere outside the inventory GUI.

It would be convenient if there was a way to quickly remove items from the hotbar - perhaps shift+click should remove an item?

Thanks!

**Comment by tsunamayo** [comment]
Good suggestion. Also I dont like many think about the codex, I will move to a hold brick and replace the target system for example.

**Comment by tsunamayo** [comment]
Okay I will try to get back to that valid request. Thanks

**Comment by tsunamayo** [comment]
We have a clear a full row button since a while now.
