### ISSUE TITLE
Crash error

### ISSUE THREAD

**Issue by tobyhawkinz** [tsunamayo/Starship-EVO#816]
I bought the game and downloaded it, when creating a character the game crashes and stops working it does this nearly every time 

...

### Steps to reproduce the issue:

...

### Environment
- Skywanderers version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by ProPeach** [comment]
Can you fill in the rest of your bug report? Like your graphics card details, version and your Output.log file. This will help a lot to fix your bug

**Comment by tobyhawkinz** [comment]
Graphics card details are in the attached image file.
The version is  pre-alpha 18w18a
The output log is attached to this email.

**Comment by tsunamayo** [comment]
Hi, it seems that there is no image nor log, I think you might have to go on the github page to drag and drop them, I guess it wont work via mail. Thanks

**Comment by tobyhawkinz** [comment]
![capture](https://user-images.githubusercontent.com/39648649/40584045-36d46fb6-6192-11e8-8895-07b9d72528a5.JPG)
[error.log](https://github.com/tsunamayo/Skywanderers/files/2042378/error.log)

**Comment by tobyhawkinz** [comment]
Hi, the output log is attached, I do confirm that I get this issue 100% of the time. My windows and GFX drivers are up to date, I have just checked them 

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2077380/output_log.txt)
