### ISSUE TITLE
[Bug] Server continues to send UDP packets to client even after client exits game

### ISSUE THREAD

**Issue by cmcarey** [tsunamayo/Starship-EVO#826]
### Short Description of the issue:
Noticed that the server was still sending UDP packets to me even after I had closed the client.  Screenshot below.

### Steps to reproduce the issue:
0. Join a server
0. Leave before fully joined
0. Observe server continuing to spam client with UDP packets

### Environment
- Skywanderers version: 18w18a

### Additional information:
![image](https://user-images.githubusercontent.com/32423458/40587872-f37661da-61cc-11e8-8725-31425186cfb8.png)

**Comment by tsunamayo** [comment]
Thanks for this technical report it is very precious (and rare).
Hi, was it happening for a long time? There is a timout, so in the worst case it should stop after a bit.
Also when you say leave before fully joined: how did you exit the game (alt-F4 ?)

**Comment by cmcarey** [comment]
Hi @tsunamayo, seems that it stopped after a while, and yes I had exited using Alt + F4.

Also, semi-related, would you have any plans to allow external third party servers?  I was looking at the protocol with plans to reverse engineer it and implement a dedicated server, though will avoid that if that type of thing doesn't have your blessing.

Cheers!
