### ISSUE TITLE
[BUG] Engine sound continues to play after engine has stopped

### ISSUE THREAD

**Issue by SsynoO** [tsunamayo/Starship-EVO#830]
### Short Description of the issue:

When the ship is at 0 M/S and I have exited it the humming of the engines can still be heard.
Looking in certain direction, typically left relative to sitting in seat facing forward, stops the noise.

### Steps to reproduce the issue:

Enter game

### Environment
- Skywanderers version: Newest at time of posting (not experimental)
- Graphics Card: GTX 970

[output_log - Copy.txt](https://github.com/tsunamayo/Skywanderers/files/2050886/output_log.-.Copy.txt)

**Comment by tsunamayo** [comment]
Okay I cant reproduce this one, could you give me more info?
What ship did you used?
What version was it (I guess 18a)?
Do you reproduce that all the time?
