### ISSUE TITLE
Crash to desktop

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#831]
### Short Description of the issue:
game crashes after a short time working on ship (crashes to desktop)
...

### Steps to reproduce the issue:
hang around the ship for 10-15 minutes
...

### Environment
- Skywanderers version: 18w20a (current experimental)
- Graphics Card: Vega 64

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2051229/output_log.txt)
would include BP but cant seem to add it

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Hi, as said on the discord could you please send the output_log.txt just after your crash, this one was taken after you relaunch the game hence it was erased. Is it something you reproduce consistently?
Thanks!
