### ISSUE TITLE
[Suggestion] Another form of the logic slider

### ISSUE THREAD

**Issue by SsynoO** [tsunamayo/Starship-EVO#834]
I think it would be cool to add a mechanism similar to the piston in scrap mechanic. When not extended the block or brick would be 1 block or 1 brick in length and width and then can extend to whatever size the user desires (within reasonable parameters of course). This would work in place of having to stack multiple sliders on top of each other (which makes the contraption look very ugly). The block could look like the gun brick but with the ability to extend. The bricks extension could be altered through mix gates and constant gates. It would look very good as the object that lowers down ramps to enter a ship. Maybe it could also be used with hinges to control how far the hinge can go.

**Comment by tsunamayo** [comment]
Yes this is definitely something I will want to add at one point, for landing gear especially it is gonna be useful. Thanks

**Comment by tsunamayo** [comment]
Hi, we have piston since a while now!
