### ISSUE TITLE
[SUGGESTION] Hardpoint System

### ISSUE THREAD

**Issue by Senakysam** [tsunamayo/Starship-EVO#838]
I suggest making a hardpoint system. With this system, there would be a male connector, and a female connector. The female connector would be on the parent entity, and control the orientation of the equipment being mounted.
 The way this would work is that on the parent entity, a joystick would be linked to the female connector, and on the child entity the male connector would be linked to a turret core, as shown: 
![711980_20180530125746_1_li](https://user-images.githubusercontent.com/26584892/40749680-6de266c6-642a-11e8-9b49-ae06a9968ae8.jpg)
With this, the hardpoint is acting as a bridge between the joystick on the parent entity, and the turret on the child entity. 

The purpose of this would be to make it easier to equip and upgrade turrets on a ship, especially for people that don't want to build. This would also help for people that want a standardized turret design on their fleet's/faction's ships.
A way this could work is that in order to equip a hardpoint, the player needs to dock at a shipyard where the turret will be built onto the ship after paying.

**Comment by MrBester** [comment]
This or some way to save a prefab blueprint of a turret we have built so we can paste them on our ships multiple times, without having to use identity block hacks.

**Comment by tsunamayo** [comment]
Yes I agree this is something I will address at some point. Not sure yet on how it would look, I could do add feature to a docking block, to rotor slider, or a new thing entirely. I need to think more about that - I will keep you posted. In the meantime you can come up with use cases, like I guess it could be used for other thing than turret.

**Comment by Tomatart** [comment]
This would work for things like elevators, that could be built then saved as their own thing that could then be put on other ships or even downloaded by other players as if it were a blueprint, then be able to add it to their ships.

Other things that could work with this that come to mind are cranes, airlocks (possibly could be used for doors in the future?) basically anything that you could consider a "modular" part of a ship.

**Comment by Raiben-EFSF** [comment]
I'd like to see mini versions as well (brick versions) for smaller pieces, but something like this would work pretty well IMHO.

**Comment by Senakysam** [comment]
Another way it could be used is for ship designs that are modular. For example, a freighter could have normal cargo containers on hardpoints, and then be able to swap them out for fuel tanks at a shipyard. Stuff like that.

**Comment by tsunamayo** [comment]
Still something I want to address as of today.

**Comment by tsunamayo** [comment]
Well we have prefab now, but
