### ISSUE TITLE
Custom Paint Bug, Suggestion

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#842]
This is a two-parter around paint: a bug report and a suggestion/update

______________________________________________________________________________________________________

Bug Report:
The custom colors seem to be player specific. For example, if I make my Custom 1 red, any blocks I paint will be the red which was selected. For any other player, they will see what their Custom 1 color choice. If another player has their Custom 1 pink, they will see anything I paint with Custom 1 as pink even though the intention was to be red.

______________________________________________________________________________________________________

Suggestion:
Instead of an entire codex menu full of singular colors and only eight custom paints, I’d suggest just having one paint item. Now this would originally be the default gray or just a brush logo (like the repair tool is the wrench logo or the logic tool is… something else.) Once you have it, you can use some key to bring up a menu like the one we have now. Except instead of just the color picker, you will have something like this.

[img]https://i.imgur.com/yqfj8a7.png[/img]
 
This example is the menu from MS Paint. A similar system would work very well here. There are the basic colors and another bar for custom colors. Instead of having just the eight custom colors that you configure, you use and save (if you so choose) them here for future use. They become just another color eliminating that glitch, condensing the menu and the codex, and add a whole other area of creativity. With this, the entire paint menu could be removed just add the one paint tool. Or the paint menu can stay while removing the custom colors. Regardless, it will fit nicely into what exists now especially with the addition of the paint menu. Plus the simplification could mean the return of the much desired default paint. With the custom color, people can now choose their own colors and start personalizing their ships much more without the annoyance of the glitch or the restrictions of limited choices. Finally it condenses the current menu and would be better once survival comes around. Perhaps the tool would be a paint brush that changes color based on the one that is picked.

I have discussed how it may change the file sizes and if it would be too taxing, though that is more up to Tsuna to decide. If anything, the current system can stay, fix the glitch, and do the one item with the menu. This will be a fitting implementation for the inevitable addition of survival rather compared an entire paint menu. I know Avorion uses something like that and I believe FTD has some RGB custom colors so it really depends.

______________________________________________________________________________________________________

Default Paint:
Now I am going to make one last argument for default paint as it applies here and chances are this will be one of the last places I can argue for it in the base game (rather than wait for the modders to inevitably re-add it.) 

Default paint was one of the most convenient parts of the whole painting system. Especially with large ships, being able to add a base layer of paint was extremely wonderful to have. Now without, we practically have to build the ship twice. Place then paint, place then paint. With that comes the likely chance that block will be missed leaving some blocks awfully uncolored. Many ships also use multiple layers of blocks. Some for design sake, some for multiple layers of “armor,” and for many other reasons. Go down to the brick level and this becomes even more prevalent. Most people place multiple layers of bricks especially at the smaller ship/fighter level. So now if you want everything painted the color you want, you can’t just place everything at once. You have to place a layer then paint it. Place a layer the paint it. This is a massive time waste that does nothing to improve the building experience and few players will ever bother with it resulting in a center of default gray and an exterior of the desired color. Once blocks get destroyed or broken, that middle uncolored layer is revealed and quite out of place. The worst consequence of this removal is the engine and shield color. Before with default, you would know that all the engines you place are the same color and will always make the same color trail. Same with the shield bubble color. Now unless you want to do the same thing of layer and paint, layer and paint, you can only paint the ends of the engines or some of the shield blocks. Smaller ships don’t have this problem, but for larger ships with hundreds, if not thousands of engines this is a real problem. It will look fine when you first fly your ship and the engines trail/bubble appears the desired color. The problem comes when you (re)spawn in the same ship or reset your game. Suddenly the engine trail or the shield bubble becomes the base color again, blue-grey. The game detects the (untested if all or majority) of the color if the engines or shields or bubble. You have to color the last engine/shield each and every time to get the color you want again just for it to return to its base state.

I don’t know who said this, but the reason it was removed was for “realism.” I would like to direct back to the word “convenience.” Making the game inconvenient to add to realism is necessary and in many cases a good addition (or retraction.) Adding food and drink levels in a survival game is inconvenient, but it is realistic and adds to the gameplay. This however may be more realistic, but it does not add to gameplay and is extremely inconvenient beyond the non-benefit of realism. It does not add to the building or the creative process. If it is brought back, I doubt anyone would hear “it is so unrealistic that it is breaking my immersion.” All removing default paint does it make the building process harder without adding to gameplay and remove the creative potential it once had.

______________________________________________________________________________________________________

Conclusion:
Now that the custom paint glitch is known, consider changing the system to something like I suggested. When survival comes around, perhaps the paint tool can be given automatically from the beginning or one simple crafting recipe/first multitool. That way players can start building and customizing their ship early on rather than be forced to gather 20 blueberries for just the blue color. I know of quite a few survival-esque that this can become a real pisser when all a player wants to do is individualize their build. Letting players start with painting their ships how they want will help drag players into the creative potential early on without needing to grind just for some customization and personalization. And only blue-gray ships look ugly. Finally, I hope it is understood of the consequences that came with removing the default paint tool and how simple it would be to bring it back. It is not worth the inconvenience for the added realism (while magically placing blocks from a multitool :D ) Ask any large ship builder and they will agree that it should be readded for the reasons above plus others. It is best for everyone and it is better in the base game then have some modder add it.

Thanks

**Comment by tsunamayo** [comment]
Hi, sorry I had a hard time understanding it all, if you could make it shorter and more structured that could help to get your message through.
Some comments:

- If there are bugs, I will fix them (engine, trail issue, or the sync in multi issues)
- Custom color is per ship, not per player
- Yes I will get rid of the dedicated codex tab for paint, you will just pick the tool and use the color wheel
- There are some limit on the data model, and they will likely tighten up (I might have to switch to 32 colors)
- Yeah I want to add reusable preset at one point, for faction that will be useful
- For the default paint it is not really about realism, more about the new art and new system. With the texture/codex refactor there will be no universal base color like the blueish gray, each hull will have its own base color.
- Honestly I dont think that add that much time, only if you are spamming huge hull with no details and no interior - but the engine is not made for gigantism (yet ?) so I am fine with that. I dont get why you guys are ready to put 100's of children entities in a circle (which seems super painful to me) but cant take a painting session haha ;-)

**Comment by ZachZent** [comment]
"Honestly I dont think that add that much time, only if you are spamming huge hull with no details and no interior - but the engine is not made for gigantism (yet ?) so I am fine with that. I dont get why you guys are ready to put 100's of children entities in a circle (which seems super painful to me) but cant take a painting session haha ;-)"

It really does. I'd suggest you ask Vic or Oojmaflip, or Sullos, or any ship builder that makes massive ships if it is as much of a burden. Even now as I am making a 120m ship, the lack of default is forcing me to go back to fill in everything and make sure blocks multiple layers thick and all painted rather then the exteriors only leaving an unpainted interior. [Yellow block, grey block, yellow block]

What it is is busy work and nothing else. We don't mind using 100's (though that is usually an overestimate) of child entities to make a circle because it is creative. We are using your blocks to create something amazing where (base layer) painting is far from creative. If we don't want to the base color to be standard blue-grey, then that means we have to go over every block again. This is hardly rewarding when a tool to make this process easier was available not long ago. Building is fun, detailing with paint is fun, a base layer is not fun. With your old Corellian Shuttle, painting was easy. 20m ship painting is hardly a chore and can be done in a few minutes. Anything more and it becomes lost time reducing fun and just adding busy work.

**Comment by Sullos** [comment]
I heard my name mentioned, and thought I had better respond.
I have to agree, at least in terms of creative mode, I sorely miss setting a default paint colour. 
Building a small shuttle out of blocks is no problem. Building a fighter with bricks is now a much slower process as bricks need to be layered and each layer painted before moving onto the next.
And as Zach put it, I couldn’t agree more about building circles as fun and creative work, where as painting things after we have already placed it separate to detailing is just busy work. 
It simply adds a lot of time.
I think that at least for creative mode, there should be a default colour option. Perhaps by opening the paint menu, and pressing ctrl, shift click on the desired colour will set it as the default placing colour. It doesn’t necessarily need to change the colour of all blocks on the hot bar, perhaps just changing a little light on the side of the multi tool to be the set colour.
Survival mode makes some sense to have blocks placed in a default colour, but for creative mode, where building should be simple, a default colour option is most desirable.
Just my opinion on the matter :)

**Comment by Vicomt** [comment]
Yes, this should definitely have different functionality in creative/survival. we don't do survival, we build, and we like big. we joined sky1 because it looked like (and is) a bloody good construction engine, but the creative / construction aspects seems to be going backward at the moment, and things just keep getting slower and slower to build. and if you want time consuming stuff that can be fixed by default paint, look no further than big thruster stacks - some of ours are 50 blocks deep with a cross-sectional area of 10x10, and OH YES I'D LOVE TO PAINT EVERY SINGLE ONE OF THEM, in between adding new stats, because we can't paint behind things.

**Comment by Creepthefrenchpastery** [comment]
In creative mode i believe blocks should be able to be placed already colored
