### ISSUE TITLE
Recommendation - switch / button titles 

### ISSUE THREAD

**Issue by SeaTreader** [tsunamayo/Starship-EVO#867]
### Short Description of the issue:
Very sorry if my formatting is off - I just noticed in the most recent version of skyrim, you can't see or make titles on switches and buttons and think we should bring that back - it really helps keep code and even doors organized! 
...

### Steps to reproduce the issue:

...

### Environment
- Skywanderers version: experimental
- Graphics Card: Radeon HD 1.09GHz

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
I will try to get a naming system back online. Thanks

**Comment by tsunamayo** [comment]
We have a tag system now. thx
