### ISSUE TITLE
[BUG][EXPERIMENTAL] Exiting warp puts ships too close to the star

### ISSUE THREAD

**Issue by Elektron72** [tsunamayo/Starship-EVO#897]
### Short Description of the issue:
When I warp to another system, the ship emerges from warp extremely close to the star, meaning it takes 10+ minutes to get anywhere in the system after warping.

### Steps to reproduce the issue:

1. Select a system from the galaxy map
2. Activate hyperdrive
3. Fly away from the star
...

### Environment
- Skywanderers version: 18w24a
- Graphics Card: NVIDIA GeForce GTX 950M

### Additional information:

![20180910165248_1](https://user-images.githubusercontent.com/36974021/45323814-52ef6d00-b51a-11e8-8f3f-2229917d71f6.jpg)

output_log.txt:
`Initialize engine version: 2018.2.0b3 (0a6b93065060)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: NVIDIA GeForce GTX 950M (ID=0x139a)
    Vendor:   
    VRAM:     2010 MB
    Driver:   24.21.13.9907
Begin MonoManager ReloadAssembly
- Completed reload, in  0.087 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 1.702512 ms
SETTINGS Loaded
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

RESTARTING THE GAME
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Loading all textures
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

TEXIM LOADED 405
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

generated block texture array:186
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

generated brick texture array:119
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

DAMAGE DEPTH8
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Fonctionnal Blocks
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Unloading 5 Unused Serialized files (Serialized files now loaded: 0)
Hull Blocks
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Construction Blocks
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Construction Bricks
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Functional Bricks
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Construction Bricks
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Paints
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

System GFX memory 2010 mb
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

System memory 8060 mb
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Suport sparse texture?  True
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Loading player 
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Unloading 5532 unused Assets to reduce memory usage. Loaded Objects now: 13905.
Total: 16.175566 ms (FindLiveObjects: 2.065367 ms CreateObjectMapping: 0.910725 ms MarkObjects: 11.465999 ms  DeleteObjects: 1.732341 ms)

Level 0 computation finished 106813
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Level 0 computation finished 106775
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

NEW CHAR Test
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

network adress 0
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

OnPlayerConnected
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Unloading 5 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 32.945444 ms
Loading player 
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Entity Culling Manager online
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Active Slot is : 0 / 
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Entity Culling Manager online
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Voxel Light Manager online
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Entity Culling Manager online
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

There has been an awakening. From the Block Entity Manager.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Local player Start sequence: 
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Unloading 151 unused Assets to reduce memory usage. Loaded Objects now: 18462.
Total: 24.783277 ms (FindLiveObjects: 2.469756 ms CreateObjectMapping: 0.245805 ms MarkObjects: 21.955197 ms  DeleteObjects: 0.111763 ms)

NEW SYSTEM
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

LOAD c[64 0 30]l0n0
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

RADIUS 10430.38 | DEPTH 2048
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

total stars 12994
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Galaxy Skybox compute finished
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Loading sequence finished
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

CommandBuffer: built-in render texture type 13 not found while executing Rings Particles Rings(Clone) (SetRenderTarget color buffer)
 
(Filename:  Line: 0)

Speed Factor 3
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Speed Factor 9
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Speed Factor 27
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Speed Factor 81
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Speed Factor 243
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Speed Factor 729
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Speed Factor 2187
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Speed Factor 6561
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Speed Factor 19683
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Speed Factor 59049
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Speed Factor 177147
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Active Slot is : 0 / Starter Block
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Speed Factor 59049
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Speed Factor 19683
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Speed Factor 6561
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Speed Factor 2187
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Speed Factor 729
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Speed Factor 243
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Speed Factor 81
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Speed Factor 27
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Speed Factor 9
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Speed Factor 3
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Speed Factor 1
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Active Slot is : 0 / Starter Block
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Active Slot is : 1 / Hull Basic
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Active Slot is : 2 / Spaceship Core
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Active Slot is : 1 / Hull Basic
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Active Slot is : 3 / Engine Unit
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Active Slot is : 4 / Hyperdrive
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Active Slot is : 5 / Void Reactor
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Active Slot is : 6 / Chair
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Active Slot is : 7 / Holographic Display
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Active Slot is : 8 / Link Tool
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Active Slot is : 0 / Switch
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Active Slot is : 7 / Panel 4x4
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Active Slot is : 0 / Switch
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Active Slot is : 8 / Link Tool
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Active Slot is : 4 / Hyperdrive
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

new star level 2|25000|3192
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

new star level 3|12500|22
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

new star level 4|6250|0
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

new star level 5|3125|0
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Set new system target System : [66|1|16]:0:0
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Active Slot is : 8 / Link Tool
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

proceed to warp System : [66|1|16]:0:0
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

NEW SYSTEM
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

total stars 13009
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Galaxy Skybox compute finished
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

SETTINGS.ini Saved
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

SETTINGS.ini Saved
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

SETTINGS.ini Saved
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

SETTINGS.ini Saved
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

SAVING GAME STATE
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Save done : C:/Users/Minecrafter/AppData/LocalLow/TsunamayoCorp/Skywanderers/Save_Data/Characters\Test
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Save done : C:/Users/Minecrafter/AppData/LocalLow/TsunamayoCorp/Skywanderers/Save_Data/PlayerEntities\iDqEDuwQWEuT3RPZLANy5g.swbp
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Save done : C:/Users/Minecrafter/AppData/LocalLow/TsunamayoCorp/Skywanderers/Save_Data/PlayerEntities\ND9xhP948UeKSKtf3b-EBg.swbp
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Save done : C:/Users/Minecrafter/AppData/LocalLow/TsunamayoCorp/Skywanderers/Save_Data/Instances\c[66 1 16]l0n0
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Save done : C:/Users/Minecrafter/AppData/LocalLow/TsunamayoCorp/Skywanderers/Save_Data/WorldEntities/c[64 0 30]l0n0/Torus0/PlayerEntities.swk
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

All saves jobs completed
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

SETTINGS.ini Saved
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

EXIT TO DESKTOP
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

SETTINGS.ini Saved
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Setting up 2 worker threads for Enlighten.
  Thread -> id: 5a64 -> priority: 1 
  Thread -> id: 2dd0 -> priority: 1 
Destroying Tracking Camera
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Destroying Starfield Particles
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

`

**Comment by tsunamayo** [comment]
No longer applicable. Thanks
