### ISSUE TITLE
[BUG] [Experimental] Game Freeze

### ISSUE THREAD

**Issue by Sir-E** [tsunamayo/Starship-EVO#902]
### Short Description of the issue:
The game freezes whenever the warp drive of one ship is activated and then the player gets into the seat of another ship before the first ship enters warp.

### Steps to reproduce the issue:
Activate the warp drive of one ship (in this case done through a button) and then immediately hop into the seat of a different ship before the first ship can enter warp. 

### Environment
- Skywanderers version: Pre-Alpha Version 18w24a
- Graphics Card: MSI GTX 1060 X Gaming 6G

### Additional information:
Screenshot of frozen game: https://imgur.com/a/K9II3Wa

Please note that even though the game was frozen, it did not crash and it stayed open until forcibly closed.

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2387424/output_log.txt)

**Comment by tsunamayo** [comment]
Interesting test case, I will make sure to deal with it when I put warp back. Thanks!

**Comment by tsunamayo** [comment]
No longer applicable. Thanks
