### ISSUE TITLE
Window side - Foggy texture faces one direction

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#945]
### Short Description of the issue:
Unsure if this is intended or a minor bug but I personally feel the foggy face should follow when you rotate the block
### Environment
- Skywanderers version: revengeoftheclip
- Graphics Card: gtx970

![20181007012459_1](https://user-images.githubusercontent.com/32974671/46579041-3e46ad80-c9d0-11e8-91fe-abdc6f0d3df9.jpg)
![20181007012503_1](https://user-images.githubusercontent.com/32974671/46579042-3e46ad80-c9d0-11e8-8f74-05e75e30cb02.jpg)

**Comment by tsunamayo** [comment]
So it actually depends on where the sun is. One face is lit and not this other. Does it feels unnatural to you? Thanks

**Comment by Xerma** [comment]
It makes sense now that you explain it lol However it would be neat to have glass that is more reflective on one side and more see through on the other. Like a one way window but still sort of see through on the reflective side

**Comment by TheCuriousSkeleton** [comment]
How did you get onto the new update?
