### ISSUE TITLE
Can't select any item in hotbar other than first position

### ISSUE THREAD

**Issue by InCrIpTiOn** [tsunamayo/Starship-EVO#962]
### Short Description of the issue:

Upon loading the world, I cannot use the number keys or scroll wheel to select the item in my inventory.

### Steps to reproduce the issue:

This bug was immediate upon loading onto a world on the latest stable version

### Environment
- Skywanderers version: 18w24a
- Graphics Card: GTX 1050ti

### Additional information:

None
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2520410/output_log.txt)

**Comment by MrBester** [comment]
Im getting this too, sometimes my world will work fine I can build away  then suddenly the scroll wheel/number select will just stop working, only way to fix is a reload.

**Comment by The-Doehg** [comment]
Im getting this as well. I found that by uninstalling and re-installing the beta, it would work.

**Comment by tsunamayo** [comment]
@InCrIpTiOn @Doehg @MrBester Did you get that issue in a recent build if you tried out the game recently? Thanks
